### ISSUE TITLE
Youtube live streaming broken

### ISSUE THREAD

**Issue by pumi** [EFForg/https-everywhere#100]
Youtube live streaming broken.

For example this https://www.youtube.com/watch?v=jrZcAsPKK74 error with extention.

**Comment by crschmidt** [comment]
In general, YouTube now does HTTPS streaming almost everywhere. I've attempted to reproduce the behavior that the original poster was having using SSL Everywhere, and I'm not able to do so at this time (but it sounds like this is expected). There have been a large number of changes in the YouTube SSL infrastructure over the past 8 months, so I think it's unlikely that the same issue that was happening back then would be happening now.

If this *is* still happening, I'd love to know about it and bring it up with the YouTube developers working on SSL; given the number of changes in this space, I think no news is probably good news on this front.

**Comment by semenko** [comment]
Thanks @crschmidt ! 

I'm going to close this for now. Please re-open / comment if there are YouTube live issues later.
