### ISSUE TITLE
Test and debug the HTTPS Everywhere experience in China (and other very hostile networks)

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#1000]
Because China differentially blocks a lot of HTTPS requests, it's reported that the default configuration of HTTPS Everywhere creates bad experiences there, and we have correspondingly few users in China.  We should consider producing variant rulesets that offer optimal experiences behind the Great Firewall.

In some cases, of course, breakage is the right response to that network's behaviour.  But we could display a note when that happens.   And in other cases, alternative (amazon, Google) URLs might be available that work.

We could probably define new ruleset platforms "blockedinchina", "onlyinchina" and mark rulesets accordingly.

**Comment by netheril96** [comment]
I use https-everywhere extensively in China, and have yet to encounter a case where the HTTP version is accessible but not the HTTPs version. In fact, there are many cases where I can only connect to a website with TLS, when not using VPN.

**Comment by J0WI** [comment]
Maybe @renyouguo could help here?

**Comment by renyouguo** [comment]
@J0WI I'm happy to do something.However, I don't think this is a good idea.
The GFW may blocks the site which use https default. While the site has been blocked by GFW, we name that "GFWed", users can not access the site directly by http . We must across the GFW, not to http.
In china, some( maybe most?) ISPs always hijack our http flow to add ads or something else.
So, https everywhere is very very very important for us.

By the way, chinese did others redirects for better internet,for example:[gooreplacer](https://github.com/jiacai2050/gooreplacer) .
You can let it work firstly.

**Comment by Artoria2e5** [comment]
> @netheril96: and have yet to encounter a case where the HTTP version is accessible but not the HTTPs version.

Hmm, the only case I can come up with is `zh.wikipedia.org`:

> https://en.wikipedia.org/wiki/Censorship_of_Wikipedia#China:
> 
> Chinese authorities started blocking access to the secure (HTTPS) version of the site on 31 May 2013, although the non-secure (HTTP) version is still available – the latter is vulnerable to keyword filtering allowing individual articles to be selectively blocked.

But this case is no longer valid now, since the WMF is enforcing mandatory HTTPS:

> Since June 2015, all Wikipedias redirect HTTP requests to the corresponding HTTPS addresses, thereby making encryption mandatory for all users. As a result, Chinese censors cannot see which specific pages an individual is viewing, and therefore cannot block a specific subset of pages (such as Ai Weiwei or Tiananmen Square) as they did in past years. As a result, Beijing chose to block the whole Chinese Wikipedia; as of June 2015, both encrypted and [unencrypted] Chinese-language Wikipedia are blocked.

So basically this is true to me.

**Comment by Artoria2e5** [comment]
> And in other cases, alternative (amazon, Google) URLs might be available that work.

↓

> By the way, chinese did other redirects for better internet, for example gooreplacer.

HTTPS Everywhere is able to do this work in rule files, although I don't know if that is still in the scope of this thing. Redirection alternatives can be interesting and useful — I used to be a user of gooreplacer and enjoyed it. [cachebrowser](https://github.com/CacheBrowser/cachebrowser) uses such property even more extensively.

**Comment by pipboy96** [comment]
Discussion seems to have stopped, closing.
