### ISSUE TITLE
Add "Show Counter"

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#10002]
In the legacy Firefox version we had a "Show Counter" option.
This option is a useful indicator that HTTPS Everywhere is active on a site.

**Comment by koops76** [comment]
#10773

**Comment by gitarra** [comment]
I think the counter is a tad too bright as it is. Doesnt really fit into the toolbar.

**Comment by drmurke** [comment]
If you disable the option for the counter it will still show after the next browser restart.

**Comment by koops76** [comment]
@drmurke Are you sure you don't have `localStorage` disabled?

**Comment by koops76** [comment]
@gitarra It is the same color as Privacy Badger's badge.

**Comment by drmurke** [comment]
I tried with a new profile, too, so I don't think so?

**Comment by Hainish** [comment]
Thanks @koops76

**Comment by Hainish** [comment]
@drmurke do not test with Nightly, this extension does not work with Nightly.  For Nightly, use our developer channel https://kittens.eff.org/https-everywhere#developers_note

**Comment by gitarra** [comment]
@koops76 I dont use that addon.

It is the single brightest spot of colour on my whole desktop. Firefox browser chrome and my Ubuntu OS UI included.

None of my other addons have badges that are bright like that.

It is competing for my attention like a modal window even though its just a counter without any real importance. I think it should be toned down.

Theres also the issue of contrast, white text on a bright background, the numbers are hard to read.

**Comment by koops76** [comment]
@gitarra If you want to make the color configurable, make a separate issue for it. I would gladly make a PR adding this feature.

**Comment by koops76** [comment]
@gitarra I don't think we can change the badge's text color. WebExtensions doesn't seem to support it.

**Comment by gitarra** [comment]
I'll just turn the counter off, its really out of place, constantly bugging me in the corner of my eye.

Since I already took a screenshot might as well throw it here anyway:

![screenshot](https://user-images.githubusercontent.com/4739888/29854451-c04e02de-8d4e-11e7-9041-dac1b536d3e6.png)

**Comment by gitarra** [comment]
As @drmurke said, the counter comes back after browser restart even though it is disabled in the settings. Has to be toggled back on and off again.

**Comment by koops76** [comment]
@drmurke @gitarra #12268
