### ISSUE TITLE
Unexpected effect when hovering rules names

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10009]
When you hover the name of a rule in the WebExtension version of HTTPS-Everywhere, the cursor turns into a question mark, suggesting that a tooltip is going to appear to give some info.

But nothing happens when you wait and upon clicking, it just enables / disables the ruleset.

Suggested fix:

- Bring back a normal cursor

**OR**

- Add a tooltip that gives info upon clicking when the cursor is a question mark and only allow enabling/disabling by clicking on the checkbox

(I can add screenshots if needed)

Related: #9958

**Comment by Hainish** [comment]
@Bisaloo, I can't reproduce this in either the WebExtensions for Firefox or for Chrome.

@jeremyn, @J0WI do either of you see this?

**Comment by jeremyn** [comment]
I'm unable to reproduce or fully understand the problem. A screenshot would help.

**Comment by Hainish** [comment]
Ahhh, I see and can reproduce this for custom rules.  Working on this now.

**Comment by Hainish** [comment]
@Bisaloo a tooltip *is* displayed for me for custom rules on both Firefox and Chrome for Linux.  Can you provide some platform/versioning info so we can narrow this down?

**Comment by Bisaloo** [comment]
@Hainish, you're right, it's only for custom rules. I missed that.

For some reason, I can't reproduce this issue now. I have a tooltip saying `user rule`. I can't say if I just previously overlooked it or if it was indeed missing (I didn't write down the exact page where I noticed this issue). I am going to close this in the meantime.
