### ISSUE TITLE
"Reset to Defaults" option missing

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#10004]
In the Firefox version we had a "Reset to Defaults" option.

**Comment by Bisaloo** [comment]
[This blog post about the rewrite of Lightbeam] may be useful.

**Comment by tribblex** [comment]
is this still going to be done or has it fallen into oblivion?

**Comment by cschanaj** [comment]
See #15411

**Comment by Giltyhub** [comment]
hi @J0WI can u put this issue in the "Done" card in https://github.com/EFForg/https-everywhere/projects/1 thanks!
