### ISSUE TITLE
Background images set via CSS aren't rewritten

### ISSUE THREAD

**Issue by migueldemoura** [EFForg/https-everywhere#10018]
Images set via css `background-image: url('http://example.com/image.png')` aren't rewritten/processed, resulting in mixed content.

Example url:
http://files.explosm.net/comics/Rob/cloud.gif

Edit: this appears to apply to all images, even those in `<img>`

**Comment by bardiharborow** [comment]
Are you sure that you actually have the [Explosm.net ruleset](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Explosm.net.xml) enabled? It's currently disabled by default due to a test failure.

**Comment by migueldemoura** [comment]
@bardiharborow, yes I have that ruleset enabled. I believe I found the actual issue, though. [uMatrix](https://github.com/gorhill/uMatrix) with strict https drops the http request before https everywhere can redirect it, leading to the behavior I'm experiencing.

**Comment by gloomy-ghost** [comment]
I would say this is something needs to be addressed at browser's side.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=878890

**Comment by gloomy-ghost** [comment]
I am pretty sure the image resources can be processed, just the UI still shows mixedcontent
![default](https://user-images.githubusercontent.com/13086421/29745707-a4ae6792-8b16-11e7-96ea-c1e5de950320.png)

**Comment by J0WI** [comment]
@migueldemoura can you provide a live example, where the bug is reproducible?
I'm only aware of the case described in https://github.com/EFForg/https-everywhere/issues/10018#issuecomment-325166453

**Comment by migueldemoura** [comment]
I'm now using chromium's `--enable-potentially-annoying-security-features` flag which automatically rewrites mixed requests before web extensions, meaning that uMatrix's `Forbid mixed content` is no longer an issue.

Afaik, the only way of circumventing this is by changing the installation order of HTTPS Everywhere and uMatrix. This isn't an issue with HTTPS Everywhere.
