### ISSUE TITLE
Add a way to delete custom rules

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10010]
The new WebExtension HTTPS-Everywhere adds the possibility of creating user rules on the fly. But where are these rules stored?

Related: #9958

**Comment by jeremyn** [comment]
I don't have the answer and I appreciate and share your curiosity but from a purely user-facing, "business need" standpoint, why do you need to know? Do you think this is something that ought to be visible to users?

**Comment by Bisaloo** [comment]
> Do you think this is something that ought to be visible to users?

Yes, I think it's important. Otherwise how do you delete wrong/outdated/redundant rulesets that you added? 

Right now, you can easily disable them but it clutters both your UI and your firefox profile.

**Comment by jeremyn** [comment]
I agree there should be some kind of interface for users to manage custom rules in the add-on. It's probably not really important where these rules are stored, like in which database or which directory. I'm okay with leaving that as a private implementation detail.

It's critical though that we have a way to add rules by using XML files for testing, like we do in Firefox (see https://github.com/EFForg/https-everywhere/issues/1779).

**Comment by Hainish** [comment]
@Bisaloo I don't think this should be exposed to the user in the UX, but I think it's perfectly reasonable for it to be in the FAQ.  At any rate, this is a general `webextensions` issue, not particular to Firefox.  I'm going to change the labels for this.

**Comment by jeremyn** [comment]
@Hainish I don't think it's a general `webextension` issue, but instead a UX/UI problem that already exists in how custom rules are implemented in Chrome.

**Comment by Hainish** [comment]
This has to do with how custom rules are stored using WebExtensions in general, not how Firefox stores them.  This is a question most appropriately handled in the FAQ, as I've already stated above

**Comment by jeremyn** [comment]
I believe @Bisaloo is asking/complaining about the current UX in Firefox related to custom rules, and is not academically curious where the rules are stored.

**Comment by Hainish** [comment]
So this is a request to be able to delete custom rules.  This makes more sense.  If this is correct, can you please change the title of the issue, @Bisaloo?

**Comment by Hainish** [comment]
This has been fixed in https://github.com/Hainish/https-everywhere/tree/webextensions and will be incorporated into the next testing release.

**Comment by Hainish** [comment]
I felt this was worth fixing on `master` for the next Chrome release, so I've done that and rebased https://github.com/Hainish/https-everywhere/tree/webextensions

**Comment by Bisaloo** [comment]
It doesn't work for me. I can see this icon next to the custom ruleset. The ruleset vanishes when I click it but it's back on page reload.

**Comment by jeremyn** [comment]
My custom rule reappears too after I click the `X` icon to delete it, but I have to restart the browser for it to reappear. Simply refreshing with Ctrl-F5 or closing the tab and making a new one does not cause it to reappear.

**Comment by Hainish** [comment]
Please include the version number you're testing with.  This issue may be related to https://github.com/EFForg/https-everywhere/issues/10039 if you were testing with a version < `2017.6.9.1337`

**Comment by jeremyn** [comment]
I can reproduce the problem I described in my last comment on 2017.6.9.1337 on Firefox 53.0.3.

**Comment by Bisaloo** [comment]
I'm using 2017.6.9.1337 as well (Firefox 53.0.3).

**Comment by Hainish** [comment]
This has been confirmed and fixed in https://github.com/EFForg/https-everywhere/tree/master as of https://github.com/EFForg/https-everywhere/commit/34f79691be2a2a23ba81e8ca593afd35123ba4e3

The next testing release will rebase from master so you can confirm the fix in Firefox.

**Comment by Bisaloo** [comment]
I can confirm this is fixed in 2017.7.21.1338.
