### ISSUE TITLE
Bitly redirect broken

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#10017]
Trying to view the link featured in the tweet at https://twitter.com/NFL/status/867102274144935937 takes me to https://on.nfl.com/RFEgCI which causes an Insecure Connection notice.  I had to disable Bitly vanity domains rule to get it to work properly.

HTTPSE 5.2.17
Firefox ESR 52.1.2
Windows 7 64-bit

**Comment by Bisaloo** [comment]
@jehiah has been updating the Bitly ruleset in the past but I don't know if he would be available to do it.

**Comment by bardiharborow** [comment]
@jehiah re-pinging.

**Comment by J0WI** [comment]
closed by #11804
