### ISSUE TITLE
Videos will not play at pilotonline.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#10016]
http://pilotonline.com/news/media/videos/

I get an error message when trying to play any video content unless I disable JW Platform.com (partial).

HTTPSE 5.2.17
Firefox ESR 52.1.2
Windows 7 64-bit

**Comment by numismatika** [comment]
How about using https://pilotonline.com/news/media/videos/ instead?

**Comment by MDawg957** [comment]
Working with HTTPSE 5.2.19.  Closing.
