### ISSUE TITLE
Fails on XE.com

### ISSUE THREAD

**Issue by snowbound** [EFForg/https-everywhere#10030]
If enabled the extension prevents loading of XE.COM currency conversion site.

**Comment by bxparks** [comment]
I also encountered this bug, and eventually traced the problem to HTTPS Everywhere. When I compared the call stack between Safari and Chrome, I found a whole bunch of broken URLs, such as this CCS file:

> http://s.xe.com/themes/xe/t_css/home_resp.4z.css

which gets rewritten by HTTPS Everywhere as:

> https://gp1.wac.edgecastcdn.net/00157D/themes/xe/t_css/home_resp.4z.css

which returns a 404.
