### ISSUE TITLE
Chrome, search and redirect loop

### ISSUE THREAD

**Issue by netheril96** [EFForg/https-everywhere#1003]
I am a Chinese user and constantly uses VPN to bypass the network restriction. By doing so, Chrome will notice that my IP is American, and my default search engine will be set to `www.google.com` instead of `www.google.com.hk`. Then, when I turn off VPN and search from the address bar, a 400 malformed request error is shown. By looking at the network response, I can see that it is in fact a redirect loop. Basically Google will redirect me to a plain HTTP address, and it will be rewritten by HTTPs everywhere to a secure address, which will then redirect itself. This error does not occur without HTTPS everywhere.

**Comment by StevenRoddis** [comment]
Hi @netheril96 does that mean for you `https://www.google.com.hk` redirects to `http://www.google.com.hk` with the VPN turned off?

**Comment by netheril96** [comment]
@StevenRoddis 

This issue seems to have disappeared for me. Perhaps Google has fixed their insecure redirection.
