### ISSUE TITLE
new rule request for toppreise.ch

### ISSUE THREAD

**Issue by bugrasan** [EFForg/https-everywhere#10038]
to be added as `topprise.ch.xml` into  https://github.com/EFForg/https-everywhere/tree/master/src/chrome/content/rules

```xml
<ruleset name="toppreise.ch">
	<target host="toppreise.ch" />
	<target host="www.toppreise.ch" />
	<rule from="^http:" to="https:" />
	<test url="http://www.toppreise.ch" />
</ruleset>
```

**Comment by jeremyn** [comment]
Hi @bugrasan , thanks for the report, but can you please create a pull request for this?

**Comment by bugrasan** [comment]
a file already exists; it seems i have missed it before.
you can close this issues. thanks.

**Comment by jeremyn** [comment]
Thanks for following up. I'm closing the issue.
