### ISSUE TITLE
Implement a "Disable on this Site" button

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#10041]
Back when HTTPS Everywhere first existed, it was feasible to manually disable rulesets if something on a was broken or potentially broken by HTTPSE.  Unfortunately, that's no longer practical; on many pages ([here's an example](https://www.economist.com/news/leaders/21722642-lot-known-about-how-reform-prisoners-far-too-little-done-americas-prisons-are)) the user is confronted with a crazy long list of rulesets, and disabling them all is both a lot of work, and probably not what the user wanted.

Instead, we should add a "Disable HTTPS Everywhere on this site" button (and maybe also a "Disable HTTPS Everywhere on this page" button) to the top of the menu. Then users can happily receive a one-click solution if we're breaking the page (or we might be, and they want to check).

**Comment by Hainish** [comment]
Closed via https://github.com/EFForg/https-everywhere/pull/16546
