### ISSUE TITLE
Intersection of title "HTTPS Everywhere" with content in the popup menu

### ISSUE THREAD

**Issue by AlexBeLi** [EFForg/https-everywhere#10040]
On webextension version if list of sites is too long and used scrolling
![https everywhere](https://cloud.githubusercontent.com/assets/20776735/26471390/ec210a08-41ba-11e7-87fc-11302bf04686.png)
Related: #9958

**Comment by Hainish** [comment]
@AlexBeLi I'm seeing a translucent background for "HTTPS Everywhere":

![screenshot_2017-06-10_13-11-19](https://user-images.githubusercontent.com/156137/27005973-b38823ae-4dde-11e7-8749-752f6dafb65b.png)

Can you provide additional details, such as your browser version and operating system?

**Comment by AlexBeLi** [comment]
hmm.. 
It only if set up in about:config
layout.css.prefixes.webkit;false

**Comment by Hainish** [comment]
Is it common to flip this pref?  I've never heard of it before

**Comment by Hainish** [comment]
This has been fixed in https://github.com/EFForg/https-everywhere/tree/master as of https://github.com/EFForg/https-everywhere/commit/4ba0b4992ccc18f4487491e8b4ae2e2d66af3593 and you can test it in the next testing release, which will be rebased from master.
