### ISSUE TITLE
Add rule for Gigabyte.com

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#10086]
Gigabyte.com has HTTPS enabled with no issues but is not default.

**Comment by jeremyn** [comment]
For reference, [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Gigabyte.com.xml) is the existing `Gigabyte.com.xml` ruleset. It looks like it could use some work.
