### ISSUE TITLE
Add rule for nowinstock.net

### ISSUE THREAD

**Issue by candrews** [EFForg/https-everywhere#10096]
Everything works fine over HTTPS, so I think a simple rule would suffice:

```xml
<ruleset name="nowinstock.net">
        <target host="www.nowinstock.net" />

        <rule from="^http:" to="https:" />

        <test url="http://www.nowinstock.net/news/" />
</ruleset>
```

**Comment by jeremyn** [comment]
Thanks for the report. I've added this domain to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-306293610` and am closing this issue. Please feel free to create a pull request to add the subdomain to HTTPS Everywhere if you like.
