### ISSUE TITLE
msnbc doesn't display right AT ALL

### ISSUE THREAD

**Issue by alchymmyst** [EFForg/https-everywhere#10099]
![https everywhere msnbc screen cap](https://cloud.githubusercontent.com/assets/29133600/26705222/ae0a09fc-46e9-11e7-886b-63385b815d1c.JPG)

**Comment by jeremyn** [comment]
Thanks for the report. When I load http://www.msnbc.com/ and look at the Firefox developer tools (F12) console, I see errors like:

> GET https://www.msnbc.com/sites/msnbc/files/styles/original/public/field_headshot_small/lastword_s_2.png?itok=6tV9ifxP [HTTP/1.1 503 Service Unavailable 886ms]

and if I separately visit https://www.msnbc.com/sites/msnbc/files/styles/original/public/field_headshot_small/lastword_s_2.png , I get an HTTP 503 error, but I get a HTTP 200 success with http. So my guess is that MSNBC is having hopefully temporary technical problems.

**Comment by jeremyn** [comment]
I've marked this `Before the Next Release` so we'll check to see if this is still a problem when preparing for the next release. Hopefully it will have been fixed on MSNBC's side by then.

**Comment by alchymmyst** [comment]
Thanks!

**Comment by jeremyn** [comment]
Pull request https://github.com/EFForg/https-everywhere/issues/10177 has been merged so I'm closing this issue.
