### ISSUE TITLE
CSS styles are killed for page: http://www.xe.com/currencyconverter/ 

### ISSUE THREAD

**Issue by deanedridge** [EFForg/https-everywhere#10156]
Using Firefox extension HTTPS-everywhere 5.2.17 on Mac OS running FirefoxDeveloperEdition (54.0b12) causes the page to not have any CSS styles.

**Comment by deanedridge** [comment]
Same result with FirefoxNightly (55.0a1) same OS

**Comment by Bisaloo** [comment]
Related: #10030
