### ISSUE TITLE
Infinite redirects for login.emedien.ub.uni-muenchen.de

### ISSUE THREAD

**Issue by PhilippWendler** [EFForg/https-everywhere#10161]
HTTPS Everywhere breaks online access to e-books, journals etc. via the system of the library of the University of Munich (largest university in Germany).

One has to login at https://login.emedien.ub.uni-muenchen.de/login (this works) and then follow links such as https://login.emedien.ub.uni-muenchen.de/login?url=http://ezb.uni-regensburg.de/fl.phtml?bibid=UBM. With HTTPS Everywhere, these links cause infinite redirects. The first request is redirected to 	
http://ezb.uni-regensburg.de.emedien.ub.uni-muenchen.de/fl.phtml?bibid=UBM, which immediately redirects back to https://login.emedien.ub.uni-muenchen.de/login?url=http://ezb.uni-regensburg.de/fl.phtml?bibid=UBM.

When I compare the requests made with and without HTTPS Everywhere using Firebug, it seems that the value of the `ezproxy` cookie (which is set during the login) is missing in the request to http://ezb.uni-regensburg.de.emedien.ub.uni-muenchen.de. Probably HTTPS Everywhere prevents sending the cookie via a plain HTTP connection because it was set on a HTTPS connection? Can this be disabled?

Many people seem to be affected by this problem, because the University of Munich even documents it on its [website](http://www.en.ub.uni-muenchen.de/borrowing/digital-access/e-media-login/index.html#login-problems) and recommends removing HTTPS Everywhere. So it would be really great to get this fixed.

**Comment by Bisaloo** [comment]
This kind of issue is often quite tricky to fix but you provided good info so I think we can do it.

This ruleset hasn't been updated in a very long time so I gave it a first go. I don't really expect it to solve your issue but who knows?

Which browser using?

**Comment by PhilippWendler** [comment]
Thanks!

Sorry, I didn't know that HTTPS Everywhere is available for multiple browsers. I am using Firefox.

Is there some way how I can test the change or help with debugging?

**Comment by Bisaloo** [comment]
> Is there some way how I can test the change or help with debugging?

Yes, with Firefox, you can. That's why I was asking.

To test the changes, you need to:

1. Disable the faulty HTTPS-Everywhere rule
2. Go to your Firefox profile and create a folder named `HTTPSEverywhereUserRules`
3. Download my [fix proposal](https://raw.githubusercontent.com/Bisaloo/https-everywhere/11b737c5fe1df0b137d4c9dc512d304dece419c8/src/chrome/content/rules/LMU-Muenchen.xml) in the `HTTPSEverywhereUserRules` folder
4. Restart Firefox
5. Test away! I am looking forward to your feedback

**Comment by PhilippWendler** [comment]
Thanks. I couldn't do item 1 (the toolbar icon did not offer that option), but I did item 2-5 and it works!

I did not test the effect on any other LMU sites, though.

**Comment by Bisaloo** [comment]
Great! I will try to get the file merged then. Then, we will have to wait the next release (in two weeks) for this change to reach all HTTPS-Everywhere users.

Just for your information, you can disable specific rulesets by clicking on them.

**Comment by dlingley** [comment]
We are experiencing a similar Issue at Purdue

**Comment by Bisaloo** [comment]
@dlingley, could you open a new issue with more details on what's precisely going on? University websites are often very complicated and some parts are restricted to students/staff so we won't be able to do anything without more info.
