### ISSUE TITLE
Option to add a site

### ISSUE THREAD

**Issue by vis15** [EFForg/https-everywhere#10178]
It would be nice to have an option to manually add a site.

**Comment by gloomy-ghost** [comment]
We do have the option:
![default](https://cloud.githubusercontent.com/assets/13086421/26809120/5816b3da-4ab6-11e7-8bf6-bf6ba2fb5078.png)

Though it's not available on Firefox yet. Maybe you can use the [testing version](https://www.eff.org/files/https-everywhere-test/index.html) before we are ready to release WebExtension for Firefox. Closing.
