### ISSUE TITLE
Make HTTPS-Everywhere atlas case insensitive

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10182]
I often copy/paste domain names from ruleset names but the atlas search function fails when there are uppercase letters.

It is a mild annoyance but it also doesn't make sense for the atlas to be case sensitive when (as far as I know) URL aren't.

**Comment by jeremyn** [comment]
What's an example search that doesn't work for you?

**Comment by Bisaloo** [comment]
For example, I looked for [`TransitionNetwork.org`](https://www.eff.org/https-everywhere/atlas/?TransitionNetwork.org) for #10183.

**Comment by jeremyn** [comment]
I can see why that's annoying. I would have expected it to match the ruleset name, which is cased exactly as `TransitionNetwork.org`.

I personally almost never use the Atlas, instead I search GitHub.

**Comment by jeremyn** [comment]
More info:

URLs are case-sensitive, but domain names (which is what matters here) [are case-insensitive](https://tools.ietf.org/html/rfc4343).

The domain name search happens [here](https://github.com/EFForg/https-everywhere-atlas/blob/a6d2db125c230e8dbb1e34ddd5bd6de95fe3a65e/templates/index.mustache#L25-L42).

**Comment by migueldemoura** [comment]
L31: `domain.indexOf(query)` -> `domain.toLowerCase().indexOf(query)`?
