### ISSUE TITLE
Dynamically detect whether an unknown site uses https

### ISSUE THREAD

**Issue by MilesBHuff** [EFForg/https-everywhere#10187]
It would be neat if HTTPS Everywhere would attempt to use https on unknown sites, and fallback to http if loading encounters errors:  something _à la_ https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/, but still keeping the official list of https-supported sites, as a way of saving performance.  
Whether https succeeds on a given site can be cached locally, as well as submitted to the EFF to help further the official https whitelist.

**Comment by migueldemoura** [comment]
There's one issue with this: some websites display a different page when connecting via https but still send a HTTP 200. This happens on misconfigured servers and those where https has been deployed incorrectly.

**Comment by pipboy96** [comment]
Already discussed in FAQ. Closing.

**Comment by MilesBHuff** [comment]
I'm not sure if this was "already discussed in FAQ" in mid-2017 when this was posted, and it doesn't look like the Wayback Machine works for eff.org.

Nevertheless, for anyone interested, here's the link to the current FAQ:  https://www.eff.org/https-everywhere/faq#why-use-a-whitelist-of-sites-that-support-https-why-cant-you-try-to-use-https-for-every-last-site-and-only-fall-back-to-http-if-it-isnt-available
