### ISSUE TITLE
Target list layout messed up

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#10188]
Firefox:
![default](https://cloud.githubusercontent.com/assets/13086421/26812588/b7277a56-4acc-11e7-8728-9499741e38a3.png)

Chrome:
![default](https://cloud.githubusercontent.com/assets/13086421/26812605/d359efe2-4acc-11e7-9675-6c51b3bdb21a.png)

**Comment by jeremyn** [comment]
I don't know what the complaint here is.

**Comment by gloomy-ghost** [comment]
The spaces between checkboxs and ruleset names are missing

**Comment by jeremyn** [comment]
Oh okay, I see what you're saying. Also the paper icon, which seems to be for favicons, is missing.

**Comment by Hainish** [comment]
Within Firefox, the favicons are non-discoverable.

**Comment by Hainish** [comment]
This has been fixed in https://github.com/Hainish/https-everywhere/tree/webextensions and will be incorporated into the next testing release.
