### ISSUE TITLE
Sync extra rules and enabledness between multiple machines using the same google account

### ISSUE THREAD

**Issue by fnkr** [EFForg/https-everywhere#1022]
Please add the ability to sync own rules and enabled/disabled rules.
https://developer.chrome.com/extensions/storage

**Comment by reedy** [comment]
You mean between multiple computers when logged in with your google account?

**Comment by fnkr** [comment]
Yes.

**Comment by reedy** [comment]
I guess something similar could/should be done for FF sync too

**Comment by diracdeltas** [comment]
This is probably a good idea; I think the % of chrome users who don't want to sync data between logged-in google-enabled Chrome profiles would be negligible.

Right now we use `window.localStorage`. Switching that over to the `chrome.storage.sync` API should be easy.

However, note that window.localStorage has 5MB of storage available per origin in Chrome, whereas chrome.storage.sync only lets HTTPS Everywhere have 100KB. That is probably not enough, unless you only sync diffs to the default rules set (user-added/enabled/disabeld rules).

**Comment by fnkr** [comment]
For those people who dont want to sync with Google we could use `chrome.storage.local` (opt-out), the API is  identical to `chrome.storage.sync` but the data stays on the local computer.

**Comment by fnkr** [comment]
For those people who dont want to sync with Google we could use `chrome.storage.local` (opt-out), the API is  identical to `chrome.storage.sync` but the data stays on the local computer.

Furthermore, I think syncing the difference between the default ruleset and the user ruleset would be the best option anyway.

**Comment by semenko** [comment]
With #1295 merged, we now declare the `storage` API in the manifest.

I agree the RE the privacy implications here -- users who don't want HTTPSe rule status synced between computers probably aren't signed into Chrome in the first place -- in which case  Chrome defaults to chrome.storage.local.

**Comment by fnkr** [comment]
So this issue can be closed?

**Comment by semenko** [comment]
Not yet -- no code has been written. Pull requests welcome if you'd like to help! :)

**Comment by TheNavigat** [comment]
If I'm not mistake, ```getStoredUserRules``` in ```chromium/background.js``` loads only manually entered rules. Also, ```addNewRule``` adds a new rule to the local storage. If that is correct, then it should be easy to use Chrome's API to store the user-added rules in the cloud. In other words, we don't really need to "only sync diffs to the default rules set".

Can someone confirm/explain this, please?

**Comment by jsha** [comment]
That's correct. We're also talking about the ability to enable or disable a ruleset. It would be nice if the "is this ruleset enabled" bit could be synced, but only for rulesets where the enable/disable status is different than the default.

**Comment by pipboy96** [comment]
This is most likely already implemented since we always use synced storage if it's available.
