### ISSUE TITLE
Hollywood Reporter (partial) breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#10268]
http://www.hollywoodreporter.com/live-feed/house-cards-season-5-is-leann-dead-neve-campbell-michael-kelly-q-a-1007890

`Hollywood Reporter (partial)` breaks the print and comment icons on the left.
Rule active:
![image](https://user-images.githubusercontent.com/12802056/26960873-842e842c-4ca8-11e7-84c0-e58b285a0910.png)
Rule disabled:
![image](https://user-images.githubusercontent.com/12802056/26960865-77669194-4ca8-11e7-8707-4d22c2634c08.png)

**Comment by numismatika** [comment]
it is a cors issue, that can only be solved by the website itself.

**Comment by jeremyn** [comment]
[`Hollywood-Reporter.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Hollywood-Reporter.xml) needs some attention, for example even the base URL https://www.hollywoodreporter.com redirects from HTTPS to plain HTTP.

**Comment by koops76** [comment]
Font issue again.

**Comment by J0WI** [comment]
@koops76 with the new ruleset from #10663?
