### ISSUE TITLE
Politiken.dk rule breaks video streaming

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#1026]
While they work perfectly well for viewing articles, the rules in Politiken.dk.xml break video streaming; [here's an example](https://politiken.dk/tv/ECE2536531/direkte-med-lidegaard-islamisk-stat-vinder-frem-i-syrien-men-vi-har-bremset-dem-i-irak/).

Since the rules is on by default, this may or may not be a problem; I imagine that the most common use case for the webpage is reading articles, but still.

**Comment by StevenRoddis** [comment]
I suspect if you add an exception for `crossdomain.xml` it'll work.

See https://github.com/EFForg/https-everywhere/issues/970
https://github.com/EFForg/https-everywhere/issues/874

**Comment by fuglede** [comment]
@StevenRoddis Doesn't seem to make a difference. As far as I can tell, it's because http://frontend.xstream.dk/politiken/player/embed-me is blocked as mixed content.

**Comment by fuglede** [comment]
Closing as fixed by the website developers.
