### ISSUE TITLE
Golf Digest vid won't play w/o disabling https Everywhere in Firefox

### ISSUE THREAD

**Issue by CWR64** [EFForg/https-everywhere#10274]
I thought this was all fixed a few weeks ago but the Tiger Woods vid itself would not play today until I disabled "https Everywhere" in current Firefox
http://www.golfdigest.com/story/paul-azinger-on-tiger-woods-some-players-that-think-theres-a-problem-there-with-pain-meds?mbid=nl_060917_daily_hitlist&CNDID=21358373&spMailingID=11225540&spUserID=MTMyNjM1Njg3NDI2S0&spJobID=1180808213&spReportId=MTE4MDgwODIxMwS2

**Comment by cschanaj** [comment]
There is a CORS issues caused by [`Cloudfront.xml#L5`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Cloudfront.xml#L5). Disable `Cloudfront.net` from the extension UI should fix the problem temporarily.

**Comment by CWR64** [comment]
I did that and it did work


Thank you




________________________________
