### ISSUE TITLE
Add lists.openid.net to OpenID.xml

### ISSUE THREAD

**Issue by AxelNennker** [EFForg/https-everywhere#10270]
Please add lists.openid.net to the ruleset.
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/OpenID.xml

`<target host="lists.openid.net" />`

**Comment by jeremyn** [comment]
This issue is resolved by pull request https://github.com/EFForg/https-everywhere/pull/10272.

**Comment by J0WI** [comment]
closed by #10272
