### ISSUE TITLE
Split Extension Code and Rulesets into different repositories

### ISSUE THREAD

**Issue by migueldemoura** [EFForg/https-everywhere#10320]
As it stands, this repository contains both the extension code and rulesets. Given the volatile nature of the lists, we end up having a lot of issues and PRs regarding them, and only a few about the code itself.

I believe splitting these two into separate repositories would be helpful in improving the speed at which the actual extension core is developed.

**Comment by cschanaj** [comment]
Related: #2697

**Comment by migueldemoura** [comment]
@cschanaj, thanks, missed that one while searching.
