### ISSUE TITLE
Progress #9906

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#10378]
Type: other

The statistics will be updated for  **the first release every month** ~odd releases and the latest release since 5.2.15~  until #9906 is closed. See [`simple-statistics.go`](https://github.com/cschanaj/lambda/blob/master/src/simple-statistics.go) for the source code used.

## `ruleset`
| `tag` | `platform` | `#platform` | `default_off` | `#default_off` |
| :---: | :---: | :---: |  :---: |  :---: | 
| 2017.12.6 | 1208 | 2 | 5675 | 104 |
| 2017.11.21 | 1202 | 2 | 5724 | 104 |
| 2017.10.4 | 1210 | 2 | 6199 | 110 |
| 2017.9.12 | 1210 | 2 | 6259 | 118 |
| 2017.8.15 | 1232 | 2 | 6351 | 120 |
| 5.2.21 | 1272 | 3 | 6564 | 131 |
| 5.2.19 | 1279 | 3 | 3647 | 134 |
| 5.2.17 | 1298 | 3 | 3893 | 182 |
| 5.2.15 | 1354 | 3 | 3980 | 198 |

## `platform`
| `tag` | `mixedcontent` | `cacert` | `cacert mixedcontent` | 
| :---: | :---: | :---: |  :---: |
| 2017.12.6 | 1194 | 14 | 0 |
| 2017.11.21 | 1187 | 15 | 0 |
| 2017.10.4 | 1194 | 16 | 0 |
| 2017.9.12 | 1193 | 17 | 0 |
| 2017.8.15 | 1210 | 22 | 0 |
| 5.2.21 | 1234 | 36 | 2 |
| 5.2.19 | 1239 | 38 | 2 |
| 5.2.17 | 1255 | 41 | 2 |
| 5.2.15 | 1244 | 104 | 6 |

## `default_off`
| `tag` | `failed ruleset test` |
| :---: | :---: |
| 2017.12.6 | 3955 |
| 2017.11.21 | 3967 |
| 2017.10.4 | 4276 |
| 2017.9.12 | 4313 |
| 2017.8.15 | 4384 |
| 5.2.21 | 4561 |
| 5.2.19 | 1620 |
| 5.2.17 | 1706 |
| 5.2.15 | 1735 |

## `target`
| `tag` | `target` | `#target` | `target (*.)` | `target (.*)` | duplicated `target` |
| :---: | :---: | :---: |  :---: |  :---: | :---: |
| 2017.12.6 | 137044 | 60452 | 3687 | 80 | 177 |
| 2017.11.21 | 134503 | 60324 | 3697 | 82 | 178 |
| 2017.10.4 | 132874 | 60149 | 3806 | 90 | 182 |
| 2017.9.12 | 132377 | 60113 | 3816 | 98 | 185 |
| 2017.8.15 | 131019 | 60047 | 4110 | 112 | 192 |
| 5.2.21 | 129152 | 60856 | 4301 | 158 | 242 |
| 5.2.19 | 129078 | 60959 | 4394 | 167 | 284 |
| 5.2.17 | 127373 | 60889 | 4457 | 168 | 302 |
| 5.2.15 | 126129 | 60885 | 4501 | 168 | 297 |

## `exclusion`
| `tag` | `exclusion` | `#exclusion` | `exclusion (?!)` |
| :---: | :---: | :---: |  :---: |
| 2017.12.6 | 2670 | 2653 | 1208 |
| 2017.11.21 | 2670 | 2653 | 1209 |
| 2017.10.4 | 2697 | 2680 | 1226 |
| 2017.9.12 | 2697 | 2680 | 1231 |
| 2017.8.15 | 2729 | 2712 | 1255 |
| 5.2.21 | 2370 | 2350 | 1303 |
| 5.2.19 | 2400 | 2378 | 1323 |
| 5.2.17 | 2438 | 2416 | 1340 |
| 5.2.15 | 2458 | 2436 | 1344 |

## `securecookie`
| `tag` | `securecookie` | `#securecookie` | 
| :---: | :---: | :---: |
| 2017.12.6 | 14673 | 8577 |
| 2017.11.21 | 14600 | 8563 |
| 2017.10.4 | 14577 | 8780 |
| 2017.9.12 | 14486 | 8816 |
| 2017.8.15 | 14394 | 8895 |
| 5.2.21 | 14305 | 9054 |
| 5.2.19 | 14384 | 9159 |
| 5.2.17 | 14430 | 9242 |
| 5.2.15 | 14465 | 9291 |

## `rule`
| `tag` | `rule` | `#rule` |
| :---: | :---: | :---: |
| 2017.12.6 | 31137 | 12757 |
| 2017.11.21 | 30998 | 12741 |
| 2017.10.4 | 31041 | 12954 |
| 2017.9.12 | 30948 | 12996 |
| 2017.8.15 | 31078 | 13829 |
| 5.2.21 | 31021 | 14769 |
| 5.2.19 | 31147 | 15338 |
| 5.2.17 | 31218 | 15612 |
| 5.2.15 | 31253 | 15731 |

**Comment by J0WI** [comment]
@cschanaj would you like to move this to a wiki page?

**Comment by cschanaj** [comment]
@J0WI Done. See https://github.com/EFForg/https-everywhere/wiki/Ruleset-Statistics. I'm closing this.
