### ISSUE TITLE
Track a package using UPS - requires login

### ISSUE THREAD

**Issue by Iiridayn** [EFForg/https-everywhere#1039]
##### What happened:

Went to UPS website with clean cache/cookies/etc. Selected a country, clicked on "Tracking" tab above, entered tracking code into "Track by Number" box. Clicked "Track" button. Was redirected to a login page.

##### What I expected to happen:

View track package page without requiring a login. Called UPS who confirmed this was the expected behavior. After some testing, identified that the expected behavior works with HTTPS Everywhere disabled for UPS.com.

**Comment by reedy** [comment]
So for HTTPS you have to login? That's just silly...

http://www.ups.com/WebTracking/track?loc=en_US&WT.svl=PriNav works fine

Try and visit https://www.ups.com/WebTracking/track?loc=en_US&WT.svl=PriNav and it will take you to https://www.ups.com/one-to-one/login?returnto=https%3a//www.ups.com/WebTracking/track%3floc%3den_US%26WT.svl%3dPriNav&reasonCode=-1&appid=ETRACK

**Comment by BobBillson** [comment]
I can confirm this behavior. It used to work as expected in the latest version of Firefox. I had a older version of https-everywhere. I upgraded to the current version. Now I am always sent
to UPS's login page.  Even the http link reedy provided above sends to the login page when I enter a valid tracking number.

**Comment by reedy** [comment]
At a quick glance the fix that @StevenRoddis made, and referenced above should solve this :+1:
