### ISSUE TITLE
https-everywhere-checker disabled Cloudfront.xml

### ISSUE THREAD

**Issue by StevenRoddis** [EFForg/https-everywhere#1042]
```
Disabled by https-everywhere-checker because:
Fetch error: http://www.cloudfront.net/ => https://www.cloudfront.net/: (6, 'Could not resolve host: www.cloudfront.net')
```

https://github.com/EFForg/https-everywhere/blob/b7c038e75b0501168136b4b34eb6c00e6046244f/src/chrome/content/rules/Cloudfront.xml

Is there a way I can specify that it's ok that the rule fails?

I noticed:
```xml
	<target host="*.cloudfront.net" />
	<target host="www.cloudfront.net" />
```
Should be
```xml
	<target host="*.cloudfront.net" />
	<target host="cloudfront.net" />
```

**Comment by jsha** [comment]
The rule failed legitimately: `www.cloudfront.net` doesn't exist. The fix should be to delete that target host. `cloudfront.net` doesn't exist either, so the target host should just be `*.cloudfront.net`. To meet the new ruleset coverage requirements, please find at least 3 example cloudfront subdomains and add them as test URLs, e.g.:

<test url="http://fkjhwfw.cloudfront.net" />

We also need a test URL that matches each of the exclusion patterns.

**Comment by StevenRoddis** [comment]
The last exclusion might be hard to find a match that doesn't expire. I'll see if I can make my own.

**Comment by jsha** [comment]
Good point. I think the https-everywhere checker may actually be okay with 404 and 403 provided they are the same on both the rewritten and unrewritten sides (which are the same in this case). I'll check it out.

**Comment by StevenRoddis** [comment]
Could you please give me PR a once over?
