### ISSUE TITLE
Bug with description translation

### ISSUE THREAD

**Issue by TotalCaesar659** [EFForg/https-everywhere#10470]
Hello, there is the bug with description translation: it remains in English on Firefox for Android and Windows.
![1](https://user-images.githubusercontent.com/14265316/27253869-5cf30688-5385-11e7-8f70-a08af3897b88.png)
![2](https://user-images.githubusercontent.com/14265316/27253871-66f6a6d0-5385-11e7-9bb8-08a3ce7c7849.png)
![4](https://user-images.githubusercontent.com/14265316/27253877-7951579e-5385-11e7-92bb-6ce5323a5daf.png)
But it's normal on Google Chrome.
![3](https://user-images.githubusercontent.com/14265316/27253880-858eae12-5385-11e7-825a-9fb32ef8affa.png)
Can it be fixed?

**Comment by Hainish** [comment]
I think this is just because it cuts off the description mid-word.
