### ISSUE TITLE
Strange behaviour for 'Block all unencrypted requests' after browser restart

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10478]
Steps to reproduce:

1. Enable 'Block all unencrypted requests'. The extension icon should turn red and unencrypted requests are blocked
2. Close Firefox.
3. Open Firefox again.
4. 'Block all unencrypted requests' is still checked (as it should be) but the extension icon is now blue and unencrypted requests are not actually blocked.

Related: #9958 (and possibly #10150).

HTTPS-Everywhere 2017.6.9.1337 and FF 54.0.

**Comment by Hainish** [comment]
@Bisaloo this seems not to be happening in the Embedded WebExtensions version, see https://github.com/EFForg/https-everywhere/pull/11760.  Can you test with this?

**Comment by Bisaloo** [comment]
Nope, still doesn't work. I can reproduce on Nightly (FF 57.0a1 (2017-08-03)) after building the xpi from 48d8d3e.

**Comment by Bisaloo** [comment]
Maybe you got tricked by this new feature, introduced in FF 55.0?

> When entering a hostname (like pinterest.com) in the URL bar, Firefox resolves to the secure version of the site (https://www.pinterest.com) instead of the insecure version (http://www.pinterest.com) when possible

https://www.mozilla.org/en-US/firefox/55.0/releasenotes/

**Comment by Hainish** [comment]
@Bisaloo if you're testing on 57, then the extension shouldn't work at all!

**Comment by Bisaloo** [comment]
Well, it looks like it does. Apparently, nightly still works with Legacy XUL add-ons if you turn the pref on. I simply have a big warning "Legacy".

https://wiki.mozilla.org/Add-ons/Firefox57

**Comment by mgol** [comment]
@Bisaloo Enabling legacy add-ons on Nightly doesn't mean the add-on will work. Firefox devs work on the assumption only WebExtensions will be supported in Firefox 57+ so they're free to break any APIs legacy add-ons depend on. You may enable them but many of them will be broken anyway.

**Comment by Bisaloo** [comment]
> @Bisaloo Enabling legacy add-ons on Nightly doesn't mean the add-on will work. Firefox devs work on the assumption only WebExtensions will be supported in Firefox 57+ so they're free to break any APIs legacy add-ons depend on. You may enable them but many of them will be broken anyway.

Okay, thanks for the heads up!

For this particular issue, it doesn't change anything. `Block all unencrypted requests` was working before browser restart and it's not after restart.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
i can also confirm this issue on chrome. very strange

**Comment by Bisaloo** [comment]
@J0WI, could you also add the `chrome` tag since it apparently affects both browser?

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
SEE ALSO #12190

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/https-everywhere/pull/12268
