### ISSUE TITLE
Add icons for redirect loops

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#10477]
The XPCOM/XUL addon used to display a red looping arrow next to rulesets causing redirect loops. As far as I can tell, the WebExtensions addon doesn't.

[Test url](https://www.instructables.com/id/Duct-Tape-Canoe/).

Related: #9958

**Comment by pipboy96** [comment]
@Bisaloo Test URL no longer reproduces the issue.

**Comment by pipboy96** [comment]
@Bisaloo Is this still relevant/needed?

**Comment by Bisaloo** [comment]
I kinda lost track of this. Does HTTPS Everywhere still detect redirect loops? This was simply intended as a UI feature request so if the underlying mechanism does not exist anymore, we can close it.

**Comment by pipboy96** [comment]
@Bisaloo It does, but AFAIK it doesn't persist between extension reloads.
