### ISSUE TITLE
imgur.com - error with direct links to images on http versions of external domains in comments

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1048]
I have noticed errors with direct links to images on external domains in comments on imgur.com. Users link directly to an image on the http version of an external domain and HTTPS Everywhere redirects to an https version of that page. However, many of the external domains that the linked images are hosted on don't have https versions. So, the user ends up with an untrusted connection error page if they open the link / no preview if they hover over the link. I think Imgur's preview function for image links in comments might have something to do with this error, but I'm not sure.
I hope this didn't sound too confusing. Check the examples below and you should see what I'm talking about.

Examples:

Error: https://cdn.cutestpaw.com/wp-content/uploads/2013/12/s-Just-Hamster-eating-a-bit-of-banana.jpg
Comment linking to the image: https://imgur.com/t/kazaam/ZwXfs

Error: https://media.ifccenter.com/images/films/princess-mononoke_592x299.jpg
Comment linking to the image: https://imgur.com/t8v63D2

Error: https://www.lettersfrompeter.com/wp-content/uploads/2013/12/shaq-and-wife.jpg
Comment linking to the image: https://imgur.com/gallery/kxw5fbg

**Comment by jsha** [comment]
Thanks @cypherpunk! This is a known issue, #747. @BrynM, any updates on the ticket you filed at imgur to avoid protocol-stripping on external links?

Thanks,
Jacob

**Comment by davidcarollo** [comment]
This appears to be fixed now
