### ISSUE TITLE
Ruleset coverage checker: Skip some implicit test URLs

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1049]
Some rulesets, e.g. Royal-Navy, have target hosts that don't make good implicit test URLs. For instance, Royal-Navy's ruleset doesn't rewrite `http://www.royalnavy.mod.uk/`, just `http://www.royalnavy.mod.uk/images/` and a handful of other paths. That means that when the ruleset coverage checker generates an implicit test URL of `http://www.royalnavy.mod.uk/` from the target host, the test fails since that test URL is not covered by any rule or exception.

We should have some way to specify that a give target host should not be used to create an implicit test URL.

**Comment by pipboy96** [comment]
Current solution seems to be creating an exception.
