### ISSUE TITLE
Oregon State University accessibility page broken over HTTPS

### ISSUE THREAD

**Issue by stephenwade** [EFForg/https-everywhere#10505]
https://oregonstate.edu/accessibility/

This page is broken because of mixed content blocking. It tries to load several items, including CSS, over HTTP.

[Screenshots on Imgur](http://imgur.com/a/eEC2r)

**Comment by HTTPSNowhere** [comment]
Oregon-State-University.xml is disabled currently so it's not a problem. @J0WI close this issue?

**Comment by stephenwade** [comment]
Must have been disabled since I ran across it. I can verify that it's disabled now. I'll close this.
