### ISSUE TITLE
Amazon India Domain Not Compatible

### ISSUE THREAD

**Issue by AmazonIN** [EFForg/https-everywhere#10515]
Hello everyone!

I have been testing Amazon's Indian domain, amazon.in, with https-everywhere add-on and found out that it actually breaks the site's functionality!

**Here's how**:
The homepage works fine and hence the rule seems fine too! But when you dig deep and navigate to say a section say, "Today's Deal" and there you will see many items disappear with an infinite loading circle! Almost 90 percent of the whole page become inaccessible!

**Note**;
Amazon US seems to have been handing Indian version a bit differently. Since amazon.com suffers no such issues as mentioned above.

Thank you for your time and I welcome your support.

Dev

**Comment by jeremyn** [comment]
Thanks for your report. We made some changes to how we handle `amazon.in` URLs in pull request https://github.com/EFForg/https-everywhere/pull/7419, which should be included in a new HTTPS Everywhere release tomorrow. Please check after you get the new release and let us know here if the problem persists.

**Comment by AmazonIN** [comment]
Thank you for your help. I will surely check the new version and let you know.

**Comment by AmazonIN** [comment]
Update: June 23, 2017

Navigate here: [http://www.amazon.in/gp/goldbox/](url)
To the very bottom there is an option:  Global Savings and Sale

Now click the ">" to go to next page.
You will here see infinite loading circle on disappeared items.
