### ISSUE TITLE
hangs all webpages on slimjet browser

### ISSUE THREAD

**Issue by geoff915** [EFForg/https-everywhere#10539]
Using SlimJet browser 14.0.15.0. Starting this afternoon, every webpage hangs when trying to access https everywhere. Disabling the extension fixes the problem, including on https websites. The other extensions I have running are ChromeIPass 2.8.1, cVim 1.2.89, Privacy Badger 2017.6.13.1, and uBlock Origin 1.12.4.

**Comment by Paddleless** [comment]
Same for me, using v.2017.6.20 with Slimjet 14.0.9.0 on Linux Mint 17.3. I tried disabling all other extensions but it made no difference.  v.2017.6.20 is working fine for me on Chrome/Chromium/Iridium/Vivaldi/Opera/Firefox.

**Comment by geoff915** [comment]
I'm on Win10. I've posted the issue on the Slimjet forums as well.

**Comment by a80b8829** [comment]
Using ANY VERSION OF SLIMJET 14.x causes issues:
Any version of windows 7,x 8.x, 10.x, seems might partially work in Vista x64.
SOMETHING IS BROKEN WITH THE HTTPS EXTENSION! 

IF ENABLED IT WILL NOT ALLOW YOU TO GET TO ANY WEB SITE HTTP OR HTTPS -*AND* CRASHES EVERY ADD-ON / EXTENSION.

**Comment by a80b8829** [comment]
Also can confirm it is STILL BROKEN ON SlimJet 15.0 BETA Release x86 or x64 versions

**Comment by a80b8829** [comment]
Still BROKEN on ALL VERSIONS OF SlimJet Windows 32 & 64 BIT.
What is taking so long to fix???????

**Comment by pipboy96** [comment]
We do not officially support Slimjet, but I will try to reproduce with current extension version.

**Comment by pipboy96** [comment]
I was unable to run SlimJet, so I can't test it. We do not support SlimJet, so this is wontfix.

**Comment by Paddleless** [comment]
Thanks for checking. I stopped using Slimjet as my default browser about six months ago, but I see I have HTTPS-Everywhere enabled there, so evidently it went back to working at some point. I don't recall the details though.
