### ISSUE TITLE
Travis test fails with error 'SSL certificate problem: unable to get local issuer certificate' even though the certificate is valid

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#10572]
For some reason tests for the pull request #10571 fail with the 'SSL certificate problem: unable to get local issuer certificate' even though the certificate used by [uesp.net](https://uesp.net) is a valid certificate issued by Comodo.

[Travis test log](https://travis-ci.org/EFForg/https-everywhere/jobs/245618490)

**Comment by J0WI** [comment]
The server serves an incomplete certificate chain: https://www.ssllabs.com/ssltest/analyze.html?d=uesp.net
You can reproduce the issue: `firefox --profile $(mktemp -d) --new-instance https://uesp.net`

If you ever visited a site using the same certificate chain, Firefox caches the intermediate chain and you won't notice the issue.
