### ISSUE TITLE
Akamai rule breaks streamcommunity.com.

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1058]
I've had this tab open for awhile, and I forgot that I've had HTTPS-Everywhere disabled for awhile.  I re-enabled it, and the TOC on the right no longer works (and no longer scrolls with the page):

http://steamcommunity.com/sharedfiles/filedetails/?id=343414185&insideModal=1

I disabled the Akamai rule, and it works fine. So it appears that, even if it works most of the time, the Akamai rule is broken.

**Comment by StevenRoddis** [comment]
See https://github.com/EFForg/https-everywhere/issues/909

**Comment by jsha** [comment]
Thanks!
