### ISSUE TITLE
Delete rulesets which are all gone from DNS

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#10595]
I suspected a number of rulesets having all `target` gone from DNS: https://github.com/EFForg/https-everywhere/pull/10516#issuecomment-311502592

Please refer to [`gone-from-dns-list.txt`](https://github.com/cschanaj/https-everywhere-issues/blob/master/gone-from-dns-list.txt)

**Comment by Bisaloo** [comment]
`Caisse-Epargne.fr.xml` is not gone from DNS.

**Comment by koops76** [comment]
Maybe we should wait for some time to let them renew their domains before deleting the rulesets?

**Comment by cschanaj** [comment]
@koops76 Thank you for helping in resolving this issue. Please note that not all the domain listed in the above are completely gone from DNS. Occasionally, you might want to update a ruleset instead of deletion.

**Comment by Bisaloo** [comment]
@cschanaj, any idea why your script didn't pick up  #10738, #10732, #10729?

**Comment by cschanaj** [comment]
For #10738, #10732 The items from the list only include ruleset which

 - `Disabled by https-everywhere-checker` once only
 - Number of occurrence of `Could not resolve host:` == number of non-wildcard `target`

As for #10729, I guess it is because of the improper indentation (with space)

**Comment by cschanaj** [comment]
Let's wait for the discussion in https://github.com/EFForg/https-everywhere/pull/10516#issuecomment-311387749 complete before submitting new deletion PRs.

**Comment by jeremyn** [comment]
@cschanaj I merged your recent deletion PRs but from https://github.com/EFForg/https-everywhere/pull/10516#issuecomment-317886379 it sounds like `full-fetch-test` should get rid of these rulesets automatically, so you don't need to submit PRs to delete them. What do you think?
