### ISSUE TITLE
Nicovideo's video's will not play with the extension enabled

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#10674]
I use nicovideo to watch videos from time to time. However, with this extension enabled, the videos will not load and simply show a black screen in place where the video should've been, I need to disable the extension when I want to watch videos there, and re-enable it again once I'm done. Kinda annoying and a little more security risk. It would be great if this got fixed.

The site domain of the site is; http://www.nicovideo.jp

**Comment by cschanaj** [comment]
Do you mind to specify which browser and HTTPS version you use? Also, it seem to me that the HTML5 playback works correctly, are you using the Flash for video playback?

**Comment by Horthal** [comment]
I use the latest version of Google Chrome and the HTTPS Version is; 2017.6.20.

And the site uses only Flash for their videos, so yes on that last question I guess.

**Comment by koops76** [comment]
@Horthal Until this issue is fixed, only disable Nicovideo's ruleset and not the entire extension so you will still have extra security it adds.

**Comment by cschanaj** [comment]
@koops76 did you test if disabling `nicovideo.jp` related rulesets works (which one)? I can only can the video played with the extension disabled.

**Comment by koops76** [comment]
@cschanaj Can you send me a developer tools log?

**Comment by cschanaj** [comment]
I can't since the machine I am using now do not have Flash installed. But I can have a closer look into this issue later. Thanks anyway.
