### ISSUE TITLE
Make it easier to add coverage to old rulesets

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1069]
Right now the process of updating old rulesets to ensure they have sufficient test coverage is very tedious. Typically one has to pull out a list of hostnames from deeply nested regexes like this one:

```
<rule from="^http://s3(?:-website)?(-ap-(?:nor|sou)theast-1|-(?:eu|us)-west-\d|-external-\d|-sa-east-1)?\.amazonaws\.com/"                                                     
```

Instead, it would be nice to automatically extract hostnames from regexes when possible. The Python `exrex` module claims to do this. We could write a script that would do use that module to extract hostnames where possible and add them to `<target host=...>` tags.

Of course, we can't extract hostnames from wildcard matches like `\w+`, but that's fine. We'll have to manually add test cases for those.

**Comment by zoracon** [comment]
Closing due to new changes seems to have resolved some of this over the years and regex heavy rules are being shied away from. Can reopen if necessary
