### ISSUE TITLE
Add 'to' URLs to ruleset checker

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1071]
Many rules rewrite to a target URL that includes a placeholder, to be replaced with a group from the pattern match. However, some rulesets like https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Microsoft.xml specify replacements with no placeholders. These should generally be safe to treat as a URL and fetch in the ruleset checker, and if the URL fails to load we should disable the rule.

**Comment by pipboy96** [comment]
I'm pretty sure `to` URLs are currently checked. Please re-open if this is not the case.
