### ISSUE TITLE
Different states for normal browser mode, and incognito

### ISSUE THREAD

**Issue by LebedevRI** [EFForg/https-everywhere#10712]
Hi.
It may be useful to be able to have different values of a setting "Block all unencrypted requests" in normal browsing mode, and in e.g. chrome's incognito mode.
While one can manually toggle it each time when opening incognito window, it is error-prone, and has bad usability.

**Comment by koops76** [comment]
Not sure what's the motivation for this. Why do you want to block all HTTP requests in incognito mode but not while browsing normally?

**Comment by LebedevRI** [comment]
Yep

**Comment by koops76** [comment]
But why do you want that?

**Comment by jeremyn** [comment]
In Firefox you can create a new profile (`about:profiles`), set it to permanent private browsing mode (`about:preferences#privacy > "Firefox will: Never remember history"`), and install a new instance of HTTPS Everywhere with its own settings. You can then switch to this second profile to get the desired effect.

As far as I know, Chrome doesn't have incognito mode profiles in the same way. The best you can do there is make a new profile, use the most private settings available, and again install HTTPS Everywhere with its own settings.

I'm not sure supporting a separate private/incognito mode pseudo-profile within HTTPS Everywhere is worth the trouble, though I'm sure it would be considered if someone submitted a pull request to add it.

**Comment by pipboy96** [comment]
This is `wontfix`, but it would be a good idea to have a separate cache for private tabs.
