### ISSUE TITLE
Cleanup Google related Rulesets

### ISSUE THREAD

**Issue by StevenRoddis** [EFForg/https-everywhere#1072]
Born from this comment: https://github.com/EFForg/https-everywhere/pull/1063#issuecomment-74406447

This issue is to track my progress in simplifying and testing Google related rulesets in HTTPSE.

**Comment by StevenRoddis** [comment]
```xml
	<!--	Subdomains that work on all in google.*
							-->
	<rule from="^http://(accounts|adwords|finance|groups|id|m|picasaweb|)\.google\.((?:com?\.)?\w{2,3})/"
		to="https://$1.google.$2/" />
```

Given that there are a lot of `google.tld` variants I'm wondering should I just have `<test>`s with 3 different ccTLDs?

**Comment by jsha** [comment]
That sounds great.

**Comment by StevenRoddis** [comment]
Looking for 3 examples of `*.corp.google.com`.
I've seen a few over the various google open source projects bugtrackers.

**Comment by StevenRoddis** [comment]
Anyone know why;

```xml
	<rule from="^http://www\.googletagservices\.com/tag/js/"
		to="https://www.googletagservices.com/tag/js/" />
```
isn't

```xml
	<rule from="^http://www\.googletagservices\.com/"
		to="https://www.googletagservices.com/" />
```

**Comment by jsha** [comment]
The corp domains are internal to Google. We shouldn't include them in our rulesets because we can't test them.

It looks like the googletagservices thing maybe only advertises the one URL, and the ruleset author was being conservative? https://support.google.com/dfp_sb/answer/2524536?hl=en. I would be fine with changing it to cover the whole domain.

**Comment by StevenRoddis** [comment]
>corp domains

Almost all of them are accessible from the outside.

**Comment by jsha** [comment]
Okay, good point. Even so, I don't think our extension should be in the business of rewriting domains that are logically "internal" to a company's operations, as the corp domains are. Besides, the most important one, login.corp.google.com, has an HSTS header.

**Comment by StevenRoddis** [comment]
`[\w-]+\.corp` existed before I touched the ruleset, perhaps whoever added it knew what they were doing?

**Comment by jsha** [comment]
@2d1: Looks like you added *.corp.google.com in 2012. What do you think of removing it now that login.corp has an HSTS header?

**Comment by StevenRoddis** [comment]
To throw my 5c in, I'm for keeping it. I feel we should force HTTPS as much as possible.

**Comment by jsha** [comment]
Alright, since you are the one putting in all the effort to refurbish this rule, I will yield to your judgement. :-)

**Comment by StevenRoddis** [comment]
I might end up doing all of the Google related rules.

**Comment by StevenRoddis** [comment]
```
2015-02-16 08:08:49,517 ERROR src/chrome/content/rules/GoogleServices.xml: Not enough tests (0 vs 4) for <Rule from 'regex.Regex('^http://(?:www\\.)?google\\.(?:com?\\.)?\\w{2,3}/custom', flags=regex.V0)' to 'https://www.google.com/cse'> [https-everywhere-checker/src/https_everywhere_checker/check_rules.py:232]
```
```xml
		<test url="http://www.google.ca/custom" />
		<test url="http://www.google.com/custom" />
		<test url="http://www.google.com.au/custom" />
```

Shouldn't these be sufficient?

**Comment by jsha** [comment]
Looks like it's not matching those URLs against that regex. Are the
double backslashes intentional? Could there be an earlier rule interfering?

**Comment by StevenRoddis** [comment]
@jsha I assumed the double backslashes were for escaping slashes in a quoted string.
I had a look there is an early rule, I've switched places and will see the result.

**Comment by StevenRoddis** [comment]
Just leaving a note for myself to test news.google.com and google.com/news

**Comment by StevenRoddis** [comment]
Will the targets in https://github.com/StevenRoddis/https-everywhere/blob/c9b6b46598c8c9852eadd6b07c0717c0542e0dac/src/chrome/content/rules/Google.xml

match `www.google.com.au` or only `www.google.com` and `www.google.ca`
I'm not sure what the `*` does in this case. eg Wildcard TLS certs are for `foo.example.org` but not `bar.foo.example.org`

**Comment by StevenRoddis** [comment]
I'm also trying to figure out if `http://www.google.com/u/` still exists and had problems.

**Comment by jsha** [comment]
The wildcards in HTTPS Everywhere match any number of DNS labels, so the target `www.google.*` matches both `www.google.ca` and `www.google.com.au`.

The /u/ path appears to still exist, mostly on G+ (requires login): https://plus.google.com/u/0/photos. I don't see a reference to that path having problems. More info?

**Comment by StevenRoddis** [comment]
https://github.com/EFForg/https-everywhere/blob/c78ab0f5e3559dd5304a7c135d9c10d256647b47/src/chrome/content/rules/GoogleServices.xml#L37

```
	Nonfunctional google.com paths:
		- analytics	(redirects to http)
		- imgres
		- gadgets *
		- hangouts	(404)
		- u/		(404)
```

**Comment by StevenRoddis** [comment]
See: https://github.com/EFForg/https-everywhere/issues/1096

**Comment by StevenRoddis** [comment]
See: https://github.com/EFForg/https-everywhere/pull/1106

**Comment by jsha** [comment]
It looks like #1096 is related to the comment you cited about how the imgres path is nonfunctional. I don't see a reference to that path in the code, though, only the comment. Maybe add it as an exclusion?

**Comment by StevenRoddis** [comment]
@jsha it's possible it's in `GoogleImages.xml

**Comment by StevenRoddis** [comment]
I can't actually find the rule that does this, I have a feeling though it's not `/imgres` but rather `/url`
I'm still doing the clean up :+1:

**Comment by StevenRoddis** [comment]
in `GoogleMaps.xml`

>Disabled by https-everywhere-checker because:
>Non-2xx HTTP code: http://maps-api-ssl.google.com/ (200) => https://maps-api-ssl.google.com/ (404)

`http://maps-api-ssl.google.com/` gives:
```
http://maps-api-ssl.google.com/
HTTP/1.1 302 Found
Location: http://www.google.com/
```
not 200 however.

The 404 seems to be correct as there is nothing there on `/`.
https://www.google.com.au/search?q=site%3Amaps-api-ssl.google.com

**Comment by jsha** [comment]
Good point, we need some mechanism to say "don't use the implicit test URL for this target, because there's nothing on the root of the domain." For now we can manually ignore that error.

**Comment by StevenRoddis** [comment]
I wonder if there are other rules that have been disabled due to this?

**Comment by StevenRoddis** [comment]
and done!
