### ISSUE TITLE
Move the rulesets and Chromium and Firefox extensions into separate repos

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#10720]
It would be better to not tie the ruleset updates to HTTPS Everywhere releases. Instead the rulesets should be updated separately. The rulesets could be downloaded by the extension from a CDN like CloudFront. To protect the users from CDN compromise the rulesets' signature should be verified by OpenPGPjs or another method. It also makes sense to move the rules into a separate Git repository.

**Comment by cschanaj** [comment]
#2697 #9104

**Comment by Bisaloo** [comment]
also https://github.com/EFForg/https-everywhere/issues/2605

**Comment by koops76** [comment]
This is not an exact duplicate of previous issues. This one suggests how the ruleset updates can be secured. Also a separate repository for rules would actually make contributing easier. However it requires changes on the EFF side. It's not something we can do on our own.

**Comment by koops76** [comment]
@Hainish

**Comment by koops76** [comment]
@Hainish We need your opinion on moving the extensions for each browser and the rulesets into separate repos.

**Comment by Hainish** [comment]
We're going to be removing the Firefox extension codebase within a few months, so there's no need to move it into a separate repo.

There is already an open branch to deliver the rulesets out-of-band from the repository itself, hosted here: https://github.com/hainish/https-everywhere/tree/sign-rulesets.  The rulesets are verified using the WebCrypto API.  This will be deployed in the upcoming months.

**Comment by koops76** [comment]
I think this can be closed now.

**Comment by koops76** [comment]
@Hainish What is the SSL Observatory's fate? WebExtensions-based extensions cannot get the SSL certificate data.

**Comment by Hainish** [comment]
The Decentralized SSL Observatory will not be part of the initial Firefox WebExtensions deployment.  We've been working with the Chromium team to add support for certificate introspection.  There's a good chance of it happening and being incorporated into the WebExtensions API, but not imminently.

**Comment by bershan2** [comment]
@Hainish, as per
>We're going to be removing the Firefox extension codebase within a few months, so there's no need to move it into a separate repo.

[This comment](https://github.com/EFForg/https-everywhere/issues/1775#issuecomment-256973768) and [this one too](https://github.com/EFForg/https-everywhere/issues/1775#issuecomment-299102506) suggest that Chrome uses inferior data structure that would be replaced by Firefox'es... but you  suggest to get rid of it... So is Firefox code being merged into WebExtensions (probably, Chrome) or is it thrown away?

**Comment by Hainish** [comment]
@bershan2 definitely not merged, since it's unusable in WebExtensions.  We've been porting some of the Firefox functionality to WebExtensions, we should also port the data structures from Chrome in at some point.
