### ISSUE TITLE
Use of \d in rules

### ISSUE THREAD

**Issue by StevenRoddis** [EFForg/https-everywhere#1073]
Perhaps useful for the style guide.

\d will match a digit **(in any language)**
[0-9] will match any of 0123456789

[0-9] is likely what is wanted.

I wouldn't worry about existing rules, I doubt there will be a situation where it will cause a problem.

**Comment by jsha** [comment]
Interesting! Are you sure that's true in Javascript? I just tried this [Devenagari 6](http://en.wikipedia.org/wiki/Numerals_in_Unicode):

```
> /\d/.test("६")
false
```

**Comment by StevenRoddis** [comment]
Interesting I can't get it to match with js either.
```
> /\d/.test("٠")
false
```

On Python 3 it matches though:
```
>>> import re;
>>> re.match(r'\d', '٠')
<_sre.SRE_Match object at 0x7f9417504370>
```
