### ISSUE TITLE
[changing-cities.org] add ruleset

### ISSUE THREAD

**Issue by jfkb** [EFForg/https-everywhere#10779]

**Comment by koops76** [comment]
Are you sure? I can't reproduce this issue.

**Comment by jfkb** [comment]
if I go to that page:
http://changing-cities.org/projekte.html

There apparently is a https version of it:
https://changing-cities.org/projekte.html

Maybe there is another issue behind it?

**Comment by Bisaloo** [comment]
Thank you for your report. Actually, HTTPS-Everywhere rewrites URL based on a user contributed set of rules.

There is simply no rule for the website you are talking about. This is why you are not redirected. If you would like to add one yourself, here is [how to get started.](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md)

**Comment by Bisaloo** [comment]
I was going to add a rule but I think this website is still being updated/built. It now redirects to `https` but `^https://www.changing-cities.org/` is broken.

I prefer waiting until they're done before creating a ruleset.
