### ISSUE TITLE
MD5 and SHA-1 are used for signing the Firefox extension

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#10770]
[src/META-INF/manifest.mf](https://github.com/EFForg/https-everywhere/blob/master/src/META-INF/manifest.mf):
```
Manifest-Version: 1.0

Name: install.rdf
Digest-Algorithms: MD5 SHA1
```

Both the [MD5](https://en.wikipedia.org/wiki/MD5#Security) and [SHA-1](https://en.wikipedia.org/wiki/SHA-1#Cryptanalysis_and_validation) are [weak](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html).

**Comment by koops76** [comment]
@Hainish ping

**Comment by koops76** [comment]
@Hainish Do you own the AMO account?

**Comment by gloomy-ghost** [comment]
This is about how does AMO sign an extension. I don't think there are anything we can do here. 

Related doc: https://wiki.mozilla.org/Add-ons/Extension_Signing#Algorithm
