### ISSUE TITLE
Add eu.httpbin.org

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1083]
The current ruleset for httpbin.org does not cover eu.httpbin.org. At the moment the user won't be redirected to the https version of the page by HTTPS Everywhere.

**Comment by reedy** [comment]
I think this might be classed as "fixed in master" https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Httpbin.org.xml as everything is rewritten to https for this domain

**Comment by cypherpunk** [comment]
Never mind, it works now.

**Comment by cypherpunk** [comment]
Now I remember the details better. If you do to https://httpbin.org/ and click the EU link at the top of the page you won't be redirected to the https version of the page.

**Comment by reedy** [comment]
Like I say, I still think this will be fixed when newer rules get sent out to users in an extension update...

What version of HTTPSE and what browser/version are you using?

**Comment by StevenRoddis** [comment]
Hi @cypherpunk I made the the change here https://github.com/EFForg/https-everywhere/pull/1054
It was only 5 days ago so it'll take a bit to be released.

**Comment by cypherpunk** [comment]
@reedy: I'm using HTTPS Everywhere 4.0.3 and Firefox 35.0.1
@StevenRoddis: Ok, I understand.
