### ISSUE TITLE
Use ESLint

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#10845]
We may use [standard](https://github.com/standard/standard) for rules.

**Comment by J0WI** [comment]
See #8843 and #9347

**Comment by koops76** [comment]
@J0WI I suggested https://github.com/standard/standard instead of a homebrewn .eslintrc.yml file. This pull request is also out of date ("This branch has conflicts that must be resolved").

**Comment by jeremyn** [comment]
Despite the name, standardjs is not an official standard, it's just popular with some developers. It also has some unusual requirements like not allowing semicolons. Related Hacker News discussion: https://news.ycombinator.com/item?id=14045617.

Two other popular eslint configurations are from Google and Airbnb. Probably the ideal way of deciding what to use it to try all three of them and figure out which configuration most closely matches what we already have.

**Comment by koops76** [comment]
@jeremyn It doesn't claim to be one: https://github.com/standard/standard#but-this-isnt-a-real-web-standard

**Comment by koops76** [comment]
#10897

**Comment by Hainish** [comment]
Can this be closed with the #10852 merge?

**Comment by koops76** [comment]
@Hainish No, it should be closed when one of the JS style guide PRs will be merged.

**Comment by koops76** [comment]
@Hainish Like #10909.

**Comment by koops76** [comment]
@Hainish I already created the PRs for each code style. Let's discuss which to use. Personally, I would prefer either Standard or Google.

**Comment by koops76** [comment]
I hope we'll finish this before the next release.

**Comment by Bisaloo** [comment]
Should help with https://github.com/EFForg/https-everywhere/issues/4039.
