### ISSUE TITLE
Re-activate top-10k+ from #10538

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#10882]
Type: ruleset issue

Related: #9906 #10538 #10545 #10782 

- [x] #6938 

- [x] #10879 

- [x] #10881 

- [x] #10911 

- [x] #10914 

- [x] #10994 

- [x] #11032 

- [x] #11256 

- [x] #11337 

- [x] #11634 

- [x] #11642 

- [x] #11664 

- [x] #11715 

- [x] #12507 

- [x] #12757 

- [x] #12982 

- [x] #13008

**Comment by koops76** [comment]
@ivysrono Maybe you'll add the actual list?

**Comment by ivysrono** [comment]
@J0WI I'll have no time and PC next week. They are important for Chinese user. Please check them if it's possible. Thanks.
