### ISSUE TITLE
Doesn't play nice with DeCentralEyes  in Chrome

### ISSUE THREAD

**Issue by TroyGuffey** [EFForg/https-everywhere#10898]
This extension failed to redirect a network request to chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/1.10.2/jquery.min.js.dec because another extension (HTTPS Everywhere) redirected it to https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js.

**Comment by TroyGuffey** [comment]
Ah, found a solution:  https://decentraleyes.org/configure-https-everywhere/

**Comment by Bisaloo** [comment]
https://github.com/EFForg/https-everywhere/issues/9404 and https://github.com/Synzvato/decentraleyes/issues/148.

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/9404.
