### ISSUE TITLE
Keep an eye on IMDB

### ISSUE THREAD

**Issue by fuzzyroddis** [EFForg/https-everywhere#1090]
https://www.imdb.com/ works MCB are ads.
However https://www.imdb.com/title/tt2967224 redirects to https://www.imdb.com/help/sslsoon

>We hope to launch SSL (actually now TLS) access to all pages on IMDb in the very near future. Thanks for your patience.

I'd just to keep this issue open as a reminder for me (or anyone else) in the future.

**Comment by J0WI** [comment]
"very near future" seems to be very relative.
Should we already redirect ```^http://www.imdb.com/$```?

**Comment by fuzzyroddis** [comment]
Sadly recently viewed and trailers are broken on the front page too.

I'm going to close this as it's been long enough.
