### ISSUE TITLE
StockCharts.com page reload loop

### ISSUE THREAD

**Issue by LanceHaverkamp** [EFForg/https-everywhere#10950]
StockCharts.com gets stuck in rapid page reload loop on Firefox.  Seems fine in Chrome.

HTTPS Everywhere 5.2.20 
in Xubuntu 16.04.01 (LTS)
using Firefox 54.0 (64-bit)

**Comment by koops76** [comment]
I guess just use Chrome then. It's not a problem in HTTPS Everywhere. Firefox and Chrome versions use the same code base. Report this bug to Firefox bug tracker instead.

**Comment by Bisaloo** [comment]
Thank you for your report. Do you have a test url for this? I can't reproduce with Firefox on https://stockcharts.com/

**Comment by LanceHaverkamp** [comment]
Hmmm, interesting.   Because Firefox is fine with that site without https everywhere, and the site told me others have reported it to them as well.

**Comment by j0e1in** [comment]
I have the same issue. I need to turn off "Force encrypted connections" to StockCharts.com manually.

**Comment by schapmangt** [comment]
The reload loop does happen for me as well in Chromium. The site redirects HTTPS to HTTP, while the extension redirects HTTP to HTTPS in an infinite loop. This includes https://stockcharts.com/ - my workaround has been to disable the extension while using the site.

HTTPS Everywhere Version: 2017.12.6
Chroimum Version 63.0.3239.108 (Developer Build) (64-bit)
OS: Arch Linux x86_64

**Comment by rckolon** [comment]
I have the same problem for stockcharts.com in Firefox.  When HTTPS EVERWHERE turns http:// to https:// stockcharts.com does a rapid page reload loop.   The page works for http://.  Disable this add-on extension works for that site.  But it would be nice if we had the ability to turn this off automatically for any designated site.

**Comment by Bisaloo** [comment]
@Hainish, you fixed this in https://github.com/EFForg/https-everywhere/commit/bf4668e0dcd00da5ef8f6f4c60ec518773b9a03f

@rckolon, if you are having issues on a website, you can disable the offending ruleset by clicking the HTTPS Everywhere icon and unchecking the relevant line.
