### ISSUE TITLE
Cloudfront.net rule breaks No such thing as a fish audio player

### ISSUE THREAD

**Issue by LinAGKar** [EFForg/https-everywhere#10970]
When the cloudfront.net rule is active the audio player on http://qi.com/podcast/ will not appear.

**Comment by numismatika** [comment]
classical CORS problem.
You could ask the site-owner to switch to Let's Encrypt instead of a self-signed cert.

**Comment by numismatika** [comment]
#10991 might help here as it rewrites most of the player as well.
Seems to work here

**Comment by Bisaloo** [comment]
@LinAGKar, I think this is fixed. Could you double check and close this issue if this is indeed fixed?

**Comment by LinAGKar** [comment]
Yes, it does seem to be working.
