### ISSUE TITLE
HTTPSE won't install with Avast enabled

### ISSUE THREAD

**Issue by apometron** [EFForg/https-everywhere#1102]
What I can do to do it work in my Firefox alpha?

I am not professional programmer, so take it easy on me.

I am a power user but not a professional programmer.

Alas, I am a beginner programmer.

So, folks, what to do?

There is something on about:config that could help?

**Comment by reedy** [comment]
Which version of HTTPSE are you trying to install? How are you trying to install it? (XPI download from EFF? Via the FF "app store"?)

Are you getting any error messages?

**Comment by apometron** [comment]
> Which version of HTTPSE are you trying to install?

From here: https://www.eff.org/https-everywhere

> How are you trying to install it? (XPI download from EFF? Via the FF "app store"?)

XPI from EFF.

> Are you getting any error messages?

"The addon could not be download because of a connection failure on www.eff.org"

Hail Mary,
Rodrigo Cesar Banhara

**Comment by jsha** [comment]
Do you have Avast anti-virus installed? We have heard that it may interfere with installation of browser extensions.

**Comment by reedy** [comment]
Stable or development releases?

Though, based on the "connection failure on www.eff.org" I suspect that isn't going to matter much

**Comment by apometron** [comment]
Yes, I have Avast, I paid for it. =(

Stable.

**Comment by reedy** [comment]
Can you try disabling Avast temporarily whilst you install HTTPSE?

**Comment by apometron** [comment]
I will try it before sleep. I will report it now, just a minute.

**Comment by apometron** [comment]
Yiiiipie, success. =D

It was Avast the problem. =)

I will install it on Seamonkey also.

Could be made a version for Maxthon, please? =)

Thanks for the help. =)

Hail Mary,
Rodrigo Cesar Banhara
http://about.me/apometron

**Comment by reedy** [comment]
If you want a version for another browser, please open a new request for this :)

**Comment by jsha** [comment]
@apometron: I'll add a warning to the download page saying that Avast may cause problems. Were you able to turn Avast back on after installing HTTPS Everywhere?

**Comment by apometron** [comment]
Yes. I will do it. Thanks!!!

**Comment by reedy** [comment]
@apometron Were you able to turn Avast back on again afterwards?

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen if you think it's still a bug.
