### ISSUE TITLE
"Compatible with Firefox 57+" badge

### ISSUE THREAD

**Issue by kpcyrd** [EFForg/https-everywhere#11027]
https-everywhere is currently one of the three extensions I have installed and I'd like to get on the multi content process train as soon as possible. :)

I've noticed https-everywhere currently doesn't have this badge. It links to this page: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

I'm not sure if there's currently progress to this topic, or if it's blocked by anything. Infos would be appreciated. Thank you!

**Comment by jeremyn** [comment]
"Compatible with Firefox 57+" means the extension uses WebExtensions technology instead of XUL/XPCOM. We are tracking the conversion process to using WebExtensions in Firefox in issue https://github.com/EFForg/https-everywhere/issues/9958.

**Comment by kpcyrd** [comment]
Thanks!
