### ISSUE TITLE
How to deal with SEC_ERROR_UNKNOWN_ISSUER?

### ISSUE THREAD

**Issue by aladar42** [EFForg/https-everywhere#11037]
A lot of e-shops in my country have HTTPS enabled on their server, but they have certificates that are issued (and self-signed) by the developers of the web store software themselves, as opposed to any trusted certificate authority. Most of these sites are built by the kind of "build an eshop as a contractor" companies. Should these be added to HTTPS Everywhere rulesets (since a lot of these issuers are a big, respected companies in the country that most likely have nothing to gain from stealing data), or ignored as not trusted?

**Comment by jeremyn** [comment]
The general rule is that HTTPS Everywhere shouldn't rewrite a URL if the result looks broken to the end user. `SEC_ERROR_UNKNOWN_ISSUER` results in an invalid certificate page, so we shouldn't rewrite URLs if they're going to generate these errors.

There are some exceptions, for example rulesets for domains signed by http://www.cacert.org are included but marked specially. Another potential example is if a particular browser had CAs that weren't recognized by other browsers, maybe we would include rulesets for those domains but also mark them specially.

**Comment by numismatika** [comment]
You should ask them to get a proper cert, Let's Encrypt makes it rather easy and the DV certs are for free,
There is no reason for public sites to use self-signed certs anymore

**Comment by aladar42** [comment]
I usually try to tell them and even direct them to Let's Encrypt, but I have never gotten anything out of it. People don't seem to care - especially these shops, I've looked at their webhosting providers and they offer automatic deployment of certs from Symantec. 

Anyway, that's all I needed to know, I'm gonna close the issue now, thnaks.
