### ISSUE TITLE
Detect if there are infinite redirection loops and show popup to user suggesting to disable the relevant ruleset

### ISSUE THREAD

**Issue by HTTPSNowhere** [EFForg/https-everywhere#11047]
In some instances, a bad ruleset may lead to an infinite loop of http->https->http->https->...

A good way to have the user fix this problem himself is to detect if there are infinite redirection loops and show popup to user suggesting to disable the relevant ruleset.

```
We detected that a ruleset was causing redirection loops, you can: [Disable] [Cancel] 
```

Not sure however if the detection part may be possible as a WebExtension.

**Comment by koops76** [comment]
I think the Chromium extension already does something similar, but without warning the user.

See https://github.com/EFForg/https-everywhere/blob/master/chromium/background.js#L556

**Comment by pipboy96** [comment]
Duplicate of #10477.
