### ISSUE TITLE
HTTPS Everywhere breaks setting user passwords in Emby media server

### ISSUE THREAD

**Issue by tkedwards** [EFForg/https-everywhere#11042]
Emby (emby.media) is an open source media server. It's managed via a web interface that runs on port 8096 (HTTP) or port 8920 (HTTPS). The problem is that with HTTPS Everywhere enabled the part of the interface where you (as an admin user) can set the passwords for other users is broken.

**To reproduce:**
- start Firefox and ensure HTTPS Everywhere is enabled
- install Emby and login to its web interface
- Settings->Users. Create a 'test' user
- While still with this user's settings open click the Password tab and attempt to set the password

**Expected Results:**
User's password is set successfully even with the HTTPS Everywhere extension enabled

**Actual Results**
Error message from Emby 'Invalid user or password entered' if the HTTPS Everywhere extension enabled

**Workaround**
Disable HTTPS Everywhere and restart Firefox, edit the Emby user's password, re-enable HTTPS Everywhere and restart FF

**Comment by pipboy96** [comment]
Extremely difficult to reproduce, issue is also old. Closing.
