### ISSUE TITLE
salsalabs.org breaks with HTTPS-E

### ISSUE THREAD

**Issue by austin987** [EFForg/https-everywhere#1107]
http://org.salsalabs.com/o/641/p/dia/action3/common/public/?action_KEY=17223

When loaded with HTTPS-E enabled, the layout of the site is broken, see screenshots.
![screenshot - 02222015 - 03 50 29 pm](https://cloud.githubusercontent.com/assets/464648/6320691/9b0b1788-baaa-11e4-8c2a-bf4bfcfdc6c4.png)
![screenshot - 02222015 - 03 50 51 pm](https://cloud.githubusercontent.com/assets/464648/6320690/9b08cc30-baaa-11e4-809e-9848e57d253c.png)

**Comment by reedy** [comment]
Ruleset is disabled by default. Mixed content from various 3rd party domains
