### ISSUE TITLE
Use Webpack

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#11107]
[Webpack](https://webpack.js.org/) allows using ES6 modules to split code instead of using global variables. It transforms ES6 modules into code that can be ran in the environment that doesn't support ES6 modules yet (for example current Chrome version). It also can use CommonJS modules like [https-everywhere-rules](https://github.com/koops76/https-everywhere-rules) which is a ruleset parsing library working in Node and browser, complete with Mocha unit tests, which I used to create a list of rulesets which have failed the ruleset test (#11114). It will also make developing and running unit tests for HTTPS Everywhere code easier.

**Comment by jeremyn** [comment]
I support switching the current extension build process from the current homegrown bash/Python stuff to npm+webpack+etc. This might be useful: https://github.com/mdn/webextensions-examples/tree/master/webpack-modules.

> It transforms ES6 modules into code that can be ran in the environment that doesn't support ES6 modules yet (for example current Chrome version).

You need something like [Babel](https://babeljs.io) for this, see https://webpack.js.org/guides/getting-started/#es2015-modules.

**Comment by koops76** [comment]
@jeremyn Nope, I tried using ES6 modules directly and it compiled into valid module-less code. Webpack is essentially a ES6 modules polyfill in addition to a bundler.

**Comment by jeremyn** [comment]
The link I gave to https://webpack.js.org/guides/getting-started/#es2015-modules says that Webpack transpiles `import`/`export` statements but nothing else. So if you're importing a module that only contains ES5 stuff, you're fine, but if you're importing a module that contains ES6 stuff then you need something like Babel.

In other words, by itself Webpack can handle the ES6 module concept, but not a module that has ES6 contents. Does this match your testing?

**Comment by koops76** [comment]
@jeremyn ES6 is not transpiled except of modules, as expected.

**Comment by koops76** [comment]
I guess I'll have to wait until #10909 is merged before starting to split the code into modules.
