### ISSUE TITLE
Search Bar Compatibility for Google Subdomains Broken

### ISSUE THREAD

**Issue by uGuardian** [EFForg/https-everywhere#11179]
When running HTTPS Everywhere, any attempts to search, for instance, google images by typing images.google.com and then pressing tab, results in a 404.

This appears to be an issue with how it redirects the request, as normally it will redirect to www.google.com
`https://www.google.com/search?site=&tbm=isch&source=hp&biw=929&bih=931&q=Beep+Boop&btnG=Search+by+image&oq=Nitronic+Rush&gs_l=img.3..0l4j0i24l6.1247.3203.0.3361.13.10.0.3.3.0.107.1003.4j6.10.0....0...1ac.1.36.img..0.13.1012.Plq7rZT5V8E&gws_rd=ssl#gws_rd=ssl&imgrc=zwb4voULlLQnBM:`

If HTTPS Everywhere is enabled, instead it attempts to redirect to https://images.google.com like this:
`https://images.google.com/search?site=&tbm=isch&source=hp&biw=929&bih=931&q=Beep+Boop&btnG=Search+by+image&oq=Nitronic+Rush&gs_l=img.3..0l4j0i24l6.1247.3203.0.3361.13.10.0.3.3.0.107.1003.4j6.10.0....0...1ac.1.36.img..0.13.1012.Plq7rZT5V8E`

In my testing, with HTTPS Everywhere disabled, using tab-searching normally brings up the exact same address in HTTP, which always does redirect properly. HTTPS appears to lack the redirect though.
It seems the only thing that needs to be changed in the URL is either,
A: It needs to be HTTP instead, or
B: It needs to specially redirect to `https://www.google.com/search?` properly, which should be possible as the address appears to be almost exactly the same after redirect, although it's missing the `&gws_rd=ssl#gws_rd=ssl&imgrc=zwb4voULlLQnBM:`

**Comment by bardiharborow** [comment]
This should have been fixed by #11068.
