### ISSUE TITLE
"Add this site" to what?

### ISSUE THREAD

**Issue by olivierlacan** [EFForg/https-everywhere#1119]
It's very unclear what this link does. Does it add the site to a whitelist therefore preventing it from being forced to use HTTPS? If so the link should say more or instead focus on what "adding this site" enables: "Make this site accessible without HTTPS", perhaps?

![image](https://cloud.githubusercontent.com/assets/65950/6372077/b056538a-bcd7-11e4-81d8-0dad8c5e2258.png)

Moreover, the "What is this?" link directs to https://www.eff.org/https-everywhere which doesn't explain the "Add this site" link. Nor does https://www.eff.org/https-everywhere/faq. 

All I could find inside the FAQ was: 

> In the meantime, you can disable the rule affecting that particular site in your own copy of HTTPS Everywhere by clicking on the HTTPS Everywhere toolbar button and unchecking the rule for that site.

"unchecking the rule for that site" is not the current interface. Maybe that recently changed and the FAQ hasn't been updated.

**Comment by reedy** [comment]
The "What is this?" is a general thing of "what is this window?", or put another way, "what is https everywhere?"

Clicking "Add this site" takes you to "Add a new rule" window. This is probably a better string to have on the first window.

The unchecking interface should be there on the same window if you visit a site with a ruleset already defined

![image](https://cloud.githubusercontent.com/assets/67615/6384542/c0c05954-bd55-11e4-85b9-793437d143ab.png)

**Comment by jsha** [comment]
Fixed, thanks!

BTW, @olivierlacan if you are interested in further improving this feature, there is a high priority bug we need help on: https://github.com/EFForg/https-everywhere/issues/741#issuecomment-71249367

**Comment by diracdeltas** [comment]
this seems sufficiently fixed

**Comment by reedy** [comment]
@olivierlacan Do you think we still need to update the docs on eff.org? Specifically, where the "What is this?" link points to?

**Comment by olivierlacan** [comment]
@reedy I think it would help. It wasn't very helpful when I did get there because I couldn't find something that matched the possible functionality for that action.

**Comment by semenko** [comment]
Seems good for now, closing.
