### ISSUE TITLE
Blocked loading mixed active content at https://query.nytimes.com/

### ISSUE THREAD

**Issue by mavit** [EFForg/https-everywhere#11191]
When http://query.nytimes.com/mem/archive-free/pdf?res=9B04E2DF1438EF32A25753C3A96F9C946497D6CF is redirected to `https://` by HTTPS Everywhere, an insecure `iframe` fails to load.

**Comment by koops76** [comment]
What does this iframe contain? If it's an ad, then it won't be fixed.

**Comment by numismatika** [comment]
No it is a pdf with seemingly old articles. It is hosted on a cdn without a valid certificate, so we can't fix that ourselfes.

**Comment by J0WI** [comment]
closed by #11262
