### ISSUE TITLE
Do a fetch test of changed rules in pull requests

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1125]
Right now our automated ruleset test on Travis only tests that updated rulesets have sufficient test coverage. Ideally I'd like it to also run a fetch test to make sure all domains exist, answer on 443, and provide a success response (and eventually, test for mixed content).

However, running a fetch test for all rulesets on all pull requests would take too long. So I'd like to make pull requests on Travis test only the rules changed in that pull request. Has anyone done this? Any suggestions?

One confounding factor: Travis does a shallow clone, so it's not trivial to do a diff --name-only against origin/master. I've tried adding a fetch command to the test, but no luck so far.

**Comment by J0WI** [comment]
This has been implemented.
