### ISSUE TITLE
Tumblr user subdomains no longer redirect to HTTP.

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11311]
For example:
https://discoverynews.tumblr.com/
https://americasgreatoutdoors.tumblr.com/
https://staff.tumblr.com/

**Comment by cschanaj** [comment]
According to [`this`](https://twitter.com/JoshHixson/status/803673098453155840), it seems that only the newly created Tumblr blog will redirect to HTTPS by default. I am not really sure what can be done on our side. 

See also [`Tumblr.xml#L17`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Tumblr.xml#L17)

**Comment by jeremyn** [comment]
@koops76 What specific changes to HTTPS Everywhere are you asking for?

**Comment by koops76** [comment]
@jeremyn Redirecting them to HTTPS I guess.

**Comment by koops76** [comment]
Closing until Tumblr will migrate all blogs to HTTPS.
