### ISSUE TITLE
List of all CACert rulesets (17 rulesets, updated 09/04/2017)

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#11385]
Similar to #11114, I created a list of all CACert rulesets, sorted by Alexa rank.

https://gist.github.com/koops76/99f0049a8026999f3ddad245275375a1

Updated 09/04/2017, commit 5a67f79.

**Comment by koops76** [comment]
#9582

**Comment by J0WI** [comment]
Sadly the list here is gone, so this issue has no value anymore. If anybody would like to create a new list, our wiki might be a better place.
