### ISSUE TITLE
"Add a rule for this site" broken in Chromium

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1148]
Steps to reproduce:

1. Visit an HTTPS site with no rule (e.g. https://jacob.hoffman-andrews.com).
2. Click HTTPS Everywhere icon
3. Click "Add a rule for this site"
4. Click "Add rule"

Expected result:

Popup goes away, rule added.

Actual result:

Popup stays, no rule added.

**Comment by diracdeltas** [comment]
I believe @vijayp implemented this so cc'ing him.

**Comment by jsha** [comment]
This is fixed!
