### ISSUE TITLE
"Download Brackets without Extract" link on brackets.io blocked

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#1157]
The "Download Brackets without Extract" link on [brackets.io](http://brackets.io/) doesn't work for me (Firefox 36.0 on Windows) when HTTPS Everywhere is enabled. I opened the console and found this:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1424389017263. This can be fixed by moving the resource to the same domain or enabling CORS.

I've opened an [issue on the brackets.io repository](https://github.com/adobe/brackets.io/issues/138) about this. Their developer is willing to help but doesn't use HTTPS Everywhere. Can you point what the exact problem is, and if there is any way for him or you to solve it?

**Comment by jsha** [comment]
There appears to be an interaction between HTTPS Everywhere and CORS that we are trying to solve: #49. In the meantime, the simplest thing the developer can do to help is to change the URLs fetched with CORS to point to the HTTPS version, e.g. httpS://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1424389017263. AFAIK S3 doesn't charge extra for using the HTTPS version, per http://aws.amazon.com/s3/pricing/.

Thanks,
Jacob

**Comment by StevenRoddis** [comment]
It's likely they'll need to send CORS headers on that json file.

What's weird is I can't resolve `files.brackets.io`

http://files.brackets.io/updates/stable/en.json
curl: (6) Could not resolve host: files.brackets.io

Which led me to think they are serving it over `brackets.io` to avoid CORS.
`Access-Control-Allow-Origin: *` being the CORS header.

```
http://brackets.io/updates/stable/en.json?asda
HTTP/1.1 200 OK
Server: GitHub.com
Date: Mon, 09 Mar 2015 02:12:56 GMT
Content-Type: application/json
Content-Length: 43534
Last-Modified: Wed, 04 Mar 2015 22:45:33 GMT
Expires: Mon, 09 Mar 2015 02:22:56 GMT
Cache-Control: max-age=600
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

I can't find the rule causing this, is there a way to enter a url and have it spit out which rulesets affect it?

**Comment by TheNavigat** [comment]
Can someone confirm that this isn't solve yet? If it isn't, any instructions on how to reproduce the issue?

**Comment by jsha** [comment]
I was able to reproduce using the instructions in the first post: Visit brackets.io, then click the "download brackets without extract" link (it's small)..

**Comment by TheNavigat** [comment]
Oh, my bad. The link works perfectly on Chrome, but not Firefox.

**Comment by fuzzyroddis** [comment]
I can confirm it works on Chrome but not Firefox too.
I get really strange behaviour on Firefox the en.json (fairly sure it's called that, it was yesterday when I tried) appears to respond with `Access-Control-Allow-Origin: *` on Firefox but is blocked for not having `Access-Control-Allow-Origin`. But on Chrome it appears to respond with `Access-Control-Allow-Origin: http://brackets.io` and works.

It's served over S3 which I don't think has the capability to send different headers based on user-agent. Could this be a problem in the extension?

**Comment by fuzzyroddis** [comment]
Just tried again on Firefox 42.0a

Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD

(This was also with the Amazon S3 ruleset disabled)

Interestingly via curl I don't get any Access-Control headers, perhaps because I'm not sending an Origin?
Yep,

curl -H "Origin: brackets.io" http://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1234
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Max-Age: 3000
```

I'm going to assume Chrome is doing something silly, I checked and according to the devtools it's responding with `Access-Control-Allow-Origin: http://brackets.io`


On enabling the Amazon S3 ruleset in HTTPSE for Firefox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1440474832738. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

Could the extension be stripping the header?

**Comment by fuzzyroddis** [comment]
Also of note is when checking with Fiddler and Wireshark, I couldn't see Firefox actually make a connection to s3.amazonaws.com when the ruleset is enabled, but it does state in the error console that it was blocked due to no `Access-Control-Allow-Origin` header. Which doesn't make sense if it never requested the resource in the first place. None of the Client Hellos I recorded had s3.amazonaws.com in their SNI. Which suggests to me Firefox isn't even making the request.

**Comment by TheNavigat** [comment]
@fuzzyroddis, "I get really strange behaviour on Firefox the en.json (fairly sure it's called that, it was yesterday when I tried) appears to respond with Access-Control-Allow-Origin: * on Firefox but is blocked for not having Access-Control-Allow-Origin. But on Chrome it appears to respond with Access-Control-Allow-Origin: http://brackets.io and works."

https://stackoverflow.com/questions/26946240/firefox-setresponseheader-isnt-working#comment42479840_26952560

If you're manipulating the headers before the request is processed, Firefox will show the original request's data, although the errors displayed will correspond to the manipulated and processed ones. Don't trust the Network tab if you're working on a Firefox add-on.

Also, regarding your last comment, are you sure the file isn't cached?

**Comment by fuzzyroddis** [comment]
@TheNavigat I'm 99% sure the file isn't cached as every other resource is grabbed again.
I was even intercepting HTTPS connections just to see what Firefox ultimately sent.

Could someone please try to reproduce? I'm happy to be proven wrong.

**Comment by fuzzyroddis** [comment]
Just confirmed that no connection was made to `s3.amazonaws.com` using Firefox with the ruleset enabled.
