### ISSUE TITLE
brackets.io - Download button does not work with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by scheinercc** [EFForg/https-everywhere#11640]
On http://brackets.io the CTA is broken (href value is "#") when HTTPS Everywhere is enabled.

See the comment on my original report which lead me to test the add-on:/
https://github.com/webcompat/web-bugs/issues/8632#issuecomment-319865463

I have now also tested it in current stable FF 54.0.1 with a pretty clean profile and only HTTPS Everywhere installed. Same issue.

Please let me know if more details are required. Thanks

**Comment by koops76** [comment]
Likely a mixed content issue.
