### ISSUE TITLE
Reference to Kaspersky antivirus in the SSL Observatory setting "Submit and check certificates signed by non-standard root CAs"

### ISSUE THREAD

**Issue by galenide** [EFForg/https-everywhere#11680]
In the SSL Observatory Preferences window, when the advanced options are shown, there is a checkbox setting to "Submit and check certificates signed by non-standard root CAs". The explanation text for this setting refers to the situation where a user's HTTPS connections go through a proxy ("an intrusive corporate network or Kaspersky antivirus software") that does inspection of HTTPS traffic by having a custom root certificate installed in the user's browser.

From what [others have said](http://www.securityweek.com/antivirus-software-has-negative-impact-https-security-researcher), inspection of HTTPS traffic via a proxy is something that is done by multiple antivirus software solutions. (In addition, such antivirus software is not specific to corporate environments.) As such, it might be useful to make the description of the option more generic, perhaps by changing "Kaspersky antivirus software" to "antivirus software".

**Comment by koops76** [comment]
SSL Observatory is going away with WebExtensions transition. At least until WebExtensions will support certificate inspection.

**Comment by koops76** [comment]
@J0WI Close please.
