### ISSUE TITLE
Tumblr redirects incorrectly redirect some images to Edgecast CDN

### ISSUE THREAD

**Issue by IBBoard** [EFForg/https-everywhere#1168]
When viewing Tumblr, approximately half of the blog-posted images on my dash do not show up. If I right-click and view the image then I get an error from Edgecast CDN [1]. The beginning parts of the URLs for working images are identical.

If I disable the "Tumblr (partial)" ruleset then everything works fine (but I'm obviously not protected). If I clone the Tumblr ruleset and comment out the line:

    <rule from="^http://data\.tumblr\.com/"
                to="https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/" />

(which gives me all of the protection of the original rules, except on data.tumblr.com) then everything works fine. I don't know why this works, since the images are on ##.media.tumlr.com and so shouldn't be matching the data.tumblr.com rule, but it seems to work.

Browser: Firefox 35 and Chromium 39 on Linux
Extension versions: 4.0.3 and 2015.1.22
No other custom rules used

[1] http://ibboard.tumblr.com/post/112897748412/thank-goodness-for-content-delivery-networks

**Comment by StevenRoddis** [comment]
From what I can tell they seem to have switched from Edgecast to Amazon AWS recently.

http://data.tumblr.com
HTTP/1.1 403 Forbidden
x-amz-request-id: ...
x-amz-id-2: ...
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 09 Mar 2015 01:52:29 GMT
Server: AmazonS3

**Comment by StevenRoddis** [comment]
Interesting

GET https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/6ee5b4a93e255317345f11072a79387f/tumblr_nkti8j6ZS61sgdbw4o1_500.jpg 403 (Forbidden)

But
https://40.media.tumblr.com/6ee5b4a93e255317345f11072a79387f/tumblr_nkti8j6ZS61sgdbw4o1_500.jpg 200 (works)

**Comment by StevenRoddis** [comment]
Found it. This makes much more sense.
https://github.com/EFForg/https-everywhere/blob/4.0.3/src/chrome/content/rules/Tumblr.xml

It's fixed in master.

**Comment by stefan2904** [comment]
thanks a lot for the fast response. :+1:
