### ISSUE TITLE
obsolete addon-sdk submodule

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#11694]
Not sure if it's worth since we move to webextensions anyway, but the addon-sdk submodule liks to an obsolete repo: https://github.com/mozilla/addon-sdk
We should make sure that we use the up to date version that is included in Firefox builds.

ping @Hainish

**Comment by Hainish** [comment]
This is going away with the move to `webextensions` anyway.  Thanks for flagging this.
