### ISSUE TITLE
Can't log in to gog.com

### ISSUE THREAD

**Issue by austin987** [EFForg/https-everywhere#1172]
Using 5.0-development2, gog.com can't log in. I noticed that it seems to have been recently disabled:
https://github.com/EFForg/https-everywhere/blob/691be3b4bcb6540258ba895a037866ab48a87cca/src/chrome/content/rules/GOG.com.xml

but there wasn't any issue for it.

**Comment by jsha** [comment]
This is fixed in master by disabling the rule.
