### ISSUE TITLE
Addon won't show any rules with current Nightly

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#11759]
The HTTPS Everywhere Icon stays light blue although there have to be rules for the page i am on.
Clicking it, shows no matching rules , not even disabled ones.

The Browser Console gives 

> ReferenceError: can't access lexical declaration `HTTPSEverywhere' before initialization
> TypeError: httpsEverywhere is undefined[Weitere Informationen]

**Comment by koops76** [comment]
@numismatika Can you tell the line numbers these errors happen on?

**Comment by numismatika** [comment]
'  toolbar_button.js:409:7'

**Comment by koops76** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/toolbar_button.js#L23
Try replacing `let` with `var`.

**Comment by J0WI** [comment]
Mozilla is removing XPCOM from the current Nightly, so it's expected that things won't work anymore.
See https://github.com/EFForg/https-everywhere/projects/1

**Comment by koops76** [comment]
This should be closed I guess.
