### ISSUE TITLE
build exclusions broken

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1176]
In create-xpi.py there is a mechanism to read a file called '.build_exclusions' in the root of the project, and exclude those from the build. The mechanism tries to glob each of those patterns, but can't glob arbitrarily deep files. It needs to be updated to glob arbitrarily deep files so patterns like "*.sw?" (vim swapfiles) can work. Alternately it should build only files that are checked into source control, plus a whitelist of known generated files like rulesets.sqlite.

**Comment by jsha** [comment]
cc @diracdeltas

**Comment by pipboy96** [comment]
Extremely old, likely related to a pre-WebExtensions version. Closing. Feel free to reopen if you are still experiencing this issue.
