### ISSUE TITLE
In-extension ruleset XML editor

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#11794]
We could use [CodeMirror](https://codemirror.net/).

**Comment by koops76** [comment]
@J0WI Maybe you'll add this to the kanban?

**Comment by jeremyn** [comment]
FYI, but as far as I know, the rulesets are stored in the extension itself in a compacted/modified form (see https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-315202693). So, they are not available to edit within the extension itself the way that you see them on GitHub or the Atlas.

On the other hand this could be part of good alternative to the soon to be deprecated `HTTPSEverywhereUserRules/` subdirectory (issue https://github.com/EFForg/https-everywhere/issues/10822 and elsewhere).

**Comment by koops76** [comment]
@jeremyn I mean the editor for the custom rulesets.

**Comment by gloomy-ghost** [comment]
Does #12863 fulfill this?

**Comment by koops76** [comment]
@gloomy-ghost No, we need real custom ruleset functionality.

**Comment by jeremyn** [comment]
This issue is technically resolved by https://github.com/EFForg/https-everywhere/pull/12863, which does introduce an XML ruleset editor in the extension. I guess though that @koops76 wants more robust XML highlighting, which is reasonable.

There must be some compromise solution between nothing and something as full-featured as CodeMirror. In https://github.com/EFForg/https-everywhere/pull/12863#issuecomment-336958528 I asked @Hainish for some guidelines but so far he hasn't responded to that request:

> * We should have some kind of XML highlighting. I know we talked about this before in https://github.com/EFForg/https-everywhere/issues/11794. CodeMirror is probably too heavyweight but there appear to be many options for small JS/browser-based syntax highlighters. I can try to find something if you can give me some requirements, e.g. must be 10kB or less in size etc.

**Comment by koops76** [comment]
@jeremyn CodeMirror can be built to only include XML highlighting for lesser size.

**Comment by koops76** [comment]
@jeremyn CodeMirror with XML highlighting included, minified and gzipped is only 54.1 KB.

**Comment by gloomy-ghost** [comment]
50KB sounds ok to me, given that we used to ship megabytes of tests in the ruleset file for years without anyone complaining

**Comment by Hainish** [comment]
Is there any reason why this has to be shipped with the release version, and not simply passed as a build flag like `--include-debug-xml-highliting`?

**Comment by jeremyn** [comment]
Building and using an unsigned extension, and using a Firefox build that allows for unsigned extensions, is annoying and requires extra steps.

It encourages using non-stable versions of Firefox and the extension for testing.

It would be nice to have highlighting available for contributors who are developing rulesets who don't want to go through these extra steps. We might get more and higher quality rulesets that way.

Firefox and Chrome have developer tools in their browsers even though most users don't use them. They could save a few bytes by leaving them out, but they don't, I guess for reasons some of which also apply here.

**Comment by jeremyn** [comment]
Also as far as I know it's not possible, or at least unsupported, to build the extension on Windows.

It might also be difficult to build the extension on a system the user doesn't fully control, such as a work/school/library/shared computer.

**Comment by Hainish** [comment]
> It encourages using non-stable versions of Firefox and the extension for testing.

The unbranded extensions are not non-stable.  They do allow unsigned versions of extensions to be installed, and that's a security risk, but non-stable is something different.  Regardless, your point is taken.  I think it's fine to add some syntax hilighting as long as it only adds ~50k.

**Comment by jeremyn** [comment]
https://github.com/google/code-prettify looks like a good choice. StackOverflow [uses it](https://github.com/google/code-prettify#javascript-code-prettifier). The minimized download at https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js is about 8KB, though of course we should include the code in the project and not use a CDN.

**Comment by Hainish** [comment]
@jeremyn is it available for `texarea` elements as well?  Some libraries only support rendered HTML rather than inputs.

**Comment by jeremyn** [comment]
Oops, you're right, code-prettify seems to just be for rendered text.

**Comment by jeremyn** [comment]
PR https://github.com/EFForg/https-everywhere/pull/13560 adds CodeMirror support to the ruleset debugger.

**Comment by jeremyn** [comment]
I'm closing this issue since CodeMirror has been added to the ruleset debugger.
