### ISSUE TITLE
Create a Dev version for FF >= 57 users

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#11805]
Many developers use the Firefox Dev version, which will be upgraded to 57 on 9/26: https://wiki.mozilla.org/RapidRelease/Calendar.  Some even use nightly, which is already on 57.

In this version, the Embedded WebExtension will cease to function.  We should provide these users with the full WebExtensions version early, through a development release channel.

We don't want to create persistent additional work moving forward, so once the full WebExtensions version is available this dev channel will be deprecated and receive no further updates.  Therefore we should make clear to these users when it becomes deprecated, and perhaps add a badge or some clear indicator in the addons dialogue that it's been deprecated and developers should upgrade to the mainline version.

**Comment by Bisaloo** [comment]
I posted this in another issue but it's also relevant here. Mozilla's plan about the deprecation of legacy add-ons in FF 57.

https://wiki.mozilla.org/Add-ons/Firefox57

**Comment by gitarra** [comment]
@Bisaloo Yes this addon has been broken on Nightly since version bump to 57.

**Comment by koops76** [comment]
@Hainish There's no need of this. See https://github.com/EFForg/https-everywhere/issues/10478#issuecomment-321625811.

**Comment by Bisaloo** [comment]
A clearer comment on what's going on in Nightly: https://mail.mozilla.org/pipermail/dev-addons/2017-August/003059.html

This won't work for the Beta channel (which will use FF57.0 from 2017-09-20, [source](https://wiki.mozilla.org/RapidRelease/Calendar)) so it may be worth to create the dev version for them.

**Comment by numismatika** [comment]
reading files from disk, is that something that won't work at all or just not yet?
I like symlinking the repo to HTTPS-UserRules for testing. Very simple and effective trick.

**Comment by koops76** [comment]
@numismatika Did you disable the built-in rulesets in some way?

**Comment by koops76** [comment]
@numismatika It won't work at all after we will migrate to WebExtensions completely.

**Comment by Hainish** [comment]
@numismatika that's right, it won't work at all under WebExtensions.  This is a *good* thing for security.  Browser extensions you install shouldn't be able to arbitrarily read contents of your filesystem.

**Comment by numismatika** [comment]
@Hainish  Nobody wants "arbitrary" file reads. I think a defined folder per extension wouldn't hurt security.
Apart from the fact that the extension can simply be unpacked and studied when reviewing it in the first place.

**Comment by sp-1234** [comment]
Stopped working on Nightly today. Please make the webext build public ASAP.

**Comment by koops76** [comment]
@sp-1234 https://eff.org/files/https-everywhere-test/
Download the latest WebExtensions-only version here.

**Comment by kah0922** [comment]
@koops76 I'm getting a 404 error with that URL,
[This is the URL you're looking for (I think)](https://www.eff.org/files/https-everywhere-test/index.html)

**Comment by edmorley** [comment]
I've opened a tracking bug on Firefox's side [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1390116), so that the script that generates https://arewewebextensionsyet.com/ has something to link to. If there are any platform changes required to assist the conversion to a web extension, please mark them as blocking that bug. Many thanks!

**Comment by ejaszewski** [comment]
Probably best to publish the WebExt version at https://www.eff.org/files/https-everywhere-test/index.html as a Beta on Mozilla's plugin website. This will allow users of Firefox who need a Web Extensions version to auto-update the plugin, rather than having to reinstall from the eff.org website for each version.

**Comment by koops76** [comment]
@ejaszewski This version is not ready for non-developer use.

**Comment by ejaszewski** [comment]
@koops76 It would still be appropriate to add it as an Alpha version then. Either way for alphas and betas on the Mozilla plugins website, the user must explicitly access them, so end users who have no need for a beta version wouldn't even see them on the normal version listing.

**Comment by Hainish** [comment]
I've released a new version from the (rebranded as) developer channel, and added the following text to https://www.eff.org/https-everywhere:

> **Developers:** If you are using Firefox Nightly, you'll have to install from our developer (fully WebExtensions) channel, available [here](https://www.eff.org/files/https-everywhere-test/https-everywhere-latest.xpi) ([signature](https://www.eff.org/files/https-everywhere-test/https-everywhere-latest.xpi.sig)).

**Comment by starchy** [comment]
FF57 is now in beta - can we update the note at https://www.eff.org/https-everywhere ?

**Comment by Hainish** [comment]
Done!

**Comment by zero77** [comment]
@Hainish 
Can you please publish the beta to the Mozilla addons page alongside the stable one.
Thanks

**Comment by Hainish** [comment]
We don't currently have plans to publish the dev extension to the AMO page.  This may become deprecated once we've launched the full WebExtensions version, so publishing it on AMO would have adverse effects.  You can install it directly from EFF: https://www.eff.org/files/https-everywhere-test/https-everywhere-latest.xpi

**Comment by zero77** [comment]
@Hainish 
Ok, although meanwhile can you please put the link in a more visible place like the readme.
Thanks

**Comment by lilydjwg** [comment]
I notice that this webext version doesn't work for me for a long time (for site http://cfp.vim-cn.com/ ). The counter doesn't show, the rulers doesn't show in the popup menu.

The last time it worked was from September 9, and the first version it didn't work was from September 19, according to my backups.

Any ideas? Should I open a new issue for this?

**Comment by J0WI** [comment]
I was able to reproduce this. The pure Web Extension works in Firefox 56, but no longer on Nightly builds.
cc @Hainish

**Comment by Hainish** [comment]
@J0WI I'm unable to reproduce this.  Please try again?

**Comment by Hainish** [comment]
I'm testing in `57.0b9 (64-bit) Linux`, and it works for me.

**Comment by lilydjwg** [comment]
It works for me again now.

**Comment by Hainish** [comment]
Thanks - I'm going to close this for now.  Let me know if the problem reoccurs.
