### ISSUE TITLE
With WebExtension in Firefox Nightly "customize mode", HTTPS Everywhere icon's title says "(inactive)" which is misleading

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#11823]
STR:
 1. Start Firefox Nightly
 2. Install latest HTTPS Everywhere WebExtension from https://www.eff.org/files/https-everywhere-test/index.html
(I'm using https-everywhere-2017.7.21.1338-eff.xpi )
 3. Click the Firefox hamburger menu (top right of UI) and choose "Customize..."
 4. Drag the HTTPS Everywhere icon from your toolbar onto the overflow menu (directly below it)

ACTUAL RESULTS:
The HTTPS Everywhere entry in the overflow menu has this text "HTTPS Everywhere (inactive)" which gives the impression that the extension is inactive/disabled somehow. Screenshot:
![Screenshot](https://user-images.githubusercontent.com/426803/29231708-0a81f40c-7e9d-11e7-83b9-6531703e3544.png)

EXPECTED RESULTS:
The entry should just say "HTTPS Everywhere", probably.

**Comment by koops76** [comment]
Fix: #11824

**Comment by koops76** [comment]
@Hainish Since you closed #11824, you may as well close this.

**Comment by Hainish** [comment]
This is still an issue and should be fixed.  I wonder if there's a way to fix it without removing the status line altogether.
