### ISSUE TITLE
Add options in HTTPS Everywhere for Firefox Mobile

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1184]
There are no options in HTTPS Everywhere for Firefox Mobile, just enable / disable. It would be nice if I could edit the settings for EFF's SSL Observatory in Firefox Mobile and select what info will / won't be submitted to the SSL Observatory.

**Comment by jsha** [comment]
There is no SSL Observatory in Firefox Mobile. If we add it at some point, we will add corresponding options.
