### ISSUE TITLE
HTTPS-Everywhere breaks Lastpass 2FA

### ISSUE THREAD

**Issue by brad2014** [EFForg/https-everywhere#11853]
LastPass chrome extension, set to require password and Google Authenticator for 2FA, behaves improperly on browser startup when HTTPS-Everywhere is enabled. The user logs in with password and 2FA, indicating that the device should be trusted for 30 days.  On next login, the user is incorrectly asked to provide 2FA again (but not a password) in order to access LastPass.  

Environment:
- Mac OS: Version 10.12.6 (Sierra)
- Chrome: Version 60.0.3112.90 (Official Build) (64-bit)
- LastPass extension for chrome, Universal binary for mac: Version 4.1.61
- HTTPS Everywhere: Version 2017.7.18

To reproduce:
- Log in to LastPass (password and Google Authenticator)
- Assure, in LastPass preferences, that auto-logout is disabled
- Quit and restart chrome

Expected behavior:
- LastPass should simply remain logged in (address-bar logo should glow red)

Actual behavior:
- LastPass does not remain logged in
- LastPass opens a new tab, presenting a form to enter a Google Authenticator token
- Only after entering that token is LastPass logged in and operating

Note: It is odd for the user to be asked for *only* the GA token to enable LastPass.  Either the user is logged out of LastPass and should be asked for both a password and a token, or the user is logged in, and neither should be needed.

Workaround: disable the HTTP Everywhere extension.  (I couldn't figure out anything short of that).

**Comment by brad2014** [comment]
It doesn't seem to be related to a particular rule.  If the default.rules file contains 
- rulesets 1-6123 (00f.net.xml - Free_Porn_Gif.com.xml) it is not triggered, 
- rulesets 1-6124 (00f.net.xml - Free_Press.xml), then the bug *is* triggered,
- rulesets 6000-12124 (Fordela.com.xml - Orange.xml), then the bug is not triggered.

**Comment by pipboy96** [comment]
Requires LastPass account to verify, outdated. Closing.
