### ISSUE TITLE
Run securecookie normalization script

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11870]
@Hainish Please run this script: https://gist.github.com/koops76/14db6c6c1250eadc98644cff51e7add7.

I'm not making this a pull request because it changes 5354 files. Travis would probably explode. 😁

Please note that if ruleset whitelist cleanup is not run before running this script, it will throw errors on SHA256 mismatches.

After the script is run, merge #11872.

**Comment by koops76** [comment]
@Hainish Is `<securecookie host="^\w" />` functionally equivalent to `<securecookie host=".+" />`?

**Comment by cschanaj** [comment]
@koops76 AFAIK

```
<securecookie host=".+" name=".+" />
                                 ^
      this space does not necessarily exist, e.g. \s*? should be better 
```

**Comment by koops76** [comment]
@cschanaj Replaced `\s+` with `\s*`.

**Comment by cschanaj** [comment]
@koops76 please also note spaces before the `quote` and consider splitting the for each orders of `name` and `host`. thanks!!

**Comment by koops76** [comment]
@cschanaj Do you mean `host=     "something"` or similar?

**Comment by cschanaj** [comment]
exactly. you can insert `\s*` right before the quotes.

**Comment by koops76** [comment]
@cschanaj Added whitespace after `=` support.

**Comment by koops76** [comment]
@cschanaj Can you try separating the regexes? I am not as good at regexes. This one was the most complex regex I made I guess. 😁

**Comment by cschanaj** [comment]
ok. A minor issues, the regex you use might rewrite commented `securecookie` as well. do you mind if I fix that as well? e.g.

```xml
<!-- <securecookie ... /> -->
```

**Comment by koops76** [comment]
Yeah, of course, do it. BTW, this is why parsing XML or HTML by regex is often a bad idea. 😁

**Comment by cschanaj** [comment]
@koops76 please have a look

- https://regex101.com/r/3oZTwt/1
- https://regex101.com/r/lcjFy4/1
- https://regex101.com/r/i0YO7Z/1

Source
- https://gist.github.com/cschanaj/eb0de61c00389cfccb93cd78381a7b8e

P.S. I seldom do nodejs I guess this will work. (at least the regex :smile: )

**Comment by cschanaj** [comment]
Just updated to make sure `host` always go before `name`.

**Comment by koops76** [comment]
@cschanaj Why `/.*/g` instead of `/.*/gi`?

**Comment by koops76** [comment]
@cschanaj The first regex may match `<securecookie host="." name="." />`.

**Comment by cschanaj** [comment]
Thing like `SecureCookie`, `Host`, `NAME` should fails `rules-test`. The same hold true if `securecookie` has double `host` or `name` as specified in https://github.com/EFForg/https-everywhere/blob/master/utils/relaxng.xml#L49

**Comment by koops76** [comment]
@cschanaj Note that `/\^?\.\*?\$?/` does not match `.+`. This is important so the files already having `.+` for all `<securecookie>` attributes won't be changed.

**Comment by cschanaj** [comment]
@koops76 `<securecookie host=".+" name=".+" />` are matched by the 1st regular expression, but it won't be replaced (the replacement does not change anything). You may permute the combination of `.`, `.+` and `.*` to exclude (`.+`, `.+`). But they are just the same IMHO.

**Comment by koops76** [comment]
@cschanaj No, it would also replace things like `<securecookie host=".+" name=".+"/>` with `<securecookie host=".+" name=".+" />`, changing lots of files. If the changed file count is not increased too much by this, I may do it.

**Comment by cschanaj** [comment]
@koops76 Would you modify your script on GIST for Hainish to run it later?

**Comment by koops76** [comment]
Check it out. I modified it.

**Comment by cschanaj** [comment]
@koops76 not the same as https://gist.github.com/cschanaj/eb0de61c00389cfccb93cd78381a7b8e? the leading `\n([ \t]*)` and `\s*?\n` avoid commented `securecookie` to be rewritten, you shouldn't remove that. 

Besides, https://gist.github.com/koops76/14db6c6c1250eadc98644cff51e7add7#file-normalize-securecookie-js-L21 match `host=""`.

**Comment by koops76** [comment]
@cschanaj Done. I guess replacing commented `securecookie`s too is not a big issue.

**Comment by cschanaj** [comment]
@koops76 since you've said that you will be modifying the script, IMHO you can rewrite the files in-place. This will avoid unnecessary workload and possible human errors in the operations. 

Besides, it is also fine not to modify the whitelist with your script, since Hanish will have to whitelist the files anyway. A bonus of this is that you can reduce the program to a `sed` script. (optional)

**Comment by koops76** [comment]
@cschanaj It needs to be able to check if SHA256 matches.

**Comment by cschanaj** [comment]
@koops76 I just think that this change is a cosmetic one (related to #10378), so minimal works should be done on making a script. Please feel free to continue your work on the script in your preferred way. 


~[`normsc.sed`](https://gist.github.com/cschanaj/acac98472b76291944f5a59a8b0f1e4b) is a `sed` script I have made and it seems that only 200+ files need whitelisting from `rules-test`, see [`list-failed-rules-test.txt`](https://gist.github.com/cschanaj/31a06d4197020865787e075bdd8a44b4). (Since I have already made the script, I prefer to leave it here AS-IS).~

**Comment by koops76** [comment]
@cschanaj No, it's also an optimization. See #11872.

**Comment by gloomy-ghost** [comment]
I created a similar PR before, see #7892

**Comment by koops76** [comment]
@J0WI Since you have write access and you are the ruleset maintainer, maybe you'll run it?

**Comment by koops76** [comment]
#12302
