### ISSUE TITLE
A better ruleset whitelist cleanup script

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11909]
We need a better ruleset whitelist cleanup script. The current one misses many hash mismatches.

**Comment by cschanaj** [comment]
Can you give a few examples such that I can confirm this issue?

**Comment by koops76** [comment]
@cschanaj 
```
$ sha256sum Zorpia.xml
af97e7113b544ba216bad6feb8ca561b819df9e3ca9b330fee8cbb1310ccf585  Zorpia.xml

$ grep "Zorpia.xml" ruleset-whitelist.csv
6750e29d302751af08e3cbe82647eb8a652fba4be1efbed4bb63473ec6ed40c2,1,1,Zorpia.xml
```

**Comment by cschanaj** [comment]
@koops76 I've got

```bash
# make sure everything is sync with the master
$ git reset --hard origin/master

# compute sha256 hash
$ sha256sum Zorpia.xml 
6750e29d302751af08e3cbe82647eb8a652fba4be1efbed4bb63473ec6ed40c2  Zorpia.xml
```

and the script works as expected.

**Comment by koops76** [comment]
Oops. Closing. Tried downloading and hashing https://github.com/EFForg/https-everywhere/raw/master/src/chrome/content/rules/Zorpia.xml. It matches. I will rewrite this script in Node anyway.
