### ISSUE TITLE
Add rules

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#11930]
Please add rules for 
https://www.skandiamaklarna.se/
https://www.lansfast.se/
https://www.momondo.se/
https://www.momondo.fi/
https://www.momondo.no/
https://www.momondo.dk/
https://www.momondo.de/
https://www.momondo.co.uk/
https://www.momondo.com/
https://www.momondo.es/
https://www.momondo.fr/
https://www.momondo.nl/
https://www.momondo.pt/
https://www.momondo.ru/
https://www.supersavertravel.se/
https://www.supersavertravel.ae/
https://www.supersaver.co.at/
https://ca.supersaver.travel/
https://www.supersaver.ch/
https://www.supersaver.dk/
https://www.supersaver.es/
https://www.supersaver.fr/
https://www.supersaver.fi/
https://www.supersaver.ie/
https://www.supersaver.it/
https://www.supersaver.jp/
https://www.supersaver.nl/
https://www.supersaver.no/
https://www.supersaver.pl/
https://www.supersaver.ru/
https://www.supersavertravel.co.uk/
https://www.supersaver.travel/
https://www.supersavertravel.co.za/
https://www.jula.se/
https://fackforbunden.se/

**Comment by jeremyn** [comment]
I've transferred this list to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353650323` , and so I'm closing this issue.
