### ISSUE TITLE
2017.8.15 Only Works in Tor Browser Bundle 7.0.4 (FF 52.3.0) (32-bit) when Security Slider Set to "Low" on Startup

### ISSUE THREAD

**Issue by gopherit** [EFForg/https-everywhere#11944]
1.  Only works when TBB Security Slider set to Low (Default) on Startup.  If TBB is started with Security Slider set to Medium or High, HTTPS Everywhere will never work for that browser session.
2.  The UI works only when the Security Slider is set to Low.  When set to Medium or High, it blanks out.

![httpseverywhere_tbb_bug_2017-08-15](https://user-images.githubusercontent.com/25557897/29364414-51467a6c-8261-11e7-8b66-08ce43a46beb.png)

**Comment by jeremyn** [comment]
This is probably a duplicate of issue https://github.com/EFForg/https-everywhere/issues/11948, but we can leave this open to separately track the problem in Tor, unless @Hainish disagrees.

**Comment by Hainish** [comment]
This is most closely a dupe of https://trac.torproject.org/projects/tor/ticket/23258#comment:25 on Tor's issue tracker, and loosely a duplicate of https://github.com/EFForg/https-everywhere/issues/11948.  I don't think we need 3 open issues, so I'm closing.
