### ISSUE TITLE
Use the storage API rather than localStorage everywhere.

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#11962]
localStorage isn't reliably present, and gives security warnings when accessed while cookies are disabled.  It'd be better to use `storage` instead.

See https://github.com/EFForg/https-everywhere/issues/11948

**Comment by J0WI** [comment]
@Hainish are the referenced issues duplicates of this?
This issue seems quite important to me for webextensions.

**Comment by koops76** [comment]
@J0WI #12939 is.

**Comment by cowlicks** [comment]
@Hainish I'm editing the issue to make it non-ruleset specific, we should deprecate localStorage everywhere.

**Comment by koops76** [comment]
@cowlicks I could try doing that, but please review my PR without delays.

**Comment by Hainish** [comment]
@J0WI I don't think this fix is strictly required for the move to full WebExtensions.  However I've opened #13356 as a fix, which migrates all settings from localStorage.
