### ISSUE TITLE
Cannot download anything from NexusMods.com while on HTTPS

### ISSUE THREAD

**Issue by BeneathThePlass** [EFForg/https-everywhere#11970]
This just started happening withing the last couple days; anytime I try to download anything from www.nexusmods.com, I receive an error message. This has been verified on three computers; my laptop, my desktop, and my wife's desktop, with both Windows 10 and Windows 7.

![http everywhere nexusmods error](https://user-images.githubusercontent.com/31116667/29440029-bba4dd98-838f-11e7-8eac-9eba75c1486c.png)

**Comment by koops76** [comment]
Duplicate of #11953, already fixed, please close.

**Comment by jeremyn** [comment]
Closing as duplicate of #11953 .
