### ISSUE TITLE
Doesn't seem to rewrite asset URLs before Firefox blocks loading them

### ISSUE THREAD

**Issue by evaryont** [EFForg/https-everywhere#1197]
Hello! Not entirely sure if the description is 100% accurate. As an example:

Loading http://aerosol.github.io/anxibits/vim-as-your-erlang-ide/ with HTTPS-E's github.io rule enabled will properly redirect to the HTTPS version. However, the site with look broken as the style sheet has not been loaded due to mixed content blocking.

I think instead the assets should be loaded since they are all in http://*.github.io which have functioning rules. I don't know if there is a way to rewrite the URLs though before Firefox's MCB checking happens.

**Comment by jsha** [comment]
Which description are you finding inaccurate?

It used to be the case that HTTPS Everywhere could rewrite asset URLs to fix up mixed content, but when Firefox implemented Mixed Content Blocking, it wound up triggering before HTTPS Everywhere gets an opportunity to rewrite. We're waiting on Firefox to make some changes to allow us to fix up asset URLs again, but it's been a few years.

**Comment by evaryont** [comment]
That is exactly what I was attempting to say. Do you have a bug tracker link for Firefox for this?

**Comment by jsha** [comment]
I don't have the bug tracker link handy. @pde, do you have it?

**Comment by jsha** [comment]
Here's the link: https://bugzilla.mozilla.org/show_bug.cgi?id=878890
