### ISSUE TITLE
Custom rules in FF stoped working in 2017.8.15

### ISSUE THREAD

**Issue by sdmeyers** [EFForg/https-everywhere#11977]
Rules in my FF (Mac OS) profile `HTTPSEverywhereUserRules` directory no longer work with the latest updates.

**Comment by foobar13373** [comment]
But the shipped rules are working? Or is it not working at all? Then it could be this issue: #11948

**Comment by sdmeyers** [comment]
Shipped rules seem to work fine (at least I haven't encountered any issues with them). Only custom rules aren't working.

**Comment by anonvoy** [comment]
My (single) custom rule in FF stopped working too. I have HTTPS Everywhere 2017.8.17 installed, FF on Linux. JS is enabled, cookies are enabled, local storage is enabled. I haven't changed those settings for a while. I've disabled HTTPS Everywhere for now.

**Comment by Hainish** [comment]
Adding *new* rules to the `HTTPSEverywhereUserRules` directory will not work after the one-time migration in the Embedded WebExtension (>= 2017.8.15) is performed.  If you had old rules, they were migrated to the new extension.

To add new custom rules, you'll have to use the popup by visiting the https version of the site you want to add a rule for, clicking the extension icon, and clicking "Add a rule for this site".

If you're still experiencing issues let me know, I can't reproduce this.

**Comment by jeremyn** [comment]
@Hainish What can't you reproduce? It sounds like this is expected behavior given the discussion in https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-314901523 and elsewhere.

**Comment by sdmeyers** [comment]
Thanks @Hainish missed the new "Add a rule for this site" option. Everything works as expect now; however, my existing rule did not migrate, so if this was supposed to be a seamless upgrade, it wasn't.

**Comment by Hainish** [comment]
@jeremyn I can't reproduce the specific failure @sdmeyers mentions - the migration not actually working.

**Comment by Hainish** [comment]
@koops76 I have a queue, please do not comment on unrelated issues
