### ISSUE TITLE
Doesn't rewrite URLs with wildcard targets in Firefox (includes *.gfycat.com, *.github.io, *.imgur.com, *.shopify.com, *.media.tumblr.com)

### ISSUE THREAD

**Issue by ADAMPOKE111** [EFForg/https-everywhere#11981]
Accessing any image under the i.imgur.com subdomain through HTTP which is commonly hyperlinked on websites is not being redirected to the HTTPS variant for some odd reason despite the rule being present here: https://github.com/EFForg/https-everywhere/blob/a641125fc36c3a48a4cc4c33938fa369f397cfcc/src/chrome/content/rules/Imgur.xml

**Comment by Folant** [comment]
https://github.com/EFForg/https-everywhere/issues/11948#issuecomment-323160151
It seems to affect [gfycat](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Gfycat.com.xml#L8)(e.g zippy.gfycat.com), [media.tumblr.com](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Tumblr.xml#L44)(e.g 68.media.tumblr.com), [shopify ](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Shopify.xml#L44)(e.g http://cdn.shopify.com), [artlebedev.ru ](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Art_Lebedev.ru.xml#L39)(img.artlebedev.ru) and maybe many [all?] other rules containing `<target host="*.x.y" />`

**Comment by ADAMPOKE111** [comment]
Interesting, nothing was changed recently regarding the way URLs are interpretted as far as I can tell. I might have overlooked this or just not noticed the issue before. I can confirm it is happening on all my devices using HTTPS Everywhere.

**Comment by Folant** [comment]
>or just not noticed the issue before

Well, v5.2.21 seems to be working fine with these rules that contain wildcards, 2017.8.15/2017.8.17 is not [at least for some of us].

**Comment by ADAMPOKE111** [comment]
I think I'm going to take a look into this tomorrow and do some experimentation to see if I can remedy it. If anyone else has anything they'd like to contribute, feel free to chip-in.

**Comment by Folant** [comment]
#11980 has basically the same issue due to [Github-Pages.xml#L6](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Github-Pages.xml#L6) btw.

**Comment by jeremyn** [comment]
I agree with @Folant that wildcard targets aren't being rewritten, including both left wildcard targets such as http://www.imgur.com from [`Imgur.xml`](https://github.com/EFForg/https-everywhere/blob/a641125fc36c3a48a4cc4c33938fa369f397cfcc/src/chrome/content/rules/Imgur.xml#L32) and right wildcard targets such as http://google.com from [`Google.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Google.xml#L20).

@Hainish Please take a look at this.

**Comment by cschanaj** [comment]
@Hainish would you make a release of the 5.2.21 (with the rulesets files from 2017.8.17) with automatic updates disabled (to be shipped with the `tor-browser bundle` as a temporary solution for tor-users/ advanced users)?  For reasons being that 

- many `target`s using wildcards, especially the `left` wildcards are important domains 
- a large number of rulesets got re-activated after 5.2.21 is release, coverage improve greatly.

**Comment by Hainish** [comment]
a69918f3fb356c422edc4c83fac95aba054b44a2 fixes this issue.  I'll try to make a release tomorrow.

As for a special release for Tor Browser, I've already instructed them how to make a release using `5.2.21` removing the update channel and checking out the latest rules.  Tor Browser builds in HTTPS Everywhere as part of their release process from signed tags, so it's not a matter of me making a special release for them.
