### ISSUE TITLE
Firefox Style UI

### ISSUE THREAD

**Issue by ExE-Boss** [EFForg/https-everywhere#11983]
Since there is #11813 for Chrome, I request we do a similar thing for Firefox using the [Firefox Panel Components](https://firefoxux.github.io/StyleGuide/#/navigation) for the popup on Firefox, because [Material](https://material.io/) [Design](https://getmdl.io/) clashes with [Photon](http://design.firefox.com/photon/) and [Australis](http://firefoxux.github.io/StyleGuide/).

**Comment by pipboy96** [comment]
See #17068.

**Comment by pipboy96** [comment]
It seems we decided on using a custom style instead.
