### ISSUE TITLE
GIFV HTML5 videos blocked on imgur.com in Firefox

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1198]
GIFV's (imgur.com's HTML5 videos) such as on https://imgur.com/gallery/8yULscM and https://imgur.com/gallery/UPswQAB do not load except for a solid white rectangle.  They do load when the Imgur rule is disabled and "https" in the address bar is edited to "http".

**Comment by 2d1** [comment]
If this happens over https with the ruleset disabled, it's probably a problem on Imgur's side.

Given that Imgur is a popular site, it would be nice if it could be fixed rather than have the ruleset disabled. Have you tried contacting Imgur support/devs about this?

**Comment by cypherpunk** [comment]
Yes.  Immediately after posting this issue, I pasted the link to it in a support request on Imgur's help site ( https://help.imgur.com/hc/en-us/requests/new ).  On their help site, the most relevant entry I've found says, "you may want to disable add-ons/extensions." ( https://help.imgur.com/hc/en-us/articles/201569776-I-can-t-see-the-images- )  However, Imgur developers have visited Issue threads here before (#747).

**Comment by 2d1** [comment]
@BrynM could you take a look at this, please?

**Comment by cypherpunk** [comment]
As of the time of this reply and with Firefox 37.0.1 and HTTPS-Everywhere 5.0.2, the links in the original post do not work, but new .gifv pages do work.  These all work for me:
* https://imgur.com/gallery/QB3nwb8 (source is from youtube.com like the first two links.  Hover over the blue Play button under the titles.)
* https://imgur.com/gallery/aJ90csT (youtu.be)
* https://imgur.com/gallery/WOJtl3X (facebook.com)

**Comment by svnpenn** [comment]
@2d1 I have trouble with this as well. Consider this MP4:

~~~
$ wget --spider http://i.imgur.com/DlUP2ZS.mp4
HTTP request sent, awaiting response... 200 OK
Length: 248074 (242K) [video/mp4]
~~~

If you visit http://i.imgur.com/DlUP2ZS.mp4 in a browser, it redirects
to http://i.imgur.com/DlUP2ZS.gifv, fair enough. However if you look at the
source it is playing a GIF rather than a video.

**Comment by BrynM** [comment]
Man, I missed this way back. The original issue should be solved or at least we haven't heard reports of it for a long time. @svnpenn, we surface the original GIF if it's under 2M. http://i.imgur.com/DlUP2ZS.gifv is going just that, weighing in at 1.9M.

**Comment by semenko** [comment]
Closing per above comment.
