### ISSUE TITLE
Chrome: HTTPS Everywhere is incredibly slow

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#12]
[Chrome specific] 

I'll be sending a bunch of pull requests over the next few days. Just wanted to open a tracking bug.

HTTPS Everywhere takes an enormous amount of CPU time, which you can see from both the Task Manager and performance profiling in Chrome. The taskbar even on fast machines frequently shows "Waiting for extension HTTPS Everywhere …".

The current performance even makes HTTPS Everywhere borderline unusable on underpowered machines (e.g. some Chromebooks).

**Comment by gopi-ar** [comment]
Bump. Chrome on my brand new mac slowed down to a crawl (tabs opening, scrolling, etc), all because of this extension! Disabling it made it all good again!

**Comment by bdzs** [comment]
Yeah I know this is a closed issue but it slows down Chrome too much. Basically I had to disable it because loading sites and the overall performance of the browser was just too low.
