### ISSUE TITLE
Ruleset is shown as activated even when the request is blocked

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#12076]
STR:
1. Install uMatrix and block all 3rd parties.
2. Open https://zh.moegirl.org/Mainpage
3. Check activated rulesets

Expected:
No ruleset should be shown

Actual:
Ruleset for 3rd parties resources are shown
![default](https://user-images.githubusercontent.com/13086421/29653320-6c17c7ae-88fd-11e7-8b32-fdaee0c314fa.png)

Can be reproduced on both Chrome and Firefox

**Comment by jeremyn** [comment]
`https://github.com/Synzvato/decentraleyes/issues/148#issuecomment-285121088` might be interesting. It links to https://developer.chrome.com/extensions/webRequest , which under the section "Conflict Resolution" says:

> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

Here I guess both uMatrix and HTTPS Everywhere are modifying the request -- uMatrix by blocking, HTTPS Everywhere by rewriting -- and uMatrix's action is  "winning" but HTTPS Everywhere isn't notified so it still displays the relevant rulesets.

So in Chrome at least, it may not be possible to do what you want.

**Comment by numismatika** [comment]
I think this a bigger problem that should be adressed upstream at both browsers root.
If you have multiple addons interfering and listening to redirects you get a lot of wrong info.
If you have an Adblocker like UBO, HTTPS-Everywhere & SmartHTTPS, Info Addons like SixOrNot&Cert Patrol and a Privacy aware addon like Decentral Eyes, the state shown by these addons can become wrong rather fast. Not to mention irritating console errors and csp warnings.
You have blocked requests, rewritten requests and you want to also save the states of those requests before and after the interference so you can properly show info about them.

**Comment by pipboy96** [comment]
This is not possible to fix since HTTPS Everywhere can't know whether the request will be blocked by the others addons you have.
