### ISSUE TITLE
Use Firefox's translation strings in Chrome version

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1207]
Chrome mostly reuses strings from Firefox. We should remove the explicit messages.json and automatically generate it from the Firefox strings at build time, so we benefit from the Firefox localization.

**Comment by reedy** [comment]
:+1:

**Comment by reedy** [comment]
This falls somewhat under the purview of #1681

**Comment by jsha** [comment]
I've got a branch that fixes this (linked), but need to finish testing it.

**Comment by J0WI** [comment]
@jsha can we close this since #1351 is merged?

**Comment by jsha** [comment]
Yep, thanks!
