### ISSUE TITLE
FF: Dev Tools: HTTPS Everywhere Tab has black font even in the dark theme

### ISSUE THREAD

**Issue by mueller-ma** [EFForg/https-everywhere#12088]
I have FF 56.0b5 and the Theme "Compact Dark" (included in FF) enabled. The black font in the https everwhere tab in the developer tools with a dark background is not very good readable.

**Comment by koops76** [comment]
@mueller-ma Can you attach a screenshot?

**Comment by gloomy-ghost** [comment]
![default](https://user-images.githubusercontent.com/13086421/29741369-4402f48c-8abf-11e7-860c-998684b04690.png)

**Comment by koops76** [comment]
Can't reproduce on Firefox WebExtensions.

**Comment by mueller-ma** [comment]
Same in FF 54. I think this theme was introduced anywhere between 50 and 52.

**Comment by koops76** [comment]
@Hainish Close please, this issue only affects legacy (non-WebExtensions) versions of HTTPS Everywhere for Firefox.

**Comment by gloomy-ghost** [comment]
The background colour of dev panel is changed in https://bugzilla.mozilla.org/show_bug.cgi?id=1379995 which actually fixes a crash, we might need to wait Mozilla to confirm whether it is a regression or intentional change.

**Comment by koops76** [comment]
@gloomy-ghost I can't reproduce with WebExtensions version.

**Comment by gloomy-ghost** [comment]
@koops76 You can change the dev panel theme to dark at toolbox option

**Comment by gloomy-ghost** [comment]
The theme of devtools no longer sync with browser theme as of [bug 1389939](https://bugzilla.mozilla.org/show_bug.cgi?id=1389939). The STR should be changed accordingly, but the issue is still reproducible.

**Comment by koops76** [comment]
@gloomy-ghost I can't reproduce even with "Dark" theme.

**Comment by gloomy-ghost** [comment]
Not sure if I understand "can't reproduce" correctly, can you attach a screenshot?

**Comment by fedaj** [comment]
I am experiencing this issue as well. I have just installed the latest WebExtensions version (at least as reported on [the testing channel's page](https://www.eff.org/files/https-everywhere-test/index.html)) and restarted the browser, and the tab added to the dev tools looks exactly as in the screenshot in [a previous comment](https://github.com/EFForg/https-everywhere/issues/12088#issuecomment-325122935).

Another bug I noticed is that I cannot disable the tab - I don't use it much anyway, and dark on dark makes it unreadable, so I tried unchecking it on the dev tools' options. The tab goes away - until you close and reopen the dev tools, that is.

**Comment by physkets** [comment]
I too see this issue, also in the HTTPS Everywhere drop-down menu. I'm using Version: 2017.8.19

**Comment by mueller-ma** [comment]
@physkets Can you provide a screenshot of the dropdown menu?

**Comment by physkets** [comment]
https://imgur.com/a/lIHjA

**Comment by mueller-ma** [comment]
The dropdown menu in my FF has a white background

**Comment by physkets** [comment]
Yes, but I have a dark theme enabled in my DE. So when under such a theme, the text should gain a non-dark colour.

**Comment by Hainish** [comment]
@physkets good to know, thanks.

**Comment by rycee** [comment]
I'm also troubled by this issue. From what I can tell it is fixed in #12052 by adding a `background-color` to the popup CSS. But that PR seems not to be merged soon? Would it be possible to merge just the `background-color` commit from that PR so this issue could be resolved?

**Comment by Hainish** [comment]
@rycee I was going to spot-check #12052 one last time before merging, but it is hard to check branches out from @ghost (it is a dummy account that all deleted accounts are merged into), but you can still merge them via the Github UI.  But since I consider the state of the PR safe (I had previously checked it and commented that it looked good), I've gone ahead and merged this today.

**Comment by rycee** [comment]
@Hainish Thanks a lot!
