### ISSUE TITLE
Broken Fastly.net rule

### ISSUE THREAD

**Issue by johnbillion** [EFForg/https-everywhere#1208]
Example from http://perf-tooling.today which shows a broken logo in the header.

`http://www.perf-tooling.today.global.prod.fastly.net/perf-tooling.svg` is rewritten to `https`, but this domain serves a certificate which is only valid for `a.ssl.fastly.net` and therefore triggers an SSL warning.

**Comment by jsha** [comment]
Can you try installing the latest development version https://eff.org/https-everywhere#install-development and tell me if you still get the same error? We'll be releasing this version as the main version soon.

**Comment by johnbillion** [comment]
Tested `5.0development.3` in Firefox, and Fastly is showing up as an inactive rule, so I guess that means it's fixed. If I enable the rule, it breaks the image.

![screen shot 2015-03-19 at 01 05 05](https://cloud.githubusercontent.com/assets/208434/6722570/13312cb6-cdd4-11e4-8951-0e7150dc2148.png)

**Comment by jsha** [comment]
@binaryparadox could you take a look at this rule and see if there are parts that can be kept if we turn it back on?

Thanks,
Jacob

**Comment by 2d1** [comment]
Fixed by expanding exclusion from *.a.prod to *.prod in ba1e448f7f3d5d6079f24669d0afc4bf99689f68

**Comment by dmccarney** [comment]
@jsha I'll take a look today :)

**Comment by dmccarney** [comment]
@jsha - The rule change made in https://github.com/EFForg/https-everywhere/commit/ba1e448f7f3d5d6079f24669d0afc4bf99689f68 should be fine.

If ` <target host="*.fastssl.net" />` was us, its deprecated and could probably be dropped.
