### ISSUE TITLE
Icon does not update in Chrome transition, new tab -> extension options

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#12097]
### Expected Behavior
Icon should be inactive when viewing options page.

### To Reproduce

1. While running in Chrome, open a new tab.  The Google interstice page with square, recent site visits should appear.  The icon should show the bright blue `active`, since several Google rulesets are active.
2. Right-click the HTTPS Everywhere icon, then click "options"

### Observed Behavior

The icon is still bright blue, showing the Google active rulesets when clicking icons as well.  Only when reloading do these rulesets disappear and the icon becomes inactive.

**Comment by cowlicks** [comment]
@Hainish is the counter supposed to show up for firefox?

**Comment by pipboy96** [comment]
No longer applies due to replacement of light/dark icon with a counter.
