### ISSUE TITLE
Custom user rules not being applied after upgrade to 2017.8.19

### ISSUE THREAD

**Issue by mkjorling** [EFForg/https-everywhere#12090]
Firefox ESR 52.3.0 / 64-bit, Debian

I have two rule files in `HTTPSEverywhereUserRules` under my Firefox profile directory. Both name the hosts specifically; these are not wildcard rules. The files are named as `X.ruleset` where `X` is the base domain name (such as, not actually, `eff.org` rules being in `eff.org.ruleset`). Both rule files are essentially equivalent to the top example at https://www.eff.org/https-everywhere/rulesets:

    <ruleset name="RabbitMQ">
            <target host="rabbitmq.com" />
            <target host="www.rabbitmq.com" />
    
            <rule from="^http:"
                    to="https:" />
    </ruleset>

Before the upgrade to 2017.8.19, these rule files worked perfectly.

After the recent upgrade to 2017.8.19, these rule files appear to no longer be read or used. This appears to be the case regardless of whether Javascript is on or off, so I don't think it's related to #12009 or #11948.

Do I need to do something in particular to make these rule files work with the upgraded version?

It is beneficial to be able to actually test rule files locally before submitting them for inclusion (to make sure nothing obvious breaks), and there exists the possibility of wanting to use HTTPS Everywhere with internal hosts (in which case including the rules within the official version would at best cause bloat, and at worst could be at least information leakage).

If the recent upgrade changed how rule files should be written, please make sure to clearly update the documentation accordingly.

**Comment by jeremyn** [comment]
You linked to other issues so I assume you understand that HTTPS Everywhere is slowly migrating to the new WebExtensions way of making extensions.

The custom rules situation with WebExtensions is not as good as it used to be with XUL/XPCOM. Please take a look at https://github.com/EFForg/https-everywhere/issues/9958 and https://github.com/EFForg/https-everywhere/issues/10822, particularly https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-321452120, to understand the current status.

Please post here again if you have follow up questions or problems, otherwise please close this issue.

**Comment by mkjorling** [comment]
So current status is that it's not possible to store custom HTTPS Everywhere rules locally for testing before submitting, even though the documentation says nothing other than that it'll work just fine? If so then I repeat my request from the end of the initial post, please make sure that the documentation reflects the current state of the extension.

I did try using "Add a rule for this site" but that wasn't persisted, and as discussed in https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-323341274 it looks like there's no way to export such rules; even as a text/plain dump to a browser tab which could be saved or copied and pasted would be beneficial.

**Comment by jeremyn** [comment]
If the custom ruleset files were there before you upgraded from the XUL/XPCOM version of the extension to the current "embedded WebExtensions" approach, then the rulesets should have been imported during a one-off process from the files to an internal storage mechanism. If you added or modified the ruleset files after you upgraded the extension to an embedded WebExtensions version, then you need to modify the about:config setting described in https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-321452120 and restart the browser to re-run the import process.

I agree the documentation is out of date. However this is all a work-in-progress, with the current approach decided on about three weeks ago (https://github.com/EFForg/https-everywhere/pull/11639#issuecomment-320374803). The current approach is also just transitional until the full WebExtensions setup is released for Firefox 57, at which point the ruleset files won't be read at all. So I don't think documentation is a high priority at the moment.

**Comment by jeremyn** [comment]
Also,

> a text/plain dump to a browser tab which could be saved or copied and pasted would be beneficial

sounds like the suggestion in issue https://github.com/EFForg/https-everywhere/issues/11794. Please feel free to add your thoughts on this interface to that issue.

**Comment by draconx** [comment]
> If the custom ruleset files were there before you upgraded from the XUL/XPCOM version of the extension to the current "embedded WebExtensions" approach, then the rulesets should have been imported during a one-off process from the files to an internal storage mechanism.

This process doesn't seem to actually work.  With no documentation it's hard to know whether or not I did it correctly, but I have a large set of personal rules which I keep synchronized between multiple systems using git.

All of my rules simply stopped being applied after "upgrading" to 2017.08.31.  5.2.21 works fine.

**Comment by jeremyn** [comment]
@draconx Have you tried setting `extensions.https_everywhere.webextensions-migrated` to `false` as described in https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-321452120 to trigger a re-import of your custom rules?

**Comment by Hainish** [comment]
This should be solved in 66293af6e74ea90651da534943a984cc8aec3c49.  If not, please indicate and I can re-open.
