### ISSUE TITLE
Can't whitelist sites on Chrome

### ISSUE THREAD

**Issue by noflag** [EFForg/https-everywhere#1211]
Using tumblr shows a lot of broken images with https everywhere is activated. I don't see settings to disable it per-site.

**Comment by jsha** [comment]
When you click on the HTTPS Everywhere icon in the URL bar, does it give you a list of rulesets? You should be able to click one to disable it.

If the icon doesn't show up on the URL bar, some people have reported issues with unusual DPI or screen magnification causing the icon to disappear.

**Comment by noflag** [comment]
I don't have either of those, and don't have a toolbar button in Chrome. I'll try reinstalling.

**Comment by noflag** [comment]
Oh, I didn't realize it was in the URL bar, sorry. Seems to work now.
