### ISSUE TITLE
hsts-prune is still pointed to the discontinued Firefox Aurora release

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#12139]
The preload list for Firefox Aurora [hasn't been updated since April](https://hg.mozilla.org/releases/mozilla-aurora/log/tip/security/manager/ssl/nsSTSPreloadList.inc). We'll need to point hsts-prune to Firefox Nightly instead, and make changes to support the new format of `nsSTSPreloadList.inc`.

**Comment by koops76** [comment]
@bardiharborow Maybe you mean Firefox Developer Edition?

**Comment by bardiharborow** [comment]
@koops76 No. hsts-prune currently pulls the preload list from:
* Chrome Stable
* Firefox Aurora (to ensure that a domain is not in the process of attempting removal)
* Firefox Stable
* Firefox ESR (the branch behind Tor Browser)


Firefox Aurora was a channel between the nightly builds from mozilla-central (now called [Firefox Nightly](https://www.mozilla.org/en-US/firefox/nightly/all/)) and beta versions from mozilla-beta (now called [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/all/)). In April 2017, [Aurora support ended](https://hacks.mozilla.org/2017/04/simplifying-firefox-release-channels/). The preload list for Aurora has not been updated since April. I'm proposing that we replace the list with:

* Chrome Stable
* Chrome Canary/Chrome master branch
* Firefox Nightly/Firefox master branch
* Firefox Stable
* Firefox ESR

**Comment by jeremyn** [comment]
@bardiharborow I agree with your proposed new list. Note that [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/04b4e1df08543be683655c67652b8d337d61daf7/CONTRIBUTING.md#hsts-preloaded-rules) refers to the "Dev" version of Firefox, which is ambiguous. This file should be updated for clarity along with actually updating hsts-prune.
