### ISSUE TITLE
Trying to add new rule, get 500 error

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#12151]
I'm trying to alter this rule:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/torrentdownloads.me.xml
(https://github.com/EFForg/https-everywhere/edit/master/src/chrome/content/rules/torrentdownloads.me.xml)
to add:
```
    <target host="torrentdownloads.co" />
    <target host="www.torrentdownloads.co" />
```

But I keep getting a 500 error. I reported to Github, but in the meantime, can someone else try to make this edit?
Thanks.

**Comment by koops76** [comment]
#12152

**Comment by terrorist96** [comment]
Thanks!
