### ISSUE TITLE
Google ruleset no longer applies to google.co.uk and google.com.au

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1215]
I think this is due to the changes in #1063 and some confusion over how deep google.* matches (https://github.com/hiviah/https-everywhere-checker/issues/13).

**Comment by StevenRoddis** [comment]
hmmm

Would google.co.* and google.com.* work?

**Comment by jsha** [comment]
@StevenRoddis: They would. If you have time, could you revert a378c6bb3afc5bdd1311691a4638e980c33a0e2c to roll-forward your earlier Google changes? Then, before submitting fix this bug by adding google.co.* and google.com.* and any other wildcard targets that were removed: best to do a thorough review of all targets that changed. Also before we submit, we'll need to fix #1216, which I think is my bug, but if you have time to fix it I would be very grateful!
