### ISSUE TITLE
Search in HTTPS Everywhere atlas is broken

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#12175]
Performing a search on https://www.eff.org/https-everywhere/atlas/ has no apparent effect.

Behind the curtains, the first search attempt redirects to `https://www.eff.org/https-everywhere/atlas/?`.

- On Firefox, the trailing `?` is trimmed so the user is back to square 1.
- On Chromium, the trailing `?` is left intact and the second search attempt will work.

**Comment by cschanaj** [comment]
It seems that [`index.mustache#L27`](https://github.com/EFForg/https-everywhere-atlas/blob/master/templates/index.mustache#L27) failed to check that `split()[1]` is `undefined`. Moving the `toLowerCase()` insides the `if` statement should fix this. (I did not tested).

**Comment by cschanaj** [comment]
@Hainish @Bisaloo I've submitted a PR in EFForg/https-everywhere-atlas attempting to fix this. thanks.

**Comment by koops76** [comment]
I am currently making a replacement for current HTTPS Everywhere Atlas.
