### ISSUE TITLE
Chromium popup doesn't display long ruleset name completely

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#12181]
On Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.9 (64-bit). However, I cannot reproduce this using Firefox. thanks in advance,

![](https://i.imgur.com/1Rj0cMt.png)

**Comment by jeremyn** [comment]
I can confirm that the problem happens in Chrome and not in Firefox.

This isn't a direct solution but we should avoid super long, descriptive ruleset names. For this ruleset we can just change the `ruleset` `name` to `ust.hk`. If you want to do that, feel free to write a PR for it and tag me to review.

**Comment by J0WI** [comment]
I think this depends on your screen/resolution. I wasn't able to reproduce this here.
A solution would be to use `text-overflow: ellipsis` and a tooltip with line breaks.
