### ISSUE TITLE
Remove inactive collaborators

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#12199]
I'm removing @fuglede, @loveithateit, @reedy, @semenko, @RReverser from collaborators, since these maintainers have been inactive from HTTPS Everywhere for some time.

Thank you for all your contributions!  If you wish to continue work on HTTPS Everywhere, please reach out.

**Comment by Hainish** [comment]
Done.

**Comment by RReverser** [comment]
Nooooooo! 😄 

Thanks for reminding though, I'm just about to push another spring cleaning update.
