### ISSUE TITLE
"Block all HTTP requests" disregards HSTS

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1219]
Steps to reproduce:

1. Visit twitter.com.
2. In HTTPS Everywhere menu, disable Twitter rule (if it's not already disabled).
3. In HTTPS Everywhere menu, enable "Block all HTTPS requests."
4. Open a new tab with twitter.com.

Expected result:

Twitter's built-in HSTS preload sends the site to its HTTPS version and it load successfully.

Actual result:

The site is blocked by "Block all HTTP requests."

**Comment by diracdeltas** [comment]
Repro'ed, working on a fix.
