### ISSUE TITLE
Why are you using gmail address on your extenstion? 

### ISSUE THREAD

**Issue by woohooatb** [EFForg/https-everywhere#12198]
https://www.eff.org/files/https-everywhere-test/index.html

Is this link hacked? Don't you have your own domain email address?

**Comment by koops76** [comment]
Err, what?

**Comment by koops76** [comment]
See https://github.com/EFForg/https-everywhere/blob/master/chromium/manifest.json.

**Comment by gitarra** [comment]
Why does EFF use a Google email address?

**Comment by koops76** [comment]
@gitarra @woohooatb If you want to avoid using a Google email address, send emails to info@eff.org.

**Comment by gitarra** [comment]
I understand why someone might find that suspicious.

And that does seem weird considering how you strive to be "super secure" in other aspects.

**Comment by koops76** [comment]
@gitarra Not as much as they could have been: #12087.

**Comment by koops76** [comment]
@gitarra Likely EFF doesn't have a dedicated email account for HTTPS Everywhere.

**Comment by jeremyn** [comment]
In `about:addons`, the public, stable version of HTTPS Everywhere   has the author is "EFF Technologists". At https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/ , "Support E-mail" links to https-everywhere@eff.org.

The development version of the add-on from https://www.eff.org/files/https-everywhere-test/index.html has the author eff.software.projects@gmail.com. You can check this in [`manifest.json`](https://github.com/EFForg/https-everywhere/blob/8869efe875ac5c72535b72d9eb73e8553e6d6bf1/chromium/manifest.json#L8) in the `webextensions` branch.
