### ISSUE TITLE
Blocking non-encrypted traffic not working in ff nor chrome

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [EFForg/https-everywhere#12190]
Blocking non-encrypted traffic not working in ff nor chrome

see #11943

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
see also #10478

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
right, this is actually now a SECURITY ISSUE. for instance, you close your browser on a secure network, then move to another network that is hostile, open the saved browser and all your traffic and cookies potentially leak over HTTP without protection. same bug also confirmed in chrome version of extension

**Comment by jeremyn** [comment]
I'm closing this issue as a duplicate of #11943 since it was created simply by referencing the earlier issue.
