### ISSUE TITLE
Latest stable Firefox + Https everywhere, custom rules dissapearing?

### ISSUE THREAD

**Issue by jmfgdev** [EFForg/https-everywhere#12264]
I set a couple of custom rules for sites that arent forced over https by default in https everywhere, and today I noticed that the last rule I set seems to have unset all of its own.

My Firefox is 55.0.3
My Https Everwhere is 2017.8.19

**Comment by jeremyn** [comment]
Please see the discussion in issue https://github.com/EFForg/https-everywhere/issues/12090 and add your own comments if you like.
