### ISSUE TITLE
Fonts broken on slate.com

### ISSUE THREAD

**Issue by abbeyj** [EFForg/https-everywhere#1228]
I'm using Firefox 36.0.4 on Windows and HTTPS-Everywhere 5.0development.4.

The rule "CDN Slate.com (partial)" is breaking custom fonts on http://slate.com/ .  Go to that URL and note that the headlines are all in a serif font (Times New Roman?).  If you disable the rule, the headlines appear in the custom font "sl-Apres" as intended.

This seems to be a problem with MIME types.  For instance, http://static.cdnslate.com/etc/designs/slate/fonts/ApresRegular/c60bb3c2-10e5-4eee-a0d4-e0e221eca5c0-3.woff has "Content-Type: application/font-woff".  With the rule enabled, this URL is rewritten to https://a248.e.akamai.net/f/248/1/1/www.slate.com/etc/designs/slate/fonts/ApresRegular/c60bb3c2-10e5-4eee-a0d4-e0e221eca5c0-3.woff which has "Content-Type: text/html; charset=UTF-8", disallowing use as a font.

**Comment by jsha** [comment]
Thanks for reporting! I'll disable the rule.
