### ISSUE TITLE
fails to install addon for firefox 57

### ISSUE THREAD

**Issue by scottstensland** [EFForg/https-everywhere#12298]
now with firefox nightly version 57.0a1 (2017-08-31) (64-bit)   on ubuntu 17.04
https everywhere addon fails to install from

https://www.eff.org/https-everywhere

Getting popup window saying the addon not compatible with ff 57

on previous ff versions this addon installed/ran just fine 
as a long time user of https everywhere I thank you all

**Comment by J0WI** [comment]
Duplicate of https://github.com/EFForg/https-everywhere/issues/11805#issuecomment-325538887
