### ISSUE TITLE
Regexps matching invalid URLs

### ISSUE THREAD

**Issue by RReverser** [EFForg/https-everywhere#12296]
These rules were found as part of https://github.com/EFForg/https-everywhere/pull/12294 and can match strings that are in fact not absolute URLs.

* **MODX.xml**: `^http?://(?:pta|services)\.modx\.com/` matches `htt://pta.modx.com/*`, `htt://services.modx.com/*` which don't look like URLs

* **Newzbin.xml**: `^http://(?:www\.)?newzbin(?:\.com|2\.es)/?` matches `http://newzbin.com*` which don't look like URLs

**Comment by koops76** [comment]
😄 at `htt://`.

**Comment by Hainish** [comment]
Fixed in 55ff0fbacc5b55a166108765040c1b07436b18ef
