### ISSUE TITLE
Colour of the ruleset number next to the icon changes on icon move

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#12307]
Step to reproduce:

- ~~Turn on `Block all unencrypted requests`~~ (not needed as per #12308)
- The square displaying the number of active rulesets should be green
- Move around the icon in the bar / Click on the customize button
- The square displaying the number of active rulesets should be red (until the next page load)

**Comment by cschanaj** [comment]
See also #12308.

**Comment by Bisaloo** [comment]
Tracking upstream ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1368303
