### ISSUE TITLE
Restore counter to disabled by default

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#12325]
We [disabled the counter by default](https://github.com/EFForg/https-everywhere/pull/4100) in Feb 2016, mainly because it's not informative: It counts rulesets (rather than resources), which is a fairly arbitrary divide since some domain names have many rulesets that potentially apply. It also counts potentially applicable rulesets rather than actually applied rulesets, which means that the extension claims credit on sites it didn't modify at all. Also note that the question "is HTTPS Everywhere potentially active on this site" is independently shown by the icon state: light blue for no applicable rules, dark blue for applicable rules. Though I'll admit that's kinda subtle.

I think the best short-term fix is to go back to hiding by default. Long-term, I think the ideal stat to track would be the number of top-level page navigations upgraded. Since this number would get large over time, it would fit better under the menu than as a notification badge.

**Comment by koops76** [comment]
It's still an important indicator whether the extension rewrites requests or not. 👎

**Comment by koops76** [comment]
Maybe we should also count the requests, but then the counter numbers will be huge. Counting unique targets which were actually rewritten would be the best option in my opinion.

**Comment by koops76** [comment]
>Also note that the question "is HTTPS Everywhere potentially active on this site" is independently shown by the icon state: light blue for no applicable rules, dark blue for applicable rules. Though I'll admit that's kinda subtle.

No longer. It was removed recently.

**Comment by jsha** [comment]
> No longer. It was removed recently.

Ah, thanks for the update! Clearly I'm a bit out of touch. :-) Why was it removed?

**Comment by koops76** [comment]
@jsha Too confusing.

**Comment by cschanaj** [comment]
IMHO, It is also confusing with the "light blue icon" removed. That's why we will implement a counter anyway.

**Comment by cschanaj** [comment]
> mainly because it's not informative: It counts rulesets (rather than resources)

I agree, how many rulesets applied depend on how a contributor structured the rulesets. It might not be important to the normal user who never contributed to the ruleset base.

> Too confusing.

Actually, I like the "light blue icon" feature instead of "counter". Mainly because  _whether the extension rewrite something_ is a boolean information.

**Comment by koops76** [comment]
@cschanaj The icon changing color seemingly without reason from light to dark blue was uninformative and the counter is easier to figure out.

**Comment by cschanaj** [comment]
I am not sure about how others using the extension, but personally I focus more on the web content I am surfing rather than looking at the behavior of the extensions I have (unless I am a web developer).

**Comment by koops76** [comment]
@cschanaj The counter is already disableable, @Hainish didn't want to include the color option, so if you want a less distracting counter, ask @Hainish to reconsider his choice to not allow the user to change the counter's color to a less distracting one if it is distracting for them.

**Comment by cschanaj** [comment]
I prefer to have the user to disable the counter manually in such case. As you might know, I am also against configurable color.

P.S. I wish the button to disable the counter can be more visible from the popup UI.

**Comment by koops76** [comment]
@cschanaj Why are you against giving the user more freedom?

**Comment by cschanaj** [comment]
because we might run into a dilemma when the _user_ demand a different "font color", "popup background color" even a different "default icon color". I would like to avoid the potential maintenance overheat.

**Comment by koops76** [comment]
@cschanaj Font color: impossible in WebExtensions
Popup background color: why?
Default icon color: WTF?

**Comment by foobar13373** [comment]
For me, the counter checbox has the same problem like the block-unencrypted checkbox before:

The checkbox state ist saved between browser sessions, but the actualy functionality is reset. If I disable the counter and restart the browser, the checkbox stays disabled, but the counter is there again.

Cookies disabled (whitelisting via FF per-page settings) and JS disabled via uBlock origin (whitelisting via uBO).

**Comment by koops76** [comment]
@foobar13373 Need to investigate, this should be fixed already. What's your extension's version?

**Comment by foobar13373** [comment]
@koops76 
2017.8.13 - the block unencrypted checkbox is working between browser sessions, but the counter functionality is reset each time (while the checkbox state is saved correctly).

**Comment by koops76** [comment]
@foobar13373 Update to 2017.8.31.

**Comment by bardiharborow** [comment]
While it may or may not serve as an important indicator, it's not a component that needs to be actively drawing user attention. Extension badges are dark grey by default, and there's no compelling reason for an extension to deviate from that unless it's attempting to indicate an abnormal condition, or something else that otherwise deserves user attention.

I found the green color quite distracting initially as I kept thinking there was some sort of notification. While I've now mostly zoned it out, I find it poor UI design. I'm happy to keep the counter if we can change the color back to dark grey.

**Comment by foobar13373** [comment]
@koops76 
Sorry, was a typo 13 -> 31 - I already have 2007.8.31

**Comment by patheticcockroach** [comment]
I have version 2017.09.12 (in Firefox 55.0.3) and I have the same problem as foobar13373: even though the counter is "disabled" according to the add-on's settings, it still show up, which is pretty distracting...

**Comment by koops76** [comment]
@patheticcockroach If it's Firefox specific, please file a bug in Mozilla bug tracker instead.

**Comment by patheticcockroach** [comment]
Hm, what do you mean the Mozilla bug tracker? Isn't that a place for Firefox's bugs and not extension bugs? (or is there a place there just for HTTPS Everywhere? I can't seem to find it :s)

**Comment by koops76** [comment]
It's likely an issue with Firefox's implementation of WebExtensions.

**Comment by patheticcockroach** [comment]
Ok, it's created there: https://bugzilla.mozilla.org/show_bug.cgi?id=1402223

**Comment by patheticcockroach** [comment]
They already closed it: "Please report the issue to the extension author" :s

**Comment by patheticcockroach** [comment]
Update on my issue: I found out that it doesn't occur in one of my (rarely used) Fx profiles. Trying to figure out what's making the difference... I already tried disabling all other extensions, so it doesn't seem to be an add-on conflict

**Comment by pipboy96** [comment]
>Since this number would get large over time, it would fit better under the menu than as a notification badge.

Related: https://github.com/EFForg/https-everywhere/issues/17068

**Comment by pipboy96** [comment]
Closed as part of UI rewrite.
