### ISSUE TITLE
https everywhere prevents downloading mods on http://www.nexusmods.com

### ISSUE THREAD

**Issue by demonicgoat** [EFForg/https-everywhere#12324]

**Comment by Bisaloo** [comment]
Duplicate of https://github.com/EFForg/https-everywhere/issues/11953 and https://github.com/EFForg/https-everywhere/issues/11970.

It's being worked on in https://github.com/EFForg/https-everywhere/pull/11961.

**Comment by gloomy-ghost** [comment]
Close as duplicate
