### ISSUE TITLE
WebExtension status to AMO page

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/https-everywhere#12330]
The [AMO](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) page will place this tag once the add-on is a WebExtension:

> Compatible with Firefox 57+

Until then people will continue to ask for the WebExtension status in their AMO Reviews for this add-on, so can you please state on the AMO page if it is:
* not a hybrid WebExtension.
* a [hybrid WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions).

Also, please mention if the current WebExtension API is to restricted for this add-on to become a full WebExtension.

**Comment by koops76** [comment]
@davidhedlund Currently it is hybrid.

**Comment by koops76** [comment]
ping @Hainish.

**Comment by davidhedlund** [comment]
@koops76 I'm glad to hear that. Can you add it to https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/ ?

**Comment by koops76** [comment]
@davidhedlund No, only @Hainish can.

**Comment by davidhedlund** [comment]
@koops76 Ok, thank you for pinging him then.

**Comment by davidhedlund** [comment]
@koops76 

An add-on is a hybrid WE if it has a "hasEmbeddedWebExtension" key available in the install.rdf.

I didn't know that was the standard procedure when I asked, sorry. However, I found it in the add-on.

**Comment by Hainish** [comment]
@davidabian thanks, I just added a note https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

**Comment by davidhedlund** [comment]
@Hainish Thank you.
