### ISSUE TITLE
Credentials in URL are not Restored

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#12377]
## Step to reproduce

1. Visit http://user:password@example.com:403/path with "Block all unencrypted connection"

2. Expect URL should be rewrote to https://user:password@example.com:403/path

3. Actual URL is https://null:null@example.com:403/path

## Reason

Seemingly wrong scoping in [`chromium/background.js#L323`](https://github.com/EFForg/https-everywhere/blob/master/chromium/background.js#L323)

**Comment by koops76** [comment]
@cschanaj Try with #12380.
