### ISSUE TITLE
Unblocking feedly.com in HTTPSEverywhere  

### ISSUE THREAD

**Issue by jbionic2016** [EFForg/https-everywhere#12411]
![feedly](https://user-images.githubusercontent.com/23212486/29998453-f7a60cc6-9033-11e7-80aa-408628cc93af.jpg)
Attached is the screenshot taken in Chrome (64-bit for Windows 10 Home) when attempting to connect to feedly.com

I dont have Adblock, but do have  HTTPSEverywhere  plugin enabled, which probably causes the disruption. 

The other thing that I noticed in the recent past is that I often lose  the secure connection while browsing my RSS links on feedly.com.

**Comment by koops76** [comment]
@jbionic2016 Can't reproduce.

**Comment by jbionic2016** [comment]
Me neither. By some reason the disruption has ended, so I can connect to feedly. Thanks. We may close the issue.

**Comment by bardiharborow** [comment]
I can not reproduce the disruption either. The domain is however serving mixed content (in my case from `lh3.googleusercontent.com`, but it may vary based on what content is displayed). HTTP-Everywhere is rewriting it, but not before it triggers a security UI downgrade (this is not something we are able to fix).

**Comment by jbionic2016** [comment]
Crystal. Thanks. Btw just for reference, what is the way to whitelist any particular domain in HTTPSEverywhere, so that it doesn't apply its rules to this domain?

**Comment by bardiharborow** [comment]
@jbionic2016 there's no way to whitelist sites from having any action taken on them, but you can disable the relevant ruleset.

**Comment by gloomy-ghost** [comment]
> What is the way to whitelist any particular domain in HTTPSEverywhere

Currently you have to disable all relevant rulesets, but it's on the wishlist: #10041. If there is any specific ruleset issues, we always encourage you to report it using the issue tracker so that other volunteers may be interested to fix it.
