### ISSUE TITLE
Badge counter is the same on all windows in Firefox 55

### ISSUE THREAD

**Issue by wavexx** [EFForg/https-everywhere#12449]
FF 55 with webextension 2017.8.31.

I noticed that when having two FF windows open side-by-side, the ruleset counter shown in the toolbar icon is identical on both, and reflects the count of the current focused window/tab, *not* of the actual tab shown in the window.

To reproduce: open two FF windows, side by side. Visit "about:" on the left, and "github.com" on the right. Notice how the counter shows the count for the focused window (simply select the other window to see the counter change on both).

**Comment by koops76** [comment]
`about:` won't work, try some different URL.

**Comment by cschanaj** [comment]
I can confirm this issues on Firefox ESR from debian platform. The counter on the badge on different windows always show the same value.

**Comment by koops76** [comment]
@cschanaj The number is global, it can't be shown only for one window.

**Comment by koops76** [comment]
Let's do that for each window then.
