### ISSUE TITLE
Hire more ruleset maintainers

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12448]
There are 700 pull requests right now and with a limited number of ruleset maintainers it would be difficult to eat and review them all

**Comment by jeremyn** [comment]
Ruleset maintainers are unpaid volunteers. See the third paragraph of [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/04b4e1df08543be683655c67652b8d337d61daf7/CONTRIBUTING.md) for information on becoming a ruleset maintainer.
