### ISSUE TITLE
Keyserver list (#11995)

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12455]
| Done | Domain | Alexa rank |
|:-:|---|--:|
|   | keyserver.leg.uct.ac.za | 7297 |
|   | pgp-srv.deib.polimi.it | 9970 |
| ✔️ | vm-keyserver.spline.inf.fu-berlin.de | 10596 |
|   | pgp.lehigh.edu | 24291 |
| ✔️ | pgp.uni-mainz.de | 25523 |
|   | gozer.rediris.es | 67647 |
|   | zuul.rediris.es | 67647 |
| ✔️ | keyserver.stack.nl | 88056 |
| ✔️ | sks.labs.nic.cz | 94848 |
|   | keyserver.uz.sns.it | 130954 |
|   | sks.ustclug.org | 180618 |
|   | gpg.nebrwesleyan.edu | 297879 |
| ✔️ | zimmermann.mayfirst.org | 393941 |
|   | sks.es.net | 404755 |
|   | keys.niif.hu | 405149 |
|   | keyserver.syseleven.de | 417613 |
|   | pgp.skewed.de | 432103 |
|   | keyserver.shadowserver.org | 608628 |
|   | agora.cenditel.gob.ve | 758519 |
| ✔️ | vanunu.calyxinstitute.org | 1173981 |
|   | keyserver.nausch.org | 1247018 |
|   | keyserver.escomposlinux.org | 1404794 |
|   | pgp.surfnet.nl | 1646645 |
|   | sks.stsisp.ro | 1899362 |
|   | keyserver.pch.net | 2128094 |
| ✔️ | keys.void.gr | 2158560 |
|   | keyserver.mattrude.com | 2523780 |
|   | ams.sks.heypete.com | 2551476 |
|   | keyserver.zap.org.au | 2744832 |
|   | pgp.gwolf.org | 3086172 |
|   | keys.klaus-uwe.me | 3104351 |
|   | keys.loli.forsale | 3948355 |
|   | gpg.n1zyy.com | 4036125 |
|   | keys.internet-sicherheit.de | 4718651 |
|   | pgpkeys.urown.net | 4881461 |
|   | keys.andreas-puls.de | 4983562 |
|   | keyserver.paulfurley.com | 5444318 |
|   | pgp.archreactor.org | 5558387 |
|   | keys.itunix.eu | 5991663 |
|   | klucze.achjoj.info | 6905526 |
|   | pgp.uplinklabs.net | 7375544 |
|   | keyserver.wetnet.net | 7479207 |
|   | schluesselkasten.wertarbyte.de | 8574570 |
|   | keyserver.metalgamer.eu | 11392021 |
|   | a.keyserver.pki.scientia.net | 12635777 |
|   | a.keyserver.alteholz.eu | 13529090 |
|   | keyserver.siccegge.de | 13904389 |
|   | keyserver.c3l.lu | 15984142 |
|   | sks.mbk-lab.ru | 16723802 |
|   | keyserver1.gnupg.pub | 17491900 |
|   | keyserver.kolosowscy.pl | 17617432 |
|   | gpg.phillymesh.net | null |
|   | keys.fspproductions.biz | null |
|   | keyserver.secure-u.de | null |
|   | keyserver.deuxpi.ca | null |
|   | key.adeti.org | null |
|   | keyserver.sincer.us | null |
|   | keyserver.boquet.org | null |
|   | keyserver.swabian.net | null |
|   | keyserver.blupill.com | null |
|   | keyserver.timlukas.de | null |
|   | keyserv.sr32.net | null |
|   | keyserver.vbrandl.net | null |
|   | keyserver.vsund.de | null |
|   | keys2.kfwebs.net | null |
|   | keys2.flanga.io | null |
|   | keyserver1.computer42.org | null |
|   | keyserver.miniskipper.at | null |
|   | keyserver2.boquet.org | null |
|   | keyserver2.computer42.org | null |
|   | key.bbs4.us | null |
|   | keys.stueve.us | null |
|   | keys.sflc.info | null |
|   | keys.schluesselbruecke.de | null |
|   | key1.dock23.de | null |
|   | keys.nerds.lu | null |
|   | key2.dock23.de | null |
|   | keys.jhcloos.com | null |
|   | keyserver.searchy.nl | null |
|   | keys.flanga.io | null |
|   | keys.drup.no | null |
|   | keys-02.licoho.de | null |
|   | keys.communityrack.org | null |
|   | keys.digitalis.org | null |
|   | keys.connectical.com | null |
|   | pgpkeys.mallos.nl | null |
|   | pgpkeys.co.uk | null |
|   | pgp.h-ix.net | null |
|   | pgp.net.nz | null |
|   | sks.okoyono.de | null |
|   | sks.fidocon.de | null |
|   | sks.funkymonkey.org | null |
|   | sks.karotte.org | null |
|   | sks.bootc.eu | null |
|   | sks.daylightpirates.org | null |
|   | sks.mj2.uk | null |
|   | sks.neel.ch | null |
|   | sks.bonus-communis.eu | null |
|   | sks.openpgp-keyserver.de | null |
|   | sks.rarc.net | null |
|   | sks.spodhuis.org | null |
|   | sks.undergrid.net | null |
|   | sks.b4ckbone.de | null |
|   | whippet.andrewg.com | null |
|   | a.keys.wolfined.com | null |
|   | keyserver.oeg.com.au | null |
|   | keys2.alderwick.co.uk | null |
|   | keyserver.brian.minton.name | null |
|   | keyserver.saol.no-ip.com | null |
|   | sks.srv.dumain.com | null |

[Node.js script](https://gist.github.com/koops76/62d8f896e34185fb8d1b57e8a75d43f0).

**Comment by pipboy96** [comment]
Link to script is dead, list is outdated.
