### ISSUE TITLE
Add alldebrid.com

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1247]
Add https://www.alldebrid.com/ as a ruleset.

**Comment by jsha** [comment]
We don't have the resources to write rulesets upon request, sorry.

**Comment by cypherpunk** [comment]
Ok, but didn't you do that with httpbin.org though?

**Comment by jsha** [comment]
It looks like one of our contributors, @2d1, wrote the httpbin ruleset. If this is a request for another contributor to write a ruleset for a given site, I'm fine with that. Apologies if I came across a bit brusque - it's been a busy week. :-)

**Comment by cypherpunk** [comment]
Anyone who  wants to write these rulesets is fine by me, I'm not picky. These sites aren't exactly highly visited websites either, so I don't mind if they are put on the backburner until someone has time to look at them. Could you reopen this issue and #1248?
