### ISSUE TITLE
Dark Theme support

### ISSUE THREAD

**Issue by typhoon71** [EFForg/https-everywhere#12484]
Using ta dark theme (in ffox or the OS itself) makes this addon on click menu in the unreadable: can something be done about this? 
Thanks.

**Comment by cowlicks** [comment]
Can you share which theme you are using and which version of FF? It looks ok to me with FF 56 and this theme https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/?src=search

**Comment by typhoon71** [comment]
Firefox 55.0.3, TTDeepdark latest.
The theme is a complete theme, but the issue with the menu appears in https averywhere only.
I'd be really happy id it get fixed... In case this addon doesn't die later this year with ffox 57.
It's already being flagged as "obsolete" on ffox 55, so I guess devs aren't that thrilled.

**Comment by Octav14n** [comment]
I have a dark UI theme on Ubuntu (installing the above suggested Firefox-theme would be easier)
I have installed the latest WebExtension version of HTTPS-Everywhere and have the same issue.

**Comment by Carm01** [comment]
FT Deepdark causes issues with me as well, cannot see anything 14.4.5

**Comment by typhoon71** [comment]
I'd like to point out that the problem isn't really on TTDeepdark, but more on what element is used by HTTPS-Everywhere addon to "draw" text the menu.
As you can see in the attacched images, both noscript and firefox menu play nicely with custom themes, while HTTPS-Everywhere doesn't.

**noscript**
![immagine](https://user-images.githubusercontent.com/1866248/30774605-912e4136-a085-11e7-99d3-3ccbc8b46e6f.png)

**firefox menu**
![immagine](https://user-images.githubusercontent.com/1866248/30774615-abd0687a-a085-11e7-9557-98714174ac62.png)

**HTTPS-Everywhere** 
![immagine](https://user-images.githubusercontent.com/1866248/30774616-bfd11d60-a085-11e7-814a-3c86ba2f7b5a.png)

**Comment by JPRuehmann** [comment]
I have the same Problem.
Whill be a Fix in the near Future?
Thanks

**Comment by rugk** [comment]
Actually, with Firefox 67 and above, all this will be possible with https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme.

And maybe you are in the soon future "_forced_" to add a dark theme for your options page, at least. See https://github.com/EFForg/https-everywhere/issues/17841 for details.

**Comment by pipboy96** [comment]
I will release a PR for this issue soon.

**Comment by pipboy96** [comment]
Closing until dark mode add-ons page will be available at least in Beta or Developer Edition version, hopefully this will be fixed upstream. Also, by default even if you select Dark theme, dark add-on page and dark versions of other pages won't be enabled unless you enable dark mode in your OS or set `ui.systemUsesDarkTheme` to `1`.
