### ISSUE TITLE
Question about rulesets

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1249]
If a site is in https by default, should it still be added as a ruleset?

**Comment by jsha** [comment]
If the site has HSTS and the cookies are all marked secure: no.

Otherwise: yes, but lower priority to implement than sites that don't use HTTPS by default.

**Comment by cypherpunk** [comment]
Should I report sites that have https, but don't load cookies until the user have logged in and the cookies are therefore unchecked?
