### ISSUE TITLE
Make a subdomain finder bot available to PR submitters to help them cover all subdomains?

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12502]
This would be based on the Sublist3er.py script, and it would work by commenting beneath one's own PR "findallsub example.com" or something like that.

It should also have rate limiting so that it doesn't get blocked from making search queries.

The reason is that for cases like me where I don't have a Linux laptop sitting near me (I mostly use Windows 10) I always use the Google iterative method, but this manual process consumes a lot of time and is inefficient for sites that have 100+ subdomains.

If this gets implemented it will definitely make PRs easier to do for me and others.

**Comment by jeremyn** [comment]
Sublist3r should work on Windows, for example its [`README.md`](https://github.com/aboul3la/Sublist3r/blob/8754fd66a734cc39e5b775dad1581f2852ec9904/README.md) has instructions for installing dependencies in Windows.

You could also use Sublist3r in a Linux virtual machine on Windows, for example see my own https://github.com/jeremyn/https-everywhere-dev-environment.
