### ISSUE TITLE
Site broken, even when unchecked. 404 error

### ISSUE THREAD

**Issue by faustmn** [EFForg/https-everywhere#1250]
First, I am simply a user, not a coder, but I find no other support forums, so I am posting my issue here. Using Chrome for Mac, HTTPS everywhere has "broken" mlssoccer.com. Despite unchecking the site from the https everywhere menu, every time I try to load it, I get the red, crossed out "https" in the URL bar and a 404 code. I have found no way to remedy this. Please advise.

**Comment by jsha** [comment]
We don't have a ruleset for mlsoccer.com: https://www.eff.org/https-everywhere/atlas/letters/m.html

Perhaps you have another extension installed that could be interfering?

**Comment by faustmn** [comment]
Thank you for the reply. It's the only site I have had an issue with. Had
been fine for many months, no new extensions installed.
Maybe best to delete httpse and reinstall

**Comment by jsha** [comment]
It's possible you accidentally added a personal rule for mlsoccer.com using "Add this site." There was a longstanding bug that allowed creation of such rules on non-HTTPS sites and prevented disabling them.

If you update to the latest version, that bug should be fixed as of today.

**Comment by faustmn** [comment]
Thank you
