### ISSUE TITLE
CBS.xml and CBSNews.xml have conflicting rules

### ISSUE THREAD

**Issue by RReverser** [EFForg/https-everywhere#12526]
CBSNews.xml added in https://github.com/EFForg/https-everywhere/pull/11933 seems to conflict with CBS.xml which has:

```xml
	<rule from="^http://markets\.cbsnews\.com/$"
		to="https://markets.financialcontent.com/cbsnews" />

	<rule from="^http://markets\.cbsnews\.com/"
		to="https://markets.financialcontent.com/" />
```

As far as I can tell, CBS.xml's rewrite rules are incorrect in this case, and CBSNews' `markets.cbsnews.com` should always take effect.

(also, seems like a good idea to somehow auto-test that different rulesets don't match same URLs)

**Comment by Bisaloo** [comment]
> (also, seems like a good idea to somehow auto-test that different rulesets don't match same URLs)

+1

`encrypted.google.com` had a similar issue (#12544)
