### ISSUE TITLE
Consider support for container based preferences

### ISSUE THREAD

**Issue by jonathanKingston** [EFForg/https-everywhere#12532]
Instead of a site by site exemption list now you have a web extension you could provide users with a container-by-container setting like the following demo I made:

https://github.com/jonathanKingston/extension-debugging/tree/master/containers-https

This shows off the latest changes we have made in container APIs and there are more to come like making this API an [optional setting](https://bugzilla.mozilla.org/show_bug.cgi?id=1386673) which would potentially allow you to make this a optional upgrade without making all your users forced to get the containers changes (57 now enables containers if you include the APIs).

We (the containers team) think using containers like this really reinforces both extension and containers for the user at the same time, for example allowing users to use the "HTTP Nowhere" setting in Shopping, Banking environments but the allow list when using social perhaps.

**Comment by jeremyn** [comment]
@Hainish FYI ^

**Comment by koops76** [comment]
May be too complicated for everybody's use, let's move this into some sort of power user mode.

**Comment by jeremyn** [comment]
@koops76 I agree this isn't something I would use or that I want shown to ordinary users by default. Also if Chrome doesn't have an identical mechanism then this would introduce unnecessary (?) Firefox-specific stuff into the codebase.

**Comment by Bisaloo** [comment]
In [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/), another webextension that supports containers, the checkbox to enable container support is visible only if the user is [already using containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).

**Comment by jonathanKingston** [comment]
@Bisaloo that won't be true soon, the changes I made to 57 will install containers. Which is why I added the comment about it might be worth waiting for the ability for the optional check where you could hide it behind a checkbox or something.

The ability to progressively enhance should still be possible with:
```
if (browser && "contextualIdentities" in browser) {
```
(I'm not sure how Chrome handles permissions in the manifest - **I will check** - that it doesn't understand though, which is why we are pushing for the optional setting instead).

> May be too complicated for everybody's use

This is far less complex than per site regex that the extension supports, once the user sets up the rules per container it would actually be very usable with these defaults.

**Comment by Hainish** [comment]
@jonathanKingston is Firefox still deploying this feature?  I haven't heard much news on this front, just wondering if it's something worth pursuing.

Thanks!

**Comment by pipboy96** [comment]
This feature still exists, but this seems to be something not worth developing, since there's no apparent use case and it's possible for users to create another profile without HTTPS Everywhere installed.
