### ISSUE TITLE
Chrome version breaks Linguee

### ISSUE THREAD

**Issue by clementhervy** [EFForg/https-everywhere#12547]
I have only visited linguee.fr and can't attest to it not breaking the other regional versions. HTTPS Everywhere seems to be blocking the site's CSS.

**Comment by Bisaloo** [comment]
I can't reproduce this issue. Can you provide more info please?

**Comment by clementhervy** [comment]
I updated Chrome and the problem went away, but I'll still give some more info, just in case.

In the console of the Chrome developers tools, with the "Linguee" rule enabled, the css files had an ERR_INSECURE_RESPONSE error and therefore not loaded, which broke the site's appearance. With the "Linguee" rule disabled the files loaded properly.

**Comment by Bisaloo** [comment]
Hum, that's weird. Glad to hear it's fixed! I will keep an eye out for this domain/rule.

**Comment by koops76** [comment]
It's an either MCB or CORS issue.

**Comment by jeremyn** [comment]
Closed since this problem has resolved itself.
