### ISSUE TITLE
Custom rules not saved

### ISSUE THREAD

**Issue by mazesy** [EFForg/https-everywhere#12545]
https-everywhere-2017.9.12-eff / Waterfox 55.0.2 / Windows 7

Custom rules are not saved. By the way I'd love to know where in the user's Firefox profile they are stored.

A created custom rule works here within the Firefox session. I only need to restart Firefox to have it vanished. I've had this problem ever since HTTPS-everywhere was transmuted to a Webextension. I'm focusing on this custom rules saving, other issues for another thread.

I cannot use HTTPS-everywhere as I have for years before Mozilla's eccentricities decided to move on to Webextensions. No more HTTPS-everywhere here unless the devs would allow downloading the updated rulesets independently of the add-on's format (add-on or Webextension) in which case I would carry on with HTTPS-everywhere Version 5.2.21 and update only the rulesets. Otherwise, over. Thanks who? Mozilla and its incompetent devs.

**Comment by jeremyn** [comment]
Custom rules are handled a lot differently in Firefox using WebExtensions vs the older XUL/XPCOM approach. For your specific questions of "where are custom rules stored?", you might find the discussion at https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-314807671 and following to be relevant. See also issues https://github.com/EFForg/https-everywhere/issues/10822 and https://github.com/EFForg/https-everywhere/issues/12090.

I'm closing this issue as a duplicate but if you are encountering specific new problems with custom rules, I encourage you to describe these problems in detail in one of the issues I linked above, probably https://github.com/EFForg/https-everywhere/issues/10822.
