### ISSUE TITLE
Add selenium tests.

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#12561]
See `test/README.md` for reference.

**Comment by koops76** [comment]
Isn't the currently recommended way to do in-browser testing is to use headless Chrome?

**Comment by cowlicks** [comment]
@koops76 that is one way. I prefer to use `xvfb` since it allows us to run Chrome and Firefox in the same way. So writing browser agnostic code is easier. See the Privacy Badger tests for example: https://github.com/EFForg/privacybadger/blob/master/doc/tests.md

**Comment by koops76** [comment]
I guess I need to look for a similar feature in Firefox.

**Comment by pipboy96** [comment]
Seems to already be implemented.
