### ISSUE TITLE
Script tags with `crossorigin="anonymous"` set are blocked in Firefox.

### ISSUE THREAD

**Issue by nanek** [EFForg/https-everywhere#12579]
# Issue

Script tags with `crossorigin="anonymous"` set are blocked in Firefox with this extension.

# Example

Example: visiting http://www.spanishdict.com in Firefox with https-everywhere enabled breaks the site as javascript assets hosted on fastly.net are blocked.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://n1.global.ssl.fastly.net/dist/desktop-min-e629278b3482f77bd3dffc90ab326ad9.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).`

# Additional information

CORS is configured properly with fastly.net for these resources. If I remove `crossorigin="anonymous"` from the script tag then the javascript scripts are not be blocked and work correctly. However, using `crossorigin="anonymous"` is valid and is required to enable error tracking, as described in https://errorception.com/docs/cors

# Questions

If a javascript script tag has `crossorigin="anonymous"` can this extension avoid re-writing to HTTPS? This is likely a common configuration and breaks sites.

Can we whitelist www.spanishdict.com from this extension as this site has only partially implemented HTTPS? 

Will whitelisting www.spanishdict.com prevent the javascript assets hosted on fastly.net from being converted to HTTPS?

**Comment by Bisaloo** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/49

> Will whitelisting www.spanishdict.com prevent the javascript assets hosted on fastly.net from being converted to HTTPS?

No, it won't help.

**Comment by gloomy-ghost** [comment]
massive close per #15157
