### ISSUE TITLE
Brave using 5.2 release (outdated) for rulesets

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#12590]
Brave still uses the `5.2` minor release for rulesets.

This is being tracked in https://github.com/brave/browser-laptop/issues/10976

**Comment by diracdeltas** [comment]
Our numbering system is confusing; we are actually using 5.2.21 (https://github.com/brave/https-everywhere-builder/commit/e4a7ea83688f4a5875c83820e7ce38ad5514532f) which is somewhat less out of date.

**Comment by koops76** [comment]
This is one of the reasons why the rulesets should be viewed as a separate project from the addon. CloudFlare also uses them for automatic HTTPS rewrites.

**Comment by Bisaloo** [comment]
Fixed by @cschanaj in brave/https-everywhere-builder#3 (the auto-closing trick didn't work :( )
