### ISSUE TITLE
cafe.naver.com - can't delete my reply

### ISSUE THREAD

**Issue by Saumer7** [EFForg/https-everywhere#12597]
when using rule'stable: naver.com', I cant delete reply on cafe.naver.com'

**Comment by pipboy96** [comment]
@Saumer7 Does this issue still exist?

**Comment by Saumer7** [comment]
> 
> 
> @Saumer7 Does this issue still exist?

no
actually I forgot that I had write this issue here.
today I install https-everywhere extension to firefox, and tested.
no problem.
thank you.
