### ISSUE TITLE
Firefox shows "HTTPS Everywhere might be making Nightly run slowly"

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#1259]
Based on [Mozilla bug 1071880](https://bugzilla.mozilla.org/show_bug.cgi?id=1071880) and the fact that I've seen warnings that HTTPS Everywhere is slowing down my browser, I'm going to take a guess and say that HTTPS Everywhere is using a bunch of Cross-Process Object Wrappers, AKA CPOWs. CPOWs provide compatibility wrappers for common JS objects for porting extension code to the new message manager, but they have a lot of problems, especially with responsiveness. Because of this, it'd be nice if HTTPS Everywhere could reduce its usage of CPOWs.

Here's [the MDN article on CPOWs](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers).

**Comment by jsha** [comment]
Thanks for flagging this! I'd definitely like to do what we can to improve HTTPS Everywhere's performance.

Could you point out a few of the more frequently called sites where we use CPOWs so we can start looking at other approaches?

**Comment by strugee** [comment]
Unfortunately, I haven't looked at this closely enough to say anything useful. However, Firefox will send warnings to the error console every time a CPOW is accessed. I'd just look at those messages - they can basically be eliminated one by one, at whatever pace is convenient, from what I understand.

FWIW, this should probably have the e10s label, since CPOW usage only negatively affects performance in e10s browsers. (In non-e10s browsers you don't get the performance penalty of doing cross-process operations synchronously, so it doesn't matter.)

I'm about to go on spring break, so I _may_ get a chance to take a look at this.

**Comment by strugee** [comment]
Nope, nevermind. Compatibility shims are only created when `multiprocessCompatible` isn't set in `install.rdf`, which is not true in this case. So if you don't know of anywhere where one is explicitly created, then we can't be using any.

Leaving open because clearly _something_ is causing the "HTTPS Everywhere might be making Firefox run slowly" bar...

**Comment by J0WI** [comment]
We are e10s for a while now. This should be fixed anyway since we move to WebExtension API anyway.
