### ISSUE TITLE
Redirect counter should detect JavaScript initiated redirects

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#12594]
If a site includes JavaScript similar to this, we should bail out and disable the rule:

```javascript
if (window.location.protocol != "http:") {
    window.location.href = "http:" + window.location.href.substring(window.location.protocol.length);
}
```

**Comment by koops76** [comment]
That's very hard to detect. You would be surprised at how many ways there are to redirect the user to another page in JavaScript, and we would have to detect all of them since from the extension's point the redirect is a simple navigation, indistingushable from the one initiated by the user.

**Comment by koops76** [comment]
I think HTTPS Everywhere may simply disable these scripts instead.

**Comment by bardiharborow** [comment]
> the redirect is a simple navigation, indistinguishable from the one initiated by the user.

Yeah, I've dug into the webRequest API more, and it doesn't look promising. If we could work out how to determine if a request is a frame navigation rather than subrequest, the we might be able to build a back-off throttle on the quite poor assumption that frame requests are issued far less repetitively, but I haven't even determined how to do that, and I'm not sure such a solution would be tenable.

> I think HTTPS Everywhere may simply disable these scripts instead.

I think that's even more of a rabbit hole, because there's endless scenarios where script access to ` window.location` should not be blocked.

I'll leave this open for a while to see if there's any better ideas, but I'm not holding out hope.

**Comment by koops76** [comment]
I mean this exact script on this exact website. The website seems to work fine with JS disabled. I expected a lot of MCB errors.

**Comment by koops76** [comment]
That's what I wanted the extension to do.

1. Find all `script` tags with this or similar content
2. Delete them before they execute.

**Comment by koops76** [comment]
Or even better, if repeating frame navigations going in a loop between `https` and `http` URLs are detected on the same tab, cancel the request.

**Comment by bardiharborow** [comment]
Closing as fairly unachievable.
