### ISSUE TITLE
Dell shop breaks

### ISSUE THREAD

**Issue by jamy015** [EFForg/https-everywhere#12598]
See e.g. http://www.dell.com/nl-nl/shop/bekijk-alle-laptops-ultrabooks-tablets/xps-13-laptop/spd/xps-13-9360-laptop

**Comment by Bisaloo** [comment]
@jamy015, I can't reproduce, is that still an issue for you?

**Comment by jamy015** [comment]
No, it doesn't seem to be an issue anymore. Thanks for checking!
