### ISSUE TITLE
Let's at least use RSASSA-PSS instead of RSASSA-PKCS1-v1_5 for ruleset signing

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12605]
cc @Hainish @cowlicks.

RSASSA-PSS [is supported by WebCrypto](https://www.chromium.org/blink/webcrypto) and [provides more security than legacy RSASSA-PKCS1-v1_5 algorithm](http://grouper.ieee.org/groups/1363/P1363a/contributions/pss-submission.pdf).

#12087 is closed for now.

**Comment by koops76** [comment]
#12715

**Comment by Bisaloo** [comment]
This was implemented. See https://github.com/EFForg/https-everywhere/issues/12606#issuecomment-358424399.
