### ISSUE TITLE
Amazon Web Services ruleset breaks Anvato video player

### ISSUE THREAD

**Issue by practik** [EFForg/https-everywhere#12632]
Anvato is a media-streaming company whose HTML5 video platform is used by a number of local TV stations across the U.S. I tested the websites of three different stations that use it (krqe.com, wkbn.com, wspa.com) and found that video would not work on them unless I disabled HTTPS Everywhere's rule for Amazon Web Services – see screenshots. This is on Firefox 55.

![anvatograb1](https://user-images.githubusercontent.com/12074235/30575631-76e9bb94-9cbf-11e7-9dc2-d83f65137526.jpg)

![anvatograb2](https://user-images.githubusercontent.com/12074235/30575632-76ec756e-9cbf-11e7-8556-e9f10e5bf490.jpg)

**Comment by Bisaloo** [comment]
@J0WI, #14656 fixed this as well.
