### ISSUE TITLE
test

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#12647]
Type: blah

**Comment by koops76** [comment]
@Hainish Why does the bot not close this issue for not following the template?

**Comment by Hainish** [comment]
The discussion on auto-closing follows from here: https://github.com/EFForg/https-everywhere/issues/12646

**Comment by Hainish** [comment]
The discussion for autoclose starts from here: https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-304164232

**Comment by Hainish** [comment]
This was probably not commented on because I had to restart the bot.

**Comment by Hainish** [comment]
Changing your "Type: " indicates it's working properly now.
