### ISSUE TITLE
Breaks blog.emsisoft.com

### ISSUE THREAD

**Issue by Myer** [EFForg/https-everywhere#12651]
Type: ruleset issue

 emsisoft.com

Domain: http://blog.emsisoft.com
For example: http://blog.emsisoft.com/2017/09/19/emsisoft-windows-firewall-protection/

**Comment by mananaBanana** [comment]
Both the sites are redirecting to https just fine. What seems to be the problem?

**Comment by Myer** [comment]
Well, now it works. Looks like they have fixed something on their side.

Before certain images and fonts wouldn't load on the blog and I could reproducibly pinpoint it to HTTPS Everywhere. It looked like in this comment from a another user: https://blog.emsisoft.com/2017/09/19/emsisoft-windows-firewall-protection/#comment-3524935244
