### ISSUE TITLE
doc.bareos.org

### ISSUE THREAD

**Issue by kkdass** [EFForg/https-everywhere#12668]
Type: ruleset issue

bareos.org

Domain: doc.bareos.org

**Comment by d--j** [comment]
https://www.bareos.org has HSTS header with `includeSubdomains` but doc.bareos.org and download.bareos.org are not available via TLS. This is not a problem of HTTPS Everywhere. Everybody loading https://www.bareos.org once cannot open http://doc.bareos.org or http://download.bareos.org regardless of whether they have HTTPS Everywhere installed/active or not.
(also affects #12667)

**Comment by d--j** [comment]
this and #12667 is fixed now and can be closed (`includeSubdomains` was removed from HSTS header)

**Comment by kkdass** [comment]
Thanks for that!
