### ISSUE TITLE
Taleo.net (partial)

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#12660]
Type: ruleset issue

Domain: `http://chc.tbe.taleo.net/chc01/ats/careers/apply.jsp;jsessionid=77EB99EA80D4E67381D8691C45A42E83?rid=5620&org=ENVIGO&cws=52`

`Taleo.net (partial)` breaks functioning of page. Can test by hitting submit at the bottom and it *should* give you an error about not filling out the fields. With the Taleo.net rule, no error is given and it just refreshes the page.

**Comment by pipboy96** [comment]
This page redirects to HTTPS on its own now, but it only contains an error message.
