### ISSUE TITLE
Mixed mode sites, flash player and mozilla.cfg settings

### ISSUE THREAD

**Issue by Carm01** [EFForg/https-everywhere#12716]
I am noticing issues with mixed content site and adobe flash ; more specifically I have a cfg file to always activate flash player:

pref("plugin.default.state", 2);
defaultPref("plugin.state.flash", 2); 

There is more to the cfg set than this, however, all this started acting up a few days ago after a release of 55.0.3 x64. After adding that second line to get things to work again properly in the config file. Once I put on https everywhere flash player was not recognized during my troubleshooting after the 55.0.3 release:

https://helpx.adobe.com/flash-player.html
or
https://get.adobe.com/flashplayer/about/

Which is a mixed mode site. I have only found these two sites that are mixed mode with flash player as of yet. Now this could very well be the only cases, but I thought I would report it.
Once I removed https everywhere the site functioned properly and flash player was detected. It seems to work fine if it is not mixed mode.

Best reards

**Comment by grahamperrin** [comment]
### https://helpx.adobe.com/flash-player.html

- https://www.eff.org/https-everywhere/atlas/domains/adobe.com-1.html
- https://www.eff.org/https-everywhere/atlas/domains/macromedia.com.html

**If** the stable rule for _Macromedia.com_ is enabled **then** the page response to a click on the amber 'Check now' button does not progress beyond: 

> Please Wait.
> Checking latest version info.

![2018-07-14 18 34 12](https://user-images.githubusercontent.com/192271/42727034-8ee2455a-8796-11e8-932c-b976c798e49a.png)

#### Workaround

Disable the rule, allow the page to reload then again, click the 'Check now' button. 

Result – note, the difference in the amber area: 

![2018-07-14 18 35 53](https://user-images.githubusercontent.com/192271/42727042-afe15250-8796-11e8-9124-29df6b9cf24b.png)

#### Environment

[Waterfox](https://www.waterfoxproject.org/) 56.2.1 on FreeBSD-CURRENT, 

```text
$ waterfox --version ; pkg info waterfox | grep Version
Mozilla Waterfox 56.2.1
Version        : 56.2.1.55_3
$ date ; uname -v
Sat 14 Jul 2018 18:50:57 BST
FreeBSD 12.0-CURRENT #7 r336136: Tue Jul 10 03:01:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by pipboy96** [comment]
@Carm01 @grahamperrin Is this still a problem?

**Comment by pipboy96** [comment]
We don't officially support old Firefox versions and forks based on them, sorry.

**Comment by Carm01** [comment]
Well, since the post is two years old I suspect that you would not support it, and since I uninstalled everything flash and shockwave awhile ago it is a mute point.

Best regards
