### ISSUE TITLE
Uncommon TLDs

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12725]
Type: other

ping @J0WI @RReverser.

These are the TLDs I am planning to cover completely since there are not a lot of domains with HTTPS support on them.

If anyone knows how to enumerate all second-level domains under a specific TLD, tell me please.

* .lgbt
* .ovh
* .sucks

**Comment by J0WI** [comment]
Some registrars support OpenData: https://opendata.afnic.fr/en/products-and-services/services/opendata-en.html
You can also use public cert logs, but this only works for really small TLD zones: https://crt.sh/

**Comment by numismatika** [comment]
maybe these guys can help as well?
https://www.openintel.nl/
They had an interesting talk about how they found possible phishing domains before they were used.
