### ISSUE TITLE
Clearing browsing history clears HTTPS Everywhere settings

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#12730]
When I clear my whole browsing history in Firefox this also clears all my HTTPS-Everywhere settings (block all unencrypted requests, ruleset states).

ping @Hainish

**Comment by gloomy-ghost** [comment]
#11962 seems related

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/13356 seems to fix this.  Care to confirm @J0WI?

**Comment by Hainish** [comment]
Closing for now, please re-open if you can reproduce this issue.

**Comment by J0WI** [comment]
Thanks, WFM now.
