### ISSUE TITLE
HTTPS Everywhere breaks the Covered California website

### ISSUE THREAD

**Issue by charlesmagnuson** [EFForg/https-everywhere#12751]
Coveredca.com cannot be loaded when this extension is enabled. If I attempt to navigate to the website when the extension is enabled, the page rapidly refreshes over and over in an endless manner. The moment I disable the extension, coveredca.com works as expected.

Here is a quick 1-minute screencast where I reproduce the issue: http://ca.mag.cm/1w3M1q0D3W2Z

This issue has been happening for many months, but currently I am using Chrome Version 61.0.3163.100 (Official Build) (64-bit).

**Comment by koops76** [comment]
Duplicate of #12580.

**Comment by koops76** [comment]
Wait until a new version with the fix will be released.

**Comment by charlesmagnuson** [comment]
Oops! Sorry for creating a duplicate. Thank you for the help.
