### ISSUE TITLE
simon04.dev.openstreetmap.org/whodidit/

### ISSUE THREAD

**Issue by contrapunctus-1** [EFForg/https-everywhere#12764]
Images on the page fail to load with HTTPS Everywhere enabled.
http://simon04.dev.openstreetmap.org/whodidit/
Firefox v52.3.0, Debian Stretch

**Comment by naoliv** [comment]
Not only there, but also on other places that use OSM tiles
For example, http://zverik.osm.rambler.ru/whodidit/ and http://www.ipmet.unesp.br/alerta/ppigis/

**Comment by Bisaloo** [comment]
Related: https://trac.torproject.org/projects/tor/ticket/23541

**Comment by pipboy96** [comment]
No longer reproducible.
