### ISSUE TITLE
Warning about missing specification of browser_style

### ISSUE THREAD

**Issue by genodeftest** [EFForg/https-everywhere#12775]
Steps to reproduce:
1. have a fresh and clean firefox profile (firefox 55.0.3 in my case) started from command line
2. install HTTPS Everywhere (Version 2017.9.12 from AMO)
3. have a look at the output

What happens:
Every time this addon is installed or firefox is started, I get this warning:
`Please specify whether you want browser_style or not in your browser_action options.`
This warning is sometimes prefixed with `[timestamp]	addons.xpi	WARN	` and sometimes with `[timestamp]	addons.webextension.https-everywhere@eff.org	WARN	`.

What should happen:
No warning

Additional info:
`browser_action` is set in https://github.com/EFForg/https-everywhere/blob/master/chromium/manifest.json#L18. 

It doesn't look like the MDN docs have a related documentation:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Browser_action

**Comment by genodeftest** [comment]
#12776 has a fix which is now conflict-freed and ready to merge imho.

**Comment by pipboy96** [comment]
I can no longer reproduce the warning in Chrome, FF and Tor Browser.
