### ISSUE TITLE
'Block all HTTP requests' feature not working

### ISSUE THREAD

**Issue by domainedma** [EFForg/https-everywhere#1282]
The block all HTTP requests feature is not working.

After enabling the option I can still visit
http://www.androidpolice.com/2015/03/25/whatsapp-calling-goes-live-everyone-provided-recent-app-version-get-invited-receiving-call/

The link loads despite HTTP request being made.

This is my HTTPS Everywhere settings page (default rulesets used)

![toolbar](https://cloud.githubusercontent.com/assets/11057863/6821482/574c96a4-d32b-11e4-8db6-9e44c27455a8.png)

Details: Windows on Firefox 36 with HTTPS Everywhere 5.0 (session with and without Firefox Private Browsing has problem)

**Comment by jsha** [comment]
This is fixed in the latest 5.0 release. You can install manually from http://eff.org/https-everywhere, or it will automatically roll out to you later this week.

**Comment by jmorahan** [comment]
I don't think it's fixed. See #1285.

**Comment by jmorahan** [comment]
Granted, the Androidpolice rule is disabled by default now, so this won't actually happen in the latest build unless you enable it manually. But even if you do (or if another currently-working site starts doing the same thing), the HTTP request should still be blocked.

**Comment by jsha** [comment]
Oh whoops, I misread the original report. This makes sense, thanks for digging in and thanks for the fix.
