### ISSUE TITLE
Release 2017.10.[2|3] forthcoming

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#12827]
Type: other

cc @cowlicks @jsha @pde @J0WI @diracdeltas @jeremyn @gloomy-ghost

To be made Monday or Tuesday.

**Comment by koops76** [comment]
cc @cowlicks.

**Comment by Hainish** [comment]
Thanks, gotta update that list.

**Comment by cschanaj** [comment]
@cowlicks @Hainish if everything looks good, please merge #12577 before the next release. thanks!

**Comment by koops76** [comment]
Review #12819 #12805 #12803 #12741 please.

**Comment by koops76** [comment]
@Hainish @cowlicks Review #12819 #12805 #12803 #12741 please.

**Comment by Hainish** [comment]
this is going out today

**Comment by koops76** [comment]
@Hainish Review my PRs please.

**Comment by strugee** [comment]
@koops76 most of those just seem like code cleanup? Is there a reason they're critical to get into the next release?

**Comment by Hainish** [comment]
Release made.  Now making release for 2017.10.4.1337
