### ISSUE TITLE
Bot posts on any edit instead of only posting once.

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#12855]
Type: code issue

**Comment by Bisaloo** [comment]
I find those answers annoying anyways. They clutter the discussion IMO. Wouldn't it be better to make the bot edit its own post? For example:

------

~~I still don't see the type of issue in your description. Can you edit your issue to add this (perhaps referring to the issue template?)~~

Thanks! Your edit helped me out. I'll take it from here now.

------

**Comment by cschanaj** [comment]
@Hainish this is annoying for issues like #10378 and #12886 which require frequent update. Any chance this will get fixed/ disabled temporarily?

**Comment by bardiharborow** [comment]
@Hainish I think the bot's just plain malfunctioning now – it's commenting multiple times on issues that GitHub says haven't been edited.

**Comment by koops76** [comment]
@bardiharborow I made the edits.

**Comment by Hainish** [comment]
@strugee care to look into this?
