### ISSUE TITLE
Firefox addon is now showing "Legacy". Make the addon compatitable with Firefox 57+.

### ISSUE THREAD

**Issue by mugdhosapiens** [EFForg/https-everywhere#12874]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue
Type: new ruleset
Type: code issue
Type: feature request
Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by koops76** [comment]
@mugdhosapiens https://www.eff.org/https-everywhere#developers_note.

**Comment by jeremyn** [comment]
@mugdhosapiens The Firefox 57/"Legacy" flag is about the required switch from XUL/XPCOM to WebExtensions. There's a current tracking issue for the WebExtensions rewrite at https://github.com/EFForg/https-everywhere/issues/9958. If you need a fully-Firefox 57-compatible version of HTTPS Everywhere right now, take a look at the link in @koops76 's comment.

**Comment by Anmar24** [comment]
![avatar-default](https://user-images.githubusercontent.com/32487084/31131297-030785d4-a85a-11e7-9525-e4e0ba3bc59a.png)
