### ISSUE TITLE
Disable dailydot.com rule by default

### ISSUE THREAD

**Issue by thisisparker** [EFForg/https-everywhere#1290]
At least on my computer, the [dailydot.com](dailydot.com) rule breaks styling on articles and the home page. It appears that it's a mixed content issue that would take a little sleuthing to track down. Even with the rule off, HTTPS connections to the site have the same issue.

**Comment by jsha** [comment]
It's definitely a mixed content issue. You can see which resources are blocked due to mixed content blocking by opening up the browser console (F12) and reloading.
