### ISSUE TITLE
www.nationalgeographic.com

### ISSUE THREAD

**Issue by szhorvat** [EFForg/https-everywhere#12901]
Type: ruleset issue

Domain: www.nationalgeographic.com

With HTTP Everywhere, redirects to www-s.nationalgeographic.com, which shows an error page.

**Comment by bardiharborow** [comment]
Confirmed. `www` seems to redirect to HTTP now, and `www-s` is defunct.

**Comment by Bisaloo** [comment]
@J0WI, can you close this now please? It was fixed in #14211
