### ISSUE TITLE
Block unencrypted connections don't work for .onion

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#12903]
Block all unencrypted connections don't work for onion URLs, only for non-onion URLs.

**Comment by Bisaloo** [comment]
It's by design. Traffic for onion services is actually encrypted.

See https://github.com/EFForg/https-everywhere/issues/4118.

**Comment by jony0008** [comment]
@Bisaloo Not by HTTPS encryption though?

**Comment by koops76** [comment]
@jony0008 This is intended behavior.
