### ISSUE TITLE
Clean out main requirements.txt

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#12911]
Most packages inside `/requirements.txt` seem to only be used in `/test/rules` so move those things to `/test/rules/requirements.txt`.

The exception is `lxml` and `selenium`.

The `selenium` requirement will be removed in #12624

**Comment by Bisaloo** [comment]
@Hainish, you fixed this in b008ed1cd3d846966ddb9bf13d0c65e7025702c9, can you close this issue please?
