### ISSUE TITLE
Firefox: HTTP to HTTPS redirection failed while running tests

### ISSUE THREAD

**Issue by mananaBanana** [EFForg/https-everywhere#12917]
Type: code issue

Hi,
I was writing a new ruleset and it looks fine when I tested it against `fetch-test.sh`. However when I am pushing to my fork, `scripts/test.py` runs into an error *Firefox: HTTP to HTTPS redirection failed*. All the requirements from `requirements.txt` are satisfied. I also upgraded all of them, just in case. 
What might be causing the problem? Could it be any of Firefox extensions (NoScript, uBlock etc.)?

Thanks!

**Comment by mananaBanana** [comment]
Running it on the `master` branch is also causing the same issue. The redirection is successful when tested against Chrome.

**Comment by cowlicks** [comment]
@mananaBanana what version of python is it using? Is this still an issue?

**Comment by ymhuang0808** [comment]
I also encounter the issue. `test/firefox.sh` looks like building a XPI file, but I'm using Firefox 57 which only support WebExtension.

@mananaBanana What's version of Firefox running?

**Comment by mananaBanana** [comment]
Firefox 56.
Here's the log:
```bash
Total included rules: 23120
Rules disabled by default: 6204
Created pkg/https-everywhere-2017.9.12~9e3463d-eff.xpi and pkg/https-everywhere-2017.9.12~9e3463d-amo.xpi
++ tail -1
++ ls -tr pkg/https-everywhere-2017.9.12~9e3463d-eff.xpi pkg/https-everywhere-2017.9.12~a7b19d8-eff.xpi
+ XPI_NAME=pkg/https-everywhere-2017.9.12~9e3463d-eff.xpi
+ rsync -a test/firefox/test_profile_skeleton/ /tmp/tmp.qPgiXqxmfD
+ unzip -qd /tmp/tmp.qPgiXqxmfD/extensions/https-everywhere-eff@eff.org pkg/https-everywhere-2017.9.12~9e3463d-eff.xpi
+ '[' '!' -d /tmp/tmp.qPgiXqxmfD/extensions/https-everywhere-eff@eff.org ']'
++ which xvfb-run
+ '[' -z '' -a -n /usr/bin/xvfb-run ']'
+ XVFB_RUN=xvfb-run
+ '[' '' == --justrun ']'
+ echo 'running tests'
running tests
+ PATH=/home/user/geckodriver:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
+ '[' -n '' ']'
+ xvfb-run python2.7 test/script.py Firefox /tmp/tmp.qPgiXqxmfD

Firefox: HTTP to HTTPS redirection failed
```
Is there a way to get a more verbose output?

**Comment by pipboy96** [comment]
Seems to be fixed.
