### ISSUE TITLE
requirements.txt needs to check for package versions

### ISSUE THREAD

**Issue by mananaBanana** [EFForg/https-everywhere#12918]
Type: code issue

Hello all,

I think that requirements.txt should not only list the package name but also the version. I had a really outdated version of selenium and `scripts/test.py` was running into an exception. On running `pip install --upgrade -r requirements.txt` things started working all right.

The latest version might not be the one that works correctly, so I think it is better we list a specific version for a package that is guaranteed to work ([like this](https://stackoverflow.com/questions/13916820/how-to-install-a-specific-version-of-a-package-with-pip/13916850#13916850)). How does that sound?

Cheers!

**Comment by Bisaloo** [comment]
Thanks for the report! 

The only library listed in [`requirements.txt`](https://github.com/EFForg/https-everywhere/blob/b008ed1cd3d846966ddb9bf13d0c65e7025702c9/requirements.txt) is now `lxml` and a minimal version is specified so I'm closing this issue as fixed.
