### ISSUE TITLE
HTTPS Everywhere doesn't redirect requests for iframes

### ISSUE THREAD

**Issue by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [EFForg/https-everywhere#12928]
Type: code issue

-------------

I observed this in a website and I tried to reproduce it in a demo that I made here:
https://I-have-50-open-PRs-to-HTTPS-EVERYWHERE.github.io/demo/iframe-youtube-and-https-everywhere.html

```
<html>
	<meta charset="UTF-8">
	<body>
		<iframe width="560" height="315" src="http://www.youtube.com/embed/PdnpNJZVUE0" frameborder="0" allowfullscreen></iframe>
	</body>
</html>
```

Basically the `http://www.youtube.com/embed/PdnpNJZVUE0` doesn't get redirected to `https://www.youtube.com/embed/PdnpNJZVUE0` as you can see by opening the HTTPS version of the demo link above and no video will show up (remember mixed content gets blocked).

In fact even the Youtube.xml ruleset wont show up when you click on the HTTPS Everywhere icon on that demo.

Is this a limitation with WebExtensions and if so can there be anyway to solve this issue?

**Comment by koops76** [comment]
@I-have-50-open-PRs-to-HTTPS-EVERYWHERE That's mixed content blocking.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@koops76 You're right, thanks.
