### ISSUE TITLE
Firefox developer support

### ISSUE THREAD

**Issue by jQrgen** [EFForg/https-everywhere#12935]
Hello,

Will there be Firefox developer edition support for this plugin?

Thanks <3

**Comment by koops76** [comment]
Duplicate.

**Comment by koops76** [comment]
See https://www.eff.org/https-everywhere#developers_note.

**Comment by jQrgen** [comment]
Thanks!

**Comment by jQrgen** [comment]
(Yes, i tried searching. No luck x)
