### ISSUE TITLE
https-everywhere-checker should only comment out problamatic domains instead of disabling the entire ruleset

### ISSUE THREAD

**Issue by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [EFForg/https-everywhere#12966]
Type: other

**Comment by Bisaloo** [comment]
Duplicate of https://github.com/EFForg/https-everywhere/issues/1998.

See also https://github.com/EFForg/https-everywhere/issues/1204, https://github.com/EFForg/https-everywhere/pull/11616 and https://github.com/EFForg/https-everywhere/pull/10538#issuecomment-309970098.

**Comment by koops76** [comment]
See also #12620 (problematic targets).

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Thanks @Bisaloo and @koops76
