### ISSUE TITLE
Magical Mystery Custom Rule Issue

### ISSUE THREAD

**Issue by mazesy** [EFForg/https-everywhere#12968]
https-everywhere-2017.10.4-eff.xpi / Waterfox 55.2.0 (=Firefox 55.0.3) / Windows 7 x64

Be it with latest HTTPS Everywhere 2017.10.4 as with all previous Webextension versions I just cannot manage to keep a rule I've set once the browser is restarted.

Example:

I open https://securityaffairs.co/wordpress. No rule for this domain, hence I create one, it concerns and is named _securityaffairs.co_

I exit the site, call http://securityaffairs.co/wordpress and all is fine : the rule allowed the site to be opened via https.

I open my Waterfox profile with Total Commander, I do a text search in my Watrfox profile  for _securityaffairs.co_ since that is the name of the rule : it appears nowhere : where does HTTPS Everywhere **physically** locate the rule I have set?

I restart Waterfox, open http://securityaffairs.co/wordpress and the rule I had set (_securityaffairs.co_) is not applied and is not shown in HTTPS Everywhere's drop-down menu ...

So I ask as I wonder : where does HTTPS Everywhere locate the custom rules? Where? In RAM? WHERE?

I'm straightforward because I've been dealing with this ever since HTTPS Everywhere shifted to a Webextension. I had been using HTTPS Everywhere for years and now it appears to me as unusable.

**WHERE are the user's custom rules located?** That is ALL I wish to know. Thanks.

**Comment by koops76** [comment]
@mazesy #12969.

**Comment by mazesy** [comment]
Could I just be told where a user's custom rule is located in the user's Firefox/Waterfox profile?

**Comment by mazesy** [comment]
I've created a new dummy Waterfox profile, installed latest HTTPS Everywhere and no isue : the custom rule is ok.
It appears this custom rule is located in the user's profile / webappstore.sqlite file : LocalStorage.

Back to my 'normal' profile, security/privacy tweaked + 65 extensions (add-ons & webextensions) my HTTPS Everywhere custom rule is not added to my LocalStorage. Why? No idea, likely tied to one of my security/privacy tweaks.

There would be no problem if HTTPS Everywhere located these user custom rules in its browser-extension-data dedicated folder within the storage.js file or as IndexedDB in the storage folder like ALL other webextensions do. LocalStorage is NOT the right place.

Forget it as I forget HTTPS Everywhere. This is far too much a pain. Sorry to say so but the work isn't correct. Bye.

**Comment by koops76** [comment]
@mazesy Custom rules are stored in WebExtensions storage.
