### ISSUE TITLE
Add a block all mixed content mode to Chrome

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#1297]
Chrome allows limited mixed content (IIRC only images?).

We could add a mode that blocks *all* mixed content.

**Comment by domainedma** [comment]
Firefox also allows mixed content

**Comment by domainedma** [comment]
Firefox also is allowing limited content https://support.mozilla.org/en-US/kb/how-does-content-isnt-secure-affect-my-safety#w_the-icon-is-a-gray-triangle

"Only the potentially harmful part of HTTP content is blocked so some websites may still have some HTTP content (such as images)"

**Comment by semenko** [comment]
Mechanistically in chrome, we can probably do this with the `frameId` and `parentFrameId` fields in the addListener callback (and can add a custom listener only for images).

**Comment by mikewest** [comment]
You could also opt-into Chrome's built-in (as of Chrome 43) support for https://w3c.github.io/webappsec/specs/upgrade/, which would have more or less the effect you're looking for.

**Comment by semenko** [comment]
Whoa -- cool!

We'd need to inject a CSP header into all HTTPS requests (if I'm reading that spec correctly)? That could be hard, as we might want to eventually drop the https://*/* permissions (and only request http://*/* to reduce our attack surface).

Just noticed the bugs for --enable-strict-mixed-content-checking / https://code.google.com/p/chromium/issues/detail?id=450458 -- which we could suggest to users.
