### ISSUE TITLE
dell.com broken (German site) shows no content unless I disable HTTPS everywhere for that domain

### ISSUE THREAD

**Issue by llucax** [EFForg/https-everywhere#12974]
Type: ruleset issue
Domain: dell.com

When visiting the German site, at least, when looking at details of notebooks, like XPS 15: http://www.dell.com/de-de/shop/notebooks-und-ultrabooks/xps-15-9560-laptop/spd/xps-15-9560-laptop?~ck=bt

I get no content except for the page header and footer unless I disable the HTTPS everywhere rule for the "dell.com (partial)". When I disable it just for that domain, it works as expected.

Broken (note the missing content and login button):

![Broken](https://user-images.githubusercontent.com/1031485/31251411-262cb42e-aa1e-11e7-960f-849c5c256ab8.png)

Working (note also the scroll bar, the page have lots more of contents):
![Working](https://user-images.githubusercontent.com/1031485/31251410-26188f76-aa1e-11e7-9126-a65e06ae37a1.png)

**Comment by bardiharborow** [comment]
Confirmed. [Dell.xml](https://github.com/EFForg/https-everywhere/blob/83de41675c85637c18f2af136ffb9738fe1dc792/src/chrome/content/rules/Dell.xml) is causing CORS errors.

**Comment by gloomy-ghost** [comment]
massive close per #15157
