### ISSUE TITLE
FireFox legacy extension not removed on installing new compatible one

### ISSUE THREAD

**Issue by tycarac** [EFForg/https-everywhere#13018]
Type: code issue 

Domain:  Addon ID for FireFox

From FireFox Bugzilla Bug 1406563

Steps to reproduce:
1. Install extension in FF56 (EFF HTTPS Everywhere 2017.9.12)
2. Update to FF57 beta
3. Manually install compatible extension from developer website (EFF HTTPS Everywhere 2017.10.4.1337)

Actual results:
Compatible extension successfully installed but legacy extension not uninstalled and removed from legacy list.

Expected results:
FF recognises compatible extension is a replacement of legacy extension and uninstall legacy extension.

Feedback from Bugzilla triage is:  The only way for connecting different versions of the same extension is using the id field.  That already supports things like updating from a legacy extension to a webextension.  We don't do anything (and don't have any plans to do anything) to connect extensions with different identifiers.  The extensions listed in comment 2 have different IDs (https-everywhere-eff-bill@eff.org for the webextension, https-everywhere-eff@eff.org for the legacy extension).

I believe that HTTPS should not have changed the AddOn Id for the new compatible Add-on.  Or is this a means to allow a FireFox tester to have a beta and current Add-on installed simultaneously for easier testing?

**Comment by gloomy-ghost** [comment]
IIRC, the main reason is that AMO does not allow us to use the same ID for self-hosted version and AMO version. Anyway, the WebExtension version has been released for a while, and you should switch back to the release channel if you just want it to work on Fx 57.

**Comment by pipboy96** [comment]
Irrelevant by now.
