### ISSUE TITLE
2017.10.4 doesnt work on the last Firefox for android 

### ISSUE THREAD

**Issue by svoa** [EFForg/https-everywhere#13035]
2017.10.4 doesnt work on the last Firefox for android

**Comment by gloomy-ghost** [comment]
I can reproduce this with the XPCOM version on Fx 56 (release), the WE version on Fx 57 (beta) and Fx 58 (nightly). For the XPCOM version, clicking the browserAction does nothing. Whereas for the WE version it does open the popup page but no ruleset is ever shown. It's not rewriting any requests neither, seems completely broken. Pinging @Hainish to prioritize this issue.
