### ISSUE TITLE
Make tests case insensitive

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#13036]
Type: other

In #12955 it turns out, that our ruleset tests are checking the targets case sensitive. But they shouldn't.
So `FOO.BAR` and `foo.bar` should be treated as duplicated target host.

**Comment by cschanaj** [comment]
It seems that we have a small number of case-sensitive duplicated targets now. ~Fixed in #13282, #13283 and #13284~. We can fix this by forbidding uppercase letters in

https://github.com/EFForg/https-everywhere/blob/6cb0f489addf4395f7a3d1d6ab8c996ec10b47c1/utils/relaxng.xml#L36 

See #13285
