### ISSUE TITLE
Re-enable Ted.com?

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#1303]
I see two comments in there  https://trac.torproject.org/projects/tor/ticket/7548 and a default_off "breaks videos" 

Sure there is passive mixedcontent on their cdn and their blog which can't be properly secured , but the page itself is working quite fine even with cookies blocked in Firefox.

Was that breakage from embedding ted on a different page or can we safely re-activate this ruleset?

**Comment by jsha** [comment]
If you've tested the site thoroughly and found that it works now, I'd be happy to accept a pull request re-enabling it. Those comments are from two years ago, I readily believe that the site has changed in that time.

**Comment by semenko** [comment]
Fixing/fixed in a PR.
