### ISSUE TITLE
wikihow.com now supports HTTPS

### ISSUE THREAD

**Issue by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [EFForg/https-everywhere#13043]
Type: new ruleset

Domain:wikihow.com

-------

I don't have the time now to go through this one, thus I thought it would be better to make an issue. The relevant files to be changed are:

+ [WikiHow.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/WikiHow.com.xml)

+ [ruleset-whitelist.csv](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-whitelist.csv)

**Comment by koops76** [comment]
#13045

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Merged by J0WI https://github.com/EFForg/https-everywhere/pull/13045
