### ISSUE TITLE
[Akamaihd.net] Rule breaks video on francetvinfo.fr

### ISSUE THREAD

**Issue by pihug12** [EFForg/https-everywhere#13046]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:akamaihd.net

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The Akamai rule ("akamaihd.net") breaks videos on the "francetvinfo.fr" website.  
**Example:** http://www.francetvinfo.fr/societe/nucleaire/terrorisme-greenpeace-alerte-sur-la-vulnerabilite-des-centrales-nucleaires-francaises_2412845.html

The problematic part seems to be: http://staticftv-a.akamaihd.net/player/...

**Comment by Bisaloo** [comment]
This is fixed now that francetvinfo.fr supports HTTPS.
