### ISSUE TITLE
Review the merged #12624 before the next release

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13050]
Type: other

#12624 was merged to make reviewing PR's easier while @Hainish is out. It should be reviewed before the next release.

**Comment by bardiharborow** [comment]
One comment I will make is that build times have been slowed way down by these changes.

**Comment by cowlicks** [comment]
@bardiharborow This is True! However, we are also running many more tests. Ideas:

* I'm not using docker containers for the selenium tests, to streamline the test process. Maybe switching back to docker containers would speed this up.
* Selenium tests are now run for *every* pull request. Including rulesets. If this is mostly a disruption of ruleset work, then we should probably just turn off selenium tests for the ruleset PRs.
* The longest runtime of an induvidual test is actually just 3 minutes. But Travis is very slow to get them all started. The tests would be fast if Travis ran them all in parallel.

**Comment by Hainish** [comment]
> Selenium tests are now run for every pull request. Including rulesets. If this is mostly a disruption of ruleset work, then we should probably just turn off selenium tests for the ruleset PRs.

I do think we should switch this, since the majority of PRs are for rulesets.  It seems silly to run the selenium tests when no core code has changed.
