### ISSUE TITLE
Add "Type: testing" to the issue template/bot

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13059]
Type: other

See https://github.com/EFForg/https-everywhere/issues/13051#issuecomment-335969414

**Comment by jeremyn** [comment]
Every new issue type requires updated documentation forever and puts a cognitive load on every new issue submitter, so we shouldn't add one unless it's really needed.

Why is this really needed here? How many issues do we have right now that would have `Type: testing` if `testing` were a valid type?

**Comment by cowlicks** [comment]
@jeremyn that is a good point. I suppose adding many `Type:`s would eventually duplicate our labels. I think `other` should be fine. But I didn't expect the bot to complain when I replaced `other` with some "other" name, so maybe we could set expectations a little better here.
