### ISSUE TITLE
Extension popup size and scrolling is intermittently buggy in Chrome.

### ISSUE THREAD

**Issue by bardiharborow** [EFForg/https-everywhere#13087]
Type: code issue

Occasionally, when I click on the extension the popup bugs out, and displays like this. You can't scroll up when this happens.

![screen shot of the issue](https://user-images.githubusercontent.com/1073681/31573701-d7dae5b6-b10c-11e7-8e43-f5a9c6c956eb.png)

Clicking out of the popup and back in resolves the issue.

![screen shot of the intended behavior](https://user-images.githubusercontent.com/1073681/31573703-da8fb598-b10c-11e7-9afa-703aca131eee.png)

I'm not sure if this is a Chrome bug or not. I'm on Chrome 62.0.3202.52 on MacOS 10.12.4.

**Comment by pipboy96** [comment]
UI code has been significantly changed, I can no longer reproduce.
