### ISSUE TITLE
Duplicated App Icons

### ISSUE THREAD

**Issue by aaidee** [EFForg/https-everywhere#13083]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
Type: other

I'm using Firefox 56.0 64bit and HTTPS Everywhere on Win10. I've installed this again from https://www.eff.org/https-everywhere But it shows twice! Is one of these a fake app? I am a liberal party member.
![app1](https://user-images.githubusercontent.com/6753994/31572937-f96a4986-b0eb-11e7-96da-960a58e760e5.jpg)
![app2](https://user-images.githubusercontent.com/6753994/31572938-fdce8f8c-b0eb-11e7-92cc-01dd3370a6fb.jpg)

And how can I backup these two extentions for evidence collection?

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by aaidee** [comment]
And How can I back up these two extentions for evidence collection.

**Comment by Bisaloo** [comment]
You probably downloaded HTTPS Everywhere from two different places:

- https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/
- https://www.eff.org/https-everywhere

You will get legit extensions from those two locations but they differ in their ID, which means that firefox won't recognize them as the same extension.

**Comment by jeremyn** [comment]
I agree with @Bisaloo . Also, you can tell which one came from https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/ by clicking the "Preferences" (equivalent) button: the one from `addons.mozilla.org` will have a "Rating" line, and the one from `eff.org` won't have this line.

**Comment by aaidee** [comment]
I see. Thank you very much.
