### ISSUE TITLE
Broken Bitly Branded Short Domain Links

### ISSUE THREAD

**Issue by jehiah** [EFForg/https-everywhere#1309]
Unfortunately 1c7baccb61d39fcca25d6018d4642c97d8d44565 breaks functionality for some links on Bitly Branded Short Domains (like ift.tt, nyti.ms, etc) because those domains are not completely interchangeable with bit.ly. The only bitly domains that can reliably be redirected from http->https are bit.ly, j.mp and bitly.com

**Comment by kevinebaugh** [comment]
@2d1 Can we get your input on this issue? This is a major bug as all ift.tt links will redirect to their bit.ly counterparts.

For example, our IFTTT newsletter this morning linked to ift.tt/newsletter28. For people running HTTPS Everywhere, they are redirected to bit.ly/newsletter28 instead.

**Comment by jsha** [comment]
Fixed by @kevinebaugh.
