### ISSUE TITLE
Travis test thinks some URL is preloaded when it's not

### ISSUE THREAD

**Issue by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [EFForg/https-everywhere#13147]
Type: other

----

Pull in question https://github.com/EFForg/https-everywhere/pull/13117

You can check using hstspreload.org that it isn't preloaded.

**Comment by jeremyn** [comment]
`thenib.com` is preloaded according to chrome://net-internals/#hsts in Chrome v61.0.3163.100.

Looking at https://hstspreload.org/?domain=thenib.com , the error is 

> Error: Max-age too low
> The max-age must be at least 31536000 seconds (≈ 1 year), but the header currently only has max-age=15768000.

From https://hstspreload.org/?domain=thenib.com#continued-requirements it looks like the `max-age` required value increased very recently. I guess that https://hstspreload.org is incorrectly using the recently-increased `max-age` requirement of 31536000 for older domains when reporting whether the domain is preloaded or not.

**Comment by jeremyn** [comment]
@lgarron Can you please take a look to see if there's a problem with the hstspreload.org site, following my previous comment?

**Comment by lgarron** [comment]
> I guess that https://hstspreload.org is incorrectly using the recently-increased max-age requirement of 31536000 for older domains when reporting whether the domain is preloaded or not.

Indeed, that's something I need to clean up. I'm pleasantly surprised someone noticed. :-)

However, https://hstspreload.org/?domain=thenib.com does accurately state that thenib.com is still preloaded.

**Comment by jeremyn** [comment]
@lgarron Oh, you're right, it does. The complete response is:

>Status: thenib.com is currently preloaded, but no longer meets the requirements. It may be at risk of removal.
>
> **Error: Max-age too low**
> The max-age must be at least 31536000 seconds (≈ 1 year), but the header currently only has max-age=15768000.

**Comment by Bisaloo** [comment]
@lgarron, as a follow-up question: you mentioned that domains falling behind the requirements may be automatically removed from the list in the future. What will happen in this specific case? The domain owner didn't purposefully removed headers, they may simply not be aware that the requirements changed.

**Comment by lgarron** [comment]
> What will happen in this specific case? The domain owner didn't purposefully removed headers, they may simply not be aware that the requirements changed.

In this specific case, we will almost certainly only apply the 18-week requirement that was in place at the time they were added, and they will stay preloaded.

If a site completely *removes* the HSTS header, though, they should expect to be removed eventually, though.
