### ISSUE TITLE
Setting privacy.resistFingerprinting to true in Firefox prevents HTTPS Everywhere installation

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#13187]
Type: other

Using Firefox 56.0, if you have `privacy.resistFingerprinting` set to `true` in `about:config` and then go to https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/ , the `Add to Firefox` button will be grayed out with the warning `This add-on is not compatible with your version of Firefox.` If you set `privacy.resistFingerprinting` to `false` and refresh the AMO page, the `Add to Firefox` button is green and the warning disappears.

(See https://www.ghacks.net/2016/07/04/tor-privacy-settings-coming-to-firefox/ for more information on the `privacy.resistFingerprinting` setting.)

Pinging @Hainish.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
This is more of a Firefox problem, privacy.resistFingerprinting when set to true sets the user agent to Firefox 50 (it would make sense if it was set to the ESR, in this case 52, so I think Mozilla should head in that direction). When going to AMO it checks the user agent to say whether the extension is compatible or not. 

Is there any Mozilla bugtracker for this one?

**Comment by jeremyn** [comment]
Thanks @I-have-50-open-PRs-to-HTTPS-EVERYWHERE , I didn't know it changed the useraagent version. In that case I guess everything is working correctly.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
@jeremyn It has been fixed in Firefox 57 https://bugzilla.mozilla.org/show_bug.cgi?id=1393283 Now the useragent when enabling that pref would be that of the ESR version for which HTTPS-E is, at least for now, going to work.

**Comment by jeremyn** [comment]
@I-have-50-open-PRs-to-HTTPS-EVERYWHERE Thanks for the update.
