### ISSUE TITLE
Planning build architecture after webextension transition

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13190]
Type: code issue

After the transition to WebExtensions we should be able to greatly simplify our development process because we will have a homogeneous build process for all distributions.

I think a structure that would allow us to load the extension as "unpacked", from the working directory be great. This way, changes to the edited code, would be reflected in the browser, when the extension is refreshed.

The only complication here is that we need handle `_locales`, and the built rulesets.json file. I was imagining we could do this on `npm install`, since that should only be run by developers. This would then link the rulesets.json & locales into the directory. We could probably just move the `_locales` into the correct directory inside of `chromium` permanently, instead of having this be a build step.

This would also lower the barrier to entry for developing HE. The steps would be:
* `git clone` the repo
* `cd https-everywhere/chromium/`
* `npm install` installs dev dependencies, and rulesets.
* load the unpacked extension from chrome

**Comment by koops76** [comment]
@cowlicks My suggestions are Gulp and/or Webpack.

**Comment by zoracon** [comment]
Seems outdated and we follow this structure and devs are able to reproduce with the build scripts we have. Closing out for now. Thank you.
