### ISSUE TITLE
Chrome: switch to declarativeWebRequest

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#132]
[For issue #12, though that's doing pretty well now :) ]

Chome's beta channel now supports declarativeWebRequests: http://developer.chrome.com/extensions/declarativeWebRequest.html

This is a high-performance way to use blocking webRequests without triggering our slow JS code on every request. Plus, it's designed to easily support the declaration of "hundreds of thousands of URLs."

I'll integrate & test, hopefully we can merge after this makes it into stable (M33 at the earliest).

This'll probably work like:
- Keep the current webRequest handler (to catch tabs opening on start)
- Build & invoke the declarativeWebRequest list
- Drop the webRequest handler (removeListener)

**Comment by semenko** [comment]
Closing since this API seems ~abandoned by Google :/

**Comment by pipboy96** [comment]
@semenko Google resurrected this API and is now going to force everyone to use it (which would seriously cripple our extension in current form0. See #17268.
