### ISSUE TITLE
Wix site not loading

### ISSUE THREAD

**Issue by tempissue** [EFForg/https-everywhere#13200]
Type: ruleset issue

Domain: wix static
(wix_static_com.xml)

In Firefox 56.0.1, this site ( http://michelineamisi.wixsite.com/amisi/home ) doesn't load, instead just staying at a white screen. When the Wix Static.com rule is turned off, it loads fine. 

On Chrome, this is not an issue and it loads fine. In addition, other wixsite.com sites also load fine.

Thanks!

**Comment by Bisaloo** [comment]
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://static.wixstatic.com/shapes/e001c0bb02684087b167a5177b0b1a3a.svg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://static.wixstatic.com/shapes/6b1da864ef84b466c566b1aac7ed2e1e_svgshape.v1.Triangle.svg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by gloomy-ghost** [comment]
massive close per #15157
