### ISSUE TITLE
Add note about filtering issues to the Contributing.md

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13204]
Type: other

I recently discovered how to filter github labels by exclusion. This makes the issue and pr trackers easier to work with because there is less noise from rulesets. I think it may be useful to ruleset maintainers too.

We should add a note about this, with links, to help contributors.

This [link](https://github.com/EFForg/https-everywhere/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20-label%3Aruleset%20-label%3Anew-ruleset%20-label%3Aruleset-bug%20-label%3Aruleset-enhancement%20-label%3Atop-100%20-label%3Atop-1k%20-label%3Atop-10k%20-label%3Atop-100k%20-label%3Atop-1m%20) is all  non-ruleset related PRs. It still shows unlabeled ruleset PR's.

This [link](https://github.com/EFForg/https-everywhere/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Aruleset%20-label%3Anew-ruleset%20-label%3Aruleset-bug%20-label%3Aruleset-enhancement%20-label%3Atop-100%20-label%3Atop-1k%20-label%3Atop-10k%20-label%3Atop-100k%20-label%3Atop-1m%20) is non-ruleset issues.

**Comment by Bisaloo** [comment]
It should be possible to auto-tag PR depending on the location of the modified files (ie within `src/chrome/content/rules/` or not).

Also related: https://github.com/EFForg/https-everywhere/issues/2697
