### ISSUE TITLE
Document and unit test API's used by downstream projects

### ISSUE THREAD

**Issue by cowlicks** [EFForg/https-everywhere#13212]
Type: other

To do this we need:
- [ ] list of downstream projects
- [ ] list of api's used by those projects

Currently I know of:

Downstream projects:
* rewriter.js

apis:
* `RuleSets`, `RuleSets.addFromXml`, and `RuleSets.rewriteURI`

**Comment by jeremyn** [comment]
See also issue https://github.com/EFForg/https-everywhere/issues/6937.

**Comment by koops76** [comment]
@cowlicks CloudFlare HTTPS rewrites and Brave.
