### ISSUE TITLE
Checker gets SSL errors that browser doesn't get

### ISSUE THREAD

**Issue by fuzzyroddis** [EFForg/https-everywhere#1323]
> Disabled by https-everywhere-checker because:
> Fetch error: http://my.commbank.com.au/ => https://www.my.commbank.com.au/: (56, 'SSL read: error:00000000:lib(0):func(0):reason(0), errno 104')

But https://www.my.commbank.com.au/netbank/Logon/Logon.aspx?HostedTheme=CommBank works.

in Commbank.xml

**Comment by jsha** [comment]
This looks like a bug in the checker, which we should fix. Please feel free to re-enable the rule with appropriate tests, and if the fetch-test flags this site with this specific error, disregard it.

**Comment by Hainish** [comment]
This appears to be fixed.
