### ISSUE TITLE
Cloudfront ruleset breaks duolingo.cn

### ISSUE THREAD

**Issue by yfdyh000** [EFForg/https-everywhere#13255]
Type: ruleset issue
Domain: duolingo.cn
The website blank if the Cloudfront ruleset enabled.
Similar to #102.
https://www.duolingo.com/ is redirected to http://www.duolingo.cn/ for Chinese users.
https://www.duolingo.cn/ is not available.

**Comment by Bisaloo** [comment]
Thanks for your report! It's caused by https://github.com/EFForg/https-everywhere/issues/12579.

**Comment by pipboy96** [comment]
Likely closed by #15157.
