### ISSUE TITLE
[eBay] Thumbnails of my articles aren't loaded in Firefox since HTTPS-Everyhwere 5.0.x

### ISSUE THREAD

**Issue by d4k0** [EFForg/https-everywhere#1325]
Yesterday I noticed that the thumbnails of my articles on eBay aren't loaded anymore. This is how it looks:

![Missing thumbnails](https://i.imgur.com/B0KiBy6.png)

It turned out that the (new?) "eBay static.com (partial)" profile is the culprit which is activated by default. When I deactivate it, the site looks like it is supposed to be:

![How it should look like](https://i.imgur.com/rYr6P3d.png)

It noticed this the first time yesterday (when HTTPS-Everyhwere was updated), so maybe there's a bug in HTTPS-Everyhwere 5.0.1. I'm using Firefox 37 as a browser.

The strange thing is that the thumbnails load without a problem in Chrom 41 and with activated "eBay static.com (partial)" profile (the version of HTTPS-Everyhwere is "2015.3.23"):

![Situation in Chrome](https://i.imgur.com/TozZwVS.png)

It would be nice if this could be fixed.

**Comment by jsha** [comment]
It looks like you have some other extensions installed in Firefox. Could you try disabling those to see if they could be interacting with HTTPS Everywhere to cause a breakage?

Also, can you provide the full URL to a broken page so I can test?

Thanks,
Jacob

**Comment by d4k0** [comment]
OK, I think I found the culprit. I tried it with a fresh profile and the thumbnails were displayed. That's why I tried to disable all add-ons (in my normal profile), but the thumbnails were still not shown.

Then I remembered that I enabled [Firefox's (experimental) tracking protection feature](https://support.mozilla.org/en-US/kb/tracking-protection-firefox) (which uses the filters from Disconnect) and I saw that it was indeed blocking something. I whitelisted the page and the thumbnails were showing again. It seems that the update to Firefox 37 seems to have changed something (after all this feature is still in development) which causes this problem (filter update?).

However, it's strange that deactivating HTTPS-Everything's new "eBay static.com (partial)" profile also works (without deactivating Firefox's tracking protecting feature). So it seems that both are somehow interfering with each other.

As for providing a link: Well, I could give you the links to the blocked thumbnails if this helps (I rather don't want to give away my eBay login data :)).

**Comment by jsha** [comment]
Ah, I didn't realize this is only for logged-in view.

Interesting that the tracking protection feature blocks these images in conjunction with HTTPS Everywhere. It's possible that the rewritten URLs for those images are on a filter list, but not the originals.

Closing this for HTTPS Everywhere, thanks for the report!
