### ISSUE TITLE
Can the Doubleclick.net.xml ruleset be enabled now?

### ISSUE THREAD

**Issue by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [EFForg/https-everywhere#13273]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Doubleclick.net.xml

**Comment by J0WI** [comment]
Since we don't care about broken ads I would say yes. Flash is also deprecated.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Thanks, I made a PR to enable it https://github.com/EFForg/https-everywhere/pull/13419

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
Solved by https://github.com/EFForg/https-everywhere/commit/6cba13e47da8edea4805fb962a4b4bc646971d3c
