### ISSUE TITLE
Block All HTTP Requests should redirect to an informational page

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1329]
Currently it aborts the request, which makes it very confusing when you hit an HTTP URL, especially since the browser continues to display the HTTPS URL of the previous page. We should instead register a URL that we can send users to indicating the request was blocked.

We may additionally want to detect whether the request is a top-level navigation, and only redirect for those that are. Otherwise images may receive an invalid response, creating confusing results. However, if this is hard I think doing the redirect for all requests would still be a net win.

**Comment by jsha** [comment]
Also, the informational page should provide an option to try the HTTPS version of the blocked page. Or perhaps it could try fetching in the background and offer the option only if it succeeds.

I think this is better than transparently redirecting to the HTTPS version, because the HTTPS version could be different content (e.g. Forbes). Also it's a good way for users to notice that a site lacks a rule and it might be useful to write one. And most importantly, there's a very high likelihood the site will be broken under HTTPS. So we want to remind the user that they are in uncharted territory and it's not necessarily a breakage in HTTPS Everywhere.

**Comment by Hainish** [comment]
Closing due to more detailed discussion in #8239 (plus this issue has some outdated concerns)
