### ISSUE TITLE
Add osu.ppy.sh, pao-pao.net and tumutanzi.com?

### ISSUE THREAD

**Issue by lqf96** [EFForg/https-everywhere#1331]
Add osu.ppy.sh, pao-pao.net and tumutanzi.com

**Comment by lqf96** [comment]
also kenengba.com

**Comment by reedy** [comment]
Pull requests are always welcome

**Comment by PotcFdk** [comment]
Pull request for osu.ppy.sh: #1670

**Comment by PotcFdk** [comment]
Pull requests for:
... pao-pao.net: #1671 
... kenengba.com: #1672

**Comment by PotcFdk** [comment]
Pull request for tumutanzi.com: #1939

**Comment by PotcFdk** [comment]
All pull requests have been merged, this can be closed.
