### ISSUE TITLE
cravetv.ca fails part way in

### ISSUE THREAD

**Issue by ergocentric** [EFForg/https-everywhere#13317]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)
cravetv.ca media servers are not https compliant, main website is compliant

**Comment by numismatika** [comment]
This site needs an account so it is hard to solve without further details.
Which rules are active on the site?
Is there any useful hint on the browser devtols that show which requests failed?
Have you tried the TLS version at https://www.cravetv.ca ?

**Comment by ergocentric** [comment]
it seems we in Canada are still in 1997, cravetv is not supporting and not
interested in privacy

------------


Hello,

Thank you for contacting CraveTV. We are committed to maintaining the
accuracy, confidentiality, security and privacy of your personal
information. We use 'Secure Sockets Layer' to safeguard your personal info
& store your payment information in an encrypted format. The account
management pages are communicating directly with a secure server and
therefore are not required to be 'HTTPS'.

Unfortunately, video streaming is not supported on http*s*://www.cravetv.ca.
However, you will be able to visit https://www.cravetv.ca/a
ccount/subscription/subscriptions in order to add/edit your credit card
details.

We are working diligently to improve our service and in the near future,
you will automatically be redirected to the SSL version of CraveTV by
default.

If you require any assistance, please reply to this email or simply call us
at 1-888-272-8388 <%28888%29%20272-8388>from 8 AM to midnight (EST).
--
Ayushi
CraveTV Support Team

**Comment by pipboy96** [comment]
Impossible to verify without an account, most likely solved. Closing.

**Comment by ergocentric** [comment]
Cancelled account because you couldn't be bothered the fix the issues.
