### ISSUE TITLE
Rules checking is failing for every build

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#13325]
Type: other

Starting from https://github.com/EFForg/https-everywhere/commit/ef24b985c95709ce99d617b3adef6e950cca35f4, every build is failing due to the rules checking. Is the code for testing changed recently?

Ping @Hainish

**Comment by Bisaloo** [comment]
https://github.com/EFForg/https-everywhere/pull/13322

**Comment by gloomy-ghost** [comment]
Fixed by #13322
