### ISSUE TITLE
Checkbox settings do not persist

### ISSUE THREAD

**Issue by primohacker** [EFForg/https-everywhere#13335]
Type: code issue 
Toggling "Enable..." and "Block unencrypted..." check boxes do not change the state of HTTPS Everwhere. Icon color does not change when check boxes are checked/unchecked. As soon as the icon menu is closed, the settings are ignored, and do not persist. 

Same issue with fresh install from both EFF and chrome store.

I do use run Chrome virtualized with Comodo, but the same issue occurs when Comodo is disabled.

**Comment by koops76** [comment]
@primohacker Can't reproduce.

**Comment by koops76** [comment]
ping @Hainish @cowlicks.

**Comment by primohacker** [comment]
After more testing I can confirm that this is not an issue with HTTPS
Everywhere. This is an issue with how Comodo application containment treats
the extension. I'll sleuth and see if there's a why to get Chrome
extensions added to the containment white list.

Feel free to close this ticket unless you would like me to update the
ticket after I find an answer this specific use case.

**Comment by Hainish** [comment]
Thanks for taking the time to report it (even if it wasn't our bad!)
