### ISSUE TITLE
Wix.com editor problem

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#13347]
Type: ruleset issue

Domain: wix.com

From an email report:
> Unfortunately the extension HTTPS EVERYWHERE has made a serius problem in
> www.wix.com. When i loged in and ask for my editor, doesnt show the editor
> and instead ask me to log in again. I try it without the extension and
> everything works nice. I thought you might intrested this

Related: #13200

**Comment by Hainish** [comment]
I can confirm this report by creating a new account with an associated site.

**Comment by gloomy-ghost** [comment]
Also related: #9429

**Comment by Hainish** [comment]
Fix needs to be confirmed

**Comment by pipboy96** [comment]
Fix works.
