### ISSUE TITLE
Add rule for www.asrock.com

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#13374]
Type: new ruleset

Domain: www.asrock.com

Is HTTPS enabled not default.

**Comment by phuzion** [comment]
I've only found the following HTTPS-enabled domains for asrock.com with a basic Google search:

* www.asrock.com
* asrock.com
* event.asrock.com

Do you know of any other subdomains under asrock.com that are HTTPS enabled? If not, I should be able to push a PR for this today.

**Comment by Bisaloo** [comment]
Fixed by #13464.
