### ISSUE TITLE
Chrome evaluates rulesets differently than Firefox

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1339]
Steps to reproduce:
1. Edit src/chrome/content/rules/Bit.ly_vanity_domains.xml to re-enable it.
2. ./test.sh --justrun
3. Visit https://trac.torproject.org/projects/tor/ticket/15529 and click the sched.co link.
4. Note it redirects to http://advancingresearchcommunicat2015.sched.org/event/1f777424fe0cb5b8e6e78b404128b103
5. ./run-chromium.sh
6. Visit https://trac.torproject.org/projects/tor/ticket/15529 and click the sched.co link.
7. Note it redirects to http://wellnesshealthyliving.ownanewbusiness.com/1085/laci-le-beau-super-dieters-tea-natural-60-bags/

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Sched.org.xml

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Bit.ly_vanity_domains.xml

**Comment by gloomy-ghost** [comment]
Now we use the same codebase for Chrome and Firefox.
