### ISSUE TITLE
Ikea.se is broken

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#13400]
Type: ruleset issue

Domain: ikea.se

This site is broken when using HTTPSE http://www.ikea.com/se/sv/catalog/products/00308467/

**Comment by Hainish** [comment]
@jony0008 I don't see this.  What aspect of the site is broken?  Can you still purchase things?

Do you have other extensions enabled which may interfere with this page loading?

**Comment by jony0008** [comment]
@Hainish It seems to be working now, it was broken 2 days ago.

**Comment by gloomy-ghost** [comment]
closing per https://github.com/EFForg/https-everywhere/issues/13400#issuecomment-340878500
