### ISSUE TITLE
Release 2017.10.30/31 forthcoming

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#13420]
Type: other

cc @jsha @pde @J0WI @diracdeltas @jeremyn @gloomy-ghost

To be made today or tomorrow.  This is the first full WebExtensions release.

**Comment by J0WI** [comment]
#13422 might be worth to look at before the release.

**Comment by Hainish** [comment]
@J0WI I'd rather get this out the door today if possible, and want to leave time for any issues that may come up during release.  #13422 may have to wait till next release.

**Comment by Hainish** [comment]
Release has been made.  Welcome to WebExtensions. :smile:

**Comment by jeremyn** [comment]
Note to all: this version includes the new in-browser ruleset editor for contributors and maintainers that was developed in PR https://github.com/EFForg/https-everywhere/pull/12863. To access it:

* in Firefox: about:addons > HTTPS Everywhere > click somewhere in the "General Settings" area > press Ctrl-Z.
* in Chrome/Chromium: chrome://extensions/ > HTTPS Everywhere > Options > click somewhere in the "General Settings" area > press Ctrl-Z

This should open a new tab with a textarea and instructions.

Thanks for adding this, @Hainish .

**Comment by gloomy-ghost** [comment]
Pressing <kbd>Ctrl-Z</kbd> at `about:addons > HTTPS Everywhere` doesn't work for me, and if I active the shortcut at moz-extension://{UUID}/options.html an alert is shown saying a popup is blocked. I would recommand open it directly using moz-extension://{UUID}/debugging-rulesets.html.

**Comment by jeremyn** [comment]
@gloomy-ghost You have to actually click in the "General Settings" area first before pressing <kbd>Ctrl-Z</kbd>, for example you could toggle the "Show Counter" checkbox twice. I get the blocked popup message if I try <kbd>Ctrl-Z</kbd> from moz-extension://{UUID}/options.html but you should never need to go to options.html in the first place.

This feature has an intended user base of about three people, me, you, and @J0WI, and it was just written, so I think it's too early for us to start using workarounds. Let's find something we can all live with. I lobbied in PR #12863 for a more explicit option somewhere, like a clickable button, but @Hainish was firmly against that. I think having to visit some UUID URL like you suggest is too awkward.

**Comment by jeremyn** [comment]
On the other hand, in practice, once the debugging page is bookmarked, it's more convenient to use the bookmark than it is to click even an obvious button under `about:addons`.
