### ISSUE TITLE
LG Brazil website without product images in respective pages.

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13446]
Type: ruleset issue

Domain: http://www.lg.com/br/

Images are not shown in product pages, for example this monitor: http://www.lg.com/br/monitores/lg-24MT48DF-PS

Thank you.

**Comment by numismatika** [comment]
This is a CORS issue.

 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.lg.com/lg4-common-gp/fonts/lg-smart/LG_Smart_Bold.ttf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

The JS handling the images and the zoom also is blocked by CORS.
LG would be in the better position to fix this across the page.

**Comment by gloomy-ghost** [comment]
massive close per #15157
