### ISSUE TITLE
In Firefox developer tools HTTPS Everywhere tab doesn't remember visibility setting

### ISSUE THREAD

**Issue by Sesshu** [EFForg/https-everywhere#13458]
Type: code issue

Versions tested: Firefox 56.0.2 and HTTPS Everywhere 2017.10.30

Steps to reproduce:
Open the Firefox' developer tools with Ctrl+Shift+I.
Go to the options tab (the gear icon) and uncheck "HTTPS Everywhere" to hide the HTTPS Everywhere tab.
Close the developer tools.
Open up the developer tools again.

Issue: The HTTPS Everywhere tab is displayed even though it should be hidden and the "HTTPS Everywhere" option in the options menu is checked again. Hiding the HTTPS Everywhere tab is not saved.

**Comment by gloomy-ghost** [comment]
Unfortunately we can do nothing about this, see https://bugzilla.mozilla.org/show_bug.cgi?id=1394750
