### ISSUE TITLE
Expand the bot's test suite

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#13466]
Type: code issue

I've PR'd some issue bot code recently that doesn't have test suite coverage, in the interest of time. We need to backfill these tests. Specifically:

- [ ] The code that ignores issues predating the bot (#13460)
- [ ] The logic that prevents >1 edit comment from being posted (#13294)
- [ ] Inline TODOs

**Comment by pipboy96** [comment]
The bot is no longer in service. Closing I guess.
