### ISSUE TITLE
Provide dynamic loading of rulesets to allow update without browser restart

### ISSUE THREAD

**Issue by timmc** [EFForg/https-everywhere#1346]
This would be similar to how Adblock Plus filtersets are updated automatically (unless the feature is disabled.)

**That said**, I wouldn't want this feature unless ruleset updating was _at least as secure_ as updating the extension itself; an attacker who can hijack the ruleset updater can inject arbitrary JS into a user's session by offering their own redirects to malicious sites.

**Comment by reedy** [comment]
This sounds a lot like #437

**Comment by timmc** [comment]
Yes, #437 would resolve this! I only checked issues and forgot to look at PRs.

I'm not sure exactly what #1293 is; it seems to be about loading stuff from the filesystem.

**Comment by reedy** [comment]
Should we close this as a dupe?

**Comment by timmc** [comment]
Hmm... I think leave it open until the PR is completed and merged. (If #437 languishes forever or is rejected, I want this issue to stay open.)

I think #1293 is only about *user* rules, not the centrally provided ones.

**Comment by J0WI** [comment]
Since we have to move to WebextensionAPIs this is done anyway.
