### ISSUE TITLE
Rulesets Disappeared?

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#13461]
So in the latest update, I've noticed that on a lot of Google sites that its associated rulesets are missing. Is this just a temporary thing or have they been permanently removed?

![capture](https://user-images.githubusercontent.com/12680340/32319563-1fc7cdc4-c00f-11e7-8111-b02d3251f4fd.PNG)

**Comment by Bisaloo** [comment]
Google rulesets have been refactored and reorganized.

Most relevant PR are https://github.com/EFForg/https-everywhere/pull/12637, https://github.com/EFForg/https-everywhere/pull/12555, https://github.com/EFForg/https-everywhere/pull/12607, https://github.com/EFForg/https-everywhere/pull/12544 and https://github.com/EFForg/https-everywhere/pull/12536.

This doesn't just the coverage for the end user, all previously secured targets/subdomains are still secured. It just makes the maintenance of Google related rulesets easier.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment]
I can't reproduce this, I get 


> ## Stable rules         
> Force encrypted connections to these websites:
> 
> - [x] Google
> - [x] Google APIs
> - [x] Google.com Subdomains (Complex)
> - [x] Google.com Subdomains
> 
> ## Experimental rules           
> May cause warnings or breakage. Disabled by default.
>
> - [ ] Google Videos
>

**Comment by bardiharborow** [comment]
@BK1233 Are you still experiencing this?
