### ISSUE TITLE
upload plugin to addons.mozilla.org

### ISSUE THREAD

**Issue by sedrubal** [EFForg/https-everywhere#1349]
Why do you not provide this plugin through addons.mozilla.org?

**Comment by jsha** [comment]
It is available there as of a week or two ago: https://addons.mozilla.org/en-us/firefox/addon/https-everywhere/

It appears to not currently be findable through their search engine. I think that is because it is still awaiting review by Mozilla.

**Comment by sedrubal** [comment]
oh cool, thank you.
