### ISSUE TITLE
Increase nvidia.com coverage

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13496]
Type: other
http://www.nvidia.com/download/driverResults.aspx/126183/en-us

Https everywhere never redirects the above address to https despite nVidia.com (partial) ruleset being checked.
Also, the nVidia.eu (partial) ruleset should be IMO enabled by default.

**Comment by BK1233** [comment]
Not sure if it would have to with insecure scripts trying to load.

**Comment by pipboy96** [comment]
Can reproduce.

**Comment by pipboy96** [comment]
This link redirects to HTTPS now.
