### ISSUE TITLE
Manual rule not working when 'Block all unencrypted requests' is enabled

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13510]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: http://www.telegraph.co.uk/usa/

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Steps to reproduce:

1. Enable **Block all unencrypted requests** in HTTPS Everywhere
2. Navigate to [http://www.telegraph.co.uk/usa/](http://www.telegraph.co.uk/usa/
)
3. Create rule. I redirect to `example.com` as a test

<img width="427" alt="image" src="https://user-images.githubusercontent.com/7436897/32481940-a0b833f0-c3e9-11e7-8371-e4cadc4fc029.png">

4. Navigate to [http://www.telegraph.co.uk/usa/](http://www.telegraph.co.uk/usa/).

Expected: Redirect to `example.com` as per custom rule
Actual: Redirect does not fire

5. Turn off  **Block all unencrypted requests**
6. Navigate to [http://www.telegraph.co.uk/usa/](http://www.telegraph.co.uk/usa/
). The manual rule works now

The manual rule only works when **Block all unencrypted requests** is off. It doesn't work if I am using **Block all unencrypted requests**.

**Comment by pipboy96** [comment]
The example URL is already rewritten by existing rulesets.

**Comment by pipboy96** [comment]
Can't reproduce.
