### ISSUE TITLE
HTTPS rewrite is sometimes failing in Firefox

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#13535]
Type: code issue
Domain: http://phishesdotnet.blogspot.com/
Version 2017.10.30
Firefox 56 on Linux

This blog site was not forced to HTTPS when visited in FF. The `Blogspot.com blogs` rule was listed further down:
![blogspot_https_insecure](https://user-images.githubusercontent.com/5124946/32631387-186d8190-c56e-11e7-9436-30498be64318.png)

Worked in Chrome. Couldn't repro on any other blogspot.

After starting a new browsing session in FF, the issue disappeared. Could the URL rewrite have failed to load for that session?

**Comment by ihave100openPRs** [comment]
@wesdawg Seems very difficult to reproduce, maybe HTTPS-E was being updated the moment you opened that website?

**Comment by wesdawg** [comment]
@ihave100openPRs No, it was last updated a few days before the bug was observed.

**Comment by Bisaloo** [comment]
I just had a similar issue on another domain. The website was accessed over `http` and the relevant ruleset was not even listed. I tried to refresh and clear the cache several times (`ctrl+F5`) but it did not solve the issue.

I restarted Firefox and I haven't been able to reproduce.

FF 59.0a1 (2017-12-18) and HTTPS Everywhere 2017.12.6

**Comment by Bisaloo** [comment]
@Hainish, I know we don't provide much info to reproduce and help you investigate here but this looks like a major security issue.

**Comment by Bisaloo** [comment]
I had this issue again on a third domain, as shown in the following screenshots (taken today, on FF 59.0a1 (2018-01-02) with HTTPS Everywhere 2018.01.11):

![screenshot from 2018-01-12 09-49-48](https://user-images.githubusercontent.com/10783929/34867912-356ddcea-f782-11e7-9b86-6459f3bff4a4.png)

For the next screenshot, I manually typed `https` but the ruleset is still missing:

![screenshot from 2018-01-12 09-51-10](https://user-images.githubusercontent.com/10783929/34867943-5a354478-f782-11e7-86b4-1326a2a75f83.png)

I tried refreshing (`F5`), refreshing with cache clearing (`ctrl+F5`), close the tab and open the same website in a new tab and the result was still the same.

I restarted Firefox and now can't reproduce.

@wesdawg, can you update the title of this issue to better reflect the fact that this is not limited to a single domain?

@Hainish, can you confirm that you have seen this issue?

**Comment by Hainish** [comment]
This may be due to an exception being triggered, causing the extension to misbehave.  If you encounter this again, please do the following:

1. Navigate to `about:debugging`
2. Click `debug` next to HTTPS Everywhere.  If you encounter an `Incoming Connection` dialogue, click `OK`.
3. Copy the contents of the `Console` tab, and paste into this issue.

You may want to screen and sanitize the contents of step 3 for extra privacy.

**Comment by wesinator** [comment]
Just had a similar issue in Chromium 66.0.3359.181
![icanhazip_not_https](https://user-images.githubusercontent.com/5124946/41811821-e51de068-76e4-11e8-9b49-59e89f3b31ed.png)

Closing and starting a new session fixed it. Nothing in console to indicate what happened.

**Comment by pipboy96** [comment]
No further reports of issue.
