### ISSUE TITLE
spiegel.de broken in Firefox when rule for adition.com enabled

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [EFForg/https-everywhere#13531]
Type: ruleset issue
Domain: spiegel.de

Only in Firefox, unless I uncheck the default stable rule for `adition.com`, I cannot view `spiegel.de`, because a window pops up suggesting I'm using an ad blocker (which I have disabled entirely for the site). See the screenshot below:

![image](https://user-images.githubusercontent.com/10466043/32600533-3263e586-c540-11e7-9dba-974b0aadcfbe.png)

Note: The same does not happen in Chromium. Experienced on a Ubuntu 16.04 system as well as a Windows 7 system.

**Comment by ihave100openPRs** [comment]
Aren't you already enabling an adblocker (Disconnect...)?

I don't see any problem with the Adition.com ruleset https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Adition.com.xml

**Comment by AlfonsoMuskedunder** [comment]
No, spiegel.de was "whitelisted" in Disconnect in the setting above.

But I can reproduce the behavior with Disconnect disabled entirely:
![nodisconnect_w_adition](https://user-images.githubusercontent.com/10466043/32619193-3d6c7300-c57a-11e7-8e6f-d9bef25741fc.png)
![nodisconnect_wo_adition](https://user-images.githubusercontent.com/10466043/32619197-422dc498-c57a-11e7-9826-c1efd6acb2bc.png)

**Comment by numismatika** [comment]
It is a CORS issue

`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://imagesrv.adition.com/banners/1337/7000452/index.html?n=89336548. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' stimmt nicht mit '(null)' überein).`

**Comment by AlfonsoMuskedunder** [comment]
@numismatika Thanks. Could you suggest a formulation in English I could translate to German and use in an email in which I ask them to do so?

**Comment by gloomy-ghost** [comment]
massive close per #15157
