### ISSUE TITLE
https failure on u77img.b0.upaiyun.com

### ISSUE THREAD

**Issue by yfdyh000** [EFForg/https-everywhere#13532]
Type: ruleset issue

Domain: u77img.b0.upaiyun.com
e.g. http://u77img.b0.upaiyun.com/upload/201711/0312092782.jpg on http://www.u77.com/game/14183. It is broken by HTTPS Everywhere.

HTTPS Everywhere 2017.10.30 on Nightly 58.

**Comment by gloomy-ghost** [comment]
Confirmed with upyun support that u77img.b0.upaiyun.com is a default domain that doesn't provide https access as designed, we should revisit the exclusions for Upaiyun.com.xml https://github.com/EFForg/https-everywhere/blob/2b77992f492ab57cda4147b119fd1bb94048d14d/src/chrome/content/rules/Upaiyun.com.xml#L19-L23
