### ISSUE TITLE
HTTPS-Everywhere pacsun.com fails to render properly

### ISSUE THREAD

**Issue by ecooke** [EFForg/https-everywhere#1355]
When using the HTTPS-everywhere addon www.pacsun.com fails to render properly, on disabling the Demandware.edgesuite.net (partial) rule, functionality is restored.  Please advise if any additional info is required.

Firefox 37.0
HTTPS-Everywhere v5.0.1

**Comment by jsha** [comment]
Fixed by @2d1 for next release.

@2d1: I noticed you whitelisted the Demandware ruleset as not needed a ruleset coverage update. When rulesets cause breakage, I'd like to favor adding test URLs over whitelisting, since they are likely to break again.
