### ISSUE TITLE
Stuttering video on Vimeo (Akamai rules)

### ISSUE THREAD

**Issue by IBBoard** [EFForg/https-everywhere#1357]
If I watch a video on Vimeo (e.g. https://vimeo.com/122325664) with HTTPS Everywhere enabled then I get a few minutes in and the video starts to stutter and jump. If I disable HTTPS Everywhere, or keep it enabled but disable the Akamai rules, then the vide seems to play through smoothly with no issue.

It can happen as early as a minute in to the video, but normally by about 10 minutes in at the latest. The stuttering tends to get worse if you try to watch through it. Memory usage seems quite stable, but CPU usage spikes as it stutters.

Given that Akamai is a big CDN then I'd obviously rather keep it enabled, but if I want to watch any videos then I currently have to disable the rule.

System: openSUSE 13.2, Core i5 4570, GeForce 620 (proprietary drivers), 8GB RAM.
Software: Firefox 36.0.4, HTTP Everywhere 5.0.1. Also running AdBlock Plus, Ghostery and a few other extensions, but as mentioned above then everything still seems to work okay if they're enabled but HTTPS Everywhere is disabled.

**Comment by semenko** [comment]
Thanks for the report! This seems to work for me now, so tentatively closing.

Please feel free to reopen if you see this with the latest version!

**Comment by IBBoard** [comment]
It's not a perfect re-test as I've since upgraded my graphics card, but I can confirm that the video seemed to play through okay (although I now realise that that video was a terrible example as it has a stuttery jumpy style at the beginning anyway!).
