### ISSUE TITLE
Divert from FB

### ISSUE THREAD

**Issue by szymon1051** [EFForg/https-everywhere#13589]
Type: other

Domain: facebook.com

Translator google :).

Does not redirect me when trying to open something with facebook when I have https-everywhere turned on and how to disable it anyway. There is something like this:
https://l.facebook.com/l.php?u=https%3A%2F%2Fsprzedajemy.pl%2Fgniazdopower-port-3-gniazda-hdmi-usb-vga-rj45x2-alum-80-wesola-a1d299-nr50038912&h=ATP5NBQqFMgJ_VAj2JDqd_x-UiCFnCs5a4sQmzdo85BKbk_NaJn3QXRarNxDj2z9ae88aUHh-FL0CQAuu8budkxk1CIY-AQf3alV_wGSIn50WLqWJIpVgv_gcl51tCF0YQG5lbOl6m3K
If you refresh the page it will sometimes load.

Orginal text:
Nie przekierowywuje mnie kiedy próbuje otworzyć coś z facebooka, gdy mam włączone https-everywhere, a jak wyłącze już tak. Zostaje mi coś takiego:

Jeżeli odśwież stronę to się czasami wczyta.

**Comment by pipboy96** [comment]
Not clear what is the issue.
