### ISSUE TITLE
Counter is shown when "Show Counter" is unticked

### ISSUE THREAD

**Issue by bronsen** [EFForg/https-everywhere#1358]
conversely, the counter is NOT shown when "Show Counter" is ticked. This is unexpected behavior.

This is HTTPS-Everywhere 5.0.1 on Firefox 37.0

**Comment by jsha** [comment]
That's strange! I wasn't able to reproduce. Does this persist across browser restart?

**Comment by bronsen** [comment]
After a browser restart the counter is only shown when the option is ticked.

**Comment by anewuser** [comment]
I usually keep the icon hidden, but today I enabled it and having the same problem. Restarting Firefox 38 didn't fix it. Maybe there's some mistake in the function that checks for this toggle?
