### ISSUE TITLE
ScienceDaily broken images

### ISSUE THREAD

**Issue by larryedwards** [EFForg/https-everywhere#1359]
I am using HTTPS Everywhere in the CyberFox browser (which works on top of FireFox).

The main graphics on a website I frequently visit have stopped displaying, and I tracked the problem down to HTTPS Everywhere 5.0.1.  I have had this addon installed for quite some time, so either it must have updated itself to this version or there is a conflict with a recent Windows update. (I use Win7 x64).

A webpage you can test the problem on is http://www.sciencedaily.com/releases/2015/04/150402161650.htm.  I was unable to see the image of the typhoon.

**Comment by jsha** [comment]
Thanks for the report! It looks like there's a problem with the 
ScienceDaily ruleset. I'll disable it for the next release. In the 
meantime you can disable it yourself by clicking on the HTTPS Everywhere 
icon, and then clicking on the "ScienceDaily" menu item.

**Comment by larryedwards** [comment]
I just now tried that (thanks for the suggestion). Neither selection (X or check-mark) fixes the problem.

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
