### ISSUE TITLE
embed.ly (partial) broken ruleset

### ISSUE THREAD

**Issue by hpr** [EFForg/https-everywhere#13606]
Type: ruleset issue

Domain: embed.ly
Domain: letsrun.com

With the embed.ly (partial) ruleset enabled on an example page here, the page previews do not appear as they should: [http://www.letsrun.com/forum/flat_read.php?thread=8539375](http://www.letsrun.com/forum/flat_read.php?thread=8539375)

![incorrect](https://user-images.githubusercontent.com/451912/32859754-62a03ec0-ca1d-11e7-9db0-ebc5b0afd08d.png)

This is what the page looks like if I disable the embed.ly (partial) ruleset, as it should:

![correct](https://user-images.githubusercontent.com/451912/32859755-62b81f54-ca1d-11e7-9727-0bb723c6a702.png)

**Comment by Bisaloo** [comment]
That ruleset should be disabled. Which version of HTTPS-Everywhere are you using?

**Comment by hpr** [comment]
I'm using version 5.2.8, which is the default version included with PureOS's PureBrowser (which itself is based on Debian testing).

**Comment by Bisaloo** [comment]
That version is [*severely* outdated](https://github.com/EFForg/https-everywhere/releases/tag/5.2.8). Do you know how we can report this to PureBrowser?

**Comment by hpr** [comment]
@Bisaloo -- Thanks, I just realized that and agree with you. Tag is [here](https://tracker.pureos.net/tag/purebrowser/), but I think the relevant bug would be [this one](https://tracker.pureos.net/T147). I had to register and wait for account approval before I could comment on issues but they approved me within minutes.

**Comment by Bisaloo** [comment]
Closing as this is not our bug. Dependencies are now tracked on the wiki. PureOS is repackaging PureBrowser so hopefully they will fix this. Out-of-band ruleset updates will take care of this issue in the future.
