### ISSUE TITLE
ruleset for filehippo

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13613]
Type: new ruleset

Domain: filehippo.com

**Comment by BK1233** [comment]
FileHippo is already HTTPS by default.

**Comment by jeremyn** [comment]
It's a valid target since it's not in the HSTS preload list. See https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages.

**Comment by J0WI** [comment]
closed by #13728
