### ISSUE TITLE
Developer-tools "switch planner pane" visibility preference not stored

### ISSUE THREAD

**Issue by wavexx** [EFForg/https-everywhere#13611]
Type: code issue

The "HTTPS Everywhere" pane which is added to the developer tools is enabled by default.

By going to the developers tools preference, you can switch it off, but the setting is not remembered/stored. As soon as the developer tool pane is closed/reopened, the pane re-appears.

This is happening with both FF56 and 57, with the latest available web-extension.

If the setting is not remembered due to a bug in FF, it should be hidden by default, as it's a nice feature to have, but I'd rather have more space for the other panes.

**Comment by Hainish** [comment]
This is a bug in WebExtensions, not HTTPS Everywhere.  It is fixed in Firefox 61: https://bugzilla.mozilla.org/show_bug.cgi?id=1394750
