### ISSUE TITLE
April 1 update broke speedtest.net

### ISSUE THREAD

**Issue by NJC2** [EFForg/https-everywhere#1362]
After the April 1 update, I get a "Configuration Load Failed" error on the speedtest.net site.  If I disable HTTPS Every-where the site loads normally.

**Comment by reedy** [comment]
Which browser?

**Comment by NJC2** [comment]
Firefox 36.x and now with 37, both Windows and Linux (Ubuntu 12.04).  This is the main page with HTTPS-Everywhere enabled:
![speedtest_httpse_on](https://cloud.githubusercontent.com/assets/6441752/6995769/c6f65432-db22-11e4-8086-e5905edbf52c.png)

Same page with HTTPS-Everywhere disabled:
![speedtest_httpse_off](https://cloud.githubusercontent.com/assets/6441752/6995770/dd7a107c-db22-11e4-98a1-3b218b88604f.png)

Or if I just disable the rule "Speedtest.net (partial)" it also works:
![speedtest_httpse_partial_off](https://cloud.githubusercontent.com/assets/6441752/6995771/f8616fe8-db22-11e4-96b5-32aa64a17519.png)
