### ISSUE TITLE
ruleset for cnn.com

### ISSUE THREAD

**Issue by alex** [EFForg/https-everywhere#13646]
Type: new ruleset

Domain: cnn.com

They haven't officially announced it as far as I can tell, nor do they redirect http:// to https:// themselves, but it seems to work just fine on `www.cnn.com` (other subdomains not explored).

**Comment by jeremyn** [comment]
@alex Thanks for your report, however this should be covered by recent changes to `CNN.com.xml` (see PR https://github.com/EFForg/https-everywhere/pull/13048), so I'm closing this issue.

**Comment by alex** [comment]
Oh, awesome, thanks!
