### ISSUE TITLE
Wrong Badge Count Number

### ISSUE THREAD

**Issue by mexesa** [EFForg/https-everywhere#13663]
I am using latest version of HTTPS Everywhere and Firefox ESR on Windows 10.

Every time, when I load amazon.co.uk amazon.de amazon.es or similar the count is 1. When I clicked on the HTTPS Everywhere icon, I have the drop menu and I see there are actually 2. If I refresh the page, the count is changing to 2, like shut be.

If I close Firefox open it and load the same page, I see number 1 on the badge for count. When I click on the HTTPS Everywhere icon, again inside the addon the number is 2.

**Comment by mexesa** [comment]
The extension is with default settings.

Please follow each step to reproduce the issue:
1-Firefox have to be closed. 
2-Open Firefox and see the blue icon, which represent the HTTPS Everywhere add on and the number count badge.
3-Load for example amazon.co.uk and see the number of the badge. It's number 1.
4-left mouse click on the HTTPS Everywhere icon and you'll have drop down menu, where you can see to enable the HTTPS Everywhere or to block all unencripted request. There you'll see the Stable rules section also. Under the stable rule section, you'll have 2 entry's AmazonWebServices and Amazon.co.uk. So, that's mean we have 2 rules but the number on the HTTPS Everywhere blue icon, the count is 1. If I refresh the page I have number 2 on the badge and number 2 under the stable rules section.
Hopefully, that make difference.

**Comment by jeremyn** [comment]
I can't reproduce this. Also, without other extensions, HTTPS Everywhere at https://www.amazon.co.uk loads more than ten rulesets for me, mostly ad/tracker/social media rulesets.

Can you reproduce this problem with a new profile (`about:profiles`) with only HTTPS Everywhere installed? If not, then you may have some kind of extension conflict in your main Firefox profile.

**Comment by Bisaloo** [comment]
I can somewhat reproduce. 

When I visit https://www.amazon.co.uk, I see 2 rulesets:

- `AmazonWebServices`
- `Amazon-adsystems.com (partial)` 

`Amazon-adsystems.com (partial)` seems to be used a couple a seconds after page load. After the counter is set.

**Comment by wonderchook** [comment]
I've tried to reproduce this with ESR (64-bit) and Windows 10 and have been unable. 

The count seems to be kept up to date as the various components load.

**Comment by Bisaloo** [comment]
Indeed, I can't reproduce on a fresh profile. I may do some digging later to try and find out what may be causing this.

**Comment by tofupe** [comment]
Maybe this is something to do with the some timeout for this number badge indicator.
Did somebody know  if there is some time out?
Other extension, like uBlock the number badge is changing constantly.

**Comment by Bisaloo** [comment]
Okay, I found simple steps to reproduce:

1. Create a fresh profile
2. Install HTTPS-Everywhere
3. Install uMatrix
4. Block `amazon-adsystem.com` in uMatrix (it should already be the case by default)
5. Visit https://www.amazon.co.uk/
6. Two rulesets will be listed but the badge displays `1`. This is updated as soon as you change tabs and come back again.

**Comment by pipboy96** [comment]
Badge has been removed.
