### ISSUE TITLE
Update hsts-prune to use preload policies

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#13682]
Type: feature request

The HSTS preload list has added a tag to indicate under which policy a given domain was added (see https://github.com/chromium/hstspreload.org/issues/111 and [this diff from the Chromium codebase](https://chromium.googlesource.com/chromium/src/+/4bf96c30121ed23f8025e0a2ee6c68831fd0786f%5E!/)).

It would be great if `hsts-prune.js` could use this new info to remove more domains. More specifically, domains with a special policy, such as `google`, `custom` or `public-suffix-requested` should be removed automatically, without the need to check for the presence of the required headers.

Related: https://github.com/EFForg/https-everywhere/issues/13235

**Comment by cschanaj** [comment]
cc @Hainish

**Comment by Hainish** [comment]
See https://github.com/chromium/hstspreload.org/issues/111#issuecomment-363957772

**Comment by J0WI** [comment]
I don't like the "special policies" used by some browser vendors for their own domains. There is no guarantee that they're all handled well across all browsers. It's also not clear what policies are added or kept in forks of these browsers.

**Comment by pipboy96** [comment]
@J0WI Same here, especially since Chrome devs have deprecated static pinning of CA keys for every website except Google-owned ones.
