### ISSUE TITLE
Mixed content on Secunia.com

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#1368]
https://secunia.com/vulnerability_scanning/personal/

**Comment by strugee** [comment]
All that's being blocked is some fonts. IMHO, this isn't a big enough issue to disable the ruleset.

**Comment by nyuszika7h** [comment]
And also some ads apparently, but that's their problem ;)

**Comment by strugee** [comment]
> And also some ads apparently, but that's their problem ;)

No, I saw those, and they aren't being blocked. Just logged.

**Comment by jsha** [comment]
Sounds good, not fixing.
