### ISSUE TITLE
GitHub Pages occasionally has Mixed Content problems

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#1369]
The GitHub Pages ruleset says that _all_ GitHub Pages content should be TLS'd. However, this can occasionally cause Mixed Content Blocker problems. GitHub Pages content is by definition open source, so it's easy to send a PR, but not everyone knows how to do that.

The fix for this is obviously to just disable that rule except on platforms that allow Mixed Content, but then we lose a huge amount of coverage for the GitHub Pages sites that _do_ perform OK under a MCB browser. Thoughts on this tradeoff?

**Comment by strugee** [comment]
See also #273

**Comment by jsha** [comment]
Good question. Are there specific examples of popular GitHub Pages that are seriously broken by MCB?

**Comment by strugee** [comment]
Not any particularly popular ones that I know of, but I run into them occasionally and the result is not pretty.

Personally, I suspect that the tradeoff of turning the rule off isn't worth it, but I thought I'd bring it up to see if others disagree.

**Comment by jsha** [comment]
That's my feeling also. We should definitely have a list of test URLs that do work properly on GitHub Pages, and as Pages crop up that trigger MCB we can `exclusion` them. We should probably come up with a more general means of deciding when to apply rules to large user-content spaces that may or may not trigger MCB.

**Comment by strugee** [comment]
Sounds good. Another thing that could be done is to add an Observatory-like feature for MCB reporting.

**Comment by strugee** [comment]
Assuming that EFF can support that infrastructure, of course.
