### ISSUE TITLE
Changelog doesn't mention any explanation of the new required permission

### ISSUE THREAD

**Issue by magicgoose** [EFForg/https-everywhere#13705]
Type: other

<img width="376" alt="screen shot 2017-11-22 at 20 36 33" src="https://user-images.githubusercontent.com/1442206/33144257-16b56744-cfc5-11e7-8561-176be7b4cc40.png">

The latest update is asking for new permission, as seen on the screenshot above.
I tried to find any reasoning behind this on the changelog (https://www.eff.org/files/Changelog.txt) to no avail. (sorry if I simply overlooked it)

I think this should have an explanation.

**Comment by ihave100openPRs** [comment]
This is due to https://github.com/EFForg/https-everywhere/pull/13560 I think.

You can see its effect when you open the developer tools in Firefox and there's an "HTTPS Everywhere" right there.

**Comment by magicgoose** [comment]
hmmm, I don't see anything that looks like a permissions change in the diff of the linked pull request. But that's probably because I am not proficient in JS and extension development.  
And it's also odd that, while I didn't upgrade yet (I am using the latest version which didn't require this permission), I still have HTTPS Everywhere in the dev tools in Firefox, and it's showing something there. If it needs a permission to do that then it wouldn't work, right?

**Comment by ihave100openPRs** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/13817

**Comment by pipboy96** [comment]
This is due to Switch Planner the extension adds to DevTools.
