### ISSUE TITLE
Trivialize custom rules on creation when possible

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#13713]
Type: feature request

Currently, when users create a custom rule using the UI, the rule follows includes the hostname even when a trivial `<rule from="^http:" to="https:" />` would be possible.

[Code handling the creation of custom rules](https://github.com/EFForg/https-everywhere/blob/master/chromium/popup.js#L196)

**Comment by koops76** [comment]
@Hainish [closed a PR which did the same thing.](https://github.com/EFForg/https-everywhere/pull/12754#issuecomment-332023244)

**Comment by Bisaloo** [comment]
The idea of this issue is slightly different. I don't think we should change the UI and the text fields, for the reason stated in https://github.com/EFForg/https-everywhere/pull/12754#issuecomment-332023244.

However, we could trivialize rules when the user clicks "Add a new rule for this site".

**Comment by jeremyn** [comment]
@Bisaloo Please fix the markup in your first comment, for clarity.

**Comment by jeremyn** [comment]
I don't use the "Add a rule" functionality and in fact I find it mildly confusing when I look at it. That said, unless there is some evidence that a lot of users out there have a problem with the existing behavior, I think we should leave it as it is.

**Comment by Bisaloo** [comment]
@jeremyn, I don't think we are talking about the same thing.

I am not proposing to change the UI here (that would be a topic for another issue), just the underlying code for better performance.

**Comment by jeremyn** [comment]
In that case I'm not sure what you want to do. Do you want to change [this](https://github.com/EFForg/https-everywhere/blob/bc0f3557a8c578682cd07722ffe9c4be7d7a1113/chromium/popup.js#L197):

```javascript
    e("new-rule-redirect").value = `https://${url.host}/`;
```

to this?

```javascript
    e("new-rule-redirect").value = `https:`;
```

Is that meaningfully faster?

**Comment by Hainish** [comment]
@Bisaloo thanks for your attentiveness.  The trivialized rules present a huge performance boost under normal circumstances, given the 17,480 active rulesets.  For this to be anything but a micro-optimization, a user would have to add at the very least hundreds of rulesets.  The addition of this logic in the code can also make it harder to read, for a relatively minimal gain.  I'm inclined to think the tradeoff isn't worth it.
