### ISSUE TITLE
Ruleset debugger can't be opened in Firefox

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#13731]
Type: code issue

HTTPS Everywhere 2017.11.21
Firefox 57
Windows 10

In Firefox, a debugging page `debugging-rulesets.html` is supposed to open when you go to `about:addons` > HTTPS Everywhere > click under `General Settings` > press <kbd>Ctrl-Z</kbd>. Chrome has similar functionality. This works on Firefox/Linux, Chrome/Linux, and Chrome/Windows, but not Firefox/Windows. Instead, nothing happens.

Ping @Hainish .

**Comment by jeremyn** [comment]
I found that the debugger will appear in Windows if I allow popups (`about:preferences#privacy` > uncheck `Block pop-up windows`). This isn't required in Linux, meaning the debugger will still open even with this box checked.

**Comment by Hainish** [comment]
I don't think there's much we can do about this, other than making ruleset maintainers & contributors aware that the debugging page exists and manually directing them to it.  This could be added to `CONTRIBUTING.md`.

**Comment by Hainish** [comment]
The debugging page seems useful for both groups, and as such could probably be added to `CONTRIBUTING.md` under https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#new-rulesets

**Comment by jeremyn** [comment]
@Hainish Do you know why the debugging page opens with popups blocked on Linux but not Windows? Maybe there is a bug, or maybe there is some extra permission we could request on Windows.

**Comment by Hainish** [comment]
@jeremyn I'm not sure why.  I don't have a Windows system to test with, but I did just order a testing unit which will arrive on Friday, I can have a closer look then.  This will also facilitate https://github.com/EFForg/https-everywhere/issues/13815, if we do decide to support Windows 10.

**Comment by Hainish** [comment]
I am aware of the free Windows Edge VMs which run Windows 10, but unfortunately my current setup does not support this either.

**Comment by jeremyn** [comment]
There's also https://www.browserstack.com/test-on-microsoft-edge-browser#live-cloud , which is recommended by the Microsoft site you link.

**Comment by jeremyn** [comment]
Never mind, I realize now that you're looking for the Windows 10 VM to test on Firefox, not to test on Edge specifically.

**Comment by jeremyn** [comment]
You can download a Windows 10 ISO from Microsoft at https://www.microsoft.com/en-us/software-download/windows10ISO and use that to install into a VM. Of course licensing is an issue but this is another option and it doesn't involve buying new hardware. (I'm also not sure whether installing Firefox onto the Edge VMs is allowed by the Edge VM license either.)

**Comment by Hainish** [comment]
Thanks for linking me to that @jeremyn.  For some reason it still isn't working in Qubes (xen) though.  The VM looks like it's booting up with the startup windows logo, then just shuts down immediately thereafter.  I'll see what I can do after I get the new hardware.

**Comment by jeremyn** [comment]
@Hainish Have you gotten a chance to confirm the problem on Windows 10? Or maybe @wonderchook ? It should be very easy to test.

**Comment by wonderchook** [comment]
I just tried this with pop-ups blocking turned on and the debugger came up fine with no issue. 

I'm using FIrefox 52.5.0 and Windows 10.0.16299

**Comment by jeremyn** [comment]
@wonderchook Can you please try it with Firefox 57?

**Comment by wonderchook** [comment]
I can confirm this is an issue if pop-up blocking is turned on with Firefox 57

**Comment by jeremyn** [comment]
Thanks!

**Comment by Hainish** [comment]
Apologies, this is taking me a while to address.  I have a Win10 testing machine now, but won't be able to get to this until Friday.

**Comment by Hainish** [comment]
Though if this is a new security measure added to Firefox 57 in Windows 10, my suspicion is we may not be able to bypass it.

**Comment by jeremyn** [comment]
It would be good to confirm that this is intentional behavior in Firefox, and not a bug on our side. Can you just ask someone at Mozilla if Firefox/Windows handles popup blocking differently than Firefox/Linux?

**Comment by Hainish** [comment]
I don't have any special access to the Windows engineers at Firefox.  Opening a ticket on bugzilla is probably the quickest way to an answer.

**Comment by jeremyn** [comment]
@Hainish Are you going to open the Bugzilla ticket? You usually interact with Mozilla when needed.

**Comment by Hainish** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429624

**Comment by jeremyn** [comment]
I'm closing this issue in favor of the Bugzilla ticket that @Hainish opened (thanks @Hainish ).

**Comment by pipboy96** [comment]
See also #17352.

**Comment by pipboy96** [comment]
Reopening due to inactivity in Bugzilla ticket.

**Comment by FranklinYu** [comment]
Is this fixed?

**Comment by pipboy96** [comment]
@FranklinYu Yes.

**Comment by FranklinYu** [comment]
Is it fixed in Firefox or in HTTPS Everywhere? Has the fix been deployed? I failed to verify the fix right now.

**Comment by pipboy96** [comment]
@FranklinYu No, waiting for next release.

**Comment by Hainish** [comment]
This has been marked as a `regression` in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1429624
