### ISSUE TITLE
Redirection conflict with Google Publisher Toolbar extension

### ISSUE THREAD

**Issue by PixelDawg** [EFForg/https-everywhere#13742]
Type: code issue

Conflict between HTTPS Everywhere Version 2017.11.21 and Google Publisher Toolbar Version 5.0.2.4 in Chrome Version 61.0.3163.100 (Official Build) (64-bit).

Google Publisher Toolbar reports the following error:

```
Warning:
This extension failed to redirect a network request to http://ad.doubleclick.net/ddm/ad/jrym/;ord=1511315166501?dpt=1 because another extension (HTTPS Everywhere) redirected it to https://ad.doubleclick.net/ddm/ad/jrym/;ord=1511315166501?.

```

**Comment by pipboy96** [comment]
@PixelDawg Does the issue still persist?
