### ISSUE TITLE
Shopify stores don't work with HTTPS everywhere

### ISSUE THREAD

**Issue by speedbunny** [EFForg/https-everywhere#13756]
Type: ruleset issue
Domain: https://*.myshopify.com/admin/ & Shopify sites.

Cannot log in to admin of Shopify sites and inconsistent browsing experience when browsing stores with HTTPS everywhere enabled.

**Comment by youdly** [comment]
ping @bouk

**Comment by bouk** [comment]
@speedbunny could you email me at bouke@shopify.com with some more information about which specific shops you have trouble with, and what is broken? Thanks

**Comment by pipboy96** [comment]
Every `myshopify.com` subdomain I found redirects to a second-level domain. Errors in question do not seem to exist anymore.
