### ISSUE TITLE
popehat.com has broken SSL, but has a HTTPS Everywhere rule. So, it's unreachable if you have HTTPS Everywhere

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#1375]
popehat.com apparently has broken SSL currently. I get SSL errors in Firefox, Chrome, & IE when I try to visit https://www.popehat.com/ and https://popehat.com/

HTTPS Everywhere has a rule that forces popehat to SSL, so it's currently completely unreachable if you have HTTPS Everywhere installed (unless you disable the rule).

**Comment by dholbert** [comment]
(For the record, the popehat HTTPS everywhere rule was added in Dec 2014 in commit b8fb139 , by @2d1)

**Comment by dholbert** [comment]
(Though that file may have just recently shipped for the first time; I'm not sure what the HTTPS Everywhere release cadence is like, but the commit page has "chrome-2015.3.31" at the top, which suggests it may've just shipped in the past few days.)

Locally, I've got HTTPS Everywhere 5.0.1, last update received 2015-04-02.

**Comment by dholbert** [comment]
Twitter thread (reporting the issue to popehat), for reference: https://twitter.com/CodingExon/status/585308489465008128

**Comment by 2d1** [comment]
"For the record", it was working when I added it. Feel free to open a pull request disabling it.

**Comment by dholbert** [comment]
Thanks!
