### ISSUE TITLE
redirection does not work properly with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by realsobek** [EFForg/https-everywhere#13765]
Type: other

Domain: translate.megaglest.org

The URL:
http://translate.megaglest.org/
should redirect to:
https://docs.megaglest.org/MG/Translations

but with "HTTPS Everywhere" enabled it does not redirect properly.
On Parabola with GNU IceCat 52.3.0 (64-bit)
HTTPS Everywhere 5.2.21
it redirects to:
https://docs.megaglest.org/MGTranslations

On Mac OS X with Mozilla Firefox 57.0 (64-bit)
HTTPS Everywhere 2017.11.21
it redirects to:
https://docs.megaglest.org/MegaGlestTranslations

Is this a bug in "HTTPS Everywhere"?

Disabling the extension makes redirection work properly in both cases.

I talked to Tom Reynolds from MegaGlest and we came to the conclusion that I file this bug report.
Tom:
This is the series of redirections I get to see here (indeed a lot):
> $ curl --head --location http://translate.megaglest.org/
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.6.2
> Date: Fri, 17 Nov 2017 18:53:26 GMT
> Location: http://wiki.megaglest.org/Translations
> X-IPLB-Instance: 10216
>
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.6.2
> Date: Fri, 17 Nov 2017 18:53:26 GMT
> Location: http://docs.megaglest.org/MG/Translations
> X-IPLB-Instance: 10215
>
> HTTP/1.1 301 Moved Permanently
> Date: Fri, 17 Nov 2017 18:53:31 GMT
> Content-Type: text/html
> Content-Length: 178
> Connection: keep-alive
> Keep-Alive: timeout=20
> Location: https://docs.megaglest.org/MG/Translations
> Server: MegaGlest 61.357
>
> HTTP/1.1 200 OK
[where the actual HTML page is then rendered]

Me: 
https://wiki.megaglest.org
is not reachable.
Could this be the problem?
Shall I file a bug report to the extension?

Tom:
I cannot remotely disagnose which part of the client software is the problem here - but I agree that "HTTPS Everywhere" is the most suspect based on your report. https://wiki.megaglest.org will indeed not work, there is no HTTPS configured there at this time. We could change this, but not to work around a bug in client software (but we could do it to enable more use of HTTPS and the general move towards replacing HTTP by HTTPS).

**Comment by heuser443** [comment]
Problem was that http://wiki.megaglest.org/Translations redirects to https://docs.megaglest.org/MG/Translations (prefix the path with `/MG/`) but http://wiki.megaglest.org/ to https://docs.megaglest.org/MG (set the path to `/MG`- no trailing slash). The ruleset in HTTPS Everywhere only had the last case covered (and the last revision of the ruleset erroneously also included the redirect from https://docs.megaglest.org/MG to https://docs.megaglest.org/MegaGlest causing the different results with different versions),

**Comment by realsobek** [comment]
Thank you for fixing the issue :)

**Comment by jeremyn** [comment]
HTTPS Everywhere doesn't redirect https://translate.megaglest.org anymore (see the [current ruleset](https://github.com/EFForg/https-everywhere/blob/1b188bd07a58a60efe2b5385d6349c08e85d8f95/src/chrome/content/rules/MegaGlest.org.xml)), so I'm closing this issue.
