### ISSUE TITLE
ikea.com falls apart

### ISSUE THREAD

**Issue by torzsmokus** [EFForg/https-everywhere#1377]
https-everywhere completely breaks ikea.com
(unreadable page, tons of 404 in console)
seems that internal redirects (307) to secure.ikea.com cause the failure.

**Comment by torzsmokus** [comment]
![ikea1](https://cloud.githubusercontent.com/assets/641862/7020281/0b4e4c92-dd18-11e4-8547-f4cfa2ee694c.png)
![ikea2](https://cloud.githubusercontent.com/assets/641862/7020282/0b5a0b0e-dd18-11e4-8801-db7d510550c2.png)
![ikea3](https://cloud.githubusercontent.com/assets/641862/7020280/0b321982-dd18-11e4-92bb-36cd2d67243e.png)

(everything is OK when I turn off HTTPS everywhere for ikea.com)

**Comment by 2d1** [comment]
Broken in ff1710aea7086c6258f28cf5d65f73ab65088e96. The comment makes it appear intentional.

**Comment by semenko** [comment]
Oof, definitely my fault. Non-capturing in exclusions should work, but definitely not in rulesets :/

**Comment by jsha** [comment]
@semenko: BTW, the latest style guide recommends using capturing groups for readability. We've had some debate over the performance impacts of capturing vs non-capturing, but no numbers so far. Could you run some perf experiments?

**Comment by jsha** [comment]
Also could you send a pull request reverting the change?

Thanks,
Jacob

**Comment by semenko** [comment]
Yep -- will try to take care of both tomorrow.
