### ISSUE TITLE
[Naver.com] New Ruleset

### ISSUE THREAD

**Issue by nadoboeg** [EFForg/https-everywhere#13780]
Type: new ruleset

Domain: section.blog.naver.com
Domain: blog.naver.com
Domain: m.blog.naver.com
Domain: blog.me
Because blog.naver.com, section.blog.naver.com, blog.me offer https connection.
e.g
http://blog.naver.com/dnd -> https://blog.naver.com/dnd
http://naver_diary.blog.me -> https://naver_diary.blog.me

**Comment by Bisaloo** [comment]
Related: #12597
