### ISSUE TITLE
Tests Fail on OSX due to sha1sum not found

### ISSUE THREAD

**Issue by wonderchook** [EFForg/https-everywhere#13794]
(this is a low priority for me)
Type: code issue

I tested installing for dev on OSX. I was able to get install-dev-dependencies.sh to work without too much issue. When I go to run the tests though I run in to `./make.sh: line 150: sha1sum: command not found`

After a little research is appears shasum could be used instead on OSX, so perhaps a minor issue. I was able to get further by [linking to shasum](https://superuser.com/questions/734411/how-to-get-sha1sum-to-work-on-mac-os-x), but then ran into other errors. I'm not really a Mac person, so I stopped there.

**Comment by J0WI** [comment]
This has been fixed in #15206
