### ISSUE TITLE
Broken redirect for gftrib.com

### ISSUE THREAD

**Issue by valdisk** [EFForg/https-everywhere#13797]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: gftrib,com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Redirecting http://gftrib.com to https://gftrib.com results in timeouts.  Site does answer on port 80.

Not sure if this is a transient issue, or if the ruleset never worked to begin with.

**Comment by bardiharborow** [comment]
gftrib.com is hosted by Bit.ly, which had [an downtime incident](http://status.bitly.com/incidents/w5rsv9bjjh5p) around the time you reported this. The issue has been resolved now.

**Comment by Bisaloo** [comment]
Confirmed fixed. Feel free to reopen if you still have issues.
