### ISSUE TITLE
Getting different pages from ow.ly with HTTPSEverywhere enabled

### ISSUE THREAD

**Issue by vpodzime** [EFForg/https-everywhere#1380]
When trying to load http://ow.ly/JGFLT I get different pages/results with HTTPSEverywhere enabled and disabled.

**Comment by jsha** [comment]
What version of HTTPS Everywhere are you running? The relevant ruleset
was disabled in the latest release, 5.0.1 / 2015.3.31.

**Comment by vpodzime** [comment]
*About HTTPS Everywhere* says ``5.0``. Firefox's *about:addons* says ``Last updated 04/04/2015``. If I go to addon's preferences (which btw completely freezes Firefox for like 10 seconds) and type ``ow.ly``, I see one enabled rule.

**Comment by vpodzime** [comment]
And the rule stays enabled even if I click the *Reset to defaults* button. Disabling the rule doesn't make a difference for the URL above.

**Comment by jsha** [comment]
In about:addons, under the Extensions tabs, can you click the wrench/screwdriver icon and select "Check for Updates?" That should update you to the latest version.

**Comment by vpodzime** [comment]
That only says *"No updates found"* and I have auto-update enabled for addons. I don't think the problem is an old version. If you guys number versions how I think you do, ``Last updated 04/04/2015`` should be okay for version ``2015.3.31``. Or are Firefox addon versions limping behind?

**Comment by jsha** [comment]
It should be okay in theory, but you said that _About HTTPS Everywhere_ has version 5.0. It should be version 5.0.1. Did you install from the EFF website or addons.mozilla.org? Either should be fine and should update normally.

Versioning: Unfortunately Chrome and Firefox have different versioning systems. We number Chrome with dates and Firefox with semantic versions. The correspondence is in https://www.eff.org/files/Changelog.txt:

```
Firefox 5.0.1 / Chrome-2015.3.31            (2015-03-31)
Firefox 5.0 / Chrome-2015.3.23              (2015-03-23)
```

That said, it's possible that your Firefox install did check addons on 4/4 but didn't get 5.0.1 for some reason.

You could also try installing fresh from https://www.eff.org/https-everywhere/

**Comment by vpodzime** [comment]
It's weird, but I can confirm that installation from https://www.eff.org/https-everywhere/ updates the addon and fixes the issue. I think this issue can be closed. Thanks for the help!
