### ISSUE TITLE
Explain why we need extension permissions

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#13817]
Type: other

Our current permissions, in `manifest.json`, are:

> "permissions": [ "webNavigation", "webRequest", "webRequestBlocking", "tabs", "cookies", "storage", "*://*/*" ],

We should explain why we need these permissions on our website somewhere.

**Comment by Hainish** [comment]
Note: this can be done by anyone, given that our FAQ is generated from a template in https://github.com/EFForg/https-everywhere/issues/13762#issuecomment-348364038.  I'll just need to be pinged to actually update the eff.org FAQ based on this template.

**Comment by fabianfrz** [comment]
Please note that I am not a native speaker but here are some 

webRequestBlocking: The permission to block requests is required for blocking HTTP requests in HTTPS only mode. A single HTTP request can leak information about your browsing history to an eavesdropper. An example is the referrer header which includes the URL from the website from which the request originated. Browsers like Firefox do not allow active content like scripts to be loaded via HTTP on a HTTPS site (only images etc.) but it is still possible to manipulate this content.

cookies: Cookies (small data chunks sent with each request) supports a flag to send them only over TLS connections. Cookies are used for managing sessions on top of stateless HTTP to allow things like logging into a website, store preferences or tracking. This permission is required to set the flag to sent cookies only via TLS if the server does not set it by itself.

**Comment by zoracon** [comment]
This has been addressed here: https://www.eff.org/https-everywhere/faq#https-everywhere-asking-for-my-website-data
