### ISSUE TITLE
Ruleset for cnn.com

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#13825]
Type: new ruleset

Domain: www.cnn.com 

Domain: edition.cnn.com

**Comment by ihave100openPRs** [comment]
Isn't it already included? https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/CNN.com.xml#L51-L70

**Comment by BK1233** [comment]
Oh it is too, case closed then.
