### ISSUE TITLE
Release 2017-12-6 forthcoming

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#13830]
Type: other

cc @jsha @pde @J0WI @diracdeltas @jeremyn @gloomy-ghost

**Comment by J0WI** [comment]
#13721 removes some obsolete icons

**Comment by J0WI** [comment]
And #13515 might be worth to look at.

**Comment by jeremyn** [comment]
https://github.com/EFForg/https-everywhere/pull/13425 would be nice to have.

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/issues/13876 seems pretty serious (enough for delaying the release, if necessary), looking into this now

**Comment by Hainish** [comment]
Release made
