### ISSUE TITLE
Broken redirect for "http://www.clipconverter.cc/"

### ISSUE THREAD

**Issue by Sallybigtits** [EFForg/https-everywhere#13870]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: Broken redirect for "http://www.clipconverter.cc/"
Type: WORKING redirect for "http://www.clipconverter.cc/" with HTTPS EVERYWHERE.  
Type: Broken redirect for "http://www.clipconverter.cc/" with HTTPS EVERYWHERE.
Type: WORKING redirect for "http://www.clipconverter.cc/" with HTTPS EVERYWHERE.  
Type: ttp://www.clipconverter.cc/

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:"http://www.clipconverter.cc/"

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by Hainish** [comment]
Using throwaway accounts with offensive names is unacceptable. Please feel free to resubmit these issues with a more appropriate account.
