### ISSUE TITLE
Huffington Post - Top Headline Image Not Displayed

### ISSUE THREAD

**Issue by garyploski** [EFForg/https-everywhere#1387]
Using the latest version of Chrome the top headline image does not load.

ENABLED
![screen shot 2015-04-07 at 10 14 29 pm](https://cloud.githubusercontent.com/assets/4456404/7039238/857cce52-dd73-11e4-849d-97801ccbb6bd.png)

DISABLED
![screen shot 2015-04-07 at 10 15 33 pm](https://cloud.githubusercontent.com/assets/4456404/7039248/a92f4974-dd73-11e4-8bb4-e1ea38723f7c.png)

**Comment by semenko** [comment]
Exists:
http://i.huffpost.com/gen/2811624/images/r-WALTER-SCOTT-huge.jpg

Doesn't (403)
https://s-i.huffpost.com/gen/2811624/images/r-WALTER-SCOTT-huge.jpg
[neither does https://i.huffpost.com/gen/2811624/images/r-WALTER-SCOTT-huge.jpg ]
