### ISSUE TITLE
Massive leak while loading psarips.com

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#13876]
Type: code issue

This issue mirrors https://bugzilla.mozilla.org/show_bug.cgi?id=1414091

Creating an issue here for parity and easy reference.

**Comment by jeremyn** [comment]
It looks like https://psarips.com itself and pretty much all the elements in the page have a redirect loop.

**Comment by Bisaloo** [comment]
I can't reproduce either. I have a CPU and (small) memory spike on page load but memory is freed after page load as far as I can tell.

**Comment by jeremyn** [comment]
Could it be that this is actually a Firefox problem that is being triggered on some systems by the extreme number of redirects for this ruleset?

In any case the ruleset should be disabled or modified to prevent this from happening. The existing version of the ruleset can be used to continue debugging the memory problem.

**Comment by Hainish** [comment]
@jeremyn 

> Could it be that this is actually a Firefox problem that is being triggered on some systems by the extreme number of redirects for this ruleset?

That would be my guess, but without reproducing it this is hard to debug.  I've removed the site from the rulesets in https://github.com/EFForg/https-everywhere/commit/cf1c66c56923c31872aa5ef5b23f909fc6f4265f.  It shouldn't be too hard to find another ruleset or checkout the old file for memory debugging in the future.

**Comment by Hainish** [comment]
There hasn't been much movement in https://bugzilla.mozilla.org/show_bug.cgi?id=1414091 in the last few days, and this may be unrelated to HTTPS Everywhere (see https://bugzilla.mozilla.org/show_bug.cgi?id=1418815).  We should close this if we observe further inactivity on this thread on Bugzilla.

**Comment by pipboy96** [comment]
I can't see any leak or redirect loops on this website. It fully supports HTTPS.
