### ISSUE TITLE
CNET Comments Section is Hidden

### ISSUE THREAD

**Issue by garyploski** [EFForg/https-everywhere#1388]
Using the latest version of Chrome the comments section of CNET articles are hidden.

ENABLED
![screen shot 2015-04-07 at 10 17 29 pm](https://cloud.githubusercontent.com/assets/4456404/7039278/3e3d3ad0-dd74-11e4-8f0d-92527efaaef8.png)

**Comment by semenko** [comment]
I think this is a feature :smile: 

This is actually currently working for me -- I see comments at the bottom.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
