### ISSUE TITLE
Ruleset for LastPass.com

### ISSUE THREAD

**Issue by DeathlyX** [EFForg/https-everywhere#1389]
At this moment the ruleset for Lastpass.com is off by default because it apparently should break the add-on. The link to this bug report (https://www.eff.org/r.3Dq) however leads to a problem solved 2 years ago. I use this ruleset together with the Lastpass add-on on Firefox for quite a while and had no problems whatsoever. I haven't verified it for other browsers though.

**Comment by jsha** [comment]
Sounds good. Want to send a pull request re-enabling it?

**Comment by DeathlyX** [comment]
I didn't make a separate branch for my pending previous fix, so if I make the change it will mix up with my other pull request. Sorry, I'm kinda new to Github...

**Comment by DeathlyX** [comment]
I've made a pull request #1390.

**Comment by J0WI** [comment]
#closeme
