### ISSUE TITLE
Add hover text to counter

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1391]
The meaning of the counter on the HTTPS Everwhere icon isn't clear. We should add hover text, specific to the counter (vs the icon) that explains "Number of HTTPS Everywhere rulesets applying to this page."

**Comment by fuglede** [comment]
Seems straightforward enough: https://github.com/fuglede/https-everywhere/commit/548d3b1d6449b373b4ce2beccf0e8c776b49143f

**Comment by pipboy96** [comment]
Legacy Firefox related, closing.
