### ISSUE TITLE
the Verge Article image and comments broken

### ISSUE THREAD

**Issue by cinghialino** [EFForg/https-everywhere#1392]
Using the latest version of Chrome:
the comments section and the main image of the articles are broken

![bug](https://cloud.githubusercontent.com/assets/11861982/7057441/c50ccc9c-de23-11e4-8f99-a26c2c8ac5d5.png)

**Comment by reedy** [comment]
Seems to be a dupe of https://github.com/EFForg/https-everywhere/issues/1299

**Comment by cinghialino** [comment]
sorry about that. you are right.
