### ISSUE TITLE
Breaks HBO GO

### ISSUE THREAD

**Issue by cweagans** [EFForg/https-everywhere#1393]
Videos won't play on HBO GO when HTTPS Everywhere is enabled in Chrome 42.0.2311.68 beta (64-bit) on Mac OS Yosemite 10.10.3.

**Comment by reedy** [comment]
What version of HTTPS Everywhere?

**Comment by cweagans** [comment]
https-everywhere-chrome-2015.4.7.crx (== 5.0.2): Broken
https-everywhere-chrome-2015.3.31.crx (== 5.0.1): Broken
https-everywhere-chrome-2015.3.23.crx (== 5.0): Broken
https-everywhere-chrome-2015.1.22.crx (== 4.0.3): Works

**Comment by reedy** [comment]
Thanks for the info/testing.

Looks like the HBO ruleset was new in 5.0. Do you see any relevant errors in the browser console? And/or Chrome blocking mixed content?

Ping @2d1

**Comment by jagtalon** [comment]
I think I have a related fix here: https://github.com/EFForg/https-everywhere/pull/1440. Looks like @jsha has fixed it as well but maybe `platform="mixedcontent"` is more apt. :) Tell me what you think!

**Comment by Schmactor** [comment]
I don't know if this helps, but it seems the issue is with HTTPS Everywhere encrypting Conviva.  Unchecking Conviva under the HTTPS Everywhere "force encrypted" settings while on HBOGO seems to fix the problem.
