### ISSUE TITLE
Delete ruleset preferences that are the default

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1394]
Right now if a user disables, then re-enables a ruleset, we store a preference that that ruleset is enabled, meaning it stays enabled even if we disabled the ruleset by default due to brokenness.

Instead, we should only store preferences that differ from the default value for that ruleset at the time that the preference is altered.

We shouldn't update preferences based on changed in the default state of a ruleset, though, because a ruleset that becomes disabled and then re-enabled by default in subsequent versions could remove somebody's preference that disabled that ruleset.

**Comment by J0WI** [comment]
+1
My prefs.js is 90% full of HTTPS-Everywhere stuff. I've to clean it up manually.

**Comment by Hainish** [comment]
@J0WI many of these options will linger in the profile once the extension is updated to WebExtensions.  At that point, though, they can be safely deleted.  The export functionality in #10007 will not include ruleset toggles that are the default.

**Comment by pipboy96** [comment]
HTTPS Everywhere migrated to WebExtensions.
