### ISSUE TITLE
mailing.mediapart.fr is using an invalid certificate

### ISSUE THREAD

**Issue by alex-min** [EFForg/https-everywhere#1395]
Hi there,

Sorry to post this bug here, I've no idea where I should report bugs like this... :(

The existing rules are working well for the mediapart.fr website but the domain they are using to track emails is using an invalid certificate.

Would it be possible to remove mailing.mediapart.fr from the https list while keeping the rest as-is ?

If it's not complicated, I can have a look myself and do a pull request after but not before this weekend, I don't have any time before.

Regards,

**Comment by jsha** [comment]
That sounds like the correct solution. We'd welcome a pull request this weekend, thanks!

**Comment by alex-min** [comment]
Oh, thanks for answering so fast !

Okay I'll do a pull-request for this domain and close this issue after then, thanks :)

**Comment by J0WI** [comment]
https://mailing.mediapart.fr WFM
#closeme?

**Comment by alex-min** [comment]
I'm sorry, I had so many things to do and forgot about this issue :(. Apparently they have fixed their certificate (I've just checked) so this is not necessary anymore, sorry about it and thanks for the work ! :)
