### ISSUE TITLE
Breaks timewellspent.io

### ISSUE THREAD

**Issue by michel-slm** [EFForg/https-everywhere#13975]
Type: ruleset issue
Domain: timewellspent.io

The site's text would load just fine, but multimedia (images, embedded videos) break and the email list sign-up does not work

**Comment by Bisaloo** [comment]
Thank you for your report!

This site works fine for me. 

Can you reproduce this issue on a clean profile with only HTTPS Everywhere installed (no other extension)?

Could you share more details about your setup (browser, browser version, HTTPS Everywhere version)?

**Comment by pipboy96** [comment]
Website redirects to humanetech.com now.
