### ISSUE TITLE
TypeError: value is not a non-null object

### ISSUE THREAD

**Issue by alexolog** [EFForg/https-everywhere#1398]
"TypeError: value is not a non-null object" is continually displayed in console for chrome://browser/content/tabbrowser.xml (430:17)

**Comment by reedy** [comment]
Browsing any site?

What version of Chrome and what version of HTTPSE?

**Comment by alexolog** [comment]
Seems like any site

FF 37.0.1
HTTPSE 5.0.2

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
