### ISSUE TITLE
Breaks the AniWeather extension

### ISSUE THREAD

**Issue by alexolog** [EFForg/https-everywhere#1399]
Breaks the AniWeather extension

**Comment by reedy** [comment]
Is this a recent change?

What browser (FF?), browser version, version of HTTPSE?

**Comment by alexolog** [comment]
Appears to be recent
FF 37.0.1
HTTPSE 5.0.2

**Comment by reedy** [comment]
Do you see any errors?

**Comment by alexolog** [comment]
There are constant errors, mostly ones I mentioned in https://github.com/EFForg/https-everywhere/issues/1398.
I do not know if they are related though.

I believe this should be easily reproducible by installing the Aniweather extension, restarting FF with HTTPSE enabled, confirming that it does not work, disabling HTTPSE and witnessing Aniweather suddenly spring to life.

**Comment by reedy** [comment]
I'm currently using a Chromebook, so only have Chrome easily accessible ;)

**Comment by reedy** [comment]
Seems to work fine for me on FF 38.0 with limited testing. What exactly is broken?

**Comment by alexolog** [comment]
probably a bug in Aniweather, looks to be mostly fixed in the latest version
