### ISSUE TITLE
AliCDN rules break Youku HTML5 video players

### ISSUE THREAD

**Issue by yan12125** [EFForg/https-everywhere#14009]
Type: ruleset issue

Domain: g.alicdn.com

Browser: Firefox developer edition (58.0b11, 64bit)
OS: Arch Linux x86_64

Description:
When HTTPS-Everywhere is enabled, the video player in http://v.youku.com/v_show/id_XMzIwOTQ0OTk4MA==.html is broken, and there's an error in the Firefox console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://g.alicdn.com/ku/youkuplayer/0.5.9/youku-player.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

If I disable the "AliCDN.com (partial)" rule, the video plays fine.

**Comment by numismatika** [comment]
I can't understand the error message the video player gives me, but
does any of this change if you try https://v.youku.com/v_show/id_XMzIwOTQ0OTk4MA==.html instead with an S for tls in the url?

**Comment by yan12125** [comment]
Thanks for the tip. Both http://v.youku.com/v_show/id_XMzIwOTQ0OTk4MA==.html and https://v.youku.com/v_show/id_XMzIwOTQ0OTk4MA==.html work fine now. Maybe something has changed at their side. I think this issue can be closed as WONTFIX.
