### ISSUE TITLE
List all conflicting filenames due to case-insensitivity issues

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1401]
Sometimes when I'm being "lazy", I work directly from github.com. And as it doesn't like all the files in the rules folder, you can't view them easily.

Merging #1159 broke the build, so I deleted said file when I noticed. However, it doesn't tell you what the names of the conflicting files actually are

```
Generating sqlite DB
src/chrome/content/rules/geocaching.com.xml failed case-insensitivity testing.
Rules exist with identical case-insensitive names, which breaks some filesystems.
```

Can we have it spit out all the conflicts in https://github.com/EFForg/https-everywhere/blob/master/utils/make-sqlite.py#L54 ?

**Comment by reedy** [comment]
(another reason having things rebased before merging would be nice)

**Comment by jsha** [comment]
Yep, spitting out conflicts sounds like a great idea!

I'm not sure how rebasing would have helped, though?

**Comment by reedy** [comment]
Forcing the unit tests to be re-run, rather than displaying a potentially old/cached/out of date test run.

My working example is at Wikimedia for MediaWiki et al, generally we rebase (via one click in gerrit) before merging, which forces one set of test runs, but then on merging, they go through the CI workflow (again), to make sure the tests all pass before actually being merged into the branch. Or, just comment "recheck" has a similar result.

It's just more because you have to go out of your way to re-run the tests via github, or like I did with this case, notice the failure popping up elsewhere. Which I was then able to quickly resolve.

No big deal though :)

**Comment by jsha** [comment]
That sounds great, and easy with gerrit. Do you know of any way to make it that easy with github?

**Comment by reedy** [comment]
Nope, I'll try having a look around. I can't imagine this would be the first project on github that would want to force a test run before the merge actually being done, even more so with potentially "stale" pull requests
