### ISSUE TITLE
Sorting rulesets by Enabled doesn't work

### ISSUE THREAD

**Issue by Fanatic-64** [EFForg/https-everywhere#1402]
Exactly what it says on the title. Since a while clicking on the "Enabled" column on the HTTPS Everywhere Preferences window doesn't sort rulesets by enabled/disabled. It used to work back in the 3.X series.

**Comment by reedy** [comment]
Confirmed in FF 38.0 with HTTPSE 5.0.1

**Comment by fuglede** [comment]
Looks like this one is no longer relevant with the removal of the preferences window.
