### ISSUE TITLE
[RFC] Use project or milestone feature to group issues and PRs

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#14047]
I would like to make use of GitHub's project or milestone feature instead of issues for huge meta tasks like _Audit all default_off="foo"_ rulesets.
Then we can easily see the progress of the work and we may be able to solve a specific group for a upcomming release.

I'm not yet sure if projects or milestones are better for this job. Both provide similar functionality.

**Comment by jeremyn** [comment]
I agree that having these meta tasks buried in the issue backlog is not good for tracking or finding people who might want to help resolve them. Using projects or milestones or even a special label would be helpful.

One problem I have with these meta tasks is that I feel like -- though I can't easily find evidence of this -- people keep adding things to them and treating them as a sort of a rolling review. If we're going to make these into projects, then we should also fix their scope at the start: "audit 'foo' -- December 2017" with N rulesets, and that's it.

**Comment by J0WI** [comment]
> If we're going to make these into projects, then we should also fix their scope at the start

Sure, otherwise we have our labels.

Any comments about the projects vs. milestones functionality?

**Comment by wonderchook** [comment]
Personally, I would say if you want to track multiple steps the project feature makes sense. If you just want to track if something is done or not milestones makes more sense.

**Comment by jeremyn** [comment]
I agree with @wonderchook about the use cases for projects vs milestones, and I think that in this case, projects make more sense.

By the way, issue https://github.com/EFForg/https-everywhere/issues/13290 is a specific example of the sort of "audit" issue we're talking about.

**Comment by bardiharborow** [comment]
I only started using this method of tracking after I saw someone else doing it, so I'm not terribly attached to it. Projects and milestone's would help to collate the various "audit" issues, but I'm not sure there's a feasible way of replacing them entirely (except filing a seperate issue for every single item, which would be chaos).

**Comment by jeremyn** [comment]
I agree that having an issue per ruleset would be too much.

A project would be useful for tracking these tracking issues, though. I'm actually not sure whether @J0WI is talking about using projects/milestones to replace the audit issues themselves, or instead is talking about using projects/milestones to track the various audit issues.

**Comment by wonderchook** [comment]
@J0WI did you have a specific project you wanted to test this out on? 

(also did you receive an email from me? If so could you respond or feel free to reach out at the address in my profile)

**Comment by J0WI** [comment]
@youdly have some pending PRs that are all related together (e.g. #14035, #14066 and #13603). I plan to test it there.

I didn't receive any mail, but I prefer GitHub Issues or our [mailing list](https://lists.eff.org/mailman/listinfo/https-everywhere) anyway.

**Comment by wonderchook** [comment]
Sounds like a good test. 

@J0WI I'm interviewing contributors as part of @brainwane and my work announced on the [mailing list](https://lists.eff.org/pipermail/https-everywhere/2017-November/002756.html) which was why I'm reaching out individually.

**Comment by J0WI** [comment]
https://help.github.com/articles/configuring-automation-for-project-boards/

I created https://github.com/EFForg/https-everywhere/projects/2

**Comment by J0WI** [comment]
It's definitely easier to sort, review and track PRs. I can recommend this way to organize future projects.
