### ISSUE TITLE
"Crucial.com (partial)" broken rule

### ISSUE THREAD

**Issue by alphacentauri7** [EFForg/https-everywhere#14046]
Type: ruleset issue
Domain: crucial.com

Doesn't work if you never visited before or don't have resources cached (ctrl+f5). Just loads forever.

**Comment by jeremyn** [comment]
I can confirm this, the page appears to hang at http://crucial.com . Here is the ruleset: [`Crucial.xml`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Crucial.xml).

Based on the behavior in the `Network` tab and looking at the page source, I think it is having some trouble loading http://assets.crucial.com/wcsstore/customdojosmall/dojo/dojo.js from within the page.

**Comment by alphacentauri7** [comment]
The page actually loads fine if you disable the rule and just use https://crucial.com. It doesn't appear to be the same code behind the both though. The "https version" loads the problematic javascripts and other active content directly from the crucial.com domain (and otherwise only loads some passive content from pics.crucial.com and assets.microncpg.com). The "http version" loads these scripts from assets.crucial.com. This last domain appears to have problems with https and is causing the issues.

The HTTPS Everywhere rule is now trying to force the "http version" of the site to use https for these requests, which fails.

**Comment by alphacentauri7** [comment]
Actually connecting directly to https seems to only work on /. Otherwise it redirects to the http version

**Comment by Bisaloo** [comment]
I can't reproduce. @alphacentauri7, can you check if this issue has been fixed for you?

**Comment by alphacentauri7** [comment]
The problematic rule seems to have been removed. So, yes, that fixes it.
