### ISSUE TITLE
Teachable.com

### ISSUE THREAD

**Issue by elharo** [EFForg/https-everywhere#14083]
Type: ruleset issue
 (Domain: wmg-publishing-workshops-and-lectures.teachable.com

Domain:

Videos won't play on *.teachable.com in Chrome for Mac  when https everywhere is active

**Comment by numismatika** [comment]
the domain you mentioned uses tls.
So the risk of cors issues that prevent loading videos is greatly reduced.
The sample short story video plays fine here.
Which rules are active when you have this problem?
Is there any obvious error mentioned by the console in the  devtools?

**Comment by elharo** [comment]
I may have misdiagnosed which plugin was at fault, or which combination of extensions.
