### ISSUE TITLE
FF 37 doesn't connect to https://www.deutschepost.de/

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#1412]
It works in Chrome, but I think we should disable this rule (temporarily).

**Comment by julianladisch** [comment]
I don't have any problems with https://www.deutschepost.de/ using my Firefox 37.0.1 for Windows. The activated deutschpost rule works just fine for me. Please explain in more detail how to reproduce the problem.

**Comment by KommX** [comment]
That's interesting.

I am also on FF 37.0.1 and I have tested with Windows and Linux. I just visit https://www.deutschepost.de/ and get the following error message:
![deutschepost de](https://cloud.githubusercontent.com/assets/7859245/7091695/16c07d98-dfac-11e4-99ec-6b4ffce46c7f.png)

**Comment by jsha** [comment]
I get the same exact error. It could be that we are hitting different frontends or load balancers, and only one is broken?

**Comment by julianladisch** [comment]
Yes.

It is a certificate problem that will be fixed soon:

https://groups.google.com/forum/#!msg/mozilla.dev.security.policy/nEM8cfLf324/Lgs6rjXJEOIJ
