### ISSUE TITLE
http://isomerdesign.com/PiHKAL/

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/https-everywhere#14127]
Domain: [http://isomerdesign.com/PiHKAL/](http://isomerdesign.com/PiHKAL/)

**Comment by jeremyn** [comment]
@davidhedlund Thanks for your issue. I've noted this domain and URL at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-354472217` and am closing this issue.

**Comment by davidhedlund** [comment]
@jeremyn Thanks.
