### ISSUE TITLE
Firefox HTTPS Everywhere breaks expatriatepdx.com.

### ISSUE THREAD

**Issue by jaydeflix** [EFForg/https-everywhere#14153]
Type: new ruleset

Domain: expatriate.com

Page is hosted on Squarespace, leading to a bunch of usability issues, notably that the two big graphics that are the navigation links won't load.

**Comment by wonderchook** [comment]
Thanks for the report @jaydeflix  Just to double check this is for expatriatepdx.com, not expatriate.com which you listed in the description.

**Comment by pipboy96** [comment]
Can't reproduce.
