### ISSUE TITLE
Breaks GameSpot comments section

### ISSUE THREAD

**Issue by oscarandjo** [EFForg/https-everywhere#1416]
I'm not sure if it affects the entire site, but I was on the site here:
http://www.gamespot.com/articles/gta-5-pc-is-the-ultimate-version/1100-6426513/#livefyre

and clicked the link to open the comments section at the top of the article. It didn't work with HTTPS everywhere enabled but did work with it disabled.

**Comment by reedy** [comment]
The GameSpot rule is disabled by default at least in 5.0.2

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
