### ISSUE TITLE
Add tests to detect different content http/https

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#14173]
Type: other

It would be useful to add tests to compare content of `http` and `https` version of each (implicit and explicit) test url.

If anyone wants to do this, you are welcome to but please open a "work in progress" PR as soon as possible. I may have a go at it soon if no one has already done it.

**Comment by cschanaj** [comment]
AFAIK, the comparison logic has been implemented. 

https://github.com/EFForg/https-everywhere/blob/e89e340cf7b9ba31839df582857a606a5c3f4656/test/rules/src/https_everywhere_checker/check_rules.py#L157-L171

**Comment by jeremyn** [comment]
Testing whether two webpages are "the same" is a very difficult problem for non-trivial pages. It looks like the existing code parses the two returned HTML documents into structures and computes some mathematical distance between those structures, and warns if that distance is too high. We might be able to improve this around the edges but I expect a serious improvement would be very challenging.

It might be better to limit the scope of the problem you want to solve, to make it more manageable.

**Comment by Bisaloo** [comment]
Is there any valid reason why the pages could slightly differ? I must be missing something but why can't we compare the shasums of the content?

**Comment by jeremyn** [comment]
One page can serve different content every time it is loaded, such as ad content, and still be "the same". An extremely trivial example of this would be a page that generates and serves a different random number on every load.

You'd also need to run all the JavaScript on the page to verify the sameness of the content. For example you can imagine a script that detects whether the page is HTTPS or plain HTTP and does something different depending on the result. You need to compare the two generated DOMs, not just raw page content.

There are other, more trivial problems too, such as the `href` values in `a` tags varying between `https:` and `http:` if the site uses absolute paths.

I'm sure there are many other problems besides these.

**Comment by jeremyn** [comment]
Another approach besides DOM comparison is to use something like https://github.com/BBC-News/wraith to take screenshots of the two versions of the page, and compare those.

**Comment by jayvdb** [comment]
To catch issues like https://github.com/EFForg/https-everywhere/issues/18942#issuecomment-587491044 , it would be useful for the rules checker to

1. detect when multiple test urls redirect to the same URL.  If this happens currently with legitimate tests, the test urls should be improved
2. enforce that the response is a sane mimetype based on the filename extension, thereby catching when real content has been replaced with generic redirects.
