### ISSUE TITLE
Rule for ubuntu.com breaks keyserver.

### ISSUE THREAD

**Issue by hicrop** [EFForg/https-everywhere#14185]
Type: ruleset issue

Domain:
https://keyserver.ubuntu.com:11371/pks/lookup?fingerprint=on&op=index&search=0x8E51A6D660CD88D67D65221D90BD7EACED8E640A 

Please move it to non-functional hosts with `SSL connect error`.

**Comment by Bisaloo** [comment]
Hi, thank you for your report. I have fixed this in #14191. In the meantime, you can use port 443 on this subdomain which works exactly the same.

https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x8E51A6D660CD88D67D65221D90BD7EACED8E640A
