### ISSUE TITLE
apa.at rule breaks embedded video on vol.at

### ISSUE THREAD

**Issue by fabianfrz** [EFForg/https-everywhere#14183]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: apa.at (content loaded from), vol.at (website)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The video player does not work on this site when apa.at is enabled:
http://www.vol.at/monsterwelle-rollte-auf-bregenz-zu/5615621
![screenshot_20180104_214001](https://user-images.githubusercontent.com/3713914/34583403-ee8c3ea6-f197-11e7-9f79-96b2acb0e6ed.png)

some translation help for the german error message:
* "gemischten Inhalten" -> "mixed content"
* "wurde blockiert" -> "was blocked"

**Comment by numismatika** [comment]
`rm.sf.apa.at` is unable to serve TLS, so unless we can convince the austrian press agency to enable TLS you have to either disable mixed-content blocking in your browser or the apa.at rule

**Comment by fabianfrz** [comment]
@numismatika disabling mixed content blocking is something I can do but it is something which cannot be done by normal users as this requires toggling a value in `about:config` in Firefox.

**Comment by Bisaloo** [comment]
@fabianfrz, I can't reproduce. This seems fixed. Can you confirm?

**Comment by fabianfrz** [comment]
Can confirm that it works now - maybe the site has been improved because I reported the issue to them too.
