### ISSUE TITLE
Breaks aastock.com

### ISSUE THREAD

**Issue by KayLeung** [EFForg/https-everywhere#14275]
Type: ruleset issue
Domain: aastock.com

Some internal pages are broken, eg.:
https://www.aastocks.com/en/stocks/quote/dynamic-chart.aspx?symbol=00005  (charts doesn't load, logging showed on devtools)

I also contacted the site supports, they said the site do not support HTTPS.

**Comment by numismatika** [comment]
Every object loaded there could be loaded over tls all they need to do is solve the mixed.content.
The foundation is already there.
