### ISSUE TITLE
Firefox HTTPSEverywhere breaks redlightradio.net

### ISSUE THREAD

**Issue by KapeteinPannenkoek** [EFForg/https-everywhere#14284]
Type: ruleset issue

Domain: redlightradio.net

http://redlightradio.net works fine. 
https://redlightradio.net returns a weird "Access Forbidden!" warning. 

I'm an end user. I don't understand what to do. 

The FAQ says: 

> If you report the problem to us, we can try to fix it. In the meantime, you can disable the rule affecting that particular site in your own copy of HTTPS Everywhere by clicking on the HTTPS Everywhere toolbar button and unchecking the rule for that site.

But there's no rule for that site. Nothing to uncheck.

I wouldn't know what sort of rule to create, other than to ignore https and go to http. Again, I don't know how to do that. 

The FAQ also says to contact the site, but I don't even understand what I'm asking them to do.

When I click "View All Rules" I'm taken to an atlas page, but the domain isn't there.

Please help,
Pannenkoek

**Comment by Bisaloo** [comment]
Thank you for your report!

You are right in there is no rule for that site. It should not redirect to `https` and it doesn't on my computer. I can't reproduce the issue you are describing.

Are you sure it is caused by HTTPS Everywhere?

What happens if you manually remove the `s` in `https` in the URL bar for that site?

**Comment by Bisaloo** [comment]
Thank you for providing screnshots, I see the issue now.

You have enabled the "HTTPS only" mode (turning the extension icon red). This means all websites will be reached using `https`, even if they are not properly configured.

This setting may cause issues in your everyday browsing (depending on the websites you visit). You may want to uncheck the "Block all unencrypted requests" in the dropdown menu when you click on HTTPS Everywhere icon. You will still be protected on all websites we have rules for.

**Comment by KapeteinPannenkoek** [comment]
I don't quite understand. But I take your word that it works. 

And indeed, it does work. I can get to http://redlightradio.net ! 

I guess I don't understand what the "rules" are, or what they do, how, or why I would write one. And the documention isn't sufficient for end-users. The FAQs go much too quickly into developer mode, in my opinion.

IF what you're saying is I should always run in "blue" mode (not blocking unencrypted requests), and that HTTPS Everywhere will still protect me on all sites we have rules for, then what can I do on about this site in particular?

**Comment by pipboy96** [comment]
@KapeteinPannenkoek This is correct.

**Comment by pipboy96** [comment]
The website in question does not support HTTPS, so I guess you can't fix this issue in any way except disabling HTTPS Everywhere on this website or disabling EASE mode.
