### ISSUE TITLE
HTTPS everywhere prevents lenovo blog from loading (downgrade not being executed?)

### ISSUE THREAD

**Issue by samtygier** [EFForg/https-everywhere#1429]
I am using HTTPS-everywhere 5.0.2 in firefox 37.0.1 on Fedora Linux. When it is enabled I cannot load http://blog.lenovo.com/

**Comment by reedy** [comment]
WFM in Chrome and HTTPSE 2015.4.7 (it doesn't redirect the blog at all)

Some other errors seen, but they're not even loading HTTPS requests

```
http://blog.lenovo.com/assets/js/blogs.js?v=1330371131 Failed to load resource: the server responded with a status of 404 (Not Found)
http://fls.doubleclick.net/json?spot=1847082&src=1515899&var=s_1_Integrate_…echo%3Fvar%3Ds_1_Integrate_DFA_get_0%26AQE%3D1%26A2S%3D1&ord=5615226638043 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://edge.quantserve.com/quant.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://blog.lenovo.com/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

Will test on FF when I'm on my laptop

**Comment by reedy** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Lenovo.xml

Seems the rulesets in FF/5.0.[12] rewrite the blog to HTTPS, and they shouldn't. Blog is listed as nonfunctional, and is "downgraded", but the downgrade apparently doesn't work?

**Comment by reedy** [comment]
Which, is seemingly a FF bug?

**Comment by semenko** [comment]
Seems fixed per above commits.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
