### ISSUE TITLE
Breaks National Geographic videos

### ISSUE THREAD

**Issue by tkossak** [EFForg/https-everywhere#1431]
Whan i have this extension running the video on National Geographic is not loading at all: http://video.nationalgeographic.com/video/news/jaguar-attacks-crocodile
I have experimental rules for NG turned off.

When i disable the extension and refresh the page it works as it should.

My specs:
Linux Mint 17.1 x64
Chrome version 41.0.2272.118 (64-bit)
HTTPS everywhere version: 2015.4.7

**Comment by reedy** [comment]
I guess it's one of the other rulesets that are in effect on the natgeo site...


```
Cloudfront
Google APIs
Monetate (partial)
Quantserve.com
ScorecardResearch.com
Gigya.com (partial)
Imrworldwide.com
Google Services
thePlatform (partial)
Chartbeat.com (partial)
Chartbeat.net
```

**Comment by DeathlyX** [comment]
I've made pull request #1547 with a possible fix to the problem. The ruleset of thePlatform was the culprit.
