### ISSUE TITLE
Not working as intended

### ISSUE THREAD

**Issue by Glorydayreject** [EFForg/https-everywhere#14312]
Type: code issue

I have gone to various websites where an https version is available, but I am not automatically directed to it. 
One website for example is iainsinclair.com

I looked into the rule for this website and it seems set up to automatically redirect me to https://www.iainsinclair.com, but does not do so.

**Comment by jeremyn** [comment]
By default HTTPS Everywhere only rewrites URLs that match rulesets included in the extension. There is no ruleset that matches `www.iainsinclair.com`, which you can see at https://www.eff.org/https-everywhere/atlas/?www.iainsinclair.com , so it makes sense that http://www.iainsinclair.com isn't rewritten to HTTPS.

If you want to force everything to be rewritten to HTTPS, you can check the `Block all unencrypted requests` option. Be aware though that this will cause problems on many sites.

Please close this issue if this has answered your question.
