### ISSUE TITLE
Fail fetch testing via HTTP/80, as site only works via HTTPS

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1435]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/GayTorrents.xml

So, for whatever reason the site only works via HTTPS. Their webserver apparently isn't listening on port 80 for HTTP, which makes having the rewrite all the more useful, as visiting HTTP results in a deadend, no server side redirection.

Could this be considered a https-everywhere-checker bug? ie it should only disable a ruleset IF the site isn't listening on 443 AND 80?

**Comment by KommX** [comment]
The same applies to fahrkarten.bahn.de and grosskunden.bahn.de.

**Comment by anand-bhat** [comment]
Also see cmp.onlinesbi.com

**Comment by reedy** [comment]
https://lists.eff.org/pipermail/https-everywhere/2015-April/002486.html

https://lists.eff.org/pipermail/https-everywhere/2015-April/002488.html

"Yes, we've decided that 'failure to connect on port 80' can be ignored, but the checker is not yet updated to do that."

**Comment by jsha** [comment]
I believe this is now fixed.
