### ISSUE TITLE
Open XML Source in new FF Tab

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1436]
It'd be useful if we could Ctrl + F in the View XML Source window.

Or maybe, a simpler (and better?) option is to either have the URL hyperlinked in the window, and/or have a "View XML Source in browser" option which opens the gitweb page in a new tab

**Comment by jsha** [comment]
I think linking to the content in a new tab is much better, let's do that.

**Comment by J0WI** [comment]
The feature to view rulesets has been removed. There is only a link to atlas now.
