### ISSUE TITLE
fetch-test.sh incorrectly reports an error because it doesn't follow a non-trivial rewrite rule

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#14365]
Type: code issue

There are three domains that behave like this:

| URL | result |
|-----|--------|
| http://armytimes.com | 301 http://www.armytimes.com/ |
| https://armytimes.com | Connection refused |
| http://www.armytimes.com | 301 https://www.armytimes.com/ |
| https://www.armytimes.com | 200 |
| http://link.armytimes.com | 302 http://armytimes.com |
| https://link.armytimes.com | 302 http://armytimes.com |

If you run `fetch-test.sh` (d5c54c4ecb9dcab1789903990b57c0cfc53795ba) against the following ruleset, which is a minimal version of [`ArmyTimes.com.xml`](https://github.com/EFForg/https-everywhere/blob/d5c54c4ecb9dcab1789903990b57c0cfc53795ba/src/chrome/content/rules/ArmyTimes.com.xml):
```xml
<ruleset name="ArmyTimes.com (minimal)">
	<target host="armytimes.com" />
	<target host="www.armytimes.com" />
	<target host="link.armytimes.com" />

	<rule from="^http://armytimes\.com/"
		to="https://www.armytimes.com/" />

	<rule from="^http:" to="https:" />
</ruleset>
```

and change the logging level to `debug` in `test/rules/manual.checker.config`, you get:
```
DEBUG Loaded certificate platforms: cacert,chromium,default,firefox
DEBUG Parsing ArmyTimes-minimal.com.xml
DEBUG Checking coverage for 'ArmyTimes.com (minimal)'.
DEBUG Checking target validity for 'ArmyTimes.com (minimal)'.
DEBUG =**= Start http://armytimes.com/ => https://www.armytimes.com/ ****
DEBUG Fetching transformed page https://www.armytimes.com/
DEBUG Fetching plain page http://armytimes.com/
DEBUG Following redirect http://armytimes.com/ => http://www.armytimes.com/
DEBUG Following redirect http://www.armytimes.com/ => https://www.armytimes.com/
DEBUG ==== D: 0.0000; http://armytimes.com/ (140074) -> https://www.armytimes.com/ (140074) =====
INFO Finished comparing http://armytimes.com/ -> https://www.armytimes.com/. Rulefile: ArmyTimes-minimal.com.xml.
DEBUG =**= Start http://www.armytimes.com/ => https://www.armytimes.com/ ****
DEBUG Fetching transformed page https://www.armytimes.com/
DEBUG Fetching plain page http://www.armytimes.com/
DEBUG Following redirect http://www.armytimes.com/ => https://www.armytimes.com/
DEBUG ==== D: 0.0000; http://www.armytimes.com/ (140074) -> https://www.armytimes.com/ (140074) =====
INFO Finished comparing http://www.armytimes.com/ -> https://www.armytimes.com/. Rulefile: ArmyTimes-minimal.com.xml.
DEBUG =**= Start http://link.armytimes.com/ => https://link.armytimes.com/ ****
DEBUG Fetching transformed page https://link.armytimes.com/
DEBUG Following redirect https://link.armytimes.com/ => http://armytimes.com
DEBUG Redirect rewritten: http://armytimes.com => https://armytimes.com
DEBUG =**= Start http://link.armytimes.com/ => https://link.armytimes.com/ ****
DEBUG Fetching transformed page https://link.armytimes.com/
DEBUG Following redirect https://link.armytimes.com/ => http://armytimes.com
DEBUG Redirect rewritten: http://armytimes.com => https://armytimes.com
DEBUG Fetch error: http://link.armytimes.com/ => https://link.armytimes.com/: (7, 'Failed to connect to armytimes.com port 443: Connection refused')
INFO Finished comparing http://link.armytimes.com/ -> https://link.armytimes.com/. Rulefile: ArmyTimes-minimal.com.xml.
ERROR ArmyTimes-minimal.com.xml: Fetch error: http://link.armytimes.com/ => https://link.armytimes.com/: (7, 'Failed to connect to armytimes.com port 443: Connection refused')
INFO Finished in 2.32 seconds. Loaded rulesets: 1, URL pairs: 3.
```

The error is invalid because the ruleset checker should use the included extra `rule` to rewrite http://armytimes.com to https://www.armytimes.com instead of rewriting it to https://armytimes.com .

**Comment by numismatika** [comment]
similiar things i saw when trying to check the turn.com ruleset #14144

**Comment by jeremyn** [comment]
@numismatika I'm having trouble following the description in https://github.com/EFForg/https-everywhere/issues/14144. The text seems cut off near the end: 

> Since www.turn.com has a cert that is only valid for www.amobee.com  but the cert on `httpS://presentation-ams1.turn.com` is valid for `*.turn.com` and `turn.com` we have a ruleset testing issue. The script says "amobee.com

**Comment by jeremyn** [comment]
@numismatika Could you provide a minimal example in your issue, like I did here?

**Comment by numismatika** [comment]
`<ruleset name="Turn.com (partial)" >

<target host="presentation-ams1.turn.com" />

	<rule from="^http:"
 		to="https:" />
</ruleset>
`

**Comment by jeremyn** [comment]
I don't get an error from `fetch-test.sh` running against that file.

**Comment by numismatika** [comment]
Mhmm then https://travis-ci.org/numismatika/https-everywhere/jobs/332958553 must be coming from something else

`ERROR src/chrome/content/rules/Turn.com.xml: Fetch error: http://presentation-ams1.turn.com/ => https://presentation-ams1.turn.com/: (51, "SSL: no alternative certificate subject name matches target host name 'www.turn.com'")`

**Comment by jeremyn** [comment]
https://presentation-ams1.turn.com/ has a valid HTTPS certificate when I check it in a browser.

**Comment by numismatika** [comment]
yea but travis doesn't like it

**Comment by jeremyn** [comment]
FYI, as of PR https://github.com/EFForg/https-everywhere/pull/14570, `fetch-test.sh` is now `test/manual.sh`.

**Comment by cschanaj** [comment]
See #14598

**Comment by jeremyn** [comment]
Thanks @cschanaj .
