### ISSUE TITLE
HTTPS Everywhere not rewriting URLs as expected

### ISSUE THREAD

**Issue by ntwb** [EFForg/https-everywhere#14387]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ~ruleset issue~
Type: ~new ruleset~
Type: ~code issue~
Type: ~feature request~
Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: All

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Version details: Extensionv2018.1.11 | Chrome v65.0.3322.3 (Official Build) dev (64-bit)

Expected behaviour: When I click a link and it opens a new tab in Chrome I expect the URL to be prefixed with `https://`

What actually happens: There is no `https://` prefix

Halp, I've been using this extension for years, it's currently broken, so many sites I visit are showing `Not Secure` because HTTPS is not being forced, it doesn't feel right, safe even, surfing unprotected!

**Comment by J0WI** [comment]
Can you please provide some screenshot, urls or other examples?

**Comment by ntwb** [comment]
Here's an example, I was reading this https://webkit.org/blog/8063/speedometer-2-0-a-benchmark-for-modern-web-app-responsiveness/ works fine, https is 👌 

At the end of the first section is this link `http://browserbench.org/Speedometer2.0/`, when I open that in a new tab it uses `http` and Chrome now shows `Not Secure` in the browser bar

I believe the functionality of this `https-everywhere` extension is upon opening that URL it detects it as `http` and swaps that out with `https` for me automagically.

I believe that magic has stopped, or some modification has been made to the extension that has caused a change in behaviour.

I could just be completely wrong and have be chance been bumping into `http` only sites far more than I typically do in the past week or so /shrug

**Comment by jeremyn** [comment]
@ntwb HTTPS Everywhere works by checking URLs against a whitelist and rewriting them in a specific way. `browserbench.org` is not in the list of URLs to rewrite, as you can see at https://www.eff.org/https-everywhere/atlas/?browserbench.org . In fact, if you try to visit the HTTPS version of your URL at https://browserbench.org/Speedometer2.0/ , you will get a `Secure connection failed` error. See the FAQ https://www.eff.org/https-everywhere/faq#why-use-a-whitelist-of-sites-that-support-https-why-cant-you-try-to-use-https-for-every-last-site-and-only-fall-back-to-http-if-it-isnt-available.

If you are in a very high security situation and want to rewrite every URL to HTTPS, you can check the `Block all unencrypted requests` option in the UI. However this will cause problems for many URLs, such as your example `browserbench.org` URL, as I just discussed.

**Comment by jeremyn** [comment]
If this answers your question, please close this issue, thanks.

**Comment by jeremyn** [comment]
(I've updated the issue title to distinguish this from the occasional Chrome-specific problem report we get.)

**Comment by ntwb** [comment]
Thanks, I tried enabling the `Block all unencrypted requests` option to see if that was the behaviour I used to see and it's not, it throws an SSL protocol error when trying to force HTTPS  on sites that are not using HTTPS such as `browserbench.org`

Thanks y'all, I'll close the issue here and if I can find a concrete way of reproducing and documenting this I'll reopen or create a new issue, appreciate the replies, thanks 😄

**Comment by jeremyn** [comment]
@ntwb I'm not sure what you mean by "it" as in "it throws an SSL protocol error", but just to be clear, it is the specific `browserbench.org` domain/server that is returning the error in this case. All HTTPS Everywhere is doing with `Block all unencrypted requests` is rewriting all URLs from `http` to `https`.

In any case, please feel free to open an issue in the future if you find a possible bug in the extension.
