### ISSUE TITLE
HTTPs everywhere breaks squarespace.com custom-domain sites

### ISSUE THREAD

**Issue by hsanjuan** [EFForg/https-everywhere#14382]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: http://laicale.com/ (or any others which have http enabled)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The problem is badly configured CORS policy on the squarespace.com side which disallows customer's HTTP origins to fetch some javascript from squarespace.com HTTPs urls (which do work when directly visiting the HTTPs sites).

I have tried reporting this, but they said having this work is a "feature" and didn't promise anything.

![image](https://user-images.githubusercontent.com/1027022/35233528-b6c66554-ff9e-11e7-9141-a8da49936b72.png)

**Comment by jeremyn** [comment]
Thanks for the report. We already have an `exclusion` in `Squarespace.xml` [here](https://github.com/jeremyn/https-everywhere/blob/076aa5bac3ab813bf53de4b5e1f37afd2e871396/src/chrome/content/rules/Squarespace.xml#L45), which is:
```xml
<exclusion pattern="^http://static\.squarespace\.com/universal/scripts-compressed/\w+-\w{20}-min.js$" />
```

but in this case the scripts we want to exclude are http://static.squarespace.com/universal/scripts-compressed/common-691f87b3b7d791c5fa02-min.en-US.js and http://static.squarespace.com/universal/scripts-compressed/commerce-807d668314a84db3bdf9-min.en-US.js (note the `en-US`).

We should fix this by generalizing the `exclusion` to all `.js` files at `http://static.squarespace.com/universal/scripts-compressed/` .

**Comment by hsanjuan** [comment]
If CORS is broken, you may as well generalize to all static.sqarespace.com I guess....

**Comment by jeremyn** [comment]
https://static.squarespace.com/universal/images-v6/damask/play-button.png is loaded from http://laicale.com/ and has the CORS header (`access-control-allow-origin: *`) set, so we don't need to exclude all of `static.squarespace.com` .
