### ISSUE TITLE
SublimeVideo cdn redirect is broken

### ISSUE THREAD

**Issue by koke** [EFForg/https-everywhere#144]
The [SublimeVideo.xml](https://github.com/EFForg/https-everywhere/blob/35e657bea25c72e49ed2c3d62b816365ef2492ae/src/chrome/content/rules/SublimeVideo.xml) rule is redirecting `https://cdn.sublimevideo.net` to `https://data.sublimevideo.net`. However:

```
$ curl -sI https://cdn.sublimevideo.net/c/sa/2.2.13/sa.js | head -1
HTTP/1.1 200 OK
$ curl -sI https://data.sublimevideo.net/c/sa/2.2.13/sa.js | head -1
HTTP/1.1 404 Not Found
```

I only noticed this because it was breaking video embeds in CloudUp (like https://cloudup.com/iNV0ccD2ytL)

**Comment by Xiller** [comment]
@koke do you solved it? it is an issu of sublimeplayer (its closed) and you can switch to local installation: http://www.sublimevideo.net/user-player-download.html  . But i have this problem now. I deleted the code part (with my 0 code knowledge) in the js file (code part: want a json file, but the download/Local version hasnt one). On my mobile device the local sublime player works fine, but chrome, opera.. dosnt. So i hope that someone here has a solution for the sublimeplayer problem.
