### ISSUE TITLE
"Squarespace.com (partial)" rule breaks images on oakvalleychico.com

### ISSUE THREAD

**Issue by HarryCutts** [EFForg/https-everywhere#14422]
Type: ruleset issue

Domain: oakvalleychico.com

When I go to http://oakvalleychico.com/ with HTTPS Everywhere fully enabled, the images don't appear ([full-page screenshot](https://screenshots.firefox.com/UVKYWcuxhC0Nab8b/oakvalleychico.com)). Disabling the "Squarespace.com (partial)" rule fixes it ([screenshot](https://screenshots.firefox.com/MrcZazxOlaYXzsrt/oakvalleychico.com)). Strangely, manually going to the HTTPS version of the same site (https://oakvalleychico.com/) also fixes the issue.

(I'm using Firefox 57 on desktop.)

**Comment by Bisaloo** [comment]
This should be fixed in the next release by https://github.com/EFForg/https-everywhere/pull/14394 but I also added a rule for oakvalleychico in #14426.
