### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by anand-bhat** [EFForg/https-everywhere#1442]
Chrome Version 41.0.2272.118 m (64-bit) + HTTPS Everywhere 2015.4.7

I've enabled the "Krebs on Security.com (partial, broken MCB)" rule to apply on krebsonsecurity.com. I see mixed content warnings for resources that should have been rewritten by HTTPS Everywhere. In fact, if I navigate to the HTTP version of the resource (CSS/ image), HTTPS Everywhere rewrites it to the HTTPS equivalent.

Is this a known bug (or a "feature") in Chrome where mixed content checks are done before an extension has the opportunity to perform a rewrite?

![image](https://cloud.githubusercontent.com/assets/7332442/7107018/98bc4408-e123-11e4-8314-ad173a0f88ad.png)

**Comment by jmorahan** [comment]
Yes, see #793

**Comment by semenko** [comment]
Yeah, this unfortunately isn't fixable by us -- it's an upstream chrome issue per above.

**Comment by anand-bhat** [comment]
Thanks. I'll be starring that although it appears to be a slow mover :(
