### ISSUE TITLE
Ebay Images

### ISSUE THREAD

**Issue by devouk** [EFForg/https-everywhere#1445]
Hi 
I am using nightly and https everywhere plugin and when i visited the ebay site, alot of the images are not displaying correctly and unsure why, wondering if the rule is to blame after disabling ebay under options then the page displays correctly.

Not sure if this is a bug or just the way https will work with ebay
many thanks
nick

**Comment by reedy** [comment]
FF nightly?

Ebay.com/co.uk both look alright to me at a quick glance. But there are multiple ebay rulesets. Which do you have active?

Anything in the browser console?

**Comment by KommX** [comment]
Same problem here. This screenshot is from ebay.de:
![ebay](https://cloud.githubusercontent.com/assets/7859245/7124315/3f11a8c0-e228-11e4-8c57-64d17db241ff.png)

The only active rule is "eBay static.com (partial)". Deactivating this rule helps getting the images back.

**Comment by reedy** [comment]
I guess the images are coming from different sources/cdns?

**Comment by devouk** [comment]
Firefox Nightly (which is a branch of firefox but with a lot more technology and seems to faster browsing and its updated nightly so its an ever evolving browser and then eventually the code will cross over to firefox)

I have just the ebay.static particalrules enabled

I am using ebay uk, so wondering if a ruleset needs to be more generic to any ebay domain or even a ruleset which is for ebay.co.uk

Where are the rules kept if i wanted to create my own rules in mozilla firefox / nightly so they can be created 

But i just tried searching for the same item on ebay.co.uk i was on friday and now the images are working for the same search..  whether an update of nightly or a restart of it compared to when i reported the issue and pulling my hair out, but as per kommx screenshot that is what i was experiencing  and wonder if reedy hit the nail on the head or it was just an persistent issue which has been cured.

I appreciate any views .

**Comment by THausherr** [comment]
I have the same problem for months with ebay.de and not with ebay.com. Here's how to reproduce:
- open the privacy mode of FF
- enter ebay.de
- search for "computer"
it shows this:
![sreenshot_ebay](https://cloud.githubusercontent.com/assets/6665575/9428269/5c243d1a-49a7-11e5-93be-4e616342288d.png)
The images come back if I disable https everywhere.
The images that don't show up are URLs like this:
http://thumbs.ebaystatic.com/images/m/milevG56OLD6_nIeCTcaucw/s-l225.jpg
this redirects to
https://securethumbs.ebay.com/images/m/milevG56OLD6_nIeCTcaucw/s-l225.jpg
when https everywhere is on.

**Comment by semenko** [comment]
Images render for me in latest version.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
