### ISSUE TITLE
HTTPS Everywhere still breaks area51.stackexchange.com login

### ISSUE THREAD

**Issue by vyznev** [EFForg/https-everywhere#14452]
Type: ruleset issue

Domain: area51.stackexchange.com

See https://area51.meta.stackexchange.com/questions/13597/area-51-openid-login-is-broken-with-https/27726#27726 for more details, but it looks like the [Stack Exchange ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Stack-Exchange.xml) should still have an exclusion for `http://area51.stackexchange.com/users/authenticate/`, something like this:

    
    <exclusion pattern="^http://area51\.stackexchange\.com/users/authenticate/" />

Area 51 runs a distinct and somewhat obsolescent fork of the Stack Exchange codebase, and apparently this problem (which used to be more general, see issue #58) still occurs there.

Ps. Also, while investigating this, I noticed that [the ruleset syntax documentation](https://github.com/EFForg/https-everywhere/blob/19468262c7a01d776371eaa7086c9f4df04099b3/docs/en_US/rulesets.md#exclusions) happens to feature as an example a very similar but broader exclusion that would've caught this. However, that exclusion was apparently removed from the actual ruleset in commit 783d040.

Pps. This may have been previously reported as issue #7275, but that report was a bit lacking in details.

**Comment by Bisaloo** [comment]
As far as I can tell, this is not an `https` issue but a parameters issue. We need a more complex redirect than just `rule from="^http:" to="https:"`.

Looking into this now.

**Comment by Bisaloo** [comment]
Uh no, you are right. There are 3 requests:

| Status | Method | File | Domain | 
|------|--------|----------------------------------------------------|---------------------------------------------|
| 302 | GET | /users/authenticate?openid_identifier=... | https://area51.stackexchange.com |
| 302 | GET | /openid/provider?openid.claimed_id=...   | https://openid.stackexchange.com |
| 200 | GET | /users/authenticate/?s=...                        | http://area51.stackexchange.com  |

**Comment by Bisaloo** [comment]
Could you also report this issue in the [main Stack Exchange thread](https://meta.stackexchange.com/questions/292058/network-wide-https-its-time) please?

**Comment by vyznev** [comment]
That's probably not necessary, since the SE devs *should* be monitoring bug reports on all Meta sites. But just in case, here goes: https://meta.stackexchange.com/a/306308
