### ISSUE TITLE
Video playback broken [wnd.com]

### ISSUE THREAD

**Issue by ms1121** [EFForg/https-everywhere#14464]
**Type:** new ruleset
**Domain:** www.wnd.com
**Issue:** video playback failure
  **_"Error loading playlist: Playlist load error: Error loading file"_**

**Sample URL:** 
 https://www.wnd.com/wnd_video/lawyer-suing-dnc-fears-for-life-after-witness-seth-rich-murdered/

**Comment by numismatika** [comment]
This one is as far as i can tell unsolvable with rulesets at this state.
We have mixed content & CORS issues here.

**Comment by Folant** [comment]
This should fix video playback, but only on HTTP version of www.wnd.com, I think.
#4531 #5086 related
