### ISSUE TITLE
Plese add eyny.com

### ISSUE THREAD

**Issue by yingziwu** [EFForg/https-everywhere#14466]
Type: new ruleset

Domain: *.eyny.com
HTTPS Everywhere version: 2018.1.11

The forum [eyny.com](http://www.eyny.com) has https version,but it is not automatically redirected.

**Comment by yingziwu** [comment]
```xml
<ruleset name="eyny.com">
  <target host="*.eyny.com" />

  <rule from="^http://(www\d*)\.eyny\.com/"
          to="https://$1.eyny.com/"/>
</ruleset>
```

**Comment by pipboy96** [comment]
See #15503.
