### ISSUE TITLE
Domain: catalog.update.microsoft.com don't work

### ISSUE THREAD

**Issue by eXPerience83** [EFForg/https-everywhere#14476]
Type: ruleset issue
Domain: catalog.update.microsoft.com

https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4078130 don't work
http://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4078130 works

**Comment by Folant** [comment]
They fixed the issue.

**Comment by Bisaloo** [comment]
Nope, I can reproduce:

> Your connection is not secure
>
> The website tried to negotiate an inadequate level of security.
>
> catalog.update.microsoft.com uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.
>
> Error code: NS_ERROR_NET_INADEQUATE_SECURITY

**Comment by Folant** [comment]
@Bisaloo Yes, you are right. It was working for a few minutes back then, it seems.

**Comment by Bisaloo** [comment]
This seems fixed now. @eXPerience83, can you check again and if everything is working for you, close this issue?

**Comment by eXPerience83** [comment]
It seems to work now. Thanks a lot.
