### ISSUE TITLE
No more "add custom rules" functionality in the latest version?

### ISSUE THREAD

**Issue by netheril96** [EFForg/https-everywhere#1447]
The latest version (2015.4.7) no longer has a button to add custom rules for enforcing https. Why is this functionality gone? Is there any way to restore it?

**Comment by reedy** [comment]
![screenshot 2015-04-14 at 08 45 45](https://cloud.githubusercontent.com/assets/67615/7136854/ae76b98a-e282-11e4-88e1-dbbdb7b0fb15.png)


WFM?

**Comment by jsha** [comment]
@netheril96: Recently we changed it so the link only appears when you are on the HTTPS version of a site. The prevents people from accidentally adding rules for sites that don't support HTTPS. Now, you have to visit the HTTPS version of the site first to see if it works.

**Comment by netheril96** [comment]
@jsha 

OK, got it.
