### ISSUE TITLE
Add raur.co / instaradio.com

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1448]
Can you add https://raur.co/ as a ruleset?

instaradio.com doesn't have an HTTPS version available, but it is an exact copy of raur.co, so maybe HTTPS Everywhere could redirect instaradio.com to raur.co? Or maybe this could mess things up if any differences between the sites would appear in the future? Could this suggestion affect Instaradio's support e-mail, which uses instaradio.com as domain?

**Comment by KommX** [comment]
Why isn't instaradio.com available over HTTPS then? Isn't it a weird consctruction to deliver the HTTPS-version of a site on a totally different domain?!

**Comment by cypherpunk** [comment]
No idea. I find it weird as well. Maybe the people behind the sites didn't want to pay for two HTTPS certificates?
