### ISSUE TITLE
HTTPS Everywhere Conflicting with Office Edit in Chrome for macOS

### ISSUE THREAD

**Issue by iamsight** [EFForg/https-everywhere#14485]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain:

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Hello Everyone! 

I'm having issues with HTTPS Everywhere 2018.1.29 and Office Edit 122.2125.2127 in Chrome 64.0.3282.119 (Official Build) (64-bit) on macOS 10.13.3.

I've tested this on a fresh system, with only the extension installed. After installing the extensions, one will need to restart the browser, not just close and re-open (Mac issues), and try opening any Office file from within Web Google Drive.

Office Edit is used in Chrome to be able to edit, to a degree, MS Office files like doc, docx, xls, xlsx, etc, directly in Chrome, without the need for MS Office or an Office-like program application. One would simply open the file in Chrome to view or edit them. It also allows one to open the same files from Web Google Drive in the same mode, without the need to download the files to open them, nor convert them to Google Docs files. Without Office Edit, the file will open in Preview mode. One can open the file in the appropriate Google Docs application but it will convert the file to a Google Docs file and one will be working on that version instead.

The issue occurs only when trying to open the office files from Google Drive. Doing so, will give me this error: 
![screen shot 2018-01-30 at 2 53 39 pm](https://user-images.githubusercontent.com/35973272/35588003-63868ff6-05cd-11e8-94e9-d7624617aac3.png)

This issue started on 01/19/2018. I've already contacted Google Support about this, and they passed the information to their engineers. Posting this here as well due to the extensions involved.

Has anyone experienced this issue or anything similar?

Thanks in advance and I hope you all have a great day!

**Comment by pipboy96** [comment]
I just tried that and I can't reproduce this error.
