### ISSUE TITLE
404 error pages triggered by HTTPS Everywhere on Google reverse image search

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1449]
Example: https://www.google.com/search?q=deadpool+game+gif&tbm=isch&tbs=simg:CAQSjAEaiQELEKjU2AQaBAgACAgMCxCwjKcIGmAKXggDEiikGb0M_1hjQHKkZrRmfGaEZng6_1DKwh2zzUJs8s0ybCLdU8pjrWJv0iGjBSX11B1Ug58_1J_1YRzOjEjIDswstmGUabx7ckeGhuNWpxbo_1cZ9SRTr49IRFUPQKDIMCxCOrv4IGgoKCAgBEgT9kRkzDA&sa=X&ei=_cIsVd7DPIGfsgHqpYGIDA&ved=0CBsQ2A4oAQ&biw=1366&bih=657

Ctrl + click on any of these images and a 404 page will appear.

Here is the 404 page for https://i.imgur.com/qhnjEbX.gif: https://www.google.com/www&ved=0CCcQMygKMAo

**Comment by reedy** [comment]
See #1494 - Does disabling the Google Video ruleset fix this?

**Comment by cypherpunk** [comment]
It seems to be working now, even though I haven't changed anything. Has an update for the Google Video ruleset been sent out already or is this change on Google's end?

**Comment by reedy** [comment]
Closing this as a dupe then
