### ISSUE TITLE
Request: help speccing out Dreamwidth ruleset reuse

### ISSUE THREAD

**Issue by brainwane** [EFForg/https-everywhere#14494]
Type: other

Per dreamwidth/dw-free#2042 and dreamwidth/dw-free#2088, the [Dreamwidth](http://dreamwidth.org/) journaling service and [open source project](https://www.dreamwidth.org/site/opensource) finds it useful to know the HTTPS URLs for several websites that its users use for, e.g., image embedding. In [this conversation](https://dw-dev.dreamwidth.org/203374.html?thread=1578606#cmt1578606) I said:

> [The image proxy-related change](https://github.com/dreamwidth/dw-free/pull/2088/) reminds me: CloudFlare and Brave use [our rules](https://github.com/EFForg/https-everywhere/tree/master/src/chrome/c%0Aontent/rules) to do automatic rewriting of requests to upgrade from HTTP to HTTPS and keep users safer. (The first item on [our architecture roadmap](https://lists.eff.org/pipermail/https-everywhere/2018-January/00276%0A0.html) is actually "signed rulesets", a feature to allow EFF to sign rulesets and thus allow users and downstreams to easily download rulesets on their own, outside the extension's updating mechanisms.) Would Dreamwidth be interested in getting [`https_url`](https://github.com/dreamwidth/dw-free/blob/90c4c7e51b54bf62df462527%0A0252011b76e95087/cgi-bin/LJ/CleanHTML.pm#L1652) to also draw from that set of rewrite rules?

and was told:

> That sounds like the same type of thing we tried with our `KNOWN_HTTPS_SITES` config ([pr #2042](dreamwidth/dw-free#2042)) and I think it would be an excellent idea to use your list going forward. Would you mind writing up an implementation spec as a Github issue for further discussion and eventual development?

Anybody want to help? Dreamwidth is written in Perl. I don't know Perl and I'm not a Dreamwidth developer but I've been a Dreamwidth user for years so I could help talk about potential use cases.

Maybe for now we could just have them reuse the work Brave does, in terms of grabbing our rulesets and turning them into something Dreamwidth can ingest? I could also imagine that this isn't something we can actually spec out until we're further along in the [sign-rulesets work](https://github.com/EFForg/https-everywhere/tree/sign-rulesets); let me know if that's so.

**Comment by jeremyn** [comment]
@brainwane : @diracdeltas described what they do for Brave at https://github.com/EFForg/https-everywhere/issues/12606#issuecomment-357807331. It seems fairly simple: download, unzip, repackage. Or are you soliciting help specifically in integrating the extracted rulesets into Dreamwidth?
