### ISSUE TITLE
nature.org URGENT you are redirecting people away from our donations pages

### ISSUE THREAD

**Issue by joerussbowman** [EFForg/https-everywhere#14523]
Type: ruleset issue

Domain: nature.org

You have this rule set for our nature.org domain 

`<rule from="^http://(support\.)?nature\.org/" to="https://www.nature.org/"/>`

support.nature.org is hosted by a third party vendor who processes our donations and provides other membership related content. www.nature.org is hosted by us.  You can check DNS and see that the CNAME for support.nature.org goes to a different organization, www is on akamai. We have spent a lot of time (months I think) trying to track this issue and finally a customer said they use your extension and we tracked it down. Please fix this ASAP, this is costing us both money and reputation.

**Comment by Bisaloo** [comment]
Thank you for your report and apologies for the inconvenience.

This is fixed in #14525 and will reach HTTPS Everywhere users in the next release.

**Comment by joerussbowman** [comment]
Thank you. What is your release schedule? That's the first question I will get from my marketing department.

**Comment by jeremyn** [comment]
@joerussbowman The EFF doesn't publish a release schedule, but you can get a sense of it through [this pull request query](https://github.com/EFForg/https-everywhere/pulls?q=is%3Apr+Release+in%3Atitle+is%3Aclosed).

The official email address for the extension is extension-devs@eff.org , available from https://www.eff.org/https-everywhere. You or your marketing department can try contacting them there.

**Comment by joerussbowman** [comment]
Thank you
