### ISSUE TITLE
steampowered.com: can't change language/add game to wishlist

### ISSUE THREAD

**Issue by Tailszefox** [EFForg/https-everywhere#1453]
On Firefox 37, using HTTPS Everywhere 5.0.2:

This issue has started appearing a few days ago.

Going on any page on steampowered.com (example: http://store.steampowered.com/app/327890/) and using the dropdown menu at the top to change language leads to the following error: "There was a problem saving your changes. Please try again later."

Also, adding a game to my wishlist leads to a "Oops, sorry" error message appearing above the button after a little while.

The only way I found to stop this and restore functionality was to disable the "Steam static.com (partial)" rule. After that, everything worked correctly again.

Trying to force HTTPS on steampowered.com just leads back to the regular HTTP version.

Could someone check if they have the same issue? This might mean the rule needs to be tweaked or disabled.

**Comment by reedy** [comment]
```
store.steampowered.com/:1 XMLHttpRequest cannot load https://store.steampowered.com/dynamicstore/userdata/?id=12246143. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
(index):1 XMLHttpRequest cannot load https://store.steampowered.com/api/addtowishlist. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
```

**Comment by Tailszefox** [comment]
Which rulesets do you mean? Even if I disable "Steam Powered.com (Partial)", I still get the error, and that's the only other Steam ruleset I can see.
![screenshot1](https://cloud.githubusercontent.com/assets/890677/7138609/c30f8cfc-e2c1-11e4-8178-2e27d9606023.png)

**Comment by reedy** [comment]
I mean I need both "Steam static.com (partial)" and "Steam Powered.com (partial)" both enabled for it not to work. With just one of them it works fine on Chrome

**Comment by jsha** [comment]
Looks like @2d1 fixed it with e1252c3. Can you verify and close? You can run the latest with `./test.sh --justrun`.

**Comment by Tailszefox** [comment]
I'm afraid I'm still getting the issue. This is after running `./test --justrun` as instructed, with the current code checked out from git.

![screenshot2](https://cloud.githubusercontent.com/assets/890677/7287470/2d5764a6-e955-11e4-924e-7d90e55133f3.png)

From the console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://store.steampowered.com/account/setlanguage/. This can be fixed by moving the resource to the same domain or enabling CORS. setlanguage
```

As I said above, disabling the "Steam powered.com" rule doesn't work (it's in light green anyway, which, if I understood correctly, means HTTPS Everywhere didn't need to do anything). Disabling the "Steam static.com" rule works, however.

Thus, I would guess the ruleset to be disabled/tweaked is the one in [src/chrome/content/rules/Steam_static.com.xml](https://github.com/EFForg/https-everywhere/blob/691be3b4bcb6540258ba895a037866ab48a87cca/src/chrome/content/rules/Steam_static.com.xml), rather than the one  e1252c3 touched.

**Comment by TechieKent** [comment]
This issue is not yet resolved. When loading http://store.steampowered.com/ after sign in, console log:
```
XMLHttpRequest cannot load https://store.steampowered.com/dynamicstore/userdata/?id=xxxxxxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
```

**Comment by Jamesits** [comment]
I've got this:
```
XMLHttpRequest cannot load https://store.steampowered.com/dynamicstore/userdata/?id=xxxxxxxxx&v=1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
(index):1 XMLHttpRequest cannot load https://store.steampowered.com/api/addtowishlist. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://store.steampowered.com' is therefore not allowed access.
```

**Comment by reedy** [comment]
Of course, Steam need to add the Access-Control-Allow-Origin headers...

TBH, I'm tempted to just disable all the Steam rulesets as broken for now

**Comment by reedy** [comment]
Closing issue as steam rulesets disabled in 726b2e7799f1afa84174aa2628b2225e33ab6722
