### ISSUE TITLE
etrade.com/activate does not work with https

### ISSUE THREAD

**Issue by cdleonard** [EFForg/https-everywhere#14541]
Type: ruleset issue
Domain: etrade.com

When etrade sends "Activate Your New Stock Plan Account" email it points users to http://etrade.com/activate and that page redirects to a more elaborate signup url. For some reason going to https://etrade.com/activate (enforced by https-everywhere) sends you to a 404 page instead (https://us.etrade.com/pagenotfound.html).

This looks like a bug on etrade's part but the result is very confusing so maybe http://etrade.com/activate shouldn't be switched to https.

It should be easy to test this even without an etrade account.

**Comment by pipboy96** [comment]
Can reproduce.

**Comment by pipboy96** [comment]
No longer can reproduce, the link no longer leads to a 404 error page.
