### ISSUE TITLE
Consolidate eff.org pages

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#14565]
Type: other

Currently, our [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md) document is being updated relatively frequently and has up-to-date information for those interested in the project.

On EFF.org, we have several pages which are quite out of date, and serve an overlapping purpose as [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md):

- https://www.eff.org/https-everywhere/development
- https://www.eff.org/https-everywhere/rulesets

These have some useful information, but much of it can be migrated into [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md).  We can then issue a 301 for those pages to something like https://www.eff.org/https-everywhere/contributing.  We should also create a symbolic link from `docs/en_US/contributing.md` to [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md)

**Comment by Hainish** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/4588

**Comment by sampablokuper** [comment]
Related: #14579 .
