### ISSUE TITLE
Carsdirect.com breaks completely

### ISSUE THREAD

**Issue by Jacalz** [EFForg/https-everywhere#14577]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: carsdirect.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The site breaks completely when using both Brave and Chrome: https://github.com/brave/browser-laptop/issues/7460
![image](https://user-images.githubusercontent.com/25466657/36043715-8692ce8c-0dd0-11e8-8774-238d7a0884a6.png)

Without https everywhere:
![image](https://user-images.githubusercontent.com/25466657/36043754-a78c9b68-0dd0-11e8-8bfb-6b50325e09f7.png)

**Comment by Bisaloo** [comment]
Thanks a lot for posting here @Jacalz! It is really helpful.

This kind of issues are easy to fix but we can't do much if we don't hear about it.
