### ISSUE TITLE
Update certificates to latest NSS

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#14636]
Type: other

Following from discussion in https://github.com/EFForg/https-everywhere/issues/5613#issuecomment-365798279 with @jeremyn, let's update our root certificate store to the latest NSS.

From that issue:

> https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/ seems to indicate that we can use [this file](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt) to determine the NSS root certificates.  Getting it into a format `curl` can handle is a different story.  https://gist.github.com/jjb/996292 provides some additional context here, including that we can use http://curl.haxx.se/ca/cacert.pem for the root store.

**Comment by Bisaloo** [comment]
This seems pretty straightforward using the `curl` tool called [`mk-ca-bundle`](https://raw.githubusercontent.com/curl/curl/master/lib/mk-ca-bundle.pl).

I can try and submit a PR later today.

**Comment by Hainish** [comment]
@Bisaloo this is also a matter of having our testing infrastructure in `test/rules/src/https_everywhere_checker/` actually use the updated certificates.  Which probably involves setting a `pycurl` option for `cafile` and removing the `capath` option.

**Comment by Hainish** [comment]
For reference, https://github.com/EFForg/https-everywhere/blob/d3117679e1f243a93f3a489ac8d65990da9fcd14/test/rules/certs_transitive_closure/build_closure.sh tries to account for sites that fail to deliver full certificate chains (but may be seen as valid due to browser intermediate cacheing) by building those chains as a transitive closure and dumping it to a directory.

We shouldn't use this method for fetch validation, as we'll see false positives for such sites.  If a fresh browser fails to validate the certificate for a site, we shouldn't enable it in the rulesets.

**Comment by Hainish** [comment]
I've performed some cleanup on `test/rules` in https://github.com/EFForg/https-everywhere/pull/14653

**Comment by jeremyn** [comment]
@J0WI See issue https://github.com/EFForg/https-everywhere/issues/14738. Also, PR https://github.com/EFForg/https-everywhere/pull/14643 should help streamline our own certificate store.
