### ISSUE TITLE
mathjax.org may need ruleset updated

### ISSUE THREAD

**Issue by noloader** [EFForg/https-everywhere#14654]
We are having a math formula [rendering problem on our wiki](https://github.com/jmnote/SimpleMathJax/issues/12). The math markup occurs with [Simple MathJax](https://github.com/jmnote/SimpleMathJax).

According to  [HTTPS Everywhere Atlas | mathjax.org](https://www.eff.org/https-everywhere/atlas/domains/mathjax.org.html):

> The release branch contains the following rules that are enabled by default:
> 
> ```
> <ruleset name="MathJax.org">
> 	<target host="mathjax.org"/>
> 	<target host="www.mathjax.org"/>
> 	<target host="beta.mathjax.org"/>
> 		<test url="http://beta.mathjax.org/mathjax/latest/test/localization.html"/>
> 	<target host="cdn.mathjax.org"/>
> 		<test url="http://cdn.mathjax.org/mathjax/latest/docs/html/platforms/index.html"/>
> 	<target host="docs.mathjax.org"/>
> 
> 	<securecookie host=".+" name=".+"/>
> 
> 	<rule from="^http:" to="https:"/>
> </ruleset>
> ```

MathJax's CDN allows HTTPS now.  From [Using the MathJax Content Delivery Network CDN](https://docs.mathjax.org/en/latest/start.html#using-the-mathjax-content-delivery-network-cdn):

> We retired our self-hosted CDN at cdn.mathjax.org in April, 2017. We recommend using cdnjs.com.
> 
> To jump start using cdnjs, you accomplish the first step by putting
> 
> ```
> <script type="text/javascript" async
>   src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">
> </script>
> ```
> 
> into the <head> block of your document...

I don't quite understand the ruleset above, but it looks like it is using HTTP instead of the {newly|recently|?} supported HTTPS. It is also using the wrong domain for HTTPS.

Please consider enabling HTTPS for MathJax requests, and please consider using the new CDN.

[//]: # (Type: ruleset issue)

**Comment by noloader** [comment]
@https-everywhere-bot,

Thanks, done.

**Comment by noloader** [comment]
@https-everywhere-bot,

Thanks, done.

By the way, when you say *"Can you edit your issue to add this"*, you might consider being more prescriptive. I was not sure if you wanted it in the title or the body. I also was not sure if you wanted the extra markup, like the `[//]`. I added field and the extra markup in the body assuming you use it to parse the field.

**Comment by Bisaloo** [comment]
When @https-everywhere-bot says "this" in this context, it refers to the issue type.

In this case, it would be `Type: ruleset issue`.

**Comment by Bisaloo** [comment]
This is not a HTTPS Everywhere issue. I can reproduce with HTTPS Everywhere disabled in Firefox and I can't reproduce with HTTPS Everywhere enabled in Chromium.

Firefox finds active mixed content from http://csp.azureedge.net/cdn/widget/fonts/icomoon.woff?-4tk0iu. Maybe, you should start here.

**Comment by noloader** [comment]
Thanks @Bisaloo.

**Comment by Bisaloo** [comment]
You are right. I don't see requests to azureedge.net anymore. Weird. I have no idea what could be causing the issue on your website.

**Comment by noloader** [comment]
@Bisaloo ,

Ack, thanks. Thanks for the help in ruling out HTTPS Everywhere.

I love the tool. I've been using it for years. keep up the great work.
