### ISSUE TITLE
Duplicate label for MCB in issue tracker

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#14679]
Type: other

We currently have 2 labels for MCB issues:

- [`broken MCB`](https://github.com/EFForg/https-everywhere/issues?q=label%3A%22broken+MCB%22)
- [`mixed-content-bug`](https://github.com/EFForg/https-everywhere/issues?q=label%3Amixed-content-bug)

`broken MCB` seems more popular but I am fine with keeping one or the other.

**Comment by jeremyn** [comment]
@Bisaloo You meant https://github.com/EFForg/https-everywhere/issues?q=label%3A%22broken+MCB%22 for your first link.

**Comment by jeremyn** [comment]
I've added `broken MCB` to all the `mixed-content-bug` issues and deleted the `mixed-content-bug` label. If someone wants to rename `broken MCB` to something else, that's fine with me.

**Comment by Bisaloo** [comment]
Thank you @jeremyn. Closing this issue.
