### ISSUE TITLE
ti.com pdf redirect is broken

### ISSUE THREAD

**Issue by dhead666** [EFForg/https-everywhere#1467]
While ti.com allow https access to the site, the pdf redirects only works for http, for example try to download the datasheet from https://www.ti.com/product/tps65251 while the extension is enabled.

I'm guessing that the fault is the webserver, so I reported this on ti.com, but it would be nice to have a workaround in the extension.

**Comment by reedy** [comment]
Are all the PDF links like http://www.ti.com/lit/gpn/tps65251?

Presumably we can just set /lit/ as an exclusion?

**Comment by dhead666** [comment]
From what I've seen so far all pdf links are like this: `http://www.ti.com/lit/*/*` , so `/lit/`as exclusion should fit.

I believe also `/general/docs/lit/` should be excluded as for example `www.ti.com/lit/pdf/spruer9` will redirect to `http://www.ti.com/general/docs/lit/getliterature.tsp?baseLiteratureNumber=spruer9&fileType=pdf` that in turn redirects to the actual pdf at `http://www.ti.com/lit/ug/spruer9d/spruer9d.pdf`
