### ISSUE TITLE
Wolfram alpha breaking

### ISSUE THREAD

**Issue by gregoryka** [EFForg/https-everywhere#14716]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: m.wolframalpha.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

When asking wolfram alpha to, for example, "plot sin(x)sin(y)", the website doesn't show anything. From a quick check, this only happens on the mobile subdomain, and doesn't happen on the desktop version at www.wolframalpha.com. Also, chrome gave a mixed content warning for the mobile subdoamin loading resources from one of the wolfram CDNs. Possibly incomplete deployment of HTTPS on the wolfram side, however the extension changes the default, and consequently breaks the site.

**Comment by Bisaloo** [comment]
Thank you for your report! It was a tricky one. The current ruleset was redirecting images with the result to the wrong subdomain, causing `404`.

**Comment by Bisaloo** [comment]
The mixed content warning is about passive mixed content so it should not be causing issues.
