### ISSUE TITLE
HTTPS Everywhere absolutely does not work in Palemoon / Linux Mint 18

### ISSUE THREAD

**Issue by gethob1** [EFForg/https-everywhere#14726]
I don't know what type of issue this is, so I guess:
Type: code issue

It's enabled in about:addons and it's set to auto-update but all links open to http:// by default.  I'd much appreciate some attention to this.

Thanks

**Comment by J0WI** [comment]
Duplicate of #1315. Palemoon is not an officially supported platform, so it isn't expected to work.
