### ISSUE TITLE
Prepare for Symantec distrust

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#14738]
Type: other

With the upcoming [Symantec distrust](https://wiki.mozilla.org/CA:Symantec_Issues) by the major browsers, I expect a large number of rules will cause issues. For Firefox, it will reach the `release` channel in May.

It may be good to run a `full-fetch-test` around this time to disable all remaining Symantec certs hosts.

This [partial list of Symantec hosts](https://bugzilla.mozilla.org/show_bug.cgi?id=1434300#c81) may also be useful.

**Comment by J0WI** [comment]
There is still a long list of open ToDo's in #13829 before we should run a `full-fetch-test` again.
I would also like to give site owners some additional time to fix their certs.

**Comment by Bisaloo** [comment]
> I would also like to give site owners some additional time to fix their certs (or at least limit it to Alexa top-x first).

The distrust has been planned and announced a long time ago. FF and Chromium have been printing warnings in the dev console for months now, saying webmasters should update their certs. This is already causing `Invalid certificate` warning pages in Nightly.

I think May is more than enough time for any serious site owner to renew their certs.

**Comment by J0WI** [comment]
Referring to [Mozilla's TLS Canary result](https://bug1434300.bmoattachments.org/attachment.cgi?id=8953466) 3% of top-10k are currently affected. Thats still too much.

**Comment by Bisaloo** [comment]
I'm using Nightly as my daily browser so I'm just going to dump a list of broken host because of the Symantec distrust. We can go through this list at a later date and see which rulesets need to be disabled:

- https://weburg.me/

Let me know if I should update this list somewhere else, such as the wiki.

**Comment by J0WI** [comment]
I did not yet start to address this during reviews, I still hope that most of them will fix their certs.

**Comment by cschanaj** [comment]
@Hainish C70 will reach stable by the end of October (https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html), it might worth addressing this issue ASAP.

**Comment by J0WI** [comment]
Same for Firefox. Release date is 2018-10-23.
There are still some sites with an affected certificate. I wonder how long it takes until they update (probably some days after the releases).

**Comment by Hainish** [comment]
Are we still observing outages due to Symantec distrusts, or should this issue be closed?

**Comment by J0WI** [comment]
These are the latest stats we have: https://tlscanary.mozilla.org/runs/2018-11-01-11-02-45/index.htm (~4k of top 1M, 0.4%)
New stats might be produced here: https://bugzilla.mozilla.org/show_bug.cgi?id=1498062

**Comment by pipboy96** [comment]
What's the status of this?

**Comment by J0WI** [comment]
I think the certificates in our ruleset tests need to be updated.

**Comment by pipboy96** [comment]
@J0WI Should I create a PR with an updated CA store?

**Comment by zoracon** [comment]
This was updated with the last fetch test
