### ISSUE TITLE
AmazonWebServices breaks social buttons

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#14731]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: https://informationisbeautiful.net/

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)
![image](https://user-images.githubusercontent.com/12802056/36580394-0c15180c-1836-11e8-89af-abf4bf20cfc0.png)

**Comment by Bisaloo** [comment]
I can't reproduce. Tested with Chromium and a fresh profile on Firefox.

**Comment by terrorist96** [comment]
Did you bypass cache when refreshing? Or delete cookies?

**Comment by Bisaloo** [comment]
Yes. I hadn't anything cached on my fresh profile anyway.

**Comment by terrorist96** [comment]
What about this link
http://informationisbeautiful.net/visualizations/snake-oil-scientific-evidence-for-nutritional-supplements-vizsweet/

**Comment by Bisaloo** [comment]
Yep, CORS issue caused by the HTTP redirect.
