### ISSUE TITLE
www.nicovideo.jp broken due to Nimg.jp rule

### ISSUE THREAD

**Issue by a4lg** [EFForg/https-everywhere#14774]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: www.nicovideo.jp

Alexa Internet: https://www.alexa.com/siteinfo/nicovideo.jp [Global rank 99]

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

# Issue

We cannot watch videos in Nico Nico Douga [ニコニコ動画] while HTTPS Everywhere enabled because the browser (Firefox in my case) blocks requests to two important scripts (with hexadecimal digits as a query string):

* http://nicovideo.cdn.nimg.jp/web/scripts/pages/watch/watch_app.js
* http://nicovideo.cdn.nimg.jp/web/scripts/pages/watch/watch_dll.js

Firefox displays a log like this (this is not the exact error because the original message is in Japanese):

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://nicovideo.cdn.nimg.jp/web/scripts/pages/watch/watch_dll.js?75d596f4. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

Relevant HTML (portions) from http://www.nicovideo.jp/watch/sm9 (while logged in):

```html
        <script type="text/javascript" src="http://nicovideo.cdn.nimg.jp/web/scripts/pages/watch/watch_dll.js?75d596f4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="http://nicovideo.cdn.nimg.jp/web/scripts/pages/watch/watch_app.js?03cef3e5" crossorigin="anonymous"></script>
```

# Workaround

Disabling "Nimg.jp" rule temporally resolves the problem. However, other than two scripts above (with `crossorigin="anonymous"`), there's no problem loading with HTTPS.

**Comment by Bisaloo** [comment]
Thank you for your detailed bug report! #14774 fixes the issue you are describing.

Related: #10674
