### ISSUE TITLE
Add ruleset for crazyhd.com

### ISSUE THREAD

**Issue by SeriousHoax** [EFForg/https-everywhere#14777]
Add a rule for http://crazyhd.com 
It's a private tracker.
HTTPS Everywhere has no ruleset for this website so it always loads in HTTP in spite of the site having HTTPS version.

**Comment by SeriousHoax** [comment]
Hmm I see what you mean. Actually, I didn't even know they have HTTPS. I manually added a ruleset for myself. Everything is working fine.

**Comment by injust** [comment]
Landing page now redirects to HTTPS and I can't observe any AMC issues.
