### ISSUE TITLE
Explain `mixedcontent` platform

### ISSUE THREAD

**Issue by sampablokuper** [EFForg/https-everywhere#14808]
Type: other

This issue report was opened to track the documentation enhancement suggested below.

@Hainish [wrote](https://github.com/EFForg/https-everywhere/pull/14788#issuecomment-369109896):
> It may be worth including a small section on the `mixedcontent` platform, but this will have to be edited from the text in [this PR](https://github.com/EFForg/https-everywhere/pull/14788)

**Comment by zoracon** [comment]
Resolved
