### ISSUE TITLE
Ruleset issue for http://www.spiegel.de - cannot be accessed since 20180301 when SPIEGEL introduced a very aggressive Anti-AdBlocking strategy

### ISSUE THREAD

**Issue by Wikinaut** [EFForg/https-everywhere#14835]
Type: ruleset issue

Domain: http://www.spiegel.de since 20180301

SPIEGEL Online has introduced a new very aggressive Anti-AdBlocker strategy. Disabling AdBlockers alone does not allow to access SPIEGEL Online anymore, as long as HTTPSEverywhere is active.

Disabling HTTPSEverywhere helps.

Perhaps you can fix the ruleset.

**Comment by Bisaloo** [comment]
It seems possible to block their anti-adblocking script. The best fix is probably to wait until anti-anti-adblocking lists pick this up.

In the meantime, you can disable the `Fastly.net (partial)` rule to fix this and I will have a look at our ruleset.

**Comment by Wikinaut** [comment]
@Bisaloo wrote
> In the meantime, you can disable the Fastly.net (partial) rule to fix this and I will have a look at our ruleset.

Confirmed!

**Comment by numismatika** [comment]
the spiegel-de.spiegel.de subdomain supports TLS so instead of an exclusion, maybe we can just change the Spiegel.de rule @Bisaloo ?

**Comment by Bisaloo** [comment]
Do you want to do it @numismatika?

**Comment by DavidLiedke** [comment]
@Bisaloo  #14508

**Comment by Bisaloo** [comment]
Nice! I missed this. Can you add `spiegel-de.spiegel.de` as a target? If so, I will close #14836.

**Comment by DavidLiedke** [comment]
Done.

**Comment by pipboy96** [comment]
No longer reproducible.
