### ISSUE TITLE
please fix the rulset for natl.io

### ISSUE THREAD

**Issue by geeknik** [EFForg/https-everywhere#14845]
Type: ruleset issue
Domain: natl.io

![screenshot_2018-03-04_00-05-27](https://user-images.githubusercontent.com/466878/36942752-1728b972-1f40-11e8-8ae4-1ea5bc57a84d.png)

**Comment by Bisaloo** [comment]
Hi, thank you for your report. We don't have a rule for this domain so this is probably not a bug in HTTPS Everywhere.

Can you try visit http://natl.io/? It should work fine.

Did you check "Block all unencrypted requests" by any chance?

**Comment by geeknik** [comment]
When I click on http://natl.io it redirects to https://www.po.st which is to be expected, however, when I click on http://natl.io/PGsegH it tries to load `https://natl.io/scmf/OrMCe04Lcp0lOEEx-z9GKWkL3054RTxIEHE_MJ2-QtFu7D80ez9FrRYIvkt9QJPJpXgKmKUB27ElOAo/PGsegH` and we get the `connection is not secure` message. When I disable HTTPS Everywhere and click on http://natl.io/PGsegH, it redirects correctly to https://www.nationalreview.com/blog/corner/lowering-voting-age-response-parkland-shooting-misguided/. I do not have `Block all unencrypted requests` checked and the icon is blue.

**Comment by Bisaloo** [comment]
Thank you for the additional details! It was a bit tricky to pinpoint the exact problem.

I identified the issue and fixed it in #14846.

**Comment by J0WI** [comment]
closed by #14846.
