### ISSUE TITLE
HTTPS breaks discordapp.com docs

### ISSUE THREAD

**Issue by Foorack** [EFForg/https-everywhere#14889]
Type: ruleset issue

Domain: https://discordapp.com/developers/docs/topics/response-codes

**Comment by Bisaloo** [comment]
Are you sure this is a HTTPS Everywhere issue? I can't reproduce on a fresh profile. Could you provide more details please?

(As a side note, uBlock origin seems to be causing issues on this page for me.)

**Comment by Foorack** [comment]
@Bisaloo Could very much be uBlock Origin has I have that installed as well. Thanks. Closing this as invalid.

**Comment by Bisaloo** [comment]
Actually, this looks like random failures because of the server configuration. I get blank pages / spinner stuck forever even without any extensions on a fresh profile. Not sure what's going on exactly... maybe this should be reported to discord devs.
