### ISSUE TITLE
Breaks Bing login in Firefox

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#14918]
Type: ruleset issue
Domain: www.bing.com

(Version: 2018.3.13)
Firefox 58

#### To reproduce:
- Log in to Microsoft account through Outlook.com
- Open Bing, click Sign in

#### Expected:
Without HTTPS Everywhere, signs into Bing automatically.

#### Actual:
Bing refreshes without signing into account.

Not repro in Chrome

**Comment by Bisaloo** [comment]
I could not reproduce this issue. Did you try on a fresh profile with only HTTPS Everywhere installed?

**Comment by wesinator** [comment]
Apologies, you are correct; the issue is with `network.http.referer.XOriginPolicy`

I need to do more testing before I go reporting issues :)
