### ISSUE TITLE
Unable to save large rulesets in debugging tool in Chrome

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#14927]
Type: code issue

Using Chrome `65.0.3325.162 (Official Build) (64-bit)`, it is not possible to save large rulesets in the <kbd>Ctrl-Z</kbd> debugging tool. As an example, copy and paste [`AmazonAWS.com.xml`](https://github.com/EFForg/https-everywhere/blob/f4cc5995e267f3f254d0e483a57d02c20bef5c13/src/chrome/content/rules/AmazonAWS.com.xml) into the debugging tool's text area, save, and refresh the debugging tool page. You will see the original content of the text area incorrectly replace the `AmazonAWS.com.xml` content you just added.

This problem is likely because the StorageArea `chrome.storage.sync` has a `QUOTA_BYTES_PER_ITEM` value of 8192. See https://developer.chrome.com/apps/storage .

Ping @Hainish .

**Comment by pipboy96** [comment]
We definitely shouldn't put debugging rulesets in `chrome.storage.sync`.
