### ISSUE TITLE
HTTPS on fmylife.com broken

### ISSUE THREAD

**Issue by cremor** [EFForg/https-everywhere#14925]
Type: ruleset issue

Domain: fmylife.com

A few months ago HTTPS on http://www.fmylife.com stopped working. It now just shows various HTTP error codes on a Cloudflare error page, see https://www.fmylife.com. I don't know why, but they still didn't fix it, so I suggest to disable the rule for the site.

**Comment by Bisaloo** [comment]
Thank you for you report! Would you like to submit a PR yourself to disable this ruleset?

**Comment by cremor** [comment]
I haven't worked with the rules before, so I would have to check how they work first. I don't know when I will find some time for this. If it's just a small change it would be more efficient if someone else does it.
