### ISSUE TITLE
Enable web.archive.org rule by default

### ISSUE THREAD

**Issue by PiRSquared17** [EFForg/https-everywhere#1492]
I don't see why this should be disabled considering Internet-Archive.xml is enabled by default.  Also, please rewrite http://waybackmachine.org/foo to https://web.archive.org/foo if possible. Thanks.

**Comment by reedy** [comment]
```
<ruleset name="Archive.org Way Back Machine" default_off="webmaster request">
```

https://github.com/EFForg/https-everywhere/commit/a4c9a3bae406beeccf73969016cece846dae4030

Maybe @2d1 can clarify why this was requested. web.archive.org goes to *.us.archive.org (for me in the USA), which is then secured by the Internet-Archive.xml ruleset too
