### ISSUE TITLE
Discussion: using the mailing list

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#14939]
Type: other

I see that there have been some discussions on the [HTTPS Everywhere mailing list](https://lists.eff.org/pipermail/https-everywhere/) recently. However, it's not clear to me when a discussion should happen on GitHub, and when it should happen on the mailing list. I'd like to have a discussion here about why people are using the mailing list, and when we should use the mailing list, if ever, instead of just some people randomly having some discussions over there that other people may not know about.

I hope by the end of this discussion that it will be clear when a discussion should happen on GitHub, or when it should happen on the mailing list, and that the reasons will be understood and agreed to by most or all of the current regular contributors and maintainers.

Ping @Bisaloo @brainwane @gloomy-ghost @Hainish @J0WI @wonderchook .

**Comment by jeremyn** [comment]
My own take is that I would prefer GitHub for all discussions. Reasons include:

* the large majority of historical activity for the project is already in GitHub
* GitHub users are authenticated and their current history with the project is readily available
* it is more difficult to be anonymous in email than on GitHub

**Comment by Bisaloo** [comment]
My main issue with the way things are going right now is that important policy decisions are scattered in comments all over this bug tracker. I have had moments in the past months where I discovered something important was being discussed in an issue I was not following. This makes it harder for users and contributors to share their opinions on important discussions about this extensions future.

I don't think a mailing list is better suited for this purpose *per se* but it seems useful to have a specific place to have all policy discussion. It would be easier not to miss anything this way.

**Comment by jeremyn** [comment]
From https://lists.eff.org/pipermail/https-everywhere/2018-February/002766.html :
 
>`#` Discussions
>
>Discussions currently happen through GitHub issues, which only reach
>those people who are following every update to the repository.
>Discussions should be moved to the mailing list instead, to have a wider
>audience. Once decisions are made, each decision should be documented
>either as an action in a GitHub issue or through an update to documentation.
>
>To do:
>
>Move discussions to mailing list
>Start practice of consistently documenting decisions

(I'm including this here as an "FYI, this was in the mailing list", not to say I agree with it.)

**Comment by wonderchook** [comment]
I think if the HTTPS Everywhere community is to grow to have all the discussions in Github issues is going to be limiting. For the reasons listed above. Most other open-source communities have a ticket tracker and then somewhere else to connect as well. Typically this is a mailing list or discussion board.

**Comment by jeremyn** [comment]
There are various ways we could promote a more unified view of discussion issues without leaving GitHub. One way is to simply look at the GitHub issues list with the `question` label, like:

https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+is%3Aissue+label%3Aquestion

We could refer to this link in `CONTRIBUTING.md` and elsewhere. Other options include having a Wiki page that links to all discussion issues, something in the Projects tab, something with [team discussions](https://help.github.com/articles/about-team-discussions/), or something with an RSS feed.

**Comment by Hainish** [comment]
I agree with @Bisaloo and @wonderchook's sentiments here.  For specific issues, GitHub is the right place.  Where general discussion about the project is concerned, the reasoning is to use the mailing list as a PSA.  I don't see this as abandoning GitHub, and in the past general project discussion has occurred in an email list.  Even with the `question` label, not everyone checks GitHub every day, or automatically follows those issues.  And not every issue for general discussion is a question.

**Comment by jeremyn** [comment]
So, practically speaking, if the EFF wants to use a mailing list to make major announcements ("PSAs") and doesn't care if there is little-to-no community feedback, then that's one thing. I can see that making GitHub issues for big announcements might be awkward.

On the other hand if the EFF wants the community to start using a mailing list in place of GitHub in some cases, then I think the EFF needs to somehow guide the community's behavior to do that. I don't know what that guiding will look like. @Hainish, @wonderchook , what do you think?

**Comment by Hainish** [comment]
> doesn't care if there is little-to-no community feedback

I find this an extreme sentiment.  The HTTPS Everywhere mailing list is publicly archived, open to subscribe to, and has a large subscriber base (currently 284 members).  If anything, this would solicit more participation than posting something on GitHub in the *hopes* that someone will see it.  GitHub is the exclusionary platform here, not a mailing list.

An additional concern is that HTTPS Everywhere shouldn't limit itself to _just_ coders.  Let's be honest with ourselves. GitHub is a forum for coders, and excludes involvement in the project by other groups - the translator community, graphic artists, etc.  A mailing list does not have these limitations.

> On the other hand if the EFF wants the community to start using a mailing list in place of GitHub in some cases, then I think the EFF needs to somehow guide the community's behavior to do that.

Promoting the HTTPS Everywhere mailing list in search engine rankings, so that when people search for the project they see this as one of the first results.

We already highlight the mailing list as the predominant forum for discussion, before we mention GitHub, in `CONTRIBUTING.md`:

https://github.com/EFForg/https-everywhere/blob/be46a16494829e8537c354273a4167292acae938/CONTRIBUTING.md#L46

**Comment by jeremyn** [comment]
@Hainish I know the EFF cares about community feedback in a general way, but the question is, what is the goal of the mailing list? For example Tor has multiple mailing lists, described at https://www.torproject.org/docs/documentation.html.en , and two of them are described as:

> * [tor-announce](https://lists.torproject.org/cgi-bin/mailman/listinfo/tor-announce/) is a low volume list for announcements of new releases and critical security updates. Everybody should be on this list. There is also an [RSS feed](http://rss.gmane.org/gmane.network.tor.announce).
> * [tor-talk](https://lists.torproject.org/cgi-bin/mailman/listinfo/tor-talk/) is where a lot of discussion happens, and is where we send notifications of prerelease versions and release candidates.

If you want the current mailing list to be more like tor-announce, where you release announcements and that's it, then you're on the right track. On the other hand if you want it to be more like tor-talk, with ongoing community discussions, then more work needs to be done ("guiding").

Your response about search engine rankings and `CONTRIBUTING.md` suggests you are relying on new contributors or new community members to start using the mailing list, and then it will eventually achieve critical mass. Is that right?

**Comment by jeremyn** [comment]
This discussion seems to have stopped. I'm not sure if people are just considering their responses, or if people are done talking about this. In any case I'll probably close this issue soon unless someone says they want to keep it going.

**Comment by jeremyn** [comment]
I'm closing this issue as mentioned in my previous comment.
