### ISSUE TITLE
Saved Responses for Maintainers

### ISSUE THREAD

**Issue by wonderchook** [EFForg/https-everywhere#14935]
Type: other

I've drafted some possible themes for saved replies for maintainers. The idea is by having saved replies it will save the maintainers some time when responding to contributions and have a friendly tone. I also included a couple more at the bottom that other projects use, but would be a change to our current workflow. 

* Delay in Updating a PR: Thank you for your work on this ruleset. Are you interested in continuing to work on it to finalize the suggested changes? 
* Duplicate Issue: Thank you for your submission. This issue is already duplicated in Issue ________. 
* Resolved bug: Thank you for your bug report, the issue has been resolved here.
* Suggested ruleset: Thank you for suggesting a ruleset. Did you know you can also submit new rulesets yourself?  To get started on that view [our guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#contributing-rulesets). 
* Failed tests: The tests have failed on your ruleset. Can you please confirm the issue in Travis?
* Update this PR, don't close it: The next time you need to update a pull request, you don't need to close the old one and open a new one. You can update your pull request and we recommend you do that (instead of closing the old PR and opening a new one) because then it's easier to see the history of what you've done, to check that you've responded to previous reviewers' comments, and to preserve links we've mentioned (in comments) with other issues and PRs.
* Good first issue: This issue is good for first time contributors. If there is not a corresponding pull request for this issue, it is up for grabs. For directions for getting set up, see [our Contributing Guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#contributing-rulesets) Guide. If you are working on this issue and have questions, please feel free to ask them here or on the [HTTPS Everywhere mailing list](https://lists.eff.org/mailman/listinfo/https-everywhere).

Other suggested messages (borrowed from Zulip)

* up for grabs* (for usage when someone says "may I work on this?": Yes, please go ahead and grab this issue! At least within Warehouse, our rule is: If there is not a corresponding pull request for this issue (visibly linked by issue number/PR number), and it's not marked as assigned to anyone, it is up for grabs. So in cases like this, you don't even need to ask. :) Just comment and say that you're starting to work on it, and link in a comment to your work-in-progress branch once you start.
As always, if you have questions along the way as you work on this, please feel free to ask them here, in [`#pypa-dev` on Freenode](https://webchat.freenode.net/?channels=%23pypa-dev), or the [pypa-dev mailing list](https://groups.google.com/forum/#!forum/pypa-dev). Thank you!

* better commit message: Thanks for writing a descriptive commit message. [Here's a guide to help you write commit messages](https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages) that are more consistent with our style, which makes it easier for us in the future -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly  understand what's happening.
[Here are some tips on tidying your commit history, including changing your commit messages.](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) And when you update your code or your commit message, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

**Comment by jeremyn** [comment]
For day-to-day usage I would prefer to write my own responses instead of using templates. However these could be useful if there is a sort of intense issue/PR-resolving effort by non-regular maintainers, like the hackathon proposed at https://github.com/EFForg/https-everywhere/issues/13890#issuecomment-364229199. These might also be useful for regular maintainers who don't feel comfortable with their own English language skills, though I'm not sure if this is a problem with our current maintainers.

**Comment by brainwane** [comment]
In my own maintainership work, I've found that templates (which I customize each time I use them) make it easier to reply faster, and to make sure I consistently link to useful resources. Individual maintainers who struggle with emotional labor could also use templates similarly to how the bottom of the MetaFilter comment box always says "Everybody needs a hug.", to remind you that there's a person on the other side of the screen and you ought to try to see things from their point of view. :)

**Comment by jeremyn** [comment]
FYI to anyone interested in using these, GitHub supports saved replies, see https://help.github.com/articles/working-with-saved-replies/ . You don't need to cut/paste these yourself.

**Comment by zoracon** [comment]
Put these in a page in the wiki for on boarding new maintainers. I have also utilized saved replies, but unfortunately you can't put these at the repo level.
https://github.com/EFForg/https-everywhere/wiki/New-Maintainers:-Sample-Responses-for-Maintainers

Also, we now have PR templates with similar wording.
