### ISSUE TITLE
Standard for Non-working Hosts?

### ISSUE THREAD

**Issue by wonderchook** [EFForg/https-everywhere#14936]
Type: feature request

Currently, there is not a standard for the comments regarding non-working hosts. This inhibits automation of ruleset testing. By creating a parsable standard it would enable automation and ease some of the manual role in ruleset testing. 

[Documentation on nonworking hosts
](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#non-working-hosts)

It seems a little weird for this to remain as a comment and maybe it should have a standard elsewhere i the XML.

**Comment by numismatika** [comment]
First problem i see is that sometimes people just cut of the common part of the domain
Instead of some.subdomain.domain.com and another.subdomain.domain.com 
the domain.com is left out and it becomes
```
Cert mismatch on:
- some.subdomain
- another.subdomain
```

**Comment by wonderchook** [comment]
I definitely don't think this is an easy fix. I think if I was going to implement it I would suggest coming up with a standard and applying for new hosts to start. Then as hosts are modified add them to the standard. It would be a slow path, but at least would make verifying new hosts easier.

**Comment by jeremyn** [comment]
There are open questions about what value there is marking non-working hosts, and what comments should be allowed in rulesets generally. Until those questions are answered and affirmatively agreed to by all the active ruleset maintainers, this sort of documentation effort, while a good idea and meaning no disrespect to @wonderchook , is unlikely to be successful.
