### ISSUE TITLE
Breaks Thumbnail Zoom Plus extension (5.0.2 w/ Firefox 37.0.1)

### ISSUE THREAD

**Issue by dadler** [EFForg/https-everywhere#1495]
Https-everywhere 5.0.2 with Firefox 37.0.01 breaks Thumbnail Zoom Plus 3.3.  Some links show TZP's yellow "!" error icon for a second instead of showing a pop-up image.  It works with https-everywhere 4.0.3

I'm the developer of Thumbnail Zoom Plus.  This is spawned from [TZP issue 207](https://github.com/dadler/thumbnail-zoom/issues/207).

This may be related to #1398 since I see that error message when TZP tries to show the pop-up.

To reproduce:

1. Install Thumbnail Zoom Plus 3.3 (from https://addons.mozilla.org/en-US/firefox/addon/thumbnail-zoom-plus/ ), disable or uninstall https-everywhere, and restart

2. Hover over this link: http://imgur.com/79jXVgh .  Notice that TZP shows a pop-up of the image.

3. Install and enable https-everywhere 5.0.2 and restart.

4. Hover that same link; this time you just see the "!" error indicator pop-up.

5. Install and enable https-everywhere 4.0.3, restart, and test again.  This time it works.

I see these messages in the console:
```
11:42:50 PM.255: ThumbnailZoomPlus: <<< SEEKING image for name="a" class="" url=
http://imgur.com/79jXVgh pageUrl=#207 (comment)
23:42:50.256 11:42:50 PM.256: ThumbnailZoomPlus: !!! PAGE 'others' (27) matches imageSource
http://imgur.com/79jXVgh
23:42:50.257 11:42:50 PM.257: _getZoomImageCompletionImmediate: getZoomImageResult=http://imgur.com/79jXVgh.jpg; type=string
23:42:50.257 11:42:50 PM.257: ThumbnailZoomPlus: >>>------ page others LAUNCHING
http://imgur.com/79jXVgh.jpg
23:42:50.258 TypeError: value is not a non-null object tabbrowser.xml:430:17
23:42:50.334 TypeError: value is not a non-null object tabbrowser.xml:430:17
23:42:50.337 11:42:50 PM.337: ThumbnailZoomPlus: >>> error loading
http://imgur.com/79jXVgh.jpg
```

The tabbrowser.xml line is the return statement in:

```
     <method name="getTabForBrowser">
        <parameter name="aBrowser"/>
        <body>
        <![CDATA[
          return this._tabForBrowser.get(aBrowser);
        ]]>
        </body>
      </method>
```

I don't find any calls to getTabForBrowser in the source of Thumbnail Zoom Plus nor https-everywhere.

I was hoping to bisect https-everywhere to find the commit which introduced the problem, but I was unable to get Firefox to run it properly from a local git clone.

Help from the https-everywhere would be appreciated.  Several TZP users have complained about the problem.  Thank you.

**Comment by dadler** [comment]
It works in Firefox beta 38.0.

**Comment by jsha** [comment]
Thanks for the report, @dadler. Given that it works in 38.0 my inclination is to just wait for 38.0 to become the mainstream release. Good by you?

**Comment by dadler** [comment]
yes, we could just wait for it to fix itself.

The risk is that some TZP users may abandon the add-on in frustration or leave bad reviews, not realizing the problem is a conflicting add-on.

Or TZP users may disable or uninstall https-everywhere since I announced the incompatibility, so you may lose some users, and users may browse less securely in the near term.

But if you don't have an easy fix, waiting may be the most expedient fix.

**Comment by SnowGabe** [comment]
Can I upgrade to Firefox 38 beta without losing all my configurations?

**Comment by jsha** [comment]
Yep.

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
