### ISSUE TITLE
Custom rules show up as stable rules in the extension popup

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#14962]
Type: feature request

Domain: https://www.example.com

Operating system: Windows 7 Home Premium Service Pack 1
Browser and version: Chrome 67.0.3377.0 canary

Steps to reproduce:

1. With HTTPS Everywhere enabled, open https://www.example.com.
2. Click on the HTTPS Everywhere icon in the Chrome toolbar.
3. Click "Add a rule for this site".
4. Click the "Add a new rule for this site" button.
5. Reload the page.
6. Click on the HTTPS Everywhere icon in the Chrome toolbar.

Expected behavior: The new custom rule shows under "Custom rules".

Actual behavior: The new custom rule shows under "Stable rules".

**Comment by pipboy96** [comment]
This should be handled as a part of upcoming UI rewrite. Closing for now.
