### ISSUE TITLE
Unable to login to https://ibanking.stgeorge.com.au

### ISSUE THREAD

**Issue by dch53** [EFForg/https-everywhere#14964]
I have had https everywhere installed in Waterfox for some time without a problem. However, 2 weeks ago I was no longer able to log into my bank at https://ibanking.stgeorge.com.au/ibank/loginPage.action.

I've found that if I disable https everywhere and then login or attempt to login and then disable https everywhere the logon proceeds OK.

I've tried disabling all rules associated with this URL to no avail.

Thanks and regards, David Hanslip.

**Comment by Bisaloo** [comment]
Hi, thank you for your report!

It's terribly difficult for us to fix issues that require a login to reproduce. Can you provide more information?

- [ ] Can you reproduce on a fresh *Firefox* profile (Waterfox is not officially supported)
- [ ] Did you try disabling  `StGeorge.com.au (partial)`?
- [ ] Did you try disabling `2o7.net`?
- [ ] Can you list all the rules listed once you managed to login?
- [ ] Can you list all domains listed in the dev console during the login process?

And anything else you can think of.

**Comment by pipboy96** [comment]
The page doesn't make any unencrypted requests, so HTTPS Everywhere doesn't touch any request. Also indeed, Waterfox is not supported.
