### ISSUE TITLE
Add New Rule buttons could be better aligned

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#14963]
Type: code issue

Operating system: Windows 7 Home Premium Service Pack 1
Browser and version: Chrome 67.0.3377.0 canary

Steps to reproduce:

1. Click on the HTTPS Everywhere icon in the toolbar.
2. Click "Add a rule for this site".
3. Look at the buttons.

Expected behavior: Buttons are horizontally aligned and spaced reasonably apart.

Actual behavior: Buttons are smashed together, as well as to the "Show advanced" link.

**Comment by pipboy96** [comment]
We're going to rewrite the UI completely.
