### ISSUE TITLE
add owl.phy.quennsu.ca (+general question)

### ISSUE THREAD

**Issue by gbnrileuhg1** [EFForg/https-everywhere#14974]
Type: new ruleset

Domain: owl.phy.quennsu.ca

Possibly other subdomains work as well, haven't tested.

Additionally, I've got a longer list of domains I've encountered in the past where HTTPS works. Several of them don't have a HE rule yet. Should I actually add a new issue for each of them (propably ~50), or may I create one issue with a list of those domains?

**Comment by Bisaloo** [comment]
Hi @gbnrileuhg1, would you be interested in adding coverage for these hosts yourself? 

Our [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md) is quite thorough and should give you everything you need to get started. We can also help you if you have specific questions with one of your pull requests.

**Comment by gbnrileuhg1** [comment]
Not really, as I'm in favor of more generous coverage of forced HTTPS (I've heard wildcard for all subdomains and exceptions are considered not optimal here), and that would mean having to test the rules (I'm running more than unfortunatly typical security tools that might affect such tests). I sorted them out and counted them in the meantime and it's about 76+29 second-level domains that are not in the HE atlas yet.

**Comment by Bisaloo** [comment]
As you wish, but to be honest, it is not very likely that a contributor will pick up the domains you want coverage for. There is way more work than contributors and volunteer contributors very often have their own priorities.

You can always add requests in #3069 though.

On a related note, from what I understand in your last comment, you may be interested in using the `Block all unencrypted requests` on a daily basis. It works pretty well with most sites now.
