### ISSUE TITLE
eur-lex.europa.eu now working over HTTPS

### ISSUE THREAD

**Issue by bl8** [EFForg/https-everywhere#14989]
Type: ruleset issue

Domain: eur-lex.europa.eu

The site at eur-lex.europa.eu is now available over HTTPS with a working configuration:
https://eur-lex.europa.eu

So I think it could be added to the list of targets in https-everywhere/src/chrome/content/rules/Europa.eu.xml

**Comment by numismatika** [comment]
We have 1846+ subdomains on europa.eu , doesn't that justify a wildcard rule?

**Comment by Cathbhadh** [comment]
@numismatika From 2877 subdomains found by Sublist3r 595 return `Timeout`, 725 `Name Not Resolved`, 414 `200 OK`, 134 `Unable to connect`, 258 `Invalid certificate`, 488 `3xx` (with valid certs), 263 other.
(See https://pastebin.com/raw/v7UxGb7v )
Some domains have working certs, but are serving some pages differently over HTTPS (e.g. ec.europa.eu) 
http://ec.europa.eu/eurostat/cache/infographs/energy-2016/wide-menu.html
https://ec.europa.eu/eurostat/cache/infographs/energy-2016/wide-menu.html

**Comment by jeremyn** [comment]
@Cathbhadh Thank you for that extra information! If you wrote the program to do that yourself, we might want to include it as a utility, or link to it from our documentation. Please feel free to open an issue or PR to discuss that if you want.

@numismatika As @Cathbhadh 's comment suggests, whether a wildcard rule is or isn't a good idea isn't based on the number of subdomains but whether we can be sure that all subdomains that exist now or might exist in the future support HTTPS. However in practice a site that is ready to make that commitment should instead use [HSTS preloading](https://hstspreload.org/).

Wildcards are best used along with restrictive `rule`s. An example would be if you want to rewrite `img1.example.com`, `img2.example.com`, ..., `img1000.example.com`. You might have a `target` for `*.example.com` and a `rule` for `img\d+\.example\.com`. In that case more typical subdomains like `www` should be listed specifically in a `rule` as well.
