### ISSUE TITLE
Url inaccessible in FF 52.5 i686

### ISSUE THREAD

**Issue by ballsystemlord** [EFForg/https-everywhere#14992]
Type: code issue

URL: https://linuxgizmos.com/raspberry-pi-cm3-carrier-has-an-artik-mcu-for-offline-bluetooth/
Domain: linuxgizmos.com

To reproduce:
1. Enter the link.
2. Firefox reports the site is inaccessible.
3. Deactivate https-everywhere.
4. Reload the page using http.
5. Reactivate https-everywhere.
6. Now the website loads.

I have done this for 2 days so the issue is persistent.
I do not have the rule set for that domain activated.
I live in the US and this problem does not occur for any other site.

Thanks!

**Comment by christianheinrichs** [comment]
Thanks for your report.

It seems that HTTPS support for `linuxgizmos.com` has been dropped (or maybe there is some kind of SSL reconfiguration going on ATM).

All the subdomains listed in the [linuxgizmos.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/linuxgizmos.com.xml) rules are currently inaccessible via HTTPS.

PR #15003 should fix the issue.
