### ISSUE TITLE
HTTPSE 2018.2.26 on chrome web store

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#14993]
Type: other

Domain: chrome.google.com

Observation: eff.org/https-everywhere, "Install in Chrome" points to chrome web store which is serving the outdated HTTPSE version 2018.2.26. https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp

Expected: HTTPSE version 2018.3.13

/cc @Hainish

**Comment by cschanaj** [comment]
... and seemingly installation from eff.org (either downloading/ clicking https://www.eff.org/files/https-everywhere-chrome-2018.3.13.crx) does not works

**Comment by Hainish** [comment]
This is strange.  Apparently the newest extension update was never reviewed by the Chrome Web Store, and rolled back to the previous version.  I'm uploading again.

**Comment by cschanaj** [comment]
@Hainish I see `2018.3.13` on chrome web store now. Feel free to close this once you can confirm. Thanks!!

**Comment by Hainish** [comment]
Seeing it now too.  Thanks for the alert!
