### ISSUE TITLE
https://pl.msi.com/ on HTTP[S]

### ISSUE THREAD

**Issue by fxjerzy** [EFForg/https-everywhere#1503]
https://pl.msi.com/product/mb/H97MG43.html

I can't excluded this website from HTTPS  :-/

**Comment by reedy** [comment]
Is it just the pl subdomain that doesn't work?

```
chronos@localhost / $ curl -I https://pl.msi.com/
curl: (7) Failed to connect to pl.msi.com port 443: Connection refused
chronos@localhost / $ curl -I http://pl.msi.com/
HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Fri, 17 Apr 2015 13:34:29 GMT
Content-Type: text/html
Connection: keep-alive
X-Powered-By: PHP/5.4.36
Set-Cookie: ci_session=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%228dd6aca7889eea8530c80bb8cfd5308e%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A12%3A%2250.30.61.212%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A11%3A%22curl%2F7.40.0%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1429277669%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3B%7D16095a05b36f163ec0b8ad720ff16eba; expires=Fri, 17-Apr-2015 15:34:29 GMT; path=/

chronos@localhost / 
```

**Comment by jsha** [comment]
It looks like the MSI rule is broken, so we should disable or fix it.

@fxjerzy, are you having trouble disabling the ruleset? Which version of HTTPS Everywhere and which browser are you using?

**Comment by fxjerzy** [comment]
HTTPS Everywhere 2015.4.7

I think only PL subdomain.
I don't have any options in this software or maybe those options are not for all global websites only for this one i'm actually on?

**Comment by jsha** [comment]
@fxjerzy: Hvae you tried clicking the HTTPS Everywhere icon in the toolbar? A blue circle with a lock and arrows pointing out of it? It possible that it might not show up in your browser; We've gotten some reports that it disappears at high DPI.

**Comment by fxjerzy** [comment]
HTTP Everywhere "for www.******.com" - its missing in title, i thought it was a global settings

Rule name
Manual rule for www.pl.msi.com
Matching regex 
^http://www\.pl\.msi\.com/
Redirect to 
https://www.pl.msi.com/

**Comment by jsha** [comment]
@fxjerzy: Are you able to disable the manual rule?

**Comment by fxjerzy** [comment]
Tried all settings, after disabling this plugin site works fine (when https is not in url) and works in other browsers too

**Comment by jsha** [comment]
@fxjerzy: Could you post a screenshot of the HTTPS Everywhere menu? There should be a checkbox next to the manual rule that you can uncheck.

**Comment by fxjerzy** [comment]
https://drive.google.com/file/d/0B6pcCFAGHHOtS2ZoLXV1azZ3Wlk/view?usp=sharing

**Comment by fxjerzy** [comment]
Now it redirects from google to http (non S)

**Comment by jsha** [comment]
@fxjerzy: I don't fully understand your last comment. You mean when you visit pl.msi.com, you get the HTTP version? Is everything working fine now?

**Comment by fxjerzy** [comment]
Maybe its a MSI server issue ?

**Comment by jsha** [comment]
Yep, the pl.msi.com server doesn't support HTTPS.
