### ISSUE TITLE
Incompatibility with First Party Isolation

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#15045]
Type: code issue

Found on [reddit](https://www.reddit.com/r/firefox/comments/875j1n/https_everywhere_with_firstparty_isolation_error/). I'm reporting myself because OP has not done it yet and they might have forgotten about it.

> Unchecked lastError value: Error: First-Party Isolation is enabled, but the required 'firstPartyDomain' attribute was not set. background.js:481

[Link to L481 of `background.js`](https://github.com/EFForg/https-everywhere/blob/master/chromium/background-scripts/background.js#L481)

I could not reproduce myself but I'm still reporting because after reading the MDN documentation, it does look like we are not handling FPI as we should:

> The cookies.get(), cookies.getAll(), cookies.set() and cookies.remove() APIs all accept a firstPartyDomain option. When first-party isolation is on, you must provide this option or the API calls will fail.

Source: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies

@Hainish

**Comment by cschanaj** [comment]
>  it does look like we are not handling FPI as we should:

I agree, but neither do I be able to reproduce this, on Firefox 59.0 on Debian 9 platform

**Comment by cschanaj** [comment]
#15048 _should_ works, but I can't reproduce this issue on my machine so I cannot confirm it.
