### ISSUE TITLE
Senate.gov subdomains wonky

### ISSUE THREAD

**Issue by thisisparker** [EFForg/https-everywhere#1505]
Similar to the effect reported in #805, at least some Senate subdomains are exhibiting weird behavior with HTTPS Everywhere on. https://www.baldwin.senate.gov/ gives a "Forbidden" error. Others, such as http://www.wyden.senate.gov/, have a redirect loop.

**Comment by jsha** [comment]
The latest release (5.0.2) should have this rule disabled by default. It's possible you've manually disabled and then re-enabled it in the past, in which case you should manually disable it.

**Comment by thisisparker** [comment]
@jsha whoops, sorry! I don't remember manually disabling and re-enabling it, but that must have happened. Thanks for catching it.
