### ISSUE TITLE
Rule for www.aidecoder.com

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#15051]
Type: new ruleset
Domain: www.aidecoder.com

**Comment by BK1233** [comment]
It doesn't work over HTTPS.

**Comment by KOLANICH** [comment]
I'm not surprised - it's a different part of [free-ocr.com](15050) #15050

**Comment by Bisaloo** [comment]
This site is not completely functional over HTTPS. Closing.
