### ISSUE TITLE
https-rulesets.org  uses a broken dmarc record

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#15060]
Type: other
The website to update rulesets from has a broken dmarc record.

According to the FeistyDuck test:

> 
> Invalid external destination
> This policy uses an external report destination that is not authorized because the permission record doesn't exist. Please refer to RFC 7489, Section 7.1, for instructions how to correct this problem.
> 
> Expected permission record location: https-rulesets.org._report._dmarc.eff.org
> External destination: mailto:dmarc_rua@eff.org

**Comment by pipboy96** [comment]
DMARC record is only used for email, which obviously does not apply to https-rulesets.org.
