### ISSUE TITLE
Unexpected mixed content on wiki.apache.org

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#15074]
2018.4.3
Chromium 65 on Linux

Type: ruleset issue
Domain: apache.org

Visit https://wiki.apache.org/spamassassin/
`Mixed Content: The page at 'https://wiki.apache.org/spamassassin/' was loaded over HTTPS, but requested an insecure image 'http://spamassassin.apache.org/images/arrowlogo.png'. This content should also be served over HTTPS.`

Looking at https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Apache.xml, both `wiki.apache.org` and `spamassassin.apache.org` are listed as fully covered domains, so I would expect all content to be served over HTTPS.

Thanks,

**Comment by wesinator** [comment]
I see, thanks.

Has this been reported to Chrome as a bug ?

**Comment by Bisaloo** [comment]
We are tracking this for various browsers in https://github.com/EFForg/https-everywhere/issues/793
