### ISSUE TITLE
www.https-rulesets.org uses broken link to "homepage"

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#15076]
Type: code issue

Domain: www.https-rulesets.org

@Hainish On https://www.https-rulesets.org/, the hyperlink of "homepage" is pointed to https://www.eff.org/https-everwhere instead of https://www.eff.org/https-everywhere, resulting a 404 page (missing char `y`).

**Comment by Hainish** [comment]
Thans!
Thanks!

**Comment by Hainish** [comment]
Fixed, should clear the cache in a moment.
