### ISSUE TITLE
Deployed release and AMO package conflict

### ISSUE THREAD

**Issue by salientfoo** [EFForg/https-everywhere#15083]
Type: code issue

Ties to #13018 #2588

When deploying this extension, it naturally makes sense to utilize the signed release hosted at eff.org rather than pulling the xpi from AMO, however with this extension, the signed release hosted at eff.org has a different id than the AMO release.

If firefox identifies that a user has an AMO installation of a deployed app, it will override the deployed version and permit usual AMO updates, allowing  a user to remain up to date even if deployed software updates lag.  With https-everywhere, given the deployed id differs from the AMO id, both will run with different configurations and are virtually indistinguishable to a user.

To reproduce:
1. Create a new firefox profile and install https-everywhere from AMO
1. Close firefox
1. Deploy https-everywhere-eff xpi to firefox installation path, browser/extensions.
1. Load firefox and observe both https-everywhere and https-everywhere-eff are running.

Suggested recourse would be to utilize the same id for both AMO and EFF.org releases. Given changes to AMO over the last years, the workaround per issue #2588 should no longer be required, as other extension developers are releasing the same package id through AMO and self-hosting.

**Comment by Hainish** [comment]
This would require migrating all our self-hosted users to install a new self-hosted extension with the matching ID, which unfortunately would be a huge amount of work.  It would have been desirable to do this from the outset, but we're stuck with the current situation.

**Comment by Hainish** [comment]
Thanks for pointing this out though, @salientfoo.  I wish we could do more here.
