### ISSUE TITLE
Standalone subscribtion manager

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#15082]
Type: feature request
Type: other

There are lots of addons requiring subscribtions: μMatrix, μBlock, GreasyMonkey, and now HTTPSEverywhere.

WebExtension API allows the extensions to send messages to each other. I guess there should be a standalone subscribtion manager extension, and all the other extensions should use it for their subscribtions. See https://github.com/open-source-ideas/open-source-ideas/issues/60 .

**Comment by Hainish** [comment]
@KOLANICH an interesting idea, though I don't think it belongs in this tracker.  Thanks for raising https://github.com/open-source-ideas/open-source-ideas/issues/60 to our attention.
