### ISSUE TITLE
htttps everywhere breaks video.pbs.org

### ISSUE THREAD

**Issue by fredex1** [EFForg/https-everywhere#1508]
I can browse to any video but when I attempt to play it, I get a black screen with a white text message saying "error loading skin, file not found."

disabling https everywhere and restarting firefox, allows the videos to play.

I don't see any rules for pbs.org, if I did I'd try disabling it/them.

**Comment by reedy** [comment]
This site doesn't seem to work...

```
chronos@localhost / $ ping pbs.org
PING pbs.org (23.21.237.247) 56(84) bytes of data.
^C
--- pbs.org ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

chronos@localhost / $ ping videos.pbs.org
ping: unknown host videos.pbs.org
chronos@localhost / $
```

http://www.downforeveryoneorjustme.com/videos.pbs.org concurs...

**Comment by fredex1** [comment]
Reedy: thanks for the heads-up. I meant to type "video.pbs.org", not videos...

here's an example: 

http://video.pbs.org/video/2365432635/

go to that URL with HTTPS everywhere enabled (in firefox, I don't know about other browsers) and it fails as described above (see attached screenshot). then go disable the add-on, restart firefox, and it plays just fine.

Fred

![screenshot-video hagia sophia istanbul s ancient mystery watch nova online pbs video - mozilla firefox](https://cloud.githubusercontent.com/assets/12013064/7220456/8a034106-e695-11e4-9a81-21a723c46981.png)

**Comment by reedy** [comment]
Thanks for providing an example URL. I get "We're sorry, but this video is not available in your region due to right restrictions." currently in Canada

But if the site is broken with the ruleset enabled, the ruleset should either be fixed, or disabled by default until it is fixed. So reopening it for this reason

**Comment by fredex1** [comment]
reedy, I hadn't thought of region issues, so you may have to dig around to find one that it lets you play in your region. But once you find one, I predict it will fail with https everywhere enabled. Well, at least for me, of all the ones I've tried, none of them work, all exhibiting the error message shown above, when it is enabled.

I didn't see any rules that looked as if they would cover this site (but I can't claim any competence at all regarding how that all works.)

**Comment by reedy** [comment]
I'm back in the USA as of about 24 hours from now, so might have a bit more luck then

**Comment by jsha** [comment]
I was able to play http://video.pbs.org/video/2365432635/ in Chrome on Linux, but not on Firefox 37.0.1, regardless of whether HTTPS Everywhere was installed (I tried a completely clean new profile).

**Comment by MDawg957** [comment]
I can confirm this is still an issue with Firefox 38.0/HTTPSE 5.0.4 on Windows using the same example link.

I was able to get it to properly work by disabling the Cloudfront rule.

**Comment by fredex1** [comment]
MDawg957: thanks for that info. I didn't know how to figure out which rule might be causing it, since I didn't see anything for PBS. That workaround works for me, as well. Linux (Centos-6) with Firefox-38.

**Comment by semenko** [comment]
PBS has overhauled their player [and dropped the video.pbs.org domain], and things seem more broken:

http://www.pbs.org/video/2187882295/
