### ISSUE TITLE
Document https-rulesets.org API

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#15109]
The new functionality on `https-rulesets.org` should be documented, that downstream projects can use it.

Type: other

**Comment by Hainish** [comment]
The URL schema may change based on the resolution of https://github.com/EFForg/https-everywhere/issues/15096, so I'm reluctant to move on this until we standardize a schema for incremental rulesets.

**Comment by Hainish** [comment]
done in https://github.com/EFForg/https-everywhere/pull/16446#pullrequestreview-151576407
