### ISSUE TITLE
Pinterest site and extension problems

### ISSUE THREAD

**Issue by daisyswain** [EFForg/https-everywhere#15118]
Type: I've been having problems accessing the Pinterest site and using the Pinterest chrome extension, I just googled the problem and seen that your extension has caused similar problems (https://productforums.google.com/forum/#!topic/chrome/gf9-NjZxGjk) - is it still an issue? It's super annoying.

Domain: pinterest.com.au

**Comment by injust** [comment]
Not likely, I believe that the rulesets covering Pinterest were removed due to HSTS preloading.

**Comment by pipboy96** [comment]
We no longer have any rules covering any Pinterest domains.
