### ISSUE TITLE
Add relaxng whitelist

### ISSUE THREAD

**Issue by epicminecrafting** [EFForg/https-everywhere#15148]
Type: feature request

See #15113 for a use case.

**Comment by cschanaj** [comment]
As the `relaxng` test is a part of the `rule-test`, it would be more desirable to have `relaxng` using the same whitelist instead of addIng new entries. This will avoid a huge diff as well.

cc @Hainish, @Bisaloo, @Yegorlevlev

**Comment by Hainish** [comment]
@epicminecrafting, @cschanaj: Do you envision adding an extra column to [`ruleset-whitelist.csv`](https://github.com/efforg/https-everywhere/blob/master/utils/ruleset-whitelist.csv), or simply using the `auto-pass coverage test` column?

**Comment by YegorIevlev** [comment]
@Hainish #15113 uses `auto-pass coverage test` column, so my PR also uses it.

**Comment by Hainish** [comment]
@YegorIevlev I see that, that's fine.  But I think this warrants discussion.

**Comment by YegorIevlev** [comment]
@Hainish I don't weigh in either way.
