### ISSUE TITLE
California Department of Tax and Fee Administration (CDTFA) site has HTTPS support

### ISSUE THREAD

**Issue by galenide** [EFForg/https-everywhere#15144]
Type: new ruleset

In case anyone is interested in creating a ruleset, the Web site for the California Department of Tax and Fee Administration (CDTFA) has a number of domains that appear to support HTTPS. (I have not tested every page under each of the listed domains.)

Domain: cdtfa.ca.gov
Domain: www.cdtfa.ca.gov
Domain: gis.cdtfa.ca.gov
Domain: services.cdtfa.ca.gov

It appears that cookies are set for the services.cdtfa.ca.gov domain; it would likely be useful to ensure that such cookies are secured.

For the gis.cdtfa.ca.gov domain, the only URL that I am aware of is https://gis.cdtfa.ca.gov/public/maps/taxrates/.

**Comment by pipboy96** [comment]
@galenide Thanks! Closed by #19312.
