### ISSUE TITLE
HTTPS hardening on https-rulesets.org

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#15151]
Type: other

- [ ] ~~Use Certificate Transparency~~ (done since 2018-03-21) and enforce it through `Expect-CT: enforce` header (currently not implemented by https-rulesets.org).
- [ ] Use HPKP to pin to at least two CAs (Chromium is currently in process of deprecating HPKP but Firefox has not announced any intention to deprecate it).
- [ ] Use DNSSEC and DANE (there are browser extensions that allow to validate DANE records).
- [x] Use a CAA record to disallow any CAs except the one currently used and at least one backup from issuing certificates for `https-rulesets.org`. (probably should be highest priority for now)

See also https://securityheaders.io/?q=https%3A%2F%2Fwww.https-rulesets.org%2F&followRedirects=on.

**Comment by injust** [comment]
I do question the value of an EV certificate, but that's just my two cents.

**Comment by pipboy96** [comment]
https-rulesets.org.	7200	IN	CAA	0 iodef "mailto:caa@eff.org"
    https-rulesets.org.	7200	IN	CAA	0 issuewild "ssl.com"
    https-rulesets.org.	7200	IN	CAA	0 issue "ssl.com"
    https-rulesets.org.	7200	IN	CAA	0 issue "letsencrypt.org"

**Comment by pipboy96** [comment]
Closing to open updated issue.
