### ISSUE TITLE
https://www.imdb.com/ works !

### ISSUE THREAD

**Issue by Pv8Nay3Bx7** [EFForg/https-everywhere#15152]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: www.imdb.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

imdb.com redirects to www.imdb.com
https://gitweb.torproject.org/https-everywhere.git/tree/src/chrome/content/rules/IMDB.xml

**Comment by Bisaloo** [comment]
Are you using the latest HTTPS Everywhere version? 

This has been fixed in https://github.com/EFForg/https-everywhere/pull/14760.

**Comment by GUiHKX** [comment]
I'm using version 2018.4.11 and it's not redirecting to the https site as well

**Comment by Bisaloo** [comment]
What happens if you visit http://freerangekitten.com/. Are you redirected to HTTPS?

**Comment by GUiHKX** [comment]
Yup

![image](https://user-images.githubusercontent.com/626206/38771012-d40c31be-3ff1-11e8-8b68-7bf763af101c.png)

**Comment by GUiHKX** [comment]
Hmm... I just tried again with imdb, but now it works. Don't know why tbh.

**Comment by Bisaloo** [comment]
@GUiHKX, maybe https://github.com/EFForg/https-everywhere/issues/13535? It does seem to happen sometimes around the time when HTTPS Everywhere is updated.

Closing this issue as the specific request (securing `imdb.com`) has already been addressed.
