### ISSUE TITLE
Livefyre comments widget on engadet.com doesn't load/appear

### ISSUE THREAD

**Issue by naobug** [EFForg/https-everywhere#1519]
The comments section on engadget.com doesn't appear.
I use Firefox stable on Windows 7.

I can disable the rule "Livefyre (partial)" and the comments widget appears.

I believe it has to do with the following:
in the rule there is d584h2bjreb1u.cloudfront.net .
But analyzing with noscript, there is another domain that is loaded on engadget, which is 
https://d8rk54i4mohrb.cloudfront.net.
Maybe this domain has to be added to the rule?

**Rule active, no comments widget**
![livefyre partial rule active no comments box](https://cloud.githubusercontent.com/assets/12033198/7237013/d0252f9c-e798-11e4-8713-55a1092a85a5.jpg)

**Rule inactive, comments widget appears**
![livefyre partial rule inactive comments appear](https://cloud.githubusercontent.com/assets/12033198/7237014/d0593242-e798-11e4-94f2-59080105a43b.jpg)

**Comment by reedy** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Livefyre.xml#L44-L45 would look like it's trying to catch the livefyre stuff

On Chrome it seems the comment sections appear, but all seemingly all posts have 0?

**Comment by naobug** [comment]
Now I installed httpseverywhere on chrome too. And it behaves the same as on Firefox. It doesn't show the comments widget from livefyre as long as the rule "livefyre (partial)" is active.

**Comment by reedy** [comment]
Thanks for the screenshots

**Comment by bardiharborow** [comment]
@gloomy-ghost this has been resolved.

**Comment by gloomy-ghost** [comment]
I can confirm that the livefyre ruleset is no longer active on engadet.com, and the comment section loads successfully.
