### ISSUE TITLE
Add polisen.se

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1520]
Cookies on https://polisen.se/ are sent over http and therefore the site would need a ruleset.

**Comment by reedy** [comment]
I'm not going to comment on every issue like this, but if you're going to have a lot of requests to add sites to HTTPSE, you might want to consider learning to write the rules yourself. The work is generally done by volunteers, so unless the target site is a very big/important site, the chances of random(); volunteer actually writing the ruleset is reduced.

**Comment by cypherpunk** [comment]
Ok, I might give that a try when I have extra time on my hands. Do you have a guide for writing rulesets somewhere?

**Comment by cypherpunk** [comment]
Can I use HTTPS Finder(https://code.google.com/p/https-finder/) to create the rulesets or should I do it in some other way?

**Comment by KommX** [comment]
You can use the script make-trivial-rule which is in src/chrome/content/rules/
