### ISSUE TITLE
Alexa labeller bot crashed

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#15213]
Type: other

It looks like the labeller bot is offline. It's been a couple of weeks now. @Hainish could you try to reboot it?

**Comment by Bisaloo** [comment]
@Hainish, this is really helpful to prioritize reviews. Did you get the chance to look at it?

**Comment by Hainish** [comment]
It looks like there were a few large rulesets that the labeller bot was attempting to parse and check against the Alexa list.  These rulesets caused the script to increase CPU load to a critical state, resulting in the process being killed.  After closing these large rulesets and re-running the script, it appears to be behaving normally.
