### ISSUE TITLE
[Zeit.de.xml] ruleset update

### ISSUE THREAD

**Issue by nmxcgeo** [EFForg/https-everywhere#15235]
Type: ruleset issue

Domain: zeit.de

The German newspaper zeit.de now redirects to their https version by default. This affects at least the TLD as well as www.zeit.de. Other Subdomains' statuses might also have changed since last edit of the ruleset as they wrote in an e-mail they would be going https-only.

Greetings Nmxosm

**Comment by J0WI** [comment]
closed by #15330
