### ISSUE TITLE
arewewebextensionsyet.com

### ISSUE THREAD

**Issue by theel0ja** [EFForg/https-everywhere#15241]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: arewewebextensionsyet.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/arewewebextensionsyet.com.xml

![image](https://user-images.githubusercontent.com/5832930/39146248-ebd9c0c8-473e-11e8-9dbd-5eb9e7e0b205.png)

**Comment by Giltyhub** [comment]
I think opening a bug in Mozilla's bugtracker would be better than disabling the ruleset since they can fix the cert issue directly.

**Comment by ExE-Boss** [comment]
Bypassing the above error returns a [502 Bad Gateway](https://developer.mozilla.org/docs/Web/HTTP/Status/502) response.

**Comment by injust** [comment]
The HTTP version of the site returns a `503`, so it's more broken than just the SSL configuration.

**Comment by ExE-Boss** [comment]
I think Mozilla has shut down this service and https://arewee10syet.com at this point, given that on the official list of [Areweyet](https://wiki.mozilla.org/Areweyet) pages, it’s listed under [the dead pages](https://wiki.mozilla.org/Areweyet#Are_we_dead_yet.3F).

**Comment by pipboy96** [comment]
@ExE-Boss Currently this link points to a copycat website with VPN ad. Also yeah both are dead.
