### ISSUE TITLE
Local rules additions do not get applied in browser testing

### ISSUE THREAD

**Issue by scop** [EFForg/https-everywhere#15280]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

I'm trying to test some local rules additions in Firefox and Chromium on Ubuntu 17.10. `test/firefox.sh --justrun` and `test/chromium.sh --justrun` both succeed and launch the browser, and the messages on console indicate that my rules do get included and they end up in rules/default.rulesets and at least in the Firefox temporary profile dir, but they do not get applied. https'ing doesn't happen, and the "Stable rules" listing doesn't list my rulesets.

The rulesets are so simple that I find it hard to believe their content would be the problem. Any advice how to debug this or get it to work? I've run install-dev-dependencies.sh and created the rulesets with make-trivial-rule. test/manual.sh works for all my added rulesets.

**Comment by jeremyn** [comment]
The recommended way to test new rulesets in the browser is to use the "hidden" debugging tool as described in [`docs/en_US/rulesets.md#testing`](https://github.com/EFForg/https-everywhere/blob/28087477257523c65d14bd5b4e1e79ad84056c08/docs/en_US/rulesets.md#testing]).

You could also put your rulesets in the [`src/chrome/content/rules/`](https://github.com/EFForg/https-everywhere/tree/master/src/chrome/content/rules) directory and then rebuild the extension with `bash make.sh`, and then install and test the rebuilt extension in a browser that allows unsigned extensions like Firefox Developer Edition.

I'm not sure about `test/firefox.sh --justrun` / `test/chromium.sh --justrun` but before someone digs into those, it might be helpful to know what you get if you try the above two approaches.

**Comment by pipboy96** [comment]
The messages are most likely from pre-WebExtensions era where extensions had full access to user profile. Otherwise, see @jeremyn's response.
