### ISSUE TITLE
Portforward.com ruleset is wrong

### ISSUE THREAD

**Issue by scubanarc** [EFForg/https-everywhere#15291]
Type: ruleset issue
Domain: portforward.com

This rule is wrong:

from="^http://(?:www\.)?portforward\.com/build/"
to="https://secure.portforward.com/build/"/>

It incorrectly redirects site resources to come from a different server. It should not mention the "secure" server. The rule should be:

from="^http://(?:www\.)?portforward\.com/build/"
to="https://portforward.com/build/"/>

**Comment by pipboy96** [comment]
Closed by #18626.
