### ISSUE TITLE
Thunderbird 52 doesn’t support WebExtensions or Embedded WebExtensions

### ISSUE THREAD

**Issue by ExE-Boss** [EFForg/https-everywhere#15313]
Type: other
-----------

Versions 2017.8.19 and newer are incompatible with Thunderbird, despite the [AMO listings saying otherwise](https://addons.mozilla.org/en-GB/firefox/addon/https-everywhere/versions/2017.8.19), which causes Thunderbird to try to install it during automatic update, but after updating it, it fails to load it due to [bug 1418914](https://bugzil.la/1418914).

<img alt="HTTPS Everywhere – issue #15313" src="https://user-images.githubusercontent.com/3889017/40149288-279aa0dc-5973-11e8-837c-24833ee9b588.png" align="top"/>

**Comment by J0WI** [comment]
Thunderbird is not an officially supported platform and it's also not shown in Thunderbird. Are there any uses cases for HTTPS Everywhere in mail clients?
See [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1396172) for WebExtensions support in Thunderbird.

**Comment by gopherit** [comment]
I haven't had this issue in Thunderbird 60.0 beta 6.  HTTPS Everywhere updates just fine.

J0WI said:
>Are there any uses cases for HTTPS Everywhere in mail clients?

I use it to ensure any applicable HTTP requests in HTML messages are appropriately upgraded to HTTPS.  I haven't verified if the extension does this, since the icon isn't visible.  I suppose I could view debug logs or do a packet capture.

**Comment by ExE-Boss** [comment]
@Hainish Well, the cause of this issue can be seen highlighted here:
<img alt="HTTPS Everywhere – issue #15313" src="https://user-images.githubusercontent.com/3889017/40149288-279aa0dc-5973-11e8-837c-24833ee9b588.png" align="top"/>

**Comment by Hainish** [comment]
I've removed Thunderbird from the list of supported clients for all Embedded WebExtensions versions (it already wasn't there for all full WebExtensions versions.)
