### ISSUE TITLE
Add shoppingmalljapan.com

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1538]
Cookies on https://shoppingmalljapan.com/ are sent over http and therefore the site would need a ruleset. However, the site layout looks different and buggier on the https version than the http version of the site.

**Comment by semenko** [comment]
Thanks for the suggestion!

We don't currently have the resources to add rules for small sites when people create Issues. If you would like to see it add HTTPS Everywhere, please submit a pull request with a new ruleset: https://www.eff.org/https-everywhere/rulesets
