### ISSUE TITLE
Easynews rule needs update

### ISSUE THREAD

**Issue by drizzler2** [EFForg/https-everywhere#15436]
Type: ruleset issue

Domain: members.easynews.com

You are forwarding to a deprecated URL. Change this:

rule from="^http://members\.easynews\.com/" to="https://secure.members.easynews.com/"

to this:

rule from="^http://members\.easynews\.com/" to="https://members.easynews.com/"

If you don't remove the "secure." part, then strange things can happen at Easynews since they don't support that URL anymore.

**Comment by J0WI** [comment]
closed by #15437
