### ISSUE TITLE
Add kolektakon.com

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/https-everywhere#1544]
Cookies on https://kolektakon.com/ are sent over http and therefore the site would need a ruleset.
This subdomains isn't covered by the https: http://proxy.kolektakon.com/

**Comment by semenko** [comment]
Thanks for the suggestion!

We don't currently have the resources to add rules for small sites when people create Issues. If you would like to see it add HTTPS Everywhere, please submit a pull request with a new ruleset: https://www.eff.org/https-everywhere/rulesets
