### ISSUE TITLE
New ruleset for slither.io

### ISSUE THREAD

**Issue by anthropomorphic** [EFForg/https-everywhere#15450]
Type: new ruleset

Domain: slither.io

This page won't load until I uncheck "block all unencrypted requests"

**Comment by injust** [comment]
Nothing to be done here, `slither.io` redirects all HTTPS requests to HTTP using JavaScript.

**Comment by anthropomorphic** [comment]
This appears to cause a loop where it just switches back and forth between http and https. How do I fix that without having to turn off HTTPS Everywhere?

**Comment by Bisaloo** [comment]
As @injust, there is nothing we can do on our side. You can always try to reach out to the webmasters of `slither.io` to ask them to support HTTPS. In the meantime, your only solution is indeed to uncheck `block all unencrypted requests` when you visit this website.

Please also note that HTTPS Everywhere remains functional even if `block all unencrypted requests` disabled. In this case, it will rely on a manually curated list of websites that we know support HTTPS.

**Comment by injust** [comment]
@Bisaloo Would a user-defined whitelist for the `block all unencrypted requests` mode be a viable addition?

Seems like it could be useful in cases such as these, where the user is comfortable using the option in the general case, but it causes a few sites to break.

**Comment by Bisaloo** [comment]
@injust, yes, it would be useful. Actually, it's a pretty old feature request: https://github.com/EFForg/https-everywhere/issues/2299
