### ISSUE TITLE
CI tests do not cover all IP addresses

### ISSUE THREAD

**Issue by injust** [EFForg/https-everywhere#15465]
Type: code issue

When running the fetch tests, it may be good to test against all IP addresses to which the domain resolves.
For example: [One fetch test](https://travis-ci.org/EFForg/https-everywhere/jobs/380708709) for `alerts.rogersbank.com` passes, and [another one](https://travis-ci.org/EFForg/https-everywhere/jobs/380714306) fails.

This is due to the fact that the domain resolves to `8.33.184.139` and `38.107.102.2`, with only the former correctly providing the intermediate certificate.

**Comment by pipboy96** [comment]
IP addresses returned by DNS may also depend on your IP and resolver, thus getting "all possible IPs" is unlikely to be possible, but at least checking all `A` and `AAAA` answers may make sense.
