### ISSUE TITLE
How to deal with "missing location header" targets?

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#15473]
Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

See for example: https://github.com/EFForg/https-everywhere/pull/15463

**Comment by injust** [comment]
That's a server misconfiguration.
HTTP 302 is a redirect, but the server doesn't provide a `Location` header indicating the redirect destination.

I guess that the correct action is to add a custom rule matching `^http://cdn\.ravenjs\.com$` and redirect that to `https://cdn.ravenjs.com`

**Comment by Giltyhub** [comment]
thanks @injust i made that change hopefully ci will pass

**Comment by Giltyhub** [comment]
cc @Hainish

**Comment by J0WI** [comment]
I would go for a simple [exclusion](https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/rulesets.md#exclusions).

**Comment by Giltyhub** [comment]
@J0WI we're trying to get the cdn.* target (since it's what's used the most on websites) so i don't see how an exclusion would help

**Comment by J0WI** [comment]
Se the example in https://github.com/EFForg/https-everywhere/pull/15463#issuecomment-394079235. Only one specific path (the root) is excluded, all other paths are still redirected.

**Comment by Giltyhub** [comment]
@J0WI oh sorry misunderstood what you said at first

ok will try hopefully it will work

**Comment by Giltyhub** [comment]
yes it did work @J0WI thanks a ton! https://travis-ci.org/EFForg/https-everywhere/builds/387084694
