### ISSUE TITLE
Auto-create rules based on 301 responses

### ISSUE THREAD

**Issue by dan2468** [EFForg/https-everywhere#15485]
Type: feature request

The extension could have a new option (perhaps under `Advanced Settings`) to allow auto-learning of rules based on `301 Moved Permanently` server replies.

After enabling it, visiting e.g. any page under `http://www.primariatm.ro/` and observing its 301-redirect to the corresponding HTTPS URL should create and enable a user rule for the whole domain.

These auto-rules should be distinguished from the ones entered manually by the user, so that in case of issues they can be deleted or disabled separately.

Additionally, perhaps an extension notification should pop up after several visits, to suggest that this new feature is possible (something like „This site supports secure connections. Do you prefer those by default?”).

**Comment by pipboy96** [comment]
Some websites may do 301 redirects from HTTP to HTTPS and vice versa on the same domain. This would result in a redirect loop. The logic should be more complex than that.
