### ISSUE TITLE
Issues with out-of-band ruleset updates

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#15482]
Type: code issue

Downloaded rulesets is not stored/ applied, despite updated timestamps on chromium browser with HTTPSE `master` (6134b7b46f20eee7b3a4ded4be373b8793b33a5a). `2018.4.11` seemingly unaffected. Possibly related to recent changes/ base64 encoding & decoding 

**Step to reproduce (1)**

1. Remove the embeded rulesets
```
$ make.sh
$ echo '[]' > pkg/crx/rules/default.rulesets
```

2. `Load unpacked extension...` using Chromium browser, open `Inspect views: background page`; 

```
Hey developer! Want to see more verbose logging?
util.js:17 Type this into the console: let util = require('./util'); util.setDefaultLogLevel(util.VERB);
util.js:18 Accepted levels are VERB, DBUG, INFO, NOTE and WARN, default is NOTE
util.js:26 Checking for new rulesets.
util.js:48 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
loadExtensionFile @ util.js:48
util.js:26 EFF (Full): A new ruleset bundle has been released.  Downloading now.
util.js:26 EFF (Full): Downloaded ruleset signature checks out.  Storing rulesets.
_generated_background_page.html:1 Unchecked runtime.lastError while running storage.set: QUOTA_BYTES quota exceeded
    at res (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/store.js:32:37)
    at generic_set_promise (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/store.js:32:10)
    at Object.local_set_promise [as set_promise] (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/store.js:48:10)
    at window.crypto.subtle.verify.then (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/update.js:140:31)
```

3. Visit `www.cnbc.com`, open popup. Expect some active rules, found none 

**Step to reproduce (2)**

4. Repeat step 1-2, add "unlimitedStorage" permission to 'pkg/crx/manifest.json' (require uninstall and re-install)

```
Hey developer! Want to see more verbose logging?
util.js:17 Type this into the console: let util = require('./util'); util.setDefaultLogLevel(util.VERB);
util.js:18 Accepted levels are VERB, DBUG, INFO, NOTE and WARN, default is NOTE
util.js:26 Checking for new rulesets.
util.js:48 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
loadExtensionFile @ util.js:48
util.js:26 EFF (Full): A new ruleset bundle has been released.  Downloading now.
util.js:26 EFF (Full): Downloaded ruleset signature checks out.  Storing rulesets.
util.js:26 EFF (Full): Applying stored rulesets.
_generated_background_page.html:1 Error in response to storage.get: incorrect header check
    at rulesets_promises.push.resolve (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/update.js:161:28)
    at applyStoredRulesets (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/update.js:159:28)
    at RuleSets.loadFromBrowserStorage (chrome-extension://ldkhgkdpiimkokbnliiejpjbdnbpcjip/background-scripts/rules.js:219:11)
```

cc @Hainish @bcyphers

**Comment by Giltyhub** [comment]
@Hainish @cschanaj unfortunately this issue still happens with 2018.6.13, can you re-open this ticket?

**Comment by Hainish** [comment]
@Giltyhub with the extension version 2018.6.13, or just the ruleset version 2018.6.13?

**Comment by Hainish** [comment]
I'm not observing this, can anyone else independently confirm?

**Comment by Giltyhub** [comment]
@Hainish of course i'm talking about the extension version

i'm experiencing it right now with firefox and when it happens the line in the popup with the ruleset version doesn't appear

hopefully @cschanaj may be able to independently confirm

**Comment by Hainish** [comment]
@Giltyhub you're probably using the same Firefox profile for debugging currently as you were when `master` was storing these rules erroneously.  So I'm guessing you have bad data in `chrome.storage.local`, resulting in an error at runtime.  Try the following from the extension debugging console:

```js
chrome.storage.local.remove(['last-checked', 'rulesets-timestamp: EFF (Full)', 'rulesets: EFF (Full)']);
```

Then disable and re-enable the extension.  This should fix things.

**Comment by Giltyhub** [comment]
@Hainish thanks for the suggestion, i'm not using the debugging mode but i'll definitely try out with a new fresh profile later this month
