### ISSUE TITLE
The file at moz-extension://... is not readable.

### ISSUE THREAD

**Issue by jonkolbert** [EFForg/https-everywhere#15590]
![https everywhere](https://user-images.githubusercontent.com/33134141/40851565-08ce089c-6585-11e8-9fc5-4d7655e8e420.png)

Type: code issue

When I click on where the HTTPS Everywhere symbol should be in Firefox, I get this error : 
"The file at moz-extension://8621afa2-0a9c-49c4-9802-b37364982bc7/pages/popup/index.html is not readable."

I've tried removing and re-adding the add-on, to no avail. I am using Firefox 61.0b10 (64-bit).

**Comment by gloomy-ghost** [comment]
I can't reproduce the issue, did you install it from eff.org or addons.mozilla.org? Also what is the version of https everywhere?

**Comment by jonkolbert** [comment]
Re-installed at a later date and it works fine. Closing.
