### ISSUE TITLE
store.steampowered.com search dropdown not functioning

### ISSUE THREAD

**Issue by twistedau** [EFForg/https-everywhere#1560]
When the ruleset "Steam Powered.com (Partial)" is enabled the search box does not automatically populate with matched results.

**Comment by twistedau** [comment]
Steam static.com (Partial) also breaks functionality on the store.steampowered.com site (Add to wishlist, follow, etc). For example: http://store.steampowered.com/app/364360/.

**Comment by reedy** [comment]
Dupe of #1453
