### ISSUE TITLE
Audit at least top-1m mixedcontent rulesets

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#15618]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

can anyone post a list of all at least top-100k mixed content rulesets? From my searches many rulesets that are mixedcontent are no longer the case, i can audit one ruleset per day to activate at least one per day and if others join in the effort i'm sure we can go though all the 1k mixedcontent rulesets. what do you think?

@cschanaj @Bisaloo @injust

**Comment by J0WI** [comment]
See also #529

**Comment by Giltyhub** [comment]
abandoned for the time being due to time restraint

**Comment by pipboy96** [comment]
@Giltyhub Done: #17436
