### ISSUE TITLE
Migrate from GitHub

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#15615]
Type: other
M$ is buying ₲H. I guess, It's time to migrate.

**Comment by Giltyhub** [comment]
it depends on the eff, maybe they can make a self-hosted gitea or gitlab instance and that would be better imo since the eff will have ur privacy in mind

**Comment by rogersachan** [comment]
See https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/

> Most importantly, we recognize the responsibility we take on with this agreement. We are committed to being stewards of the GitHub community, which will retain its developer-first ethos, operate independently and remain an open platform. We will always listen to developer feedback and invest in both fundamentals and new capabilities.

> Once the acquisition closes later this year, GitHub will be led by CEO Nat Friedman, an open source veteran and founder of Xamarin

I don't think there's anything to worry about.

**Comment by sampablokuper** [comment]
@rogersachan [wrote](https://github.com/EFForg/https-everywhere/issues/15615#issuecomment-394402940):
> I don't think there's anything to worry about.

https://en.wikipedia.org/wiki/Embrace_extend_extinguish

**Comment by Giltyhub** [comment]
https://natfriedman.github.io/hello/

**Comment by Giltyhub** [comment]
by the way for those who want the eff to migrate to something else: provide links to migration guides that also include PRs, issues, ... :)

**Comment by Bisaloo** [comment]
The final decision about a migration lies in the EFF's hands but for those who want to delete their github account:

- you can report issues on the [Tor Project issue tracker](https://trac.torproject.org/projects/tor/report/19)
- you can [send rulesets by email](https://lists.eff.org/mailman/listinfo/https-everywhere-rules)

Those two options have been unused lately but it should be possible to revive them.

**Comment by gloomy-ghost** [comment]
Of course GitLab won't dismiss such opportunity, they've gone beyond providing migration guide:
https://about.gitlab.com/2018/06/03/movingtogitlab/

TBH I don't see M$ acquiring GitHub as a sustainable reason, but it's a good time for devs to realise that [they are relying on a proprietary service](https://mako.cc/writing/hill-free_tools.html). I don't think GitLab.com is any better, and I'm not sure whether EFF will want to host a GitLab CE themselves. This proposal will have my full support when [federation](https://gitlab.com/gitlab-org/gitlab-ce/issues/4013) gets implemented though.

**Comment by sampablokuper** [comment]
@gloomy-ghost [wrote](https://github.com/EFForg/https-everywhere/issues/15615#issuecomment-394628256):
> I don't think GitLab.com is any better [than GitHub]

GitLab.com is definitely not perfect, but it is [measurably better than GitHub](https://www.gnu.org/software/repo-criteria-evaluation.html) in several important respects.

**Comment by DanHarkless** [comment]
https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT is also a potentially useful resource.  They're developing a "GitHub Evacuation Guide".

**Comment by YegorIevlev** [comment]
I think EFF needs to mirror the repositories of their projects on their self-hosted GitLab or servers, instead of migrating away from where the developers are, losing developer base in result.

**Comment by sampablokuper** [comment]
@YegorIevlev [wrote](https://github.com/EFForg/https-everywhere/issues/15615#issuecomment-396729990):
> I think EFF needs to mirror the repositories of their projects on their self-hosted GitLab or servers

They already do, as has already been noted [earlier in this thread](https://github.com/EFForg/https-everywhere/issues/15615#issuecomment-394589786). (Please read threads before commenting on them.)

> instead of migrating away from where the developers are, losing developer base in result

This is a self-defeating argument. You are effectively saying: "In the face of a de-facto monopoly, give up."

The only way in which the EFF's efforts, in general, will remain meaningful, is if there are ethical alternatives at the electronic frontier. As such, the EFF, if it is to truly serve its purpose, must *not* give up in the face of challenges like this.

It must, instead, minimise its reliance on GitHub, and encourage other GitHub users to do likewise. I.e. just as it does in relation to, say, Verizon ("[Verizon users might want to start looking for another provider.](https://www.eff.org/deeplinks/2014/11/verizon-x-uidh)") or GoDaddy ("[Please check [out these alternatives to GoDaddy] and, if possible, jump on board.](https://www.eff.org/deeplinks/2011/12/moveyourdomain-protest-internet-blacklist-bills)").

**Comment by YegorIevlev** [comment]
@sampablokuper What I mean is that we should be more flexible in order to keep the developer base, instead of being stubborn on migrating away and losing it.

**Comment by Giltyhub** [comment]
fwiw i was neutral but after github flagged my account **for no reason** i'm now in favor of moving up if possible

**Comment by pipboy96** [comment]
@Giltyhub Doubling this, my account was also flagged, and support only removed the flag the second time I contacted them.

**Comment by pipboy96** [comment]
According to @zoracon this is currently discussed by EFF, but is not going to happen very soon.

**Comment by Giltyhub2** [comment]
To reiterate what I said in https://github.com/EFForg/https-everywhere/issues/18118

> I don't think it will be possible for me to continue contributing to a project when I risk that my effort gets lost. For no reason I can no longer access my @Giltyhub account since I need to "confirm my identity" by receiving some code in my email whereas I had used a guerrillamail scrambled email address which means that I can't receive their confirmation code. As a result I can no longer maintain my other previous PRs. This isn't the first time Github screwed up badly, they did flag my account multiple times simply because I keep using Tor, and when I wanted to make this new account they stopped accepting throwaway mail services (guerrillamail and co) and they flagged my new account for 3 days. Note that gitlab isn't a good option either since they don't accept throwaway mails and you have to go through the impossible ReCAPTCHA.

**Comment by Giltyhub2** [comment]
(Yet) another reason: https://github.com/1995parham/github-do-not-ban-us/

One nice alternative: https://notabug.org (or a gitea instance hosted by the EFF)

**Comment by Foorack** [comment]
Alternatively self-hosted GitLab instance or any other software. There is along list of other alternatives. I think this is something the EFF should start looking more seriously into, and priorities higher on their list.

**Comment by pipboy96** [comment]
@Giltyhub2 I don't want to pretend to be a lawyer but I think EFF would be subject to same restrictions as GitHub as a US-based entity. I hope someone with actual legal expertise from EFF will clarify if that's the case.

**Comment by pipboy96** [comment]
I personally would recommend [Gitea](https://gitea.io/).

**Comment by Giltyhub2** [comment]
@Foorack in my experience even if one uses a gitlab self hosted instance it's hard to make an account there since 1) freaking google recaptcha 2) most throwaway mails aren't accepted in the registration

**Comment by gloomy-ghost** [comment]
I'm willing to handle the https-everywhere-rules mailing list and the issue tracker hosted by tor project if needed

**Comment by pipboy96** [comment]
@Giltyhub2 You may contact @Hainish or @andresbase if you have trouble creating an account.

@gloomy-ghost I'm not sure about a mailing list, mailing lists are not private at all. I made just a few posts on one mailing list and now my email address is all over the internet. Also, deleting your posts from a mailing list is impossible, and mailing list archives get indexed by search engines pretty quickly.

**Comment by KOLANICH** [comment]
>I personally would recommend Gitea

I personally would recommend `trac`.

**Comment by pipboy96** [comment]
@KOLANICH Trac feels antiquated and not beginner-friendly to me.

**Comment by andresbase** [comment]
@Giltyhub2 you can email me andres at eff dot org. I'm also on keybase as andres_base

**Comment by pipboy96** [comment]
@andresbase For now I recommend keeping actual development repo on GitHub, but also creating a Gitea-based mirror repo on EFF's Gitea/GitLab instance. This would make it easier to test the waters before actually migrating to a self-hosted Git repo.

I think this is how we should proceed if EFF decides to migrate:

1. GitHub (origin) ➡️ mirrored to ➡️ EFF-hosted Git repo (mirror)
1. EFF-hosted Git repo (origin) ➡️ mirrored to ➡️ GitHub (mirror)
1. Deprecate GitHub mirror.

Personally, I would prefer to make the migration unless it will significantly complicate contributing to the project.

**Comment by KOLANICH** [comment]
>Trac feels antiquated 

It is a benefit that it is usable without JavaScript, not a drawback.

**Comment by pipboy96** [comment]
@KOLANICH Gitea is pretty simplistic, should also be usable without JS.
