### ISSUE TITLE
Remove da_DK translation

### ISSUE THREAD

**Issue by scootergrisen** [EFForg/https-everywhere#15640]
Type: other

I see both "da" and "da_DK" translation included in _locale folder.
But only the "da" translation exists on Transifex so im guessing "da_DK" was removed from Transifex but not here.

So please delete:

    _locales\da_DK\messages.json
    _locales\da_DK\

In https://github.com/EFForg/https-everywhere/blob/master/src/META-INF/manifest.mf#L225-L230 there is also some lines that properly should be deleted.

**Comment by Hainish** [comment]
Thanks.  Translations are controlled by the Tor Project, so I'll send a note along to them.

**Comment by Hainish** [comment]
Fixed: https://gitweb.torproject.org/translation.git/commit/?h=https_everywhere&id=0974512eae0a87991aaa674e19aac9431cf2c92c
