### ISSUE TITLE
channel4.com player issue

### ISSUE THREAD

**Issue by erstaEP4** [EFForg/https-everywhere#1564]
http://www.channel4.com/now/c4
http://www.channel4.com/programmes/made-in-chelsea/on-demand/61205-002 (click play)
Video player is not loading asset. HTTPS-E looks to be reidrecting calls to ais.channel4.com.
However the flash player has loaded its crossdomain.xml from http.
Result is that a crossdomain exception occurs.

**Comment by reedy** [comment]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://4id.channel4.com') does not match the recipient window's origin ('http://www.channel4.com').

**Comment by erstaEP4** [comment]
The things you mention are not related to the issue.
Video won't play in incognito mode in Chrome because it is protected using Adobe DRM. This is a limitation of Chrome.
From Adobe:
"DRM policies are required when encrypting/packaging content with Adobe Access DRM protection. Policies are often bound to a particular device.  In incognito mode this information is often not available resulting in this error during playback".

Please test using a normal Chrome window. Disabling the channel4.com ruleset allows the player to correctly load data from ais.channel4.com. With it enabled the call to ais.channel4.com breaks.
This is the problem.

**Comment by erstaEP4** [comment]
Can someone look at this please. I opened the issue 22 days ago.

**Comment by jsha** [comment]
This rule is now off by default due to the breakage you reported (thanks!). If you've turned the rule off and on again, your browser will remember that, so you'll need to manually disable the rule again.

**Comment by erstaEP4** [comment]
Many thanks
