### ISSUE TITLE
Videos broken on dictionary.com

### ISSUE THREAD

**Issue by DanHarkless** [EFForg/https-everywhere#15701]
Type: ruleset issue
Domain: dictionary.com

The videos on http://www.dictionary.com/ don't play unless HTTPS Everywhere is disabled.  The HTML5 player gets the error "Could not download the video" / "Error Code: PLAYER_ERR_TIMEOUT".  The player apparently loads a .m3u8 file from http://manifest.prod.boltdns.net/, which contains a bunch of http://bcbolt446c5271-a.akamaihd.net/ .ts file links.  I see there are no rules for dictionary.com or boltdns.net, so it would seem it's something to do with the akamaihd.net rules, though strangely, when I take one of the http://bcbolt446c5271-a.akamaihd.net/ links, change it to https, and paste it into the URL bar, the .ts file downloads fine.  Anyhow, here's an example page:

http://www.dictionary.com/e/matters-way-emoji-gun-facing-video/

**Comment by Bisaloo** [comment]
Hi, thank you for your report!

This bug has been fixed in #15157. Everything should work fine in the next release coming soon (#15665). Please feel free to reopen if that's not the case.

**Comment by DanHarkless** [comment]
Thank you!  I'd also opened #4263 a couple of years ago regarding breakage of videos on discovery.com and had been wondering what the "CORS" referenced on it meant.  After reviewing the tickets you linked, I have a better understanding.
