### ISSUE TITLE
gHacks.net rule blocks images

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#1574]
Open http://www.ghacks.net/2015/04/23/tech-support-one-click-away-in-windows-10/ with the gHacks.net rule and then turn it off. HTTPS Everywhere is blocking images.

**Comment by reedy** [comment]
http://cdn.ghacks.net/wp-content/plugins/social-media-feather/synved-social/image/social/regular/96x96/facebook.png

becomes

https://ghacks-ghacks.netdna-ssl.com/wp-content/plugins/social-media-feather/synved-social/image/social/regular/96x96/facebook.png
