### ISSUE TITLE
Rule "tagesschau.de (partial)" breaks faktenfinder.tagesschau.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#15762]
Type: ruleset issue

Domain: faktenfinder.tagesschau.de

The rule "tagesschau.de (partial)" upgrades http://faktenfinder.tagesschau.de/kurzerklaert/csu-kurz-erklaert-101.html to https://faktenfinder.tagesschau.de/kurzerklaert/csu-kurz-erklaert-101.html but this site includes an iframe with `src="http://www.tagesschau.de/multimedia/video/video-414531~ardplayer.html"`.
This iframe then breaks of course:
`Mixed Content: The page at 'https://faktenfinder.tagesschau.de/kurzerklaert/csu-kurz-erklaert-101.html' was loaded over HTTPS, but requested an insecure resource 'http://www.tagesschau.de/multimedia/video/video-414531~ardplayer.html'. This request has been blocked; the content must be served over HTTPS.`
(from the Chrome console)

**Comment by pipboy96** [comment]
The iframe seems to have been removed.
