### ISSUE TITLE
Travis CI failing browser tests

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#15773]
Type: other

#15239 is officially marked fixed with an added sleep , but i still experience failed ci tests.

Firefox: test/selenium/test_options.py::OptionsTest::test_show_counter FAILED
https://travis-ci.org/numismatika/https-everywhere/jobs/392344406 
https://travis-ci.org/numismatika/https-everywhere/jobs/392344076
https://travis-ci.org/numismatika/https-everywhere/jobs/392344098
https://travis-ci.org/numismatika/https-everywhere/jobs/392344460
https://travis-ci.org/numismatika/https-everywhere/jobs/392344042
https://travis-ci.org/numismatika/https-everywhere/jobs/392343842

Since all branches are rebased to the eff master branch, what is still going wrong here?
Other branches build fine

**Comment by J0WI** [comment]
See also #11793

**Comment by gloomy-ghost** [comment]
A fix was landed 2 days ago but it seems like it didn't eliminate all failing. I'll bump the `sleep` value a little and let's see how it goes.
