### ISSUE TITLE
CPU pegged at 100% in chrome 67

### ISSUE THREAD

**Issue by evan-burke** [EFForg/https-everywhere#15821]
Type: code issue

I'm using HTTPS Everywhere 2018.6.13 with Chrome 67.0.3396.87.  I only suspend or restart my computer occasionally, perhaps once or twice a month; otherwise it runs 24/7. After 2 or so days of heavy Chrome usage (14h/day), HTTPS Everywhere will peg the CPU at 100% (as shown in Chrome task manager) and Chrome won't be able to make any new http(s) requests.

Disabling and re-enabling the extension will fix the issue temporarily, but after another day or two of usage the issue will recur. 

This only began occurring last week - which seems to coincide with the release of 2018.6.13 of the extension.

I imagine you'll need more info on this - are there logs for the extension that I can pull?

**Comment by YegorIevlev** [comment]
@evan-burke Go to Extensions page and turn on Developer mode. Open DevTools by clicking "background page" on HTTPS Everywhere card. Keep the DevTools open until it hangs. Then, upload everything in console to https://gist.github.com/.

**Comment by evan-burke** [comment]
Thanks. Logfile didn't appear to show anything without verbose mode active; with verbose mode it's 5+ mb, so I've provided an excerpt here. Let me know if you need additional detail from the logfile.

https://gist.github.com/evan-burke/c6f46729bd6761d4483e2751921f5a6b

**Comment by YegorIevlev** [comment]
@evan-burke What other browser extensions do you run?

**Comment by evan-burke** [comment]
currently enabled: 

The   Great Suspender
Windows Defender Browser Protection
Save to Pocket
ReviewMeta.com Review Analyzer
RescueTime for Chrome and Chrome OS
Page Ruler
OneTab
Keepa - Amazon Price Tracker
Google Docs Offline
GoToMeeting Pro Screensharing
JSON Formatter
No Coin - Block miners on the web!
ColorZilla

**Comment by YegorIevlev** [comment]
@evan-burke Disable everything but HTTPS Everywhere and try again.

**Comment by Bisaloo** [comment]
I was thinking this could be related to https://trac.torproject.org/projects/tor/ticket/26451.

The fact that you encounter this bug on a regular basis makes me doubt it though.

**Comment by mjlmjl888** [comment]
Did you figure out which one it was?
