### ISSUE TITLE
europa.eu/rapid/ not available in HTTPS

### ISSUE THREAD

**Issue by nemobis** [EFForg/https-everywhere#15864]
Type: existing ruleset
Domain: europa.eu

http://europa.eu/rapid/search.htm works, https://europa.eu/rapid/search.htm gives

> The content you are looking for has moved.

**Comment by Bisaloo** [comment]
Thank you for your report but we don't have a rule for `europa.eu` so this shouldn't be an issue. Am I missing something here?

**Comment by nemobis** [comment]
Do you mean there's no rule within [Europa.eu.xml](https://github.com/christianheinrichs/https-everywhere/blob/ce69c39b8273b9b7d3c820c02658e3990f13067b/src/chrome/content/rules/Europa.eu.xml) to redirect such an URL? Indeed I could not find one and in the request header I see a `Upgrade-Insecure-Requests: 1` whose origin I'm not sure about.

There's no way for the extension to override an incorrect HTST, is there?

**Comment by Bisaloo** [comment]
`europa.eu` does not send a HSTS header either.

`Upgrade-Insecure-Requests: 1` may be set by extensions such as [MixedContentHunter](https://addons.mozilla.org/en-US/firefox/addon/mixedcontenthunter/) or HTTPS Everywhere in "block unencrypted requests mode".

This is maybe what is happening. Which color is your HTTPS Everywhere icon?

**Comment by pipboy96** [comment]
I can no longer reproduce this issue. In addition, RAPID is going to be replaced with [Commission Press Corner](https://ec.europa.eu/commission/presscorner/home/en) in November 2019 according to the website.
