### ISSUE TITLE
[Feature Request] Multipool Subdomains Support For Rule Creator

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#15913]
Type: feature request

Can you please add support for adding multipool subdomain in the inbuilt rule creator, and wildcard support for if there's lots of subdomains.
Thanks

**Comment by pipboy96** [comment]
Not clear what the author had intended.

**Comment by zero77** [comment]
@pipboy96 
At the moment the rule creator only works for the domain and it doesn't have the option to add subdomains or even third party domains.

For example, `api.github.com,` `live.github.com` or third party domains like, `github.githubassets.com,` `avatars1.githubusercontent.com`

**Comment by pipboy96** [comment]
@zero77 Try using debugging rulesets editor (moz-extension://eb5d92e8-fe96-4259-8c7f-3126de3ff9c7/pages/debugging-rulesets/index.html/ or chrome-extension://gcbommkclmclpchllfjekcdonpmejbdp/pages/debugging-rulesets/index.html depending on your browser).

**Comment by zero77** [comment]
I am using firefox but, neither link is working.
Also, how will this help.

**Comment by pipboy96** [comment]
@zero77 Try `about:debugging#/runtime/this-firefox`. Copy "manifest URL" from there and replace "manifest.json" with "pages/debugging-rulesets/index.html".

**Comment by zero77** [comment]
> moz-extension://74eee0e7-a730-47fe-84a5-692ac0286513/pages/debugging-rulesets/index.html

This worked, but i was looking for something a bit more stable, that users can use to create rules to submit.

**Comment by pipboy96** [comment]
@zero77 This should be addressed as part of UX rewrite. @zoracon is there any work/plans on replacing debugging-rulesets with a more robust UX?
