### ISSUE TITLE
Wikia now once again has partial HTTPS support

### ISSUE THREAD

**Issue by ExE-Boss** [EFForg/https-everywhere#15911]
## Type:
Ruleset issue

## Domain:
https://fandom.wikia.com/explore (and all other Wikia sub‑domains)

## Notes:
The Wikia index page (https://fandom.wikia.com/) still redirects to HTTP (http://fandom.wikia.com/), but the rest of the website seems to support HTTPS now (finally).

**Comment by pipboy96** [comment]
@ExE-Boss Wikia is currently migrating to a new domain (`*.fandom.com`) which is supposed to fully support HTTPS.

**Comment by ExE-Boss** [comment]
I’m well aware.
