### ISSUE TITLE
Firefox captive portal detection/access broken

### ISSUE THREAD

**Issue by jcgoble3** [EFForg/https-everywhere#15925]
Type: ruleset issue

Domain: detectportal.firefox.com

Firefox, at least on Ubuntu, detects when you are connected to a Wi-Fi network with a captive portal and displays a message informing you of this with a button to log in to the network. Clicking this button takes you to http://detectportal.firefox.com/success.txt (notice the `http://`), which is intended to redirect to the captive portal sign-in page. However, HTTPS Everywhere is now rewriting all subdomains of firefox.com to `https://`, which breaks this feature since captive portals cannot be accessed through an HTTPS URL (the result of that being a security certificate mismatch). Please adjust the rules to exclude detectportal.firefox.com so that it remains `http://`. Thanks.

**Comment by Bisaloo** [comment]
Thank you for your report! This is fixed in #15917.

**Comment by jcgoble3** [comment]
Thanks for the fast response!
