### ISSUE TITLE
Breaks Flickr login

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1592]
Per user report on Twitter: https://twitter.com/AlanDejecacion/status/591631531392663553

cc @2d1

**Comment by 2d1** [comment]
According to the reporter's [latest tweet] (https://twitter.com/AlanDejecacion/status/592760991038976000), it's working again.

He didn't explicitly state that he confirmed the ruleset having been the problem, and the timing of the tweets suggest it may not have been, per this order:
1. "[Is this still happening for you? I was able to repro on Friday but can't anymore.] (https://twitter.com/HTTPSEverywhere/status/592742329770967041)"
2. "[thanks for quick reply. seems to work now after disabling rules for flickr. pic.twitter.com/OyOSd7OeGK] (https://twitter.com/AlanDejecacion/status/592753115725697024)"
3. "[ok, i just re-enabled the rule. logged out and in again works fine.] (https://twitter.com/AlanDejecacion/status/592760991038976000)"

Had you tested disabling the ruleset on Friday?

**Comment by jsha** [comment]
On Friday I did not test disabling the ruleset in my main profile, but confirmed that login was broken on my main profile, and that a temporary test profile running the version of the ruleset with securecookie removed did in fact succeed in logging in. It's possible Yahoo was having some intermittent changes on their login servers during that time, such that it would succeed in one profile and fail in another, but that seems odd. Considering this closed since no-one can repro anymore. Thanks!
