### ISSUE TITLE
Roll forward Google rulesets refactors

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1595]
@fuzzyroddis did a bunch of work to refactor the Google rulesets for the new coverage rules, but I had to revert them at the last minute for the 5.0 release because the refactor broke coverage for deep country TLDs like .co.uk. Here's the revert: https://github.com/EFForg/https-everywhere/pull/1217

We should roll forward that change, fixing #1216 and #1215 at the same time.

**Comment by fuzzyroddis** [comment]
I wish I had time to do this but my days are spent looking after my health. Anyone feel free to do this :+1:

**Comment by jsha** [comment]
Sorry to hear you are having health problems, @fuzzyroddis! No worries, we will take care of the roll forward.

**Comment by fuzzyroddis** [comment]
Thank you so much for doing this, I really wish I had the time to do it.
