### ISSUE TITLE
Error #2035 on embedded youtube videos

### ISSUE THREAD

**Issue by cluesch** [EFForg/https-everywhere#1598]
On http://www.theregister.co.uk/2015/04/25/frankfurt_musikmesse_2015/ there are two embedded youtube videos, which are launched with jwplayer (loaded via JS & CDN). If https-everywhere is running, then I get an **Error #2035** when trying to play them, if it is disabled they play.

System is Windows 7 64-bit, Firefox 31.6.0 ESR and HTTPS-Everywhere 5.0.3, freshly updated and booted. There are a few other extensions running.

**Comment by jsha** [comment]
I wasn't able to reproduce on Firefox 31 / HTTPS Everywhere 5.0.3 / Debian 8.

Can you create a fresh Firefox profile and see if it still reproduces?

Thanks,
Jacob

**Comment by reedy** [comment]
I can replicate this on FF 38.0 (not sure which beta), HTTPSE 5.0.3 on Windows 7 x64. Works with HTTPSE disabled

https://wordpress.org/support/topic/plugin-wordtube-error-2035-when-playing-youtube-videos

**Comment by reedy** [comment]
Creating a new profile just installing HTTPSE, then visiting that page results in the same error
