### ISSUE TITLE
Unable to launch “Debugging Rulesets” page on Firefox

### ISSUE THREAD

**Issue by franklinyu** [EFForg/https-everywhere#16023]
Type: other
Operating system: Windows 8.1
Browser: Firefox 61.0

On the settings page, I clicked the space below the title “General Settings”, and hit `Ctrl`+`Z`. Nothing happened. This is available on Chrome; is it disabled on Firefox or the trigger is different? Currently I manually append the path `/pages/debugging-rulesets/index.html` to the extension ID to navigate to that page.

**Comment by Bisaloo** [comment]
Duplicate of https://github.com/EFForg/https-everywhere/issues/13731?

**Comment by franklinyu** [comment]
Sigh. I only searched for “Debugging Rulesets”.
