### ISSUE TITLE
Feature: Allow password inputs only on HTTPS pages

### ISSUE THREAD

**Issue by sedrubal** [EFForg/https-everywhere#1603]
I don't know, how hard it is to implement to give a warning or to block inputs if there are password inputs on `http://` pages. Firefox reports this in the developer console but a normal user won't see this.

**Comment by reedy** [comment]
Out of interest, what's the warning?

**Comment by sedrubal** [comment]
```
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
Password fields present in a form with an insecure (http://) form action. This is a security risk that allows user login credentials to be stolen.[Learn More]
```

Link: https://developer.mozilla.org/en-US/docs/Security/InsecurePasswords

**Comment by jsha** [comment]
I think this is out of scope for HTTPS Everywhere, but I appreciate the suggestion!
