### ISSUE TITLE
[feature request] blacklist to skip some sites

### ISSUE THREAD

**Issue by beenotung** [EFForg/https-everywhere#16037]
Some site don't support https but is redirected to https, the content are just blank. Probably wrong configuration or the site admin is not aware of it (expecially then the site is generated, not coded manaully)

I tried to create custom rule to redirect to to http but it doesn't work, still redirected to https version.

**Comment by Bisaloo** [comment]
Hi, thank you for your report. I am not entirely sure what you are asking, could you provide an example of URL where you have this issue?

**Comment by beenotung** [comment]
Unfortunately, for privacy, I don't want to share that site here
but I can add more story to it.
When I'm surfing this site with http, it's working fine,
when I'm surfing this site with https, it displayed belows
```
Welcome to (domain name)
To change this page, upload a new index.html to your private_html folder
```

However, I just founds some sites from https://gist.github.com/Enegnei/6b13b2d5d0bc7adebb66195f807f3f3b that is having invalid cert:
- ymp.gov
- americorp.gov
- www.stealmylogin.com/
For these sites, does running https and http making no much different?

**Comment by beenotung** [comment]
I just searched the sentense "To change this page, upload a new index.html to your private_html folder
" on google and found quite a lot of sites, for example:
www.klassewijzer.nl

**Comment by pipboy96** [comment]
I believe the only thing you can do is to disable the extension on the affected website. We no longer allow downgrade rules.
