### ISSUE TITLE
Unable to run standalone profile of Firefox with new version of Firefox.

### ISSUE THREAD

**Issue by svaniksharma** [EFForg/https-everywhere#16061]
Type: other

Hey there.
I was trying to run a standalone profile of Firefox with the latest code (`bash test/firefox.sh --justrun`). I noticed that HTTPS Everywhere wasn't enabled so I checked whether the extension was on by default. It turns out that the version of Firefox (61.0.1) that I'm using seems to prevent the extension from working because it wasn't verified by Mozilla which is now a requirement according to [this](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox). I've also tried to do `bash test/firefox.sh` after installing Geckodriver, but it failed saying `Firefox: HTTP to HTTPS redirection failed.`

**Comment by s1l3ntcat** [comment]
I didn't mention this in my original comment, but I'll mention it here: To fix the problem I had with Firefox, I did the following:
`bash test/firefox.sh --justrun`
Go to `about:debugging`
Click "Load Temporary Add-on"
Select any of the HTTPS Everywhere XPI files.
Click the Reload button beneath the newly loaded add-on.
Do whatever testing you want.

This was my solution. Not sure if it worked though.
