### ISSUE TITLE
HTTPS Everywhere breaks www.budgettravel.com site

### ISSUE THREAD

**Issue by libove** [EFForg/https-everywhere#1606]
I *think* that it is HTTPS Everywhere doing this...
Clicking on links in email newsletters from Budget Travel Magazine, e.g. this link in a recent email:
http://link.p0.com/u.d?UYGrM1Gw9CS2jP8VxJ5zva=95471
launches by default web browser, Firefox, in which I have HTTPS Everywhere installed and active, and ends me up at:
https://www.budgettravel.com/feature/10-common-warning-signs-to-look-for-at-a-hotel,45589/?wpisrc=newsletter
with a Cannot connect error.
Manually changing the https:// back to http:// allows the page to load.

I looked for an option within HTTPS Everywhere to "Turn off HTTPS Everywhere for the currently displayed page", but did not find one. So I checked the HTTPS Everywhere FAQ, and it says to disable the rule affecting the page (HTTPS Everywhere shows no rules firing on this page) or to report it as a bug.

So, two things.
1. I guess it's a bug. HTTPS Everywhere and http://www.budgettravel.com don't like each other. (Or perhaps it's an interstitial link between the http://link.p0.com/... and when it finally transfers the user to http[s]://www.budgettravel.com)
2. Feature request: Add an 'Idiot Light' type option to HTTPS Everywhere to let the (non-technical) user simply click on the HTTPS Everywhere browser toolbar icon and select "Disable HTTPS Everywhere for this site".

thanks,

**Comment by reedy** [comment]
So that sort of looks like HTTPSE is turning the link.p0.com link into HTTPS, which then just does a protocol relative redirect to budgettravel.com

The ruleset for p0 is Infogroup.xml in this case

Which sort of means it's not HTTPSE at fault here. Though, the question is whether we disable the link.p0.com rewrite if it causes problems such as this

**Comment by libove** [comment]
Hi reedy,
I confirm that disabling the infogroup rule stops this problem.
I looked at the infogroup rule source, and I don't see how it might be edited to NOT do an HTTPS redirect if the destination of the p0 redirect happens to be BudgetTravel.com ... ?

**Comment by reedy** [comment]
I don't think we can either, and probably shouldn't. We could possibly put downgrade rules in for BudgetTravel.com, but that seems overkill.

Part of me would be in favor of disabling that whole redirect...

**Comment by libove** [comment]
This being closed, does it mean that the infogroup rule has been updated, and in a near-future release of HTTPS Everywhere the problem will be fixed for the BudgetTravel email redirects? Or, what does it mean that this is closed? thank you.

**Comment by reedy** [comment]
It means in a future release that link.p0.com redirect urls won't be changed to HTTPS, which means they won't then incorrectly redirect to HTTPS for sites that don't have their own rulesets on HTTPSE already
