### ISSUE TITLE
Thunderbird --> no longer available?

### ISSUE THREAD

**Issue by StealthBlackOxide** [EFForg/https-everywhere#16077]
Type: other

https://addons.thunderbird.net/en-US/thunderbird/addon/https-everywhere/

"We're sorry, but we can't find what you're looking for.
The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly. "

**Comment by pipboy96** [comment]
Indeed, it does not seem to be there.

**Comment by Hainish** [comment]
We don't support Thunderbird, sorry.  Third parties are welcome to ingest the rulesets we have available at https://www.https-rulesets.org/. Documentation for rulesets are available here: https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/ruleset-update-channels.md
