### ISSUE TITLE
Add German Greenpeace sites

### ISSUE THREAD

**Issue by blobgo** [EFForg/https-everywhere#1608]
Add [www.greenpeace.de] (https://www.greenpeace.de).
This is the German website of Greenpeace and unlike the [international site] (https://www.greenpeace.org/international/en/) (bad domain - akamai) everything works correctly with HTTPS there based on my test.
On greenpeace.de the webserver also changes the links correctly to https://.

On the second site [www.greenpeace-energy.de] (https://www.greenpeace-energy.de) which also belongs to greenpeace the links aren't correctly changed, but I think this is no problem because HTTPS-Everywhere would redirect these.

And finally the third site provides HTTPS by default, but [as you know] (https://www.eff.org/https-everywhere/faq#faq-Why-does-HTTPS-Everywhere-include-rules-for-sites-like-PayPal-that-already-require-HTTPS-on-all-their-pages?) it's also good to add a ruleset for this site: [www.greenpeace-magazin.de] (https://www.greenpeace-magazin.de/)

**Comment by blobgo** [comment]
Okay a few more sites related to Greenpeace:
https://www.greenpeace-jugend.de/ (by default HTTPS)
https://kids.greenpeace.de/ (HTTPS supported; mixed content, but this only affects an image from YouTube. - However if you have the YouTube rule of HTTPS-Everywhere activated it loads the image via HTTPS although Firefox displays the mixed content warning anyway.)

**Comment by reedy** [comment]
FYI, you don't really need to list all the domains in the subject

**Comment by blobgo** [comment]
Okay... :smiley:

**Comment by reedy** [comment]
Certainly, being explicit in the comments, listing what sites/subdomains should be added is appreciated though

**Comment by reedy** [comment]
Oh, and someone has already created a ruleset for Greenpeace-Energy.de in #1586 which is awaiting review/merge

**Comment by blobgo** [comment]
Okay thanks for the information. So maybe @julianladisch wants to add the other sites as well...

**Comment by J0WI** [comment]
#1787 should finally fix this.
