### ISSUE TITLE
Rules GUI causes firefox freeze and shows an empty list at the first start

### ISSUE THREAD

**Issue by blobgo** [EFForg/https-everywhere#1609]
The user interface which shows all rules is very slow if I open it at first (it takes a few seconds) and it even shows an empty rules list.
If I start a new browser session (so just close the browser and restart) and click on the HTTPS-Everywhere icon --> Activate/Deactivate rules Firefox will freeze for a few seconds, CPU usage for Firefox goes up and after some time it will finally show the GUI. But this is only an empty list.
If I close the window and open it again it instantly shows everything correctly.

Browser: Firefox 37.0.2
Add-on version: 5.0.3

**Comment by blobgo** [comment]
For what it's worth here is the video of this issue: https://mega.co.nz/#!3MAkiZBC!IcAcFz2B_E69Ym5vs4PAe99OU39-RgDetYU7DUkrfKg
Ignore the things I did during the freezing - I just wanted to make some screenshots.

FYI I could reproduce the issue every time after a Firefox restart.
So after I made this video I tried to narrow it down to another add-on, so I disabled them all, enabled HTTPS Everywhere again and enabled every other addon one by one. But sadly the issue didn't happened again, even with all add-ons enabled - I had to wait more than 5 seconds again everytime to show the GUI, but it finally showed a it correctly. So all rules were listed correctly and there was no empty list anymore.
Because of this I close this issue now. If I'm experiencing this issue another time I will reopen this issue.

**Comment by blobgo** [comment]
Well... it's appearing again and again.
It's strange that I couldn't reproduce it at the time I wanted to reproduce it.
However I also noticed two new things. At first during freezing the RAM usage goes up very much and the CPU is also drained quite much.
Secondly Firefox often shows me that the following script is causing errors (during freezing). If I click on "Stop" I can go on and this time even the rules list was successfully shown.
> chrome://global/content/bindings/popup.xml:28

![httpsseverywhere_cpuandramusage](https://cloud.githubusercontent.com/assets/12105354/7901811/f1598a1e-079b-11e5-9d3e-9b5c53f592c7.png)

**Comment by lkraider** [comment]
Same issue here, I get the unresponsive script dialog when clicking to open the addon preferences:
```
Script: chrome://global/content/bindings/popup.xml:28
```

**Comment by blobgo** [comment]
In v 5.0.6 the complete window was now removed, so we I close this issue now. (fixed by https://github.com/EFForg/https-everywhere/pull/2121)

IMHO this is not an optimal solution as I really liked the ruleset window, but now it's done.
