### ISSUE TITLE
Fox News rule breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#16109]
Type: ruleset issue

Domain: foxnews.com

http://insider.foxnews.com/2018/07/06/nratv-host-responds-liberal-author-confused-about-black-man-bmw-who-supports-nra

Video is broken when the Fox News rule is active.
![image](https://user-images.githubusercontent.com/12802056/43359944-ada3d578-927a-11e8-879d-144ba77d37f8.png)

**Comment by Bisaloo** [comment]
> Mixed Content: The page at 'https://video.insider.foxnews.com/static/p/video/app/embed/iframe/vod.html?_fx=y&video_id=5806130369001&autoplay=true&share_url=http://insider.foxnews.com/2018/07/06/nratv-host-responds-liberal-author-confused-about-black-man-bmw-who-supports-nra&share_title=NRATV%20Host%20Responds%20to%20Liberal%20Author%20%27Confused%27%20About%20Black%20Man%20in%20BMW%20Who%20Supports%20NRA%20&share=true' was loaded over HTTPS, but requested an insecure image 'http://a57.foxnews.com/media2.foxnews.com/BrightCove/694940094001/2018/07/06/640/360/694940094001_5806126285001_5806130369001-vs.jpg'. This content should also be served over HTTPS.

**Comment by pipboy96** [comment]
Video plays with both HTTPS Everywhere on and off.
