### ISSUE TITLE
Texas Instruments wiki and tools need exceptions

### ISSUE THREAD

**Issue by regdoug** [EFForg/https-everywhere#1611]
It seems there used to be an exclusion rule for http://processors.wiki.ti.com/ (which does not support HTTPS) but is has been commented out, leaving the site unusable.  See https://github.com/EFForg/https-everywhere/blob/ddb268380c7cffba22e65602353dad3f5118599d/src/chrome/content/rules/Texas-Instruments.xml#L120

Additionally, at least some http://www.ti.com/tool/[tool id] pages do not support HTTPS and an exception should probably be added for all http://www.ti.com/tool/*.  See https://www.ti.com/tool/pmp9754 for an example of a broken page.

**Comment by reedy** [comment]
The whole processors.wiki.ti.com host isn't targetted by HTTPSE (in master at least)

https://github.com/EFForg/https-everywhere/blob/ddb268380c7cffba22e65602353dad3f5118599d/src/chrome/content/rules/Texas-Instruments.xml#L83

**Comment by semenko** [comment]
Seems fixed per above commits.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
