### ISSUE TITLE
Release 2018.8.7/8 forthcoming

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#16122]
Type: other

cc @bcyphers @jsha @pde @J0WI @diracdeltas @jeremyn @gloomy-ghost @Bisaloo

Let's come up with some release notes in the comments, as well.

Release Notes (incomplete):
    * Adding a warning to pages which 'Block all unencrypted requests' is unable to upgrade
    * Reduces memory overhead by optimizing exclusion regex
    * Block insecure FTP connections when 'Block all unencrypted requests' is checked

**Comment by cschanaj** [comment]
Block insecure FTP connections when 'Block all unencrypted requests' is checked (#15813)

**Comment by Hainish** [comment]
I would like for this release to incorporate a UX I'm working on to give users control of what update channels are available.  I'm going to push this off until next week and do a ruleset update today.

**Comment by J0WI** [comment]
#15938 LGTM, but may need to be updated before the release.

**Comment by J0WI** [comment]
> npm packages should be checked for security updates during the release process. Some of our scripts raise security warnings.

I've added #16290

**Comment by cschanaj** [comment]
It might worth take a look at #15747, #15486 and #15790 if time is allowed.

**Comment by Hainish** [comment]
Thanks @J0WI and @cschanaj, I think there will be time.  I just merged https://github.com/EFForg/https-everywhere/pull/16306, which I'd love some eyes on before doing a launch.  I'm going to push this off another week to mid-next week.

@cschanaj do you want to check out #16306 and do a little review?  It's already merged but I want another pair of eyes on it for QA's sake.

**Comment by cschanaj** [comment]
Fix complex rewrites on Firefox 59+ when 'Block all unencrypted requests' is checked

**Comment by Hainish** [comment]
Release 2018.8.22 made!

**Comment by J0WI** [comment]
The update requires a new permission #13817
