### ISSUE TITLE
Can't apply policies to applications in Duo Security admin dashboard

### ISSUE THREAD

**Issue by lucascantor** [EFForg/https-everywhere#16121]
Type: ruleset issue

Domain: duosecurity.com

This issue occurs within Duo customers' admin dashboards
- e.g., `admin-12ab34cd.duosecurity.com/applications/A1B2C3D4E5F6G7H8I9J0K`

**Comment by Bisaloo** [comment]
Hi, thank you for your report!

Unfortunately, it looks like an account is required to reproduce this issue. This is always quite difficult for us to fix as we're working in the dark.

Is there any way you can provide more information? Mixed content warnings from your browser, output from developer console, etc.

**Comment by lucascantor** [comment]
Hi @Bisaloo 

Thanks so much for the super-fast follow-up 🙌🏼

I'm not seeing any warnings from my browser (Chrome 68.0.3440.75) and the developer console remains completely empty before, during, and after reproducing the issue ☹️

**Comment by Bisaloo** [comment]
Uhm, we can at least try to pinpoint the faulty ruleset.

Can you try to see if everything works as expected when you disable the `Duo Security.com (partial)` ruleset (by clicking on the checkbox in the HTTPS Everywhere dropdown menu)?

**Comment by lucascantor** [comment]
Hmm, interestingly now I'm unable to reproduce the issue at all, which is even more confusing... I wonder if Duo just changed something on their end 🤔

I suppose it makes sense to close this issue for now, but re-open it if the problem re-occurs.

Thanks so much for the help regardless 🙏
