### ISSUE TITLE
Ruleset submissions

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#1612]
This is a ruleset I created with HTTPS Finder. If the ruleset is ok and you give me access to add rulesets into HTTPS Everywhere I will submit a lot of rulesets in the near future.

```<ruleset name="Penguin United Store">
<target host="www.penguinunitedstore.com"/>
<rule from="^http://(www\.)?penguinunitedstore\.com/" to="https://www.penguinunitedstore.com/"/>
</ruleset>```

**Comment by reedy** [comment]
This looks fine at a quick glance, though, with the rule like that, you probably want to target with no www too.

Please submit these as proper pull requests though

**Comment by anonsubmitter** [comment]
Ah sorry, I'm new at rulesets and GitHub. What part of the ruleset should I change to target non-www URLs?

**Comment by reedy** [comment]
You just add another target element with the host without the www. See below

```
<ruleset name="Penguin United Store">
<target host="penguinunitedstore.com"/>
<target host="www.penguinunitedstore.com"/>
<rule from="^http://(www\.)?penguinunitedstore\.com/" to="https://www.penguinunitedstore.com/"/> </ruleset>
```

As for making pull requests, https://help.github.com/articles/using-pull-requests/ should be helpful to you :+1: Good luck!

**Comment by anonsubmitter** [comment]
Thanks. I'll take a look at it. :)

**Comment by anonsubmitter** [comment]
Which layout is preferred for the ruleset by the way, the one HTTPS Finder produces or the structured version you displayed?

**Comment by reedy** [comment]
Either is good. It generally looks better indented, but it's not a deal breaker

**Comment by jsha** [comment]
Closing this issue; Please reopen as a pull request.

**Comment by jsha** [comment]
Closing this issue; Please reopen as a pull request.
