### ISSUE TITLE
Redirecting only the main document location and not internal page resources

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#1613]
Is it possible to redirect http://example.net/image.jpg to something else when I open the image directly and see it in the address bar, but not when it is embedded in an HTML page?

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.

[I don't think we're likely to support top-level only redirects, but feel free to send a PR.]

**Comment by anewuser** [comment]
Workaround: https://addons.mozilla.org/firefox/addon/redirector/
