### ISSUE TITLE
Hitbox.tv is refreshing repeatedly forever

### ISSUE THREAD

**Issue by mh0rst** [EFForg/https-everywhere#1616]
When visiting hitbox.tv (tried main page and a users channel), it keeps refreshing the page repeatedly. 

It seems that this change https://github.com/EFForg/https-everywhere/commit/9ee66a115110b22f69e0526c96ebc60c196b4f86 is responsible for this behaviour, because disabling the hitbox.tv ruleset resolved the issue for me.

**Comment by reedy** [comment]
It seems to do some weird redirecting later in the loading process
