### ISSUE TITLE
UU.se.xml disabled by mistake(?)

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#1617]
The ruleset in UU.se.xml was

    Disabled by https-everywhere-checker because:
    Fetch error: http://uu.se/ => https://www.uu.se/: (6, 'Could not resolve host: uu.se')

At first, I figured that this could have been do to a temporary outage when the test was run, but in fact, no parts of the rule redirect to uu.se (with no www), so it is unclear to me why not being able to resolve that host would cause the rule to be disabled in the first place, but I might be misreading the test output.

**Comment by reedy** [comment]
Does running the test now (with the disabling removed) pass for this ruleset?

**Comment by jsha** [comment]
@fuglede: The checker as it currently stands will disable the ruleset if a 'from' URL doesn't exist. I recently worked on a change with @Hainish to ignore connection refused / connection timeout in 'from' URLs. It's not 100% clear to me that in general we should ignore name resolution in 'from' URLs. Perhaps only in the non-www -> www case.

That said, it looks like uu.se does resolve now, so we can probably re-enable. Run `./fetch-test.sh src/chrome/content/rules/UU.se.xml` to check?

**Comment by fuglede** [comment]
Actually, let me just take a tour through the site to see what works and what doesn't; I'll submit a PR afterwards. From the looks of it, most of the domains work completely fine even when mixed content is taken into account.
