### ISSUE TITLE
Brightcove rule blocks videos on Welt.de

### ISSUE THREAD

**Issue by d4k0** [EFForg/https-everywhere#1618]
Hi,

I wanted to watch a video on the German news website "Welt.de" today, but the video failed to load. After a few tests it turned out that the rule "Brightcove (partial)" is the culprit. If I deactivate it, the video loads.

Here is an example: http://www.welt.de/sport/article140206957/Warum-Floyd-Mayweather-fuer-Henry-Maske-Favorit-ist.html
This is the video url that is loaded by the news website: http://brightcove01.brightcove.com/7/8385562001/201504/1769/8385562001_4201324377001_V013-SID26479.mp4

It would be nice if this could be fixed.

**Comment by reedy** [comment]
Works fine for me

**Comment by d4k0** [comment]
I just tried it with a new profile (I'm using Firefox 37.0.2) with only HTTPS-Everywhere installed and it still doesn't work (the site says: "We are sorry, there was an error"):

![Error](https://i.imgur.com/3R0ziq7.png)

If I deactivate "Brightcove (partial)", the video loads:

![Working](https://i.imgur.com/dFd73oO.png)

**Comment by reedy** [comment]
Chrome 44 w/ HTTPSE 2015.4.23 works fine

FF 38.0 (not sure which beta) with HTTPS 5.0.3 plays the advert fine, but then the actual video won't play after

http://brightcove01.brightcove.com/7/8385562001/201504/1769/8385562001_4201324377001_V013-SID26479.mp4 becomes https://bcsecure01-a.akamaihd.net/7/8385562001/201504/1769/8385562001_4201324377001_V013-SID26479.mp4 when browsed directly.

**Comment by d4k0** [comment]
I now also tried it with Chome 42 and it indeed works there without a problem (strange!).

If I deactivate "Brightcove (partial)" and activate it again on the site (using Firefox), I get exactly your behaviour with Firefox.

So this issue somehow seems to be Firefox related.

**Comment by reedy** [comment]
Having spoke with a Brightcove developer, things like this are going to happen very widely due to the use of CDNs, and a lot of their customers not wanting to pay the money for the required SSL certs etc...

**Comment by J0WI** [comment]
This seems fixed to me. "Weld.de" also recently moved to https themselves (#6818).
