### ISSUE TITLE
Chrome: "Block HTTP requests" runs before HSTS?

### ISSUE THREAD

**Issue by alex** [EFForg/https-everywhere#1622]
Hi all!

I've been trying out the Block HTTP requests feature, and for the most part it's great! However, one thing I'm seeing is that it seems to run the "block" logic before checking the `Strict-Transport-Security` database.

The result is that if you have a URL you've previous visited, which enters the domain in the HSTS DB, and then you go to the `http://` URL, you get an error instead of automatically upgrading it to https.

Thanks!

**Comment by jsha** [comment]
Interesting. I thought @diracdeltas fixed that for FF: https://github.com/EFForg/https-everywhere/issues/1219. Should be included in 5.0.1+. What version are you on? Chrome or FF?

**Comment by alex** [comment]
This is Chrome, version 2015.4.23, which I guess is the problem?

Is there a way to force it to upgrade?

**Comment by reedy** [comment]
2015.4.23 is 5.0.3

**Comment by jsha** [comment]
Yeah, looks like you're up to date, but this bug exists in Chrome too. We should fix it.

**Comment by diracdeltas** [comment]
This might be tricky in Chrome - the fix in Firefox depended on a channel property that indicates HSTS will be applied even though the URI scheme is HTTP.

**Comment by semenko** [comment]
This isn't exposed through the Chrome API, I'm afraid. Closing for now since it's not solvable by us -- and the Chrome developers haven't expressed interest in a deeper TLS API / HSTS API.

**Comment by jsha** [comment]
Thanks for investigation, @semenko.
