### ISSUE TITLE
mit.edu redirects to an invalid certificate

### ISSUE THREAD

**Issue by garrettr** [EFForg/https-everywhere#1628]
## Versions

* Google Chrome 42.0.2311.135
* HTTPS-E 2015.4.23

## STR

1. Visit http://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf
2. HTTPS-E redirects to https. In drop-down window, says "MIT.edu (partial)" under "Stable Rules".
3. The https site uses an expired certificate that also appears to be intended for internal use on the MIT network (signed by CSAIL Master CA v2).
4. Chrome shows a TLS error page

The expiry is not HTTPS-E's problem, but I think it would be ideal if HTTPS-E did not redirect to pages with certs that are unlikely to validate in the average user's browser.

Does HTTPS-E try to distinguish between redirecting to sites that have certs and sites that have certs that appear valid in the average user's browser (e.g. not self-signed or signed by an internal CA)? If it does not, I would argue that it should - otherwise, you are training users to click through browser warnings to get to the content they want. In this case, I just want to read a public domain academic paper - while I'd prefer if it was sent to me encrypted, I think it would be better not to see this type of TLS warning.

**Comment by jsha** [comment]
Yep, we only include rules for sites that validate in typical browsers*, so this is broken and should be fixed.

*Exception: Some rules with platform=cacert can be enabled by users who add cacert to their trust store (rare).
