### ISSUE TITLE
Add New ruleset for www.whatreallyhappend.com & www.greatis.net

### ISSUE THREAD

**Issue by rugabunda** [EFForg/https-everywhere#16302]
Type: new ruleset

Domain:

www.whatreallyhappened.com
www.greatis.net

**Comment by rugabunda** [comment]
Just noticed that enabling https on whatreallyhappened.com causes some youtube videos to break. Please fix this if possible.

**Comment by Bisaloo** [comment]
Thank you for your message, I'm closing this as a duplicate of #17060
