### ISSUE TITLE
Add new exclusion for www.sonicwall.com/iconfirm.html

### ISSUE THREAD

**Issue by jcochran** [EFForg/https-everywhere#16367]
Type: ruleset issue
Domain: www.sonicwall.com

The Content Filter for Sonicwall appliances can redirect to a page hosted at www.sonicwall.com/iconfirm.html. This page does not support use of HTTPS. I suggest an exclusion for the iconfirm.html page. This has also been reported to Sonicwall technical support. 

<exclusion pattern="^http://(?:\w+\.)?sonicwall.com/iconfirm.html" />

**Comment by pipboy96** [comment]
Webpage no longer exists, HTTP requests are redirected to HTTPS on website's side.
