### ISSUE TITLE
Add exclusion for http://neverssl.com

### ISSUE THREAD

**Issue by isiahmeadows** [EFForg/https-everywhere#16360]
Type: new ruleset
Domain: neverssl.com

All assets from neverssl.com should be excluded, because the whole point the site exists is to enable users to get around things like broken WiFi portals (that can't intercept HTTPS at all), where anything beyond basic unencrypted HTTP/1.1 itself is a problem. It's otherwise just a static web page with an associated favicon - I checked the network requests fetched - so there's no risk in just adding a global exception for that domain.

It explains all this in the site itself.

**Comment by pipboy96** [comment]
The point of this website is to test the browser's behavior if a page does not support HTTPS. Adding an exclusion for this page doesn't make sense, neither the extension does support any built-in exclusions to EASE mode. You can always disable the extension for websites you don't want to be rewritten/blocked. This is `wontfix` sadly.
