### ISSUE TITLE
Display original URL when HTTPS Everywhere redirects to HTTP Nowhere blocking page

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#16387]
Type: feature request

A bit of user feedback:

> Hello,                                                                                                                                          
>                                                                                                                                                 
> I just experienced your new warning page for the first time (the page that is displayed when I try to visit unsecure webpages). I like it.      
>                                                                                                                                                 
> I just have a small issue with it:                                                                                                              
>                                                                                                                                                 
> I sometime want to navigate to a given unsecure webpage anyway, and what I usually do is I copy/paste the URL into an Incognito window (where I 
keep HTTPS Everywhere off) and go on browsing from there.                                                                                         
> With your new UI I have to go back to the origin of that URL, in order to copy it, or in order to remember what page it was (in case I forgot). 
>                                                                                                                                                 
> Do you think it could be possible to make the extension display the URL of the blocked webpage somewhere on the warning page?                   
> That way people can see which page has been blocked and if they decide they want to visit it anyway (or do anything else with it) they can copy 
the URL directly from there.

**Comment by Bisaloo** [comment]
This is fixed by dc04b6d845736922667317ab240bfe97e63135ce
