### ISSUE TITLE
Warning page do not work on Chrome Incognito mode

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#16394]
Type: code issue

## Platform

Browser: Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Platform: Debian 9

## Step to reproduce

1. Start Google Chrome in Incognito mode and check "Block all unencrypted requests"
2. Visit http://time.com/ and expect the site to be blocked due to redirect loop and the warning page implemented in #16053 shown up
3. Observe Google Chrome display its own warning page

![screenshot_2018-08-26_10-39-04](https://user-images.githubusercontent.com/23636124/44624278-54b31100-a91c-11e8-8744-7497c5dab8a0.png)

**Comment by Giltyhub** [comment]
I can reproduce it as well.

**Comment by bcyphers** [comment]
It looks like this happens with any chrome-extension:// URL you try to open in incognito mode. I just tried accessing some Privacy Badger resources and had the same issue. The logic is working correctly, but we need to find a way to work around this.

**Comment by cschanaj** [comment]
IMHO, redirect the page to an external resource on eff.org seem promising. First, it avoid breaking the code. It will also allow EFF to provide more detailed information to the extension users. Since this might have privacy implication, there should be an option for user to opt-out the redirect.

P.S. According to the docs, `"incognito": "split"` is not supported by Firefox (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito)

cc @jeremyn @J0WI @gloomy-ghost @Bisaloo opinions?

**Comment by Bisaloo** [comment]
I don't really like the idea of redirecting to an external resource (such as `eff.org`). As you said, it has many important privacy implications, such as referers which may information about visited pages.

A fourth option would be to keep things as they are right now. It's not optimal but the default page shown in the OP screenshot is still quite explicit and should work well enough.

**Comment by J0WI** [comment]
I'm not so happy with redirecting to another site. Isn't there any other solution? How does e.g. uBlock Origin handle this case?

**Comment by cschanaj** [comment]
It seem that uBlock Origin has no problem with redirecting the users to the warning pages, tested with http://com.com/. If we can apply the same solution uBO used, I agree that it should be preferred.

**Comment by bcyphers** [comment]
@cschanaj uBlock uses `"incognito": "split"` in Chrome (https://github.com/gorhill/uBlock/blob/master/platform/chromium/manifest.json). This bug doesn't appear to affect Firefox.

**Comment by bcyphers** [comment]
Related: https://github.com/EFForg/privacybadger/issues/2092

**Comment by geekley** [comment]
Can't you just make the extension popup show up by itself in this case? As if you had clicked on it? And make the warning show up there?
Or maybe redirect to a data URL for an HTML containing the warning?

Also, I can confirm this happens in Opera, even when I check the option to allow the extension to run in private mode.

**Comment by goodjohnjr** [comment]
Hello,

I noticed the same problem as well, this has happened with some other extensions as well, but I imagine that something could be done about this; thank you for reporting this.

I was just about submit an issue about this as well until I saw this thread while I was typing the title for my issue:

I would like to report a bug with the latest HTTPS-Everywhere for Google Chrome when using the Encrypt All Sites Eligible (EASE) option when using Incognito Mode (which is the mode that I use when using Chrome) where you do not get the warning page when a page (example: http://click.malwarebytes.com/?qs=48d85b525f203f66ff3a5f2dcf8beb40fa547c8543ffda46f55a587fa6bd31e3f5e0e438e923f213af97fe8b559f59b2d5cb6d6ab9d640d1) is blocked for lacking HTTPS and instead you get a message like this:

> gcbommkclmclpchllfjekcdonpmejbdp is blocked Requests to the server have been blocked by an extension.
> Try disabling your extensions.
> ERR_BLOCKED_BY_CLIENT

![498a4764-e0d2-49ad-a351-0de690f73e0c png](https://user-images.githubusercontent.com/46236743/53123373-864d1380-351e-11e9-897a-37140d5eb537.jpg)

In normal Chrome mode (non-Incognito Mode) it looks like this which is the way that it should look in Incognito Mode as well:

![53696562-c89d-4519-823d-d347d56f9e25 png](https://user-images.githubusercontent.com/46236743/53123407-995fe380-351e-11e9-9f44-4669a9f43427.jpg)

> HTTPS Everywhere noticed you were navigating to a non-HTTPS page, and tried to send you to the HTTPS version instead. The HTTPS version is unavailable. Most likely this site does not support HTTPS, but it is also possible that an attacker is blocking the HTTPS version. If you wish to view the unencrypted version of this page, you can still do so by disabling the 'Block all unencrypted requests' option in your HTTPS Everywhere extension. Be aware that disabling this option could make your browser vulnerable to network-based downgrade attacks on websites you visit.
> 
> URL: http://click.malwarebytes.com/?qs=48d85b525f203f66ff3a5f2dcf8beb40fa547c8543ffda46f55a587fa6bd31e3f5e0e438e923f213af97fe8b559f59b2d5cb6d6ab9d640d1

I clicked on the link for that website from an email in Gmail from Malwarebytes:

![2593120d-26c1-4ef4-b41c-50916a9db731 png](https://user-images.githubusercontent.com/46236743/53123664-2e62dc80-351f-11e9-8d91-7c559af5e549.jpg)

Thank you,
-John Jr

**Comment by zoracon** [comment]
This issue may be addressed by "Allow in incognito" setting in Chrome. If still persistent I can always open it back up.

**Comment by Michael82548** [comment]
@zoracon This issue is still present even when enabling "Allow in incognito/Allow in Private" on Chrome/Chromium. You would not be able to use this extension at all in incognito/private if this setting is disabled.

I have been affected by this for years and its very annoying. I have to manually add it to exclusions in the extension settings. Not very user friendly

Once I add the URL to the exclusion list manually, the issue is temporarily resolved for that specific website.

Requesting for issue to be re-opened

**Comment by preall** [comment]
@zoracon It does not work that way.
If we are seeing this error, it means we've already enabled the "Allow in incognito" option.

See the following from the [Chrome Developers Manifest Documentation - Incognito](https://developer.chrome.com/docs/extensions/mv3/manifest/incognito/):
> Because incognito tabs cannot use this shared process, an extension using the "spanning" incognito mode will not be able to load pages from its extension package into the main frame of an incognito tab.

> As a rule of thumb, if your extension needs to load a tab in an incognito browser, use split incognito behavior. If your extension needs to be logged into a remote server use spanning incognito behavior.

So this issue must be re-opened as it isn't fixed and HTTPS Everywhere should start using the "split" incognito mode.

**Comment by zoracon** [comment]
> So this issue must be re-opened as it isn't fixed and HTTPS Everywhere should start using the "split" incognito mode.

It looks like I missed the origin of the issue in my review of old issues. I will take a look at this again and make a decision. Apparently Firefox does not support "split". But I am less worried about Firefox these days since they do have a native HTTPS Only mode now.

**Comment by zoracon** [comment]
Since we manipulate the `manifest.json` file anyway upon build, I remove the key for Firefox since default behavior is "spanning" and made sure to leave for the Chrome package as "split". I am hoping this solution suffices. Undergoing tests now.

**Comment by zoracon** [comment]
This fix has been deployed in yesterday's release. Closing and if issues persist let us know.
