### ISSUE TITLE
Warn users about insecure links on search engines

### ISSUE THREAD

**Issue by bcyphers** [EFForg/https-everywhere#16417]
Type: feature request

Following up on a conversation we had in-person earlier. It would be nice if HTTPS Everywhere could warn users about insecure links on search engines that can't be upgraded. For example, we could do something like the following:

![httpse link styling demo](https://user-images.githubusercontent.com/4840035/44705920-da39dc80-aa54-11e8-83c4-21231d555e3f.PNG)

Opening this issue for discussion: 
* Should this happen in HTTP nowhere mode, or all the time?

* We talked about checking, on the fly, whether http:// links can be upgraded. Is it OK to make the number of requests that would be required to check each link on a page full of them? Is there another way to do it (on hover, maybe, or after some kind of dialog)?

* What's the right styling to do? Red text plus tooltip on hover? Strikethrough? Should we remove insecure links altogether in HTTP Nowhere mode?

* Where should we do this? It's probably too dangerous to modify `a`'s everywhere, but we could start by covering the major search engines (e.g. Google, Bing, DDG, Disconnect). 

Related to #14895.

@Hainish @jsha @sydneyli

**Comment by tobiaalberti** [comment]
Would this feature need to be built separately for each major search engine?
If yes: Which search engines would you consider supporting?

Should this be done with search engines' search results alone, or for any page that contains any sort of unsecure link?

**Comment by l0b0** [comment]
I've written a simple [Firefox plugin](https://addons.mozilla.org/en-US/firefox/addon/insecure-links-highlighter/) to do this.
