### ISSUE TITLE
abc.go.com - Unable to authenticate with cable provider

### ISSUE THREAD

**Issue by garyploski** [EFForg/https-everywhere#1641]
The following needed to be unchecked to be able to click on the cable providers to be able to authenticate to watch content on abc.go.com. If it is left selected the providers are shown on the screen and clicking any of them does nothing. With it unselected I was able to click my provider.

![screen shot 2015-05-06 at 6 07 17 am](https://cloud.githubusercontent.com/assets/4456404/7493518/6d808bd2-f3b6-11e4-804f-6965455fb955.png)

**Comment by reedy** [comment]
The Kaltura rule?

Do you see any errors in your JS console?

**Comment by garyploski** [comment]
Yes. I un-clicked Kaltura and after a refresh was able to click on the authentication options (images of cable providers).

I'm sorry to say I didn't look to see if there were errors in the JS console so I just tested with the most recent episode of Grey's Anatomy. Here is a screen shot... 
![screen shot 2015-05-07 at 12 27 36 pm](https://cloud.githubusercontent.com/assets/4456404/7524143/d82ffedc-f4b4-11e4-9c5b-4ddd93a83810.png)

Also attached is an animated gif of a reload and multiple clicks on the cable providers...
![https](https://cloud.githubusercontent.com/assets/4456404/7524124/bdd31c40-f4b4-11e4-83eb-bead5cfa92d2.gif)
