### ISSUE TITLE
CNN.com article pages load, then go blank and hang partway through a reload

### ISSUE THREAD

**Issue by DanHarkless** [EFForg/https-everywhere#16447]
Type: ruleset issue
Domain: cnn.com

On URLs such as http://www.cnn.com/2009/HEALTH/08/14/cocaine.traces.money/index.html, Firefox will load the page, display it briefly, then suddenly go blank and auto-reload the page, hanging (seemingly permanently) partway through the reload, with the page still blank.  Disabling the "CNN.com (partial)" ruleset works around the problem ("IMR Worldwide.com" can be left on).  I also use uBlock Origin, but I confirmed the problem still occurs with it disabled.

Interestingly, if you manually change the URL to use https, the site redirects back to http (surprising in this day and age), so it would seem the hang is a non-detected redirect loop.

**Comment by Bisaloo** [comment]
Thank you for your report. I can reproduce on Firefox but not on Chromium.

Strangely, if I visit other pages on `edition.cnn.com` and then go back to the page you linked, everything works fine...

**Comment by pipboy96** [comment]
Also can reproduce.

**Comment by pipboy96** [comment]
High priority due to high-traffic website being affected.
