### ISSUE TITLE
https not enforced on redirect

### ISSUE THREAD

**Issue by azsr** [EFForg/https-everywhere#16463]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
[//]: #
[//]: # (If you are submitting a new ruleset, please check the list at)
[//]: # (https://www.eff.org/https-everywhere/atlas/index.html and the open)
[//]: # (issues and pull requests to make sure it doesn't already exist.)

Type: code issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: osmose.openstreetmap.fr

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

(This seems more like a basic code issue than a domain-specific issue, although I have only found one instance of this.)

When I manually input https://osmose.openstreetmap.fr , it automatically redirects me to osmose.openstreetmap.fr/en/map/ , **without** the https:// out front. While this could be fixed by adding osmose.openstreetmap.fr to the openstreetmap.fr ruleset, it would be nicer if this apparent code issue were fixed.

**Comment by franklinyu** [comment]
https://github.com/EFForg/https-everywhere/blob/718867698b7402f18d4a17da29d4efd1836b625a/src/chrome/content/rules/Openstreetmap.fr.xml#L18

The domain is *not* covered.

**Comment by azsr** [comment]
@franklinyu Yes, I know that the domain is not covered. Not that I've had a day to think about it, I feel like this is more of a feature request. What I feel like should happen is that if I manually type in "https://" in front of a domain, HTTPS Everywhere should try to keep the https:// through redirects, even if the domain is not on the list.

Also, osmose.openstreetmap.fr does work on https and does not return a 404 error, at least for me. 
https://imgur.com/a/otGcIbM

**Comment by franklinyu** [comment]
I did some research and found that the ruleset is created in #4145. You may want to discuss with @rugk to see what happened back then.

**Comment by Bisaloo** [comment]
> What I feel like should happen is that if I manually type in "https://" in front of a domain, HTTPS Everywhere should try to keep the https:// through redirects, even if the domain is not on the list.

It is not uncommon for the same domain to have pages to support HTTPS and some that don't. Implementing this behaviour would likely break a lot of pages.

**Comment by rugk** [comment]
Ah, hi here.
I guess the redirect to HTTP is bad and should be reported to OpenStreetMap.

So here you go: https://github.com/openstreetmap/operations/issues/241

As for: 
> to see what happened back then.

Well… no idea. :smile: 
But [according to the PR](https://github.com/EFForg/https-everywhere/pull/4145/files#diff-36e5a245913cd1c4b75b6d036a28cdedR12 – "404/wrong content") it just showed a  error or shower

**Comment by pipboy96** [comment]
Look into EASE mode if you want to prevent websites from redirecting back to HTTP.

**Comment by pipboy96** [comment]
This particular URL seems to be rewritten in the current extension/rulesets version by the way.
