### ISSUE TITLE
Request to optimize performance

### ISSUE THREAD

**Issue by redbrain1014** [EFForg/https-everywhere#16475]
`Type: feature request`

Recently, my friend complained about the Chrome extension because 

> "It lagged when I visited a site, so I just removed [the extension.]"

I realized that no one would make their computer secure this way if they had to sacrifice their *performance*.

I created this issue, to reference some other old issues (and pull requests) that would be good to continue to work on so more people will continue to use this extension.
**Issues** #11203 #12232 #4369 #1998
[Pull request 4110](https://github.com/EFForg/https-everywhere/pull/4110)

**Comment by Bisaloo** [comment]
I am inclined to close this as a duplicate of #12232. #12232 also lists clear solutions to improve memory usage and performance.

Can you justify why you think this issue is different than #12232?

**Comment by redbrain1014** [comment]
Anyone want to help?

**Comment by Hainish** [comment]
Thanks @redbrain1014 - closing this issue as a duplicate.
