### ISSUE TITLE
"Block all unencrypted requests" per site switch

### ISSUE THREAD

**Issue by TheFinalCut83** [EFForg/https-everywhere#16508]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
[//]: #
[//]: # (If you are submitting a new ruleset, please check the list at)
[//]: # (https://www.eff.org/https-everywhere/atlas/index.html and the open)
[//]: # (issues and pull requests to make sure it doesn't already exist.)

Type: feature request

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Is it possible to add a per site switch to the "block all unencrypted requests" feature and also add an auto-reload for it similar to the one that already have rulesets?

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by Hainish** [comment]
Thanks @TheFinalCut83.  This is an oft-requested enough feature that I'm inclined to prioritize this.

**Comment by TheFinalCut83** [comment]
Thanks for the answer!

**Comment by Hainish** [comment]
I think this can be neatly folded into the more general settting "Disable HTTPS Everywhere on this site" as per https://github.com/EFForg/https-everywhere/issues/10041.
