### ISSUE TITLE
https://https-rulesets.org use a mismatched certificate

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#16507]
Type: other

Domain: https-rulesets.org

Given the domain `301` redirect from `http` to `https`, I believe that a valid certificate should be used.

```bash
$ curl -I https-rulesets.org
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 07 Sep 2018 04:51:14 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://https-rulesets.org/
```

Besides, `^` should ideally redirect to `www` but instead it gives an empty response.  

```
$ curl -Ik https://https-rulesets.org
curl: (52) Empty reply from server
```

**Comment by cschanaj** [comment]
@Hainish RT, is this intentional?

**Comment by Hainish** [comment]
@cschanaj we only use the `www` subdomain but I agree, we should ensure the TLD+1 has a valid certificate as well.

**Comment by Hainish** [comment]
Thanks @starchy, looks good to me now!
