### ISSUE TITLE
&quot; - in warning unencrypted website

### ISSUE THREAD

**Issue by tscpd** [EFForg/https-everywhere#16513]
Type: other

New warning by opening NON-HTTPS website with activated "block unencrypted websites" option has someme html code in it (german) &quot; 
&quot;Alle unverschlüsselten Anforderungen blockieren&quot; 
![https-everywhere-quot](https://user-images.githubusercontent.com/26028013/45311075-58ec4a80-b528-11e8-8915-f21be2b7a981.png)

**Comment by Hainish** [comment]
Oh that's interesting.  I think we can create a fix for this in the build process.
