### ISSUE TITLE
HTTPS Everywhere not downloading in CWS

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#16532]
Type: other

HTTPS Everywhere is currently not downloading in the Chrome Web Store.  We are working with the CWS to resolve the issue.  Screenshot attached.
![httpse](https://user-images.githubusercontent.com/156137/45506149-46019200-b743-11e8-8790-c0a4c75e2e34.png)

**Comment by Macley-Kun** [comment]
Resolved at my end :-)

**Comment by Hainish** [comment]
Thanks - Chrome has resolved the immediate issue but there are still underlying issues that need to be resolved.  Keeping this open for now.

**Comment by Hainish** [comment]
This issue is resolved as of 2018.9.19.
