### ISSUE TITLE
Use IndexedDB instead of WebStorage

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#16551]
Type: code issue

WebStorage uses text files with serialized JSON. It has multiple issues.

1. The file is completely rewritten on any modification. This causes flash burning out on devices using flash memory-based SSD.
2. json escapes special characters, which is inefficient.
3. You have to serialize binary data into base64 which is damn inefficient.

The better approach is to use IndexedDB which allows storage of binary data and also has DB capabilities, which can be used for incremental updates.

I guess some compression support is also needed, maybe some modification to FF allowing to use compressed SQLite files.

**Comment by Bisaloo** [comment]
From what I understand, this change will be automatic with FF 56. Is that correct?

https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/

**Comment by KOLANICH** [comment]
I don't think so. DB is more than just a key-value storage.

**Comment by cschanaj** [comment]
> From what I understand, this change will be automatic with FF 56. Is that correct?
> 
> https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/

My understanding is that the change should be automatic from FF 66, but storage waste with JSON escape and base64 encoding will remain to be solve on the extension side.
