### ISSUE TITLE
Cannot manually update my update channel in Tor Browser

### ISSUE THREAD

**Issue by pastly** [EFForg/https-everywhere#16673]
Type: other

@Hainish 

When I add my update channel in about:addons and click the "update" button on my update channel, HTTPS Everywhere never manages to fetch the new ruleset.

However, if I edit background-scripts/update.js to update in the background every 10 seconds, one of those auto updates is able to fetch the ruleset.

**Comment by Hainish** [comment]
This is due to a race condition when the update button is clicked.  The new keys are loaded at the same time an update attempt is performed.  This doesn't give time for the keys to finish loading, and thus the update fails.
