### ISSUE TITLE
pem-jwk and dependency on nodejs can be replaced with a short python script

### ISSUE THREAD

**Issue by pastly** [EFForg/https-everywhere#16671]
Type: other

... and a python package not in Debian.

After `pip install pyjwkest` (possibly in a virtual environment), the following script can replace the need for npm/nodejs in [this section on making an update channel](https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/ruleset-update-channels.md#1-creating-an-rsa-key-and-generating-a-jwk-object-from-it)

```
#!/usr/bin/env python3
from jwkest.jwk import RSAKey
print(RSAKey().load('/dev/stdin'))
```

I realize this is essentially replacing a dependency with a different dependency.

**Comment by Bisaloo** [comment]
I'm not sure what the current view on this is but it would go against #9993.

**Comment by pipboy96** [comment]
We are currently rewriting everything in Node.
