### ISSUE TITLE
"Open with Tor Browser" option when visiting usecured pages

### ISSUE THREAD

**Issue by tobiaalberti** [EFForg/https-everywhere#16697]
Type: feature request

Since I've enabled the _Block all unencrypted requests_ feature on my main web browser I've been trying to come up with a way to keep visiting webpages that are only available over unsecured connections in a manner that would also (at least to some extent) protect my privacy.

The best way I found so far is to open unsecured pages that I really want to visit using the _Tor Browser_.
This means that when _HTTPS Everywhere_ fails to force an HTTPS connection, I copy the URL, get rid of the "s" from HTTPS, paste it into the _Tor Browser_, and go. This has been working pretty well for me.

Now I would like to suggest doing something similar to other people, regular people. People that wouldn't find copy/pasting and removing an extra "s" a very easy thing to do. So I thought that maybe a new feature could come out of this...

What I'm thinking about is an _Open with Tor Browser_ button. This button would appear on the page that pops up when _HTTPS Everywhere_ fails to redirect to the secure version of a page and would allow people to open the page in the _Tor Browser_ without having to copy/paste the URL and removing the "s" from it.

Is this feasible?
If yes: Does it make sense to you?

**Comment by Atavic** [comment]
It is done at browser level, not into a webextension. Something like:
https://github.com/darktrojan/openwith
...may help.

**Comment by Giltyhub** [comment]
opening insecure page with a different browser is still insecure, unlike with this for example https://github.com/EFForg/https-everywhere/pull/16702

**Comment by pipboy96** [comment]
Extensions are not capable of working external apps in such manner, security benefit is extremely unclear. Closing.
