### ISSUE TITLE
habrahabr.ru broken

### ISSUE THREAD

**Issue by powerman** [EFForg/https-everywhere#1669]
It opens in http and font-icons doesn't work (in left side panel and comment form).
Disabling "Habrahabr.ru (partial)" rule will "fix" this issue.

At same time similar Geektimes.ru with much simpler rules works ok, so probably it makes sense to remove outdated complexity and workarounds from Habrahabr.ru.xml.
Also it looks like 3rd similar site should be added: megamozg.ru.

**Comment by reedy** [comment]
Some sites do have bad rules, but some sites also are just setup badly. Some need complex rules, some don't

```
Font from origin 'https://habrahabr.ru' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://habrahabr.ru' is therefore not allowed access.
```


Please open a seperate requests for new site(s)

**Comment by powerman** [comment]
I don't get it. Fonts are loaded using relative url in css file. css file is loaded from same domain (habrahabr.ru). Everything is loaded in standard way by browser with GET requests, without XHR and non-standard headers. How these requests may be blocked because of CORS?

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
