### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by Reeder960** [EFForg/https-everywhere#1674]
One day 95% of the songs I tried to load on Google's music service wouldn't stream the loading arrow would just keep spinning. I had this problem for a week before I started to debug the issue. When I disabled the https-everywhere plugin it started working again. I can't live without my music!

**Comment by semenko** [comment]
Working for me now.

Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
