### ISSUE TITLE
Chrome Feature Parity

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1681]
I thought there was an issue for this, but couldn't find it when looking... Are we ever going to get feature  parity in Chrome vs FF? :)

**Comment by jsha** [comment]
Want to break out the specific feature differences here so we can start prioritizing? There are some features, like SSL Observatory, that may never be possible on Chrome, but I definitely would like to bring them to feature parity (and similar UI!).

**Comment by reedy** [comment]
Yup, I can do. Keep this as a semi tracking ticket for the whole lot?

I wonder if for stuff like the SSL Observatory we could upstream it to Google/Chromium? Are these likely to be WONTFIX then upstream?

**Comment by jsha** [comment]
I'm not *positive* SSL O would be WONTFIX in Chromium. Historically that team has been very against any extension change the HTTPS trust mechanics, but I think has been tentatively open to letting extensions read certificate data about pages (but not modify).

**Comment by zmanian** [comment]
My impression is that various architectural decisions have made SSL
observatory capability in the Chrome APIs complex to implement.

Documented here:
https://code.google.com/p/chromium/issues/detail?id=107793

**Comment by reedy** [comment]
Annoying, but not a big deal. Thanks for the info!

**Comment by reedy** [comment]
Just trying to think what other differences there are...

**Comment by Mikaela** [comment]
Will this change with the Firefox Web Extensions API? From what I understood they are going to deprecate the current API and then move to WebExtensions API which is compatible with Chrome with minimal changes.

Or does it remove SSL Observatory also from Firefox? If it's coming, will it also have the option to use Tor?

* [Mozilla Add-ons blog: The Future of Developing Firefox Add-ons](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/)

**Comment by gloomy-ghost** [comment]
Now we use the same codebase for Chrome and Firefox.
