### ISSUE TITLE
Decide on future of HTTPS Everywhere Preferences window

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1683]
The "Enable / Disable Rules" aka the HTTPS Everywhere Preferences window should be added to Chrome, along with the dependant view xml source windows.

Subtask of #1681

**Comment by jsha** [comment]
BTW, I would actually be excited about *removing* this window from Firefox to reach parity. I think it is used very seldom, and the dropdown checkboxes serve 95% of the use cases it serves. Interested to hear your thoughts on the matter though.

**Comment by jsha** [comment]
The other things we have in that window are `Reset to defaults` (could be moved to dropdown) and `Disable all` (superseded by `Disable HTTPS Everywhere` in the menu, should probably be removed.

**Comment by reedy** [comment]
I'd be up for that, yeah. It has some use for a layman to see "what's supported", I think, Some way of getting from from the ruleset (a hyperlink) to viewing the ruleset in a web browser tab (#1436 or similar) would be useful.
