### ISSUE TITLE
Breaks congstar.de login page

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1686]
Per tweet: https://twitter.com/MarcGLib/status/596041523956953091

**Comment by alex42ka** [comment]
Can confirm this.

**Comment by J0WI** [comment]
Can't see any failures on https://www.congstar.de/meincongstar
Do I need a valid account to reproduce?

**Comment by orrc** [comment]
Hmm, I can reproduce it with my account, but it's a weird one.

What should happen:
* Log in at https://www.congstar.de/meincongstar/
* You are redirected to https://www.congstar.de/meincongstar/?authUserSuccess=1 where your account details are shown
* You can refresh this page or visit https://www.congstar.de/meincongstar/ again — it's all the same: you remain logged in and see your account details

What happens with HTTPS Everywhere, **90% of the time**:
* Log in at https://www.congstar.de/meincongstar/
* You are redirected to https://www.congstar.de/meincongstar/?authUserSuccess=1 **but the login form is shown again**
* Refreshing doesn't help; you just see the login form again

The other 10% of attempts, it works as it should.
Disabling the "congstar" rule makes it work 100% of the time.

Sorry I don't have more time to dig in further at the moment, but let me know if I can provide any more info.

**Comment by jeremyn** [comment]
Is this problem still active for anyone?

**Comment by orrc** [comment]
Just tried logging in and out three times, and had no problems.

**Comment by jeremyn** [comment]
@orrc Thanks for checking.

I'm closing the issue, but if anyone here is still having a problem logging in with HTTPS Everywhere enabled, please feel free to reopen the issue with a comment.
