### ISSUE TITLE
Breaks getpocket.com Firefox toolbar button

### ISSUE THREAD

**Issue by kvibber** [EFForg/https-everywhere#1693]
The current rule for getpocket.com causes Pocket's Firefox extension (toolbar and right-click menu item) to fail and log the user out of the service.

Otherwise the website seems to work normally, and pages can be added manually on the site.

**Comment by reedy** [comment]
Do you see any relevant console errors?

**Comment by kvibber** [comment]
I checked out the console and found that the Pocket add-on is sending a GET request to http://getpocket.com/ext_save.php, with or without the httpse ruleset enabled.  When the ruleset is turned off, the server is responding with a 200 OK. When it's turned on, the server is responding with a 302 redirect.  Comparing the request headers, the successful request has a bunch of session cookies, while the failing request doesn't. That explains the failure to post. And the server response explicitly deletes the cookies, explaining why it's logged out.

So in short:
1. The add-on is still contacting http://getpocket.com/ext_save.php even with the ruleset turned on.
2. Because httpse has forced all the login cookies to be secure only, the server doesn't see them and treats it as an invalid session.
3. The server then wipes the site's cookies to set a clean slate for login, logging the user out of the website.

If I visit http://getpocket.com/ext_save.php directly in a browser tab, it's getting rewritten to use https, and the console only shows the https GET (which doesn't do anything without parameters, but  responds with a 200 OK and doesn't log me out). So the ruleset seems to be mapping correctly. Maybe HTTPSE can't intercept calls generated from other add-ons, or from the "Services" class of add-ons?

This is with Firefox 38.0 and the Pocket 1.2 add-on found at the top of https://getpocket.com/add/ when viewed with Firefox.

**Comment by mythness2** [comment]
The problem does not seem to exist anymore when using Firefox 39.0 (beta), which has the Pocket service integrated (no installed add-on or service, since it it built in). I tested this issue on Firefox 39.0 (beta) with HTTPS Everywhere 5.0.5, and everything seems to work smoothly. Can anyone else verify this?

**Comment by kvibber** [comment]
Seems to work OK in Firefox 39 release here too. Thanks.

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
