### ISSUE TITLE
Nerdist videos break with Brightcove enabled

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#1694]
Link:
http://nerdist.com/exclusive-ingrid-michaelson-covers-radioheads-creep-on-the-nerdist-podcast/

**Comment by reedy** [comment]
Same as #1618, just for a different site it would seem

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
