### ISSUE TITLE
Travis CI not triggered by PRs

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#16950]
Type: other

Travis CI is no longer triggered by PRs.

@Hainish could you have a look please?

**Comment by J0WI** [comment]
Actually the checks run in background, but the API to expose the results is somehow broken.

**Comment by Hainish** [comment]
@J0WI I'll take a look at this tomorrow.

I've noticed a lot of new issues for sites that don't yet have rulesets.  Are you finding these issues useful, or should I encourage users who are automating these issue creations to stop?

**Comment by J0WI** [comment]
If the issue creation is automated it's not very helpful. Or is the bot open source, so that we can see the criteria (might be interesting to also auto generate rulesets)?
For manual created issues we know at least, that someone noticed that the site actually works over HTTPS.

**Comment by J0WI** [comment]
@Hainish did you already found something about the Travis issue?

**Comment by Hainish** [comment]
I've switched Travis from being a project service to GitHub app, and re-enabled the integration on the Travis CI side.  It looks like it's working now, but I think you'll have to close and re-open PRs in order to initiate the CI in existing PRs.
