### ISSUE TITLE
http://fuckyouverymuch.dk/ does not load pictures

### ISSUE THREAD

**Issue by Niflheim123** [EFForg/https-everywhere#1696]
http://fuckyouverymuch.dk/
its a blog and the pictures are not loaded because of https everywhere

**Comment by reedy** [comment]
WFM on Chrome...

**Comment by Niflheim123** [comment]
sorry, forgot to mention 
firefox 37.0.2
8164
https everywhere 4.0.1

**Comment by reedy** [comment]
Stable release of HTTPSE on FF is 5.0.4. Can you upgrade to the current stable release and try again please?

**Comment by Niflheim123** [comment]
works now :) thank you
