### ISSUE TITLE
Add new ruleset for eldarya.com

### ISSUE THREAD

**Issue by NatoBoram** [EFForg/https-everywhere#16974]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
[//]: #
[//]: # (If you are submitting a new ruleset, please check the list at)
[//]: # (https://www.eff.org/https-everywhere/atlas/index.html and the open)
[//]: # (issues and pull requests to make sure it doesn't already exist.)

Type: new ruleset

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: eldarya.com.br
Domain: eldarya.de
Domain: eldarya.es
Domain: eldarya.hu
Domain: eldarya.it
Domain: eldarya.pl
Domain: eldarya.ru
Domain: eldarya.com
Domain: eldarya.fr
Domain: www.eldarya.com.br
Domain: www.eldarya.de
Domain: www.eldarya.es
Domain: www.eldarya.hu
Domain: www.eldarya.it
Domain: www.eldarya.pl
Domain: www.eldarya.ru
Domain: www.eldarya.com
Domain: www.eldarya.fr

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

It's all the same website, but translated. The transition is recent, it happened this week. The website has a hard time choosing between the www and non-www version, so let's just HTTPS them all.

**Comment by NatoBoram** [comment]
Patch : [0001-Add-Eldarya-and-all-its-websites.zip](https://github.com/EFForg/https-everywhere/files/2504405/0001-Add-Eldarya-and-all-its-websites.zip)

**Comment by J0WI** [comment]
Please provide patches as Pull Request.

**Comment by NatoBoram** [comment]
I can't even build it without the patch, so I'll just let someone with a working environment do it.

**Comment by J0WI** [comment]
It's not required to build it locally, you can also just open a PR and look for the tests run by Travis.

**Comment by NatoBoram** [comment]
There's a Git hook attached to pushes, I think it runs a bunch of tests before allowing a push. I'm not too familiar with that, but it seems like I fail the test so I can't push at all. Is there a way to ignore hooks and tests so I can push and see if Travis can make something out of it?

**Comment by J0WI** [comment]
I assume that you executed the `install-dev-dependencies.sh`?
So you can simply remove the `.git/hooks/pre-push` symlink t disable the hook.
