### ISSUE TITLE
Add new ruleset for cz-usa.com

### ISSUE THREAD

**Issue by TotalCaesar659** [EFForg/https-everywhere#16970]
Type: new ruleset
Domain: http://cz-usa.com/

**Comment by Hainish** [comment]
@TotalCaesar659 automated submission of issues for ruleset isn't terribly useful for our ruleset maintainers.  See https://github.com/EFForg/https-everywhere/issues/16950#issuecomment-431926552

Please stop automated submission for these rulesets.

**Comment by Hainish** [comment]
cc @J0WI

**Comment by Hainish** [comment]
Closing issues of this type, see https://github.com/EFForg/https-everywhere/issues/16984
