### ISSUE TITLE
Remove "menu triangle" from Firefox toolbar button?

### ISSUE THREAD

**Issue by ghostwords** [EFForg/https-everywhere#1697]
Is there a purpose to the triangle on HTTPS Everywhere's Firefox toolbar button?

In the screenshot below, I am hovering over Pinboard's toolbar button, which also has a triangle. Clicking the triangle produces a menu, while clicking the rest of the button does something else. However, HTTPS Everywhere's button performs the same action regardless of where you click. (Hovering over the button never "pops" the triangle, although the triangle area is clickable.)

![screenshot from 2015-05-14 09 49 23](https://cloud.githubusercontent.com/assets/794578/7632974/442aa0dc-fa1f-11e4-81fe-54d6f2dc4384.png)

If the triangle is w/o purpose, I suggest removing it, as it is misleading + needlessly takes up space.

**Comment by reedy** [comment]
WFM

**Comment by jsha** [comment]
I'd be fine with this, although I suspect it's something that is automatically added by one of the XUL elements we use, like `menupopup` or `toolbarpalette`. Needs some more research.

**Comment by fuglede** [comment]
One fix to this is proposed in https://github.com/EFForg/https-everywhere/issues/2470#issuecomment-131462213.
