### ISSUE TITLE
Discussion: Automatic tools for Issues/PRs

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#16984]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: other

Cc: @J0WI, @Bisaloo, @zoracon, @cschanaj 

There have been a lot of issues automatically opened on sites that we don't have coverage for, and talking it over with @J0WI this doesn't seem particularly useful for our ruleset maintainers.  I plan on closing these issues, but I wanted to broaden the discussion.  In the past we've discussed what types of tools *would be* helpful for ruleset maintainers, and how we can incorporate those into our submission workflow.  This has resulted in the issue labeller bot, and other ideas.  I'd like to open this up to discussion some more, and see at this point what would be useful.

One idea was the creation of a periodic scan of sites in the Alexa top X, determining via a webdriver where there is no significant difference between the HTTP and HTTPS sites.  This would be disrupted by dynamic content and ads, probably, but we may just install an adblocker to prevent this from messing with our heuristic in the scan.  At that point, if there are sites with no coverage but are forwarding to HTTPS, we can create issues for them.

Just an idea, maybe you all will have others?

**Comment by J0WI** [comment]
+1 for auto generated rules, but a `platform="robot"` will likely never be enabled for a majority of our users. I would like to merge these into "normal" rules somehow.
