### ISSUE TITLE
AdultSwim.com broken

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#1698]
Using Firefox 38.0 on Windows 7 with HTTPSE 5.0.4 the website just gives you a notice and nothing loads.  Disabling the AdultSwim.com rule makes the site work correctly.

**Comment by reedy** [comment]
Looks like mixed content from a CDN mostly

**Comment by semenko** [comment]
Working for me now.

Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
