### ISSUE TITLE
Extended breaks Access To livejournal.com

### ISSUE THREAD

**Issue by va-al** [EFForg/https-everywhere#1699]
For example:
 Then I try to open  http://ellustrator.livejournal.com/816220.html
I've got redirect to http://www.livejournal.com/__setdomsess?dest=https%3A%2F%2Fellustrator.livejournal.com%2F816220.html&k=ljdomsess.ellustrator&v=v1%3Au71350080%3As3%3At1431622800%3Ag8ebc60611d52e9f0b38339e34ed16b6c3de9f5ad%2F%2F1

With error "Page not found"

If extension is switch off, everything work fine.

p.s. Sorry for Google Translate =( Thanks for advance!

**Comment by reedy** [comment]
What browser, browser version and version of HTTPSE?

**Comment by va-al** [comment]
1. Chromium 41.0.2272.76 Built on Ubuntu 14.04, running on LinuxMint 17.1
(64-bit)
2. (Version: 2015.5.12)

2015-05-15 3:46 GMT+03:00 Sam Reed <notifications@github.com>:

**Comment by reedy** [comment]
I see a load of mixed content, but it doesn't redirect for me

**Comment by va-al** [comment]
From what I can see in Developers Tools

First HTTPSE generate 307 Internal Redirect, there is log:

General
Request URL:http://ellustrator.livejournal.com/816220.html
Request Method:GET
Status Code:307 Internal Redirect

Response Headers
Location:https://ellustrator.livejournal.com/816220.html
Non-Authoritative-Reason:Delegate

Request Headers
Provisional headers are shown
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36


Next browser try get https page version:

General
Remote Address:208.93.0.150:443
Request URL:https://ellustrator.livejournal.com/816220.html
Request Method:GET
Status Code:302 Found

Response Headers
view source
Accept-Ranges:bytes
Age:0
Connection:keep-alive
Content-Length:0
Content-Type:text/plain; charset=UTF-8
Date:Fri, 15 May 2015 16:14:51 GMT
Location:http://www.livejournal.com/misc/get_domain_session.bml?return=https%3A%2F%2Fellustrator.livejournal.com%2F816220.html&sign=6fc398442f44912187c640a1adb43963&t=1431706491
Server:nginx
X-AWS-Id:ws50
X-Beta:http://varnish
X-Gateway:bil1-swlb03.prod.livejournal.org
X-Varnish:1408235011
X-VWS-Id:bil1-varn30

Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:ru,en-US;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Cookie:ljident=2869171628.20480.0000; ljuniq=0EsSxieWJAtpNd4%3A1396608730%3Apgstats0; __utma=48425145.1557067309.1396608728.1409917562.1410245338.11; __utmc=48425145; __utmv=48425145.|1=ljuser=TODO%3Aloggedin%2Fanonymous%2Fyou=1; __auc=ecfcc98e149f1ccea2902e1b674; ljloggedin=v2:u71350080:s3:t1417789814:g2a5442e7b8e6cd6377a1d6fa2c161e383126ece7; langpref=ru/1430416719; ljsession=v1:u71350080:s3:t1430413200:g16d422610a7e93431c57d66d1f528d0618282ee0//1; _ga=GA1.2.1557067309.1396608728; xtvrn=$528851$; xtan=2-71350080; xtant=1
DNT:1
Host:ellustrator.livejournal.com
Pragma:no-cache
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36

And then browser get ""Location:http://www.livejournal.com/misc/get_domain_session.bml?return=https%3A%2F%2Fellustrator.livejournal.com%2F816220.html&sign=6fc398442f44912187c640a1adb43963&t=1431706491"" and I see this:

![2015-05-15 19 23 54](https://cloud.githubusercontent.com/assets/3016713/7657102/0a2e15a2-fb38-11e4-9576-ad825580634f.png)


The effect is repeated for every link * .livejournal.com

**Comment by Amarchuk** [comment]
Same bug for me.

Google Chrome version 45.0.2454.7 dev-m on Windows 7 (and I notice that issue-starter and I both from Russia)

**Comment by intari** [comment]
Happens for me to.
Google Chrome	 44.0.2403.125 (64-bit) Mac OS X 
regular chrome build.
I'm from Russia but all http/https traffic goes via european proxy.

**Comment by J0WI** [comment]
I cannot reproduce this anymore. Could somebody confirm?

**Comment by pipboy96** [comment]
I can't either.
