### ISSUE TITLE
sha256sum discrepancies and unclarity regarding versions

### ISSUE THREAD

**Issue by anchev** [EFForg/https-everywhere#17009]
Hi,

The version I download from https://www.eff.org/files/https-everywhere-chrome-2018.10.31.crx has a checksum:
```
[/tmp/download]: sha256sum https-everywhere-chrome-2018.10.31.crx
06ac18beae0ad1e52be1fad017942da148ff8b24652d4dc9d4b0deb4feb5b5a6  https-everywhere-chrome-2018.10.31.crx
```
The versions which I build using `bash make.sh` show different checksums:
```
[/tmp/download/https-everywhere-2018.10.31]: bash make.sh
Building version 2018.10.31
 * Parsing XML ruleset and constructing JSON library...
 * Writing JSON library to src/chrome/content/rules/default.rulesets
 * Everything is okay.
/opt/ungoogled-chromium/chromium-browser
CWS crx package has sha256sum: c8095f02a8d8df7ac05e305cdd33f5a369612627b8abdf18fe7f3df837d4f599
EFF crx package has sha256sum: 10c9a3f2f46efaad37a82df737c9e7015d74567497eabd98ecd58ae92fa7ebc4
AMO xpi package has sha256sum: e1a487a473397dc119ae0ef134a0d954ad984fccccfac0cb92bd3e66079f1145
EFF xpi package has sha256sum: c2a80f81228d52d184ae7759f79662fd2d0de52c5dbd4c6bbdf2d4ed713fa338
Total included rules: 24411
Rules disabled by default: 5479
Created pkg/https-everywhere-2018.10.31~pre-amo.xpi
Created pkg/https-everywhere-2018.10.31~pre-eff.xpi
Created pkg/https-everywhere-2018.10.31~pre-cws.crx
Created pkg/https-everywhere-2018.10.31~pre-eff.crx
```
Additionally from the `README.md` it is not clear which crx package to use (cws or eff) and what is the difference between the two.

Can someone clarify all this please?

**Comment by Hainish** [comment]
Hey @anchev,

The current Chrome releases are not reproducible, unfortunately.  This is because in the move from CRX2 to CRX3, Chrome has enforced the use of the `chromium` (or `google-chrome`)  binary to do releases.  Unlike before, creating a CRX3 release in this way is not reproducible unfortunately.

Thanks for reaching out!

**Comment by anchev** [comment]
Thanks for explaining. Could you please also answer the second part?

> it is not clear which crx package to use (cws or eff) and what is the difference between the two.

**Comment by Hainish** [comment]
@anchev the only difference between the two packages is that one is uploaded to Chrome Web Store (thus the `cws`) and the other is uploaded to Opera browsers extension store, as well as our own website if the user wishes to install the extension manually (the `eff` one).

**Comment by Hainish** [comment]
The `cws` version specifically lists that it will update from Chrome Web Store, the other leaves the update URL unspecified.  Unspecified update URLs are usually defaulted to some specific URL that is defined by the browser itself, and points at that browsers' extension update channel.

**Comment by Hainish** [comment]
Best for that is probably the `eff` version.
