### ISSUE TITLE
forums.fanboy.co.nz uses an invalid security certificate

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#1701]
```
forums.fanboy.co.nz uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
The certificate is only valid for webhost13.inspire.net.nz 
```

There's another problem. It uses HSTS, so once it's loaded over HTTPS, it's going to always try that:

```
Strict-Transport-Security: "max-age=15552000; includeSubDomains"
```

**Edit:** That page apparently only says "Forums are no longer accessible, for any issues submit to http://forums.lanik.us/", so maybe it's not such a big deal. `fanboy.co.nz` itself works over HTTPS.

**Comment by reedy** [comment]
I've not looked at the ruleset, but we should at least update it to stop securing that host, and possibly rewrite it to the lanik.us host?

**Comment by jeremyn** [comment]
`forums.fanboy.co.nz` is gone from DNS. Closing issue.
