### ISSUE TITLE
Possible Issue on Steam's Store

### ISSUE THREAD

**Issue by zauberparacelsus** [EFForg/https-everywhere#1702]
I've found an issue with the steam store, which I first noticed yesterday (and I note that it was yesterday, may 13th, that HTTPS Everywhere last updated).  I don't know if this issue is with Steam or with HTTPS Everywhere, so I've reported in both places.

Here are the repro steps:
1) go to https://store.steampowered.com/
2) At the blue row of buttons near the top under "Browse by Genre" click any of the tags under the Games menu.
3) Do any of the following: change the Sort By method, narrow selection by one of the tags at the left, or try to go to page 2.

What I am seeing is that all the games get faded out and then nothing further happens. The games don't get sorted, narrowed by tag, and the next page doesn't load. This portion of the website simply refuses to do anything beyond displaying the first page of results.   If the page is loaded over HTTP (with HTTPS Everywhere disabled, of course) then the problem vanishes.

**Comment by reedy** [comment]
Possibly related to #1453

**Comment by reedy** [comment]
Closing issue as steam rulesets disabled in 726b2e7799f1afa84174aa2628b2225e33ab6722
