### ISSUE TITLE
option to use archives/caches etc to workaround lack of https

### ISSUE THREAD

**Issue by pabs3** [EFForg/https-everywhere#17036]
Type: feature request

For sites that do not have https support, the "Block all unencrypted requests" option could automatically direct to one of the many websites that archive or cache the web, since most of these support https. Some of the archive websites also support on-demand archiving (such as archive.org and archive.is), which could be used when the site is not yet archived.

This WebExtension contains a list of such archive/cache services:

https://github.com/dessant/view-page-archive

**Comment by Bisaloo** [comment]
Hi, thanks for reaching out! This is currently being discussed in https://github.com/EFForg/https-everywhere/pull/16702.

**Comment by Hainish** [comment]
Closing as duplicate.  Thanks for the suggestion.
