### ISSUE TITLE
Allow certain 40x responses when testing rulesets

### ISSUE THREAD

**Issue by fghzxm** [EFForg/https-everywhere#17064]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The ruleset tester only accepts a target host if an HTTPS request to the host is responded with HTTP 20x.  It may be a good idea to accept HTTP 401, 403 and like as well.

For example, websites like `demos.igalia.com` require HTTP authentication for access.  Such hosts are currently rejected by the ruleset tester because they respond with HTTP 401 rather than 20x.

However, in reality users of those websites will submit credentials and be able to browse them.  Due to the nature of such websites it is even more important to have proactive HTTPS protection for them than for publicly accessible websites.

**Comment by saschanaz** [comment]
ad.dmm.com requires exact path for ads or it returns 403.
