### ISSUE TITLE
Khronos.org man pages hang with HTTPS-Everywhere

### ISSUE THREAD

**Issue by Dark-Photon** [EFForg/https-everywhere#17075]
(First time problem reporter, so I hope I'm doing this right.)

Whenever I try to bring up a man page on the khronos.org web site with HTTPS-Everywhere enabled, the request just hangs.   However, when I disable HTTPS-Everywhere, restart the browser, and retry, then the request completes immediately.

Here's a sample URL that hangs with HTTPS-Everywhere:

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml

This is with HTTPS-Everywhere ver 2018.10.31 (in Firefox 60.3.0esr).

Thanks for reviewing this.

**Comment by Bisaloo** [comment]
Thank you for you report! Unfortunately, I can't reproduce this issue. The URL you provided works fine for me, even with HTTPS-Everywhere enabled.

Could you try in a fresh Firefox profile where HTTPS-Everywhere is the only installed extension?

**Comment by pipboy96** [comment]
Can't reproduce.
