### ISSUE TITLE
Add new ruleset for Gamer Network's websites

### ISSUE THREAD

**Issue by domebacsi** [EFForg/https-everywhere#17082]
Type: new ruleset
Domain: http://nintendolife.com
Domain: http://www.pushsquare.com

**Comment by RemakingEden** [comment]
@Bisaloo @zoracon I have a slight issue with this ruleset.I have check all subdomains with http to https and they all redirect back to http. There is no way to get them to resolve as https without forcing it in the extension.

It seems that https works when logging in etc but that appears to be pre loaded hsts.

What would you recommend to do in this case?

**Comment by zoracon** [comment]
> @Bisaloo @zoracon I have a slight issue with this ruleset.I have check all subdomains with http to https and they all redirect back to http. There is no way to get them to resolve as https without forcing it in the extension.
> 
> It seems that https works when logging in etc but that appears to be pre loaded hsts.
> 
> What would you recommend to do in this case?

Are you talking about both domains or just one of them?

**Comment by RemakingEden** [comment]
> > @Bisaloo @zoracon I have a slight issue with this ruleset.I have check all subdomains with http to https and they all redirect back to http. There is no way to get them to resolve as https without forcing it in the extension.
> > It seems that https works when logging in etc but that appears to be pre loaded hsts.
> > What would you recommend to do in this case?
> 
> Are you talking about both domains or just one of them?

I have only looked into Nintendolife in detail right now. but from a quick look it seems to be the same on pushsquare.

**Comment by zoracon** [comment]
> > > @Bisaloo @zoracon I have a slight issue with this ruleset.I have check all subdomains with http to https and they all redirect back to http. There is no way to get them to resolve as https without forcing it in the extension.

If I understand correctly, there are problematic domains that aren't configured to go to HTTPS.

If that is the case, then just list in the comments above the ruleset about which ones gave issues and don't list them as valid targets.

A good example is this ruleset with problematic subdomains:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Aalborg_University.xml

**Comment by zoracon** [comment]
Posted a cleaner ruleset as an example above ^

**Comment by RemakingEden** [comment]
@zoracon Okay thanks for the clarification. So you would create a ruleset even if it has no working domains? This is what I have so far:

> > 
> <ruleset name="Nintendolife.com">
> 
> 	<rule from="^http:" to="https:" />
> </ruleset>

**Comment by pipboy96** [comment]
@RemakingEden Well, such ruleset won't pass relaxng test, and even if it did, it would effectively be a no-op.

**Comment by RemakingEden** [comment]
Well i'm afraid I need more guidence on the above if anyone can offer it. That is all I can figure out so far, unless there is another way to build rulesets. Please let me know if there is any documentation on this or we could close this request?

**Comment by pipboy96** [comment]
Is there any currently functioning subdomain of nintendolife.com?

**Comment by Bisaloo** [comment]
@RemakingEden, `redirects to HTTP` means that:

https://subdomain.example.com -> http://subdomain.example.com

We can't add a rule in this case because it would create a redirect loop

https://subdomain.example.com -*server*-> http://subdomain.example.com -*HTTPS Everywhere*-> https://subdomain.example.com -*server*-> http://subdomain.example.com ...

In this case, https://nitendolife.com redirects to http://www.nitendolife.com. It's therefore a valid target for HTTPS Everywhere.

On a related note, https://www.nitendolife.com itself would be a valid target because it returns HTTP 200.

**Comment by RemakingEden** [comment]
> @RemakingEden, `redirects to HTTP` means that:
> 
> https://subdomain.example.com -> http://subdomain.example.com
> 
> We can't add a rule in this case because it would create a redirect loop
> 
> https://subdomain.example.com -_server_-> http://subdomain.example.com -_HTTPS Everywhere_-> https://subdomain.example.com -_server_-> http://subdomain.example.com ...
> 
> In this case, https://nitendolife.com redirects to http://www.nitendolife.com (different subdomain). It's therefore a valid target for HTTPS Everywhere.
> 
> On a related note, https://www.nitendolife.com itself would be a valid target because it returns HTTP 200.

Okay thanks, I think I understand. I will give it another go.
