### ISSUE TITLE
Try to switch to HTTPS by default

### ISSUE THREAD

**Issue by Al2Klimov** [EFForg/https-everywhere#17116]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

As a user I'd like HTTPS Everywhere to automatically try to switch from HTTP to HTTPS by default – i.e. w/o having to tick "Block all unencrypted requests". If a such upgrade fails while "Block all unencrypted requests" isn't ticked, HTTPS Everywhere should fall back to HTTP.

**Comment by J0WI** [comment]
Thanks for suggesting this. Please have ha look at #16488 and #7936 where this has already been discussed.

**Comment by Al2Klimov** [comment]
I understand why my suggestion isn't secure enough by itself. But it would be secure on top of the whitelist, wouldn't it?

**Comment by J0WI** [comment]
We can't detect if the site is fully compatible with HTTPS. Mixed content is still a common issue. Some servers are also misconfigured and do not provide the same content on HTTPS or end up in redirect issues.

**Comment by Al2Klimov** [comment]
But the addon seems to do exactly what I suggest (ex fallback) if I tick "Block all unencrypted requests". Doesn't that behavior have the same issue(s)?

**Comment by J0WI** [comment]
"Block all unencrypted requests" is expected to break things and it's for "advanced" users. But for most users HTTPS Everywhere should "just work" seamless. I think #16998 would be a good compromise.
There is already an Add-On called "[Smart HTTPS](https://addons.mozilla.org/en-US/firefox/addon/smart-https-revived/)" doing exactly what you request, so feel free to test this side-by-side with HTTPS Everywhere.
