### ISSUE TITLE
"Block all unencrypted requests" should reload the page

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#17126]
Many of our menu items, like enabling or disabling rulesets, reload the page. We should do the same for BAUR. This is particularly useful if you notice you're on a page without HTTPS, have BAUR disabled, and want to try turning on BAUR to see if it sends that page to HTTPS.

**Comment by Bisaloo** [comment]
This looks like a duplicate of #16870. Which one do you want to keep?

**Comment by jsha** [comment]
Hah, thanks for spotting that @Bisaloo! I guess I keep thinking of this, and forgot that I already filed a ticket. Will close this one.
