### ISSUE TITLE
Minor translation issue (https-everywhere.cancel.he_blocking_explainer)

### ISSUE THREAD

**Issue by musonius** [EFForg/https-everywhere#17194]
There is a minor issue with the German translation of the following text:

`<!ENTITY https-everywhere.cancel.he_blocking_explainer "HTTPS Everywhere noticed you were navigating to a non-HTTPS page, and tried to send you to the HTTPS version instead. The HTTPS version is unavailable. Most likely this site does not support HTTPS, but it is also possible that an attacker is blocking the HTTPS version. If you wish to view the unencrypted version of this page, you can still do so by disabling the 'Block all unencrypted requests' option in your HTTPS Everywhere extension. Be aware that disabling this option could make your browser vulnerable to network-based downgrade attacks on websites you visit.">`

The relevant part of the German translation reads:

`Falls Sie die nicht verschlüsselte Version dieser Seite ansehen möchten, können Sie dass immer noch tun, indem Sie die Option &quot;Alle unverschlüsselten Anforderungen blockieren&quot; in Ihrer HTTPS Everywhere Extension deaktivieren.`

The `&quot;` should actually be quotation marks and _Extensions_ should better be translated with _Erweiterung_:

`Falls Sie die nicht verschlüsselte Version dieser Seite ansehen möchten, können Sie dass immer noch tun, indem Sie die Option "Alle unverschlüsselten Anforderungen blockieren" in Ihrer HTTPS Everywhere Erweiterung deaktivieren.`

Otherwise thank you very much for your excellent work!

**Comment by musonius** [comment]
#17042 was merged into EFForg:master from Hainish:fix-translations-quotation on 5 Nov.

The latest version 2018.10.31, which is the one I am using, is from an earlier date. Nevertheles, I have created a fresh profile and installed the extension from addons.mozilla.org shortly before writing this comment: it still reads _&quot;_.

**Comment by Bisaloo** [comment]
Oh yes, you're right sorry. The new version is programmed for release in about one week (#17157). It should be fixed then.

**Comment by cschanaj** [comment]
The latest full release was made in late October while the fix (#17042) was merged in early November. So I am afraid the users will have to wait for the January release (#17157)  to see this is fixed. 

@Hainish @zaracon Maybe it is worth mentioning this fix in the changelog.

**Comment by musonius** [comment]
The quotes are displayed correctly with version 2019.1.7. Thank you.
