### ISSUE TITLE
[Feature] Support Pale Moon

### ISSUE THREAD

**Issue by gjhklfdsa** [EFForg/https-everywhere#17216]
**Description**: Add Official Extension for [Pale Moon](https://addons.palemoon.org/)

**Comment by Dyras** [comment]
Is this even worth it? How many people actually use Pale Moon?

**Comment by dotnetfox** [comment]
EFF doesn't have additional employers to maintain support for small browsers like palemoon (see https://github.com/EFForg/https-everywhere/issues/1315#issuecomment-88181300 and https://github.com/EFForg/https-everywhere/issues/1315#issuecomment-89823299).

**Comment by zoracon** [comment]
Closing for now, if we have the capacity one day. We can revisit. This is also a duplicate of #1315

**Comment by Fincer** [comment]
People who are still looking for HTTPS everywhere (or alternatives) for Pale Moon browser might want to check out HTTPS Always extension for Iceweasel available on [here](https://wiki.hyperbola.info/doku.php?id=en:project:iceweasel-uxp_addons).

As far as I've tested, it works in Pale Moon (28.5.2). Might be bit out-dated but it's still better than nothing at all.
