### ISSUE TITLE
CartoonNetwork.com streaming issues

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#1722]
Using Firefox 38.0.1 on Windows 7 with HTTPSE 5.0.4 when attempting to watch full episodes after signing in with provider credentials,  the video never loads.  Disabling Turner.com (partial) solves this issue, but then you get an Error Undefined message unless you disable the Adobe.com rule.

http://www.cartoonnetwork.com/video/adventuretime/hoots-episode.html can be used as an example.

**Comment by MDawg957** [comment]
It looks like this issue was partially fixed in 5.0.6, but the Adobe.com rule still causes the Undefined error to display.

http://www.cartoonnetwork.com/video/index.html?atclk_gn=un_video_see-all-video can be used as a better reference page since it is stable.

**Comment by MDawg957** [comment]
This is still unfixed in the latest version, 5.1.1.  Disabling the Adobe.com rule resolves the problem.

**Comment by tancrackers** [comment]
The video on this page cannot play is Adobe.com is enabled:
http://www.biography.com/people/harriet-tubman-9511430

Adobe.com breaks videoplay (in Firefox, but in Chrome).

**Comment by semenko** [comment]
Videos (on both sites) play for me in the latest release.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
