### ISSUE TITLE
Archive fo/is/today broken with https-everywhere activated (disabling site fixes issue for .is)

### ISSUE THREAD

**Issue by jeroen7s** [EFForg/https-everywhere#17239]
loading archive.fo shows ssl mismatch errors, same for archive.is/archive.today (same website, different domain)
disabling the archive.is rule fixes it for archive.is, same rule shows for .fo and .today, but disabling does not fix it on these domains

**Comment by Giltyhub** [comment]
can't reproduce, can you try again I'm sure it was fixed?

**Comment by Bisaloo** [comment]
My guess is that it's https://community.cloudflare.com/t/archive-is-error-1001/18227/6

See also #17213, #17209

**Comment by jeroen7s** [comment]
@Bisaloo yup seems like it
thought it wasn't that because it's not a DNS error, but it seems like cloudflare is loading their page saying that the DNS record could not be found, which causes Https everywhere to produce an SSL error instead of the "dns record not found" page
