### ISSUE TITLE
Macromedia.com rule breaks Flash Settings Manager

### ISSUE THREAD

**Issue by dreamlayers** [EFForg/https-everywhere#1723]
I'm using HTTPS Everywhere 2015.5.12 in Chrome 42.0.2311.152 (64-bit) in Ubuntu 15.04. The macromedia.com rule breaks the Flash settings manager at https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager03.html

The page formatting is lost and the Flash object which actually allows Flash settings to be changed does not appear. An inconspicuous grey shield appears at the right side of the address bar with the message "This page is trying to load scripts from unauthenticated sources". By clicking on it I can "Load unsafe scripts" and get things working. Disabling just the macromedia.com rule avoids this problem.

**Comment by reedy** [comment]
Looks like it has various mixed content

**Comment by numismatika** [comment]
If you allow mixed active content temporarily, the rulesets will also rewrite the wwwimages subdomain to akamai tls , so once the infamous https://bugzilla.mozilla.org/show_bug.cgi?id=878890 is fixed, this problem should be solved automatically

**Comment by semenko** [comment]
Currently working for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
