### ISSUE TITLE
pubs.opengroup.org subdomain should redirect to HTTPS

### ISSUE THREAD

**Issue by lnikkila** [EFForg/https-everywhere#17251]
Type: ruleset/website issue

Domain: pubs.opengroup.org

The ruleset comments currently state:

```
	Nonfunctional subdomains:
		- pubs	(redirects to http)
```

However this doesn’t seem to be the case anymore, the HTTPS version loads for me if I navigate to it manually, e.g. <https://pubs.opengroup.org/onlinepubs/9699919799/>.

**Comment by pipboy96** [comment]
Closed by #17687.
