### ISSUE TITLE
"Disable HTTPS Everywhere on this site" not working

### ISSUE THREAD

**Issue by jakemagee** [EFForg/https-everywhere#17253]
Type: code issue

Using Firefox 64.0 and HTTPS Everywhere 2019.1.7, the "Disable HTTPS Everywhere on this site" doesn't appear to work correctly... at least not for rainwave.cc.  The HTTPS Everywhere icon displays as grayed out only for rainwave.cc, but the site still does not stream correctly.  The only way I have been able to work around the issue is to enable HTTPS Everywhere for the site again, and instead disable the "Block all unencrypted requests".  However, this affects all sites, not just a single site.

**Comment by Bisaloo** [comment]
Thank you for your report!

It's because the problematic domain is a third party resource (`gameowls.com`). Where you add an exception, it's for the first party (`rainwave.cc`) so it doesn't work.

As a temporary fix, you could add problematic `gameowls.com` subdomains in your whitelist by explicitly visiting them once.

cc @Hainish @zoracon

**Comment by jakemagee** [comment]
That would be an awesome workaround... however, it didn't seem to work for me.  How did you find the reference to gameowls.com?  Maybe I'm randomly pulling from another third party that I need to whitelist.

I also contacted the admins about this and they said its going to take some time to convert their relays over to HTTPS (but hopefully something they are working on).

**Comment by Bisaloo** [comment]
Oh right, this won't be enough because we're also adding an additional header to upgrade all resources to HTTPS in this mode.

#17254 should fix this part.

**Comment by jakemagee** [comment]
Sweet... so I'll just keep an eye out for when that's merged.  Thanks!
