### ISSUE TITLE
Unable to edit Github Wiki

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#17266]
RT, the Edit button is no longer available and I am not able to update the page https://github.com/EFForg/https-everywhere/wiki/Ruleset-Statistics. Is this intentional?

**Comment by J0WI** [comment]
It works for me

**Comment by cschanaj** [comment]
Please add me as a collaborator if that is needed to edit the Wiki page. thanks!!

**Comment by zoracon** [comment]
@cschanaj You have been invited, let me know if you don't see it

**Comment by cschanaj** [comment]
I can edit the Wiki page now. Thanks!
