### ISSUE TITLE
Unable to log into the network when using strict HTTPS

### ISSUE THREAD

**Issue by alex65536** [EFForg/https-everywhere#17409]
Using strict HTTPS mode seems to break logging into the network. The login is usually done by intercepting HTTP pages and sending the login form instead. To detect that, Firefox sends a query to `http://detectportal.firefox.com/success.txt`. But the extension tries to load this file using HTTPS, which doesn't allow to log into the network. Maybe it's better to add this URL as an exception?

**Comment by pipboy96** [comment]
@alex65536 I think Firefox devs should make this request bypass any installed extensions instead of us adding an exception.

**Comment by alex65536** [comment]
OK, I will try to report it into firefox.

**Comment by alex65536** [comment]
Reported it to Firefox devs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1525993

**Comment by zoracon** [comment]
Is it okay to close this out? Since this is out of the scope of HTTPSE?

**Comment by pipboy96** [comment]
@zoracon I'm not sure. This issue may happen with any extension that rewrites or blocks HTTP requests.

**Comment by zoracon** [comment]
From the bug report they seem to have a temporary work around for them and have set a priority level on this. So I'll take it as them confirming the bug on their end. But this is definitely something to keep in mind as a browser quirk! I'll close for now, and if needed it can be re-oponed.
