### ISSUE TITLE
Securecookie and leading dots

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#1743]
According to [the docs](https://www.eff.org/https-everywhere/rulesets#secure-cookies),

> A cookie whose domain attribute starts with a "." (the default, if not specified by Javascript) will be matched as if it was sent from a host name made by stripping the leading dot.

This appears to not be the case though; for the ruleset in #1742, I tried with and without the leading \., and only including in led to all cookies being secured. This is in Firefox/31.0 with the latest GitHub build of https-e.

**Comment by jsha** [comment]
Your ruleset is correct. The docs could be clearer. They are talking about how incoming cookies from Javascript are treated, not how you should write the securecookie tag. In other words, if JS sets a cookie with `domain=".foo.com"`, for the purposes of matching hostnames in HTTPS Everywhere, that's equivalent to an HTTPS response from `foo.com` sending a `Set-Cookie` header.

The HTML for that doc is checked into the repo. I'd happily accept a pull request clarifying.

**Comment by fuglede** [comment]
I see; that makes perfect sense, thanks.

While we're at it, I was wondering if the securecookie tag I added was actually necessary in that particular ruleset; since the entire site is covered, will cookies not be secured automatically as all requests are carried out over https?

**Comment by jsha** [comment]
That's true. If all subdomains of a site are covered by rewrites to HTTPS, generally a securecookie rule is not necessary, though it may be nice for paranoia. E.g. if HTTPS Everywhere is temporarily disabled, cookies tagged as secure still won't be leaked over HTTP.

**Comment by fuglede** [comment]
Good point. Thanks again.
