### ISSUE TITLE
Add ability to disable HTTPS Everywhere for specific domains without first visiting the site

### ISSUE THREAD

**Issue by raman325** [EFForg/https-everywhere#17434]
Type: feature request

Hi, I've run into some issues using HTTPS Everywhere while on sites on my corporate networks, or on sites that are "public" but are proxied via Microsoft Application Proxy to our internal network. I'm not sure why this is creating problems (in this case it was our JIRA instance), but in trying to get around it, I've noticed that I can only disable HTTPS Everywhere for a site if I am on the site and disable it through the extensions right click menu.

It would be great if I could explicitly whitelist domains that HTTPS Everywhere would be disabled for without having to do it for every site as needed (in my case, I'd disable it for my corporate domains). I think it would make sense to add this functionality into the extension settings, maybe even under "Advanced".

Thanks for your consideration!

**Comment by pipboy96** [comment]
I'll attempt to implement this.

**Comment by bershanskiy** [comment]
@pipboy96 Any update on this? If you are not working on this, may I pick up this issue?

**Comment by pipboy96** [comment]
@bershanskiy No, it's fine.

**Comment by bershanskiy** [comment]
#17890
