### ISSUE TITLE
UI dropdown checkboxes look fuzzy on external display screen

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#17440]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

```
Firefox 65
Version: 2019.1.31
macOS 10.14.3
Macbook Pro
```

On an external 1920x1080 HD monitor, the checkboxes in the UI dropdown look blurry / fuzzy
![image](https://user-images.githubusercontent.com/5124946/52671535-5338cd80-2ee9-11e9-95fd-6298c0099640.png)

They're crisp when the window is moved to the builtin Retina display.
<img width="325" alt="image" src="https://user-images.githubusercontent.com/5124946/52671709-c9d5cb00-2ee9-11e9-9229-a83e5f08ebf5.png">

**Comment by zoracon** [comment]
@wesinator Is this explicitly just HTTPS Everywhere's menu? Could you check another extension out to see if the menu also blurs out and compare?

**Comment by pipboy96** [comment]
@wesinator Here's a page with a checkbox, please check if it's blurry: https://pipboy96.github.io/index.html

**Comment by zoracon** [comment]
> @wesinator Here's a page with a checkbox, please check if it's blurry: https://pipboy96.github.io/index.html

This might not cause the same issue as an extension popup menu, but it doesn't hurt to try

**Comment by pipboy96** [comment]
@zoracon It's just a `<input type="checkbox">`, just like the popup checkboxes.

**Comment by wesinator** [comment]
@pipboy96 Oh interesting, yea that looks blurry too:
![image](https://user-images.githubusercontent.com/5124946/52682821-ca348d00-2f0e-11e9-8f2d-66a57ae8a3e7.png)

I guess this is a Firefox UI issue then

**Comment by pipboy96** [comment]
@wesinator Please report this bug on Mozilla bugtracker then.
