### ISSUE TITLE
Cloudfront rule breaks Eurovision Song Contest streaming

### ISSUE THREAD

**Issue by dreamlayers** [EFForg/https-everywhere#1747]
If the Cloudfront rule is enabled, I can't stream http://www.eurovision.tv/page/webtv?program=132903 , which uses Flash and Infinite HD Octoshape. The Infinite logo stays for an extended time and then I get a "Stream is not available. 3262032" error. This is in Firefox 38.0.1 in Windows 7 SP1 x86.

**Comment by numismatika** [comment]
i made #1748 , stream not available doesn't appear then.

**Comment by semenko** [comment]
fix per above
