### ISSUE TITLE
Detect parked domains

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17474]
It would be great if we could test the ruleset database for domains that are not technically NXDOMAIN but are no longer used and display parking pages. To do that, a list of name servers used by domain parking services is required.

**Comment by pipboy96** [comment]
Related: https://github.com/EFForg/https-everywhere/pull/17320#issuecomment-458146191

**Comment by Bisaloo** [comment]
Related: https://github.com/EFForg/https-everywhere/pull/12973
