### ISSUE TITLE
Mismatch between hsts-prune and hstspreload.org minimal max-age

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#17506]
Type: other

The minimal `max-age` for preloading eligibility via https://hstspreload.org increased to 1 year (https://github.com/chromium/hstspreload.org/commit/b48ae5ac7c2db1d8a0635ee60a4c68a4b2f9c88e). Yet, our `hsts-prune` script still uses the old requirement of  18 weeks:

https://github.com/EFForg/https-everywhere/blob/3895957bdad9a9ccdf41f4fc1120dbb63404748a/utils/hsts-prune/index.js#L148

Is it something we should change?

**Comment by pipboy96** [comment]
My guess is that we should follow the actual browser preload lists, not the policies for new entries, e.g. if website was previously added with less than 1 year `max-age`, we should keep it.

**Comment by cschanaj** [comment]
From https://github.com/chromium/hstspreload.org/commit/b48ae5ac7c2db1d8a0635ee60a4c68a4b2f9c88e

> ... and that sites may be removed automatically in the future for failing to keep up the requirements.

IMHO, we should follow the hstspreload.org minimal max-age policy and increase the requirement. Otherwise, the script might mistakenly remove rulesets for sites that are in a pending removal status from the preload list.

**Comment by pipboy96** [comment]
@cschanaj I think there is an API to check if website is pending removal.

**Comment by cschanaj** [comment]
@pipboy96 yes, there is an API https://hstspreload.org/api/v2/pending-removal to retrieve a list of pending removal domains. (However, for how long an entry will be kept in this list???) 

AFAIK, `hsts-prune` works by comparing the inclusion of the preload lists bundled to our supported browsers' source code, which the updates might lag behind hstspreload.org (a). It increases the likelihood to mistakenly remove a targets from our rulesets if we use a looser policy. 

`hsts-prune` will normally check if a target is included in all preload lists bundled in the supported browsers AND then send a request to check the HSTS header. A target for a site will only be removed if it is preloaded in all supported browsers and  

https://github.com/EFForg/https-everywhere/blob/3895957bdad9a9ccdf41f4fc1120dbb63404748a/utils/hsts-prune/index.js#L148

hold true. We should use a stricter policy (`max-age > 1 year`) to avoid leaving sites unprotected. It also do less harm even if (a) is not the case.

**Comment by pipboy96** [comment]
Closed by #17507.
