### ISSUE TITLE
Missing interstitial page on https://amphibian-reptile-conservation.org

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#17529]
Type: code issue

Interstitial page is missing on FF Nightly with HTTPS Everywhere 2019.1.31 EASE for https://amphibian-reptile-conservation.org

**Comment by zoracon** [comment]
Looks like an SSL error we don't account for, I'll add that in to the fray.

**Comment by Bisaloo** [comment]
@zoracon, this is still an issue in HTTPS Everywhere 2019.5.13.

Another test url: https://lafabriquedesmobilites.fr/

**Comment by zoracon** [comment]
Odd, I'll rerun and see what the SSL code brings up this time.

Posting what is seen just for reference - FF (66.0.4)
![image](https://user-images.githubusercontent.com/4276080/58134489-d601b080-7bdb-11e9-890a-0288b9d0cc31.png)

**Comment by Bisaloo** [comment]
FYI, another one:

https://feeds.nature.com/~r/ncomms/rss/current/~3/F0Ch24Ri4iM/s41467-019-10682-3
