### ISSUE TITLE
HTTP favicons slip even when EASE is enabled

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#17535]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

how to reproduce: make  a small http file with a favicon from a site that is only accessible over http, enable ease mode, open the http file, you see that the favicon loads up (tested on firefox)

**Comment by pipboy96** [comment]
Can reproduce locally, but not with an online page (https://pipboy96.github.io/insecure-favicon-test.html)

**Comment by pipboy96** [comment]
cc @Hainish @zoracon.

**Comment by zoracon** [comment]
Was this for a live site? @Giltyhub 

HTTPS Everywhere permissions are limited to:

- `http://, https://, wss://, ws://`, and `ftp://`. 

We do not intercept for `file://`. So the Content Security directive for `upgrade-insecure-requests` that we send for `onHeadersReceived` wouldn't go through.

For local files I like striking up a quick local server sometimes with this tool. (Yes I know, it's a Chrome App :) )
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb

**Comment by pipboy96** [comment]
@zoracon You can also use `darkhttpd` or `python3 -m http.server`. Do you suggest setting up a firewall to block unencrypted HTTP (by port or packet contents) or always use local server for users who do not want to leak any unencrypted connections?

**Comment by zoracon** [comment]
> @zoracon You can also use `darkhttpd` or `python3 -m http.server`. Do you suggest setting up a firewall to block unencrypted HTTP (by port or packet contents) or always use local server for users who do not want to leak any unencrypted connections?

No, I just meant for testing something like this scenario with a local HTML file.

**Comment by pipboy96** [comment]
The condition for this issue to happen is a remote favicon included in a local .html file opened using `file:` protocol.

**Comment by zoracon** [comment]
Closing for now since we do not filter `file:///`

**Comment by Giltyhub** [comment]
@zoracon actually this happens even with `https://*`

**Comment by zoracon** [comment]
Do you have an example I can try out? @Giltyhub

**Comment by pipboy96** [comment]
@zoracon It should be easy enough to create one. I will work on this.

**Comment by pipboy96** [comment]
@zoracon @Giltyhub This issue can't be reproduced on FF Nightly or Chrome Stable. It can be reproduced in Tor Browser, but it's not specific to it since the same issue exists in Firefox 60 ESR. In this version of Firefox, favicon requests bypass both WebExtensions, Network tab in DevTools and MCB. Seems the only solution for Tor Browser devs is to wait for the next ESR.

URL for testing: <https://insecurefavicontext.xyz/>. It makes a request to<http://insecurefavicontext.xyz/favicon.png> which deliberately is not available over HTTPS.

**Comment by Giltyhub** [comment]
@pipboy96  so it seems it has been fixed in Firefox, hence it's not even a HTTPS-E bug so i'm closing this, thanks again for your effort in reproducing and testing this bug!

@zoracon
