### ISSUE TITLE
kathryndow.photoshelter.com Broken by HTTPS Everywhere

### ISSUE THREAD

**Issue by MikeA01730** [EFForg/https-everywhere#17542]
Type: ruleset/website issue

Hi,

When displaying URL https://kathryndow.photoshelter.com/gallery/Landscape/G0000SPlGJnZD9dQ/ on Windows 10 Firefox ver. 65.0.2 the images displayed should change every 2 seconds or so.  However when https-everywhere is enabled only the first image is shown and other images are not displayed.  

Mike

**Comment by pipboy96** [comment]
Can't reproduce on FF Nightly, Linux.

**Comment by zoracon** [comment]
Testing in a Windows 10, Firefox ver. 65.0.2. With HTPSE enabled, disabled, and removed. I do not see this slides working.

**Comment by MikeA01730** [comment]
When I disable the extension then the slides work.  When I enable it they don't work.  I switched back and forth a few times and it's consistent.  I also disabled all my other extensions when doing this to make sure nothing else was affecting the behavior.  As I recall (didn't retest) I have to reload the page to see the change.

**Comment by pipboy96** [comment]
@MikeA01730 Try on a new browser profile with only HTTPS Everywhere installed.

**Comment by MikeA01730** [comment]
I created a new profile and installed only HTTPS Everywhere.  When I tested the web site it worked correctly.  

I then tried the original profile which has HTTPS Everywhere, 1Password, Disconnect, Evernote Web Clipper, uBlock Origin, and Web to PDF installed and enabled.  Previously it failed with this setup, but this time it worked fine.  

I went back to my desktop (previously I was using my laptop) and tried the same thing, i.e. same extensions, and it worked correctly there too.  

Previously it failed on both PCs, and now it works correctly on both.  Don't know what's going on here but the problem for me has disappeared.  

Mike

**Comment by pipboy96** [comment]
@MikeA01730 I guess this should be closed then.

**Comment by pipboy96** [comment]
@MikeA01730 By the way, you don't need Web to PDF, Windows 10 already provides this functionality (Print to PDF) and you can make a .png screenshot of any page using Firefox DevTools (type `:screenshot` in console. Neither you need Disconnect, which has some tracking code in the extension.

**Comment by MikeA01730** [comment]
I have Web to PDF because none of the converters always work right and this one often works when others don't.  

Didn't know about the Disconnect Malvertising filter.  I'll add it and drop the Disconnect extension.  Thanks for the information.  

I'll close the issue.  

Mike

**Comment by pipboy96** [comment]
@MikeA01730 FF also has Disconnect-based filters:
![block](https://user-images.githubusercontent.com/46632672/54052346-35fbd400-41f5-11e9-89d3-da726301eae0.png)
