### ISSUE TITLE
SSL Labs website keeps reloading

### ISSUE THREAD

**Issue by Grossdm** [EFForg/https-everywhere#17552]
Type: other

I tried to load a [report on SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=troyhunt.com), and the page had what appeared to be a table header that displayed a loading icon.
The page reloaded every few seconds.

The uBlockO logger showed nothing blocked for the site.
I disabled scripting, which did not help.

After I disabled HTTPS Everywhere for SSL Labs, the site loaded properly.

**Comment by pipboy96** [comment]
Can't reproduce.

**Comment by J0WI** [comment]
This is not related to HTTPS Everywhere. The site is using a `<meta http-equiv="refresh" content="7; ... " />` to update the results.
I assume that the test was already completed when you disabled HTTPS Everywhere.

**Comment by pipboy96** [comment]
@J0WI Almost forgot that `<meta http-equiv="refresh">` tag exists.
