### ISSUE TITLE
Option to downgrade to stable rules while EASE is enabled

### ISSUE THREAD

**Issue by User486375** [EFForg/https-everywhere#17554]
Type: feature request

Rather than disabling the extension entirely to access non HTTPS sites, users should default to stable rules and also be able to downgrade to them just like the option `Disable HTTPS Everywhere on this site`. This would be especially useful on sites which are partially HTTP.

**Comment by pipboy96** [comment]
Do you mean "Disable HTTPSe on this website" should be replaced with "Disable EASE on this website"?

**Comment by User486375** [comment]
> Do you mean "Disable HTTPSe on this website" should be replaced with "Disable EASE on this website"?

No, because users may still want to have that option while EASE is enabled if stable rules break a site, I think this should be in addition to it but only an option while EASE is enabled. As for when users choose to visit the HTTP version of a site the default should be `Disable  EASE`.

**Comment by pipboy96** [comment]
@User486375 By default only stable rules are enabled already.

**Comment by User486375** [comment]
I'm saying when a user clicks to visit an HTTP site with EASE enabled, the default behavior should be disabling EASE but they should still have the option to fully disable the extension for that specefic site if need be.

**Comment by zoracon** [comment]
I'm trying to understand this request more. How is this more beneficial than unchecking EASE, since in "normal" mode stable rules will apply and allow you to navigate to HTTP sites?

**Comment by pipboy96** [comment]
@zoracon They want to use EASE for all website except one or two that still do not support HTTPS. These websites likely reference other websites that can be rewritten to HTTPS. They want to rewrite as many requests as possible.

**Comment by sirald66** [comment]
I may not fully understand the issue, but is this an example? - https://qpages.com/

With EASE enabled, the icons break and their labels overwrite the text making them unreadable.

**Comment by pipboy96** [comment]
@sirald66 This page has mixed content issues that are unrelated to EASE. Same thing happens if strict MCB is enabled in browser settings.

**Comment by sirald66** [comment]
@pipboy96 I've novice in this area.  What/where would this MCB setting be in Chrome?

**Comment by pipboy96** [comment]
@sirald66 `chromium --enable-strict-mixed-content-checking`

**Comment by Bisaloo** [comment]
> I'm trying to understand this request more. How is this more beneficial than unchecking EASE, since in "normal" mode stable rules will apply and allow you to navigate to HTTP sites?

@zoracon if you disable EASE, you have to reactivate it afterwards (and it's easy to forget). That does not happen if you simply add an exception for a given domain.

**Comment by pipboy96** [comment]
@Bisaloo EASE has a differently looking HTTPS Everywhere icon. Not sure how it's possible to not notice it.

**Comment by mikhaelkh** [comment]
I want to use "encrypt everything" by default, and when it breaks the site, I don't want to completely disable HTTPS Everywhere on the site straightaway, first I want to apply rulesets on the site. And if rulesets are breaking the site, only then I want to disable extension on the site until the ruleset issue is being resolved.

There's 3 possible states of HTTPS Everywhere: encrypt everything, apply rulesets, disabled. But only 2 of them are available at any given moment: either rulesets & disabled or encrypt everything & disabled.
And only one custom site list exists - for disabled sites.

Consider Chrome's implementation of Cookies - `chrome://settings/content/cookies`. There's also 3 states for each domain: allow, clear on exit, block. Chrome maintains 3 custom lists - a list for each state.
