### ISSUE TITLE
Restarting Firefox undoes any custom placement of the extension's icon

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [EFForg/https-everywhere#17567]
When I use Firefox's 'customize' feature to move the ([excessively obtrusive](https://github.com/EFForg/https-everywhere/issues/5737)) HTTPS Everywhere icon, and subsequently restart Firefox, the icon returns to where it was before. 

HTTPS Everywhere: 2019.1.31
Browser: Firefox 65.0.2
OS: Windows (I do not have the problem when using the extension on Linux)

**Comment by pipboy96** [comment]
@LinuxOnTheDesktop It's highly unlikely that this is HTTPSe's fault. Try filing a bug at Mozilla.

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but the thing is, it does not affect any other extension (well, admittedly: not at the moment - I have had the problem with a few other extensions, in the past). Also, I've got too many open bug reports with Mozilla and - more to the point, I suppose - it's not my extension; I'm just a (would-be . . ) user of it.

**Comment by pipboy96** [comment]
@LinuxOnTheDesktop I can't reproduce with Nightly on Linux.

**Comment by LinuxOnTheDesktop** [comment]
As I said, I do not have the problem on Linux but only on Windows.

**Comment by pipboy96** [comment]
@LinuxOnTheDesktop HTTPSe is OS-agnostic. It is not supposed to behave differently depending on the OS the browser is running on. You should most likely file a bug at Mozilla.

**Comment by LinuxOnTheDesktop** [comment]
OK; done.

**Comment by zoracon** [comment]
Closing this for now since it's confirmed filing was done with Mozilla
