### ISSUE TITLE
Https everywhere

### ISSUE THREAD

**Issue by imasuvivior** [EFForg/https-everywhere#17606]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: other

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by pipboy96** [comment]
@zoracon Close this and ban him please.

**Comment by pipboy96** [comment]
He also spammed on this commit:
https://github.com/EFForg/https-everywhere/commit/5445384b37448a796054ba555bc71f59161761ef
