### ISSUE TITLE
giantitp.com some assets don't load

### ISSUE THREAD

**Issue by maxrothman** [EFForg/https-everywhere#17605]
Type: ruleset/website issue

Domain: giantitp.com
Browser: Chrome 72.0.3626.121

With HttpsEverywhere enabled, many of the assets (images, etc.) on www.giantitp.com do not load. With HttpsEverywhere disabled, the site loads as expected.

I didn't spend long looking into it, but it appears that HttpsEverywhere is changing some of the URLs, removing initial slashes in the path, so that www.giantitp.com/images/a.png becomes www.giantitp.comimages/a.png.

**Comment by pipboy96** [comment]
Can't reproduce with FF Nightly on Linux.

**Comment by maxrothman** [comment]
Any update? I've had to disable httpseverywhere as a result of this issue.

**Comment by pipboy96** [comment]
Update your browser and the extension, disable all extensions except HTTPS Everywhere and retry. If this fixes the issue, it's very likely that our extension is not to blame. We do not currently have any rules that affect giantitp.com.

**Comment by fuglede** [comment]
Also, could it be that you've manually added a ruleset for the site (through the "Add a rule for this site" functionality)?

**Comment by maxrothman** [comment]
Huh, now I'm unable to reproduce this issue either. Maybe it was a temporary issue with their site.
