### ISSUE TITLE
https-everywhere: xpi timestamp of files is 1/1/1980

### ISSUE THREAD

**Issue by apoleon** [EFForg/https-everywhere#17618]
This is Debian bug

https://bugs.debian.org/925177

The timestamp of files in the distributed xpi version of https-everywhere dates back to January 1980 on Linux systems. Obviously this is not accurate. 

Once https-everywhere shipped a script in utils/create_xpi.py that was responsible for creating the xpi file. It just lacked a date_time parameter.

https://salsa.debian.org/webext-team/https-everywhere/blob/99fcc50e0bb5617c64e55457a7b3e502013e0dc8/debian/patches/use-newer-timestamp-date.patch

Debian applied the aforementioned patch to change the timestamp to a recent value. The create_xpi.py script does not exist anymore but maybe you want to correct this anyway. You can easily reproduce this issue by unpacking the xpi file on a Debian GNU/Linux system.

**Comment by pipboy96** [comment]
@apoleon This is expected, it's needed for reproducible builds.

**Comment by apoleon** [comment]
This shouldn't be necessary for reproducible builds because several alternatives are known.

https://wiki.debian.org/ReproducibleBuilds/Howto

https://wiki.debian.org/ReproducibleBuilds/TimestampsInTarball

**Comment by pipboy96** [comment]
@apoleon Can you try implementing one of such alternatives?
