### ISSUE TITLE
Add support for Safari 12 - 2019 and still no secure option for Safari

### ISSUE THREAD

**Issue by whatthehomepod** [EFForg/https-everywhere#17631]

**Comment by pipboy96** [comment]
Duplicate of #5121.

**Comment by whatthehomepod** [comment]
Yeah do something about it than. I opened another one because the first issue opened three years ago. Jesus Christ. 

Verstuurd vanaf mijn iPhone

**Comment by pipboy96** [comment]
@whatthehomepod Please address all your concerns to #5121.
