### ISSUE TITLE
Who are the users authorized to merge PRs?

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17640]
I see that I can no longer merge any PRs due to only "authorized" users being able to do that. For transparency's sake, I would like to know who is allowed to merge pull requests now.

Also I would like the list of all people who has collaborator status in the repo to be public.

**Comment by andresbase** [comment]
Hi @pipboy96, my name is Andrés, and I'm EFF's Director of Consumer Privacy Engineering (the team that works on HTTPS Everywhere and Privacy Badger). Can you contact me at andres@eff.org?   I'd like to chat with you about your work on the project over the past couple of days.

**Comment by andresbase** [comment]
Also, please do not contact EFF employees through their personal accounts. We try to keep a healthy separation between our work and personal lives, and that's much easier to do if contributors stick to contacting us through Github or our EFF email addresses.

**Comment by pipboy96** [comment]
@andresbase Can we talk here? If not, why?

**Comment by pipboy96** [comment]
@andresbase @zoracon did not have any contact info except email or phone, and I personally didn't want to use either. I apologize for looking out her Gmail address and contacting using Hangouts. If she had Tox, Telegram or XMPP+OTR account I would have used it.

**Comment by andresbase** [comment]
I would prefer to talk directly about sensitive issues.

**Comment by pipboy96** [comment]
@andresbase I want to make it clear then that I will keep the record of conversation, but I will not give it to anyone except the more "senior" EFF staff. I also ask to treat my email address as sensitive information. Please wait for me to generate a GPG key and sign it with my current GitHub key.

**Comment by pipboy96** [comment]
https://github.com/pipboy96/gpgkey/tree/master

The GPG key is signed by the key I set up in GitHub.

**Comment by pipboy96** [comment]
@andresbase Please confirm that `309A B3E1 766A 0535 56AF  233F 095C B6A6 B3B9 F29C` is your correct fingerprint for email alexis at eff.org.

**Comment by andresbase** [comment]
That is my fingerprint for https://www.eff.org/files/2017/06/28/andres.txt

Please email to andres@eff.org and not to alexis.

**Comment by pipboy96** [comment]
oops
Thanks for noticing.

**Comment by pipboy96** [comment]
@andresbase This is my email, encrypted with the key you linked to:

```
-----BEGIN PGP MESSAGE-----

hQIMAyMnTO+g/lUWAQ/+NyhswyMOQxUnvydZ4YJjkKjL07wOjXz9jdWr+eEWrTXW
nOiFULhRPcoJL59sf7/KB9R4Na6zg1gX5u4IOf2lMt39INp2Qv7UK5v8uoJwGFGc
JqBzIFQG3NdpOu5Sd/e5qrWF17sUIjZLTscWXmKWgD7ePhyODFBnhxdBNnExkJ8i
4uuV0WOMCIHZEECWyYqqE8hSXWycRbzxzLB1f13TydRaciBBjyD6AN5nKQ5H31oN
YF38LaZxdLiOiAHvPf7hSiQ0sRPJe4PCF1RyEUyAnDE6oA/wB5+ovIgSTeZfA7Ag
L1tpyzN/Bal/eD7zNL/l1DbkbZgAu6ds1Gfs0NV4Z06DkPL2lyuUUIWffpRQWjjO
KT+Zr5p75o9XR4nvsdMxVXrSA4QNTV+pG468NjnVgj7pqvYKsWmkjj1MCK3uP3uC
wnZx5R5Sj1dsl7OGjAwja1CG8dN9FXKj2+/O/tXgoSgNfjxbBEwqMilFwltg6eKr
jZU3mOtiMNYlkX+q7woXIGg9qNivXaIlI5r37xYl/3QY2f6VCfCoPaEIHkERKHZY
V9my5T7Bi/Gig0xh0otGWPRbrubTkDOXf7q5ZStAM+TORY1kFIyFdUDztFtP/Wjx
RDmo49Bnxdcvq/GrH4xhyPvXffdkl7TOJDmLb+jILplrO2PoGvD4zPU4Ww6Vi/HS
wFYBb/8mezYJRJQE2bVetOpndFwsQZIX9NjId28phy8T+gYVOTe+Iy1KhsKxIPuH
W2C2C5eGwnOT0TIHyuejaBxPH+EZk0Rq0Ck/2t7QYkZVFsXSFH6+XIuK1Glgg2NL
8lQ9/Ow91syd6WNAXt9KG3ArBfk1mJ27RRLM4Ryoq7WvaB35V6YB0XVQjkiTIQER
Z4hqGK84uw/FTFC1vpb2M6a2wypzU2GNsyuSby1MH0K0MakSqNB3RAsJqCgfIIHa
tFl9db66rdqg7K9trbTLYpzBM345fDSZq6ojRUagTf7sScA9JAPuCuszbvd2npOL
AaHSdeTxbk49PkJ/ofbKlZTqBUi/zr9SuBYhHRkBxssdLG4O4yMXtA==
=Gk96
-----END PGP MESSAGE-----
```

**Comment by pipboy96** [comment]
@andresbase I am unable to verify the email because it is in some weird format, with signature being sent as an attachment, not to mention that the email was not encrypted. I actually went through generating a encryption keypair only for this. This is also why I was reluctant of using email.

**Comment by pipboy96** [comment]
@andresbase Just in case, I just added this text on https://github.com/pipboy96/gpgkey:

>If you want to contact me privately, please create an issue in this repository with your encrypted message. I may not be able to answer if I will not be able to find your public key.

**Comment by andresbase** [comment]
Thanks, will take more care next time.
