### ISSUE TITLE
Add support for webdiplomacy.net

### ISSUE THREAD

**Issue by garethcollins** [EFForg/https-everywhere#17658]
Type: new ruleset

Domain: webdiplomacy.net, www.webdiplomacy.net

I gave it a try here:

https://github.com/garethcollins/https-everywhere/commit/cf9cb85f8c904679d90dd84919cdfe755e55a956

but it wasn't working consistently. On an Ubuntu 14.04 machine, it appeared to work fine...but I couldn't run the verifications scripts because I had a problem with python2.6. I remade the change on an Ubuntu 18.04 machine. It validated fine (using test/validations/special/run.py) but didn't seem to change http to https when I ran bash test/firefox.sh --justrun or the chromium equivalent test.

Perhaps I am missing something obvious so I am adding an issue instead of a direct pull request

**Comment by Bisaloo** [comment]
It looks fine. That must have been a problem with the test scripts. Feel free to create a PR and I'll have a look.

**Comment by pipboy96** [comment]
Closed by #17683.
