### ISSUE TITLE
Memory leak in Chrome

### ISSUE THREAD

**Issue by Pascal666** [EFForg/https-everywhere#17659]
Version: 2019.1.31 on Chrome Version 73.0.3683.86 (Official Build) (64-bit) on Windows 10.

Per Chrome Task Manager, HTTPSE only uses about 150MB on startup.  After running for 10 days it is using over a gigabyte.  Disabling and re-enabling it brings memory usage back down to 150MB.

**Comment by pipboy96** [comment]
@Pascal666 Is there any way to reproduce this without running Chrome for 10 days?

**Comment by Pascal666** [comment]
I doubt the leak is time-based, it is probably per URL.  Do you have a tool that will automatically open and close a bunch of random URLs?  Just letting the browser sit for 10 days probably won't recreate the problem, you'd actually have to use it during that time.  Depending upon where the leak is, it may or may not show up justing opening and closing the same URL repeatedly.

**Comment by pipboy96** [comment]
@Pascal666 I installed an extension to make random pages open and am currently trying to reproduce your issue.

**Comment by pipboy96** [comment]
@Pascal666 Do you have any other extensions installed?

**Comment by Pascal666** [comment]
From the Extensions tab of chrome://system/

ahfgeienlihckogmohjhadlkjgocpleb : Web Store : version 0_2
apdfllckaahabafndbhieahigkjlhalf : Google Drive : version 14_1
blpcfgokakmgnkcojhhkbfbldkacnbeo : YouTube : version 4_2_8
cjpalhdlnbpafiamejdnhcphjbkeiagm : uBlock Origin : version 1_18_10
dgefbojfgdddnignhmfmnencgiloojpe : Turkopticon : version 3_41
dhdgffkkebhmkfjojejmpbldmpobfkfo : Tampermonkey : version 4_8
edacconmaakjimmfgnblocblbcdcpbko : Session Buddy : version 3_6_3
emehklffcaphknhhfhadkjhpfapcbpco : Strong Password Generator : version 1_6
fheoggkfdfchfphceeifdbepaooicaho : McAfee® WebAdvisor : version 6_0_0_25011
figkapeodjhdgnpiamleongcmecfjccb : Stop Autoplay for Youtube™ : version 4_1_0
gcbommkclmclpchllfjekcdonpmejbdp : HTTPS Everywhere : version 2019_1_31
gdbofhhdmcladcmmfjolgndfkpobecpg : Don't track me Google : version 4_22
gfdkimpbcpahaombhbimeihdjnejgicl : Feedback : version 1_0
iglbakfobmoijpbigmlfklckogbefnlf : MTurk Suite : version 2_6_8
impiikfnffjblkkefnplfonianmboaam : Call From Browser : version 1_44_0
jgpmhnmjbhgkhpbgelalfpplebgfjmbf : Smile Always : version 0_93
jnjfeinjfmenlddahdjdmgpbokiacbbb : Quick Tabs : version 2019_2_27
kbfnbcaeplbcioakkpcpgfkobkghlhen : Grammarly for Chrome : version 14_905_2163
klbibkeccnjlkjkiokjodocebajanakg : The Great Suspender : version 7_0_109
kmendfapggjehodndflmmgagdbamhnfd : CryptoTokenExtension : version 0_9_74
lcfdefmogcogicollfebhgjiiakbjdje : Disable Extensions Temporarily : version 1_0
mfehgcgbbipciphmccgaenjidiccnmng : Cloud Print : version 0_1
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
nakplnnackehceedgkgkokbgbmfghain : Fakespot - Analyze Fake Amazon Reviews : version 0_5_3
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
niloccemoadcdkdjlinkgdfekeahmflj : Save to Pocket : version 3_0_6_1
njabckikapfpffapmjgojcnbfjonfjfg : cookies.txt : version 1_14_1
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_12
nkgllhigpcljnhoakjkgaieabnkmgdkb : Don't Fuck With Paste : version 2_5
nmmhkkegccagdldgiimedpiccmgmieda : Chrome Web Store Payments : version 1_0_0_4
occjjkgifpmdgodlplnacmkejpdionan : AutoScroll : version 4_10
ocfjjjjhkpapocigimmppepjgfdecjkb : Storage Area Explorer : version 0_4_2
ocpcmghnefmdhljkoiapafejjohldoga : Context Menu Search : version 2_93
oiillickanjlaeghobeeknbddaonmjnc : RECAP : version 1_2_11
olfiakiemgabphalhjfjbcmganhfkbcg : Screen Recorder : version 0_18
pjkljhegncpnkpknbcohdijeoejaedia : Gmail : version 8_1
pkedcjkdefgpdelpbcmbmeomcjbeemfm : Chrome Media Router : version 7319_128_0_1
pncabnpcffmalkkjpajodfhijclecjno : Password Checkup : version 1_10
pnjaodmkngahhkoihejjehlcdlnohgmp : RSS Feed Reader : version 7_6_2

**Comment by pipboy96** [comment]
@Pascal666 Can you try disabling all extensions except HTTPS Everywhere and verify that the leak still exists? (I am currently trying to reproduce by myself, but still, please do)

**Comment by Pascal666** [comment]
What extension are you using to open random pages?

Is there some debug info I can get from HTTPSE that would help?

**Comment by pipboy96** [comment]
@Pascal666 https://noiszy.com

I doubt you can, currently, the extensions can't see how much memory they consume.

**Comment by pipboy96** [comment]
@Pascal666 On the off chance you still have the browser with 1GB memory consumption by HTTPS Everywhere open, please tell me. Currently I can't reproduce, the memory consumption is steady at ~100MB after hour or so of auto browsing.

**Comment by pipboy96** [comment]
Apparently there is a way to make a memory usage snapshot of the extension, so @Pascal666 please tell me if you will run into this bug and **don't close the browser**.

**Comment by Pascal666** [comment]
So how do I make that snapshot?

**Comment by pipboy96** [comment]
1. chrome://extensions/
1. Developer mode -> on
1. HTTPS Everywhere -> background page
1. Memory
1. Take snapshot

**Comment by Pascal666** [comment]
Chrome history shows I visited around 4000 web pages in the past 10 days.  Looks like Noiszy takes one action per minute, and that action is not necessarily loading a new page.  At that rate, it would take at least 3 days.

**Comment by Pascal666** [comment]
I believe I was able to reproduce the problem with only HTTPSE loaded.  I didn't run it all the way up to 1GB, but I can see its memory usage steadily increasing.  I loaded facebook.com, then clicked with the scroll wheel on my mouse and dragged the cursor to the bottom of the page.  This enabled auto scrolling.  I checked the memory usage occasionally on the extension's background page and can see it steadily increasing.  If you don't have a clickable scroll wheel, there are auto-scroll extensions or you can hold down the end key.

**Comment by pipboy96** [comment]
@Pascal666 I see the memory usage growing, but nowhere nearly as dramatically.

**Comment by pipboy96** [comment]
I was unable to get memory usage go over 200 MB after running auto browsing for a few hours.

**Comment by Pascal666** [comment]
It is my understanding that HTTPSE's memory usage should never increase.  It sounds like you were able to reproduce the problem.  Were you able to get a snapshot and see where the extra RAM is going?

**Comment by pipboy96** [comment]
@Pascal666 After some point, yes, it should not.

**Comment by zoracon** [comment]
Memory usage can vary but overall (depending on what's on or off in the settings on the extension) there should be a cap and not going towards 1GB at the very least. That being said, this is not something readily fixable on the extension side. We can optimize the code, that is clear. But I doubt what is causing that 1GB profile is from HTTPS Everywhere without knowing what else was in that 1GB capture. The 10 hour run of browsing isn't reasonable reproduce on our end but @pipboy96 thank you for testing this as well for a few hours.

**Comment by Giltyhub** [comment]
Maybe you have some special configuration that leads to this bug, can you @Pascal666 go to the addons part of your browser and go to the settings of HTTPS Everywhere and see if there are any site exceptions? (exceptions appear under "General Settings")

**Comment by Pascal666** [comment]
The only options I see under General Settings are two checkboxes labeled " Show Counter" and "Auto-update rulesets".

**Comment by pipboy96** [comment]
@Pascal666 Try uninstalling the extension and reinstalling it again.

**Comment by Pascal666** [comment]
Brand new install of HTTPSE 2019.1.31 on Chrome Version 71.0.3578.98 (Official Build) (64-bit) on CentOS Linux release 7.6.1810 (Core) also shows only these two options.

**Comment by pipboy96** [comment]
@Pascal666 I meant that there's probably no "reset everything" option yet, you have to reinstall the extension.

**Comment by pipboy96** [comment]
@Pascal666 If you notice this bug again please tell.
