### ISSUE TITLE
What is the function of the release branch?

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#17677]
Type: other

#17672 got me thinking: what is the function of the `release` branch? To me it sounds highly redundant with the git release tags.

If it serves no purpose, it might be easier to delete it. It would prevent new contributors from being confused about which branch they should target it their PR (as in #17672).

**Comment by pipboy96** [comment]
It always points to the last release.

**Comment by Hainish** [comment]
The `release` branch is a predictable place for the [Atlas](https://atlas.eff.org/) to look for the latest release, which it needs in order to tell what's new as compared to `master`
