### ISSUE TITLE
Default "Microsoft (partial)" filter still breaks Netflix 

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#1767]
The default filter **Microsoft (partial)** breaks the loading of the DRM system used by Netflix, so no videos can be played and non-technical users are unable to find the source of the problem. It should be disabled until Netflix stops using Silverlight.

Related: [#373](https://github.com/EFForg/https-everywhere/issues/373) and [#442](https://github.com/EFForg/https-everywhere/issues/442)

**Comment by draeath** [comment]
Noting that this bug is still present, and the workaround (disabling this filter) difficult to find.

**Comment by semenko** [comment]
Is this still true? Does netflix still use Silverlight? (I can't seem to repro this now)

**Comment by anewuser** [comment]
> Today we’re excited to announce the availability of our HTML5 player in Firefox! Windows support is rolling out this week, and OS X support will roll out next year.

http://techblog.netflix.com/2015/12/html5-video-is-now-supported-in-firefox.html

**Comment by rugk** [comment]
Also notice [this discussion](https://github.com/EFForg/https-everywhere/issues/2258#issuecomment-168034035). It is claimed the Microsoft filter would not show up when you visit a site which uses Silverlight (e.g. Netflix).
But AFAIK HTTPS-E shows all rulesets it applies, so I do not know whether this is possible.

Has anyone of the collaborators a idea?

**Comment by semenko** [comment]
Ok, so this impacts Firefox (Silverlight is dead on Chrome) -- perhaps only on Linux.

Glancing at the ruleset, area looks promising:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Microsoft.xml#L544

**Comment by rugk** [comment]
BTW Silverlight will be dead on Firefox soon too as Firefox [is depreciating NPAPI plugins](https://stackoverflow.com/questions/19011884/chrome-and-firefox-are-not-going-to-support-npapi-for-long-what-are-my-options) too.

**Comment by jeremyn** [comment]
Is this problem still active for anyone?

**Comment by gloomy-ghost** [comment]
Silverlight is already depreciated in Firefox
https://support.mozilla.org/en-US/kb/npapi-plugins
