### ISSUE TITLE
Improve UI to reflect what HTTPS Everywhere is actually doing

### ISSUE THREAD

**Issue by Gitoffthelawn** [EFForg/https-everywhere#17673]
Type: feature request

Would it be possible to update the UI in the dropdown (and the toolbar button's counter) to reflect what HTTPS Everywhere is actually doing?

An example will hopefully best illustrate this feature request:

Let's say the user goes to `https://www.site-1.com`, and that site makes connections to `https://www.site-2.com` and `https://www.site-3.com`.

In this case, HTTPS Everywhere should be doing nothing, since every connection is *already* being established via HTTPS (please correct me if I'm mistaken).

Yet, depending on the sites involved (and thus the HTTPS Everywhere rules), it is not uncommon for the HTTPS Everywhere UI in the dropdown (as well as the counter on the button) to show that HTTPS Everywhere is involved in 1 or more actions.

In these cases - **which nowadays is a majority of cases** -  I would like the HTTPS Everywhere UI to show that it did not do anything, and for the counter to reflect this as well.

Thanks for a great extension!  Your hard work is appreciated!

**Comment by pipboy96** [comment]
@Gitoffthelawn Thanks! We are already working on UI redesign in #17068 and #16669.

**Comment by Gitoffthelawn** [comment]
@pipboy96 Thanks! I see that there is a lot going on there.  Is there anything appropriate to do so that the ideas I posted are considered in the redesign efforts?

**Comment by pipboy96** [comment]
@Gitoffthelawn Please post in https://github.com/EFForg/https-everywhere/issues/17068.
