### ISSUE TITLE
Default Lotus (partial) breaks lotus.com site

### ISSUE THREAD

**Issue by jarihu** [EFForg/https-everywhere#1769]
Using version 5.0.4 and default rulesets. When trying to access URL: 
https://www-10.lotus.com/ldd/nd85forum.nsf/DateAllFlatWeb/73fd5558d147b0bc852579e900344f7c?OpenDocument
 it ends up in never-ending reload loop.
When disabling Lotus (partial) ruleset, the site loads properly. 
(edit: Firefox 38.0.1, Win7)

**Comment by J0WI** [comment]
the site has som evil inline JS:
```
if (window.location.protocol == "https:") {
var host = window.location.hostname;
var pathname = window.location.pathname;
var search = window.location.search;
var url = "http://" + host + pathname + search;
location.replace(url);
}
```
We could make an exclude for ```http://www-10.lotus.com/ldd/*```
