### ISSUE TITLE
HTTPS not forced on s3.us-east-2.amazonaws.com , but AmazonWebServices shows checked

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#17717]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #

Type: ruleset/website issue

[//]: # (Uncomment and fill the domain bellow if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)
http://s3.us-east-2.amazonaws.com/index/
Domain: s3.us-east-2.amazonaws.com

![image](https://user-images.githubusercontent.com/5124946/56061045-6aa00580-5d36-11e9-9ba3-725c9ff84181.png)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by pipboy96** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/AmazonAWS.com.xml

This ruleset needs to be rewritten, and name should be changed to the one that makes more sense.

**Comment by pipboy96** [comment]
Related: https://github.com/EFForg/https-everywhere/issues/17912.
