### ISSUE TITLE
HTTPS-E should defer all network activity at the start until it loads up

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#17716]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

when first starting firefox nightly+https-e on a vm with low amount of ram+cpu resources and then loading up a website that has an https everywhere ruleset and that i expected to immediately go to https but was instead loading up over http

noscript webextension does something like that if i remember

**Comment by pipboy96** [comment]
That's unlikely to be possible because of how WebExtensions is working. Same issue exists with uB0 and PB.

**Comment by pipboy96** [comment]
Easiest way to reproduce: close all browser windows, make sure the browser is no longer running and run this: `firefox -- http://s3.amazonaws.com/abcd/efgh`. This request should be rewritten by default rulesets, but it is not rewritten.

**Comment by Hainish** [comment]
There are two separate issues here:

1. URLs that load before the extension itself loads
2. URLs that are loaded after the extension loads, but before the rulesets are loaded

It is only possible to fix (2) in WebExtensions.

**Comment by pipboy96** [comment]
I'll try making a PR.
