### ISSUE TITLE
HTTPS Everywhere displaying in Arabic

### ISSUE THREAD

**Issue by SteveMawrCymraeg** [EFForg/https-everywhere#1773]
Firefox extension HTTPS Everywhere is displaying almost completely in what I think is Arabic (I don't know Arabic, so can't be sure)

My installation of Firefox (version 38.0.1, Welsh interface) was installed on my newly rebuilt laptop yesterday (64-bit Windows 7 Enterprise sp1).  All the text (apart from words like "HTTPS Everywhere", "HTTP", "HTTPS", and "SSL") is in Arabic, including the Options and SSL Observatory dialog.  I speak Welsh, and my locale is "cy" for Cymraeg.

Here are some images:
![2015-05-25_114643](https://cloud.githubusercontent.com/assets/12607049/7807970/6e975e02-0387-11e5-888e-21e53ee5fe5e.gif)
![2015-05-25_114644](https://cloud.githubusercontent.com/assets/12607049/7807971/6e9dca76-0387-11e5-987f-ccdad8a2f92d.gif)
![cropimage](https://cloud.githubusercontent.com/assets/12607049/7807973/6ee87062-0387-11e5-8746-e7b77f1d12fa.gif)

I emailed https-everywhere-owner@lists.eff.org to report this, and Seth David Schoen kindly replied, noting:
"My hypothesis would be that the translation-parsing code got confused by
your Welsh locale and, instead of falling back to English in the case of
an unknown locale, fell back to the alphabetically first locale in its
list, which is Arabic ("ar") rather than English ("en")."

**Comment by reedy** [comment]
Yup, it's a fallback issue, with Welsh not being supported and it's already been fixed.

See also #1729
