### ISSUE TITLE
Ruleset Release 2019.4.16

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#17744]
Type: other

As requested in #17641, alerting Ruleset maintainers and others interested in the last hash before a ruleset release is issued.

Git commit hash of master HEAD: 5ef57c31b37692a1a57bf021533b6b190304a58a

@Bisaloo @cschanaj @J0WI @pipboy96

**Comment by pipboy96** [comment]
@zoracon Can you simply add this info into the ruleset file?

**Comment by zoracon** [comment]
> @zoracon Can you simply add this info into the ruleset file?

Wanted public record of response to the previous issue opened  (#17641). But we could potentially add that in for future ruleset releases.
