### ISSUE TITLE
In EASE mode the warning page is shown when clicking on Esc

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#17774]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Suppose you wanted to go to youtube.com but instead wrote youube.com so you quickly click on Esc, but then with EASE mode the warning is shown, can't there be some sort of 5s timeout at least?

**Comment by pipboy96** [comment]
@Giltyhub Can you explain what pressing <kbd>Esc</kbd> is supposed to do?

**Comment by Giltyhub** [comment]
@pipboy96 it stops the loading of the website

**Comment by pipboy96** [comment]
@Giltyhub In which browser? Pressing <kbd>Esc</kbd> didn't stop the loading on FF Nightly.

**Comment by Giltyhub** [comment]
@pipboy96 tor browser

**Comment by pipboy96** [comment]
@Giltyhub Can reproduce now. Most likely reason is that local extension page takes almost no time to load.

**Comment by pipboy96** [comment]
low priority since this bug is cosmetic only and doesn't actually cause any malfunction.

**Comment by Giltyhub** [comment]
@pipboy96 it's not just cosmetic, it's a very noticeable nuisance, whenever I make a typo for a website and (without clicking on Esc) i go back to the url bar and correct it and press enter I end up with that page and so i have to retype the url again

**Comment by pipboy96** [comment]
@Giltyhub Currently I don't know how to fix this bug. I need to take a closer look on it.
