### ISSUE TITLE
Add ability to edit and/or delete user-created rules

### ISSUE THREAD

**Issue by TriMoon** [EFForg/https-everywhere#1779]
I just noticed im unable to manually edit the used rulesets.
I made a custom rule using the current interface, but made a mistake, now i can't edit that rule only disable it... i mean really??

Anyway the reason i made (tried), was because i needed to make an exception for:"avatar-user.s.aeriastatic.com"
This is being used on the aeria games forums to display user images.
The domain "avatar-user.s.aeriastatic.com" is providing a certificate that belongs to " a248.e.akamai.net", which means it is blocked due to wrong sequrity certificate...

**Comment by reedy** [comment]
Can you edit them in FF?

**Comment by jsha** [comment]
Yes, although the FF mechanism is very different: You directly edit XML files in a special subdirectory of your Firefox profile. The Chrome version is more user-friendly and accessible but lacks some features that are fairly necessary to use it well.

**Comment by reedy** [comment]
Ah, I wasn't sure if this was some addition in the GUI somewhere

Tagging #1681

**Comment by gloomy-ghost** [comment]
We are now using the same codebase for Firefox, so I edited the title to reflect on this.
(Also deleting the comment from https-everywhere-bot since it's malfunctioning...)

**Comment by Hainish** [comment]
User-created rules can be deleted - @gloomy-ghost am I missing something here?  Closing issue.
