### ISSUE TITLE
data.gov.uk - https everywhere breaks some download links

### ISSUE THREAD

**Issue by caglarkoksal** [EFForg/https-everywhere#17845]
Type: ruleset/website issue

Domain: https://data.gov.uk/dataset/d7fcc345-6028-4266-836c-1d7cc6b034c5/english-local-authority-green-belt-dataset

Trying to download data from UK government's website. Data in question is titled "2017-18 Boundaries - Geoserver shapefile download". When HTTPS Everywhere is on, it returns an error:

> Not Found
> 
> The requested URL /geoserver/dclg_inspire/ows was not found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request. 

If I turn HTTPS Everywhere off just for this site, I still receive the same error. Only after I disable HTTPS Everywhere completely then I can download the data. Other links to data on different subpages of data.gov.uk work fine. Thanks.

**Comment by Bisaloo** [comment]
Thanks for your report! 

The issue is actually with the domain `maps.communities.gov.uk`. Submitting a fix now.
