### ISSUE TITLE
HTTPS-Everywhere website handshake flaw

### ISSUE THREAD

**Issue by TNTBOMBOM** [EFForg/https-everywhere#17851]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type:Check website handshake,cipher,protocol..etc before confirming its safe to connect to

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

I dunno if this ticket related to HTTPS-Everwhere or browser level flaw or it just wont get fixed because of the difficulty: 

https://trac.torproject.org/projects/tor/ticket/30335

-------------------------------

Aside from this issue when im typing my issue it says on the top:

>  Request a feature to help us improve HTTTP Everywhere. If this doesn’t look right, choose a different type. 

HTTTP Everywhere? minor typo to be fixed.

**Comment by pipboy96** [comment]
HTTPS Everywhere doesn't have access to SSL protocol info. Sorry.
