### ISSUE TITLE
New chrome extension reloads page unnecessarily

### ISSUE THREAD

**Issue by catthou** [EFForg/https-everywhere#17866]
Type: code issue

The new chrome extension was pushed to me today and it keeps reloading the page when I'm trying to change settings. This is super annoying on video pages where the video restarts every time.

The page reloads anytime the area "Settings for this site" is clicked. You can click on the gear icon, the text header, the text description, the background, the "see more" drop-down menu button... anywhere, and the page refreshes even though no settings have been changed.

**Comment by pmo13224s** [comment]
Same issue in Firefox: clicking anywhere in "settings for this site" box refreshes the page.

**Comment by zoracon** [comment]
Writing as a note to myself for debugging: This refresh issue seems to occur on sites with rules listed under the "Stable Rules" section.

**Comment by cschanaj** [comment]
@zoracon this sounds like a regression of the new UX due to #15532 which delegate all click actions to the parent elements.
