### ISSUE TITLE
Clicking on a link on the warning page turns to the infinite loop

### ISSUE THREAD

**Issue by alex65536** [EFForg/https-everywhere#17881]
Type: code issue

When I opened an http-only website, the following warning is shown:

![image](https://user-images.githubusercontent.com/25226083/57164105-bb69c200-6dfb-11e9-8ae1-f6a839e39bce.png)

When I click to the link on this page (not to the button "Open insecure page"), nothing happens: I am getting the redirect to the same page again.

Also I can't get the intended difference between these two options (clicking on a link and clicking on "Open insecure page button).

**Comment by zoracon** [comment]
This is expected behavior with the UX tweak. The URL text is now meant to show where you are trying to navigate to, and the button is the action to go to that url. 

I see that this can cause confusion since the link text is still written as hyperlinked mark up.

**Comment by zoracon** [comment]
I have unlinked the text so users focus on the button. Thank you for flagging this.
#17911
