### ISSUE TITLE
Options UI "HTTPS Everywhere Sites Disabled" list not updated

### ISSUE THREAD

**Issue by bershanskiy** [EFForg/https-everywhere#17880]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

# Options UI "HTTPS Everywhere Sites Disabled" list not updated if UI is already opened and user adds new domain via Popup interface

## Summary
Options UI "HTTPS Everywhere Sites Disabled" list is updated only when UI is opened. If user adds a site to that list after UI is opened, it will not be displayed until the UI is re-opened again.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

## Reproduction steps
1. Open extension Options, e.g.
    > chrome://extensions/?options=gcbommkclmclpchllfjekcdonpmejbdp

    and some site where HTTPS Everywhere is enabled (make sure domain in not in "HTTPS Everywhere Sites Disabled" list).
2. Disable HTTPS Everywhere on that site via the Popup UI
3. Go back to extension Options, look for the domain in "HTTPS Everywhere Sites Disabled" list. It is not there (bug).
4. Now, close the Options UI and reopen it again. Now the new domain name will appear in the list.

## Expected result
On step 3, the newly added domain is displayed without closing the UI and reopening it.

**Comment by cschanaj** [comment]
AFAIK, this is the expected behavior since the content is only loaded when the Option page is loaded. There is no AJAX or timer to keep the page sync-ed with the internal storage.

**Comment by bershanskiy** [comment]
@cschanaj Thanks for your response
> this is the expected behavior since the content is only loaded when the Option page is loaded.

This is true, the script loads the list in `getOption_("disabledList", [], function(item) {/* display list */}`.

>  There is no AJAX or timer to keep the page sync-ed with the internal storage.

We don't need a times, we can use the provided [chrome.runtime.onMessage](https://developers.chrome.com/extensions/runtime#event-onMessage) and update the list when needed, namely when popup UI calls `sendMessage("disable_on_site", url.host)` and `sendMessage("enable_on_site", url.host)`.

I actually started implementing this with `chrome.runtime.onMessage`, but found it too tiresome because there are plenty different events to consider (e.g., popup UI uses `sendMessage` in 12 places total -- and about 8 of these events might need to be reflected in the Options UI). That's a fair amount of work, but it's totally doable. If you (@cschanaj and other maintainers) find this a worth-while feature, I can prepare a PR. However, first I wanted to get some feedback for #17882, to avoid doing the same work twice if UI reorganization goes forward.
