### ISSUE TITLE
"Reset to Defaults" button should not be under "Settings for this site"

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#17885]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

This is a global settings and not limited to the site scope. Clicking on this button will reset the on/off states of all rulesets (except custom rulesets) to the defaults and affect all sites. It is a bit misleading to put it under "Settings for this site" 

cc @zoracon

**Comment by Hainish** [comment]
Good catch, this should be prioritized for before next release.
