### ISSUE TITLE
Reorganize Options UI "General Settings" and "Advanced Settings"

### ISSUE THREAD

**Issue by bershanskiy** [EFForg/https-everywhere#17882]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

This is a proposal to reorganize the Options UI of the extension, the provided images are just rough sketches of the logical structure and not style (I changed only HTML, but left CSS the same).

## Current UI

The UI height changes based on the tab (and for "General Settings", even the number of disabled domains in the list). this causes UI to jump whenever a tab is hanged or domain is deleted from "disabled" list. I propose that the UI occupies the same amount of vertical space for all tabs.

### General Settings
![General Settings](https://user-images.githubusercontent.com/45960703/57164680-812c0080-6dba-11e9-8f73-a313a69dfd39.png)

#### Issues:
1. The distinction between "General" and "Advanced" settings is unclear.
2. "Show counter" might be unnecessary as noted [here](https://github.com/EFForg/https-everywhere/issues/17868#issuecomment-489178104)
3. If the "sites disabled" and "custom rules" lists are long, they get hard to navigate.
4. In Chrome, when page gets too long, the whole page becomes scroll-able, including the tab buttons, which seems unnatural (tab buttons should always stick to the top).

### Advanced Settings
![Advanced Settings](https://user-images.githubusercontent.com/45960703/57164759-b8021680-6dba-11e9-8ce6-bae891a0583b.png)

#### Issue:
1. The distinction between "Advanced" and "General Settings" is unclear. 

## Proposal
1. Make all tabs have the same height by making the UI fill all vertical space.
2. Make the tab buttons smaller and fixed to the top of the page.
3. Move "HTTPS Everywhere Sites Disabled" list and "User rules" form "General Settings" into separate tabs.
4. Move all check boxes from "General Settings" and "Advanced Settings" onto the same tab called just "General Settings" or similar.
5. For each checkbox item add a small explainer about what exactly it does (to clarify the impact of the setting and to fill up the extra vertical space).

### Result (work in progress)

Edit: Please see pull request #17896 for up-to-date information. That PR also includes code necessary for a "Dark Mode".

I would like to hear you feedback and possible improvements. If this sounds like a reasonable idea, I can implement this change and create a pull request for review.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by meelten** [comment]
I wasn't even aware of this advanced settings. What "enable mixed content" do exactly? Should it be on or off?

**Comment by bershanskiy** [comment]
@meelten 
> What "enable mixed content" do exactly?

It is a setting that is applicable only to the Tor Browser (not Firefox and Chrome). You can read up on it int the [docs](https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/rulesets.md#mixed-content-blocking-mcb). You actually brought up a good point: since the setting does not do anything on Chrome and Firefox may be it should be removed from the UI altogether and the corresponding rulesets should not be loaded into the memory at all.

**Comment by Bisaloo** [comment]
Mixed content rulesets actually refer to rulesets that, when enabled, might break part of the related website UI due to [mixed content blocking](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox). But some users might have other extensions to mitigate this issue and/or decide that the gain in security (more website are covered by HTTPS Everywhere) is worth the possible breakage and choose to enable these rulesets.

This setting is actually valid in any browser.

**Comment by J0WI** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
