### ISSUE TITLE
Firefox 66.0.3 disables and will not install HTTPS everywhere

### ISSUE THREAD

**Issue by alinen** [EFForg/https-everywhere#17895]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by sbrl** [comment]
Are you sure that's not [this issue](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4)?

**Comment by alinen** [comment]
I think it is. I wanted to make sure you were aware of it since I had not
yet seen a resolution online. Thanks for the response!

**Comment by J0WI** [comment]
Please have a look at https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
