### ISSUE TITLE
Toggle from OFF to ON do not change the description

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#17891]
Toggling from OFF to ON do not change the description from "HTTPS Everywhere is OFF" to "HTTPS Everywhere is ON". Though the reverse is ok.  

[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by zoracon** [comment]
Did the window close for you a second after toggling ON to OFF? Or not at all?

**Comment by cschanaj** [comment]
Yes, the extension popup did close about a second afterward. 

I think #17919 will fix this, please take a look if you have the time. thanks.
