### ISSUE TITLE
The space between "see more" and the arrow doesn't open the menu

### ISSUE THREAD

**Issue by j-james** [EFForg/https-everywhere#17893]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

In the popup menu, clicking on the space between "See more" text and the arrow doesn't open the dropdown menu. Additionally, the "Settings for this site" blank space is affected by #17892.

Firefox Developer Edition 67.0b12, Manjaro 18.0.4 Illyria

**Comment by zoracon** [comment]
This has been patched with #17911
