### ISSUE TITLE
Popup UI overflows on Firefox

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17903]
<img width="1440" alt="Screenshot 2019-05-05 at 13 52 14" src="https://user-images.githubusercontent.com/46632672/57192804-240c8800-6f3d-11e9-9d37-de05272ca230.png">

This behavior happens if either or both of collapsibles are expanded.

**Comment by Bisaloo** [comment]
I get a scrollbar with FF Nightly.

**Comment by zoracon** [comment]
On which computer screen size is this? I don't get overflow or scroll at all on Firefox

**Comment by pipboy96** [comment]
@zoracon MacBook Air Late 2018.

**Comment by zoracon** [comment]
Okay. Hopefully my white space reductions solve this issue.

**Comment by zoracon** [comment]
@pipboy96 Is there still overflow for you with the new release? (2019.5.6.1)

**Comment by pipboy96** [comment]
@zoracon No, except of the cases when there are many rulesets triggered.

**Comment by zoracon** [comment]
@pipboy96 The overflow with rules is expected behavior. But thanks for checking with the initial pop up. Closing this now.
