### ISSUE TITLE
Patch Release: 2019.5.6

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#17901]
Type: Patch Release

The following will be addressed with this patch.

- Offline file's signature is incorrect due to a mistake during the release process to AMO (Mozilla Add-ons). This is top priority
- #17866
- #17867
1. White space
2. Button Size
3. See more feature
4. Header size adjustment

Will try to get this out with the UI tweaks EOD, but the offline XPI file is the main focus for this patch. Please refrain from using this as a forum for more issues with the new UI and refer to the issues already opened.

**Comment by Bisaloo** [comment]
The UI has already greatly improved compared to the previous version IMO. Thanks for your work on this!

**Comment by zoracon** [comment]
@Bisaloo Thank you!
