### ISSUE TITLE
Popup info is showing opposite of actual status

### ISSUE THREAD

**Issue by gms77** [EFForg/https-everywhere#17918]
Type: code issue

When showing the popup from the toolbar icon it shows the incorrect status, ie HTTPS Everywhere is OFF when it is on.  The same problem with EASE mode.

Tested in both Firefox 67 Beta and last stable Chromium.

![Screenshot_20190507_165742](https://user-images.githubusercontent.com/15159047/57314582-d719e480-70e9-11e9-8886-708e98e1be77.jpg)

**Comment by zoracon** [comment]
When you turn these on and off. Does the pop-up window close for you a second afterward? Or not at all?

**Comment by gms77** [comment]
Yes, the popup closes after toggling on or off.

**Comment by gms77** [comment]
With the popup open, clicking on EASE to ON reloads the page and says "Encrypt all sites eligible is ON".  Then toggle EASE to OFF and clicking away from the popup then opening the popup again says "Encrypt all sites eligible is ON".

Actually, clicking the EASE toggle does not close the popup.  Only the main ON/OFF toggle closes the popup.

**Comment by pipboy96** [comment]
For me it's just stuck on OFF, slider position does not affect the text.

**Comment by pipboy96** [comment]
Closed #17919.
