### ISSUE TITLE
Patch Release 2019.5.13 forthcoming

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#17944]
Type: release

This will be another patch release addressing the following as priority:
- Translation errors (Fixed with #17942, #17919)
- Stable rules bugs (#17916, Fixed with #17917, #17954)
- Unit test for ruleset toggle (#17952)

Will try to also fix the following:
CSS animation flaw with EASE toggle

**Comment by cschanaj** [comment]
#17907 is a trivial fix on the hsts-prune utility. would you take a look on that?

**Comment by zoracon** [comment]
Release is out
