### ISSUE TITLE
Latest ruleset on https://www.https-rulesets.org/v1/ is out-of-date compared to the one in the latest extension

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#17958]
I updated the HTTPS Everywhere ruleset bundled in the Brave browser and then ran into problems testing it.

I first tried to see if http://www.redferret.net would get upgraded since that was [recently fixed](https://github.com/EFForg/https-everywhere/commit/19746d128d820f5f0ab14f9b83cf696bbbd03ed6) but that didn't work.

I also tried: http://www.didierstevens.com unsuccessfully even though it was [supposed to be in there](https://github.com/EFForg/https-everywhere/commit/d1cc4c6fecbc5434d756cfea1e0b820594f35402).

Looking at https://www.https-rulesets.org/v1/, I see that the timestamp on all of the rulesets is 2019-04-25. Indeed, if I download the [latest ruleset](https://www.https-rulesets.org/v1/default.rulesets.1556228316.gz) according to https://www.https-rulesets.org/v1/latest-rulesets-timestamp, it's not up to date.

The above two domains are however in the ruleset bundled in the [latest XPI](https://www.eff.org/files/https-everywhere-2019.5.13-eff.xpi).

Is there an infrastructure problem or are the rulesets no longer available from https://www.https-rulesets.org/v1/?

**Comment by zoracon** [comment]
@fmarier Looks like we need to run a ruleset release for everything to be in sync and purge the cache on that url. Thanks for bringing this to attention.

**Comment by zoracon** [comment]
@fmarier A fresh ruleset release is out, let me know if you see the updated rulesets

**Comment by pipboy96** [comment]
Ruleset update seems to be successful.

**Comment by fmarier** [comment]
Indeed, it's working for me now. Thanks!
