### ISSUE TITLE
Unicode characters in test URLs cause test failure

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#17978]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

https://github.com/EFForg/https-everywhere/pull/17971

https://travis-ci.org/EFForg/https-everywhere/jobs/534196627

**Comment by pipboy96** [comment]
The current version of the file no longer contains any non-7-bit ASCII characters.

**Comment by pipboy96** [comment]
oops, sorry.

**Comment by pipboy96** [comment]
What I perceive as a correct solution is urlencoding your string. I may be wrong though.
