### ISSUE TITLE
"A response to feedback on the proposed changes in Manifest V3" from the Chrome team

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#18030]
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/veJy9uAwS00%5B1-25%5D

RIP HTTPS-E (for Chrome)

(btww I had to make a new issue since the other one was limited to collaborators)

**Comment by Giltyhub** [comment]
Comments by gorhill: https://github.com/uBlockOrigin/uBlock-issues/issues/338#issuecomment-496009417

**Comment by pipboy96** [comment]
I have just unlocked the issue (https://github.com/EFForg/https-everywhere/issues/17268) for you. I also suggest you to ask @zoracon for a position as ruleset reviewer, which you already deserve (in my opinion) and that will allow you to post in locked issues and unlock them.

**Comment by pipboy96** [comment]
Related: https://www.youtube.com/watch?v=JS_OUMdwaTE.

**Comment by andresbase** [comment]
We are following this issue closely and thinking on how to proceed. Thanks!

**Comment by pipboy96** [comment]
@andresbase Lock conversation?

**Comment by pipboy96** [comment]
Closing since this is effectively a duplicate.
