### ISSUE TITLE
Add https://antennapod.org

### ISSUE THREAD

**Issue by Grossdm** [EFForg/https-everywhere#18042]
I'm sure this would be easier if your markup were anything like what I've seen on GitHub before. 🤷‍♂️

Specifically, you should have a method within the addon to report websites that can (and will) load with HTTP, but that have valid SSL certificates.

I'm really not sure what will happen with this issue, given the puzzling markup.

**Comment by pipboy96** [comment]
@Grossdm This markup is leftover from time we had a bot automatically assigning labels to issues. You may ignore it completely.

**Comment by pipboy96** [comment]
Done: #18043.

**Comment by Grossdm** [comment]
@pipboy96, so do you have no thoughts on my suggestion to allow simple reports from the addon?

The only things that I see when I try to look into the addon are options for, and documentation regarding, the creation of rulesets.

**Comment by pipboy96** [comment]
@Grossdm Can you create another issue detailing the functionality you want?

**Comment by Bisaloo** [comment]
@Grossdm, is this what you have in mind? https://github.com/EFForg/https-everywhere/issues/6322

**Comment by Grossdm** [comment]
@Bisaloo, yes that appears to be what I had in mind.

As the discussion on #6322 is lengthy, I didn't read it all. It looks like my suggestion/feature request has been given due consideration, though.

Thank you!
