### ISSUE TITLE
Add some Mastodon instances

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#18046]
Instances list is taken from [instances.social](https://instances.social/).

**Be aware that some websites are NSFW!**

## Alexa top 1M

The number in parentheses is Alexa rank.

- [x] pawoo.net (18434)
- [ ] switter.at (53689)
- [ ] mstdn.jp (69517)
- [ ] humblr.social (82525)
- [ ] puri.sm (98927)
- [ ] dajiaweibo.com (101756)
- [ ] baraag.net (107513)
- [ ] eigadon.net (114019)
- [ ] peertube.video (132430)
- [ ] id.cc (196860)
- [ ] mstdn.guru (199356)
- [ ] mastodon.social (218187)
- [ ] aaronparecki.com (235251)
- [ ] artalley.porn (321294)
- [ ] imaginair.es (327886)
- [ ] mamot.fr (328168)
- [ ] octodon.social (402164)
- [ ] framapiaf.org (410234)
- [ ] mastodon.xyz (458761)
- [ ] ruby.social (485747)
- [ ] masthead.social (498430)
- [ ] todon.nl (504739)
- [ ] kinky.business (513003)
- [ ] librem.one (518558)
- [ ] catgirl.science (630489)
- [ ] nerdica.net (640454)
- [ ] nulled.red (666098)
- [ ] sleeping.town (667999)
- [ ] walkaway.space (669846)
- [ ] abdl.link (676626)
- [ ] chaos.social (707822)
- [ ] maxlaumeister.com (740222)
- [ ] infosec.exchange (752333)
- [ ] dentrassi.de (826598)
- [ ] nul.tokyo (921535)
- [ ] adult-game.dev (923585)
- [ ] berries.space (944243)
- [ ] chitter.xyz (952032)
- [ ] dragon.style (961013)
- [ ] fuckonthefirst.date (969565)
- [ ] mastodon.host (991477)

## The rest

Moved to https://gist.github.com/pipboy96/bde9ff68b8427fdcc9790b17b164cf89.

**Comment by cschanaj** [comment]
pawoo.net #9626

**Comment by ShenZhouHong** [comment]
mastodon.cloud #19176
