### ISSUE TITLE
Add some VPN services

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#18059]
VPN list is taken from [ThatOnePrivacySite.net](https://thatoneprivacysite.net/).

## Alexa top 1M
- [ ] whoer.net (10655)
- [ ] surfshark.com (27676)
- [ ] vpngate.net (28033)
- [ ] ipvanish.com (35343)
- [ ] vyprvpn.com (37600)
- [ ] vpnunlimitedapp.com (56088)
- [ ] vpnhub.com (64446)
- [ ] zoogvpn.com (141901)
- [ ] trust.zone (170805)
- [ ] ibvpn.com (172510)
- [ ] fastestvpn.com (178102)
- [ ] acevpn.com (188754)
- [ ] dotvpn.com (190702)
- [ ] zpn.im (192638)
- [ ] le-vpn.com (205438)
- [ ] seed4.me (219891)
- [ ] my-private-network.co.uk (237138)
- [ ] sigavpn.com (241815)
- [ ] defencevpn.com (248428)
- [ ] newshosting.com (263166)
- [ ] goosevpn.com (267576)
- [ ] anonymousvpn.org (268567)
- [ ] hide-my-ip.com (307140)
- [ ] buffered.com (311183)
- [ ] sumrando.com (312491)
- [ ] proxpn.com (389707)
- [ ] flyvpn.com (439069)
- [ ] virtualshield.com (626439)
- [ ] limevpn.com (641026)
- [ ] encrypt.me (692744)
- [ ] vip72.com (722584)
- [ ] unblockvpn.com (735161)
- [ ] cactusvpn.com (745158)
- [ ] tigervpn.com (759782)
- [ ] vpnuk.net (876431)
- [ ] ghostpath.com (886464)
- [ ] doublehop.me (960822)
- [ ] my-expat-network.com (996377)

## The rest
- [ ] activpn.com
- [ ] anonvpn.io
- [ ] beevpn.com
- [ ] blockless.com
- [ ] bolehvpn.net
- [ ] boxpn.com
- [ ] celo.net
- [ ] chillglobal.com
- [ ] citizenvpn.com
- [ ] cloakvpn.com
- [ ] crypticvpn.com
- [ ] cryptohippie.com
- [ ] faceless.me
- [ ] finchvpn.com
- [ ] flowvpn.com
- [ ] frostvpn.com
- [ ] gotrusted.com
- [ ] hideipvpn.com
- [ ] hotvpn.com
- [ ] identitycloaker.com
- [ ] in-disguise.com
- [ ] incognitovpn.com
- [ ] insorg.org
- [ ] intellivpn.net
- [ ] ipredator.se
- [ ] ironsocket.com
- [ ] libertyshield.com
- [ ] libertyvpn.net
- [ ] liquidvpn.com
- [ ] myip.io
- [ ] nextgenvpn.com
- [ ] nvpn.net
- [ ] octanevpn.com
- [ ] overplay.net
- [ ] privatepackets.io
- [ ] rootvpn.net
- [ ] securevpn.com
- [ ] securevpn.to
- [ ] shadeyouvpn.com
- [ ] slickvpn.com
- [ ] smartvpn.com
- [ ] tgvpncom.com
- [ ] torvpn.com
- [ ] totalvpn.com
- [ ] tvwhenaway.co.uk
- [ ] unseen.online
- [ ] unspyable.com
- [ ] vanishedvpn.com
- [ ] vpn.cc
- [ ] vpn.sh
- [ ] vpn4all.com
- [ ] vpnarea.com
- [ ] vpnaus.com
- [ ] vpnbaron.com
- [ ] vpnjack.com
- [ ] vpnland.com
- [ ] vpnme.com
- [ ] vpnshazam.com
- [ ] vpnshieldapp.com
- [ ] vpntraffic.com
- [ ] vpntunnel.com
- [ ] waselpro.com
- [ ] witopia.com
- [ ] worldvpn.net

## Completed
- [x] ~~expressvpn.com~~ (1481)
- [x] ~~nordvpn.com~~ (3529)
- [x] ~~zenmate.com~~ (4813)
- [x] ~~hola.org~~ (6776)
- [x] ~~safervpn.com~~ (8219)
- [x] ~~hide.me~~ (11451)
- [x] ~~hidemyass.com~~ (13450)
- [x] ~~windscribe.com~~ (14109)
- [x] ~~hotspotshield.com~~ (18049)
- [x] ~~privateinternetaccess.com~~ (18432)
- [x] ~~cyberghostvpn.com~~ (18974)
- [x] ~~protonvpn.com~~ (21206)
- [x] ~~tunnelbear.com~~ (26500)
- [x] ~~purevpn.com~~ (34825)
- [x] ~~astrill.com~~ (38213)
- [x] ~~riseup.net~~ (40510)
- [x] ~~betternet.co~~ (49340)
- [x] ~~vpnbook.com~~ (58553)
- [x] ~~speedify.com~~ (67266)
- [x] ~~disconnect.me~~ (73686)
- [x] ~~getflix.com.au~~ (80035)
- [x] ~~seedboxes.cc~~ (80624)
- [x] ~~privatevpn.com~~ (92971)
- [x] ~~torguard.net~~ (93196)
- [x] ~~unlocator.com~~ (93842)
- [x] ~~mullvad.net~~ (107946)
- [x] ~~smartdnsproxy.com~~ (111801)
- [x] ~~ivacy.com~~ (118876)
- [x] ~~airvpn.org~~ (130812)
- [x] ~~strongvpn.com~~ (147744)
- [x] ~~psiphon.ca~~ (154216)
- [x] ~~ovpn.com~~ (168987)
- [x] ~~privatetunnel.com~~ (204759)
- [x] ~~frootvpn.com~~ (230299)
- [x] ~~surfeasy.com~~ (254494)
- [x] ~~ivpn.net~~ (292665)
- [x] ~~unblock-us.com~~ (320017)
- [x] ~~vpn.ht~~ (324375)
- [x] ~~torrentprivacy.com~~ (436240)
- [x] ~~steganos.com~~ (439765)
- [x] ~~hideallip.com~~ (480920)
- [x] ~~ovpn.to~~ (506761)
- [x] ~~anonymizer.com~~ (593878)
- [x] ~~getfoxyproxy.org~~ (594894)
- [x] ~~anonine.com~~ (939233)
- [x] ~~azirevpn.com~~
- [x] ~~blackvpn.com~~
- [x] ~~btguard.com~~
- [x] ~~cryptostorm.is~~
- [x] ~~earthvpn.com~~
- [x] ~~freedom-ip.com~~
- [x] ~~integrity.st~~
- [x] ~~onevpn.com~~
- [x] ~~perfect-privacy.com~~
- [x] ~~proxy.sh~~
- [x] ~~prq.se~~
- [x] ~~ra4wvpn.com~~
- [x] ~~secure.raynersw.com~~
- [x] ~~securitykiss.com~~
- [x] ~~switchvpn.net~~
- [x] ~~vikingvpn.com~~
- [x] ~~vpn.ac~~
- [x] ~~vpn.asia~~
- [x] ~~vpnsecure.me~~
- [x] ~~wifimask.com~~
- [x] ~~zorrovpn.com~~

**Comment by maxxdmg** [comment]
Hey I am going to work through the list!

**Comment by deno102** [comment]
Nord vpn command please
