### ISSUE TITLE
Regression in UX when HTTPSE is put in Firefox' Overflow Menu

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#18081]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Put HTTPSE in Firefox' Overflow Menu and you see that it isn't well aligned (this didn't happen with the previous UX)

**Comment by pipboy96** [comment]
@Giltyhub Can you make a screenshot?

**Comment by pipboy96** [comment]
<img width="1475" alt="Screenshot 2019-06-11 at 07 32 11" src="https://user-images.githubusercontent.com/46632672/59243975-4324c680-8c1b-11e9-89d0-502142ec93ea.png">
I don't see any overflow.

**Comment by Bisaloo** [comment]
I can reproduce. There is extra padding on the right.

![Screenshot from 2019-06-11 10-59-01](https://user-images.githubusercontent.com/10783929/59258534-70cc3880-8c38-11e9-94b1-5b89d799c985.png)

(don't pay attention to the fact the popup is dimming. I couldn't figure out how to take a good screenshot)

**Comment by pipboy96** [comment]
Can reproduce in current TB.

<img width="1112" alt="Screenshot 2019-06-11 at 12 23 18" src="https://user-images.githubusercontent.com/46632672/59260129-b6423300-8c43-11e9-9e62-9b09b24f994a.png">

My guess is that we will have to wait for TB to update. Latest FF Stable does not have this bug.

**Comment by Giltyhub** [comment]
@pipboy96 it happens even with Firefox Nightly on Linux, just don't forget to resize the browser to 1000x600 (just like TB)

**Comment by pipboy96** [comment]
@Giltyhub Can you create a bug in Mozilla's Bugzilla instance? We can't really fix this on our side.

**Comment by Giltyhub** [comment]
@pipboy96 I mean the previous design didn't have that problem, so I'm pretty sure this is fixable (since it's by definition a regression, and every regression is in theory fixable)

**Comment by pipboy96** [comment]
@Giltyhub The only way to fix it seems to be to reduce popup width. That would require changing the design.
