### ISSUE TITLE
Add some small free height in the HTTPSE' preferences to be compatible with Firefox' new about:addons

### ISSUE THREAD

**Issue by Giltyhub** [EFForg/https-everywhere#18092]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Use nightly and go to about:addons then to HTTPS prefs:

![image](https://user-images.githubusercontent.com/38662885/59460771-5f895480-8e0f-11e9-83db-95f2efb81663.png)

there should be some small free height above each button

**Comment by Giltyhub2** [comment]
this has been fixed by Firefox itself, so you can close this @pipboy96 (unless if you feel that more free space would be good)
