### ISSUE TITLE
Site broken when EASE active -- even when whitelisting

### ISSUE THREAD

**Issue by Sgt-Nukem** [EFForg/https-everywhere#18143]
Type: ruleset/website issue

A) Have HTTPS Everywhere installed and enabled
B) Have EASE option active (encrypt all sites)

When you then surf to http://avm.de/nc/service/zack-der-speedtest-fuer-ihre-breitbandverbindung/

1) you have to add that site to the whitelist (as it doesn't have an https endpoint)
2) but **afterwards the speed checker there is broken**

If you completely disable the HTTPS Everywhere extension and reload the page it is working again.

After 2) there are also fonts missing:
So it may be that fetching JS + CSS subresources (without https) needed for speedchecking fail due to https-EASE-inceptor (and fail silently).

**Comment by cschanaj** [comment]
This is a bug due to the way we obtain the `firstPartyHost` for each request. Sub-document resources originated from a third-party domains are still rewrote by HTTPSE. The expected behavior is that _if the main_frame URL is whitelisted, all sub-requests are whitelisted within the same tab_. 

cc @Hainish @zoracon

**Comment by crazygirl1972** [comment]
This is Mrs Mclendon I am having issues with my accounts with github and
google and chrome. My first account I&8462mac@icloud.com and
8462mac@gmail.com was taken over by another person through your site. So I
open another account crazybeautiful8462@gmail.com and crazygirl1972 with
your site. Now the same thing is happening your site is allowing someone
else to make changes within my account and frankly I am tired of these
privacy breech against me. I want this issue fixed or I will take legal
actions against all three sites and the ones hacking my accounts.
Thank you

Mr & Mrs McClendon

**Comment by Hainish** [comment]
@cschanaj looking into this now.  I believe what breaks the whitelisting in tabs is not that it comes from a third-party domain, but that it is loaded from within a separate frame.
