### ISSUE TITLE
Making the CDN, Google API calls goes through the encryption

### ISSUE THREAD

**Issue by nishanthj6** [EFForg/https-everywhere#18157]
[//]: # Making the CDN, Google API calls goes through the encryption even with HTTP based websites

Type: feature request

As I'm trying to make the unsecured hosted server(non-SSL based) that which are coded calling the standard Google API's & CDN websites 
Thereby, making that connections goes via encrypted.

For instance say I had included this script below to our hosted server

    <style type="text/css">
      @import url(http://fonts.googleapis.com/css?family=Oswald:400,300);
      @import url(http://fonts.googleapis.com/css?family=Open+Sans);
    </style>

    <section class="divider parallax layer-overlay overlay-deep" data-stellar-background-ratio="0.2"  data-bg-img="http://placehold.it/1920x1280"> ... </section>
    <div class="thumb"><img alt="" src="http://placehold.it/270x270" class="img-fullwidth"></div>

    <script src="http://maps.google.com/maps/api/js"></script>

When browsing via the Brave browser, by enabling the Connections encrypted feature & thereby, calling the Google API's and some other sites connected with website,
it encrypts only the fonts.googleapis.com, placehold.it, and AuthenticationService Google Map API

    https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3A%2F%2Fsomedomain.org%2F&5shttp%3A%2F%2Fsomedomain.org%2F&callback=_xdc_._l5b8s4&token=72548

[![enter image description here][1]][1]

and rest of the following calls mentioned below didn't encrypt at all.

    http://maps.google.com/maps/api/js
    
    http://maps.google.com/maps-api-v3/api/js/37/6/common.js
    
    http://maps.google.com/maps-api-v3/api/js/37/6/util.js

Tested with HTTPS Everywhere extension even after turning Encrypt All Sites Eligible is ON feature The extension would disable itself as it tries to navigating to a non-HTTPS page after the clicking the Open insecure Page

As I'm looking for a solution  with the browser extensions developed specifically, that takes care of the functionality by replacing all the  standard Google API's & CDN websites calls that goes with the secured protocols recursively?

  [1]: https://i.stack.imgur.com/rzIH3.jpg

**Comment by pipboy96** [comment]
HTTPS Everywhere doesn't seem to work with local files. I'm not sure how to fix it. Sorry.

**Comment by pipboy96** [comment]
I can't reproduce this issue with the extension, sorry. Please open an issue in Brave repository.

**Comment by nishanthj6** [comment]
Will you answer why does the HTTPS Everywhere extension disables, even after turning Encrypt All Sites Eligible is ON feature. The extension would disable itself as it tries to navigating to a non-HTTPS page after the clicking the Open insecure Page @pipboy96

**Comment by pipboy96** [comment]
@nishanthj6 It only disables itself on the website you try to visit but is only available over HTTP.

**Comment by nishanthj6** [comment]
Why does HTTPS Everywhere extension doesn't make the connections upgrade to https @pipboy96

**Comment by pipboy96** [comment]
?

**Comment by nishanthj6** [comment]
What does ? mean??? Since I tested with chrome extension with [SKN SSL Enforcer](https://chrome.google.com/webstore/detail/skn-ssl-enforcer/eldkkiimeobmnkkiielcgemfkaadpchm/related?hl=en) made the Google API upgrade to HTTPS version based on rule set @pipboy96

**Comment by pipboy96** [comment]
Please try to be less combative, it's hard to understand what you are trying to say.

**Comment by nishanthj6** [comment]
I mean to say when you are browsing via Non-secured version(HTTP) of website. The browser extension HTTPS Everywhere disables after clicking `Open insecure Page`.   But [SKN SSL Enforcer](https://chrome.google.com/webstore/detail/skn-ssl-enforcer/eldkkiimeobmnkkiielcgemfkaadpchm/related?hl=en) won't disables there by making every Google API calls goes via encrypted. 

My question what's the use of HTTPS Everywhere in Non-secured version of website.

@pipboy96

**Comment by nishanthj6** [comment]
> I mean to say when you are browsing via Non-secured version(HTTP) of website. The browser extension HTTPS Everywhere disables after clicking `Open insecure Page`. But [SKN SSL Enforcer](https://chrome.google.com/webstore/detail/skn-ssl-enforcer/eldkkiimeobmnkkiielcgemfkaadpchm/related?hl=en) won't disables there by making every Google API calls goes via encrypted.
> 
> My question what's the use of HTTPS Everywhere in Non-secured version of website.
> 
> @pipboy96

By default, Loading Non-secured version of CDN over HTTPS would give rises error on console

> Mixed Content: The page at 'https://somedomain.in' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-migrate-3.0.0.min.js'. This request has been blocked; the content must be served over HTTPS.


@pipboy96

**Comment by Giltyhub2** [comment]
@pipboy96 i think he's referring to the

**Comment by Giltyhub2** [comment]
@nishanthj6 can you enable the EASE mode (Encrypt All Sites Eligible) by clicking on the extension icon and see if the problem happens?

**Comment by nishanthj6** [comment]
Yes, still the problem persist @Giltyhub2

**Comment by nishanthj6** [comment]
For instance, If we are going to surf for eg.: http://www.memo.tv. The extension doesn't connect to https://www.memo.tv/ with SSL enabled

@pipboy96 @Giltyhub2

**Comment by pipboy96** [comment]
@nishanthj6 There is currently no ruleset for this domain. I will create one right now and create a pull request for it.

**Comment by Bisaloo** [comment]
Hi @nishanthj6, thanks for reaching out!

If I understand correctly, this is a duplicate of #17554. If #17554 is implemented, request to `font.googleapis.com` and `maps.google.com` will be encrypted, even when called from a whitelisted domain, because we have rules for them.

Regarding your other comment:

> Mixed Content: The page at 'https://somedomain.in' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-migrate-3.0.0.min.js'. This request has been blocked; the content must be served over HTTPS.

This is a known issue that can only be fixed at the browser level (#793). https://addons.mozilla.org/en-US/firefox/addon/mixedcontenthunter/ might help but it will also break some websites. I recommend you only use it if you truly understand what's going on.
