### ISSUE TITLE
Use `platform="mixedcontent"` rulesets when EASE is enabled

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#18160]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

It would be useful to use the `platform="mixedcontent"` rulesets with EASE to increase the number of functional websites.

You can test this by visiting http://legorafi.fr (with EASE enabled) even when there is a rule (with `platform="mixedcontent"`) that should handle this case:

https://github.com/EFForg/https-everywhere/blob/3336050dce0da5a84b196b8dcf7171ae2e8b73cf/src/chrome/content/rules/LeGorafi.fr.xml#L13-L14

Because EASE also sends the `upgrade-insecure-requests` header, `platform="mixedcontent"` rulesets should not cause any issues in most cases.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by pipboy96** [comment]
Nice one! I also noticed EASE can fix mixed content issues. Can we also do the opposite and allow some rulesets to attempt such fix even if user does not have EASE on?

**Comment by pipboy96** [comment]
I think we can also bypass MCB even if further redirects are required by using `upgrade-insecure-requests` and then doing https => https redirect.

**Comment by Giltyhub2** [comment]
@pipboy96 

> Nice one! I also noticed EASE can fix mixed content issues. Can we also do the opposite and allow some rulesets to attempt such fix even if user does not have EASE on?

IIRC I think this has been already implemented?
