### ISSUE TITLE
ThePlatform.xml breaks video streaming on tv2.dk

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#1816]
The video [on this stream from tv2.dk](http://common.tv2.dk/mpx/player.php/guid-Trine060514.html) will not display with the ThePlatform.xml ruleset applied.

**Comment by tancrackers** [comment]
ThePlatform also prevents videos from playing on this site:
http://www.theblaze.com/stories/2015/06/14/despite-the-fact-rachel-dolezal-has-two-white-parents-msnbc-host-wonders-is-it-possible-she-might-actually-be-black/

**Comment by reedy** [comment]
Does the fix above helo?

**Comment by tancrackers** [comment]
I believe they do. Thanks!
