### ISSUE TITLE
Periodically run 'preload' travis test on PR

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#18192]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Sometimes, old PRs can target domains that have been preloaded in the meantime. It would be nice to periodically run the 'preload' test to ensure the reviewer and the contributor don't waste their time working on a ruleset that won't make it to master (e.g. #17052).

I don't know it the [cron feature from travis](https://docs.travis-ci.com/user/cron-jobs/) would work on PRs or if it only work on branches from the upstream repo itself.

Ideally, it would be good to post a comment or auto-close PR that don't pass this test.

Maybe a job for a revised bot? (cc @strugee)

**Comment by pipboy96** [comment]
@Bisaloo I also want to try this. I may not have enough free time to do that though.

**Comment by pipboy96** [comment]
I previously had created a bot to find PRs that reference domains that are gone from DNS. I may try looking for it in my old files.
