### ISSUE TITLE
[feature] Warn on HTTP with no ruleset

### ISSUE THREAD

**Issue by lofidevops** [EFForg/https-everywhere#18206]
Type: feature request

**User story:** I am an everyday user. When I open an insecure link with no ruleset, I want a bold warning, so that I can choose to back out or proceed.

**Proposed workflow:**

* I enter http://internetbadguys.com in the address bar, or click on a link to http://neverssl.com
* There is no ruleset to upgrade the address to HTTPS
* I received a warning interstitial (similar to EASE mode)
* I can choose to proceed, or close the tab, before making a connection to the insecure domain

**Notes:**

* This should be on by default
* To prevent warning fatigue:
   * Remember the user's preference per-domain for (7 days? 30 days?)
   * In the interstitial include the option "Stop showing me these warnings"

**Comment by pipboy96** [comment]
Can you explain how is this different from the current EASE feature?

**Comment by david-libremone** [comment]
@pipboy96 This suggestion would be an (optional) enhancement to "ruleset mode". A warning is shown only if no ruleset is found. So for a HTTP domain with a ruleset, the connection is silently improved, whereas in EASE mode, it would simply fail.

I guess this is an inverse of #17554 - keep EASE mode "strict" but add a warning to ruleset mode. I'm not sure which is more in line with the long-term vision of HTTPSE.

**Comment by pipboy96** [comment]
@david-libremone Do you mean it is identical to EASE but if website is not available over HTTPS there's no warning?

**Comment by david-libremone** [comment]
@pipboy96 Perhaps I don't properly understand EASE (my summary below)? Where can I read up?

Case | EASE | Non-EASE
---- | ---- | ----
1 | Warn | Show [a]
2 | Warn [b] | Apply ruleset
3 | Show (may break) | Apply ruleset
4 | Show | Show

1. HTTP link. No ruleset.
2. HTTP link. Ruleset available.
2. HTTPS link. Mixed content. Ruleset available.
3. HTTPS link.

[a] Instead show a warning (this ticket).
[b] Instead fall back on ruleset (#17554).

Reading through this now, I suspect that the non-EASE logic is "always show a web page, make it as safe as possible" whereas EASE is "only show HTTPS, allow the user to downgrade". In which case this suggestion doesn't fit the user story for non-EASE mode.

**Comment by Giltyhub2** [comment]
Chrome and Firefox (soon in version 70) already display "Insecure" warnings for HTTP, so I don't see why this would be useful.

**Comment by david-libremone** [comment]
@Giltyhub2 I guess it depends on whether you'd classify them as "bold warnings" and if they inhibit the connection until the user opts-in. Do you have any details on that?

**Comment by pipboy96** [comment]
@david-libremone This warning is only red if web page contains a password form control.

**Comment by Giltyhub2** [comment]
@pipboy96 @david-libremone I don't know about Chrome but for Firefox starting with version 70 the warning will be displayed on _all_  HTTP pages, not just those with password fields.

**Comment by pipboy96** [comment]
@Giltyhub2 I hope. This warning is not the "splash screen" type though, like the ones that appear if certificate is invalid.

**Comment by zoracon** [comment]
For now, warning users in non-EASE mode may be more of an interrupting experience imo. This mode has been requested to remain the way it is (with rulesets applied), because people still want this option of interstitial free usage while utilizing our rulesets. However, if they'd like more restriction, they can turn on EASE mode and create exceptions if needed.

**Comment by lofidevops** [comment]
> However, if they'd like more restriction, they can turn on EASE mode and create exceptions if needed.

This make sense, and is less complicated than my suggestion!
