### ISSUE TITLE
[feature] Limit EASE exceptions

### ISSUE THREAD

**Issue by lofidevops** [EFForg/https-everywhere#18207]
Type: feature request

**User story:** I am a security-conscious user using EASE mode. When I decide to visit an HTTP domain, I want to disable HTTPSE domain *temporarily*, so that the next time I visit I get a warning again. (For example, I usually refuse to visit HTTP links, but for practical reasons I must do so this one time.)

**Suggested solutions:**

* All EASE exceptions expire at the end of (session? 7 days? 30 days?)
* Two options in the EASE interstitial: "temporary access", "permanent access"
* Configuration option :P

**Comment by pipboy96** [comment]
@david-libremone IMO all EASE exception should die if EASE is disabled, at very least (they should not affect non-EASE functioning of the extension).

**Comment by david-libremone** [comment]
@pipboy96 That makes sense. In this scenario, I plan to never leave EASE mode :D

**Comment by zoracon** [comment]
Solved by: https://github.com/EFForg/https-everywhere/pull/18417
