### ISSUE TITLE
Add usage-monitoring.com

### ISSUE THREAD

**Issue by nathanielcwm** [EFForg/https-everywhere#18225]
Type: new ruleset

Domain: usage-monitoring.com

**Comment by Bisaloo** [comment]
This domain has active mixed content, which causes the slides on the landing page to break when browser over HTTPS.

**Comment by pipboy96** [comment]
@Bisaloo are there any domains that are not broken?

**Comment by pipboy96** [comment]
All subdomains are either non-functional or broken due to MCB. I will still submit a PR with a "mixedcontent" platform.
