### ISSUE TITLE
New ruleset request: learning.hccs.edu

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#18239]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
[//]: #
[//]: # (If you are submitting a new ruleset, please check the list at)
[//]: # (https://www.eff.org/https-everywhere/atlas/index.html and the open)
[//]: # (issues and pull requests to make sure it doesn't already exist.)

Type: new ruleset

Domain: learning.hccs.edu

This came in through email:

http://learning.hccs.edu/ has an https option but is not yet on the https-everywhere list. Could you please add it? Thank you.

**Comment by pipboy96** [comment]
Well, generally we try to make a ruleset for the corresponding second-level domain. In this case the second-level domain (`hccs.edu`) has a very large number of subdomains. I'm not sure what the correct way to handle this.

**Comment by Bisaloo** [comment]
In my opinion, it's fine to create a ruleset for `learning.hccs.edu` in this case. It can eventually be merged into a `hccs.edu` if we end up creating one at some point.

This is already the case for some existing rulesets.

**Comment by pipboy96** [comment]
@Bisaloo Thanks for advice.
