### ISSUE TITLE
codesculptor.org save broken

### ISSUE THREAD

**Issue by HarolddeBruijn** [EFForg/https-everywhere#1828]
In chromium on ubuntu 15.04 I have found no other option than to completly disable the https-everywhere if wanting to save my projects. would it be viable to have an exclude list like in adblock plus ?

**Comment by jsha** [comment]
Can you provide more detail instructions to reproduce the problem?

You should be able to disable individual rules by clicking on the HTTPS Everywhere icon.

**Comment by HarolddeBruijn** [comment]
Go to www.codeskulptor.org, press the save button, (2nd from left) , error pops up, disable https everywhere via chrome extensions, reload page, saving is now possible.

**Comment by jsha** [comment]
Thanks! Here's the error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://codeskulptor-user40.commondatastorage.googleapis.com/user40_cPPriEvrJ3_0.py. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Looks like this is another instance of the #49 bug. We should disable the rule for now.

**Comment by jsha** [comment]
Or rather, since the rule in question is for Google APIs, we probably don't want to delete it, but create an exception.
