### ISSUE TITLE
content.fireeye.com is not forced HTTPS

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#18294]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #

Type: ruleset/website issue

[//]: # (Uncomment and fill the domain bellow if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)

Domain: content.fireeye.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)
http://content.fireeye.com/m-trends

https://github.com/EFForg/https-everywhere/blob/496c95015c07f9fe0affb7532f2184e5a3f70814/src/chrome/content/rules/FireEye.xml#L48 seems like it should cover this domain

**Comment by pipboy96** [comment]
It won't without a corresponding rule.

**Comment by wesinator** [comment]
> It won't without a corresponding rule.

What's the purpose of having a wildcard then ?

**Comment by pipboy96** [comment]
Old syntax.

**Comment by zoracon** [comment]
@wesinator It looks like this ruleset is older and needs to be updated with the newer guidelines.
