### ISSUE TITLE
Txbit.io breaks when https everywhere is enabled

### ISSUE THREAD

**Issue by nathanielcwm** [EFForg/https-everywhere#18295]
Type: ruleset/website issue

# Domain: https://txbit.io/
When https everywhere is enabled on this site I will continually get logged out when navigating to any of the pages.

**Comment by pipboy96** [comment]
Can this be reproduced without an account?

**Comment by pipboy96** [comment]
@nathanielcwm We do not have any rulesets for Txbit.io. It's extremely unlikely HTTPS Everywhere is causing this issue. Do you have any other browser extensions installed?

**Comment by nathanielcwm** [comment]
oh ok i have:
facebook container
https everywhere
ublock origin
tampermonkey
reddit enhancement suite
bitwarden
augmented steam
