### ISSUE TITLE
Vox "cards" do not load when Vox is enabled in https-everywhere

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#1831]
Site:
https://www.vox.com/2015/6/1/8700111/rand-paul-patriot-act

Scroll towards the bottom, and you'll find the card.
NOTE: You must "disable protection" in Firefox in order to view the card with or without Vox enabled.
Even then, Vox must be disabled.

Screenshot of card in article:
https://i.imgur.com/fJRvgF8.png

**Comment by semenko** [comment]
Cards working for me now.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
