### ISSUE TITLE
issue\request: wildcard support for rules

### ISSUE THREAD

**Issue by Owyn** [EFForg/https-everywhere#18371]
Type: feature request

![scre](https://user-images.githubusercontent.com/1309656/64134255-fcdb9f80-cde4-11e9-860c-6712ec9bd289.jpg)

Had to add each page manually and still have a thousand to go...

Either a way to edit exclusion rules manually and add wildcards or just a way to add upper-level domain rule & all sub-domains would do

cuz there is only a button to disable\enable the extension for current exact sub-domain and only that: 
![изображение](https://user-images.githubusercontent.com/1309656/64134395-3fea4280-cde6-11e9-8f14-38aa217e10d4.png)

**Comment by selurvedu** [comment]
I need this very much for local web development which does not have TLS.
