### ISSUE TITLE
Disable rule for cdn.leafletjs.com

### ISSUE THREAD

**Issue by krmr** [EFForg/https-everywhere#1837]
The current rule redirects http://cdn.leafletjs.com/  to https://d591zijq8zntj.cloudfront.net/. Unfortunately the latter does not exist. This effectively breaks pages using leafletjs.

**Comment by wannabeCitizen** [comment]
Hit the same error today.  Would be great if this rule could be removed.

Thanks!

**Comment by mynameisfiber** [comment]
+1
