### ISSUE TITLE
Saving PDF files from non-HTTPS websites encounters "Network error"

### ISSUE THREAD

**Issue by mingcenwei** [EFForg/https-everywhere#18392]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

- OS Version: macOS Mojave Version 10.14.6 (18G87)
- Browser Version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- HTTPS Everywhere Version: 2019.6.27 

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

If I go to a non-HTTPS website, choose to *Open insecure page*, open a pdf file from it (*Image 1*), and then save the file (either by pressing *command + S* or by clicking the download button on the top-right corner), I will encounter *Network error* and the download will fail (*Image 2*).

Opening the download manager, I found that the download link used **HTTPS** instead of **HTTP** (*Image 3*). If I click the download link, the browser will display *This site can't provide a secure connection* (*Image 4*).

However, if I disable *HTTPS Everywhere* **globally**, I can save the file normally. Thus I think there exists a bug.

1. <img width="320" alt="Image 1" src="https://user-images.githubusercontent.com/47605337/64488690-3ac14380-d27d-11e9-9a3d-8655692a7ad1.png" >
1. <img width="320" alt="Image 2" src="https://user-images.githubusercontent.com/47605337/64488691-3ac14380-d27d-11e9-8efe-a1baaf16a87e.png">
1. <img width="320" alt="Image 3" src="https://user-images.githubusercontent.com/47605337/64488692-3b59da00-d27d-11e9-8178-73661092cece.png">
1. <img width="320" alt="Image 4" src="https://user-images.githubusercontent.com/47605337/64488689-3a28ad00-d27d-11e9-96b6-b5f75d29fd4d.png">

**Comment by pipboy96** [comment]
@mingcenwei Please post the PDF link that does not work for you.

**Comment by mingcenwei** [comment]
@pipboy96 [This](http://fdjpkc.fudan.edu.cn/_upload/article/files/0e/83/a46568d14073ba2a9a0a70fe843a/ee845423-f38c-41b3-b06a-a41cc7276988.pdf) is an example.

**Comment by pipboy96** [comment]
I was unable to reproduce this issue, either by using Command+S or by right-clicking. Do you have EASE mode on?

**Comment by pipboy96** [comment]
Please also try with a new Chrome profile with only HTTPS Everywhere installed.

**Comment by mingcenwei** [comment]
The problem persists even when I use a new Chrome profile with only HTTPS Everywhere installed.
However, if I turn off EASE mode (which I typically enabled), I can save the file normally.

**Comment by zoracon** [comment]
Unable to reproduce on:
Ubuntu 18.04
Chrome Version 78.0.3904.97 (Official Build) (64-bit)
Firefox 70.0.1 (64-bit)

Since I assume you need to access the file for a one time download, then this is resolved and you were able to ultimately access your PDF. However, if you come across this issue again in the future with another file, let us know and we will try again. This is hard to triage since it could be some sort of network error we can't ultimately see from our end.
