### ISSUE TITLE
Options UI bug: Update Channels is empty after after removing a channel

### ISSUE THREAD

**Issue by bershanskiy** [EFForg/https-everywhere#18399]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

# Reproduction steps
1. Open extension options
2. Switch to "Update Channels" tab
3. Add a new channel
On the bottom, in the box with the placeholder saying "Enter update chanel name" enter something and click "Add update channel"
4. Remove the newly added update channel by clicking "Delete"

# Expected results
The default update channel is shown, UI is responsive

# Actual result
The channel list is empty, the UI is not responsive.

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by cschanaj** [comment]
I can reproduce the same result, but only that the update channel is shown after waiting a moment of time. It took about 5 seconds to appear again after being unresponsive on my devices. I assume this is a performance issue on Google Chrome browser.
