### ISSUE TITLE
Update "ppy.sh" ruleset and add "how-old.net"

### ISSUE THREAD

**Issue by lqf96** [EFForg/https-everywhere#1845]
ppy.sh: https://gist.github.com/lqf96/ad2065d8e0b39e85af63
how-old.net: https://gist.github.com/lqf96/55bd82e9c1a775981736

**Comment by reedy** [comment]
Please submit these as pull requests :)

**Comment by fuglede** [comment]
Both domains are now covered by rulesets, so this can be closed.
