### ISSUE TITLE
Exclude all local subnets from HTTPSE

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#18474]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

Coming in from email:

> Hello,
> I would like to know if HTTPS everywhere can be disabled globally for private ip addresses (10.0.0.0/8 172.16.0.0/12 192.168.0.0/16) since they don't need https most of the time being 
in the same subnet and it would be very inconvenient to disable HTTPS everywhere for every single ip address.

What do people think about this request?

**Comment by pipboy96** [comment]
@Hainish The most obvious reason this is needed is to let people configure their routers without disabling EASE.

**Comment by pipboy96** [comment]
Maybe we need to also let the user decide on domain names/IP ranges they want whitelisted from EASE?

**Comment by zoracon** [comment]
Still deciding on whether this is a common enough use case to implement, right now if the user is on a private net, is using public facing applications common? Maybe I'm thinking of older intranet infrastructure.

**Comment by pipboy96** [comment]
@zoracon Most common case would be 192.168.(0|1).1 (most routers have a settings page listening on this IP)
