### ISSUE TITLE
what is this that keeps popping up when i search on google

### ISSUE THREAD

**Issue by ZongMan** [EFForg/https-everywhere#1847]
what is this that keeps popping up when i search on Google
i notice this also appears on https everywhere too
flickr.net

this appears in my tcp logs
storage6-l3.flickr.vip.gq1.yahoo.com

**Comment by jsha** [comment]
Can you provide more detailed steps to reproduce?

**Comment by ZongMan** [comment]
this is old now i got around to figuring out it was one of my plugin on
firefox thanks for responding back though

**Comment by ZongMan** [comment]
well im using Firefox 38.0.1 and using Stylish Plugin, the script page im using it for is Google pages/search and stuff, the actual script at fault was Darker Google by zigboom so i stopped using it an the issue went away ill post the link, https://userstyles.org/styles/43463/darker-google so as you can see its very separate to this extensions sub forum and has nothing to do with HTTPS-Everywhere sorry for taking up your time
