### ISSUE TITLE
broken popup layout when language is set to Chinese

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#18482]
Type: code issue

![图片](https://user-images.githubusercontent.com/13086421/66163149-290c6980-e68c-11e9-84cc-d81d9f9f5685.png)

cc: @ivysrono

**Comment by pipboy96** [comment]
cc @zoracon.

**Comment by ivysrono** [comment]
Mobile +1
![图片](https://user-images.githubusercontent.com/2649544/66176816-bbfbd280-e691-11e9-918e-ff71da706fe1.png)
