### ISSUE TITLE
BusinessInsider.com (partial) prevents Feature / Trending / Recent from loading

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#1848]
Example:
http://www.businessinsider.com/the-most-entitled-generation-isnt-millennials-2015-1

Scroll to the bottom, then scroll to the top, and you'll see the section "Feature / Trending / Recent" pop up.
It is greyed out when BusinessInsider.com (partial) is enabled.

Screenshot (BI disabled to show it):
https://i.imgur.com/PbjTiL9.png

**Comment by semenko** [comment]
Seems their site changed, and works now?

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
