### ISSUE TITLE
Allow end user to add *.neverssl.com into the disabled sites list

### ISSUE THREAD

**Issue by sunnz** [EFForg/https-everywhere#18503]
Type: query

I find that ``neverssl.com`` is unusable on EASE mode, even when its domain is added to my "HTTPS Everywhere Sites Disabled" list, as it currently redirects you to a url like ``lxzmwvtdsnrhkfbc.neverssl.com`` (where part before the dot is random data) to fix problems with stale in-browser cache

<img width="685" alt="Add-ons_Manager" src="https://user-images.githubusercontent.com/1378551/66376248-eb487180-e9fa-11e9-9131-c54df495c588.png">

So I like a way to add ``*.neverssl.com`` into the disabled sites list so that ``neverssl.com`` would work for me on EASE mode

I have written a custom ruleset for ``neverssl.com`` and added it into firefox via debugging rulesets but it still doesn't work with EASS

<img width="949" alt="Debugging_Rulesets" src="https://user-images.githubusercontent.com/1378551/66376188-c8b65880-e9fa-11e9-8338-b115ccf64468.png">

It would be the good if ``*.neverssl.com`` can be excluded in https-everywhere. If not, please allow the user to add it themselves via a ruleset, or adding disabled sites with wildcard in the extension's preference UI, or both, so that ``neverssl.com`` continues to work for users that choose to use EASS mode

**Comment by pipboy96** [comment]
@sunnz For now try using http://httpforever.com/.

**Comment by Bisaloo** [comment]
This sounds like a specific case of #18371.
