### ISSUE TITLE
Rapportive Gmail Plugin

### ISSUE THREAD

**Issue by garyploski** [EFForg/https-everywhere#1850]
I needed to uncheck Linkedin.com (partial) to have access to Rapportive in Gmail. This wasn't necessary previously.

![screen shot 2015-06-04 at 3 13 49 pm](https://cloud.githubusercontent.com/assets/4456404/7995621/87e3b080-0acc-11e5-9a0d-bbd1a8ceec30.png)

**Comment by pipboy96** [comment]
Author's account is inactive, issue was opened in 2015 with no follow-up, closing. If you believe this is a mistake, contact me.
