### ISSUE TITLE
WASM implementation sometimes fails to find rules

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#18589]
Type: code issue

With EASE enabled, http://meta.unix.stackexchange.com/ leads to the interstitial page while we would expect it to lead to https://unix.meta.stackexchange.com/ because of:

https://github.com/EFForg/https-everywhere/blob/b11aa252a38932ce09bb50b87adcc1f14382c59c/src/chrome/content/rules/Stack-Exchange.xml#L137-L139

I think this used to work. Am I missing something obvious here?

**Comment by pipboy96** [comment]
@Bisaloo I will try figuring this out.

**Comment by cschanaj** [comment]
It is likely to be an issue with the way the WASM implementation handling the wildcards. It also affect browsing session outside of EASE since the last release `2019.6.27`.

**Comment by pipboy96** [comment]
This is not EASE specific if I correctly understand, so I removed `EASE` label for now.

**Comment by cschanaj** [comment]
cc @zoracon @Hainish I have submit a PR at https://github.com/EFForg/https-everywhere-lib-core/pull/1 relate to this issue on WASM module wildcard rules handling.

**Comment by Hainish** [comment]
Fixed - thanks!
