### ISSUE TITLE
Travis "unittest" failure because of  NodeJs Active LTS release

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#18600]
Type: code issue

The latest Node Active LTS is released 21 Oct.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.13.0

Related PR:

- #18598, #18597

**Comment by pipboy96** [comment]
@cschanaj I'm in process of making a PR that will fix this temporarily by downgrading to Dubnium LTS.
