### ISSUE TITLE
Time.com latest stream and toolbar do not load when enabled

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#1860]
Website example:
http://time.com/3905841/autism-hyperfunctional/

The floating bar is blank, and the left side "Latest" section does not load when Time.com is enabled.

**Comment by semenko** [comment]
Loads for me on latest version.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
