### ISSUE TITLE
Certificate verification fails but browsers load fine

### ISSUE THREAD

**Issue by donced** [EFForg/https-everywhere#1862]
I'm writing rule for [Webjet](https://www.webjet.com.au/) which has this subdomain: https://cruises.webjet.com.au/
The rule test fails with following message:
`ERROR src/chrome/content/rules/Webjet.xml: Fetch error: http://cruises.webjet.com.au/ => https://cruises.webjet.com.au/: (60, 'server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none')`
same thing with `curl` ([related?](https://github.com/EFForg/https-everywhere/pull/1780#issuecomment-106966620)):
```
$ curl -I -L https://cruises.webjet.com.au
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
```
But Firefox and Chrome load just fine.
I can workaround by [adding](https://stackoverflow.com/a/28385096) the missing cert to `/etc/ssl/certs/ca-certificates.crt`, but build bot would fail just the same.
I found [Travis CI](https://travis-ci.org/) website has similar chain, but openssl command would output 4 certs while the Webjet website only output 2 certs. maybe it's [missing](https://stackoverflow.com/a/30680099)/[wrong order](https://stackoverflow.com/a/27282841) intermediate cert?

I'm using Ubuntu 15.04, ca-certificates (20141019ubuntu0.15.04.1).

**Comment by KommX** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=cruises.webjet.com.au&hideResults=on the server sends the certificates with the fingerprints
b45c283c51d3334447e4657a8d426b7ead60423a 
and
339cdd57cfd5b141169b615ff31428782d1da639
The last one is signed by afe5d244a8d1194230ff479fe2f897bbcd7a8cb4 which is in Chrome's and FF's trust store but unfortunately not in the trust store of httpsE.
httpE should add this certificate, I think.

**Comment by KommX** [comment]
I also use Ubuntu 15.04 and now I think that the package ca-certificates is just missing the root certificate with the fingerprint afe5d244a8d1194230ff479fe2f897bbcd7a8cb4.

Therefore I created a bug report:
https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1465243

**Comment by jsha** [comment]
The https-everywhere-checker has a local repository of trust roots that should be the transitive closure of roots trusted by firefox. If one is missing, we can add it there.

**Comment by KommX** [comment]
I am pretty sure that
"COMODO RSA Certification Authority"
Fingerprint: afe5d244a8d1194230ff479fe2f897bbcd7a8cb4
is missing.

**Comment by donced** [comment]
Thanks guys for your clarification. I already create a new pull request. The current version of `/etc/ssl/certs/ca-certificates.crt` does have a few missing CA certs (in addition to "COMODO RSA") which have been added into [dev](https://launchpad.net/ubuntu/+source/ca-certificates/20150426) version.
