### ISSUE TITLE
Is it possible to notify about images loaded using http?

### ISSUE THREAD

**Issue by DevAlone** [EFForg/https-everywhere#18645]
Now if the page loads image using http it looks like this:
![image](https://user-images.githubusercontent.com/18538513/67715799-96858e80-f9db-11e9-94de-ef464c21c6a0.png)
The same thing but with https everywhere disabled:
![image](https://user-images.githubusercontent.com/18538513/67715890-bcab2e80-f9db-11e9-8f38-500907d5581a.png)
Is it possible to change it to something like this?
![image](https://user-images.githubusercontent.com/18538513/67716145-4d820a00-f9dc-11e9-9ec4-08fc11bc7265.png)
Button should be of course something like "Show insecure image" :)

**Comment by pipboy96** [comment]
You can do that using either command line flags or `about:config` depending on browser. Replacing images with some kind of HTML would be impossible since images may also be loaded by CSS.

**Comment by DevAlone** [comment]
> or about:config options called security.mixed_content.block_display_content and security.mixed_content.upgrade_display_content in Firefox

if this allows me to see content loaded by http, it's not a solution.

> Replacing images with some kind of HTML

Is it possible to replace it with an image using webrequest hook?
