### ISSUE TITLE
EASE: when https is disabled for a site, check https works and automatically re-enable it if it does

### ISSUE THREAD

**Issue by pabs3** [EFForg/https-everywhere#18679]
Type: feature request

I browse with EASE turned on and often have to turn https off on some sites. Later I visit the site again, notice it uses http and then enable https again and notice that https works now. It would be nice if when EASE is on https-everywhere could check http and https in parallel and if the https version loads, discard the http version, render the https version and re-enable https for the domain.

**Comment by pipboy96** [comment]
Try using a new option called "Open insecure page for this session only":

<img width="674" alt="Screen Shot 2019-11-13 at 14 38 57" src="https://user-images.githubusercontent.com/46632672/68760631-5ea95880-0623-11ea-85c0-a90cf5a576f0.png">

**Comment by pabs3** [comment]
That option isn't quite what I want, because it means I have to click
through the insecure site page basically every time I visit a site.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by zoracon** [comment]
I am not sure I understand the request. If HTTPS is enabled for a site, in EASE mode, it will take you to the HTTPS version of the site.

**Comment by pipboy96** [comment]
@zoracon He means he wants HTTPS Everywhere to test if website enabled HTTPS support once in a while (if user chooses to).

**Comment by pabs3** [comment]
Here is the timeline of events currently:

 * I enable EASE
 * I visit a site
 * https-everywhere tries to connect to https and fails
 * I choose to visit the site insecurely
 * Time passes
 * I visit the site again
 * https-everywhere connects insecurely
 * I notice http in the URL
 * I enable https for the domain and it works

I want this timeline of events instead:

 * I enable EASE
 * I visit a site
 * https-everywhere tries to connect to https and fails
 * I choose to visit the site insecurely
 * Time passes
 * I visit the site again
 * https-everywhere connects to both http and https
 * when the https URL succeeds, https-everywhere discards the http
   request/result, switches to the https result and re-enables https
   for the domain

In case the dual connection isn't possible for WebExtensions, it should
connect first to https and if it fails then load the http version.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pipboy96** [comment]
@pabs3 Thanks for clarifying!

**Comment by zoracon** [comment]
@pabs3
Just acknowledging this request and that it makes sense to check the disabled list if HTTPS is available for it. Will try to work out how this will look workflow wise and see what we can do.

**Comment by pabs3** [comment]
For now restarting my browser daily and using the new disable-for-session-only option is working quite well so this isn't an urgent option.
