### ISSUE TITLE
Addon interferes with the automatic login for imgur.com

### ISSUE THREAD

**Issue by Tamren** [EFForg/https-everywhere#18687]
I'm using Firefox 70.0.1 64-bit, on Windows 7, with version 2019.11.7 of HTTPS Everywhere.

It appears that HTTPS-E doesn't allow me to login automatically on the imgur.com website, specifically the beta version of imgur. (there is no issue on the older non-beta version). When I log into imgur what normally happens is I don't have to enter my password again until a few months later when the imgur cookies expire. But when HTTPS-E is active I have to login to the website every time, and most of the website cookies (including the one that handles login apparently) are deleted when I visit the site again.

If I disable HTTPS-E entirely or disable imgur.com under the stable rules section it logs in automatically like normal. I've been using this addon for years and haven't had login issues on any other website, so I'm not sure if the website or the addon is the problem.

Here are the steps I used to replicate the issue:

- Step 1: log into Imgur normally
- Step 2: Open the HTTPS everywhere menu (the blue S icon), open the "see more" tab on the bottom right.
- Step 3: Under the "stable rules" section, untick the slider next to imgur.com

If the slider is disabled or if I turn off HTTPS Everywhere, the imgur website will remember my login as normal. 

However if HTTPS is on and the slider next to imgur.com is active, imgur will not remember my login when I visit the site the following day.

**Comment by pipboy96** [comment]
@Tamren Sorry, I can't reproduce this without creating an account (which requires me to submit my phone number).

@zoracon I have a feeling this is caused by `securecookie` rule. Is there an easy way to verify that?

**Comment by Tamren** [comment]
Whatever you guys changed seems to have fixed the issue for me. I can access Imgur normally now and it doesn't log me out every single time unless I turn the addon off. Thanks.

**Comment by pipboy96** [comment]
@Tamren Glad to hear it. If this problem returns, please make a comment here and this issue will be re-opened.
