### ISSUE TITLE
Update Firefox logo on https://www.eff.org/https-everywhere

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#18694]
https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/

**Comment by cschanaj** [comment]
@zoracon I think that the logos for Google Chrome, Opera have adopted a new flattened design too. It would be great if they can be updated as well. Besides, it seems that even the Android robot get a new design too. https://developer.android.com/distribute/marketing-tools/brand-guidelines#android_robot

**Comment by zoracon** [comment]
Trying to find the official branding channels for these logos @J0WI @cschanaj

**Comment by zoracon** [comment]
Update: The request is in with design, should see new logos soon
