### ISSUE TITLE
Firefox: mixed content: absence of the yellow alert for insecure content

### ISSUE THREAD

**Issue by grahamperrin** [EFForg/https-everywhere#18699]
Original (insecure): 

- <http://meyerweb.com/eric/thoughts/2017/03/07/welcome-to-the-grid/>

Partially secure: 

- <https://meyerweb.com/eric/thoughts/2017/03/07/welcome-to-the-grid/>

With [HTTPZ 0.10.0](https://github.com/claustromaniac/httpz/releases/tag/0.10.0) added to Firefox, a traditional warning for insecure content: 

![2019-11-20 07:24:30](https://user-images.githubusercontent.com/192271/69218509-ca7e4a80-0b68-11ea-851a-5b741249a066.png)

With HTTPS Everywhere 2019.11.7: 

![image](https://user-images.githubusercontent.com/192271/69218534-d23def00-0b68-11ea-9308-0bf4edbbd515.png)

– no warning. Please, is this by design? 

### Suggested label

`mixed-content-bug`

### Environment

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Wed 20 Nov 2019 07:10:07 GMT
FreeBSD 13.0-CURRENT #36 r354616: Tue Nov 12 01:28:03 GMT 2019     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 70.0.1_3,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

----

Apologies if this issue is a duplicate … the closest I could find was `18491`.

**Comment by pipboy96** [comment]
@grahamperrin Yes, this is by design. Due to EASE mode being enabled you are not making any unencrypted requests, thus no warning is created.

**Comment by grahamperrin** [comment]
Thanks, I'm confused, there's insecure content (the image below) with EASE both  disabled _and_ and enabled: 

![2019-11-20 09:18:14](https://user-images.githubusercontent.com/192271/69228612-c7d92080-0b7b-11ea-8111-e3b3e4617b45.png)

![image](https://user-images.githubusercontent.com/192271/69228625-cf98c500-0b7b-11ea-9402-01fbbb76b4ce.png)

**Comment by pipboy96** [comment]
@grahamperrin It gets requested over HTTPS due to `Content-Security-Policy: upgrade-insecure-requests` header the extension appends to all responses when EASE mode is on. You may see it in Network tab of developer tools.

**Comment by grahamperrin** [comment]
Sorry, I'm still confused (not a developer) …

> Due to EASE mode being enabled you are not making any unencrypted requests, 

If no unencrypted request is made, then why does the unencrypted (http) content appear in this mode?

**Comment by pipboy96** [comment]
@grahamperrin Even if initial request was made for HTTP version of the resource, this request was rewritten to actually get a secure HTTPS version before it left your machine. I hope this makes sense. Your browser never actually sent the insecure request as result of HTTPS Everywhere and EASE mode being enabled.

**Comment by grahamperrin** [comment]
So the Page Info dialogue is not reliable?

**Comment by pipboy96** [comment]
@grahamperrin In this case the reliable source is Network tab in DevTools.

**Comment by grahamperrin** [comment]
OK, thanks, are you aware of a Mozilla bug for users being misled by the Page Info dialogue in situations such as this?

**Comment by pipboy96** [comment]
Try filing a bug at bugzilla.mozilla.org.
