### ISSUE TITLE
Add Polish bank domains

### ISSUE THREAD

**Issue by gjedeer** [EFForg/https-everywhere#18708]
Type: new ruleset

Domain: inteligo.pl
Domain: system.aliorbank.pl
Domain: bn.aliorbank.pl

Additional info: Bank #1 login page is https://inteligo.pl/secure/igo2 and bank #2 has two different login pages for two different products: https://system.aliorbank.pl/ and https://bn.aliorbank.pl/hades/do/Login

**Comment by pipboy96** [comment]
Done: #18711, #18709
