### ISSUE TITLE
Link to downgrade attack explanation on EASE error page is missing from some translations

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#18702]
Examples (click to show an image):

## Link is missing

<details>
<summary>🇩🇪 German (de)</summary>
<img width="631" alt="de" src="https://user-images.githubusercontent.com/46632672/69541624-a53f7100-0f9a-11ea-9c27-c23b40944deb.png">
</details>

<details>
<summary>🇫🇷 French (fr)</summary>
<img width="631" alt="fr" src="https://user-images.githubusercontent.com/46632672/69541625-a53f7100-0f9a-11ea-8d6c-0abe5bceedf3.png">
</details>

<details>
<summary>🇨🇳 Chinese (zh_CN)</summary>
<img width="632" alt="zh" src="https://user-images.githubusercontent.com/46632672/69541631-a6709e00-0f9a-11ea-9f3a-a87df04f79a2.png">
</details>

## Link is correctly displayed

<details>
<summary>🇮🇹 Italian (it)</summary>
<img width="631" alt="it" src="https://user-images.githubusercontent.com/46632672/69541627-a5d80780-0f9a-11ea-98c7-ec17e01cbf29.png">
</details>

<details>
<summary>🇳🇱 Dutch (nl)</summary>
<img width="624" alt="nl" src="https://user-images.githubusercontent.com/46632672/69541628-a5d80780-0f9a-11ea-88fc-6f80efce1f7f.png">
</details>

<details>
<summary>🇸🇪 Swedish (sv)</summary>
<img width="631" alt="se" src="https://user-images.githubusercontent.com/46632672/69541629-a6709e00-0f9a-11ea-8cc1-fb365c5057ea.png">
</details>

**Comment by pipboy96** [comment]
cc @zoracon.

**Comment by zoracon** [comment]
So after investigating this it appears to be case sensitive replacement and some mishandling of that on our part.

So for example, the German text in the paragraph is: `netzwerkbasierte Downgrade-Angriffe` but the replacement text to insert the link is looking for `Netzwerk-basierte Downgrade Angriffe`.

Now that I think I found the issue, will think of a way to handle this better.

**Comment by pipboy96** [comment]
I hope a real solution will be done shortly.

**Comment by zoracon** [comment]
> I hope a real solution will be done shortly.

@pipboy96 for now this is the "real solution". Can you clarify what a better solution would look like?

**Comment by pipboy96** [comment]
@zoracon My guess is real solution could be allowing some BBCode- or Markdown-like syntax in translations, of course with restriction what websites could be linked to. We should probably link to an language-appropriate version of Wikipedia if possible.
