### ISSUE TITLE
Ruleset house.gov

### ISSUE THREAD

**Issue by ericamick** [EFForg/https-everywhere#18748]
Type: ruleset/website issue

clerk.house.gov does not support https.

**Comment by pipboy96** [comment]
@ericamick If clerk.house.gov is the only domain that doesn't support HTTPS, I recommend using HSTS preloading instead. See https://www.eff.org/https-everywhere/faq/#how-do-i-add-my-own-site-to-https-everywhere and https://hstspreload.org/ for more information.

**Comment by Nintendofan885** [comment]
It looks like clerk.house.gov supports https now
