### ISSUE TITLE
MAC OS Depedencies and Environment Install Issues

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#18751]
Type: Toolchain 

Multiple issues potentially due to out of date scripts 

Original issues came out of Indeed Study Hall for Open Source: #18745

- [ ] `MacOS 10.13.6 High Sierra`
Running `./make.sh`
`I’m sorry, `getopt --test` failed in this environment.`

**Comment by zoracon** [comment]
- [ ] `MacOS 10.13.6 High Sierra`
Running `./make.sh`
`I’m sorry, `getopt --test` failed in this environment.`

**Comment by pipboy96** [comment]
@zoracon This can be fixed by installing GNU getopt from Homebrew and changing the script to use it.

**Comment by zoracon** [comment]
> @zoracon This can be fixed by installing GNU getopt from Homebrew and changing the script to use it.

@pipboy96 We tried that during the study hall and unfortunately still came across problems :(

**Comment by pipboy96** [comment]
@zoracon I successfully built the extension under macOS Mojave.

**Comment by zoracon** [comment]
> @zoracon I successfully built the extension under macOS Mojave.

@pipboy96 That's promising then. Maybe it's the configurations of their Mac OS environments.

**Comment by zoracon** [comment]
Closing for now, since no further reporting came from the team

**Comment by yuujay** [comment]
Getting this error on Mac OS `Big Sur v11.0.1 (20B50)`. Tried using  GNU getopt but didn't help. Any other workarounds for this?
