### ISSUE TITLE
Add DuckDuckGo Smarter Encryption list

### ISSUE THREAD

**Issue by unbranched** [EFForg/https-everywhere#18759]
DuckDuckGo recently wrote a blog article where they compare lists of HTTPS websites and they seem to have the largest one:
https://spreadprivacy.com/duckduckgo-smarter-encryption/

Any plan in adding DuckDuckGo list of sites to HTTPS Everywhere?
The code is open source and the list is available to download.
Repo: https://github.com/duckduckgo/smarter-encryption
List: http://staticcdn.duckduckgo.com/https/smarter_encryption_latest.tgz

**Comment by unbranched** [comment]
And only a few seconds I post this request I read the only line I missed in the article...
"We plan to work with the EFF to try to make available our entries into their extension."

**Comment by superusercode** [comment]
This would have made a good tracking issue

**Comment by pipboy96** [comment]
@superusercode Please don't bump old issues. This is being handled internally by the EFF.
