### ISSUE TITLE
Unmatching security certificate to hw1.pa-cdn.com

### ISSUE THREAD

**Issue by joepanda111** [EFForg/https-everywhere#18775]
Hello there, 

I am currently getting nonstop alerts from Bitdefender Internet security while on one website
https://forums.penny-arcade.com

Usually happens when I click on a subforum or thread. 

"Suspicious connection blocked
one minute ago

Feature:
Online Threat Prevention

firefox.exe attempted to establish a connection relying on an unmatching security certificate to hw1.pa-cdn.com. We blocked the connection to keep your data safe since the used certificate was issued for a different web address than the targeted one"

After disabling HTTPS Everywhere the alerts stop.

**Comment by pipboy96** [comment]
Thanks for sending a report! Please clarify if you have EASE (Encrypt All Sites Eligible) option enabled or disabled.

**Comment by joepanda111** [comment]
> 
> 
> Thanks for sending a report! Please clarify if you have EASE (Encrypt All Sites Eligible) option enabled or disabled.
Yes this option is on

**Comment by pipboy96** [comment]
Please add `hw1.pa-cdn.com` to EASE exclusions, this should fix the issue.

**Comment by joepanda111** [comment]
> 
> 
> Please add `hw1.pa-cdn.com` to EASE exclusions, this should fix the issue.

Sorry to be a bother, but I'm not sure if I am doing this correct.

Can you please clarify the steps I need to do to exclude this?

What I have currently tried is going to the 'hw1.pa-cdn.com' site and selecting 'disable

**Comment by pipboy96** [comment]
@joepanda111 You may disable the alerts for your browser process and just let your anti-malware solution block invalid certificates automatically, or not block them at all since browsers already block invalid certificates (but some applications actually do not, so this feature is a good idea).

**Comment by joepanda111** [comment]
I made an exclusion for alabasterslim.com as it's owner apparently has an association with the website.

I am getting no more security alerts

**Comment by pipboy96** [comment]
@joepanda111 Glad to hear it!
