### ISSUE TITLE
foxitsoftware website doesn't fully support HTTPS

### ISSUE THREAD

**Issue by OredBlack** [EFForg/https-everywhere#1878]
When [Foxitsoftware] is checked for HTTPS the following page does not load.

http://www.foxitsoftware.com/PDF_Editor/

<ruleset name="Foxitsoftware">
<target host="*.foxitsoftware.com"/>
<rule from="^http://www\.foxitsoftware\.com/" to="https://www.foxitsoftware.com/"/>
</ruleset>

Reproduce the problem:
Load "http://www.foxitsoftware.com"
From the drop-down menu click on "Products", then "Foxit Reader"

Strange! Tried clicking on the other menu choices unter the "Products" menu, Some load OK, Some do not.

**Comment by reedy** [comment]
Sounds like bad server config, but if it's spotty like this, we should probably disable the ruleset

**Comment by OredBlack** [comment]
I disabled the foxitsoftware rule and the pages loaded. 

Thanks for the quick response.

**Comment by reedy** [comment]
I mean, we should disable it by default in HTTPSE :)

**Comment by OredBlack** [comment]
I am not familiar with HTTPSE I'm new to this site.
