### ISSUE TITLE
Slows down opening links from Gmail in Firefox Mobile

### ISSUE THREAD

**Issue by wesinator** [EFForg/https-everywhere#18791]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

Links opened in Gmail on Android, with Firefox as default browser take a few seconds longer to load with HTTPS Everywhere
Gmail redirect `https://www.google.com/url?q=http://example.com/desination` stays for a few seconds before loading the destination.

Loads much faster when HTTPS Everywhere is disabled

**To reproduce:**
 - Firefox Android default browser, HTTPS everywhere enabled
 - Open link in Gmail

Firefox 68.3.0 
Android 9

**Comment by pipboy96** [comment]
@wesinator Does it only happen on Android? Can it be reproduced on a desktop browser?
