### ISSUE TITLE
Add ANSA.it

### ISSUE THREAD

**Issue by nemobis** [EFForg/https-everywhere#18797]
Type: new ruleset
Domain: ansa.it

Since a while ago, http://www.ansa.it/ is also available at https://www.ansa.it/ (this is a website in the top 50 Alexa rank for Italy).

There are a number of sub-sites as directories, but most of them seem to work correctly over HTTPS. I've tested over a dozen, including:

```
/sito
/english
/ansa2030
/eccellenze_italiane
/canale_lifestyle
/mare
/europa
```

etc. I only got a mixed content warning for https://www.ansa.it/canale_viaggiart/it/

**Comment by Atrate** [comment]
Added in 4ff881bb34f
