### ISSUE TITLE
HTTPS Everywhere Configuration resets to default after Chromium/Firefox shuts

### ISSUE THREAD

**Issue by ediowar** [EFForg/https-everywhere#18799]
I use  [short guide](https://decentraleyes.org/configure-https-everywhere/) When I quit Chromium/Firefox all the settings in HTTPS Everywhere reset to default. So after re-launching Chromium I have to re-apply the same settings again.
Browser settings are set by default. Only HTTPS Everywhere is enabled.
HTTPS Everywhere Version 2019.11.7. Encrypt All Sites Eligible is OFF.
Chromium Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Firefox for Ubuntu 71.0 (64-bit)
Firefox  71.0 and 72.0.1 (64-bit) in Windows 8 SL 64-bit

**Comment by ediowar** [comment]
When you open a new tab, an error appears
![Screenshot from 2020-01-11 01-08-20](https://user-images.githubusercontent.com/44164186/72190250-fa263200-33f6-11ea-9a8c-3597343cea33.png)
When you tick or untick any checkbox within the "Stable rules" section, an error appears
![Screenshot from 2020-01-11 01-08-41](https://user-images.githubusercontent.com/44164186/72190639-f5ae4900-33f7-11ea-893a-22ea3f5eced4.png)

**Comment by pipboy96** [comment]
@zoracon Please take a look at this.
