### ISSUE TITLE
calameo.com (partial) rule breaks fr.calameo.com

### ISSUE THREAD

**Issue by mohicanb** [EFForg/https-everywhere#1880]
Here's a file that cannot be opened when the calameo.com (partial) rule is on (default) : http://fr.calameo.com/read/004260307690d779c9a4e
it opens all right when rule is off.

**Comment by reedy** [comment]
WFM, it doesn't get redirected

**Comment by mohicanb** [comment]
I am using Firefox 38 on Ubuntu 14.04.2
I made a new test on a default Firefox profile where I just installed https-everywhere from the EFF website.

At the first trial on the file, a have a running circle and nothing is displayed. If I reload the page I get an error message "enable to load viewer error 911".
There's no apparent redirection.
And when I disable the rule "calameo (partial)" then I have access to the document.

**Comment by KommX** [comment]
I can reproduce the behaviour mohicanb is describing.

**Comment by donced** [comment]
The rule is already off ([Calameo.com-problematic.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Calameo.com-problematic.xml) [Calameo.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Calameo.com.xml)).
