### ISSUE TITLE
remove www.sonicwall.com

### ISSUE THREAD

**Issue by yrkey** [EFForg/https-everywhere#18812]
Hi, 

I notice the Https-Everywhere browser plugin might disturb our productions by changing http to https.
So would you remove the rule about _www.sonicwall.com_ ?

Thanks

**Comment by pipboy96** [comment]
@yrkey Can you elaborate further? What does prevent the website from working on HTTPS?

**Comment by yrkey** [comment]
@pipboy96 This is not a bug of Https-Everywhere. 
We build firewall. Sometims, our users send a http request to access to blocked sites.
The Https-Everywhere might modify the http request into https request without establishment.  
So it bypasses our https checker.
The firewall will fail to analyse the request.

**Comment by pipboy96** [comment]
@yrkey How would deleting `SonicWALL (partial)` rule (which only affects domains `sonicwall.com`, `www.sonicwall.com` and `software.sonicwall.com` prevent users from making HTTPS requests to other websites?

**Comment by pipboy96** [comment]
Since I do not have access to your firewall software, I can't test that. You can, though, by going to https://sonicwall.com with HTTPS Everywhere installed and disabling this ruleset in the extension (click on extension icon).

**Comment by yrkey** [comment]
@pipboy96 That works. But if our users start using Https-Everywhere more and more, we must ask every customer to disable the rules about _sonicwall.com_.
Is it possible to remove those rules in Https-Everywhere permanently?

**Comment by pipboy96** [comment]
@yrkey Am I correct that if user makes a request to a blocked site it gets redirected to `http://sonicwall.com/[something]`, `http://www.sonicwall.com/[something]` or `http://software.sonicwall.com/[something]`, and then that request is also catched?

**Comment by yrkey** [comment]
@pipboy96 correct. 
Http requests are always catched. 
Https requests can also be catched and analysed if there is establishment.
Is Https-Everywhere sends https packages but does not establish a https connection before?

**Comment by pipboy96** [comment]
@yrkey Can you give me an example of the URL blocked websites get redirected to, so I may create an exclusion?

**Comment by yrkey** [comment]
@pipboy96 The redirected url is http://www.sonicwall.com/iConfirm.html
But this http url can only be accessed through firewall.

**Comment by pipboy96** [comment]
@yrkey Ok, I will make a copy of ruleset with an exclusion and give it to you for testing.

**Comment by pipboy96** [comment]
@yrkey Steps to test:

1.  Ensure SonicWall ruleset is still disabled. If it is not, disable it.
2.  Go to `chrome-extension://gcbommkclmclpchllfjekcdonpmejbdp/pages/debugging-rulesets/index.html` if you have Chrome or Chromium-based browser, if you have Firefox, tell me.
3.  Paste this into form and press "Save":
    ```xml
    <ruleset name="SonicWall.com (partial)">
    	<target host="sonicwall.com" />
    	<target host="www.sonicwall.com" />
    	<target host="software.sonicwall.com" />
    
    	<securecookie host=".+" name=".+" />
    
        <exclusion pattern="^http://www\.sonicwall\.com/iConfirm\.html$" />
    
        <test url="http://www.sonicwall.com/iConfirm.html" />
    
    	<rule from="^http:" to="https:" />
    </ruleset>
    ```
4.  Test if the problem still exists.

**Comment by yrkey** [comment]
@pipboy96 https-everywhere does not rewrite http://www.sonicwall.com/iConfirm.html into https even if I do noting on settings. Is those rules auto update?

**Comment by pipboy96** [comment]
@yrkey The ruleset has not been changed on our side.

**Comment by zoracon** [comment]
@pipboy96 , @yrkey I can update this ruleset with the exclusion. But I will reference this issue and conversation.

**Comment by pipboy96** [comment]
@zoracon We need to first check if it actually does anything.

**Comment by pipboy96** [comment]
Related issue: #18817

**Comment by pipboy96** [comment]
@yrkey Is this resolved? Can this issue be closed?
