### ISSUE TITLE
No badge with counter

### ISSUE THREAD

**Issue by kanlukasz** [EFForg/https-everywhere#18832]
#### Type: problem code or future request

Nowhere do I see anything like a badge with a counter
I mean something like in uBlock or uMatrix:
![obraz](https://user-images.githubusercontent.com/30685349/73591164-9a014800-44eb-11ea-9911-9075f5cfbafa.png)

It would be useful to know when HTTPS Everywhere works on a website

I am not sure if this is a BUG or FR because I remember there was once a badge counter, unless I missed something?

#### Env:
![obraz](https://user-images.githubusercontent.com/30685349/73591174-aab1be00-44eb-11ea-8fa1-f31152e2ab47.png)
![obraz](https://user-images.githubusercontent.com/30685349/73591180-b56c5300-44eb-11ea-9ca5-6b745cace0c7.png)

**Comment by pipboy96** [comment]
The counter was disabled (and then removed) because it was considered uninformative:

>We disabled the counter by default in Feb 2016, mainly because it's not informative: It counts rulesets (rather than resources), which is a fairly arbitrary divide since some domain names have many rulesets that potentially apply. It also counts potentially applicable rulesets rather than actually applied rulesets, which means that the extension claims credit on sites it didn't modify at all. Also note that the question "is HTTPS Everywhere potentially active on this site" is independently shown by the icon state: light blue for no applicable rules, dark blue for applicable rules. Though I'll admit that's kinda subtle.

Source: https://github.com/EFForg/https-everywhere/issues/12325

Am I correct that you suggest re-adding it (possibly always showing 1 if anything gets upgraded, or counting upgraded domains instead of rulesets)?

**Comment by kanlukasz** [comment]
Yes, that's exactly what I suggest

**Comment by pipboy96** [comment]
@zoracon Your opinion?

**Comment by zoracon** [comment]
Last year when we did the redesign we did extensive surveying and asked about the counter in particular to get a wide set of user's opinions. We moved the counter to the rules section in the pop-up menu for in context viewing. It's understood other extensions use different U.I., but we do not make our design decisions based on other projects. 

The counter in the pop-up menu:
![image](https://user-images.githubusercontent.com/4276080/73682569-779b3600-4675-11ea-8fd0-b324b5aaa38c.png)

I admit we didn't do a great job rerouting and on-boarding these features when we rolled out the design last year. We promise moving forward to do a much better job at letting users know what was updated and such to avoid future confusion.

**Comment by pipboy96** [comment]
@zoracon Thanks for clarifying!

**Comment by FranklinYu** [comment]
> Also note that the question "is HTTPS Everywhere potentially active on this site" is independently shown by the icon state: light blue for no applicable rules, dark blue for applicable rules. Though I'll admit that's kinda subtle.

This seems to have been reverted? Tested with http://www.example.com. Is there any feature request for it?

> Last year when we did the redesign we did extensive surveying and asked about the counter in particular to get a wide set of user's opinions.

Where can I get news about such survey in future? I wasn’t aware of the survey at all.

**Comment by zoracon** [comment]
@FranklinYu  That site wouldn't come up with rules for other sites, try something more robust, any news site would likely due.

We emailed extensively last year as well had an open issue that discussed about the UX and redesign that was open in the repo for a while.

**Comment by FranklinYu** [comment]
> That site wouldn't come up with rules for other sites

That’s precisely what I want. Nowadays it’s more difficult to find a website without any active rule. So I went to http://www.example.com/ and the icon still showed “active”. Is that expected?
