### ISSUE TITLE
RFC: Block HTTP for banking pages

### ISSUE THREAD

**Issue by Thorsten-Sick** [EFForg/https-everywhere#1885]
This is a RFC:

We want to ensure encryption for critical connections (banking, maybe extend to shops, ...). As a HTTP-nowhere light it will enforce encryption for a list of bank urls. A connection to one of those urls will be canceled if it is not encrypted. This way a user can not be tricked by "sslstrip" into connecting to his bank unencrypted.

What do you think ? How to best implement that ?
1) Add a short lived HSTS entry to the browser DB
2) At the end of background.js:OnBeforeRequest test against a list

(I'd prefer 2)

Will be implemented by Avira for Chrome

**Comment by J0WI** [comment]
This sound interesting since HTTPS-Everywhere will disable a rule-set if it detects a http redirect.
AFAIK you can only block all http requests, but this will also break sites without https.

**Comment by jsha** [comment]
For banks that offer HTTPS, we already provide a mechanism for this: Adding the bank's URLs to a ruleset.

If the bank does not offer HTTPS, I don't think HTTPS Everywhere should block access.

**Comment by Thorsten-Sick** [comment]
Did anyone test what happens when a bank offers HTTPS but the connection is attacked with SSLStrip ? Would the connection fail ? Would the error message be understandable ?

I did not test it yet. Would love to set up a hackme-network....

**Comment by pipboy96** [comment]
Closed because:
* Opened in 2015
* Last update 2015
* Similar feature (EASE) is already implemented

If you believe this closing is not appropriate, contact me please.
