### ISSUE TITLE
RFC: Additional certificate verification

### ISSUE THREAD

**Issue by Thorsten-Sick** [EFForg/https-everywhere#1887]
This is a RFC:

Additional to the verification of the certificate chain the browser is already doing I want to do an additional certificate verification step based on crowd-sourced data (like ssl-observatory). This way we could prevent the next superfish malware.

Maybe we can reduce the checks to banking only (first phase) and later extend it to other critical pages.

Is the SSL-Observatory data good enough ? Can it be used ?
This feature could be added to HTTPS-Everywhere or be in a separate Extension...your call.

What do you think ?

Will be implemented by Avira for Chrome

**Comment by jsha** [comment]
The SSL Observatory code already has provisions for the Observatory to report a "dangerous" cert and warn the user. This warning will always fire after the bad connection has already completed, because we do not want to slow down all web browsing by making it wait on the Observatory.

The SSL Observatory does receive many many reports of MITM certs like the Superfish one. The most common source is anti-virus software. We don't have a good way of figuring out which of those reports are "interesting" vs which are normal. Definitely interested in some ideas here!

**Comment by Thorsten-Sick** [comment]
Is the SSLObservatory already integrated into the chrome port ? I did not see anything in the code there.

I am asking because we (Avira) are building a secure browser that will have https-everywhere pre-installed. And this is based on chromium.

One of the reasons for our own browser is, that we can scan at the browser (not at a proxy). Because encryption will be more common in the future and we do not want to break it.

We already have an internal task opened to add something to the Certificate-Validation issues. So maybe we can first contribute the ssl-obervatory for chromium and then check how to handle the "legit" MITM attacks

**Comment by reedy** [comment]
See #1681 for a bit of a discussion about Chrome not having the SSLObservatory. The TL;DR; version is that it's not currently included.

**Comment by Thorsten-Sick** [comment]
Thanks, reedy. I added the issue and the chromium bug to our internal task manager. We do have some chromium developers around....

I do not know íf we find a secure and elegant way to implement that feature. If chromium does not accept it, we can at least implement it in our Avira flavour of Chromium.

**Comment by reedy** [comment]
Fingers crossed that you can do it, and hopefully get it upstreamed. I'd guess the EFF would be supportive of your efforts too

**Comment by pipboy96** [comment]
Closed because:
* Opened in 2015
* Last update in 2015
* Currently impossible to implement because of WebExtensions restrictions
* Not completely clear what kind of validations are suggested.

If you believe this closing is not appropriate, contact me please.
