### ISSUE TITLE
RFC: Error reporting to server

### ISSUE THREAD

**Issue by Thorsten-Sick** [EFForg/https-everywhere#1888]
This is a RFC:

Add a feature to the extension that:
- Identifies when https-everywhere breaks a page (url loading errors, mixed content errors, ...)
- collects relevant data (rule used, urls, ...)
- sends that to a server
- the server displays the collected error data sorted by priority so the XML rules can be fixed with the ones having the most impact first
- everything opt-in for the user (like the ssl-observatory)

I'd prefer to have that DB/Webinterface on an EFF server because I do not want to fragment the https-everywhere project. I also want to use the server tech (frameworks, DBs) the EFF is normally using to simplify maintenance.

I think that could improve the quality of HTTPS-everywhere rules and reduce broken sites.

What do you think ?
Will be implemented by Avira for Chrome

**Comment by jsha** [comment]
Hi Thosten,

This is something we've been wanting to implement for a long time! The hard part is figuring out how to do it in the most privacy-preserving way possible. Ideally I'd like to make it opt-in on a per page basis. That is, if you are on a page where HTTPS Everywhere detects that it's likely broken something (e.g. more than one resource was blocked by mixed content blocking, or a redirect loop), the icon would change state to indicate something wrong. Then there would be an option in the menu to report the issue, and it would show exactly what it's going to report before sending it.

The other issue here is that we are likely to receive a huge flood of reports, and we don't really have the staffing to process a significant number of them. However, periodically reviewing only the most-reported sites would probably be a great benefit.

**Comment by Thorsten-Sick** [comment]
I would also add logging of the reports (if not in incognito mode). To be transparent. The main index of the report to the server should be the host url where it failed. So the backend could create a priority list. This would not produce more work than the current situation. But would allow to simpler triage where to invest the time with the biggest effect.

I do not know how often failures occur on a client PC. If it is not that often, a popup-style UI would be ok. If it is to common, that would annoy the users.

**Comment by Thorsten-Sick** [comment]
I created a PR with my suggestion on how we could handle that in a privacy preserving and transparent way. Please have a look

**Comment by pipboy96** [comment]
There's no conversation since 2015, PR is also closed without any updates since 2015. This also should be opt-in only if it will ever be implemented. Closing.
