### ISSUE TITLE
Common rules for +/- www.

### ISSUE THREAD

**Issue by jayvdb** [EFForg/https-everywhere#18910]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

There are a lot of rules which I believe can be simplified because their targets cover a simple set of hostnames, but they are using literal host names in the rules unnecessarily IIUC.  e.g. the following 13 all have a single glob target, and a single rule which could be the basic `{'from': '^http:', 'to': 'https:'}` as long as `*.foo.com` target doesnt apply to `foo.com`.

- *.actionkit.com
- *.csmres.co.uk
- *.stcllctrs.com
- *.mdgms.com
- *.service.mirror-image.net
- *.vo.msecnd.net
- *.secure.nonprofitsoapbox.com
- *.ntwk45.com
- *.ovpn.to
- *.omeda.com
- *.staticwars.com
- *.thankyou4caring.org
- *.zerista.com

There are many more cohorts like this, but to find them easily another type of conversion is needed (first).

There are a lot of rules which are only also adding or removing `www.` when upgrading to https.  e.g. `zuerich.ch.xml` and `zarunet.org.xml` .  These +/- `www.` rules can be detected and replaced with a common pattern and replacement, i.e. 
```py
REMOVE_WWW_RULE = ('^http://(?:www\\.)?([^/]+)/', 'https://$1/')
ADD_WWW_RULE = ('^http://([^/]+)/', 'https://www.$1/')
```

If those commonly usable rules are used instead, it is fairly easy to find pairs (or more) of rules which can be reduced to simpler rules, like `Computeruniverse.xml`.

However changing existing rulesets from quite literal patterns for +/- www. to using patterns with replacement variables will cause rule processing time to be slightly increased.  IMO this is a very small hit, and worth doing as the benefit is that common rules for +/- www. can be stored once globally and thus help with memory usage (i.e. https://github.com/EFForg/https-everywhere/issues/12232).  Also for regex engines which discard unused compiled regex from the cache, re-using the same regex increases performance overall even if they are slightly more complex regex, as they are a cache hit more often resulting in less re-compilation occurring, and there are fewer overly precise regex pushing other entries out of the cache.

The change to using common rules like this could occur only in the merge-ruleset script, or could be done in the XML directly, but it does make the XML less readable for basic rulesets.

**Comment by pipboy96** [comment]
@jayvdb Yes, this is a good idea.

**Comment by jayvdb** [comment]
Should it be done in the XML , making simple rules more complicated (but aiding copy&paste to new rulesets?) , or in the ruleset merging process as a normalisation process like the merging of exclusion rules ?

**Comment by cschanaj** [comment]
I note that some of the ruleset you mentioned above cannot be reduced to the trivial rule `{'from': '^http:', 'to': 'https:'}`, e.g. in `ActionKit.com.xml`

https://github.com/EFForg/https-everywhere/blob/00d1bc513853f90507a16d9cc2e36b665946b7b3/src/chrome/content/rules/ActionKit.com.xml#L18-L19

IMHO, the project contributing guide discourage the uses of snapping rewrites, see https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#snapping-redirects . I am not sure that optimizing for snapping rewrites would be a good idea.

**Comment by J0WI** [comment]
I'd prefer replacing them with a more explicit pattern like
https://github.com/EFForg/https-everywhere/blob/6eb65f9a19d11c438664b6429c2c00a286ff06dc/src/chrome/content/rules/Ice-WM.org.xml#L11-L14

This is very easy to read and to update if the redirect becomes obsolete.
