### ISSUE TITLE
omtrdc.net

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#18916]
Type: ruleset/website issue

[//]: # (Uncomment and fill the domain bellow if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)

Domain: omtrdc.net

If you have a Capital One credit card, go to this link and sign in:
`https://verified.capitalone.com/sic-ui/#/esignin?Product=Card&Action=ProductUpgrade`

This link should then take you to the Rewards Upgrade page, where you can see what offers exist if you wish to upgrade/product change your credit card. When the `omtrdc.net` rule is active, this page won't load. Disabling the rule fixes the issue. Can this rule be fixed to account for this issue?

**Comment by pipboy96** [comment]
@terrorist96 Can this be reproduced in any way without a Capital One credit card?

**Comment by terrorist96** [comment]
I don't think so. I'm willing to give you TeamViewer access if there's no other option.

**Comment by terrorist96** [comment]
@pipboy96 how would you like to move forward?

**Comment by pipboy96** [comment]
@terrorist96 I'm not sure. I'm not willing to log into other people's machines using TeamViewer since it's a responsibility I'm not willing to take.

Can you open Network tab of DevTools and load this page (enable both "Preserve log" and "Disable cache") and also give me the contents of Console tab after loading the page?

**Comment by terrorist96** [comment]
For some reason I'm not able to replicate this issue anymore. I cleared cache and even tried on two different profiles.

**Comment by pipboy96** [comment]
@terrorist96 Thanks for confirming this issue is gone!
