### ISSUE TITLE
Constant spam in Firefox console about unsafe aliasing in rust.

### ISSUE THREAD

**Issue by T0m0rr0w** [EFForg/https-everywhere#18921]
Recursive use of an object detected which would lead to unsafe aliasing in rust https_everywhere_lib_wasm.js:419

Just asking if this is normal or is there something wrong. Im using FF 56.0.2 (64bit) with HTTPS Everywhere addon version 2019.11.7. Rulesets version for EFF (Full): 2020.2.3

**Comment by zoracon** [comment]
Can you give a scenario as to when this console message appears? It seems like you were in your console testing something to see it in the first place. The more information, the better.
