### ISSUE TITLE
Myftp.utechsoft.com.xml cert problem

### ISSUE THREAD

**Issue by jayvdb** [EFForg/https-everywhere#18940]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Myftp.utechsoft.com.xml

https://myftp.utechsoft.com/ has an expired cert since 2017

The page contains a meta redirect and note to go to https://filecatalyst.com/ instead.

Do we update the rule to point to https://filecatalyst.com/ or delete the ruleset?

**Comment by pipboy96** [comment]
I would delete the ruleset. If it was a HTTP redirect I would suggest making a redirect.

**Comment by jayvdb** [comment]
> If it was a HTTP redirect I would suggest making a redirect.

Do you mean that ... if the website was a http redirect instead of a meta redirect, then a replacement rule would be preferred.

I doubt it matters much in this case as few users would be manually visiting an old website, but I guess ppl could have bookmarks they havent updated.  Deleting the ruleset would mean any http bookmark would start being a http hit again, and the user may see the note before the meta redirect, but if they havent updated their bookmark already, the slight delay of the meta redirect also probably wont trigger them enough to update the bookmark.

Anyways, delete it is!
