### ISSUE TITLE
Shell scripts, hashbangs and docs require python3.6

### ISSUE THREAD

**Issue by jayvdb** [EFForg/https-everywhere#18951]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Shell scripts like the test coverage scripts explicitly refer to `python3.6`, which is increasingly not present on Linux distros which often provide python3.7 or python3.8 now.  Also iirc, Python installers for Windows do not provide Python3.6.exe/cmd , and may not even provide a Python3.exe - should re-check that, as Windows users should be able to help with issues like https://github.com/EFForg/https-everywhere/issues/18745 , and docs saying `python3.6` is going to confuse them.

`git grep python3.6` has 48 results; very varied.

Suggest using just `python3` now, and check the minimum supported version inside the scripts, especially any which dont work on python3.4+ which is a really safe minimum, and provide a useful error message if an insufficient version is installed.

**Comment by cschanaj** [comment]
As per https://trac.torproject.org/projects/tor/ticket/29097

> ... which ensures that Firefox builds are deterministic, is derived from the Python 3.6 standard library. We've targeted 3.6 for this reason, as well as to enforce similar tooling across different contributor development environments.

In https://github.com/EFForg/https-everywhere/issues/6749#issuecomment-363281281, @Hainish explained the rationale behind hard-coding Python 3.6 dependency approximately 2 years ago, which seems unfit for this moment when Python 2.7 is obsolete and Ubuntu 18.04 LTS is released. 

We use the `bionic` release for Travis CI and docker image. I think it is fine to use ```#!/bin/usr/env python3``` as the Ubuntu LTS ships with Python 3.6 by default if the builds remains deterministic. If possible, we proceed with #9993 in the long term.

**Comment by zoracon** [comment]
I have been slowly moving into using Python3 instead. This has been on the backlog as a ticket so I don't lose sight of this.

**Comment by kristapsk** [comment]
I also don't have Python 3.6 on my laptop anymore, so `test/firefox.sh` don't work. Also, Python 3.6 has EOL in 9 months (23 Dec 2021).

**Comment by zoracon** [comment]
@kristapsk updated to Python3. If you could test to let me know if the tests work out for you I'd appreciate it!

**Comment by zoracon** [comment]
Assuming this is not an issue now, closing.
