### ISSUE TITLE
Shopyourway non-functional

### ISSUE THREAD

**Issue by jayvdb** [EFForg/https-everywhere#18963]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Shop_Your_Way.com.xml

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/SYW_CDN.net.xml

https://www.shopyourway.com/ is returning an error 

> Sorry, an error has occurred.
> We recorded the error in our logs for further investigation. Thank you!

I'm also seeing timeouts on many of the hosts in .sywcdn.net

The last webarchive this month showed it alive, so could be a temporary thing.

https://web.archive.org/web/20200216072113/https://www.shopyourway.com/today

The program is still prominent on https://www.sears.com/shopyourway

I was planning on changing
```diff
-       <rule from="^http://(apps|\d+)\.sywcdn\.net/"
+       <rule from="^http://(apps|s(?:[1-9]|10))\.sywcdn\.net/"
```

But that ruleset is lacking tests.

**Comment by Nintendofan885** [comment]
It seems to be back up now
