### ISSUE TITLE
Emphasize temporary exceptions over permanent ones.

### ISSUE THREAD

**Issue by Semnodime** [EFForg/https-everywhere#18970]
Type: feature request

**Current State**
The left button is used to deactivate HTTPS permanently for this page.
![Current state of Buttons](https://user-images.githubusercontent.com/19511852/75048371-b1b76500-54c8-11ea-8ea9-0068d478f79e.png)

**Requested State**
Make the temporary option the default option.

**Recommended list of available solutions**
- make a radio button option beneath the disable HTTPS button, (for this session only, default)
- make a checkbox (default, checked!) beneath the button, saying "for this session only"
- switch the order of the buttons for disabling HTTPS 'permanently' vs 'per session'

**Related history**
- issue #17217
- issue #10041

**Visual preview to allow for easy decision making**
- make a radio button option beneath the disable HTTPS button, (for this session only, default)
![Button with radio option](https://user-images.githubusercontent.com/19511852/75049948-563aa680-54cb-11ea-83c0-c55681c81e34.png)

- make a checkbox (default, checked!) beneath the button, saying "for this session only"
![Button with checkbox](https://user-images.githubusercontent.com/19511852/75048428-c7c52580-54c8-11ea-9035-48ff6911ae41.png)

- switch the order of the buttons for disabling HTTPS 'permanently' vs 'per session'
![Button reordered](https://user-images.githubusercontent.com/19511852/75048409-c136ae00-54c8-11ea-9c50-f703f435140f.png)

**Comment by pipboy96** [comment]
@zoracon Your opinion?

**Comment by zoracon** [comment]
I don't see a problem with flipping the order of the options. Toying with the radio options or checked based options would take extra effort of course, but we can easily experiment with flipped order here.

**Comment by pipboy96** [comment]
@zoracon Good! I will make a quick PR which would simply flip the order of the buttons and maybe slightly change the wording of the one that whitelists the domain forever.

**Comment by pipboy96** [comment]
This is a rough mock-up of the UX I propose (which is based on Chrome and Firefox HTTPS error pages):

![ease](https://user-images.githubusercontent.com/46632672/75434031-faa46900-5961-11ea-9090-d0e4a5405454.png)

**Comment by cschanaj** [comment]
@pipboy96 are you planning to submit a PR?
