### ISSUE TITLE
"WP Engine.com" rule broken on x.y.wpengine.com subdomains

### ISSUE THREAD

**Issue by ivoanjo** [EFForg/https-everywhere#1897]
wpengine.com's SSL cert is only valid for  `*.wpengine.com, wpengine.com`, and not `*.*.wpengine.com`.

This breaks any site in the x.y.wpengine.com format, such as the following link:
<http://talkdesk.staging.wpengine.com/wp-content/uploads/2014/12/desk-widget-2.png>

Thanks for looking into this!

**Comment by jeremyn** [comment]
It looks like pull request #2000 fixed this issue. Closing.
