### ISSUE TITLE
Stale too many redirects

### ISSUE THREAD

**Issue by jayvdb** [EFForg/https-everywhere#18981]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

I was looking for a live example of too-many-redirects problem, and https everywhere has a treasure trove of these errors.
```
> git grep https.*redirects.*http | wc -l
556
```

Or so I thought based on that.  When I tried to reproduce these errors, I found almost every one I tried was no longer causing the problem.  This is a good thing, as the web is becoming saner, but it also means that HTTPS Everywhere has lots of stale data.  Most of the rulesets which have these notes have previously been disabled by the checker, e.g. in commit 9bf49cbeb4 (June 2017).

I havent found the exact scenario I wanted to find, but I did find some good test cases, and while I was working through them I tidied up the rulesets which were now false positives, and the result is https://github.com/EFForg/https-everywhere/pull/18980 

Is it worthwhile continuing with that effort?  Or will these be (semi-)automatically re-enabled by the checker/maintainers during the "comprehensive" fetch test process?
Recheck the failing test cases is simple enough, and re-enabling them shouldnt be hard, but often there are some unrelated breakages due to other hosts in the period of time while the ruleset was disabled, so the checker may not be able to rescue the ruleset very often.

If there is a process for re-enabling these rulesets in bulk, and maintainers would prefer to do it by themselves, I could re-attempt this after the full fetch process, to find any extra ones which need a bit more analysis and adjustment to get the ruleset back into operation.

**Comment by pipboy96** [comment]
It's a good idea to continue. Rulesets that were disabled due to fetch problems will be re-enabled and re-tested at fetch test AFAIK.

**Comment by jayvdb** [comment]
Thanks.  I have tidied up the first batch in https://github.com/EFForg/https-everywhere/pull/18980 , which re-enables 19 rulesets.
