### ISSUE TITLE
Return a simple mapping of trivial rulesets for given update channel

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#18983]
Type: feature request

Reference: https://trac.torproject.org/projects/tor/ticket/28005

Exciting news - Tor Project is using our [update channels](https://github.com/EFForg/https-everywhere/blob/master/docs/en_US/ruleset-update-channels.md) in their alpha release to assist with the discovery of next-generation onion services!

To move this forward, Tor Browser developers have asked us to provide a hook in HTTPS Everywhere to return an object which contains a mapping of { host, to } for simple rulesets in a given update channel.  This should work for rulesets in the format specified in the [example ruleset channel](https://people.torproject.org/~acat/misc/rulesets/) Tor has provided us.

**Comment by Hainish** [comment]
I'll begin work on it this week.

**Comment by pipboy96** [comment]
@Hainish Wouldn't it make more sense to separate this from HTTP to HTTPS redirects, and how would it work if we deprecated all `to="http://*"` rules?

**Comment by Hainish** [comment]
@pipboy96 I think in order to support this, making deprecation of all `to="http://*"` URLs an option in the codepath that we can default to `true` rather than ripping out all the code for this is preferable.

**Comment by pipboy96** [comment]
@Hainish You mean Tor Browser's HTTPS Everywhere version is now going to be different from the regular one?

**Comment by Hainish** [comment]
@pipboy96 I think we could add a hook for HTTPSE to flip that option programmatically. Having a different extension in Tor Browser seems to invite a long-term maintenance burden

**Comment by pipboy96** [comment]
@Hainish I get it, but how is that flag going to be activated? WebExts can no longer read user.js? Will we just turn it on based on user agent?

**Comment by cschanaj** [comment]
The JSON in `default.rulesets.1579180748.gz` looks like this when prettified. 
```
{
    "timestamp": 1579180748,
    "reference": "4437a4168878143ce3fdc63bbd355d537b1cea57",
    "rulesets":
    [
        {
            "name": "Nytimes.securedrop.tor.onion",
            "target":
            [
                "nytimes.securedrop.tor.onion"
            ],
            "rule":
            [
                {
                    "from": "^http[s]?://nytimes.securedrop.tor.onion/",
                    "to": "https://nyttips4bmquxfzw.onion/"
                }
            ]
        }
    ]
}
```

So HTTPS Everywhere is going to list of `*.tor.onion` address specifically for the Tor Browser?

**Comment by Hainish** [comment]
@pipboy96 at the browser level, they can do this through the extension message passing interface such as they do in https://github.com/acatarineu/tor-browser/commit/28005#diff-f2877e5f680c088366ab9ef15860e3e1R43

**Comment by Hainish** [comment]
@cschanaj not specifically for `*.tor.onion`, I'd like to be more generic than that.  I'm not exactly sure the implementation details just yet, but I think we could request it for a specific update channel or perhaps the request for mapping could include a regex filter.

**Comment by cschanaj** [comment]
I tried the test build in the https://trac.torproject.org/projects/tor/ticket/28005, this is a fabulous enhancement to the onion browsing experience where a human-readable addresses can be used instead of the random-looking ones. HTTPSE should definitely help to move forward this. 

![Screenshot from 2020-02-26 10-12-52](https://user-images.githubusercontent.com/23636124/75305299-b3927700-5880-11ea-99bf-65e7fecdad1f.png)

**Comment by pipboy96** [comment]
@cschanaj They will keep these as a separate ruleset bundle which would be updated using update channels feature.

**Comment by pipboy96** [comment]
@Hainish Should enabling this flag also add the update channel, or would it be added in some other way?

**Comment by pipboy96** [comment]
@cschanaj There is a problem with this screenshot. The certificate doesn't match the domain (it should only match the "real" onion address), but the browser shows that it does.

**Comment by jayvdb** [comment]
> to="http://

IIUC, there is nothing to deprecated in the rules in this repo -- the three which use this are all disabled, and I have made it an [assertion in my library](https://github.com/jayvdb/https-everywhere-py/blob/873a5b7/https_everywhere/_rules.py#L618) as I was told that it was already firm policy not to downgrade at https://github.com/EFForg/https-everywhere/issues/18867#issuecomment-583935974 .

```py
git grep -E '(to="http://|downgrade)'
Canon.xml:      <!-- Domains without TLS support/with downgrade/Broken certificate:
Cato-Institute.xml:             to="http://www.cato.org/$1" downgrade="1" /> -->
Tesco.xml:              to="http://www.tesco.com/" downgrade="1" /-->
Yandex.xml:             to="http://static-maps.yandex.ru/" downgrade="1" /-->
```

**Comment by pipboy96** [comment]
@jayvdb The problem is, onion services usually use HTTP, and we don't allow rewrites that result in a `http://` URL.

**Comment by Hainish** [comment]
@pipboy96 
> @jayvdb The problem is, onion services usually use HTTP, and we don't allow rewrites that result in a `http://` URL.

We enforce this through policy, not in the code.  And that policy only effects the default ruleset update channel, not any others.
