### ISSUE TITLE
Please add pistar.uk

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#18998]
Type: new ruleset
Domain: pistar.uk

http://www.pistar.uk/ should redirect to https://www.pistar.uk/, especially because there is a section for downloading software images, but it's not setup server-side.

**Comment by pipboy96** [comment]
Thanks for suggestion! I have made a pull request to add this domain (#18999).

**Comment by fmarier** [comment]
Thanks @pipboy96 !
