### ISSUE TITLE
Preference page incompatible with FF's dark theme

### ISSUE THREAD

**Issue by finn0** [EFForg/https-everywhere#18991]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

**Type**: Bug

### Description
HTTPSEverywhere preference page isn't compatible with FF's `Dark` theme.

### Steps to reproduce
- Set FF theme to Dark (Burger icon -> Customize -> Theme -> Dark)
- Open Add-ons Manager (`ctrl+shift+A`)
- Click on `HTTPSEverywhere` addon
- Click on `Preferences` section

### Actual output
Preferences page background is white.

![https-everywhere-preference-page cleaned](https://user-images.githubusercontent.com/28824347/75407448-ef721e80-590a-11ea-9a6d-34dd30893d11.png)

### Expected output
Preferences page background should be same as background of FF.

**Comment by pipboy96** [comment]
@finn0 Thanks for reporting! We are already aware of this issue and hopefully will fix it by the next release.

(related PR: #17896)
