### ISSUE TITLE
Convert `sendResponse()`s to `Promise`s

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#18997]
Type: code issue

`sendResponse()` [will be removed from the W3C spec](https://github.com/mozilla/webextension-polyfill/issues/16#issuecomment-296693219), and returning a `Promise` from the `onMessage` handler is now preferred.  We should convert all `sendResponse()`s to `Promise`s.

**Comment by pipboy96** [comment]
@Hainish I am working on this right now.

**Comment by cschanaj** [comment]
@pipboy96 are you still working on this?

**Comment by pipboy96** [comment]
@cschanaj Yes.
