### ISSUE TITLE
question: is Windows supported?

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#19019]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: other

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

please make it clear. all i know is bash is not present on windows. consider powershell or cmd if you want support, they are installed by default.

you are welcome
Raj

**Comment by pipboy96** [comment]
This extension works on any OS Chrome or Firefox may run on, and is also supported and installed by default in Tor Browser.

This is the answer assuming you are only using this extension and not building it from source.

**Comment by zoracon** [comment]
Chromium is also the under layer of the new Edge browser, which is in Windows. If you mean development tools to help develop, please clarify.
