### ISSUE TITLE
Update install-dev-dependencies.sh to work with Debian Buster

### ISSUE THREAD

**Issue by Jochen-A-Fuerbacher** [EFForg/https-everywhere#19023]
The script `install-dev-dependencies.sh` doesn't work with Debian Buster at the moment. The error is:

```
E: Unable to locate package python3.6-dev
E: Couldn't find any package by glob 'python3.6-dev'
E: Couldn't find any package by regex 'python3.6-dev'
E: Package 'chromedriver' has no installation candidate
```

In Debian Buster there are no `python3.6-dev` and `chromedriver` packages available. However, there are [python3.7-dev](https://packages.debian.org/buster/python3.7-dev) and [chromium-driver](https://packages.debian.org/buster/chromium-driver) packages available.

The installation script should be updated so that installs the requiered dependencies also on Debian Buster.

**Comment by cschanaj** [comment]
related #18951

**Comment by zoracon** [comment]
After I run a release going to work on just setting these dependencies to Python 3 support. This is snowballing into issues every where. Thank you for your patience and submitting this issue.

**Comment by ShenZhouHong** [comment]
This issue can be reproduced on the additional following operating systems: Ubuntu 16.04, and Ubuntu 14.04:

## Ubuntu 16.04.6-server-amd64
```
shen@ubuntu16-test:~/https-everywhere$ ./install-dev-dependencies.sh

Warning: Installing the development dependencies for HTTPS Everywhere
may alter your system, installing requirements both within the package
management system and also external binaries.

Are you sure you want to continue? [y/N]: y

[sudo] password for shen:
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease

...

Reading state information... Done
E: Unable to locate package python3.6-dev
E: Couldn't find any package by glob 'python3.6-dev'
E: Couldn't find any package by regex 'python3.6-dev'
```

## Ubuntu 14.04.6-server-amd64
```
shen@ubuntu14-test:~/https-everywhere$ ./install-dev-dependencies.sh

Warning: Installing the development dependencies for HTTPS Everywhere
may alter your system, installing requirements both within the package
management system and also external binaries.

Are you sure you want to continue? [y/N]: y

Ign http://us.archive.ubuntu.com trusty InRelease

...

Reading state information... Done
E: Unable to locate package python3.6-dev
E: Couldn't find any package by regex 'python3.6-dev'
```
