### ISSUE TITLE
irc.w3.org currently needs HTTP-only

### ISSUE THREAD

**Issue by wseltzer** [EFForg/https-everywhere#19035]
Type: ruleset/website issue

# Domain:
irc.w3.org

W3C's irc service uses http://irc.w3.org/ for community chat, versus https://irc.w3.org as restricted. Efforts to reach http://irc.w3.org/ should not be redirected or upgraded.

**Comment by pipboy96** [comment]
Thanks for reaching out. This domain is currently not redirected by HTTPS Everywhere with default settings. Do you have EASE mode enabled (is the extension icon red)?

**Comment by zoracon** [comment]
Also, even in EASE mode, the extension allows you to navigate to the insecure page if you need HTTP.
