### ISSUE TITLE
Firefox Nightly for android 

### ISSUE THREAD

**Issue by szymon1051** [EFForg/https-everywhere#19036]
Can add this to Firefox Nightly for android https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora ?

**Comment by zoracon** [comment]
If they have capability for addons for Android, you should be able to do so.

**Comment by zoracon** [comment]
Just an update: Firefox Preview is adding support as well!
https://blog.mozilla.org/addons/2020/04/14/april-extensions-for-firefox-preview/
