### ISSUE TITLE
Cipher mismatch in ruleset tests

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#19034]
The following error appears in multiple PRs:
`OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to host.example`

This is a regression of #18964 which has disabled AES-CBC ciphers.

Type: other

**Comment by cschanaj** [comment]
I agree with @pipboy96 that we should have a tool to check for the the supported cipher list for each browser as discussed in https://github.com/EFForg/https-everywhere/pull/18964#issuecomment-589989760 . Manual cross checking require a lot time-consuming parsing work which could possibly go wrong. The ideal way is to setup a cipher checking server (with docker?) to handle the ciphers checking systematically and automatically.
