### ISSUE TITLE
High cpu consumption with new update 

### ISSUE THREAD

**Issue by own2pwn** [EFForg/https-everywhere#19069]
With new update, `2020.3.16` cpu usage jumped about 10x and takes the whole cpu core I believe. Regarding to macOS activity monitor it's just above ~120%. 

Version: `2020.3.16`, browser: `Version 83.0.4094.0 (Official Build) canary (64-bit)`, macOS: `10.14.6 (18G3020)`

**Comment by own2pwn** [comment]
Maybe any debug info I can record?

**Comment by pipboy96** [comment]
@zoracon is there anything that can be recorded to help discovering the source of this issue?

**Comment by zoracon** [comment]
2 things:
While your CPU seems to be being over utilized, could you take a shot of the extension's use?  This is located in Task Manager: menu (3 dots) > more tools > task manager.

Also, if you could provide a memory snapshot by following these steps:
1. Go to menu (3 dots) > more tools > Extensions
2. Turn on "Developer Mode"
3. Select "background page" on extension (under ID)
4. In console place 'let util = require('./util'); util.setDefaultLogLevel(util.VERB);`
5 Right click over logs as they after a good amount come in and save log file, you can just place the log info as a comment.

Let me know if you need further guidance on any of that. Thank you

**Comment by own2pwn** [comment]
I completely missed that my reply was never send! It seems that was bug in Canary since after a few more releases high load seems to be gone.
