### ISSUE TITLE
Interaction with WikiWand extension

### ISSUE THREAD

**Issue by jcoetzee** [EFForg/https-everywhere#1906]
I have the [WikiWand](http://www.wikiwand.com/) extension installed on my Chrome and it's interacting weirdly with https-everywhere. Essentially wikiwand tries to redirect requests to wikipedia.org to wikiwand.com (note that it defaults to HTTPS even if the original request to wikipedia was over HTTP). When I have both wikiwand and https-everywhere enabled the two clash; one tries to redirect http://wikipedia.org to https://wikipedia.org while the other tries to redirect to https://wikiwand.com, in the end I end up on wikiwand.com but over http instead of https. Also a Chrome extension error is thrown for WikiWand:

```
This extension failed to redirect a network request to
http://www.wikiwand.com/en/HTTPS_Everywhere because another extension
(HTTPS Everywhere) redirected it to
https://en.wikipedia.org/wiki/HTTPS_Everywhere.
```

Is there workaround so that https-everywhere only redirects after other extensions have fired? Or maybe even whitelisting wikipedia.org so that https-everywhere doesn't try redirect for that domain?

**Comment by Bisaloo** [comment]
HTTPS Everywhere doesn't have a Wikipedia rule anymore so this issue should be fixed.
