### ISSUE TITLE
Yospace.com blocks some videos from playing

### ISSUE THREAD

**Issue by jcosentino** [EFForg/https-everywhere#1907]
Example:
http://www.reuters.com/video/2015/06/11/supreme-court-nears-historic-ruling-on-s?videoId=364553239&videoChannel=118169

When yospace is enabled, this video fails to load on my end.

**Comment by numismatika** [comment]
@jcosentino this is no longer an issue, is it?

**Comment by jcosentino** [comment]
The video loads without any issue.

**Comment by Bisaloo** [comment]
> The video loads without any issue.

@jcosentino, in that case, can you close this issue please?
