### ISSUE TITLE
Exception to specific domain stopped working on version 2020.3.16

### ISSUE THREAD

**Issue by andyat** [EFForg/https-everywhere#19085]
Type: other

I have local server in my lan with domain name "satellite.l" ("l" is local domain). It was added as https everywhere exception (disabled sites list) and was working fine over http before updating to version 2020.3.16. After update it doesn't open over http even though this site is still in exceptions list. It keeps redirecting to https even though this server doesn't have https. Other servers in "l" domain work fine over http when added to disabled sites list. I'm using "encrypt all sites eligible" mode, but exceptions should still work even in this mode.

**Comment by pipboy96** [comment]
This is a result of broken code ending up in the release. We can't make another release due to lockdown. See #19029.
