### ISSUE TITLE
WeatherBug Chrome App's Blocked Maps

### ISSUE THREAD

**Issue by itsamike** [EFForg/https-everywhere#1908]
HTTPS Everywhere blocks maps in WeatherBug's app for Chrome https://chrome.google.com/webstore/detail/weatherbug/njkkjobcechefaoknodniidfjapgfoco?hl=en

Since the underlying URLs aren't visible, and the HTTPS Everywhere extension doesn't easily recognize Chrome apps, how might we work around that?

**Comment by pipboy96** [comment]
Extension seems to be deleted.
