### ISSUE TITLE
Question: addon release tag

### ISSUE THREAD

**Issue by margre8** [EFForg/https-everywhere#19090]
Dear developers,

today a pop-up window appeared with release notes, in this window I can see release tag 3.9.2020, but current release is 2020.3.16.

Is everything okay with https everywhere update?

Thank you for answer.
![Snímek obrazovky pořízený 2020-03-27 18-01-10](https://user-images.githubusercontent.com/40942201/77780981-13816680-7055-11ea-9581-c1e18d1ced02.png)

**Comment by MSBack** [comment]
I agree this is concerning or at least confusing.

**Comment by margre8** [comment]
Thank you for answer.
