### ISSUE TITLE
Not redirected to HTTPS for T411

### ISSUE THREAD

**Issue by M5oul** [EFForg/https-everywhere#1909]
With Https-everywhere I'm not redirected from http://www.t411.io/ to https://www.t411.io/.

**Comment by reedy** [comment]
What browser version and what version of HTTPSE?

WFM

**Comment by M5oul** [comment]
Firefox 38, HTTPSE 4.0.3. Looks an old version. I will try 5.0 version.

**Comment by M5oul** [comment]
Works fine with 5.0.5. Thanks :)

**Comment by M5oul** [comment]
I installed it from [Fedora repo](https://apps.fedoraproject.org/packages/mozilla-https-everywhere).
