### ISSUE TITLE
Tor Browser: get_simple_rules_ending_with returning no rulesets in some cases

### ISSUE THREAD

**Issue by acatarineu** [EFForg/https-everywhere#19102]
This is related to https://trac.torproject.org/projects/tor/ticket/28005#comment:39. I could only reproduce this on a first run of Tor Browser (a custom build, soon should be in nightly). We install a `SecureDropTorOnion` update channel via `create_update_channel` + `update_update_channel` message, which seems to be loading rules properly (redirects work), but `get_simple_rules_ending_with` returns 0 rules. After a browser restart it works properly. The issue does not always occur, sometimes it works well, which may indicate a race condition.

When the problem occurs, I can see these logs (just showing the util.js lines):
```
Loading update channels and importing associated public keys. util.js:26:15
EFF (Full): Update channel key loaded. util.js:26:15
SecureDropTorOnion: Could not import key.  Aborting. util.js:24:15
Loading update channels and importing associated public keys. 2 util.js:26:15
EFF (Full): Update channel key loaded. util.js:26:15
SecureDropTorOnion: Update channel key loaded. util.js:26:15
EFF (Full): Update channel key loaded. util.js:26:15
SecureDropTorOnion: Update channel key loaded. util.js:26:15
Checking for new rulesets. util.js:26:15
EFF (Full): A new ruleset bundle has been released.  Downloading now. util.js:26:15
EFF (Full): Downloaded ruleset signature checks out.  Storing rulesets. util.js:26:15
SecureDropTorOnion: A new ruleset bundle has been released.  Downloading now. util.js:26:15
SecureDropTorOnion: Downloaded ruleset signature checks out.  Storing rulesets. util.js:26:15
EFF (Full): Applying stored rulesets. util.js:26:15
SecureDropTorOnion: Applying stored rulesets. util.js:26:15
```
I assume the `SecureDropTorOnion: Could not import key.  Aborting. util.js:24:15` line is relevant. My guess is that some update that was triggered on extension startup took the `SecureDropTorOnion` update channel before it was properly setup with `update_update_channel` and failed (because it has nothing except the update channel name). But I'm not sure if this has to do with `get_simple_rules_ending_with` not returning the rules.

**Comment by Hainish** [comment]
How do I test this with my local HTTPS Everywhere build?  This script used to work, but doesn't seem to with this alpha anymore: https://github.com/EFForg/https-everywhere/blob/master/test/tor-browser.sh

**Comment by acatarineu** [comment]
You need to enable unsigned extensions for this to work now, this should do the trick: acatarineu@17f083a3570cf5834ae0b8a239506a6fc1f55422.

Note: I tested with alpha and I can still reproduce, it happened 2 out of 4 times I tested.

**Comment by Hainish** [comment]
It looks like the `SecureDropTorOnion` rulesets are getting added twice, and thereby failing this conditional:

https://github.com/EFForg/https-everywhere/blob/4183a2077a69a4fdb77fbb8c302906a4560634f6/chromium/background-scripts/rules.js#L740

We could just remove the conditional, but it's better to figure out why it's being added twice.  I'll look into it again tomorrow.

**Comment by Hainish** [comment]
@acatarineu can you see if this fixes the problem for you? https://github.com/Hainish/https-everywhere/commit/6fab7a15000dea85fb453183de85184531ea2ee6

**Comment by acatarineu** [comment]
Yes, with this I cannot reproduce the issue anymore. Thanks!
