### ISSUE TITLE
Codepen ruleset needs review

### ISSUE THREAD

**Issue by austinpray** [EFForg/https-everywhere#1910]
It is impossible to log out of http://codepen.io if you have https-everwhere enabled.

![screenshot 2015-06-11 14 04 31](https://cloud.githubusercontent.com/assets/2192970/8115817/a493fcea-1043-11e5-9763-e06f09e600ee.png)

@CodePen @chriscoyier

**Comment by reedy** [comment]
Is it because one of the js files aren't being loaded?

**Comment by austinpray** [comment]
![screenshot 2015-06-10 13 36 38](https://cloud.githubusercontent.com/assets/2192970/8117572/bba7b538-104e-11e5-859c-09cfc74d7eb5.png)

I'm almost positive it's because it is trying to call https://codepen.io/logout when it needs to be calling http://codepen.io/logout. The https is just a redirect back to http.

**Comment by quezo** [comment]
We just fixed it so that you can logout while using https everywhere. Thanks for bringing this to our attention.

**Comment by austinpray** [comment]
Sweet guys!

**Comment by jsha** [comment]
Thanks for fixing it, @quezo! For our own record keeping, this was caused by https everywhere issue #49.
