### ISSUE TITLE
Tor Browser: store.get is undefined error if we call create_update_channel too early

### ISSUE THREAD

**Issue by acatarineu** [EFForg/https-everywhere#19101]
In Tor Browser, for https://trac.torproject.org/projects/tor/ticket/28005 we send a "create_update_channel" followed by a "update_update_channel" message to HTTPS Everywhere extension. However, if we do this too soon, `create_update_channel` throws a `store.get is undefined` error. Currently, the workaround is to wait one second before sending the first `create_update_channel`, and retry if it stills throws the error. I'm assuming that if there is no error, then the extension was initialized properly and is able to process those messages.

Even if this assumption is correct, I think would be good to have a way from Tor Browser side to know whether the extension was initialized properly. For example, a message could be sent from `background.js` upon initialization (via `chrome.runtime.sendMessage`) and from Tor Browser side we could listen to it to avoid doing these retries. An alternative would be to make the extension accept those messages (maybe queue them?) even if it still has not finished initialization.

**Comment by zoracon** [comment]
I will look into getting this messaging sent over.

**Comment by Hainish** [comment]
@acatarineu https://github.com/EFForg/https-everywhere/pull/19309 sends the message string `"store_initialized"` - will this work?

**Comment by acatarineu** [comment]
Thanks, I tested and now I can send the first `create_update_channel` without the previous `store.get is undefined` error, just waiting until `store_initialized` message is received.

However, there seems to be some other issue when sending the second message `update_update_channel`. The channel gets updated (can be seen in the UI), but the rules are not fetched. I don't get a response to that `update_update_channel` message, which I assume means that `sendResponse(true)` is not called in https everywhere side, for some reason. If I add a 1 second wait between `create_update_channel` and `update_update_channel` messages, then it works fine.

**Comment by zoracon** [comment]
@acatarineu Do you still need someone from our side to take a look at your last comment? Sorry this fell off the plate a little
