### ISSUE TITLE
EASE exceptions broken on non-default ports (hosts and netlocs are used inconsistently)

### ISSUE THREAD

**Issue by g2p** [EFForg/https-everywhere#19107]
Type: code issue

I use EASE mode to encrypt everything by default.
I am trying to add an exception for a host that runs plain HTTP on port 8000.
I used the extension's menu to add an exception, and it got added as a netloc (host:port) in the extension preferences page.
Unfortunately, the exception isn't used properly by the extension, and I still get redirected to the same netloc with the HTTPS protocol, which fails.
Visiting without a port specification, and adding an exception, works, and the (IMHO underspecified) exception gets used correctly when I next visit on port 8000.

Suggested fix: interpret the exception list as netlocs rather than hostnames, and apply exceptions if and only if the ports match.

**Comment by abrain** [comment]
This seems to be covered in #19029 and already solved. Unfortunately, the release of the update had to be postponed, see discussion in #19032
