### ISSUE TITLE
Issue with redirect

### ISSUE THREAD

**Issue by Makishima** [EFForg/https-everywhere#19110]
Type: ruleset/website issue
# Domain: http://we.the-village.ru
I'm trying to follow a link in this post https://www.facebook.com/Villagemsk/posts/4292138030811979 but I'm stuck on https://amp.gs/0Xc7 without getting redirected

**Comment by pipboy96** [comment]
Do you have EASE mode on? This domain doesn't support HTTPS, and is not redirected by current rulesets.

**Comment by Makishima** [comment]
Yes, EASE mode is on. So how can I resolve this problem?

**Comment by pipboy96** [comment]
@Makishima Please downgrade to previous release. Sadly we made a broken release and COVID-19 lockdown prevents us from withdrawing it or making a new one. More information #19029. If you need help doing that, answer here please.

**Comment by zoracon** [comment]
Resolved with https://github.com/EFForg/https-everywhere/pull/19288
