### ISSUE TITLE
Travis is not running

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#19124]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Travis is not running for PR after #19108 and affect several new PRs.  

cc @J0WI @ivysrono @pipboy96

**Comment by gloomy-ghost** [comment]
The tests are actually running - https://travis-ci.org/github/EFForg/https-everywhere/builds/671143599 for #19122. GitHub isn't getting the results for some reason

**Comment by zoracon** [comment]
I am not sure why the connection to Github isn't being made at the moment. Will investigate today.

**Comment by zoracon** [comment]
This looks like there was some sort of outage occurring and webhooks are firing again. Will close for now but please reopen if this persists.
