### ISSUE TITLE
freedesktop release link broken

### ISSUE THREAD

**Issue by reedy** [EFForg/https-everywhere#1912]
From IRC

```
[06:52:35] <mcmc> I hate to be guy-who-reports-error-without-submitting-patch, but I've been super busy lately
[06:53:52] <mcmc> anyway, it seems like HTTPS Everywhere is breaking the release link here: https://wiki.freedesktop.org/nice/
[06:54:07] <mcmc> confirmed with with the relevant mailing list
[06:55:01] <mcmc> it's pretty easy to see that both the domain and the path of the URL you get are different than what's listed in the link
```

http://nice.freedesktop.org/releases/ becomes https://wiki.freedesktop.org/nice/releases/

**Comment by reedy** [comment]
```
	<rule from="^http://(apoc|dri|gypsy|ldtp|libbsd|libdlo|liboil|libopenraw|nice|nouveau|pm-utils|sitewranglers|swfdec|telepathy|testrepo|www|xorg)\.freedesktop\.org/wiki(?=$|\?)"
		to="https://wiki.freedesktop.org/$1" />

	<rule from="^http://(apoc|dri|gypsy|ldtp|libbsd|libdlo|liboil|libopenraw|nice|nouveau|pm-utils|sitewranglers|swfdec|telepathy|testrepo|www|xorg)\.freedesktop\.org/(?:wiki/)?"
		to="https://wiki.freedesktop.org/$1/" />
```

**Comment by 2d1** [comment]
The latter. Though I suggest excluding [\w-]+\.freedesktop\.org/+releases($|[?/]), unless it's clear that other projects don't have the same behavior.

**Comment by alanc** [comment]
http://xcb.freedesktop.org/dist/ has a similar issue and gets redirected to an invalid URL.

**Comment by jwilk** [comment]
The second rule seems overzealous.
It assumes that `$PROJECT.freedesktop.org/$FOO` is always the same as `$PROJECT.freedesktop.org/wiki/$FOO`, but I've seen no evidence of this except when `$FOO` is empty.

**Comment by jwilk** [comment]
<http://xcb.freedesktop.org/dist/> is a funny case.
There's exclusion for this particular URL, but the logic is backwards:
```xml
<exclusion pattern="^http://xcb\.freedesktop\.org/+(?!dist(?:$|[?/]))" />
```

So now the whole `xcb.freedesktop.org` is unprotected, with the exception of `/dist`, which is broken.

This whole ruleset looks so hairy (see also #3802), that I'm tempted to throw it away and redo it from scratch.

**Comment by J0WI** [comment]
It seems that this has been fixed.

**Comment by fooishbar** [comment]
Right, we did a wholesale conversion of fd.o to be TLS-only on all domains (with valid certs), earlier on this year. Please remove all exclusions for fd.o, if there are in fact any, and let me know if anything is broken. Thanks!

**Comment by J0WI** [comment]
@fooishbar these are great news!
You can find current issues with https documented on https://www.eff.org/https-everywhere/atlas/domains/freedesktop.org.html
Since you plan to move to TLS-only, sou should implement [preloaded HSTS](https://hstspreload.appspot.com/), this would make a rule in https-everywhere obsolete.

**Comment by fooishbar** [comment]
> Nonfunctional hosts in *freedesktop.org:
>		- planet *
> 	* Shows www.freedesktop.org

This was only ever transient, due to broken DNS; it was fixed long ago.

As for the rest of the sites, I can provide you an updated list of all our domains and those which redirect; is this the best place to do so?

> Since you plan to move to TLS-only, sou should implement preloaded HSTS, this would make a rule in https-everywhere obsolete.

Although ... this might be better. I'll look into that when I next get some time for admin work; thanks!

**Comment by J0WI** [comment]
> As for the rest of the sites, I can provide you an updated list of all our domains and those which redirect; is this the best place to do so?

Yes, you're welcome to open a pull request here with updates.
