### ISSUE TITLE
Premature FCC listing?

### ISSUE THREAD

**Issue by collina** [EFForg/https-everywhere#1915]
Pull request #1334 seems to have added apps.fcc.gov, but the HTTPS side does not contain content and has caused issues with accessing ECFS. The FCC would probably be the person with the real responsibility for this issue, but until then maybe the rule should be changed?

**Comment by jeremyn** [comment]
Thanks for the report. https://apps.fcc.gov was disabled as part of the fix for issue #2874. Closing issue.
