### ISSUE TITLE
Firefox ESR flags HTTPS Everywhere as an unsigned (insecure) addon and disables it.

### ISSUE THREAD

**Issue by develroo** [EFForg/https-everywhere#19177]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: maintenance bug

Firefox ESR V. 68.7.0esr (64-bit) Debian Testing (Bullseye)

Addon version 2020.3.16

Attached screenshot shows status.

Mozilla  ask you to visit [this URL](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct)
![Screenshot from 2020-04-18 03-37-29](https://user-images.githubusercontent.com/7777993/79626202-366bdb80-8126-11ea-9841-c2a5a5dd7f4b.png)

**Comment by develroo** [comment]
What more info do you need?

**Comment by pipboy96** [comment]
I can't reproduce this on macOS version of Firefox 68.7.0esr. Does it also happen  with other extensions?

**Comment by pipboy96** [comment]
@develroo Was unable to reproduce with Debian either. Can you create another profile and test if that fixes the issue.

**Comment by develroo** [comment]
I can try. Give me 24 hours not at the machine atm.

**Comment by pipboy96** [comment]
@develroo If you still have this issue please answer so I can reopen this issue.

**Comment by develroo** [comment]
> @develroo If you still have this issue please answer so I can reopen this issue.

Yes.. From what I can tell the latest version of the addon and ESR seem to work together now. No warnings. Thanks.
