### ISSUE TITLE
Travis fails (TEST="chrome beta" BROWSER=google-chrome-beta)

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#19188]
The stable version of chromedriver (version 81.x) is used to test against chrome beta (M83). 

https://github.com/EFForg/https-everywhere/blob/57b3ad89f5842069f198f00e159c642cc9189fb0/test/setup_travis.sh#L7

it gives the following error message: 

```session not created: This version of ChromeDriver only supports Chrome version 81```

Sadly, there is no immediate endpoint which provide the beta version of chromedriver from the official repository, otherwise the fix would be simple. 

https://chromedriver.storage.googleapis.com/index.html

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by zoracon** [comment]
Working on this at the moment, it's at the top of my priority to get this fixed ASAP

**Comment by zoracon** [comment]
Pushed in a fix, going to go through failing PRs and rerun these jobs. Thank you for your patience!

**Comment by zoracon** [comment]
Looks like `test/selenium/test_navigation.py::TestNavigation::test_httpnowhere_blocks ` test is acting strange. I'm assuming this is a Selenium issue but will not close until I found out what is going on, in case this is related.

**Comment by ivysrono** [comment]
If it takes long time, could we merge PRs only fails on chrome tests?
