### ISSUE TITLE
User rules offer no ability to modify or view details (also they don't display the name you give the rule on creation)

### ISSUE THREAD

**Issue by DFNCTSC** [EFForg/https-everywhere#19180]
Type: feature request / enhancement / UI

This seems like it should be done already considering how many years user rules have existed.

When you go into the Options for HTTPSE it **only** has the ability to delete the "HTTPS Everywhere User Rules" via red X's.

At a minimum these rules should display the  **rule names** the user assigns to them, not _the host_ the rules are applied to. (An optional extra feature would be to list the rules **[collapsable] by host** whilst still displaying the rule names in the individual host trees.)
Additionally from this menu you should be able to at the very least edit the same values that you're given when you create the rules. 
As well, it'd be nice if the rules could be toggled on/off individually from within the same menu.

Thanks for your time. :)

**Comment by Neonate14** [comment]
Any updates on this?

**Comment by pipboy96** [comment]
@Neonate14 Not yet.

**Comment by cschanaj** [comment]
Linking #16618 

>  there is some constraint in the current implementation (in lookups & caching) which rendered this more complicated than I have expected... And it is not possible to allow custom user rules names, meaning there is only 1 custom rule for each domain...

AFAIK, the custom user rule names have never worked (at least since the webextension version). `renitalizeAllRules` was slow when #16618 was introduced. So it leaves little option to implement this features that time. We can bring back custom user rule names if we ignore the performance issue on platforms without WASM.
