### ISSUE TITLE
pre-installation issue with tor-browser

### ISSUE THREAD

**Issue by 0-wiz-0** [EFForg/https-everywhere#19209]
Type: code issue

I'm packaging for pkgsrc and want to pre-install the https-everywhere plugin for it so that it can be updated by the users.

Following a stackoverflow post I found (https://stackoverflow.com/questions/37728865/install-webextensions-on-firefox-from-the-command-line) I made packages that install the xpi files for noscript and https-everywhere below `${MAINDIR}/distribution/extensions/`, like this:
````
-rw-r--r--  1 root  wheel  3076882 Apr 21 21:37 /usr/pkg/lib/tor-browser/distribution/extensions/https-everywhere@eff.org.xpi
-rw-r--r--  1 root  wheel   582656 Apr 21 21:37 /usr/pkg/lib/tor-browser/distribution/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi
````
I got the final names under which to install them from a tor-browser user profile into which I installed them manually.

When I start tor-browser without a profile, I see that the noscript xpi was copied automatically, but the https-everywhere one was not.

I.e., `${PROFILEDIR}/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi` exists but `https-everywhere@eff.org.xpi` is not there. I see the same in about:addons - NoScript is listed, but HTTPS Everywhere is not.

Any ideas what I might be doing wrong, or how to find out for sure?

Is the name wrong?

**Comment by zoracon** [comment]
The id is incorrect: `https-everywhere@eff.org.xpi`
Just missing that last `-eff` at `https-everywhere-eff@eff.org`.

Try that out.

**Comment by 0-wiz-0** [comment]
That was it. Thank you!
