### ISSUE TITLE
Allow installing locked update channel in Tor Browser

### ISSUE THREAD

**Issue by acatarineu** [EFForg/https-everywhere#19207]
This one is also related to https://trac.torproject.org/projects/tor/ticket/28005. For that, it would be nice to have a way to setup an update channel so that it cannot be edited via UI in `about:addons -> Preferences -> Update Channels` (just like the default EFF (Full) update channel). Maybe support a `locked` attribute in the `update_update_channel` message?

**Comment by pipboy96** [comment]
@acatarineu Thanks for suggestion. If possible, please explain how this would be useful?

**Comment by acatarineu** [comment]
Yes, sorry, I should have provided more context. As explained in a different bug (#19102), in Tor Browser Alpha we now (programatically) install a  `SecureDropTorOnion` update channel by sending `create_update_channel` + `update_update_channel` messages to the https-everywhere extension. It would be useful for us to be able to do so in a way that this channel cannot be edited via UI by users, so that it's treated like the default EFF (Full) channel.

In principle I don't think this requested change makes sense other than to Tor Browser. We use this message passing so that we don't have to do custom builds of https-everywhere of Tor Browser with the `SecureDropTorOnion` update channel preinstalled.

**Comment by pipboy96** [comment]
@acatarineu I think it should be possible for the user to disable this channel, but possibly it should not be deletable since it may be difficult to re-add it. Would that be a good option?

**Comment by acatarineu** [comment]
I think being able to disable the channel would be nice, but I thought this would be a different feature to be implemented, since currently it's not possible to individually disable update channels.

So if we can install the channel in a way that is non-editable except for possibly disabling/enabling it, I think it would be perfect.

**Comment by Hainish** [comment]
@acatarineu can you see if adding the `locked` attribute does the trick in https://github.com/Hainish/https-everywhere/tree/add-locked-attribute-to-update-channels?

**Comment by acatarineu** [comment]
Works for me, thanks!
