### ISSUE TITLE
Update Https everywhere on Microsoft Store

### ISSUE THREAD

**Issue by Tiamatti** [EFForg/https-everywhere#19211]
HTTPS Everywhere in [Microsoft Store is outdated](https://microsoftedge.microsoft.com/addons/detail/fchjpkplmbeeeaaogdbhjbgbknjobohb). The last version is 2019.11.7 launched in 01/22/2020. 

While [Chrome Store have the version 2020.3.16 ](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)from 03/16/2020

Do you intend to keep updating the Edge Store? Why so much difference if both are chromium browsers?

**Comment by zoracon** [comment]
It's outdated by one version because there was a significant bug introduced into the latest version. So it was decided to update the Microsoft store with the next release.

https://twitter.com/HTTPSEverywhere/status/1240699953267105792
