### ISSUE TITLE
Add cryptocurrency-related websites

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#19229]
This list is based on a list at https://cryptositeslist.com/. Number in parentheses indicates the Alexa rank of a domain.

## Alexa top 1M

- [x] iqoption.com (161) #19236
- [x] investing.com (290) #19235
- [ ] bitfun.co (1329)
- [ ] binance.com (1499)
- [ ] cointelegraph.com (2019)
- [ ] freebitco.in (2161)
- [ ] zb.com (2511)
- [ ] okex.com (3744)
- [ ] robinhood.com (4121)
- [ ] mellowads.com (4188)
- [ ] big.one (4235)
- [ ] cointraffic.io (4773)
- [ ] bitflyer.com (5719)
- [ ] etherscan.io (6247)
- [ ] minds.com (6291)
- [ ] beermoneyforum.com (6815)
- [ ] crypto.com (7354)
- [ ] indodax.com (7493)
- [ ] xtb.com (7848)
- [ ] treasury.gov (7962)
- [ ] binance.vision (8901)
- [ ] coinspot.com.au (9070)
- [ ] btc.com (9169)
- [ ] whattomine.com (9336)
- [ ] bitpanda.com (10170)
- [ ] newsbtc.com (10268)
- [ ] ethplorer.io (10299)
- [ ] bithumb.com (10440)
- [ ] coingecko.com (12434)
- [ ] deribit.com (12571)
- [ ] bitcoinist.com (13145)
- [ ] ccn.com (13377)
- [ ] paribu.com (16885)
- [ ] cryptowat.ch (17005)
- [ ] wirexapp.com (17453)
- [ ] insidebitcoins.com (17547)
- [ ] cryptocompare.com (17852)
- [ ] changelly.com (18013)
- [ ] block.io (19048)
- [ ] btcmanager.com (20562)
- [ ] admiralmarkets.com (20603)
- [ ] buybitcoinworldwide.com (24230)
- [ ] blockgeeks.com (25043)
- [ ] eobot.com (25942)
- [ ] coinone.co.kr (27003)
- [ ] genesis-mining.com (27075)
- [ ] bitinfocharts.com (30617)
- [ ] btc-echo.de (30680)
- [ ] bitcointicker.co (31589)
- [ ] coin360.com (34097)
- [ ] beincrypto.com (34105)
- [ ] trustwallet.com (34156)
- [ ] cryptobriefing.com (34254)
- [ ] d.tube (36760)
- [ ] cryptodaily.co.uk (37203)
- [ ] michaelnielsen.org (37899)
- [ ] blockonomi.com (39004)
- [ ] ethereumworldnews.com (40179)
- [ ] minergate.com (40210)
- [ ] worldcoinindex.com (40800)
- [ ] coinsquare.com (41120)
- [ ] coincap.io (42132)
- [ ] 1xbit.com (43830)
- [ ] cointracking.info (44920)
- [ ] fairmillions.com (45079)
- [ ] miningrigrentals.com (45593)
- [ ] coinmetrics.io (46883)
- [ ] coinigy.com (46912)
- [ ] messari.io (49241)
- [ ] uphold.com (51301)
- [ ] coinspeaker.com (54566)
- [ ] metamask.io (54685)
- [ ] disclose.tv (54713)
- [ ] cryptopanic.com (65150)
- [ ] newline.co (65769)
- [ ] bitcoinmining.com (66720)
- [ ] bravenewcoin.com (67645)
- [ ] nomics.com (67924)
- [ ] ethgasstation.info (68338)
- [ ] f2pool.com (70618)
- [ ] jaxx.io (72468)
- [ ] nulltx.com (72688)
- [ ] gate.io (73154)
- [ ] coinmarketcal.com (75699)
- [ ] preev.com (76247)
- [ ] xcoins.io (76761)
- [ ] dogecoin.com (78276)
- [ ] airdropalert.com (78404)
- [ ] ufx.com (79030)
- [ ] nuvoo.io (81212)
- [ ] coinad.com (82515)
- [ ] virgingalactic.com (83833)
- [ ] markets.com (85981)
- [ ] fortunejack.com (88855)
- [ ] coinatmradar.com (90517)
- [ ] coinwarz.com (90813)
- [ ] cryptominingfarm.io (91315)
- [ ] coinlib.io (91815)
- [ ] parity.io (92756)
- [ ] sapien.network (93454)
- [ ] blockstack.org (98983)
- [ ] luno.com (99363)
- [ ] fiatleak.com (100738)
- [ ] etherchain.org (103812)
- [ ] cryptopotato.com (105352)
- [ ] cryptokitties.co (107642)
- [ ] icodrops.com (107805)
- [ ] blockfolio.com (107814)
- [ ] billfodl.com (119650)
- [ ] cryptocontrol.io (123318)
- [ ] confirmo.net (125645)
- [ ] etherdelta.com (137640)
- [ ] celsius.network (148734)
- [ ] livebitcoinnews.com (151521)
- [ ] cryptoground.com (153231)
- [ ] easyminer.net (156918)
- [ ] bitcoinwallet.com (167351)
- [ ] openbazaar.org (179218)
- [ ] coinspectator.com (179223)
- [ ] bitmedia.io (180503)
- [ ] gatehub.net (180701)
- [ ] coinsbank.com (181390)
- [ ] mastersofcrypto.com (182220)
- [ ] walletgenerator.net (197649)
- [ ] globalcryptopress.com (200838)
- [ ] airdropbob.com (205906)
- [ ] groupfabric.com (209204)
- [ ] coinjournal.net (210915)
- [ ] betmoose.com (221024)
- [ ] fidelitycharitable.org (222971)
- [ ] exx.com (230723)
- [ ] coin.fyi (231115)
- [ ] all.me (232667)
- [ ] chainalysis.com (238955)
- [ ] cryptotrader.org (240710)
- [ ] metacert.com (243596)
- [ ] thebitcoin.pub (249994)
- [ ] trufflesuite.com (255923)
- [ ] kryptomoney.com (258219)
- [ ] oxbtc.com (259649)
- [ ] badcryptopodcast.com (264483)
- [ ] bitbond.com (265318)
- [ ] bitcoin.pl (265321)
- [ ] bitcoin.tax (265322)
- [ ] bostonfed.org (265710)
- [ ] coinnewsasia.com (267856)
- [ ] onchainfx.com (281970)
- [ ] delta.exchange (295965)
- [ ] bitkong.com (302304)
- [ ] bitco.in (303693)
- [ ] tidex.com (304227)
- [ ] cryptomining-blog.com (320655)
- [ ] bitronictech.net (335982)
- [ ] lykke.com (347239)
- [ ] multiminerapp.com (348879)
- [ ] zycrypto.com (365099)
- [ ] bitcoingarden.org (365216)
- [ ] righto.com (370585)
- [ ] cryptoninjas.net (379025)
- [ ] bitwala.com (380858)
- [ ] coin.market (381026)
- [ ] hashtaginvesting.com (381795)
- [ ] bitrss.com (393922)
- [ ] bitcoinchaser.com (397096)
- [ ] bitalk.org (401290)
- [ ] paycent.com (408254)
- [ ] altpocket.io (411418)
- [ ] trade.com (421377)
- [ ] coincenter.org (421676)
- [ ] cryptotrader.tax (421698)
- [ ] bitcoinspot.nl (434804)
- [ ] letstalkbitcoin.com (437471)
- [ ] smartbit.com.au (439402)
- [ ] bitlisten.com (445559)
- [ ] usethebitcoin.com (455912)
- [ ] bitcoinpaperwallet.com (456238)
- [ ] learnmeabitcoin.com (456568)
- [ ] upcoin.com (461111)
- [ ] abra.com (467838)
- [ ] coincheck.com (530686)
- [ ] uquid.com (534364)
- [ ] rightbtc.com (572012)
- [ ] 7bitcasino.com (580028)
- [ ] cryptozombies.io (583644)
- [ ] hodlhodl.com (587133)
- [ ] lbank.info (589496)
- [ ] bakkt.com (603106)

## The rest

- [ ] 10daysofbitcoin.com
- [ ] 21cryptos.com
- [ ] 4minutecrypto.com
- [ ] abitsky.com
- [ ] queue.acm.org
- [ ] acrypto.io
- [ ] adbit.biz
- [ ] aidus.io
- [ ] airdrops.live
- [ ] airdrops.me
- [ ] allcoin.ca
- [ ] altcoinstalks.com
- [ ] anonibet.com
- [ ] argocasino.com
- [ ] baobi.com
- [ ] baserank.io
- [ ] malaysia.belfrics.com
- [ ] blockchain.berkeley.edu
- [ ] betbtc.co
- [ ] binance.charity
- [ ] bitclubpool.com
- [ ] bitcoin-analytics.com
- [ ] bitcoin-millionaire.com
- [ ] bitcoin.com.au
- [ ] bitcoin.info.ke
- [ ] en.bitcoin.it
- [ ] bitcoin.kn
- [ ] bitcoincity.info
- [ ] bitcoincommodities.com
- [ ] bitcoindifficulty.com
- [ ] bitcoindoc.com
- [ ] bitcoinedge.org
- [ ] bitcoinfilm.org
- [ ] bitcoinmonitor.com
- [ ] bitcoinofamerica.org
- [ ] bitcoinpenguin.com
- [ ] bitcoinppi.com
- [ ] bitcoinprbuzz.com
- [ ] bitcoinshirtz.com
- [ ] bitcoinsinireland.com
- [ ] bitcoinwarrior.net
- [ ] bitdice.me
- [ ] blog.bitfinex.com
- [ ] bitgivefoundation.org
- [ ] bithope.org
- [ ] en.bithumb.com
- [ ] bitkassa.nl
- [ ] bitkee.com
- [ ] bitkoin.io
- [ ] bitkonga.com
- [ ] bitonic.nl
- [ ] blog.bitpay.com
- [ ] insight.bitpay.com
- [ ] bitrazzi.com
- [ ] bitsig.io
- [ ] bitzillions.com
- [ ] bl3p.eu
- [ ] blender.io
- [ ] blendingbot.com
- [ ] blockchain3d.info
- [ ] blockchainlion.com
- [ ] blockcrowd.org
- [ ] blox.io
- [ ] bonpay.com
- [ ] brainwallet.io
- [ ] blog.btc.com
- [ ] wallet.btc.com
- [ ] btc.top
- [ ] btcbox.co.jp
- [ ] btcrobot.com
- [ ] btcworldnews.com
- [ ] cbix.ca
- [ ] ccowl.com
- [ ] blog.cex.io
- [ ] changehero.io
- [ ] chaoex.com
- [ ] chatwithtraders.com
- [ ] bitcoin.clarkmoody.com
- [ ] cleanwatercoin.org
- [ ] cobinhood.com
- [ ] coinairdrops.com
- [ ] coinapi.io
- [ ] coinbeagle.com
- [ ] coinbet24.com
- [ ] coincalendar.info
- [ ] coindar.org
- [ ] coinfalcon.com
- [ ] coinfund.io
- [ ] exchange.coinjar.com
- [ ] coinmap.org
- [ ] coinmarketgame.com
- [ ] coinmastery.com
- [ ] coinna.com
- [ ] coinpress.io
- [ ] coinrail.co.kr
- [ ] coinreport.net
- [ ] coinroll.com
- [ ] coinscalendar.com
- [ ] coinsnap.eu
- [ ] blog.coinspectator.com
- [ ] coinspondent.de
- [ ] coinvault.io
- [ ] coinvision.co
- [ ] counterparty.io
- [ ] cryptalert.com
- [ ] crypto-games.net
- [ ] crypto101podcast.com
- [ ] cryptoanalyst.co
- [ ] en.cryptobadges.io
- [ ] cryptobuzz.io
- [ ] cryptocharityfund.com
- [ ] cryptocoin.cc
- [ ] cryptocoindude.com
- [ ] cryptoconverts.com
- [ ] cryptocoremedia.com
- [ ] cryptocousins.com
- [ ] cryptocurrencytalk.com
- [ ] cryptohackers.party
- [ ] cryptoheresy.com
- [ ] chainz.cryptoid.info
- [ ] cryptointalk.com
- [ ] cryptoknights.io
- [ ] cryptomartez.com
- [ ] community.cryptominded.com
- [ ] cryptonapp.tech
- [ ] cryptorials.io
- [ ] cryptorum.com
- [ ] cryptoscamdb.org
- [ ] cryptositeslist.com
- [ ] cryptostache.com
- [ ] cryptovoices.com
- [ ] cryptovue.com
- [ ] cubits.com
- [ ] dappdaily.com
- [ ] decryptionary.com
- [ ] deepwebthemovie.com
- [ ] dether.io
- [ ] dignitasinternational.org
- [ ] donationcoin.org
- [ ] dsx.uk
- [ ] eidoo.io
- [ ] electroncash.org
- [ ] elrond.com
- [ ] epicenter.tv
- [ ] erisx.com
- [ ] essaysonbitcoin.com
- [ ] etheroll.com
- [ ] etherreview.info
- [ ] etherwall.com
- [ ] ethfiddle.com
- [ ] ethlend.io
- [ ] ecb.europa.eu
- [ ] excc.co
- [ ] exploringtheblock.com
- [ ] faws.com
- [ ] fidelityhouse.io
- [ ] blog.flitpay.in
- [ ] forklog.net
- [ ] fortunecoins.club
- [ ] foxbit.com.br
- [ ] fried.com
- [ ] blog.genesis-mining.com
- [ ] programmingblockchain.gitbook.io
- [ ] glacierprotocol.org
- [ ] goanadupabitcoin.ro
- [ ] gobitcoin.io
- [ ] gpushack.com
- [ ] guiminer.org
- [ ] historyofbitcoin.org
- [ ] blog.icoalert.com
- [ ] indorse.io
- [ ] investfeed.com
- [ ] ipayyou.io
- [ ] jelurida.com
- [ ] just-dice.com
- [ ] kimcoin.com
- [ ] koineks.com
- [ ] komodoplatform.com
- [ ] blog.kraken.com
- [ ] lastcrypto.com
- [ ] liberland.org
- [ ] lifeonbitcoin.com
- [ ] lisk.io
- [ ] lopp.net
- [ ] lottopark.com
- [ ] luckyb.it
- [ ] luckybity.com
- [ ] madana.io
- [ ] mapofcoins.com
- [ ] mars.casino
- [ ] membrana.io
- [ ] monero.how
- [ ] moneromonitor.com
- [ ] moneytoken.com
- [ ] multidoge.org
- [ ] mycrypto.guide
- [ ] mycryptobuddy.com
- [ ] satoshi.nakamotoinstitute.org
- [ ] negociecoins.com.br
- [ ] nem.io
- [ ] noded.org
- [ ] omnilayer.org
- [ ] omniwallet.org
- [ ] openledger.info
- [ ] opentimestamps.org
- [ ] opreturn.org
- [ ] oshi.io
- [ ] outputs.today
- [ ] forums.overclockers.co.uk
- [ ] oxt.me
- [ ] blog.paxful.com
- [ ] peernova.com
- [ ] propsproject.com
- [ ] blog.purse.io
- [ ] safedice.com
- [ ] saltlending.com
- [ ] samlewis.me
- [ ] satoshicircle.com
- [ ] info.shapeshift.io
- [ ] sliver.tv
- [ ] softledger.com
- [ ] solume.io
- [ ] spend.com
- [ ] stampery.com
- [ ] steemdb.com
- [ ] strongcoin.com
- [ ] strymex.com
- [ ] taifuindexes.com
- [ ] terabox.me
- [ ] thebitcoinnews.com
- [ ] thebitcoinpodcast.com
- [ ] thecryptocurrencymagazine.com
- [ ] theswisspharmacy.com
- [ ] thewalletgenius.com
- [ ] tokeneconomy.co
- [ ] transactionfee.info
- [ ] fees.truelevel.io
- [ ] ukbitcoinblog.com
- [ ] unchainedpodcast.co
- [ ] digitalcurrency.unic.ac.cy
- [ ] upfolio.com
- [ ] usebitcoins.info
- [ ] utxo-stats.com
- [ ] blog.vaultoro.com
- [ ] vdice.io
- [ ] verystream.me
- [ ] pool.viabtc.com
- [ ] bitcoin-script-debugger.visvirial.com
- [ ] warchild.ca
- [ ] whatthefee.io
- [ ] gekko.wizb.it
- [ ] charts.woobull.com
- [ ] yogh.io
- [ ] blog.zebpay.com
- [ ] zenledger.io
- [ ] zumminer.com

## Preloaded

- [x] ~~youtube.com (2)~~
- [x] ~~reddit.com (19)~~
- [x] ~~github.com (34)~~
- [x] ~~medium.com (71)~~
- [x] ~~coursera.org (174)~~
- [x] ~~coinbase.com (2384)~~
- [x] ~~ig.com (2543)~~
- [x] ~~blockchain.com (5232)~~
- [x] ~~bitcoin.org (8401)~~
- [x] ~~mercadobitcoin.com.br (8667)~~
- [x] ~~ftx.com (10196)~~
- [x] ~~myetherwallet.com (14435)~~
- [x] ~~slushpool.com (17171)~~
- [x] ~~bitgo.com (23391)~~
- [x] ~~bitso.com (24289)~~
- [x] ~~gemini.com (24338)~~
- [x] ~~steemit.com (28302)~~
- [x] ~~bitcoin.com (36878)~~
- [x] ~~torproject.org (47233)~~
- [x] ~~btc-alpha.com (48465)~~
- [x] ~~keybase.io (49225)~~
- [x] ~~electrum.org (60674)~~
- [x] ~~coindeal.com (88220)~~
- [x] ~~fxopen.com (92560)~~
- [x] ~~bitminter.com (99583)~~
- [x] ~~earn.com (107689)~~
- [x] ~~mycrypto.com (131837)~~
- [x] ~~tokenmarket.net (149049)~~
- [x] ~~delta.app (222257)~~
- [x] ~~greenaddress.it (223552)~~
- [x] ~~bitrefill.com (232188)~~
- [x] ~~peername.com (232303)~~
- [x] ~~coin.dance (317418)~~
- [x] ~~bitcoincore.org (481765)~~
- [x] ~~777coin.com~~
- [x] ~~forum.bitcoin.com~~
- [x] ~~mining.bitcoin.com~~
- [x] ~~news.bitcoin.com~~
- [x] ~~bitcoin.info~~
- [x] ~~bitcoin.ninja~~
- [x] ~~bitedge.com~~
- [x] ~~ciphrex.com~~
- [x] ~~coin.space~~
- [x] ~~coinapult.com~~
- [x] ~~blog.coinbase.com~~
- [x] ~~commerce.coinbase.com~~
- [x] ~~pro.coinbase.com~~
- [x] ~~blog.coingate.com~~
- [x] ~~bitcoinfees.earn.com~~
- [x] ~~bitnodes.earn.com~~
- [x] ~~chrome.google.com~~
- [x] ~~play.google.com~~
- [x] ~~holytransaction.com~~
- [x] ~~litevault.net~~
- [x] ~~blog.trezor.io~~
- [x] ~~en.wikipedia.org~~
- [x] ~~xbtce.com~~
- [x] ~~gov.uk~~

## Redirected

- [x] ~~amazon.com (14)~~
- [x] ~~netflix.com (18)~~
- [x] ~~microsoft.com (30)~~
- [x] ~~soundcloud.com (95)~~
- [x] ~~businessinsider.com (232)~~
- [x] ~~khanacademy.org (249)~~
- [x] ~~coinmarketcap.com (268)~~
- [x] ~~digitaltrends.com (599)~~
- [x] ~~pluralsight.com (3139)~~
- [x] ~~coindesk.com (4237)~~
- [x] ~~kraken.com (4652)~~
- [x] ~~hitbtc.com (5814)~~
- [x] ~~bitpay.com (10568)~~
- [x] ~~a-ads.com (16462)~~
- [x] ~~bitstamp.net (16629)~~
- [x] ~~ethereum.org (17807)~~
- [x] ~~zaif.jp (17933)~~
- [x] ~~exodus.io (18408)~~
- [x] ~~cryptonator.com (18563)~~
- [x] ~~bittrex.com (18794)~~
- [x] ~~manning.com (20013)~~
- [x] ~~99bitcoins.com (22296)~~
- [x] ~~youtu.be (24954)~~
- [x] ~~bitfinex.com (30938)~~
- [x] ~~bitcointalk.org (31060)~~
- [x] ~~poloniex.com (33392)~~
- [x] ~~coinjar.com (41843)~~
- [x] ~~btcmarkets.net (43419)~~
- [x] ~~bitcoinmagazine.com (57636)~~
- [x] ~~shapeshift.io (59665)~~
- [x] ~~passwordsgenerator.net (60919)~~
- [x] ~~antpool.com (86627)~~
- [x] ~~gyft.com (99704)~~
- [x] ~~blockexplorer.com (114023)~~
- [x] ~~tradeblock.com (130791)~~
- [x] ~~bitaddress.org (145737)~~
- [x] ~~bitbay.net (146065)~~
- [x] ~~mycryptopedia.com (155715)~~
- [x] ~~stellar.org (238010)~~
- [x] ~~diasporafoundation.org (260696)~~
- [x] ~~tripwire.com (309154)~~
- [x] ~~itbit.com (345126)~~
- [x] ~~solidity.readthedocs.io (354876)~~
- [x] ~~bitcoin-vr.github.io (445555)~~
- [x] ~~bitcoinity.org (445556)~~
- [x] ~~bitcoincharts.com (456237)~~
- [x] ~~satoshidice.com (532951)~~
- [x] ~~bitcoinforum.com (559805)~~
- [x] ~~bitcoinarmory.com~~
- [x] ~~bitcoinaverage.com~~
- [x] ~~bitcoinchain.com~~
- [x] ~~bitcoincoreslack.herokuapp.com~~
- [x] ~~data.bitcoinity.org~~
- [x] ~~bitcoinwisdom.com~~
- [x] ~~btcturk.com~~
- [x] ~~cdecker.github.io~~
- [x] ~~coinfloor.co.uk~~
- [x] ~~coinforum.de~~
- [x] ~~blog.coinjar.com~~
- [x] ~~cryptovpn.com~~
- [x] ~~cryptrader.com~~
- [x] ~~dailyblockchain.github.io~~
- [x] ~~blog.ethereum.org~~
- [x] ~~gocoin.com~~
- [x] ~~hashnest.com~~
- [x] ~~korbit.co.kr~~
- [x] ~~paymium.com~~
- [x] ~~pineapplefund.org~~
- [x] ~~bitcoin.stackexchange.com~~
- [x] ~~therocktrading.com~~
- [x] ~~weusecoins.com~~
- [x] ~~winkdex.com~~

**Comment by Allcryptowebsites** [comment]
Hello,
maybe on this [List](https://allcryptowebsites.com) are more useful Crypto related Links to find!
