### ISSUE TITLE
Issue with app.hello.zendesk.com

### ISSUE THREAD

**Issue by maartenvhb** [EFForg/https-everywhere#19239]
Type: ruleset/website issue

# Domain: app.hello.zendesk.com

When accessing http://app.hello.zendesk.com in the Brave browser version 1.8.90, with HTTPS redirection enabled, which I believe uses the HTTPS Everywhere ruleset, the browser automatically loads https://app.hello.zendesk.com.

Looking at https://atlas.eff.org//domains/zendesk.com.html, there is already an exception in place for app.hello.zendesk.com:

exclusion pattern="^http://app\.hello\.zendesk\.com/"/
test url="http://app.hello.zendesk.com/"/

However, this does not seem to be working.

Any thoughts as to why this may be the case?

**Comment by pipboy96** [comment]
@maartenvhb Sorry, I cannot reproduce this on Chrome with current version of HTTPS Everywhere installed. This doesn't seem to be an HTTPS Everywhere issue. Please create an issue at [Brave's issue tracker](https://github.com/brave/brave-browser).

**Comment by maartenvhb** [comment]
Thanks for checking, @pipboy96 ! I'll reach out to Brave.
