### ISSUE TITLE
HTTPS Everywhere strips Set-Cookie line for DSL Reports Speed Test

### ISSUE THREAD

**Issue by jmwoods301** [EFForg/https-everywhere#19234]
It appears that DSL Reports has added a new Set-Cookie feature for running the HTTP version of their Speed Test tool.

Even when "Disable HTTPS Everywhere on this site" has been selected, DSLR complains that -

"Your browser was sent a Set-Cookie line that should have created cookie r7bc66b with random value."

"Failure: we did NOT see cookie r7bc66b in this new page request."

when doing their site cookie test.

The result is that the HTTP version of Speed Test cannot be run until HTTPS Everywhere is completely turned off.

This behavior is new as of 5/1/2020 when they made a change to their site to only allow registered users to run any version (HTTPS or HTTP).

I am a registered user and logged in to their site.

I have reported this to one of their moderators, as I think the issue is likely theirs, but I am surprised the only way the function works and their cookie test passes is to turn HTTPS Everywhere off completely.

**Comment by pipboy96** [comment]
@jmwoods301 Hello! Thanks for reporting this issue! Is there any way I can open the speed test without an account, so I can figure what the issue is?

**Comment by jmwoods301** [comment]
> 
> 
> @jmwoods301 Hello! Thanks for reporting this issue! Is there any way I can open the speed test without an account, so I can figure out what the issue is?

Unfortunately there isn't.

And there now appears to be a "minimum number of posts" required before users with an account can run the speed test.

If there is anything you would like me to collect, let me know.

**Comment by jmwoods301** [comment]
Another clue found using the Firefox debugger is the Set-Cookie cookie appears to have a format problem -

"Cookie “auid” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute."

I have no idea why the speed test function works when HTTPS Everywhere is completely disabled, and does not work when it's disabled for everything on the site.

**Comment by jmwoods301** [comment]
DSL Reports has reversed the changes made to their speed test.

Since then, HTTPS Everywhere works as expected.

Thanks for looking into it.
