### ISSUE TITLE
Please add rule for shoutout.wix.com

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#19252]
Type: new ruleset

Domain: shoutout.wix.com is missing from the [wix.com entry](https://atlas.eff.org//domains/wix.com-1.html)

For example: http://shoutout.wix.com/so/0LgXfwLb?cid=1154950d-d9fb-41c0-a7a7-91eb781b4aba#/main

It's used in email marketing and also shows up in places like https://emmaus.qld.edu.au/wp-content/uploads/Emmaus-College-eNewsletter-29-March-2018.pdf

**Comment by pipboy96** [comment]
Thanks! Closed by #19255.
