### ISSUE TITLE
forums.na.leagueoflegends.com doesn't support HTTPS

### ISSUE THREAD

**Issue by methanols** [EFForg/https-everywhere#1927]
https://forums.na.leagueoflegends.com/ produces Error 500.

An exclusion in [League_of_Legends.com.xml](https://github.com/EFForg/https-everywhere/blob/stable/src/chrome/content/rules/League_of_Legends.com.xml) probably fixes this.

**Comment by finaljason** [comment]
Thanks for your report. The commit referenced above should solve your issue. If you want you can do a little more extensive testing with the rewritten ruleset, but there shouldn't be any greater problems.
