### ISSUE TITLE
Does not appear the option to add a website to my HTTPS Everywhere user rules

### ISSUE THREAD

**Issue by Henriquemcc** [EFForg/https-everywhere#19276]
When I try to add this specific website `ipv6.br` to my website rule list the button "Adicione uma exceção para esse site" (add a exception for this site) does not appear. 

![bug https everywhere](https://user-images.githubusercontent.com/31051669/81939442-b9207300-95cc-11ea-8094-5f0732bf48e9.png)

Type: code issue

More information:

HTTPS Everywhere version: 2020.3.16.
Google Chrome Version: 81.0.4044.138 (64 bits).
Operating System: Ubuntu 20.04 LTS.

**Comment by pipboy96** [comment]
Please go to https://ipv6.br/, not http://ipv6.br/.

**Comment by Henriquemcc** [comment]
Now it worked. Thanks
