### ISSUE TITLE
Can't add HTTPS Everywhere extension to Chromium 81.0.4044.138 on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by escarta** [EFForg/https-everywhere#19287]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

When I try to add HTTPS Everywhere extension to Chromium 81.0.4044.138 on a fresh install of Ubuntu 20.04 LTS gets the error "Se esperaba el ID "gcbommkclmclpchllfjekcdonpmejbdp", pero se ha detectado el ID "efgagbdbanhcledjfakhkjmedkpdjmmf"".
![Captura de pantalla de 2020-05-20 12-22-31](https://user-images.githubusercontent.com/46460025/82435551-bfaf5e80-9a94-11ea-8a36-4eaeeddb49e3.png)

**Comment by doopler** [comment]
I have the same error..chrome 83
![Screen Shot 2020-05-20 at 14 38 51](https://user-images.githubusercontent.com/42199374/82442137-bed3f800-9aa7-11ea-81a0-30a49c7586fe.png)

**Comment by RooneyMcNibNug** [comment]
I'm getting the same results in Chromium on a Fedora 31 box. I'm not sure what level this Extension ID mismatch is occurring on, but that seems to be the clear root issue?

**Comment by pipboy96** [comment]
We need someone at EFF to look at this. @zoracon @Hainish

**Comment by zoracon** [comment]
Looks like a file discrepancy caused an issue. We are working to deploy an update as soon as possible. Sorry for the inconvenience and thank you for reporting!

**Comment by KeithMyers** [comment]
Can't add HTTPS Everywhere extension to Google Chrome version Version 83.0.4103.61 (Official Build) (64-bit) in Ubuntu 20.04 LTS.  Error is:
Expected ID "gcbommkclmclpchllfjekcdonpmejbdp", but ID was "efgagbdbanhcledjfakhkjmedkpdjmmf"

**Comment by zoracon** [comment]
This has been resolved in Chrome store! Please go ahead and retry.
