### ISSUE TITLE
Icon does not reflect some site are whitelisted

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#19293]
Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

# Steps to reproduce:

1. Install HTTPS Everywhere version 2019.11.7 and disable automatic updates.
2. Turn on Ease mode, visit `http://www.pettigrew.lib.nc.us:8080/`
3. After being redirected to the HTTPS Everywhere warning page, choose "Open insecure page" 
4. HTTPSE redirects user to HTTP version of the webpage 

# Observations:

Icon remained to show the EASE mode (the red icon).

# Expected:

Icon show that HTTPS Everywhere is disabled (the grey icon).

**Comment by zoracon** [comment]
Can you test on version 2020.8.13 to see if the issue persisted?

**Comment by cschanaj** [comment]
I am able to reproduce this issue with Firefox 79.0 on Ubuntu 20.04 LTS. The extension icon shows EASE mode is enforced despite it is disabled per site by the user.  It appears to affect hostname which specified a port number only, however, with `http.badssl.com` the icon shows a disabled icon. 

### www.pettigrew.lib.nc.us:8080 (red icon is incorrectly shown)

![image](https://user-images.githubusercontent.com/23636124/91177608-42733580-e6e4-11ea-9ce1-11e9cf4b678e.png)

### http.badssl.com (grey icon is expected)

![image](https://user-images.githubusercontent.com/23636124/91178117-fc6aa180-e6e4-11ea-82a4-efbf7f13c90f.png)
