### ISSUE TITLE
Release 2020.5.20 don't fix #19288 and #19110

### ISSUE THREAD

**Issue by Makishima** [EFForg/https-everywhere#19306]
Hello!
My previous issue #19110 was closed as resolved in #19288. But I have exactly the same problem as described in #19110 while using 2020.5.20.

**Comment by pipboy96** [comment]
Try re-adding the exclusion.

**Comment by Makishima** [comment]
> Try re-adding the exclusion.

I do not have any exclusion for this site. After I add http://we.the-village.ru as exclusion it's work now. 

I opened this issue because there is no mention of exclusion in #19288 and #19110. If it is intended to add exclusion so we can close this ticket.

**Comment by pipboy96** [comment]
@Makishima We don't have any ruleset that redirects http://we.the-village.ru/ to HTTPS. If adding the exclusion stopped http://we.the-village.ru/ redirecting in EASE mode, this issue is resolved.
