### ISSUE TITLE
Make install-dev-dependencies.sh work for Linux != Ubuntu/Debian

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#1931]
It doesn't work with Fedora 22 because 'dnf' has to be used instead of 'apt-get'.
When I tried to write a little patch I noticed that I don't know the names of the equivalent packages, e.g. libxml2-dev.

**Comment by reedy** [comment]
libxml2-devel https://apps.fedoraproject.org/packages/libxml2-devel

**Comment by KommX** [comment]
I hope #1942 is doing the trick.

**Comment by jsha** [comment]
Fixed by #1942.
