### ISSUE TITLE
Cloudfront rule should be removed

### ISSUE THREAD

**Issue by dpmccabe** [EFForg/https-everywhere#1932]
There are plenty of issues in this repo and around the web documenting how this add-on can break certain websites that use Cloudfront. The fact that there is a rule for Cloudfront at all suggests the developers here don't understand what Cloudfront is and how it works.

Say I have a site, `http://example.com`, with an asset `http://asdf.cloudfront.net/logo.png` in my homepage HTML. The first time a request to `http://asdf.cloudfront.net/logo.png` is made, Cloudfront will fetch `http://example.com/logo.png` from my web server. It fetches this image once and then caches it and serves it via the CDN thereafter.

The default Cloudfront setting is to proxy this request based on whether the browsing user is accessing `example.com` via HTTP or HTTPS. So if I visit `https://example.com`, Cloudfront fetches and caches `https://example.com/logo.png`. Now, the problem is that if I have a site that isn't SSL-secured, the HTTPS Everywhere user will visit `http://example.com` and Cloudfront will try to fetch `https://example.com/logo.png` from my web server (assuming it hasn't been cached yet), which is impossible. Thus, the logo doesn't display for that user. Instead, Cloudfront serves a 502 error page in place of the image.

Wait, it gets worse. Not only does the logo not display for that user who happened to be the first person to request `logo.png`, now Cloudfront serves that 502 page to _everyone_ regardless of whether they use this extension.

This is extremely opinionated behavior and a serious problem. If I put `http://asdf.cloudfront.net/logo.png` in my HTML, I expect the browser to request `http://asdf.cloudfront.net/logo.png`, *period*. I don't expect the browser to be internally redirected somewhere else. Not only that, how do I know this extension forwards all the necessary HTTP headers when it redirects? Fonts and certain other assets need a particular set of request headers in order to be rendered by the browser. Issue #49 suggests this might still be a problem.

As a developer, I shouldn't have to muck around with my CDN settings in order to work around a bug in a browser extension. Redirecting `http://somebank.com` to `https://somebank.com` is one thing--and that's a great feature--but breaking my CDN is something else.

**Comment by fuzzyroddis** [comment]
Hi @dpmccabe could you please provide a url to your site?

**Comment by jsha** [comment]
@dpmccabe Thanks for the feedback! It sounds like your CDN is misconfigured. The cache buckets for the HTTP and HTTPS version of your site should not be shared. Additionally, your CDN should not be caching 502s. It may be a hassle, but I strongly suggest you contact Cloudfront support to fix your caching issue. It may be causing other problems you haven't noticed yet.

If you provide the URL to your site, we can exclude it from HTTPS Everywhere so users of the extension won't see a broken page. That said, I'd definitely encourage you to deploy HTTPS. You can get a free certificate from https://www.startssl.com/ or https://buy.wosign.com/free/. Implementing HTTPS early on in your site's lifetime will save you a lot of hassle versus implementing it later.

**Comment by dpmccabe** [comment]
The site I've witnessed this bug on is a staging server whose URL I can't share publicly. My production site is accessible only over SSL.

Just because this extension triggers a bug in my asset hosting does not mean my CDN is misconfigured. You might want to read up [Cloudfront's caching behavior](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html). It will cache 400/500 error pages for as long as TTL sent from the hosting server and I think this is a reasonable behavior.

Having separate distributions for HTTP and HTTPS will not solve this problem. In addition to being completely unnecessary from the standpoint of setting up a Cloudfront CDN (a single distribution handles both protocols), it requires the endpoint server be accessible via HTTPS since the extension will redirect the HTTP Cloudfront requests no matter what.

To reiterate, this extension should never rewrite a web request from HTTP to HTTPS unless the HTTPS endpoint is guaranteed to exist. **This is not the case with Cloudfront** and it is not a matter of misconfiguration on either the CDN or the originating server. You are assuming that if `http://foo.cloudfront.net/bar` exists then `https://foo.cloudfront.net/bar` must also exist. This is simply incorrect in the case of Cloudfront.

**Comment by jsha** [comment]
In my judgement, the benefit to our users of including the broad Cloudfront rewrite rule is worth the occasional breakage. It sounds like the best fix in your case is to disable the Cloudfront ruleset. Navigate to any site that triggers the rewrite, click the HTTPS Everywhere icon, then click the "Cloudfront" entry to disable that ruleset.

Thanks,
Jacob

**Comment by fuzzyroddis** [comment]
@jsha :+1:
