### ISSUE TITLE
Google Translate is not upgraded by the Google ruleset

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#19337]
Type: ruleset/website issue

Domain: translate.google.com

It looks like the ruleset for `google.com` doesn't work for `translate.google.com`.

For example, http://translate.google.com/translate?hl=en&sl=en&tl=ny&u=https://www.google.com/ stays on HTTP whereas https://translate.google.com/translate?hl=en&sl=en&tl=ny&u=https://www.google.com/ works fine.

(Originally reported on https://github.com/brave/brave-browser/issues/4483.)

**Comment by pipboy96** [comment]
Sorry, I was unable to reproduce this issue. It's likely that it is specific to Brave HTTPS rewriting engine. `translate.google.com` is redirected by [Google.tld_Subdomains.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.tld_Subdomains.xml) ruleset.
