### ISSUE TITLE
Problem with potentiallyApplicableRuelsets / "rs is null" exception

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#1933]
Testing from git, I'm seeing the following errors in the Firefox developer console:

HTTPS Everywhere WARN: Malformed host passed to potentiallyApplicableRulesets: 
**rs is null**  [HTTPSRules:line 514](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/code/HTTPSRules.js#l514)

**Comment by jsha** [comment]
I can't reproduce. More details?

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
