### ISSUE TITLE
EASE doesn't upgrade http://www.photopea.com

### ISSUE THREAD

**Issue by dentistformyeye** [EFForg/https-everywhere#19347]
Type: ruleset/website issue

# Domain: photopea.com

## Description of bug and actual result
When EASE is on, connecting to http://photopea.com fails and triggers the "non-HTTPS page" error.
![image](https://user-images.githubusercontent.com/51429646/85209449-2b8c1d80-b306-11ea-961f-4daa388b69eb.png)

## Expected result
When the user tries to connect to http://photopea.com, EASE should automatically change the URL to https://photopea.com, which should successfully end up at https://www.photopea.com.

## Additional notes
The site seems to automatically upgrade to HTTPS on its own without the help of the browser or HTTPS Everywhere, so turning off EASE is a workaround. The domain isn't in the HTTPS Everywhere rules.

**Comment by zoracon** [comment]
Can you please give info on what browser and version of it you are using. I am not able to replicate on Firefox 77.0.1 on Ubuntu Linux.

**Comment by dentistformyeye** [comment]
I'm using Brave Desktop version 1.10.97 (Chromium 83.0.4103.116) on macOS 10.15.4.
The issue appears only after I enable Javascript on photopea.com. Even if I disable JS afterward, the issue persists unless I clear my site data and cache.

Here is a screen recording:
https://youtu.be/CdVu5-eVs58

**Comment by pipboy96** [comment]
@dentistformyeye Brave has its own HTTPS rewriter based on HTTPS Everywhere rulesets. It may cause conflicts, so try disabling it:

![image](https://user-images.githubusercontent.com/46632672/85620020-d89ac900-b66b-11ea-85dc-c3d9bd6bb239.png)

**Comment by dentistformyeye** [comment]
Disabling the Brave shield or disabling HTTPS Everywhere for photopea.com only while EASE is on still triggers the error. Disabling EASE or turning off HTTPS Everywhere works normally.
The bug is very minor though; I have to go out of my way to trigger it. Typing in photopea.com (rather than http://photopea.com) works normally no matter what.

**Comment by zoracon** [comment]
@dentistformyeye  With the video you provided I am definitely seeing the HTTPS connection (from exclamation mark for insecure to the padlock for HTTPS) and the EASE mode page triggering each time. You may see a slight lag at times with upgrading, but it's connecting to HTTPS. Closing for now. Also we aren't on official Brave support, except for rulesets.
