### ISSUE TITLE
Please add http://pirilampo.org/ to the ruleset

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#19346]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)
[//]: #
[//]: # (If you are submitting a new ruleset, please check the list at)
[//]: # (https://www.eff.org/https-everywhere/atlas/index.html and the open)
[//]: # (issues and pull requests to make sure it doesn't already exist.)

Type: new ruleset

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com)
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)

Domain: `pirilampo.org`

https://pirilampo.org/ works fine on HTTPS, but there is no redirect from http://pirilampo.org/

https://pirilampo.org/org-mode/syntax/ on the other hand has problems loading stylesheets if the mixed content blocker is ON. I suspect these might go away once the domain is added to the HTTPS Everywhere ruleset though.

**Comment by pipboy96** [comment]
@fmarier Thanks for suggestion. Unfortunately, this domain currently can't be redirected due to severe mixed content issues.

**Comment by fmarier** [comment]
Thanks for checking @pipboy96 . What's the best way to test a new potential rule (for example to see if adding the domain would trigger mixed-content blocking)? Is there an easy way to add a rule to the Firefox extension for testing?

**Comment by pipboy96** [comment]
@fmarier Go to `moz-extension://[extension_uuid]/pages/debugging-rulesets/index.html` (the extension UUID is different on different installs, you can get it from `about:debugging#/runtime/this-firefox`).
