### ISSUE TITLE
Overflow in popup when pinned to overflow menu on Firefox

### ISSUE THREAD

**Issue by pablotheissen** [EFForg/https-everywhere#19366]
When the extension is pinned to the overflow menu, scrollbars are shown in the popup:

![image](https://user-images.githubusercontent.com/13626568/85397356-f15b8f80-b542-11ea-9944-235d90d2b01e.png)

When unpinned the popup is sized appropriately:
![image](https://user-images.githubusercontent.com/13626568/85397485-1f40d400-b543-11ea-8bc6-5e1dfc7681af.png)

This happens at least with Firefox set to German or set to English.

* Firefox 77
* Windows 10 Edu, 2004
* Scaling in Windows set to 100%, 2560×1440

**Comment by zoracon** [comment]
Thank you for reporting with details! Will look into this soon.

**Comment by zoracon** [comment]
Can you check version 2020.8.13 to see if your issue persisted?

**Comment by pablotheissen** [comment]
![image](https://user-images.githubusercontent.com/13626568/91178232-63338f00-e6d4-11ea-9e9d-3722f1d4c0a4.png)
Unfortunately, yes...

**Comment by Eagle3386** [comment]
@zoracon More than a year later, the issue still persists:
![image](https://user-images.githubusercontent.com/5111490/143881700-c0a8a573-ed85-4868-ad7e-34bcab361613.png)
Would you mind taking another try to fix it?
