### ISSUE TITLE
Ruleset updates are still fetched when "Auto-update rulesets" option is disabled

### ISSUE THREAD

**Issue by joediggs111** [EFForg/https-everywhere#19369]
Type: code issue

Issues:

1. It seems HTTPS Everywhere ignores whether one wants it to call home or not.
2. I am clueless as to why securedrop.org needs to be involved at all.
3. Securedrop.org "trusts" and is altered by cloudflare, which uniquely identifies each browser session.

Steps to reproduce:

1. Open TorBrowser and go to about:addons -> HTTPS Everywhere
2. Un-check "Auto-update rulesets"
3. Restart TorBrowser
4. See among onion circuits that it is doing the same WRONG behavior

Please see the attached screenshot with helpful mark-up of HTTPS-Everywhere calling home to securedrop.org (why?) which is hosted on cloudflare and serves an alt-svc header which directs the browser to an custom-generated-per-connection onion address, effectively identifying your TorBrowser with a unique request every time it loads.  Bug or malfeasence?

![wtf_torbrowser](https://user-images.githubusercontent.com/67403472/85651502-ba4ac280-b697-11ea-9057-b3d1701e01a4.jpg)

**Comment by pipboy96** [comment]
The request to `securedrop.org` is caused by downloading additional rulesets (from `https://securedrop.org/https-everywhere/`) added by Tor Browser. See https://trac.torproject.org/projects/tor/ticket/28005 for more information. I reproduced these requests still being made even when "Auto-update rulesets" option is disabled and will try fixing it.

**Comment by joediggs111** [comment]
Thanks for fixing the main bug.

It still occurs to me that deanonymizing yourself to cloudflare every time you launch TorBrowser is _surely_ not the intended behavior.  So it seems to me there is still a bug left.  Why does HTTPS Everywhere reach out to 2 different rulesets sites by default, and what exactly is being fetched from securedrop.org?  Who is responsible for that?  And what is the reasoning behind it?

Thank you.

**Comment by pipboy96** [comment]
@joediggs111 Tor Browser adds an additional ruleset pack to HTTPS Everywhere, which is downloaded from https://securedrop.org/https-everywhere/ (unfortunately, currently there is no setting to disable it right now). This ruleset pack is limited to domains matching `*.securedrop.tor.onion`.

No information is sent to securedrop.org, and only three files are downloaded:

- https://securedrop.org/https-everywhere/latest-rulesets-timestamp
  - This file only contains a timestamp of the latest version of the ruleset pack.
    Current file contents:
    ```
    1588004096
    ```
- https://securedrop.org/https-everywhere/default.rulesets.1588004096.gz
  - This file contains the rulesets contained in the ruleset pack
    Current file contents (ungzipped and indented):
    ```
    {
      "timestamp": 1588004096,
      "reference": "14be6e7cea757e2620ec8828bb1754bdd0083c39",
      "rulesets": [
        {
          "name": "The Intercept",
          "target": [
            "theintercept.securedrop.tor.onion"
          ],
          "rule": [
            {
              "from": "^http[s]?://theintercept.securedrop.tor.onion",
              "to": "http://xpxduj55x2j27l2qytu2tcetykyfxbjbafin3x4i3ywddzphkbrd3jyd.onion"
            }
          ]
        },
        {
          "name": "Lucy Parsons Labs",
          "target": [
            "lucyparsonslabs.com.securedrop.tor.onion"
          ],
          "rule": [
            {
              "from": "^http[s]?://lucyparsonslabs.com.securedrop.tor.onion",
              "to": "http://qn4qfeeslglmwxgb.onion"
            }
          ]
        },
        {
          "name": "Lucy Parsons Labs",
          "target": [
            "lucyparsonslabs.securedrop.tor.onion"
          ],
          "rule": [
            {
              "from": "^http[s]?://lucyparsonslabs.securedrop.tor.onion",
              "to": "http://qn4qfeeslglmwxgb.onion"
            }
          ]
        }
      ]
    }
    ```
- https://securedrop.org/https-everywhere/rulesets-signature.1588004096.sha256
  - This file contains a RSA electronic signature for the ruleset pack, which is checked by HTTPS Everywhere before loading the pack.

I hope this is a sufficient proof that the traffic to securedrop.org created by Tor Browser is not malicious.

I recommend you to take a look at [update.js](https://github.com/EFForg/https-everywhere/blob/master/chromium/background-scripts/update.js) and [update_channels.js](https://github.com/EFForg/https-everywhere/blob/master/chromium/background-scripts/update_channels.js) in HTTPS Everywhere source, and [HttpsEverywhereControl.jsm](https://gitweb.torproject.org/tor-browser.git/tree/browser/components/onionservices/HttpsEverywhereControl.jsm?h=tor-browser-68.10.0esr-9.5-1) in Tor Browser source.

Also, I recommend you to open an issue in the [Tor Browser bug tracker](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues).

Have a nice day!
