### ISSUE TITLE
See: http://blog.chromium.org/2013/11/protecting-windows-users-from-malicious.html

### ISSUE THREAD

**Issue by sema0703** [EFForg/https-everywhere#19392]
See: http://blog.chromium.org/2013/11/protecting-windows-users-from-malicious.html

There are some alternatives, though none seem applicable here: https://developer.chrome.com/extensions/external_extensions

_Originally posted by @semenko in https://github.com/EFForg/https-everywhere/issues/819#issuecomment-66883300_

**Comment by pipboy96** [comment]
This doesn't seem to be solvable from our side, except by removing this download link altogether, due to us not having any control over Chrome's policies.
