### ISSUE TITLE
"add a rule for this site" rules not saving

### ISSUE THREAD

**Issue by aaronwi** [EFForg/https-everywhere#19420]
`Version: 2020.5.20`
`Rulesets version for EFF (Full, Bundled): 2020.5.20`

When trying to add a custom regex for a sub domain redirect, the rule is not 

to create this issue, I used this entry:

`Smile redirect`
`^http[s]?://www\.amazon\.com$`
`https://smile.amazon.com`

other variants such as `^http://www\.amazon\.com/` `^https://www\.amazon\.com$` dont work either

result:

nothing saved, no new rule created

**Comment by zoracon** [comment]
Closing for now, if this issue persisted I can reopen.
