### ISSUE TITLE
Expanding tu-darmstadt.de

### ISSUE THREAD

**Issue by nmxcgeo** [EFForg/https-everywhere#19421]
Type: new ruleset
Domain: tu-darmstadt.de

Hello,

I plan to expand expand the ruleset of [tu-darmstadt.de](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/TU-Darmstadt.de.xml) substantially. In order to do this, I first ran Sublist3r as suggested and got 1914 domain names. 

To further filter them I ran a `curl`command against them and now I have got the following sets of domains: 

- [x] 1. exit code 6: Couldn't resolve host 
- [x] 2. exit code 7: Failed to connect to host
- [x] 3. exit code 28: Operation timeout
- [x] 4. exit code 35: SSL connect error
- [x] 5. exit code 56: Failure in receiving network data
- [x] 6. exit code 60: Peer certificate cannot be authenticated with known CA certificates
- [x] 7. HTTP status 200 OK 
- [ ] 8. HTTP status 301 Moved Permanently
- [ ] 9. HTTP status 302 Moved temporarily
- [ ] 10. HTTP status 303 See Other
- [ ] 11. HTTP status 307 Temporary Redirect
- [ ] 12. HTTP status 400 Bad Request
- [ ] 13. HTTP status 401 Unauthorized
- [ ] 14. HTTP status 403 Forbidden
- [ ] 15. HTTP status 404 Not Found
- [ ] 16. HTTP status 405 Method not allowed
- [ ] 17. HTTP status 500 Internal Server Error
- [ ] 18. HTTP status 503 Service Unavailable

I assume I should exclude points 1 to 6 from further analysis (I tested against Mozillas set of accepted roots and their known intermediates).
I assume that I have to check point 7 by hand. 
I assume that points 8 to 11 can be included into the ruleset as long as they redirect to https.
I am completely unsure what to do about the rest. 

Can you give me some advice, which domains would be interesting and which can be discarded automatically?

Greetings
Nmxcgeo

**Comment by pipboy96** [comment]
@nmxcgeo Can you create a [Gist](https://gist.github.com/) and copy the domain list there?

**Comment by nmxcgeo** [comment]
You can find the Gist at https://gist.github.com/nmxcgeo/578a6060cf84877888c2a9279759670a
