### ISSUE TITLE
broken CSIRO rule

### ISSUE THREAD

**Issue by bentley** [EFForg/https-everywhere#1944]
“CSIRO (partial)” (`src/chrome/content/rules/CSIRO.xml`) makes pages inaccessible.

For example, http://www.atnf.csiro.au/people/mcalabre/WCS/ is a real page, but https://www.atnf.csiro.au/people/mcalabre/WCS/ returns 404.

**Comment by fuzzyroddis** [comment]
Thanks @bentley for reporting it, I've gone ahead and submitted a fix.
It appears they no longer support https and just have a page saying make sure you have the correct protocol.
