### ISSUE TITLE
Ticketmaster rule causes pages to break

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#1953]
http://www.ticketmaster.com/WWE-Live-SummerSlam-Heatwave-Tour-tickets/artist/1989737

Tour Tickets and Event Dates will just spin on loading for a while before going to a failure page.  Disabling the Ticketmaster (partial) rule resolves the issue.

Using Firefox 38.0.5 on Windows 7 with HTTPSE 5.0.5

**Comment by reedy** [comment]
The console (on Chrome anyway), is full of Access-Control-Allow-Origin related errors

**Comment by terrorist96** [comment]
http://www.ticketmaster.com/Snoop-Dogg-tickets/artist/763942

Tickets/Concert Dates element won't load due to Ticketmaster (partial) rule.
In addition, after about 20 seconds, the page will forward to a page that says
> We're sorry, we're unable to process your request. Please try again.

**Comment by fuglede** [comment]
Also breaks https://billetnet.dk
