### ISSUE TITLE
garmin.opentopomap.org has different websites for https and http

### ISSUE THREAD

**Issue by helohe** [EFForg/https-everywhere#19530]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #

Type: ruleset/website issue

[//]: # (Uncomment and fill the domain bellow if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)

Domain: https://garmin.opentopomap.org/

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

https://garmin.opentopomap.org/ has different website versions for both http and https versions.
The http version contains the content, so that is what people want to visit.

**Comment by pipboy96** [comment]
https://garmin.opentopomap.org/ has an invalid certificate too.

**Comment by pipboy96** [comment]
https://garmin.opentopomap.org/ doesn't seem to be redirected by the current ruleset for [opentopomap.org](https://opentopomap.org/), see [OpenTopoMap.org.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/OpenTopoMap.org.xml).
