### ISSUE TITLE
Request: gainward.com

### ISSUE THREAD

**Issue by war59312** [EFForg/https-everywhere#19562]
Request: gainward.com

Site supports https but not forwarding to it by default

**Comment by pipboy96** [comment]
@war59312 Thanks! Closed by #19563.

**Comment by pipboy96** [comment]
@war59312 Do you know any way to contact the website owners? This misconfiguration is pretty easy to fix, but it can only be fixed by the website owner.

**Comment by war59312** [comment]
http://www.gainward.com/main/contact.php?lang=en

Their site is all screwed up, the top menus don't even work for example.
