### ISSUE TITLE
Encrypt All Sites Eligible is ON should provide option to open HTTPS website forcibly

### ISSUE THREAD

**Issue by NN---** [EFForg/https-everywhere#19576]
I have configured: "Encrypt All Sites Eligible is ON".
When I open this website http://vsixgallery.com/extension/e83d71b8-8bfc-4e06-b145-b0388910c016/ , I have the following choice:

![image](https://user-images.githubusercontent.com/580536/92888214-cbe17200-f41d-11ea-8491-ea0585b73f0f.png)

I would like to see an option "Open HTTPS" which will open `https://vsixgallery.com/extension/e83d71b8-8bfc-4e06-b145-b0388910c016/`.

**Comment by pipboy96** [comment]
@NN--- To clarify, do you want to browse the website over HTTPS despite the certificate warning?

**Comment by NN---** [comment]
The website redirects to https from http afterwards and is a valid certificate.

**Comment by pipboy96** [comment]
@NN--- https://vsixgallery.com has an invalid certificate, while https://www.vsixgallery.com has a valid one.

**Comment by NN---** [comment]
Oh. I didn’t pay attention to www .
Sorry.
