### ISSUE TITLE
Present option to use archive.org to view non-https webpages.

### ISSUE THREAD

**Issue by jmgurney** [EFForg/https-everywhere#19607]
Type: feature request

I realized that as archive.org allows saving http pages, and is https, it can be used as a pseudo gateway to convert http only sites to https.  It would be a nice option that when browsing with encrypt all sites on, that if a site doesn't allow https, that a button can be clicked to send you to archive.org's latest capture of the page, or possibly have it save it if one isn't present.

**Comment by pipboy96** [comment]
Duplicate of #7533.

**Comment by pipboy96** [comment]
Nevertheless, I think this feature may be useful, thus not closing the issue.

**Comment by zoracon** [comment]
I think presenting this as an option on the EASE Interstitial may work.
