### ISSUE TITLE
Breaks congstar.de

### ISSUE THREAD

**Issue by hannob** [EFForg/https-everywhere#1961]
When using HTTPS everywhere the login on congstar.de breaks. While the page is available as https it seems this is not true for all ressources needed to function correctly.

**Comment by SebastianS90** [comment]
Yeah, I can confirm this. See also [a post in the congstar support forum](http://www.congstar-forum.de/kundenbereich/meincongstar-rechnung-und-freundschaftswerbung/52784-meincongstar-login-geht-nicht/index2.html#post346131)
