### ISSUE TITLE
Remove rule for pomf.se

### ISSUE THREAD

**Issue by squarefractal** [EFForg/https-everywhere#1966]
The pomf.se service has closed down; and none of the pages that they do serve are available over HTTPS.

(I'd have sent in a PR, but Github doesn't allow me to perform multiple forks.)

**Comment by reedy** [comment]
Use a branch per set of commits, and you can have multiple active PRs

**Comment by squarefractal** [comment]
[**@reedy**](https://github.com/reedy) commented on [Sunday, June 21, 2015 5:09:09 PM](https://github.com/EFForg/https-everywhere/issues/1966#issuecomment-113886927):
> Use a branch per set of commits, and you can have multiple active PRs
The fork that I maintain is for a particular little-known browser, sending in that PR would really make no sense.

**Comment by jsha** [comment]
@squarefractal: You can have branches within your fork that are relative to the HTTPS Everywhere master branch. For instance, if you have a git remote named `eff` that points at https://github.com/EFForg/https-everywhere.git, you can start a branch like so:

```
git remote update
git checkout -b remove_pomf eff/master
# ... make some edits ...
git commit -a
git push origin remove_pomf
```

Then GitHub should present you the remove_pomf branch as an option for submitting a pull request against the EFF repo.
