### ISSUE TITLE
Bionicle.com 400 Error

### ISSUE THREAD

**Issue by matt81093** [EFForg/https-everywhere#1967]
Bionicle.com (http://www.lego.com/en-us/bionicle/?domainredir=www.bionicle.com) breaks whenever you attempt to use it with HTTPS. Although, if you disable the lego.com portion, it's fine.

----
url: https://wwwsecure.lego.com/en-us/bionicle/?domainredir=www.bionicle.com
Bad Request - Invalid Hostname

HTTP Error 400. The request hostname is invalid.
----

**Comment by donced** [comment]
Do you know whether it affects bionicle only? ninjago.com (also a lego product) seems fine though.

**Comment by matt81093** [comment]
Might be other areas of the website as well. But I haven't looked extensively

**Comment by MDawg957** [comment]
This issue still is not fixed. Checking bionicle.com still routes to https://wwwsecure.lego.com/bionicle?domainredir=bionicle.com which produces a Bad Request page.

http://www.lego.com/en-us/bionicle will partially load, but disabling Lego.com (partial) is the only way it will function correctly.

I'm also seeing Bad Request errors or partially loading issues on the following pages (all obtained by going to https://wwwsecure.lego.com/en-us/products):

https://wwwsecure.lego.com/en-us/duplo?icmp=COUSFRDuplo
https://wwwsecure.lego.com/en-us/friends?icmp=COUSFRFriends
https://wwwsecure.lego.com/en-us/city?icmp=COUSFRCity
https://wwwsecure.lego.com/en-us/marvelsuperheroes?icmp=COUSFRMarvelSuperHeroes
https://wwwsecure.lego.com/en-us/dccomicssuperheroes?icmp=COUSFRDCSuperHeroes
https://wwwsecure.lego.com/en-us/mixels?icmp=COUSFRMixels
https://wwwsecure.lego.com/en-us/elves?icmp=COUSFRElves
https://wwwsecure.lego.com/en-us/jurassicworld?icmp=COUSFRJurassicWorld
https://wwwsecure.lego.com/en-us/ultraagents?icmp=COUSFRUltraAgents
https://wwwsecure.lego.com/en-us/creator?icmp=COUSFRCreator
https://wwwsecure.lego.com/en-us/movie?icmp=COUSFRLEGOMovie
https://wwwsecure.lego.com/en-us/speedchampions?icmp=COUSFRSpeedChampions
http://videogames.lego.com/en-us
https://wwwsecure.lego.com/en-us/herofactory?icmp=COUSFRHeroFactory
https://wwwsecure.lego.com/en-us/architecture?icmp=COUSFRArchitecture
https://wwwsecure.lego.com/en-us/minifigures?icmp=COUSFRMinifigures
https://wwwsecure.lego.com/en-us/technic?icmp=COUSFRTechnic
https://wwwsecure.lego.com/en-us/mindstorms?icmp=COUSFRMindstorms
https://wwwsecure.lego.com/en-us/pirates?icmp=COUSFRPirates
https://wwwsecure.lego.com/en-us/classic?icmp=COUSFRClassic
http://thelordoftherings.lego.com/en-us/default.aspx
http://thehobbit.lego.com/en-us
http://lifestyle.lego.com/en-us/default.aspx
http://turtles.lego.com/en-us
https://wwwsecure.lego.com/en-us/castle?icmp=COUSFRCastle
http://powerfunctions.lego.com/en-us/default.aspx
http://george.lego.com/en-us
https://wwwsecure.lego.com/en-us/juniors?icmp=COUSFRJuniors
https://wwwsecure.lego.com/en-us/dimensions?icmp=COUSFRDimensions
https://wwwsecure.lego.com/en-us/scoobydoo?icmp=COUSFRScoobyDoo
https://wwwsecure.lego.com/en-us/ideasproducts?icmp=COUSFRIdeas

**Comment by donced** [comment]
Probably due to recent website changes, the links at products page were fine last week though.
