### ISSUE TITLE
Amend Check Rules Script for Future Fetch Tests

### ISSUE THREAD

**Issue by zoracon** [EFForg/https-everywhere#19714]
Items that need attention for `test/rules/src/https_everywhere_checker/check_rules.py` script in result from postmortem review on [last Fetch Test](https://github.com/EFForg/https-everywhere/pull/19339)
- [x] Skip Onion Rulesets, Edit: Allowlist should list all Onions properly. Make sure to add to fetch test rubric
- [ ] Check for recently expired certs (60 Days Grace Period)
- [ ] Review https://github.com/EFForg/https-everywhere/issues/19330

**Comment by pipboy96** [comment]
@zoracon Can we re-enable rulesets marked as "failed ruleset test" before testing?

**Comment by zoracon** [comment]
> @zoracon Can we re-enable rulesets marked as "failed ruleset test" before testing?
> 
> If you find rulesets with functional hosts that were previously marked as disabled, you can re-enable with updated rulesets.

Sorry if I misunderstand the question. Ultimately, if you see a disabled rulesets that are functional again, you can take those on. If you mean run a check on previously disabled rulesets as prep for a fetch test, that can be considered. I plan to run these tests in much smaller batches/more frequently.
