### ISSUE TITLE
Add ability to add sites to an IGNORE list

### ISSUE THREAD

**Issue by scottstensland** [EFForg/https-everywhere#1976]
I love this extension - however it breaks site 

    http://jsfiddle.net

for instance

    http://jsfiddle.net/rjw57/A6Pgy/

I have to disable this extension whenever I use jsfiddle.net which is often and its a popular site for front end developers including those using WebGL and three.js

Please add feature to allow us to add sites to some IGNORE list

**Comment by jsha** [comment]
You should be able to do this by visiting jsfiddle.net, then clicking the HTTPS Everywhere icon and clicking the "jsFiddle" entry, which will disable the ruleset for that site.

**Comment by scottstensland** [comment]
OK cool I never noticed that icon ... was looking for Settings from the browser extensions HTTPS Everywhere entry
