### ISSUE TITLE
Travis CI changes

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#19762]
Type: other

This is a heads up that Travis CI is changing their infrastructure and policies for open source repos:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

It seems that they started to limit the concurrent builds for open source projects recently: https://www.traviscistatus.com/
I already noticed the performance penalty for our ruleset tests.

If I got their announcement right our tests will stop working completely by the end of the year:

> We are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

cc @zoracon @Bisaloo @cschanaj @pipboy96

**Comment by Bisaloo** [comment]
I completely moved to GitHub actions for my projects and I'm super happy with it. Faster, less fragile, and you can configure it to get a notification when the build fails.

**Comment by cschanaj** [comment]
I agree that GitHub actions would be a reasonably good alternative to Travis CI if EFF doesn't plan to host their own CI. It is also a chance to rewrite and document the unit tests per #9993 and #17820 .

**Comment by zoracon** [comment]
Thank you for alerting us to this, will discuss with the team internally about what is best as a next step. We have internal pipelines, but I am also familiar with Github Actions.

**Comment by zoracon** [comment]
We have migrated to travis-ci.com! Closing this out.
