### ISSUE TITLE
Add some email services

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#19771]
This list already excludes the services which use HSTS preloading or are redirected by current rulesets.

## Alexa top 1M

- [ ] rediff.com (545)
- [ ] rackspace.com (1735)
- [ ] one.com (2011)
- [ ] privateemail.com (2273)
- [ ] freenet.de (3403)
- [ ] zoho.eu (3504)
- [ ] bluewin.ch (9624)
- [ ] lilo.org (15533)
- [ ] lycos.com (21102)
- [ ] goneo.de (35151)
- [ ] excite.com (58522)
- [ ] aikq.de (122307)
- [ ] tchncs.de (326912)
- [ ] netcourrier.com (500970)
- [ ] thexyz.com (512518)
- [ ] online.de (577679)

## The rest

- [ ] 5x2.de
- [ ] aktivix.org
- [ ] anpa.de
- [ ] beinglibertarian.email
- [ ] biomail.de
- [ ] criptext.com
- [ ] cryptix.de
- [ ] digitalsafe.com
- [ ] elude.in
- [ ] emailn.de
- [ ] eumx.net
- [ ] free.de
- [ ] islandnet.com
- [ ] mailcow.de
- [ ] mailjunky.de
- [ ] mybluelight.com
- [ ] onionmail.info
- [ ] openmailbox.com
- [ ] ownbay.net
- [ ] paranoid.email
- [ ] polarismail.com
- [ ] privaterelay.com
- [ ] redpin.com
- [ ] safe-mail.nl
- [ ] scryptmail.com
- [ ] sdf.org
- [ ] secmail.pro
- [ ] skymail.de
- [ ] unspyable.com

**Comment by suraj10k** [comment]
Hey can I get assigned this issue ?

**Comment by pipboy96** [comment]
@suraj10k Done!
