### ISSUE TITLE
WordPress rule breaks Like button on private sites

### ISSUE THREAD

**Issue by aheckler** [EFForg/https-everywhere#19772]
Type: ruleset/website issue

When the `WordPress` rule is enabled, it causes the post Like button on private WordPress.com sites to break. I tested in Chrome and Vivaldi browsers.

To reproduce:

0. Start with a clean browser. No cookies, cache, etc.
1. Install HTTPS Everywhere. Default settings and rules are fine.
2. Go to [WordPress.com](https://wordpress.com/) and create a site. No need to assign a domain or pay for a plan. A free site in the form of `XXXXX.wordpress.com` will work.
3. Visit this URL: `https://wordpress.com/settings/general/XXXXX.wordpress.com` but obviously substitute in the site name you used instead of `XXXXX`.
4. Click the **Launch Site** button. 
![Markup on 2020-11-07 at 06:08:34](https://user-images.githubusercontent.com/5512652/98439497-41855980-20c0-11eb-98b4-de678de3c60e.png)

5. Click **Skip Purchase** to avoid buying a domain.
6. Click **Continue with your free site** to avoid buying a plan.
7. After a minute, your site will be live.
8. Go back to `https://wordpress.com/settings/general/XXXXX.wordpress.com`.
9. Change your site to be private. 
![Markup on 2020-11-07 at 06:10:28](https://user-images.githubusercontent.com/5512652/98439500-4ba75800-20c0-11eb-9bd8-eacc5956a9d2.png)
10. Now, actually go to the frontend of your site at `XXXXX.wordpress.com` and find a blog post. The URL will be something like so: `https://XXXXX.wordpress.com/2020/11/07/post-title-text-here/`.
11. Notice that, below the post, you'll see the Like button fail to load: 
![Markup on 2020-11-07 at 06:14:41](https://user-images.githubusercontent.com/5512652/98439547-8f01c680-20c0-11eb-9969-b451a99b112f.png)
12. You can get the Like button to load either by A) going back to `https://wordpress.com/settings/general/XXXXX.wordpress.com`, changing the site settings to be public, and then refreshing the blog post page, or B) disabling HTTPS Everywhere, restarting your browser, then going back to the still-private post page.

**Comment by zoracon** [comment]
The WordPress rule [has been amended ](https://github.com/EFForg/https-everywhere/issues/19954)since this was first reported. Could you retest to see if you have the same issue?

**Comment by aheckler** [comment]
I cannot repro now, closing.
