### ISSUE TITLE
Add new ruleset for www.eff.org

### ISSUE THREAD

**Issue by dentistformyeye** [EFForg/https-everywhere#19798]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #

Type: new ruleset

[//]: # (Uncomment and fill the domain below if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)

# Domain: eff.org

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

[//]: # (I have removed information related to a browser bug because I had mistakenly believed HTTPS Everywhere could upgrade mixed content.)

**Comment by pipboy96** [comment]
eff.org is [HSTS preloaded](https://hstspreload.org/?domain=eff.org).
