### ISSUE TITLE
[Docs] Obsolete for firefox 83?

### ISSUE THREAD

**Issue by lonix1** [EFForg/https-everywhere#19797]
Type: feature request

Been using this for years, it's wonderful. But firefox 83 no includes automatic [https upgrade](https://support.mozilla.org/en-US/kb/https-only-prefs).

So is this extension still required for firefox? Does it have any features that firefox does not provide?

(Also might be worth a mention in the docs/faq.)

**Comment by dentistformyeye** [comment]
Firefox doesn't seem to have a way to keep track of which websites have been whitelisted, so it would be hard to remove them.

**Comment by lonix1** [comment]
Good point! I guess this extension still has it's place.

(Realistically though, I'm sure ff will improve in time.)
