### ISSUE TITLE
HTTPS-Everwhere Breaks Typepad's Backend Web Pages

### ISSUE THREAD

**Issue by outtacontext** [EFForg/https-everywhere#1979]
When I have this plugin enabled and I am in the backend of TypePad creating a new blog post I encounter problems saving updates. I enter something new and save it, yet it reverts to the earlier saved version. This happens within the body of the post, with keywords, with Technorati tags, and in the Excerpt field. In addition, when I try to preview, the first time I try I get a message on the popup window that states I must hit the Preview button to preview (which, of course I already have). The second time I hit Preview it works. 

I have isolated this problem to your plugin. And, for the time being I have disabled it for the Typepad site.

**Comment by jeremyn** [comment]
Thanks for this write-up. Is this still an active problem for you?

**Comment by J0WI** [comment]
Closing due the lack of response and details.
