### ISSUE TITLE
Amazon Web Services breaking PremiumBeat.com samples

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#1980]
http://www.premiumbeat.com/sfx/view/sweepers

When attempting to play a sample before purchase, nothing plays, but the moment Amazon Web Services rule is disabled the audio plays without any problems.

**Comment by finaljason** [comment]
Thanks for your report. The fix above should solve your problem. Can you also test by adding the AmazonAWS.xml from the referenced commit into your UserRules folder (as described on https://www.eff.org/de/node/58830#testing)?

**Comment by MDawg957** [comment]
I tested out the replacement ruleset and it still doesn't want to work.  Amazon Web Services doesn't show as something to disable when you first visit the page and play something, but if you go to another tab in Firefox and come back, it shows up.  Disabling it at that point allows the sample to play.

**Comment by finaljason** [comment]
Hmm, this is strange. The fix i did was meant to exclude the sound files for the player from rewrite. The flash application which plays them doesn't seem to support HTTPS.
Before the fix I could confirm your issue, but now, with the rule, it works perfectly fine for me.

That the AWS rule didn't show up should mean it wasn't applicated. Have you tried using a clean Firefox profile? Alternatively, you can try to provide the URL where the content is loaded from for you (could be region specific). Just open the Firefox Network Analyzer (under Development Tools) and try to play a one of the previews with the AWS rule disabled. When you click the Play button, a connection to amazonaws.com will be shown in the analyzer window. Right-click onto it and provide me the link please.

**Comment by MDawg957** [comment]
http://s3.amazonaws.com/pb_sfx_previews/0333_production_element_hit_sweeper/0333_production_element_hit_sweeper

http://s3.amazonaws.com/pb_sfx_previews/ seems to be the common address for any previews across the site from a few spot checks.

**Comment by finaljason** [comment]
Exactly. Those addresses are excluded by the fix. The new rule:
``<exclusion pattern="^http://s3\.amazonaws\.com/pb_(sfx_)?previews/" />``
catches both http://s3.amazonaws.com/pb_sfx_previews/ and http://s3.amazonaws.com/pb_previews/ (which is for previews from the music section). I have no idea why this doesn't work out for you. Isn't it working with a completely clean firefox profile and just https-everywhere 5.0.5 + fix in the User rule directory?

**Comment by MDawg957** [comment]
Apologies, I messed up when I downlaoded the XML fix originally it seems. I re-downloaded on another computer I was worknig on as a quickie check and it worked, so I did it again on the original and swapped the XML I had previously used and everything worked.  

I'm not so familiar with Github yet, so I think that was part of the problem.  Thank you for taking the time to resolve this issue.
