### ISSUE TITLE
Broken download of files from HTTP-Sites

### ISSUE THREAD

**Issue by JoAllg** [EFForg/https-everywhere#19828]
Type: code issue

**Problem Description:**
When trying to download File from a http website that was added to the exceptions, via right clicking on the link to the file and selecting "Save link as" an Error occurs:
![grafik](https://user-images.githubusercontent.com/57436524/100914989-141ba800-34d4-11eb-8ad5-8ebaf17981ff.png)
(it says that the file coudn't be downloaded because of an unknown error)

Opening the file in the Browser with left click and then downloading it works fine. 

**Steps to reproduce:**
Enable Encrypt All Sites Eligible in HTTPS Everywhere
Open http://ac.informatik.uni-freiburg.de/teaching/ws20_21/algo2021.php **in Firefox**
Add this Site to the Exceptions, when the HTTPS Everywhere warning occurs ("open insecure page")
Scroll down to the Exercise Sheets and try to download one of the pdfs by right clicking -> "Save link as"
Wait for the error message

**Or**

Enable Encrypt All Sites Eligible in HTTPS Everywhere
Open http://ac.informatik.uni-freiburg.de/teaching/ws20_21/algo2021/recordings/introduction.mp4
Add this Site to the Exceptions, when the HTTPS Everywhere warning occurs
With the mouse on top of the video click with the right mouse button -> "Save video as"
Wait for the error message

Edit: There is no problem/error in chromium btw.

**Comment by zoracon** [comment]
This error dialogue is not generated from HTTPS Everywhere, especially if you deactivated the extension before this error box popped up.

Can you confirm if the icon is grey before you try to save? That would confirm if the extension is deactivated properly before you save.

**Comment by JoAllg** [comment]
Hey, i forgot to specify that the error does not occur anymore if I deactivate the addon completely

When staying on the website, then the icon is grey (however not HTTPS Everywhere is only deactivated for this website) and the problem is there.
When deactivating the plugin then there is no error and saving the file works well.

**Comment by zoracon** [comment]
EASE mode or Encrypt All Sites Eligible is expected to interrupt unencrypted or HTTP only connections at times. If HTTPS Everywhere blocked this, normally this page would pop up

![image](https://user-images.githubusercontent.com/4276080/101852403-6aab6680-3b12-11eb-8ca6-ac90bd48b2ef.png)

Did you see this page?

**Comment by JoAllg** [comment]
As I have added the website to the exceptions, I do not see the message when opening
http://ac.informatik.uni-freiburg.de/teaching/ws20_21/algo2021.php
or
http://ac.informatik.uni-freiburg.de/teaching/ws20_21/algo2021/algo-exams/ExamFall20.pdf
(same website / domain, needs only to be added once to the exceptions).

However when trying to download the file via context menu from the a page that is added to the exceptions, then the error occurs. As downloading a linked file via context menu does not open it in a new tab, I can't check what is happening in the background. However obviously HTTPS Everywhere seems to block it. Even when it is not blocked when opening the file in a new tab.

For clarification, do you not experience the problem i described?
