### ISSUE TITLE
EASE mode does not work on Firefox (Fenix)

### ISSUE THREAD

**Issue by cschanaj** [EFForg/https-everywhere#19830]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

## Step to reproduce:

1. Enable EASE mode
2. Visit http://http.badssl.com/

## Expect:

EASE mode warning page show up. 

## Actual:

A broken EASE mode warning page show up, styles and buttons are not working. When connected via USB remote debugging, it seems that the extension resources are redirect to the wrong domain:

Console output:

Loading failed for the <script> with source “http://http.badssl.com/translation.js”. http.badssl.com:28:1
Loading failed for the <script> with source “http://http.badssl.com/util.js”. http.badssl.com:29:1
Loading failed for the <script> with source “http://http.badssl.com/ux.js”. http.badssl.com:30:1

Note that this bug also affect the tor browser on Android. cc @zoracon 

## Platforms

- Firefox 83.1.0 on Android 8.0.0 with HTTPS Everywhere 2020.11.17
- Tor Browser 10.0.4 (82.1.1-Release)

**Comment by zoracon** [comment]
Going to enlist the help of Mozilla Firefox team and file a bug report since I personally can't find out the origin of this error. Hopefully they can guide in the right direction as to why this is occurring.

**Comment by zoracon** [comment]
Issue filed: https://github.com/mozilla-mobile/fenix/issues/17321

**Comment by cschanaj** [comment]
Discussions moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1685403

**Comment by zoracon** [comment]
The Fenix team pushed a patch into Nightly, will monitor for when this change lands in stable. I see the fix in Nightly Fenix personally.

**Comment by cschanaj** [comment]
The EASE mode work for me on Firefox for Android 86.1.1 . Please feel free to close this issue. Thanks.
