### ISSUE TITLE
vnav.io should have an exception

### ISSUE THREAD

**Issue by CrazyPython** [EFForg/https-everywhere#19879]
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #

Type: ruleset/website issue

[//]: # (Uncomment and fill the domain bellow if you belive that yet another)
[//]: # (domain should be added to the existing ruleset.)

[//]: # Domain: vnav.io

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Please add an exception for vnav.io.

**Comment by pipboy96** [comment]
@CrazyPython Thanks for asking. Currently, vnav.io is not redirected by HTTPS Everywhere. Do you have the EASE mode on (is your HTTPS Everywhere icon red)?
