### ISSUE TITLE
question: Firefox 83+ HTTPS-Only Mode vs https-everywhere ?

### ISSUE THREAD

**Issue by Owyn** [EFForg/https-everywhere#19905]
https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/ 

found out Firefox 83 introduces HTTPS-Only Mode on Mozilla Security Blog

It seems to do the very same thing as the extension now, no? 

Can you clarify whether it's still needed to use the extension with the introduction of this FF 83 new feature and what for?

**Comment by zoracon** [comment]
Please refer to this answer in our FAQ:
https://kittens.eff.org/https-everywhere/faq#https-only-mode

I hope this clarifies your questions!

**Comment by Owyn** [comment]
I suppose it's not needed anymore fore FireFox then
