### ISSUE TITLE
Update https-everywhere-checker to disable single target hosts rather than entire rules

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1998]
One common case in https-everywhere-checker is a single hostname that has been disabled or no longer supports HTTPS. Right now the checker will disable the whole ruleset. For large domains with many subdomains, this is more disruptive than is warranted for a single subdomain. It's also correspondingly more likely for such domains.

The checker should be able to automatically comment out single target hosts in rulesets if a fetch test for that hostname fails, and the ruleset is simple (no exclusions, only an http->https rewrite).

**Comment by reedy** [comment]
:+1:

**Comment by J0WI** [comment]
I think this would reduce ruleset maintenance a lot. @Hainish could you have a look at the open PR?

**Comment by Hainish** [comment]
@J0WI I'll be picking up that PR where the contributor left off.

**Comment by Bisaloo** [comment]
This is fixed by #17000
