### ISSUE TITLE
Add web.mit.edu

### ISSUE THREAD

**Issue by bllsrj** [EFForg/https-everywhere#19992]
Type: ruleset/website issue

Domain: http://web.mit.edu/2.111/www/2010/ps2Solutions.pdf

It doesn't redirect to the HTTPS, please add it to the ruleset.

**Comment by Nihal247** [comment]
Hey @bllsrj, I checked for it in Brave & Microsoft Edge, and it redirects me to the HTTPS version of the site. It seems that it redirects in Chromium browsers. Which browser are you using?
