### ISSUE TITLE
Document that only a small chunk of the Smarter Encryption list is used

### ISSUE THREAD

**Issue by klausenbusk** [EFForg/https-everywhere#20052]
Type: other

From the [*HTTPS Everywhere Now Uses DuckDuckGo’s Smarter Encryption*](https://www.eff.org/deeplinks/2021/04/https-everywhere-now-uses-duckduckgos-smarter-encryption) announcement, I got the impression that the whole list is used, but [apparently](https://github.com/EFForg/generate-smarter-encryption-bloom-filter/blob/2490818ba1f809a14286cb28892081e032d09c86/src/main.rs#L124-L131) only the domains in both the Smarter Encryption list and Majestic Million list is used. That should be documented to avoid confusion.

**Comment by zoracon** [comment]
This is written out here: https://github.com/EFForg/https-everywhere/blob/master/docs/adrs/bloom-filter-rule-signing.md#decision-outcome

I can link this in the description in the repository to make that more clear. The main reason was getting the benefit of the list without suffering from intense memory issues.

**Comment by klausenbusk** [comment]
I'm not sure how I missed that (apparently just skimming the doc wasn't enough), but IMO it should be documented more publicly and not just hidden in a design doc.

Ex: https://www.eff.org/https-everywhere nor https://www.eff.org/deeplinks/2021/04/https-everywhere-now-uses-duckduckgos-smarter-encryption mentions it.

**Comment by zoracon** [comment]
I can add it to our FAQ page and main page on the EFF Stite. This wasn't meant to be intentionally hidden from the public in terms of usage.

**Comment by klausenbusk** [comment]
Sounds good to me :)

**Comment by zoracon** [comment]
Pages have been updated with technical details of how we use Smarter Encryption linking the original doc above. Thank you!
