### ISSUE TITLE
canon.ca

### ISSUE THREAD

**Issue by joshuaauger** [EFForg/https-everywhere#2006]
canon.ca support and drivers page uses an iframe with the custhelp.com domain. When using HTTPS Everywhere, this page will not load and will not give an error.

http://www.canon.ca/inetCA/en/inFrame?m=showInFrame&url=http://canoncanada.custhelp.com/ the important part being http://canoncanada.custhelp.com/

**Comment by semenko** [comment]
Only half closed

**Comment by jeremyn** [comment]
@joshuaauger If I go to http://www.canon.ca/inetCA/en/inFrame?m=showInFrame&url=http://canoncanada.custhelp.com/ and click the "Drivers, Software & Manuals" image, I'm brought to a page where I can enter a model name. This looks working to me. Is this still an active problem for you?

**Comment by joshuaauger** [comment]
Seems fine now.

**Comment by jeremyn** [comment]
@joshuaauger Thanks for the quick reply. Closing issue.
