### ISSUE TITLE
Android: remove HTTPSE icon from address bar

### ISSUE THREAD

**Issue by chr00t** [EFForg/https-everywhere#2007]
On android, I can see HTTPS Everywhere icon on the top left corner of the address bar.
Please remove it. I don't want to see it because my screen is small.

**Comment by reedy** [comment]
FF for android presumably?

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/6617 will fix this issue

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/https-everywhere/pull/6617
