### ISSUE TITLE
Add an option to remove EASE dialogs?

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#20084]
Type: feature request

Could you add an option to remove the proceed anyway and disable dialogs? I like having everything encrypted but if it can't be I'm not going to leave the website.

**Comment by Nihal247** [comment]
I think @theo-3, this is an important security feature (resists downgrade attack) and must not be removed, as this is one of the most important aspects of the extension to warn you against visiting unencrypted sites. If you would like to visit the site, then just go with 'Disable on this side' button.

I don't recommend removing '**Proceed anyway (unsafe**)' & '**Disable on this side**' dialogs.

**Comment by theo-3** [comment]
I meant an option to remove them that isn't enabled by default, not removing them for all users

**Comment by Nihal247** [comment]
That's fine!
