### ISSUE TITLE
Shows an HTTPS Website a Non-HTTPS Website.

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#20100]
I use the HTTPS Everywhere extension with Encrypt All Sites Eligible is ON. 
 
![Screenshot (1050)_LI](https://user-images.githubusercontent.com/80682093/124702950-00736c80-df0f-11eb-81d0-5a0230aef440.jpg)

Whenever I navigate to https://www.cricbuzz.com/, it shows me the warning that the page you are visiting is a non-HTTPS page,

![Screenshot (1053)](https://user-images.githubusercontent.com/80682093/124703316-b2129d80-df0f-11eb-95c8-3a56ddef240a.png)

but https://www.cricbuzz.com/ has a valid HTTPS Certificate, and is using HTTPS Protocol. Then why I have to disable the extension every time I visit the page.

Versions:
Firefox - 90.0.2
HTTPS Everywhere - 2021.4.15
OS - Windows 10 Home Single Language (10.0.19043.1151)

Thank you in advance.

**Comment by aerocyber** [comment]
I have a similar issue in brave browser which uses list from https-everywhere:

## Steps to Reproduce


   1. When visiting [http://www.glyphrstudio.com/](http://www.glyphrstudio.com/) and some other sites, I found this issue.

## Actual result:

![Not Secure badge when visiting http:// site.](https://user-images.githubusercontent.com/86760749/126887138-7840e0e6-9da0-4773-a06c-9a3745b6353a.png)


## Expected result:
![Padlock sign indicating https://](https://user-images.githubusercontent.com/86760749/126887147-e9ae4699-d025-4446-b7ca-7a4d61813a50.png)


## Reproduces how often: 
No steps to reproduce; occurs on random sites.

## Desktop Brave version:

```
Brave: 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)
OS: Linux
```

## Android Device details:
   - Install type : x86
   - Device type : Phone
   - Android version: 5.1; 11

## Version/Channel Information:


- Can you reproduce this issue with the current release? Yes

## Other Additional Information:

- Is the issue reproducible on the latest version of Chrome? Yes

**Comment by Nihal247** [comment]
How are you able to get extensions for Brave in Android? As per my knowledge, extensions are not available for the Android version.

**Comment by TNTBOMBOM** [comment]
im access both sites without issues to https (https://www.cricbuzz.com/ , https://www.glyphrstudio.com/)

Firefox-esr, Debian GNU/Linux, Extension version:  2021.4.15 , Last Updated: July 15, 2021

**Comment by Nihal247** [comment]
Yeah, thanks @TNTBOMBOM, I am now able to access the website without any issues.

Definitely, the latest version has fixed the problem.

**Comment by Nihal247** [comment]
Yeah, thanks @TNTBOMBOM, I am now able to access the website without any issues.

Definitely, the latest version has fixed the issue.

**Comment by Nihal247** [comment]
I am reopening this issue because I faced the problem with https://www.airindia.in/ on Brave Browser

**Steps to Reproduce**

Just type airindia.in on Brave, with Encrypt All Sides Eligible is ON

This issue is also faced when visiting https://www.whatsapp.com and https://www.dailypioneer.com/ the first time on Brave.

I didn't get this issue on Firefox.

I think this issue is on Chromium web browsers.

**Comment by Nihal247** [comment]
These issue are not experienced with only the above mentioned sites, but with many sites I have experienced while browsing.

Note: These issues are only faced on the Chromium browsers, not Firefox.
