### ISSUE TITLE
Add cbseacademic.nic.in

### ISSUE THREAD

**Issue by prorounak2005** [EFForg/https-everywhere#20117]
cbseacademic.nic.in is a Indian government website.

**Comment by zoracon** [comment]
We have stopped accepting new rulesets as of May 31st, 2021. Please see: #20099.

We will still accept requests on rulesets already in our list that are causing significant breakage for users through the summer. However in autumn, we will begin the plan to ultimately move our crowdsourced rulesets out of the extension.
