### ISSUE TITLE
Add new ruleset for muzines.co.uk

### ISSUE THREAD

**Issue by tjhietala** [EFForg/https-everywhere#20122]
Type: new ruleset

Domain: muzines.co.uk

**Comment by zoracon** [comment]
We have stopped accepting new rulesets as of May 31st, 2021. Please see: #20099.

We will still accept requests on rulesets already in our list that are causing significant breakage for users through the summer. However in autumn, we will begin the plan to ultimately move our crowdsourced rulesets out of the extension.
