### ISSUE TITLE
Add https://www.math.u-szeged.hu

### ISSUE THREAD

**Issue by benedek20** [EFForg/https-everywhere#20121]
Type: new ruleset

please add http://www.math.u-szeged.hu  ---> https://www.math.u-szeged.hu

**Comment by zoracon** [comment]
We have stopped accepting new rulesets as of May 31st, 2021. Please see: #20099.

We will still accept requests on rulesets already in our list that are causing significant breakage for users through the summer. However in autumn, we will begin the plan to ultimately move our crowdsourced rulesets out of the extension.
