### ISSUE TITLE
Where is the Chromium version?

### ISSUE THREAD

**Issue by Ryu945** [EFForg/https-everywhere#20128]
Where is the Chromium version of HTTPS-everywhere?

**Comment by Nihal247** [comment]
Click on the Chromium-based browser you're using.
[Google Chrome](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)
[Microsoft Edge](https://microsoftedge.microsoft.com/addons/detail/https-everywhere/fchjpkplmbeeeaaogdbhjbgbknjobohb)
[Opera](https://addons.opera.com/en/extensions/details/https-everywhere/)
[Brave](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)
[Vivaldi](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)

**Comment by Ryu945** [comment]
> Click on the Chromium-based browser you're using.
> [Brave](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)
> [Google Chrome](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)
> [Microsoft Edge](https://microsoftedge.microsoft.com/addons/detail/https-everywhere/fchjpkplmbeeeaaogdbhjbgbknjobohb)
> [Opera](https://addons.opera.com/en/extensions/details/https-everywhere/)
> [Vivaldi](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)

I asked on the Github because I can't use the Chrome Store to get addons.   I am using degoogled Chromium.   I have to manually add each addon through developer mode.

**Comment by Nihal247** [comment]
@Ryu945, the Opera one has the same .crx extension, you can just install that, and I think it'll work as same.

Hope that helps!

**Comment by Ryu945** [comment]
The Opera version appears to be working.   Thankyou.
