### ISSUE TITLE
Add a rule to ignore .i2p sites

### ISSUE THREAD

**Issue by AstralStorm** [EFForg/https-everywhere#20170]
It seems there is an interaction between HTTPS Everywhere and I2P when used to access internal eepsites, with .i2p domain.
This issue only happens in EASE mode.

Normally, eepsites do not use TLS because they are already on a network that's encrypted and authenticated in another, somewhat more manual, way.
It would be nice to have a rule to skip .i2p domain altogether, even in EASE mode, and especially for .b32.i2p and .b64.i2p addresses.

**Comment by Vftdan** [comment]
It would be nice to be able to configure such tlds, e. g. add `*.i2p` to the list of disabled sites. (It currently fails with `This host could not be added because it was not formatted correctly. Please check it and try again.`)

**Comment by mmgen** [comment]
Or you can just hack the XPI file: unzip, edit `background-scripts/background.js` with the changes in the patch, delete the `META-INF` directory, re-zip and install.

Note: installation of non-signed XPIs requires that `xpinstall.signatures.required` be set to `false` in `about:config`
