### ISSUE TITLE
404 requests found related to this project

### ISSUE THREAD

**Issue by renebaudisch** [EFForg/https-everywhere#20188]
Type: other

We have entries like this in our logs:
error=404&url=/artikel/https/t.svtrd.com/collect/d875a44f-b683-4597-8efd-caa34204ac85/4296433e-d4b2-400a-b67a-6fbf750ed900?ct=engagement&name=bannerView&cup=adID:506525067&cup=advertiserID:4652781&cup=campaignID:26527380&cup=creativeID:166274197&cup=placementID:313753878&cup=implicit:true&cup=iab:true&cup=r42Consent:true&cup=consentString:%7B%221%22:true,%222%22:true,%223%22:true,%224%22:true,%225%22:true,%226%22:true,%227%22:true,%228%22:true,%229%22:true,%2210%22:true%7D

After some research I found this project behind this domain and I was wondering if anyone can see which ad-based user is using your tool having this kind of parameters or at least

do something to avoid settings that will break urls like this, e.g. sanitize the settings.

**Comment by zoracon** [comment]
Hello, is this log associated with this domain: t.svtrd.com?

**Comment by renebaudisch** [comment]
We found it in the log of one of our domains where ads are on
