### ISSUE TITLE
PGP key used to sign 2022.5.24 changed from previous

### ISSUE THREAD

**Issue by pospeselr** [EFForg/https-everywhere#20206]
```
gpg: Signature made Tue 24 May 2022 11:54:23 PM UTC
gpg:                using RSA key AF1E082A343D8331225BB1E7EF9F92E86D8CF643
gpg: Can't check signature: No public key
Author: zoracon <alexis@eff.org>
Date:   Tue May 24 16:54:07 2022 -0700
```

I've not been able to find this key in any of the obvious places.

**Comment by zoracon** [comment]
Apologies for the confusion. This signing subkey [S] was added to my main key to delegate signing. I pushed to a MIT server as an update. 

https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0D16CFA2BA1F7420

**Comment by zoracon** [comment]
Marking as resolved for now
