### ISSUE TITLE
Contribute buttons don't work

### ISSUE THREAD

**Issue by Gersonzao** [EFForg/https-everywhere#20214]
The buttons to contribute in both Mozilla AMO page and in the add-on management page take me to an inaccessible page

**Comment by zoracon** [comment]
Hello, could you list the linked to the page you tried to access? Both https://supporters.eff.org/donate/support-https-everywhere and https://paypal.me/SupportEFF appear to go through.

**Comment by Gersonzao** [comment]
The links are working now. Maybe they were changed
