### ISSUE TITLE
Version in Mozilla AMO outdated?

### ISSUE THREAD

**Issue by Jon-guy30** [EFForg/https-everywhere#20212]
Type: other

Hi! I'm just wondering if the Firefox version on the Mozilla amo website is outdated? EFF.org shows a new version 2022.5.11. Should I get that one? The Firefox version hasn't been updated in a while. The version in Firefox is 2021.7.13.

**Comment by zoracon** [comment]
Hello! We had some release issues but you can use the updated extension here:
https://www.eff.org/files/https-everywhere-2022.5.11-eff.xpi

Sorry for the confusion.

**Comment by Croydon** [comment]
Could the version on AMO please be updated?

Edit: I understand that you are sunsetting this addon, but many people won't uninstall it anytime soon. I think it is better if those people get at least an update to the last version.
