### ISSUE TITLE
This extension breaks google logins on the Brave browser

### ISSUE THREAD

**Issue by EnderShadow** [EFForg/https-everywhere#20220]
Type: ruleset/website issue

Domain: *.google.com

When this extension is enabled, all attempts to sign into google through the Brave browser cause an automatic sign-out and a redirect to this page [Unable to sign in to your Google Account: Delete cookies](https://support.google.com/chrome/thread/4399961/cannot-sign-in-unable-to-sign-in-to-your-google-account-delete-cookies-after-deleting-cookies?hl=en) even after following the steps on the page. This occurs for [gmail](https://mail.google.com), managing your google account, and possibly other google sites. Websites like youtube and google search do appear to be logged in, but it's a weird pseudo-logged-in state since attempting to go to the above mentioned google subdomains causes the above mentioned error. After disabling this extension I am able to sign in with no issues.

**Comment by Yvha** [comment]
Having the same issue as mentioned above. The extension breaks the login for *.google.com domains.

**Comment by Yvha** [comment]
Update

Issue appears to have been resolved.

**Comment by jonpsp** [comment]
I have been unable to login to gmail for several days. I disabled HTTPS Everywhere by changing the "HTTPS Everywhere is ON" to off, then was able to login to gmail. Logging off from Gmail and turning HTTPS Everywhere on once again broke Gmail login (`Unable to sign in to your Google Account: Delete cookies`).
I am using HTTPS Everywhere 2022.5.4 on Brave 1.44.105 on Windows 10.
