### ISSUE TITLE
Chrome default.rulesets contains test URLs

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2040]
Right now we assemble the rulesets for a release one of two ways. For Chrome, we use `utils/merge-rulesets.py`, which concatenates rulesets and removes some comments and whitespace with regexes. For Firefox, we use `utils/make-sqlite.py`, which parses XML, removes comments, whitespace, and certain elements and attributes, adds the `f=` attribute, and serializes it again.

When I added the `<test />` tag, I added stripping for it in `utils/make-sqlite.py` but forgot to add it to `utils/merge-rulesets.py`, which means default.rulesets for Chrome is a little bigger than it needs to be.

In the long run we should consolidate Chrome and Firefox on the same ruleset storage, sqlite. As a short term fix, we should remove `utils/merge-rulesets.*` and have `make-sqlite.py` output both a database and a concatenation of XML, renaming it in the process.

**Comment by TheNavigat** [comment]
I'm wondering which block of code strips the tag in ```utils/make-sqlite.py```

**Comment by gloomy-ghost** [comment]
The ruleset size is decreased from 8.8M to 7.8M after remove `<test />`

**Comment by gloomy-ghost** [comment]
Closed by #7651
