### ISSUE TITLE
Remove Agar.io

### ISSUE THREAD

**Issue by Matheus28** [EFForg/https-everywhere#2056]
Hello.

I'm the developer of Agar.io. Could you remove it from the list of sites that get redirected to the https version? Right now, the https version has to use wss, which means that we have to pass through a reverse proxy to kill it and turn into unsecure websockets before handing it to the game servers, which results in an unnecessary increase in latency. We currently only support https because Facebook demands it for their Canvas app stuff, but we prefer to send users to the http version.

Thank you.

(See here for domain ownership proof: http://agar.io/2056.txt)

**Comment by J0WI** [comment]
I think we prefer ```default_off="webmaster request"```.
Note that http is deprecated [1] and https has many benefits over http. So it's recommend to migrate to https sooner or later.

[1] https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/

**Comment by Matheus28** [comment]
I am aware that http is deprecated, we plan to move fully to https soon, but for now, users that are using https have a slightly worse latency. The main issue is that we can only use secure websockets on https pages, which require us to actually write some code to support that on the game server, which we're in the process of doing, but will probably take a little while.

Thank you for your understanding

**Comment by jsha** [comment]
Fixed by #2069. Thanks!
