### ISSUE TITLE
5.0.5 Breaks redirect on DSLReports.ca

### ISSUE THREAD

**Issue by PHPDev-CA** [EFForg/https-everywhere#2058]
http://www.dslreports.ca is redirected to http://www.dslreports.com and this has worked fine with HTTPS Everywhere until 5.0.5, re-writing it properly as https://www.dslreports.com.  However, with this latest update it's now re-writing it as https://secure.dslreports.com which is not a valid subdomain for their certificate.  There are no rules that I could find for that site so I'm not sure what's causing it.

**Comment by PHPDev-CA** [comment]
This appears to be more than a simple ruleset bug.  It is overriding other rulesets like

<ruleset name="Trueachievements.com">
  <target host="trueachievements.com" />
  <target host="www.trueachievements.com" />

  <rule from="^http://(?:www\.)?trueachievements\.com/" to="https://www.trueachievements.com/" />
</ruleset>

Pre-5.0.5 that ruleset exempted that domain from HTTPS Everywhere, post-5.0.5 it seems to ignore/override it.

**Comment by donced** [comment]
The dslreports [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/BroadbandReports.xml) is pretty old (last updated last year https://github.com/EFForg/https-everywhere/commit/69922ad087f73698b2a67c32f285e661c533d6f5). The ruleset has always redirect (www.)dslreports.com to secure.dslreports.com. AFAIK, there is [no](https://www.eff.org/https-everywhere/atlas/letters/d.html) ruleset for dslreport.ca

**Comment by PHPDev-CA** [comment]
The old ruleset did not affect using DSLR at all if accessed directly via the http://www.dslreports.com address - it would change to https and everything was fine.  It's something that has changed with regards to redirect/forwarding that is causing the problem (what dslreports.ca does).  Another example is that if I access http://www.trueachievements.com I have a ruleset that exempts that domain to keep it unsecured, it works perfectly if I type in the address manually.  If I click a link in my email, which uses redirects to track link clicks, all of the sudden my exemption ruleset is ignored and I'm dumped onto https://www.truachievements.com which causes all sorts of problems.

**Comment by donced** [comment]
I tried [v5.0.2](https://www.eff.org/files/https-everywhere-5.0.2.xpi) and [v5.0.4](https://www.eff.org/files/https-everywhere-5.0.4.xpi), same behaviour as v5.0.5.
I did some test using v5.0.5 with current ruleset (not the patch),
http://www.dslreports.ca/ --> http://www.dslreports.com -> https://secure.dslreports.com
http://dslreports.com -> https://secure.dslreports.com
http://www.dslreports.com -> https://secure.dslreports.com
https://dslreports.com --> http://www.dslreports.com -> https://secure.dslreports.com
https://www.dslreports.com , no redirect
(-> is addon redirect, --> is server redirect)
