### ISSUE TITLE
multimedia.pol.dk

### ISSUE THREAD

**Issue by hansharhoff** [EFForg/https-everywhere#2072]
Hi, I just wanted to let you know that HTTPS Everywhere breaks image loading on pol.dk (major danish newspaper)
The domain multimedia.pol.dk does not support https.

**Comment by fuglede** [comment]
[The domain was disabled](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Pol.dk.xml) around a week ago. Moreover, the pol.dk devs are aware and one of them talked about fixing their site.

**Comment by J0WI** [comment]
#closeme?
