### ISSUE TITLE
Gannett-cdn.com breaks video playback

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2079]
Video link:
http://www.foxsports.com/college-football/outkick-the-coverage/florida-state-seminoles-fsu-qb-deandre-johnson-battery-video-070615

**Comment by jeremyn** [comment]
The `foxsports.com` URL redirects to [here](http://www.outkickthecoverage.com/florida-state-seminoles-fsu-qb-deandre-johnson-battery-video-070615), and the video loads for me there.

@tancrackers Is this problem still happening for you?

**Comment by tancrackers** [comment]
It wasn't redirecting before. I guess this is a worksforme?

**Comment by jeremyn** [comment]
Thanks, closing issue.
