### ISSUE TITLE
developers.500px.com doesn't have a valid certificate

### ISSUE THREAD

**Issue by orrc** [EFForg/https-everywhere#2086]
Currently, the 500px.com rule also applies to the dev blog at `developers.500px.com`, but they're hosting on GitHub pages, so the certificate is not valid (`www.github.com`).

**Comment by donced** [comment]
The ruleset has been updated, but not yet released. 86cc6d5dccc43ec735916c7bae7f39b7348fc65e

**Comment by donced** [comment]
The ruleset has been updated, but not yet release. 86cc6d5dccc43ec735916c7bae7f39b7348fc65e
