### ISSUE TITLE
Add a FAQ item around deleting vs default_off'ing

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2088]
This is a common issue that comes up in reviews, it would be useful to have a FAQ entry.

**Comment by 2d1** [comment]
suggest that there be a grace period for rulesets covering domains which no longer work at all over tls. Say, 2-6 months. Once that period has expired and there's no indication that the website will reenable tls, suggest that ruleset be removed. At that point it's unlikely to be of any use in the future.

**Comment by jsha** [comment]
That sounds like a good rule of thumb, thanks!

**Comment by J0WI** [comment]
I think it's also safe to delete rules when the host doesn't exist anymore or the domain is for sale.

**Comment by zoracon** [comment]
Likely moving this to the Contributor Docs instead of FAQ, which I feel is more end user oriented
