### ISSUE TITLE
Issues with MeinFernbus.de

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2090]
There is already a rule for [MeinFernbus.de](https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/MeinFernbus.xml) (where I strangely can't show the contributor), but the rules on http://meinfernbus.de must be more specific.
Actually on many pages it just reloads (301 redirect) the HTTP version. Only the front page and the shop use HTTPS.
And because of this the rule often is automatically disabled - although it could be used in some specific URLs.
BTW I've asked MeinFernbus about this confusing use of HTTPS: https://twitter.com/rugkme/status/618871828061270016 (German)

**Comment by donced** [comment]
Following are the non-functional pages I found so far:
```
	Nonfunctional directory:
		- en (except for /en/rebooking)
		- kundenservice
		- ueber-uns
		- presse
		- staedte
	Nonfunctional page:
		- *.html
		- seitenuebersicht
```
Let me know if I miss anything.

**Comment by rugk** [comment]
No I could not find any more.

Only as a small note (sorry for hijacking this issue) the partner company https://www.flixbus.de/ could also be included in a ruleset. (+ https://shop.flixbus.de) There I saw no nonfunctional URLs.

**Comment by donced** [comment]
I can create separate ruleset for flixbus.de. I try to avoid putting different domain in a ruleset for maintainability.
