### ISSUE TITLE
http://www.antenna.gr/webtv/live broken

### ISSUE THREAD

**Issue by fateswarm** [EFForg/https-everywhere#2098]
http://www.antenna.gr/webtv/live does not work with it on. (It normally plays a TV channel live).

(it's a legal site, the official site of the channel)

**Comment by stullig** [comment]
Bit hard to reproduce cause region locked to greece

**Comment by fateswarm** [comment]
Well, ask a few others from that region to confirm

**Comment by reedy** [comment]
There's at minimum, loads of mixed content...

**Comment by J0WI** [comment]
Can you check if #2175 solves the problem?
You may report the problem on https://github.com/kargig/https-everywhere-greek-rules as offered in the code comment.

**Comment by semenko** [comment]
Closing, per rule update above.
