### ISSUE TITLE
conviva broken

### ISSUE THREAD

**Issue by carlzoo** [EFForg/https-everywhere#2125]
Sites using conviva rule causes videos to not load.
Example: http://sports.cntv.cn/2015/07/11/VIDE1436615767485725.shtml

It works fine with the rule disabled.

**Comment by youdly** [comment]
The video seems to be accessible from China only.
https://veuwer.com/i/2ucr.png

**Comment by pipboy96** [comment]
The page in question does not trigger that rule anymore, and can't be tested outside mainland China. Closing I guess.
