### ISSUE TITLE
www.amazon.co.uk not redirecting to HTTPS in version 5.0.5

### ISSUE THREAD

**Issue by l0b0** [EFForg/https-everywhere#2133]
Not sure what's happening, but I get a 301 "Moved permanently" redirect to HTTP when trying to access a product page over HTTPS. Has Amazon really turned off TLS for everything except their front page and shopping basket?

**Comment by 2d1** [comment]
> Has Amazon really turned off TLS for everything except their front page and shopping basket?

Yes, since [April 2014] (https://github.com/EFForg/https-everywhere/commit/cd03aa0ae618c4e06b49a0ef80de3f0fdeb53e20).

Product pages did work for a short time last week. That momentary oversight seems to have been fixed, though.

**Comment by jsha** [comment]
Yep, unfortunately Amazon doesn't support HTTPS, so we can't rewrite their pages.
