### ISSUE TITLE
HTTPS Everywhere Atlas lists "development" rulesets

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#2157]
But we no longer make development branch releases.  So we should consider removing those from the Atlas, perhaps?

**Comment by jsha** [comment]
Right now the "development" rulesets show what's in master. But that is a bit confusing. Ideally the script should show the latest version number, e.g. "These are the 5.0.5 rulesets", and "These are the rulesets that will be in the next release."

**Comment by Hainish** [comment]
This now shows "current release" with the date of the latest release
