### ISSUE TITLE
Cannot view all rules in HTTPS Everywhere 5.0.6

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2177]
I updated to HTTPSE 5.0.6 with Firefox 39.0 and noticed the Enable/Disable Rules option didn't work.  I figured maybe it was wrong with my system, but I've since been able to test it on another (both Windows 7 x64 with current patches as well as a Mac with OS X 10.9.5) and clicking the option never displays anything.  I was able to rest my rulesets to test out the new version's changes, but I cannot see all the rules like I had previously been able to.

**Comment by jsha** [comment]
Hi @MDawg957: We removed the "view all rules" functionality because, with the large number of rules we have today, it was causing browser hangs and crashes. I recommend using the HTTPS Everywhere Atlas (https://www.eff.org/https-everywhere/atlas/) to view and search all rules.

**Comment by foobar13373** [comment]
@jsha Why is the button still there if the functionality is removed? I was about to file the exact same issue, luckily I first looked in the closed ones...

**Comment by jsha** [comment]
@foobar13373: The menuitem now serves as a label to indicate that the items below it do: that is, they enable or disable rules. I agree the UI is rather unclear. I'm under a lot of time pressure lately, and needed to do the minimal thing to fix the hang / crash bug. I'm definitely open to suggestions on how the updated UI should work, to be incorporated into a future version!

**Comment by foobar13373** [comment]
@jsha Either remove it (to see that one can click the rules below is clear anyways, IMHO) or make it an unclickable label: one that does not highlight and  that also spans over the left "icon sidebar"), so that it looks like a real "headline".
