### ISSUE TITLE
Chrome build likely broken

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#2220]
FYI, @jsha -- it looks like https://github.com/EFForg/https-everywhere/commit/08a1f4acae648be8b76bdb74a8e720b193e20797 broke the Chrome build because of the unterminated:
```<securecookie host="^\.paste2\.org$" name="^(?:__cfduid|__qca$" />```

This throws:
```Uncaught SyntaxError: Invalid regular expression: /^(?:__cfduid|__qca$/: Unterminated group```

I'm guessing the version submitted to the Chrome store (and stuck) is broken (!)

* We should fail more gracefully in Chrome if a rule is malformed.
* We should expand tests to catch that.

**Comment by jsha** [comment]
Good catch, thanks! Fixed and test added in #2222.
