### ISSUE TITLE
Chrome: Recover from failures when reading rulesets

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2223]
In #2220, a bad regexp made it into the released package. This would have caused rewrites to fail for all users, but fortunately the release got hung up in the Chrome Web Store, probably by automated validation.

We should put try/catches around the relevant blocks, so a problem loading a single ruleset does not break all rulesets.

**Comment by nallar** [comment]
> but fortunately the release got hung up in the Chrome Web Store

Actually, it did get released :(

Getting `Uncaught SyntaxError: Invalid regular expression: /^(?:__cfduid|__qca$/: Unterminated group` on current version from the Chrome Web Store.
