### ISSUE TITLE
Next INpact domain broken

### ISSUE THREAD

**Issue by Berbe** [EFForg/https-everywhere#2226]
Following the last rewrite of the rules set for this domain (d1de66a1dc2ae362ce737eacabe44dc597c47e4e), nextinpact.com is redirected from HTTP to HTTPS, despite the site not profinding any SSL certificate for the base domain.

A request to http://nextinpact.com redirects to http://www.nextinpact.com, thus proving there is no handling of the base domain for content.
Please note that a request to https://www.nextinpact.com redirects to http://www.nextinpact.com, so do not try to convert the old nextinpact.com rule into its www subdomain one, producing an infinite loop.

Please remove the base domain from the rules for this domain.

**Comment by youdly** [comment]
It seems the website is using CloudFlare but stopped using CloudFlare SSL, despite cert's subject still matches *.nextinpact.com and nextinpact. I commented out the base domain from the ruleset.
