### ISSUE TITLE
Chrome: Cannot create / modify rules

### ISSUE THREAD

**Issue by smarek** [EFForg/https-everywhere#2227]
In latest version of extension, I'm unable to enable/disable applied rules or create custom rules, the dialog contains only "block all http request" item, see screenshot. Is this expected behavior?

Using Chrome Canary 46.0.2455.0

![screen shot 2015-07-15 at 16 51 41](https://cloud.githubusercontent.com/assets/384824/8701406/d99dd22e-2b11-11e5-897f-21adc99c8582.png)

**Comment by nallar** [comment]
Caused by #2220.

It's not just not displaying them, no rules are being applied at all. The broken build was released for some reason.

**Comment by smarek** [comment]
Well, can I request comment from devs please? @semenko @jsha

**Comment by jsha** [comment]
@smarek: Apologies for the broken build. The fixed version (2015.7.15) should be available now. Has your browser auto-updated?

**Comment by smarek** [comment]
@jsha well, thank you wery much, i didn't notice that. now rules appear to be workin, "block all http requests" too, however not "add rule for this site", that one will show the buttons, but all three actions do nothing ("Show advanced", "Add new rule", "Cancel"), collected error is on screenshot, only error shown for this version:
![screen shot 2015-07-16 at 01 02 33](https://cloud.githubusercontent.com/assets/384824/8711898/732d8c1a-2b56-11e5-994a-f351b1f4041c.png)

**Comment by semenko** [comment]
Hm, yeah, I see it on some sites but not others. Missing on nytimes.com, but present on github.com.

**Comment by jsha** [comment]
Thanks for point this out, @smarek! I fixed it in #2234, which will be included in the next release.
