### ISSUE TITLE
5.0.6 breaks netflix

### ISSUE THREAD

**Issue by ansamech** [EFForg/https-everywhere#2232]
with HTTPS enabled it gives an error, with it disabled, it does not.

**Comment by jsha** [comment]
What operating system and browser version? Can you provide more detailed instructions to reproduce?

I tried to reproduce on Chrome / Linux, but was unsuccessful.

**Comment by jsha** [comment]
Fixed by disabling the Netflix rule, will go out in the next release. Thanks for the report!
