### ISSUE TITLE
trulia.com : icons are broken with https everywhere installed

### ISSUE THREAD

**Issue by xuhdev** [EFForg/https-everywhere#2233]
There are some downside arrows which are broken on trulia.com when https everywhere is installed. More (meaningful) icons are broken when you browse the site.

**Comment by terrorist96** [comment]
Can't reproduce on newest version on Chrome. Which ruleset causes the problem?

**Comment by xuhdev** [comment]
@terrorist96 I'm using Firefox. Maybe that's the reason?

**Comment by terrorist96** [comment]
Works on FF too, but I'm using the development channel,  not the stable version.

**Comment by xuhdev** [comment]
@terrorist96 I tested the dev version, same thing. I started a clean profile and below is the screenshot:

![screenshot - 07212015 - 10 54 42 pm](https://cloud.githubusercontent.com/assets/325476/8818988/78338476-2ffc-11e5-90e2-b05b213d186a.png)

It works well for me on Chromium.

**Comment by xuhdev** [comment]
OK, once I disabled the trulia-cdn.com rule, things get normal.

**Comment by xuhdev** [comment]
Sorry for the spamming. If I disable the trulia-cdn.com rule then reenable it, the problem is still there. It looks like sort of a bug deep into the plugin, not the ruleset itself... I also tested an early version of Firefox (31.8) and an earlier version of Https everywhere (5.0.4), they are still reproducible.

**Comment by terrorist96** [comment]
I don't see what the problem is in your screenshot. What is broken exactly?

**Comment by xuhdev** [comment]
The icons (actually unicode font) e.g. right to the big Buy

**Comment by terrorist96** [comment]
You're right. I can reproduce it. The drop down arrow in the Buy text field is broken. Re-enabling the ruleset didn't cause it to break again, because it was saved in cache, but if you ctrl + f5 to do 100% refresh (not from cache), the issue reappears.

**Comment by blake-harris** [comment]
I believe this may be related to #3175 .

**Comment by stephen304** [comment]
This just cropped up for me. Trulia set up their https to redirect to plain http. The page source references everything from trulia-cdn.com over plain http despite the CDN supporting https, so the trulia-cdn.com rule blocks tons of resources. The CSS isn't even loading for me, in both firefox and chrome.

![2015-12-17-103323_1366x768_scrot](https://cloud.githubusercontent.com/assets/981915/11873637/a165d462-a4a9-11e5-8c46-71864f1a03b9.png)

![2015-12-17-103317_1366x768_scrot](https://cloud.githubusercontent.com/assets/981915/11873641/a617da28-a4a9-11e5-8057-1085ccf6918c.png)

**Comment by semenko** [comment]
Thanks for the report!

If you have the time, it'd be great if you could submit a small pull request excluding that subdomain.

**Comment by stephen304** [comment]
I found the relevant file: https-everywhere/src/chrome/content/rules/Trulia-cdn.com.xml
But I also noticed that it's doing a url rewrite to akamai. The Akamai url no longer works, so I think it would be a better solution to just change the rewrite to change http to https on (css|static).trulia-cdn.com instead of rewriting to akamai or removing the rule entirely.

Does that sound good?

**Comment by semenko** [comment]
Sounds great -- thanks! :)

**Comment by stephen304** [comment]
Which branch should I use and where should I send the merge?

**Comment by semenko** [comment]
Just to master would be great -- and right here at https://github.com/EFForg/https-everywhere :)
