### ISSUE TITLE
Internationalized domain name (IDN) not managed ?

### ISSUE THREAD

**Issue by aeris** [EFForg/https-everywhere#2246]
Hello,

I want to add a new set of rules to protect some domains, but one of my domain is an IDN.
Currently, seems HTTPSEverywhere is not able to allow such domain :
- If punny-code inserted on rule file, the domain not match when used in browser. I suspect a too simple « strcmp » or equivalent check between site and rule host.
- If Unicode direcly inserted on rule file, RelaxNG schema is too restrictive and reject the host. This way can also leads to encoding problem on rule files, and doesn’t protect direct user-inputed punny-code on browser address bar. After relaxing (:D) the RelaxNG schema, all is good and the browser match the domain.

I think the first solution is the better one if HTTPSEverywhere wants to handle IDN correctly and safely.

See https://github.com/EFForg/https-everywhere/pull/2245 for such example.
(IDN : café-vie-privée.fr, punny-code : xn--caf-vie-prive-dhbj.fr)

Regards,

**Comment by Bisaloo** [comment]
Related: https://trac.torproject.org/projects/tor/ticket/8182

**Comment by rbstrachan** [comment]
Hey, @aeris. This issue has been stale for _quite a while_. Is this still an issue?

**Comment by pipboy96** [comment]
IDNs are correctly handled now, as long as rulesets have Punycoded names.
