### ISSUE TITLE
CSS scaling issue for Firefox toolbarbutton in hamburger menu

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2253]
This is probably of very low priority, but here goes: When the counter label is shown while the button is in the hamburger/Australis menu, the button (+ label) can become too big to fit in the default grid, which makes it act a bit wonkily, as it forces other buttons to move around.

To reproduce, place the button in the horizontal center of the menu grid, surrounded by other buttons on both sides, and run

```
document.getElementById("rsapplied").value = "10"
```

in the browser console.

One obvious fix to this would be to simply not show the label when the button is hidden away; a better one might be to move label a bit (for instance, Ghostery has its label fixed in the lower right corner of its toolbarbutton, which I personally like). It looks like <code>/src/chrome/content/toolbar_button_binding.xml</code> would be the place to change the style.

**Comment by jeremyn** [comment]
@fuglede I can't tell if this is still a problem. Is it?

**Comment by fuglede** [comment]
It is. Note that one now has to set `devtools.chrome.enabled` to `true` to run commands in the browser console interpreter.

Here's what it looks like on Firefox 48.0.2 on Windows; it is impossible to have 3 buttons in the row containing the HTTPS Everywhere button:

![untitled](https://cloud.githubusercontent.com/assets/6169306/18230025/f993bb9a-728f-11e6-8316-4687003e00ec.png)

**Comment by jeremyn** [comment]
Okay, I see it now. The picture and the `devtools.chrome.enabled` reference helped.

Is this really a problem though? You're saying that if you increase the size of the add-on, it pushes other buttons around. What else would happen?

**Comment by fuglede** [comment]
No other side effects, I would imagine. As mentioned in the original post, I do consider this low priority. Nonetheless, it did [show up in another issue thread as well](https://github.com/EFForg/https-everywhere/pull/2882#issuecomment-141923976).

**Comment by jeremyn** [comment]
What is the side effect happening here?

**Comment by fuglede** [comment]
One unintended effect is that if you have three buttons in the relevant row, then the third button will be forced down when the label grows in size, which in turn can mess up the ordering in the rest of the menu.

**Comment by jeremyn** [comment]
If one button becomes too big, what else could Firefox do besides push the other buttons down?

Or is the issue that you can affect the size of the counter using CSS at all?

**Comment by fuglede** [comment]
Well, I simply don't think that we should give rise to the misalignment in the first place. If, for instance, the label extended in the opposite direction, this would not be an issue.

**Comment by jeremyn** [comment]
In your picture you mean if the "10" was on the right side over the arrow?

**Comment by fuglede** [comment]
I was actually thinking that it could be in the same spot, but that it would extend to the right instead of to the left.

**Comment by jeremyn** [comment]
So it would potentially overlap the top left corner of the icon if the number is really big?

**Comment by fuglede** [comment]
Yes.

Really, what will likely happen here is that one day a WebExtensions port will come by, and in that world, there will either be no counter, or the counter logic is built into the button object in such a way that this issue is no longer relevant.

**Comment by jeremyn** [comment]
If we weren't redoing it all with WebExtensions, then I would make the fix for this having the counter extend to the right as you said. But since we will eventually redo it, I agree that we should just wait and see. I personally disable the counter during normal use anyway.

**Comment by pipboy96** [comment]
Specific to deprecated version of HTTPSE.
