### ISSUE TITLE
EFF birthday (un)checkable?

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2254]
Is it intended that this birthday message (added in https://github.com/EFForg/https-everywhere/pull/2118) can be checked and unchecked?

![effbirthdaycheckable](https://cloud.githubusercontent.com/assets/11966684/8757084/bad4e04a-2cd7-11e5-935a-c93f34cd24a5.png)

Firefox 39.0
Add-on version: 5.0.6

**Comment by rugk** [comment]
I just saw in the pull request that also the EFF logo was used there (https://github.com/EFForg/https-everywhere/blob/master/src/chrome/skin/eff-16.png) so I think it was intended to have some purpose...
So should this maybe displayed there instead of the tick? (Because I can't find the logo anywhere in the addon)

**Comment by jsha** [comment]
How interesting! Do you have any user styles, themes, or extensions that might change UI elements in FF? The tick mark is supposed to be the EFF logo, and shows up correctly on FF 39 / 5.0.6 / Linux for me.

**Comment by rugk** [comment]
No it's just the default Firefox theme, style and so on. I will try it with all other add-ons disabled, but I don't think this makes a difference.

**Comment by finaljason** [comment]
I can confirm this issue for FF 40 / 5.0.7 / Windows.
Tested it with a clean profile and just HTTPSEverywhere installed. This problem does not occur under Linux with the same FF and Addon version.

    <menuitem type="checkbox" class="birthday menuitem-iconic" image="chrome://https-everywhere/skin/eff-16.png"
          label="Happy 25th birthday, EFF!" command="https-everywhere-menuitem-birthday" />

Some thoughts about this crossing my mind:

    type="checkbox"
Is this really needed here? We are not checking for any enabled/disabled state but just open a link on click.

    class="birthday menuitem-iconic"
This class seems not to be defined. "menuitem-iconic" would be a valid XUL class for showing a picture according to https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Style/menuitem-iconic

However, Firefox under Linux and Windows seem to honor things a little differently here but they definitely shouldn't.

**Comment by rugk** [comment]
BTW I've also tried it with Tor Browser and it was the same result. (uncheckable)

**Comment by rugk** [comment]
EFF's birthday is gone, so what about this issue? Should it be closed?

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's a valid bug.
