### ISSUE TITLE
Disable/Enable ruleset window gone

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#2258]
The disable/enable window was removed in #2121 (v 5.0.6 later). As already mentioned in #1609 IMO this is not optimal.
It was such nice to see what sites/services are supported. Okay you can do this with [Atlas](https://www.eff.org/https-everywhere/atlas/index.html) too, but there it is much less uncomfortable.

Some things I liked with the rules window, which we lost now:
- ability to search/filter addons (with Atlas you have to click on the first letter of the name - that's terrible UX compared to the search feature :cry:)
- ability to just right click and show the XML source directly from the addon (this was nice for quickly debugging/looking into a ruleset, now you have to visit Atlas for this and look for the correct ruleset there, which is annoying)
- an overview over which rules you have enabled and disabled

Besides this also Atlas is not linked from the addon (about page or somewhere else), so many users, which previously used the ruleset window, maybe do not find it.

**Comment by jsha** [comment]
You make some good points. We should definitely link and promote the Atlas better. And its UI should certainly be improved! You actually can search for rulesets in the Atlas, you just have to type in the big query box with no label. :-)

I would definitely like to add back the ability to view source directly from the addon, probably as a link from the rulesets that show up in the icon menu when you are on a given site.

**Comment by blobgo** [comment]
> You actually can search for rulesets in the Atlas, you just have to type in the big query box with no label. :-)
:astonished: Oh yes you're right. So I think about this box and UX you don't have to say more.

> I would definitely like to add back the ability to view source directly from the addon, probably as a link from the rulesets that show up in the icon menu when you are on a given site.

Yes somehow like this would be good.

BTW about "an overview over which rules you have enabled and disabled" I think also a display of all rules where you (=the user) toggled the state would be enough - so you can see, which rules you modified.

**Comment by David-Leudolph** [comment]
So, if the (useful) ruleset window is gone, the links to it in the toolbar and tools menu should be removed as well. Shouldn't they?

**Comment by jsha** [comment]
I left the "Enable / disable rules" text in the toolbar menu as an indicator of what clicking the menu items below it will do. I forgot to give it the disabled property so it looks less like a menu item itself; that's coming in a future release. I'm also very open to changes in wording or UI that will achieve the same goal more clearly.

Also, I'd like to hear more about your use case for the ruleset window, to see if I can meet it some other way. Does the HTTPS Everywhere Atlas help? https://www.eff.org/https-everywhere/atlas/

**Comment by David-Leudolph** [comment]
Hi jsha 

The ruleset window provided a nice overview of all the rules, but It seems like the atlas page does this as well.

**Comment by rezad1393** [comment]
so it is definitely gone?
that is not good.
now I have no way of knowing enabled and disable websites before I visit them.
no I am not talking about what rules are in Atlas website are.
I am talking about my version of addon installed on my computer which can be offline and can differ from the latest rules in Atlas.( as far as I know rules are packaged in addon and are not updated or loaded separately from Atlas website, which would be better , but that's another matter).

now if I want to check to see what rules are disable by default or by my modification I have no way of seeing that.
also I have a lot of rules added by https finder addon and they definitely  are not in Atlas.and I cant see their state  anymore .
I understand the lookup of browser when opening the rules window but couldn't it be still there but hidden and as a alternative to Atlas? 
this is sad.

**Comment by blobgo** [comment]
> ( as far as I know rules are packaged in addon and are not updated or loaded separately from Atlas website, which would be better , but that's another matter).

cross reference: https://github.com/EFForg/https-everywhere/issues/2605 :wink: 

> I have a lot of rules added by https finder addon and they definitely are not in Atlas.and I cant see their state anymore .

Good argument. I haven't thought about this earlier.
I mean you can see there state in the context menu, but you have to visit the site before you can do this, so I understand that a rules overview would be better.

**Comment by blobgo** [comment]
As for a **reimplementation of the rulesets list** one small suggestion: Use a tab page.
This way you easily have a flexible windows and I think, because of the HTML basis there it should be easily (or at least easier) to create (than the old window) and is possibly more robust than the old one (preventing things like https://github.com/EFForg/https-everywhere/issues/1609).
This would be the same approach which is also used by the new version of Privacy Badger, which display the detected trackers.

**Comment by alice-margatroid** [comment]
>rezad1393 commented
>so it is definitely gone?
>that is not good.
>now I have no way of knowing enabled and disable websites before I visit them.

I agree with rezad1293 here, without the Preferences menu, as it was called. There is no meaningful way to use the addon anymore. I need the search function in the extension and the ability to change rules before I visit a site.

Since this issue is being ignored the only way is downgrading to an old version, turning off upgrades and risking having less protection. I recommend everyone doing the same. They won't learn until new installs go down.




![menu](https://cloud.githubusercontent.com/assets/13979667/10178707/afa9591c-6701-11e5-8283-93d12f0577fb.jpg)

**Comment by vicgarin** [comment]
@jsha How do I Enable and Disable my custom rulesets now?

**Comment by margentieri** [comment]
Completely removing this functionality has damaged the usability of this addon, and has FORCED me to downgrade to 3.4.5 to retain the preferences window. You are ignoring the fact that not all sites that are being converted to an HTTPS connection are actually that of the website being visited, and therefore do not show up as options to check or uncheck on the site. A prime example is Netflix, which uses Silverlight to play their videos and provide DRM. Silverlight needs to communicate with Microsoft, but none of Microsoft's websites are listed on the dropdown when you are on Netflix's site. Without disabling HTTPS Everywhere for Microsoft, Silverlight fails to properly communicate with Microsoft, and the site will not play ANY videos. In the past, I simply had to go into the addon's settings, search for Microsoft, and uncheck it. Now I can't do that, which completely breaks Netflix. I should note that I am using Firefox on Ubuntu Linux, not Windows or Mac. Functionality in an addon like this should never be totally removed for the sake of convenience or the laymen. If you want to remove it from sight for the laymen, fine, but like alice-margatroid suggested, at least provide a means to re-enable it though an expert mode check box or an about:config setting that can be changed.

**Comment by rugk** [comment]
This is completely off-topic, but just FYI: For watching videos on Netflix with Firefox [you now do not need Silverlight anymore](https://blog.mozilla.org/blog/2015/12/17/firefox-users-can-now-watch-netflix-html5-video-on-windows/).
But as I see you use Linux I have to say that on Linux this does not work currently AFAIK as you do not have Adobes Content Decryption Module here.

**Comment by margentieri** [comment]
Hi @rugk, yes I am aware that Firefox HTML5 can play Netflix videos, but this option is currently only available on Windows machines, which forces me to use Pipelight instead (Pipelight being a Linux port of Silverlight)

**Comment by rugk** [comment]
Okay and as a a reference: The Silverlight issue seems to be tracked in https://github.com/EFForg/https-everywhere/issues/1767.

**Comment by margentieri** [comment]
Thanks, but personally I don't see this so much as a bug as I do an issue of a site that I would just need to manually did myself by disabling HTTPS connections with Microsoft. The issue I see here is that my ability to make this kind of fix has been completely removed. Netflix and Silverlight was just an example. If this kind of issue is present with Netflix, it would not surprise me to find the same kind of issue elsewhere. The only way to fully address this kind of issue is to enable users to see AND modify the HTTPS settings for every site without having to first visit them, as was the case before the HTTPS Everywhere preferences page was removed.

**Comment by rugk** [comment]
I don't really know the details but AFAIK all connections a site makes and which are redirected/influenced by HTTPS-Everywhere should appear in the context menu of the icon.

**Comment by margentieri** [comment]
If that were true, then Microsoft would show up on Netflix due to the Silverlight connection; however, this is not the case. Silverlight DOES need to connect to Microsoft for DRM, this is known, so the fact that HTTPS Everywhere disturbs this connection proves it is redirecting/influencing that connection, especially since disabling Microsoft in the HTTPS Everywhere preferences fixes the issue.

**Comment by rugk** [comment]
Well... the only explanation would be that Silverlight itself accesses Microsoft, but the HTTPS Everywhere filter usually do not affect plugins so this is really strange.

**Comment by margentieri** [comment]
Understood, but again... That was just an example. A useful feature such as this should not be totally removed. Hide it if you want, maybe only make it accessible through altering an about:config setting, but don't completely remove its utility for those of us who know what we are doing and have use of it. Total removal of a feature for the sake of the layman is a horrible horrible philosophy to develop with. At the very least, as @rezad139 pointed out, as Atlas only shows the default rules, I now no longer have any means to view which rules I have manually added or disabled myself unless I visit the site, and if I'm interested in a list of which custom rules I have... Am I supposed to try and visit every website I've ever visited so I can check what shows up on that stupid drop down menu?

**Comment by jsha** [comment]
To clarify: We removed this feature because it required ongoing maintenance disproportionate to its usefulness. With the large number of rules we have today, the preference window was crashing people's browsers, and the only reasonable course was to take it out.

If you'd like to view your custom rulesets, they are in the same place you created them: under the HTTPSEverywhereUserRules directory of your Firefox profile.

**Comment by rezad1393** [comment]
then to disable and enable my own custom rules I have to go to that directory  then find and move out the needed rules files and and then "disable https everywhere" and then enable it again , just to check to see the effect?

brilliant.

**Comment by jsha** [comment]
No, your custom rules should show up in the drop-down menu when you visit a site that they affect. You can then enable or disable them from the drop-down.

Is the issue that you are modifying your custom rules and need an easy way to reload them after modification?

**Comment by rezad1393** [comment]
please try your own solution and see if it works for you .
doesn't work for me for custom rules.just for default rules.

**Comment by rugk** [comment]
Indeed I have to confirm that you cannot enable or disable custom rulesets. I thought this was a known issue and is just not implemented or something like this.
Should I open a new issue about this?

Tried with Firefox 44

**Comment by jsha** [comment]
Thanks for pointing that out. I thought we had fixed that a while ago. It's possible we fixed a different bug and then regressed. Anyhow, the custom rule enable/disable bug should now be fixed in #4095.

**Comment by mzso** [comment]
@alice-margatroid 
> the only way is downgrading to an old version, turning off upgrades and risking having less protection. I recommend everyone doing the same. 

Hi!
Do you know where to get the old version? Is really 5.0.6 the latest with this window.

**Comment by pipboy96** [comment]
This issue is specific to pre-WebExtensions Firefox version. Closing.
