### ISSUE TITLE
SSL Observatory display issues

### ISSUE THREAD

**Issue by blobgo** [EFForg/https-everywhere#2261]
There are two issues:
1. The window is resizeable without any limitation which is quite useless.
2. There is still talked about Torbutton, but the new Tor versions use Tor Launcher (at least this is how the addon is called).

Addon 5.0.7
Firefox 39.0
Windows 7

**Comment by jsha** [comment]
Can you tell me more about where the Torbutton is referenced?

**Comment by blobgo** [comment]
There: SSL Observatory --> Use SSL Observatory --> Check certificates with tor [...] \(requires **Torbutton**) --> (tooltip) ... requires the installation of Tor and **Torbutton**

This is loosely translated, because I'm using a Non-English version of Firefox and HTTPSE.

**Comment by jsha** [comment]
Thanks! What language are you using? I think this might be an out-of-date translation, since the current English version doesn't say that.

**Comment by blobgo** [comment]
German.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
