### ISSUE TITLE
List of broken rules.

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#2274]
I have an extensive list of rules that break websites. What's the prefered mode of action? Should I post them here in one thread? Should I make a separate issue for each rule? Or should I go and add `default_off="Breaks site"` to each rule?
Thanks.

**Comment by reedy** [comment]
You could at minimum post the list of what rules break site, and then open pull requests for the lot. Ideally with what breaks, rather than a "it doesn't work". It depends on the nature of the breakages; disabling them fully works sometimes, but in other cases, just disabling specific rules or hosts helps

**Comment by terrorist96** [comment]
Okay, here's the list. I haven't checked to see if they are all outstanding, as some may have been fixed:

https breaks page (Microsoft (partial)); have to load the unsafe script: https://social.technet.microsoft.com/Forums/office/en-US/eeb1e7ba-c1f0-4374-ba5c-ed7be59e928d/spell-check-stopped-in-the-middle-of-my-document?forum=word
and
silverlight crashes: http://windows.microsoft.com/en-US/windows7/Create-a-system-repair-disc


Amazon web services breaks videos:
http://www.amazon.com/BACtrack-Keychain-Breathalyzer-Portable-Detector/dp/B006536ZXC/ref=sr_1_2?ie=UTF8&qid=1392853342&sr=8-2&keywords=breathalyzer
and
http://wavy.com/2014/02/27/attorney-video-shows-police-used-excessive-force-in-mans-death/
and
http://www.kshb.com/news/local-news/investigations-extras/discarded-tea-leaves-false-positive-drug-tests-prompt-search-warrant-of-joco-familys-home
and
http://www.infowars.com/caught-on-tape-cop-shoves-trips-soccer-fans/
and
http://www.activistpost.com/2014/05/texas-man-facing-possible-life-sentence.html


Echo enabled breaks comments:
http://www.kshb.com/news/local-news/investigations-extras/discarded-tea-leaves-false-positive-drug-tests-prompt-search-warrant-of-joco-familys-home

Akamai breaks video: http://foxnewsinsider.com/2014/02/20/watch-judge-napolitano-takes-radical-fcc-plan-monitor-media-fox-and-friends

Amazon web services and Cloudfront break video:
http://pro.stansberryresearch.com/1310PSIEANEW/LPSIQ315/?h=true

Youtube (partial) blocks the video from appearing/loading:
http://www.scottrose.tv/videos.php?vid=21
and
http://www.collateralmurder.com/
and
http://wearechange.org/veteran-fights-for-his-rights/
and
http://forum.xda-developers.com/moto-x/orig-development/root-rockmymoto-yes-ota-t2509590


Turner (partial) breaks video:
http://video.adultswim.com/fat-guy-stuck-in-internet/buffalo-chicken-flowers.html
http://teamcoco.com/video/full-episode-thurs-7-9-the-cast-of-the-hunger-games-mockingjay-part-2-?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjl9 (FF)


PC world https broken:
http://www.pcworld.com/article/128248/article.html

Chartbeat (partial) breaks video (in chrome only):
http://www.politico.com/story/2014/04/eric-holder-james-clapper-testimony-105478.html
http://www.politico.com/story/2013/04/senate-gun-control-deal-rejected-90225.html
http://www.nbcnews.com/feature/edward-snowden-interview/watch-primetime-special-inside-mind-edward-snowden-n117126
http://www.wsbtv.com/news/news/national/139m-florida-mansion-becomes-most-expensive-listin/nhJTK/


News Corporation (partial) breaks images from loading:
http://online.wsj.com/news/articles/SB10001424052702304914904579435592981780528

Reuters (partial) slows down page load severely and prevents image from loading:
http://www.reuters.com/article/2014/04/21/us-usa-justice-clemency-idUSBREA3K0QF20140421

Livestream (partial) breaks video:
http://www.activistpost.com/2014/05/watch-glenn-greenwald-debate-nsas.html

Adobe breaks video:
http://www.fox.com/watch/264593475760

About ads (partial) breaks the stylesheet:
http://www.aboutads.info/choices/

Cloudfront prevents videos from being displayed:
http://www.chooseliberty.org/irsvideo.aspx?pid=0713a

CNBC (partial) breaks video:
http://www.cnbc.com/id/101838640

Chartbeat (partial) breaks video:
http://www.cincinnati.com/story/news/2014/08/04/seeking-security-women-turn-guns/13609625/

Ikea (partial) prevents you from adding stuff to your cart ("buy online" button)
http://www.ikea.com/us/en/catalog/products/S79932697/#/S39932699

Telegraph media group (partial) blocks images from loading:
http://blogs.telegraph.co.uk/news/danielhannan/100283348/seventeen-years-after-dunblane-its-still-impossible-to-discuss-the-effectiveness-of-the-handgun-ban/

Echo Enabled breaks comments:
http://www.abc2news.com/news/region/anne-arundel-county/women-and-guns

businessinsider (partial) breaks images:
http://www.businessinsider.com/chipotle-threatens-fast-food-chains-2014-9

Chartbeat and Akamai break video:
http://www.usatoday.com/story/tech/2014/09/30/microsoft-windows/16474073/

Zillow breaks loading of houses on map and list on right hand side:
http://www.zillow.com/homes/

Google Videos breaks opening images in a new tab:
https://www.google.com/search?site=&tbm=isch&source=hp&biw=1344&bih=613&q=example&oq=example&gs_l=img.3..0l10.846.1713.0.1858.7.7.0.0.0.0.142.412.0j3.3.0.msedr...0...1ac.1.62.img..4.3.411.2DN6TnejnFM

Fox news (partial) breaks images:
http://www.foxnews.com/us/2015/03/24/shoddy-stats-fbi-figures-tweaked-to-show-phony-increase-in-mass-shootings-says/

LiveFyre breaks comments:
http://www.foxnews.com/us/2015/03/24/shoddy-stats-fbi-figures-tweaked-to-show-phony-increase-in-mass-shootings-says/

Demandware.edgesuite.net (partial) breaks style sheet
http://www.barneys.com/homepage

Huffington Post (partial) breaks images:
http://www.huffingtonpost.com/2015/03/26/peta-shelter-virginia-bill-sb-1381_n_6942866.html?ncid=fcbklnkushpmg00000063

MakeUseOf (partial) breaks image to the left of the sections (the '>' image):
http://www.makeuseof.com/tag/jay-zs-tidal-music-streaming-service-doomed-fail/

Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

Lowes.com (partial) breaks Sorting by price Low to High:
http://www.lowes.com/Search=hot+water+heater?storeId=10151&langId=-1&catalogId=10051&N=0&newSearch=true&Ntt=hot+water+heater#!&Ns=p_product_price%7C0&page=1

Tesla (partial) breaks info panel on left:
http://www.teslamotors.com/findus#/bounds/49.38,-66.94,25.82,-124.39,d?search=supercharger&name=us&place=mishawakasupercharger

Leaflet JS (partial) breaks map:
http://www.liberland-urbandesign.org/

Gave up reporting..

MSNBC (partial) breaks video)
http://www.koaa.com/story/29566136/verdict-reached-in-theater-shooting-trail

Webs.com (partial) breaks members.webs.com

**Comment by terrorist96** [comment]
Going through a few, I notice that many have been fixed by disabling the rule by default or tweaking the rule. I'll go through and strike the ones that don't need to be fixed.

**Comment by terrorist96** [comment]
Ok, I finally went through it all and only the ones that are still broken are left.
Please advise.

**Comment by terrorist96** [comment]
One more:
torrentfreak.com/why-are-porn-perfomers-scared-to-talk-about-internet-piracy-140413/

Have to first enable 'load unsecure shit' then have to disable ABC News (partial) in order for the video at the bottom to load.

**Comment by terrorist96** [comment]
I also have a list of sites that *should* have https forced, but I'll post that after we get these fixed. =)

**Comment by terrorist96** [comment]
What about

> Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

?
@2d1

**Comment by terrorist96** [comment]
@2d1 ?

**Comment by terrorist96** [comment]
The struggles of trying to get a dev to reply... :expressionless:

**Comment by terrorist96** [comment]
> Webs.com (partial) breaks stylesheet on http://members.webs.com

> Tesla (partial) breaks info panel on left:
http://www.teslamotors.com/findus#/bounds/49.38,-66.94,25.82,-124.39,d?search=supercharger&name=us&place=mishawakasupercharger

> Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

These are still broken in the latest version (2015.08.13). The rest look to be fixed.
@2d1 
Thanks

**Comment by terrorist96** [comment]
Tesla motors (partial) is also breaking the "Range Per Charge" toggle options (speed, outside temp, wheels, etc)
http://www.teslamotors.com/models

@fuglede can you please help with this?

in addition to:

> Webs.com (partial) breaks stylesheet on http://members.webs.com

Tesla (partial) breaks info panel on left:
http://www.teslamotors.com/findus#/bounds/49.38,-66.94,25.82,-124.39,d?search=supercharger&name=us&place=mishawakasupercharger

Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

**Comment by rugk** [comment]
[**@terrorist96**](https://github.com/terrorist96) commented on [20. Juli 2015, 05:55 MESZ](https://github.com/EFForg/https-everywhere/issues/2274#issuecomment-122752763 "2015-07-20T03:55:17Z - Replied by Github Comment Enhancer"):
> Okay, here's the list. I haven't checked to see if they are all outstanding, as some may have been fixed:
> 
> Microsoft (partial)  
> 
> silverlight doesn't load: [http://windows.microsoft.com/en-US/windows7/Create-a-system-repair-disc](http://windows.microsoft.com/en-US/windows7/Create-a-system-repair-disc)

Create a system repair disk?!
Using all my imagination I cannot see any relation between the two issues. (other one tracked in https://github.com/EFForg/https-everywhere/issues/1767).
