### ISSUE TITLE
LiveJournal rules break commenting

### ISSUE THREAD

**Issue by tdsmith** [EFForg/https-everywhere#2285]
Using HTTPS Everywhere 2015.7.17 on Chrome 43.0.2357.134 on OS X, disabling the LiveJournal rule is necessary to reply to comments on journal entries at livejournal.com.

LJ support is aware:
> Thank you for your inquiry. This behavior most often happens when you have a browser add-on called HTTPS Everywhere installed. The HTTPS Everywhere add-on is known to cause problems on LiveJournal, as several locations such as comment pages and the edit profile page do not have https support.

Commenting fails by redirecting to an "Unhandled Error" page. Turning off the rule restores functionality.

**Comment by youdly** [comment]
I updated the ruleset. In fairness, the issue is actually caused by poor support/implementation of HTTPS by LJ, not the addon.
"The HTTPS Everywhere add-on is known to cause problems on LiveJournal, as several locations such as comment pages and the edit profile page **do not have https support.**"
