### ISSUE TITLE
Allow individual whitelisting of HTTP sites for "Block all HTTP requests."

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2299]
It would be nice, in "Block all HTTP requests" mode, to be able to say "this site is okay to hit over HTTP," and have that stored by the extension.

**Comment by axch** [comment]
Additional potentially useful UI elements:
- "Let this one tab make as many insecure requests as it wants"
- "Allow insecure requests (from this tab?) for the next 3 minutes"
- "Retry the last rewritten request without rewriting it"

and maybe some of these things in combination with each other.

**Comment by Bisaloo** [comment]
This is fixed by dc04b6d845736922667317ab240bfe97e63135ce as far as I can tell. Users can now click on the URL they were trying to visit in the "Secure only" mode to add a permanent exception for this site.
