### ISSUE TITLE
Invalid cert for lxr.mozilla.org

### ISSUE THREAD

**Issue by squarefractal** [EFForg/https-everywhere#2302]
lxr.mozilla.org uses the same cert as mxr.mozilla.org, triggering an invalid cert error.

I would like to request disabling of the Mozilla rule for lxr.mozilla.org

**Comment by J0WI** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1190224

**Comment by jeremyn** [comment]
According to the Bugzilla bug that @J0WI linked, it looks like MXR/LXR have been replaced by DXR. `lxr.mozilla.org` is not available in DNS. So, I'm closing this issue.
