### ISSUE TITLE
Adap.TV breaks sites

### ISSUE THREAD

**Issue by candi7** [EFForg/https-everywhere#2303]
I visit this site every day(a couple times a day) but since I added the https app add on now it won't load the video on this site .....  http://www.post-gazette.com/sports/outdoors/2014/01/31/LIVE-Bird-s-eye-view-of-Pittsburgh-s-bald-eagles/stories/201401310148
I clicked the disable https everywhere, but that only disables it for that site, correct?
Thank you very much,
Candi

**Comment by MDawg957** [comment]
I had to find an alternate site since I ran out of views for your link and didn't want to create an account, but I was able to use  http://www.pixcontroller.com/falcons/ for my test.

Disabling the specific rule Adap.TV (partial) will fix the issue.

Disable HTTPS Everywhere will disable it for all sites, you can disable the specific rule I mentioned above to resolve it for the time being though and continue to be secure elsewhere.

**Comment by candi7** [comment]
Ok.  Great!  Thanks!  But how do I do that?  Disable the specific rule Adap.TV(partial)?   I have no idea how to do that. Thanks again!   On 07/22/15, MDawg957<notifications@github.com> wrote: I had to find an alternate site since I ran out of views for your link and didn't want to create an account, but I was able to use  http://www.pixcontroller.com/falcons/ for my test.Disabling the specific rule Adap.TV (partial) will fix the issue.Disable HTTPS Everywhere will disable it for all sites, you can disable the specific rule I mentioned above to resolve it for the time being though and continue to be secure elsewhere.—Reply to this email directly or view it on GitHub.

**Comment by MDawg957** [comment]
When you're on the site with the issue, click the HTTPS Everywhere button and instead of picking "Disable HTTPS Everywhere" (Enable it if you have it disabled already), click on "Adap.TV (partial)" and the page will reload with the content properly loading.

**Comment by candi7** [comment]
Ok, great!  Easy enough!Thank you very much!!!!   On 07/22/15, MDawg957<notifications@github.com> wrote: When you're on the site with the issue, click the HTTPS Everywhere button and instead of picking "Disable HTTPS Everywhere" (Enable it if you have it disabled already), click on "Adap.TV (partial)" and the page will reload with the content properly loading.—Reply to this email directly or view it on GitHub.

**Comment by semenko** [comment]
Video plays for me now.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
