### ISSUE TITLE
Issue with WildEarth.TV

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2305]
http://wildearth.tv/

The icons that should display under "Sign in using one of these accounts" do not and you only get two white boxes.  Disabling the rule JanRain (partial) fixes this.

**Comment by jeremyn** [comment]
Thanks for this write-up. At http://wildearth.tv/ I see six icons under "Sign in using one of these accounts", none of which look broken to me, so this issue looks resolved. I'm closing this issue but please feel free to reopen it with a comment if this is still a problem for you.
