### ISSUE TITLE
Problems on heise.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2308]
If you follow this link
http://www.heise.de/foto/galerie/fullscreen/?sort=neueste&page=1
you end up on a broken page.
![heise_enabled](https://cloud.githubusercontent.com/assets/7859245/8846087/acf8cc2e-3124-11e5-83b4-29a5afc7fdde.png)

If you disable the "Heise.de (partial)" rule everything's fine.
![heise_disabled](https://cloud.githubusercontent.com/assets/7859245/8846260/c7de4176-3125-11e5-983c-defeffa23866.png)

**Comment by numismatika** [comment]
Heise seems to be experimenting lately with TLS,  certain parts of their page get tls and some all of a sudden redirect to plain again.
#2262 fixes the news pages 
I'll experiment with the gallery soon, probably needs exceptions for a few files.

**Comment by numismatika** [comment]
@KommX second commit in my pull-request seems to fix it.
