### ISSUE TITLE
Cloudfront video breakage

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2310]
Example:
bleacherreport.com/articles/2529416-71-hs-center-thon-maker-crosses-up-defender-sinks-jumper-at-fab-48

See the first flash video

Browser:
Firefox

**Comment by semenko** [comment]
Video plays for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
