### ISSUE TITLE
Fix Transifex integration

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2313]
We have tests that fail if a message is present in the english locale
file but absent from some of the other locales, which makes it hard to
add a new message. Our integration with Transifex, our translation platform,
means that we should add new messages to the english locale, commit, then
wait a short while and pull the latest copy from Transifex, which will have an
instance of that message for every locale, defaulted to English (and updated
over time). Currently this would make our tests fail.

We should keep only the English locale in our source repo, with a submodule
that tracks the upstream Transifex repo. We should remove the test for "all
locales present" and move it to a separate set of pre-release tests.

**Comment by reedy** [comment]
In WMF projects, we have translations done to translatewiki.net 99.9% of the time, but some authors do them manually to source files. Those get pulled in, and periodically we rebuild all language files, to remove any erroneous translations etc.
