### ISSUE TITLE
HTTPS Everywhere logo blurry on retina Macbook Pro

### ISSUE THREAD

**Issue by adikamdar** [EFForg/https-everywhere#2316]
<img width="101" alt="screenshot 2015-07-24 00 49 06" src="https://cloud.githubusercontent.com/assets/1112044/8869870/ebfea5d2-319d-11e5-8467-49d5bc1e5192.png">

**Comment by reedy** [comment]
I agree. It looks like we need a high definition logo, and it's the same in FF :)

**Comment by reedy** [comment]
https://github.com/EFForg/https-everywhere/blob/master/chromium/manifest.json#L25-L29

Those would look like they're supposed to dish out better icons, but I've not really much idea

**Comment by S-ed** [comment]
https://github.com/EFForg/https-everywhere/pull/2351

**Comment by S-ed** [comment]
Heh, found this icon later:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/skin/https-everywhere-128.png

**Comment by jsha** [comment]
Yes, I think the issue is not lack of high-res logos, but failure to choose the proper high-res logo. Or, perhaps, the browser is choosing the right logo but then needs to resize it for some reason, leading to blurriness.

**Comment by jsha** [comment]
I think I found the cause! On Chromium we set the icon manually based on whether `Block all HTTP requests` is enabled: https://github.com/EFForg/https-everywhere/blob/master/chromium/background.js#L86, and the code doesn't take into account resolution.

Not sure the best way to fix, but thought I'd post what I found so far.

**Comment by jsha** [comment]
@reedy: Can you provide a screenshot in Firefox on a retina Mac Pro? Preferably including neighboring icons for reference?

**Comment by reedy** [comment]
<img width="273" alt="screen shot 2015-08-13 at 09 46 58" src="https://cloud.githubusercontent.com/assets/67615/9245980/4e52f9c4-41a0-11e5-966d-fd4221e073c9.png">

**Comment by jsha** [comment]
@reedy: Looks like you've got 16px icons, same as I do on a regular-resolution PC running Linux. I get the same blurriness on the 16px icon, which I think is just because the icon doesn't shrink well. I've talked a little to our in-house graphic designer about a completely new icon for HTTPS Everywhere that would be more legible / less blurry.

In the meantime, we should at least be able to do better for Retina displays.

**Comment by gloomy-ghost** [comment]
close as fixed
