### ISSUE TITLE
www.codeskulptor.org doesn't work

### ISSUE THREAD

**Issue by ibu2004** [EFForg/https-everywhere#2319]
When I use www.codeskulptor.org it works but the Google API when encrypted prevents it from opening and saving my files to the cloud.

**Comment by jeremyn** [comment]
Thanks for the report. On http://www.codeskulptor.org/ , only the rulesets `Google Maps` and `Google APIs` are available, and only `Google Maps` is active by default. Also it looks like the save functionality works though I'm not really familiar with how this site works.

This looks fixed/not currently a problem to me so I'm closing the issue, but please feel free to reopen it with a comment if this is still a problem for you.
