### ISSUE TITLE
virtualearth.net rule broken on tesco.com

### ISSUE THREAD

**Issue by CosmicTourist** [EFForg/https-everywhere#2320]
Tesco's store finder use virtualearth.net to display the search research, but if the virtualearth.net rule is enabled then nothing happens when you click "Find stores" - http://www.tesco.com/store-locator/uk/. I have to disable the rule to get it working.

**Comment by jeremyn** [comment]
Clicking `Find stores` works for me on both Firefox and Chrome. Closing issue, but please feel free to reopen it with a comment if you are still having this problem.
