### ISSUE TITLE
Add some hosters/domain registrars

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2324]
- [x] https://www.domaindiscount24.com
- [x] https://rage4.com/
- [x] https://www.royaldns.net/
- [x] https://www.transip.de/
- [x] https://www.rb-media-group.de/
- [ ] https://www.rrpproxy.net/
- [ ] https://www.omc.net/
- [ ] https://www.mk.de/
- [ ] https://www.mcs.de/
- [ ] https://joker.com/
- [ ] https://www.internetx.com
- [ ] https://www.epag.de/
- [ ] https://www.edns.de/
- [ ] https://domainexpress.de/
- [x] https://desec.io
- [x] https://www.dotplex.de/
- [x] https://www.cps-datensysteme.de
- [x] https://www.core-networks.de/
- [x] https://www.123domain.eu/

**Comment by J0WI** [comment]
It would be great to get a pull request from you!
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by rugk** [comment]
If I get time I will do.

**Comment by rugk** [comment]
dotplex.de already has a rule: https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Dotplex.de.xml

**Comment by zneaa** [comment]
@rugk joker.com.xml https://github.com/EFForg/https-everywhere/pull/8891

**Comment by zneaa** [comment]
@rugk cps-datensysteme.de.xml https://github.com/EFForg/https-everywhere/issues/2324

**Comment by zneaa** [comment]
@rugk core-networks.de.xml https://github.com/EFForg/https-everywhere/issues/8893

**Comment by jeremyn** [comment]
I've closed pull request https://github.com/EFForg/https-everywhere/pull/8892 without merging it, so `cps-datensysteme.de` still needs a ruleset.

**Comment by RemakingEden** [comment]
@J0WI I'm slightly confused on some of these older issues. I'm new to contributing so i'm sorry if this is a basic question. Ive just tested a lot of these and they all seem to resolve to https automatically. 

Should I check all of them and if they all resolve automatically should this be closed? Or if thye resolve automatically, is it still good to make rulesets for them?

Thanks for the help!

**Comment by rugk** [comment]
@RemakingEden It does not matter if a site automatically redirects to HTTPS. See https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages

**Comment by RemakingEden** [comment]
@rugk thanks for the info! So does this mean we should make rulesets for every single website out there? It seems like the extension may get impossibly large then?

**Comment by J0WI** [comment]
Yes, our goal is to have HTTPS Everywhere and the infinitely growing database is an issue we can't really solve as long as unsecured connections are still supported.
We remove rulesets for domains that support preloaded HSTS, but this is also a infinitely growing database in browsers. Some new TLD are preloaded itself, so things will be easier there.

**Comment by RemakingEden** [comment]
@J0WI Added a ruleset for RB-Media https://github.com/EFForg/https-everywhere/pull/17356

**Comment by RemakingEden** [comment]
Added new rulesets for Rrpproxy and Rb-media-group https://github.com/EFForg/https-everywhere/pull/17370 https://github.com/EFForg/https-everywhere/pull/17369

**Comment by pipboy96** [comment]
See #17760, #17759, #17758, #17757, #17756, #17755, #17754, #17753, #17752.
