### ISSUE TITLE
Dota2.com watch section is broken

### ISSUE THREAD

**Issue by jeifour** [EFForg/https-everywhere#2326]
1) Go to http://www.dota2.com/watch/
2) Choose any stream you want to watch (currently only works flawlessly in Chromium/Chrome because it uses MSE)
3) Video won't load properly

A fix I found is disabling the "Steam Community.com (partial)" rule. Then the stream works as expected. I also spoke with some people in the stream chat, and they also reported their problems with Https-everywhere and this rule when watching streams.

**Comment by Ivoz** [comment]
This is yet another reason that something like [this](https://github.com/EFForg/https-everywhere/issues/296) should be implemented.

Let's face it, some sites in 2015 *still* break when they have HTTP forced to HTTPS.

And https-everywhere is the cause of this breakage.

I love the idea of getting HTTPS everywhere by default, but I'd also love the option to **allow sites to work**. There is no configurability in the plugin to allow this. We need to be able to manually exclude domains from its effects when we want to.

The current alternative is far worse - I'm being forced to *completely disable* https-everywhere just so I can use a single site.

**Comment by jeifour** [comment]
Well in this case you only need to disable a single rule, which is easy enough. It'd probably a bit nicer to be able to only disable this rule for a given website, but I think the current situation is actually quite manage-able.

**Comment by vith** [comment]
Still broken.

**Comment by strout** [comment]
Also seeing this with steamcommunity.com (streams found under http://steamcommunity.com/?subsection=broadcasts ). The extension forces a downgrade to HTTP but the video can only be streamed over HTTPS.
