### ISSUE TITLE
NLNet Labs

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2327]
https://nlnetlabs.nl/ does not use CAcert anymore, so the CAcert 'flag' can be removed.

**Comment by reedy** [comment]
src/chrome/content/rules/NLnet-Labs-cacert.xml needs folding into src/chrome/content/rules/NLnet-Labs.xml

**Comment by rugk** [comment]
@J0WI 
Did you already created a pull request? I only see your commit.

**Comment by J0WI** [comment]
See #2367
