### ISSUE TITLE
Libre Office Templates & Extensions sites issues

### ISSUE THREAD

**Issue by GeorgeChalkitis** [EFForg/https-everywhere#2335]
Libre Office Templates ( https://templates.libreoffice.org/ ) and Extensions ( https://extensions.libreoffice.org/  ) Sites have issues with Https. After loading unsafe scripts, Https is disabled and the pages work.
![2015-07-28 10 55 57](https://cloud.githubusercontent.com/assets/5755827/8926296/4cbea0bc-3517-11e5-94d8-2bef6fa4cb82.png)
![2015-07-28 10 56 16](https://cloud.githubusercontent.com/assets/5755827/8926297/4cbf7ed8-3517-11e5-9e69-dd5f36b36baa.png)

**Comment by quilloss** [comment]
Another Libre Office site with issues.
https://ask.libreoffice.org/ -> no reply.
http://ask.libreoffice.org/ -> works.
