### ISSUE TITLE
RTE webplayer adblocking statement?

### ISSUE THREAD

**Issue by almightymat** [EFForg/https-everywhere#2341]
Hi all,

Irish broadcaster RTE has an issue with https everywhere on their webplayer - it's treating it like an adblocker:

http://www.rte.ie/rnag/an-taobh-tuathail/programmes/2014/0109/496669-an-taobh-tuathail-thursday-9-january-2014/?clipid=1390443

Is there a way around this that doesn't involve disabling the Firefox plugin for the duration of a program?

Thanks!

**Comment by MDawg957** [comment]
I was able to get it to work by disabling these rules:

YouTube
ScorecardResearch.com
2mdn.net
Conviva (partial)

Re-enabling any of them would reproduce the message every time, but it's a better option than disabling the add-on like you have been.

**Comment by gloomy-ghost** [comment]
www.rte.ie has moved to https, and I can't reproduce the issue with https everywhere enabled.
