### ISSUE TITLE
Insecure ad image loading on statcounter.com

### ISSUE THREAD

**Issue by Ryan-Goldstein** [EFForg/https-everywhere#2352]
There is an iframe on the left side of the page when logged into statcounter.com - this is URL of the iframe: https://statcounter.com/frame/?side

It shows a "GAIN NEW CUSTOMERS!" ad: http://www.statcounter.com/images/advertise/gain-new-customers.png

The valid HTTPS version of that ad image is: https://statcounter.com/images/advertise/gain-new-customers.png (dropping the www).

The current version of the Chrome extension (2015.7.17) loads that insecure resource even with "Block all HTTP requests" enabled, turning the HTTPS Everywhere icon red.

**Comment by semenko** [comment]
Can't repro in latest version -- network inspector shows blocked request.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
