### ISSUE TITLE
League of Legends bilgewater event site broken

### ISSUE THREAD

**Issue by Diazonium** [EFForg/https-everywhere#2354]
Problematic site:http://eune.leagueoflegends.com/en/site/bilgewater/#brochure-2

console log:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/27279201-3cd9-4945-9cef-7af110543647.woff. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/js/files.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/27279201-3cd9-4945-9cef-7af110543647.woff. (Reason: CORS request failed). <unknown>
downloadable font: download failed (font-family: "beaufort" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source: http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/27279201-3cd9-4945-9cef-7af110543647.woff bilgewater:29:121
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/js/files.json. (Reason: CORS request failed). <unknown>
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] bg-bar.jpg
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] icon-game-lol.png
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] dropdown-trigger-blue.png
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] BeaufortforLOL-Regular.woff
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] BeaufortforLOL-Italic.woff
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/e029a83f-5e26-40b7-8cd8-274b1a73ed50.ttf. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/e029a83f-5e26-40b7-8cd8-274b1a73ed50.ttf. (Reason: CORS request failed). <unknown>
downloadable font: download failed (font-family: "beaufort" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/fonts/e029a83f-5e26-40b7-8cd8-274b1a73ed50.ttf bilgewater:29:121
Error: WebGL: getParameter: parameter: invalid enum value <enum 0x9246> html5player.js:1743:397
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-1/Bilgewater_web_audio_1_v2.ogg. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-2/Bilgewater_web_audio_2_v2.ogg. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-3/Bilgewater_web_audio_3_v2.ogg. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-1/Bilgewater_web_audio_1_v2.ogg. (Reason: CORS request failed). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-2/Bilgewater_web_audio_2_v2.ogg. (Reason: CORS request failed). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://lolstatic-a.akamaihd.net/site/bilgewater/e70e1ad99c9a02f580be10f7491f96a87428ba6d/audio/act-3/Bilgewater_web_audio_3_v2.ogg. (Reason: CORS request failed). <unknown>

**Comment by jeremyn** [comment]
This is related to #49. It works if you disable the `Akamai` ruleset.

**Comment by gloomy-ghost** [comment]
massive close per #15157
