### ISSUE TITLE
needs https forced http://cryptovpn.me/

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#2359]
http://cryptovpn.me/
should have https forced.

**Comment by terrorist96** [comment]
@J0WI thanks for issuing that commit. I have a list of other websites that need https forced. Would you prefer me to list them here or to create a separate issue for each? Please let me know.

Thanks!

**Comment by J0WI** [comment]
I would prefer pull requests ;)

**Comment by terrorist96** [comment]
Lol I'm not very qualified. I don't know how to test to see if they really *should* have https forced (without breaking anything). I'll list them here (some may not be valid anymore, this is an old list I've compiled):

ecointalk.net (embedded youtube video won't be displayed)
blackarrowsoftware.com
weminecryptos.com/forum [in dev channel]
cyberpowerpc.com
https://www.google.com/insidesearch/features/search/knowledge.html
craigslist.org (but have to use a subdomain [e.g. richmond] [in dev channel]
rossu.edu
https://leg1.state.va.us/
monoprice.com [in dev channel]
www.rs-components.com/index.html [most countries has https]
https://broadband.mpi-sws.org/
https://glossographia.wordpress.com/ [in dev channel]
https://www.adamvstheman.com/
sunlightfoundation.com
https://www.stopfasttrack.com/ and https://cms.fightforthefuture.org/stopfasttrack-email/ and fightforthefuture.org
https://ietf.org (redirects to datatracker.ietf.org/ though doesn't display that in the url)
openvpn.net (in dev channel)
https://www.subguns.com/
torrentfreak.com (in dev channel) but blocks embedded videos (https://torrentfreak.com/why-are-porn-perfomers-scared-to-talk-about-internet-piracy-140413/)
verizonwireless.com
https://blog.pushbullet.com/
falkvinge.net (in dev channel)
http://store.nike.com/us/en_us/product/free-tr-4-id/?piid=34980&pbid=111232352#?pbid=111232352 forward to https://secure-store.nike.com/us/en_us/product/free-tr-4-id/?piid=34980&pbid=111232352#?pbid=111232352 But breaks the customization flash element (in dev channel)
https://hstalks.com/
amazon.com
disqus.com
https://www.cardreaderfactory.com/
earthvpn.com (can't run speedtest on speedtest page)
budsgunshop (in dev channel; needs www prefix)
coinmarketcap.com
https://owncloud.org/ (in dev channel)
https://www.nationalgunrights.org/
deviantart.com
my.ebay.com
thepiratebay.se (in dev channel)
paranoidsecurity.nl
https://www.google.com/safebrowsing/report_phish/ (in dev [stable ff, but not chrome] channel)
https://winkdex.com/#/
wikileaks.org (in dev channel)
https://tox.im/ (in dev channel)
http://www.hackthissite.org/pages/index/index.php
mediafire.com
frozencpu.com (in dev channel)
kickass.to (in dev channel)
whatsapp.com
networkworld.com (in dev channel, youtube videos won't load if https)
hsbc.com and hsbc.co.uk
https://shadowserver.org/wiki/
gpgtools.org (in dev channel)
torrentprivacy.com
coinapult.com
sparklabs.com and secure.sparklabs.com
https://secure-computing.net/
lulubyleah.com
eyeboot.com
http://yify-torrents.com/ (in dev channel) and http://yts.im/ (doesn't work? not in dev channel) and http://yts.re/ (not in dev channel)
https://www.internetdefenseleague.org/
dragoninnovation.com
anonymox.net (in dev channel)
pock.io
http://webchat.oftc.net/
http://riskanalytics.com/
https://getkeepsafe.com/
coinex.pw
https://www.redstarpoker.com/
winpoker.com
livepokersupport.com
infinitipoker.com (secure.infinitipoker.com)
mibbit.com
dealmesupport.com
snort.org
jetblue.com
http://bter.com/ (in dev channel)
whymandesign.wordpress.com (in dev channel)
coinality.com
bitcoinity.org (in dev channel)
link-base.org
proxfree.com
gawminers.com
gmx.com
paygarden.com
forum.utorrent.com (in dev channel)
proxybig.net
shareblue.eu
asmbinfo.wordpress.com/wp-login.php (in dev channel)
proxpn.com
bro.org (in dev channel)
geti2p.net (in dev channel)
saf.org
dogechain.info
wi-fi.org (in dev channel)
coinb.in/multisig/
desk.com (in dev channel)
expresscoin.com
matthew5025.com
freedomboxfoundation.org
secure.vaguntraining.com
bayfiles.net
globevestor.com
pandora.com
solopool.net
shapeshift.io/
https://hedgy.co/
https://shadow.cash/
demonoid.pw
www.netzero.net
www.juno.com
https://www.iacr.org/
https://richmondmuralproject.wordpress.com/
https://www.cloudfogger.com/en/
https://www.okayfreedom.com/
https://chat.iptorrents.com/
https://bitreading.com/deltafeed/
https://www.ogicom.pl/
neovim.org
https://codecombat.com/
https://www.yodlee.com/
opencryptoaudit.org
https://www.hdme.eu
https://www.swisswineimports.com/
empirehost.me
https://teespring.com/

**Comment by J0WI** [comment]
Please double check those domains, some of them already have rulesets.
You may open separate bugs for each host if not.

**Comment by J0WI** [comment]
you should read https://www.eff.org/https-everywhere/rulesets and https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
It's very easy to write a simple ruleset.

**Comment by terrorist96** [comment]
I'll go through and edit the list to include only those that don't have any rules in the stable or dev branches. I don't really have the time to code rulesets for all of these; I was hoping the main contributors would take on the task.

**Comment by terrorist96** [comment]
The ones at the bottom have been checked. I'll keep working my way up.
