### ISSUE TITLE
Fontawesome icons blocked on laptopmag.com

### ISSUE THREAD

**Issue by iripu** [EFForg/https-everywhere#2425]
The fontawesome icons on http://www.laptopmag.com/reviews/laptops/sony-vaio-pro-11-ultrabook are not showing. I disabled the addon v5.0.7, then it showed them correctly. I use Firefox developer version 37 with windows 8.1 64bit.

**Comment by semenko** [comment]
seems fixed by referenced issue -- I see magnifying glasses, etc.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
