### ISSUE TITLE
Ability to select/de-select more than one site before refreshing

### ISSUE THREAD

**Issue by dfc** [EFForg/https-everywhere#2426]
I apologize if this is a duplicate. I have to think it is but I could not find it here or at the torproject tracker. 

It would be nice if you could turn on/off more than one rule at a time. Https everywhere and noscript have similar drop down menus with multiple on/off switches. With noscript it is possible to flip more than one rule off/on before the page refreshes. With https everywhere when I disable Site-X I have to wait for the page to refresh before I can disable Site-Y.

For what its worth this is only relevant for me in iceweasel/firefox, I have no idea about chromium.

**Comment by vgturtle127** [comment]
:+1: 

Really want this to be integrated!

@fuglede @jsha
