### ISSUE TITLE
Why https-everywhere needs a connection to NephoScale Inc. even if SSL Observatory was deactivated?

### ISSUE THREAD

**Issue by CHEF-KOCH** [EFForg/https-everywhere#2428]
https-everywhere version: 5.0.7
Firefox 39.x + FF mobile 39 version
SSL Observatory completely disabled 
Example IP: [69.50.225.155](https://www.virustotal.com/en/ip-address/69.50.225.155/information/)
Country: US, NephoScale Inc.
I guess that comes from the custom proxy or observatory.testing entry but disabling the Observatory also should deactivate this too.

Szenario:
Restart the browser, after disabling the Observatory and see that <code>randomip-nephodns.com</code> wants to send some kB, but I don't want or like such behavior, especially on Android with non unlimited data plans because I want as less as possible bandwidth consumption.

**Comment by reedy** [comment]
I don't think this is the fault of HTTPSE, or even anything to do with it

Grepping for nephodns finds nothing in the sources, in the core HTTPSE or any of it's submodules

Googling randomip-nephodns.com finds only this ticket. http://www.nephodns.com/


http://www.nephodns.com/ itself looks dodgy enough. It looks a lot like your phone is possibly infected with some ad/spyware or similar. If it was an EFF affiliation, it would be advertised as such.

**Comment by jsha** [comment]
NephoScale is actually EFF's hosting provider, and 69.50.225.155 is www.eff.org. The extension is expected to periodically contact www.eff.org to check for updates.

**Comment by CHEF-KOCH** [comment]
Thanks for the confirmation, can you integrate an option to disable the internal update mechanism via about:config? Because as I said I want as less as possible bandwidth consultation. And the normal update mechanism to update the addon(s) itself can be handled by the FF internal updater (which can be controlled).

So an option would be nice that every connection is shutdown if the observatory is disabled because I do not want this for several reasons.

**Comment by jsha** [comment]
Do you have add-on updates disabled in Firefox? If so, I'm not sure what causes the connection to www.eff.org. If you can confirm this happens with add-on updates disabled, I'll reopen the ticket and take a look.

**Comment by CHEF-KOCH** [comment]
Thanks for looking into this. Yes, the internal update mechanism was disabled, since I'm using the addons-updater addon (set to 48 hours, so that FF never checks on each start or during the session useless for updates).
