### ISSUE TITLE
BROKEN RULESET (Scene7)

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#2430]
https://www.verizonwireless.com/wcms/consumer/products/verizon-messages.html

Scene7 breaks video at bottom.

**Comment by terrorist96** [comment]
You have to be logged in to see this, but I assure you, Scene7 breaks the video.

**Comment by terrorist96** [comment]
Can this be merged?
@fuglede

**Comment by terrorist96** [comment]
Verizon Wireless along with Scene7 are now breaking the video here:
https://www.verizonwireless.com/wcms/myverizon/smart-rewards.html

No login required to reproduce the issue. And I doubt a default=off rule for verizonwireless.com is going to be merged. Other than that, I don't know how to fix this...

**Comment by fuglede** [comment]
Thanks for the fix. You mean [this video](https://www.verizonwireless.com/wcms/overlays/tips-video.html), right? If so, then you're right that there's no reason to turn off the entire ruleset. In my testing, adding a

    <exclusion pattern="http://s7mbrstream\.scene7\.com/" />

to <code>Scene7.xml</code> does the job.

**Comment by terrorist96** [comment]
Thanks, I made a PR with that code:
https://github.com/EFForg/https-everywhere/pull/3177

**Comment by fuglede** [comment]
Thanks, I'll comment there. Maybe I should add for the record that I didn't pull that exclusion pattern out of the air: if you open the browser console (F12 in Firefox) with the broken ruleset active, then you'll see a bunch of errors relating to s7mbrstream.scene7.com when loading the video.

**Comment by terrorist96** [comment]
@fuglede With the new version out, the videos on these pages still don't load. Verizon Wireless and Scene7 have to be disabled, and only then will they load.
https://www.verizonwireless.com/wcms/consumer/products/verizon-messages.html
https://www.verizonwireless.com/wcms/myverizon/smart-rewards.html

**Comment by fuglede** [comment]
Thanks for the update; is there any pattern of problematic pages or is it just those two?

**Comment by terrorist96** [comment]
Not sure. Those are the two that I know of. I haven't found anything else that is broken, but that doesn't mean they don't exist. :)

**Comment by semenko** [comment]
Fixed in #3630
