### ISSUE TITLE
Firefox extension does not work if installed globally

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#246]
The Firefox extension does not work if it is installed in Firefox's extensions directory (the so-called "global installation", scenario two in [this document](//mike.kaply.com/2012/02/09/integrating-add-ons-into-firefox/)). I have verified this bug with HTTPS Everywhere 3.5 installed on Mozilla Firefox 24.4 ESR running on Windows 7 Enterprise 64-bit SP1.

After some research, I have determined the cause to be hardcoding of `rulesets.sqlite`'s location. Specifically, [src/chrome/content/code/HTTPSRules.js](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/code/HTTPSRules.js) (line 372 at the moment) hardcodes its location as paths `["extensions", "https-everywhere@eff.org", "defaults", "rulesets.sqlite"]` from the profile directory (`"ProfD"`) which is not always the case.

P.S. In case you are wondering about the exact way I used to install the extension, I unzipped `https-everywhere-3.5.xpi` to the `C:\Program Files (x86)\Mozilla Firefox\browser\extensions\https-everywhere@eff.org` folder.

**Comment by jsha** [comment]
For other people trying to do the same thing: The id of this extension has changed. It is now `https-everywhere-eff@eff.org`. Sorry for any breakage this caused. We had to change the id to comply with Mozilla's new requirements in #2051.
