### ISSUE TITLE
Harley-davidson.com shop for parts all the pictures are blocked

### ISSUE THREAD

**Issue by alaricd** [EFForg/https-everywhere#2463]
No doubt this is a rule, but I can't tell what is breaking.  I do know that it is HTTPS Everywhere that is breaking the flash content on this site.  It would be nice to be able to have a screen that would show which connections where re-written so troubleshooting could be done, and rules edited.

**Comment by MDawg957** [comment]
Can you give a specific link where this is happening?  I've spot-checked the site using the following and everything is loading for me.

http://www.harley-davidson.com/shop/motorcycle-parts-accessories
http://www.harley-davidson.com/shop/motorcycle-gauges
http://www.harley-davidson.com/shop/motorcycle-security

**Comment by alaricd** [comment]
So this is a URL to test.

http://www.harley-davidson.com/store/1-piece-detach-tall-passenger-upright

I am running a fresh install of Firefox 39.0, with the ONLY extension being HTTPSEverywhere.

**Comment by alaricd** [comment]
![missingimage](https://cloud.githubusercontent.com/assets/7239618/9114271/8de1096e-3c1e-11e5-858b-32db2f786ed8.png)

**Comment by MDawg957** [comment]
I see it now.  You can disable the rule for Scene7 for the time being to allow the images to load properly.

**Comment by alaricd** [comment]
Thanks, I see what I was looking for now too, I just wasn't seeing it before.
