### ISSUE TITLE
Deadline.com not loading some content

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2465]
https://deadline.com/2015/08/jon-stewart-arbys-thank-your-ad-video-1201492738/

Deadline.com (partial) is causing some video content to not load.

**Comment by semenko** [comment]
Still broken in current version.

**Comment by MDawg957** [comment]
Still broken with HTTPSE 5.2.6 on Firefox ESR 45.4.0

Images aren't all loading when testing out the following:

https://deadline.com/2016/10/weaveworld-josh-stolberg-write-cw-adaptation-clive-barker-book-1201841176/

Turned off Deadline.com (partial) and swapped to to the http version and everything loads fine.

**Comment by bardiharborow** [comment]
This issue has been resolved. The domain has other mixed content issues, but they mostly affect ad tracking domains and a few webfonts, so I'm not sure if it's worth touching.

**Comment by MDawg957** [comment]
Confirmed.  Closing this issue.
