### ISSUE TITLE
Firefox 42 now requires signed extension, blocks HTTPS Everywhere on upgrade

### ISSUE THREAD

**Issue by shuhaowu** [EFForg/https-everywhere#2467]
HTTPS everywhere is getting automatically disabled now with Firefox nightly. See https://wiki.mozilla.org/Addons/Extension_Signing for details.

I understand the review process for Firefox addons is not great, but is there something the EFF can do with Mozilla?

**Comment by Rudloff** [comment]
The workaround is to set ```xpinstall.signatures.required``` to false (but this is clearly not optimal).

**Comment by numismatika** [comment]
I would say this duplicates #2051

**Comment by jsha** [comment]
Agreed. Closing as duplicate of #2051, thanks.
