### ISSUE TITLE
plug.dj

### ISSUE THREAD

**Issue by F1L1P** [EFForg/https-everywhere#2468]
This add-on is causing incorrect functionality of the site plug.dj

**Comment by MDawg957** [comment]
What is breaking on the site? I was playing around with it in Firefox and saw no issues.

**Comment by F1L1P** [comment]
It is not showing video and dolls if the add-on is enabled

**Comment by fuglede** [comment]
Is there any page in particular that is problematic? I also can't see any difference on the front page or on the music player. Indeed, the site appears to serve a 301 redirect to its https version if one tries to load it over http.

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
