### ISSUE TITLE
Fox News (partial) breaks some images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#2472]
http://www.foxnews.com/us/2015/08/03/navy-official-not-ruling-out-charging-service-member-who-fired-on-chattanooga/

Fox News (Partial) breaks images in "Bank Rates" section.

**Comment by terrorist96** [comment]
I don't want to change this to `default_off="breaks site"` because it's a minor part of the site that's broken. I don't know what to do to fix it other than `default_off="breaks site"`

**Comment by semenko** [comment]
Discussed in another bug, I think fox news was overhauled and seems to generally work now.
