### ISSUE TITLE
Active HTTPS-Everywhere rule "Spiegel" prevents loading of SPIEGEL Online (www.spiegel.de) Silder

### ISSUE THREAD

**Issue by Herr-Sepp** [EFForg/https-everywhere#2477]
Some article from Spiegel Online use Silders that will not load when the HTTPS Everywhere (HE) rule "Spiegel" is active.

**System information**

I noticed the problem under these circumstances:

Page/s where the problem is present: http://www.spiegel.de/
Chrome: Https Everwhere 2015.07.17
Example: http://www.spiegel.de/netzwelt/games/spielemesse-gamescom-was-gamer-hassen-a-1047143.html

**Quick fix**

Deactivation of the rule for "Spiegel" helps and the Silders can then be loaded and shown as expected.

**Full Fix**
(Not tested)

Slider Source:
http://www.spiegel.de/static/happ/_pattern/slider/rs/v1/pub/index.html

```
<!-- exclude static/happ/_pattern to make slider work properly -->

<exclusion pattern="^http://www\.spiegel\.de/static/Happ/_pattern/" />
```

**Comment by jsha** [comment]
I wasn't able to find a slider on the page you linked. Can you provide more detail.

I tried loading the page with the latest HTTPS Everywhere and didn't get any mixed content errors.

**Comment by MDawg957** [comment]
It's not a slider, but a slideshow.  On the referenced page there should be one, but the Spiegel.de (partial) rule hides it.  Disabling that has it appear properly.

**Comment by numismatika** [comment]
I can browse through the article and pictures with no errors @MDawg957 , is that still a problem anywhere else on that page?

**Comment by MDawg957** [comment]
@numismatika Looks good on my end.  Slideshow functioning without issues.

**Comment by DavidLiedke** [comment]
@J0WI | @Bisaloo the problem doesn´t exist anymore. 

Tested with Firefox & Chrome and HTTPS Everywhere 2018.1.29
