### ISSUE TITLE
Enable/Disable rules

### ISSUE THREAD

**Issue by FakeFBI** [EFForg/https-everywhere#2493]
I can't open Enable/Disable rules in HttpsEverywhere. Can you fix it at 5.0.8 ?

On windows : http://i.hizliresim.com/OZ7QR5.gif

**Comment by fuglede** [comment]
You can enable/disable rules by clicking on the relevant labels from the dropdown menu. The popup menu was removed on purpose in #2121; see that PR for details more details.

**Comment by jsha** [comment]
Thanks @fuglede! Closing as duplicate of https://github.com/EFForg/https-everywhere/issues/1683
