### ISSUE TITLE
Adtech.de

### ISSUE THREAD

**Issue by jcosentino** [EFForg/https-everywhere#2500]
Breaks videos:
http://www.hs.fi/kaupunki/a1439084786918

**Comment by gitarra** [comment]
Can someone fix this? Video playback is broken on the website of the biggest Finnish newspaper.

**Comment by numismatika** [comment]
To get more of the requests on this site switched to TLS i created #9078 , #9080 , #9081 & #9082
So far i haven't seen a video play yet on this website.
Maybe a few other samples could help.
Adtech itself seems to be part of some kind of adblocker check or so, name of the file failing suggests that.

**Comment by bardiharborow** [comment]
The URL provided seems to have a video, but it doesn't work even over HTTP without rewriting. https://www.hs.fi/kaupunki/art-2000005407933.html has a video which works with HTTPS-Everywhere, and I think this issue has been resolved.

**Comment by Bisaloo** [comment]
Thank you for testing @bardiharborow.

Another test url: https://www.hs.fi/kulttuuri/art-2000005624204.html

This was likely as CORS that is now fixed since `http://www.hs.fi` 301 redirect to HTTPS. Closing. Feel free to reopen if you have further issues.
