### ISSUE TITLE
Support Python 3 in test.sh

### ISSUE THREAD

**Issue by l0b0** [EFForg/https-everywhere#2502]
I'm not able to run tests on the master branch:

    $ bash test.sh
    dirname: missing operand
    Try 'dirname --help' for more information.
    Validation of included rulesets completed.

    Validation of rulesets against relaxng.xml succeeded.
    Validation of included locales completed.
    Total included rules: 16728
    Rules disabled by default: 4906
    Created pkg/https-everywhere-5.0.7~c562f8c-dirty.xpi and pkg/https-everywhere-5.0.7~c562f8c-dirty-amo.xpi
    ~/dev/https-everywhere/addon-sdk ~/dev/https-everywhere
    Error: You appear to be using Python 3, but the Add-on SDK only supports the Python 2.x line.
    ~/dev/https-everywhere
    ~/dev/https-everywhere/https-everywhere-tests ~/dev/https-everywhere
    running tests
    Traceback (most recent call last):
      File "/home/user/dev/https-everywhere/addon-sdk/bin/cfx", line 30, in <module>
        import cuddlefish
      File "/home/user/dev/https-everywhere/addon-sdk/python-lib/cuddlefish/__init__.py", line 381
        except SystemExit, e:
                         ^
    SyntaxError: invalid syntax
    ~/dev/https-everywhere
    Traceback (most recent call last):
      File "https-everywhere-checker/src/https_everywhere_checker/check_rules.py", line 21, in <module>
        import http_client
      File "/home/user/dev/https-everywhere/https-everywhere-checker/src/https_everywhere_checker/http_client.py", line 7, in <module>
        import regex
    ImportError: No module named regex
    Ruleset test coverage was insufficient.

    Under the new ruleset testing rules (February 2015), any modified ruleset
    must have sufficient test coverage. You can often improve test coverage by
    adding <test url='...' /> tags, or by restructuring the rule to avoid
    wildcard <target> tags. See these documents:
    https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md
    https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
    To reproduce this build (https://wiki.debian.org/ReproducibleBuilds), please use this version of sqlite3:
    3.8.11.1 2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f
    Git commit c562f8c8846a76969a92f6b586a215e9a4bba6d3
    SHA256(pkg/https-everywhere-5.0.7~c562f8c-dirty-amo.xpi)= 53518dfebce34fbafd204c15f16a06212d25dededf1d5442b7722abcedabd1f5

If there's an option to force the use of Python 2, it's not obvious.

    $ which python2
    /usr/bin/python2
    $ which python
    /usr/bin/python

**Comment by jsha** [comment]
This looks like a bug in the Firefox addon SDK (https://developer.mozilla.org/en-US/Add-ons/SDK). They are pretty up front about not supporting Python 3, but they should be able to find Python 2 if it's installed. Could you file an issue against that project?

HTTPS Everywhere is in a similar spot: We don't support Python 3, but we generally try to call python2.7 explicitly (and consider it a bug if we don't).

**Comment by semenko** [comment]
Going to close this as a wontfix, since this issue is in the Addon SDK's Python selection.
