### ISSUE TITLE
Limelight Networks and yimg.com

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2513]
These break some video play:
http://sports.yahoo.com/blogs/mlb-big-league-stew/blue-jays-sweep-yankees-for-eighth-straight-win--will-never-lose-again-033533120.html

**Comment by tancrackers** [comment]
Another example:
http://news.yahoo.com/obama-visit-orleans-10th-anniversary-hurricane-151414975--politics.html#

Limelight Networks caused problems streaming Yahoo News videos

**Comment by semenko** [comment]
Currently those videos play for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
