### ISSUE TITLE
Imgur.com rule issue

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2527]
http://www.bleedingcool.com/2015/08/11/what-if-spider-man-had-grown-up-in-smallville/

Animated footage will not display until until the Imgur.com rule is disabled.

**Comment by donced** [comment]
The site embeds flash version of the animated footage. I don't think this issue would arise if the site simply embeds https://i.imgur.com/JxTUJqL.gif or https://i.imgur.com/JxTUJqL.gifv (or even the original source https://www.youtube.com/watch?v=sLQJjKtV2do)

**Comment by MDawg957** [comment]
Wouldn't it be possible to add an exemption (or some sort of parity matching) for the flash converter Imgur is using?

https://s.imgur.com/include/flash/gifplayer.swf?imgur_video=http://i.imgur.com/JxTUJqL.mp4&imgur_width=718&imgur_height=404&imgur_url= seems to fail cause s.imgur.com is https while imgur.com is http.

**Comment by semenko** [comment]
Seems to work for me (fixed by imgur / us?). Closing.

**Comment by MDawg957** [comment]
Still able to re-create this issue as mentioned originally.
