### ISSUE TITLE
Enable / Disable rules menu not working in Firefox 40

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2528]
Firefox 40.0
Https-everywhere 5.0.7
Arch Linux with KDE

The menu does not pop up to enable / disable rulesets.

**Comment by jsha** [comment]
The new way to enable / disable rulesets is by clicking their respective elements in the icon dropdown menu. The vestigial "Enable / disable rulesets" text is just to indicate what the items below it do. It will be marked as disabled in the upcoming release to reduce confusion. See #1683 for more details.

Also note that you can find all existing rulesets via https://www.eff.org/https-everywhere/atlas/.
