### ISSUE TITLE
Can't be installed or run on Firefox 41

### ISSUE THREAD

**Issue by Nick-Payne** [EFForg/https-everywhere#2540]
Latest Firefox beta (41.0b1) refuses to install (or run already installed) unsigned extensions. Firefox 40 warned about unsigned extensions but one could allow them to run. FF 41 won't run them full stop. This means that neither https-everywhere nor privacy badger will run in this (or presumably any future) version of Firefox. The extensions need to be signed by Mozilla to be of any use going forward. See https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox. 

Latest Firefox can be downloaded here: https://www.mozilla.org/en-US/firefox/beta/all/

![ff41ext](https://cloud.githubusercontent.com/assets/3879090/9237032/df3ece14-418b-11e5-8ad9-cf35c853bdeb.png)

**Comment by jsha** [comment]
Thanks for reporting! We're working on it: #2051.
