### ISSUE TITLE
newjobs.com rule breaks images on monster.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2545]
If you go here http://stellenanzeige.monster.de/IT-SECURITY-EXPERTE-W-M-F%C3%9CR-UNSER-IT-SICHERHEITSLABOR-F%C3%9CR-DIE-INDUSTRIELLE-PRODUKTION-Job-Karlsruhe-Ettlingen-Baden-W%C3%BCrttemberg-Deutschland-154232985.aspx?jobPosition=2
some images fail to load due to the newjobs.com rule.

Disabling the rule works as a workaround.

**Comment by J0WI** [comment]
Fixed in 69a0f36

**Comment by KommX** [comment]
The mentioned commit is not yet part of a released version, right?

**Comment by J0WI** [comment]
Nope, but it will likely be in 5.0.8
