### ISSUE TITLE
monster.de rule breaks site

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2546]
Just go to http://www.monster.de/ and activate and deactivate the rule "Monster (partial)" to see the difference.

**Comment by J0WI** [comment]
This seems to be fixed in https://github.com/EFForg/https-everywhere/commit/69a0f368f326fc711f143e047ca6ec802bd57640

**Comment by KommX** [comment]
I think your mentioned commit could fix #2545 but not this issue.

**Comment by J0WI** [comment]
Can you specify what the issue here is?

**Comment by KommX** [comment]
Many images don't load.

![monster](https://cloud.githubusercontent.com/assets/7859245/9248228/4779f782-41ba-11e5-9cf3-0b1f7ac964e0.png)

**Comment by KommX** [comment]
Seems to be fixed.
