### ISSUE TITLE
Checked-in merge conflict

### ISSUE THREAD

**Issue by InPermutation** [EFForg/https-everywhere#2551]
It's in an XML comment, so it probably doesn't affect anything: 
https://github.com/EFForg/https-everywhere/blob/b5a1d86f98d98decc6f1d1303330aad9c4640c6f/src/chrome/content/rules/Stack-Exchange.xml#L12

**Comment by jsha** [comment]
Thanks for spotting! Will fix.

**Comment by jsha** [comment]
Fixed.
