### ISSUE TITLE
HTTPS Everywhere 5.0.8 isn't loaded in non-English Firefox

### ISSUE THREAD

**Issue by d4k0** [EFForg/https-everywhere#2553]
I just updated HTTPS Everywhere to version 5.0.8 and now it isn't loaded anymore (the icon also doesn't appear). When I go to the add-ons menu and click the "Options" button on the HTTPS Everywhere site, this error message appears (it also appears when starting Firefox):

![Error message](https://i.imgur.com/FMp6zKJ.png)

It says:

> XML processing error: Not defined entity
> Address: chrome://https-everywhere/content/observatory-preferences.xul
> Line 6, column 1:
>
> <dialog id="https-everywhere-prefs"
> ^

I then tried a new profile using a portable version of Firefox 40 and it also didn't work there. After that I tried the portable version of Firefox 40 in English (I'm usually using the German version of Firefox as can be seen on the screenshot) and it now worked without a problem. I haven't tested if other languages are also affected. I'm using Firefox 40 and Windows 8.1 x64.

**Comment by jsha** [comment]
Sorry about this! It should be fixed in 5.0.9, which I just released.

**Comment by Mikaela** [comment]
I have the same issue with version just installed from addons.mozilla.org (I finally used the unsigned extension workaround). When will the fixed version appear there?

**Comment by jsha** [comment]
Thanks for pointing that out. I forgot to upload the updated version to AMO. I've updated it now.

**Comment by Freso** [comment]
I have this issue in Firefox 5.1.9.

**Comment by lsdamsgaard** [comment]
I also have this issue.
Linux Mint 17.3 Cinnamon 64bit.
Firefox 47.0 for Linux Mint -1.0
