### ISSUE TITLE
Can not see main icon

### ISSUE THREAD

**Issue by 0rovan** [EFForg/https-everywhere#2554]
Main icon to open pop-up menu has gone missing after upgrade to 5.0.8.
Opening HTTPS-everywhere preferences from Firefox Add-ons Page opens window shown in attached image. Rollback to 5.0.7 return HTTPS-everywhere icon back to Firefox Customize Page.

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0

![https-everywhere_my_bug](https://cloud.githubusercontent.com/assets/12017207/9264096/8601f742-421a-11e5-83a2-c647c298aa2d.png)

**Comment by d4k0** [comment]
I have the same problem which I reported here:

https://github.com/EFForg/https-everywhere/issues/2553

However, for me this only occured when using the German version of Firefox 40 (maybe other languages are also affected), the English version somehow worked (on my system) without a problem. So there definitely seems to be some problem with the new version.

**Comment by 0rovan** [comment]
I have checked previous issues and before I wrote mine, yours wasn't submitted - it just took me bit longer to write it - I find this really funny.
Anyway, I am using English (British) version

**Comment by jsha** [comment]
Alright, I think I see the problem. Fix coming soon!

**Comment by jsha** [comment]
Just released 5.0.9, which should fix this. Sorry!

**Comment by jsha** [comment]
Just released 5.0.9, which should fix this. Sorry!
