### ISSUE TITLE
techsupportalert.com rule breaks site

### ISSUE THREAD

**Issue by paulderdash** [EFForg/https-everywhere#2558]
I cannot disable rule techsupportalert.com. Only if I disable HTTPS Everywhere completely can I view this site.
Also: how do I apply 'ruleset-bug' label?

**Comment by fuglede** [comment]
Which browser are you using? The rule is marked as broken on those that block mixed content, which in practice means that it is off by default on up-to-date Firefox and Chrome. Exceptions are if you have changed the values of <code>security.mixed_content.block_active_content</code> or <code>extensions.https_everywhere.enable_mixed_rulesets</code> in about:config.

**Comment by paulderdash** [comment]
To be honest I am confused.
I am using FF40.0.2. Both about:config settings mentioned are at their
defaults: True and False respectively.
If I navigate to 'techsupportalert.com' it defaults to the https version
and doesn't display correctly. (If I disable HTTPS-E completely and
navigate to the same site, it goes to the http version and displays
correctly).
With HTTPS-E enabled I see the following rules:
Techsupportalert.com (enabled)
BootstrapCDN.com (partial)
JQuery.com (partial)
Techsupportalert (disabled)
If I try to disable Techsupportalert.com, nothing happens - it stays
enabled.
It could be another add-on, or security software, that is interfering with
this? I tried removing techsupportalert.com from NoScript whitelist but it
made no difference.
I tried HTTPS-E in a new profile, but I see a completely different bunch of
rules when navigating to the same site, and no 'Techsupportalert.com' ...

**Comment by fuglede** [comment]
The not being able to disable the rule sounds strange. Did you at some point use custom rulesets for the site? Those have been causing issues for a while  (cf. #932). Also, perhaps you can check if the value of <code>extensions.https_everywhere.rule_toggle.Techsupportalert</code> matches of the plugin dropdown menu; the setting should change on the fly as you toggle the ruleset.

For comparison, here's what the site looks like in a clean profile with its default settings here (as obtained via <code>test.sh --justrun</code>)
![tilgithub](https://cloud.githubusercontent.com/assets/6169306/9288676/07394fa2-4353-11e5-9eb3-c0c573340221.png)

**Comment by paulderdash** [comment]
Stranger and stranger.

I did in the past use HTTPS Finder extension, and created some rules, also
modified rules; but I have disabled this for a while now. And I have since
repeatedly reset rules to defaults, also removing and re-adding HTTPS
EveryWhere (now 5.0.9).

Below is what I see on my normal profile (normal.jpg; note https) - and I
do not have that rule in about:config, only two for Adobe and BBC
(rules.jpg)!

On a clean profile I see clean.jpg - and no rules in about:config
(rules2.jpg) !!

So I am very confused! Or I am doing something wrong, not understanding
something :)

Hope you can get me to fix this somehow!

Paul

**Comment by fuglede** [comment]
I think something went wrong in your mail; the pictures don't show up here. Perhaps you can edit them in on GH?

So, this depends a bit on what clean.jpg looks like, but if you have created the rules with HTTPS Finder, they should stay even after you disable that. Also, if you delete the actual rules it creates, those might also stay in the database. In the first case, you can check in <code>~/.mozilla/firefox/XXXX.default/HTTPSEverywhereUserRules</code> for residues. If you know that you once had a rule for this site which might have snuck into the database, you may want to delete that one and grab a fresh version. The easiest way to do that would be to remove HTTPS-E, delete whatever might be left in <code>/.mozilla/firefox/XXXX.default/extensions/https-everywhere@eff.org</code>, and install HTTPS-E anew.

**Comment by paulderdash** [comment]
Hi fuglede - have edited in the pictures ... can you see them?
I will try your solution later after you respond?

**Comment by fuglede** [comment]
Yep, thanks! Try it out the solution above. HTTPS-E doesn't have a rule called "Techsupportalert.com" (only without the .com), so that probably stems from HTTPS-Finder.

**Comment by paulderdash** [comment]
Hi fuglede - have edited in the pictures ... can you see them?
I will try your solution later after you respond?

**Comment by paulderdash** [comment]
Deleted the HTTPSEverywhereUserRules (plenty remnants there), removed HTTPS-E, which also removed /.mozilla/firefox/XXXX.default/extensions/https-everywhere@eff.org - then readded HTTPS-E.
Voila - fixed! Now to similarly fix my other profiles ...
Thanks so much for sorting me out!

**Comment by fuglede** [comment]
You're welcome. I use HTTPS Finder to discover new sites as well, and #932 is a bit of an issue there. On the bright side, it's a good excuse to add those rulesets to HTTPS-E directly, rather than just store them locally.

**Comment by paulderdash** [comment]
I've stopped using HTTPS Finder add-on because someone commented that the rules it produces were not always accurate, and it is not maintained anymore, so I just want the HTTPS-E defaults now ... but it would be useful for those who have knowledge, to find, then add customized rulesets directly.
Thanks again.
