### ISSUE TITLE
www.lemonde.fr, map is not displayed

### ISSUE THREAD

**Issue by promeneur** [EFForg/https-everywhere#2559]
FF 39.0
https-everywhere 5.0.9

site www.lemonde.fr

graphical data are not displayed if https is activated
see
http://www.lemonde.fr/les-decodeurs/article/2015/08/13/pourquoi-la-biere-coute-t-elle-moins-cher-en-grece-qu-en-allemagne_4723541_4355770.html

you don't see the geographical chart

**Comment by fuglede** [comment]
Fixed by #2564.

**Comment by promeneur** [comment]
thanks
