### ISSUE TITLE
Polygon.com image loading issue

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2562]
https://www.polygon.com/2015/8/14/9153273/1989-batmobile-batman-arkham-knight

Images will not load due to a mixed-content notice.  Disabling Polygon.com and loading the HTTP version of the page works.

The problem seems to be that it's not picking up that the images are coming from Imgur.  That portion never loads in the HTTPS version of the page due to it being mixed content.

**Comment by fuglede** [comment]
Fixed by #2563.
