### ISSUE TITLE
Cannot use HTTPS Everywhere in Firefox 41 due to extension signing

### ISSUE THREAD

**Issue by blaise-io** [EFForg/https-everywhere#2571]
I just updated to Firefox 41b and it automatically disabled the HTTPS Everywhere addons because it's not digitally signed.

The reason for this can be found at https://wiki.mozilla.org/Addons/Extension_Signing

>    Firefox 40: Firefox warns about signatures but doesn't enforce them.
>    Firefox 41: Firefox will have a preference that allows signature enforcement to be disabled (xpinstall.signatures.required in about:config).
>    Firefox 42: Release and Beta versions of Firefox will not allow unsigned extensions to be installed, with no override.

So in Firefox 41, I could work around it by setting `xpinstall.signatures.required` to `false` in `about:config` but I rather don't do that because that I will be vulnerable to malicious unsigned addons, and it will cease to work in Firefox 42.

Is there a plan to sign the addon through addons.mozilla.org?

**Comment by alexmuller** [comment]
I'm having the same problem with version 41.0b1. When I try to install the addon I get this message:

![screen shot 2015-08-15 at 19 29 22](https://cloud.githubusercontent.com/assets/121219/9290275/fc0f618a-4383-11e5-86d0-710f702a8f5a.png)

**Comment by fuglede** [comment]
This is being worked on; see e.g. #2051.

**Comment by blaise-io** [comment]
@fuglede Thanks! I missed that one when searching. Closing this issue.
