### ISSUE TITLE
Videos don't play on sportschau.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2577]
The rule "Westdeutscher Rundfunk" includes the domain sportschau.de

Unfortunately the embedded videos don't play if the site is redirected to https.
Test case:
https://www.sportschau.de/doping/geheimsache-doping-102.html

**Comment by numismatika** [comment]
They play for me, there is just a small note for mixed display content from
http://adaptiv.wdr.de
display content isn't blocked by default, just active.
Did you change that setting?

**Comment by KommX** [comment]
@numismatika 
I can reproduce the behavior you described with Chrome Version 44.0.2403.155 (64-bit) and HTTPS Everywhere 2015.8.13.
But with the dev Version 46.0.2478.0 dev (64-bit) I have the problem described in my initial post. Perhaps  Chrome changed something with respect to mixed content?!

**Comment by KommX** [comment]
The same (or at least related) issue exists for this site:
https://tv.sport1.de/player/player.php?id=s225420

It's fine with the stable version of Chrome and HTTPS Everywhere.
But with the dev version of Chrome the videos don't play.

Perhaps it's not yet an httpsE issue but maybe it will be in the future?!

**Comment by numismatika** [comment]
It might be that chrome dev is stepping up security and blocking passive mixed content now as well.
One would need to check for related possible changes there.
Right now it can't be fixed with a https-everywhere rule , because Akamai doesn't serve certificates that are valid for event02-lh.streaming.sport1.de

**Comment by KommX** [comment]
Now I have a test case with the current stable version of Chrome (Version 45.0.2454.99 (64-bit)):
1. Go to https://www.sportschau.de/fussball/bundesliga/videolewandowskieinfachtorgeschossen100.html
2. Try to get the video to play.

**Comment by numismatika** [comment]
``
Blocked loading mixed active content "http://www1.sportschau.de/sportschau_specials/mm_ticker/css/radiolivestream.css"

Blocked loading mixed active content "http://containerids.wdr.de/container.js?761708" ``

Clear case of https://bugzilla.mozilla.org/show_bug.cgi?id=878890

You could temporarily override the active content blocking for the site in firefox or less secure:
security.mixed_content.block_active_content = false in about:config.

**Comment by KommX** [comment]
The bug you mention is a Firefox bug. Does the same bug exist in Chrome?

**Comment by numismatika** [comment]
I think this was https://code.google.com/p/chromium/issues/detail?id=122548

**Comment by KommX** [comment]
Thank you for the link.
Since both bugs are very old and still open, I think updating the rule "Westdeutscher Rundfunk" would be the quickest fix for https everywhere users.

**Comment by numismatika** [comment]
i will check if we can fix videos without disabling the domain completely.
On related news, WDR told me that they are aware of this and other issues with encryption on their websites and are working on fixing them.

**Comment by KommX** [comment]
This bug is still present in Chrome version 2015.12.16

**Comment by numismatika** [comment]
Videos are loaded over a wdr akamai domain with a proper tls cert, is this isssue solved for you as well?

**Comment by KommX** [comment]
I think so.
But the old URLs aren't working anymore.

**Comment by DavidLiedke** [comment]
@J0WI can also be closed. No problems anymore.
