### ISSUE TITLE
Ruleset breaks Texas Instruments website

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#2580]
Sample page: https://www.ti.com/lsds/ti/amplifiers-linear/precision-amplifier-overview.page

Happens both with Firefox and Chrome. As soon as I revert to HTTP the page is rendered normally.

![screenshot from 2015-08-17 01 16 57](https://cloud.githubusercontent.com/assets/13108002/9295888/b8981af0-447d-11e5-883f-8ce00db2c6cc.png)

Thanks.

**Comment by semenko** [comment]
Remains broken in current version.

**Comment by lcafaro** [comment]
Sent a message to their UI/UX dept.

![2015-12-17-225122_397x283](https://cloud.githubusercontent.com/assets/13108002/11883081/c7666e94-a510-11e5-9291-3f8902bcb78d.png)

**Comment by lcafaro** [comment]
Just got a reply from Texas Instruments - they've identified the issue and they're discussing a fix.

**Comment by Bisaloo** [comment]
This website is still broken but that ruleset is now `default_off` so it should not be an issue for users.
