### ISSUE TITLE
Error when switching language on oslo.craigslist.org

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2581]
If you try to switch to any language on https://oslo.craigslist.org/ it will redirect you to https://oslo.en.craigslist.org/, which is apparently not covered by craigslist's SSL certificate and displays the "This Connection is Untrusted" warning page.

I wonder if this is an isolated error or if it also exists on other craigslist sites.

**Comment by fuglede** [comment]
It's not isolated: The same thing happens on https://losangeles.craigslist.org/

Moreover, the fourth level domains are not actually covered by https-e, so it's Craigslist itself serving the bad links.

**Comment by semenko** [comment]
Language switching works for me now. Maybe craigslist fixed this.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
