### ISSUE TITLE
Google.com Subdomains rule breaks opening Gmail in Firefox via URL shortcut

### ISSUE THREAD

**Issue by owoc** [EFForg/https-everywhere#2582]
Firefox 40.0.2 on Windows 10.

Reproducible on a fresh Firefox profile:
1. Install HTTPS Everywhere with default settings.
2. In Windows, create a shortcut (a .url file) to https://mail.google.com/
3. Launch Firefox via said shortcut (make sure it's not already running). The page will fail to load properly and will require a manual refresh.

Disabling the rule "Google.com subdomains" fixes the problem.

**Comment by jeremyn** [comment]
Thanks for the report. This works for me on Windows 10, Firefox 48.0.2, HTTPS Everywhere 5.2.3. Is this still a problem for you?

**Comment by pipboy96** [comment]
Legacy Firefox extension, closing.
