### ISSUE TITLE
ESPN streaming not working

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2587]
http://espn.go.com/watchespn/player/_/channel/espn1/

Unable to watch ESPN stream unless I disable Conviva (partial)

**Comment by Wolfeman0101** [comment]
This is still a problem.  I get an "internal authorization error" on WatchESPN or ESPN.

**Comment by jeremyn** [comment]
On Windows 10, Firefox 48.0.2, HTTPS Everywhere 5.2.3, I see a red circle with spinning color that doesn't go away. If I disable HTTPS Everywhere, then I get a screen that asks me to `Choose your Provider`. So, it still looks broken, but in a different way than @Wolfeman0101 described. Are either of you seeing that now?

**Comment by MDawg957** [comment]
@jeremyn With HTTPS 5.2.4 I still got the red circle, but disabling the Adobe.com rule got me to the Choose your provider option.  THe red circle still happened, so I turned off the Conviva (partial) rule and streaming works.

**Comment by jeremyn** [comment]
Thanks @MDawg957 .

**Comment by Bisaloo** [comment]
Probably related: #2125

**Comment by pipboy96** [comment]
Extremely old issue, can't verify by visiting the link.
