### ISSUE TITLE
US Senate (senate.gov) doesn't serve www subdomain on HTTPS

### ISSUE THREAD

**Issue by jaypl** [EFForg/https-everywhere#2596]
There is a comment already in 
https://github.com/EFForg/https-everywhere/blob/stable/src/chrome/content/rules/Senate.gov.xml
That mentions non-www.senate.gov won't serve over HTTPS and it appears neither will www.senate.gov (at least during some periods of time) since URLs such as:
https://www.senate.gov/
https://www.senate.gov/pagelayout/legislative/a_three_sections_with_teasers/votes.htm
Return a page advising only to use HTTP

> Request unable to be completed.
> The submitted https request was not able to be completed at this time.
> Please retry your request using http. This may require disabling some browser based plug-ins.

**Comment by anewuser** [comment]
"www" isn't the only problematic subdomain. See some more examples:

https://www.cruz.senate.gov/
https://scott.senate.gov/

**Comment by Bisaloo** [comment]
I think this issue is solved. `senate.gov` now redirects to https without HTTPSE. @J0WI, can you close it please?

**Comment by J0WI** [comment]
Not every subdomain redirects to https, but at least nothing is broken.
