### ISSUE TITLE
The "about" menu of https-everywhere-5.1.0.xpi display "version 5.0.9"

### ISSUE THREAD

**Issue by tdelmas** [EFForg/https-everywhere#2597]

**Comment by rugk** [comment]
I can confirm this. I've also installed the EFF version of HTTPSE and in the about-window it displays version 5.0.9. But in the add-ons manager it displays v 5.1.0 and no warning. So it's the correct new, signed version. (https://github.com/EFForg/https-everywhere/issues/2051)

**Comment by jsha** [comment]
Yes, this was a packaging error, thanks for pointing it out. The version number in the add-ons manager is correct, and the about page will be fixed in the next release.

**Comment by jsha** [comment]
Fixed.
