### ISSUE TITLE
merge-rulesets.py inserts spaces into rulesets incorrectly

### ISSUE THREAD

**Issue by fuzzyroddis** [EFForg/https-everywhere#2600]
I wrote this rule in Feb https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Mailinator.com.xml

However subdomain.mailinator.com never worked as intended for me and I always assumed I stuffed up.

I finally got around to checking what goes on and I need some help as I can't figure out what's causing the problem.

```xml
<rule from="^http://([\w-]+)\.mailinator\.com/"
			to="https://www.mailinator.com/inbox.jsp?to=$1" />
```

Test: http://bhjbgfbgfhf.mailinator.com
Chrome requests: https://www.mailinator.com/inbox.jsp?%20to=bhjbgfbgfhf

Note the *%20* so I downloaded the ruleset and examined it closely with a hex editor, there's nothing between ? and t

**Comment by fuzzyroddis** [comment]
Even weirder it works correctly on Firefox.

**Comment by jsha** [comment]
Even weirder, for me, it works correctly on Firefox, but on Chrome http://bhjbgfbgfhf.mailinator.com/ sends me to https://www.mailinator.com/.

**Comment by fuzzyroddis** [comment]
@jsha I have the same problem, if you open the web console you'll see HTTPS Everywhere on Chrome is redirecting to https://www.mailinator.com/inbox.jsp?%20to=bhjbgfbgfhf

**Comment by jsha** [comment]
Got it! It's these lines in the truly ugly `merge-rulesets.py`:

```
to_and_from_pattern = re.compile(r'\s*(to=|from=)')
rulefile = to_and_from_pattern.sub(r' \1', rulefile)
```

I remember looking at that code and thinking it would bite us someday, and now it has. Nice find @fuzzyroddis!

Nowadays for Firefox we actually parse the XML and then spit out a commentless and spaceless version into the sqlite DB using lxml. We should adapt make-sqlite.py to also output a concatenated ruleset file suitable for use in Chrome. In the long run we should also make Chrome use the same sqlite format, but that's a bigger change.
