### ISSUE TITLE
Alert user on global failures

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2613]
For instance, if the nsIHttpChannel.redirectTo API is missing, we log a scary warning to console. But we should actually open a window notifying the user, and show the disabled version of the toolbar icon.

We should do similar if there is any failure loading the initial ruleset DB, or if there are too few rulesets.

**Comment by vgturtle127** [comment]
:+1:

**Comment by pipboy96** [comment]
XPCOM is deprecated, but such feature should most likely be added to WebExtensions version at some point.
