### ISSUE TITLE
Icons for rules missing in context menu

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2618]
![httpse_iconsmissing](https://cloud.githubusercontent.com/assets/11966684/9388261/a6da9af6-4764-11e5-99f6-baf3f7388d13.png)

I think there should be tick/red reload icons or something like this.

FYI the activate/deactivate also looks different and probably this could be the reason (although the 'activate/deactivate' look is intended as I assume):
![httpse_iconsmissing2](https://cloud.githubusercontent.com/assets/11966684/9388431/9d130336-4765-11e5-8bec-9dfce900d87e.png)

Add-on 5.0.10
Firefox 40.0.2
Windows 7

**Comment by rugk** [comment]
The issue still appears in v5.1.1.

**Comment by vgturtle127** [comment]
@rugk @fuglede @jsha 

No icons on HTTPS Everywhere 5.1.3 using 64-bit Firefox 44.0.2, 64-bit Firefox Developer Edition, Google Chrome 48, all on 64-bit Windows 10 Pro.

I never knew there were supposed to be icons! :cry:

**Comment by gloomy-ghost** [comment]
Closing as obsolete since we have migrated to WebExtension.
