### ISSUE TITLE
Causing browser crashes?

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#262]
Update: Several people have said that turning off SSL Observatory fixes this.

We are seeing more frequent browser crashes for some users. It seems to happen on OS X, Windows, and Linux.

This seems to be happening only on 3.4.5+. It occurs on at least Firefox 29 and 30, haven't seen it in Tor Browser yet.

Also being tracked here:
* https://trac.torproject.org/projects/tor/ticket/11700
* https://bugzilla.mozilla.org/show_bug.cgi?id=999434

Typical crash signatures:
* Linux: https://crash-stats.mozilla.com/report/index/7f9b693b-ee47-42fb-8db6-616622140617
* OS X: https://crash-stats.mozilla.com/report/index/ca4ee3ff-6549-4227-9706-0e6382140616
* Windows: https://crash-stats.mozilla.com/report/index/db43d540-bf8b-4315-aada-a96412140418

My vague impression is that it's occuring more often for Windows users.

**Comment by jsha** [comment]
Fixed over a year ago. :-)
