### ISSUE TITLE
Add Dolphin (Browser)

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2622]
Please add https://dolphin.com.

**Comment by KommX** [comment]
It's quite easy to do this yourself if you use the make-trivial-rule script in src/chrome/content/rules.

**Comment by rugk** [comment]
Okay, a bash script. (didn't know that something even exists)
But it's not difficult to do it manually either...

So, done: https://github.com/EFForg/https-everywhere/pull/2631
