### ISSUE TITLE
Rename the bato.to ruleset to Batoto

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2627]
This is a very minor detail, but could someone rename the bato.to ruleset to Batoto since that is the site's name?

**Comment by semenko** [comment]
Thanks for the suggestion!

We don't currently have the resources to add & modify rules for small sites when people create GitHub Issues. If you would like to see it add HTTPS Everywhere, please submit a pull request with an updated ruleset: https://www.eff.org/https-everywhere/
