### ISSUE TITLE
Firefox - turning on Block all HTTP request in incognito mode.

### ISSUE THREAD

**Issue by direwolfie** [EFForg/https-everywhere#2629]
Hi! I am running Firefox 40.0 on Ubuntu 14.04 x64.
When I turn on "Block all HTTP requests" in the private window (aka incognito mode) it will enable it in the normal browsing mode, but will not turn the icon red or place a tick mark in the HTTPS-everywhere menu. Hence not showing that Block all HTTP mode is enabled.
It can be reversed by enabling the "Block all HTTP requests" in normal browsing mode or turning on the private browsing window and reversing the setting.
This is very confusing when all http sites refuse to open. Specially since there is no notification that the sites are being blocked by an add-on (like in chrome).
Also, there is the same issue with Show Counter feature.

Hopefully this helps.

**Comment by fuglede** [comment]
This is not an answer: In the current master, the toolbar button and its label is identified and manipulated through the use of <code>document.getElementById</code>. In the case where one has only two open windows, the toolbar button in the 'other' window can be accessed through <code>window.opener.document.getElementById</code>. That is, one can use that to manipulate both buttons at once. To see how it works, try having the counter label active on both buttons and use the following to manipulate the two labels:

    rsa = document.getElementById("rsapplied");
    rsb = window.opener.document.getElementById("rsapplied");
    rsa.value = 10;
    rsb.value = 60;

Using this trick for detection is clearly a terrible hack though, and it does not appear to extend to the case of more than two windows.

**Comment by gloomy-ghost** [comment]
Verified as fixed in the WebExtension version.
