### ISSUE TITLE
MedicineNet.com breaks some tumbnails

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2635]
Example:
http://www.medicinenet.com/brain_aneurysm/patient-comments-602-page4.htm

See the pausable slideshow towards the top of the page.

**Comment by fuglede** [comment]
Looks like earlier, these images (which are currently served on a domain with a bad cert) could be 'saved' by redirecting them to a different host. Now, though, whereas one can still find the images over HTTP like that, the resulting HTTPS URLs redirect to a *different* HTTP URL (not containing the image). Browsing around a bit, it seems like the ruleset is therefore not of much use; #2642 default_off's it.

**Comment by jsha** [comment]
Fixed by default_off'ing the ruleset.

**Comment by TheNavigat** [comment]
I guess this issue needs to be closed.
