### ISSUE TITLE
GameSpot videos won't load

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2637]
Sample: http://www.gamespot.com/videos/now-playing-mad-max/2300-6426597/

HTTPS Everywhere is causing GameSpot videos to not load. Disabling the "GameSpot (partial)" ruleset fixed this.

Sort of related: https://github.com/EFForg/privacybadgerfirefox/issues/544

**Comment by TheNavigat** [comment]
I've traced the issue to this rule.

```<rule from="^http://static(\d)?\.gamespot\.com/(?!.+\.css(?:$|\?))"
		to="https://a248.e.akamai.net/f/50/31/6/static$1.gamespot.com/" />```
