### ISSUE TITLE
Try implementing HTTPS Everywhere using WebExtensions

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2640]
According to this Mozilla blog post, Firefox is moving to a new WebExtensions model, which is supposed to be compatible with Chrome extensions: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/.

We have a long lead time before XPCOM is deprecated, and there are some big issues to solve, like how to make SSL Observatory work in such a world (probably we need Mozilla to implement some extra APIs).

We should try implementing HTTPS Everywhere using the new API, to see if it is possible. Probably starting from the Chromium code rather than the existing Firefox code makes the most sense.

**Comment by Mikaela** [comment]
I was wondering whether SSL Observatory is coming to Chrome or disappearing from Firefox too at https://github.com/EFForg/https-everywhere/issues/1681#issuecomment-137374049 and I was linked here after asking at OFTC and this issue answers my question.

> We have a long lead time before XPCOM is deprecated, and there are some big issues to solve, like how to make SSL Observatory work in such a world (probably we need Mozilla to implement some extra APIs).

Would *[Proposal: native.js to “embrace & extend” the WebExtensions API](https://discourse.mozilla-community.org/t/proposal-native-js-to-embrace-extend-the-webextensions-api/3457)* help if Mozilla implements it?

**Comment by semenko** [comment]
So I took a cursory look here, and it'll be surprisingly easy to adapt the Chrome code to support the new WebExtensions model, and move to one unified extension codebase.

There's great documentation here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

And some issues to look at here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities

As of now, it looks like:
- SSL Observatory support may die: It's never going to work in Chrome, and it may stop working in Firefox without a new Mozilla API (see above comment) 
- We'll need to change some handlers to be platform specific and listen in onBeforeSendHeaders in Firefox -- Chrome lets us rewrite requests earlier (see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest)
- It's not clear we can catch redirect loops in Firefox

**Comment by vgturtle127** [comment]
@semenko Can you explain why in detail that we won't be able to have the SSL Observatory? I saw and read the links, but I don't understand what you're referring to.

**Comment by semenko** [comment]
No APIs exist, that I'm aware of, that allow for access to TLS data in Chrome (or in the WebExtension model in Firefox).

The Chrome dev team also announced that they won't be adding any new APIs to support accessing TLS info. (You can probably find a bug somewhere at https://crbug.com)

**Comment by vgturtle127** [comment]
@semenko Well, that sucks. I wonder what purpose they have of not allowing TLS? Wouldn't it just make it more secure? Chrome isn't exactly the most secure or private browser, so you would think they would want to improve it when they can...

**Comment by Hainish** [comment]
I'm closing this for now, we can reopen a separate issue for building the SSL Observatory into the WebExtensions codebase if the APIs become available at some point.

**Comment by Hainish** [comment]
Thanks for all your work on this @semenko !
