### ISSUE TITLE
Google Translate, Firefox 29, and HTTPS Everywhere producing redirect loop

### ISSUE THREAD

**Issue by robbiemu** [EFForg/https-everywhere#265]
note: This problem also happens at Bing translate.

On Chrome, as some rule-sets match, the Google page loads over HTTPS and the whole thing works just fine.

But in Firefox (at least version 29.0), when the rule-sets match, the Google page loads and redirects to itself forever, showing the same content saying "Translating" with the user bar above .. it loads this again and again until the page is full of repeated top-bar content (user bar, "translating", user bar, "translating", etc).

If I turn on "warn me when the page you are visiting tries to redirect" in Firefox's options, it stops at the first instance with the warning and a button to allow, but allowing just causes the same reload loop to step through one page load at a time.

So that sounds like a Firefox problem. But! If I turn off HTTPS Everywhere (or the Google rule-sets that match) the URL won't get converted to HTTPS, and suddenly Firefox has no problem with it — the translation comes through without a hitch.

**Comment by semenko** [comment]
WFM now.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
