### ISSUE TITLE
Youtube videos embedded on deredactie.be fail to play

### ISSUE THREAD

**Issue by fhimpe** [EFForg/https-everywhere#2654]
Youtube movies included on the website deredactie.be fail to play: only a message is shown that the video is not yet available in the requested format. Disabling Youtube rules in https everywhere makes the video play correctly.

Example URL: http://deredactie.be/cm/vrtnieuws/videozone/ookdatnog/1.2422446

**Comment by TheNavigat** [comment]
Works for me on both Chrome and Firefox.

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
