### ISSUE TITLE
Akami prevents html5 videos from playing

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2656]
Site:
http://www.dash-player.com/

Disabling Akami allows the video to load.

**Comment by TheNavigat** [comment]
Video works for me with Akamai rule enabled as long as I'm using Chrome. However, it fails on Firefox.

**Comment by numismatika** [comment]
This seems to be a rather easy one to fix.
Firefox complains about CORS failing for bitdash-a.akamaihd.net.
However https://www.dash-player.com/ seems to work rather fine.

**Comment by TheNavigat** [comment]
@numismatika , I believe I'm missing something. Can you suggest how to fix that?

**Comment by numismatika** [comment]
Try creating a new custom rule file with the following content
```
<ruleset name="bitmovin GmbH">

	<target host="www.dash-player.com"/>

	<rule from="^http:"
		to="https:" />

</ruleset>

```

**Comment by TheNavigat** [comment]
Oh... I got it. I didn't notice the extra "s" in the link you included in your comment.
