### ISSUE TITLE
RottenTomatoes.com partially broken

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2680]
http://www.rottentomatoes.com/browse/opening/

Page will not load the results unless the Cloudfront rule is disabled.

**Comment by J0WI** [comment]
CORS bug

**Comment by semenko** [comment]
Pages currently load fine for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Comment by MDawg957** [comment]
Still not loading properly unless Cloudfront is disabled.  HTTPSE 5.1.2.

**Comment by MDawg957** [comment]
Checked with HTTPSE 5.1.5 on Firefox 45.0.1 and the page still won't load properly until Cloudfront.net is disabled.

Please re-open.

**Comment by Bisaloo** [comment]
This has been fixed when `rottentomatoes.com` switched to HTTPS.
