### ISSUE TITLE
utf-8 rule

### ISSUE THREAD

**Issue by djasa** [EFForg/https-everywhere#2686]
How to reproduce:
1. create a .xml rule file in $profile/HTTPSEverywhereUserRules/ directory:
    <ruleset name="Reportér Magazín">
            <target host="reportermagazin.cz" />
            <target host="www.reportermagazin.cz" />

```
        <rule from="^http:"
                to="https:" />
</ruleset>
```
1. restart firefox, go to http://reportermagazin.cz
2. click the HTTPS-Everywhere icon

What happens: rubbish is displayed instead of é and í in "Reportér magazín" as in attached image

What should happen: The rule title in the icon menu should be the same as in XML file

Environment:
Firefox ESR 38 @ linux
Firefox environment mixed language but all the encodings are UTF-8:

```
$ strings -a /proc/26738/environ | grep 'LANG\|LC'
LC_PAPER=cs_CZ.utf8
LC_MONETARY=cs_CZ.utf8
LC_NUMERIC=cs_CZ.utf8
LANG=en_US.utf8
GDM_LANG=en_US.utf8
LC_MEASUREMENT=cs_CZ.utf8
LC_TIME=cs_CZ.utf8
```

**Comment by djasa** [comment]
Hmph, image attachment seems impossible and xml got wrong so
1. xml file:
```
<ruleset name="Reportér Magazín">
        <target host="reportermagazin.cz" />
        <target host="www.reportermagazin.cz" />

        <rule from="^http:"
                to="https:" />
</ruleset>
```
and the rubbish looks like displaying the utf-8 string as iso8859-1

**Comment by jsha** [comment]
Thanks for reporting! Will take a look. This is only for custom rules, right? E.g. if you visit https://raphaelhertzog.com/ and click the drop-down, do you get a correctly encoded "Raphaël Hertzog?"

**Comment by djasa** [comment]
Yeah, I see that correctly.

**Comment by J0WI** [comment]
I think it would be a good idea to convert all our code files to utf-8 anyway...
Currently all files are ascii encoded, except those with special characters.

**Comment by Hainish** [comment]
Closing as an issue that affected the legacy (deprecated) codebase.
