### ISSUE TITLE
broken login on www.respekt.cz: modify links in <form ... action="http://current_site/..." /> as well

### ISSUE THREAD

**Issue by djasa** [EFForg/https-everywhere#2695]
test case:
1. create a rule for respekt.cz:
```
<ruleset name="Respekt.cz">
        <target host="respekt.cz" />
        <target host="www.respekt.cz" />

        <rule from="^http:"
                to="https:" />
</ruleset>
```
2. go to login form of https://www.respekt.cz (in Menu in top left corner)
3. fill in some credentials and hit "Přihlásit" ("Log in")
(of course, they might fix it but before that...)

Actual result: nothing happens as form still points to http://www.respekt.cz

Expected result: action attribute of form element is upgraded to https://www.respekt.cz

Note: when the action attribute is hand-rewritten using FF Developer Tools, login works OK

**Comment by jsha** [comment]
HTTPS Everywhere doesn't rewrite the internal components of a page. Instead, when you submit the form, it will rewrite the request before it actually hits the wire.

**Comment by djasa** [comment]
Well, HTTPS Everywhere doesn't get a chance to rewrite it because FF will block the request: 

> Blocked loading mixed active content "http://www.respekt.cz/"

When I allow the insecure mixed content however, FF will block the request with:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.respekt.cz/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://www.respekt.cz/. (Reason: CORS request failed).

I know I'm dealing with buggy page (it should use https page as POST target in the first place) but I was hoping that HTTPS-everywhere would be more powerful in these cases than simple extensions setting HSTS per-site such as Enforce Encryption or in the past, Force TLS.
