### ISSUE TITLE
HTTPS Everywhere should not force HTTP on meta.*.stackexchange.com subdomains

### ISSUE THREAD

**Issue by q--** [EFForg/https-everywhere#2700]
With HTTPS Everywhere off, you can still use HTTPS if you accept the mismatched certificate. With HTTPS Everywhere on, you will always get redirected back to HTTP. This is extra problematic because HTTPS Everywhere uses `<securecookie>` for [Stack Exchange](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Stack-Exchange.xml), so you can't get logged in on the Meta sites.

This issue does not apply to sites that have their own domain, such as stackoverflow.com and superuser.com.

**Comment by TheNavigat** [comment]
Can you post a sample link, please?

**Comment by q--** [comment]
For example: If you're logged in to https://travel.stackexchange.com/, you will not be logged in to http://meta.travel.stackexchange.com/ and if you try to go to <a href="https://meta.travel.stackexchange.com/">http<strong>s</strong>://meta.travel.stackexchange.com/</a> HTTPS Everywhere will redirect you back to HTTP.

**Comment by TheNavigat** [comment]
"https links from other pages to these will cause MCB for important elements, hence the downgrades"

Copied from Stackoverflow's rule file.

**Comment by youdly** [comment]
Users shouldn't be expected to accept mismatched cert hence the downgrade. But I can see the issue "If you're logged in to https://travel.stackexchange.com/, you will not be logged in to http://meta.travel.stackexchange.com/". On one hand, HTTPS Everywhere can ensure (with appropriate rule) HTTPS cookie doesn't pass over HTTP. But in this case, user relies on cookie from https://travel.stackexchange.com to use http://meta.travel.stackexchange.com . Currently, what I can think of is excluding subdomains *.stackexchange.com (assuming all subdomains have meta.*). But excluding all subdomains is too drastic though, any other suggestion anyone?

**Comment by TheNavigat** [comment]
I've suggested on another ticket, #49 specifically, that we might need to inject cookies to resolve the issue. In this case, a valid option would be to inject an HTTP session cookie (or allow the HTTPS cookie to be passed over to HTTP). However, I believe that is too drastic as well.

**Comment by q--** [comment]
The `meta.*.stackexchange.com` sites are now no longer available over HTTPS, even if you disable HTTPS everywhere and ignore the certificate warning; they now display a `403 Forbidden` error.

This means that the only way to use the meta sites when using HTTPS everywhere is disabling HTTPS Everywhere *and* removing the cookie HTTPS Everywhere flagged as `Secure` and logging in again.

I know removing the `<securecookie>` rule will enable session hijacking, but this is hardly workable. The alternative, keeping the StackExchange rule disabled at all times, is even less desirable than removing cookie protection.

**Comment by TheNavigat** [comment]
I agree, honestly. Makes sense.

**Comment by youdly** [comment]
@q-- https://github.com/EFForg/https-everywhere/issues/2700#issuecomment-135528570
I did a test and I can't recreate the issue. When I login to https://travel.stackexchange.com, I also logged in to http://meta.travel.stackexchange.com (without re-login). I tested using v2015.8.13 on Chrome and also latest [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Stack-Exchange.xml) on Firefox.

**Comment by q--** [comment]
I tested it; it turned out that I had the _Stack Exchange (mixed content)_ ruleset enabled, which was responsible for this.

I removed that ruleset in pull request #2701 a few weeks ago because it appeared it had lost its usefulness.But if everything is still working with the latest version of the _Stack Exchange_ ruleset, I may have missed something that wasn't covered by the _Stack Exchange_ ruleset after all.

**Comment by youdly** [comment]
Maybe https://github.com/EFForg/https-everywhere/pull/2701 fixed this issue somehow.

**Comment by q--** [comment]
Well, I'm still curious how #2701 could have solved the issue, but since the problem because of which I opened this issue has been resolved, I'm closing it.

**Comment by wilfm** [comment]
Would any of this help with http://meta.stackexchange.com/q/276702/243424 ?
