### ISSUE TITLE
Please disable rule for PrintFriendly

### ISSUE THREAD

**Issue by j-manu** [EFForg/https-everywhere#2708]
This is the ruleset - https://github.com/EFForg/https-everywhere/blob/e93105c8ce89f591ceaae1ab7f21ac175ff21bff/src/chrome/content/rules/PrintFriendly.xml

We don't use S3 anymore and haven't used it for a very long time. This particular change broke our product since users with HTTPS anywhere installed received old and invalid code from S3. We had to workaround this by uploading our code to S3 which cannot be a permanent solution.

**Comment by jsha** [comment]
Thanks for the report @j-manu, and sorry for breaking your product. Would you like us to disable the whole rule, or just remove the S3 part?

**Comment by j-manu** [comment]
Disable the whole rule. 

We don't and can't have HTTPS enabled for the CDN domain as we need to support legacy clients and though we do support HTTPS, the target might change

HTTPS for our main domain will not work 100% since we embed third party content which may not be HTTPS

So right now, auto redirecting of HTTP traffic to HTTPS like what https-everywhere does is not an option for us.

**Comment by J0WI** [comment]
Could you provide a pull request adding ```default_off="webmaster request"```?

**Comment by j-manu** [comment]
@J0WI Done.  #2821

**Comment by jsha** [comment]
Fixed, thanks for submitting that pull request @j-manu.
