### ISSUE TITLE
Golf Digest page reners wrong in Firefox & Chrome

### ISSUE THREAD

**Issue by CWR64** [EFForg/https-everywhere#2713]
On Dell desktop running Windows 8.1 with all Windows update applied, and current copies of Chrome and FireFox. I get regular emails from Golf Digest magazine, and those emails have links to things on Golf Digest web pages.  When I click the links in IE11, the launched web pages render OK.  When I click those same links in either Firefox or Chrome, the pages do not render correctly at all.  In FireFox & Chrome, if I disable HTTPS Everywhere, the pages render OK. 
Here is an example of a web url that gets rendered wrong in FireFox & Chrome when HTTPS Everywhere is enabled:  https://www.golfdigest.com/story/reliving-butch-harmons-long-lost-pga-tour-career?mbid=nl_082715_daily_hitlist&CNDID=21358373&spMailingID=8022741&spUserID=NTY3MzcwMjIyOTIS1&spJobID=743288873&spReportId=NzQzMjg4ODczS0

**Comment by semenko** [comment]
Lots of mixed content, but seems largely OK to me now.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
