### ISSUE TITLE
Cannot use https everywhere as a global extension

### ISSUE THREAD

**Issue by afrayedknot** [EFForg/https-everywhere#2716]
I am attempting to use https everywhere as a global extension.

I have followed the guidelines for doing this from the Mozilla Wiki and placed the extension with the correct naming in /usr/lib64/firefox/browser/extensions/https-everywhere-eff@eff.org. I have also tried extracting the extension to the extension id in /usr/share/mozilla/extensions/{ec803....}/https-everywhere-eff@eff.org

HTTPS Everywhere loads into the browser but the menu in Tools -> HTTPS Everywhere is blank. The ruleset also appears to be blank, making the extension useless.

This seems to be similar (or identical?) to previous issue #246 

I don't have any experience with extension writing but hopefully this is enough to pinpoint the issue.

Thanks.

**Comment by afrayedknot** [comment]
Further investigation shows that with 5.1.1 rules are working after all, and it is just the menu bug that remains.

Manually going into customize and adding the https everywhere button to the UI fixes the tools menu also. Is part of the XPI install not executed when installing globally?

**Comment by pipboy96** [comment]
Issue is related to a deprecated version of extension.
