### ISSUE TITLE
walmartimages.com ruleset breaks thumbnails of product images on walmart.com

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2727]
Thumbnails of product images on walmart.com won't load with the walmartimages.com ruleset enabled.
Sample page: http://www.walmart.com/browse/0/0/?cat_id=0&facet=special_offers:Special%20Buy||special_offers:Clearance||special_offers:Rollback

While editing this ruleset you could maybe also rename it from Walmart images.com to Walmartimages.com

**Comment by J0WI** [comment]
WFM
