### ISSUE TITLE
JW Platform.com and JWPsrv.com break video streaming

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2732]
Filters:
JW Platform.com
JWPsrv.com

Example:
http://dailycaller.com/2015/08/30/bernie-sander-the-business-model-of-wall-street-is-fraud-video/

**Comment by semenko** [comment]
Currently working for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
