### ISSUE TITLE
interactive elements on spiegel.de get blocked

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2736]
Test case:
http://www.spiegel.de/wirtschaft/betongold-die-interaktive-deutschlandkarte-a-1047006.html

If you disable the rule "Spiegel.de (partial)", you can see a colored map of Germany with some interactive features.
With the rule enabled you simply see nothing.

**Comment by KommX** [comment]
This is another example:
http://www.spiegel.de/politik/deutschland/wirtschaftsfaktor-fluechtlinge-die-profiteure-der-krise-a-1052299.html

**Comment by fuglede** [comment]
Fixed by #2938.
