### ISSUE TITLE
Videos broken with Vox-CDN.com

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2740]
http://www.vox.com/xpress/2014/9/25/6843509/income-distribution-recoveries-pavlina-tcherneva

This video is unable to stream

**Comment by numismatika** [comment]
Are you using a dev edition of chrome? Are there any symbols or messages in the browser console that might point towards broken mixed content?
So far on my firefox nightly it is playing just fine.

**Comment by tancrackers** [comment]
I have to remember to mention which browser(s).
I re-enabled vox-cdn, and the video now works.
I guess it was a mistake on my end.

**Comment by semenko** [comment]
Currently working for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
