### ISSUE TITLE
Videos and search preview broken on Rotten Tomatoes

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2742]
The "preview feature" for [Rotten Tomatoes](http://www.rottentomatoes.com/)' search box that allows users to see results as they type is blocked by HTTPS Everywhere. After deactivating the Cloudfront and CloudFlare.com rulesets the "preview feature" displays correctly, so those are the rulesets that are causing the problem.

**Comment by anonsubmitter** [comment]
The Cloudfront ruleset also prevents video overlays for trailers to open.
Sample: http://www.rottentomatoes.com/m/black_mass_2015/

**Comment by J0WI** [comment]
Done in #4529
