### ISSUE TITLE
Disable force-pushes & force Travis correctness

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#2748]
Whenever this feature launches, an owner should turn this stuff on:

https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by jsha** [comment]
We had already disabled force-pushes by emailing GitHub support. I just turned it on in the UI as well to be thorough.

I've been using the status check requirement in another repo, and I think it is unfeasible for HTTPS Everywhere. Any branch that is out of date with master needs to have the latest master merged into it before the status checks are considered valid for merging. This is correct behavior: it ensures tests pass on the merge of current master and the given branch. However, in practice it would mean frequently asking contributors to merge master into their branch and re-push.
