### ISSUE TITLE
Current BBC ruleset breaks iPlayer

### ISSUE THREAD

**Issue by jay-to-the-dee** [EFForg/https-everywhere#275]
I've presently had to disable the BBC (partial) rule as it breaks the Flash BBC iPlayer. I tested with this URL:

http://www.bbc.co.uk/iplayer/episode/b042v5m2/hd/Orphan_Black_Series_2_Governed_by_Sound_Reason_and_True_Religion/ (works)

OR

https://www.bbc.co.uk/iplayer/episode/b042v5m2/Orphan_Black_Series_2_Governed_by_Sound_Reason_and_True_Religion/ (doesn't work)

When the rule is on the page loads fine, but the Flash player displays "This content doesn't appear to be working. Try again later", with the rule disabled content plays fine.

I guess these rules don't play nice with Flash or that there’s some URL checking featuring within the player that's conflicting with the rules right?

**Comment by numismatika** [comment]
@jay-to-the-dee what is the current status on this?
BBC announced that they will both transition to TLS over time and they also are replacing their flash based player with an html5 version.

**Comment by jay-to-the-dee** [comment]
Hi @numismatika ! You are entirely correct that they are planning on transitioning away from Flash to HTML5 over time. However I would expect the vast majority people will continue to be presented with the Flash version for at least a few more months. I've also not heard the same news you have about TLS so I've learnt something there!

I haven't looked at his issue for a while, but I've just logged onto iPlayer now whilst enabling the two default disabled rules ("BBCi.co.uk (partial)" & "BBC (need testing and feedback)"). The iPlayer works absolutely fine, in this situation (getting the Flash Player using Firefox 48 on Linux). But I've just tried a BBC news video under the same circumstances and that appears to be break the player when the "BBC (need testing and feedback)" rule is enabled. So for now I have had to disable it again.

Hope this helps!

**Comment by numismatika** [comment]
Loveithateit has done quite some work on it indeed
https://github.com/EFForg/https-everywhere/commit/a8578fd0e211cf764d116d72603fe427b7daf222
So the exception rules still break the flash version?

**Comment by jay-to-the-dee** [comment]
This is the sort of thing that is currently broken http://www.bbc.co.uk/news/world-37026321

**Comment by jay-to-the-dee** [comment]
Seems to the BBCi.co.uk ruleset that's causing it actually!

**Comment by numismatika** [comment]
So far it seems that the following 3 subdomains break the player with mixed content trouble:

`
	<target host="emp.bbc.co.uk" /> 
	<target host="open.live.bbc.co.uk"/> 
	<target host="emp.bbci.co.uk" />  
`
unfortunately the underlying Firefox problem is still not solved yet.
BBC community management still says "work in progress, be patient".
