### ISSUE TITLE
re-enable kirjoitusalusta.fi

### ISSUE THREAD

**Issue by Mikaela** [EFForg/https-everywhere#2754]
* https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Kirjoitusalusta.xml

I just noticed that you have ruleset for it and that it's disabled. It had SSL problems previously due to enabling some weak algorithm (I don't remember which), but that has been fixed some weeks ago.

I would open PR by myself, but I don't know how the rule should be changed for enabling and I don't own the domain (which is required in ruleset writing instructions, so I assume it's required here too).

**Comment by Mikaela** [comment]
If I can abuse this issue a little, are there any requirements for getting my site included by HTTPS Everywhere? I am wondering if it's open for everyone or if I should be someone important for it.

It's in the HSTS preload list, but browsers seem to update it very slowly and for some reason the redirect from http to https doens't always work before HSTS is seen by the browser.

**Comment by semenko** [comment]
Hey -- generally no. If your site supports HTTPs, and you're willing to write a rule, you're good!

**Comment by Mikaela** [comment]
Thanks for the reply, I will be opening PR soon hoping everything is correctly with the rule. The test script isn't Arch (tries to use everything else than pacman).
