### ISSUE TITLE
Problems on br.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#2756]
With the rule "Bayrischer Rundfunk" enabled I'm unable to follow the link http://story.br.de/innerdeutsche-grenze/ with Chrome. The problem doesn't occur on Firefox.

**Comment by numismatika** [comment]
Mhmm i only see requests to cdn-storage.br.de and story.br.de on that page.
The only issue i had with the link are disabled cookies, which seem to be required.
#2570 should have fixed the problem of non-tls subdomains on that website

**Comment by KommX** [comment]
I'm not sure how to see if #2570 made it into the last Chrome release, but I guess that not. But there was a Firefox release lately, so perhaps this explains the difference.

**Comment by J0WI** [comment]
what about https://story.br.de/?

**Comment by KommX** [comment]
@J0WI I don't understand your question.

btw:
I can't reproduce my problem anymore with Chrome Version 46.0.2490.86.

**Comment by numismatika** [comment]
https://story.br.de/innerdeutsche-grenze/ says "story doesn't exist", so it looks like that it isn't a valid alternative.

**Comment by KommX** [comment]
@numismatika 
https://story.br.de/innerdeutsche-grenze/ works for me.

**Comment by numismatika** [comment]
i forgot to enable cookies again, sorry.
I opened a PR #3335 to fix it.

**Comment by semenko** [comment]
Currently working for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
