### ISSUE TITLE
incorrect redirect on cdn.discourse.org

### ISSUE THREAD

**Issue by riking** [EFForg/https-everywhere#2775]
https://www.eff.org/https-everywhere/atlas/domains/discourse.org.html

	<rule from="^http://cdn\.discourse\.org/" to="https://try-discourse.global.ssl.fastly.net/"/>

cdn.discourse.org is now HTTPS without a redirect, and try-discourse.global.ssl.fastly.net is now a dead domain. The rule should be changed to a plain upgrade.

**Comment by fuglede** [comment]
Thanks for the report! This is fixed by #2810.
