### ISSUE TITLE
Pre-commit test broken on Debian Jessie; pushing impossible

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2803]
Apologies if I am missing something on the pre-commit testing but I am having a few issues with it. First of all, the test in <code>https-everywhere-tests/test/test-httpse-installed.js</code> fails on Debian Jessie, even if chromium is actually installed. Changing <code>require("chrome")</code> to <code>require("chromium")</code> allows me to push the test a bit further, but even with this change, the test stalls at this point:

    console.log: https-everywhere-tests: [JavaScript Error: "intet element fundet" {file: "data:text/plain," line: 1}]
    console.log: https-everywhere-tests: [JavaScript Error: "1441557887338	Toolkit.GMP	ERROR	GMPInstallManager.onLoadXML could not load xml: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 142"  data: no]" {file: "resource://gre/modules/Log.jsm" line: 749}]
    console.log: https-everywhere-tests: [JavaScript Error: "1441557887338	Toolkit.GMP	ERROR	GMPInstallManager.simpleCheckAndInstall Could not check for addons: {"target":{},"status":200,"message":"[Exception... \"SSL is required and URI scheme is not https.\"  nsresult: \"0x8000ffff (NS_ERROR_UNEXPECTED)\"  location: \"JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 142\"  data: no]"}" {file: "resource://gre/modules/Log.jsm" line: 749}]

Due to the hooking, this breaks pushing even simple changes. Of course, <code>git push --no-verify</code> still does the job, but clearly that is not intended.

**Comment by TheNavigat** [comment]
https://github.com/EFForg/https-everywhere/issues/2801#issuecomment-138102004

**Comment by fuglede** [comment]
Right, I guess this is a duplicate of #2801. Closing as such.
