### ISSUE TITLE
Make pre-push hook smarter

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#2809]
Since Travis builds everything now, let's think about making the pre-push hook a bit smarter. Say, by only testing Firefox and Chrome if the extension code changed.

It's a bit annoying to have a bunch of FF/Chrome windows appear for every tiny non-extension change & work-in-progress stuff I'm saving.

**Comment by Multibituser** [comment]
![i don t know but they don t look like photos to me](https://cloud.githubusercontent.com/assets/5903234/9707461/88506f40-54d7-11e5-91ac-d3adf4899a97.JPG)[ ]Office Depot (cyan, terabyte backup, daybook)
