### ISSUE TITLE
GNUnet: broken ruleset for www.gnunet.org

### ISSUE THREAD

**Issue by PotcFdk** [EFForg/https-everywhere#2822]
I updated the ruleset in #1733. On June 22nd, @2d1 pushed cb5c33d7b44ffdf4209fb67c2ddeb6167975e97d, which breaks https://www.gnunet.org due to a certificate subject name mismatch.
Has this change even been tested or was it just blindly pushed to HTTPSE?

**Comment by TheNavigat** [comment]
I think this comment is valid. https://github.com/EFForg/https-everywhere/commit/cb5c33d7b44ffdf4209fb67c2ddeb6167975e97d#commitcomment-13198469

If it answers your question, can you please close this issue?

**Comment by PotcFdk** [comment]
It depends on whether this is intended behavior.

**Comment by TheNavigat** [comment]
@fuglede should be able to answer that accurately.

**Comment by J0WI** [comment]
this is obsolete since (www.)gnunet.org uses a valid cert from Let's Encrypt now.

**Comment by PotcFdk** [comment]
@J0WI Thanks, you're right.
