### ISSUE TITLE
[Directory Opus] Fail Travis test

### ISSUE THREAD

**Issue by ldgbc** [EFForg/https-everywhere#2834]
Not sure why the travis auto check keep failing for me.

See pull request: https://github.com/EFForg/https-everywhere/pull/2833#partial-pull-merging
https://github.com/EFForg/https-everywhere/pull/2833

**Comment by semenko** [comment]
If you click on the little red "X", you can see the full Travis logs.

Usually the message you want is near the bottom (where the script aborts).

For one of your PRs:
https://travis-ci.org/EFForg/https-everywhere/builds/79384689#L264
```
src/chrome/content/rules/Directory Opus failed validity: Rule filenames cannot contain spaces
```
