### ISSUE TITLE
HTTPS Everywhere Atlas ignore case-senstive

### ISSUE THREAD

**Issue by ldgbc** [EFForg/https-everywhere#2837]
Issue: Search result search use case sensitive (Uppercase)
Solution: Resolve all uppercase as lowercase or ignore uppercase.

Reproduce: Go to https://www.eff.org/https-everywhere/atlas/index.html
Search keyword: Eff.org / https://www.eff.org/https-everywhere/atlas/index.html?Eff.org
Result is 0.
Now search keyword: eff.org / https://www.eff.org/https-everywhere/atlas/index.html?eff.org
Find 1.

**Comment by TheNavigat** [comment]
I think that's easy to fix but I'm not sure if the public has access to the atlas's code.

**Comment by jsha** [comment]
That's correct, we just have a copy on our website, though we should bring it into the HTTPS Everywhere repo.

I've fixed the case sensitivity, thanks!
