### ISSUE TITLE
Chrome extension causes bug on ikea.com/us

### ISSUE THREAD

**Issue by cs54** [EFForg/https-everywhere#284]
Greetings! Huge HTTPS Everywhere fan here, with a minor glitch to report:

For whatever reason, it looks like the Chrome extension is causing the Add to Cart button on Ikea's website to hang, per the screenshots below. (I won't pretend to understand why -- I deduced that HTTPS Everywhere is the culprit thru one-by-one disabling of my extensions but am already out of my depth.)

With the extension disabled, here's what happens when I add to cart at the product link below:

![image](https://cloud.githubusercontent.com/assets/6879699/3000567/8acd36f2-dd25-11e3-84a8-e1bf7772d16a.png)

with the extension enabled, it just seems to hang like so:

![image](https://cloud.githubusercontent.com/assets/6879699/3000558/62a49f1c-dd25-11e3-943c-ac0d1019224d.png)

product link: http://www.ikea.com/us/en/catalog/products/60169251/

Thank you for this wonderful extension!

-Chris

**Comment by dron221231** [comment]
Looks like a common issue on these website created on wordpress. Had the same problem with the order on http://buonanotte.md/shop/
