### ISSUE TITLE
Some regexps use `?` quantifiers for look-aheads

### ISSUE THREAD

**Issue by RReverser** [EFForg/https-everywhere#2842]
Probably purely a code style issue, but some regular expressions use constructs like `(?=...)?` which is valid in JavaScript but don't make sense and only complicate expressions. Here's a list of all the found ones:

```javascript
{ input: '^http://www\\.heteml\\.jp/[^?]*(?=\\?)?',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 36,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
{ input: '^http://store\\.mandriva\\.com/[^?]*(?=\\?.*)?',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 43,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
{ input: '^http://soe\\.stanford\\.edu/+(?=\\?.*)?$',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 37,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
{ input: '^http://(?:www\\.)?tescofinance\\.com/+(?=\\?.*)?$',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 46,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
{ input: '^http://hilfe\\.udmedia\\.de/[^?]*(?=\\?.*)?',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 41,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
{ input: '^http://livechat\\.udmedia\\.de/[^?]*(?=\\?.*)?',
  error: 
   { name: 'RegexSyntaxError',
     type: 'NothingRepeat',
     lastIndex: 44,
     message: 'Nothing to repeat!Repeat after assertion doesn\'t make sense!' } }
```

**Comment by fuglede** [comment]
Are you talking about that the <code>?</code> after the look-ahead? If so, I'm not quite sure what it means that it doesn't make sense? While I agree that those expressions aren't the easiest to read, the question mark is not non-functional. For example, the pattern <code>/</code> is matched by <code>/[^?]*(?=\?.*)?</code> but not by <code>/[^?]*(?=\?.*)</code>.

**Comment by forgreatsh** [comment]
Back references "don't make sense" if by "don't make sense" you mean describe something other than a formal language. `?!` and `?=` make perfect sense in pcre (which I concede are irregular).

There are at least two good reasons for using such lookaheads:
* It makes it harder to misplace or misnumber backreferences. It's also easier to review when the intention to drop or keep the matched pattern is clear, which the distinction between `?!`, `?=`, and `\?[^?!:]`  makes so.
  * Admittedly ?: Also serves this purpose, but it's even easier to see ?! and ?=.
* Complicated but direct rewrites can be turned into exclusions, such that it is impossible for a malicious author to include an expression that rewrites to, say, *$evil_tracking_location*. The worst they could do is exclude a pattern that we would expect to be secured.

**Comment by RReverser** [comment]
> Are you talking about that the `?` after the look-ahead? If so, I'm not quite sure what it means that it doesn't make sense? While I agree that those expressions aren't the easiest to read, the question mark is not non-functional. For example, the string `/` is matched by `/[^?]*(?=\?.*)?` but not by `/[^?]*(?=\?.*)`.

Original message was from regulex parser which is stricter than regular JS engines. My understanding is that it's correct, you just chose incorrect alternative. The thing is that either both me and regulex authors are missing something, or `/[^?]*(?=\?.*)?` has just the same effect as `/[^?]*` since "optional lookahead" doesn't make any sense at least in the end of regular expression - it's just the same as if there would be no look-ahead at all.

**Comment by RReverser** [comment]
@forgreatsh No, that's not what I mean by "doesn't make sense". I know what are look-aheads for in general :) Please see explanation of this specific problem in previous comment.

**Comment by JexCheng** [comment]
@RReverser  Sorry it's my fault, I have noticed this kind bug these days, the fix will come soon:
https://github.com/JexCheng/regulex/issues/29

**Comment by RReverser** [comment]
I see, thanks. Sorry for confusion then.

**Comment by fuglede** [comment]
I think you're right though, that <code>/[^?]*(?=\?.*)?</code> is equivalent to <code>/[^?]*</code>, so there must be a reason it was done the other way. The Mandriva ruleset has the following comment, which may or may not have something to do with it:

**Comment by RReverser** [comment]
I see, keeping it open then.

**Comment by RReverser** [comment]
> due to ruleset validation

@fuglede If this is a reason, maybe it would make sense to fix rule validation. What do you think?

**Comment by fuglede** [comment]
It validates just fine with <code>/[^?]*</code> though. @2d1?

**Comment by loveithateit** [comment]
[clarification: yet another @2d1 account after my dev machine was wiped remotely (@QubesOS); the probably reason for which I suspect is apparent to @pde]

@RReverser sorry, I rushed to defend lookaheads without reading through your report. You're absolutely right, and I assume that they were all 'brain farts', as it were, on my part. Some of the cases are redundant (since `*(?!\?)` is greedy), and others are impossible.

@fuglede I haven't got back to a point where I can contribute yet (setting up security policy, auditing, etc.), so feel free to make the appropriate changes.

**Comment by fuglede** [comment]
Super. @RReverser, do you want to submit a PR fixing the redundant ones?

**Comment by RReverser** [comment]
I can a bit later.

**Comment by RReverser** [comment]
Done!
