### ISSUE TITLE
Correct & cleanup intevation.org

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#2846]
These rules really need a cleanup. There are 3 rules for the same site, which are not only outdated, but could also be simplified.

https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Intevation-GmbH.xml
https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Intevation.xml
https://github.com/EFForg/https-everywhere/blob/fe756cd650cdc4b81a25b93982fe86be801037f6/src/chrome/content/rules/Intevation-problematic.xml

**Comment by rugk** [comment]
So I've tried to make a first step in https://github.com/EFForg/https-everywhere/pull/2845.

**Comment by rugk** [comment]
Any more ideas?

**Comment by TheNavigat** [comment]
I don't think so, this looks perfect. Great work!
