### ISSUE TITLE
HTTPS Everywhere breaks videos on DN.no

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2860]
HTTPS Everywhere breaks videos on dn.no. Disabling the "Brightcove (partial)" ruleset fixes this.
Sample: http://www.dn.no/magasinet/2015/09/07/1606/Popcorn-Time/inside-popcorn-time--the-worlds-fastest-growing-piracy-site

**Comment by numismatika** [comment]
Seems to be a CORS issue.
Try 
https://www.dn.no/magasinet/2015/09/07/1606/Popcorn-Time/inside-popcorn-time--the-worlds-fastest-growing-piracy-site 
The TLS version of the domain has some minor mixed-content warnings, but seems to work for me.
If it works well enough for you and doesn't break anything on the page, i'll submit a PR to fix it.

**Comment by anonsubmitter** [comment]
Everything including the video seems to be working fine for me on the HTTPS version of the site.
