### ISSUE TITLE
RevSci.net breaks video playback

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2868]
Example:
http://www.reuters.com/article/2015/09/11/us-usa-election-wilks-specialreport-idUSKCN0RB0ZF20150911

Filter:
RevSci.net

**Comment by TheNavigat** [comment]
Works on Chrome, doesn't work on Firefox. I believe it's CORS related, i.e. issue #49 

That's part of what Firefox's console says.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://freegeoip.net/json/. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://freegeoip.net/json/. (Reason: CORS request failed).
```

**Comment by semenko** [comment]
Seems fixed per above commits.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
