### ISSUE TITLE
Breakage on fjallfoss.fcc.gov and apps.fcc.gov

### ISSUE THREAD

**Issue by kevinoid** [EFForg/https-everywhere#2874]
I was recently browsing the FCC website and noticed some breakage caused by HTTPS Everywhere:

* First, http://fjallfoss.fcc.gov/ecfs2/ returns a 302 redirect to http://apps.fcc.gov/ecfs/ while https://fjallfoss.fcc.gov/ecfs2/ returns a 404 page.  Currently HTTPS Everywhere rewrites the first to the second, resulting in an unexpected 404.
* Compounding the above, although http://apps.fcc.gov/ecfs/ returns the page for the new Electronic Comment Filing System, https://apps.fcc.gov/ecfs/ results in a 404.  So the user is again presented with an unexpected 404.

I could write up a pull request, but I am unsure how this should be handled and would appreciate your input.  It appears that fjallfoss.fcc.gov redirects everything to other subdomains and that none of the redirects work over HTTPS (e.g. see https://www.reddit.com/domain/fjallfoss.fcc.gov/).  So I suspect the test for that subdomain should simply be removed.

apps.fcc.gov is more difficult.  From a bit of testing, the ecfs directory is the only one that I have found which is broken.  But apps.fcc.gov hosts a lot of different applications and it's likely per-application whether HTTPS is supported, so there may be more breakage either presently or in the future.  Does it make more sense for these directories to be black- or white-listed?

Thanks for considering,
Kevin

**Comment by TheNavigat** [comment]
I would appreciate if you could take a look at https://github.com/EFForg/https-everywhere/pull/2885 and let me know what do you think :)

**Comment by kevinoid** [comment]
Thanks @TheNavigat, that looks great!

Funny that the apps.fcc.gov certificate expired ~24 hours ago.  Makes the decision about what to do for that subdomain much easier!
