### ISSUE TITLE
HTTPS Everywhere breaks Symantec Connect Blogs

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2880]
HTTPS Everywhere breaks the layout of Symantec Connect Blogs to the degree that it is impossible to read any blog post or navigate the blog's frontpage without disabling the "Symantec (partial)" ruleset.

Samples:
http://www.symantec.com/connect/blogs
http://www.symantec.com/connect/blogs/firefox-vulnerability-could-allow-attackers-steal-documents

**Comment by dholbert** [comment]
I hit this as well, with this blog post which is making the tech press rounds over the past few days:
http://www.symantec.com/connect/blogs/tough-day-leaders

@TheNavigat, looks like you've got a patch for this -- do you know if it's already being considered for inclusion? It'd be great to see this fixed.

**Comment by TheNavigat** [comment]
@dholbert That's the PR link, https://github.com/EFForg/https-everywhere/pull/2881. It's not merged yet :/

**Comment by semenko** [comment]
merged per above
