### ISSUE TITLE
UPI.com breaks webpage rendering

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#2883]
Example:
http://www.upi.com/Sports_News/2015/09/12/Report-Seattle-Seahawks-owner-Paul-Allen-ends-talks-with-Kam-Chancellor/7581442031746/

Website:
http://www.upi.com/

Filter:
UPI.com (partial)

Browser:
Firefox
Chrome

**Comment by TheNavigat** [comment]
@semenko , I think someone needs to close this issue.

**Comment by semenko** [comment]
Done! :P

You were so close to a magic phrase with "Fixing" :cake: 
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by TheNavigat** [comment]
such speed
very efficient
wow

Also, aha, I see! Alright then, I'll use "Fixes" afterwards.
