### ISSUE TITLE
HTTPS Everywhere breaks Torcache

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2887]
HTTPS Everywhere breaks torcache.net so that torrent files won't load and pop up in a "save window". Disabling the "Torcache" ruleset fixes this.
Sample: https://torcache.net/torrent/72F242DB89E763B6CE390F25D576195C2169B149.torrent

**Comment by fuglede** [comment]
Is this still an issue? I don't see any problems with the reference URL.

**Comment by fuglede** [comment]
[Looks like](https://github.com/EFForg/https-everywhere/pull/2931#issuecomment-143507604) this one fixed itself.
