### ISSUE TITLE
"301 Moved" on Firefox's new-tab page thumb previews

### ISSUE THREAD

**Issue by ahmedtds** [EFForg/https-everywhere#290]
When HTTPS Everywhere enabled, on Firefox's new-tab page thumbnail previews of some pages looks empty and says "301 Moved"

Gmail for example:
![gmail](https://cloud.githubusercontent.com/assets/6431737/3075699/85db9620-e38d-11e3-9159-c35e96a6e7f6.PNG)

I use Firefox 29.0.1 and Windows 7

**Comment by StevenRoddis** [comment]
@ahmedtds does this still occur with the latest stable version of HTTPS Everywhere?

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen if you think it's still a bug.
