### ISSUE TITLE
HTTPS Everywhere causes Firefox tabs no longer to be moveable

### ISSUE THREAD

**Issue by andy-maier** [EFForg/https-everywhere#2912]
Firefox supports moving tabs by dragging them, either into a new position in the same FF window, or into a different FF window.
When HTTPS Everywhere is installed and enabled, that tab dragging does not work anymore. The tab behaves as if it was not dragged, or as if FF would not support such dragging. When I disable HTTPS Everywhere and restart FF, it works again.
This is on RHEL 6.6 on x86-64, and with Firefox ESR 38.2.1.
Andy

**Comment by TheNavigat** [comment]
It works perfectly for me on Ubuntu 14.04.3 LTS, Firefox 40.0.3.

**Comment by vgturtle127** [comment]
@fuglede @jsha We can close this, the bug has been fixed.

**Comment by fuglede** [comment]
@vgturtle127: It's cool that you've been hunting down some dead issues, but just as an FYI (in case you find more of them), my 'powers' are limited to ruleset management, so I'll leave some of these to the grown-ups.

**Comment by vgturtle127** [comment]
@fuglede Oh, alright. Good to know. Thanks!

@jsha Thanks!
