### ISSUE TITLE
Rule enforcement confusion

### ISSUE THREAD

**Issue by Forage** [EFForg/https-everywhere#2916]
Hi,

Today I gave the HTTPS Everywhere add-on for Firefox a try and I must say that it's quite a confusing experience for something that should be as clear and simple as possible.
I am hoping to get some answers by reporting it as an issue here and maybe it can serve as a feature request at the same time.

Going to a site you typically get to see 3 things in the add-on's menu:
- Greyed out entries with a green check mark in front of it
- Entries with a green check mark in front of it
- Entries with a red cross in front of it

All can be interpret in different ways:
- Red cross: is the rule disabled now or will it be disabled when I click on it?
- Green check: is the rule enabled now or will it be enabled when I click on it?
- Greyed out entries: Is a rule applied at all, is it ignored?

Maybe something like switches as in the Ghostery add-on should be used in stead of checks and crosses to indicate a rule is enabled or disabled and allowing the user to change it. That would be much more clear.

Then there's the matter of default disabled rules. It appears that some rules are present but not applied. The user doesn't get to know if he doesn't bother to check every site every time in the add-on's menu.
If the rules are not applied anyway, than why bother including them in the first place?
If there is a need for them: maybe it would be good to give an indication when a site is known but the rule is not applied in the add-on's icon. This way the user can actually know about it and decide if he wants to enforce the rule.

**Comment by fuglede** [comment]
> The user doesn't get to know if he doesn't bother to check every site every time in the add-on's menu.
If the rules are not applied anyway, than why bother including them in the first place?

This particular question I attempted to address with #2009 which contains an option to show the number of applicable rules on a page.

**Comment by jeremyn** [comment]
Issue #1180 is also about the UI not being clear.

**Comment by pipboy96** [comment]
Related: #17068.
