### ISSUE TITLE
youngarts.org supports TLS

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#2923]
At least, the homepage does. Triggers MCB, though I'm not sure if it really matters.

**Comment by fuglede** [comment]
I'm having some issues with the site's SSL support; see https://github.com/EFForg/https-everywhere/pull/2928#issuecomment-143495524.

**Comment by fuglede** [comment]
I wrote their devs about the issue. If they fix it, we can have a look at it again.
