### ISSUE TITLE
Images broken on www.ok.ru

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#2924]
Reported for Opera [here](https://addons.opera.com/en/extensions/details/https-everywhere/?display=en&reports#r130045).

When this ticket is closed, let's be sure to reply to the original report.

**Comment by J0WI** [comment]
Maybe a dupe of #3228

**Comment by J0WI** [comment]
See https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Ok.ru.xml
