### ISSUE TITLE
HTTPS Everywhere breaks videos on TED.com

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2925]
HTTPS Everywhere breaks videos on ted.com. Disabling the "Akamai" ruleset fixes this.
Sample: https://www.ted.com/talks/christopher_soghoian_a_brief_history_of_phone_wiretapping_and_how_to_avoid_it

**Comment by anand-bhat** [comment]
I believe this has been addressed via https://github.com/EFForg/https-everywhere/issues/2816

**Comment by anonsubmitter** [comment]
Ah, so it seems.
