### ISSUE TITLE
Publish https-everywhere-rewriter

### ISSUE THREAD

**Issue by RReverser** [EFForg/https-everywhere#2926]
Would you be open to publishing [rewriter](https://github.com/EFForg/https-everywhere/tree/master/rewriter) to npm? We would like to use it for custom tool testing needs, and would be very convenient not to include it from git submodule just for that.

**Comment by RReverser** [comment]
Ideally would be nice to have `ruleSets` exposed out-of-module as well.

**Comment by jsha** [comment]
Yes, I'd definitely be open to that. Would you be interested in being the maintainer for the npm module?

**Comment by RReverser** [comment]
Sure, why not.

**Comment by RReverser** [comment]
@jsha It looks like `rewriter` got broken due to restructuring of `chromium` page and changes to `RuleSets` constructor, so our code that used it, broke :( (one more reason to keep them as separate packages)

**Comment by RReverser** [comment]
@jsha @fuglede On a related note, would you be open to modularizing https-everywhere a bit more? In particular, splitting rules, browser extension and generic code into own submodules so that one could safely update XML data without code breakage and so?

**Comment by fuglede** [comment]
That idea actually aired in https://github.com/EFForg/https-everywhere/issues/3999#issuecomment-175782777.

Personally, I have no strong opinions on the matter; my first thought was that it might make doing projects like https://github.com/chris-barry/darkweb-everywhere a bit more straightforward to maintain, but then again, that's not really a very strong argument for anything.
