### ISSUE TITLE
Delete the Blip.tv ruleset

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#2936]
Blip.tv has been discontinued in favour of Maker.tv. Since the site is no longer accessible there is no reason for there to be a ruleset for it.

**Comment by J0WI** [comment]
this still gives us a 'secure' redirect to the new host...
The ruleset should be rewritten for maker.tv instead of deleting it.

**Comment by anonsubmitter** [comment]
Yeah, now that you say it, rewriting it to Maker.tv would be better. (Weird that I didn't think that far.)

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's still a bug.

**Comment by semenko** [comment]
(er, not so old, but seems like an ok rule)
