### ISSUE TITLE
Allow custom exclude rules

### ISSUE THREAD

**Issue by Ivoz** [EFForg/https-everywhere#296]
Using Chrome https-everywhere, I have the option to add a rule include a new site, but not to exclude a part or subdomain of one.

For instance, I came across http://asmeurer.github.io/python3-presentation/slides.html

When upgraded to https this presentation breaks because the javascript used to render it is hosted under a http link. So while generally using https for `*.github.io` I would like to exclude this subdomain. It would be great to have an easy option box to add a rule that does this.

**Comment by githubmarker** [comment]
Just came across this issue since I had a similar problem. It would be helpful if there were a way to do this exclusion through the UI.

**Comment by szTheory** [comment]
How do you add an exception from the UI?

**Comment by zoracon** [comment]
Closed by #16669
