### ISSUE TITLE
https_everywhere_checker disables good rewrites when only from-host times out

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2982]
Now this might be working as intended but it seems that it's not: the PR #2939 gave an example of a host (banking.spkrb.de) which is being rewritten from HTTP to HTTPS but where the HTTP version actually serves nothing. The checker disabled the ruleset as a result even though it does serve a (perhaps minor) purpose.

**Comment by jsha** [comment]
Agreed: we already have code that treats connection refuse on an HTTP host as acceptable, we should probably handle timeouts as well. Note that some checker-related bugs are already fixed but still have a backlog of disabled rules checked in that we need to update.
