### ISSUE TITLE
HTTPS Everywhere breaks TED videos

### ISSUE THREAD

**Issue by rhodin** [EFForg/https-everywhere#2998]
If HTTPS Everywhere is enabled, when I click the play triangle the loading icon keeps playing forever, the video is not played and I get this error message:

"We're sorry: video playback cannot be initialized at this time. You can always download this talk or save it to watch later."

As suggested in HTTPS Everywhere's FAQ, I've already reported this problem to TED so they can fix it. But if they don't, it would be great if HTTPS Everywhere developers did it. I know I can always download the video, but it would be much better if the embedded video player on TED worked well with HTTPS Everywhere.

BTW, I couldn't find a way to disable HTTPS Everywhere only on TED as suggested by HTTPS Everywhere's FAQ ("In the meantime, you can disable the rule affecting that particular site in your own copy of HTTPS Everywhere by clicking on the HTTPS Everywhere toolbar button and unchecking the rule for that site"). Is it because you can't disable the add-on for the current site, but just disable the particular elements from that site on which HTTPS Everywhere works (which on TED.com would be: Google Services Simple, Google APIs and Akamai)?

Thank you for your time!

**Comment by numismatika** [comment]
@rhodin  could you try again?
So far the only thing that keeps the videos from playing here are disabled-cookies,
which they had already fixed in the past.

**Comment by semenko** [comment]
Should be fixed in updated version -- plus some PRs addressing this.
