### ISSUE TITLE
HTTPS everywhere breaks NHL.com videos

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#3001]
Videos do not load at all. Turn it off, they play fine.

**Comment by zond2** [comment]
I had the same issue. When on the webpage for the video, I pressed the HTTPS everwhere button, went to the list of stable rules and de-selected akamai. Videos now play fine. Not, in my opinion, the perfect solution, but better (and more secure) than having to disable the whole extension.

**Comment by numismatika** [comment]
@tkiperchuk NHL.com seems to be TLS-enabled now. Do you still have issues with the video?

**Comment by J0WI** [comment]
Closing due the lack of response.
