### ISSUE TITLE
ruhr-uni-bochum.de broken

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#3009]
The rule 'Ruhr-Uni-Bochum.de (partial)' breaks these site:
https://www.ruhr-uni-bochum.de/studierendensekretariat/studium/einschreibung/gasthoerer.html.de
https://www.ruhr-uni-bochum.de/uebersicht/
https://www.ruhr-uni-bochum.de/suche/

**Comment by KommX** [comment]
https://www.ruhr-uni-bochum.de/anreise/bus-und-bahn.html
is also broken.

**Comment by fuglede** [comment]
Added to #3012.
