### ISSUE TITLE
JSON rulest

### ISSUE THREAD

**Issue by stokito** [EFForg/https-everywhere#3011]
Why Chromium extension load and parses a ruleset as XML file?
Maybe it would be better to load it as JSON?

**Comment by jsha** [comment]
XML is the format we decided on many years ago when HTTPS Everywhere started, and is the format in which the rulesets are maintained. JSON has some advantages and some disadvantages, but I think we are unlikely to switch over now.

**Comment by stokito** [comment]
Hi @jsha could you please give more details why we can't switch over now? 
As I see, we can just generate JSON from XML rulsets and fetch it on loading.

**Comment by techtonik** [comment]
@jsha do you have any toolchain that relied on these rules to be XML? I think a symmetric 1:1 converter between two formats in possible.
