### ISSUE TITLE
Satellite images don't load.

### ISSUE THREAD

**Issue by losuler** [EFForg/https-everywhere#3021]
I'm not sure of the cause of the issue, but I was able to verify it was https-everywhere.
http://satview.bom.gov.au/

**Comment by anand-bhat** [comment]
I see the following errors in the browser console:
>XMLHttpRequest cannot load https://d30f2i1nzx9v71.cloudfront.net/himawari/text/IDY28000_TEX.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

>XMLHttpRequest cannot load https://d30f2i1nzx9v71.cloudfront.net/himawari/IDE00436/Himawari/timesteps.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

When the Cloudfront rule is disabled, these errors disappers and the images appear.

**Comment by J0WI** [comment]
closed by #14705
