### ISSUE TITLE
No longer installable in Chrome / Chromium (2015.5.28_0 a.k.a. 2015.8.13)

### ISSUE THREAD

**Issue by SMcCandlish** [EFForg/https-everywhere#3025]
The version reported as 2015.8.13, and which is internally labeled 2015.5.28_0, will no longer load into Chrome or Chromium (on Mac OS X 10.10.5, anyway). If you try to do it the normal way, it generates a "Could not move extension directory into profile" error (which is basically meaningless). If you go the "Load unpacked extension" route, you get "Manifest file is missing or unreadable."  You get the same error if you already have the extension installed in a Chrome, and try "Pack extension" option to export it.

**Comment by semenko** [comment]
WFM on Chrome 48, closing as invalid.
