### ISSUE TITLE
[Android] Dialog boxes missing "Yes" option

### ISSUE THREAD

**Issue by gitarra** [EFForg/https-everywhere#3029]
It isnt possible to reset the rules to defaults by long-tapping on the add-on logo since the confirmation dialog box that follows contains only the "No" option.

This also happens if you try to disable HTTPS Everywhere through its entry in the Firefox dropdown menu.

![box](https://cloud.githubusercontent.com/assets/4739888/10246659/f3193890-691b-11e5-91ed-c6ba00bc3d63.png)

**Comment by rugk** [comment]
:+1: 
Also saw this issue. That's a really funny choice the user has there. :laughing: 
UX par excellence. :wink:

**Comment by Hainish** [comment]
https://github.com/EFForg/https-everywhere/pull/6617 will fix this issue, this is due to an api change in FF Android

**Comment by Hainish** [comment]
Fixed in https://github.com/EFForg/https-everywhere/pull/6617
