### ISSUE TITLE
Mobygames.com rule broken

### ISSUE THREAD

**Issue by fvmrc** [EFForg/https-everywhere#3030]
In the screenshots gallery, thumbnails are not visible.
eg: http://www.mobygames.com/game/doom/screenshots

**Comment by PotcFdk** [comment]
Now that's interesting.
On the non-ssl version, those items are `<a>` tags with `style="background-image: url("/images/shots/s/362965-doom-3do-screenshot-title-screen.jpg");"`.
On the ssl-version, it's `style="background-image: url("//images/shots/s/362965-doom-3do-screenshot-title-screen.jpg");"` (note the additional leading `/`, which is probably a typo or the result of some kind of misconfigured/broken script).
Did you try contacting the operator of that page?

**Comment by fvmrc** [comment]
Good point, this problem is not directly related with https-everywhere, but is present when accessing the website using https in general. Probably on their side, sent them an email.

**Comment by fvmrc** [comment]
It seems they have fixed this issue.
