### ISSUE TITLE
Slow scrolling with Observatory enabled.

### ISSUE THREAD

**Issue by mxxcon** [EFForg/https-everywhere#3044]
I use Windows 10, Firefox 41.0.1, HTTPS-Everywhere 5.1.0 from AMO. I have HTTPS-Observatory enabled.
When I load https://twofactorauth.org/ and scroll down, that website dynamically loads additional favicons as they come into view. With Observatory enabled there's a noticeable delay and stuttering as each image gets into view and loaded. With Observatory disabled scrolling is much more smooth.
Here's what it looks like in Firefox's dev tools:
![clipboard01](https://cloud.githubusercontent.com/assets/847140/10281711/70014db4-6b44-11e5-8d01-70403c3c2356.png)
![clipboard02](https://cloud.githubusercontent.com/assets/847140/10281710/6fffd876-6b44-11e5-8388-40cac15a3286.png)
Blue blocks in the 2nd screenshot are Observatory's javascript.

**Comment by gitarra** [comment]
I see the same behaviour, major stuttering while scrolling. CPU usage of HTTPS Everywhere goes through the roof and I can see warnings about it slowing Firefox down.

**Comment by gitarra** [comment]
This is especially bad if you have JavaScript disabled and all the pictures are downloaded at the same time.

I can cause Firefox to hang infinitely with JS disabled on that site.

**Comment by LMLB** [comment]
I use Windows 7, Firefox 42.0, HTTPS Everywhere 5.1.0 from AMO.
Firefox hangs on the HTTP/2 test on https://www.cloudflare.com/http2/ when Observatory is enabled. It doesn't hang when Observatory is disabled.

**Comment by gloomy-ghost** [comment]
Observatory is gone in the WebExtension release
