### ISSUE TITLE
map.berniesanders.com zoom by zip broken

### ISSUE THREAD

**Issue by BryanQuigley** [EFForg/https-everywhere#3045]
Go here, with Https Everyone on:
http://map.berniesanders.com/#zipcode=08043&distance=50&eventtype=R&eventtype=CW&eventtype=E&eventtype=D&daterange=all-events

Then turn it off, note how it selects the zip code and zooms in.  Also reported to campaign via email with link here.

**Comment by semenko** [comment]
WFM now.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.

**Comment by BryanQuigley** [comment]
Just realized, this only occurs in Firefox not Chrome (I'm also on Linux if that matters).
This still occurs for me (in Firefox) with HTTPS Everywhere 5.1.2 and the beta 5.1.3.

**Comment by BryanQuigley** [comment]
I can't reopen the issue myself afaict...
