### ISSUE TITLE
Opening this gallery is grayed out

### ISSUE THREAD

**Issue by amaru7** [EFForg/https-everywhere#3046]
Hello,

scroll down on this website and click on "Bildergallerie starten" and it will be gray and not show with HTTPSEverywhere, so I had to remove the App.

Please fix it.

http://web.de/magazine/wirtschaft/plagiate-peinlichkeiten-30911058

Thank you.

**Comment by numismatika** [comment]
Web.de doesn't allow tls on that part of the page and redirects to plaintext.
the  UnitedInternet CDN used to power that gallery serves all content via TLS but doesn't allow access from plaintext via CORS headers.
The best solution would be asking UnitedInternet to take out the redirect to plain on the page.

**Comment by amaru7** [comment]
That's too technical, I'm not a webdesign backend expert, but I found out that HTTPSEverywhere allow selective unblocking, so this was a solution. Thanks alot still for your reply.

Love that add on to improve my security and it doesn't normally get in the way to surfing like other security add ons (NoScript for instance)
Date: Wed, 7 Oct 2015 02:37:18 -0700

**Comment by numismatika** [comment]
This one is no longer an issue, bachelor candidates gallery looks fine now. The original url is gone from the archive.

**Comment by DavidLiedke** [comment]
@J0WI can be closed. No problems anymore. 

Test URL:
https://web.de/magazine/unterhaltung/stars/dieter-bohlen-andrea-berg-pop-titan-beendet-zusammenarbeit-schlagersaengerin-32874614
