### ISSUE TITLE
Videos broken on kendte.dk

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#3048]
Report from user: YouTube ruleset breaks videos on http://kendte.dk/5-aarig-pige-charmer-dommere-men-saa-begynder-hun-at-synge/

**Comment by jeremyn** [comment]
I can't get the video to play in Firefox even if I disable HTTPS Everywhere entirely. It works in Chrome without HTTPS Everywhere. Do you know what's going on in Firefox?

**Comment by fuglede** [comment]
I'm also having issues with the site in Firefox, but it looks like it now works in Chrome both with and without the ruleset.
