### ISSUE TITLE
[broken ruleset] Washington Free Beacon (partial)

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#3053]
Breaks the 'stylesheet'

http://freebeacon.com/politics/leaked-audio-clinton-says-supreme-court-is-wrong-on-second-amendment/

**Comment by fuglede** [comment]
Thanks for the fix. I think this should be merged with the ruleset containing problematic target hosts, since there's no reason to have two separate files containing problematic domains.

**Comment by terrorist96** [comment]
How do I do that? Thanks.

**Comment by fuglede** [comment]
What I had in mind was that you could simply take the hosts from <code>Washington_Free_Beacon-problematic.xml</code> (which no longer has an accurate <code>default_off</code> note anyway), put them in <code>Washington_Free_Beacon.xml</code>, and then remove <code>Washington_Free_Beacon-problematic.xml</code>.

**Comment by terrorist96** [comment]
How about now?
