### ISSUE TITLE
Failures in the filters of the Universitat Politècnica de Catalunya

### ISSUE THREAD

**Issue by cubometa** [EFForg/https-everywhere#3058]
- `https://atenea.upc.edu` does not work with HTTPS Everywhere enabled. Apparently, the only rule that’s enabled in this case is the “Google APIs” rule. While the login page is HTTPS, the pages are HTTP once you log in.
- `https://www.upc.edu/saladepremsa/(.*)` does not work with HTTPS Everywhere enabled. The only rule that’s enabled in this case is the “Polytechnic University of Catalonia (partial)” rule.

**Comment by pipboy96** [comment]
Can't reproduce.
