### ISSUE TITLE
SSL Observatory WARN: Failed to initialize NSS component:Error: couldn't find function symbol in library

### ISSUE THREAD

**Issue by gitarra** [EFForg/https-everywhere#3059]
I get the following warning in the Browser Console on Firefox startup:

SSL Observatory WARN: Failed to initialize NSS component:Error: couldn't find function symbol in library

Windows 8.1
Firefox 43.0a2 and 44.0a1

This doesnt happen on Linux.

**Comment by jeremyn** [comment]
This is still active as of Firefox 48.0.2, Windows 10, HTTPS Everywhere 5.2.3.

**Comment by DrunkenSasquatch** [comment]
@jeremyn This is still happening on Firefox 51, HTTPS Everywhere 5.2.9 on all Windows Platforms. Are you aware of what is causing this error?

**Comment by jeremyn** [comment]
@DrunkenSasquatch No, sorry.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
