### ISSUE TITLE
HTTPS Everywhere breaks info.pca.dfn.de certificate download

### ISSUE THREAD

**Issue by genodeftest** [EFForg/https-everywhere#3067]
With HTTPS Everywhere installed and active one cannot download certificates from https://info.pca.dfn.de/uni-erlangen-nuernberg-ca/index.html and other sites below https://info.pca.dfn.de/ which are served though a CDN on http://cdp.pca.dfn.de/
I know that this is an issue in their configuration (and I already contacted them to fix that) but they haven't yet so these certificate downloads don't work.
On a Firefox without HTTPS Everywhere (installed or active) or on other browsers this site works fine.

**Comment by fuglede** [comment]
Good catch, and thanks for letting them know about it.

**Comment by genodeftest** [comment]
Thank you!
