### ISSUE TITLE
www.lemonde.fr, map is not displayed

### ISSUE THREAD

**Issue by promeneur** [EFForg/https-everywhere#3076]
opensuse 13.1 x86_64
FF 41.0
https 5.1.1

map is not displayed
see
http://www.lemonde.fr/les-decodeurs/article/2015/10/15/le-ministere-de-l-interieur-livre-enfin-les-chiffres-de-la-delinquance_4790212_4355770.html

**Comment by fuglede** [comment]
Thanks for the report. This was fixed with 401f473f6bb8ee665f0d5d808e22ed69adac6349.
