### ISSUE TITLE
GiantBomb.com broken

### ISSUE THREAD

**Issue by EmilLassen** [EFForg/https-everywhere#3084]
If you go to giantbomb.com, all graphics, including images are broken and do not load. Disabling the extension fixes the issue.

Thanks and best regards,
Emil

**Comment by fuglede** [comment]
Hi Emil, and thanks for the report. The front page looks fine on both 5.1.1 release and on the current master to me, though. Which version of the extension are you running?

**Comment by HappySkyPoodle** [comment]
@fuglede The front page looks fine, but any content served by Akamai (their CDN), including videos, livestreams and user-contributed content to the wiki is broken. I poked around a little bit in the developer console and HTTPS Everywhere seems to be forcing an HTTPS connection to `fast.cbsi.demdex.net` which has an invalid SSL certificate. I'm not 100% sure if it's the only URL causing problems, but you can try watching any of the Quick Looks (http://www.giantbomb.com/videos/quick-looks/) without registering, for free. Disabling the 'Giant Bomb (partial)' ruleset in HTTP Everywhere fixes the problem.

**Comment by semenko** [comment]
Also renders fine for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
