### ISSUE TITLE
imgur album lightbox loads images over http

### ISSUE THREAD

**Issue by MER-C** [EFForg/https-everywhere#3091]
URLs: https://imgur.com/a/Qjswt https://imgur.com/a/tY98G (any album will do)
HTTPS Everywhere 5.1.1, Firefox 41.0.1 (Linux).

Click to zoom on any image; a non-secure request is made for that image. The mixed content warning shows up. You must have JavaScript enabled.

**Comment by J0WI** [comment]
I can't reproduce. Has this been fixed?

**Comment by MER-C** [comment]
No. I'm using HTTPS Everywhere 5.1.9, Firefox 46.0.1 now. In addition to HTTPS Everywhere, I am also using uBlock Origin 1.7.0, NoScript 2.9.0.11 and RequestPolicy Continued 1.0beta12 (I was using the same combination of extensions previously). NoScript allows imgur.com and ajax.googleapis.com, denies everything else. RequestPolicy denies all. The insecure request shows up on the uBO request log for the latter URL but not the former.

**Comment by J0WI** [comment]
I can't see any insecure request Firefox' network console.
Could try a new with a clean profile and only HTTPS Everywhere installed?

**Comment by MER-C** [comment]
Tried that, same result. The image should pop up with a border over the original page. I can confirm the insecure request does not appear in the network console.

**Comment by J0WI** [comment]
This sounds like a known 'bug' in Firefox.
Firefox triggers the mixed content before we can redirect it. As long as it's just display content, which is not blocked yet, this can be closed.

**Comment by MER-C** [comment]
That sounds plausible. Thanks for your time.
