### ISSUE TITLE
www.peabody.jhu.edu Broken

### ISSUE THREAD

**Issue by kevindb** [EFForg/https-everywhere#3109]
www.peabody.jhu.edu cannot load many insecure elements when the site is loaded over HTTPS. The only works properly when loaded over HTTP.

**Comment by semenko** [comment]
There's definitely mixed content, but I don't see anything that's actually broken -- even videos play.

Can you link me to a broken page / function?

**Comment by kevindb** [comment]
It's subtle. Most importantly, jQuery and "Hubwidget" fail to load. The end result is that the "Upcoming Events" section on both the homepage and the Events pages fails to load any results.

Correct page load over HTTP
![screen shot 2016-01-05 at 8 06 58 am](https://cloud.githubusercontent.com/assets/3468013/12115856/6bd26af2-b383-11e5-9e0b-86d292121a71.png)

Incorrect page load over HTTPS
<img width="523" alt="screen shot 2016-01-05 at 8 06 50 am" src="https://cloud.githubusercontent.com/assets/3468013/12115855/6bd1b60c-b383-11e5-9fb5-37937d3e00a6.png">

**Comment by jeremyn** [comment]
http://www.peabody.jhu.edu is [no longer active in The_Johns_Hopkins_University.xml](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/The_Johns_Hopkins_University.xml#L211) as of at least c7755ae0d44e03ec0cc5970cfa06706b3428de08. Closing issue.
