### ISSUE TITLE
HTTPS Everywhere sometimes causes errors with the extension Disconnect Search

### ISSUE THREAD

**Issue by southorange** [EFForg/https-everywhere#3114]
When using HTTPS Everywhere and Disconnect Search, searching in the search bar **occasionally** causes error such as
```
This extension failed to redirect a network request to https://search.disconnect.me/searchTerms/search?query=example&amp;source=extension&amp;extension=chrome&amp;ses=Google because another extension (HTTPS Everywhere) redirected it to https://www.bing.com/search?q=example&amp;form=MSSRPD.
```
I do not know whether or not it is a HTTPS Everywhere issue or a Disconnect issue.
I am using Chrome 46.0.2490.71 on Windows 8.1 with the extensions, Adblock, Disconnect, Disconnect Search, HTTPS Everywhere and h264ify.

**Comment by semenko** [comment]
Unfortunately, this isn't something we can fix. Multiple extensions redirecting the same page is a known Chrome issue that's not solvable by us (luckily, it usually just throws warnings, and doesn't cause breakage).
