### ISSUE TITLE
iOS Firmware Image Download Broken

### ISSUE THREAD

**Issue by ay-kay** [EFForg/https-everywhere#3124]
Rule to download iOS Firmware Images from appldnld.apple.com seems to be broken:

<rule from="^http://appldnld\.apple\.com/" to="https://a248.e.akamai.net/7/248/51/20120908/appldnld.apple.com/"/>

Example Image File:

http://appldnld.apple.com/ios9.0.2/031-37157-20150930-7ECBD7B0-64A0-11E5-9DC8-58E151D92A8C/iPad2,2_9.0.2_13A452_Restore.ipsw

Recommended Fix:

Update rule to redirect http://applednld.apple.com to https://secure-appldnld.apple.com.

**Comment by timbru31** [comment]
I can confirm this issue, very fatal if you want to download ipsw's manually.

Redirect to
https://a248.e.akamai.net/7/248/51/20120908/appldnld.apple.com/ios9.0.2/031-37157-20150930-7ECBD7B0-64A0-11E5-9DC8-58E151D92A8C/iPad2,2_9.0.2_13A452_Restore.ipsw
