### ISSUE TITLE
EFF ruleset: Chrome redirections broken

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#3126]
In [the EFF ruleset](https://github.com/EFForg/https-everywhere/blob/bcb101723edb31a933b1f4e26cce17c2364da31d/src/chrome/content/rules/EFF.xml#L41-L47) there are too sites mentioned:
https://www.eff.org/sites/all/themes/frontier/images/got-https-e-chrome.png 
and
https://www.eff.org/sites/all/themes/frontier/images/get-https-e-chrome.png
However they return 404 errors. So what should be done with those?

**Comment by J0WI** [comment]
cc @Hainish @jsha

**Comment by jsha** [comment]
These were from a promotion we ran a while ago but no longer run. You can delete them.
