### ISSUE TITLE
Let user to add custom rewrite rule(like ABP)

### ISSUE THREAD

**Issue by espress0** [EFForg/https-everywhere#3134]
URL: [ Rewrite if ] [ Rewrite to ]

http://insecure.server | https://insecure.server

**Comment by fuglede** [comment]
Currently, if you don't feel like building the add-on, in the case of Firefox you can write custom rewrite rules and put them in the directory <code>HTTPSEverywhereUserRules</code> subfolder of your profile folder. The [add-on website](https://www.eff.org/https-everywhere/rulesets) has a bit more information on that.

**Comment by vgturtle127** [comment]
@fuglede Can we close this?

**Comment by anewuser** [comment]
@vgturtle127 Don't you think this is a valid request that would make the creation of rules much simpler? The current method requires you to create new files for each new rule and then restart your browser.

@espress0 Before HTTPS Everywhere is improved, you can use this instead to create rules quickly: [Redirector](https://github.com/einaregilsson/Redirector#download-links).

**Comment by vgturtle127** [comment]
@anewuser I figured since he said something about writing custom rules in the profile folder, that meant that was what he recommended and nothing more was going to be done. I suppose I assumed too much.
