### ISSUE TITLE
represent.colorofchange.org supports TLS

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#3140]

**Comment by strugee** [comment]
Oops, typo.

**Comment by semenko** [comment]
Thanks for the suggestion!

We don't currently have the resources to add rules for small sites when people create GitHub Issues. If you would like to see it add HTTPS Everywhere, please submit a pull request with a new ruleset: https://www.eff.org/https-everywhere/rulesets

**Comment by strugee** [comment]
@semenko I know, I'll probably be sending a bunch over my winter break :)

Mostly I file bugs because _I_ don't have time to add rulesets, and I don't want to forget.
