### ISSUE TITLE
teslamotors.com broken when maxmind.com is blocked

### ISSUE THREAD

**Issue by dset0x** [EFForg/https-everywhere#3145]
In http://www.teslamotors.com/ and http://my.teslamotors.com/models/design?source=homepage most of the content fails to load when maxmind.com blocking is enabled.

**Comment by loveithateit** [comment]
Did you described blocking, did you mean to report a privacy badger issue?

**Comment by dset0x** [comment]
@loveithateit I recall that I was trying to figure out whether it was `https-everywhere` or another add-on that was causing me trouble. Looking at my description, you're probably right. In fact the issue is gone now, so I'm going to go ahead and close this.
