### ISSUE TITLE
NBCSports.com video player not working fully

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#3158]
http://www.nbcsports.com/video/verducci-royals-showcase-something-teams-want-copy

With the Akamai rule enabled the video player controls do not appear.  Disable it and they show up.

**Comment by semenko** [comment]
Works for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Comment by MDawg957** [comment]
I'm still seeing this one come up with HHTPS 5.1.2 on Firefox ESR 38.5.0.  I'm not so familiar with the system, so how would I send a pull request?

**Comment by semenko** [comment]
Still wfm Chrome 49/2015.12.16. Are you running any other extensions (adblock, etc.)?

**Comment by MDawg957** [comment]
I have Adblock Plus.  Disabled it and tested again, still does not work show the controls unless Akamai is disabled.  Same issue on Firefox 43.0.1 64-bit.
