### ISSUE TITLE
QVC.com video not playing

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#3159]
When you attempt to view the live stream the video will never play

http://www.qvc.com/LiveShowDisplay?storeId=10251&catalogId=10151&langId=-1&cm_re=LN-_-QVCTVMENU-_-WATCHLIVETV

http://www.qvc.com/LiveShowDisplay?storeId=10251&catalogId=10151&langId=-1&channelCode=2CH&cm_sp=LIVETV-_-STREAM-_-PLUS

Disabling the Delvenetworks rule fixes this problem.

**Comment by terrorist96** [comment]
http://www.covance.com/

Video doesn't play. Delvenetworks rule causes it to break. @fuglede

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10
I wish the policy would be to immediately deactivate rules that breaks websites, and only to reactivate them after the issue has been fixed, instead of leaving the rules active (i.e. sites broken) while waiting on a fix.

**Comment by terrorist96** [comment]
Still broken in 2016.6.9.

**Comment by Bisaloo** [comment]
This is fixed for me. @MDawg957, can you check it's working for you and if so, close this issue?

**Comment by J0WI** [comment]
Closing due the lack of response.
