### ISSUE TITLE
Breaks dns management on enom.com

### ISSUE THREAD

**Issue by gricey432** [EFForg/https-everywhere#3161]
With https-everywhere enabled I get same-origin request block errors using enom.com 's domain management.
Doesn't happen with https-everywhere disabled.
Firefox

**Comment by loveithateit** [comment]
I'm guessing that enom's management interface is in the clear and loads either iframes or scripts that aren't excluded.

@gricey432 if you could, please provide a pattern of said resources for exclusion, and a few test cases.

**Comment by pipboy96** [comment]
User moved to bitbucket, issue can't be verified without enom.com account, issue created in 2015 without any further comments. Closing. If you believe this is a mistake, contact me.
