### ISSUE TITLE
Https-everywhere 5.1.0 freezes Firefox 42.0 when accessing AOL.com

### ISSUE THREAD

**Issue by JustPeekin** [EFForg/https-everywhere#3162]
Https-everywhere 5.1.0 freezes FFox 42.0 when enabled and accessing AOL.com
AOL Front page will come up fine but the minute u click an article or mail it freezes
Have to "end process" thru taskmgr and restart FFox
when Https disabled - everything runs great

platform:  W7 SP1 Ultimate x64
HP DV7 1tb 8gb ATI Radeon 5650
Flash is disabled by choice - prefer using addons:
 YouTube High Definition ver 41.2 
Simple YouTube HTML 5 video player ver 0.2.38.1
Video without Flash ver 3.1.2

**Comment by foobar13373** [comment]
Current version is 5.1.1, did you try that? It does not crash aol.com for me in FF42 (64 Bit, Windows, but also have uBlock Origin with loads of Filters, maybe it is not aol.com directly)

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
