### ISSUE TITLE
bbb.org xml causes site to throw a 503 error

### ISSUE THREAD

**Issue by ChuckIT** [EFForg/https-everywhere#3163]
Using the bbb.xml ruleset in stable causes the site to throw a 503 error when you attempt to access a report on a bussiness. Investigation from the Error Console reveals that a 404 error is thrown when trying to access https://bbb.org/style/.+. Disabling the bbb.org xml fixes the problem.

**Comment by loveithateit** [comment]
ChuckIT@ could you provide an example url, please.

**Comment by ChuckIT** [comment]
Hi Loveithateit
Here is an example of the URL I was trying to reach.
http://www.bbb.org/kitchener/business-reviews/movers/kingsway-van-lines-in-markham-on-1297240
it results in the 503 error as indicated in the second screen shot.

Assuming they have files missing from https://bbb.org/styles I have informed bbb.org that this could break the site for others as well.

Things work fine once I disable bbb.org (partial) ruleset.

Attached is:
A screenshot of the actual error.
A screen shot of a 404 error that firefox threw prior to hitting the 503. 

![screenshot from 2015-11-04 09 52 14](https://cloud.githubusercontent.com/assets/2983847/11001986/2d796330-8478-11e5-8a57-1400aea628b4.png)
![screenshot from 2015-11-04 15 21 13](https://cloud.githubusercontent.com/assets/2983847/11001987/2d7d4a4a-8478-11e5-8d74-f01c3486a278.png)
![Uploading Screenshot from 2015-11-04 15:21:13.png…]()
