### ISSUE TITLE
Neowin.net forums (page navigation) broken

### ISSUE THREAD

**Issue by corobin** [EFForg/https-everywhere#3164]
Ever since the last update to the Neowin.net forum styles, they're using a JavaScript thing to flip pages. the HTTPS-Everywhere rule is breaking page-changing functionality. e.g. https://www.neowin.net/forum/forum/214-site-announcements/

**Comment by semenko** [comment]
Nav works for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.
