### ISSUE TITLE
GOG.com rule: secure.gog.com is obsolete

### ISSUE THREAD

**Issue by shmerl** [EFForg/https-everywhere#3165]
https://secure.gog.com now redirects to https://www.gog.com so rule should probably be updated to reflect that (to save on extra redirect).

**Comment by redranamber** [comment]
I've done this already, it just needs to be committed. You can see it at https://github.com/redranamber/https-everywhere/commit/cc396c33226ac1dfbde4de377051a9023c732020 and let me know if you have any feedback.

**Comment by shmerl** [comment]
What about the rest of the stuff there (static, favicon, etc.)? Are those not relevant anymore? Your rule is very minimal.

**Comment by redranamber** [comment]
The wildcard (*.gog.com) covers all of their sub-domains. I activated the rule in my Firefox profile for testing and haven't had any issues. Some pages have mixed content being blocked but none of it seems to be important or even noticeable.
