### ISSUE TITLE
stuck on version 5.1.0 if installed from AMO

### ISSUE THREAD

**Issue by vicgarin** [EFForg/https-everywhere#3170]
stuck on version 5.1.0 if installed from AMO

please update the version on AMO regularly

https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

thnx

**Comment by loveithateit** [comment]
afaict, this depends on https://github.com/EFForg/https-everywhere/issues/2612.

**Comment by semenko** [comment]
closed as duplicate per above
