### ISSUE TITLE
Trulia.com : static assets served through trulia-cdn.com are broken on Chrome

### ISSUE THREAD

**Issue by oldhill** [EFForg/https-everywhere#3175]
The trulia-cdn.com rule re-writes certain URLs of Trulia static assets by pre-pending an HTTPS akamai URL: https://a248.e.akamai.net/f/176/831/8m/

This akamai server is currently throwing 503s for these re-written requests, so most static assets aren't loading on trulia.com and other pages on that domain. Disabling the trulia-cdn.com rule fixes the problem.

Current rule set is here: https://github.com/EFForg/https-everywhere/blob/bcb101723edb31a933b1f4e26cce17c2364da31d/src/chrome/content/rules/Trulia-cdn.com.xml

<img width="826" alt="trulia" src="https://cloud.githubusercontent.com/assets/2712276/11022175/eb78668e-860c-11e5-889f-eadbd73a10e7.png">

**Comment by jeremyn** [comment]
Thanks for the report. Pull request #3493 should have fixed this so I'm closing this issue, but please feel free to reopen this issue with a comment if this is still a problem for you.
