### ISSUE TITLE
Add letterboxd.com

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#3180]
http://letterboxd.com/ -> https://letterboxd.com/

**Comment by semenko** [comment]
Thanks for the suggestion!

We don't currently have the resources to add rules for small sites when people create Issues. If you would like to see it add HTTPS Everywhere, please submit a pull request with a new ruleset: https://www.eff.org/https-everywhere/rulesets

**Comment by anewuser** [comment]
Letterboxd isn't exactly a "small website", but I'll leave it up to them to make HTTPS official for all users (they have plans for that).

**Comment by semenko** [comment]
You're also welcome to submit a pull request adding the site :)
