### ISSUE TITLE
Breaks Avast Online Security extension

### ISSUE THREAD

**Issue by goldmandrummer** [EFForg/https-everywhere#3198]
Using latest Chrome on a Macbook Air running El Capitan, I continuously get an extension error from Avast Online Security as shown in the attached image.
![screen shot 2015-11-14 at 1 35 44 am](https://cloud.githubusercontent.com/assets/4130929/11162447/157e6ab6-8a70-11e5-93d2-0b0a63649860.png)

**Comment by semenko** [comment]
Unfortunately, probably not something we can solve. Two extensions trying redirecting the same site will throw warnings in Chrome.
