### ISSUE TITLE
[new ruleset] connect.mheducation.com

### ISSUE THREAD

**Issue by Marsfan** [EFForg/https-everywhere#3215]
the above listed website has some https for the ui, but the core part of the website does not have https.

**Comment by jeremyn** [comment]
Thanks for the issue. This was added recently, though not by me. See [here](https://github.com/EFForg/https-everywhere/blob/69c44f612773494091ca6be3c4f3a6ed571f9327/src/chrome/content/rules/mheducation.com.xml) and [here](https://github.com/EFForg/https-everywhere/blob/69c44f612773494091ca6be3c4f3a6ed571f9327/src/chrome/content/rules/mheducation.com-falsemixed.xml). I'm closing this, but please feel free to reopen it with a comment if needed.
