### ISSUE TITLE
seattle.gov supports TLS

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#3217]
I haven't tested this extensively, though.

**Comment by J0WI** [comment]
got a redirect to http, only subpages seems to work

**Comment by strugee** [comment]
https://seattle.gov returns 404, whereas http://seattle.gov redirects to HTTP. However, https://www.seattle.gov/visiting-seattle works just fine. So I think you're right. Is it all subpages?

**Comment by jeremyn** [comment]
There is already a ruleset for seattle.gov, [City_of_Seattle.xml](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/City_of_Seattle.xml), added in 2012 and later disabled.

**Comment by Riotism** [comment]
Close?
