### ISSUE TITLE
F-Secure Client Security breaks SSL on (false positive) "harmful web sites"

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#3218]
The ruleset for https://www.4shared.com/ breaks the site. It seems like they no longer offer an HTTPS version of the site.

**Comment by anonsubmitter** [comment]
I get a "Secure Connection Failed" notice when I try to access the site over HTTPS.
(If I deactivate the ruleset and try to access the HTTP version, F-Secure Client Security blocks the website because it thinks that 4shared is a harmful website.)

**Comment by fuglede** [comment]
Works fine here;

    $ curl -I https://www.4shared.com
    HTTP/1.1 200 OK

**Comment by anonsubmitter** [comment]
By the way, here is the error code I get: ssl_error_access_denied_alert

**Comment by anonsubmitter** [comment]
I get the exact same warning with https://support.comodo.com/. F-Secure Client Security also believes that this website is harmful and is blocking it as well. I think F-Secure Client Security is the cause of this.

**Comment by fuglede** [comment]
Given Comodo's track record, that's kind of funny. Anyway, closing as not related to HTTPS Everywhere.
