### ISSUE TITLE
Add option to add HSTS-header to all HTTPS-connection

### ISSUE THREAD

**Issue by intchloe** [EFForg/https-everywhere#3220]
If we could instead add an HSTS-header to all HTTPS-connection we will force encryption even further. Also, less requests will be made because we could let HTTPS Everywhere ignore all domains that got the HSTS-header sat manually. 

This could be a optional setting because this could break some sites.

What do you think?

**Comment by J0WI** [comment]
See https://addons.mozilla.org/en-US/firefox/addon/enforce-encryption/

**Comment by vgturtle127** [comment]
@J0WI Can we close this?

**Comment by J0WI** [comment]
Let me ping @fuglede and @jsha if there is any code that we can use for HTTPS Everywhere.

**Comment by fuglede** [comment]
#77 is relevant here. The way I see it, the biggest win in identifying HSTSable rulesets would be in performance, as @diracdeltas also mentions in that post. Work such as #3958 counts in that direction.

**Comment by vgturtle127** [comment]
@J0WI @fuglede By the way, I don't like the term "forced". I would much rather it was an option. I know sending the info along with the header isn't really a forced/option kind of argument, but I just mean we should word it so people don't think if a site is broken they will be out of luck.

I am all for HSTS, but we should be careful how we implement it so it isn't an issue to maintain.

Will this be it's own ruleset, or an addition to the current rulesets?

**Comment by jsha** [comment]
Closing. I don't think it's safe to inject HSTS headers for sites, since that means any certificate error turns into a hard fail (can't click through it). I think it really needs to be at the site owner's discretion to turn on HSTS.
