### ISSUE TITLE
Please add archive.mozilla.org to HTTPS Everywhere's "Mozilla" list

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#3224]
Mozilla recently migrated various logs and binaries from ftp.mozilla.org to archive.mozilla.org.

archive.mozilla.org supports HTTPS; could it be added to the HTTPS Everywhere list for mozilla?

(I believe this will help with the problem described in https://bugzilla.mozilla.org/show_bug.cgi?id=1225303#c0 , where we've got a http://hg.mozilla.org URL which loads content from http://archive.mozilla.org -- and right now, HTTPS Everywhere promotes the hg.m.o URL but not the archive.m.o URL, so the page ends up being broken for HTTPS Everywhere users due to mixed content.  If HTTPS Everywhere promoted the archive.m.o URL, though, then all would be well.)

**Comment by youdly** [comment]
The [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Mozilla.xml) targets all subdomains of Mozilla.org (line 222). There are a few excluded subdomains (e.g. website-archive, www-archive) (line 230), but archive.mozilla.org is not one of them.
When I browse archive.mozilla.org, I can see the ruleset is activated.
Judging by the [URL](https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=http://archive.mozilla.org/pub/mobile/tinderbox-builds/mozilla-inbound-android-api-11/1447698713/mozilla-inbound_ubuntu64_vm_armv7_large_test-plain-reftest-12-bm53-tests1-linux64-build307.txt.gz&only_show_unexpected=1) provided at your bugzilla report, I believe firefox has blocked the request to archive.m.o before HTTPS-E can see it.

**Comment by dholbert** [comment]
Ah, looks like you're right. Sorry for my confusion, & thanks for testing/clarifying.
