### ISSUE TITLE
Kinopoisk.ru's charts broken

### ISSUE THREAD

**Issue by VitalD** [EFForg/https-everywhere#3228]
Charts on site kinopoisk.ru broken with https-everywhere (v. 2015.8.13).
Site uses falsh application to show charts on different pages and this app can't load chart's data files when extention works. 
![image](https://cloud.githubusercontent.com/assets/4930200/11245261/dc02e9c2-8e22-11e5-9390-d4e0445fd6aa.png) 
![image](https://cloud.githubusercontent.com/assets/4930200/11245274/e52a9c5c-8e22-11e5-88e3-fb8cd2fc8b1b.png)

**Comment by J0WI** [comment]
I can't see any errors or graphs, please provide a link.

**Comment by VitalD** [comment]
@J0WI That was a long time ago, I checked current version and graphs works.
