### ISSUE TITLE
https://microsoft.com/ uses a wildcard subdomain cert

### ISSUE THREAD

**Issue by nealey** [EFForg/https-everywhere#3234]
If you go to http://microsoft.com/, something other than their web server (I am guessing HTTPS everywhere, I can't reproduce it, unfortunately, even in incognito mode) redirects to https://microsoft.com/, which uses a cert issued for *.microsoft.com: this triggers a security message in Chrome and FF.

**Comment by fuglede** [comment]
Yep, that's a problem with HTTPS Everywhere. You can reproduce it by disabling the ruleset in the dropdown menu and going to http://microsoft.com. It looks like this could be fixed by redirecting instead http://microsoft.com to https://www.microsoft.com.
