### ISSUE TITLE
Javascript animation double playing on Firefox 42 & Firefox Dev when HTTPS Everywhere is enabled

### ISSUE THREAD

**Issue by mh4it** [EFForg/https-everywhere#3235]
1.Load website haagen-dazs.co.uk
2.Change screen width to study responsive design
3.Modular Tiles reshuffle and justify to the new screen width
4.Using Firefox 42, and Firefox Dev, with HTTPS Everywhere enabled

CSS / Javascript Modular Tiles resettle once with an animation to their new position and then resettle a second time.  They move once correctly and then once settle from the opposite direction.

**Comment by vgturtle127** [comment]
@mh4it Have you tried to use the latest HTTPS Everywhere and Firefox?

**Comment by jeremyn** [comment]
I get the same "double shuffle" behavior on Windows 10 and Firefox 48.0.2 even with HTTPS Everywhere disabled, which means it's not an HTTPS Everywhere problem. @mh4it , do you see that behavior with HTTPS Everywhere disabled too?

**Comment by gloomy-ghost** [comment]
No response from the reporter for a year, closing for now
