### ISSUE TITLE
Netvibes rule broken

### ISSUE THREAD

**Issue by theodoor** [EFForg/https-everywhere#3249]
The rule for netvibes (http://www.netvibes.com) is not working correctly.

**Comment by fuglede** [comment]
Thanks for the report. Could you elaborate on what's wrong with the ruleset? Had a quick look around the site without any problems here.

**Comment by theodoor** [comment]
When I go the website www.netvibes.com it doesn't redirect me to the secure website, but it is available on https://www.netvibes.com. I think the exception in the ruleset almost excludes everything, but not sure about that.

**Comment by fuglede** [comment]
Ah, right, that's almost certainly intentional. The exclusion was added in f813cf6becb4f661dacec963463c5f3a03d867f2 and excludes everything but <code>(?!favicon\.ico|img/|signin(?:$|[?/]))</code>. It might be possible to apply the ruleset to more of the site now, though.

**Comment by theodoor** [comment]
Yes, as if I navigate directly to https://netvibes.com everything looks working fine. Would be great if this can be included in the rules.
