### ISSUE TITLE
bugzil.la supports TLS

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#3266]

**Comment by fuglede** [comment]
Hi @strugee. Could you elaborate a bit on what the issue is here?

**Comment by strugee** [comment]
@fuglede whoops, I'm sorry! I thought we didn't have a ruleset for `bugzil.la`, but we do. Closing.

**Comment by fuglede** [comment]
Ah, cool cool. Worth noting by the way that bugzil.la is on the HSTS preload list which contains many sites not currently covered by HTTPS Everywhere (not that they necessarily should be).
