### ISSUE TITLE
Resist redirects to insecure version

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#3268]
Some websites pass Location header to redirect users visiting HTTPS version to http one to reduce load though they give identical content through http and https. It can be useful to have an option to disable the redirects, the sole effect of which is downgrade.

**Comment by jsha** [comment]
If the site always serves a 301 for a given HTTPS URL, there is no way for HTTPS Everywhere to coerce that site into serving a 200 for that URL instead.

**Comment by KOLANICH** [comment]
In fact I meant 200 with location header or 301/302/307 with non empty body. I rechecked the site, now they return 301 instead of 200 they returned some time ago.
