### ISSUE TITLE
Image loading issues on TheVerge.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#3280]
http://www.theverge.com/2015/11/25/9798952/wu-tang-clan-secret-album-sale-millions

Images aren't loading on sidebars and at the top.  Disabling The Verge.com (partial) fixes the problem.

Firefox 42.0, HTTPSE 5.1.1

**Comment by semenko** [comment]
Thanks for the report! This seems to work for me, so tentatively closing.

Please feel free to reopen if you see this with the latest version!

**Comment by MDawg957** [comment]
Checked with HTTPSE 5.1.5 on Firefox 45.0.1 and it still isn't loading images.

Please re-open.

**Comment by jeremyn** [comment]
http://www.theverge.com was removed from [The-Verge.xml](https://github.com/EFForg/https-everywhere/blob/69c44f612773494091ca6be3c4f3a6ed571f9327/src/chrome/content/rules/The-Verge.xml) in 55932b5939de0376e41d3e55ade84d4c587a475d. In any case the given URL looks okay to me with Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.3.

I'm re-closing this issue, but again please feel free to reopen the issue with a comment if this is still a problem for you.
