### ISSUE TITLE
Rewrite "https://*.gstatic.cn/" to "https://*.gstatic.com/"

### ISSUE THREAD

**Issue by LGA1150** [EFForg/https-everywhere#3298]
`gstatic.cn` cannot be accessed via HTTPS, for example, https://www.gstatic.cn/onebox/weather/64/sunny_s_cloudy.png . It will either timed out or 404.
Rewrite `gstatic.cn` to `gstatic.com` will solve this. https://www.gstatic.com/onebox/weather/64/sunny_s_cloudy.png

**Comment by youdly** [comment]
Similar to https://github.com/EFForg/https-everywhere/issues/2747, adding such rule could affect China users. This is unless (assuming) Google China is currently redirecting `google.*` or `gstatic.*` to `.cn`. My idea to resolve this is to create a separate ruleset to include your proposed rewrite rule, and if China users are somehow affected, they can easily disable that ruleset.
However, there is no `gstatic.cn` [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Google.xml) currently, so this issue only affects website that hardlinks to `https://*.gstatic.cn/`.

**Comment by J0WI** [comment]
Works for me (outside of China)

**Comment by gloomy-ghost** [comment]
Closing as WFM
