### ISSUE TITLE
Rule for Just-Eat

### ISSUE THREAD

**Issue by funkydude** [EFForg/https-everywhere#331]
https://www.just-eat.co.uk/

It fully supports HTTPS. If you log on via HTTPS, it will remember said option instead of knocking you back onto HTTP whilst browsing.

Unfortunately the default is HTTP, a basic rule should suffice.

**Comment by funkydude** [comment]
Does the lag usually last nearly a year?

**Comment by jsha** [comment]
We've had an unusually long gap between stable and development branches because of the huge volume of new rule submissions we've received. We're working on systems to allow us to manage the new, larger corpus without breaking websites. We expect to have a new stable release out soon.
