### ISSUE TITLE
Observatory should compress POST data

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#334]
By default, POST data isn't gzip-encoded. However, since we are posting from an extension we can choose to do so. The Observatory's performance profile is dominated by overly-long connections from clients that are trying to push through a few kilobytes of POST on slowish connections. The POST data is highly compressible. I believe we could significantly improve the Observatory server's performance by compressing POST data on the client side.

**Comment by rolandshoemaker** [comment]
Over the last week I've been fiddling around with unhappy SQL queries on the observatory data and was able to pull out the data below. This confirms the distribution of both certificate and chain sizes are pareto and that the current padding scheme is probably overkill.

The last chart shows an estimated distribution of the padded submissions received based on the chain dist and the dist of a alternative padding scheme along the lines of what @jsha proposed that looks like it would prove somewhat more efficient.

![obs-cert-chain-padding-dist](https://cloud.githubusercontent.com/assets/5080674/11456286/961958aa-9639-11e5-8d20-64d59f065b3a.png)

**Comment by gloomy-ghost** [comment]
Observatory is gone in the WebExtension release
