### ISSUE TITLE
Problem with WDR rule

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#3347]
The rule "Westdeutscher Rundfunk" breaks http://www1.wdr.de/themen/wissen/natur/klimaschutz-tipps-100.html
There I can't click on "voriges Bild" (previous image) and "nächstes Bild" (next image).

**Comment by fuglede** [comment]
Hm, it seems to work here; indeed, the WDR fails the redirect loop test and is disabled automatically.

**Comment by KommX** [comment]
I can still reproduce on Chrome 47.0.2526.73.

**Comment by fuglede** [comment]
Thanks for checking again; it was working in Firefox here. In Chromium, it fails with

    XMLHttpRequest cannot load https://www1.wdr.de/themen/wissen/natur/klimaschutz-tipps-100_imageNo-5.html. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www1.wdr.de' is therefore not allowed access.
