### ISSUE TITLE
IMDB blocked by IMDBPro Sign-up page when HTTPS Everywhere is enabled

### ISSUE THREAD

**Issue by hal-gh** [EFForg/https-everywhere#3351]
I'm currently discussing the issue described in the title with a member of the IMDB Support Team, via their getsatisfaction.com pages:

https://getsatisfaction.com/imdb/topics/cannot-access-user-boards-as-they-are-behind-an-imdbpro-signup-page?topic-reply-list[settings][filter_by]=all&topic-reply-list[settings][page]=1

Could one of the https-everywhere devs get involved so that we can solve this for everyone? Thanks

**Comment by J0WI** [comment]
Can you provide some console output?

**Comment by hal-gh** [comment]
I'm sorry, I no longer use this addon, as it was too difficult to use with these problems.

**Comment by J0WI** [comment]
Sad to hear this. We need the feedback from our users and did much progress in the last few years.
I'll close this since this issue requires someone that has an account on IMDB.

**Comment by nileplumb** [comment]
HI I don't mind helping with this if I can.... I have an imdb account and constantly bump into this issue "log into imdbpro" when simply clicking on the poster image for the film
