### ISSUE TITLE
Not able to disable https-everywhere on IMDB

### ISSUE THREAD

**Issue by hal-gh** [EFForg/https-everywhere#3353]
Note: using Firefox 42.0 on Ubuntu 12.04 (works fine in Chrome)

https-everywhere currently causes problems when browsing IMDB (see #3351, which discusses those issues). In the meantime, could someone explain how to disable it for just IMDB?  I don't see IMDB in the config for the site, even though there is a [rules page](https://www.eff.org/https-everywhere/atlas/domains/imdb.com.html) for IMDB:

![menu_340](https://cloud.githubusercontent.com/assets/133699/11540812/d14f74c8-9926-11e5-866c-601639d07e1d.png)

[menu image](https://imgur.com/Xblcnx5)

What I'd expect is to see "imdb" listed, and to be able to de-select it.

Could someone explain why there isn't an "imdb" option, and how to disable the rules for it?

Thanks

**Comment by J0WI** [comment]
You can only disable a rule when it's used on the page you currently are.
