### ISSUE TITLE
The ruleset for linuxtv.org are disabled and wrong

### ISSUE THREAD

**Issue by mchehab** [EFForg/https-everywhere#3357]
Since Dec, 3, linuxtv.org use valid certs provided by Let's Encrypt, for all domains that it uses:
    linuxtv.org
    patchwork.linuxtv.org
    git.linuxtv.org
    www.linuxtv.org

However, the existing rule for it is currently disabled.

**Comment by J0WI** [comment]
Resolved in #3369
