### ISSUE TITLE
Polygon.com comments not working

### ISSUE THREAD

**Issue by JamesBulman** [EFForg/https-everywhere#3358]
The comment sections on articles are not working with the Polygon.com rule enabled. For example:

http://www.polygon.com/2015/12/3/9847206/konami-prevented-kojima-attending-game-awards-2015

Chrome extension Version: 2015.8.13

Chrome version 47.0.2526.73 m (64-bit) (Windows 10)

**Comment by fuglede** [comment]
Thanks for the report. What is the problem exactly? They show up fine here, but perhaps adding new ones is the problem? And if so, could you have a look in the browser console (F12 in Firefox) and see if any security warnings pop up if you try to submit new ones while the add-on is active?

**Comment by OmanMkII** [comment]
I noticed the same issue at Polygon, as well as some images not loading properly (apparently they were all 1x1 images). I managed to get around it for now by disabling HTTPS for Polygon.com, it fixed the images and the comments for me.

Specifically with the comments, scrolling down to the end of the article would normally load the comments section, but lately it would not load, simply displaying "There was an error loading the comments. Please try again later." I can't see the field to add new comments.

In the console (Chrome Version 47.0.2526.73 m) I have 41 errors and 1 warning. The warning is listed as "The key 'shrink-to-fit' is not recognised and ignored. The errors appear to be identical for multiple parts "Failed to load resource : net : : ERR_BLOCKED_BY_CLIENT".

I'm also running AdBlock Plus and Disconnect, so these errors might be their fault.

Hope that can be of use Fuglede - I have also noticed similar lack of formatting on other webpages, but nothing so significant.

**Comment by JamesBulman** [comment]
This is what I'm seeing with the Polygon.com rule enabled:

![image](https://cloud.githubusercontent.com/assets/11304085/11624100/58059b32-9cc9-11e5-8c22-c0a3c7fbc2f1.png)

This is what I'm seeing without the Polygon.com rule enabled:

![image](https://cloud.githubusercontent.com/assets/11304085/11624140/8fd1f10a-9cc9-11e5-803b-f1d4184d72f4.png)

This was from my Chrome developer console:

[www.polygon.com Developer Console Log.txt](https://github.com/EFForg/https-everywhere/files/53720/www.polygon.com.Developer.Console.Log.txt)

I'm also running Ghostery and uBlock Origin, I've tried disabling them and it doesn't fix the problem, only disabling the HTTPS Everywhere Polygon.com rule fixes it.

**Comment by MDawg957** [comment]
I'm also seeing the same issue in HTTPSE 5.1.2 on Firefox ESR 38.5.0.  Disabling the Polygon.com rule has comments load correctly.  I also have Adblock Plus, but no other blocking extensions.

**Comment by justlurking** [comment]
Also seeing the same problem on Polygon.com as described by @JamesBulman.  Similarly, disabling the Polygon rule results in the comments section loading.

**Comment by numismatika** [comment]
(Reason: CORS header 'Access-Control-Allow-Origin' missing).
The site only has TLS active for some of the resources and loading the secured comments from within a non-secured page fails.
A simple exclusion might fix it.

**Comment by numismatika** [comment]
(Reason: CORS header 'Access-Control-Allow-Origin' missing).
The site only has TLS active for some of the resources and loading the secured comments from within a non-secured page fails.
A simple exclusion might fix it.

**Comment by numismatika** [comment]
```<exclusion pattern="^http://www\.polygon\.com/comments/load_comments/" /> ```
brings comments back

**Comment by numismatika** [comment]
#3610 should solve it
