### ISSUE TITLE
SpamCop broken without www.

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#3360]
https://spamcop.net/:

```
spamcop.net uses an invalid security certificate. The certificate is only valid for the following names: a248.e.akamai.net, *.akamaihd.net, *.akamaihd-staging.net, *.akamaized.net, *.akamaized-staging.net
```

Ater disabling HTTPS Everywhere on that site, http://spamcop.net/ redirects to https://www.spamcop.net/, which works fine.

**Comment by fuglede** [comment]
Thanks for the report; this was fixed in 417a44a430c74d7f98fec3b20d57bad28c85d074 and the surrounding commits.
