### ISSUE TITLE
Access denied on ruleset guide and atlas site on eff.org

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#3366]
I get a 403 ("Access denied") error when trying to access https://www.eff.org/https-everywhere/rulesets.
Same with https://www.eff.org/https-everywhere/atlas/index.html?q.

![access denied](https://pbs.twimg.com/media/CUS-DkfXAAAamSN.png:large)

/cc @efforg

**Comment by fuglede** [comment]
Looks like it's up again with URLs having changed; see e.g. https://www.eff.org/https-everywhere/atlas/letters/q.html

**Comment by rugk** [comment]
> Looks like it's up again with URLs having changed; see e.g. https://www.eff.org/https-everywhere/atlas/letters/q.html

But still a bit broken. Just click on the header/ruleset name or a number and you'll get the 403 error again.

**Comment by J0WI** [comment]
seems fixed.

**Comment by rugk** [comment]
No I still get a 403 error when searching for "q" in the Atlas: https://www.eff.org/https-everywhere/atlas/?q

**Comment by fuglede** [comment]
I'm also getting 403s.

**Comment by J0WI** [comment]
Ah, I can reproduce when searching for `q`, but not when clicking on the letter `Q`.
/cc @Hainish

**Comment by Hainish** [comment]
Interesting, this seems only to happen for queries starting with "q" - I wonder if this is some IDS at play.  I'll follow up.

**Comment by Hainish** [comment]
Fixed now.

**Comment by rugk** [comment]
Just because I am curious: What was the reason?

**Comment by Hainish** [comment]
This was a result of a security measure which was intended to be applied to other areas of our website, not the Atlas.

**Comment by rugk** [comment]
Thx for your information.
