### ISSUE TITLE
Does not work with direct URL typing

### ISSUE THREAD

**Issue by NicoHood** [EFForg/https-everywhere#3385]
If I type something in the url box like `nintendo.de` it is resolved as http, not https.

**Comment by KommX** [comment]
https-everywhere DOES work like this.
In the case of nintendo.de there is already a rule which was introduced after publishing the last release. It will be part of the next release I guess.

**Comment by NicoHood** [comment]
https://elementary.io/ Also does not switch automatically. Why cant the addon try to load https and load http if it fails? Why do we need a list for this?

**Comment by KommX** [comment]
The reason why https everywhere doesn't do this is that some servers deliver content via https but the site breaks, e.g. (you have to disable the Ruhr-Uni-Bochum.de (partial) rule or the whole add-on)
http://www.ruhr-uni-bochum.de/studierendensekretariat/studium/einschreibung/gasthoerer.html.de
https://www.ruhr-uni-bochum.de/studierendensekretariat/studium/einschreibung/gasthoerer.html.de

But there is an add-on that does exactly what you want:
https://code.google.com/p/https-finder/

Unfortunately the last version of this add-on is very old.

**Comment by NicoHood** [comment]
Okay so someone should add this website and close the issue?

**Comment by KommX** [comment]
A rule for elementary.io was already written. You can see it here:
https://www.eff.org/https-everywhere/atlas/domains/elementary.io.html

**Comment by semenko** [comment]
Closed per above.
