### ISSUE TITLE
Issue with dropdown lists

### ISSUE THREAD

**Issue by kalpetros** [EFForg/https-everywhere#3392]
When HTTPS everywhere is enabled some dropdown lists don't work.

HTTPS everwhere **enabled**
![onpaste 20151211-000912](https://cloud.githubusercontent.com/assets/5626758/11730121/a67bbd30-9f9b-11e5-869e-d4d69b6ba148.png)
HTTPS everywhere **disabled**
![onpaste 20151211-001039](https://cloud.githubusercontent.com/assets/5626758/11730122/a67f31c2-9f9b-11e5-9aa7-94103902ed3e.png)

**Comment by reedy** [comment]
On what website?

Check your JS console?

**Comment by kalpetros** [comment]
I get the following error:
>XMLHttpRequest cannot load https://en.aegeanair.com/sys/flights/airports?airport=&airline=&expandGroups=False&hideGroups=False&direction=from&lang=en. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://en.aegeanair.com' is therefore not allowed access.

**Comment by galeksandrp** [comment]
@J0WI This is fixed by #4931
