### ISSUE TITLE
Issue with Variety.com rule

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#3394]
https://variety.com/2015/film/news/golden-globe-nominations-2016-scorecard-20th-century-fox-netflix-1201658230/

With Variety.com (partial) enabled the site goes into a continual loading loop that it never seems to get out of.  Disabling the rule gets the page to load properly.

HTTPSE 5.1.0, Firefox ESR 38.4.0

**Comment by semenko** [comment]
Thanks for the report!

If you have the time, it'd be great if you could submit a small pull request excluding that domain.

**Comment by semenko** [comment]
Appears fixed per above commits

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.

**Comment by MDawg957** [comment]
Checked with HTTPSE 5.1.5 on Firefox 45.0.1 and it is still doing the looping issue.

**Comment by J0WI** [comment]
They are now HTTPS by default, so I'm closing this again.
