### ISSUE TITLE
http://www.independent.co.uk/ moved certificate

### ISSUE THREAD

**Issue by adde9708** [EFForg/https-everywhere#3397]
The rule now breaks the site completely just shows it like in directory style with a bunch of  links.
But seems like the cert has moved to a.ssl.fastly.net. So it mismatches. You can try to add that domain to the rule.Just a tip

**Comment by semenko** [comment]
Appears fixed per above commits

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
