### ISSUE TITLE
Washingtonpost

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#3425]
Is [the ruleset](https://github.com/EFForg/https-everywhere/blob/9a6b31c86cae4b77a182a1883af3942998c8900a/src/chrome/content/rules/Washington-Post-Company.xml) up to date?

> Today, more than 99% of our traffic is redirected to HTTPS.

https://developer.washingtonpost.com/pb/blog/post/2015/12/10/moving-the-washington-post-to-https

**Comment by oxguy3** [comment]
Ruleset is definitely out of date. HTTPS Everywhere tries to force HTTPS on voices.washingtonpost.com, but that domain doesn't properly support HTTPS and is thus completely inaccessible with HTTPS Everywhere installed.

**Comment by semenko** [comment]
Appears fixed per above commits
