### ISSUE TITLE
Add amazon.co.uk

### ISSUE THREAD

**Issue by ukaccount123** [EFForg/https-everywhere#3444]
Defaults to non-https http://www.amazon.co.uk/ but appears to support it without issues, at least on the main pages https://www.amazon.co.uk/

**Comment by drmike** [comment]
I just came up to mention that the main site http://amazon.com stays as non-https.  Maybe all of Amazon's domains need to be checked.

**Comment by vgturtle127** [comment]
@ukaccount123 @drmike Good catch!

@fuglede @jsha Have you guys seen this?

I thought the rule was changed last year because Amazon kept breaking under HTTPS?

**Comment by drmike** [comment]
>I thought the rule was changed last year because Amazon kept breaking under HTTPS?

That may be still true.  I haven't done any testing on this.  When I visited the github issue list, I saw this and another ticket and just added my 2 cents.

#2133 is the issue in question I believe.

**Comment by vgturtle127** [comment]
@drmike In that issue it says it isn't currently supported, but that is not the case anymore, so I say we add a new rule.

**Comment by J0WI** [comment]
closed by #4997

**Comment by vgturtle127** [comment]
@J0WI Thanks!
