### ISSUE TITLE
Further issues on bahn.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#3465]
![bahn](https://cloud.githubusercontent.com/assets/7859245/11840911/dca56eb2-a3f9-11e5-9cbe-45caf837cbf0.png)

Lately I have some problems on bahn.de when searching for connections (see screenshot). There are some images missing and the function to expand connection details isn't working well.
Can others reproduce this? Is this a problem with our rule or do they simply have performance issues?

**Comment by J0WI** [comment]
I have no issues here. Could you post a link?

**Comment by KommX** [comment]
I can't reproduce anymore. I think that I just observed performance issues on their side.
