### ISSUE TITLE
Not verified for use in Firefox and thus disabled.

### ISSUE THREAD

**Issue by BrodyHolden** [EFForg/https-everywhere#3466]
When viewing about:addons in Firefox, it states that "HTTPS-Everywhere could not be verified for use in Firefox and has been disabled." There does not seem to be a way to manually enable the add-on.

Tested on Firefox 43.0 on Ubuntu 14.04 LTS.

**Comment by jsha** [comment]
Which version of HTTPS Everywhere?

**Comment by BrodyHolden** [comment]
I was using 5.1.1.
I updated to 5.1.2 and it works now.
