### ISSUE TITLE
Bad rewrite for easychair.org/smart-program

### ISSUE THREAD

**Issue by catalin-hritcu** [EFForg/https-everywhere#3472]
The following working link:
http://easychair.org/smart-program/CPP2016/
is rewritten to the following 404 Not Found link:
https://easychair.org/smart-program/CPP2016/
There are already quite a few exceptions in the rule for easychair.org:
https://www.eff.org/https-everywhere/atlas/domains/easychair.org.html
so you'll probably need to add one more for `smart-program`.

Anyway, we're trying to link to this program from a conference website (https://people.csail.mit.edu/adamc/cpp16/) and it's important that it works for all our users.

**Comment by catalin-hritcu** [comment]
The EasyChair Support Team answered that they "are planning to change all our Web pages to https, it will take a bit of time though."  I think that until that happens adding an exception would be great.

**Comment by stephen304** [comment]
I took a look at this, and while I don't have a nice solution (yet?), I noticed that using www. bypasses the rewrite: http://www.easychair.org/smart-program/CPP2016/

**Comment by catalin-hritcu** [comment]
@stephen304  This is a nice workaround, thanks a lot.

**Comment by Bisaloo** [comment]
This is no longer an issue as far as I can tell since `easychair.org` now supports HTTPS and this ruleset is currently off by default. I'm closing this issue.
