### ISSUE TITLE
Some issues with Firefox

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#3479]
First of all, I don't know if you guys have been signing new releases on your website, but Firefox keeps telling me it won't install anything form the website unless it has been signed.

So, my idea was you guys could just link to the official pages where the addon/extension can be downloaded (Chrome webstore, Mozilla extension repository, etc.) instead of having local versions on your website. Of course, you may want to still have the option to install them from your site since websites do go down occasionally. But have it as a secondary option instead.

Second, on nightly builds of Firefox, SSL Observatory settings won't open. Not sure what the cause is, but I thought I would mention it.

**Comment by jsha** [comment]
We've been doing our best to comply with Mozilla's new requirements, but there have been some glitches along the way. What version of Firefox, what platform, and what version of HTTPS Everywhere are you trying to install?

**Comment by vgturtle127** [comment]
64-bit Firefox 43.0 EME-free, 64-bit Windows 10 Pro, HTTPS Everywhere 5.0.9

As far as I can tell, everything runs fantastic except the fact that sometimes when there is an update or I install directly from the website it tells me it isn't signed and that it won't keep my current installation. Installing from the Mozilla extension repository helps, so I'm sure that is the problem. I'm not sure if signed .xpi files can be distributed outside of the Mozilla extension repository, but I suppose you could try it and see if that helps? :question:

**Comment by jsha** [comment]
It is possible to distributed signed xpi files outside of AMO, and that's what we've done for 5.1.0, 5.1.1, and 5.1.2. Is there any particular reason you're trying to install 5.0.9?

**Comment by vgturtle127** [comment]
That is the version it gave me when I tried to download it from both sites?

I am using the latest version of Firefox, and when I try it with Chrome, Opera, and Firefox developer edition it does the same thing. Latest versions of all those too.

Really weird bug or something?

**Comment by robertvanbregt** [comment]
When I re-install from the EFF website, it is working, but after I restart Firefox, the extension is disabled. Running FF 43.0.4 on Mac OS X.

**Comment by robertvanbregt** [comment]
Related to #2051.

**Comment by vgturtle127** [comment]
@jsha We should probably fix the version numbers in the addon, as they are incorrect. The version I have is still labeled 5.0.9 in the about window, and 5.1.0 in the Firefox addon menu. But I am assuming that I am running 5.1.2...

**Comment by vgturtle127** [comment]
@jsha The version numbers issue has been rectified.
