### ISSUE TITLE
Internet.org web font doesn't load

### ISSUE THREAD

**Issue by andreasbovens** [EFForg/https-everywhere#349]
When the HTTPS Everywhere extension is turned on (in Opera), the web font on http://internet.org/projects doesn't load.

Once the extension is disabled, everything works fine again.

**Comment by julianladisch** [comment]
What is the URL of the font that http://internet.org/projects tries to load?  I cannot reproduce the problem.

**Comment by KommX** [comment]
Is this bug really still open? I can't reproduce.

**Comment by stevenmg** [comment]
I am no longer able to reproduce the problem in Firefox 37 so it is probably safe to close it.

**Comment by semenko** [comment]
Same.
