### ISSUE TITLE
Cloudfront breaks campus.codeschool.com

### ISSUE THREAD

**Issue by FriendFX** [EFForg/https-everywhere#3500]
Specifically, I am looking at [this page](http://campus.codeschool.com/courses/shaping-up-with-angular-js/level/1/section/1/creating-a-store-module) which doesn't succeed when I click the "Check my work" button.

When I disable the "Cloudfront" rule through the HTTPS Everywhere button, the site works as expected.

**Comment by tancrackers** [comment]
It also breaks video playback:
http://www.breitbart.com/video/2015/12/20/trump-hillary-is-a-liar-she-lies-like-crazy-about-everything/

**Comment by numismatika** [comment]
@FriendFX it is a cross origin request issue. (trying to load a secure content from within an insecure page)
You should ask Codeschool to extend TLS support to their campus subdomain.

**Comment by numismatika** [comment]
@tancrackers it isn't cloudfront on your page, but the same issue, the player can't handle the rewrite of its urls. You should go to Ooyala  and breitbart to get it fixed. You can't make exceptions with conditions for pages that get embedded on multiple other pages.

**Comment by JasonMFry** [comment]
I'm having this issue on CodeSchool, too.  I've contacted them to have them extend TLS support that @numismatika mentioned.  Anyone else with this issue please reach out to them at https://codeschool.reamaze.com/conversations/new.  In their FAQs they say,

> Some of our newer courses also use some advanced browser features for caching content and using localStorage. And furthermore we run into issues validating code when users are running Chrome Extensions (AdBlock, HTTPSeverywhere, DoNotTrack or ModHeader in particular).

**Comment by pipboy96** [comment]
Website no longer exists, it's now a part of Pluralsight.
