### ISSUE TITLE
Yidio.com search not working

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#3505]
http://www.yidio.com/

If I try and use the search box at the top of the page, it does not work.  Disabling the Google APIs ruleset gets things working properly again.

HTTPSE 5.1.2, Firefox ESR 38.5.0, Windows 7 64-bit

**Comment by jeremyn** [comment]
This works for me with Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.3. Is this still a problem for you?

**Comment by MDawg957** [comment]
@jeremyn Confirmed as working in HTTPSE 5.2.4 with Windows 7 and Firefox 48.0.2.

**Comment by jeremyn** [comment]
Thanks.
