### ISSUE TITLE
add ruleset for blog.fefe.de

### ISSUE THREAD

**Issue by sjjh** [EFForg/https-everywhere#3510]
Following rule should add support for https://blog.fefe.de

    <ruleset name="Fefes Blog">
            <target host="blog.fefe.de" />

            <rule from="^http:"
                    to="https:" />
    </ruleset>

**Comment by semenko** [comment]
Thanks! Do you think you could add create a [pull request](https://help.github.com/articles/using-pull-requests/) with that rule?

**Comment by sjjh** [comment]
Done:  #3515
I hope I did everything correct. The rule is untested (but looks trivial to me).

**Comment by sjjh** [comment]
The change seems non-trivial to me any more, I don't have the necessary knowledge of the xml file structure. I hope you can get the idea of what I wanted to archive in my second pull request.

**Comment by numismatika** [comment]
@semenko did you check the certs before merging?
https://www.ssllabs.com/ssltest/analyze.html?d=blog.fefe.de&latest and related seem to be back at the CACert stuff with:
Strict Transport Security (HSTS) 	Yes   TOO SHORT (less than 180 days)
Issuer 	CA Cert Signing Authority

seems like either trolling or a rather short test of LE

**Comment by sjjh** [comment]
I can confirm that the site is from Let's encrypt back to CAcert. Maybe rollback and wait until the sites certificates get more stable.

**Comment by semenko** [comment]
Sorta confused -- the entry at https://www.ssllabs.com/ssltest/analyze.html?d=blog.fefe.de shows LE certs. Their blog post seems to say they fixed the issue, and chrome was showing stale data.
