### ISSUE TITLE
Pbsrc.com STILL breaks photobucket functionality

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#3527]
This was reported as an issue in the 2015.8.13 version and is still an outstanding issue in 2015.12.16.

Pbsrc.com breaks flash copy action in the Email & IM, Direct, HTML, IMG fields:
http://s721.photobucket.com/user/terrorist96/media/ghgdsfghfd_zps0378f4b9.png.html

**Comment by terrorist96** [comment]
This is still broken in Version: 2016.2.18

**Comment by terrorist96** [comment]
Still broken in Version: 2016.3.23

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10 :sob:

**Comment by J0WI** [comment]
I would try the following fix:
```
<exclusion pattern="^http://pic2\.pbsrc\.com/flash/ZeroClipboardFV3\.swf">
```
This also requires to add a test url:
```
<test url="http://pic2.pbsrc.com/flash/ZeroClipboardFV3.swf">
```
Furthermore, the issue should be documented in the ruleset.

**Comment by J0WI** [comment]
Reopen, see https://github.com/EFForg/https-everywhere/pull/4796#issuecomment-225250030

**Comment by terrorist96** [comment]
Looks to be fixed now.

**Comment by terrorist96** [comment]
Actually never mind. Still broken. See:
http://media.photobucket.com/user/ThomasLovesJeremy/media/tumblr_m2lvj8gtln1qhzv6oo1_500.gif.html?filters[term]=animated%20gifs&filters[primary]=images&filters[featured_media]=1748&filters[secondary]=videos&sort=1&o=2

**Comment by terrorist96** [comment]
Can't reproduce anymore.
