### ISSUE TITLE
nVidia.com (partial) breaks shield.nvidia.com

### ISSUE THREAD

**Issue by stephen304** [EFForg/https-everywhere#3538]
Some images don't load on the following URL with the nVidia.com (partial) rule, which is enabled by default:
http://shield.nvidia.com/android-tv

Screenshots:
![screenshot 2015-12-19 12 33 17](https://cloud.githubusercontent.com/assets/981915/11914360/ff9ed9b2-a64c-11e5-913b-c1332b7a4afa.png)

The relevant rule file seems to be:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/NVidia.xml

The problem seems to boil down to the akamai CDN - the rule redirects the whole page to an akamai url for the html, which loads fine, but some relatively reverenced recources (images and icons or icon font) don't seem to be present in their relative locations on the CDN.

Page redirect, which is fine:
http://shield.nvidia.com/android-tv
https://a248.e.akamai.net/f/248/10/10/shield.nvidia.com/android-tv

Relative resource which is not present on the CDN:
Exact link: /images/holiday-bundle/free-remote-bundle.png
Normal URL: http://shield.nvidia.com/images/holiday-bundle/free-remote-bundle.png
CDN URL (fails): https://a248.e.akamai.net/images/holiday-bundle/free-remote-bundle.png
Correct CDN URL: https://a248.e.akamai.net/f/248/10/10/shield.nvidia.com/images/holiday-bundle/free-remote-bundle.png

I'm not sure how we would fix this, and I barely understand the rule, so if anybody else wants to take a stab at this that'd be great.

**Comment by numismatika** [comment]
we fix it this way:
replace

```

	<rule from="^http://(http\.developer|(?:developer|international|us)\.download|shield)\.nvidia\.com/"
		to="https://a248.e.akamai.net/f/248/10/10/$1.nvidia.com/" />
```
with
```
	<rule from="^http://(http\.developer|(?:developer|international|us)\.download)\.nvidia\.com/"
		to="https://a248.e.akamai.net/f/248/10/10/$1.nvidia.com/" />
```

so http://shield.nvidia.com/android-tv gets redirected to https://shield.nvidia.com/android-tv
The only issue seems to be a blocked favicon that gets marked as mixed content.

**Comment by numismatika** [comment]
Done in #3611
