### ISSUE TITLE
chrome/content/rules/Hartwork-Project-mismatches.xml mixes up hartwork.org and .de

### ISSUE THREAD

**Issue by hartwork** [EFForg/https-everywhere#358]
Hello!

I just stumbled upon `chrome/content/rules/`[Hartwork-Project-mismatches.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Hartwork-Project-mismatches.xml).

I opened this ticket because:

 * the related SSL certificate is not self-signed any more
 * hartwork.de is some other website, hartwork.org is what you seem to refer to. binera.de is correct, though.

**Comment by StevenRoddis** [comment]
Was this ever fixed?

| host | status |
| ------ | ------- |
| binera.de | mismatch |
| hartwork.de | doesn't support TLS |
| hartwork.org | valid cert |
| blog.hartwork.org | valid cert |

Given this is a cross domain redirection shouldn't we take more care in verifying that binera.de wants to be redirect to hartwork.org?

```
$ curl -i -X HEAD www.binera.de
HTTP/1.1 302 Found
Date: Fri, 23 Jan 2015 02:44:44 GMT
Server: Apache/2.2.22
Location: http://www.hartwork.org/
Connection: close
Content-Type: text/html; charset=iso-8859-1
```
```
curl -I -X HEAD www.binera.de
HTTP/1.1 302 Found
Date: Fri, 23 Jan 2015 02:45:10 GMT
Server: Apache/2.2.22
Location: http://www.hartwork.org/
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

@2d1 I need some help:

* src/chrome/content/rules/Hartwork-Project-mismatches.xml exists in `master`
* src/chrome/content/rules/Hartwork-Project.xml exists in `4.0` and `master`

How do I deal with this? Should I make a commit into `master` and another into `4.0`? Can I do this all in one PR?



exist in

**Comment by hartwork** [comment]
I would like to repeat/emphasize that hartwork.**de** has nothing to do with hartwork.**org**/binera.de. Only the latter two are mine.

**Comment by StevenRoddis** [comment]
@hartwork thanks I plan to remove the rules for `hartwork.de` no idea how they got in there.
