### ISSUE TITLE
Tiscali.it problem

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#3583]
Related to https://github.com/EFForg/https-everywhere/issues/2427 
The rule for this domain is disabled by default.
I'm on firefox 43.0, https everywhere 5.1.2.
With https everywhere enabled I can login into the webmail, but I can't go from the dashboard (http://mail.tiscali.it/?_task=mail&_action=plugin.tiscali_dashboard) to the inbox folder (http://mail.tiscali.it/?_task=mail&t_tab=folder&_mbox=INBOX), write a new mail (http://mail.tiscali.it/?_task=mail&_action=compose), the draft folder (http://mail.tiscali.it/?_page=1&_task=mail&_mbox=Draft), the sent folder (http://mail.tiscali.it/?_page=1&_task=mail&_mbox=Sent), and in general I can't browse the webmail, it just reloads the dashboard.
If I disable all of the rules for other domains on tiscali.it I can't browse the webmail.
Only when I completely disable https everywhere the webmail works as expected.

**Comment by J0WI** [comment]
The rules has been updated recently.
Can you check if the bug was fixed? Please post the errors showing in the console.

**Comment by fvmrc** [comment]
Tried again  on firefox 45.0, https everywhere 5.1.5.
I still have that exact same problem.
If I disable all of the rules for other domains on tiscali.it I still have this problem.
Everything works correctly when I disable https everywhere.
Here is the output of the console when i click on various links on the navigation bar:
https://gist.github.com/fvmrc/31fcc76ac6837c10dbe3

**Comment by pipboy96** [comment]
Can't reproduce without account, author is @ghost, old versions of rulesets, browser and extension, last heard from in 2016.
