### ISSUE TITLE
Theverge.com problem

### ISSUE THREAD

**Issue by fvmrc** [EFForg/https-everywhere#3584]
Related to https://github.com/EFForg/https-everywhere/issues/1299, https://github.com/EFForg/https-everywhere/issues/3358.
The rule for theverge.com is disabled by default.
Comments won't be displayed.
 I'm on firefox 43.0, https everywhere 5.1.2.
You just get the error: There was an error loading the comments. Please try again later.
If I disable https everywhere, everything works as expected.
eg: http://www.theverge.com/2015/12/20/10631330/iphone-camera-team-800-people#comments, and click on READ THEM.

**Comment by numismatika** [comment]
```<exclusion pattern="^http://www\.theverge\.com/comments/load_comments/" />```
for now.
It is a CORS problem, although it shouldn't happen if the rule is disabled anyway ;)

**Comment by numismatika** [comment]
#3610 should fix it, till they do a proper fix.
