### ISSUE TITLE
Cannot view custom rules I made in HTTPS everywhere Enable/Disable Rules box

### ISSUE THREAD

**Issue by vicgarin** [EFForg/https-everywhere#360]
Cannot view custom rules I made in HTTPS everywhere Enable/Disable Rules box

**Comment by wickles** [comment]
I would like this feature, it is sorely missing.

**Comment by jeremyn** [comment]
Custom rules currently show up for enabling/disabling. If you add the following custom ruleset file as described [here](https://www.eff.org/https-everywhere/rulesets#testing):

```xml
 <ruleset name="My Rules">
	<target host="www.eff.org" />

	<rule from="^http:" to="https:" />
</ruleset>
```

and go to https://www.eff.org , you should see `My Rules` under `Enable/Disable Rules`.

I'm closing this issue, but please feel free to reopen it with a comment if needed.
