### ISSUE TITLE
Website for submiting rules?

### ISSUE THREAD

**Issue by lqf96** [EFForg/https-everywhere#3601]
Currently the only way to submit HTTPS everywhere rules is to use git, which i personally think is not enough. HTTPS is going to be widely deployed, more and more people are going to learn the importance of a secure website. Yet most of them are not programmers or computer enthusiasts and they don't know how to use git or using CLI tools to create a rule... So I think a website where people can submit rules will be a good idea.

**Comment by fuglede** [comment]
With the risk of sounding slightly flippant: Sort of like [this website for submitting rules](https://github.com/EFForg/https-everywhere/new/master/src/chrome/content/rules)?

**Comment by semenko** [comment]
Perhaps we'll improve this if github adds features in the future. Otherwise probably a ~wontfix.
