### ISSUE TITLE
Breaks comments on theguardian.com in Firefox

### ISSUE THREAD

**Issue by OliverJAsh** [EFForg/https-everywhere#3609]
E.g. comments on http://www.theguardian.com/australia-news/2015/dec/24/tony-abbott-defends-threatened-statue-of-father-of-apartheid-cecil-rhodes.

**Comment by OliverJAsh** [comment]
This is because an XHR is made with a protocol relative URL, which seems to resolve to HTTP, which the plugin doesn't like and thus the request fails.

**Comment by RadicalRadish** [comment]
For a workaround to this broken comments issue on the Guardian see the following thread: https://github.com/EFForg/https-everywhere/issues/3862

The third post there gives the workaround.

Hope this helps.
