### ISSUE TITLE
Test for RC4-only https sites before 2016 browser deprecation

### ISSUE THREAD

**Issue by ukaccount123** [EFForg/https-everywhere#3627]
Not sure if this has been posted before...

In (early!) 2016 all of the major browsers will stop supporting RC4 cipher-suites for HTTPS, as reported [here](http://venturebeat.com/2015/09/01/google-microsoft-and-mozilla-will-drop-rc4-support-in-chrome-edge-ie-and-firefox-next-year/).

Therefore sites which only support RC4 cipher-suites for https, such as https://identity.virginmedia.com as [shown by SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=identity.virginmedia.com), will be unreachable unless they also support insecure http connections.

We should test all of our rules for sites that only support RC4 cipher-suites so that we don't denial-of-service HTTPS-Everywhere users.

edit: of course, some sites will quickly get complaints from users after browser updates and switch to supporting newer cipher-suites, but we can't accurately tell which ones these are.

**Comment by J0WI** [comment]
Some rules are already commented, I'll have a look at them.

**Comment by semenko** [comment]
Fixed per above.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
