### ISSUE TITLE
Tavis CI: Check for bad securecookie

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#3636]
As said [in this PR](https://github.com/EFForg/https-everywhere/pull/3488#issuecomment-165504924) it would be a good thing to check whether there are wrong characters at the end of the securecookie domain [as fixed in this PR](https://github.com/EFForg/https-everywhere/pull/3188).

**Comment by semenko** [comment]
Appears fixed per above?

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
