### ISSUE TITLE
Breaks digitalocean.com

### ISSUE THREAD

**Issue by 0sinner** [EFForg/https-everywhere#3697]
Hello HTTPS Everywhere community. Long time user, you guys are awesome.

I noticed an issue with DigitalOcean.com today that I initially sent a support ticket to them about, but later discovered (by disabling and enabling my various extensions) that HTTPS Everywhere is breaking the site.

The behaviour is as follows:
When I open the login page at: https://cloud.digitalocean.com/login the following session cookie is created:
```
Name: Wed Dec 30 2015 13:56:15 GMT-0500 (Eastern Standard Time)
Value: IldlZ...lKSI=
(NOTE I have shortened the value as I don't know what information is encoded and I don't want to open myself up for session hijacking or anything like that).
Domain: cloud.digitalocean.com
Path: /
Size: 137
HTTP: N
Secure: Y
```

Refreshing the page creates a new cookie with a slightly different value but the name is an updated timestamp (so refreshing created a new cookie named "Wed Dec 30 2015 14:00:32 GMT-0500 (Eastern Standard Time)	" etc).

In effect every page load creates a new cookie, so as I'm navigating the dashboard these cookies accumulate. Eventually I get a 400 Bad Request from DigitalOcean, and am unable to navigate further until I clear my cookies for the domain and re-login.

Is this a known issue? Can someone help me? Let me know if you need more details or troubleshooting...

Using the latest Chrome browser with HTTPS Everywhere version 2015.12.16

**Comment by 0sinner** [comment]
Thank you loveithateit for addressing this issue.

I'm not familiar with HTTPSEverywhere's release schedule when should I expect to see the fix in the live plugin?

**Comment by jsha** [comment]
Releases are more or less on an as-needed basis. I've been a little less frequent with the releases than I would like lately, but I'll probably do one soonish.

**Comment by 0sinner** [comment]
True. thanks jsha. I'll check back in a week, and if it's been updated I'll try it again, and update this ticket as appropriate.

I've disabled the extension until this is fixed as this is crippling my everyday usage at the moment.

**Comment by 0sinner** [comment]
I'm not sure if a new version has been released or not, but it looks like it's still broken. If it has been released has the commit by squarefractal made it in?

**Comment by gramakri** [comment]
Just ran into this issue today. Just wanted to say that DigitalOcean still does not work with the latest release.
