### ISSUE TITLE
openstreetmap.org,FF43

### ISSUE THREAD

**Issue by promeneur** [EFForg/https-everywhere#3708]
i fill the the itinerary template
then
i click on "ok"
then
nothing happens , no itinerary is supplied.

if i click on the red rule then the rule switches to green
then
this time if i ask for an itinerary then this one is supplied

**Comment by numismatika** [comment]
Do you have any picture of what you are trying to do or a link that creates warnings and / or console log messages that might hint at the problem?
Your description alone is a bit vague

**Comment by julianladisch** [comment]
https://www.openstreetmap.org/directions?engine=mapzen_car&route=51.8008%2C10.4473%3B51.7996%2C10.4459
in FF 43 works for me.
@promeneur Can you give a complete link so that we can reproduce and fix your problem?

**Comment by promeneur** [comment]
Sorry i am not at home.
I can't expériment on m'y PC.
Wait for 3 weeks please

**Comment by promeneur** [comment]
i got this pb also with android 4.2.2 and FF

but today with last version of FF 44.0.2 no more pb
