### ISSUE TITLE
Broke WatchESPN For Me

### ISSUE THREAD

**Issue by mchenja** [EFForg/https-everywhere#3712]
I'm very new to HTTPS Everywhere, so I apologize if I made a mistake, but—

I was using WatchESPN (http://espn.go.com/watchespn/) successfully to watch football games,
then I installed the Chrome extension for HTTPS Everywhere,
then I found that WatchESPN rejected my credentials for some unknown reason,
and I couldn't successfully use the service, even after logging out and logging in again,
then I disabled HTTPS Everywhere,
and then WatchESPN started working again.

Don't know if it matters, but I was using WatchESPN through a XFINITY/Comcast subscription.

**Comment by mlokc** [comment]
Same here. I can log in, but I get an "Internal Authorization Error" when I try to watch a video. After disabling all extensions, I gradually narrowed the problem down to HTTPS Everywhere. When it is disabled, WatchESPN works fine. When it is enabled, I get the error. 

I'm on ATT Gigapower, FWIW.

**Comment by Liam3851** [comment]
I've seen the same issue-- WatchESPN only works with HTTPS everywhere disabled using Chrome. I'm on a fiber connection logged into a Time Warner account (different from prior two posters), so account used seems not to matter.

**Comment by pipboy96** [comment]
Can't be reproduced without subscription, website has most likely changed by now.
