### ISSUE TITLE
RT.com now uses HTTPS by default for all pages

### ISSUE THREAD

**Issue by ekaris** [EFForg/https-everywhere#3721]
Should we delete the ruleset?

**Comment by ekaris** [comment]
What is done in these cases @J0WI

**Comment by J0WI** [comment]
Nothing, because RT.com still lacks of preloaded HSTS including all subdomains.

**Comment by fuglede** [comment]
And even actually HSTS-preloaded sites [still appear](https://lists.eff.org/pipermail/https-everywhere/2015-October/002639.html) in the ruleset database.

**Comment by loveithateit** [comment]
@fuglede I'm sorry if this comment is offensively patronizing, but in case it isn't (as this issue existing would seem to imply...), remember that torbrowser's HSTS preload list is quite outdated compared to Chromium.

**Comment by loveithateit** [comment]
@fuglede I'm sorry if this comment is offensively patronizing, but in case it isn't (as this issue existing would seem to imply...), remember that torbrowser's HSTS preload list is quite outdated compared to Chromium's.

**Comment by fuglede** [comment]
@loveithateit No offense taken; my comment was only to follow along the same line of J0WI's and say that even if the site *were* HSTS preloadable and included in the HTTPS-E database, that does not mean that it should necessarily be deleted from the database.
