### ISSUE TITLE
Silverlight

### ISSUE THREAD

**Issue by bryanroscoe** [EFForg/https-everywhere#373]
I have had 2 computers running this plugin in chrome have issues playing Netflix and Amazon prime. 

On one computer would play amazon prime and not Netflix. When I told it not to encrypt amazon it started working.

My other computer would not play Netflix ( i did not try amazon prime) I had to uninstall HTTPS everywhere to get it to work.

**Comment by semenko** [comment]
It looks like silverlight is dying. We'll see if this stays around post NPAPI transition.
