### ISSUE TITLE
bootstrapcdn.com rule breaks webfonts

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#3736]
Open this URL on Firefox 43.0.3: http://everyfuckingwebsite.com/

With the default BootstrapCDN rule on, the icons (AwesomeFont characters) aren't displayed.

When that rule is off, they are downloaded and displayed correctly from     http://netdna.bootstrapcdn.com .

**Comment by numismatika** [comment]
***The Same Origin Policy disallows reading the remote resource at http://netdna.bootstrapcdn.com/font-awesome/3.2.1/font/fontawesome-webfont.ttf?v=3.2.1. (Reason: CORS header 'Access-Control-Allow-Origin' missing).***

Either you keep the BootstrapCDN rule disabled or get the website owner to fix their website.

**Comment by anewuser** [comment]
>Either you keep the BootstrapCDN rule disabled or get the website owner to fix their website.
How can he "fix their website" by this issue caused by the use of a third-party extension?

**Comment by Bisaloo** [comment]
> How can he "fix their website" with this issue caused by the use of a third-party extension?

They can switch to HTTPS. You can check https://github.com/EFForg/https-everywhere/issues/49 for background on this issue.

**Comment by anewuser** [comment]
I don't use HTTPS Everywhere anymore.
