### ISSUE TITLE
www.dailykos.com CSS

### ISSUE THREAD

**Issue by WcRnm** [EFForg/https-everywhere#3755]
http://www.dailykos.com/ does not display correctly - CSS is not loading.

**Comment by numismatika** [comment]
quite a lot of exceptions in that ruleset file.
Anything major that breaks for you @WcRnm  when using https://www.dailykos.com/ instead, apart from a few warnings about mixed passive content?

**Comment by WcRnm** [comment]
Thanks for taking a look at this. Here is a link to a screenshot someone
took - I see essentially the same thing. Both Chrome and Firefox are
effected.

http://helpdesk.dailykos.com/discussions/dk-5-daily-kos-beta-bugs/509-https-everywhere-destroys-kos-home-page-formatting

~Rory


~R

**Comment by numismatika** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/6436819/12078078/cb5063f2-b203-11e5-9488-5b17a27638ef.PNG)
Is what i see here.
Has the website owner been asked to fix the mismatched content yet? The domains that serve images for example are using wrong certificates.

**Comment by sgonyea** [comment]
@WcRnm / @numismatika:  Looks the rulesets were fixed by @jsha in #3896.  So I think this issue can be closed.

**Comment by WcRnm** [comment]
Thanks for the info - It renders properly now.
~R

~R

**Comment by fuglede** [comment]
Closing as fixed.
