### ISSUE TITLE
The freenode ruleset only covers the webchat, not the main site

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#3766]
The freenode ruleset seems to only covers the webchat and not the main site. Would it be possible to expand the ruleset so that it covers the main site as well?

**Comment by fuglede** [comment]
The [freenode ruleset](https://www.eff.org/https-everywhere/atlas/domains/freenode.net.html) has covered the main site since its first iteration. Could you elaborate on why you believe that it does not in your configuration?

**Comment by anonsubmitter** [comment]
It doesn't show up on HTTPS Everywhere's ruleset list when I'm on the main site.

**Comment by fuglede** [comment]
And by the main site, you mean freenode.net, right? Which version of the add-on are you using?

**Comment by anonsubmitter** [comment]
Oh, looks like I was on [freenode.org](https://www.freenode.org/).

**Comment by fuglede** [comment]
Heh, that explains it. And you're right, that should be addable.
