### ISSUE TITLE
Https-everywhere 3.5.4 causes Firefox 31.0 to crash on exit on Ubuntu

### ISSUE THREAD

**Issue by jjaone** [EFForg/https-everywhere#377]
After updating Firefox to 31.0 on Ubuntu when https-everywhere is actived in extensions the browser crashes everytime on exit. When this extension is disabled Firefox works as expected and quits cleanly.

https://crash-stats.mozilla.com/report/index/42ca271c-1845-451d-996d-20b1e2140723

**Comment by StevenRoddis** [comment]
@jjaone does Firefox still crash with the latest (stable) version of HTTPS Everywhere?

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
