### ISSUE TITLE
Vox.com images don't load

### ISSUE THREAD

**Issue by ChrisTheCat** [EFForg/https-everywhere#3787]
Vox.com images don't load when https-everywhere is active. Turning off "force encrypted connections" to vox.com allows the images to display.
![screenshot 2016-01-05 10 58 05](https://cloud.githubusercontent.com/assets/8732435/12124621/3da0b0a4-b39b-11e5-93f2-0c005df95728.png)
![screenshot 2016-01-05 10 57 54](https://cloud.githubusercontent.com/assets/8732435/12124622/3da122d2-b39b-11e5-8890-903845518588.png)

**Comment by numismatika** [comment]
The website redirects tls requests to plain currently.
