### ISSUE TITLE
Ruleset breaks landsend.com

### ISSUE THREAD

**Issue by ZenAdm1n** [EFForg/https-everywhere#3795]
Unable to browse landsend.com on Firefox 43.0.3. The site fails to load.

Images and ecommerce content is broken in Google Chrome.

**Comment by numismatika** [comment]
Their main page supports TLS, but their shop on the same domain redirects to plain for a weird and unknown reason. Since CORS headers aren't set browsers refuse to load the images.

**Comment by gloomy-ghost** [comment]
massive close per #15157
