### ISSUE TITLE
[Idea] Tor Onion services

### ISSUE THREAD

**Issue by frafra** [EFForg/https-everywhere#3798]
Some websites are providing access as a Tor Onion service, like:
- DuckDuckGo - http://3g2upl4pq6kufc4m.onion/
- Facebook - https://facebookcorewwwi.onion/
- Tor Project - http://bt3ehg7prnlm6tyv.onion/
- Wikileaks - http://gjlng65kwikileax.onion/

Roger Dingledine (original developer of Tor along with Nick Mathewson and Paul Syverson) says something like "Tor Onion services vs HTTPS only websites is like HTTPS vs HTTP few years ago".
-- https://media.ccc.de/v/32c3-7322-tor_onion_services_more_useful_than_you_think#video&t=1041

I think it would be cool to have an option in HTTPS Everywere which instead of replacing http:// with https:// could replace the domain with the equivalent .onion domain.

I submitted a new issue on https-everywhere because I know this program is a collaboration between EFF and The Tor Project and the aim is to making browsing more secure, so I think there could be an interest for this kind of feature.

> HTTPS Everywhere is a Firefox, Chrome, and Opera extension that encrypts your communications with many major websites, making your browsing more secure. [...]
> HTTPS Everywhere is produced as a collaboration between The Tor Project and the Electronic Frontier Foundation.
> -- https://www.eff.org/https-everywhere

Would it makes sense to you? Or do you think it would be better to develop a different project, maybe using the same codebase of https-everywhere?

**Comment by numismatika** [comment]
If you have it as a separate project and the user runs both addons i see a conflict of rewrites,
Having it in HTTPS-Everywhere needs a way to figure out if TOR is active, since otherwise the redirects are useless. Maybe implement it as an extra platform-tag?

**Comment by frafra** [comment]
I would prefer to integrate such feature in HTTPS Everywhere if possible.

`platform="tor"` looks goods:
> Note: This should be something like platform=tor, to indicate that these rules should not go through the fetch tester on the non-Tor Internet because they will fail. As an approximation to that, we just use platform="mixedcontent", since Tor Browser is a mixedcontent platform, and the https-everywhere-checker will skip non-default platforms.
> - [src/chrome/content/rules/FacebookCoreWWWi.onion.xml](https://github.com/EFForg/https-everywhere/blob/61cf352307131540f6b2ab3e45ed2164e00e981a/src/chrome/content/rules/FacebookCoreWWWi.onion.xml#L4)
> - [src/chrome/content/rules/Cyphdbyhiddenbhs.onion.xml](https://github.com/EFForg/https-everywhere/blob/61cf352307131540f6b2ab3e45ed2164e00e981a/src/chrome/content/rules/Cyphdbyhiddenbhs.onion.xml#L5)

`platform="mixedcontent"` is currently used by Tor Browser only:
> To enable a rule only on platforms that allow mixed content (currently only the Tor Browser), you can add a platform="mixedcontent" attribute to the ruleset element.
> - [docs/rulesets.html](https://github.com/EFForg/https-everywhere/blob/61cf352307131540f6b2ab3e45ed2164e00e981a/docs/rulesets.html#L286)

Platform is currently selected by [checkMixedContentHandling](https://github.com/EFForg/https-everywhere/blob/61cf352307131540f6b2ab3e45ed2164e00e981a/src/chrome/content/code/HTTPSRules.js#L427) during initialization. We could just append `|tor` to `localPlatformRegexp` if Tor is on.

Tor is considered enabled if [testProxySettings](https://github.com/EFForg/https-everywhere/blob/61cf352307131540f6b2ab3e45ed2164e00e981a/src/components/ssl-observatory.js#L758) sets `proxy_test_successful` to `true`. It uses https://check.torproject.org/, but what if Tor is on but check.torproject.org is off or there's a temporary connection issue?

Here's my proposal:
 1. Add "tor" to `localPlatformRegexp` if `testProxySettings` says that Tor is on
 2. Replace `platform="mixedcontent"` with `platform="tor"` in src/chrome/content/rules/*.onion.xml
 3. Create new ruleset with `platflatform="tor"` in order to rewrite domains with theirs .onion counterparts if they exist
 4. Enhance `testProxySettings`: testing an .onion service and/or allow to override the test with a parameter (optional)

**Comment by zero77** [comment]
This may make things a bit slower. Although this is a great idea I would defiantly like to see this added.

**Comment by fuglede** [comment]
There actually was a fork for that: https://github.com/chris-barry/darkweb-everywhere

**Comment by J0WI** [comment]
Referring to the discussion in #7094 and #5085 we won't redirect from public hosts to hidden ones.
To redirect http to https on .onion hosts we need to update our tests (see patches provided in #5085).

**Comment by punkwritecode** [comment]
https://trac.torproject.org/projects/tor/wiki/org/projects/WeSupportTor

**Comment by UsernameLoginIsAlreadyTaken** [comment]
Tor Browser already included HTTPS Everywhere by default. How about adding a new function to detect
the browser? If the user is using Firefox, redirect to https. If not, redirect to .onion.

My pull request have 3 URLs: http, https, onion.
https://github.com/EFForg/https-everywhere/pull/11009

**Comment by HTTPSNowhere** [comment]
@UsernameLoginIsAlreadyTaken 

> Tor Browser already included HTTPS Everywhere by default. How about adding a new function to detect
the browser? If the user is using Firefox, redirect to https. If not, redirect to .onion.

Some of Tor Project devs already  "discussed with the HTTPS everywhere
people over the years, but it's unclear whether the team has the
firepower and energy to handle such a task, or whether it's worth it at
all.

As an alternative here is a more general and abstract approach to
solving the UX problem: https://lists.torproject.org/pipermail/tor-dev/2016-October/011514.html" 
https://lists.torproject.org/pipermail/tor-talk/2017-March/043027.html

**Comment by Bisaloo** [comment]
Following @Hainish's comment in https://github.com/EFForg/https-everywhere/issues/10007#issuecomment-321595470:

> TB no longer enables `platform="mixedcontent"` rules. See trac.torproject.org/projects/tor/ticket/21323

I did some testing and onion rules are indeed disabled. This means `platform="tor"` is now necessary for those rules.

**Comment by koops76** [comment]
That would be harder to test too.

**Comment by koops76** [comment]
I think we should have this preference order:
HTTPS over `.onion` > HTTPS > HTTP over `.onion` > HTTP

**Comment by koops76** [comment]
@Bisaloo Does that mean we can delete all `platform="mixedcontent"` rules?

**Comment by Bisaloo** [comment]
No, users may still want to enable them. This simply means that `platform="mixedcontent"` rulesets are now considered `default_off` by all browsers.

**Comment by koops76** [comment]
@Bisaloo Are you completely sure we still need them? These websites are broken with mixed content blocking on and disabling mixed content blocking is a security risk.

**Comment by Bisaloo** [comment]
@koops76, please refer to https://github.com/EFForg/https-everywhere/issues/9971 for a more detailed discussion about `platform="mixedcontent"` rulesets.

**Comment by Hainish** [comment]
I don't see why we need a `platform` attribute at all for `.onion` URLs.  The worst thing that happens is someone who enters an onion URL such as `http://facebookcorewwwi.onion` is redirected to `https://facebookcorewwwi.onion` in a normal browser.  In either case, the resolution fails.  So what's the advantage here?

I think we should just remove `platform='mixedcontent'` from onion rulesets.  It seems a little hacky, anyway.  The only reason we're calling these rulesets `mixedcontent` is because then they will redirect within the Tor Browser, not because they actually have mixed content on that page.

**Comment by J0WI** [comment]
@Hainish I think a platform would still be helpful to pass out fetch tests. We had a PR about this, but I can't find it anymore.

**Comment by koops76** [comment]
@J0WI Or we could just access all domains that end in .onion over Tor during the fetch test.

**Comment by koops76** [comment]
#11988

**Comment by Hainish** [comment]
@J0WI thanks for the tip.  I'm going to close this issue for the reasons described above in https://github.com/EFForg/https-everywhere/issues/3798#issuecomment-249998001
