### ISSUE TITLE
[FreeDesktop] Broken http://www.freedesktop.org/icons/*.gif

### ISSUE THREAD

**Issue by jwilk** [EFForg/https-everywhere#3802]
When HTTPSE is enabled, there are no icons on <http://www.freedesktop.org/software/ConsoleKit/dist/>.
<http://www.freedesktop.org/icons/compressed.gif> gets rewritten as <https://wiki.freedesktop.org/www/icons/compressed.gif>, but the latter is 404.

**Comment by J0WI** [comment]
Fixed in dae57bfeb3a97ab037651a5550704b169b51f07e
