### ISSUE TITLE
trulia.com

### ISSUE THREAD

**Issue by eirenicon** [EFForg/https-everywhere#3849]
the site does not present correctly...

**Comment by oldhill** [comment]
Looks like this was fixed in master on 12/17 with this PR: https://github.com/EFForg/https-everywhere/pull/3493

But the fix hasn't made it into a release yet (latest was on 12/16).

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
