### ISSUE TITLE
Bug?: HTTPS-Everywhere Breaks Guardian Online Newspaper Comments Functionality

### ISSUE THREAD

**Issue by RadicalRadish** [EFForg/https-everywhere#3862]
OS = Linux Mint Cinnamon Edition 17.3 x64
Firefox 43.0 (for Linux Mint)
I have tested this with HTTPS-Everywhere versions 5.1.0, 5.1.2-eff and 5.13asyncbeta-eff

I read the Guardian newspaper online: http://www.theguardian.com/uk

Very often on an article webpage there is, near the bottom of the webpage, an area where readers can leave comments about the news article. In recent weeks this seemed not to be working for me - the comments section would never load successfully. To get it to load at all I had to click on the text offered (instead of the comments) "Loading comments… Trouble loading?"

Clicking on that "Trouble loading?" link then opened a new webpage where I could view comments left by readers. Normally in viewing that webpage I would be able to sort the comments according to age and other factors, however, I was not even offered the capacity to do this (in other words the webpage wasn't being drawn properly). However, if I logged-in to the Guardian I would not be able to reply to or post a new comment of my own. I contacted the Guardian about this and they responded by asking if I was using HTTPS-Everywhere - which, they said, seemed over the last few weeks to be preventing people from seeing comments displayed and from being able to interact with the comments sections of articles.

I tested this on my own system and, yes, HTTPS-Everywhere is implicated in this problem with the Guardian website. If I disable HTTPS-Everywhere the Guardian website returns to functioning as normal.

As the Guardian seem to be aware of this problem then maybe someone here could contact the Guardian and ask for further information on the issue. An email address for the Guardian would be userhelp@theguardian.com

Hope this is of help.

**Comment by nfdisco** [comment]
Hi there. I had the same problem. Using Firefox's inspector feature I found out that several .js files on assets.guim.co.uk were inaccessible when HTTPS-Everywhere was turned on (Error codes 403 Forbidden). I disabled this site running the following command

    $ cat > HTTPSEverywhereUserRules/Guim.co.uk.xml <<EOF
    <ruleset name="Guim.co.uk (partial)">
      <target host="guim.co.uk"/>
    </ruleset>
    EOF

in my Firefox profile directory.  After restarting Firefox the comments on the Guardian site work again.

**Comment by RadicalRadish** [comment]
Hi nfdisco,

Thanks for the information. It's a pity that HTTPS-Everywhere dropped the functionality to allow users to exclude sites with a simple mouse click. For users like myself setting up 'rules' in the way you describe sounds overly complex.

In any case, I contacted the Guardian about this as well. They replied saying that they were in the process of setting up the Guardian website to transfer completely to HTTPS.  They said that their work on this was still at 'beta' stage. They said that as a workaround to the issue for just now, if you want to use HTTPS, then you should access the Guardian using the following url: http://www.theguardian.com/https/optin

I tested this out and the comments started to work again fine even though site access was via HTTPS.

I would note that you only need to access the site using that url once per-browser-session. I assume that the Guardian is putting cookie information into the browser that then tells the website that you want to enter the site using HTTPS no matter what url links you are using. After accessing the site by that method I find that all my old stored Guardian links work just fine and do access the site via HTTPS (which would, in my case, be being enforced by HTTPS-Everywhere). So you just need to use the 'optin' link once per-browser-session then proceed as you would normally do and still keep  HTTPS-Everywhere enabled as per normal.

They did say that some bugs might show up in using this method, but to date I haven't come across any.

Hope this helps.

**Comment by nfdisco** [comment]
Hi RadicalRadish, 
Thanks for the info.
I've just found out there's a menu Tools > HTTPS Everywhere in Firefox where individual sites can be disabled with a mouse click. I guess I overlooked it.

**Comment by RadicalRadish** [comment]
> I've just found out there's a menu Tools > HTTPS Everywhere in Firefox where individual sites can be disabled with a mouse click.

Something I hadn't noticed as well. That said I just went to test it and find that "Enable/Disable Rules" doesn't work, it's not selectable (at least not on my system). Ah, well. Thanks for the thought anyway.

**Comment by nfdisco** [comment]
> Something I hadn't noticed as well. That said I just went to test it and find that "Enable/Disable Rules" doesn't work, it's not selectable (at least not on my system).
The "Enable/Disable Rules" item is the heading. By clicking on the items below it you can enable/disable HTTPS for the sites listed, but you need to have some page opened to see it.

**Comment by RadicalRadish** [comment]
Okay - got it! Thanks very much.
