### ISSUE TITLE
Unable to connect to arriseverywhere.com

### ISSUE THREAD

**Issue by ewodwerdna** [EFForg/https-everywhere#3869]

**Comment by youdly** [comment]
Server doesn't support HTTPS.
```
$ curl -I -L https://www.arriseverywhere.com/
curl: (35) Unknown SSL protocol error in connection to www.arriseverywhere.com:443 
$ curl -I -L https://arriseverywhere.com/
curl: (35) Unknown SSL protocol error in connection to arriseverywhere.com:443
```

**Comment by J0WI** [comment]
As far as I can see we have no rule for arriseverywhere.com, so how is this related to HTTPS Everywhere?

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.
