### ISSUE TITLE
MNGInteractive

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#3931]
See:
http://www.twincities.com/crime/ci_29400416/st-paul-cop-allegedly-urged-drivers-hit-black

The site is broken when MNGInteractive is enabled.

**Comment by terrorist96** [comment]
MNGInteractive isn't listed on that site, and it doesn't seem broken. It does however break other sites; see https://github.com/EFForg/https-everywhere/issues/3934

**Comment by J0WI** [comment]
I think this has been fixed.
