### ISSUE TITLE
Error: Too many redirects 310 Chrome from University EZProxy kuleuven.ezproxy.kuleuven.be

### ISSUE THREAD

**Issue by BugReportGuy** [EFForg/https-everywhere#3935]
Hello,

Not sure what is causing the redirect error, the ezproxy or the springer page. Full link can be found below: 

http://kuleuven.ezproxy.kuleuven.be/login?url=http://link.springer.com/article/10.1007/s00216-010-3754-0

I think it's ezproxy because other journal publishers also don't work (Nature, Wiley etc.)

Tried incognito and it worked, so I did the plugins one by one and HTTPS everywhere was the culprit. Hope it's fixed, because I love the plugin, but also use this daily for my work.

Thanks a lot for your work!

**Comment by pipboy96** [comment]
Can't reproduce.

**Comment by BugReportGuy** [comment]
Yeah only three years after reporting it good job.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pipboy96** [comment]
@BugReportGuy Don't spam please.
