### ISSUE TITLE
Redirection changes host on api.cloudsponge.com

### ISSUE THREAD

**Issue by dangerouse** [EFForg/https-everywhere#3949]
To reproduce:

1. enable HTTPS Everywhere extension in Chrome
2. visit http://api.cloudsponge.com/ping
3. observe the new URL: https://api.cloudponge.com/ping

Expected behaviour: The new URL should be
https://api.cloudsponge.com/ping
not
https://api.cloudponge.com/ping

The redirection has removed the 's' from cloudsponge, changing the domain. 

I've tracked this issue down to [a rule that appears to have a typo](https://github.com/EFForg/https-everywhere/blob/bcb101723edb31a933b1f4e26cce17c2364da31d/src/chrome/content/rules/CloudSponge.xml#L18) in it. 

I've only tested this with the Chrome extension.

**Comment by fuglede** [comment]
Closed by #4749.
