### ISSUE TITLE
Video does not play in UFC Fightpass

### ISSUE THREAD

**Issue by gideonguillen** [EFForg/https-everywhere#4010]
Go to http://www.ufc.tv/page/fightpass. Videos on this does not play correctly.

There should be a Flash video playing on the upper right part of the page. This does not play with default HTTPS-Everywhere rules. However when I disable rules for Akamai video will play.

**Comment by jeremyn** [comment]
Thanks for the report. I don't see a Flash video at the given URL even with HTTPS Everywhere disabled entirely. Is this still a problem for you?

**Comment by gideonguillen** [comment]
Unfortunately I won't be able to verify anymore. I used to have a subscription there. The front page, the URL sample I gave used to have a Flash-based player there. There was a redesign that happened just a few weeks I ended my subscription, though. I won't be able to verify if there was any changes made on the product behind the pay-wall.

**Comment by jeremyn** [comment]
Okay thanks. I'm closing this issue then, but if you (or anyone else reading this) get this problem in the future, please feel free to reopen this issue with a comment.
