### ISSUE TITLE
Https Everywhere breaks Nvidia driver downloads

### ISSUE THREAD

**Issue by random6969** [EFForg/https-everywhere#4028]
example: http://www.nvidia.com/download/driverResults.aspx/97767/en-us

Clicking "download" will lead to a page with broken formatting. 
Disabling "nVidia.com (partial)" fixes it. 

- chrome (v48) 64-bit, Windows 10 64-bit

**Comment by funkydude** [comment]
This seems like an HTTPSE issue to me. The CSS files Chrome is blocking from being downloaded works fine when accessed over HTTPS (the rule kicks in correctly), however HTTPSE isn't changing the HTTP request to HTTPS.

The workaround would be setting the following exclusion which I have not tested:
`<exclusion pattern="^http://www\.nvidia\.com/(download|content)/" />`

**Comment by funkydude** [comment]
cc @semenko
Am I misunderstanding the functionality or should the requests being made (and blocked by Chrome) not be re-written to HTTPS by the extension?

**Comment by semenko** [comment]
Outstanding chrome bug #793 https://code.google.com/p/chromium/issues/detail?id=122548

**Comment by funkydude** [comment]
@semenko 2012 seriously? Ugh... Should we be working around these Chrome specific issues with exclusions in the rules themselves?

**Comment by semenko** [comment]
Generally yes :(
