### ISSUE TITLE
Is there a webpage which lists all the supported websites on one page?

### ISSUE THREAD

**Issue by thenoncoder** [EFForg/https-everywhere#4033]
If not, I really want one.

I don't want to click on around 27 separate pages for each letter, then copy and paste the domain names, format, etc.

**Comment by jsha** [comment]
What's your goal? If you're searching for a particular domain name, you can do that from the main page. If you're trying to programmatically do something with the rulesets, you might be better off checking out the repo and modify some of the tools in `util/`.

**Comment by thenoncoder** [comment]
I'm just writing a script to do some specific things so I need those domain names.

**Comment by jsha** [comment]
That's pretty vague! I'm afraid I can't help you more than the above.
