### ISSUE TITLE
Settings not synced with/across Chrome incognito sessions

### ISSUE THREAD

**Issue by TheRyuu** [EFForg/https-everywhere#4034]
Since the move to using split mode[1] for incognito windows/sessions the settings are not saved for use across different incognito sessions.  They're also not synced properly with the non-incognito extension process as you would expect it to.  This behavior isn't what you really expect from an extension even if it's using split mode.  The settings should still be synced between them and across sessions.  uBlock Origin[2] behaves this way and keeps settings synced between them.

To test what I'm describing:

1. Make sure all chrome processes are closed before starting.
2. Start chrome with the incognito command (i.e. "chrome.exe --incognito").
3. Browse to any site which has a rule and change this rule
4. Close chrome and ensure all processes end.
5. Start Chrome again in incognito mode as in step 2.
6. Browse to the same site as in step 3 and check the rules.  It will revert to the defaults.

You can also change various rules in normal (non-incognito) mode then browse to those same sites in incognito mode and see the settings for the rules are not the same.  The incognito window will be using whatever the default rules are.

There are two possible ways to fix this.  Obviously you could remove the split mode (is it even necessary anymore?) so that it only runs one extension process.  This fixes all problems described above and is the easiest fix provided it would not have security implications.  However if you do want to keep using split mode you'll have to sync the settings between them somehow (e.g. how uBlock Origin does it).

[1] https://developer.chrome.com/extensions/manifest/incognito
[2] https://github.com/gorhill/uBlock

**Comment by semenko** [comment]
Yeah, split mode arose as we use a cache that we'd like to keep separate for incognito.

There are two solutions I'd be fine with:
- Remove split incognito if we can clear the cache somehow (is it possible to detect when an incognito session is closed?)
- Use chrome.storage for more things (like syncing ruleset state) -- then we'd sync rulesets to any new install that uses Chrome sync (yay! we should probably do this no matter what)
