### ISSUE TITLE
Cannot use go.cnn.com with https-everywhere enabled

### ISSUE THREAD

**Issue by shaomeng** [EFForg/https-everywhere#4062]
go.cnn.com reports DRM3315 error and won't play. Problem solved when https-everywhere is disabled. Attached is a screenshot in Chrome, and the same issue happens in Firefox too.

![screen shot 2016-01-31 at 11 28 34 pm](https://cloud.githubusercontent.com/assets/814885/12710342/da0bfc82-c872-11e5-9c63-e3830524aff2.png)

**Comment by J0WI** [comment]
requires flash

**Comment by jeremyn** [comment]
http://go.cnn.com works for me in Firefox 48.0.2 on Windows 10 with Flash installed and with HTTPS Everywhere enabled. I get a different DRM error in Chrome 52.0 on Windows 10 even with HTTPS Everywhere disabled.

@shaomeng This doesn't seem like an HTTPS Everywhere problem to me. Is it still an issue for you?

**Comment by shaomeng** [comment]
@J0WI  It has flash, and I confirmed that it's https-everywhere causing problem.

@jeremyn Sorry for the late response. I tried today on Chrome 55.0 and the problem is gone. 

Now I'm closing this ticket.

**Comment by jeremyn** [comment]
That's okay, thanks for letting us know.
