### ISSUE TITLE
i think this rule is broken http://www.independent.co.uk/

### ISSUE THREAD

**Issue by adde9708** [EFForg/https-everywhere#4063]
When i try to access it shows up as a bunch of links while https everywhere is enabled. Looks like a directory or something but it does mismatch cause the certificate is in a.ssl.fastly.net. But  i know someone fixed this awhile ago but it seems broken again.

**Comment by adde9708** [comment]
Cause without it i can access it i mean without https everywhere enabled

**Comment by funkydude** [comment]
This specific rule is disabled by default already, you shouldn't need to disable the entire extension.

**Comment by adde9708** [comment]
Didnt mean it like that i meant disable the rule.So your right
Den 1 feb 2016 15:34 skrev "funkydude" <notifications@github.com>:

**Comment by adde9708** [comment]
Also just wanted to let you guys know

**Comment by adde9708** [comment]
Cause it worked for awhile after you guys fixed it.Now it breaks

**Comment by funkydude** [comment]
Are you sure when it "works" for you, you're not browsing over HTTP? For me, browsing to https://www.independent.co.uk/ and allowing all content with HTTPSE disabled still fails to work. Seems like a problem with the website itself.

**Comment by adde9708** [comment]
yeah that's what i baiscly said :) the certifcate seems to be at a.ssl.fastly.net somekind of CDN maybe? but yeah if you follow  it even though the mismatch it shows up as only links

**Comment by adde9708** [comment]
that's what i meant :P

**Comment by adde9708** [comment]
i baiscly just wondered if its possible to just redirect some of them to fastly just a sugestion otherwise il just keep it off until they fix it as in independent then its not you guys fault.

**Comment by adde9708** [comment]
since that's what it says when it mismatches

**Comment by adde9708** [comment]
but no worrys if it doesnt work then il just keep it off just trying to help :)

**Comment by IDKwhattoputhere** [comment]
If it's disabled by default then there's a reason for that. You're experiencing that reason.

**Comment by funkydude** [comment]
This isn't an instant messenger, edit your comments and add extra text to them.

This ticket can be closed, not an HTTPSE problem.

**Comment by fuglede** [comment]
Closing as not an issue.
