### ISSUE TITLE
docs.openstack.org and logs.openstack.org should not be rewritten

### ISSUE THREAD

**Issue by andrewbogott** [EFForg/https-everywhere#4069]
Neither docs.openstack.org nor logs.openstack.org supports https, but the https everywhere rule redirects them to https, which gets me error pages.

Examples:

http://docs.openstack.org/developer/nova/
http://logs.openstack.org/51/242251/19/check/gate-nova-python27/eb151ab/

**Comment by J0WI** [comment]
We do not redirect these hosts:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/OpenStack.xml

**Comment by andrewbogott** [comment]
Yep, I can confirm that firefox with the latest git does not have the rewrite problem.  So... something interesting is happening but whatever it is isn't in the https-e ruleset.
