### ISSUE TITLE
archive.is not available via https in Russia

### ISSUE THREAD

**Issue by volth** [EFForg/https-everywhere#4075]
archive.is not available via https in Russia https://en.wikipedia.org/wiki/Archive.is#Worldwide_availability
Please consider either making the rewrite rules geo-aware or stop rewriting "archive.is".

**Comment by stevenatwork** [comment]
>In Russia you can access only the HTTP version of the website; the HTTPS version is blocked on the state firewall.

https://en.wikipedia.org/wiki/Archive.is#Worldwide_availability

In my opinion this is a **terrible reason** to stop rewriting to HTTPS.

**Comment by jsha** [comment]
Thanks for reporting! I wouldn't have put it quite so strongly, but we won't disable rulesets because of local censorship, nor make HTTPS Everywhere geo-aware. It would go against EFF's anti-censorship stance.
