### ISSUE TITLE
Wowhead.com hangs lately unless it's ignored on rules

### ISSUE THREAD

**Issue by fateswarm** [EFForg/https-everywhere#4076]
Example page: http://www.wowhead.com/item=118878/copelands-clarity

**Comment by numismatika** [comment]
wow.zamimg.com takes very long to answer requests, sometimes it breaks before that.
I sent an e-mail to the wowhead/Zam team to ask them about the matter.

**Comment by J0WI** [comment]
Works for me, @fateswarm @numismatika can you confirm?

**Comment by numismatika** [comment]
So far it looks good, no time outs no errors on the network logging tab.
They still redirect anything other than the ressources to plain but that is some evangelism left todo.
