### ISSUE TITLE
Pictures broken on vox.com

### ISSUE THREAD

**Issue by xaocon** [EFForg/https-everywhere#4086]
I tried my ad blocker first but that didn't do it. Disabling this brought the pictures back. I'll look in to it more but probably something that should be fixed on their side instead. I think there should be a way to disable for a site or something similar so that you don't have to disable the whole extension for broken sites.

**Comment by xaocon** [comment]
Disabling vox.com works. Will have to look at the rules after work to determine what's needed in a pull request.

**Comment by xaocon** [comment]
Should have looked at closed issues as well. Need to look at #3787 and #1936.

**Comment by xaocon** [comment]
Building from master didn't seem to work for me so I don't think #3787 works here. #1936 should have been merged in the version I was using if it was accepted. I'll have to dig into the rules now that I have an env set up to dev and test on.

**Comment by funkydude** [comment]
I can't reproduce this in Chrome or Firefox with the February update.

**Comment by xaocon** [comment]
After creating a clean chrome profile and rebuilding it now works for me. Looks like my problem isn't with this.

**Comment by xaocon** [comment]
I take that back. It looks like the vox.com rule was disabled because it's considered experimental. When I enable the rule the pictures quit showing up again. Can you confirm that it works fine for you? I'm using Chrome 48.0.2564.109.

**Comment by funkydude** [comment]
>Can you confirm that it works fine for you?

Erm.

>I can't reproduce this in Chrome or Firefox with the February update.

This is using the default setting. If the default setting is disabled, then expect issues by enabling it. Bug reports for disabled rules are invalid (unless you're telling us that a disabled rule now works).

**Comment by xaocon** [comment]
Missed your reply somehow. Sorry for the confusion, I thought that the rule would have been removed or something if it was known to be broken. Closing.

**Comment by funkydude** [comment]
@xaocon Broken rules are generally just turned off by default. That way if the server owner ever resolves their HTTPS issues, it can just be toggled back on.
