### ISSUE TITLE
Reference examples in rules styleguide

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#4090]
For instance, there is a line that reads:

```
If there are a handful of tricky subdomains, but most subdomains can handle the plain rewrite from "^http:" to "^https:", specify the rules for the tricky subdomains first, and then then plain rule last.
```

It would be great if there were a good canonical example to point to - a domain that's been tricky in this way for a long time.  It would be good to see how this looks in an exemplary rule.

There are several places in the style guide that can be improved in this way.

**Comment by gloomy-ghost** [comment]
We have examples in CONTRIBUTING.md now
