### ISSUE TITLE
AMO outdated

### ISSUE THREAD

**Issue by kollegah1338** [EFForg/https-everywhere#4094]
The AMO Website still offers version 5.1.0 and hasn't been updated since August 2015.

https://addons.mozilla.org/de/firefox/addon/https-everywhere/
Version 5.1.0
August 18, 2015

**Comment by jsha** [comment]
Known issue, I'm afraid: Mozilla has been rejecting our uploads because we read rulesets from the SQLite DB synchronously (as we have for two years now). We're working on a fix, but it's taking a while.
