### ISSUE TITLE
Video breakage on theatlantic.com

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#4105]
Video:
http://www.theatlantic.com/video/index/424995/autism-in-love-dating-and-courtship-on-the-spectrum/

Filter:
The Atlantic (partial)

**Comment by Hainish** [comment]
@tancrackers do you happen to have Privacy Badger installed? I can't reproduce this unless I have PB installed as well.

**Comment by Hainish** [comment]
cc @cooperq

**Comment by tancrackers** [comment]
I have uBlock Origin instaled, default deny to third party scripts.
I should have accounted for that. However, I enabled The Atlantic in https-everywhere today and the video now plays.

**Comment by funkydude** [comment]
@tancrackers If it's not an HTTPS Everywhere issue then close it please.
