### ISSUE TITLE
HSTS Everywhere

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#4107]
In addition to rules maybe you should cache the list of websites once accessed via HTTPS and not covered by the rules and then allow to connect to them only by HTTPS during some time since the last connection. You can also add a button which will upload the domains from that list to EFF (or any other location), where will be a script checking whether these websites are available through HTTPS and creating the rules automatically and post them as drafts. Then someone picks a rule draft, tests it, modifies and makes a pr. One more feature we need is the about:config pref disallowing http without TLS.

**Comment by jsha** [comment]
> cache the list of websites once accessed via HTTPS and not covered by the rules and then allow to connect to them only by HTTPS during some time since the last connection. 

Unfortunately, a large number of sites would break under this configuration.

> One more feature we need is the about:config pref disallowing http without TLS.

We've already got this: it's in the dropdown menu from the icon, called "Block all HTTP requests."

**Comment by KOLANICH** [comment]
>Unfortunately, a large number of sites would break under this configuration.

Infinite redirection caused by this should be detected and the site should be removed from the list. The same should be done in the case of unavailability of https (unless HSTS prescribes to behave in another way).

Will this help?

**Comment by jsha** [comment]
> he same should be done in the case of unavailability of https (unless HSTS prescribes to behave in another way).

HSTS prescribes to prevent access to the site if HTTPS is unavailable, which is part of why it's not a good fit to automatically apply it to sites.

**Comment by KOLANICH** [comment]
>HSTS prescribes to prevent access to the site if HTTPS is unavailable, which is part of why it's not a good fit to automatically apply it to sites.

Maybe I have expressed not clearly. I meant that the websites policed with hsts shouldn't be policed with the hsts surrogate.

**Comment by pipboy96** [comment]
Not clear what is intended by author. HSTS preloading seems to already do that.

**Comment by KOLANICH** [comment]
HSTS preloading is a completely different thing. It is optin by website admin and is not widely used because can cause breakage. HE is optin by website users, not its admin. Unfortunately we can rely on admins, lot of admins because it is known fact that admins are lazy: lot of them still use plain http even if they were given all the information needed to setup LE, because they don't think that their website needs tls because they are neither banks, nor payment systems.

**Comment by pipboy96** [comment]
@KOLANICH Please describe in detail the solution you suggest HTTPSe to implement.

**Comment by KOLANICH** [comment]
When a website is accessed via TLS and the tls version doesn't;
1. it checks its presence in the ruleset
2. if it is not present in a ruleset, it checks if hsts headers are present
3. if they are not present the tool puts the domain into own database
4. additionally the tool may remember the best cyphersuite successfully used and require ciphersuites not worse than that one (on downgrade a warning).

When accessing a website without tls without a rule, but which is in the db:
1. rewrite URI to access TLS version.
2. if the TLS version redirects to http - display a warning, asking if the downgrade should be allowed. There should be a checkbox in the settings allowing all downgrades for the computers of houswives and grannies.

The result should be like creating a rule for that website, but more automatic. Why it is needed? Some websites provide internal links via https, but they have no hsts, no automatic redirection, and some searcu engines (at least Google) use http links to that websites in their search results despite https availability.

There is some problem - it may be used as a supercookie by creating lot of domains selectively allowing/disallowing TLS/ciphersuites for a certain IP addr.

**Comment by pipboy96** [comment]
Currently TLS introspection is not possible with Chrome, and Firefox API is not standardized. For similar effect you can use Smart HTTPS addon. It doesn't memorize pages that support HTTPS though.

I am currently considering a slightly different solution, which is unlikely to break anything and that hopefully could be deployed for advanced users who want a bit of extra protection and possibly help the ruleset database grow. Currently, there's no deadline and I would still need the existing code team to review it (I am a ruleset maintainer).
