### ISSUE TITLE
ssl_error_no_cypher_overlap on clockworkmod.com 

### ISSUE THREAD

**Issue by l0b0** [EFForg/https-everywhere#4108]
Using HTTPS-Everywhere 5.1.0 on Firefox 44.0.

**Comment by numismatika** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=clockworkmod.com&s=50.23.163.121&hideResults=on&latest , there are a couple of problems with their tls config , short 1024 dh parameters and only two ciphersuites enabled.
FF 44 on Win7 works here, so does the nightly.
Did you modify your tls settings in any way?

**Comment by l0b0** [comment]
I don't think so. I also just tried restarting with add-ons disabled, and I got the same result.

**Comment by numismatika** [comment]
I suspect changes in the internals of FF, like you can do with Calomels TLS addon and without.
Disabling weak ciphers is easy.

**Comment by J0WI** [comment]
Please verify that at least one of those ciphers in about:config is enabled, as it's current the default on Firefox:
security.ssl3.dhe_rsa_aes_128_sha
security.ssl3.dhe_rsa_aes_256_sha

**Comment by l0b0** [comment]
You're right, both of those are set to `false` for security reasons.
