### ISSUE TITLE
Issuu.com rule broken

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4117]
http://www.bleedingcool.com/2016/02/09/there-are-no-monsters-like-us-preview-of-insexts-3/

The Issuu.com (partial) rule causes a "Error loading data" message to come up on content that should load.  Disabling it has the content load correctly.

Firefox 44.0.1, HTTPSE 5.1.2, Windows 7 64-bit

**Comment by galeksandrp** [comment]
works on https://github.com/EFForg/https-everywhere/commit/master https://github.com/EFForg/https-everywhere/commit/30c306a857b3780cfa5b11e937193915beba4300
@jeremyn

**Comment by jeremyn** [comment]
I can confirm that the Issuu comic book element in the middle of the page seems fine now, thanks @galeksandrp.

@MDawg957 Can you please confirm and if it works for you, close this issue?

**Comment by MDawg957** [comment]
@jeremyn Confirmed as working.  Closing.

**Comment by jeremyn** [comment]
Thanks for the update @MDawg957.

**Comment by yfswun** [comment]
I have the same issue. It only happens in Firefox, but not on Chrome, IE, and Opera.

Error displayed by issuu:
```
Error loading data
40351406 | | mozilla 55.0 | 1504029527
```
Program section on this page:
[http://www.asianinc.org/event-gala-2016/](http://www.asianinc.org/event-gala-2016/)

FF 55.0.3 (64-bit)
HTTPS Everywhere 5.2.20
Windows 8.1

**Comment by jeremyn** [comment]
I can reproduce the problem in @yfswun 's comment on Firefox and not Chrome. On Firefox but not Chrome, the dev console reports this error three times:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://e.issuu.com/embed/16001500/40351406.json?v=1.0.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

**Comment by Bisaloo** [comment]
http://www.asianinc.org/event-gala-2016/ seems to work fine now. The dev console on FF warns about MCB for fonts and a CSP violation but it's report-only. I think this issue can be closed.

**Comment by jeremyn** [comment]
The Issuu-provided content on both http://www.bleedingcool.com/2016/02/09/there-are-no-monsters-like-us-preview-of-insexts-3/ and http://www.asianinc.org/event-gala-2016/ seems okay now.

@MDawg957 , @yfswun I'm closing this issue, but please feel free to add a comment if this is still a problem for you.
