### ISSUE TITLE
[New Feature Request] Rulesets Idear

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#4132]
Can you add an inbuilt butten into HTTPS Everywhere that will check the website for potential new rulesets and then automatically submit it if the checks are successful.

**Comment by foobar13373** [comment]
+1.

**Comment by J0WI** [comment]
There is an Add-On called HTTPS-Finder, but auto generated rule sets are mostly pretty bad, because they doesn't cover as much as manually researched.

**Comment by zero77** [comment]
Yes, but I mean an extra way to submit rulesets alongside the standard pull request way even if it was just a basic http to https rule to start with. As this would speed up rulesets submissions and allow less technical users to submit rulesets. There could always be an additional report rulesets button for if the page was broken.

**Comment by rezad1393** [comment]
I  completely agree.
I see many rules everyday with just my own browsing that a reporting (of course optional) is very good.
I am pretty sure they are a lot more http->https sites that the users can find.
and the manual power can be put to testing  the reported finds from the users.

this way it would have the good part of crowd-sourcing and removing the bad parts of crowd-sourcing.

this would be more relevant as more and more website use the lets-encrypt to encrypt their websites.

and also this helps find rules that are for websites that are not very mainstream ( like non-english) sites.

**Comment by zero77** [comment]
Although you could make an automated new ruleset checking system to run in the back ground provided submissions where completely anonymous and there was an option to turn it off if required by the user.

**Comment by jsha** [comment]
Thanks for the suggestion! We probably won't implement this right now. In the past, as @J0WI says, we have found that automatically generated rulesets tend to be of low quality. However, we definitely should do some work to improve the automated checking of rulesets so we can have higher confidence in newly submitted rulesets.
