### ISSUE TITLE
www.sos.wa.gov supports TLS

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#4150]
https://www.sos.wa.gov/elections/myvote/olvr.html is functional, but the HTTP version doesn't automatically redirect.

I've only looked at at this one page, so I'm not sure whether the rest of the site works over TLS.

**Comment by jeremyn** [comment]
@strugee If you submit a pull request for this issue and @ me, I'll take a look. If you want to work on it, [here](https://www.eff.org/https-everywhere/rulesets) and [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) is some documentation to help you.
