### ISSUE TITLE
Biography.com videos

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#4156]
Videos on biography.com do not work when these are enabled:
Adobe.com
Akami.com

Example:
http://www.biography.com/people/franklin-d-roosevelt-9463381

**Comment by galeksandrp** [comment]
works on https://github.com/EFForg/https-everywhere/commit/master
@jeremyn

**Comment by jeremyn** [comment]
The video in the middle of the Biography.com page works fine now, thanks @galeksandrp.

@tancrackers Can you please confirm and if it works for you, close this issue?

**Comment by tancrackers** [comment]
Yes! It works in Firefox and in Chrome.
