### ISSUE TITLE
MapMyRun.com broken on Firefox with https-everywhere

### ISSUE THREAD

**Issue by joemccall86** [EFForg/https-everywhere#4159]
Following the recommendation made in the [FAQ](https://www.eff.org/https-everywhere/faq#faq-What-if-HTTPS-Everywhere-breaks-some-site-that-I-use?)

### Version
Firefox 44.0.2
Linux Mint 17.3 Cinnamon 64-bit
Https-Everywhere 5.1.2

### What breaks
Once I log into MapMyRun.com, the spinners spin indefinitely. Developer tools indicate that firefox is blocking scripts from consent.truste.com and cloudfront.net due to the CORS header missing. When I disable the rules for both those domains on mapmyrun.com it works. I'm also filing this with their website so they can fix things on their end.

### Other Browsers
This doesn't seem to affect Opera and Chromium running https-everywhere 2015.12.16.

**Comment by funkydude** [comment]
@joemccall86 Is this still an issue with the February update?

**Comment by joemccall86** [comment]
It appears to be. I updated and switched to default rules, and the issue still happened. If I disable the rule for cloudfront it works around the issue. I still get console errors for the missing CORS headers for truste, which I believe is something they need to address.
