### ISSUE TITLE
high memory usage in Chrome/Chromium

### ISSUE THREAD

**Issue by pszi1ard** [EFForg/https-everywhere#4160]
Chrome 48.0.2564.109 (64-bit) on OS X 10.11.3 I get 199 MB memory consumption reported (in the Chrome task manager) with a single tab but no websites open.
Chrome 48.0.2564.109 (64-bit) on Linux x86-64 I get 132,404 KB memory consumption reported with a few tab but no websites open.
Chromium 48.0.2564.82 Ubuntu 14.04 (64-bit) on Linux x86-64 I get 121,928 KB memory consumption reported with a single tab but no websites open.

I know that the reported amount of memory can be off, but this still seems rather high.

**Comment by semenko** [comment]
Duplicate #1775

**Comment by pszi1ard** [comment]
Thanks for the update and sorry for the duplicate.
