### ISSUE TITLE
Add a "Donate to EFF" menu item

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#4162]
Should link either

1. Directly to the supporters.eff.org donate page (no new design required)
2. A custom page for HTTPSE users (must coordinate with webdev & design for this)

**Comment by maxateff** [comment]
Need some assets + text from dev, but the path will be: https://supporters.eff.org/donate/support-https-everywhere

**Comment by fuglede** [comment]
Looks like this one could be closed?

Out of curiosity, are there any kind of donation motivating budgets on HTTPS-E openly available?

**Comment by Hainish** [comment]
@fuglede: https://www.eff.org/about/annual-reports-and-financials
