### ISSUE TITLE
http sites fail to load

### ISSUE THREAD

**Issue by Rrego6** [EFForg/https-everywhere#4164]
When trying to access any http website, a loading icon shows in the tab, but the current page of firefox never changes. 

Example site is pastebin.com. Fails to load if accesed from url bar, from google, and from duckduckgo. Same result occurs for all three. No visible error shown, but the current page never changes. Only https sites seem to load. If I open a search result from Google to an http site in a new tab a blank intersital is shown. Attempts to reload this page show the same intersital.

All http sites load properly when addon is disabled. Quck look through the issue tracker and I couldn't find any duplicate questions.

Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
on Arch Linux

Https Everywhere 5.1.0

**Comment by vgturtle127** [comment]
@Rrego6 Have you tried the latest version of HTTPS Everywhere?

**Comment by Rrego6** [comment]
Works now. Thanks @vgturtle127

**Comment by vgturtle127** [comment]
@Rrego6 Sure, no problem. I didn't really do anything. :laughing: 

Firefox and HTTPS Everywhere have both had extensive updates since then, so I assumed the problem was most likely patched.
