### ISSUE TITLE
gfblip.appspot.com does not work with https

### ISSUE THREAD

**Issue by pallas** [EFForg/https-everywhere#4174]
This site uses HTTP to send single-packet payloads to two different web servers in order to measure latency. This does not work with HTTPS but multiple rules for Google hit since this is on appspot.com, which should probably not be turned off.

**Comment by Bisaloo** [comment]
@pallas, this seems fixed. Is this still an issue for you? If not, can you close this issue please?

**Comment by J0WI** [comment]
Closing due the lack of response.
