### ISSUE TITLE
Google Maps issue

### ISSUE THREAD

**Issue by interloperux** [EFForg/https-everywhere#4175]
Hi. Okay so I have version 5.1.0 in Firefox. I use google.com.au

I go to maps.google.com.au with HTTPS Everywhere enabled. Search for an address. The address details load, but the map won't update, nor will it respond to direct interaction (zooming, clicking on locations.)

If I click Disable HTTPS Everywhere, the problem is resolved.

**Comment by funkydude** [comment]
@interloperux Does this happen with the February update?

**Comment by interloperux** [comment]
Sorry for the delay in replying. Yes, this is happening as of version 5.1.4

**Comment by J0WI** [comment]
@interloperux can you provide some console output?

**Comment by J0WI** [comment]
Closing due the lack of response.
