### ISSUE TITLE
"Tools" flyout is empty if Firefox starts with HTTPS-E widget hidden

### ISSUE THREAD

**Issue by kwill** [EFForg/https-everywhere#418]
Steps to reproduce:
- In Firefox, open the Customize interface
- Move HTTPS Everywhere widget into the "Additional" area (i.e. hidden, no longer appears on Firefox interface)
- Navigate to Tools and hover over "HTTPS Everywhere" (flyout appears, all options visible)
- Quit Firefox
- Start Firefox
- Navigate to Tools and hover over "HTTPS Everywhere"

What should happen:
- Flyout appears, all options visible

What happens instead:
- Very thin flyout appears, no options visible

Notes:

This works for other extensions, for example, AdBlock Edge.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
