### ISSUE TITLE
custom rulessets not used in new version?

### ISSUE THREAD

**Issue by rezad1393** [EFForg/https-everywhere#4180]
I updated to the new versions of addon and lost the ability to use custom rules saved in my profile folder. 

also in my firefox some of the rules that are being applied the tick is not shown in front of their name in menu. if I click on them then it reloads and it is shown as a cross but when enabled is shows as empty box with no tick .
this happens for some rules so some show correctly in menu but some don't.

**Comment by zymase** [comment]
Same here with HTTPS Everywhere 5.1.3 on Firefox 44.0.2 64-BIT / Windows 7 64-BIT
Several sites in France & Europe running perfectly well with https (confirmed with Calomel SSL Validation add-on) are not handled by HTTPS Everywhere and if custom rules no longer work I have no reason to keep it. Removed.

**Comment by Hainish** [comment]
I can reproduce this.  Looking into it now.

**Comment by Hainish** [comment]
Looks like there was a regression introduced via #4110 - `loadTargets` here never loads custom rules from the JSON: https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/code/HTTPSRules.js#L410

**Comment by Hainish** [comment]
`loadTargets` overwrites the targets that are set by the previous call to `scanRulefiles`.  Calling `scanRulefiles` after `loadTargets` should fix the problem.

**Comment by Hainish** [comment]
Note: we should probably include additional tests for custom rulesets to make sure they're being triggered properly (I like to use `example.com`, which we don't have a rule for but it has an https endpoint, which makes it perfect for a custom ruleset)
