### ISSUE TITLE
Infogram breaks graphics

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#4182]
Firefox 44.0.2
Https-everywhere 5.1.3

Filter:
Infogr.am (partial)

Example:
http://www.silive.com/news/index.ssf/2016/02/si_traffic_tickets_almost_doub.html

See the graphic "Top traffic violations on Staten Island," right above the comments.

**Comment by fuglede** [comment]
Thanks for the report. This is fixed by #4237 by not upgrading the relevant script.
