### ISSUE TITLE
breaks udacity.com

### ISSUE THREAD

**Issue by mathias-gibson** [EFForg/https-everywhere#4187]
results in lot being able to login to your account on the site

**Comment by bgkonzman** [comment]
Confirming this.

Specifically, the issue seems to be with the "Udacity.com (partial)" rules. When I uncheck that box and restart my browser, I can log in without issue.

**Comment by fuglede** [comment]
Can we close this one?

**Comment by bgkonzman** [comment]
Just checked the site with the 2016.3.23 release. Works now. We can close.

**Comment by fuglede** [comment]
Great, thanks for the fix!
