### ISSUE TITLE
tampabay.com rule breaks site

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#4190]
Tampa Bay.com (partial) breaks the site www.tampabay.com

**Comment by funkydude** [comment]
@terrorist96 Works fine here, please post useful information in your bug report. Browser, browser version, HTTPSE version. Describe exactly how it's "broken".

**Comment by terrorist96** [comment]
My bad. Looks like there's no issue. Before, the stylesheet was broken and was fixed when I disabled that rule. I tested it a few times too, to be sure.
