### ISSUE TITLE
Synchronize version numbers and versioning styles between different versions

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#4194]
So Firefox version numbers are the typical 0.0.0 version scheme. Makes sense to me.

But then you get to the Chrome version, and those are dates when it was updated. This would be OK if it also allowed you to view the version number, but it doesn't.

But with Firefox, you get the version number and the date it was updated.

This is confusing in my opinion. I think it would be easier if either you switched both to the typical version scheme for extensions/addons, or you could make them both date version numbers, but also supply a version number as well.

I think changing this will make it less confusing for users and developers, and easier to pinpoint regressions and bugs. This is my opinion obviously, but let me know what you guys think.

Feedback would be appreciated.

**Comment by jeremyn** [comment]
I agree with this request.

@Hainish Any chance we can synchronize the version numbers between Firefox and Chrome with the change to using WebExtensions for Firefox?

**Comment by Hainish** [comment]
@jeremyn yes, that's the plan.  We'll be standardizing on the `YYYY.MM.DD` versioning.  The git tags will also be standardized using this format.

**Comment by jeremyn** [comment]
Great! I agree that standardizing on date instead of incrementing numbers is the way to go here.

**Comment by gloomy-ghost** [comment]
Already standardized in #12301, closing as fixed
