### ISSUE TITLE
Imgur's advanced editor is broken with HTTPS

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#420]
It just keeps loading forever. I'm using Firefox 32 on Windows 8.1 Update.

Perhaps this is relevant:

```
https://s.imgur.com/min/global.js?1407545757 is being assigned a //# sourceMappingURL, but already has one
https://s.imgur.com/min/edit.js?1407545757 is being assigned a //# sourceMappingURL, but already has one
```

**Comment by semenko** [comment]
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Comment by justlurking** [comment]
This is probably not the place for this question but I'm not sure where else to ask.  I originally submitted this bug.  If I had whitelisted the site to make it work on a previous version of the extension, where do I go to remove the whitelist (and to view any other sites I might have previously whitelisted and which may now be functioning properly?)  Thank you.

**Comment by semenko** [comment]
I don't think we have a great way to do that currently. One option is to visit imgur.com & click on the HTTPSe extension icon -- you should then be able to re-enable the ruleset (if you previously disabled it).

**Comment by justlurking** [comment]
My apologies - I meant to post in issue #1417 (https://github.com/EFForg/https-everywhere/issues/1417).  That bug on the WSJ comments involved embedded comments hosted by livefyre, but there may have been other domains involved.  Do you know which domains I should browse to for bug #1417 in order to test for removed rules?  Thanks again.

**Comment by semenko** [comment]
Hm, honestly not sure the best way to go about that, other than just visiting the wsj site and hoping the disabled rule is encompassed. (I think in Chrome, entirely removing and reinstalling the extension resets its preferences.)

**Comment by justlurking** [comment]
Thanks.  I wasn't seeing anything whitelisted, so I deleted and reinstalled just to be sure.  Might be a good "future enhancement" opportunity for the extension for users to be able to view, modify, and "reset to default" any user-created rule changes.
