### ISSUE TITLE
Fake_Name_Generator.com.xml should be off by default

### ISSUE THREAD

**Issue by bui** [EFForg/https-everywhere#4202]
Using HTTPS on fakenamegenerator.com requires their premium service. Thus, HTTPS Everywhere causes every request on there to be redirected to https://www.fakenamegenerator.com/premium.php

**Comment by funkydude** [comment]
This can be closed. Fixed by commit https://github.com/EFForg/https-everywhere/commit/53aa7f956cb64567bf36a5ac7ea418c28146235e
