### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#4215]
I tried to fork the repository to contribute, but uh...

Well, my hard drive filled up and then Git crashed. :laughing: 

So when I was wondering what happened, I opened up the folder to find about 80 branches. Some were very large (I am unsure why).

Maybe we can clean some of those up?

I know sometimes people use them as snapshots of code from various versions and stuff, but some of the branches are very old, and some have really unhelpful names. If we can help clean up the branches in any way, that would be good for people on Windows for sure, but also people who by default download all branches, but might not have a huge hard drive as their main drive.

I know I don't have to download all of the branches, but I didn't know there were so many. :wink: 

Any thoughts or feedback on this would be appreciated.

**Comment by funkydude** [comment]
I'm not going to comment on your PC issues but I do agree that some branches could be purged.

**Comment by vgturtle127** [comment]
@funkydude Well, it was only mostly my PC. Downloading gigabytes of branches was never my intention. :laughing:

**Comment by funkydude** [comment]
My repo directory is ~250MB, but still, it's annoying scrolling down all the branches sometimes.

**Comment by vgturtle127** [comment]
@funkydude My Git client downloads all branches as a separate directory, so it gets a bit huge sometimes. I switched to the GitHub desktop client and it isn't as bad. :smile:

**Comment by gloomy-ghost** [comment]
I'm closing this issue since #6965 is assigned.
