### ISSUE TITLE
icon gets blurry when moved menu from toolbar in Firefox

### ISSUE THREAD

**Issue by peterbandi** [EFForg/https-everywhere#4219]
The icon of HTTPS-Everywhere is blurry if moved to the menu from the toolbar in Firefox. Sytem: Windows 10, Firefox 44.0.2 (64 bit).

![firefox_menu](https://cloud.githubusercontent.com/assets/16120716/13304863/adff2554-db57-11e5-973d-edf0934a6968.png)

**Comment by jeremyn** [comment]
I can confirm this problem still exists even with the new icon, Windows 10, Firefox 48.0.2.

**Comment by gloomy-ghost** [comment]
@Hainish I checked the icon field in Chrome manifest file, which was modified in a release commit. Just wondering would it be possible to fix the Firefox version in next release?

**Comment by Hainish** [comment]
We had a problem when providing the high-resolution icon in the manifest.  With OSX retina displays, the icon appeared disproportionately large.  We'll have to consider and test for this when making any change to the icon resolution.

**Comment by gloomy-ghost** [comment]
Verified as fixed in release 2017.8.19, but feel free to re-open this if anyone is still having the issue.
