### ISSUE TITLE
HTTPS Everywhere breaks SVG <use> elements (e.g. YouTube embed buttons, forecast.io clip-path), in Firefox

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#4220]
STR: **(NOTE: these YouTube STR no longer trigger the bug, as of ~June 2016. Use forcecast.io STR further down instead.)**
1. Install Firefox Nightly from https://nightly.mozilla.org/
2. Install HTTPS Everywhere from https://www.eff.org/Https-everywhere and restart Firefox to complete installation.
3. Visit http://www.youtube.com/embed/C4qgAaxB_pc and click the video to start playing.

(NOTE: the URL you type or paste in needs to be HTTP, not HTTPS. That is important.)

ACTUAL RESULTS:
Controls (e.g. play button) are not visible.

EXPECTED RESULTS:
Controls should be visible.

I diagnosed this in https://bugzilla.mozilla.org/show_bug.cgi?id=1250770 -- the issue is here:
https://github.com/EFForg/https-everywhere/blob/fbfaac74e0d2e15227ce69421028c2b337db66aa/src/chrome/content/code/HTTPSRules.js#L163

HTTPS Everywhere is initializing a `nsIStandardURL` with a "default port" of 80, but it's almost-certainly an HTTPS URI (given that it's an upgraded URI that HTTPS Everywhere is producing), so 80 is almost-certainly-wrong.

The bug goes away if I replace 80 with 443 in that init() call.

NOTE: This bug will likely not reproduce in Firefox Beta 45 or Firefox Aurora 46, because those versions have a [band-aid](https://bugzilla.mozilla.org/show_bug.cgi?id=1249452) for a related Gecko bug, and that band-aid happens to work around this bug as well. So -- to test this, use Firefox Nightly 47.

**Comment by dholbert** [comment]
I believe this same bug also breaks clipping in some SVG charts on forecast.io. (Clipping is similar to `<use>` in that it has local ID references and has same-origin checks.  If the channel's URI has the wrong default port, as is the case here, then the same-origin URI comparison fails.)

Steps to reproduce for this forecast.io issue, with Firefox & HTTPS Everywhere installed:
 (1) Visit http://forecast.io/lines/ (the "http" is important there).
 (2) Look at the left edge of the graphs.

ACTUAL RESULTS: The graph's lines overlap the vertical-axis labels.
EXPECTED RESULTS: The paths should be clipped to the graph region -- they shouldn't overlap the vertical-axis labels.

The lines each inside of a `<g clip-path="url(#highcharts-1)">` element, which should clip them to the graph area. But there's no clipping if HTTPS Everywhere is upgrading the page from HTTP to HTTPS, due to this bug.

**Comment by Hainish** [comment]
I'm not able to reproduce this issue in either Firefox 45, Firefox Nightly (48.0a2) or current nightly (49.0a1).  Is this still an issue?

**Comment by dholbert** [comment]
Yes, I'm still seeing this reproduce this in latest Nightly 49.0a1 (2016-06-02), with HTTPS Everywhere 5.1.9 (latest stable release).

(If you can't reproduce, I'm wondering whether you might accidentally be loading the https version of the page directly. As noted in the STR, it's important that you use HTTP when entering the URL, because that's what lets HTTPS Everywhere perform the HTTPS upgrading that triggers the bug.)

**Comment by dholbert** [comment]
(My post just now was about [the forecast.io steps-to-reproduce](https://github.com/EFForg/https-everywhere/issues/4220#issuecomment-193420988) -- those definitely still reproduce this bug.

However, my original YouTube steps-to-reproduce don't seem to trigger the bug anymore. That's probably because YouTube has upgraded to use HSTS for https-upgrading, and perhaps that's even being shipped in Firefox's preload list so that YouTube URLs get upgraded before HTTPSEverywhere gets a chance to touch them.)
