### ISSUE TITLE
Can't open EOBs in Anthem

### ISSUE THREAD

**Issue by edbkegan3** [EFForg/https-everywhere#4229]
I can log into the anthem.com website and navigate like normal with HTTPS Everywhere enabled, but when I go to view an EOB, it tries until it times out and gives me an error.  I was only able to see the EOB after I disabled HTTPS Everywhere.  I have uBlock Origin installed, but I have anthem.com whitelisted.

**Comment by jeremyn** [comment]
@edbkegan3 Is this still an issue for you? Can you reproduce this problem on any anthem.com page that doesn't require a login? Thanks.

**Comment by pipboy96** [comment]
No follow-up since 2016, can't reproduce without account.
