### ISSUE TITLE
Website/Changelog discrepancies

### ISSUE THREAD

**Issue by nelegalno** [EFForg/https-everywhere#424]
The contents of https://www.eff.org/files/Changelog.txt (matches the one from 4.0 branch) and https://github.com/EFForg/https-everywhere/blob/master/src/Changelog do not mach.

Also the https://www.eff.org/files/https-everywhere-latest.xpi still points to v3.5.3. and there is no link to v4 but the file is uploaded to the server https://www.eff.org/files/https-everywhere-4.0.0.xpi and the v5 dev link is published.

**Comment by rugk** [comment]
The Changelog at https://www.eff.org/files/Changelog.txt is again outdated, because the most recent version is 5.0.6.

**Comment by jsha** [comment]
Thanks! Fixed. Will take a little time for our caching layer to clear.

**Comment by blobgo** [comment]
Already updated for v 5.0.7? (https://github.com/EFForg/https-everywhere/commit/06e657d223d10c0e4fc86730858b95c33cf5cdb6)
https://www.eff.org/files/Changelog.txt now shows 5.0.6 as the newest Firefox version.

**Comment by jsha** [comment]
Fixed for 5.0.7 now too.
