### ISSUE TITLE
In Firefox Nightly, "NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments [nsICookieManager2.remove] HTTPS.js:164:0"

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#4241]
Not sure about exact STR, but in Firefox Nightly 47 with HTTPS Everywhere 5.1.4, I saw this error in my Browser Console (ctrl shift J):

> NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments [nsICookieManager2.remove] HTTPS.js:164:0

This points to the following source code in HTTPS Everywhere's HTTPS.js source file:

```
  handleInsecureCookie: function(c) {
      [...]
      cookieManager.remove(c.host, c.name, c.path, false);
```

The error happens because the `remove` function-signature was modified recently, here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1245184
http://hg.mozilla.org/mozilla-central/diff/ab3a305b3e41/netwerk/cookie/nsICookieManager.idl#l47

A new parameter "aOriginAttributes" has been added.

**Comment by dholbert** [comment]
(CCing @bakulf who made this change in Gecko.)

**Comment by bakulf** [comment]
the new method wants an additional param. Change that line to:

cookieManager.remove(c.host, c.name, c.path, c.originAttributes, false);

**Comment by dholbert** [comment]
(Of course, that change on its own would make HTTPS Everywhere stop working in earlier versions of Firefox. So really, I suspect they might want to do this in a try{}catch{}, or something else to allow for both versions of the method.)

**Comment by Vednier** [comment]
Right now Nightly (Firefox 50) throws a lot of errors like this in console
“nsICookieManager.remove()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManagerHTTPS.js:164:6
“nsICookieManager2.add()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2HTTPS.js:165:6

**Comment by Vednier** [comment]
> the new method wants an additional param. Change that line to:
cookieManager.remove(c.host, c.name, c.path, c.originAttributes, false);

No, this doesnt work, changing that in HTTPS.js only cause this error to appear.
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICookieManager2.remove]           HTTPS.js:164

**Comment by Lithopsian** [comment]
They changed it so that origin attributes is the last parameter.  It appeared as the fourth parameter in an initial incarnation in nightly, but that just broke too many addons, so it was moved after the existing parameters.  It is also optional, although the documentation doesn't say that and it is likely to become mandatory at some point.  The console message should only appear if the origin attributes parameter (the fifth one) is undefined or empty.

**Comment by Vednier** [comment]
Changing lines 164 and 165 from
`cookieManager.remove(c.host, c.name, c.path, false);
      cookieManager.add(c.host, c.path, c.name, c.value, true, c.isHTTPOnly, c.isSession, expiry);`
to 
`cookieManager.remove(c.host, c.name, c.path, false, c.originAttributes);
      cookieManager.add(c.host, c.path, c.name, c.value, true, c.isHTTPOnly, c.isSession, expiry, c.originAttributes);`

Solves problem completely (but breaks signing, which i dont care for)

**Comment by evilpie** [comment]
Can we get this fixed? @Hainish @jeremyn

**Comment by bakulf** [comment]
You don't need to fix this issue. We make originAttributes an optional argument.

**Comment by dholbert** [comment]
Ah, looks like that indeed changed in https://bugzilla.mozilla.org/show_bug.cgi?id=1259169 (a few months after this bug was filed).

OK, I think this issue can just be closed then -- this was addressed by that ^^ bugzilla bug.

(As a sanity-check that this is indeed fixed: I don't see any mentions of NS_ERROR_XPC_NOT_ENOUGH_ARGS in my error console, in my current Firefox session which has HTTPS Everywhere active.)

**Comment by Vednier** [comment]
> (As a sanity-check that this is indeed fixed: I don't see any mentions of NS_ERROR_XPC_NOT_ENOUGH_ARGS in my error console, in my current Firefox session which has HTTPS Everywhere active.)

Sure about that?
I see like loads of 
`“nsICookieManager.remove()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager  HTTPS.js:164:6
“nsICookieManager2.add()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  HTTPS.js:165:6
“nsICookieManager.remove()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager  HTTPS.js:164:6
“nsICookieManager2.add()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  HTTPS.js:165:6
`
in my console. Using 51.0a1 (2016-09-19) (64-bit) Nighly

**Comment by Vednier** [comment]
There is still tons of deprecation warnings instead in  51.0a1 (2016-09-19) (64-bit) Nighly 

“nsICookieManager.remove()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager  HTTPS.js:164:6

“nsICookieManager2.add()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2  HTTPS.js:165:6

**Comment by dholbert** [comment]
Ah, I guess I must not have exercised HTTPS Everywhere sufficiently in that browser-session.

@bakulf , are those warnings expected?  If not, we should figure out what's causing them...  Or if they are indeed expected, then we should indeed get this fixed in HTTPS Everywhere.

**Comment by bakulf** [comment]
Those warnings are expected if OriginAttributes is not passed as argument, yes. I was commenting the title of the bug, and nsICookieManager.remove() doesn't throw NS_ERROR_XPC_NOT_ENOUGH_ARGS anymore, so this issue it's fixed.

I'm going to send a pull-request for this issue, but we should file a new for supporting originAttributes correctly. This means: privateBrowsing(?), WebExtensions and containers, these 3 features (and maybe in the future we could have more) are currently managed via OriginAttributes.

**Comment by bakulf** [comment]
https://github.com/EFForg/https-everywhere/pull/6920

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
