### ISSUE TITLE
Could still pick up UN/P...

### ISSUE THREAD

**Issue by chewzerita** [EFForg/https-everywhere#4242]
I don't know if this is website specific, but using the [cpm online textbook](http://ca4425.textbooks.cpm.org/)  with the extension enabled still picked up the username and password in ettercap. Ettercap/Wireshark showed the traffic as HTTP, so is it user error or just site specific?

**Comment by numismatika** [comment]
This addon relies on a hand-picked list of rules to rewrite requests.
In this case there is no rule applied to the specific site you mentioned.
It also isn't possible to write one at this time, because the site doesn't offer a valid cert for the subdomain you mentioned.

**Comment by fuglede** [comment]
Closing this as unfixable.
