### ISSUE TITLE
3sat.de CDN not https ready now

### ISSUE THREAD

**Issue by Webmaster3sat** [EFForg/https-everywhere#4245]
Hi,

3sat.de is now defined in your ruleset, nice - but the CDN is not complete https-ready until now. For example the whole videoplayout is http-only and needs some time. So for example https://www.3sat.de/mediathek fails due to https/http-mismatch with your ruleset

could you please revert all *.3sat.de https-forwardings for now ?

https://www.eff.org/https-everywhere/atlas/domains/3sat.de.html

Thx!

**Comment by numismatika** [comment]
Videos seem to come from zdf_hdflash_dach-vh.akamaihd.net which gets an A- in the SSLLabs test:
https://www.ssllabs.com/ssltest/analyze.html?d=zdf_hdflash_dach-vh.akamaihd.net&s=23.61.195.83
So i suspect it is the player  that is used on the page that can't handle the rewrite.

On a related note, the detection script has bad defaults, if you have both a browser for html5 and a flash plugin, the site should load the html5 player not the flashplayer.

**Comment by Webmaster3sat** [comment]
There are several videoformats we deliver via akamai (HLS+Adaptive+f4m and more on different subs) and most of them are only delivered http by now (although the host itselfs has akamai-ssl-support), trustme!. https for 3sat.de is in testing stage and should not be used till it is ready! There are more things, which need to be protocoll-relative (or fixed otherwise) to work as expected!

**Comment by numismatika** [comment]
@Webmaster3sat pull request to fix it is open.
Please consider making flash the fallback and html5 the default in the future.
