### ISSUE TITLE
SSLObservatory causes massive slow down of 4chan catalog

### ISSUE THREAD

**Issue by NougatRillettes** [EFForg/https-everywhere#4251]
When browsing one of 4chan's boards' catalog with SSLobservatory enabled, two of my cores goes up to 100% and firefox becomes laggy for about two to five seconds. After checking with FF's Performance profiler, it seems that SSLObservatory's `observe` function is guilty.
![profile](https://cloud.githubusercontent.com/assets/1002826/13458963/d4302bcc-e0b3-11e5-9220-6741bb83ed0b.png)

**Comment by NougatRillettes** [comment]
Possibly linked to #4119

**Comment by gloomy-ghost** [comment]
Closing as obsolete since we have migrated to WebExtension.
