### ISSUE TITLE
Allows insecure images with enabled predefined rulesets

### ISSUE THREAD

**Issue by The-Keeper** [EFForg/https-everywhere#4253]
I get Mixed Content warnings from time to time, apparently when there are images with `http://` prefixes (in particular at stackexchange sites, on pages with imgur-links). For example [here](https://tex.stackexchange.com/questions/1319/showcase-of-beautiful-typography-done-in-tex-friends) and [here](https://tex.stackexchange.com/questions/230526/list-of-books-written-in-latex-with-the-source-available), while the extension button menu shows that _imgur_ ruleset is checked.
As I've learned, HTTPS Everywhere should deal with hotlinks by changing prefixes to `https`. 

I've also created a clean profile to install only HTTPS Everywhere (to test 'some conflict between extensions' hypothesis), but it still gives the warning with similar circumstances.

software versions: Firefox 44.0.2; HTTPS-Everywhere 5.1.4
(These warnings are also reproduced in Chromium)

**Comment by numismatika** [comment]
The addon will rewrite all content it finds matching rules for.
Mixed-Content is checked by the browser **before **the rewrites happen, so the https-everywhere can't do anything about it.

**Comment by The-Keeper** [comment]
@numismatika so I should treat these warnings as false alarm? Is there an extension that will show true state of connections? Or maybe some 'lock applet' replacement?

**Comment by jeremyn** [comment]
@The-Keeper I'm not sure what you're asking. Could you please be more specific?
