### ISSUE TITLE
add amazon.com

### ISSUE THREAD

**Issue by alex** [EFForg/https-everywhere#4255]
As of today amazon.com appears to support HTTPS, on every page I've looked at. I can't say I've visited the entire site or anything, but I think it might be ready to be HTTPS everywhere'd!

**Comment by funkydude** [comment]
@alex Whilst the homepage works fine, clicking on some links push back to http e.g. Amazon Tap, deal of the day. I'd wager that when they fully support it they will make an announcement boasting about it.

**Comment by loveithateit** [comment]
@alex Some parts added in 2feba2877b5dc26471da83c88f1df8acd63967ac, resulting from a cursory browse. There's definitely more to be added.

It needs testing and feedback from Amazon users.

**Comment by ratcheer** [comment]
If I click on View All Rules and search for Amazon, I find a complex ruleset for amazon.com (in the standard provided rulesets). However, if I surf to amazon.com or www.amazon.com, I get an http connection.

If I then write a simple rule for amazon.com, similar to the example rule given on the HTTPS Everywhere Rulesets web page, and restart my browser, it will give me HTTPS connections.

Why does the standard provided amazon.com ruleset not work for even the simplest scenario?

**Comment by funkydude** [comment]
@ratcheer There is no way to create a rule "for the simplest scenario". A rule will encompass everything on a set domain, to make it "simpler", you need to add exclusions. A glance at the current exclusion list just shows what a mess Amazon is currently.

**Comment by ratcheer** [comment]
Ok, thank you funkydude.

**Comment by J0WI** [comment]
closed by #4997
