### ISSUE TITLE
LongTail ruleset breaks certain versions of jwplayer (democracynow.org)

### ISSUE THREAD

**Issue by dndprude** [EFForg/https-everywhere#4259]
The LongTail ruleset causes certain jwplayer versions to fail to load with the error "Could not load plugins: File not found." This effects both flash and html5 playback.

Example broken jwplayer 6.8.4616 link:
http://www.democracynow.org 

Example working jwplayer 7.1.0 link: 
http://www.democracynow.org/2015/8/18/meet_the_whistleblower_who_exposed_the

**Comment by funkydude** [comment]
@fuglede closed by https://github.com/EFForg/https-everywhere/pull/4218
