### ISSUE TITLE
5.0dev is incompatible with Android Firefox beta at the moment

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#426]
When i try to install https-everywhere 5.0dev on my android phone with firefox beta, the installation fails.

**Comment by reedy** [comment]
Is this still broken?

**Comment by numismatika** [comment]
@reedy I can't tell for sure, i currently haven't got access to a working android device

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.
