### ISSUE TITLE
https everywhere breaking the glorious GOP debate stream

### ISSUE THREAD

**Issue by carlzoo** [EFForg/https-everywhere#4262]
getting 404 video not found on this page:http://www.foxnews.com/live-coverage/fox-news-gop-debate
But when I turn it off it works.

May not be able to reproduce tomorrow as video link might be removed.

Here is what the error looks like:
https://i.gyazo.com/c520ec71810e72278c41bf56f17eff1c.png

**Comment by jeremyn** [comment]
@carlzoo I don't see the error you referred to on http://www.foxnews.com/live-coverage/fox-news-gop-debate . Is this still broken for you?

**Comment by carlzoo** [comment]
@jeremyn thanks for the timely reply. I'm guessing this issue only happened when that event was streaming live. But now it is working for me as well.
