### ISSUE TITLE
Breaks video playback on discovery.com (e.g. https://www.discovery.com/tv-shows/mythbusters/videos/)

### ISSUE THREAD

**Issue by DanHarkless** [EFForg/https-everywhere#4263]
Had to disable HTTPS Everywhere on www.discovery.com to get TV show videos on the site working again.

**Comment by galeksandrp** [comment]
Also MCB/CORS issue on https://www.discovery.com/schedule/

**Comment by gloomy-ghost** [comment]
https://www.discovery.com/schedule/ still has CORS issues but the video is playing fine
