### ISSUE TITLE
Removing toolbar button renders menu nonfunctional until button is returned

### ISSUE THREAD

**Issue by DanHarkless** [EFForg/https-everywhere#4264]
Back when I installed HTTPS Everywhere (a few months ago on this Firefox profile), I removed the toolbar button using View... Toolbars... Customize, because the same actions can be achieved with the Tools... HTTPS Everywhere menu, and I personally don't like to have unneeded buttons reducing my browser real estate for URL display, etc. (and in this case, also distracting me unnecessarily with the rules counter).  However, today when I went to try to disable the rule for www.discovery.com to get videos working again (see Issue #4263), I found that I could not, because hovering over Tools... HTTPS Everywhere showed nothing -- no submenu appeared.

To get it working again, I had to use View... Toolbars... Customize to put the button back on my toolbar.  After I had done this and used the button to disable the www.discovery.com rule, I found that the menu was working again, so I again removed the button.  So far the menu is continuing to work with the button hidden, but if it breaks again after a browser restart, I'll update this issue.

**Comment by DanHarkless** [comment]
OK, restarted my browser, and unfortunately the HTTPS Everywhere menu is nonfunctional again -- I am forced to replace the unwanted toolbar button.  Other extensions like Adblock Plus have their menus function even if you remove their toolbar buttons, so hopefully HTTPS Everywhere can be updated so that's the case for it as well.  (And I believe it used to work.)

**Comment by DanHarkless** [comment]
BTW, this occurs on Windows 7 32-bit and 64-bit (32-bit Firefox in both cases), and also Linux 64-bit, and is repeatable.

**Comment by jeremyn** [comment]
Thanks for the report. I can reproduce this problem with Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.3.

By the way, you can turn off the counter by unchecking "Show Counter" in the add-on submenu.

**Comment by Hainish** [comment]
This should be fixed in the WebExtensions version.  Closing now, if you're still having issues please open a new issue
