### ISSUE TITLE
Google APIs breaks loading on steam.tools/cards

### ISSUE THREAD

**Issue by erbkaiser** [EFForg/https-everywhere#4265]
The Google APIs stable rule breaks the loading of the tables on http://steam.tools/cards

Version 2016.2.23 for Opera browser.

**Comment by jeremyn** [comment]
Thanks for the report. I can't reproduce this in Firefox 48.0.2, HTTPS Everywhere 5.2.4. Is this still a problem for you?

**Comment by erbkaiser** [comment]
Thanks for the response. It's been fixed in the mean time.

I forgot I had reported it here.

**Comment by jeremyn** [comment]
No problem, thanks for closing the issue.
