### ISSUE TITLE
NitroSell.com (partial) breaks image loading on store pages

### ISSUE THREAD

**Issue by twistedau** [EFForg/https-everywhere#4272]
Having NitroSell.com (partial) enabled causes images not to be loaded on sites such as this example page: http://www.mypetwarehouse.com.au/cat-collar-leads-harness?sort=price&order=.

**Comment by J0WI** [comment]
Works for me, @twistedau can you confirm?

**Comment by twistedau** [comment]
For me it looks like the NitroSell.com (partial) rule is no longer applying. Not sure if there's a change to the rule or the site. It all works fine now.
