### ISSUE TITLE
https://www.ucl.ac.uk/dropbox/ not working

### ISSUE THREAD

**Issue by mu22le** [EFForg/https-everywhere#4288]
Hello, 
the ucl.ac.uk rule needs an exception to redirect http://www.ucl.ac.uk/dropbox/ to https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox.cgi and not to https://www.ucl.ac.uk/dropbox/ as the latter does not work.

**Comment by jeremyn** [comment]
Pull request #6241, after it's merged and pushed live, should resolve this issue. Going forward, exactly these four URLs:

http://ucl.ac.uk/dropbox
http://ucl.ac.uk/dropbox/
http://www.ucl.ac.uk/dropbox
http://www.ucl.ac.uk/dropbox/

should redirect to https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox.cgi .
