### ISSUE TITLE
Please add a MetaInfo file for software centers

### ISSUE THREAD

**Issue by hughsie** [EFForg/https-everywhere#431]
Please consider including this file in the https-everywhere.xpi bundle: http://people.freedesktop.org/~hughsient/temp/mozilla-https-everywhere.metainfo.xml

It has to be named mozilla-https-everywhere.metainfo.xml and should be optionally installed to /usr/share/appdata on GNU/Linux. I'm happy to reassign copyright or change the licence as required. This will allow us to show https-everywhere as an addon in gnome-software in the future. See http://blogs.gnome.org/hughsie/2014/06/ ... -software/ for more information. Thanks!

Richard

**Comment by StevenRoddis** [comment]
Hi @hughsie from what I understand from your post the file should go here: https://github.com/EFForg/https-everywhere/tree/master/src

**Comment by hughsie** [comment]
You can upload the file into the repo where-ever you like, but it needs to be installed onto the host system in /usr/share/appdata

**Comment by gloomy-ghost** [comment]
I don't really understand this proposal, but for now we don't have direct access to filesystem. Closing as a part of clean-up after migrating to WebExtension.
