### ISSUE TITLE
Breaking Firefox 45 developer tools

### ISSUE THREAD

**Issue by flyrs8810** [EFForg/https-everywhere#4320]
When opening developer tools in Firefox 45. Under the Inspector tab on the right where css rules should show, it is blank ( on any site ). Disabling this add-on fixes the issue. I am using Windows 7 64bit ( if that is of any help )

**Comment by jeremyn** [comment]
I can't reproduce this problem on Firefox 48.0.2, Windows 10, visiting https://www.eff.org/ . Is this still broken for you?

**Comment by flyrs8810** [comment]
I have updated to Firefox 48 and the problem seems to be fixed. No broken sites so far.
