### ISSUE TITLE
"Disable HTTPS Everywhere" works, but disabling each rule individually does not.

### ISSUE THREAD

**Issue by ChodaBoy** [EFForg/https-everywhere#4322]
http://www.sbnation.com/2016/3/2/11145404/shanghai-major-problems-dota-esports-lost-keyboard-soundproof-booths-problems

If I disable each HTTPS Everywhere rule for the above page, some images still do not appear. See: HTTPSE1.png

However, if I completely disable HTTPS Everywhere, the image appears. See: HTTPSE2.png

It would seem that HTTPS Everywhere is affecting the page even though the rules are disabled individually, which is unwanted.

Firefox 44.0.2
![httpse1](https://cloud.githubusercontent.com/assets/2310708/13662414/ddaa3e34-e65f-11e5-8911-c74d5184f73e.png)
![httpse2](https://cloud.githubusercontent.com/assets/2310708/13662421/e90ebebc-e65f-11e5-943c-78601036dc52.png)

**Comment by gloomy-ghost** [comment]
Closing as obsolete since we have migrated to WebExtension.
