### ISSUE TITLE
Data from SSL observatory

### ISSUE THREAD

**Issue by schmiedecker** [EFForg/https-everywhere#4323]
I was wondering, is there any way to query the SSL observatory for seen certificates? Are there plans to release the data, or build an API to query it similar to the ICSI notary? 

I'd be happy to help get this data published, host it on one of my servers, or help pushing it in some other way. Pushing the data to scans.io or into censys (even not-uttermost-recent-data cleaned of all user-identifying information) would be a treat for the scientific community.

**Comment by rugk** [comment]
Any information on this?

**Comment by pipboy96** [comment]
@schmiedecker You may be interested in https://crt.sh/. HTTPS Observatory no longer functions.
