### ISSUE TITLE
UI bug in Opera Developer

### ISSUE THREAD

**Issue by bkrcrc** [EFForg/https-everywhere#4330]
Opera Developer version: 37.0.2163.0 [DOWNLOAD](https://get.geo.opera.com/pub/opera-developer/37.0.2163.0/)
HTTPS Everywhere version: 2016.2.23
Screenshot: https://s11.postimg.org/xdwfr8nkj/screenshot.png

Please fix the problem, on stable Opera release there is no problem but Opera Developer version has this bug. I do not know is it Opera's problem or not?
Please fix this before this Opera version will be stable.

Thanks

**Comment by ihave100openPRs** [comment]
@bkrcrc Can you reproduce that problem now? If not please close this issue.
