### ISSUE TITLE
Breaks video playback on several norwegian websites

### ISSUE THREAD

**Issue by JallaJ** [EFForg/https-everywhere#4332]
The https-everywhere plugin for Chrome prevents video playback on several norwegian sites, including
http://www.vgtv.no/
http://www.aftenposten.no/webtv/
http://www.bt.no/tv/

**Comment by numismatika** [comment]
They are using JWplayer so #4218 might fix this one too

**Comment by numismatika** [comment]
@JallaJ  would you mind having a look at the alternative names on https://www.ssllabs.com/ssltest/analyze.html?d=ap.mnocdn.no and grouping them together and telling us where they belong to? 
I'd like to get the hosts into the correct files when trying to fix these media sites

**Comment by numismatika** [comment]
@JallaJ  would you mind having a look at the alternative names on https://www.ssllabs.com/ssltest/analyze.html?d=ap.mnocdn.no and grouping them together and telling us where they belong to? 
I'd like to get the hosts into the correct files when trying to fix these media sites

**Comment by JallaJ** [comment]
@numismatika I'd be glad to help but unfortunately I'm clueless about this stuff.. Could you explain what you mean by "grouping them together and telling us where they belong to"?

**Comment by numismatika** [comment]
@JallaJ the issue i have with this stuff is that i can't figure out what domain belongs to the actual newspaper, what belongs to the press company that runs them , what is a cdn and what is custom api like googleapis.
Schipstedno for example seems to overlap with medianorge.
I could make one big "norwegianstuff.xml" but it is better to split that.

**Comment by funkydude** [comment]
@fuglede closed by https://github.com/EFForg/https-everywhere/pull/4218
