### ISSUE TITLE
Videos in the 3sat library cause redirect loop

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#4351]
Example: https://www.3sat.de/mediathek/?mode=play&obj=50970

You see that the site tries to reload itself again and again...

**Comment by numismatika** [comment]
i would say duplicate of #4245

**Comment by rugk** [comment]
@numismatik Yes, indeed this seems to be a duplicate.
Feel free to close it.

**Comment by J0WI** [comment]
Closed by #4254
