### ISSUE TITLE
amazon video breaks with https everywhere

### ISSUE THREAD

**Issue by philgithub1** [EFForg/https-everywhere#4366]
FF45
addon 5.1.4
clicking a video opens window but soon says silverlight is not installed.
diabling the addon cures it

**Comment by J0WI** [comment]
Please provide an url

**Comment by charlesbevans** [comment]
I can confirm, and there appear to be duplicates of this bug in the issue tracker.
http://www.amazon.com/gp/product/B0172TTTD0?ref_=aiv_dp_season_select

**Comment by J0WI** [comment]
closed by #4997
