### ISSUE TITLE
Forbid `*` in the middle of the target host

### ISSUE THREAD

**Issue by RReverser** [EFForg/https-everywhere#4369]
As @jsha pointed in https://github.com/EFForg/https-everywhere/issues/2981#issuecomment-194468323:

> Agreed we want to remove internal \* in target hosts, and remove it from support in the rewriter.

So decided to create an issue for 1) removal of support for this in rewriter code 2) having tests that check against such `<target host />` occurences.

**Comment by RReverser** [comment]
Looks like after https://github.com/EFForg/https-everywhere/issues/2981 was fixed by https://github.com/EFForg/https-everywhere/pull/3603, some new cases appeared:

```
src/chrome/content/rules/Argonne-National-Laboratory.xml:	<target host="www.*.anl.gov" />
src/chrome/content/rules/General-Electric.xml:	<target host="files.*.geblogs.com"/>
src/chrome/content/rules/GPLHost.xml:	<target host="dtc.*.gplhost.com"/>
src/chrome/content/rules/Monster.xml:	<target host="hiring.*.monster.com" />
src/chrome/content/rules/OnSugar.xml:	<target host="secure.*.onsugar.com" />
src/chrome/content/rules/OnSugar.xml:	<target host="www.*.onsugar.com" />
src/chrome/content/rules/Projectplace.com.xml:	<target host="projectplace.*.dimelo.com" />
src/chrome/content/rules/Right-Media.xml:	<!--target host="tm.*.dp.yieldmanager.net" /-->
src/chrome/content/rules/Truenudists.com.xml:	<target host="cdn.*.truenudists.com" />
src/chrome/content/rules/United-States-Department-of-Energy.xml:	<target host="www.*.doe.gov" />
src/chrome/content/rules/University-of-Alaska.xml:	<target host="www.*.alaska.edu" />
src/chrome/content/rules/University-of-Bern.xml:	<target host="www.*.unibe.ch" />
src/chrome/content/rules/University-of-Idaho.xml:	<target host="www.*.uidaho.edu" />
src/chrome/content/rules/University-of-Southampton.xml:	<target host="www.*.soton.ac.uk" />
src/chrome/content/rules/University_of_Houston.xml:	<target host="www.*.uh.edu" />
src/chrome/content/rules/University_of_Maine.xml:	<target host="www.*.umaine.edu" />
src/chrome/content/rules/US-Dept-of-Veterans-Affairs.xml:	<target host="www.*.vaforvets.va.gov" />
src/chrome/content/rules/US-Dept-of-Veterans-Affairs.xml:	<target host="www.*.vba.va.gov" />
src/chrome/content/rules/US-military.xml:	<target host="usarmy.*.llnwd.net" />
src/chrome/content/rules/Wikidot.xml:	<target host="1.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="2.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="3.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="4.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="5.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="6.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="7.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="8.*.wdfiles.com"/>
src/chrome/content/rules/Wikidot.xml:	<target host="9.*.wdfiles.com"/>
```

cc @fuglede @jsha @Hainish @Bisaloo - can we attempt to fix these and, this time, add a linter rule to prevent adding similar rules in future?

**Comment by koops76** [comment]
This will protect us from wildcard-in-the-middle attacks like #12312 and #12314. 😄

**Comment by Bisaloo** [comment]
- [x] Argonne-National-Laboratory.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] General-Electric.xml: https://github.com/EFForg/https-everywhere/pull/12317
- [ ] GPLHost.xml
- [ ] Monster.xml
- [x] OnSugar.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [ ] Projectplace.com.xml
- [x] Truenudists.com.xml: https://github.com/EFForg/https-everywhere/pull/12333
- [x] United-States-Department-of-Energy.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University-of-Alaska.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University-of-Bern.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University-of-Idaho.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University-of-Southampton.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University_of_Houston.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] University_of_Maine.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] US-Dept-of-Veterans-Affairs.xml: https://github.com/EFForg/https-everywhere/pull/12320
- [x] US-military.xml:	https://github.com/EFForg/https-everywhere/pull/12314
- [x] Wikidot.xml: https://github.com/EFForg/https-everywhere/pull/12320

**Comment by jeremyn** [comment]
@Bisaloo I've replaced PR #12314 with my new PR https://github.com/EFForg/https-everywhere/pull/14011. Please update https://github.com/EFForg/https-everywhere/issues/4369#issuecomment-326727385 above.

**Comment by pipboy96** [comment]
:tada:

**Comment by zoracon** [comment]
#12319
