### ISSUE TITLE
Add three Wikimedia sites

### ISSUE THREAD

**Issue by davidabian** [EFForg/https-everywhere#4373]
Please add the following Wikimedia websites that support HTTPS:
* wikimedia.or.id
* wikimedia.org.il
* wikimedia.es

wikimedia.es allows HTTPS for all subdomains. I don't know about the others.

**Comment by davidabian** [comment]
Also wikilov.es, which has no subdomains.

**Comment by J0WI** [comment]
fixed in #4467
