### ISSUE TITLE
Create port specific rules?

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#4389]
The domain `halley.ens.fr` has a rule in https everywhere and it works fine most of the time

https://halley.ens.fr/

However, some uses require to connect to port 4550 and then, https everywhere breaks it because ssl is not / badly (?) configured for this port.

https://halley.ens.fr:4550/

I could simply create a PR to disable this subdomain in the rule but my question is more general: 

**Is there a way to specify port specific rules? If no, maybe it should be implemented** (just a suggestion given I wouldn't be able to do it myself)

**Comment by J0WI** [comment]
Are you looking for something like this?
```
<target host="foo.example" />

<rule from="^http://foo\.example:2083/"
           to="https://foo\.example:2083/" />
```

**Comment by Bisaloo** [comment]
Well, that was kind of obvious in hindsight. Thank you!

I submitted a PR (#8969) to fix what lead me to ask this question in the first place.
