### ISSUE TITLE
Sign-in broken on delicious.com

### ISSUE THREAD

**Issue by DouglasRoyds** [EFForg/https-everywhere#4395]
delicious.com recently reverted to their previous Python-based web-site. It is now impossible to log-in from Firefox with https-everywhere enabled. See their blog posts for the background:
- http://blog.delicious.com/2016/01/delicious-changes/
- http://blog.delicious.com/2016/03/site-revisions/

Note also that they will be reverting at some point to their old del.icio.us domain.

Firefox 45.0 on Ubuntu 15.10

**Comment by pipboy96** [comment]
Website no longer exists. There are currently no active rules for del.icio.us.
