### ISSUE TITLE
Adobe rule breaks NCAA march madness live streaming

### ISSUE THREAD

**Issue by knekritz** [EFForg/https-everywhere#4398]
http://www.ncaa.com/march-madness-live gives a video playback error with the Adobe.com rule enabled, it works with it disabled.

The problematic redirect is one of these, likely the first:
http://entitlement.auth.adobe.com/entitlement/AccessEnabler.swf
http://sp.auth.adobe.com/crossdomain.xml

**Comment by numismatika** [comment]
The recorded videos seem fine with current master.
Livestream is blocked outside the us, so can't look at it.
