### ISSUE TITLE
The extension breaks the ability to play videos on startribune.com

### ISSUE THREAD

**Issue by darmbrust** [EFForg/https-everywhere#4399]
http://video.startribune.com/

Videos won't play - simply says "Could not load plugins: File not found" after clicking play.  Disabling the extension allows it to work again.

**Comment by numismatika** [comment]
#4218 might have fixed this already.
Startribune is using JWPlayer.

@darmbrust have you tried with the current master branch?

**Comment by funkydude** [comment]
@fuglede closed by https://github.com/EFForg/https-everywhere/pull/4218
