### ISSUE TITLE
Isnt working on RT and Bloomberg

### ISSUE THREAD

**Issue by DJHeady** [EFForg/https-everywhere#4406]
Go to facebook page of RT (https://www.facebook.com/RTnews/) and click a link. You will get 404. Same for Bloomberg, e.g. http://l.facebook.com/l.php?u=http%3A%2F%2Fwww.bloombergview.com%2Farticles%2F2015-10-12%2Frelax-we-ll-survive-china-s-sales-of-u-s-debt&h=XAQG3KWFY - also 404

**Comment by NewEraCracker** [comment]
the **on.rt.com** domain should not be HTTPS-forced.

**Comment by fuglede** [comment]
I can not reproduce this; for instance, the top link at the moment, on https://www.facebook.com/RTnews/posts/10154301172654411, redirects to https://www.rt.com/usa/341581-bin-laden-live-tweet/ as expected.

**Comment by J0WI** [comment]
https://github.com/EFForg/https-everywhere/pull/4678#issuecomment-234953490
