### ISSUE TITLE
Video streaming complaints

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#442]
A number of users are commenting in the Chrome Web Store that we break Amazon/Netflix streaming videos, and a few talking about Silverlight crashing (also issue #373).

Let's look into this before the next release.

**Comment by StevenRoddis** [comment]
Has this been fixed? Should we close this issue?

**Comment by semenko** [comment]
This was more of a metabug, to keep track of its children.

I guess it looks like most of the children are closed -- let's close this too.
