### ISSUE TITLE
vodlocker videos broken

### ISSUE THREAD

**Issue by sbs101** [EFForg/https-everywhere#4425]
Go to vodlocker.com, choose a video (e.g. http://vodlocker.com/2550p20z0ixt), find the button "Proceed to Video" below the advertising, press the button, page reloads, video should be displayed behind some advertising, but no video is displayed. Without https everywhere it is working. (version 5.1.4)

**Comment by numismatika** [comment]
@sbs101  displays just fine here. Could you try again with a recent version?

**Comment by sbs101** [comment]
Seems to work with 5.2.3
