### ISSUE TITLE
palemoon compatibility

### ISSUE THREAD

**Issue by a923315** [EFForg/https-everywhere#443]
HTTPS Everywhere for Android is not currently compatible with Palemoon Android.

Palemoon is an increasingly popular firefox alternative based on an older firefox version without all the recent "masses against the powerusers" decisions.

A thread on the palemoon forums has identified the incompatibility problem as a setting in the install.rdf file, down to the minVersion and MaxVersion settings.

Quoting JSB2000:
"changed the minVersion to 21.0, the MaxVersion to 23.* and reinserted it into the XPI."
and we have a working version.

Link to palemoon thread:
https://forum.palemoon.org/viewtopic.php?f=39&t=5382&sid=9442e6f5b8e9aa05b17c08e0e58865d4

Hopefully we can bump the maxVersion and solve the problem. Otherwise, please advise any compatibility issues so that the community may solve them.

**Comment by StevenRoddis** [comment]
The current xpi (4.0.3) has
`<em:minVersion>21.0</em:minVersion>`

Looks like it's all fixed.

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's still a bug.
