### ISSUE TITLE
redirect loop sometimes not detected

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#4432]
Ex: http://www.apple.com/apple-events/march-2016/ sends HTTPS-E into an infinite redirect loop in both Chrome and Firefox (and Brave). at least in Chrome, looks like the channel ID keeps increasing so HTTPS-E doesn't increment the redirect counter which is keyed by ID. i haven't looked into what Apple is doing to implement this annoying type of redirect.

**Comment by diracdeltas** [comment]
Just fixed this in Brave by adding some code to the redirect loop detection heuristic which checks if a URL returns 307 more than 5 times in 100ms. https://github.com/brave/browser-laptop/commit/9b945c5286e3d5672adfd62d6b5c09f03b305b2d#diff-a4a57e1c5be3df294e71a726d2e444cbR189

**Comment by J0WI** [comment]
```
<script type="text/javascript">
if (true && window.location.protocol == "https:") {
window.location.href = "http:" + window.location.href.substring(window.location.protocol.length);
}
</script>
```

no comment

**Comment by diracdeltas** [comment]
Ugh, I didn't realize the Apple event was today. We would have done some releases. :(
