### ISSUE TITLE
Videos not displaying on TMZ.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4439]
https://www.tmz.com/videos/0_15eiiiuo/

Disabling TMZ.com and swapping to http://www.tmz.com/videos/0_15eiiiuo/ fixes the problem.

**Comment by Bisaloo** [comment]
@MDawg957, this seems fixed. Can you double check and close that issue if everything works for you?

**Comment by J0WI** [comment]
Closing due the lack of response.
