### ISSUE TITLE
On subpages of the apple.com webpage enabling HTTPS Everywhere ends up in a redirect loop

### ISSUE THREAD

**Issue by niemalsnever** [EFForg/https-everywhere#4441]
Hi,
when trying to view the Keynote pages on the apple.com, seemingly those are not offered via HTTPS which results in a redirect loop where HTTPS Everywhere redirects every request to HTTPS, and Apple redirects every HTTPS request back to HTTP.

Observe: www.apple.com/apple-events/march-2016/

**Comment by fuglede** [comment]
Thanks for the report; this one is a duplicate of #4334.

**Comment by niemalsnever** [comment]
Oops, sorry, I forgot to check if this issue was already on here. I'll close this issue for it being a duplicate.
