### ISSUE TITLE
Comments not loading at Salon.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4452]
https://www.salon.com/2015/07/22/i_was_slimed_by_gawker_in_the_worst_year_of_my_life_i_became_a_regular_target_%E2%80%94_and_it_was_devastating/

Comments won't load unless the Salon.com rule is disabled.

**Comment by pipboy96** [comment]
Can't reproduce, comments don't load (or are empty) with HTTPS Everywhere either on or off.
