### ISSUE TITLE
Videos not playing at digitaltrends.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4453]
http://www.digitaltrends.com/videos/

You get an error message on video content unless you disable the JW Platform.com (partial) rule.

**Comment by jeremyn** [comment]
On Windows 10, Firefox 48.0.2, HTTPS Everywhere 5.2.3, I can play the video at the given URL without an error. Is this still a problem for you?

**Comment by MDawg957** [comment]
@jeremyn  Confirmed that this is now working in HTTPS 5.2.4.

**Comment by jeremyn** [comment]
Thanks.
