### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by funkydude** [EFForg/https-everywhere#4457]
We need a new release to resolve the growing amount of video playback problems that was fixed by https://github.com/EFForg/https-everywhere/pull/4218 but wasn't pulled for 5.1.4.

@jsha @Hainish @cooperq

**Comment by Hainish** [comment]
Incidentally I was planning on it today to test some modified release scripts.

**Comment by Hainish** [comment]
New release 5.1.5 is out.
