### ISSUE TITLE
Council of Europe homepage (coe.int) breaks with HTTPS everywhere enabled

### ISSUE THREAD

**Issue by lutoma** [EFForg/https-everywhere#4469]
HTTPS everywhere redirects all Council of Europe pages to their encrypted counterpart, but at least the main page doesn't work via https (anymore) as it requests all scripts and stylesheets via http.

**Comment by jeremyn** [comment]
Thanks for the report. WIth Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.4, if I go to https://www.coe.int/en/ , the only blocked content I see reported in the Firefox Web Console is

> Blocked loading mixed active content "http://play.webvideocore.net/js/dplayer.js"

which seems okay.

Is this still a problem for you?

**Comment by J0WI** [comment]
Closing due the lack of response.
