### ISSUE TITLE
Require minimum test URLs per target host

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#4477]
From https://github.com/hiviah/https-everywhere-checker/issues/12

For ruleset coverage testing, we currently check that each rule and exclusion has a number of covering test URLs. We should add logic that checks that each target host has at least one test URL, and left-wildcard target hosts have at least three, and right-wildcard target hosts have at least ten.

**Comment by J0WI** [comment]
@Hainish is there any roadmap for this?

**Comment by Hainish** [comment]
@J0WI this strikes me as a good volunteer task - I've added this as a label.

**Comment by Bisaloo** [comment]
Isn't this fixed by https://github.com/EFForg/https-everywhere/pull/11998?
