### ISSUE TITLE
Installing extension (FF & Chrome) on multiple user (Win) profiles

### ISSUE THREAD

**Issue by amiked** [EFForg/https-everywhere#4480]
Is it possible to install the extension in Chrome and/or Firefox for all user profiles on Windows machines that are joined to a domain?

It looks like [this might be an option for Chrome](https://dev.chromium.org/administrators/policy-list-3#ExtensionInstallForcelist), but thought I would check here first.

**Comment by jeremyn** [comment]
Thanks for your question, but this isn't really specific to HTTPS Everywhere, so I'm closing this issue. Maybe these links will help:

https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment#Packaging_Extensions
https://www.chromium.org/administrators/pre-installed-extensions
