### ISSUE TITLE
D&D Wiki support HTTPS

### ISSUE THREAD

**Issue by foobar13373** [EFForg/https-everywhere#4481]
https://www.dandwiki.com just works. It redirects to http://www.dandwiki.com/wiki/Main_Page however, but from there one https://www.dandwiki.com/wiki/Main_Page works.

**Comment by SgtLion** [comment]
As an admin on dandwiki, I gotta say: Thanks for doin' this. I love y'all.

**Comment by fuglede** [comment]
@SgtLion: You're welcome. Any chance you guys could simply redirect to HTTPS by default (preferably [preloading HSTS](https://hstspreload.appspot.com/)) -- then the ruleset wouldn't even have to be there.

**Comment by SgtLion** [comment]
We'd like to, and I did suggest it to our server guy, but since dandwiki uses CloudFlare SNI, we're not sure HTTPS is 100% supported, as per [our discussion on it](https://www.dandwiki.com/wiki/User_talk:Blue_Dragon#Also.2C_HTTPS)
