### ISSUE TITLE
Add clashdaily.com

### ISSUE THREAD

**Issue by IDKwhattoputhere** [EFForg/https-everywhere#4488]
I had an attempt at this but it breaks the front page of the site.

```
<ruleset name="ClashDaily">

	<target host="clashdaily.com" />
	<target host="www.clashdaily.com" />

	<rule from="^http:"
		to="https:" />

</ruleset>
```
Any help is appreciated.

**Comment by J0WI** [comment]
Locks good so far. Could you add a comment for the mismatching hosts?
cd.clashdaily.com
news.clashdaily.com
opinion.clashdaily.com

Please open a PR with your changes.
