### ISSUE TITLE
Mentor-Graphics.xml needs restructuring

### ISSUE THREAD

**Issue by davidabian** [EFForg/https-everywhere#4493]
I would add the following target tags to [Mentor-Graphics.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Mentor-Graphics.xml)...

```
    <target host="accounts.mentor.com" />
    <target host="analytics.mentor.com" />
    <target host="beta.mentor.com" />
    <target host="blogs.mentor.com" />
    <target host="connect.mentor.com" />
    <target host="crm.mentor.com" />
    <target host="help.mentor.com" />
    <target host="iweb.mentor.com" />
    <target host="learn.mentor.com" />
    <target host="login.mentor.com" />
    <target host="marketing.mentor.com" />
    <target host="salesconnect.mentor.com" />
    <target host="signin.mentor.com" />
    <target host="sourcery.mentor.com" />
    <target host="store.mentor.com" />
    <target host="store1.mentor.com" />
    <target host="supportnet.mentor.com" />
    <target host="video.mentor.com" />
    <target host="www.mentor.com" />
```

... if I could apply a simple...

```
<rule from="^http:"
        to="https:" />
```

... but that's not the case.

Would you simply replace the existing tags by the above? Should we get an intermediate solution? Should we add an enormous `rule` tag like this?

```
<rule from="^http://(accounts|analytics|...|video|www)\.mentor\.com/"
        to="https://$1.mentor.com/" />
```

**Comment by fuglede** [comment]
One thing you could do for this one would be to add the trivial <code>\<rule from="^http:" to="https:" /\></code> rule after the existing rules; rules are applied from the top to the bottom, so if you can just ensure that all the non-trivial cases have been checked first (which in particular means that the wildcard target needs to go), then you should be good.

**Comment by pipboy96** [comment]
Closed by https://github.com/EFForg/https-everywhere/pull/18068.
