### ISSUE TITLE
HTTPS Everywhere breaks winsupersite.com

### ISSUE THREAD

**Issue by Quenz** [EFForg/https-everywhere#4497]
It says in the FAQ https://www.eff.org/https-everywhere/faq#faq-What-if-HTTPS-Everywhere-breaks-some-site-that-I-use? to report this kind of thing here, so here you go. Pages on this site barely render with HTTPS.

**Comment by J0WI** [comment]
@Quenz please give us some more detail about what is broken.
Can you provide an URL?

**Comment by J0WI** [comment]
Closing due the lack of response.
