### ISSUE TITLE
Part of just-install.it blocked as a Cross-Origin Request when the RawGit.com rule is active

### ISSUE THREAD

**Issue by guiweber** [EFForg/https-everywhere#4507]
Part of just-install.it is blocked as a Cross-Origin Request when the RawGit.com rule is active.

The issue is triggered by a protocol-relative call made within Angular to load a json file. Firefox gives this security error in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://rawgit.com/lvillani/just-install/master/just-install.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

The browser doesn't display any warning to the user (such as a mixed content blocked warning), so the user doesn't know that something is missing from the page unless he checks the console.

Is this the expected behavior? 

(Tested on Windows, FF 45.0.1 and HTTPSE 5.1.5)

**Comment by galeksandrp** [comment]
http://rawgit.com/lvillani/just-install/master/just-install.json now have Access-Control-Allow-Origin: *, so this issue should gone.

**Comment by guiweber** [comment]
Yes, it looks like it's fixed.
