### ISSUE TITLE
dhgate.com - too many redirects

### ISSUE THREAD

**Issue by therealmarv** [EFForg/https-everywhere#4508]
To reproduce error:
1. Use Chrome and turn on https everywhere
2. Visit online shop http://www.dhgate.com/
3. Search for something there, e.g. "jackets"

Expected behaviour is that I see search results. Instead I'm getting a Chrome error `ERR_TOO_MANY_REDIRECTS`. Also many parts of the site regarding articles are broken with https everywhere.

**Comment by J0WI** [comment]
I don't get such errors, but there is a redirect loop, so the rule needs to be fixed.

**Comment by virtual812** [comment]
fwiw i have the same issue
