### ISSUE TITLE
m.imgur.com - /r/r/

### ISSUE THREAD

**Issue by Lvl4Sword** [EFForg/https-everywhere#4509]
when on mobile firefox, when going to a subreddit without a / at the end ( https://m.imgur.com/r/privacy for example ) any link you click on sends you to an image that has /r/r/ as opposed to just /r/ ( such as https://m.imgur.com/r/r/privacy/417Vp8S )

if the subreddit link has a / at the end ( https://m.imgur.com/r/privacy/ for example ), those image links have /r/privacy/r/privacy added to them ( such as https://m.imgur.com/r/privacy/r/privacy/417Vp8S )

turns out this isn't a https-everywhere issue. it's a website issue as it applies to http without https-everywhere enabled

**Comment by fuglede** [comment]
Closing as not an issue.
