### ISSUE TITLE
Amazon Web Services breaking video (and graphics) on multiple sites

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#4510]
http://losangeles.cbslocal.com/2016/03/27/ventura-police-search-for-suspect-in-connection-with-gun-store-break-in/

http://losangeles.cbslocal.com/2016/04/04/court-employers-must-allow-workers-to-sit-if-they-prefer-while-on-the-job/

Amazon Web Services needs to be turned off in order to fix the video.

**Comment by terrorist96** [comment]
It's also breaking the videos on fox
http://www.fox5dc.com/news/117109699-story

**Comment by terrorist96** [comment]
http://www.fox5ny.com/news/100475345-story

**Comment by terrorist96** [comment]
http://www.abc15.com/news/region-phoenix-metro/central-phoenix/phoenix-man-says-hes-being-watched-by-mysterious-box

**Comment by terrorist96** [comment]
http://thefreethoughtproject.com/red-light-robin-hood-hero-risks-years-jail-free-citizens-unlawful-red-light-cameras/

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10
I wish the policy would be to immediately deactivate rules that breaks websites, and only to reactivate them after the issue has been fixed, instead of leaving the rules active (i.e. sites broken) while waiting on a fix. :\

**Comment by J0WI** [comment]
@terrorist96 please post some deep links to broken videos. I couldn't find any video or AWS related content so far.

**Comment by terrorist96** [comment]
You don't see videos in any of the links? Do you have flash installed? Are you testing on Chrome or FF? I'm not sure how to post deep links. I'm trying to look in the source and inspect element, but I can't find it.

I found the one for thefreethoughtproject one:

**Comment by terrorist96** [comment]
Still broken in 2016.6.9.

**Comment by J0WI** [comment]
Please note that this issue is still open which means it hasn't been fixed yet.

**Comment by terrorist96** [comment]
In my opinion, the first step should be for the rule to be disabled if it's breaking content. Breaking the web should always be avoided. Second, when the rule gets fixed, then and only then should the rule be turned back on. This is going to remain broken for another month at least now since it missed the June 9 release.

**Comment by J0WI** [comment]
As you can [see](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/AmazonAWS.xml) this rule is quite complex and depends on a lot of other sites. So just disabling it would have the drawback that all other sites will no longer be secured. This would harm a lot all our Tor users.

**Comment by terrorist96** [comment]
http://sacramento.cbslocal.com/2016/07/06/california-gun-law-changes-have-advocates-up-in-arms/

**Comment by terrorist96** [comment]
http://www.wsbtv.com/news/local/north-fulton-county/1-dead-in-attempted-robbery-at-buckhead-jewelry-store/389269261

Amazon Web Services **and** Akamai break video.

**Comment by terrorist96** [comment]
http://www.theindychannel.com/news/local-news/man-arrested-charged-with-shooting-at-impd-officers-house-vehicle

**Comment by terrorist96** [comment]
http://www.ktnv.com/news/political/most-nevada-sheriffs-against-gun-background-check-initiative_18521357

**Comment by terrorist96** [comment]
AWS breaks the map here:
http://www.movoto.com/blog/novelty-real-estate/patriotic-states-map/

**Comment by Hainish** [comment]
I can confirm that the AWS ruleset causes problems in https://github.com/EFForg/https-everywhere/issues/4510#issuecomment-247797393

**Comment by terrorist96** [comment]
Thanks for confirming for movoto.com, but could you not reproduce the issue on all the other reported sites above, or did you not check? I can still reproduce it on cbslocal.com, thefreethoughtproject.com, and wsbtv.com.

Fox, ABC, theindychannel.com, and kntv.com links seem to work now, even with AWS active.

**Comment by Hainish** [comment]
I only tried the Movoto map.

**Comment by Bisaloo** [comment]
"Fun" fact: all those issues are related and caused by a single subdomain (excluded in #14656).

**Comment by terrorist96** [comment]
@Bisaloo I got the feb 26 release and this is still broken for me.
http://up.anv.bz/latest/anvload.html?key=eyJtIjoiY2JzIiwicCI6ImRlZmF1bHQiLCJ2IjoiMzM4NTA0MSIsInBsdWdpbnMiOnsiY29tc2NvcmUiOnsiY2xpZW50SWQiOiIzMDAwMDIzIiwiYzMiOiJuZXd5b3JrLmNic2xvY2FsLmNvbSJ9LCJkZnAiOnsiY2xpZW50U2lkZSI6eyJhZFRhZ1VybCI6Imh0dHA6Ly9wdWJhZHMuZy5kb3VibGVjbGljay5uZXQvZ2FtcGFkL2Fkcz9zej0yeDImaXU9LzQxMjgvQ0JTLk5ZJmNpdV9zenMmaW1wbD1zJmdkZnBfcmVxPTEmZW52PXZwJm91dHB1dD14bWxfdmFzdDImdW52aWV3ZWRfcG9zaXRpb25fc3RhcnQ9MSZ1cmw9W3JlZmVycmVyX3VybF0mZGVzY3JpcHRpb25fdXJsPVtkZXNjcmlwdGlvbl91cmxdJmNvcnJlbGF0b3I9W3RpbWVzdGFtcF0iLCJrZXlWYWx1ZXMiOnsiY2F0ZWdvcmllcyI6IltbQ0FURUdPUklFU11dIiwicHJvZ3JhbSI6IltbUFJPR1JBTV9OQU1FXV0iLCJzaXRlU2VjdGlvbiI6ImZlYXR1cmVkIn19fSwiaGVhcnRiZWF0QmV0YSI6eyJhY2NvdW50IjoiY2JzbG9jYWwtZ2xvYmFsLXVuaWZpZWQsY2JzbG9jYWwtc3RhdGlvbi1uZXd5b3JrLW5ld3lvcmstdW5pZmllZCxjYnNsb2NhbC1zdWJwcmltYXJ5LXN3dHYtdW5pZmllZCxjYnNsb2NhbC1tYXJrZXQtbmV3eW9yay11bmlmaWVkIiwicHVibGlzaGVySWQiOiI4MjNCQTAzMzU1Njc0OTdGN0YwMDAxMDFAQWRvYmVPcmciLCJqb2JJZCI6InNjX3ZhIiwibWFya2V0aW5nQ2xvdWRJZCI6IjgyM0JBMDMzNTU2NzQ5N0Y3RjAwMDEwMUBBZG9iZU9yZyIsInRyYWNraW5nU2VydmVyIjoiY2JzZGlnaXRhbG1lZGlhLmhiLm9tdHJkYy5uZXQiLCJjdXN0b21UcmFja2luZ1NlcnZlciI6ImNic2RpZ2l0YWxtZWRpYS5kMS5zYy5vbXRyZGMubmV0IiwidmVyc2lvbiI6IjEuNSJ9LCJyZWFsVGltZUFuYWx5dGljcyI6dHJ1ZX0sImFudmFjayI6ImFudmF0b19jYnNsb2NhbF9hcHBfd2ViX3Byb2RfNTQ3ZjNlNDkyNDFlZjBlNWQzMGM3OWIyZWZiY2E1ZDkyYzY5OGY2NyJ9

**Comment by Bisaloo** [comment]
I don't get it. I can reproduce with the stock `AmazonWebServices` ruleset but not with my custom ruleset even though the content is identical.

**Comment by Bisaloo** [comment]
@terrorist96, the new release improved the situation because instead of a blank screen, I now reach a screen saying:

> Please install the latest Adobe Flash Player Plugin to watch this content.

I can't go any further. If your issue is after that, you will need to provide the console output so I can understand what's going on

**Comment by terrorist96** [comment]
On Chrome, I click to allow flash to run. But neither the thumbnail of the video, nor the video itself will play unless I disable the AmazonWebServices ruleset.
```
Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
VM4295:13 GET http://dpm.demdex.net/id?d_visid_ver=1.5.3&d_rtbd=json&d_ver=2&d_orgid=823BA0335567497F7F000101%40AdobeOrg&d_nsid=0&d_mid=12812631535234849667852495825086851914&d_cb=s_c_il%5B0%5D._setAudienceManagerFields net::ERR_BLOCKED_BY_CLIENT
Visitor.a.oa @ VM4295:13
Visitor.a.r @ VM4295:20
Visitor.a.getAudienceManagerLocationHint @ VM4295:26
Visitor @ VM4295:37
Visitor.getInstance @ VM4295:38
s_Visitor_Flash_142259420_new @ VM4297:1
(anonymous) @ VM4297:1
cbsdigitalmedia.hb.omtrdc.net/crossdomain.xml:1 GET http://cbsdigitalmedia.hb.omtrdc.net/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
b.scorecardresearch.com/crossdomain.xml:1 GET http://b.scorecardresearch.com/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
VM4322:71 GET http://s0.2mdn.net/instream/video/client.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ VM4322:71
(anonymous) @ VM4322:71
(anonymous) @ VM4322:71
(anonymous) @ VM4322:72
rt.analytics.anvato.net/crossdomain.xml:1 GET http://rt.analytics.anvato.net/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
cbsdigitalmedia.hb.omtrdc.net/crossdomain.xml:1 GET http://cbsdigitalmedia.hb.omtrdc.net/crossdomain.xml net::ERR_BLOCKED_BY_CLIENT
```

**Comment by Bisaloo** [comment]
There is no indication of HTTPS Everywhere breaking anything in this log.

Can you check the network log to see if you get `404` links with the `AmazonWebServices` rule enabled? Or even better copy the whole network log and put it in a gist or on any pastebin service.

**Comment by terrorist96** [comment]
On a test profile with only HTTPS Everywhere active, after trying to play the video and it doesn't load:
![image](https://user-images.githubusercontent.com/12802056/36947747-11a08288-1f9e-11e8-83c2-e742de2abca3.png)

I can't see a clear way of copying the entire Network log.

**Comment by Bisaloo** [comment]
This is too complicated without being able to poke around by myself. I will try to find a computer with flash next week and see what I can do.

**Comment by terrorist96** [comment]
Chrome has flash built in that you can enable just for this one particular site. Or you're welcome to TeamViewer into my computer. Whatever is easier for you.

**Comment by Bisaloo** [comment]
I don't want to install chrome on my computer. It's fine, I should be able to find a computer with flash next week (we're not going to have a release in the meantime anyways). I'll let you know how that goes.

**Comment by terrorist96** [comment]
@Bisaloo *gentle nudge *

**Comment by Bisaloo** [comment]
My bad, I forgot about this. Thank you for reminding me. I will try to see what I can do tomorrow!

**Comment by Bisaloo** [comment]
... I forgot again. Feel free to ping me tomorrow between 10am and 5pm UTC. I may be able to find a computer with flash then.

**Comment by terrorist96** [comment]
@Bisaloo reminder

**Comment by Bisaloo** [comment]
Okay, I identified the issue. It was indeed a completely different problem. It was hidden mixed content blocking. I will submit a fix soon.
