### ISSUE TITLE
Wamba CDN.net bug

### ISSUE THREAD

**Issue by trup** [EFForg/https-everywhere#4511]
Switching pages (at the bottom of page) do not work.
example: [http://www.mamba.ru/ru/search.phtml?ia=M&lf=F&af=25&at=35&t=a&s_c=3159_4312_4400_0&form=1&offset=0](url)

**Comment by J0WI** [comment]
Works for me, @trup can you confirm?

**Comment by trup** [comment]
no, see screenshots.
v5.1.9
enable rule
![with](https://cloud.githubusercontent.com/assets/3046716/15179506/e1d5cf5e-1784-11e6-96d0-faf0663ee3bd.png)
disable rule
![without](https://cloud.githubusercontent.com/assets/3046716/15179507/e1f1ea7c-1784-11e6-8443-3f9af89f0bd4.png)

**Comment by trup** [comment]
photo*.wambacdn.net not support ssl. please add exclusion.
