### ISSUE TITLE
umblr.com rule causes security errors (because umblr.com serves a cert from a different domain)

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#4515]
STR:
 1. Visit http://t.umblr.com/ with HTTPS Everywhere installed.

ACTUAL RESULTS:
HTTPS Everywhere upgrades the connection to `https`, and I end up at an error page:
> Your connection is not secure
> The owner of t.umblr.com has configured their website improperly.
> [Advanced]
> t.umblr.com uses an invalid security certificate.
> The certificate is only valid for *.srvcs.tumblr.com

The `https` upgrade comes from an HTTPS Everywhere rule called "umblr.com".  Please disable that rule for the time being, since this site isn't correctly configured to support HTTPS.

**Comment by fuglede** [comment]
This should be a duplicate of #4491(which is already fixed).

**Comment by dholbert** [comment]
Yup, thanks!
