### ISSUE TITLE
On-demand content not working on WWE Network

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4517]
The live stream works, but unless the Google APIs rule is disabled, no on-demand content will properly play.

Examples:
http://network.wwe.com/video/v541320583
http://network.wwe.com/video/v554272283

HTTPSE 5.1.5, Firefox ESR 45.0.1, Windows 7

**Comment by J0WI** [comment]
Requires account to test.

**Comment by MDawg957** [comment]
This seems to be part of a trend with the Google APIs rule. #4897 has the same problem.

**Comment by MDawg957** [comment]
#4545 seems to have a multitude of these issues.  Is there possibly a larger problem with the Google APIs ruleset?

**Comment by gloomy-ghost** [comment]
massive close per #15157 assuming this is also caused by the Google API rule, feel free to reopen if it isn't
