### ISSUE TITLE
Video not playing at Variety.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4519]
http://variety.com/2016/film/news/nerdland-trailer-paul-rudd-patton-oswalt-1201742110/

Unless Google APIs and Fastly.net (partial) are disabled, I can't get the video to load properly.

HTTPSE 5.1.5, Firefox ESR 45.0.1, Windows 7

**Comment by J0WI** [comment]
Works for me, @MDawg957 can you confirm?

**Comment by J0WI** [comment]
The video works fine for me. Note that Mozilla blocks tracking resources in private mode.

**Comment by jeremyn** [comment]
The video plays for me on Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.4 with the `Google APIs`  ruleset enabled although it's very laggy.

@MDawg957 Are you getting any errors in the Firefox Web Console (`Ctrl-Shift-I > Console`)?

**Comment by MDawg957** [comment]
@jeremyn I tried it on another computer and noticed the same thing.  Putting it into a private window I had the spinning loader and noticed the following message in the console

`Unknown pseudo-class or pseudo-element '-webkit-media-text-track-container'.  Ruleset ignored due to bad selector.`

Refreshing again after about 5 minutes the video played properly.

**Comment by jeremyn** [comment]
That's pretty weird. I also have problems playing the video at first when I went into a private window with tracking protection enabled, but I didn't see the `Ruleset ignored` error. The video played after reload/refresh/something. 

Can you reliably recreate the `Ruleset ignored` error?

**Comment by MDawg957** [comment]
@jeremyn For a moment I thought that error was tied to Adblock Plus.  Disabling it and then opening the private window with the link that error does not come up, but scrolling farther up, I'm still seeing the message re-appearing in any new private windows opened even with ABP disabled.

Yes, I can consistently re-create that error message from what I'm seeing.

**Comment by jeremyn** [comment]
I think the `Ruleset ignored` message is unrelated to HTTPS Everywhere, for example see [this Google search](https://www.google.com/#q=%22Ruleset+ignored+due+to+bad+selector.%22). So let's ignore that.

If you [create a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) with no add-ons, including no HTTPS Everywhere, and load the variety.com URL in a private window, what happens with the video? I get the same behavior: it seems to hang the first time, and then plays when I refresh the page.

**Comment by MDawg957** [comment]
@jeremyn Tried out what you said and got the exact same results as you.

**Comment by jeremyn** [comment]
Thanks. So are you okay in calling this a problem between the site and Firefox, not with HTTPS Everywhere, and reclosing the issue?

**Comment by MDawg957** [comment]
Yeah, I think it's safe to close this at this point.  Thank you.

**Comment by jeremyn** [comment]
That's fine, thanks again.
