### ISSUE TITLE
Redirect loop for cvent.com

### ISSUE THREAD

**Issue by daniel-barrows** [EFForg/https-everywhere#4520]
HTTPS Everywhere seems to cause an infinite redirect loop on cvent.com.

Specifically, the [CSH Summit 2016](http://www.cvent.com/events/csh-summit-2016/event-summary-b05896613e504f549b12ef1d73909e59.aspx?ct=48832732-1e0d-43b1-8af7-01e4e9cd58aa) page, linked to from the [Path Program Calendar](http://pathprogram.samhsa.gov/Events/Calendar.aspx) (June) causes my browser to load perpetually, without showing a page. The title reads "HttpsGuard"; I'm not sure what that means.

As soon as I disable HTTPS Everywhere for cvent.com, the problem is resolved.

**Comment by J0WI** [comment]
JS redirect:
```
function Redirect() {
	var httpsLocation = 'http://' + document.location.host + document.location.pathname + document.location.search;
	document.location = httpsLocation;
}
Redirect();
```
