### ISSUE TITLE
Issues on Verizon.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4525]
http://www.verizon.com/home/fiosavailability/

If you try and check availability and try to click to continue, it will not work unless the Verizon (partial) rule is disabled.

HTTPSE 5.1.5, Firefox ESR 45.0.1, Windows 7

**Comment by J0WI** [comment]
Works for me, @MDawg957 can you confirm?

**Comment by jeremyn** [comment]
Closing issue because the reporter @MDawg957 says this is working for them now.
