### ISSUE TITLE
Virus or false positive ?

### ISSUE THREAD

**Issue by Petrouchka** [EFForg/https-everywhere#4541]
I've got this alert : https://www.virustotal.com/fr/file/82503023d085506bdf99e16a8f774c78d685572ae0020a12db97b87736f4fe9f/analysis/1459780462/
Perhaps the same problem than with DVDstyler ? Its author solved it with a new version of the packager : https://sourceforge.net/p/dvdstyler/bugs/617/

**Comment by J0WI** [comment]
This is a false positive.
Furthermore, I can't reproduce it with the current version: https://www.virustotal.com/en/url/2f1411cf687a167846407475c191e72bd63398ed08b61445c453e32178fd75ca/analysis/

Please make always sure, that you get the extension directly from eff.org or addons.mozilla.org.
