### ISSUE TITLE
Google APIs breaks video on multiple sites

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#4545]
http://www.cbsnews.com/videos/speaker-paul-ryan-still-withholding-endorsement-after-donald-trump-meeting/

Need to deactivate/modify `Google APIs` rule to fix video.

Seems to be a common issue:
https://github.com/EFForg/https-everywhere/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+google+apis

**Comment by terrorist96** [comment]
First video is broken due to Google API

**Comment by rm22** [comment]
Google APIs rule breaks video on** cbc.ca **

**Comment by terrorist96** [comment]
http://www.euronews.com/2016/05/01/dozens-killed-in-isil-suicide-blasts-in-southern-iraq/

Another example of Google API breaking a video. Would think that this would have been fixed by now, since it's so widespread.

**Comment by terrorist96** [comment]
Still broken in Version: 2016.5.10.
@fuglede

**Comment by J0WI** [comment]
I tried to reproduce these failures with the following results:
> http://www.cbsnews.com/videos/speaker-paul-ryan-still-withholding-endorsement-after-donald-trump-meeting/

I'm able to reproduce, but I didn't found the reason.
> http://www.wnd.com/2016/04/trump-erupts-as-cruz-sweeps-colorado-without-votes/

CORS issue depends only on JW (#4531), but not on Google APIs.
> http://www.euronews.com/2016/05/01/dozens-killed-in-isil-suicide-blasts-in-southern-iraq/

Works for me.

**Comment by terrorist96** [comment]
> http://www.cbsnews.com/videos/speaker-paul-ryan-still-withholding-endorsement-after-donald-trump-meeting/
I'm able to reproduce, but I didn't found the reason.

Disabling Google API fixes the video, so isn't that the reason?

> http://www.wnd.com/2016/04/trump-erupts-as-cruz-sweeps-colorado-without-votes/
CORS issue depends only on JW (#4531), but not on Google APIs.

Here's a strange issue: if you disable JW but leave Google APIs enabled, both videos will work. **However**, if you play the second video first, then try to play the first video, it will **not** work. If you disable both JW and Google API, and play the second video first, then try to play the first video, it **will** work.
So, something in Google API is causing the first video to not play if the second video is played first.

> http://www.euronews.com/2016/05/01/dozens-killed-in-isil-suicide-blasts-in-southern-iraq/
Works for me.

Strange. It works for me as well with all HTTPS Everywhere rules enabled. But if I enable Ghostery's Google+ Platform rule, the video won't work unless I disable Google APIs. So, Google APIs blocks the video when Ghostery's Google+ Platform rule is active, but doesn't block the video when Ghostery is inactive. So would this be a Ghostery issue or HTTPS Everywhere issue? Because the video work when only one or the other is active, but when both are active (specifically when HTTPSE's Google APIs rule and Ghostery's Google+ Platform rule), then the video won't work.

**Comment by rm22** [comment]
>  Google APIs rule breaks video on** cbc.ca **
Works for me

@J0WI, sorry i should have mentioned - the rule does not work in Firefox (32-bit), but it seems to work fine in Chrome. I haven't tested any other browsers.

**Comment by J0WI** [comment]
@rm22 I tested on Firefox. Please try to reproduce with a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and only HTTPS Everywhere installed. Make sure that everything is up to date.

**Comment by funkydude** [comment]
I stumbled across this issue today when trying to watch a (flash) video on cnet:
http://www.cnet.com/products/lg-tone-infinim-hbs-900/

The following resources fail to work on cnet when forced over https:
http://imasdk.googleapis.com/flash/sdkloader/adsapi_3.swf
https://imasdk.googleapis.com/flash/core/3.234.0/adsapi.swf

**Comment by terrorist96** [comment]
My CBS link is no longer valid. Here's a replacement: http://www.cbsnews.com/videos/

Google APIs breaks the videos.

**Comment by terrorist96** [comment]
Another example of Google APIs breaking a video on a site:
http://www.usatoday.com/story/opinion/2016/06/13/gun-laws-deter-terrorists-opposing-view/85844946/

**Comment by terrorist96** [comment]
http://www.realclearpolitics.com/video/2016/06/19/abcs_jonathan_karl_to_sen_chris_murphy_your_gun_control_proposals_would_not_have_stopped_orlando.html

JW Platform and Google APIs breaks video.
#5086

**Comment by terrorist96** [comment]
http://www.express.co.uk/news/politics/665033/EU-Referendum-2016-What-Brexit-Mean-for-Gibraltar-Rock-British-Territory-Spain

**Comment by terrorist96** [comment]
http://www.indystar.com/story/news/politics/2016/07/11/pence-rally-trump-amid-vp-speculation/86940242/

**Comment by terrorist96** [comment]
http://www.cbsnews.com/news/vice-president-joe-biden-restrict-sale-of-armor-piercing-bullets-dallas-shooting/

**Comment by terrorist96** [comment]
http://mashable.com/2012/09/13/six-degrees-kevin-bacon/#GRVzKpuroqqA

**Comment by terrorist96** [comment]
http://fox23maine.com/news/local/nra-takes-aim-at-question-3-in-maine

**Comment by terrorist96** [comment]
http://www.cbssports.com/olympics/news/2016-paralympics-in-worst-situation-ever-just-before-opening-ceremony/

**Comment by ipatjolvur** [comment]
http://www.cbsnews.com/live/video/edward-snowden-wants-a-presidential-pardon/

**Comment by ipatjolvur** [comment]
https://trac.torproject.org/projects/tor/ticket/18748

**Comment by terrorist96** [comment]
https://reason.com/blog/2016/09/19/watch-the-60-minutes-interview-with-gary

(have to load unsafe scripts)

Google APIs breaks the CBS video.

**Comment by terrorist96** [comment]
http://wgme.com/news/local/no-on-3-sign-vandalized-in-york-county

Google APIs breaks video.

**Comment by terrorist96** [comment]
http://www.courierpostonline.com/story/news/local/south-jersey/2016/09/23/nj-bill-ban-some-toy-guns-advances/90904514/

Google APIs AND Brightcove (partial) (#7140) breaks video.

**Comment by terrorist96** [comment]
http://www.app.com/story/news/local/redevelopment/2016/11/03/lacey-ammo-store-jersey-sportsman-guns/93241898/

Google APIs breaks video.

**Comment by terrorist96** [comment]
http://www.dailystar.co.uk/news/latest-news/563846/twitter-child-sex-porn-ring-pizzagate-gamer-leaks-thousands-of-social-media-accounts

Google APIs breaks video.

**Comment by gloomy-ghost** [comment]
massive close per #15157. I'm not able to reproduce most issues reported here since it has been a long time and many sites adopted https, but feel free to open new individual issue if you find one
