### ISSUE TITLE
Problem with HTTPS: Everywhere

### ISSUE THREAD

**Issue by doderberg** [EFForg/https-everywhere#4558]
Hi!
HTTPS Everywhere is redirecting our site, http://pjmedia.com/instapundit/ to https.  This interferes with the site's look and functionality.  Please remove all rules relating to PJMedia.com; the site knows best when to use http and when to use https.

**Comment by jeremyn** [comment]
@doderberg I'm closing this issue because the related pull request (#4573) has been merged, but please feel free to reopen the issue with a comment if necessary.
