### ISSUE TITLE
Issues on mobile.de

### ISSUE THREAD

**Issue by mwld** [EFForg/https-everywhere#4560]
German second-hand car website https://www.mobile.de does not work correctly in the HTTPS version. The following actions do not work:
- Adding cars to the watchlist (click "Parken" on a car's site)
- Saving searches (click "Suche speichern" on a search results page)

All of the above works with HTTPS disabled. So I guess that page and/or the mentioned actions should be removed from the ruleset.

I'm using Firefox 45.0.1 (on Windows 7 64-bit) with Add-on HTTPS-Everywhere in version 5.1.6.

**Comment by DavidLiedke** [comment]
@J0WI 

Test it with FF 59.0.1 and Chrome 65 with HTTPS Everywhere 2018.3.13 and no problems anymore.

**Comment by J0WI** [comment]
Thanks!
