### ISSUE TITLE
News Limited (partial) rule needs to be turned off for news.com.au

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#4561]
http://www.news.com.au/national/breaking-news/no-plans-to-change-gun-laws-keenan/news-story/914ebfe8e1e7caec2b7cef8ba9ef20b0

News Limited (partial) forces HTTPS, but Chrome will give the following warning:
`Your connection is not private
Attackers might be trying to steal your information from www.news.com.au (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID`

Ignoring the warning and proceeding to the site works, but then you also have to load unsafe scripts. Then everything looks fine except for the red crossed out https in the URL bar.

**Comment by fuglede** [comment]
Looks like that one was introduced by accident in 2647856610903cb3854c07ef972e85e6cd01dbdb.

**Comment by terrorist96** [comment]
This is still broken in Version: 2016.5.10. It'll still redirect to https and Chrome will flash the warning.
@fuglede @J0WI

**Comment by fuglede** [comment]
The fix was merged on 12/5 (CEST); do you experience the error on the current master branch?

**Comment by terrorist96** [comment]
I'm using whatever is the latest version in the Chrome web store. Since it was updated about 3 days ago, I presumed this fix was merged into that release, but looks like it was fixed one day after the release? So we'll be waiting another month or so to see this fix, it seems.

Side issue: is there anyway to have ruleset updates be independent of updates to the extension? Similar to how AdBlock Plus has filter lists that you can force to update to the latest revision, independent of the extension's version number.

**Comment by fuglede** [comment]
Currently, the only way would be to build the ruleset database.

**Comment by terrorist96** [comment]
I mean for like a layperson. Introducing a button within the extension or an autoupdate feature where it'll update the ruleset automatically every few days or so.

**Comment by fuglede** [comment]
You could always propose it as a separate issue. Personally, my opinion probably is that a certain amount of delay is acceptable for a non-popular site, whereas an extremely important ruleset should drive forward the date of a new release.

**Comment by terrorist96** [comment]
> whereas an extremely important ruleset should drive forward the date of a new release.

In my opinion, the following two ruleset issues should have been given higher priority:
https://github.com/EFForg/https-everywhere/issues/4510
https://github.com/EFForg/https-everywhere/issues/4545

They're breaking a lot of things across a lot of different websites, and the issues were overlooked when it came time to push the 2016.5.10 update.
