### ISSUE TITLE
Add dummy release process to test.sh

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#457]
To avoid the issue that we're currently having with signature verification on update.rdf in the 4.0.0 release, it would be nice to do the release signing process with a dummy key in test.sh. This would involve making the release signing scripts public, which we haven't done in the past for opsec reasons (as I understand it). 

Relatedly, we should come up with a way to sync changes to the release scripts to the airgap machine.

**Comment by zoracon** [comment]
Closing due to new changes since this conversation took place, but will still be linked to referenced newer issues
