### ISSUE TITLE
Update "HTTPS Everywhere development" page

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#4588]
https://www.eff.org/pages/https-everywhere-development looks a bit dated, information-wise; for instance, it does not mention the GitHub repo at all.

**Comment by salty-horse** [comment]
I found the following bits of information outdated or missing (note that I didn't follow the whole guide):

* `./makexpi.sh` creates two extensions, one with an `-amo.xpi` suffix, another with `-eff.xpi` - which to use?
* `./makexpi.sh` creates unsigned extensions. To install them in Firefox, I had to disable `xpinstall.signatures.required`.
* The guide references a `pending-rules` directory. It's missing, and I believe that's not the current workflow.

**Comment by J0WI** [comment]
cc @Hainish
