### ISSUE TITLE
Common ruleset bugs we've seen & suggested tests

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#460]
(Expanding on issue #451)

Some examples of common ruleset errors we might be able to test for.

    <target host="www.df.eu" /> <------ Missing non-www target host to match rule.
    <rule from="^http://(www\.)?df\.eu/" to="https://www.df.eu/"/>

**Comment by jsha** [comment]
Update: Per #984, we now have ruleset coverage testing that should catch a lot of these "rule doesn't match target host" problems.
