### ISSUE TITLE
http://tesco.com/groceries/

### ISSUE THREAD

**Issue by DanAtkinson** [EFForg/https-everywhere#4615]
The Tesco Groceries site renders incorrectly in HTTP when the extension is enabled.

Disabling the extension allows the website to show correctly.

**Comment by MDawg957** [comment]
Disabling the Tesco (partial) rule specifically should let it work till a proper fix can be implemented. The page loads correctly for me after I do that.

**Comment by DanAtkinson** [comment]
I have also reached out to Tesco separately, asking them to look at this problem.

There's no logical reason why one of the largest supermarket chains in the world has an invalid SSL certificate on its homepage when loaded over HTTPS (https://www.tesco.com/).

**Comment by J0WI** [comment]
The sites CSP blocks content from secure.tesco.com

**Comment by dandart** [comment]
I tried this partial one earlier on this week and got yet more issues from their site. I had to remove the whole site from consideration.

**Comment by janipewter** [comment]
Amazingly, Tesco still haven't fixed their website yet. After a long chat with their technical support today, their best advice was to disable the extension.

I'm fine though thanks. This is the only website I've ever tried to use which breaks itself when HTTPS Everywhere is enabled, and I would rather not lower my own privacy settings because their developers have misconfigured their site.

**Comment by DanAtkinson** [comment]
It is rather ridiculous that they can't support https everywhere across their servers and have instead created this situation for themselves where it's a mishmash of secure/insecure pages. It's not even consistent. I can be on http pages and have personal data exposed for no good reason.

**Comment by J0WI** [comment]
There is a [proposal](https://github.com/w3c/webappsec-csp/issues/25) for the CSP spec, that hard coded `http://` policies should be ignored by browsers, but it has not been implemented yet.

**Comment by gerv** [comment]
This bug has been open six months; why not just remove the rule for Tesco from the HTTPSE ruleset, if it breaks things?

**Comment by rjgould** [comment]
Have to agree with @gerv I couldn't figure out why Firefox wasn't showing the site properly so just had to play the "check every AddOn" game to find out it was HTTPS Everywhere.  I'd rather this was excluded so I can go back to using the addon continuously instead of having to switch it on and off.

**Comment by J0WI** [comment]
This ruleset depends on a lot of other ones, but since there are so many issues with that site I'm fine with just disabling it.

**Comment by galeksandrp** [comment]
Did this issue persist?

**Comment by J0WI** [comment]
`https://secure.tesco.com/groceries/` looks broken, but `https://www.tesco.com/groceries/` WFM

**Comment by janipewter** [comment]
It does look like they have FINALLY fixed it

**Comment by Bisaloo** [comment]
Can we close this issue if this is fixed?

**Comment by DanAtkinson** [comment]
They appear to have fixed their hodge-podge SSL problems, so I believe that this issue can be closed.
