### ISSUE TITLE
Can't listen to music on http://player.edge.ca/ with HTTPS Everywhere activated

### ISSUE THREAD

**Issue by 0sinner** [EFForg/https-everywhere#4649]
This seems to block the player, despite the fact that the resources that fail to load appear to have https equivalents..

**Comment by J0WI** [comment]
Works for me, @0sinner can you confirm?

**Comment by fuglede** [comment]
Works for me as well. It might very well have been fixed by the recent jwplayer fix; closing as such (but do ping for a re-open if it still fails on the current master).
