### ISSUE TITLE
gfblip.appspot.com kills browser (freeze)

### ISSUE THREAD

**Issue by sourcejedi** [EFForg/https-everywhere#4656]
Visiting gfblip.appspot.com with "HTTPS Everywhere" enabled causes my browser to freeze, at least for long enough to trigger ~"this app is unresponsive, kill it?"

Odd that this wasn't seen in report #4174

Firefox 45.0.2, running under Fedora Linux.
Other enabled content extensions: NoScript, Disconnect (tracker blocker).

**Comment by Bisaloo** [comment]
@sourcejedi, this seems fixed. Do you still have issues with this website? If not, can you close this issue please?

**Comment by sourcejedi** [comment]
It doesn't seem to happen now.  I still have HTTPS Everywhere enabled.  Thanks.

I might not use this website _deliberately_ in the same browser, because I like to use a script blocked and the website makes script requests to a lot of different addresses.  But if I stumble upon a browser _hang or crash_ again, I will be aiming to [re-]report that.
