### ISSUE TITLE
Please remove Ask.fm from HTTPs redirects

### ISSUE THREAD

**Issue by krootee** [EFForg/https-everywhere#4660]
Good day,

You added Ask.fm domain to HTTPs rules, but affecting some of our users during experiments on our side where we deploy data over HTTP - those users end up in infinite loop.
Please remove us from the list.

Thank you!

**Comment by reedy** [comment]
Is there just some domains that we can blacklist/not HTTPS?

**Comment by krootee** [comment]
Nope - all top domains could serve content via HTTP including ask.fm / www.ask.fm / m.ask.fm.

**Comment by krootee** [comment]
FYI - m.ask.fm / ask.fm / www.ask.fm is not using HTTPS anymore, so users of your plugin would be unable to properly work with the site using default rules.

**Comment by J0WI** [comment]
@krootee are you an employer of ask.fm? Can you confirm that somehow?
Please note that http is insecure and deprecated, so removing https on your side is always a really bad idea.

**Comment by krootee** [comment]
You could send email to konstantin.root at ask.fm to verify - could also lookup me on LinkedIn.
There is a strong case to do this move on our side.

**Comment by J0WI** [comment]
Ownership confirmed, I'll open a PR.
