### ISSUE TITLE
Freezing after trying to open new Windows on Firefox

### ISSUE THREAD

**Issue by pedrokleiz** [EFForg/https-everywhere#4661]
Hi, I'm using HTTPS-Everywhere on Firefox 46 on OS X 10.11.5 and every time I try to open a New Windows it just freezes and I can't do anything with the browser. I can create a more elaborated log if necessary but I didn't find any way to do so.

**Comment by scarf** [comment]
I'm using Firefox 47 on Ubuntu 14.04 and Firefox will freeze when a site tries to open a (legitimate) popup window.  Sometimes one popup window will open fine, but if i close that and try to open another popup window, Firefox will freeze.

It seems to be a conflict between HTTPS-E and Beef Taco (http://jmhobbs.github.io/beef-taco/).
HTTPS-E + Beef Taco = freeze

Disabling either of these add-ons stops the freezing.  The particular site I am testing with is just a local, intranet site and HTTPS-E doesn't have any rules for the site.  But the freeze happens at internet sites too when trying to open (legitimate) popup windows.

**Comment by pipboy96** [comment]
Closed since extension was rewritten into WebExtension.
