### ISSUE TITLE
Observatory-popup  Popup warning everytime i start Firefox

### ISSUE THREAD

**Issue by aquatic7** [EFForg/https-everywhere#4664]
Hello,

Everytime I start Firefox i get this popup window.
How can I fix this?

![markering_007](https://cloud.githubusercontent.com/assets/18247537/14680910/5318d57e-071f-11e6-99a6-1e1116461f98.png)

Also when I go to settings I get this popup.
![markering_008](https://cloud.githubusercontent.com/assets/18247537/14680977/8f6a2a14-071f-11e6-8c9f-3884977fd1f7.png)

I can't get into the settings.
How can I fix this?

It also dont show in the toolbar.
![markering_009](https://cloud.githubusercontent.com/assets/18247537/14681139/2f2ab6ea-0720-11e6-8da0-ed0dfba2361d.png)

Linux Mint 17.3, preinstalled Firefox.

Thank you.

**Comment by J0WI** [comment]
Can you reproduce with the current version on a clean Firefox profile?
(start Firefox in terminal mit `-p` to create a new profile)

**Comment by lsdamsgaard** [comment]
Yes, I can reproduce it with the current version on a clean Firefox profile. :(

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
