### ISSUE TITLE
dylmye.me breaks - due to SRI integrity hash or Cloudflare?

### ISSUE THREAD

**Issue by dylmye** [EFForg/https-everywhere#4668]
Hi. On the website dylmye.me, I include stylesheets like so:

``` html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
```

With HTTPS Everywhere disabled the resources included like this load fine, however with the extension enabled I get these errors in console:

```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource at http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.2/css/bootstrap.min.css. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

I know for certain that `Access-Control-Allow-Origin: *` is included with cdnjs resources and my wesbite. Is this an error with your cloudflare rules?

Thanks!

_Tested on Firefox latest version, Windows 10 w/h latest updates, latest version of HTTPS Everywhere_

**Comment by J0WI** [comment]
This behavior looks very intressting. The rule looks fine and the files are equal on http and https.
Looks like an issue in the core of HTTPS Everywhere.
cc @Hainish @jsha

**Comment by dylmye** [comment]
Possibly an error to do with GitHub Pages server handling?

**Comment by jsha** [comment]
There's a longstanding issue with Access-Control-Allow-Origin: #49

**Comment by gloomy-ghost** [comment]
dylmye.me moved to https and there shouldn't be anymore CORS issue
