### ISSUE TITLE
Firefox's Inspector doesn't work on a specific website that uses CloudFlare's CDN

### ISSUE THREAD

**Issue by pilosus** [EFForg/https-everywhere#4674]
Firefox doesn't display CSS Rules pane in its Inspector just for one specific website. Website itself seems to be completely fine, CSS are loaded, I can see them in Chrome's Inspector with no problem.

Once Firefox is loaded with add-ons disabled, the problem is gone. Disabling add-ons one by one, I figured out that the problem is related to HTTPS Everywhere (when its disabled, everything is back to normal). I can get Inspector working even with HTTPS Everywhere enabled, once I disable rules for CloudFlare.com (the website in question uses it's CDN for jquery and bootstrap stuff).

So something's wrong with the rules for CloudFlare.com, I guess.

My system:
OS X El Capitan 10.11.4
Mozilla Firefox 45.0.2
HTTPS Everywhere 5.1.16

Looks like a similar problem:
https://support.mozilla.org/en-US/questions/1110326

**Comment by JbIPS** [comment]
I've got the same error with BootstrapCDN.com. Deactivating the rule solve everything.

**Comment by pipboy96** [comment]
The original issue applies to a pre-WebExtensions Firefox version.

**Comment by pipboy96** [comment]
The issue pointed out by @dstensnes also can't be reproduced.
