### ISSUE TITLE
TMZ is broken due to mixed content

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#4704]
https://www.tmz.com/ doesn't load

**Comment by fuglede** [comment]
Is it just me or is this really inconsistent? Half the time it loads just fine for me.

**Comment by diracdeltas** [comment]
it loads fine on mobile because m.tmz.com is not included. maybe that's what you're running into?

**Comment by fuglede** [comment]
Nope, it was actually the www subdomain being inconsistent. The following is taken with the ruleset active, where it appears to render fine:

![skaermbillede fra 2016-05-10 20 05 39](https://cloud.githubusercontent.com/assets/6169306/15157164/a935d4d6-16ea-11e6-94a4-b7d6374ece8e.png)

Yet I did also hit the mixed content issues when I checked last time..

**Comment by gloomy-ghost** [comment]
Seems like the site doesn't have mixedcontent anymore, closing for now.
