### ISSUE TITLE
Cosmetic Issue: Chrome DevTools Dark Theme

### ISSUE THREAD

**Issue by Injust** [EFForg/https-everywhere#4707]
When the dark theme is enabled in Chrome's DevTools panel, the text is illegible on the HTTPS Everywhere extension panel.

![image](https://cloud.githubusercontent.com/assets/3387175/14970370/5d91cce2-1096-11e6-8d7c-d80a57b336d8.png)

**Comment by gloomy-ghost** [comment]
Workaround: https://github.com/EFForg/https-everywhere/commit/b7e8be7afe8ace37f5d02cfaa3c7f604d753890c
