### ISSUE TITLE
DRY up build process

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#471]
Right now makecrx has a lot in common with makexpi, in particular validation. Validation should be extracted into a separate script.

Probably it's worthwhile to move to make for building, since we now have distinct stages that can sometimes be skipped if things are already up-to-date. E.g. make sqlite, validate, make package, test.

**Comment by jeremyn** [comment]
I'm closing this issue now that we have just [`make.sh`](https://github.com/EFForg/https-everywhere/blob/256f89e7478436d6f057a9e857b67047cb75aa48/make.sh).
