### ISSUE TITLE
Ruleset release 5.1.9

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#4710]
cc @jsha @cooperq @pde @J0WI @fuglede @semenko @loveithateit

I'll be releasing a ruleset release (5.1.7) hopefully today.  I plan on cutting the release after reviewing and merging https://github.com/EFForg/https-everywhere/pull/4505

I'm going to start opening issues before a release is scheduled to let ruleset maintainers know when a release is forthcoming.  I'll mention the main ruleset maintainers so they are notified.  This will let the maintainers close loop on any PRs they are reviewing.  This is a courtesy issue, and may or may not be followed upon every release, depending on circumstance.

I've also created a new label, `release-forthcoming`, to group these type of issues.

**Comment by Hainish** [comment]
Looks like this release may be pushed to tomorrow, as #4505 requires some auditing.

**Comment by diracdeltas** [comment]
i'd like to be CC'ed too, as the https e maintainer for Brave. :)

**Comment by Hainish** [comment]
Sounds good, I'll include you as well

**Comment by Hainish** [comment]
Looks like the release will have to be pushed to tomorrow, due to complications arising from https://github.com/EFForg/https-everywhere/pull/4505#issuecomment-217261080

**Comment by Hainish** [comment]
With https://github.com/EFForg/https-everywhere/pull/4505 merged, I'll be ready to make a release tomorrow for sure.

**Comment by Hainish** [comment]
Considering it now, it's better to make this release on Monday rather than late on a Friday afternoon.

**Comment by J0WI** [comment]
Thanks for the announce.
#4673, #4282 and #4433 seems trivial.
#4471, #4178, #4370 and #4371 would be important to be released.

**Comment by Hainish** [comment]
Merged the trivial PRs.  If we want to release today, we'll have to delay the non-trivial PRs to next release.

**Comment by Hainish** [comment]
A few problems came up while doing the release, pushing to tomorrow morning.

**Comment by J0WI** [comment]
Can we have milestones for such cases?
#4101 is also waiting for review btw.

**Comment by Hainish** [comment]
Milestones make sense to me, as long as we don't keep piling ruleset changes onto a single milestone.

**Comment by J0WI** [comment]
Since the rules are not separated from the core it's hard to merge just rule bugfixes instead of rebased rules.
Buggy rules could block a release, new or rebased ones shouldn't.

**Comment by Hainish** [comment]
Because of the aforementioned release issues, we've version-jumped to `5.1.9` for Firefox.

**Comment by J0WI** [comment]
See https://github.com/EFForg/https-everywhere/milestones/Before%20the%20Next%20Release
