### ISSUE TITLE
Redbubble

### ISSUE THREAD

**Issue by jcosentino** [EFForg/https-everywhere#4714]
RedBubble (partial) stops content from displaying in Firefox
Https Everywhere 5.1.6
Example:
http://www.redbubble.com/people/kebuenowilly/works/21726392-dis-boi-unicycle-frog-meme?p=laptop-sleeve
The laptop bag being presented doesn't show with this filter enabled.

**Comment by gloomy-ghost** [comment]
massive close per #15157
