### ISSUE TITLE
Add britishairways.com

### ISSUE THREAD

**Issue by jbrowngithubuser** [EFForg/https-everywhere#4718]
The homepage for British Airways defaults to HTTP so leaks username/password (users can login on the top right), even though it supports HTTPS. Please add britishairways.com and www.britishairways.com

https://www.ssllabs.com/ssltest/analyze.html?d=britishairways.com
https://www.ssllabs.com/ssltest/analyze.html?d=www.britishairways.com

**Comment by J0WI** [comment]
The current rule needs to be updated: https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/BA.xml

We have a nice guide about how to do that here: https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md

**Comment by illicitonion** [comment]
This got merged already :)
