### ISSUE TITLE
Untrusted extension

### ISSUE THREAD

**Issue by caffeine74** [EFForg/https-everywhere#4721]
I had to override the signing requirement to install in Firefox 46 on Linux Mint 17.3 (Rosa).

According to [this page](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct)  the next major release we wont be able to use HTTPS Everywhere unless it [gets signed by Mozilla](https://developer.mozilla.org/en-US/Add-ons/Distribution).

I didn't see this issue raised anywhere else but if I missed it and this is a dupe I apologize.

--
Ben.

**Comment by J0WI** [comment]
We already have a signed version on addons.mozilla.org.
Are you sure that you are using the latest version of HTTPS Everywere?

Let me ping @Hainish to solve migration issues if there are any.

**Comment by Hainish** [comment]
@caffeine74 where did you install the extension from?

On May 10, 2016 10:00:23 AM PDT, J0WI <notifications@github.com> wrote:
>We already have a signed version on addons.mozilla.org.
>Are you sure that you are using the latest version of HTTPS Everywere?
>
>Let me ping @Hainish to solve migration issues if there are any.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/issues/4721#issuecomment-218222613

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Hainish** [comment]
@caffeine74 you should no longer see this problem.  This was due to a faulty release being cached on our servers.
