### ISSUE TITLE
Cloudera documentation website not well displayed

### ISSUE THREAD

**Issue by jbarotin** [EFForg/https-everywhere#4722]
The HTML of the Cloudera documentation is mixing http and https url, so the design of this website is broken while navigating with httpseverywhere extension. You can find a sample here : 
https://www.cloudera.com/documentation/enterprise/5-6-x/

**Comment by jeremyn** [comment]
There's currently no blocked mixed content at that URL and the site looks okay enough to me. Is this still a problem for you?

**Comment by jbarotin** [comment]
Yep, it works. I close this issue

**Comment by jeremyn** [comment]
Thanks.
