### ISSUE TITLE
https://www.openbsd.org Please add default rule to enable TLS on OpenBSD domain

### ISSUE THREAD

**Issue by fdback** [EFForg/https-everywhere#4727]
Could we please add a default rule to HTTPS Everywhere to redirect openbsd.org and www.openbsd.org to https://www.openbsd.org

Thanks

(you can check it here https://www.openbsd.org/ it's up and running)

**Comment by fdback** [comment]
Sorry I havent checked specifically which subdomains have TLS enabled but I believe it is the vast majority of them

**Comment by fdback** [comment]
For the time being, the rule should redirect openbsd.org and www.openbsd.org to https://www.openbsd.org

**Comment by mnordhoff** [comment]
Pull #4726 fixes this.
