### ISSUE TITLE
label for mixed content bugs

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#4729]
Some `ruleset-bugs` refer to a specific page that contains mixed content. They are trivial than other bugs (like http redirects or CORS). Can we have a separate label for them?

We should split the `ruleset-bug` generally a bit up, I think this would make it easier to filter and fix them.

ping @Hainish @jsha @reedy

**Comment by Hainish** [comment]
Done: https://github.com/EFForg/https-everywhere/labels/mixed-content-bug
