### ISSUE TITLE
firefox problems, ancestry website and missing toolbar/icon

### ISSUE THREAD

**Issue by shdsolent** [EFForg/https-everywhere#4742]
please help - no idea what I am doing, just need help - https everywhere breaks parts of the Ancestry website but I dont know how to 'turn off' https for a site, faq says something about an icon in a toolbar but I cant find this icon or toolbar anywhere in firefox, I have menu bar and bookmarks toolbar ticked.

**Comment by fuglede** [comment]
Which version of Firefox are you using? The toolbar button should look like the one on the right [on this picture](https://cloud.githubusercontent.com/assets/627911/9125761/c445bc04-3c58-11e5-8948-47dffc8ad6dc.png).

**Comment by shdsolent** [comment]
Hi, many thanks for looking, I have no idea where it went but apparently it is back just now!  I have firefox 46.0.1 with win7pro, I did do a pc restart so maybe something was blocking it.  I reported to ancestry that https doesn't work with parts of their website - it is odd, it looks like the problems you get with eg java - buttons that dont work, image based buttons/forms that dont show at all, that sort of thing.

**Comment by fuglede** [comment]
Assuming you mean ancestry.com, it does appear to run fine from a quick test here. Do you have any URLs causing problematic behaviour in particular?

**Comment by shdsolent** [comment]
Hi, it is actually the uk site but I would have thought it would affect equally - but maybe the uk one has specific rules.  For example the support home - https://ancestryuk.custhelp.com/  when https everywhere is installed the buttons dont work.  On my own pages, for example the all hints, page is almost blank - http://hints.ancestry.co.uk/tree/32844435/hints?hf=allhints&src=hn

**Comment by fuglede** [comment]
Thanks for elaborating. That first page looks pretty broken indeed.

Since the second one requires a login, it is a bit annoying to troubleshoot. Can I convince you to fire up the Firefox browser console (keyboard shortcut F12) and reload the problematic page, taking note of any warnings that it may trigger?

**Comment by shdsolent** [comment]
Hi this is the copy/paste of the console tab - Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://c.mfcreative.com/allhints/1.0.119/resources/bundleResources.en-GB.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://c.mfcreative.com/allhints/1.0.119/templates/app.html. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://c.mfcreative.com/allhints/1.0.119/templates/list.html. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
"Error: [$compile:tpload] http://errors.angularjs.org/1.3.15/$compile/tpload?p0=http%3A%2F%2Fc.mfcreative.com%2Fallhints%2F1.0.119%2Ftemplates%2Flist.html
R/<@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:412
d/<@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:66498
f/<@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:53903
Pe/this.$get</n.prototype.$eval@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:60880
Pe/this.$get</n.prototype.$digest@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:59448
Pe/this.$get</n.prototype.$apply@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:61160
l@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:38351
M@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:40501
wf/</e@http://c.mfcreative.com/lib/tgn/combo.ashx?x/lib/jquery/jquery-1.7.1.min.js&x/Lib/AngularJS/angular-1.3.15.min.js&x/Lib/AngularJS/angular-1.3.15-route.min.js&x/Lib/AngularJS/angular-1.3.15-resource.min.js&x/Lib/AngularJS/angular-1.3.15-sanitize.min.js:3:41093
" undefined combo.ashx:3:49167

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://c.mfcreative.com/allhints/1.0.119/resources/bundleResources.en-US.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing). <unknown>
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. combo.ashx:2:38763

**Comment by fuglede** [comment]
Excellent, thanks for getting those! Based on that, I added what is hopefully a solution in #4747. If you're up to it, you could try building that to see if it helps. Otherwise I suppose that we will know by the next release.

**Comment by shdsolent** [comment]
Hi, many thanks (you work hard and very fast!) I have no idea how to 'build' as I am only a user - unless it is simple to do then I will also wait! ;)
