### ISSUE TITLE
Videos on golem.de don't work

### ISSUE THREAD

**Issue by gossi** [EFForg/https-everywhere#4770]
Hey guys,

just made a fresh firefox installation and added 4 addons:
- AdblockPlus
- Ghostery
- PrivacyBadger
- HTTPS everywhere

No further settings. Videos on golem.de don't work with default https-everywhere settings, see here: http://www.golem.de/news/traceroute-wann-ist-ein-nerd-ein-nerd-1605-120903.html

Hope you can fix that.

**Comment by J0WI** [comment]
I can't reproduce this whits only HTTPS Everywhere installed.
Please check if the issue depends on a third party extension.

**Comment by CheapApples12** [comment]
It's got to be a third-party extension causing the issues. I can't reproduce any errors and the only extensions I have are HTTPS Everywhere, Authy and Gyazo

**Comment by gossi** [comment]
I have the following addons installed:

- Adblock Plus
- Ghostery
- HTTPS Everywhere
- Privacy Badger

I deactivated all but https everywhere. Restart firefox, a lot of ads but no video. What I did to fix it for me is locate my profile folder (`~/Library/Application Support/Firefox/Profiles/<myid>.default/HTTPSEverywhereUserRules` on OSX) and created the `Golem.de.xml` file in there with the following contents:

```xml
<ruleset name="Golem.de">

		<!--	Direct rewrites:
					-->
	<target host="cpxl.golem.de" />
	<target host="cpx.golem.de" />
	<target host="account.golem.de" />
	<target host="suche.golem.de"/>
	<!--<target host="video.golem.de" />-->
	<!-- whitepaperdb.golem.de expired-->
	<!-- TLS not supported on golem.de and ads.golem.de -->

	<rule from="^http:" to="https:"/>

</ruleset>
```

Which got me video.

**Comment by fuglede** [comment]
I'm seeing the same issues; on the surface (plowing through the Firefox network log), it looks a lot like some of the [crossdomain.xml](https://github.com/EFForg/https-everywhere/issues?utf8=%E2%9C%93&q=crossdomain.xml) issues that we have had before, but I did not manage to find a nice solution. #4829 contains the same fix that you are using.

**Comment by J0WI** [comment]
I just found out how to reproduce this:
- If Flash Player is _installed_, Golem will force Flash and break HTTPS.
- If Flash Player ist _not installed_, Golem will use HTML5 video and it works fine.

Not that click to play won't work, because Flash is still forced then.

**Comment by fuglede** [comment]
Hah, good catch!

**Comment by fuglede** [comment]
The comment by @ridwande in https://github.com/EFForg/https-everywhere/pull/4829/files/37a81aa036dc0266d6cb6c720849e221266e1255#r72236714 mentions that the videos work with the old ruleset again. @gossi: Would you be able to confirm this?

**Comment by J0WI** [comment]
Without testing I think they changed the behavior described in https://github.com/EFForg/https-everywhere/issues/4770#issuecomment-227363318 to use HTML5 if available and fall back to Flash if not.

**Comment by numismatika** [comment]
Without media.mediasource.enabled=true , you get mixed content issues from two advertising domains:

> Blocked loading mixed active content “http://hgcorigin.svonm.com/hd-main.js?cache=KgzbCLuycK”
> Blocked loading mixed active content “http://084fe6e6df477cdb130e8e9d3d7cb90b76298fdb.2.damoh.golem.de/”

Still trying to properly force the flashplayer here.
Won't be easy on a nightly that forces html5 content more and more :)
