### ISSUE TITLE
Latency to Asian hosts

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#4810]
It turns out, that Travis has a huge latency to Asian hosts.
This results in frequent false positive timeouts during tests.

**Comment by fuglede** [comment]
For what it's worth (which is not all that much), this is not a huge issue for the day-to-day Travis usage: the test only [compares with the current master branch](https://github.com/EFForg/https-everywhere/blob/master/test/travis-ruleset-fetch.sh#L23). This means that the fetch test is run for PRs but not for the merge commit, allowing us to ignore the results if needed, and after confirming that the false negatives are indeed false.

However, this of course has no influence on the periodic database-wide runs of the checker which will still give false negatives.

**Comment by fuglede** [comment]
@J0WI: Will you keep an eye on whether or not this was sufficient to kill off the issues?

**Comment by J0WI** [comment]
Sure. I'll reopen if I still run in this issue.
