### ISSUE TITLE
Certain domain (pitt.edu) breaks when HTTPS everywhere chrome extension is active

### ISSUE THREAD

**Issue by Cull-Methi** [EFForg/https-everywhere#4826]
Expected:

![image](https://cloud.githubusercontent.com/assets/5355839/15362130/27a04192-1ce2-11e6-9b22-99c6e44275e9.png)

Actual: 

![image](https://cloud.githubusercontent.com/assets/5355839/15362154/3ee85448-1ce2-11e6-979e-789efd970c90.png)

Reporting as per https://www.eff.org/https-everywhere/faq#faq-What-if-HTTPS-Everywhere-breaks-some-site-that-I-use?

Some sites within the domain (for example the site my professor uses for class, http://www.pitt.edu/~bonidie/syllabus.html) return 404s when HTTPS everywhere is enabled

**Comment by phillipremaker** [comment]
This is probably "unsafe scripts" getting blocked. Clock on the "shield" in the URL and allow unsafe scripts to load. I'm not sure the right way to deal with this in rulesets. A couple of sites behave this way. 
SOME of the page loads with https, but it seems the browser balks at loading unsigned scripts if ANY part of the page successfully loads with https, even if the main site itself is not using https.

**Comment by Cull-Methi** [comment]
@phillipremaker yes that appears to be the issue, I can confirm that it works when I allow unsafe scripts to load. Sorry for the late reply

**Comment by ckujau** [comment]
```pitt.edu``` also has a problem with their user directories: e.g. ```http://www.pitt.edu/~kloman/harry.html``` works, but ```https://www.pitt.edu/~kloman/harry.html``` produces a 404. Using the excemption toggle and then reloading the ```http``` version works though.

**Comment by J0WI** [comment]
This seems to be fixed.
