### ISSUE TITLE
Marvel.com not loading some content

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4868]
https://marvel.com/news/movies/26203/marvel_studios_confirms_stellar_new_cast_members_of_the_highly_anticipated_thor_ragnarok

Marvel.com (partial) is causing the image in the article to not load properly.  Disabling lets it work.

**Comment by fuglede** [comment]
Did you notice any more problematic pages than this one?

**Comment by numismatika** [comment]
It is mixed content:
"http://marvel.com/images/gallery/slides/story/26203?callback=JCGallery_26203&isTouch=0&limit=50&centerImage=true&slideIndex=0" is considered active and therefore blocked.

**Comment by J0WI** [comment]
Seems to be fixed.
