### ISSUE TITLE
tv4play.se flash videos blocked

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/https-everywhere#4881]
I cannot stream tv4play.se videos with HTTPS-everwhere enabled. It however works when I disable HTTPS-everywhere.

HTTPS-everywhere 5.1.9
Firefox 46.0.1

**Comment by numismatika** [comment]
@davidhedlund is the tv4play.se rule active for you?
It might be a problem of mixed content.
If i go to https://www.tv4play.se/program/nyheterna?video_id=3382332 it seems to load.
Haven't defeated their anti-adblocker yet so i am not sure if it will work 100%.

**Comment by davidhedlund** [comment]
@numismatika 

> Haven't defeated their anti-adblocker yet so i am not sure if it will work 100%.

I had no clue that HTTPS Everywhere defeated anti-adblockers.

You should check this out: https://github.com/reek/anti-adblock-killer/issues/1464

**Comment by numismatika** [comment]
No it doesn't defeat them but sometimes https-everywhere triggers them because the element they check is blocked for being mixed content :)
Does using the https link i gave you fix your video issue?
If yes, i think this can be solved rather quickly by re-enabling the tv4play.se rule

**Comment by davidhedlund** [comment]
@numismatika Yes, HTTPS Everywhere works with https://www.tv4play.se/program/nyheterna?video_id=3382952 works but not http://www.tv4play.se/program/nyheterna?video_id=3382952.

**Comment by numismatika** [comment]
#4924 re-enables the rule
Hopefully there are no major problems with the ruleset.

**Comment by numismatika** [comment]
@davidhedlund 

koket.se sfanytime.com & sfanytime.se  do they belong to the same station?

**Comment by davidhedlund** [comment]
@numismatika Only koket.se is owned by TV4-Gruppen.

**Comment by flyingzebras** [comment]
@numismatika tv4play.se now require that you create and login with an account. So expect to see a loading video that never stop loading even for http:// links from now on as long as you are not logged in.

**Comment by davidhedlund** [comment]
@fuglede @numismatika This bug have not been fixed in HTTPS Everywhere 5.1.10.

**Comment by J0WI** [comment]
closed by #4924, will likely be in our next release.

**Comment by davidhedlund** [comment]
I'm sorry, I can not stream tv4play.se with HTTPS Everywhere 5.2.4 @fuglede @numismatika

**Comment by flyingzebras** [comment]
Thanks.

**Comment by flyingzebras** [comment]
You need to deactivate rules for inpref.s3.amazonaws.com for tv4play.se. That made it stream videos for me. @J0WI @fuglede

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:re-evaluate](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Are-evaluate%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
It is working in HTTPS Everywhere 5.2.5.

**Comment by J0WI** [comment]
@flyingzebras can you confirm?

**Comment by flyingzebras** [comment]
@J0WI It seems like tv4play.se switched to from Flash to HTML5 just a few days ago which is great news!

They have frequently changed the settings on the website, right now amazonaws.com do not need to be added to any rules.

**Comment by flyingzebras** [comment]
@J0WI You can close this issue again.

**Comment by davidhedlund** [comment]
[mylabel:quarantined](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aquarantined%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
https://github.com/reek/anti-adblock-killer/issues/1464

**Comment by flyingzebras** [comment]
@WildS0ft https://github.com/reek/anti-adblock-killer/issues/1464#issuecomment-250237213

>||videoplaza1.tv^$third-party

This must be installed to block ads but it will also active adblock detection.
