### ISSUE TITLE
Streaming video not working on AMC.com

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#4897]
http://www.amc.com/shows/preacher/full-episodes/season-01/episode-00/pilot

Disabling the Google APIs rule allowed this to play without issue.

http://www.amc.com/shows/preacher/video-extras/season-01/episode-00/making-of-preacher-episode-100 can be used as well in case the episode doesn't load due to regional nonsense.

**Comment by jeremyn** [comment]
Using Windows 10, Firefox 48.0.2, and HTTPS Everywhere 5.2.4, I can confirm the problem on the second URL and the fix of disabling the `Google APIs` ruleset.

**Comment by ipatjolvur** [comment]
Related Google APIs rule issues:
#4545

**Comment by gloomy-ghost** [comment]
massive close per #15157
