### ISSUE TITLE
Undefined entity: <dialog id="https-everywhere-prefs"

### ISSUE THREAD

**Issue by Freso** [EFForg/https-everywhere#4909]
This is pretty much exactly the same as https://github.com/EFForg/https-everywhere/issues/2553 - just with HTTPS Everywhere 5.1.9. I've tried installing it from both Firefox's addons repository and directly from EFF.org. I've tried uninstalling it completely (including manually `rm -rf`'ing the leftovers in the profile folder). But I keep getting this when I try to load up the preferences:
![https-everywhere-config-issue](https://cloud.githubusercontent.com/assets/177659/15538965/d7012d0c-227f-11e6-88a0-f11c19e49592.png)

**Comment by sauce-imperial** [comment]
I have the exact same issue. I cannot use any versions higher than 5.1.1.1-let-fixed in any of my Firefox-browsers running on 64bit Debian 8 machines.

**Comment by lsdamsgaard** [comment]
I have the same issue for month now.
Very annoying.

**Comment by jeremyn** [comment]
I use an `en-US` localization of Firefox. I can confirm this problem on Firefox 48.0.2, Windows 10, when I do the following using [these instructions from Mozilla](https://support.mozilla.org/en-US/questions/1018686):

1. Install the Danish language pack from [here](https://addons.mozilla.org/en-US/firefox/language-tools/).
2. Set `about:config > intl.locale.matchOS` to `false`
3. Set `about:config > general.useragent.locale` to `da-DK`.
4. Restart the browser.
5. Open `Add-ons > HTTPS-Everywhere > Options` and observe the error.

The problem doesn't happen with the `en-US` localization so, as a workaround, try switching to that to set your preferences.

**Comment by jeremyn** [comment]
A similar error window is reported in issue #4664.

**Comment by 6a68** [comment]
If this only happens with the danish translation, there's probably some kind of unescaped special character in the Danish locale that breaks XML parsing.

Considering that Firefox is deprecating overlay-based extensions this year, it's probably fine to wontfix this and focus on building a FF-compatible WebExtension instead.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
