### ISSUE TITLE
CBS.com videos won't stream after the April update

### ISSUE THREAD

**Issue by Akainaa** [EFForg/https-everywhere#4918]
Hello,

After the update of HTTPS Everywhere in April 2016 the videos on CBS (such as http://www.cbsnews.com/evening-news/full-episodes/) didn't start to stream anymore. After I disable HTTPS they start to play. 

HTTPS : 5.1.9
Firefox: 46.01

**Comment by numismatika** [comment]
Which rules are active for you on cbsnews?

**Comment by Akainaa** [comment]
I counted 19 dark green rules, 7 light green and 3 grey
![eff https everywhere](https://cloud.githubusercontent.com/assets/19587172/15584371/a86c2e46-237a-11e6-9810-ac9d62bfcbd4.PNG)

**Comment by Bisaloo** [comment]
It may be related to https://github.com/EFForg/https-everywhere/issues/4897.

Can you try disabling the Google API rule?

**Comment by Akainaa** [comment]
I disabled the Google API rule and the stream started to work immediately. Much obliged.

**Comment by ma7r** [comment]
I also need to disable the Google APIs rule to view videos on stuff.co.nz, e.g.:
http://www.stuff.co.nz/life-style/life/80520155/friendly-falcon-moves-on-in

**Comment by ipatjolvur** [comment]
Related Google APIs rule issues:
#4545
