### ISSUE TITLE
Certificate inconsistency between Iceweasel test instance, and normal Iceweasel instance

### ISSUE THREAD

**Issue by sampablokuper** [EFForg/https-everywhere#4948]
With Debian Jessie 8.4 (x86), using the `master` branch at [`56c9667b98828498cb7144d2a23dab2fe9674f79`](https://github.com/EFForg/https-everywhere/commit/56c9667b98828498cb7144d2a23dab2fe9674f79), I created the following ruleset file at `src/chrome/content/rules/Mensa.org.uk.xml`:

```
<ruleset name="Mensa.org.uk">
        <target host="mensa.org.uk" />
        <target host="www.mensa.org.uk" />
        <target host="test.mensa.org.uk" />
        <target host="profile.mensa.org.uk" />

        <rule from="^http:" to="https:" />

        <securecookie          host="^mensa\.org\.uk$" name=".+" />
        <securecookie     host="^www\.mensa\.org\.uk$" name=".+" />
        <securecookie    host="^test\.mensa\.org\.uk$" name=".+" />
        <securecookie host="^profile\.mensa\.org\.uk$" name=".+" />
</ruleset>
```
As you can see, this includes a rule for `profile.mensa.org.uk`.

Running `bash test/firefox.sh --justrun` and then browsing to https://profile.mensa.org.uk/contact.aspx in the resulting browser instance, yields a warning in the browser:

> 
> This Connection is Untrusted
> 
> You have asked Iceweasel to connect securely to profile.mensa.org.uk, but we can't confirm that your connection is secure.
> 
> Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.
> What Should I Do?
> 
> If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.
> 
> profile.mensa.org.uk uses an invalid security certificate.
> 
> The certificate is not trusted because the issuer certificate is unknown.
> 
> (Error code: sec_error_unknown_issuer)
> 
> If you understand what's going on, you can tell Iceweasel to start trusting this site's identification. Even if you trust the site, this error could mean that someone is tampering with your connection.
> 
> Don't add an exception unless you know there's a good reason why this site doesn't use trusted identification.

However, browsing to https://profile.mensa.org.uk/contact.aspx in a normal Iceweasel instance (i.e. started using the command `iceweasel`, not via `bash test/firefox.sh --justrun`) yields no warning, and instead finds a TLS certificate with the following Subject field:

```
CN = profile.mensa.org.uk
OU = Domain Control Validated - RapidSSL(R)
OU = See www.rapidssl.com/resources/cps (c)15
OU = GT91227394
```

**I do not know the reason for this inconsistency.**

**Presumably this inconsistency should not be present.**

The inconsistency may be related to #2801 .

The inconsistency may be related to the following facts:

- mensa.org.uk, www.mensa.org.uk, and test.mensa.org.uk are served by Apache, whereas profile.mensa.org.uk is served by IIS;

- as with `bash test/firefox.sh --justrun`, `curl` can't find a certificate for https://profile.mensa.org.uk

Compare the following output for the domains served by Apache ...

```
$ curl --head http://mensa.org.uk
HTTP/1.1 200 OK
Date: Sat, 28 May 2016 12:39:12 GMT
Server: Apache
Pragma: no-cache
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: SESS4b296932593725667cea89bf7eb4e462=t7qa9kbr9frc9cftcjfeqiet75; path=/; domain=.mensa.org.uk
Last-Modified: Sat, 28 May 2016 12:39:12 GMT
Content-Type: text/html; charset=utf-8

$ curl --head https://mensa.org.uk
HTTP/1.1 200 OK
Date: Sat, 28 May 2016 12:39:48 GMT
Server: Apache
Pragma: no-cache
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: SESS4b296932593725667cea89bf7eb4e462=f3k9cd0m61970u7touur1be820; path=/; domain=.mensa.org.uk
Last-Modified: Sat, 28 May 2016 12:39:48 GMT
Content-Type: text/html; charset=utf-8

$ curl --head http://www.mensa.org.uk
HTTP/1.1 200 OK
Date: Sat, 28 May 2016 12:39:22 GMT
Server: Apache
Pragma: no-cache
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: SESS4b296932593725667cea89bf7eb4e462=8ioip7pjlk06kjbqlfkfnf8gj2; path=/; domain=.mensa.org.uk
Last-Modified: Sat, 28 May 2016 12:39:22 GMT
Content-Type: text/html; charset=utf-8

$ curl --head https://www.mensa.org.uk
HTTP/1.1 200 OK
Date: Sat, 28 May 2016 12:39:56 GMT
Server: Apache
Pragma: no-cache
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: store, no-cache, must-revalidate, post-check=0, pre-check=0
Set-Cookie: SESS4b296932593725667cea89bf7eb4e462=d10lbmrpju03rccsaftdemiai6; path=/; domain=.mensa.org.uk
Last-Modified: Sat, 28 May 2016 12:39:56 GMT
Content-Type: text/html; charset=utf-8

$ curl --head http://test.mensa.org.uk
HTTP/1.1 301 Moved Permanently
Date: Sat, 28 May 2016 12:52:21 GMT
Server: Apache
Location: http://www.mensa.org.uk/
Cache-Control: max-age=1209600
Expires: Sat, 11 Jun 2016 12:52:21 GMT
Content-Type: text/html; charset=iso-8859-1

$ curl --head https://test.mensa.org.uk
curl: (51) SSL: no alternative certificate subject name matches target host name 'test.mensa.org.uk'
```

... to the output for the domain served by IIS:

```
$ curl --head http://profile.mensa.org.uk
HTTP/1.1 302 Found
Date: Sat, 28 May 2016 12:39:17 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
X-AspNet-Version: 4.0.30319
Location: /contact.aspx
Set-Cookie: ASP.NET_SessionId=g4hxmn3xvu4twuamfpyibcs2; path=/; HttpOnly
Set-Cookie: WebToolsParam= ; path=/; HttpOnly
Cache-Control: no-cache, no-store
Pragma: no-cache
Expires: -1
Content-Type: text/html; charset=utf-8
Content-Length: 130

$ curl --head https://profile.mensa.org.uk
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by sampablokuper** [comment]
As the inconsistency between cURL and a normal Iceweasel instance is outside the scope of this bug, I have asked about it [elsewhere](http://unix.stackexchange.com/q/286122/6860). If anything potentially relevant to this bug emerges from that inconsistency, I will try to remember to report it here.

**Comment by mnordhoff** [comment]
https://profile.mensa.org.uk/ has an improperly configured certificate chain:

https://www.ssllabs.com/ssltest/analyze.html?d=profile.mensa.org.uk&hideResults=on

(It's also incredibly archaic, badly configured, and entirely insecure, but that's not directly relevant.)

Basically, a server is supposed to go "here's my certificate, and here's my CA's intermediate certificate that signed it," and maybe "here's my CA's other intermediate that signed the first intermediate." profile.mensa.org.uk is only going "here's my certificate." TLS implementations react to this problem in various ways. Firefox will work normally if it has previously visited another website serving the same intermediate(s) and already cached it/them; otherwise it will display the "untrusted" error page. This is why it works in your normal profile but fails in the test profile.

For HTTPS Everywhere's purposes, the Mensa.org.uk ruleset should contain a `<!-- comment -->` noting that `profile.mensa.org.uk` has a bad chain, but the rule for that subdomain should be commented out or deleted.

**Comment by sampablokuper** [comment]
@mnordhoff thanks for investigating. As you say, the behaviour seems to be due to server misconfiguration, and does not appear to result from any flaws in HTTPS Everywhere. So, I'll close this issue.
