### ISSUE TITLE
Remove duplicated ruleset whitelist entries

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#4975]
Just discovered that the list contains some duplicated entries that are not removed by the script in #4830. So the script should contain some `sort | uniq` magic.

**Comment by fuglede** [comment]
I did consider having the script remove the dupes (cf. the remark at the end of https://github.com/EFForg/https-everywhere/pull/4830#issue-155598754) but honestly didn't bother, as they are comparatively few in number. That being said, it is a very natural addition to [utils/ruleset-coverage-whitelist-cleanup.sh](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-coverage-whitelist-cleanup.sh).

**Comment by jeremyn** [comment]
Pull request #6246 should resolve this issue.
