### ISSUE TITLE
HTTPS on Amazon

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#4997]
Amazon announced to finally support HTTPS. We should rebase our Amazon rules to check which sites can be secured now.

See also #1578 #3323 #3444 #4255 #4366

**Comment by xiaoyinl** [comment]
HTTPS support on Amazon is still partial. For instance, https://www.amazon.com/J.K.-Rowling/e/B000AP9A6K/ redirects to http.

**Comment by J0WI** [comment]
Seems to happen on all `/B00\w+/` pages -.-

**Comment by ivan** [comment]
https://www.amazon.com/J.K.-Rowling/e/B000AP9A6K/ seems to stay on HTTPS now.
