### ISSUE TITLE
Apple store unable to check out

### ISSUE THREAD

**Issue by ChrisTheCat** [EFForg/https-everywhere#5039]
On this page: http://www.apple.com/us-hed/shop/bag the "Check Out" button doesn't work until I disable https everywhere. After I disable the extension, the check out button works and leads to https://secure1.store.apple.com/us-hed/shop/sign_in?c=aHR0cDovL3d3dy5hcHBsZS5jb20vdXMtaGVkL3Nob3AvYmFnfDFhb3M5OTNlZTJlMjI5MDdmZTRkOWFiYzVmMzhkMDFhNmJlNmM2ZTY0N2Yx&o=O01BQ0JPT0tBSVJfWi0xMDQ5NTk7TUhOSDI&r=SXYD4UDAPXU7P7KXF&s=aHR0cHM6Ly9zZWN1cmUxLnN0b3JlLmFwcGxlLmNvbS91cy1oZWQvc2hvcC9jaGVja291dC9zdGFydD9wbHRuPTJENUJCNjcyfDFhb3M3Nzc5ZjhmOTA1YTZkN2VhODRjMTBhMzEzYmE2M2FkMjhiNjRkMzc3&t=SXYD4UDAPXU7P7KXF&up=t

**Comment by pipboy96** [comment]
No longer reproducible.
