### ISSUE TITLE
Please add www.jd.com and item.jd.com

### ISSUE THREAD

**Issue by LisonFan** [EFForg/https-everywhere#5043]
Thanks

**Comment by renyouguo** [comment]
#4849

**Comment by renyouguo** [comment]
https://github.com/EFForg/https-everywhere/pulls/renyouguo
There are 58 open PRs which I have add.

**Comment by rafaelyine** [comment]
www.jd.com run good in https, support +1

item.jd.com run good mostly, but sitll some urls broked. Oppose -1
e.g. https://item.jd.com/1403977.html

**Comment by renyouguo** [comment]
@rafaelyine https://item.jd.com/1403977.html is ok for me.

**Comment by jeremyn** [comment]
@rafaelyine What is wrong with https://item.jd.com/1403977.html ?

**Comment by gloomy-ghost** [comment]
#5626 was merged long time ago
