### ISSUE TITLE
Working on *.gov

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#5047]
This project seems quite interesting for us: https://pulse.cio.gov/

They provide a list of the https migraton status:
https://pulse.cio.gov/data/domains/https.csv

**Comment by Hainish** [comment]
Based on the spreadsheet, I suppose that the we can safely make trivial rules for those domains which `Enforces HTTPS` is set to `true`, and `HSTS` is set to anything but `Yes, and preloaded`.  The category `Uses HTTPS` is probably quite a lower barrier covering any range of configurations.

Perhaps @konklone can speak to this.

**Comment by konklone** [comment]
`Uses HTTPS` means that the site can be reached over HTTPS, which does mean that https->http downgrades don't count, but it also means that, for example, senate.gov has a `Yes` for `Uses HTTPS`. So yeah, I wouldn't use that.

`Enforces HTTPS` is pretty strict and means that the domain appear to redirect its "endpoints" (`http://` and `http://www`) to an `https://` version. It only requires one of `https://` or `https://www` to be up. I think you could safely use that, though it's possible there's an edge case I'm not thinking of.

If `HSTS` is `Yes`, it means that the domain's "canonical" endpoint has HSTS on it. This could mean, for example, that `https://www.example.gov` has an HSTS policy on it but `https://example.gov` does not, if the canonical endpoint for the domain uses `www`. In fact, `https://example.gov` could easily have a certificate not valid for its hostname, while `http://example.gov` redirects successfully to `https://www.example.gov`.

If `HSTS` is `Yes, and preload-ready`, it means that the root has the right HSTS policy to be preloaded, like `https://example.gov`, regardless of whether the "canonical" endpoint for the domain uses `www`. But it means it's not in the preload list at the moment, for whatever reason.

If `HSTS` is `Yes, and preloaded` then it's in the preload list.

This methodology is documented at a high level on https://pulse.cio.gov/https/guidance/. It's possible it could change, or that the implementation could change in some subtle way. I don't want to recommend one way or the other that you incorporate the results from pulse.cio.gov, but I do want you to have the information you need to decide if it's helpful.

**Comment by Hainish** [comment]
Thank you @konklone all this info is very helpful.
