### ISSUE TITLE
Please add these sites who enabled HTTPS

### ISSUE THREAD

**Issue by juhiyu** [EFForg/https-everywhere#5055]
I found some websites who have HTTPS but no HTTPS-E rules

fivethirtyeight.com and subdomains
dailymotion.com and subdomains other cdn domains etc.
einthusan.com and subdomains
nofap.com
socialblade.com

**Comment by juhiyu** [comment]
beeg.com too

**Comment by Foorack** [comment]
Nofap.com already redirect all domains to HTTPS.

**Comment by zneaa** [comment]
@juhiyu   socialblade.com is already incuded.

**Comment by HTTPSNowhere** [comment]
Already included:
fivethirtyeight.com https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/FiveThirtyEight.com.xml
dailymotion.com https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Dailymotion.xml
socialblade.com https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Socialblade.com.xml

Closed ruleset:
- [ ] nofap.com https://github.com/EFForg/https-everywhere/pull/6293 @J0WI this should be reopened and merged right?

New ruleset:
- [ ] einthusan.tv <- einthusan.com https://github.com/EFForg/https-everywhere/pull/11048

**Comment by J0WI** [comment]
The repository of this PR has been deleted.

**Comment by jeremyn** [comment]
I've noted `einthusan.com` and `nofap.com` at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-353648503`. `fivethirtyeight.com`, `dailymotion.com`, `socialblade.com`, and `beeg.com` have rulesets.

So, I'm closing this issue.
