### ISSUE TITLE
MapMyRun can't work with HTTPS everywhere

### ISSUE THREAD

**Issue by singpolyma** [EFForg/https-everywhere#5060]
http://www.mapmyrun.com/routes/create/ fails with HTTPS Everywhere because the default ruleset forces their JS to load over HTTPS which then makes it fail a CORS check

**Comment by Kovensky** [comment]
This also affects CORS loads from http://source.pixiv.net -- used in not yet public code. Chrome sends an `Origin: null` header when connecting from non-secure origins (such as `www.pixiv.net`), which causes a CORS check failure.

An exclusion rule for `^http://source\.pixiv\.net/.*/app/[^/]+\.js` (note: no `$`) would work around the problem for now, but a better fix would be to either not rewrite `mode: 'cors'` fetches, or convince the UA to not "censor" the `Origin` header if the URL was rewritten.

**Comment by J0WI** [comment]
closed by #14705
