### ISSUE TITLE
add support for bittorrenthub.me

### ISSUE THREAD

**Issue by treakiandroid** [EFForg/https-everywhere#5068]
maybe like this:

```
<ruleset name="bittorrenthub.me">
        <target host="bittorrenthub.me" />
        <target host="*.bittorrenthub.me" />

        <rule from="^http:"
                to="https:" />
</ruleset>
```

**Comment by J0WI** [comment]
Please have a look at our guides:
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md

We are always happy to receiving pull request ;)

**Comment by treakiandroid** [comment]
just check if it is working also at your site and then add it yourselv, i dont have the abilitys to code or use that pull request thing. i am not a programmer, i have just seen that this site is accessible through https but not by default, but you can add a s behind the http and then there is no downside but encription (so not as on some pages/sites (web) where the same domain/url using https dosnt workes as good as)

so take it or leave it...

regards
