### ISSUE TITLE
JW Platform.com (partial) breaks video (on Chrome)

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#5086]
http://dailycaller.com/2016/03/30/jane-sanders-hillary-tries-to-get-votes-from-people-at-the-worst-time-in-their-life-video/

JW Platform.com (partial) breaks video

Another example: http://www.wnd.com/2016/04/trump-erupts-as-cruz-sweeps-colorado-without-votes/
breaks both videos. First video is also broken by Google API. #4545
#4531

@J0WI

**Comment by terrorist96** [comment]
http://www.realclearpolitics.com/video/2016/06/19/abcs_jonathan_karl_to_sen_chris_murphy_your_gun_control_proposals_would_not_have_stopped_orlando.html

JW Platform and Google APIs breaks video.
#4545

**Comment by terrorist96** [comment]
http://www.realclearpolitics.com/video/2016/07/11/trump_i_am_the_law_and_order_candidate.html

JW-platform.com (partial) breaks video.

**Comment by terrorist96** [comment]
http://deadspin.com/lebron-carmelo-wade-cp3-open-espys-with-statement-on-1783626133

JW Platform.com (partial) breaks video, in addition to Kinja-static.com (#6194)

**Comment by terrorist96** [comment]
http://mashable.com/2012/09/13/six-degrees-kevin-bacon/#GRVzKpuroqqA

**Comment by terrorist96** [comment]
http://mashable.com/2016/11/07/reborning-babies/#EIhpNz8Wiaqp

**Comment by J0WI** [comment]
@terrorist96 refering to https://github.com/EFForg/https-everywhere/pull/7345#issuecomment-285549109 this issue can no longer be reproduced. Can you confirm this?

**Comment by terrorist96** [comment]
Confirmed.
