### ISSUE TITLE
Remove nsIChannelEventSink implementation?

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#509]
It's marked with a comment that suggests it's no longer necessary. TODO: Test whether everything works without it.

In either case, I think `onChannelRedirect` gets called before the listener for `http-on-modify-request`, so it should probably have the new `shouldIgnoreURI` checks before calling `HTTPS.replaceChannel`.

**Comment by jeremyn** [comment]
@diracdeltas I can't find any reference to `nsIChannelEventSink` in the code but I'm not sure what this is about. Has `nsIChannelEventSink` been removed already?

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
