### ISSUE TITLE
Add trade.jd.com & cashier.jd.com to ruleset

### ISSUE THREAD

**Issue by rafaelyine** [EFForg/https-everywhere#5132]
This two urls work well in https, but they do not redirect to themselves.
They refer to money, hope add its to ruleset as soon as possible!
Thank U!

**Comment by jeremyn** [comment]
Can you please provide a working, "real" URL for `cashier.jd.com`? Google search [here](https://www.google.com/search?q=site%3Acashier.jd.com&ie=utf-8&oe=utf-8) doesn't show any results, and https://cashier.jd.com is empty. I'd like to see a nonempty page for that domain before we add it. [Here](https://trade.jd.com/shopping/order/getOrderInfoWithoutRegist.action) is an example for `trade.jd.com`.
