### ISSUE TITLE
KrxD.net

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#5134]
This breaks video playback. Example:
http://www.sbnation.com/nba/2016/6/17/11962842/steph-curry-mouthpiece-fan-nba-finals-suspension-fine

**Comment by numismatika** [comment]
I went there and it didn't play before
I rewrote a couple of involved rulesets like Ooyala, SBnations (disabled),Vox-Media , Vox-CDN and Vine.co.
Couldn't find any request to KrxD.net there, which i think is an adnetwork that i filter out.

**Comment by numismatika** [comment]
@tancrackers is this issue fixed now?

**Comment by tancrackers** [comment]
It's all working now, on my end.
