### ISSUE TITLE
[Humboldt-Universität zu Berlin] add hu-berlin.de

### ISSUE THREAD

**Issue by rid007** [EFForg/https-everywhere#5146]
Please add new rule set to https://hu-berlin.de with and without www works both.

**Comment by jeremyn** [comment]
There are a lot of subdomains  that should be added or noted as nonworking for a new `hu-berlin.de` ruleset along with https://www.hu-berline.de and https://hu-berlin.de . [Here](https://www.google.com/search?q=site%3Ahu-berlin.de&ie=utf-8&oe=utf-8#q=site:*.hu-berlin.de) is a Google search showing them.
