### ISSUE TITLE
[German Research Center for Artificial Intelligence] www.dfki.de

### ISSUE THREAD

**Issue by rid007** [EFForg/https-everywhere#5178]
Please add new rule set for www.dfki.de

**Comment by J0WI** [comment]
Thanks for your suggestion.

We are always happy to receive pull requests ;)
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md

**Comment by zneaa** [comment]
PR https://github.com/EFForg/https-everywhere/pull/8890

**Comment by jeremyn** [comment]
I've closed PR #8890 without merging it, so `dfki.de` still needs a ruleset.

I've also added `dfki.de` to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-352916881`, so I'm closing this issue.
