### ISSUE TITLE
lon.gs doesn't work because of Bitly vanity domains

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#5253]
lon.gs simply doesn't work with Bitly vanity domains enabled.

https://www.eff.org/https-everywhere/atlas/domains/lon.gs.html

**Comment by J0WI** [comment]
Thanks for your report!
@jehiah announced an updated of the affected ruleset soon on https://github.com/EFForg/https-everywhere/issues/5083#issuecomment-225904065, so this will hopefully be fixed then.

**Comment by J0WI** [comment]
closed by #11804
