### ISSUE TITLE
Please add 'vip.jr.jd.com'

### ISSUE THREAD

**Issue by LisonFan** [EFForg/https-everywhere#5266]
Thanks

**Comment by J0WI** [comment]
Thanks for your suggestion.

We are always happy to receive pull requests ;)
https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md

**Comment by fuglede** [comment]
Closed by #6687.
