### ISSUE TITLE
Please add 'www.v2ex.com'

### ISSUE THREAD

**Issue by LisonFan** [EFForg/https-everywhere#5267]
Thanks

**Comment by odv** [comment]
@LisonFan I've just checked the rules directory and we already have a rule for 'www.v2ex.com' in 'https-everywhere/src/chrome/content/rules/V2ex.xml'.

**Comment by tomwys** [comment]
There is already ruleset for that site https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/V2ex.xml .

**Comment by jeremyn** [comment]
@LisonFan I'm closing this issue because as @tomwys said, there is already a ruleset that covers this domain, but please feel free to reopen this issue with a comment if needed.
