### ISSUE TITLE
SSLObservatory Slows SessionRestore

### ISSUE THREAD

**Issue by bill-mcgonigle** [EFForg/https-everywhere#527]
while looking into a performance problem while running Tree Style Tabs https://github.com/piroor/treestyletab/issues/720, I ran the JS profiler on a SessionRestore with about 1600 tabs, which took about 15 minutes (quad core 2.6GHz AMD).

Looking at the events that the profiler captured, about half the profiled JS time was spent in SSLObservatory.prototype.observe().  

Not sure how this works, but if it's being fired for each tab, we could get more performance by delaying its action until the tab is actually loaded (SessionRestore w/ TST creates the tab but does not load it until it's clicked on, at least in my config).

I haven't yet found a way to blind the profile data itself such that uploading it would be sensible, but here's a screeshot of the call list above 0.0%:

![js-tst-sslobservatory](https://cloud.githubusercontent.com/assets/880256/4112645/4addc37c-3234-11e4-9499-dff96ba7b8ee.png)

**Comment by gloomy-ghost** [comment]
Observatory is gone in the WebExtension release
