### ISSUE TITLE
Bug report: *.baidupcs.com & *.pcs.baidu.com both failed in https

### ISSUE THREAD

**Issue by rafaelyine** [EFForg/https-everywhere#5301]
Both *.baidupcs.com & *.pcs.baidu.com are download links, actually get no speed when its forced to https. Hope fixed. Thanks!

**Comment by lqf96** [comment]
Maybe this is an ISP-specific problem. I could download files from Baidu Cloud (which uses HTTPS for "\*.baidupcs.com" domains), though the speed is bit slow. I'm in Beijing and use CERNET.

**Comment by pipboy96** [comment]
Impossible to reproduce outside GFW and without any test links.
