### ISSUE TITLE
Breaks links in YAMM-created emails

### ISSUE THREAD

**Issue by pizza2code** [EFForg/https-everywhere#5342]
HTTPS Everywhere results in a 'connection not secure' error when following [YAMM](https://sites.google.com/site/scriptsexamples/available-web-apps/mail-merge/)-generated email links such as this:

[Farms Will Stop Grinding Male Chicks](http://thehumaneleague.yamm-track.appspot.com/Redirect?ukey=1O1h864egntIQyisnzVy7Rg-sCqpgt6EhFGAMfDKGrfI-660977523&key=YAMMID-41267121&link=https%3A%2F%2Fwww.washingtonpost.com%2Fnews%2Fanimalia%2Fwp%2F2016%2F06%2F10%2Fegg-producers-say-theyll-stop-grinding-male-chicks-as-soon-as-theyre-born%2F)

I got around this by adding a rule to redirect from the https to the http.  Would submit a pull request, but the backlog there looks scary.

**Comment by jeremyn** [comment]
Thanks for the report. I know what you mean by the backlog, but submitting a pull request will get this resolved faster than not submitting one,
