### ISSUE TITLE
adds 2 seconds to / doubles firefox startup time

### ISSUE THREAD

**Issue by prougrugge** [EFForg/https-everywhere#5354]
On my computer, with no extensions installed, Firefox takes about 2 seconds to start.

If I install HTTPS-Everywhere, Firefox takes an additional ~2 seconds to start, for a total of about 4 seconds.

Note that I can install 26 other extensions without adding a second to the Firefox startup time.

**Comment by prougrugge** [comment]
at this point https-everywhere adds 3.5 seconds to the startup time of my profile; i've finally decided to disable it.

**Comment by Giltyhub** [comment]
@prougrugge can u try now with the new webextension release?

**Comment by Bisaloo** [comment]
Closing this as duplicate of #12232.
