### ISSUE TITLE
Please Update NYTimes.xml

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#5376]
This rule reeds big change.
- [x] #9398 
- [x] #9399 
- [x] #9400 
- [x] #9402 
- [x] #9423 
- [x] #9424 
- [x] #9425 
- [x] #9426 
- [x] #9437 
- [x] #9451

**Comment by jeremyn** [comment]
https://www.nytimes.com/ in a browser returns an HTTP 301 ("Moved Permanently") redirect to http://www.nytimes.com/ . I see some little things returned from https://www.nytimes.com/, possibly related to ads or analytics, but it looks like overall they are deliberately discouraging HTTPS access.

What's the goal for this issue?

**Comment by ivysrono** [comment]
@jeremyn 
https://www.ssllabs.com/ssltest/analyze.html?d=cn.nytimes.com
https://www.ssllabs.com/ssltest/analyze.html?d=cn.nytstyle.com

**Comment by ivysrono** [comment]
I have just received a notice from April 22, my job will become very, very busy.

@jeremyn @J0WI , is it possible to review the PRs that I still open?

I am afraid there will not be so much time to maintain complex rules.

Thank you very much for your long-term support, help and guidance.

I will make every effort to take the time to continue to promote the progress of the project.

In any case, thank you.

**Comment by J0WI** [comment]
Thanks!
