### ISSUE TITLE
Enabling "Https everywhere" in chrome leads to disappearing grid icon at Google home page

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#54]
Titile:- Enabling "Https everywhere" in chrome leads to disappearing grid icon at Google home page
![enable_https_everywhere_chrome_grid_icon](https://f.cloud.github.com/assets/6317041/1844420/f907f830-7526-11e3-8ab0-2c8caafdb90f.jpg)
![diabling_https_everywhere_chrome](https://f.cloud.github.com/assets/6317041/1844421/f910dc48-7526-11e3-9deb-176fd1aadc43.jpg)
![enable_https_everywhere_chrome](https://f.cloud.github.com/assets/6317041/1844422/f91a12b8-7526-11e3-9876-3f40d64fee31.jpg)

Steps to reproduce:- (Prerequisites are Https everywhere extension is installed in chrome)

1:- Go to Google Homepage before enabling https everywhere and check if Grid icon appears at homepage

2:- Enable "Https everywhere" and check if you still see the grid icon, it disappears

Note:- Refer to screenshots attached.

System Info:-
Windows 7 (Ultimate) -64bit
Google Chrome:- Version 31.0.1650.63 m
Https everywhere:- 2013.10.16

Submitted by:-

Kashif Ahmad
kahmad01@gmail.com
+91-7259582807

**Comment by kahmad01** [comment]
> Titile:- Enabling "Https everywhere" in chrome leads to disappearing grid icon at Google home page
> ![enable_https_everywhere_chrome_grid_icon](https://camo.githubusercontent.com/6ec411cc181fd0f1b995059e8603805db8cc5098dc2f24cdc77bd005851eb924/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363331373034312f313834343432302f66393037663833302d373532362d313165332d386162302d3263386361616664623930662e6a7067)
> ![diabling_https_everywhere_chrome](https://camo.githubusercontent.com/2277b2d21072d3c3c33ad56ede1bd6eaae4630b85bfc5297801b155ffeabef66/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363331373034312f313834343432312f66393130646334382d373532362d313165332d396465622d3137366664316161646334332e6a7067)
> ![enable_https_everywhere_chrome](https://camo.githubusercontent.com/11e1b5271276adff2e397f5baca685f44a41b1fce38da2327e960cac7fb24d43/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363331373034312f313834343432322f66393161313262382d373532362d313165332d393837362d3366343064363466656533312e6a7067)
> 
> Steps to reproduce:- (Prerequisites are Https everywhere extension is installed in chrome)
> 
> 1:- Go to Google Homepage before enabling https everywhere and check if Grid icon appears at homepage
> 
> 2:- Enable "Https everywhere" and check if you still see the grid icon, it disappears
> 
> Note:- Refer to screenshots attached.
> 
> System Info:-
> Windows 7 (Ultimate) -64bit
> Google Chrome:- Version 31.0.1650.63 m
> Https everywhere:- 2013.10.16
> 
> Submitted by:-
> 
> Kashif Ahmad
> [kahmad01@gmail.com](mailto:kahmad01@gmail.com)
> +91-7259582807

Can you please remove my email and no. from the thread?
