### ISSUE TITLE
ReadTheDocs

### ISSUE THREAD

**Issue by mightyiam** [EFForg/https-everywhere#550]
Hi and thank you for important privacy protecting software.

Seems that [ReadTheDocs](http://readthedocs.org/) has HTTPS [support](https://readthedocs.org/).

And it [seems](http://selenium-python.readthedocs.org/) [trivial](https://selenium-python.readthedocs.org/).

**Comment by nopjmp** [comment]
looks like https://*.rtfd.org may have problems as it redirects to readthedocs.org without readthedocs.org getting a new certificate or extending it to the shortened version. HTTPS Everywhere could do a rewrite rule from the shorten version to help them out and secure the shortened version.

**Comment by destroyerofbuilds** [comment]
@2d1 is there any further work here required?

@nopjmp I believe the issue you mention has been resolved.

**Comment by nopjmp** [comment]
Yes it appears that the issue has been resolved. Thank you everyone involved!
