### ISSUE TITLE
Add contributor notification to release process

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#552]
When we generate a release, our tools should also generate a list of email addresses from the commit logs between the previous release and the current one. We should CC those addresses on release announcements.

This is useful for two reasons. It helps contributors know when their changes are in so they can test them on the production release, and it helps people be more involved in the project.

**Comment by pipboy96** [comment]
This doesn't seem to be a good idea. Generally, before any automated email you need to obtain consent from everyone subject to such email, and also provide a way to unsubscribe from them. Issue was also created in 2014, with no follow-up. Closing.
