### ISSUE TITLE
Request to add 'cvs.com'

### ISSUE THREAD

**Issue by VladimirTechMan** [EFForg/https-everywhere#5599]
The website of CVS / Pharmacy supports HTTPS perfectly well. But it does not re-route its visitors to the version using the encrypted connection when they connect through plain HTTP. (Even in the case when they try to log in to their personal accounts at CVS.com. Too bad.) Thus, HTTPS-Everywhere could really come to their rescue.

**Comment by chris-barry** [comment]
Added some rules, check'em out.

**Comment by VladimirTechMan** [comment]
Thanks, @chris-barry. I manually added the new rule file to the HTTPSEverywhereUserRules folder inside my profile folder of the local Firefox copy. Then I restarted it and did some tests. Based on that, it looks good the me.

**Comment by J0WI** [comment]
closed by #14552
