### ISSUE TITLE
Must disable Cnzz.com or Bilibili.com's video will get error #2048

### ISSUE THREAD

**Issue by zzhhbyt1** [EFForg/https-everywhere#5602]

**Comment by jeremyn** [comment]
Here's an example link: http://www.bilibili.com/video/av6050274/ . On Windows 10, if I visit the URL in Chrome, the video won't play and instead I see a white screen that says `Loading (100%)...`. If I disable the `Adobe.com` rule, the video will work. If I visit the URL in Firefox, the video plays right away, and the `Adobe.com` doesn't even appear under `Enable / Disable Rules`. The `Cnzz.com` ruleset doesn't seem related.

**Comment by hwk603** [comment]
Same here , On Windows 10 , https 2016.9.1
![images 2016-09-04 1472996969](https://cloud.githubusercontent.com/assets/7033138/18231317/a03a1b02-72e9-11e6-97aa-3edb27d850ea.png)

**Comment by Artoria2e5** [comment]
```
http://tajs.qq.com/stats?sId=9156259&_=1473883615714
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

stat.php?id=2724999&web_id=2724999&_=1473883615711:16
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

https://hzs11.cnzz.com/stat.htm?id=2724999&r=&lg=en-us&ntime=1473602138&cnz…4%E5%93%A9%E5%BC%B9%E5%B9%95%E8%A7%86%E9%A2%91%E7%BD%91&h=1&rnd=1196376936
Failed to load resource: net::ERR_TIMED_OUT

VM44 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'url' of undefined
    at chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.min.js:2:4148
```

**Comment by Artoria2e5** [comment]
And yes, my personal suggestion is to ditch all of the `s\d+\.cnzz\.com` domains. I guess being able to work with HTTPs is a result of some misconfiguration for CNZZ.

**Comment by gloomy-ghost** [comment]
I tried to open the link in incognito mode, which allows me to disable all extensions except https-everywhere. The video successfully loaded without any error:

![image](https://cloud.githubusercontent.com/assets/13086421/18615029/5fb9362e-7def-11e6-80d2-f52305e73ed4.png)

Furthermore, CNZZ has official support of https. Look here: http://help.cnzz.com/support/kuaisuanzhuangdaima/changjianwenti/2013/0902/25.html

**Comment by Artoria2e5** [comment]
I know that one occurs anyway. But the s11 server being too clever is… meh.

**Comment by gloomy-ghost** [comment]
The timeout of `hzs11.cnzz.com` does not really break bilibili. Visitors won't care about the site and third-party trackers are unable to track them :)

I sent an email to both cnzz and bilibili. Hope they will look it up...

BTW, bilibili is not only using cnzz (They also have own trackers). They should do something if the data deviation of cnzz is unacceptable and they care about it.

**Comment by gloomy-ghost** [comment]
`hdslb.com` is breaking live videos (e.g. http://live.bilibili.com/204600) now... Found nothing about `hdslb.com` on console when the ruleset is enabled though.

**Comment by gloomy-ghost** [comment]
#7976 fixes live videos, can anyone on this thread who experienced video issues have a look at the PR if it fixes the main site as well?

**Comment by gloomy-ghost** [comment]
I believe this has been fixed, but please feel free to reopen if anyone is able to reproduce it.
