### ISSUE TITLE
ark.intel.com broken

### ISSUE THREAD

**Issue by petteyg** [EFForg/https-everywhere#5603]
With HTTPS Everywhere 5.1.10 with Firefox 47.0, ark.intel.com "compare" feature is non-functional. Clicking the link/button results in an endless loading animation from the browser. Not sure which rule is causing it - disabling any combination of en25, tealium, and/or intel doesn't fix it, while disabling HTTPS Everywhere allows it to work.

EDIT: The link sometimes functions, sometimes doesn't. May be something on Intel's end just coinciding with me installing HTTPS Everywhere.

**Comment by socram8888** [comment]
It's working fine on my computer with the same Firefox and HTTPS Everywhere versions.

**Comment by J0WI** [comment]
Works fine here.

**Comment by jeremyn** [comment]
I'm not getting this problem either. This works for me on Windows 10, Firefox and Chrome:

1. Go here: http://ark.intel.com/products/family/79318/Intel-High-End-Desktop-Processors#@Desktop
2. Click `Compare All+`
3. Click `Compare Specifications (...)` slide-down.

I'm closing this issue, but @petteyg please feel free to reopen the issue with a comment if you are still getting this problem.
