### ISSUE TITLE
Remove "Swehack.org"

### ISSUE THREAD

**Issue by intchloe** [EFForg/https-everywhere#5609]
I'm the owner of the domain swehack.org and I would like to remove this rule. You can see proof here: https://keybase.io/dotchloe

Rule: https://www.eff.org/https-everywhere/atlas/domains/swehack.org.html

I can't remove the rule via Github for some strange reason and I don't have the time to fight the issue (yes, I've tried). 

Thanks!

**Comment by fuglede** [comment]
Would it be sufficient for you if the ruleset were simply disabled? This has the advantage that it will not be added again on accident.

**Comment by intchloe** [comment]
@fuglede Yes, that is fine. Thanks you.
