### ISSUE TITLE
Akamai breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#5621]
http://www.wsbtv.com/news/local/north-fulton-county/1-dead-in-attempted-robbery-at-buckhead-jewelry-store/389269261

Akamai breaks video.

Amazon Web Services also breaks the video. #4510

**Comment by ipatjolvur** [comment]
HTTPS-E v5.2.0
Firefox 47.0.1

The Akamai rule breaks ABC News videos.
http://abcnews.go.com/ThisWeek/video/win-election-held-today-41028489

**Comment by terrorist96** [comment]
http://decider.com/2016/09/18/jeb-bush-emmys-2016/

**Comment by terrorist96** [comment]
http://kuklaskorner.com/tmr/comments/quick-take-red-wings-blackhawks

**Comment by terrorist96** [comment]
No longer broken for me.
