### ISSUE TITLE
Squarespace.com and campaignzero

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#5622]
Website:
http://www.joincampaignzero.org/

Ruleset:
Squarespace.com (partial)

The campaign squares will not load unless the above ruleset is disabled.

**Comment by richardbank** [comment]
Same goes for http://thuisaandeamstel.nl/lookbook/, a squarespace site. Images do not load when https-everywhere is on.

**Comment by iangreenleaf** [comment]
Appreciate the upcoming workaround!

I get the feeling, though, that pages with storefronts are going to immediately fail with the same issue on `http://static.squarespace.com/universal/scripts-compressed/commerce-b93fa8a402a00d639e58-min.js`. And I'm not even sure if those are the only scripts or if there are more I don't know about.

Is there an underlying issue that needs to be addressed here?

Here's one more example page: http://www.metalandhoney.com/shop/ramen-lovers-club-enamel-pin

**Comment by jeremyn** [comment]
Reopening because of ongoing discussion.

**Comment by rafpaf** [comment]
The squarespace site laurakotevska.com does not load at all for me when https-everywhere is enabled.

**Comment by jeremyn** [comment]
The remaining problems in this issue are fixed by pull request https://github.com/EFForg/https-everywhere/pull/9155, which should be included in the next release.
