### ISSUE TITLE
expand options.redirectDepth

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#5632]
I do not understand the error in [this](https://travis-ci.org/EFForg/https-everywhere/jobs/144189564#L1519) context:
http://www.tkgorod.ru/ => https://www.tkgorod.ru/ => http://tkgorod.ru/ => https://tkgorod.ru/

I think this is still an acceptable process, so "options.redirectDepth" might be expanded.

**Comment by fuglede** [comment]
Maybe I don't understand the question, but redirecting http://www.tkgorod.ru/ => https://www.tkgorod.ru/ would give rise to a redirect loop, which the test should complain about;

    $ curl -Is https://www.tkgorod.ru/ | grep Location
    Location: http://www.tkgorod.ru/

**Comment by J0WI** [comment]
```
$ curl -LIs https://www.tkgorod.ru/ | grep Location
Location: http://www.tkgorod.ru/
Location: https://tkgorod.ru/
```
