### ISSUE TITLE
SourceForge ruleset causing endless redirect loop

### ISSUE THREAD

**Issue by thomaspurchas** [EFForg/https-everywhere#5637]
It looks like SourceForge rulesets is causing an endless redirect loop and preventing pages from ever loading.

**Comment by J0WI** [comment]
@thomaspurchas could you give an example?

**Comment by thomaspurchas** [comment]
I've been seeing this on any SourceForge page. https://sourceforge.net/#!/projects/ngnms/ is an example.

It seems that if the page loads completely once, then it's not obvious that the page is being reloaded, just the X/Refresh button flickers a little in Chrome.

**Comment by J0WI** [comment]
Oh yes, there is an evil JavaScript redirect.

**Comment by anewuser** [comment]
That has been fixed.

**Comment by jeremyn** [comment]
I can't reproduce the issue at https://sourceforge.net/#!/projects/ngnms/ . Closing issue, but @thomaspurchas please feel free to reopen the issue with a comment if you are still getting this problem.
