### ISSUE TITLE
forums.lanik.us bad performance

### ISSUE THREAD

**Issue by TheFinalCut83** [EFForg/https-everywhere#5651]
[https://forums.lanik.us](https://forums.lanik.us)
Firefox 48.0b7, HTTPS Everywhere 5.1.10.
Very bad responsiveness of these forums, I have to double-click the most of topics to read them because first click goes into an infinite load. Disabling "lanik.us" in HTTPS Everywhere solves the problem.

**Comment by jeremyn** [comment]
I can't reproduce this issue. Are you saying that if you visit, for example, http://forums.lanik.us/viewtopic.php?f=23&t=9041 , you get an infinite loop?

**Comment by TheFinalCut83** [comment]
Situation seems to be normal for now. Maybe it was a temporary glitch or problem on my side (or my ISP) Sorry, I forgot to close this issue.

**Comment by jeremyn** [comment]
That's fine, thanks.
