### ISSUE TITLE
[ruleset-bug] Can't connect to frys.com 

### ISSUE THREAD

**Issue by phillipremaker** [EFForg/https-everywhere#5653]
Connections to Frys.com with https everywhere yield ERR_CONNECTION_REFUSED.

Shouldn't Frys.com fall back to http?

**Comment by fuglede** [comment]
HTTPS Everywhere currently has no active rules for upgrading connections to frys.com; the only ruleset containing the main domain is [off by default](https://www.eff.org/https-everywhere/atlas/domains/frys.com-2.html). Perhaps you activated it on accident?

Closing as not an issue, but I can reopen if necessary.

**Comment by phillipremaker** [comment]
Looks like I may have accidentally turned on the rule, sorry. Turning it off fixed the issue. Not a bug, but Fry's needs to get their https on!!
