### ISSUE TITLE
OCSP Broken on some Wells Fargo sites

### ISSUE THREAD

**Issue by doug1** [EFForg/https-everywhere#566]
Version 4.0.0 in Firefox 24.8.0 shipped with CentOS 6.5
Some sites using the Wells Fargo CA such as healthbenefits.wellsfargo.com, wellsfargocommunity.com fail to load becuase OCSP server validator.wellsfargo.com is forced to upgrade to HTTPS, which it does not support.

**Comment by J0WI** [comment]
I think we can close this now.
