### ISSUE TITLE
Intermittent issue when using httpse via Optus mobile network

### ISSUE THREAD

**Issue by virtual812** [EFForg/https-everywhere#5712]
Have spent a great deal of time trying to pin this  down over the past week+

Intermittently, and usually more of then than not when i use some sites with https-everywhere enabled i get a massive reduction in speed.
Some sites effected...
xero.com
gmail.com
google.com (sometimes)
reddit.com
speedof.me (get a solid 30kbps here, where as on speedtest.net i get 35Mbps)

If i enable a proxy cache at my end the issue goes away.
If i disable http-e at my end the issue goes away.

I suspect something is happening to outbound requests that are upsetting a proxy or something at the ISP end.

Switching in my proxy must do something to rectify it.
Pictures attached.

No idea whom is at fault, be it http-e or something at the ISP end being upset by it.

Maybe someone here has a better idea of the inner workings and can form a better theory than I.
![speedof me_16-07-19 1-01pm google chrome browser proxy cache disabled](https://cloud.githubusercontent.com/assets/5173141/16938459/926e0bda-4dbb-11e6-92f8-5b88a6a25353.png)
![speedof me_16-07-19 12-55pm google chrome browser proxy cache enabled](https://cloud.githubusercontent.com/assets/5173141/16938463/95e08252-4dbb-11e6-80ef-669f25a38ace.png)

**Comment by J0WI** [comment]
Maybe your ISP does not respect net neutrality?

**Comment by virtual812** [comment]
I had all sorts of conspiracy theories before i worked it out.
The issue is intermittent, and i have a plausible theory as to why it is intermittent.
They are investigating and i'm confident it is a configuration error and not interntional.

I have a little enterprise networking experience, so take the following with a grain of salt, i am no expert, i have no knowledge of the Optus backend and this is just a theory, but here i go...

Facts:
- Issue only happens sometimes and not others, appears as if there is a session in the backend.
- Issue only happens with HTTPSeverywhere enabled
- Issue stops when running through a local proxy cache

Theory:
- Optus run several proxies, via load balancing.
- Some, and not all of the proxies have a problem with the changes HTTPSeverywhere makes to a request
- Load balancer puts user through a particular proxy that may differ per session
- When going through an unaffected proxy all is fine
- When going through an affected proxy the configuration error is causing snail speeds.

Opinion:
The issue lies at the Optus end, and is possibly effecting more users unknowingly.
This problem should not be happening and should be resolved.
Optus should follow this through.

After a call i took yesterday it does appear as if Optus are taking this seriously and i have been advised that i will be kept informed.

The promise to continue to keep me in the loop was re-affirmed even after me stating that i now have a working fixed connection and am no longer heavily reliant on the mobile data service.

The promise shows to me that they may believe something is wrong and accept that the issue may affect more than just myself.

I'd encourage anyone coming across this thread whom is in a position to do so the try to emulate my results.

Optus internet via tethered phone or mobile hotspot connected to a browser, not using a proxy, running the HTTPSeverywhere plugin, beware that it can take minutes/hours/days for the slowdown to appear, and the slowdown only appears on some websites (speedof.me is a good example).
If anyone replicates the issue, disable the plugin and re-test immediately.
- Post your findings.
- Would be great to see the issue replicated

Re net neutrality.
I don't think this situation specifically hints in any way a neutrality issue.
If the issue were consistent both time wise and with/without plugin then i'd be more suspicious.

Interesting neutrality is mentioned as it makes me think back to one lead i was chasing on this issue, the fact that since Android 4.4 Google has marked tethered packets differently to packets directly from the handset, thus allowing mobile providers a tool to treat traffic differently.
I'd be querying Googles reasons for this, as it provides a tool to providers to ruin neutrality.

**Comment by fuzzyroddis** [comment]
Are the requests to the speed tester being sent over HTTPS with HTTPSE and HTTP without it?

**Comment by virtual812** [comment]
That's correct.
With HTTPSE disabled the speed test sites use regular HTTP.
However the speed issue exists with other sits that _do_ use https even _without_ HTTPE enabled.
When HTTPE is disabled the problem disappears for all sites (the speed tests and xero.com and the others)

**Comment by pipboy96** [comment]
Can't be reproduced in any realistic way without being in the US and purchasing Optus subscription, issue is very old and most likely is gone by now.
