### ISSUE TITLE
Disable HTTPS on goaskalice.columbia.edu, which isn't covered by columbia.edu's SSL certificate

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#5714]
[goaskalice.columbia.edu](http://goaskalice.columbia.edu/) isn't covered by [columbia.edu](http://www.columbia.edu/)'s partial SSL certificate, so SSL should be disabled on that sub-domain.

**Comment by tomwys** [comment]
My Firefox dosn't complain about SSL, are you sure this problem is still valid?

**Comment by anonsubmitter** [comment]
Looks like they have expanded SSL coverage to that sub-domain now.
