### ISSUE TITLE
Error installing extension in chromium

### ISSUE THREAD

**Issue by KristobalJunta** [EFForg/https-everywhere#5715]
I run chromium on OpenSUSE Tumbleweed, and trying to install HTTPS Everywhere extension via Chrome web store resulted in an error saying
```
Package is invalid. Details: 'Could not load icon 'icons/icon-active-38.png' for browser action.'.
```

**Comment by NeatBeauty** [comment]
I'm seeing the same with Chrome 51.0.2704.106 on macOS 10.11

**Comment by KristobalJunta** [comment]
Oh, btw forgot to specify my Chromium version, it's 51.0.2704.103 (64-bit)

**Comment by Ricty** [comment]
I've also got this error with a note about "icons/icon-active-48.png".
Chrome 51.0.2704.106 m on Windows 10(10586)

**Comment by TErenberger** [comment]
Unpacking the .crx file shows that the ~/icons/ folder is empty. Adding icons manually resolves the issue. 

Looks like they were left out in a build/pack script?

**Comment by Hainish** [comment]
Thanks for this, working on it now

**Comment by Hainish** [comment]
An update has gone out and should be delivered to the Chrome Web Store pending Google approval

**Comment by Hainish** [comment]
Closing for now, please open a new issue if problems persist
