### ISSUE TITLE
Virus or False positive?

### ISSUE THREAD

**Issue by TheMaxwellsDemon** [EFForg/https-everywhere#5717]
I’ve tried to install extension from official website and then found this issue. I believe that it’s false positive, because all links are clear, according to reports received from VirusTotal. Besides, this anti-virus program... To be honest, I’ve never heard about it.

Results of URLs check:

https://www.eff.org/files/https-everywhere-chrome-2016.7.19.crx

https://www.virustotal.com/en/url/e183b102ce911d4ee63c1d2642798fcc51a5a40ec67972cc46bc29c02219447d/analysis/1468960850/

https://www.eff.org/files/https-everywhere-chrome-2016.7.18.crx

https://www.virustotal.com/en/url/b088d6a474b8bd9aea04175c482b4eb9f07145084310e8110cfcf6b39cfa72be/analysis/1468960914/

https://www.eff.org/files/https-everywhere-chrome-2016.6.9.crx

https://www.virustotal.com/en/url/e0f27ba1317a203b9b7beba4c7a7ed6d1803749d7c37056ef02071a964563f51/analysis/1468960947/

https://www.eff.org/files/https-everywhere-chrome-2016.5.10.crx

https://www.virustotal.com/en/url/f3d7d0dbf4c2357f736abb6173e686980b3f5434f915bf568e789eb265bf5ce3/analysis/1468961636/

Results of files check:

https-everywhere-chrome-2016.7.19.crx

https://www.virustotal.com/en/file/933232f1fe1b9e2a2ea258e2e1f1165da07f0f75bc3480e936c971c0b3ff89d3/analysis/1468960995/

https-everywhere-chrome-2016.7.18.crx

https://www.virustotal.com/en/file/113b86da574ef28fcedd8a6205ece984ba9dcbbc2bda9f341ed8c7c149445191/analysis/

https-everywhere-chrome-2016.6.9.crx

https://www.virustotal.com/en/file/3036ce962915deb7d6c1fea136b91803ff50237b96c547f7e1a8c9959df3e64a/analysis/

https-everywhere-chrome-2016.5.10.crx

https://www.virustotal.com/en/file/7963a45f526cd1f2ae0304fcf4110ab7ebc68c57893ca31f5b0abfaf16db3515/analysis/

**Comment by J0WI** [comment]
The hash sum of your files is not the same than the hash sum of EFF, so it seems that your files are corrupt.

**Comment by TheMaxwellsDemon** [comment]
Where can I find hash sum of original EFF files? Unfortunately, they are not presented on official webpage of the extension.

**Comment by J0WI** [comment]
Yes, it seems that they are only available for Firefox' versions. But that should be easy to fix.
@jsha @diracdeltas @Hainish

**Comment by Hainish** [comment]
The sha256sum results for the files posted above look accurate to me.  It looks like only one Antivirus out of 55 detect `virus.js.gen`.  I wouldn't worry about it too much, antivirus software has false positives all the time.  We may want to do a periodic scan of the files and see if the 1/55 figure increases at any point.  If it does, that may be cause for alarm.

Closing now
