### ISSUE TITLE
Can't install extension in Chrome

### ISSUE THREAD

**Issue by alexander-turner** [EFForg/https-everywhere#5718]
I get the error message

> Package incorrect. Détails : "Impossible de charger l'icône "icons/icon-active-38.png" d'action du navigateur."

This roughly translates to

> Invalid package. Details: "Impossible to load the icon "icons/icon-active-38.png" through the browser."

Help!

**Comment by MisterT87** [comment]
+1
same problem here

**Comment by gvarisco** [comment]
+1

**Comment by KommX** [comment]
This bug should now be fixed, see:
https://lists.eff.org/pipermail/https-everywhere/2016-July/002684.html

**Comment by MisterT87** [comment]
Yep, fixed. Now its working again :)
