### ISSUE TITLE
filecrypt.cc rule breaks click'n'load functionality

### ISSUE THREAD

**Issue by SimJoSt** [EFForg/https-everywhere#5727]
Filecrypt contains containers of links. The site contains the click'n'load functionality to automate transfering the containing links of the container to a download manager.
As this feature does not have https compatibility built in, it's broken through the use of https-everywhere.
Moreover the error message doesn't contain any information to what caused the problem and it took me some time to figure it out.

In the file https://github.com/EFForg/https-everywhere/blob/c2f8c67/src/chrome/content/rules/filecrypt.cc.xml an exclusion needs to be added.
Unfortunately I am not able to write it myself.

An example for a link, the click'n'load feature opens in a little popup, looks like this: http://filecrypt.cc/helper.html?1469099854883
The number is random and changes every time.

I will help anywhere I can.

**Comment by Bisaloo** [comment]
@SimJoSt, from what I understand, this was fixed by your edits in #5728. Is that right? If so, can you close this please?

**Comment by SimJoSt** [comment]
I didn't run into the problem again, so of course and thank you for the reminder.
