### ISSUE TITLE
The new logo is visually too loud

### ISSUE THREAD

**Issue by dredmorbius** [EFForg/https-everywhere#5737]
On Firefox/Android, I received an updated https-everywhere a few days ago, and was wondering what this big, bright, boxy, blue 'S' was.

I'll admit it's clearer than the previous abigram networky-wimy-wibbly thing.  But it's also kind of distracting -- I'm one of those types who really likes a distraction-free browsing environment.

Removing the dark 3-D border would help.  A paler blue and smaller 'S' perhaps as well.

A heads-up (splash screen or something) on the logo change would also have been helpful, as it wasn't clear immediately what the heck it was.

Apologies for being winy-pants on this, but it's an always-in-my-face annoyance.

Thanks.
![tmp_20623-2016-07-21 15 23 291455930100](https://cloud.githubusercontent.com/assets/5445858/17037550/1fb408ae-4f57-11e6-8cd9-8c1ee1ac3531.png)

**Comment by Meyermagic** [comment]
I'd say the "lock" icon is pretty strongly associated with HTTPS, used on pretty much every platform. Blue variant of something like this, perhaps?: https://design.google.com/icons/#ic_lock

**Comment by dylmye** [comment]
Slightly different, but my issue is that it's literally *too big*. It's 3x the size of the other icons on mine. I'm using "Simple White X" and it looks like this. 

![wtf-eff](https://cloud.githubusercontent.com/assets/7024578/17054222/ebec9138-4ffd-11e6-9ceb-5c8e59cd5bfc.png)

**Comment by J0WI** [comment]
There was released a new version recently. Please update and restart Firefox.

**Comment by dredmorbius** [comment]
Will try the restart, though that raises another question of whether or not it's HTTPS Everywhere that seems to cause Firefox/Android to lose its history on restart.

I have trouble keeping up with tabs (various FF issues, including slow performance & reload), and losing 100-300 at a go can be traumatic.  I'm just noting that here, if I happen to notice it again w/ HTTPS Everywhere updates, that might warrant notice.

**Comment by J0WI** [comment]
This sound like a new issue. Please open a new ticket with more details.
