### ISSUE TITLE
HE causing Firefox to die immediately on Firefox startup

### ISSUE THREAD

**Issue by dmadsen** [EFForg/https-everywhere#5772]
I don't have too much specific information and would welcome debugging suggestions for the following problem.

I've used HE for a long time and it's worked well for me.  All of a sudden, it started causing Firefox 47.0.1 to die immediately upon Firefox startup with resultant Firefox crash message.  Each time, Firefox crashed upon restart.  After a few times, Firefox offered to start in safe mode, which worked OK -- all tabs restored, etc, except that extensions were prevented from running.  I then manually disabled all extensions and restarted, enabling a few at a time and restarting to see if an extension caused the problem.  Since I'm posting this here, you know the results :-).

To verify it wasn't some compatibility issue between extensions (it shouldn't be, the browser environment has been unchanged for a while), I then disabled everything except HE.  Still caused failure, indicating that running HE causes the issue.

Since this isn't a widespread issue ("install HE and your browser dies"), I'm guessing that something changed in my Firefox installation/profile, but I don't know what -- and I haven't changed anything (famous last words, but it's true, I swear).

**Comment by Hainish** [comment]
@dmadsen strange.. perhaps it has to do with the tabs you have open?  Maybe one of them is triggering a rule that causes the HE crash?

**Comment by dmadsen** [comment]
That's an idea that I didn't think of...
I don't want to close those tabs or do a reset, because these tabs have
state that I don't want to lose.
Do you have any suggestions on how to chase this possibility?

What happened was that it was working and then the next time I started the
machine and opened Firefox, it didn't work.


On Sat, Jul 23, 2016 at 3:57 PM, William Budington <notifications@github.com

**Comment by Hainish** [comment]
What platform are you on?  On Linux (and this may work on OSX), you could copy your ~/.mozilla directory to ~/.mozilla-backup, then test with various tab configurations, and when your done remove ~/.mozilla and move ~/.mozilla-backup to ~/.mozilla ...

**Comment by dmadsen** [comment]
Unfortunately, Windows.  So you're suggesting then that I backup the
profile, fool around with it, and then restore it?  I'm willing to do that,
but I need to know that I can restore *everything* back.  Are there any
other places that Firefox makes changes on Windows that I'd need to care
about -- registry, other places in App Data, etc, etc?  It's been a few
years since I checked last on how to back up a Firefox profile; do you have
a favorite tool these days?

Do you think that looking at History might help?  As I mentioned, it was
stable until I opened it up one day.   Perhaps the latest couple tabs would
be the ones most likely to have caused a problem if it is one of the tabs.

Do you have any other guesses as to what it could be?  When Firefox dies,
does it write out anything (semi-)intelligible to a log somewhere that
maybe I can look at?  Something like "the whatchamacallit is broken which
is a fatal error"?

How often are the rulesets in HE updated?  If it is within a relatively
recent timeframe, that might be something, too, no?




On Sat, Jul 23, 2016 at 4:36 PM, William Budington <notifications@github.com

**Comment by Hainish** [comment]
I don't think Firefox stores anything about browser state in the windows registry, but I'm unsure of where the Firefox session data is stored in Windows.  Another possible debugging method is to open Firefox with the ProfileManager, install HTTPSE, then manually copy/paste the last few URLs you visited and see if any of these are the ones causing problems.

**Comment by dmadsen** [comment]
OK, thanks.  I don't know how to do that, but Google is my friend. :-)

On Wed, Jul 27, 2016 at 4:09 PM, William Budington <notifications@github.com

**Comment by Hainish** [comment]
oh I meant to post a link to it: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by dmadsen** [comment]
Golly, I knew there was a reason I liked you! :-)  Thanks!

On Wed, Jul 27, 2016 at 4:53 PM, William Budington <notifications@github.com

**Comment by jeremyn** [comment]
@dmadsen Is this still an active problem for you?

**Comment by dmadsen** [comment]
Because I've had other demands (looking for new job!), I've just left the
extension disabled for now.  I've never had good luck dealing with profiles
-- I tend to lose all the stuff I care about -- so it's an easy thing to
put off trying to deal with.

I'm guessing it would still be a problem unless it mysteriously has gone
away in the same way it arrived.  There has been a Firefox update since
then; is there any reason to believe that this may have changed anything?

**Comment by jeremyn** [comment]
Not that I know of. We just have a lot of open issues and it's good to identify the ones that are actionable. Right now the status of this issue is that you've reported it crashes Firefox, but it presumably works for most people so we need more information from you.

**Comment by dmadsen** [comment]
I documented the information and observed behavior in my first few messages
on this thread.  If there's any additional procedure / flags I need to use
to obtain data that would help determine what's happening, I'd be happy to
play along.

**Comment by jeremyn** [comment]
It would be helpful if you could narrow down what's causing the crash. Ideally you could reproduce it with a fresh profile using HTTPS Everywhere and the minimal tabs or other add-ons necessary to cause the crash.

**Comment by dmadsen** [comment]
Just as a SWAG, I'm thinking that a new profile will work just fine.
Remember, it just started happening one day.  There were no new tabs added.


How would you suggest that I do the testing while saving the old profile
and being able to go back to it?

**Comment by jeremyn** [comment]
You can use the profile manager that @Hainish discussed in [this earlier comment](https://github.com/EFForg/https-everywhere/issues/5772#issuecomment-235746220).

**Comment by dmadsen** [comment]
I saw that and was intending to check it out but I haven't -- yet.  Thanks
for the reminder, this weekend may be a good time to try it while I'm
eating a burger on Sunday and trying to be lazy on Monday.
[After all, what's the meaning of Labor Day if you can't sit around and nap
all day? :-)]

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
