### ISSUE TITLE
Remove locale string from link to Opera extension

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#5773]
The Opera link on https://www.eff.org/https-everywhere should point to `https://addons.opera.com/extensions/details/https-everywhere/`, without a locale string. That will redirect the user to the Opera addons website in their favorite language.

**Comment by J0WI** [comment]
@jsha @Hainish this need to be done on eff.org

**Comment by Hainish** [comment]
I've opened a ticket for our web team, and will close this when they fix it.

**Comment by Hainish** [comment]
Fixed on the site, closing.
