### ISSUE TITLE
Handling local duplicates better

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#5784]
If you work on rulefiles a lot like i do, you often have improved editions of already existing ruleset files in your User-Rules folder.
HTTPS-Everywhere should just load the local file and prefer it over the bundled file instead of complaining about duplicates in the console.

**Comment by jeremyn** [comment]
@numismatika Is the request here different from the request in issue #1291?

**Comment by numismatika** [comment]
@jeremyn not that much, i just focussed on the console spam.

**Comment by jeremyn** [comment]
In that case do you mind if I close this issue?

**Comment by numismatika** [comment]
fine with me

**Comment by jeremyn** [comment]
Thanks.
