### ISSUE TITLE
"nsICookieManager.remove()" has been changed, passing of correct originAttributes is now needed

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [EFForg/https-everywhere#5791]
I am running Ubuntu GNOME 16.04 with GNOME 3.20, Firefox 47 and the latest stable version of HTTPS Everywhere made available. I was looking through my Firefox log today and found this message which I thought I should report:

![https-everywhere_update_code_firefox_message](https://cloud.githubusercontent.com/assets/11575271/17085163/a4b71d38-51c9-11e6-899a-427b9d80c1b8.png)

**Comment by Vednier** [comment]
If you can turn off signing verification, then changing lines 164 and 165 from
`cookieManager.remove(c.host, c.name, c.path, false);
      cookieManager.add(c.host, c.path, c.name, c.value, true, c.isHTTPOnly, c.isSession, expiry);`
to 
`cookieManager.remove(c.host, c.name, c.path, false, c.originAttributes);
      cookieManager.add(c.host, c.path, c.name, c.value, true, c.isHTTPOnly, c.isSession, expiry, c.originAttributes);`
in https-everywhere-eff@eff.org/chrome/content/code/HTTPS.js will solve your problem

**Comment by salty-horse** [comment]
Do you have an example website that triggers the warning? I assume it only shows up when a website serves cookies over HTTP...?

**Comment by SeventhSonOfASeventhSon** [comment]
@salty-horse, Seemingly whenever I am in one of the chat rooms on the following site: https://chat.stackexchange.com/

**Comment by rugk** [comment]
I think the site does not matter. Also on GitHub I can reproduce this error.

These errors spam my browser console:
```
"nsICookieManager.remove()" wurde verändert. Aktualisieren Sie Ihren Code und übergeben Sie die korrekten originAttributes. Lesen Sie mehr auf MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManagerHTTPS.js:164:6
"nsICookieManager2.add()" wurde verändert. Aktualisieren Sie Ihren Code und übergeben Sie die korrekten originAttributes. Lesen Sie mehr auf MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2HTTPS.js:165:6
Allowing request to domain NOT in the block-list.(unbekannt)
"nsICookieManager.remove()" wurde verändert. Aktualisieren Sie Ihren Code und übergeben Sie die korrekten originAttributes. Lesen Sie mehr auf MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManagerHTTPS.js:164:6
"nsICookieManager2.add()" wurde verändert. Aktualisieren Sie Ihren Code und übergeben Sie die korrekten originAttributes. Lesen Sie mehr auf MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2HTTPS.js:165:6
```

The errors point to [this file](https://github.com/EFForg/https-everywhere/blob/cecfd3b30df4d72873d19feb53bcd9ad2e7f2e00/src/chrome/content/code/HTTPS.js#L165).

**Comment by salty-horse** [comment]
Can't reproduce it consistently. I only got the errors once while refreshing this page. :(

**Comment by wbt** [comment]
Buzzfeed makes the errors go nuts.  Check out https://www.buzzfeed.com/danvergano/trump-on-nukes or https://www.buzzfeed.com/williamalden/a-tech-mogul-said-hed-push-for-california-to-secede-if-trump to see if you can reproduce it there.   There are two errors that alternate back and forth (so it doesn't accumulate with the red number):

> HTTPS.js:165:6:
> “nsICookieManager2.add()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager2

> HTTPS.js:164:6:
> “nsICookieManager.remove()” is changed. Update your code and pass the correct originAttributes. Read more on MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManager

**Comment by Vednier** [comment]
Same here, gettin a lot of warnings on https://www.buzzfeed.com/danvergano/trump-on-nukes, can confirm.

**Comment by Forkest** [comment]
It actively spams the browser console, very annoying. Could somebody merge that PR please?
