### ISSUE TITLE
Archive.is redirecting HTTPS to HTTP

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#5805]
It seems archive.is has started redirecting HTTPS requests to HTTP (with an annoying 10-second delay). For example: https://archive.is/2VUZ (though I can't consistently reproduce this 100% of the time). Not sure how to disable a rule (just comment it out, or something else?) so I'm just opening an issue.

**Comment by fuglede** [comment]
I tried refreshing and waiting for 10 seconds quite a few times in both Firefox and Chromium and did not manage to reproduce the issue.

What goes wrong with respect to HTTPS Everywhere -- if the site provided a single redirect, I would expect it to simple re-secure the connection (with an additional redirect).

**Comment by nyuszika7h** [comment]
Sorry, I forgot to mention that when it happens, it just shows a white page saying "redirecting to http://archive.is/2VUZ in 10 seconds", and when that elapses, HTTPS Everywhere redirects back to HTTPS and it starts over...

**Comment by nyuszika7h** [comment]
OK, it seems it only does this if the referrer is Wikipedia (telling RefControl to forge it as `https://en.wikipedia.org/` works).

**Comment by nyuszika7h** [comment]
Or maybe not, it may be some weird A/B testing. After disabling the referrer spoofing I still got redirected a few times and then it stopped, and now different message: "Redirecting to https://archive.today/2VUZ in 10 seconds".

**Comment by fuglede** [comment]
Yeah, I see what you are saying:

	$ curl -I http://archive.is/test
	HTTP/1.1 200 OK
	Refresh: 12;url=http://archive.today/test

	$ curl -I http://archive.today/test
	HTTP/1.1 302 Found
	Location: //archive.is/test

Now I'm wondering why Firefox isn't picking this up.

**Comment by fuglede** [comment]
And it is pretty random indeed;

	$ curl -Is https://archive.is/2VUZ | grep Refresh
	$ curl -Is https://archive.is/2VUZ | grep Refresh
	Refresh: 12;url=https://archive.today/2VUZ

**Comment by anewuser** [comment]
Please report this to the owner of Archive.is instead of disabling the rule for everyone who isn't affected by it.

**Comment by fuglede** [comment]
I contacted the webmaster of the site, and it seems that the behaviour above is due to a bot request throttling mechanism (which could also explain why I was only able to reproduce after testing for a while).
