### ISSUE TITLE
Please add Meetrics GmbH

### ISSUE THREAD

**Issue by rid007** [EFForg/https-everywhere#5815]
This Origination have wild card SSL Certificate
 *.meetrics.de ; *.meetrics.net ; *.research.de.com

**Comment by jeremyn** [comment]
We already have a ruleset for Meetrics, see [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Meetrics.xml). What are some URLs that the add-on doesn't cover that you want it to cover?
