### ISSUE TITLE
hotpepper.jp

### ISSUE THREAD

**Issue by luixxiul** [EFForg/https-everywhere#5823]

**Comment by fuglede** [comment]
Hi @luixxiul. Thanks for your contributions! I note that all of your issues come with their own fixing commits. Can you submit those as pull requests instead? That makes it a lot easier to review and include the changes.

**Comment by luixxiul** [comment]
Hi @fuglede, actually there are ones already: https://github.com/EFForg/https-everywhere/pulls/luixxiul

From next time I will send just a PR. thanks

**Comment by fuglede** [comment]
Ah sorry; I had missed those -- thanks!

**Comment by jeremyn** [comment]
I'm closing this issue as a duplicate of pull request #5814.
