### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by rnc** [EFForg/https-everywhere#5828]
Using Firefox 47.0.1 on Fedora 24 with HTTPSEverywhere 5.2.0.

The new icon is far too big and doesn't scale correctly (for that matter I thought the older icon was better but thats personal preference).

For example:

![httpseverywhere](https://cloud.githubusercontent.com/assets/1169793/17212137/7358a848-54c5-11e6-9e29-e0df9ff05083.jpg)

**Comment by Hainish** [comment]
@rnc You'll have to download the newest version (5.2.1) to get rid of that icon bug: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/
