### ISSUE TITLE
Add ca-girlstalk.jp

### ISSUE THREAD

**Issue by luixxiul** [EFForg/https-everywhere#5839]

**Comment by luixxiul** [comment]
I get mixed content warnings because of ``http://stat100.ameba.jp``, which however should be redirected to https [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Ameba.xml#L35). Not sure why?

**Comment by luixxiul** [comment]
This too: https://official.ameba.jp/

**Comment by luixxiul** [comment]
By the way if I directly get the blocked resource from URL bar, they are redirected to https.

**Comment by jbrowngithubuser** [comment]
Chrome and Firefox block active mixed content before HTTPS-Everywhere has a chance to rewrite the URLS to https://

See https://www.eff.org/https-everywhere/rulesets

> Mixed Content Blocking (MCB)
> 
> Some rulesets may trigger active mixed content (i.e. scripts loaded over HTTP instead of HTTPS). This type of mixed content is blocked in both Chrome and Firefox, before HTTPS Everywhere has a chance to rewrite the URLs to an HTTPS version. This generally breaks the site. However, the Tor Browser doesn't block mixed content, in order to allow HTTPS Everywhere to try and rewrite the URLs to an HTTPS version.
> 
> To enable a rule only on platforms that allow mixed content (currently only the Tor Browser), you can add a platform="mixedcontent" attribute to the ruleset element.
