### ISSUE TITLE
Only do fetch test for ruleset changing PRs

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#5844]
As mentioned in https://github.com/EFForg/https-everywhere/pull/5626#issuecomment-235990461, it would make sense to change our Travis setup so that only the fetch tests are carried out for a given PR containing only ruleset changes, the main benefit being a dramatic decrease in Travis test durations.

**Comment by fuglede** [comment]
One could probably come up with different viable approaches to this, but one that should would be to simply imitate the logic from [the existing Travis fetch test](https://github.com/EFForg/https-everywhere/blob/master/test/travis-ruleset-fetch.sh#L20), in which the difference from `upstream/master` is recorded.

**Comment by J0WI** [comment]
`check_rules.py` should also be runned.

**Comment by fuglede** [comment]
Yep, good point!
