### ISSUE TITLE
HTTPS Everywhere Atlas is double escaping output

### ISSUE THREAD

**Issue by fuzzyroddis** [EFForg/https-everywhere#585]
eg. https://www.eff.org/https-everywhere/atlas/domains/php.net.html

```html
&amp;#185; Secured by us
&amp;#178; Not secured by us &lt;= domain not covered
```

The output should look like:
```
¹ Secured by us
² Not secured by us <= domain not covered
```
but instead shows:
```
&#185; Secured by us
&#178; Not secured by us <= domain not covered
```

**Comment by J0WI** [comment]
@Hainish another bug on the website

**Comment by Hainish** [comment]
This seems to be an outdated issue - the example given no longer displays the double-escape, and I haven't encountered this issue.  Closing.

**Comment by J0WI** [comment]
I can still reproduce

**Comment by Hainish** [comment]
@J0WI, link?

**Comment by J0WI** [comment]
The above still works. Atlas doesn't show the superscript chars.

**Comment by Hainish** [comment]
I wonder if this is a difference of default encoding? What is the encoding you're viewing it in?

On July 28, 2016 9:19:31 PM EDT, J0WI <notifications@github.com> wrote:
>The above still works. Atlas doesn't show the superscript chars.
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/issues/585#issuecomment-236070528

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fuzzyroddis** [comment]
@Hainish Why browser did you try?
The source code has for example `- doc &amp;#185;` in it using Chrome and curl.

**Comment by Hainish** [comment]
Ah, I don't see it in the same place as in the issue, but I do see it now.  I'll work to fix this next week

**Comment by Hainish** [comment]
This is fixed now, as of https://github.com/EFForg/https-everywhere-atlas/commit/a6d2db125c230e8dbb1e34ddd5bd6de95fe3a65e
