### ISSUE TITLE
new symbol is using up to much space of iceweasel

### ISSUE THREAD

**Issue by treaki** [EFForg/https-everywhere#5891]
hi,

i have the problem that the new symbol is displayed to big. All other simbols are displayed small (about 16x16) pixes but the new https everywhere symbol is using up about 40x40 px of space. While doing that the high of the bar in iceweasel has increased very much which is stealing usefull space.

its iceweasel 31.2.0 running here.

please fix that so that the new symbol is also correctly displayed within iceweasel

**Comment by fuglede** [comment]
Thanks for the report; this issue was fixed in 5.2.1. See #5719.
