### ISSUE TITLE
Jquery ruleset breaks weather radar on idokep.hu

### ISSUE THREAD

**Issue by Diazonium** [EFForg/https-everywhere#5892]
This website uses jquery for implementing a weather radar: http://www.idokep.hu/radar
If the jquery ruleset is enabled, the weather radar is not displayed correctly. Some other weather maps on this site are also affected.

**Comment by jeremyn** [comment]
@fuglede @J0WI I'm trying to understand CORS. When you load the URL given in the issue description with HTTPS Everywhere active, the Firefox web console reports

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://code.jquery.com/jquery-3.1.0.min.js. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

If I look at the headers for the jQuery response, I see that it does in fact have `Access-Control-Allow-Origin: *`. Looking at issue `https://github.com/EFForg/https-everywhere/issues/49` (I broke the link in case I'm wrong in thinking it applies here), there's a behavior problem with HTTPS Everywhere where the browser tries to check the jQuery response to verify the header, but the add-on rewrites the request to https, so the file the browser expects never loads, so the JS functionality is broken.

Do I understand the problem correctly? Should we add the CORS-bugs label to this issue?

**Comment by HTTPSNowhere** [comment]
@jeremyn Tested it again and I didn't notice any issue, should this be closed then?
