### ISSUE TITLE
a248.e.akamai.net

### ISSUE THREAD

**Issue by luixxiul** [EFForg/https-everywhere#6007]
This is likely to be a new pattern: 
https://a248.e.akamai.net/f/248/45380/10m/dac1.download.akamai.com/45379/rsi/ut/a_62_780.js

**Comment by jeremyn** [comment]
I'm not sure what you're asking for. Could you please be more specific?

**Comment by gloomy-ghost** [comment]
Oops, sorry for flooding commits
