### ISSUE TITLE
Conflict with 'Smile Always' Chrome extension.

### ISSUE THREAD

**Issue by sircod** [EFForg/https-everywhere#6034]
Smile Always is a chrome extension that redirects amazon.com links to smile.amazon.com. Recently HTTPS Everywhere has started to conflict with it and prevent it from working. Getting this message from Smile Always:

Warning:
This extension failed to redirect a network request to http://smile.amazon.com/dp/<LINK> because another extension (HTTPS Everywhere) redirected it to https://www.amazon.com/dp/<LINK>.

Was using Chrome 52 beta (64-bit) when it started, now using Chrome 53 beta (64-bit).

**Comment by fuglede** [comment]
Can't they just redirect from the page after it's loaded on HTTPS? It sounds like they would want to that in  any case.

**Comment by alanhoyle** [comment]
It appears that https-everywhere might not be required for Amazon anymore.  When I go to "http://amazon.com" it is rewriting the URL to "https://amazon.com" without the extension enabled.      I haven't checked universally, but I checked five different amazon links on a couple of different browsers and they all seem to switch without the extension.

**Comment by fuglede** [comment]
@alanhoyle: This is in fact the case for many of the rulesets included in HTTPS Everywhere. They will generally be kept in the database as they do protect the user from MITMing for the initial request to http://amazon.com, prior to the server's own upgrade (which is also why we generally like HSTS).

**Comment by sircod** [comment]
@alanhoyle Yeah, I am seeing the same thing, but as @fuglede said, it's best for the redirect to happen immediately. 

I am not sure there is an easy fix for this, and it seems more like an issue for Chrome.

**Comment by diego898** [comment]
I am seeing this as well - so for right now just ignore it? And just to be sure, this would be an issue not with https everywhere or smile always, but with chrome?

**Comment by fuglede** [comment]
@diego898: You can't really blame the race condition on either extension (or Chrome), but as mentioned above, I think the easiest fix would be for the other extension to also redirect from HTTPS (i.e. after HTTPS Everywhere has done its work).

**Comment by bbodenmiller** [comment]
@fuglede there is an issue at https://github.com/Jdhaimson/smilealways/issues/27 open for this. How can we wait for HTTPS Everywhere to do its redirect and then do the Smile Always logic?

**Comment by fuglede** [comment]
@bbodenmiller: It looks like the same suggestion as above is also in the smilealways thread: So, HTTPS Everywhere translates the HTTP request to a HTTPS one, but it does not do anything to the HTTPS request. That is, if you navigate to https://www.amazon.com/dp/, HTTPS Everywhere will not do anything. Therefore, as I see it, the other add-in could simply make sure to redirect the HTTPS link to what it wants. So, HTTPS Everywhere rewrites the vanilla Amazon request from HTTP to HTTPS, and the other add-in rewrites the vanilla HTTPS request to a smile HTTPS request.

**Comment by asmeurer** [comment]
Similar issue with https://github.com/jparise/chrome-utm-stripper.

**Comment by mueller-ma** [comment]
You could remove the Smile addon and add a custom rule to https everywhere to redirect to smile.amazon.com.

**Comment by pipboy96** [comment]
Extension no longer seems to be developed anymore.
