### ISSUE TITLE
OpenStreetMap editing using Potlatch 2 broken by GitHub rule

### ISSUE THREAD

**Issue by jonpsp** [EFForg/https-everywhere#6042]
Using HTTPS Everywhere on Firefox 47.0.1 on Windows 10, if I try to edit a map on OpenStreetMap.org using Potlatch 2, no backgrounds are listed in the Background menu, and there is no background for the map.  If I disable the "GitHub Pages" rule in HTTPS Everywhere, background maps are listed in the Background menu and I can see the currently selected background map in the background.
e.g. https://www.openstreetmap.org/edit?editor=potlatch2#map=21/51.55052/-0.14060

**Comment by pipboy96** [comment]
Not reproducible without account.
