### ISSUE TITLE
Cloudfront rule prevents some fonts from loading

### ISSUE THREAD

**Issue by Jonathan-Eyler-Werve** [EFForg/https-everywhere#6047]
On [this site](http://sproutsocial.com/features/social-media-publishing) ( and, one assumes, some others ), the font `proxima-nova` does not load when the HTTPSEverywhere Cloudfront.net rule is active. The error can be toggled by activating and deactivating this rule. 

Detected while running Chrome, build 51.0.2704.103 on OSX. 
I'm using the WhatFont extension which may speed your debugging. 

![screen shot 2016-08-02 at 3 33 10 pm](https://cloud.githubusercontent.com/assets/4624190/17345059/fbffb0da-58c9-11e6-9aaf-908646db46fe.png)

**Comment by Bisaloo** [comment]
This issue was fixed when sproutsocial.com switched to HTTPS by default. @Jonathan-Eyler-Werve, can you confirm you no longer see this issue and if so, close this issue?

**Comment by J0WI** [comment]
Closing due the lack of response.
