### ISSUE TITLE
The new logo is awful

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#6058]
1 It is meaningless. What doe "s in a blue square" mean? It can mean anything, such as "square" or "south".
2 It is too bright.
3 It is neither flat nor 3d, it is just a cube, which  breaks flatness of the toolbar.

So even the old logo is much better than this one.

**Comment by Foorack** [comment]
I like the new logo. I think it looks more modern than the old one.

Everyone have different opinions but looking at it realistically I think there is little to no chance they will switch back, unless a major reason to do so comes up which I find highly unlikely.

**Comment by zneaa** [comment]
I agree with @Foorack

**Comment by jeremyn** [comment]
I'm closing this issue because there is no active discussion and nothing specific to do.
