### ISSUE TITLE
Firefox 47 on Linux still has the old logo

### ISSUE THREAD

**Issue by forteller** [EFForg/https-everywhere#6065]
At least for me. I use Ubuntu Gnome 16.04, Firefox 47.0 and HTTPS-Everywhere 5.2.1

**Comment by fuglede** [comment]
Cruious Firefox 47.0.1 on Debian here, and I have the new logo.

**Comment by forteller** [comment]
Hmm… After updating to Fx 48 I have the new logo too, so I guess everything is ok :)

**Comment by fuglede** [comment]
It would have been nice to understand the cause of course; I guess we'll see if more reports come in. Do you want to close this?

**Comment by Hainish** [comment]
I'm guessing this was just due to the extension not having been upgraded, I'm closing but feel free to open a new issue if you can reproduce.
