### ISSUE TITLE
Is the name HTTPS-Everywhere or HTTPS Everywhere?

### ISSUE THREAD

**Issue by forteller** [EFForg/https-everywhere#6066]
On the website and here on GitHub it says HTTPS Everywhere, but on my list of installed extensions it says HTTPPS-Everywhere
![screenshot from 2016-08-03 22-33-13](https://cloud.githubusercontent.com/assets/343561/17381031/4d11153a-59ca-11e6-81c6-bb13360c2f1e.png)

**Comment by fuglede** [comment]
The dash appears to only appear in very few places. I removed them in #6081.
