### ISSUE TITLE
Images do not load on prnt.sc

### ISSUE THREAD

**Issue by d1g1t** [EFForg/https-everywhere#6074]
It appears the page tries to load the image via HTTP which causes firefox to block the content.

The subdomain hosting the images does not appear to be load on https even though they seem to be using cloudflare (shows an Error 521 at this time)

Example page: https://prnt.sc/c1okcg

**Comment by fuglede** [comment]
Thanks for the report. It looks like there is not all that much to do about it, since the server hosting the image does not itself support HTTPS properly at the moment. The ruleset is disabled in #6110.
