### ISSUE TITLE
Design slightly broken on install

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#6078]
When installing on Firefox 48/Windows 8/Danish locale, the Observatory prompt window is too small for its contents, and the logo looks stretched.

![designbreakage](https://cloud.githubusercontent.com/assets/6169306/17446797/51c315ba-5b4b-11e6-9f5f-d5b7942d0170.png)

**Comment by jeremyn** [comment]
I remember seeing the cut-off at the bottom on the `en-US` locale too.

**Comment by J0WI** [comment]
I would prefer a tab instead of a popup, then we can also get rid of static window sizes...

**Comment by Hainish** [comment]
@J0WI this should all be superseded when we move to WebExtensions anyway.  I consider this a hotfix, and when we code the UI for the observatory within WebExtensions I'll make sure it's a tab.
