### ISSUE TITLE
HTTPS everywhere causing issues when loging in on www.tsp.gov

### ISSUE THREAD

**Issue by L36** [EFForg/https-everywhere#6086]
When logging in on tsp.gov, you are greeted with an error message that reads the following:

> Response Error
> 
> Null Response or Return Code. This information was not found in the header of the response. You may need to add it to your response to allow accurate request tracking in the proxy audit log.

Using FF 49 stable, disabled all my other addons. Only when HTTPS everywhere is enabled I get this error.

**Comment by pipboy96** [comment]
Can't reproduce without account.
