### ISSUE TITLE
Rulesets issue : Gallery pictures/videos do not load on NSFW pornfuncams.com

### ISSUE THREAD

**Issue by ttitsCDN** [EFForg/https-everywhere#6104]
Go for instance to the page
http://www.pornfuncams.com/fr/chat/AliceEnchanted
(flash plugin necessary)
and click on the "Show gallery" icon on the left side menu. Pictures and videos do not load, and in no other room either.
Now in the https-everywhere menu click on the dark green "dditscdn.com" to turn the rule to grey, now pictures and videos do load.
I suspect that only the https forcing for gallery.dditscdn.com causes the problem and should be turned into an exception, the other dditscdn.com subdomains can probably stay in https, although i could not test this hypothesis.

**Comment by pipboy96** [comment]
Can no longer reproduce.
