### ISSUE TITLE
https-everywhere causing issues on Amazon India website while updating zipcode. 

### ISSUE THREAD

**Issue by Rocky-Github** [EFForg/https-everywhere#6157]
On the Amazon India website selecting a new delivery location (entering a new pin code (zipcode) and clicking update) on the product page throws an error message !!
![bug-1292467](https://cloud.githubusercontent.com/assets/20929060/17520443/645326b4-5e6d-11e6-873e-c4c49a5949ba.png)

1.Go to http://amazon.in on any Laptop or PC.
2.Search and select any product to buy.
3.Click "**Select a delivery address**" below "**Deliver to**:" label on the RHS.
4.A pop form is displayed with the option of signing in or just enter the PINCODE (Zipcode).
5.Enter any valid 6 digits PINCODE in India (Example : 560078, 440018)
6.Click update
**Actual response**: An error message is displayed: : "Please enter a valid 6 digit PINCODE !!

**Expected Response**:
The form should update the delivery address and display the delivery time for the entered new address (PINCODE).

This issue is not happening without the https-everywhere addon.
Firefox version : 48

**Comment by J0WI** [comment]
It's likely because of the ajax request to `http://www.amazon.in/gp/delivery/ajax/address-change.html`

**Comment by rajatkhare619** [comment]
I also have the same issue. Using Chrome.

**Comment by J0WI** [comment]
Let me ping @jeremyn or @Hainish to have a look at https://github.com/EFForg/https-everywhere/pull/7419
