### ISSUE TITLE
5.2.1 icon takes up xtra space

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#6163]
icon seems to include extra space on its right hand side. see screenshot

win10, ff dev.

![https everywhere 5 2 1](https://cloud.githubusercontent.com/assets/347010/17522300/5c346446-5e0b-11e6-9988-731d9c6117b4.PNG)

**Comment by Hainish** [comment]
@jzhu I haven't seen this anywhere else, can you confirm that this happens even when you move HTTPS Everywhere to the left of Privacy Badger?

**Comment by jzhu** [comment]
yes, still happens





On Aug 09, 2016, at 12:55 PM, William Budington <notifications@github.com> wrote:



@jzhu I haven't seen this anywhere else, can you confirm that this happens even when you move HTTPS Everywhere to the left of Privacy Badger?

**Comment by nywilds** [comment]
I have this problem too. I think it might be leftover space from when the button used to have a down arrow. Here's what it looks like when it's selected (on a blank profile in Firefox 48):

![firefox https everywhere](https://cloud.githubusercontent.com/assets/19141554/17539557/43687bee-5e6c-11e6-9761-4189f0258c88.png)

**Comment by jzhu** [comment]
interestingly it doesn't happen with ff dev on macOS 10.11. i only see it on windows.

**Comment by fuglede** [comment]
Yeah, I can confirm, this is an old issue from back when the arrow was removed; https://github.com/EFForg/https-everywhere/pull/3876#issuecomment-192885898. If the add-on is ported to WebExtensions, this should fix itself.

**Comment by Hainish** [comment]
I'm curious: does uninstalling and reinstalling the extension resolve this?

**Comment by Hainish** [comment]
(another way of asking if it's just an artifact from continually upgrading since the arrow days)

**Comment by fuglede** [comment]
I recently (as in, last week) installed it on a fresh Windows box and had the same issue there, so it would not seem so.

**Comment by jzhu** [comment]
@Hainish, just uninstalled and installed again from eff site. not resolved.

**Comment by pipboy96** [comment]
Issue no longer exists since it is specific to extremely old versions of browser and extension.
