### ISSUE TITLE
Foolz.us no longer supports HTTPS, remove/disable the ruleset

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#6171]
[Foolz.us](http://www.foolz.us/) no longer supports HTTPS, so the ruleset should either be removed or disabled for the site to be accessible.

**Comment by fuglede** [comment]
It looks like HTTPS is still supported but the site is misconfigured (including it serving a bad certificate and serving bad TLS).

	$ diff <(curl -ks https://www.foolz.us) <(curl -ks http://www.foolz.us)
	7c7
	<         <link href="https://www.foolz.us/assets/bootstrap2/css/bootstrap.min.css?v=0.5.2" rel="stylesheet" type="text/css" />        <link href="https://www.foolz.us/assets/fontawesome/css/font-awesome.css?v=0.5.2" rel="stylesheet" type="text/css" />        <link href="https://www.foolz.us/assets/theme/style.css?v=0.5.2" rel="stylesheet" type="text/css" />
	---
	>         <link href="http://www.foolz.us/assets/bootstrap2/css/bootstrap.min.css?v=0.5.2" rel="stylesheet" type="text/css" />        <link href="http://www.foolz.us/assets/fontawesome/css/font-awesome.css?v=0.5.2" rel="stylesheet" type="text/css" />        <link href="http://www.foolz.us/assets/theme/style.css?v=0.5.2" rel="stylesheet" type="text/css" />
	17c17
	<                 <a class="brand" href="https://www.foolz.us/">Foolz</a>
	---
	>                 <a class="brand" href="http://www.foolz.us/">Foolz</a>
	52,53c52,53
	<             <a class="btn btn-info" href="https://www.foolz.us/docs/foolfuuka"><i class="icon-book"></i> Docs</a>
	<             <a class="btn" href="https://www.foolz.us/info/foolfuuka"><i class="icon-info-sign"></i> Info</a>
	---
	>             <a class="btn btn-info" href="http://www.foolz.us/docs/foolfuuka"><i class="icon-book"></i> Docs</a>
	>             <a class="btn" href="http://www.foolz.us/info/foolfuuka"><i class="icon-info-sign"></i> Info</a>
	68,69c68,69
	<             <a class="btn btn-info" href="https://www.foolz.us/docs/foolslide"><i class="icon-book"></i> Docs</a>
	<             <a class="btn" href="https://www.foolz.us/info/foolslide"><i class="icon-info-sign"></i> Info</a>
	---
	>             <a class="btn btn-info" href="http://www.foolz.us/docs/foolslide"><i class="icon-book"></i> Docs</a>
	>             <a class="btn" href="http://www.foolz.us/info/foolslide"><i class="icon-info-sign"></i> Info</a>
	84,85c84,85
	<             <a class="btn btn-info" href="https://www.foolz.us/docs/foolslide2"><i class="icon-book"></i> Docs</a>
	<             <a class="btn" href="https://www.foolz.us/info/foolslide2"><i class="icon-info-sign"></i> Info</a>
	---
	>             <a class="btn btn-info" href="http://www.foolz.us/docs/foolslide2"><i class="icon-book"></i> Docs</a>
	>             <a class="btn" href="http://www.foolz.us/info/foolslide2"><i class="icon-info-sign"></i> Info</a>
	190,191c190,191
	<     <script>window.jQuery || document.write('<script src="https://www.foolz.us/assets/js/jquery.js"><\/script>')</script>
	<     <script defer src="https://www.foolz.us/assets/bootstrap2/js/bootstrap.min.js?v=0.5.2"></script>
	---
	>     <script>window.jQuery || document.write('<script src="http://www.foolz.us/assets/js/jquery.js"><\/script>')</script>
	>     <script defer src="http://www.foolz.us/assets/bootstrap2/js/bootstrap.min.js?v=0.5.2"></script>

That being said, you're right, we should not secure that connection.
