### ISSUE TITLE
Kinja-static.com ruleset breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6194]
http://deadspin.com/lebron-carmelo-wade-cp3-open-espys-with-statement-on-1783626133

Kinja-static.com breaks the video.
JW Platform.com (partial) also breaks the video. #5086

**Comment by Bisaloo** [comment]
@terrorist96, this seems fixed. I'm guessing it was a CORS issue that resolved itself when deadspin.com switched to https.

Tested with https://deadspin.com/the-winter-olympics-feature-2-951-of-the-world-s-greate-1823138678

Can you confirm?

**Comment by terrorist96** [comment]
Confirmed
