### ISSUE TITLE
sina.com.cn rule disables Weibo's login redirection

### ISSUE THREAD

**Issue by MagaFun** [EFForg/https-everywhere#6227]
So I have enabled HTTPS everywhere during a  Weibo login, I enter "weibo.com" into the browser and it redirects me to "https://login.sina.com.cn/", and then nothing happens. When I disable "sina.com.cn (partial)", I am able to login and being redirect to "weibo.com".

**Comment by MagaFun** [comment]
#5106 Same issue.

**Comment by J0WI** [comment]
closed by #6765
