### ISSUE TITLE
OpenStreetMap editing using Potlatch 2 does not show Bing Aerial Imagery background

### ISSUE THREAD

**Issue by jonpsp** [EFForg/https-everywhere#6233]
Using HTTPS Everywhere on Firefox 47.0.1 on Windows 10, if I try to edit a map on OpenStreetMap.org using Potlatch 2, if I select "Bing Aerial Imagery" in "Background", no background is shown (the background remains white).  If I disable the "VirtualEarth.net" rule in HTTPS Everywhere, I can see the Bing background images (i.e. aerial photography).
e.g. https://www.openstreetmap.org/edit?editor=potlatch2&changeset=41292838#map=18/51.51466/-0.14107 then select "Bing Aerial Imagery" under "Background"

**Comment by pipboy96** [comment]
Can't reproduce without account.
