### ISSUE TITLE
Firefox android: "Would you like to turn HTTPS Everywhere off" has only "no" as answer

### ISSUE THREAD

**Issue by tdelmas** [EFForg/https-everywhere#6239]
When opening the three-dot menu of Firefox, click on "HTTPS Everywhere (on)" a popup appears with that question, and only one possible answer. Looks like a bug or terrible UX?

**Comment by renyouguo** [comment]
+1

**Comment by fuglede** [comment]
Thanks for the report. This is a duplicate of https://github.com/EFForg/https-everywhere/issues/3029

**Comment by tdelmas** [comment]
Yes, you're right, sorry :)

**Comment by fuglede** [comment]
No problem; it's better to have too many reports than too few.
