### ISSUE TITLE
Certificate verification failed in fetch-test.sh for https://megabusgold.com

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#6275]
Sites https://megabusgold.com and https://www.megabusgold.com, added with commit 9acece46af4b07fa203a290de86f629622402633, cause the following error from `fetch-test.sh`:

Fedora 24:

```
ERROR rules/Megabus.com.xml: Fetch error: http://megabusgold.com/ => https://megabusgold.com/: (60, "Peer's Certificate issuer is not recognized.")
```

Ubuntu 14.04:

```
ERROR rules/Megabus.com.xml: Fetch error: http://megabusgold.com/ => https://megabusgold.com/: (60, 'server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none')
```

The https sites work fine in Firefox. Issue #1862 was similar and it had to do with a missing CA certificate, so I suppose that's the problem here too.

**Comment by fuglede** [comment]
Hm, I can not reproduce this issue (Debian Jessie, cf. below); I noticed that it also [passed Travis](https://travis-ci.org/EFForg/https-everywhere/jobs/152223194#L222) in #6274, so that's a bit curious.

	$ ./fetch-test.sh rules/Megabus.com.xml 
	INFO Finished comparing http://ca.megabus.com/ -> https://ca.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://caeu.megabus.com/ -> https://caeu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://deeu.megabus.com/ -> https://deeu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://eseu.megabus.com/ -> https://eseu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://esus.megabus.com/ -> https://esus.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://frca.megabus.com/ -> https://frca.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://freu.megabus.com/ -> https://freu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://iteu.megabus.com/ -> https://iteu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://megabus.com/ -> https://megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://megabusgold.com/ -> https://megabusgold.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://nleu.megabus.com/ -> https://nleu.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://uk.megabus.com/ -> https://uk.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://us.megabus.com/ -> https://us.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://www.megabus.com/ -> https://www.megabus.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished comparing http://www.megabusgold.com/ -> https://www.megabusgold.com/. Rulefile: rules/Megabus.com.xml.
	INFO Finished in 36.73 seconds. Loaded rulesets: 1, URL pairs: 15.

**Comment by jeremyn** [comment]
Works for me on Debian Jessie as well, still broken on Fedora.

**Comment by jeremyn** [comment]
I'm closing this issue because the [`Megabus.com.xml`](https://github.com/EFForg/https-everywhere/blob/9bf49cbeb4696cdea76df23f685da1d11031f693/src/chrome/content/rules/Megabus.com.xml) ruleset has been disabled.
