### ISSUE TITLE
license incompatibility in test/rules/: GPL-3 vs GPL-2

### ISSUE THREAD

**Issue by DonKult** [EFForg/https-everywhere#6466]
Hi,

test/rules/\* contains in COPYING the GPL-3 license text and declares itself via test/rules/setup.py as license="GPL3". That looks like a problem to me as the embedded copy of gvgen in test/rules/src/https_everywhere_checker/gvgen.py is licensed as GPL-2-only (= without the later clause) which is as such incompatible with rest of the code under GPL-3-only.

**Comment by jeremyn** [comment]
[Link to gvgen.py](https://github.com/EFForg/https-everywhere/blob/2fdd1d2b262e7e2c91c98ec4d27c76cf50af0474/test/rules/src/https_everywhere_checker/gvgen.py).

@Hainish Can you look at this?

**Comment by Hainish** [comment]
The HTTPS Everywhere checker was originally a separate repo that in the last few months we moved into `test/rules`.  I'd defer to the lowest-level scope (in this case that of the checker) for the correct license.  We should probably reach out to Ondrej Mikle (ondrej.mikle@nic.cz), the original author of the checker, to see if it's okay with him if we change the license to GPLv3, so everything is consistent.

**Comment by DonKult** [comment]
@Hainish as far as I see it the problem isn't really with Ondrej's code as I guess we can assume that with writing the setup.py file and including the COPYING file his code is meant to be GPLv3. The problem is with the one file he didn't author, gvgen.py, an embedded modified copy of an earlier version of https://github.com/stricaud/gvgen (just from the look of it), which is GPLv2, so it can't legally be used by GPLv3 code.

Assuming that you would either need @stricaud (Sebastien Tricaud) and all other contributors to that file to relicense to GPLv2+ or the code using that file (and hence likely test/rules as a whole) to be relicensed by all authors to GPLv2 – so, that isn't a matter of "consistency", but a matter of not violating the GPL. See also: https://www.gnu.org/licenses/license-compatibility.html

(I dislike these GPLv2 vs GPLv3 incompatibility issues as much as the next guy and I doubt it was the intend of the authors to prevent the other from using the code, but if we as open source community do not respect our own licenses, nobody will…)

**Comment by stricaud** [comment]
oh I can change the license for GVGen. I will make this permissive. Is the WTFPL fine? https://en.wikipedia.org/wiki/WTFPL

Thanks!

**Comment by mnordhoff** [comment]
The file says "Copyright (c) 2007 INL", "Written by" you. Do you have the authority to relicense it? I hate to be pedantic, but...

**Comment by stricaud** [comment]
the company died a few years ago. I will reflect this in the license and copyright.

**Comment by jeremyn** [comment]
Another idea: `python-gvgen` is available in the [Ubuntu 16.04](http://packages.ubuntu.com/xenial/python-gvgen) repositories. I'm having trouble figuring out for sure whether it is or isn't available through PyPI, (Fedora) dnf, or (Mac) homebrew. If it is available everywhere we need it to be though, then wouldn't installing it as a dependency be preferable to distributing it with the code?

**Comment by jeremyn** [comment]
@mnordhoff [This version of gvgen.py](https://github.com/stricaud/gvgen/blob/b1c95642b551003e9c504cd7f86a800de354a783/gvgen.py#L6) under @stricaud's profile has `Copyright (c) 2012 Sebastien Tricaud`, so either he has the right to change the license for at least that version of it, or I don't know what to say.

**Comment by Hainish** [comment]
`python-gvgen` is available for Ubuntu & Debian, but I could not find any equivalent for Fedora.  I also could not find it on PyPI when I searched.  But if @stricaud is willing to change the license, I think that should make the licensing for `gvgen` consistent with the rest of the checker.  Thanks for the prompt response @stricaud!

**Comment by pipboy96** [comment]
Closed by #18061.
