### ISSUE TITLE
No HTTPS for www.porvoo.fi

### ISSUE THREAD

**Issue by nemobis** [EFForg/https-everywhere#6475]
www.porvoo.fi has no server configured for HTTPS. Should the rule be deleted? https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/porvoo.fi.xml

**Comment by fuglede** [comment]
Thanks for the report! It should either be deleted or disabled (by adding `default_off="connection refused"` to the `ruleset` XML tag) -- disabling it can be useful if the failure is temporary as the ruleset history becomes more clearly preserved. Otherwise deletion is fine.

**Comment by fuglede** [comment]
Just went ahead and submitted the fix as #6552.
