### ISSUE TITLE
(Chrome) This extension makes Google maps constantly reload

### ISSUE THREAD

**Issue by HappyCerberus** [EFForg/https-everywhere#6477]
When this extension is enabled, google maps will reload after every tiny action (map move, zoom in/zoom out).

Not only that, it also makes the map recenter on some nearby random location (not sure how this is determined, I can't find a causal link between my actions and the final map position).

**Comment by J0WI** [comment]
I cannot reproduce on https://www.google.ch/maps/.
Can your reproduce this on a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)?

**Comment by HappyCerberus** [comment]
OK, nevermind, I think it's a problem with a specific version of Chrome.
