### ISSUE TITLE
Breaking Website: NFL Fantasy Football

### ISSUE THREAD

**Issue by ahamilton9** [EFForg/https-everywhere#648]
Haven't had a chance to see what exactly is breaking, but the extension is breaking the NFL Fantasy Football website in lots of places. I'll see if I can take a closer look soon, since I know this will affect a small number of users, and only those who are in leagues can really test if it's been fixed. 

If there IS another Fantasy Football playing dev who sees this, here's what I've been seeing:

* Show Chart in the Game Center is broken
* Changing Players on the My Team page (dragging) broken
* Links to player pages from anywhere (modal) broken

Sounds like a dead core library. I'll start there.

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen if you think it's still a bug.
