### ISSUE TITLE
Shall we require additional review for top-100 rules?

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#6492]
After #6424 comes up, I wonder if we should expand the review for the top-100 rules.
If these rules get manipulated or break functionality a huge part of all websites and users would be affected.

Usually, rules are just reviewed once and get merged then. We can improve quality and security when we require more persons to review them or require further testing.

cc @Hainish, @fuglede, @jeremyn

**Comment by Hainish** [comment]
I think it's okay if there is only one reviewer, just as long as they treat the `top-100` sites with extra care.  Already, it can take a long time for rulesets to get merged.  We may be introducing an extra bottleneck if we require more than one reviewer, and for the sake of expediency we want the `top-100` sites often to be merged quickly.

If we see problems down the road maybe we can revisit, but closing for now.
