### ISSUE TITLE
error when using at the same time as mega.nz extension

### ISSUE THREAD

**Issue by SimJoSt** [EFForg/https-everywhere#6536]
Chrome notified me with a orange menu "sandwich", that there is an extension error. HTTPS Everywhere showed the following:

> Warnung:
> Die Erweiterung konnte die Netzwerkanfrage nicht an https://mega.nz/ weiterleiten, da eine andere Erweiterung (MEGA) sie an chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega/secure.html weitergeleitet hat.

Roughly translated that would be:

> Warning:
> The extension could not forward the network request to https://mega.nz/, as another extension (MEGA) forwarded it to chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega/secure.html.

The MEGA extension secures it's service by running it offline and locally on the computer with the help of an extension, instead of just running the plain webapp.

**Comment by pipboy96** [comment]
Not reproducible anymore.
