### ISSUE TITLE
urlquery.net rule causes breakage

### ISSUE THREAD

**Issue by davidwagner** [EFForg/https-everywhere#6560]
urlquery.net currently has no HTTPS server available.  The rule for urlquery.net should be disabled.

https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=urlquery.net
https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/UrlQuery.xml

**Comment by fuglede** [comment]
Fixed in #6568.
