### ISSUE TITLE
Apple mzstatic conversion error

### ISSUE THREAD

**Issue by cedricbousmanne** [EFForg/https-everywhere#6566]
Following the rules found online [1], I tried to fetch https version of Apple App Store icons. 

However I found an issue with Google Map's Icon. It is available in http, but https "translated" url responds with a 404.

This icon : http://a4.mzstatic.com/eu/r30/Purple19/v4/bb/e8/1a/bbe81a5f-5656-643b-982c-30877a28c920/CRV_AP_360x216.jpeg

HTTPS responds with a 404 : https://s4.mzstatic.com/eu/r30/Purple19/v4/bb/e8/1a/bbe81a5f-5656-643b-982c-30877a28c920/CRV_AP_360x216.jpeg

[1] https://web6.eff.org/https-everywhere/atlas/domains/mzstatic.com-2.html

**Comment by pipboy96** [comment]
Not reproducible.
