### ISSUE TITLE
Test CA repository does not reflect Firefox state

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#6569]
PR #6102 gives an example of a host which whose SSL configuration will cause breakage in Firefox (due to an invalid chain) but which passes the fetch test.

cc @Hainish.

@jeremyn, @j0wi: You may want to be aware of this when reviewing; I just came across a second false positive.

**Comment by J0WI** [comment]
When you visited a site with the same cert chain before, the browser caches the chain and doesn't show any errors.
As far as I know we integrated some cert chains in our test infrastructure that tests don't fail. We may reconsider this.

**Comment by J0WI** [comment]
They are located in "test/rules/platform_certs/", but they might only be used on rules with platform CAcert or incomplete (do we have a platform for that?) specified.

**Comment by jeremyn** [comment]
This is a useful link for anyone trying to understand this problem: https://wiki.mozilla.org/CA:FAQ .

**Comment by fuglede** [comment]
@j0wi: The ones in `test/rules/platform_certs/default` are exactly the ones that `fetch-test.sh` and friends use, so those are the ones that would appear to be out of sync.

**Comment by jeremyn** [comment]
Considering @J0WI 's "We may reconsider this.":

My rule of thumb has been that a rewrite works if the https and http version of a page do the same thing: return the same content, have the same 4xx error, whatever. If a site is misconfigured to not correctly fetch an intermediate certificate, the two versions don't do the same thing and the rule is bad. So by this rule of thumb, I don't think we should include prefetched intermediate certificates in our tests.

**Comment by Hainish** [comment]
Looking into this now

**Comment by Hainish** [comment]
I wonder how this list of intermediates was generated in the first place.

The [Mozilla CA Certificate Store](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/) lists this [source file with all of the included root certificates](https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt).  We could possibly parse this file and generate a new `test/rules/platform_certs/defaults` that is more current.

@jsha, do you know how this was generated in the first place?

**Comment by fuglede** [comment]
Pinging @hiviah as he [added them in the first place](https://github.com/hiviah/https-everywhere-checker/commit/53e2048dfc27309e2085a1120d122581235465a4#diff-8990ddd6ec42bfc8d7da8b90be9c1d9b). Having an automated fetch-and-parser sounds like it would be great.

**Comment by jsha** [comment]
There are two questions:
 - How do we add new roots when they are added to Mozilla's root program? (we don't, or do it ad-hoc)
 - How do we add new intermediates?

We include intermediates because some sites fail to include those intermediates, which will break curl, but not necessarily Firefox (since Firefox has different certificate caching logic). I'm not sure how @hiviah generated the original set, but for similar work in the SSL Observatory we've, in the past, generated the transitive closure of all intermediates from trusted roots. To keep the list up-to-date, I've occasionally used the ad-hoc script in test/rules/platform_certs/get-issuer.sh.

Perhaps a better long-term solution would be to use the public CT logs. Not guaranteed to be comprehensive, but given that Google pushes certs from their crawls into those logs, most likely all the intermediates we care about would show up there.

**Comment by fuglede** [comment]
> We include intermediates because some sites fail to include those intermediates, which will break curl, but not necessarily Firefox (since Firefox has different certificate caching logic). I'm not sure how @hiviah generated the original set, but for similar work in the SSL Observatory we've, in the past, generated the transitive closure of all intermediates from trusted roots. To keep the list up-to-date, I've occasionally used the ad-hoc script in test/rules/platform_certs/get-issuer.sh.

I'm actually a bit surprised by this part, as I've typically been able to use curl to catch faulty Firefox behavior. Do we have an example of a host which will break curl but not Firefox?

**Comment by jsha** [comment]
I don't have one off-hand, but the case where it happens is when the site doesn't provide an intermediate *and* the Firefox user has previously visited another site that did provide the same intermediate, so the intermediate is cached by Firefox.

You could make an argument against including such sites, because they will break when visited in a completely fresh FF profile, but so far we have included them.

**Comment by fuglede** [comment]
Ah, right, then we're on the same note. But actually, I've avoided including such rulesets exactly because they potentially cause issues; in fact #3107 was more or less motivated by this very phenomenon.

**Comment by Hainish** [comment]
I'd also air on the side of not including hosts which do not provide their intermediates, since this would cause us to force users with a fresh FF profile on to a site they can't access.  If these sites are submitted in a PR and we spot this, it may also be worth it to try to reach out to the site maintainers to notify them of the problem.

**Comment by hiviah** [comment]
I generated the original certificate sets from Firefox exported roots and generating transitive closure - with [this script](https://github.com/hiviah/https-everywhere-checker/blob/master/certs_transitive_closure/build_closure.sh). 

The intermediates were taken from my own observatories ([Perspectives notary fork storing complete chains](https://github.com/hiviah/perspectives-observatory) - notary1.qabs.cz/notary2.qabs.cz, CA certs have separate table which makes export easy)

Using CT would certainly work as well, but you'd have to sieve the certs for intermediate certs.

**Comment by jsha** [comment]
Also worth noting: Often Chrome will successfully load such misconfigured sites due to something called "AIA chasing:" i.e., the leaf certificate includes metadata telling you where to fetch its parent. [Firefox doesn't implement AIA chasing](https://bugzilla.mozilla.org/show_bug.cgi?id=399324). So that brings additional pressure to include such sites. All that said, I agree that it makes sense to leave them out in general.

**Comment by J0WI** [comment]
I think we should not check with intermediates, except with a platform specified (https://github.com/EFForg/https-everywhere/pull/6697#issuecomment-244210302). This would also allow us to not `default_off` all the affected rules.


To catch all the intermediates you may have a look at https://crt.sh/mozilla-disclosures

**Comment by Hainish** [comment]
PR #6790 updates the certificate store to reflect the latest Firefox export of roots, as of 48.0.2, and removes all intermediates.

This is still a work in progress, which requires more testing.

Testing with https://github.com/EFForg/https-everywhere/pull/6789, a PR which passes the fetch test, there are a number of failures:

```
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.at/ => https://help.zalando.at/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.be/ => https://help.zalando.be/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.ch/ => https://help.zalando.ch/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.de/ => https://help.zalando.de/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.dk/ => https://help.zalando.dk/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.es/ => https://help.zalando.es/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.fi/ => https://help.zalando.fi/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.fr/ => https://help.zalando.fr/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.it/ => https://help.zalando.it/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.nl/ => https://help.zalando.nl/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.no/ => https://help.zalando.no/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.pl/ => https://help.zalando.pl/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.se/ => https://help.zalando.se/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/Zalando.xml: Fetch error: http://help.zalando.co.uk/ => https://help.zalando.co.uk/: (60, 'SSL certificate problem: unable to get local issuer certificate')
```

And indeed, these domains do give a certificate error when accessed from a fresh profile on Firefox.

**Comment by Hainish** [comment]
For #6102, I get the following, which seems to correspond to what @fuglede saw in the browser for this issue:

```
ERROR src/chrome/content/rules/octopuspop.com.xml: Fetch error: http://admin.octopuspop.com/ => https://admin.octopuspop.com/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/octopuspop.com.xml: Fetch error: http://ap.octopuspop.com/ => https://ap.octopuspop.com/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/octopuspop.com.xml: Fetch error: http://octopuspop.com/ => https://octopuspop.com/: (60, 'SSL certificate problem: unable to get local issuer certificate')
ERROR src/chrome/content/rules/octopuspop.com.xml: Fetch error: http://www.octopuspop.com/ => https://www.octopuspop.com/: (60, 'SSL certificate problem: unable to get local issuer certificate')
```

**Comment by Hainish** [comment]
Is there an example of a ruleset which failed tests due to its CA not *yet* being in our store of certs, but may pass with the newest Firefox store of CAs?

**Comment by fuglede** [comment]
> Is there an example of a ruleset which failed tests due to its CA not yet being in our store of certs, but may pass with the newest Firefox store of CAs?

Hard to say for sure, but I do not recall ever seeing such an example.
