### ISSUE TITLE
Crash & loss of tabs

### ISSUE THREAD

**Issue by corv89** [EFForg/https-everywhere#6583]
I'm getting crash reports and occasional loss of tabs upon restarting Firefox Developer Edition [50.0a2 (2016-08-23)]

Disabling https-everywhere solves the issue.

https://crash-stats.mozilla.com/report/index/7819a73a-f35c-470f-8f73-5f3cb2160824

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
