### ISSUE TITLE
"nsIJSON.encode is deprecated.  Please use JSON.stringify instead.1ssl-observatory.js:625:31" message in Firefox console

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [EFForg/https-everywhere#6589]
I have recently noticed the following error appearing in my Firefox Browser Console log:

![nsijson-encode_deprecated_firefox_warning](https://cloud.githubusercontent.com/assets/11575271/17933144/e10dd30e-6a0a-11e6-82ac-e4176cd03fb6.png)

Clicking on the link takes me to this file `~/.mozilla/firefox/bpyt2o4o.default/extensions/https-everywhere@eff.org/components/ssl-observatory.js` and this line:

```
reqParams.push("certlist="+this.compatJSON.encode(base64Certs));
```

I am running Ubuntu GNOME 16.04 with GNOME 3.20 and Firefox 48.

**Comment by jeremyn** [comment]
I can't reproduce this issue using Firefox 48.0.2 on Windows 10. Are you seeing this everywhere or only on certain sites?

**Comment by gitarra** [comment]
@jeremyn This is a problem with the addon code, not a website. More exactly the observatory code.

If you search theres a lot of issues with the observatory including causing slowness and hangs.

I'd recommend you to turn it off.

**Comment by fuglede** [comment]
I noticed a few different deprecation notes (given below) but was not able to reproduce the one you see. Tried on Firefox ESR, on 48.0.1, and on 50.0a2. Could you detail steps necessary to reproduce the issue?

	Advarsel: 'nsIOService::NewChannel()' er forældet, brug i stedet 'nsIOService::NewChannel2()'HTTPSRules.js:253:18
	“nsICookieManager.remove()” er ændret. Opdater din kode og send de korrekte originAttributes. Læs mere på MDN: https://developer.mozilla.org/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsICookieManagerHTTPS.js:164:6

**Comment by jeremyn** [comment]
Hm, I still can't get the warning to appear even after browsing around a bit with all observatory features enabled.

**Comment by fuglede** [comment]
@jeremyn: Hm, you are using the browser console (Ctrl+Shift+J), right?

**Comment by jeremyn** [comment]
@fuglede Oops! I learned something new today, thanks. I do see the warning in the Firefox [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console), where before I was checking in the Firefox [web console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console).

**Comment by benwaffle** [comment]
https://github.com/EFForg/https-everywhere/blob/cb6487d9ea38119b8584a928f02427b525bf7efe/src/components/ssl-observatory.js#L109

since it's called `compatJSON` do we need a check for older versions of firefox that don't have `JSON.stringify`?

**Comment by koops76** [comment]
@J0WI Close please.
