### ISSUE TITLE
Can't view images on prnt.sc (prntscr.com)

### ISSUE THREAD

**Issue by realchriscasey** [EFForg/https-everywhere#6591]
When I browse to http://prnt.sc/c9shwr to view an image, the image isn't displayed. To view the image, I have to disable https for the site prntscr.com.

The debug console shows the following:

> Mixed Content: The page at 'https://prnt.sc/c9shwr' was loaded over HTTPS, but requested an insecure resource 'http://prntscr.com/image.html'. This request has been blocked; the content must be served over HTTPS.

**Comment by fuglede** [comment]
Thanks for the report. Actually, this is a duplicate of #6074 which has already been fixed (and the fix should be available with the next release).

**Comment by realchriscasey** [comment]
apologies; I missed the closed issues tab when I ran my search. Thanks for the quick response.
