### ISSUE TITLE
user rule doesn't work if there are bundled rules for the same site

### ISSUE THREAD

**Issue by magicgoose** [EFForg/https-everywhere#6596]
I tried creating a user rule for a website for which the extension has also bundled rules (which I did disable first), but my rule is not picked up by the extension.

The rule code, if that would help:

```
<ruleset name="Aliexpress">
        <target host="aliexpress.*" />
        <target host="*.aliexpress.*" />
        <target host="alibaba.*" />
        <target host="*.alibaba.*" />
        <target host="alicdn.*" />
        <target host="*.alicdn.*" />

        <rule from="^http:"
                to="https:" />
</ruleset>
```

Expected result — http://www.aliexpress.com is rewritten to https://www.aliexpress.com, but instead it's not rewritten and my rule doesn't show up in the rule list which is displayed after pressing the extension button.

Is it even possible to use user rule when there's a built-in rule(s) for the same website? What can I do if I want to use my own rule and not the built in rule? I think there should be a possibility for that.

BTW, I have also other user rules and they work flawlessly. So I'm indeed using the correct folder to store them, etc.

**Comment by jeremyn** [comment]
I don't think the parser understands double-sided wildcard targets like `*.aliexpress.*`, so `www.aliexpress.com` isn't matching anything. `aliexpress.com` matches your ruleset.

**Comment by magicgoose** [comment]
Hmmm.
Is it hard to make it match double-sided wildcards then?

**Comment by jeremyn** [comment]
Both left-side and right-side wildcards are discouraged unless really needed (see [here](https://www.eff.org/https-everywhere/rulesets#wildcard-targets) and [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md)). They also require a lot of tests (see [here](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md)). I doubt double-sided wildcards are supported at all. If they were, they would be extremely discouraged.

**Comment by biergaizi** [comment]
+1 for this issue! It doesn't matter if wildcards are used or not. If there is a system rule for a particular website, the user rules won't work, even if the rules are not overlapped, or the built-in one is disabled!
