### ISSUE TITLE
Incompatibility with FineUploader

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#6616]
I have a report of incompatibility with the FineUploader extension, which uploads to S3.

From the report:

> I'm a developer at a startup, and I use your HTTPS Everywhere Chrome
> extension. I found recently that it interfered with a Javascript plugin I
> was using called FineUploader (direct to S3 version). Just wanted to let
> you know of the incompatibility issue. Thanks for the extension, by the
> way.

**Comment by rnicholus** [comment]
I'm the maintainer of Fine Uploader, and while I'm not aware of the specifics, if I can help shed some light on this issue in any way, let me know.

**Comment by Hainish** [comment]
Thanks @rnicholus, I'll have some time to look into this possibly next week.

**Comment by Hainish** [comment]
@rnicholus is there an example site that supports HTTPS as well as has FineUploader in use?  This way I can do some testing.

**Comment by rnicholus** [comment]
Fine Uploader S3 is used integrated into a lot of sites, but I don't have a running list, and of the ones I do know of off the top of my head are commercial sites that require an account, especially those that support SSL. However, my employer uses Fine Uploader S3 in some of its products. If you can provide any information needed to reproduce and report details necessary to fix/troubleshoot, I'd be happy to help myself.

**Comment by pipboy96** [comment]
Closed since https://github.com/FineUploader/fine-uploader/issues/2073.
