### ISSUE TITLE
Rule for StackExchange doesn't allow to visit https version of meta.*.stackexchange.com

### ISSUE THREAD

**Issue by magicgoose** [EFForg/https-everywhere#6625]
For example, https://meta.codegolf.stackexchange.com gets redirected to http://meta.codegolf.stackexchange.com.

It works throught https without the extension, though — if I accept the fact that the certificate is not strictly correct.

> This server could not prove that it is meta.codegolf.stackexchange.com; its security certificate is from *.stackexchange.com

The owner of the website is the same, so this is not a big deal in this case.

**Comment by fuglede** [comment]
Did HTTPS Everywhere redirect you to the HTTPS version? This domain should be caught by `<exclusion pattern="^http://([\w.-]+)\.([\w-]+)\.stackexchange\.com"/>`, so that no redirection should occur. In fact, we even do the opposite and redirect HTTPS to HTTP to avoid those problems.

**Comment by magicgoose** [comment]
> In fact, we even do the opposite and redirect HTTPS to HTTP to avoid those problems.

This is exactly what happened. And I want to disable that behavior for this rule. Is it possible?

**Comment by fuglede** [comment]
Ah, sorry, I misunderstood your question. Unfortunately, there is no way to do that without disabling the ruleset (through the toolbar menu).

One way around the issue would be to split the ruleset in two, one for the downgrade rule, and one for the rest. That would allow you to modify their behaviour independently of each other.

**Comment by Bisaloo** [comment]
This issue is fixed. See https://github.com/EFForg/https-everywhere/issues/9085 for more info.
