### ISSUE TITLE
fetch tests should check OCSP response

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#6630]
Test should check OCSP response to detect revoked certs (e.g. in https://travis-ci.org/EFForg/https-everywhere/builds/149843004).

**Comment by Bisaloo** [comment]
Would setting `--cert-status` in curl options be enough?

[Man page link for this option](https://curl.haxx.se/docs/manpage.html#--cert-status)

**Comment by J0WI** [comment]
Sadly `--cert-status` does only work for servers supporting OCSP stapling.

The following command will print the OCSP status for any host:
```
openssl ocsp -issuer [issuer cert] -cert [server cert] -url [ocsp server] -resp_text -header HOST=[HTTP host]
```

**Comment by zoracon** [comment]
Due to the new direction of our rulesets I am cleaning issues based on the current parameters:

- Transition to new Smarter Encryption primary usage in Autumn
- Discontinuing new crowd sourced rulesets
- Deprecation of the HTTPS Labeller and Fetch Test tooling
