### ISSUE TITLE
Pornhub videos not playing

### ISSUE THREAD

**Issue by Sanugon** [EFForg/https-everywhere#6680]
I can visit the site with no problems but as soon as I click on a video it just doesn't play. It opens the video but instead of playing it gives a black screen where the video should be,

I disabled all of my extensions and tested the videos again and they worked. So I systematically turned on all my extensions one by one till I got to https-everywhere and the problems started again. I then turned off all my extensions again and tested it solely with https-everywhere and it is definitely the culprit. For now I just disabled it for that site.

It's not a major issue but it could potentially cause problems on other video sites which doesn't use https.

Specs:

Google Chrome Version 52.0.2743.116 m (64-bit)
HTTPS Everywhere 2016.8.24

**Comment by numismatika** [comment]
@Sanugon Which rules are active on the site? Does the console report any mixed content issues?

**Comment by Sanugon** [comment]
@numismatika 

Stable Rules

Force encrypted connections to these websites:

PornHub.com (partial)
TrafficJunky.net (partial)
Google APIs
Doublepimp.com (partial)

**Comment by numismatika** [comment]
@Sanugon i can't reproduce that issue here. Are you using flash for the videos by chance?

**Comment by Sanugon** [comment]
@numismatika Funny enough the problem started again. I followed the same procedure as before and now the same thing is happening with Ad Block Plus. It is only ABP that is giving the issue; it still works fine with Ad Block enabled.

I'm starting to wonder if it has more to do with www.pornhub.com than the actual extensions.

Oh and the only flash I use is what comes pre-installed with Chrome. I do use a flash blocker, although the results are the same regardless if it's enabled or not.
