### ISSUE TITLE
Exclude a domain?

### ISSUE THREAD

**Issue by orschiro** [EFForg/https-everywhere#6688]
Dear all,

Thank you very much for your development of this Chrome extension!

I have one question:

How can I exclude a domain? For example, for `http://www.domain.com` I do not want a redirect to `https://www.domain.com`.

Is this possible?

Thankfully,

-Robert

**Comment by jeremyn** [comment]
I don't know if you can exclude domains using the add-on UI in Chrome. In Firefox you can write custom rulesets to do whatever you want. For example you could copy the ruleset for `domain.com` to some other file, add your exclusion there, and then disable the original ruleset. See [here](https://www.eff.org/https-everywhere/rulesets) to get started on working with rulesets.

**Comment by fuglede** [comment]
This is probably not what you want, but just in case it is, and you are not already aware: In case the relevant domain is the only one included in a ruleset, it will suffice to disable the ruleset, which you can do by clicking the toolbar button and unchecking the ruleset.

**Comment by orschiro** [comment]
Thank you both for your comment! 

I am indeed a Chrome user and it is not clear to me how to access the rulesets. 

As pointed out by @jeremyn, I cannot find any UI dialog for it. 

-Robert

**Comment by advaith1** [comment]
So you want to disable a ruleset?

Just click the HTTPS Everywhere button next to the Omnibox or in the Customize and Control menu.

**Comment by orschiro** [comment]
Yes, correct. 

This seems to have been implemented since my last comment. 

Thank you! :-)

![image](https://cloud.githubusercontent.com/assets/170947/24440147/cdae233e-1452-11e7-9e8b-b66791cd12d4.png)

**Comment by gloomy-ghost** [comment]
Closing this issue as it is answered.
