### ISSUE TITLE
dell.com images broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6737]
http://www.dell.com/support/article/us/en/19/SLN291879/EN

Dell.com (partial) breaks the small images throughout in the article.

**Comment by fuglede** [comment]
This issue may be fixed simply by adding

```xml
<exclusion pattern="^http://afcs\.dell\.com/support/article/static/" />
```

However, the ruleset has numerous other issues that need to be fixed:

	ERROR rules/Dell.xml: Fetch error: http://de.community.dell.com/cfs-filesystemfile/__key/communityserver-components-secureimagefileviewer/communityserver-components-userfiles-00-00-00-53-65-features/new_5F00_caution.jpg_2D00_160x160.jpg => https://de.community.dell.com/cfs-filesystemfile/__key/communityserver-components-secureimagefileviewer/communityserver-components-userfiles-00-00-00-53-65-features/new_5F00_caution.jpg_2D00_160x160.jpg: (51, "SSL: no alternative certificate subject name matches target host name 'de.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://en.community.dell.com/Themes/Groups/DellTechCenterFiji/Images/FacebookIcon.jpg => https://en.community.dell.com/Themes/Groups/DellTechCenterFiji/Images/FacebookIcon.jpg: (51, "SSL: no alternative certificate subject name matches target host name 'en.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://en.community.dell.com/cfs-file/__key/communityserver-components-sitefiles/Direct2Dell_5F00_banner.png => https://en.community.dell.com/cfs-file/__key/communityserver-components-sitefiles/Direct2Dell_5F00_banner.png: (51, "SSL: no alternative certificate subject name matches target host name 'en.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://es.community.dell.com/resized-image/__size/45x0/__key/widgetcontainerfiles/e8cd36567b8c485e9516257a9560715c-u-AAAAAAAAAAAAAAAAAAAAAA-page-1common_2D00_home/859745199_2D00_6746.ideastorm.jpg => https://es.community.dell.com/resized-image/__size/45x0/__key/widgetcontainerfiles/e8cd36567b8c485e9516257a9560715c-u-AAAAAAAAAAAAAAAAAAAAAA-page-1common_2D00_home/859745199_2D00_6746.ideastorm.jpg: (51, "SSL: no alternative certificate subject name matches target host name 'es.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://fr.community.dell.com/cfs-file.ashx/__key/themefiles/s-e8cd36567b8c485e9516257a9560715c-files/favicon.ico => https://fr.community.dell.com/cfs-file.ashx/__key/themefiles/s-e8cd36567b8c485e9516257a9560715c-files/favicon.ico: (51, "SSL: no alternative certificate subject name matches target host name 'fr.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://ko.community.dell.com/cfs-file/__key/defaultwidgets/c0d011fc348b4529892cd747fe562169-44bc38ea68ce486499ae79d6dd255642/new_2D00_message_2D00_background.gif => https://ko.community.dell.com/cfs-file/__key/defaultwidgets/c0d011fc348b4529892cd747fe562169-44bc38ea68ce486499ae79d6dd255642/new_2D00_message_2D00_background.gif: (51, "SSL: no alternative certificate subject name matches target host name 'ko.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://media.community.dell.com/Themes/Groups/DellTechCenterFiji/images/border.png => https://en.community.dell.com/Themes/Groups/DellTechCenterFiji/images/border.png: (51, "SSL: no alternative certificate subject name matches target host name 'en.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://pt.community.dell.com/cfs-file/__key/defaultwidgets/c0d011fc348b4529892cd747fe562169-44bc38ea68ce486499ae79d6dd255642/search_2D00_icon.gif => https://pt.community.dell.com/cfs-file/__key/defaultwidgets/c0d011fc348b4529892cd747fe562169-44bc38ea68ce486499ae79d6dd255642/search_2D00_icon.gif: (51, "SSL: no alternative certificate subject name matches target host name 'pt.community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://advisors.dell.com/ => https://advisors.dell.com/: (35, 'Unknown SSL protocol error in connection to advisors.dell.com:443 ')
	ERROR rules/Dell.xml: Fetch error: http://community.dell.com/ => https://community.dell.com/: (51, "SSL: no alternative certificate subject name matches target host name 'community.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://powermore.dell.com/ => https://powermore.dell.com/: (51, "SSL: no alternative certificate subject name matches target host name 'powermore.dell.com'")
	ERROR rules/Dell.xml: Fetch error: http://techpageone.dell.com/ => https://techpageone.dell.com/: (6, 'Could not resolve host: techpageone.dell.com')
