### ISSUE TITLE
Please fix EXTENSION HTTPS Everywhere 2016.9.1 ERROR IN GOOGLE CHROME version 53.0.2785.89 m (64-bit)

### ISSUE THREAD

**Issue by ChamZank** [EFForg/https-everywhere#6744]
Please fix EXTENSION HTTPS Everywhere 2016.9.1 ERROR IN GOOGLE CHROME version 53.0.2785.89 m (64-bit) i found extension corrupt
![capture-20160904-022436](https://cloud.githubusercontent.com/assets/6598967/18226959/751dea62-7248-11e6-98af-f5db69764bc3.jpg)

**Comment by jeremyn** [comment]
This is a duplicate of #5874. Closing issue.
