### ISSUE TITLE
Cannot login to forums.guru3d.com with extension enabled

### ISSUE THREAD

**Issue by mdamaged** [EFForg/https-everywhere#6746]
Cannot login to forums.guru3d.com with extension enabled, disabling any/all of the stable rules that show up does not help, only disabling the entire extension works. Would be a nice addition to be able to add a whitelist where one can disable the extension only on designated sites.

OS: Windows 10 x64 Home 1511
Chrome: Version 53.0.2785.89 m
Extension: Version: 2016.9.1

**Comment by fuglede** [comment]
Thanks for the report. It sounds a little weird that disabling the visible rules did not help as this should be functionally equivalent to disabling the add-on entirely.

**Comment by jeremyn** [comment]
I think what happens is that one site calls another, which can call another, and so on in a chain. The functionality that that the user wants, like logging in, is enabled by some site down the chain. If the ruleset for the first site is broken, then the chain is broken. When the ruleset for the first site is disabled, then HTTPS Everywhere probably either isn't refreshing "enough" to restart the chain, or something has been [cached](http://www.refreshyourcache.com/en/cache/), or both.

**Comment by verlain3** [comment]
8 months and this is still not fixed?!

I'm having the same issue.

**Comment by J0WI** [comment]
Is this still an issue? I can't see any active rules on this site.

**Comment by mdamaged** [comment]
Seems to work for me now, with and without the extension disabled (meaning the in-app disable).

**Comment by J0WI** [comment]
Thanks for your response! I'll close this for now, please fill a new issue if a new issue occurs.
