### ISSUE TITLE
HTTPS Everywhere is defective and can not be repaired!

### ISSUE THREAD

**Issue by strykenKN** [EFForg/https-everywhere#6748]
AddOn ist unter Google Chrome 53 (x64) defekt nach dem Update und funktioniert nicht mehr. Reparatur ist nicht möglich. Neuinstallation nicht möglich!

Englisch: 

AddOn is under Google Chrome 53 (x64) defective after the update and no longer works. Repair is not possible. Reinstallation is not possible!

HTTPS Everywhere 2016.9.1
Diese Erweiterung ist möglicherweise beschädigt.

Englisch: 

HTTPS Everywhere 01.09.2016
This extension may have been corrupted.

**Comment by kvineet** [comment]
I am getting same issue.

HTTPS Everywhere 2016.9.1
Chrome version: 53.0.2785.92 (64-bit)
OS: Manjaro Linux (kernel 4.7.2-1)

* Removing and re-installing the extension had no effect. 
* Changing `chrome://flags/#extension-content-verification` flag to `default` or `bootstrap` had no effect.

**Comment by fuglede** [comment]
Thanks for the report. This one is a duplicate of #5874.
