### ISSUE TITLE
Version 2016.9.1 Crashes on chrome

### ISSUE THREAD

**Issue by YSZhuoyang** [EFForg/https-everywhere#6758]
Installed Version: 2016.9.1
Chrome Version: 53.0.2785.89 (64-bit)
Got the Error - "This extension may have been corrupted".

Tried both repair and re-installing it many times but always got the same error.

**Comment by jurgenhaas** [comment]
I'm seening the exact same problem with Chrome Version 53.0.2785.92 (64-bit) and neither repair nor re-install does help.

**Comment by jeremyn** [comment]
This is a duplicate of #5874 , closing.
