### ISSUE TITLE
Chrome says: This extension may have been corrupted.

### ISSUE THREAD

**Issue by peterbrinck** [EFForg/https-everywhere#6766]
After the latest update, Chrome says: This extension may have been corrupted.

**Comment by anand-bhat** [comment]
Reported and being tracked via Issue https://github.com/EFForg/https-everywhere/issues/5874.

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of #5874.

**Comment by peterbrinck** [comment]
Oh, sorry
I didn't see there already was one

**Comment by jeremyn** [comment]
@peterbrinck That's fine, you're not the only one.
