### ISSUE TITLE
infogr.am (partial) breaks graph

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6791]
http://www.standard.net/Police-Fire/2016/08/21/Utah-concealed-weapons-permits-now-numbering-663K-see-surge-in-popularity

**Comment by terrorist96** [comment]
http://www.theage.com.au/interactive/2016/gun-city/day1.html

**Comment by terrorist96** [comment]
@fuglede 
https://github.com/EFForg/https-everywhere/pull/4503#issuecomment-202535289

> Thanks. If it turns out to be problematic in more cases, I'll throw in my vote to simply disable the domain.

**Comment by fuglede** [comment]
Removed the subdomain from the ruleset in #6903.
