### ISSUE TITLE
boston.com (partial) rule broken

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6792]
http://www.boston.com

The boston.com (partial) rule causes the page to continuously reload and appends a "g00//" at the end of the URL continuously.

**Comment by jeremyn** [comment]
I can't reproduce this problem in either Firefox or Chrome. Are you still seeing this, and if so, using what browser?

**Comment by terrorist96** [comment]
Can't reproduce anymore either. I feel like it was an issue with my ad blocker and https everywhere not getting along. Though if you go to the site, you'll notice the g00// appended at the end very briefly, but it goes away, instead of like before, it would keep getting appended continuously.

**Comment by terrorist96** [comment]
@jeremyn This is happening again for me.

**Comment by terrorist96** [comment]
Can't reproduce anymore.

**Comment by jeremyn** [comment]
@terrorist96 Thanks for the follow up.
