### ISSUE TITLE
Images broken at aftenposten.no

### ISSUE THREAD

**Issue by heftig** [EFForg/https-everywhere#6822]
http://www.aftenposten.no/meninger/kommentar/Dear-Mark-I-am-writing-this-to-inform-you-that-I-shall-not-comply-with-your-requirement-to-remove-this-picture-604156b.html

Embedded image URLs (starting with `//ap.mnocdn.no/`) are rewritten to `https://www.aftenposten.no/` but produce 404s.

In addition, attempting to load the page with https redirects to http.

**Comment by numismatika** [comment]
I am still digging but so far i can only see the Aftenposten rule that just has a target of
`		<target host="ap.mnocdn.no" />`
which is rewritten with
`	<rule from="^http:"
		to="https:" />`
so it should not end up with the rewrite you mentioned above.
Are you on a current release @heftig ?

**Comment by heftig** [comment]
Maybe this is a combination of the rewrite to `https:` and `ap.mnocdn.no` being misconfigured to redirect https requests to `www.aftenposten.no`.

**Comment by numismatika** [comment]
I get redirected from `http://ap.mnocdn.no/images/author/88f55278-2fc6-41ce-b142-f0b0286237d1?fit=crop&q=80&w=180`

to
`https://ap.mnocdn.no/images/author/88f55278-2fc6-41ce-b142-f0b0286237d1?fit=crop&q=80&w=180`
looks like a perfect picture.

**Comment by numismatika** [comment]
I get redirected from `http://ap.mnocdn.no/images/author/88f55278-2fc6-41ce-b142-f0b0286237d1?fit=crop&q=80&w=180`

to
`https://ap.mnocdn.no/images/author/88f55278-2fc6-41ce-b142-f0b0286237d1?fit=crop&q=80&w=180`
looks like a perfect picture.

**Comment by heftig** [comment]
The latter URL works, but the former is rewritten to `https://www.aftenposten.no/images/author/88f55278-2fc6-41ce-b142-f0b0286237d1?fit=crop&q=80&w=180` if https-everywhere 5.2.4 is enabled.

**Comment by J0WI** [comment]
This seems to be fixed.
