### ISSUE TITLE
HTTPS no longer supported on TheVideo.me - disable ruleset

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#6835]
HTTPS is no longer supported on [TheVideo.me](http://thevideo.me/), so the ruleset should be disabled so that the site is functional again.

**Comment by jeremyn** [comment]
https://thevideo.me looks okay to me except for some minor mixed content blocking:

> Blocked loading mixed active content "http://thevideo.me/js/thumb_slide.js"

What happens for you?

**Comment by anonsubmitter** [comment]
I get SSL_ERROR_ACCESS_DENIED_ALERT on the HTTPS version of the site in Firefox. The HTTP version of the site is blocked by F-Secure Client Security Premium.

**Comment by jeremyn** [comment]
Based on your description, this looks like another F-Secure false positive like you reported in issue #3218. Can you try the site without using F-Secure?

**Comment by anonsubmitter** [comment]
I can't disable F-Secure as far as I can see.
