### ISSUE TITLE
HubSpot.net breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#6851]
http://www.tecan.com/careers-join

`HubSpot.net` breaks small images (to the left of cities)

http://www.tecan.com/career-detail?ID=106&ConID=13287
Back button image.

http://www.tecan.com/
Search magnifying glass image.

**Comment by galeksandrp** [comment]
Does http://www.tecan.com/careers-join requires some login? Can't see images even without HTTPSE
http://www.tecan.com/career-detail?ID=106&ConID=13287 back button present on https://github.com/EFForg/https-everywhere/commit/master https://github.com/EFForg/https-everywhere/commit/30c306a857b3780cfa5b11e937193915beba4300
Describe more about issue with magnifying glass image.

**Comment by terrorist96** [comment]
Can't reproduce anymore.
