### ISSUE TITLE
Itunes.com broken

### ISSUE THREAD

**Issue by joshniesler** [EFForg/https-everywhere#6870]
HTTPS Everywhere is enforcing https on _http://www.itunes.com/*_ which is resulting in a CERT_NAME_INVALID error from browsers.

Observation: https://t.co/mGptgBmIWq

Thanks :)

**Comment by jeremyn** [comment]
Thanks for the report.

https://www.itunes.com has a certificate mismatch. One way to fix this is to add a rule to [`iTunes.com.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/ITunes.com.xml) to rewrite `http://www\.itunes\.com/` to `https://itunes.com/` and also note the mismatch in the top comment.
