### ISSUE TITLE
UI: Enable/Disable Rules is out of place?

### ISSUE THREAD

**Issue by DrunkenSasquatch** [EFForg/https-everywhere#6880]
![dialog box](https://cloud.githubusercontent.com/assets/16097892/18533946/38a9b440-7b2a-11e6-846e-6deaa2412191.jpg)

**Comment by jeremyn** [comment]
I hadn't thought about it before but it is a little weird that `Enable / Disable Rules` is reverse-indented like that. Why is it above `Donate to EFF`, for example?

**Comment by Wannabe-Programmer** [comment]
@jeremyn I've noticed this bug for a long time now. However, I only realized yesterday that HTTPS Everywhere had it's own GitHub page :sweat_smile:

**Comment by fuglede** [comment]
Weird. I'm not seeing that on Firefox/Firefox ESR on Debian. It also looks like the checkmarks have disappeared again.

**Comment by jeremyn** [comment]
I see a checkmark when I select for example `Show Counter` on Windows 10, Firefox 48.0.2, HTTPS Everywhere 5.2.4.

**Comment by fuglede** [comment]
@jeremyn: I was actually thinking about the ones next to the rulesets, but it looks like I misremembered, and they were never actually fixed; #2618.

**Comment by jeremyn** [comment]
Oh, okay.

**Comment by gloomy-ghost** [comment]
The WebExtension UI has shipped
