### ISSUE TITLE
Polygon.com comments not loading

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#6887]
http://www.polygon.com/2016/9/15/12927770/pokemon-sun-and-moon-anime-preview-art-style#comments

I had to disable the Polygon.com (partial) rule to get the comments to display otherwise it just stays as Loading comments always.

**Comment by antoniojtorres** [comment]
Polygon seems to be 301 redirecting all traffic to http. 

`curl -vI https://www.polygon.com/2015/11/27/9807860/hearthstone-disconnect-dreamhack-tournament-drama
*   Trying 151.101.13.52...
* Connected to www.polygon.com (151.101.13.52) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.voxmedia.com
* Server certificate: GlobalSign CloudSSL CA - SHA256 - G3
* Server certificate: GlobalSign
> HEAD /2015/11/27/9807860/hearthstone-disconnect-dreamhack-tournament-drama HTTP/1.1
> Host: www.polygon.com
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< Server: nginx
Server: nginx
< Content-Type: text/html
Content-Type: text/html
< Location: http://www.polygon.com/2015/11/27/9807860/hearthstone-disconnect-dreamhack-tournament-drama
Location: http://www.polygon.com/2015/11/27/9807860/hearthstone-disconnect-dreamhack-tournament-drama
< X-Request-Id: 24d5d19ed15f37e651827da164c2fe9d8f7be343
X-Request-Id: 24d5d19ed15f37e651827da164c2fe9d8f7be343
< X-Runtime: 0.001829
X-Runtime: 0.001829
< Via: 1.1 varnish-v4
Via: 1.1 varnish-v4
< Content-Length: 11
Content-Length: 11
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Date: Sat, 29 Oct 2016 05:58:50 GMT
Date: Sat, 29 Oct 2016 05:58:50 GMT
< Via: 1.1 varnish
Via: 1.1 varnish
< Age: 0
Age: 0
< Connection: keep-alive
Connection: keep-alive
< X-Served-By: cache-fra1221-FRA
X-Served-By: cache-fra1221-FRA
< X-Cache: MISS
X-Cache: MISS
< X-Cache-Hits: 0
X-Cache-Hits: 0
< X-Timer: S1477720730.783041,VS0,VE102
X-Timer: S1477720730.783041,VS0,VE102
< Vary: Origin, X-Forwarded-Proto, X-Chorus-Unison-Testing
Vary: Origin, X-Forwarded-Proto, X-Chorus-Unison-Testing

< 
* Connection #0 to host www.polygon.com left intact`

**Comment by antoniojtorres** [comment]
The URL https://www.polygon.com/services/entry_stats?id=12691811,13224455,13224459,13225063,13225633,13226301,13226637 seems to be the one related to comments and is returning a CORS error. Will test with excluding that one as well

**Comment by IDKwhattoputhere** [comment]
Similar issue but with images can be observed here: `http://www.polygon.com/2016/12/21/14039220/super-mario-run-nintendo-apple-sales-failure`
![](https://cloud.githubusercontent.com/assets/16030872/21464706/68b4c7d8-c986-11e6-8771-fbf974745212.png)
I'm commenting here since this issue is with `Polygon.com (partial)` and the fix could be similar.

**Comment by terrorist96** [comment]
http://www.polygon.com/tv/2016/12/6/13855390/adult-swim-million-dollar-extreme-canceled

`Polygon.com (partial)` breaks images.
