### ISSUE TITLE
cert expired for www.thesprawl.org

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#6892]
So we shouldn't redirect to https.

**Comment by Foorack** [comment]
@KommX Thanks for reporting it. I made a pull request disabling it.

Regarding expired certificate issue reports, is it up to a project maintainer to notify the website owner or can this be done by anyone? I know there isn't anything stopping others from doing it, I was more wondering what the project-maintainers prefer in regard to professionalism and overseight.
