### ISSUE TITLE
forms.verisign.com fails with HTTPS-Everywhere

### ISSUE THREAD

**Issue by Myer** [EFForg/https-everywhere#6909]
One example:
[http://forms.verisign.com/DDoSTrendsReportQ22016](http://forms.verisign.com/DDoSTrendsReportQ22016)
vs.
[https://forms.verisign.com/DDoSTrendsReportQ22016](https://forms.verisign.com/DDoSTrendsReportQ22016)

It gets linked at the end of this blog post:
[https://blog.verisign.com/security/verisign-q2-2016-ddos-trends-layer-7-ddos-attacks-a-growing-trend/](https://blog.verisign.com/security/verisign-q2-2016-ddos-trends-layer-7-ddos-attacks-a-growing-trend/)

[https://www.ssllabs.com/ssltest/analyze.html?d=forms.verisign.com&ignoreMismatch=on](https://www.ssllabs.com/ssltest/analyze.html?d=forms.verisign.com&ignoreMismatch=on)

**Comment by jeremyn** [comment]
Thanks for the report. It looks like the [`Verisign.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Verisign.xml) rule needs an `exclusion` for `forms.verisign.com`.
