### ISSUE TITLE
add josm.openstreetmap.de

### ISSUE THREAD

**Issue by Newbie07** [EFForg/https-everywhere#691]
Hi

Please add josm.openstreetmap.de to the ruleset. The site supports ssl for a long time now.

Thanks

**Comment by StevenRoddis** [comment]
@reedy I think @Newbie07 meant to say it's not part of openstreetmap.org.

The cert looks good, I always thought the cert was invalid. I haven't done any OSM/JOSM stuff in years.
Writing up a rule now.
