### ISSUE TITLE
Create test for no `target`s existing for a `ruleset`

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#6915]
It is unclear to me that tests will fail if there are not `target`s for a `ruleset`.  We should ensure that it does.

Related: https://github.com/EFForg/https-everywhere/pull/6813

**Comment by Bisaloo** [comment]
Yes, they should fail because of the `<oneOrMore>` in [`relaxng.xml`](https://github.com/EFForg/https-everywhere/blob/09fb5724f474f92f447d6af85642304a172f1524/utils/relaxng.xml#L32).
