### ISSUE TITLE
Partial rule for Aftenposten.no breaks all images

### ISSUE THREAD

**Issue by forteller** [EFForg/https-everywhere#6935]
Aftenposten is one of Norway's largest newspapers. The "Aftenposten (partial)" ruleset breaks absolutely all images, except for the logo and some social buttons, on aftenposten.no. This might get a lot of Norwegian users to uninstall HTTPS Everywhere.

**Comment by jeremyn** [comment]
I'm closing this as a duplicate of issue #6822, but please feel free to reopen with a comment if it's not a duplicate.
