### ISSUE TITLE
Add an option to never send cookies over HTTP

### ISSUE THREAD

**Issue by wilhelmy** [EFForg/https-everywhere#694]
This might be less obstructive than disabling HTTP entirely.
Another possibility might be to never send cookies over HTTP which were received via HTTPS (although I guess this wouldn't make much of a difference for users already running the plugin)

**Comment by Giltyhub** [comment]
cc/ @cschanaj Do you think this would be an interesting feature?

**Comment by zoracon** [comment]
Closing due to new changes since this conversation took place and work has been done for secure cookies
