### ISSUE TITLE
Implement platform for chain issues

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#6966]
From https://github.com/EFForg/https-everywhere/pull/6697#issuecomment-244210302:

There are a lot of rules that are currently disabled because of incomplete certificate chains. A platform would allow users to easily enable those rules and would also allow us to test them.

**Comment by J0WI** [comment]
This might be obsolete in near future:
https://trac.torproject.org/projects/tor/ticket/20461
https://bugzilla.mozilla.org/show_bug.cgi?id=657228

**Comment by pipboy96** [comment]
@J0WI Is this fine to close?

**Comment by J0WI** [comment]
Intermediate preloading in Firefox is still in an alpha state, but once it's considered stable it will be enabled in tor browser.
