### ISSUE TITLE
update maxVersion?

### ISSUE THREAD

**Issue by n8fr8** [EFForg/https-everywhere#6981]
Firefox for Android, and Orfox as well, are now well based v40 territory, but HTTPS Everywhere is still:

  em:maxVersion40.0/em:maxVersion

Is there a reason for that? Can you increase to 45.\* at least?

**Comment by gloomy-ghost** [comment]
Version 5.2.9
Released December 20, 2016  2.7 MiB
Works with Firefox for Android 26.0 - 54.0, Firefox 26.0 and later, SeaMonkey 2.17 and later, Thunderbird 26.0 and later.

Closing.
