### ISSUE TITLE
Chrome extension prevents SumoMe from loading

### ISSUE THREAD

**Issue by dkm945** [EFForg/https-everywhere#6982]
Hey there. As of yesterday afternoon, SumoMe wouldn't load on a WordPress site that I'm working on. After testing on different browsers and disabling extensions, I discovered that the issue was caused by HTTPS Everywhere, which caused no problems before yesterday afternoon. There must be an issue with the most recent update.

**Comment by jeremyn** [comment]
Thanks for your report. Can you please give more specific instructions on how to reproduce this problem, aimed at someone who doesn't know what SumoMe is?

**Comment by dkm945** [comment]
Step1. Have/access a site powered by WordPress.
Step2. Install/activate/login to the WordPress plugin SumoMe, see results directly below.

![1](https://cloud.githubusercontent.com/assets/12143983/19125465/c3166a1a-8afc-11e6-9ebc-1c5cf5c0f19a.png)


Step3. Enable HTTPS Everywhere in Google Chrome.
Step4. Access SumoMe, be greeted with white space (below).

![2](https://cloud.githubusercontent.com/assets/12143983/19125529/fd616530-8afc-11e6-9013-5776176f5fab.png)

**Comment by jeremyn** [comment]
Thanks. Is there a way to reproduce this problem without logging into SumoMe?

**Comment by dkm945** [comment]
Unfortunately, I think not.

Another detail (might help, might not): I revisit the site I work on while HTTPS E is active, I have to manually load up SumoMe (type 'sumome' then up arrow), at which point it has a sign up prompt. I then deactivate HTTPS E, reload site, and it treats me as if I'm logged in.

**Comment by pipboy96** [comment]
Not reproducible, 2016.
