### ISSUE TITLE
Ruleset Style Guide Problem

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#6985]
The [style guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) doesn't like wildcard, it requires a list of subdomains with a plain rewrite rule in rulesets rather than `regexes with long strings of subdomains`.

However, some sites have a bunch of subdomains to balance loading pressure, or just to avoid concurrent connections limit in bowsers. Then it is too much to list them all.

A recent example is #6899, in that case we have `c[2-79].yunpan.360.cn`, which have exactly the same function. There are [3 options](https://github.com/EFForg/https-everywhere/pull/6899#issuecomment-249233479):

1. List nearly 80 subdomains one by one, which is a huge list.
2. Use a wildcard with a special rule, but then we have to use `regexes with long strings of subdomains` instead of a plain rewrite rule.
3. Use a exclusion with negative lookahead operator, which is confusing for somebody.

The style guide notes option 2 and 3 as a bad example, even though option 1 is not an elegant solution. If this still need to consider, another example is [McAfee.xml](https://github.com/gloomy-ghost/https-everywhere/commit/3478e6c1c7753c772cc1c3d632bf62cb1c250f71):

Only some certain pages under `www.mcafee.com` have https, and all of the others redirect to http. In this case we don't have option 1, so it seems to be a problem that has no solution if we don't violate the style guide.

**Comment by jeremyn** [comment]
I've already participated in this discussion in pull request #6899 , so @fuglede @Hainish @J0WI please add your comments here.

**Comment by Hainish** [comment]
I don't think that the styleguide needs to change here - the wording is open-ended enough to allow reasonable exceptions.  Words like "avoid" and "prefer" provide the flexibility needed to allow for option 2.  Which is my preference as well.

**Comment by J0WI** [comment]
Since the question has been answered I'm closing this issue.

**Comment by gloomy-ghost** [comment]
Sorry, didn't notice the email.

But there are some large rulesets which are using option 3  and it is really looong to write every subdomains in the rule, such as QQ.xml. So are these acceptable or not?

**Comment by jeremyn** [comment]
It's case-by-case. In #6899 that you linked above, there are [only seven subdomains](https://github.com/EFForg/https-everywhere/pull/6899#issuecomment-249233479) that need to be listed in one regex, and two subdomains (including one wildcard with `\d{1,2}`) in the other. [Here](https://github.com/EFForg/https-everywhere/blob/aec06ebba4fc7eab0ed46f0f0dfe84d261346711/src/chrome/content/rules/Microsoft.xml#L630) is an example of one regex with over twenty subdomains. So I think that if some new rule has a lot more than twenty subdomains in one regex, we can worry about it then. And even then listing each subdomain might be better than whatever the alternative is.

**Comment by gloomy-ghost** [comment]
There are 50 subdomains in #6986. I will just leave it there and whoever wants to do that please feel free.
