### ISSUE TITLE
enable sorting of "Enabled" column

### ISSUE THREAD

**Issue by Cathryne** [EFForg/https-everywhere#703]
So that people can more easily review disabled rules.

Is it possible at all, seeing that the entries [in that column](https://github.com/EFForg/https-everywhere/blob/5051e73cb7e28ce68e8644a3a681e18c43d97aa5/src/chrome/content/preferences.xul#L41) are checkbox types instead of strings?

**Comment by pipboy96** [comment]
Issue is specific to dead, pre-WebExtensions version. Closing.
