### ISSUE TITLE
Firefox icon and checkbox do not sync "Block all HTTP requests" setting in private windows

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#709]
`Mozilla Firefox 33.0.2`
`Linux 3.17.2-1 x86_64 GNU/Linux`  
- Open Firefox. 
- Ensure "Block all HTTP requests" setting is disabled. The icon should be blue. 
- Open a new private window. 
- Enable "Block all HTTP requests" in private window.  The icon in the private window will be red. 
- Close the private window. 
- The icon remains blue in the original window and the setting remains unchecked, yet "Block all HTTP requests" is enabled.

**Comment by diracdeltas** [comment]
Sorry for the delay; I just discovered you can filter for issues that mention your github username :). 

I'm not 100% convinced this is a bug. Generally the browser is supposed to minimize shared state between private and regular browsing sessions. So for instance, HSTS entries aren't shared from non-private to private browsing in Firefox.

**Comment by NicolasP** [comment]
@diracdeltas The fact that the icon color loses sync with the actual behavior is still a bug.

**Comment by diracdeltas** [comment]
@NicolasP thanks, I realized I misread the original bug report. Will look into it.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
