### ISSUE TITLE
eo.mondediplo.com has https version

### ISSUE THREAD

**Issue by pizzamaker** [EFForg/https-everywhere#7151]
Currently, the extension does not force HTTPS when viewing this site

**Comment by jeremyn** [comment]
Thanks for the report. A new `target` should be added to [`MondeDiplo.com.xml`](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/MondeDiplo.com.xml).

**Comment by Bisaloo** [comment]
@jeremyn, could you close this issue please? It was fixed in #7486

**Comment by jeremyn** [comment]
Good catch, @Bisaloo. Closing.
