### ISSUE TITLE
HTTPSE icon expands add-on bar unnecessarily

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#7179]
I use [an add-on](https://addons.mozilla.org/firefox/addon/new-add-on-bar) to show an add-on bar at the bottom of Firefox.
When HTTPSE's icon is not in this bar it looks like this:
![smallbar](https://cloud.githubusercontent.com/assets/11966684/18932804/4b526080-85d2-11e6-9e7d-5ede35f028df.png)

As you can see PrivacyBadger's count number overlaps the bar. Now when I drag & drop HTTPE's icon into the bar, the height of the bar increases very much:
![largeaddonbar](https://cloud.githubusercontent.com/assets/11966684/18932712/f558bc88-85d1-11e6-8666-5356572d7f32.png)

There PrivacyBadger's icon is inside the bar.

Firefox 49.0.1
Gnome
Linux x64 (Debian)

**Comment by gloomy-ghost** [comment]
Closing as obsolete since we have migrated to WebExtension.
