### ISSUE TITLE
breaks Avast!

### ISSUE THREAD

**Issue by ingber** [EFForg/https-everywhere#7224]
From my Windows 10 Chrome (Version 53.0.2785.143 m) extension page:

Avast Online Security 11.1.0.955
Avast Browser Security and Web Reputation Plugin.
Details  Options
Warning:
This extension failed to redirect a network request to chrome-extension://gomekmidlodglbbmalcneegieacbdmki/common/mocks/empty.js because another extension (HTTPS Everywhere) redirected it to https://acdn.adnxs.com/prebid/c/6856/pb.js.
ID: gomekmidlodglbbmalcneegieacbdmki

**Comment by gloomy-ghost** [comment]
Looks like the same problem with #6034

**Comment by smw-koops** [comment]
@ingber http://www.howtogeek.com/239950/dont-use-your-antivirus-browser-extensions-they-can-actually-make-you-less-safe/

I request closing this as non-issue.

**Comment by lopatnov** [comment]
Error in extension://gomekmidlodglbbmalcneegieacbdmki/common/mocks/ga.js

**Comment by pipboy96** [comment]
Can't be fixed by us in any way.
