### ISSUE TITLE
Could we add rules to redirect one https to another?

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7253]
Examples:

For work correctly: #6894 

For work better: #6889

**Comment by anewuser** [comment]
You can use this extension to write custom redirects: https://github.com/einaregilsson/Redirector#download-links

**Comment by ivysrono** [comment]
@anewuser I am using it. However, it does not work in Android, does not for everyone.

**Comment by jeremyn** [comment]
I don't like redirecting domains, for example see the discussions in #2709 and #6905 . I might consider it if both domains were related and this could be verified. For example, I might allow redirects between the various Wikimedia projects listed [here](https://wikimediafoundation.org/wiki/Special:SiteMatrix).

We've already discussed this though so I'll let others contribute.

**Comment by anewuser** [comment]
@ivysrono Subscribe to this issue to know when Android support for Redirector is implemented: https://github.com/einaregilsson/Redirector/issues/29
