### ISSUE TITLE
Document all ruleset tests

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#7257]
We have many tests that aren't documented in [ruleset-testing.md](https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md):

```
test.sh
test/rules.sh
utils/ruleset_filenames_validate.py
utils/validate.sh
utils/trivial-validate.py
```

The scripts should also be more consistent about where they are located.

**Comment by J0WI** [comment]
In general all the stuff in `utils` and `test` needs to be documented/cleaned up. =/

**Comment by zoracon** [comment]
Checking in, how do you feel about the documentation? I plan on making this a summer project to clean up and update all docs in a sprint
