### ISSUE TITLE
Business Insider does not display article content in slide mode w/ httpsE

### ISSUE THREAD

**Issue by mcomella** [EFForg/https-everywhere#7266]
Slide mode appears to be enabled with the GET param, `op=0`.
## 

I originally opened: 
http://www.businessinsider.com/elon-musk-bill-gates-mark-zuckerberg-productivity-hacks-2016-9?op=0

And the article content did not appear. I disabled httpsE & the content appeared.

After re-enabling httpsE, I tried removing `?op=0` from the url and the page correctly loads. The new url is:
http://www.businessinsider.com/elon-musk-bill-gates-mark-zuckerberg-productivity-hacks-2016-9

I noticed in the bottom of the new article, "View as: One Page | Slides" had "One Page" selected. Clicking "Slides" adds the `?op=0` parameter, which again breaks the page.

**Comment by mcomella** [comment]
I should note that I'm using FF51 with [tracking protection](https://testpilot.firefox.com/experiments/tracking-protection?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged) on OS 10.11.6.

**Comment by jeremyn** [comment]
I can reproduce this problem on Windows 10, Firefox 49.0.1, HTTPS Everywhere 5.2.5. Disabling the [`BusinessInsider.com (partial)`](https://github.com/EFForg/https-everywhere/blob/7e015bdcd2b7b687566750d997776b1db2b9aba4/src/chrome/content/rules/BusinessInsider.xml) fixes the problem (meaning, allows the content to display).

I guess this is the error, from the [Firefox Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console):

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.businessinsider.com/assets/CMS/assets/templates/slideshow/controls.tpl. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I can confirm there is no `Access-Control-Allow-Origin` header in the response for `controls.tpl`.

Adding this exclusion to the ruleset linked above, somewhere around [here](https://github.com/EFForg/https-everywhere/blob/7e015bdcd2b7b687566750d997776b1db2b9aba4/src/chrome/content/rules/BusinessInsider.xml#L92), should fix the problem:

```xml
<exclusion pattern="^http://www\.businessinsider\.com/assets/CMS/assets/templates/slideshow/controls.tpl$" />
```

**Comment by gloomy-ghost** [comment]
There are still CORS problems but as far as displaying content is concerned I'll close this issue
