### ISSUE TITLE
Customize the path of HTTPSEverywhereUserRules?

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7270]
I want to move the path to my cloud drive, not in firefox's profile.

**Comment by jeremyn** [comment]
It looks like the path for custom rulesets is hardcoded in the add-on, see [here](https://github.com/EFForg/https-everywhere/blob/b6303ddb10f53606be1a9ea9cfe699e390c6f469/src/chrome/content/code/HTTPSRules.js#L198-L214).

Can you move your Firefox profile to your cloud drive? Or make a new profile?

**Comment by ivysrono** [comment]
I want to set different profiles get same custom rulesets.

**Comment by jeremyn** [comment]
Depending on your operating system and configuration, you might be able to put your custom ruleset directory on your cloud drive and then create "symbolic links" from that directory into your profiles. This is system configuration though, not HTTPS Everywhere configuration.
