### ISSUE TITLE
Insufficient test coverage error not triggered by wildcard target and no tests

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#7272]
The below ruleset, from pull request #7248 , has a `target` with a lefthand wildcard and no tests, so it should trigger the `Ruleset test coverage was insufficient.` error. However it doesn't trigger that error [in Travis](https://travis-ci.org/EFForg/https-everywhere/jobs/164522009) or when I run `fetch-test.sh` against it.

``` xml
<ruleset name="Vimeo Pro.com">
    <target host="vimeopro.com" />
    <target host="www.vimeopro.com" />
    <target host="*.vimeocdn.com" />

    <rule from="^http:" to="https:" />
</ruleset>
```

**Comment by cschanaj** [comment]
#11998

**Comment by jeremyn** [comment]
This is fixed now, thanks @cschanaj .
