### ISSUE TITLE
HTTPS Everywhere breaks area51.stackexchange.com login

### ISSUE THREAD

**Issue by fmitha** [EFForg/https-everywhere#7275]
I was unable to log in to area51.stackexchange.com till I disabled the HTPS Everywhere extension. I'm not sure what the problem is, but I thought I would report it here.

Version: 2016.9.21 for Chromium 53.0.2785.89-1~deb8u1 on Debian jessie.

**Comment by gloomy-ghost** [comment]
Were there any errors or warnings on your Console? It would be easier to track the problem if you could provide more informations.

**Comment by fmitha** [comment]
I'm not sure what you mean by the Console. Can you elaborate?

**Comment by gloomy-ghost** [comment]
Press F12 on the page where https-ew might causes some problems, you will
find a console tab with some errors such as mixed content blocking and CORS
blocking. It would be helpful if you could post those errors.

**Comment by gloomy-ghost** [comment]
stackexchange moved to full https. #9085
