### ISSUE TITLE
Tampa Bay.com (partial) breaks slideshow

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#7278]
http://www.tampabay.com/news/politics/stateroundup/former-congresswoman-gabrielle-giffords-survivor-of-2011-shooting-set-to/2295682

Tampa Bay.com (partial) breaks the slideshow. The second image is missing and you can't see the image caption.

**Comment by jeremyn** [comment]
I can't reproduce this on Windows 10, Firefox 49.0.1, and HTTPS Everywhere 5.2.5. Both images appear, and the captions appear when I click on the image. The left and right arrows don't do anything when I click them, but that's true with or without `Tampa Bay.com (partial)` active.

**Comment by terrorist96** [comment]
Can you try in Chrome? Seems to work in FF.

**Comment by jeremyn** [comment]
I get the problem in Chrome, but it happens even with HTTPS Everywhere disabled.

**Comment by terrorist96** [comment]
Interesting. Did you force refresh without cache (ctrl + F5)?
I just tried again and the slideshow works for me when I disable the tampa rule, and doesn't work when I re-enable the tampa rule.

**Comment by jeremyn** [comment]
Okay, I can reproduce the problem in Chrome now. Incognito mode seems to cache something in a way that ctrl-F5 doesn't break through, but re-creating the tab or using regular mode works.

**Comment by terrorist96** [comment]
It also breaks some images, like the print and comment icons.

**Comment by terrorist96** [comment]
No longer broken for me.
