### ISSUE TITLE
Chrome Extension 2016.9.21 Reports as Corrupted - Auto disabled by Chrome

### ISSUE THREAD

**Issue by Lithodus** [EFForg/https-everywhere#7280]
Extension version 2016.9.21 is automatically being disabled in Chrome. The error is "This extension may have been corrupted". All attempts to repair, or re-install end in the same error message.

**Comment by jeremyn** [comment]
Thanks for the report. I'm closing this issue as a duplicate of #5874 . Please see https://github.com/EFForg/https-everywhere/issues/5874#issuecomment-249885095 and the related discussion for more information and a workaround.
