### ISSUE TITLE
document howto install extensions directly from EFF 'Recent Releases'

### ISSUE THREAD

**Issue by TomRoche** [EFForg/https-everywhere#7282]
@ https://github.com/EFForg/https-everywhere/issues/6506#issuecomment-251862708 I attempt (in step#=8) to install the standalone Chrome extension=https://www.eff.org/files/https-everywhere-chrome-2016.9.21.crx from https://www.eff.org/https-everywhere section='Recent Releases'. (One more item for the TODO list: make sections linkable!) Unfortunately, that section has no instructions for the user regarding how to install extensions directly from EFF (i.e., from [the main page](https://www.eff.org/https-everywhere)), nor is there any matching content currently in [the FAQ](https://www.eff.org/https-everywhere/faq). Since installing directly should be useful for troubleshooting issues (e.g., #6506), I recommend documenting how to do direct installs (at least for the most popular browsers), either at that section='Recent Releases' (and make that linkable!) or in the FAQ.

**Comment by pipboy96** [comment]
`chromium --enable-easy-off-store-extension-install` seems to be the solution for Chrome, Firefox seems to have Store requirement hardcoded and requires you to download an "unbranded" version (for example Nightly or ESR).

**Comment by zoracon** [comment]
The download triggers in the browser as well these days. closing for now
