### ISSUE TITLE
CBS.Com videos not loading

### ISSUE THREAD

**Issue by atm0915** [EFForg/https-everywhere#7287]
The online cbs.com videos won't load with the extension. Apon disabling it, i was able to get it to load

**Comment by jeremyn** [comment]
Thanks for the report. Please give a specific link that shows the problem.

**Comment by atm0915** [comment]
http://www.cbs.com/shows/big-brother-over-the-top/video/8v2GPBtQbsiwk2AqQYcX48miVdgP7u3Y/big-brother-over-the-top-episode-1/

**Comment by jeremyn** [comment]
That link requires an account to see the video. Do you have a link that doesn't require an account?

**Comment by atm0915** [comment]
Yeah, didn't think about that

http://www.cbs.com/shows/ncis/video/CA2C1DF1-CF0A-B494-0A6D-6D1AF3768C44/ncis-being-bad/

**Comment by jeremyn** [comment]
Thanks. When I visit the second link in Firefox 49.0.1, Windows 10, with HTTPS Everywhere 5.2.5 enabled, the video in the center never loads, instead there is just a spinner that doesn't go away. When I disable HTTPS Everywhere entirely, the video eventually loads. Is that what you're seeing?

**Comment by atm0915** [comment]
Yes

**Comment by mnordhoff** [comment]
This is the Google APIs issue. #4545 #4918

**Comment by gloomy-ghost** [comment]
cbs adopted https so this shouldn't be an issue anymore
