### ISSUE TITLE
Fails weibo

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#7292]
HTTPS-EW enabled
https://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.18)
[Header] None
XMLHttpRequest cannot load https://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.18). No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

HTTPS-EW disabled
http://login.sina.com.cn/sso/login.php?client=ssologin.js(v1.4.18)
[Header] Access-Control-Allow-Origin: http://www.weibo.com
No errors
***
https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter...
[Header] None
XMLHttpRequest cannot load https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=http%…w.weibo.com%2Flogin.php&ua=php-sso_sdk_client-0.6.23&_rand=1475979103.8721. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.weibo.com' is therefore not allowed access.

Can't find this request after disable HTTPS-EW
***
Similar issue ref: #49 #6865 #7283
CC: @ivysrono

**Comment by ivysrono** [comment]
First: #7353

**Comment by J0WI** [comment]
closed by #7353
