### ISSUE TITLE
Recode.net (partial) breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#7312]
http://www.recode.net/2015/12/21/11621610/is-your-messaging-app-encrypted

`Recode.net (partial)` breaks images

**Comment by jeremyn** [comment]
Please clarify what's broken.

**Comment by terrorist96** [comment]
Images under "TRENDING" don't load.

**Comment by jeremyn** [comment]
What does "don't load" mean for you, exactly?

**Comment by terrorist96** [comment]
![1](https://cloud.githubusercontent.com/assets/12802056/19403881/103f27cc-9238-11e6-9f14-9b089c8b3cd4.PNG)
vs.
![2](https://cloud.githubusercontent.com/assets/12802056/19403880/103d0d66-9238-11e6-81bc-e105096937c7.PNG)

**Comment by mnordhoff** [comment]
I filed #7381 about this also affecting Racked.com. The Polygon.com ruleset was fixed a few months ago. It sounds like all Vox properties need to be checked for an `optimally_sized_images` endpoint.

**Comment by J0WI** [comment]
WFM. They finally use HTTPS now.
