### ISSUE TITLE
dreamhost.com and the possibility of new subdomains over time

### ISSUE THREAD

**Issue by galenide** [EFForg/https-everywhere#7313]
With the dreamhost.com domain, it appears that there are a number of subdomains under which third party sites are hosted, such as http://mug.dreamhost.com/, http://www.otismaxwell.dreamhost.com/, http://ovaltine.dreamhost.com/, http://crookedtimber1.dreamhost.com/, and http://apache2-xenon.shasta.dreamhost.com/. In addition, it appears that these subdomains for third party sites do not necessarily support HTTPS. As of this writing, the DreamHost ruleset has a wildcard rule for redirecting all subdomains by default to HTTPS, along with an exclusion list for subdomains that do not support HTTPS. From what it would seem, if it is possible over time for subdomains to be added under dreamhost.com for the hosting of third party sites, and with the subdomains not supporting HTTPS, then it may well be more useful for the DreamHost ruleset to have an explicit list of domains that should be redirected to HTTPS, and to only redirect domains on the list.

**Comment by mnordhoff** [comment]
Hostnames like "apache2-xenon.shasta.dreamhost.com" are for a specific Apache 2 instance (xenon) on a specific shared web server (shasta). I'm not sure breaking internal infrastructure that shouldn't really be accessed by the public or at all is much of a problem.

(I'm not sure what all of those hostnames are, though.)
