### ISSUE TITLE
Always connects to check.tpo when Torbutton is installed, even if Observatory has been disabled

### ISSUE THREAD

**Issue by rustybird** [EFForg/https-everywhere#7322]
If the Torbutton Firefox extension is installed, HTTPS Everywhere will connect to `https://check.torproject.org` to test if SSL Observatory submissions can be torified. But it will do so even when the Observatory has been disabled, which is the Tor Browser default.

Looks like the only way to avoid this connection is by setting the following two prefs (to [disable the `tor_safe` variable](https://github.com/EFForg/https-everywhere/blob/ea5703d84a96067c4e1e0ed7cf0ec983fe404686/src/components/ssl-observatory.js#L879) and [hence the Tor check](https://github.com/EFForg/https-everywhere/blob/ea5703d84a96067c4e1e0ed7cf0ec983fe404686/src/components/ssl-observatory.js#L781)):

```
user_pref("extensions.https_everywhere._observatory.use_custom_proxy", true);
user_pref("extensions.https_everywhere._observatory.use_tor_proxy", false);
```

**Comment by Hainish** [comment]
#7322 will fix this particular issue.
