### ISSUE TITLE
Does https-everywhere test rulesets on a regular cadence?

### ISSUE THREAD

**Issue by ClifHouck** [EFForg/https-everywhere#7325]
Not sure if this is an issue or not, depends on the answer to the title question.

It seems https-everywhere _does_ have a fair number of automated tests designed to check the validity of a given ruleset. However, I'm wondering how often an existing ruleset is re-checked. Functionally testing existing rulesets regularly could quickly identify regressions. However, I'm not familiar enough with the project infrastructure to tell if this is already done or not.

Anyone know?

**Comment by jeremyn** [comment]
All rulesets are checked for syntax/XML validation errors by Travis during code pushes etc. I know this because sometimes all the tests break because some ruleset with a validation error was merged.

Rulesets are not regularly checked that for example domains don't time out and test coverage is sufficient. I know this because it's a regular occurrence where someone wants to make a small update to a ruleset but then has to make other changes because the ruleset turns out to have other problems that make Travis fail.

[Here](https://github.com/EFForg/https-everywhere/blob/master/test/travis.sh) is the Travis script FYI.

**Comment by ClifHouck** [comment]
So it sounds like the answer to the original question is 'No.'.

My next question is: do https-everywhere maintainers think adding functional testing of rulesets on a regular cadence valuable?

**Comment by jeremyn** [comment]
There have been several discussions regarding automating parts of development/review process, such as https://github.com/EFForg/https-everywhere/issues/6912 . Having a program that duplicates what I do as a human reviewer would be extremely useful.

On the other hand creating a simple script that scans all the rulesets and lets us know that e.g. 1000 rulesets have some problem might be interesting, but it's unlikely that someone would dive into fixing them given our current open issues and pull requests. Also we're discussing purging HSTS preloaded rulesets (https://github.com/EFForg/https-everywhere/issues/7126) and I would not hurry to clean up rulesets that might just get deleted soon anyway.

**Comment by fuglede** [comment]
We already have the necessary infrastructure for mass checking-and-disabling existing rulesets across the database. Any ruleset with a `default_off='failed ruleset test'` (of which there currently are a whopping 1892) have had such mass-disabling occur to them. Now, as far as I recall/have been paying attention, no run has been performed in a while, but if you wanted to, it would be as simple as running [the checker](https://github.com/EFForg/https-everywhere/tree/master/test/rules) with the [appropriate configuration](https://github.com/EFForg/https-everywhere/blob/master/test/rules/disable-broken-rulesets.checker.config).

**Comment by jeremyn** [comment]
There is some discussion (https://github.com/EFForg/https-everywhere/issues/7338) about when rulesets should be disabled if they have some problem, though of course that discussion may just be me disagreeing how it's currently done.
