### ISSUE TITLE
HTTPSE breaks Boulder County voter registration

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#7327]
This reported from a user:

> Hi —
>
> I’m not sure if this is the appropriate forum, but I’ve noticed that HTTPS
> Everywhere is breaking the links to Boulder County’s voter registration.
>
> (if you go to the following page and then click on english or spanish
> voter registration)
> http://www.bouldercounty.org/elections/register/pages/register.aspx
>
> The link works fine if you turn off HTTPS everywhere.
>
> Just thought this was strange, and thought I’d pass it on.

**Comment by jeremyn** [comment]
This is fixed by PR #7328 .
