### ISSUE TITLE
Cloudfront.net breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#7330]
http://www.vegaspbs.org/election-2016/roundtable-discussions/

`Cloudfront.net` breaks video.

**Comment by theel0ja** [comment]
Screenshot about issue:

![Screenshot about what's happening (Using Vivaldi]
(https://i.imgur.com/K94jTNm.png)

**Comment by terrorist96** [comment]
http://www.pbs.org/wnet/tavissmiley/interviews/presidential-candidates-dr-jill-stein-gary-johnson-pt-1/?show=28582

**Comment by Jim-G** [comment]
Same problem with pbs.org videos, e.g., http://www.pbs.org/video/2365911408/
"cannot load M3U8: crossdomain access denied (2048)

**Comment by J0WI** [comment]
Does #8940 fix this?

**Comment by terrorist96** [comment]
@J0WI IDK, it hasn't been merged yet and HTTPSE hasn't been updated with the merge for me to test.

**Comment by J0WI** [comment]
@terrorist96 you can test it by just using HTTPS manually on this site.

**Comment by terrorist96** [comment]
It works.

**Comment by terrorist96** [comment]
This shoulda been closed.
