### ISSUE TITLE
[Request for ruleset modification] http://www.easyjet.com/

### ISSUE THREAD

**Issue by Wikinaut** [EFForg/https-everywhere#7336]
When trying to book flights, the calendar plugin fails to load unless you deactivate HE.
I would like to suggest you add a ruleset for Easyjet.

The website I use is http://www.easyjet.com/ or http://www.easyjet.com/de/

**Comment by Wikinaut** [comment]
better: to modify the existing ruleset.

**Comment by jeremyn** [comment]
Thanks for the report. Please describe the exact steps you take to see the problem.

For reference, [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/EasyJet.com.xml) is the existing `EasyJet.com.xml` ruleset.

**Comment by Wikinaut** [comment]
for some reasons, it works now (even after a restart of firefox). I close the issue and will reopen, _if_ the problems comes back.

In addition:
I had the issue on two different computers with Firefox + HE (Debian 8 and Mac OS El Capitan).

**Comment by MDawg957** [comment]
I can replicate this issue in Firefox ESR 45.4.0 with HTTPS 5.2.5 on Windows.

http://www.easyjet.com/en/

Picking an origin and then a destination and clicking on the calendar button or on Departing or Returning gives you a message that you have to pick a single destination.  Disabling easyJet.com (partial) and doing the same thing allows the calendar to load and the options to properly function.

**Comment by MaximeMorel** [comment]
Same here with Firefox 50, on Windows and Linux.
It seems to have the calendar working, these kind of request:
[http://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f](http://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f)
have to be rewritten to:
[https://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f](https://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f)

Not sure it's possible in the end, going to [https://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f](https://www.easyjet.com/en/?sc_itemid=b99b4c3b-6996-49a3-b815-840e7f2a731f) automatically redirects to http...

My tweaking attempts in [Easyjet.com.xml](https://www.eff.org/https-everywhere/atlas/domains/easyjet.com.html) were a fail...
