### ISSUE TITLE
TheWire.com partially broken

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#7339]
http://thewire.com/
http://www.theatlantic.com/thewire/ (previous link redirects here, but older articles also can use thewire.com link)

The page is partially broken due to the rule The Wire.com (partial).  Disabling it fixes things.

Firefox ESR 45.4.0 with HTTPSE 5.2.5

**Comment by jeremyn** [comment]
For reference: [`The_Wire.com.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/The_Wire.com.xml).

**Comment by smw-koops** [comment]
@MDawg957 How is it broken?

**Comment by MDawg957** [comment]
@smw-koops HTTPS on - https://i.imgur.com/E0kEZPR.png
HTTPS off - https://i.imgur.com/tzYB7JP.png

**Comment by galeksandrp** [comment]
http://www.theatlantic.com/thewire/ now redirects to https://www.theatlantic.com/news/
many other links redirects to https://www.theatlantic.com/... or https://www.theatlantic.com/.../archive/...
