### ISSUE TITLE
cant access HTTPS everywhere on the Tor browser I downloaded 2 days ago

### ISSUE THREAD

**Issue by HTTPSeverywherenotworking** [EFForg/https-everywhere#734]
The 'HTTPS everywhere' option in the drop down menu will not open so I cannot make any changes. Could I have downloaded a dodgy Tor browser? The Tor browser file says it was downloaded in 2001 when I look at it in my downloads folder.

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's still a bug.
