### ISSUE TITLE
https-everywhere doesn't catch URL loads on browser startup

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#7343]
I only tested this with Chrome.

When Chrome is closed and I fire it up by clicking a URL in Thunderbird or other external applications Chrome loads this URL but https everywhere seems to be still inactive and doesn't catch this load.

Is it possible to catch this first URL load?

**Comment by gitarra** [comment]
If you want this, you'll have to use Firefox. Firefox initializes addons during startup so that they are ready to catch the first page load.

**Comment by Atavic** [comment]
@gitarra Not always, see: https://github.com/gorhill/uBlock/issues/2067

**Comment by gitarra** [comment]
@Atavic I'm not going to read through that trainwreck of a bug report.

**Comment by geekyi** [comment]
@Atavic just fyi, that bug report you mentioned was for chrome

**Comment by gitarra** [comment]
Probably not as I have seen him only write bugspam that doesnt make any sense.

**Comment by Atavic** [comment]
Well, if you do not understand it, that doesn't automatically means that it doesn't make any sense, @gitarra

**Comment by geekyi** [comment]
By the way, is there any test suite / set of urls that I can use? I've not seen any special page in any of the https addons to check if they actually work. (I've been using stackoverflow)

**Comment by geekyi** [comment]
http://www.httpvshttps.com/ might last longer than stackoverflow.com

**Comment by Atavic** [comment]
> The browser does not wait for extensions to be fully loaded and ready before opening tabs, it's a by-design browser issue.

Applies to borh Firefox and Chrome.

**Comment by xftroxgpx** [comment]
Looks like Atavic is correct: https://bugzilla.mozilla.org/show_bug.cgi?id=1378459
(from https://github.com/gorhill/uBlock/issues/1327 )

I gotta admit, I doubted him at first, thinking that `it's by-design browser issue`, in [context](https://github.com/gorhill/uBlock/issues/2067#issue-182703928), referred to Chrome.

**Comment by Atavic** [comment]
:+1: And I got harsh replies for no motive.

**Comment by pipboy96** [comment]
This issue is known and can't be fixed on our extensions's side.
