### ISSUE TITLE
How to set a user defined proxy for firefox https-everywhere extension

### ISSUE THREAD

**Issue by yhnmj6666** [EFForg/https-everywhere#7349]
I'm a user from china and because of the GFW, the extension can't access observatory.eff.org:443. However, i noticed that there's some options about proxy for this extension in about:config, and i do have a local proxy to across the GFW. To make this extension work, i want to set a proxy for it, but don't know what value should i set for each option. could you give me a document or brief introductions ?

**Comment by Atavic** [comment]
Addons use the proxy set into the browser preferences or into the PAC file (if used).

**Comment by yhnmj6666** [comment]
thanks help a lot
