### ISSUE TITLE
To be or not : Redirect Invalid certificate https to working host

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7350]
For example: #6894 
https://*.gitbook.io/ will get Invalid certificate.
Should we redirect them to the working host by rules ?

Similar:
Ubuntu-CN.xml
We get lots https://*.ubuntu.org.cn/ , Invalid certificate.

**Comment by J0WI** [comment]
I would say yes, if the target redirects anyway. E.g. in case of help.gitbook.io.
Also for common cases like status subdomains.

But redirects like cdn. to cloudflare or amazonaws are quite dangerous, because they can break the site when they change. They need to be tested and maintained well.
