### ISSUE TITLE
Add houseoffraser.co.uk

### ISSUE THREAD

**Issue by jbrowngithubuser** [EFForg/https-everywhere#7360]
Valid:
apply.houseoffraser.co.uk
bond.houseoffraser.co.uk
bookings.houseoffraser.co.uk
corp.houseoffraser.co.uk
houseoffraser.co.uk
points.houseoffraser.co.uk
stores.houseoffraser.co.uk
suppliers.houseoffraser.co.uk
welcome.houseoffraser.co.uk
www2.houseoffraser.co.uk
yoursay.houseoffraser.co.uk

Valid (requires authentication):
development.houseoffraser.co.uk
staging.houseoffraser.co.uk

Valid (but redirects to HTTP version of same subdomain):
m.houseoffraser.co.uk
origin.houseoffraser.co.uk
www.houseoffraser.co.uk

Invalid:
answers.houseoffraser.co.uk
careers.houseoffraser.co.uk
ebm.emails.houseoffraser.co.uk
emails.houseoffraser.co.uk
f.emails.houseoffraser.co.uk
m.staging.houseoffraser.co.uk
mail.houseoffraser.co.uk
mail1.houseoffraser.co.uk
mail2.houseoffraser.co.uk
mta837.emails.houseoffraser.co.uk
press.houseoffraser.co.uk
recs.houseoffraser.co.uk
reg.emails.houseoffraser.co.uk
reviews.houseoffraser.co.uk
staging2.houseoffraser.co.uk
stories.houseoffraser.co.uk
ugc.houseoffraser.co.uk

**Comment by jeremyn** [comment]
FYI @jbrowngithubuser : I asked @gloomy-ghost to remove some of the URLs you requested from their original pull request, and so those URLs were not included in the new ruleset I merged in. Please see #7386 for more information.
