### ISSUE TITLE
Made a mistake when adding a user rule, can't edit or delete it

### ISSUE THREAD

**Issue by flussence** [EFForg/https-everywhere#7365]
I'm using version 2016.9.21 of the Chrome extension.

I thought I could add a rule for `http://([a-z]+\.)foo\.localdomain -> https://\1foo.localdomain` but it seems regex is only half-supported. Trying to overwrite it with another rule doesn't work, and I have no idea where this extension saves stuff (nor is it documented) so I can't even fix it by hand.

**Comment by Atavic** [comment]
The default Chrome profile directory is located at `%LOCALAPPDATA%\Google\Chrome\User Data\Default` under Windows and `~/.config/google-chrome/Default` under Linux.

**Comment by flussence** [comment]
Yeah, er, I know how XDG directories work, thanks. That's not helpful at all.

**Comment by Atavic** [comment]
https-everywhere stores the user created rules in an XML File there.

**Comment by J0WI** [comment]
At least for Firefox they are stored inside the `HTTPSEverywhereUserRules` directory. You need to restart your browser to apply the changes. To fix your rule you should try to replace `\1` with `$1`.

**Comment by flussence** [comment]
Sorry, but I'm going to have to cut you off there because these attempts at "help" are getting ridiculous and irritating, and completely miss the point.

First off, what you were *trying* to tell me is "the extension stores everything in `~/.config/chromium/<profile>/Local Storage/chrome-extension-gcbommkclmclpchllfjekcdonpmejbdp_0.localstorage`". Don't feel bad for giving me three non-answers though, it took me half an hour to figure out where on disk it was too.

For anyone else who fell into this trap, here's a slightly less horrific solution than surgically editing raw JSON in an SQL query by hand:

1. Open (Chromium|Chrome|Opera|Whatever)'s extensions page
2. Turn on "Developer Mode" at the top
3. Hit "inspect background page" under the extension
4. Open the "Application" tab
5. Open "Local Storage" in the left panel, "chrome-extension://(gibberish)" under that
6. Double-click the value of the "userRules" row to edit it
7. *Carefully* delete the broken entry in question by finding it, highlighting it and the surrounding `{…}`s, and hitting backspace
8. Repeat step 7 for any duplicate-by-name entries in the list, because nothing stops those from getting in even though the UI only picks one at random to display
9. Proofread that the end result is still valid JSON syntax with no trailing commas
10. Disable and reenable the extension to make it notice you've edited its database from underneath it

People shouldn't be expected to memorise a bunch of line noise file paths, the SQLite command set, or be experts in DOM and WebExtension hacking just to undo a simple typo. This is insanity.

*That* is the bug I'm reporting here. I see now that I should have spelled it out from the start — for that, I apologise.

**Comment by gloomy-ghost** [comment]
I think is's necessary to let users be able to modify custom rulesets in the popup window...

**Comment by Hainish** [comment]
This seems fixed when I attempt to reproduce the problem.  Closing for now, let me know if you still encounter this problem.
