### ISSUE TITLE
Ruleset test shouldn't fail for cacert if the website is marked with the cacert platform

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#7375]
I was editing the CCC-Cacert ruleset in  #6316 , which is marked with a platform tag of "CaCert".
So far so good, not everyone has imported their root cert.
The results of the checkin test script is confusing though.
https://travis-ci.org/EFForg/https-everywhere/builds/168084327 marks all domains as "error: self-signed"
although the Domains are listed in the cert properly.
In my humbe opinion the test should pass as the cert is valid (if you trust the root) for the domains in question.

**Comment by koops76** [comment]
Add `default_off="cacert"` to the ruleset and it will work.

**Comment by pipboy96** [comment]
`cacert` platform is deprecated now.
