### ISSUE TITLE
Migrate HTTPS everywhere to WebExtensions. Should be easy.

### ISSUE THREAD

**Issue by andreicristianpetcu** [EFForg/https-everywhere#7389]
Hi. I'm just a user not an addon dev but I think I migrated HTTPS everywhere to WebExtensions. It is signed and you can download it [from here](https://my.owndrive.com/index.php/s/AbSQmTzTN7mSirK).

This is how I did this. I installed [this addon](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) went to [chrome web store](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) and installed in inside Firefox.

I downloaded the xpi from Chrome web store with the Foxified extension, unzipped it and I ran this commands:

```bash
npm install -g web-ext
web-ext sign --api-key $API_KEY --api-secret $API_SECRET -s HTTPS_Everywhere
```

HTTPS_Everywhere is the folder with the unzipped xpi addon.

Why migrate to web extensions? They use async APIs so they are faster, only one codebase for both browsers.

**Comment by andreicristianpetcu** [comment]
web extensions APIs https://www.arewee10syet.com/

and browser status https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by gitarra** [comment]
Related: https://www.reddit.com/r/firefox/comments/58ge89/lighetr_unofficial_webextension_https_everywhere/

**Comment by Hainish** [comment]
HTTPS Everywhere is already migrated to WebExtensions, this is what the Chromium version of the extension runs. We maintain a codebase for this and will be moving to this for Firefox with the deprecation of XPCOM. https://github.com/EFForg/https-everywhere/tree/master/chromium

**Comment by andreicristianpetcu** [comment]
Why not publish the Chromium version in addons.mozilla.org instead of the XPCOM version? The XPCOM version uses a lot more resources than the WebExtension version on Firefox and it already works in Firefox. The deprecation of XPCOM might take a while.

**Comment by Hainish** [comment]
@andreicristianpetcu The WebExtensions addon works well in Firefox desktop, but currently certain UI elements are lacking in WebExtensions for Fennec.  Also, there is no API for inspecting the certificate chain in WebExtensions, which is necessary for us to continue to support submissions to the Decentralized SSL Observatory.  Lastly, Tor Browser is based on Firefox ESR, and some UI elements lack full support in ESR (which is at Firefox 45 currently).

**Comment by jwatt** [comment]
Doesn't Mozilla [Bug 1149250 - Ensure Web Extensions surface allowing manual http->https (secure update) redirects not blocked by CORS checks](https://bugzilla.mozilla.org/show_bug.cgi?id=1149250) need to be fixed? Or does HTTPS Everywhere not require that functionality any more somehow?

Also for anyone that's interested it looks like Mozilla [Bug 1322748 - Web extensions: SSL (TLS) status API request](https://bugzilla.mozilla.org/show_bug.cgi?id=1322748) is the bug that needs to be fixed to support submissions to the Decentralized SSL Observatory.

**Comment by heubergen** [comment]
Any update on this? Should't be this issue open as the XPCOM version is still published on AMO?

**Comment by Hainish** [comment]
No.  HTTPS Everywhere has already been migrated to WebExtensions.  We're unable to switch HTTPSE on Firefox over to WebExtensions until Tor Browser rebases in 52, as I already stated: https://github.com/EFForg/https-everywhere/issues/7389#issuecomment-255846606

This is already on the roadmap, there is no need to open an additional, Firefox-specific issue for this.

**Comment by z3ntu** [comment]
Tor Browser 7.0.1 is based on Firefox 52.2.0 😃

**Comment by Hainish** [comment]
Currently the main blocker to WebExtensions deployment on Firefox is a secure signing mechanism for the self-hosted version.  See https://github.com/EFForg/https-everywhere/issues/9958#issuecomment-302581089
