### ISSUE TITLE
DynStatus.com not working

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#7404]
Going to https://www.dynstatus.com/ causes an Insecure Connection message to pop up.  Disabling Dyn Status.com and then going to http://www.dynstatus.com/ allows the site to load properly (it swaps to HTTPS itself).

Firefox ESR 45.4.0, HTTPS 5.2.5, Windows 7

**Comment by Hainish** [comment]
This is most likely due to the DDoS against Dyn today.  It's working for me now.  Closing.
