### ISSUE TITLE
SLU.se rule not working

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#7502]
Seems to be some issues with 
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/SLU.se.xml
I think the space between " and /> should be removed
Please also add rules to these URLs: student.slu.se, internt.slu.se, universitetsdjursjukhuset.se

**Comment by gloomy-ghost** [comment]
There are some more subdomains. I can take this issue later.

**Comment by jony0008** [comment]
This line is not right <rule from="^http://internt\.slu\.se/" to="https://internet.slu.se/"/>
Please fix it.
