### ISSUE TITLE
Rule "InMotion Hosting.com" breaks sites

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#7593]
Test case:
http://www.inmotionhosting.com/support/website/modsecurity/what-is-modsecurity-and-why-is-it-important

**Comment by smw-koops** [comment]
Mixed content blocking blocks the stylesheet before HTTPS Everywhere has a chance to redirect it to HTTPS. It's the website problem. HTTPS Everywhere can't do anything to fix it.

**Comment by KommX** [comment]
I'm not sure if we understand each other correctly.
The http version of the site works fine. The https version doesn't. Probably that's the reason why they don't put a redirect themselves.

https everywhere users only see the broken site because they get redirected to the https site.
If this website has a problem with https and the rule can't be fixed then this rule should be deleted.

**Comment by Bisaloo** [comment]
@KommX, I can't reproduce. This seems fixed. Can you confirm and if you agree, close this issue?
