### ISSUE TITLE
Please add wizchan.org to rules [https://wizchan.org/]

### ISSUE THREAD

**Issue by isthisme** [EFForg/https-everywhere#7594]
By default wizchan.org doesn't use encryption.  Please add it to your ruleset so http://wizchan.org/ becomes https://wizchan.org/

**Comment by jeremyn** [comment]
@isthisme Thanks for your report, but for now please add new domain requests to issue #3069. See https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-261560271 . I'm closing this issue.
