### ISSUE TITLE
http://internt.slu.se/ will direct to https://internet.slu.se/ Please fix

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#7596]
internt.slu.se does not direct correctly and breaks to https://internet.slu.se

**Comment by jony0008** [comment]
internet.slu.se

**Comment by jeremyn** [comment]
This is fixed by open pull request #7504 , which should resolve issue #7502 . So, I'm closing this issue as a duplicate of issue #7502 .
