### ISSUE TITLE
vice.com (partial) breaks image/content

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#7598]
http://www.vice.com/en_us

`vice.com (partial)` breaks the search icon in the top right hand corner. Might be breaking other images too.

Edit: it's also breaking loading content when hovering your mouse over the Sections, Photos, etc tabs at the top.
Edit2: it also breaks loading more articles when you scroll to the end of the page.

**Comment by advaith1** [comment]
It works for me, and there is no search icon in the top right corner, or tabs at the top, with or without the extension.

**Comment by terrorist96** [comment]
Yep, looks like the site's layout has been updated. It's also super slow and laggy.
