### ISSUE TITLE
WordPress site not switching to HTTPS

### ISSUE THREAD

**Issue by Dangthrimble** [EFForg/https-everywhere#7631]
I have a WordPress site and the hosting company has switched on free SSL for testing over a 90 day period. However, though I can access the site via its HTTPS URI, https-everywhere is not making the switch automatically for me. Is this a problem with https-everywhere or WordPress?

**Comment by smw-koops** [comment]
HTTPS Everywhere only rewrites requests to websites hosted at WordPress.com. Tell your website's URL so I can make a rule for it.

**Comment by Dangthrimble** [comment]
http://www.crindau.org.uk/

**Comment by smw-koops** [comment]
@Dangthrimble Is https://mail.crindau.org.uk supposed to redirect to https://www.crindau.org.uk?

**Comment by Dangthrimble** [comment]
@smw-koops I take it you mean "Is http://www.crindau.org.uk supposed to redirect to https://www.crindau.org.uk?" If so, the answer is yes.

**Comment by smw-koops** [comment]
@Dangthrimble No. I meant exactly that. Is mail.crindau.org.uk supposed to redirect to www.crindau.org.uk?

**Comment by Dangthrimble** [comment]
@smw-koops Not something I've ever thought about. Is that normal?

**Comment by smw-koops** [comment]
@Dangthrimble I don't know.

**Comment by Dangthrimble** [comment]
@smw-koops So why the question? I'm confused.

**Comment by smw-koops** [comment]
@Dangthrimble Do you have any subdomains other than crindau.org.uk, mail.crindau.org.uk and www.crindau.org.uk?

**Comment by smw-koops** [comment]
@Dangthrimble I can't find any, just in case.

**Comment by Dangthrimble** [comment]
@smw-koops I haven't created any so, unless they have been created in the background by either WordPress or the site host, then no. And mail.crindau.org.uk does currently redirect to www.crindau.org.uk. Never knew that before.

**Comment by Dangthrimble** [comment]
Or a WordPress plugin, of course.

**Comment by Dangthrimble** [comment]
@smw-koops Presumably when/if the host turns off SSL at the end of the 90 days, https-everywhere will not prevent access to the site via http? Hopefully they'll decide to keep it turned on.

**Comment by smw-koops** [comment]
@Dangthrimble If your website will stop supporting HTTPS, then the rule should be removed. For the rule to be removed you need to open another issue or pull request.

**Comment by Dangthrimble** [comment]
@smw-koops How quickly do the changes impact access? Does https-everywhere access a registry each time a site is accessed?

**Comment by smw-koops** [comment]
@Dangthrimble I think the rules are stored inside the extension itself and update when the extension updates itself.

**Comment by Dangthrimble** [comment]
@smw-koops So if SSL does get turned off I will need to disable https-everywhere for the site whilst the rule change propagates to my extension.

**Comment by smw-koops** [comment]
@Dangthrimble I don't recommend dealing with a host that doesn't offer SSL for free for all customers at all.

**Comment by Dangthrimble** [comment]
@smw-koops I think they are intending to offer it for free, but they have only just started offering it.

**Comment by smw-koops** [comment]
@Dangthrimble Maybe. But most users will be able to use your website anyway.

**Comment by smw-koops** [comment]
@Dangthrimble Also if someone bookmarks a https link to your website or make a https link on their own website it won't function anymore if your host turns SSL off.

**Comment by smw-koops** [comment]
@Dangthrimble Maybe you can tell me what host did you use for the website?

**Comment by Dangthrimble** [comment]
@smw-koops [Godsweb.uk](https://mygodsweb.co.uk)

**Comment by smw-koops** [comment]
@Dangthrimble Maybe we can chat by email, instead of a GitHub issue? I sent you an email.

**Comment by jeremyn** [comment]
I strongly suggest that you do not create a ruleset for a site where you are only testing HTTPS. If you stop offering HTTPS then every user who has HTTPS Everywhere installed will not be able to access your site without manually disabling something. Rules are stored in the extension and changes need to be reviewed before they are merged. We have open pull requests that are well over six months old, so it's possible your users will have a broken experience for at least that long.

**Comment by Dangthrimble** [comment]
@jeremyn Happy to take your advice. Does that mean the addition listed above needs to be killed? Do I come back once the trial has been made formal?

**Comment by smw-koops** [comment]
@Dangthrimble Usually pull requests do not stay open for six months, they can get resolved quickly but sometimes they may also sink into the backlog,

**Comment by smw-koops** [comment]
@jeremyn Maybe make a disabled by default rule?

**Comment by Dangthrimble** [comment]
@smw-koops @jeremyn I bow to your collective knowledge in this area. Is it easier to enable a disabled rule once SSL becomes permanent rather than to then request the rule be created?

**Comment by jeremyn** [comment]
@Dangthrimble Yes, and I've already closed it. I suggest that when you're confident you'll keep HTTPS around for a while, you take a look at https://www.eff.org/https-everywhere/development and submit a pull request to us yourself.

Every ruleset is an additional maintenance and technical burden so we don't want to add them unless we need them. Disabled-by-default rulesets are appropriate for rulesets that are weirdly problematic due to their content, or old rulesets where the site is having new HTTPS problems. They shouldn't be used for maybe-in-the-future sites.

**Comment by Dangthrimble** [comment]
@smw-koops @jeremyn Thanks for the help and advice.

**Comment by jeremyn** [comment]
@smw-koops 

> Usually pull requests do not stay open for six months, they can get resolved quickly but sometimes they may also sink into the backlog,

Pull request resolution time can be random. We don't want to put anyone in a position where they need to submit a pull request that is time-sensitive.
