### ISSUE TITLE
Where is HTTPSEverywhereUserRules folder for Chrome and FirefoxForAndroid？

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#7635]
I only know the way to custom rules for Firefox PC.

**Comment by smw-koops** [comment]
It seems there is none, at least for Chrome, likely due to sandboxing limitations.

**Comment by jeremyn** [comment]
You can add simple rules using the HTTPS Everywhere GUI in Chrome but editing rules in a file is not easy or encouraged. See https://github.com/EFForg/https-everywhere/issues/1779 and https://github.com/EFForg/https-everywhere/issues/7365 . I recommend using Firefox for ruleset development and testing.

I don't know about Firefox for Android. I just looked around on an Android device with Firefox installed and didn't see an obvious place.

For reference, here's where that folder is discussed in the documentation: https://www.eff.org/https-everywhere/rulesets#testing .

**Comment by gloomy-ghost** [comment]
HTTPS Everywhere for Chrome will be marked as corrupted and get disabled if you change rules in `default.rulesets` since Chrome regularly checks hashes of extensions. You can try to directly modify `userRules` in its local storage, but be careful because they are squashed in one line.
