### ISSUE TITLE
'Google Images' ruleset blocks a iframe from accessing a cross-origin iframe

### ISSUE THREAD

**Issue by Foorack** [EFForg/https-everywhere#7647]
http://images.google.de/imgres?imgurl=https://blog.discordapp.com/content/images/2015/11/Discord-Logo-Wordmark-WnC.png&imgrefurl=http://blog.discordapp.com/how-to-get-the-most-out-of-your-community-server/&tbnid=OGj7kdSuALEW5M:&docid=oIseYIgOqyuczM

The 'Google Images' ruleset breaks the "Full-size image" button on the right side. Disabling the extension or this rule fixes it. The issue seems to be related to the iframe DOMException's thrown in console with the rule enabled. The issue only seems to appear on German Google, however, this is not yet confirmed.

**Comment by spooky360** [comment]
I have the same issue, Google France.

**Comment by clementhervy** [comment]
Same issue here, France as well. "Website for this image" and "Full-size image" links don't work if the rule is on.

**Comment by panicbit** [comment]
Can confirm, same issue here.

**Comment by panicbit** [comment]
Google seems to have the image search. The issue doesn't exist in the redesigned version anymore.

Here's a snap from the new version:
![google_images](https://cloud.githubusercontent.com/assets/628445/22717643/8ed3f986-ed9c-11e6-9281-fc7a16a5ca65.png)

**Comment by gloomy-ghost** [comment]
Close as fixed
