### ISSUE TITLE
Chrome Web Store Screenshot Update

### ISSUE THREAD

**Issue by gloomy-ghost** [EFForg/https-everywhere#7652]
The screenshot on [Chrome web store](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) is out of date, maybe update it during next release?

Ping: @Hainish

**Comment by Hainish** [comment]
@gloomy-ghost the screenshot has been updated and should propagate shortly.  Thanks for noticing this!
