### ISSUE TITLE
HTTPS rewrite for connect.asana.com causes 404

### ISSUE THREAD

**Issue by tdechangy** [EFForg/https-everywhere#7668]
Hi, when opening this link from a newsletter it brings to a 404 error page instead of the HTTPS one :   http://connect.asana.com/1L9Q-4MG6Y-NJ386K-2DOSJU-1/c.aspx

> I disabled the rule affecting that particular site in my own copy of HTTPS Everywhere by clicking on the HTTPS Everywhere toolbar button and unchecking the rule for that site.

**Comment by jeremyn** [comment]
I've updated the title to be more specific.

I can reproduce the problem. Whoever wants to fix this should probably start with [this `rule` in `Asana.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Asana.xml#L43-L44).
