### ISSUE TITLE
Add the option to rewrite bookmarks and browsing history

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#7671]
Bookmarks and browsing history still keep the plain version until you edit it manually.
We should offer to let HTTPS-Everywhere fix them for you as it saves one redirect and it is annoying to do that yourself manually.

**Comment by smw-koops** [comment]
This is non-issue. The redirect is done by HTTPS Everywhere before any request is sent so it doesn't add any extra latency.

**Comment by gloomy-ghost** [comment]
As @smw-koops said, HTTPS Everywhere redirects requests as soon as you click the bookmark/history. Also rewriting bookmarks and history will require extra permissions, which is unnecessary. Closing.
