### ISSUE TITLE
iStockphoto.com broken / cant login

### ISSUE THREAD

**Issue by ticky13** [EFForg/https-everywhere#7675]
iStockphoto.com (partial) refuses login if HTTPS enabled.

**Comment by jeremyn** [comment]
Thanks for the report. Is there a way to test this problem without having an iStockphoto.com account?

**Comment by ticky13** [comment]
It doesn't seem so, but you can sign up for an account for free.

**Comment by pipboy96** [comment]
I signed up (with a disposable email address) and was unable to reproduce this issue.
