### ISSUE TITLE
Broken on Firefox Nightly

### ISSUE THREAD

**Issue by gitarra** [EFForg/https-everywhere#7676]
Addon does not work on Firefox Nightly.

I am getting for syntax error in Browser Console.
https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/code/IOUtil.js#L130

Disable non-standard for-each:
https://bugzilla.mozilla.org/show_bug.cgi?id=1293305

**Comment by jeremyn** [comment]
@Hainish Pinging you to make you aware of this. We don't want another https://github.com/EFForg/https-everywhere/issues/5874 .

**Comment by numismatika** [comment]
I have seen that the menu is partially broken on my FF53 nightly , the top half is gone. Might be related.
![cut-off](https://cloud.githubusercontent.com/assets/6436819/20590886/f70c2526-b225-11e6-973d-e17a54b0b63d.png)

**Comment by jeremyn** [comment]
@smw-koops Does your pull request fix the problem @numismatika reported in the previous comment?

**Comment by smw-koops** [comment]
@jeremyn I don't know.

**Comment by numismatika** [comment]
Is there a way to make a beta test release to find out?

**Comment by jeremyn** [comment]
@numismatika Yes. You want to build an `.xpi` as described in [the README](https://github.com/EFForg/https-everywhere/blob/master/README.md).

**Comment by numismatika** [comment]
It doesn't like my Python Installation on Windows even if i try to install 2.7 again and lxml (which fails as well there).
On Linux it fails with various whitelisting issues.  Can't you just merge it upstream and release it?
I don't think it would break.

**Comment by jeremyn** [comment]
@numismatika Development on Windows isn't really supported, see the discussion around https://github.com/EFForg/https-everywhere/pull/5584#issuecomment-238396932 . What problems are you having with Linux?

**Comment by AlexBeLi** [comment]
Maybe it make sense to use msys/msys2?

**Comment by jeremyn** [comment]
@AlexBeLi I don't think MSYS or Cygwin will work. I even tried the new Bash on Windows functionality a while ago (see https://github.com/EFForg/https-everywhere/pull/5584#issuecomment-238581977) and that didn't work. I really recommend that anyone using Windows uses a Linux VM for HTTPS Everywhere development.

**Comment by numismatika** [comment]
@jeremyn first the whitelist was ignored.

Now with a fresh pull i get
> stat: calling of stat for 'translations/*' is not possible : file or folder not found

stat itself is a valid command though and the submodules where pulled and updated

**Comment by numismatika** [comment]
fixes my issue.
I forgot to init the submodules before building the xpi, that's what broke it.

**Comment by jeremyn** [comment]
@numismatika So (re)running `install-dev-dependencies.sh` fixed the problem?

**Comment by numismatika** [comment]
@jeremyn it was 
> git submodule update --init --recursive
Rulesets are visible again after building current master.
