### ISSUE TITLE
"Responsive images" broken on WordPress blogs (img srcset?)

### ISSUE THREAD

**Issue by roode** [EFForg/https-everywhere#7678]
Images in blog entries in {some|many|all} WordPress blog sites are broken.  See example of problem at [https://freethoughtblogs.com/pharyngula/2016/11/16/a-nose-balloon-too-far/](url)

The site supports https, but images in blog entries are apparently created with the "srcset" attribute on the `<img>` tag... with the alternate URLs coded as http.  I do not know if this is a WordPress bug, or a blog operator style preference or setting, or what.  I do not know why having the page's protocol set to https would fail to display (alternate) images with the http protocol--- bug?  security practice?  something else?

For now I will disable HTTPS Everywhere on WordPress sites I visit, but I will miss it. :-)

Below is the HTML code for one of the broken images on the example page above; you can see the inconsistent coding of image alternatives.

`<img src="//freethoughtblogs.com/pharyngula/files/2016/11/IMG_EE623E0B720D-1-500x500.jpeg" alt="img_ee623e0b720d-1" width="500" height="500" class="aligncenter size-large wp-image-32712" srcset="http://freethoughtblogs.com/pharyngula/wp-content/blogs.dir/3/files/2016/11/IMG_EE623E0B720D-1-150x150.jpeg 150w, http://freethoughtblogs.com/pharyngula/wp-content/blogs.dir/3/files/2016/11/IMG_EE623E0B720D-1-300x300.jpeg 300w, http://freethoughtblogs.com/pharyngula/wp-content/blogs.dir/3/files/2016/11/IMG_EE623E0B720D-1-768x768.jpeg 768w, http://freethoughtblogs.com/pharyngula/wp-content/blogs.dir/3/files/2016/11/IMG_EE623E0B720D-1-500x500.jpeg 500w, http://freethoughtblogs.com/pharyngula/wp-content/blogs.dir/3/files/2016/11/IMG_EE623E0B720D-1.jpeg 1080w" sizes="(max-width: 500px) 100vw, 500px">`

**Comment by smw-koops** [comment]
Mixed content blocking blocks the image before HTTPS Everywhere has a chance to redirect it to HTTPS. It's the website problem. HTTPS Everywhere can't do anything to fix it.

**Comment by gloomy-ghost** [comment]
HTTPS Everywhere only can rewrite mixed content on Tor Browser, See [/docs/rulesets.md#mixed-content-blocking-mcb](https://github.com/EFForg/https-everywhere/blob/cc746cb06fa4d53b95eb4b67b312d1e56917625e/docs/rulesets.md#mixed-content-blocking-mcb)

**Comment by gloomy-ghost** [comment]
MCB is implemented at browser side and sadly we don't have the chance to redirect the request when it is blocked by MCB.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1055750
