### ISSUE TITLE
Add version release date to 'About HTTPS Everywhere'

### ISSUE THREAD

**Issue by jbrowngithubuser** [EFForg/https-everywhere#7682]
Clicking the HTTPS Everywhere icon then 'About HTTPS Everywhere' shows the version number, but not the release date of that version. The release date is a quick way of telling how up-to-date the plugin is, and currently has to be worked out by looking up the version at https://github.com/EFForg/https-everywhere/releases

Can the release date be added, either in the same field (e.g. '5.2.6, 21 October 2016') or as a separate line/field?

**Comment by jeremyn** [comment]
Just FYI, you're describing the behavior on Firefox. Chrome/ium actually has the exact opposite problem: the version is given as a date everywhere it appears, and I can't find the version number `5.2.x` anywhere.

**Comment by gloomy-ghost** [comment]
[/chromium/manifest.json#L47](https://github.com/EFForg/https-everywhere/blob/4131c79805912785ea8ea2b4568f5621f21dbe19/chromium/manifest.json#L47)

`#DEFINE VERSION getdate("%y.%m.%d")` 😆

**Comment by gloomy-ghost** [comment]
The version number is the date of release now
