### ISSUE TITLE
privacy breach: loads FAQ from the network after installation

### ISSUE THREAD

**Issue by real-dam** [EFForg/https-everywhere#769]
Reported in Debian as https://bugs.debian.org/771286

The first time the browser is started after installing https-everywhere, a notification bar is shown, informing of the fact that some https enforcement is active and pointing to the toolbar button for options.

What is bad about that is that when the notification is dismissed, the browser is forced to open https://www.eff.org/https-everywhere/faq

This is a privacy breach, as it informs the authors (and user's ISP) that there is a new installation of https-everywhere.

The patch at http://anonscm.debian.org/cgit/pkg-mozext/https-everywhere.git/tree/debian/patches/no-unconditional-FAQ-load.patch adds a dedicated button to the notification bar. Pressing that button loads the FAQ page as before, and just dismissing the notification bar does nothing. In other words, it makes the user *request* the FAQ before loading it.

**Comment by StevenRoddis** [comment]
I have a feeling extensions on AMO/Chrome web store also send installation data?

**Comment by semenko** [comment]
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.

[There are lots of ways to identify HTTPSe users, since you'll be accessing uncommon HTTPS domains after installation.]

**Comment by real-dam** [comment]
OK. The pull request is coming. Not sure how to reopen this issue.
