### ISSUE TITLE
Project: Find all the HTTPS Everywhere rules that can be HSTS rules

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#77]
Someone should take this project; it sounds fun!

The idea is to write a program that parses HTTPS Everywhere rules and detects which ones can be equivalent to HSTS preloads. Seth took a stab at it in utils/simple.py, but it needs some work.

Once we have a list of rules from HTTPS Everywhere that can be used to expand the built-in browser HSTS preload list, there's a couple of awesome things we can try:
* Offer this list as a download to developers writing software/apps that would benefit from STS.
* Since it's impossible to make HTTPS Everywhere for Safari, the next-best thing seems to be adding this list to ~/Library/Cookies/HSTS.plist in Mavericks. This file remembers STS for Safari and possibly other apps as well.
* Perhaps we can completely replace these rules in FF and Chrome by STS preloads so that we use the browsers' built-in STS mechanism for switching domains to HTTPS rather than HTTPS Everywhere's. This might help with performance issues.

**Comment by jsha** [comment]
Closing. I don't think it's safe to inject HSTS headers for sites, since that means any certificate error turns into a hard fail (can't click through it). I think it really needs to be at the site owner's discretion to turn on HSTS.
