### ISSUE TITLE
Videos on the Daily Express website don't work 

### ISSUE THREAD

**Issue by OrganizedStalking** [EFForg/https-everywhere#7702]
The videos on the Daily Express website doesn't work when you have HTTPS Everywhere enabled. An example can be found here http://www.express.co.uk/news/world/736223/9-11-tower-Building-7-collapse-fire-conspiracy

**Comment by numismatika** [comment]
There is a Daily Express rule.
For me the videos play, even though there is mixed-content in play.
Which rules are active for you on this site?

**Comment by OrganizedStalking** [comment]
I just tested it again and it appears to work now. Maybe it was fixed in the new version 5.2.8.
I was using the default settings/rules.

**Comment by Bisaloo** [comment]
@OrganizedStalking, I checked and this is indeed fixed. Can you close this issue?
