### ISSUE TITLE
Pluralsight: The current rule breaks the bookmarks-section

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#7704]
http://app.pluralsight.com/bookmarks just doesn't show the bookmarks when the rule "pluralsight.com" is enabled.
Disabling the rule fixes this issue.

Hint:
When the rule is enabeld I can see this in the developer console:

> XMLHttpRequest cannot load https://app.pluralsight.com/templates/user/bookmarks.html. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://app.pluralsight.com' is therefore not allowed access.

**Comment by Bisaloo** [comment]
This should be fixed by #15157. I'm closing this issue. Please feel free to report back if you are still having issues.
