### ISSUE TITLE
Toonami.com not loading properly

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#7705]
http://toonami.com
http://www.adultswim.com/toonami/ (redirects here)

Most of the page's content does not load until the Amazon Web Services rule is disabled and then everything loads properly.

https://i.imgur.com/CPd16o7.png - how the page looks before AWS is disabled.

HTTPSE 5.2.7, Firefox ESR 45.5.0, Windows 7 64-bit

**Comment by gloomy-ghost** [comment]
Seems fixed
![default](https://user-images.githubusercontent.com/13086421/31574982-1ad1f096-b138-11e7-9d9e-e889624d7588.png)

**Comment by MDawg957** [comment]
It still gets stuck on that loading page for me until I turn off AmazonWebServices.

HTTPSE 2017.10.4, Firefox ESR 52.4.0, Windows 7 64-bit

**Comment by pipboy96** [comment]
This issue seems to have been fixed again.
