### ISSUE TITLE
"ReferenceError: can't access lexical declaration `HTTPSEverywhere' before initialization " in latest Firefox Nightly

### ISSUE THREAD

**Issue by Vednier** [EFForg/https-everywhere#7712]
Well, it seems that several days ago in Firefox Nightly something have changed so https-everywhere
 started to spam tons of identical error messages to console in latest Nightly:

ReferenceError: can't access lexical declaration `HTTPSEverywhere' before initialization  toolbar_button.js:409:7
	migratePreferences chrome://https-everywhere/content/toolbar_button.js:409:7
	bound migratePreferences self-hosted:971:17

HTTPSEverywhere version is 5.2.7, Nightly version is 53.0a1 (2016-11-29) (64-bit)

**Comment by Vednier** [comment]
Oh, just as addition - i dont sure but it looks like HTTPSEverywhere is kinda crippled now, Show Counter option doesn't do anything as well as rules used is not showing. Not a big deal.

**Comment by jeremyn** [comment]
I wonder if this is related to issue https://github.com/EFForg/https-everywhere/issues/7676. Version 5.2.8 is coming out soon, which should fix https://github.com/EFForg/https-everywhere/issues/7676. Please let us know whether you get the problem in this current issue with the new version after it's released.

**Comment by Vednier** [comment]
Yes, disappeared since 5.2.8. Thanks to all.

**Comment by jeremyn** [comment]
Great! Thanks for the feedback.
