### ISSUE TITLE
Trouble understanding a problem with Travis on my fork

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#7713]
As a contributor i forked the eff-master branch to my local master branch.
Then there is my rule_lab branch that is my experimental branch and gets all ideas that i am currently working on.
Once i am rather confident, i create a new branch from master and cherry pick the commits from rule_lab for the specific page and make a pull request.

To check for possible issues that need solving i use the same travis testing scripts running on the eff branches.
The only thing that i don't understand is the following:

> - When i commit changes to my rule_lab branch, travis ignores these changes and marks the check green after about 30 seconds.
> - The same changes on a future pr-branch get tested and end up with a red error  (i had duplicated hosts or typos in there

Why does travis skip these files on my experimental branch? What criteria is different`?
There are over 150 changes on my rule.lab branch compared to the master, so there should be plenty to test and possible fail on. Can someone explain this and hopefully tell me how to fix it?

**Comment by jeremyn** [comment]
I usually run `./fetch-test.sh rules/MyRuleset.xml` or similar when I want to test a specific ruleset. For more testing you can run `./test.sh` like it says in [`README.md`](https://github.com/EFForg/https-everywhere/blob/master/README.md). Be careful with testing any other way, including running `travis.sh`, because there are various config files and logical paths that can surprise you if you're not careful.

**Comment by numismatika** [comment]
I do not run them manually, they are run automatically if i push all my local changes to the github repo.
If i make a mistake like in https://github.com/numismatika/https-everywhere/tree/LGT2
i get an error in my results  as in https://travis-ci.org/numismatika/https-everywhere/builds/179776526
On the rule_lab branch https://github.com/numismatika/https-everywhere/tree/rule_lab
everything is always green:
https://travis-ci.org/numismatika/https-everywhere/builds/179913698
As you can see in the last test
https://travis-ci.org/numismatika/https-everywhere/jobs/179913704
not even a single url was really tested.
I don't see the diffrence between those two branches/results.

**Comment by jeremyn** [comment]
I don't know the details -- they should be discoverable in the public code -- but some of the tests have a way of identifying what's changed and only testing the changes.

Having a huge branch with a lot of mixed up changes is not how git is usually used. The identifying-changes logic might be confused by that. The more usual approach is to use separate branches for each small, related group of changes.

**Comment by numismatika** [comment]
Yes i do have those, but they are piling up faster then they get reviewed and merged so i need to store the work somewhere while i use it for personal profit and quality assurance.
Travis.sh is public, i just don't understand the logic

**Comment by jeremyn** [comment]
I'm not sure what you mean about storing the work. You can have branches in your public repository that you don't make pull requests from.

Anyway specifically about Travis, I'd have to trace through the logic to figure it out.

**Comment by jeremyn** [comment]
@numismatika I'm checking in on this issue and I'd like to resolve it somehow. What specifically would you like to know before you consider this issue closed?

**Comment by numismatika** [comment]
@jeremyn i would like to know why travis only does proper tests on pullrequests i make and not on my own repo branches and therefore a clue on how to get that back to a working state.
Opening pull requests before the rule is ready and then amending commits is a bit ugly.

**Comment by galeksandrp** [comment]
Since #8948 is merged, your branch can't be behind https://github.com/EFForg/https-everywhere/commit/master more than 50 commits (that's because testing scripts fetch additional remote with depth 50, and then finding merge base with master of that shallow remote and HEAD of your branch).

**Comment by numismatika** [comment]
With the additional sleeps in the base branch now, it should be no longer that much of an issue
