### ISSUE TITLE
When downgrade rules are appropriate

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#7717]
Continuing discussion in #7646, when is it appropriate to use downgrade rules. Downgrade rules should be whitelisted, showing that they should be avoided if possible, however it's not clear when they are allowed.

For instance, are they allowed to:

1. Avoid 404 error?
2. Avoid invalid certificate?
3. Avoid redirect to a wrong page?
4. Avoid broken page UX if mixed content blocking is enabled?
5. Avoid broken page functionality if mixed content blocking is enabled?
6. Avoid broken page UX even if mixed content blocking is disabled?
7. Avoid broken page functionality even if mixed content blocking is disabled?

**Comment by jeremyn** [comment]
Pinging @fuglede @gloomy-ghost @Hainish @J0WI .

**Comment by jeremyn** [comment]
I want to note here that @smw-koops was nice enough to remove their downgrade from pull request #7646 so we could move forward with it while this discussion is happening.

**Comment by J0WI** [comment]
From a technical aspect they are appropriated whenever a (protocol) relative link does not behavior the same on https than on http.
I don't know if there are any scenarios with mixed content, I think most will hit point 2.

**Comment by J0WI** [comment]
I think we can get rid of downgrade rules anyway, see #8833.

**Comment by jeremyn** [comment]
Getting rid of all of them is the best solution if possible.

**Comment by Hainish** [comment]
Thanks @J0WI @jeremyn. Can I close this?

**Comment by jeremyn** [comment]
I think this issue can be closed. Maybe another should be opened by someone, sometime, to remove the technical ability to create downgrades at all, and remove any related documentation too.
