### ISSUE TITLE
Fox News (partial) breaks video

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#7721]
http://insider.foxnews.com/2016/11/30/judge-napolitano-reacts-muslims-islamberg-arming-confrontation-after-trump-win

`Fox News (partial)` breaks the video. This used to work not too long ago.

**Comment by terrorist96** [comment]
http://rare.us/story/after-a-guest-on-his-show-compared-trump-to-hitler-and-then-accused-him-of-name-calling-tucker-carlson-cant-help-but-point-out-her-hypocrisy/

**Comment by gloomy-ghost** [comment]
```
Mixed Content: The page at 'https://scdn.cxense.com/p1.html...' was loaded over HTTPS, but requested an insecure script 'http://cdn.cxense.com/cx.js'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://scdn.cxense.com/p1.html...' was loaded over HTTPS, but requested an insecure script 'http://p1cluster.cxense.com/p1.js'. This request has been blocked; the content must be served over HTTPS.
```

I can confirm that there are some mixed content blocking when https-ew is enabled, but the video is broken even https-ew is disabled.

**Comment by terrorist96** [comment]
Really? I just tested it again. The video doesn't play with `Fox News (partial)` enabled, but will work if I disable that rule. Tested on Chrome.

**Comment by terrorist96** [comment]
http://www.theblaze.com/news/2017/03/25/louie-gohmert-explodes-over-gop-leaderships-lie-to-trump-freedom-caucus-about-health-care-bill/

**Comment by terrorist96** [comment]
https://www.facebook.com/RepThomasMassie/posts/1533849316639227

**Comment by terrorist96** [comment]
http://www.foxbusiness.com/features/2017/04/13/judge-napolitano-dragged-united-passengers-lawyer-leaves-airline-defenseless.html

**Comment by terrorist96** [comment]
http://lawnewz.com/high-profile/judge-napolitano-now-calls-for-jailing-serial-liar-susan-rice/

**Comment by terrorist96** [comment]
http://www.foxbusiness.com/features/2017/04/13/judge-napolitano-dragged-united-passengers-lawyer-leaves-airline-defenseless.html

**Comment by terrorist96** [comment]
http://www.ronpaullibertyreport.com/archives/ron-paul-get-out-of-syria

**Comment by bardiharborow** [comment]
That ruleset has other big issues (#4330) as well.

**Comment by gloomy-ghost** [comment]
massive close per #15157
