### ISSUE TITLE
sbs video blocked 

### ISSUE THREAD

**Issue by KodeToad** [EFForg/https-everywhere#7726]
www.sbs.com.au mostly works with httpseverywhere enabled, but for videos.
Enabled, the videos timeout. Once disabled, videos work fine.
There also seems to be some mixed content that isn't working when logging in from the ondemand part of the site. I was able to logon only from the landing page.

**Comment by gloomy-ghost** [comment]
Could you provide a URL that is having problem?

**Comment by hughbragg** [comment]
Very sorry I provided the wrong url. I updated the original and here it is again. http://www.sbs.com.au
Any video I tried has this problem.

**Comment by gloomy-ghost** [comment]
I don't have an account for playing videos. Can you check the console errors (F12) when https-ew is enabled?

**Comment by hughbragg** [comment]
That's part of the problem. The whole creating an account and signing in from the ondemand part of the site fails to. http://www.sbs.com.au/ondemand
Anyone should be able to create an account there. I'm fairly certain you can use a disposable email address.

**Comment by hughbragg** [comment]
HTH
[www.sbs.com.au-1481399690683.txt](https://github.com/EFForg/https-everywhere/files/644015/www.sbs.com.au-1481399690683.txt)

**Comment by pipboy96** [comment]
Can't be verified without AU IP, last update 2016.
