### ISSUE TITLE
Ruleset for www.shabdkosh.com

### ISSUE THREAD

**Issue by ankitpati** [EFForg/https-everywhere#7744]
Please consider the ruleset for [this site](https://www.shabdkosh.com/ "Shabdkosh | शब्दकोश") in PR #7743

**Comment by jeremyn** [comment]
Thanks, but there is no need to have both this issue and the pull request, so I'm closing this issue.

**Comment by ankitpati** [comment]
Please pardon my inexperience with this project. Some other projects require an issue to even consider a PR.

**Comment by jeremyn** [comment]
Don't worry about it, and thanks for contributing.
