### ISSUE TITLE
Rule "Giant Bomb (partial)" breaking site

### ISSUE THREAD

**Issue by SteveEasley** [EFForg/https-everywhere#7787]
There was a new video player for Giant Bomb released, and the svg icons are not loading because they are being forced to load via SSL, when the site is not SSL ready yet (causing mixed content errors). Notice the player here is missing the controls: http://www.giantbomb.com/videos/best-of-giant-bomb-112-chief-beef/2300-11742/, which is a result of the failing http://www.giantbomb.com/bundles/phoenixsite/images/core/sprites/icons/svg/icons-sprite-min.svg. Disabling the rules fixes it.

I assume the confusion here is that while there is an SSL cert installed for www.giantbomb.com, its not fully SSL ready (CDN links need to be converted). Can it be removed for now (or have the rules fixed)?

This also applies to www.gamespot.com and comicvine.gamespot.com.

**Comment by pipboy96** [comment]
No longer reproducible, player was replaced with YouTube.
