### ISSUE TITLE
ct.gov rule no longer works

### ISSUE THREAD

**Issue by sometimegithubuser** [EFForg/https-everywhere#7840]
The rule for ct.gov no longer works. The ct.gov web site has been completely re-done and the redirect site (https://www.ct.egov.com/) is no longer valid. So the rule:

`<rule from="^http://(?:www\.)?ct\.gov/.*" to="https://www.ct.egov.com/"/>`

takes me to a 404-not found error site. 

I addition I cannot disable the rule. Either I turn off HTTPS Everywhere and get to portal.ct.gov site with no ability to disable the rule, or I leave it turned on, get redirected to non-functional site and then find that HTTPS Everywhere says that there is no rule for the site.

**Comment by jeremyn** [comment]
Thanks for the report.

On Firefox, you can disable the CT.gov rule by typing the domain into the address bar and, without pressing enter and loading the site, disabling the rule through the HTTPS Everywhere user interface. I can't get the same trick to work on Chromium, unfortunately.

**Comment by pipboy96** [comment]
This redirect no longer happens on current version of HTTPS Everywhere.
