### ISSUE TITLE
Weibo's certificate is invalid

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#7852]
[Weibo's](http://www.weibo.com/login.php) SSL certificate is invalid, so the ruleset should be disabled.

**Comment by gloomy-ghost** [comment]
Thanks for reporting.

@ivysrono Could you take this issue?

**Comment by ivysrono** [comment]
简单看了下，渣浪全系可以重写了。
工程浩大……

**Comment by ivysrono** [comment]
#7860 慢慢干吧。

**Comment by ivysrono** [comment]
终于算是基本重构了一遍，累死了，比 #7548 写搜狐都类，渣浪实在是令人无语。

**Comment by gloomy-ghost** [comment]
Closed by #7961
