### ISSUE TITLE
idnes.cz does not work with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by Alex-007-** [EFForg/https-everywhere#7903]
Hello,
I can't load following page because of plugin in Firefox and Chrome:
http://technet.idnes.cz/
I mention this page, but it is related to most of the pages on:
idnes.cz
Issue is solved as soon as I disable the addon (it is NOT enough to switch it off). I use "HTTPS everywhere" already long time, but this issue appeared as new.

**Comment by jeremyn** [comment]
Thanks for the report. I've updated the issue title to be more specific.

**Comment by J0WI** [comment]
@Alex-007- I don't have any issues, can you confirm that this has been fixed?

**Comment by jankratochvil** [comment]
idnes.cz does have https support now; although it is still mixed content.  Still the rules are fragile as they test only rajce websites for all idnes.cz sites and rajce appears to have some separate administration (as in the past rajce had https working while the rest of idnes.cz did not).

**Comment by J0WI** [comment]
So can we just solve this by adding `platform="mixedcontent"`?

**Comment by krejmaj** [comment]
All issues with idnes.cz should be fixed except for topkontakt.idnes.cz which is just a redirect
