### ISSUE TITLE
Chrome mixed content fires before HTTPS Everywhere gets a chance to rewrite

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#793]
This is a tracking ticket for the Chrome bug:

https://code.google.com/p/chromium/issues/detail?id=122548

This prevents HTTPS Everywhere from rewriting internal resources before they get blocked for being mixed content.

**Comment by Bisaloo** [comment]
Tracking issue for Firefox:

https://bugzilla.mozilla.org/show_bug.cgi?id=878890

**Comment by Bisaloo** [comment]
The same issue on Tor bug tracker: https://trac.torproject.org/projects/tor/ticket/3777

**Comment by pipboy96** [comment]
Closing since it's a browser issue, not a HTTPS Everywhere code base issue. If you believe this is a mistake, feel free to reopen.
