### ISSUE TITLE
ksl.com doesn't work with HTTPS everywhere enabled

### ISSUE THREAD

**Issue by richiepreece** [EFForg/https-everywhere#7933]
More specifically, the [weather radar](http://www.ksl.com/?nid=175) doesn't work

**Comment by jeremyn** [comment]
Thanks for your report. Please clarify what you mean by "doesn't work". This will help a future reviewer understand the problem even if, for example, the site behavior later changes or you're not available to provide more information.

**Comment by richiepreece** [comment]
The page refreshes over and over and never actually shows content.

**Comment by advaith1** [comment]
I have just tested this, the reason is every time it loads the page using TLS, it redirects to the insecure version. With HTTPS Everywhere, it keeps redirecting back to the secure version, so it is trapped in a redirect loop.

**Comment by pipboy96** [comment]
Website returns "Forbidden", whether with HTTPS Everywhere or not.
