### ISSUE TITLE
Point out difference b/t HTTPSE and Smart HTTPS in FAQ

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#7936]
e.g. downgrade susceptibility with smart https, not working with when resource is on difft subdomain or path

**Comment by jeremyn** [comment]
Did someone ask this question "in the wild"? I'm wondering who the audience for this question is: security professionals, non-technical activists? There are trivial differences like `securecookie`, but the difference that really matters is that HTTPS Everywhere rulesets have been curated by people over possibly thousands of hours while Smart HTTPS is just an automated program. How we "sell" HTTPS Everywhere vs an automated program depends on who we're talking to.

**Comment by jeremyn** [comment]
On https://addons.mozilla.org for the HTTPS Everywhere add-on, there's [a review](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/reviews/832794/) that says: "It's a Great Addon, i only have one question: Isn't HTTPS already default on Firefox?" Do we want this FAQ to cover this person's question?

**Comment by Hainish** [comment]
@jeremyn yes, there was an inquiry that came in to the info@eff.org email address.  That's why I think it would be good to address it.  Lots of people complain about the memory usage of the addon, and I think it'd be a good question to address and point out that there's a huge benefit that comes with the memory cost.

btw I just limited the discussion on this issue b/c I mean this to just be a reminder to myself to create a PR for this, I don't want it to get too freewheeling.  once we have a PR that can lead to a discussion, I just don't want to forget to do this

**Comment by jeremyn** [comment]
> I don't want it to get too freewheeling

Sure, that's fine. Please ping me when you submit the pull request.

**Comment by Hainish** [comment]
Will do!

**Comment by pipboy96** [comment]
Why was this even locked?

**Comment by Hainish** [comment]
This was answered in https://github.com/EFForg/https-everywhere/issues/7936#issuecomment-268415082.

Please do not undo the actions of repo maintainers without clearing it with them.

**Comment by pipboy96** [comment]
@pipboy96 Sorry, the reason I removed the lock is that you locked it from the beginning, without reason for lock (now GitHub allows specifying reason), and that apparently there was no such "complaints" anymore.

**Comment by pipboy96** [comment]
I want to actually write a section explaining how both extensions work and what's the problem with S-HTTPS, and why it does not apply to HTTPS Everywhere and EASE mode.

**Comment by Hainish** [comment]
@pipboy96 that sounds great!
