### ISSUE TITLE
Access to NetApp Technical Reports broken

### ISSUE THREAD

**Issue by knerhood** [EFForg/https-everywhere#7946]
When enabled the NetApp.com (partial) rule now breaks access to the NetApp technical reports section of their website.

For example there is no https access to the following report http://www.netapp.com/us/media/tr-4517.pdf

When you try to access via https with the rule turned on you get File Not Found.

Turning off the rule does allow access.

--ken

**Comment by Folant** [comment]
Works fine for me.

**Comment by J0WI** [comment]
WFM too. Please reopen with more details if the issue still exists.
