### ISSUE TITLE
Akamai and CloudFront.net rules break videos on cbc.ca

### ISSUE THREAD

**Issue by mtughan** [EFForg/https-everywhere#8008]
Videos on CBC's website don't seem to play when HTTPS Everywhere is enabled with its default rule set. I believe I've tracked it down to the Akamai and CloudFront.net rules: videos don't seem to play if either rule is enabled, but they do play if they're both disabled.

Tested using this news story: http://www.cbc.ca/news/canada/toronto/ttc-bus-queen-and-sherbourne-1.3916146

HTTPS Everywhere 5.2.9
Firefox 50.1.0
macOS 10.12.2

**Comment by numismatika** [comment]
Works for me here with the flashplayer and 7 enabled rules, even without cookies enabled.

**Comment by gloomy-ghost** [comment]
I can't reproduce the issue neither, close as WFM
