### ISSUE TITLE
Conflict with Tab Mix Plus Firefox extension

### ISSUE THREAD

**Issue by Wskyy** [EFForg/https-everywhere#8125]
Whenever I enable HTTPS Everywhere it seems to break some of the functionality of TMP. The Xs on each of the tabs disappear and when I click on New Tab two fixed tabs will appear and am unable to X them out.  They stay fixed and cannot be used. Problem goes away if I disable HTTPS Everywhere. I have no clue how because HTTPS Everywhere affects a totally different part of the browser.  The problem can be annoying so I simply leave HTTPS everywhere disabled, but many sites default to http without my noticing it so it would be nice if these extensions could work together.

There has been another problem reported by others also http://tabmixplus.org/forum/viewtopic.php?f=2&t=18603&p=64901&hilit=https+everywhere#p64901

**Comment by TheFinalCut83** [comment]
What is your configuration? I've tried in Win 7 x64, portable FF 50.1, only HTTPS Everywhere and stable Tabmix from AMO store and couldn't reproduce.

> There has been another problem reported by others also http://tabmixplus.org/forum/viewtopic.php?f=2&t=18603&p=64901&hilit=https+everywhere#p64901

That was in 2014, everything should be allright now. I'm using Tabmix devbuilds for years and HTTPS Everywhere almost a year, I do not see anything like you described. Maybe [latest devbuild](https://addons.mozilla.org/firefox/downloads/file/563335/tab_mix_plus-0.5.0.2pre.170102a1-fx.xpi) can help you.

**Comment by Wskyy** [comment]
It has been happening for a while and assumed I could just type in
https.  That doesn't work so well so trying to use HTTPS Everywhere
but it keeps messing different extensions up, especially tab mix plus.
The Icon for Random Agent Spoofer sometimes won't appear with https
everywhere active. Using Win7 64 FF38.8 ESR.  Also have Portable FF
45ESR and Portable FF 50.1 for testing.  They are incompatible with so
many extensions I'm not ready to migrate. https Everywhere has caused
other problems with tab mix plus as indicated by the link.  Just
installed the dev build of TMP upon advice of an admin there.  Still
problems.

This is a separate issue but there used to be an option to add
websites to https everywhere in a much easier way than writing a rule
set.  (Too lazy to figure out how to write and add a rule set to the
entire list.)  It should be by just clicking.

**Comment by Wskyy** [comment]
Same config w/ ff38.8ESR. Have the portable 45esr and portable50.1 for testing but they break so many extensions I have been staying with the recently supported esr for now.  Yes it has been happening since about 2014.  Just thought perhaps those who know more about it would have resolved it.  Yes was using the latest dev build of TMP upon advice from the TMP forum but it still has the problem.  Since https everywhere is also affecting another extension (icon sometimes won't appear in navigation toolbar) thought I'd put it up here. 

Another problem with https-everywhere is there doesn't seem to be a simple way to add any new websites (eg. msn.com) without having to write a rule set.  Have no idea how to add a rule set to the main list.  I thought before HE had a way to view these?  Also, how do you go back to the old icon/logo with the magnifying glass and arrows. I notice it is still in the folder.  The new blue S is too similar to other extensions.

**Comment by numismatika** [comment]
> Another problem with https-everywhere is there doesn't seem to be a simple way to add any new websites (eg. msn.com) without having to write a rule set. Have no idea how to add a rule set to the main list. I thought before HE had a way to view these?

There was another Addon called HTTPS- Finder that could optionally make HTTPS-Everywhere rules, but it is no longer developed and broken.
There is Smart-HTTPS ( https://addons.mozilla.org/de/firefox/addon/smart-https/ ) that works without rules.

These are both **external** and not part of this addon which still relies on manually crafted rules

**Comment by pipboy96** [comment]
Related to pre-WebExtensions version.
