### ISSUE TITLE
Breaks zattoo.com

### ISSUE THREAD

**Issue by amilopowers** [EFForg/https-everywhere#8167]
Hello

After logging in to zattoo.com account the browser tries to load http://zattoo.com/highlights. It always reloads the page and never stops. When I disable https-everyhere itw works flawlessly.

I work on a Fedora 25 machine with Firefox 50.1.0.

Regards
amilopowers

**Comment by Giltyhub2** [comment]
@amilopowers do you still experience this issue?

**Comment by amilopowers** [comment]
I haven't used this service for some time so I can't tell u.

**Comment by pipboy96** [comment]
@amilopowers Can this be tested without creating a user account?

**Comment by pipboy96** [comment]
I have just registered an account (using a VPN server located in Switzerland) and was unable to reproduce this issue. @amilopowers If you will ever encounter this problem again, feel free to post a comment here so I could reopen this.
