### ISSUE TITLE
NYTimes no longer good example of captive portal trigger

### ISSUE THREAD

**Issue by pinobatch** [EFForg/https-everywhere#8175]
From <https://www.eff.org/https-everywhere/faq>

> If you go to a website that isn't protected by HTTPS Everywhere (currently, nytimes.com is one such site)

Actually, the site has to be protected neither by HTTPS Everywhere nor by HSTS.

*The New York Times* is moving to HTTPS according to "[HTTPS on NYTimes.com](https://open.blogs.nytimes.com/2017/01/10/https-on-nytimes-com/?_r=0)". The device that I'm using right now provides no HSTS indicator as of yet, but I imagine it may be added soon. And if not, expect somebody to submit a pull request adding it.

**Comment by jeremyn** [comment]
Any site that isn't in the HSTS preload list is a valid target for HTTPS Everywhere, for example see https://www.eff.org/https-everywhere/faq#why-does-https-everywhere-include-rules-for-sites-like-paypal-that-already-require-https-on-all-their-pages. I agree though that now that the NY Times partially supports HTTPS, the FAQ shouldn't use it as an example, just to avoid confusion.

Pinging @Hainish to modify the FAQ.

**Comment by Hainish** [comment]
Great!  This can actually be implemented via a PR since the FAQ is now generated from markdown in the repo:

https://github.com/EFForg/https-everywhere/blob/master/docs/faq.md

**Comment by pinobatch** [comment]
In <https://github.com/EFForg/https-everywhere/pull/8180> I recommend Example.com

**Comment by jeremyn** [comment]
I've merged the FAQ change from nytimes.com to example.com in pull request #8180 , so I'm closing this issue.

**Comment by jeremyn** [comment]
Thanks for making the changes. I've merged the pull request.

I disagreed with the other changes for multiple reasons, for example I think Let's Encrypt is suitable for long-term needs; I don't think we should recommend any specific paid service; I'm not entirely sure what "Such a list would largely be redundant to the HSTS preload list." means. I didn't want to have a multipronged discussion of all these points in here, especially holding up merging the NYTimes.com change that we already agreed on.

Please feel free to create a new issue to discuss any further changes you want to make to the FAQ. We can make a new pull request once we've settled on something.

(I'm sorry if I came across as rude. Improving documentation is one of our biggest needs, thank you for working on it.)
