### ISSUE TITLE
Directory of paid CAs for cases when 90-day certificates are impractical

### ISSUE THREAD

**Issue by pinobatch** [EFForg/https-everywhere#8186]
The section "Isn't it more expensive or slower for a site to support HTTPS compared to regular HTTP?" of the FAQ currently states:

> It used to be expensive to purchase a certificate for HTTPS usage, but they can now be obtained for free from Let's Encrypt as well.

In [a comment to another pull request](https://github.com/EFForg/https-everywhere/pull/8180#issuecomment-272204277), jeremyn wrote:

> I think Let's Encrypt is suitable for long-term needs

Only if your current web host offers ACME. Many web hosting subscribers currently subscribe to shared hosting providers and managed VPS providers that do not integrate an ACME client. Because of the 90-day validity period of certificates issued by Let's Encrypt, a subscriber would have to log in every 60 to 90 days and ether upload the renewed certificate to a form in the hosting control panel or file a support ticket with the hosting provider's technical support department. Unlike a certificate from Let's Encrypt, this periodic installation labor cannot "be obtained for free".

**Case in point: WebFaction** Only in September 2016, for example, did web hosting provider [WebFaction switch from filing a support ticket to uploading through a form](https://blog.webfaction.com/2016/09/manage-ssl-certificates-with-the-control-panel/). There's a [feature request for integration with Let's Encrypt](https://community.webfaction.com/questions/18989/using-lets-encrypt-to-get-ssl-certificates), but it's been open for well over a year with no ETA.

> I don't think we should recommend any specific paid service

With the distrusting [by Mozilla](https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/) and [by Google](https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html) of WoSign and StartSSL certificates issued on October 21, 2016, or later, all widely trusted certificate authorities that issue TLS certificates with a validity period at least one year are paid services. Some hosting subscribers are willing to pay $15 per three years in order to avoid the periodic labor of having to log in to the panel eighteen times over the course of those three years. Instead of "recommend[ing] any specific paid service", would it be proper to recommend a directory of paid services? Or would it instead be proper to recommend switching from a web hosting provider that does not integrate with Let's Encrypt to one that does?

I just don't see how it's proper to sweep under the rug the addition of a requirement to upload a certificate to your web host six times a year.

**Comment by jeremyn** [comment]
That part of the FAQ is answering the question [Isn't it more expensive or slower for a site to support HTTPS compared to regular HTTP?](https://www.eff.org/https-everywhere/faq#isnt-it-more-expensive-or-slower-for-a-site-to-support-https-compared-to-regular-http) You can think of it as a little advertisement for site admins to use HTTPS, not a walkthrough on how to do it.

Other free or nearly free HTTPS options include [GitHub Pages](https://help.github.com/articles/securing-your-github-pages-site-with-https/) and [AWS](https://aws.amazon.com/certificate-manager/), but they, like Let's Encrypt, require some compromises. Why does Let's Encrypt get special treatment in the FAQ? I don't know for sure. I do know the EFF is a primary sponsor of Let's Encrypt, and also hosts an ACME client at https://certbot.eff.org. I think it's all right for the EFF to put a little ad in there for their own thing.

I definitely don't want some constantly-shifting list of commercial sites in the FAQ.

I'd be okay with linking to some general, comprehensive "How to configure HTTPS" page that is maintained elsewhere by an organization or person with a mission aligned with the EFF's, maybe the EFF itself, or the FSF or Whisper Systems or Bruce Schneier or something/someone like that.

**Comment by pipboy96** [comment]
Off-topic, unrelated to the extension.
