### ISSUE TITLE
Chrome on Windows disables non-web store HTTPS Everywhere on restart

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#819]
Steps to reproduce:

1. In Chrome on Windows, install HTTPS Everywhere directly from EFF (download the .crx, drag and drop into Extensions page).
2. Restart Chrome.

Expected result:

HTTPS Everywhere stays installed.

Actual result:

On next startup, a notice appears in the upper right saying "Unsupported extensions disabled. To make Chrome safer, we disabled some extensions that aren't listed in the Chrome Web Store and may have been added without your knowledge.

 - HTTPS Everywhere"

On the Extensions page, HTTPS Everywhere is greyed out, disabled, and the checkbox to re-enable it is greyed out. Enabling developer mode doesn't fix it, nor does dragging in the .crx again. Deleting the extension and dragging back in the .crx works until the next restart.

We should ask Google about this.

**Comment by NewEraCracker** [comment]
There are two options to workaround this.

One is extracting the CRX to a new folder in the computer and use programing mode to load the extension from the folder.

Another one is, the one I use for archival purposes, download the CRX from Chrome webstore using "Give me CRX": https://chrome.google.com/webstore/detail/give-me-crx/acpimoebmfjpfnbhjgdgiacjfebmmmci

Apparently there is some method of certificate authentication in CRX files and those downloaded from eff's website mismatch the copies at google's servers.

Regards,
NewEraCracker

**Comment by semenko** [comment]
Closing this since ~unfixable -- Google has worked hard to block non-webstore installed extensions due to malware.

**Comment by McKinleyGroup** [comment]
Hi jsha,
Hi Semenko,
https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp

Version: 2016.4.4
Updated: April 4, 2016

Should do just fine! :+1: 

I hope this helps. :-)

**Comment by buaabyl** [comment]
But can't access Google domain in China:(

**Comment by ChamZank** [comment]
i found HTTPS Everywhere 2016.9.1 corrupted in google chrome version 
![capture-20160904-022436](https://cloud.githubusercontent.com/assets/6598967/18227003/bf59eb16-7249-11e6-8591-c10f2144de56.jpg)

**Comment by nikw92** [comment]
@ChamZank -  I found a workaround for this latest issue. With the extension installed, go to the Chrome Webstore page for HTTPS Everywhere. There will be prompt saying that "This extension has been disabled in Chrome" with a button to enable it. Enable it from there and it should work.

**Comment by ChamZank** [comment]
not work..

**Comment by dld-r00f** [comment]
Try to delete extention and install it again with Chrome Webstore. Then enable it as described above. [chrome version 53.0.2785.113 m (64-bit)]

**Comment by q158073378252010** [comment]
@ChamZank 我也有同样的问题！不排除扩展bug

**Comment by Raciel14** [comment]
gracias McKinleyGroup este enlace funciona para la extension en chrome dejo el link:  https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp
que Dios los bendiga... :+1:

**Comment by nullQ** [comment]
gracias McKinleyGroup este enlace funciona para la extension en chrome dejo el link: https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp
que Dios los bendiga... 👍

thx , it's useful

**Comment by q158073378252010** [comment]
该地址中有个解决方案
https://www.chromium.org/administrators/policy-templates

**Comment by CRESCENDO462** [comment]
http://earnstipend.com/?ref=11899
