### ISSUE TITLE
HTTPS Everywhere development environment with Vagrant

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#8196]
@gloomy-ghost @Hainish I created a Vagrant setup for HTTPS Everywhere development at https://github.com/jeremyn/https-everywhere-dev-environment. Feel free to check it out and let me know what you think.

**Comment by Hainish** [comment]
Nice!  This is great.  I'm curious, why separate it out into a separate repo, instead of adding a Vagrantfile to this one?

**Comment by jeremyn** [comment]
It's a lot more than just a Vagrantfile.

**Comment by Hainish** [comment]
Regardless, this could be added to a `vagrant` path within HTTPS Everywhere.  I think if it's generally useful, why make it hard to find?

**Comment by jeremyn** [comment]
It can't go inside the HTTPS Everywhere directory structure, because HTTPS Everywhere gets installed completely inside the VM.

Anyway it's pretty heavyweight and I don't think it's something that we should just throw into the bucket to officially support, and if it is officially supported then I don't want to be the only person who can work with it. For example if someone adds a new Ubuntu dependency to `install-dev-dependencies.sh`, then the corresponding Ansible task needs to be updated at the same time. It's also opinionated, for example I install system versions of dependencies where possible instead of pip versions.

I'd say if you personally aren't prepared to make it your daily driver, then it should stay unofficial. I'm okay with referring to it in the documentation though, once it gets some use to shake out problems.

**Comment by Hainish** [comment]
Fair enough.  I figure we may want to build a development environment in docker, as well, at some point.

**Comment by Hainish** [comment]
Closing issue, since this was just to flag us.  Feel free to reopen if there is a reason to do so
