### ISSUE TITLE
HTTPS Everywhere extension causes Firefox to crash

### ISSUE THREAD

**Issue by jish** [EFForg/https-everywhere#8197]
Steps to reproduce:

1. Install the HTTPS Everywhere extension in Firefox
2. Enable the "Block all unencrypted requests" option
3. Leave Firefox open for a while
4. The problem occurs when websites begin to load slowly or not at all
5. Firefox will eventually stop responding

I can reliably reproduce this on two separate computers running Mac OS.

The issue can be resolved or reintroduced by uninstalling or reinstalling the HTTPS Everywhere extension.

**Comment by gloomy-ghost** [comment]
Closing as we are moving to WebExtension
