### ISSUE TITLE
Blocks encrypted AJAX requests on https://medstro.com

### ISSUE THREAD

**Issue by ChaosFreak** [EFForg/https-everywhere#8215]
Users with the HTTPS Everywhere plugin enabled are unable to post updates or comments when using the site https://medstro.com.
This site is 100% SSL. Posting updates and comments use AJAX requests, which appear to be blocked by the plugin.
To test, go to a public area of the website (for example, https://medstro.com/groups/primary-care-innovation-challenge) and then type a response to any of the posts and click "Respond". The site will hang and the response will not be recorded.

**Comment by pipboy96** [comment]
Can't reproduce.
