### ISSUE TITLE
*.readthedocs.io cannot be accessed by https

### ISSUE THREAD

**Issue by jmozmoz** [EFForg/https-everywhere#8222]
The Python documentations at readthedocs.io (and probably also all other subdomains) cannot be accessed by https. They are reachable by http:

does not work: https://numpy.readthedocs.io/en/latest/
works: http://numpy.readthedocs.io/en/latest/

(this worked up until a few weeks ago, but at least since one week, it does not anymore.)

*.readthedocs.io was added by issue #6242

**Comment by jeremyn** [comment]
https://numpy.readthedocs.io/en/latest/ works for me now. Maybe they just fixed it?

**Comment by jmozmoz** [comment]
Indeed, it looks like the problem has been fixed on the server side.
