### ISSUE TITLE
symbols.mozilla.org needs an exception

### ISSUE THREAD

**Issue by the8472** [EFForg/https-everywhere#8225]
> symbols.mozilla.org:443 uses an invalid security certificate. The certificate is only valid for the following names: *.herokuapp.com, herokuapp.com

Similar to #6613

**Comment by LiveChief** [comment]
No it dosent.

**Comment by the8472** [comment]
This is with HTTPS Everywhere 5.2.9:

![httpseverywhere](https://cloud.githubusercontent.com/assets/1065730/22130963/fe92ad90-deaf-11e6-8c05-ce9467633fc7.png)

**Comment by strugee** [comment]
I can reproduce the certificate error.

**Comment by jeremyn** [comment]
I'm closing this issue because it was fixed by pull request #8247.
