### ISSUE TITLE
Add rule for mojang.net

### ISSUE THREAD

**Issue by BK1233** [EFForg/https-everywhere#8230]
It not is not default like it used to be and it supports https but there is no rule for it.

**Comment by jeremyn** [comment]
I get a `Server not found` for http://mojang.net, and `dig mojang.net` doesn't find an IP address. Could you please provide a working URL?

**Comment by BK1233** [comment]
Of its Mojang.com

**Comment by jeremyn** [comment]
Thanks. I've added this to issue https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-275807281 and I'm closing this issue.

**Comment by jeremyn** [comment]
I changed the issue title to say `.com` instead of `.net`, to make the issue more clear.
