### ISSUE TITLE
vpsBoard's SSL certificate is misconfigured, disable HTTPS Everywhere ruleset

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#8234]
[vpsBoard](http://vpsboard.com/) has a misconfigured SSL certificate, so the HTTPS Everywhere ruleset should be disabled.

**Comment by jeremyn** [comment]
Unencrypted http://vpsboard.com is getting an HTTP 500. Are they shut down completely?

**Comment by neonardo1** [comment]
They have a valid SSL again.

**Comment by jeremyn** [comment]
Thanks for letting us know @neonardo1 .
