### ISSUE TITLE
Would like more info in UI about blocked/rewritten/allowed traffic

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#8238]
It'd be kinda neat if I was able to see some statistics on exactly how much unencrypted traffic HTTPS Everywhere was preventing using the "block all unencrypted requests" option.

**Comment by strugee** [comment]
Actually, now that I think about it, this would also be neat for all of HTTPS Everywhere's functionality. I'm imagining a pie chart that would show what percentage of requests were a) already HTTPS, b) upgraded to HTTPS via a ruleset, and c) sent over unencrypted HTTP (or blocked by the HTTP blocker).

**Comment by jeremyn** [comment]
Thanks for your idea. I've updated the issue title to something I think describes your request better.

**Comment by strugee** [comment]
@jeremyn thanks, that's much better :P

Do you know if patches would be accepted for this? I might try my hand at it if I get some time

**Comment by jeremyn** [comment]
I'm not sure. Something graphical like a pie chart, probably not, especially with the different UI between Firefox and Chrome. Also you can get the same information from Dev Tools > Network. Another problem is sites that never stop loading things. Do you keep updating the pie chart? 

Maybe the most likely approach is information logged to or otherwise accessible in the JavaScript console after checking some kind of "Log Statistics" option in the UI that doesn't exist right now.

@Hainish What do you think, is this a feature we want?

**Comment by Hainish** [comment]
This is interesting.  It introduces a layer of persistence that is not currently kept by the addon, and thus more complexity.  I think we'd have to discuss more and see how this fits into our prioritization of HTTPS Everywhere tasks.  I think it would be useful, it's just a matter of measuring the utility against the time investment and maintenance.

**Comment by jeremyn** [comment]
We need to be super careful about introducing any persistence. AFAIK HTTPS Everywhere currently has (almost?) no persistence at all, which is best for privacy.

All the data @strugee wants in their second comment https://github.com/EFForg/https-everywhere/issues/8238#issuecomment-274566569 can be found either in Dev Tools or the existing blocked items counter in the add-on UI.

For the data requested in their first comment https://github.com/EFForg/https-everywhere/issues/8238#issue-202606353 'how much unencrypted traffic HTTPS Everywhere was preventing using the "block all unencrypted requests" option', we could maybe add a second counter in the UI for the number of items that were blocked using the "Block everything" fallback logic.

**Comment by Hainish** [comment]
@jeremyn the only persistence we have in HTTPS Everywhere is user prefs in `about:config`.  Yes, it's super important that we do not persist data that could be linked to the users' browsing habits or history without getting an explicit opt-in from the user.  This is especially true since we are included in the Tor Browser.

**Comment by strugee** [comment]
@jeremyn I don't see any privacy problems. I'm not suggesting we store all URLs that HTTPS Everywhere has ever rewritten, only the number of URLs. That doesn't particularly strike me as an issue.

**Comment by jeremyn** [comment]
@strugee One problem is browser fingerprinting, see [here](https://panopticlick.eff.org/about#browser-fingerprinting). For example imagine there are two indistinguishable Tor users, A and B, who regularly visit a particular site. The site owner ordinarily has no way to match users to visits. Suppose now that HTTPS Everywhere stores that User A has blocked 1000 sites and User B 2000 sites, and this is queryable through JavaScript. Now the site owner can match users to visits by checking the number of blocked sites for each (Tor) visitor.

**Comment by strugee** [comment]
@jeremyn I'm familiar with Panopticlick. I wasn't at _all_ suggesting that this be queryable through JavaScript. I hope I was clear that this information would _only_ be available to the user through the extension's UI. I'm completely with you that exposing this to untrusted JS would be disastrous, for exactly the same reason.

**Comment by Hainish** [comment]
@strugee even avoiding direct queries from JavaScript, we need to be careful here.  The Tor Browser design document has a specific section on how they try to [avoid disk persistence](https://www.torproject.org/projects/torbrowser/design/#disk-avoidance).  So at the very least, any local form of data collection should be behind a pref, which we can set in the TB context.

**Comment by jeremyn** [comment]
Also, the most protected data is data that doesn't exist. Even if this data were secured behind some technical barrier, it's still there to be accessed if there is some vulnerability in Tor, or if the computer is physically seized. Someone could at least see whether Tor was used a little or a lot.

**Comment by strugee** [comment]
Agreed that we should disable this in TBB.

**Comment by pipboy96** [comment]
See #16669.

**Comment by zoracon** [comment]
Closing for now since this could introduce a layer of fingerprinting on the user and has been addressed in the more recent issue above
