### ISSUE TITLE
Can't get disable a rule 

### ISSUE THREAD

**Issue by asgorin** [EFForg/https-everywhere#8240]
On sidereel.com, no matter what I do, I can't seem to disable the rule for it even when I uncheck the box associated with that rule. I must disable HTTPS Everywhere entirely.

**Comment by jeremyn** [comment]
At http://www.sidereel.com there is a `SideReel (partial)` rule that is active by default, and when I toggle it, the page reloads and the rule then shows as inactive. I haven't looked at what the ruleset actually does but so far this looks fine to me.

Can you please provide more information about your system and what specifically you think should happen but doesn't?

**Comment by pipboy96** [comment]
@asgorin If you are still experiencing this issue, please make a comment and I will re-open this issue.
