### ISSUE TITLE
Exclusion rule for squarespace.com subdomain sg-links

### ISSUE THREAD

**Issue by dtauerbach** [EFForg/https-everywhere#8251]
Hello, I work for Squarespace (and was a former EFF technologist). We are getting some complaints about the subdomain sg-links.squarespace.com which is hosted by sendgrid and not us and it's non-trivial to get a cert for it on their side. The upshot is poor user experience for HTTPS Everywhere users clicking certain links from email, like, say, unsubscribe. I am going to write a rule to exclude this subdomain from the Squarespace partial rule, & send a PR referencing this issue; if there is another preferred workflow beyond the repo guidelines that I missed please let me know.

**Comment by jeremyn** [comment]
I'm closing this issue since the associated PR is merged.
