### ISSUE TITLE
Rule for hartwork.org 

### ISSUE THREAD

**Issue by joshtriplett** [EFForg/https-everywhere#8265]
The rules in src/chrome/content/rules/Hartwork-Project.xml redirect http://hartwork.org to https://hartwork.org ; however, the latter gives SSL errors, because the certificate only works for www.hartwork.org.  The site itself redirects to https://www.hartwork.org/

cc @hartwork

**Comment by hartwork** [comment]
I have migrating to Let's Encrypt on my todo list. I need more time though.
If there is something quick that I could do before new certificates, please let me know.

**Comment by joshtriplett** [comment]
@hartwork I don't think you need to do anything here.  https-everywhere should stop sending people to hartwork.org with https.

When you do migrate to Let's Encrypt, I'd recommend choosing a canonical domain name (for instance, hartwork.org), and redirecting everything else (such as www.hartwork.org) to that canonical name, rather than having multiple domains that serve the same content.  But you'll still need SNI and SANs to allow https connections for the non-canonical domains in order to send such a redirect.

**Comment by hartwork** [comment]
> @hartwork I don't think you need to do anything here. https-everywhere should stop sending people to hartwork.org with https.

Okay.

> When you do migrate to Let's Encrypt, I'd recommend choosing a canonical domain name (for instance, hartwork.org), and redirecting everything else (such as www.hartwork.org) to that canonical name, rather than having multiple domains that serve the same content. But you'll still need SNI and SANs to allow https connections for the non-canonical domains in order to send such a redirect.

Sounds good, thanks!

**Comment by hartwork** [comment]
> The rules in src/chrome/content/rules/Hartwork-Project.xml redirect http://hartwork.org to https://hartwork.org ; however, the latter gives SSL errors, because the certificate only works for www.hartwork.org.

I fixed the SSL errors on https://hartwork.org now using Let's encrypt. I would like to keep [src/chrome/content/rules/Hartwork-Project.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Hartwork-Project.xml) in place personally, so that people are not MITM'ed on the initial (otherwise plain HTTP) request.

> When you do migrate to Let's Encrypt, I'd recommend choosing a canonical domain name (for instance, hartwork.org), and redirecting everything else (such as www.hartwork.org) to that canonical name, rather than having multiple domains that serve the same content.

I have put that to action now.

**Comment by Bisaloo** [comment]
This seems fixed. Can we close this issue?

**Comment by hartwork** [comment]
I have added a PR to remove the forward from binera.de since — unlike when this ticket was created — it has a valid certificate of its own now.

> This seems fixed. Can we close this issue?

From my point of view, yes.
