### ISSUE TITLE
Rule for dkb.de

### ISSUE THREAD

**Issue by Septa9** [EFForg/https-everywhere#8268]
There is at least one non-https page at dkb.de: dkb-cash-kanns.dkb.de. Thus, the corresponding link from (at least) https://www.dkb.de/privatkunden/dkb_cash/ results in "Secure Connection Failed".

**Comment by DavidLiedke** [comment]
@J0WI i think this issue can be closed. 

"dkb-cash-kanns.dkb.de" has a correct ssl certificate. https://www.ssllabs.com/ssltest/analyze.html?d=dkb-cash-kanns.dkb.de
