### ISSUE TITLE
Is there special handling for the URL "github.com"?

### ISSUE THREAD

**Issue by jeremyn** [EFForg/https-everywhere#8279]
In HTTPS Everywhere 5.2.9 in Firefox, if I go to https://github.com, it says ruleset [`GitHub`](https://github.com/EFForg/https-everywhere/blob/7e621becf2c50f2b92d488d98f508d445b83cf97/src/chrome/content/rules/Github.xml) is active. However github.com isn't covered by that ruleset. If I copy the ruleset file, give the `ruleset` a different `name`, put it in `HTTPSEverywhereUserRules/`, and type "github.com" into the address bar without pressing Enter, it says it matches ruleset `GitHub` but not my test ruleset which is identical except for the name.

What's going on with "github.com"? Why is that URL matching a ruleset that doesn't cover it, and not matching a near-identical ruleset?

Pinging @gloomy-ghost @Hainish .

**Comment by Hainish** [comment]
Hey @jeremyn,

As of HTTPS Everywhere 5.2.9, `github.com` *was* covered by that ruleset.  The coverage was removed in 5.2.10 (it's HSTS preloaded).  I'll look and see if I can reproduce the `HTTPSEverywhereRules/` issue.

**Comment by jeremyn** [comment]
Oh okay, that makes sense. In that case there's nothing to reproduce with the second part of the problem, because my "near identical" ruleset that didn't match was the 5.2.10 version, so it wasn't actually identical.
