### ISSUE TITLE
Version 2017.1.25 not working on Google Chrome Version 56.0.2924.76 (64-bit)

### ISSUE THREAD

**Issue by hourback** [EFForg/https-everywhere#8285]
It gets disabled automatically.  I try re-enabling it and get a message in Chrome that the extension may have been corrupted.  I attempt repair and the cycle repeats.

**Comment by jeremyn** [comment]
Thanks for your report, however we are currently tracking "extension corrupted in Chrome" problems in issue https://github.com/EFForg/https-everywhere/issues/7456. Please feel free to comment there. I'm closing this issue as a duplicate.

**Comment by hourback** [comment]
Thank you, Jeremy!  Sorry I missed that.
