### ISSUE TITLE
Breaks Internet Connection Test for GoTo Webinar

### ISSUE THREAD

**Issue by stoltzld** [EFForg/https-everywhere#8343]
I was trying to use the URL Below to Test Firefox with GoTo Webinar.  The Internet Connection Test failed until I diabled HTTPS Everywhere.

http://help.citrix.com/webinar/joincheck?c_name=confirmation&role=attendee&language=english&source=attendeeRegistrationPage#

**Comment by stoltzld** [comment]
The problem seems to be tied to the rules for Amazon Web Services

**Comment by numismatika** [comment]
Have you tried using the HTTPS version?
For me the whole test works but i can't join the test meeting as it seems to require a windows executable.

**Comment by stoltzld** [comment]
I just did.  It says that the certificate is invalid (I'm assuming they use cloudfront based on the details of the message).  If you use the link above it redirects to https://care.citrixonline.com/gotowebinar/joincheck?c_prod=g2w&c_name=main anyway.

**Comment by pipboy96** [comment]
`care.citrixonline.com` = `NXDOMAIN`.
