### ISSUE TITLE
geck.bethsoft.com, creationkit.com

### ISSUE THREAD

**Issue by githubbantor** [EFForg/https-everywhere#8381]
http://geck.bethsoft.com -> https://geck.bethsoft.com
http://creationkit.com, http://www.creationkit.com, https://creationkit.com ---> https://www.creationkit.com

**Comment by Bisaloo** [comment]
see https://github.com/EFForg/https-everywhere/pull/8264

**Comment by jeremyn** [comment]
Thanks for the issue. http://www.creationkit.com is added by pull request #8264 and I've noted http://geck.bethsoft.com at `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-277541630`, so I'm closing this issue.
