### ISSUE TITLE
Websites that aren't in rules

### ISSUE THREAD

**Issue by yozel** [EFForg/https-everywhere#839]
I think https everywhere rule system is good. But, what about websites that aren't in rules? I think, we should add a feature like this:

1- If url is in rules, make it HTTPS
2- If url isn't in rules, check this site has SSL, if site has (valid) SSL certificate, add it to rules and go to this url with HTTPS.

That would be great!

**Comment by StevenRoddis** [comment]
I've always liked the idea of users being able to use the extension to submit a request.
I'm not sure of the best way to word it.
"Tell x to add this site in future releases"
"Submit a request to add this site to HTTPSE"

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's still a bug.
