### ISSUE TITLE
Mobile: applicable rules list lacks rule for top-level URL

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#840]
Steps to reproduce:
1. On Android with 5.0development.2 (or master), visit http://www.reddit.com/robots.txt.
2. Click HTTPS Everywhere icon in URL bar.

Expected result:

Menu pops up including rule for reddit.

Actual:

Menu pops up that does not include reddit rule.

Note that if you visit www.reddit.com, the reddit rule shows up due to subresources.

**Comment by zoracon** [comment]
Closing due to new changes since this conversation took place. Can reopen if issue comes up again
