### ISSUE TITLE
Deterministic builds are broken again. 

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#841]
Steps to reproduce:
1. Check out 5.0development.2
2. ./makexpi.sh
3.  sha256sum pkg/https-everywhere-5.0development.2~4a7cf97.xpi

Expected result:

Output matches sha256sum from
https://travis-ci.org/EFForg/https-everywhere/builds/44882904#L741

Actual result:

Output does not match.

**Comment by wonderchook** [comment]
@jsha @Hainish should this be closed? The branch to verify does not exist anymore and I'm thinking it might no longer be an issue.

**Comment by Hainish** [comment]
@wonderchook reproducibility is achieved with https://travis-ci.org/EFForg/https-everywhere/jobs/333371311 (though this is using python 2.6!).  I was able to verify that my local `sha1sum` build hashes match that of the latest master hashes in https://travis-ci.org/EFForg/https-everywhere/jobs/333371311#L559.
