### ISSUE TITLE
NBC.com videos won't stream after the January update of HTTPS Everywhere

### ISSUE THREAD

**Issue by Akainaa** [EFForg/https-everywhere#8417]
Hello,

After the update of HTTPS Everywhere in January 2017 the videos on NBC (such as Nightly News http://www.nbcnews.com/nightly-news) won't stream anymore. After I disable HTTPS they start to play.

Earlier on CBS.com had a similar issue due to Google API rule but I don't see it among the rules in this case.

HTTPS : 5.2.10
Firefox: 51.01 (64-bit)

The rules concerned can be found here:
![nbc news rules](https://cloud.githubusercontent.com/assets/19587172/22626585/35999f66-ebb1-11e6-84ad-c95127c1888e.PNG)

**Comment by HansHauge** [comment]
Using `(Version: 2017.1.25)` the videos play for me in Chrome `Version 55.0.2883.95 (64-bit)`

**Comment by HansHauge** [comment]
Just tried this with Firefox `51.0.1 (64-bit)` and HTTPS Everywhere `5.2.10` and there were some delays but the video did play eventually.

**Comment by Akainaa** [comment]
Perhaps geolocation has a bearing on the issue. I watch NBC news daily here in Europe and it played fine until the update at the end of January. Now it streams normally if I disable HTTPS. Programs such as Meet The Press and Watch Live still function as before.
All the videos on CBS.com (Evening news, Meet the Nation, 60 minutes) played for some time after Google API was disabled but then stopped playing  later last year. After that they worked if I disable the app. PBS news and ABCnews.com stream as intended when HTTPS is disabled. 

I use habitually only Firefox but due to Windows 10 Edge (version 38.14393.0.0) is preinstalled (without apps) and it plays all the streams well.

**Comment by Akainaa** [comment]
After the February update NBC and PBS (NewsHour, Washington Week) work again, much obliged. Also CNN works.

The streams on CBS and ABC remain blocked.

**Comment by gloomy-ghost** [comment]
CBS has moved to https, and I can no longer reproduce the issue
