### ISSUE TITLE
Ruleset issue : Akamai rule breaks french public TV streaming

### ISSUE THREAD

**Issue by SomeTVGuest** [EFForg/https-everywhere#8481]
Go to the french public TV live streaming sites (with flash plugin installed)

http://pluzz.francetv.fr/france2
and
http://www.francetvinfo.fr/en-direct/tv.html

With https-everywhere installed, video ads may be seen but not the live TV streaming normally following, instead an error message appears in the player "Erreur de lecture vidéo." ("Video reading error").

If I disable the "Akamai" rule in the https-everywhere interface by clicking on it to make it grey, live streaming works. I guess this rule should be disabled for these two domains above for everybody, if possible but this is to be tested.

Exactly the same problem exists for other french public TV channels but as far as I know they are all on the same domains as above

http://pluzz.francetv.fr/france3
http://pluzz.francetv.fr/france4
http://pluzz.francetv.fr/france5
http://pluzz.francetv.fr/franceo

**Comment by Bisaloo** [comment]
This seems fixed. Can you confirm @SomeTVGuest?
