### ISSUE TITLE
Ruleset: cmip-pcmdi.llnl.gov does not have https

### ISSUE THREAD

**Issue by pv** [EFForg/https-everywhere#8485]
The following llnl.gov subdomain doesn't actually have https enabled (port 443 talks http...):
http://cmip-pcmdi.llnl.gov

**Comment by Bisaloo** [comment]
@pv, this is no longer an issue as far as I can tell. Can you double check and close this issue if everything is working as intended now?

**Comment by pv** [comment]
indeed
