### ISSUE TITLE
Ruleset issue: sci-hub.bz

### ISSUE THREAD

**Issue by githubtefo** [EFForg/https-everywhere#8487]
https://sci-hub.bz redirect to https://moscow.sci-hub.ac/ and the site is down, so I need to deactivate http to https conversion (http://sci-hub.bz works fine).

**Comment by Bisaloo** [comment]
Fixed by https://github.com/EFForg/https-everywhere/pull/8561.

**Comment by Bisaloo** [comment]
@J0WI, can you close this as well please? Thanks!
