### ISSUE TITLE
Spiegel.tv videos not playing

### ISSUE THREAD

**Issue by Acromonkey** [EFForg/https-everywhere#8490]
Hello,

I found the following issue on Chrome, Chromium and Firefox:

With HTTPS Everywhere activated I cannot watch videos from spiegel.tv.

Since Spiegel is a very famous and popular German news, I strongly recommend to try to fix that problem.

Best
Acromonkey

**Comment by rnaaeyhm** [comment]
hi

**Comment by numismatika** [comment]
I would complain to that news magazin first, they still have flash for their video player which makes this kind of hard to solve.

**Comment by gloomy-ghost** [comment]
Seems they don't use flash now, and I can't reproduce the issue. Feel free to re-open if it still occurs.
