### ISSUE TITLE
5.2.11 reverts manifest grouping

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#8496]
https://github.com/EFForg/https-everywhere/pull/8495 reverts the manifest.json grouping introduced in https://github.com/EFForg/https-everywhere/pull/7650 due to usage of https://github.com/EFForg/https-everywhere/blob/5.2.11/utils/setversion.py.  `setversion.py` should be updated to preserve grouping.

**Comment by pipboy96** [comment]
Related to XPCOM version of extension.
