### ISSUE TITLE
Provide redirect for IETF

### ISSUE THREAD

**Issue by frewsxcv** [EFForg/https-everywhere#850]
HTTPS Everywhere should redirect:

 [`http://tools.ietf.org/html/rfc6979`](http://tools.ietf.org/html/rfc6979) -> [`https://tools.ietf.org/html/rfc6979`](https://tools.ietf.org/html/rfc6979)

I'm running the latest stable version of HTTPS Everywhere (4.0.2) on Firefox.

**Comment by julianladisch** [comment]
`https-everywhere-5.0development.2.xpi` from https://www.eff.org/https-everywhere#https-everywhere-files correctly redirects `tools.ietf.org` to `https`.

**Comment by jsha** [comment]
Closing as fixed. Thanks!
