### ISSUE TITLE
steamcommunity.com Artwork & Screenshots broken again

### ISSUE THREAD

**Issue by foresto** [EFForg/https-everywhere#8529]
https everywhere is forcing https on steamcommunity.com, which breaks all of the content on that site's Artwork and Screenshots tabs. (Looks like the browser's mixed content blocker is kicking in when the main page is loaded via https.)

This has been reported before (#1911). Looks like it's broken again.

I'm using version 5.2.11.

**Comment by numismatika** [comment]
All Screenshots are hosted on an akamai domain that doesn't support TLS.
Seems that Valve is dynamically altering the images so they are classified as active content and therefore blocked.
So all we can do is disable the rule again.

**Comment by Wuerstchen** [comment]
Doesn't seem to be broken anymore.

**Comment by Bisaloo** [comment]
This should be fixed by Steam complete switch to HTTPS (see #15088)
