### ISSUE TITLE
American University

### ISSUE THREAD

**Issue by david-beers** [EFForg/https-everywhere#8534]
It seems that sites under the domain american.edu are not redirecting properly. When typing in http://www.american.edu/ it just loads for a long time and eventually fails because the server is taking too long to respond. When navigating to https://www.american.edu/ it connects to the HTTPS version fine.

**Comment by jeremyn** [comment]
Thanks for the report. I don't fully understand this issue though, and http://www.american.edu/ works for me. Is this still a problem for you?

**Comment by zneaa** [comment]
@david-beers Tested and it works fine for me.

**Comment by david-beers** [comment]
When I start typing "american.edu" into the address bar and press enter when the correct address is highlighted, it just keeps on saying "Connecting." I will try clearing my cookies and cache too see if that solves the issue.

**Comment by david-beers** [comment]
The issue persists after clearing my cookies and cache. Sometimes it ends with the error that the server timed out, but usually it just stops trying without any error and shows a blank new tab page.

**Comment by jeremyn** [comment]
@david-beers I'm still not able to reproduce this issue. Could you please let us know your operating system, browser, browser version, and HTTPS Everywhere version? Also if you are comfortable with your browser's developer tools, please let us know if you see anything interesting in either the "Console" or "Network" tabs when you try to load http://american.edu.

**Comment by pipboy96** [comment]
Can't reproduce, last activity 2017.
