### ISSUE TITLE
"Block all unencrypted requests" breaks Google Chrome / Chromium "did you mean to go to" DNS short domain hijacking detection

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [EFForg/https-everywhere#8543]
Google Chrome / Chromium both attempt to detect DNS hijacking by upstream ISPs by sending invalid short DNS domain names like "ajdgrythrg" upstream to see if the default DNS server replies with a DNS A record. If it does, Chrome / Chromium know that the upstream DNS server is faking DNS replies for NXDOMAIN aka non-existent domains. This becomes an issue if the user utilizes the "omnibox" to type short search queries that go to the default search provider.

For instance, typing "ip" into the Google Chrome / Chromium omnibox (URL bar location) should perform a search for "ip" at https://www.google.com/search by default. The response should be the source IP address of the browser. However, due to HTTPS Everywhere option "Block all unencrypted requests", this will break such functionality and cause Google to ask the user "Did you mean to go to http://ip/?". According to a Google Chrome bug report, this may be because the browser interprets an valid 3xx response (or other legitimate response) as a remote web server being up, even if HTTPS Everywhere spoofed the response itself to Chrome / Chromium in order to perform the redirection. Perhaps HTTPS Everywhere could instead handle invalid / DNS short names differently to fix this issue?

Disabling the "Block all unencrypted requests" feature can prevent this error, but leaves the user vulnerable to unencrypted HTTP requests.

https://bugs.chromium.org/p/chromium/issues/detail?id=521009

**Comment by gloomy-ghost** [comment]
From https://bugs.chromium.org/p/chromium/issues/detail?id=521009#c46:
> The change should roll out with Chrome 63, hitting the Stable channel likely sometime in December.

Closing as it's fixed by upstream.
