### ISSUE TITLE
Unable to add items to cart on Landsend.com

### ISSUE THREAD

**Issue by VerbenaZero** [EFForg/https-everywhere#8553]
When using HTTPS Everywhere with default settings, landsend.com properly redirects to https://landsend.com .  However, when going to a product page and attempting to add the item to the cart/bag, the item is not actually added to the cart/bag.  Upon contacting Lands End customer support, they state:  "If HTTPS Everywhere is installed, please temporarily disable it.  Our product pages don't support this add-on. Lands' End will always use encrypted connections for pages where you are entering any personal information, such as checking out or accessing your Personal Shopping Account"

**Comment by pipboy96** [comment]
I can no longer reproduce this issue. The ruleset has some unrelated issues though.
