### ISSUE TITLE
Kagi no longer supports HTTPS-should the Kagi ruleset be disabled?

### ISSUE THREAD

**Issue by galenide** [EFForg/https-everywhere#8564]
HTTPS Everywhere currently has a [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Kagi.xml) for Kagi. Around the end of July 2016, Kagi [ceased operations](https://tidbits.com/article/16665). As a result, it appears that none of the target hosts in the ruleset support HTTPS.

One possible option would be to set the ruleset to off by default, with an explanation of "no HTTPS support" for the `default_off` parameter. Another option might be to remove the `kagi.com` and `www.kagi.com` target hosts while leaving the ruleset enabled. This could provide some protection if a user makes an HTTP request to a URL at a domain such as `order.kagi.com`, for example. As of now, http://kagi.com/ and http://www.kagi.com/ lead to an [explanation page](http://kagi.com/), and it would be useful for users in any case to be able to reach that page.

**Comment by jeremyn** [comment]
https://order.kagi.com is gone from DNS for me.

If all the subdomains are either gone (`order`) or likely to be permanently broken for HTTPS (`^`/`www`), then we should delete the ruleset entirely, not just disable it.
