### ISSUE TITLE
"Block all HTTP requests" has no effect

### ISSUE THREAD

**Issue by emanueLczirai** [EFForg/https-everywhere#857]
When "Block all HTTP requests" is enabled, visiting any http site loads normally.

Tested with Firefox 34.0.5 (on Linux Manjaro) with kernel 3.19.0-rc2-gb7392d2
and latest master https-everywhere commit de8c62d15393fb0ec1679d4873536c84a4add1c6

The version that works(doesn't load http sites) is, the official(stable) https-everywhere (4.0.2): https://www.eff.org/files/https-everywhere-latest.xpi

Tested on a brand new firefox profile too, with 0 plugins(set to openh264 to Never Activate) and 0 other extensions.

**Comment by emanueLczirai** [comment]
With  `Block all HTTP requests` enabled, 
http://www.funtoo.org  site doesn't load, 
however http://www.funtoo.org/Welcome  works and loads.
But http://www.funtoo.org , with disabled `Block all HTTP requests`, will load and autoupdates url to http://www.funtoo.org/Welcome .

This seems to be the only case in which "Block all HTTP requests" works. Other http sites that I've encountered load ok regardless of this setting. eg. http://whatismyreferer.com

tested with commit: 4cbe605e4ceed8cb65bcc1f94d31ef9b59ef703f

**Comment by emanueLczirai** [comment]
Looks like the reason for this is because IOUtil.abort is failing:
`Cr is not defined`

```javascript
abort: function(channel, noNetwork) {
  channel.cancel(Cr.NS_ERROR_ABORT);
 },
```
`Cr` seems to be defined in `src/components/ssl-observatory.js`
`const Cr = Components.results;`
but there are 2 errors within this file which maybe affect this(?):

```
HTTPSEverywhere.getWindowForChannel is not a function ssl-observatory.js:621
nsIJSON.encode is deprecated.  Please use JSON.stringify instead.  ssl-observatory.js:586
```

The tested workaround seems to be: prepend this line `const Cr = Components.results;` in file `/src/chrome/content/code/IOUtil.js`
Unless I'm missing something, this works. Perhaps if the above `ssl-observatory.js` errors were fixed then this workaround wouldn't be needed? 

Thanks.

**Comment by jsha** [comment]
This is still an issue.

**Comment by emanueLczirai** [comment]
Is it? It works ok for me with 80d93de033ed676bc7cc876f9aed1336b2660036 
And now updated to latest commit and still working 938a1655c8dec23763b7fd6973a58774e5ea89ba
I'm on a laptop with Linux (not mobile phones)
Can you give some reproducible steps?
Thanks.

**Comment by emanueLczirai** [comment]
Is it possible that you hit #709 ? (so the icon looked red even though the setting itself was off)

**Comment by jsha** [comment]
Oops, you're right. It is indeed fixed, I just wasn't testing against the very latest master.
