### ISSUE TITLE
5.0development2 breaks mzl.la links in Firefox nightly

### ISSUE THREAD

**Issue by todesschaf** [EFForg/https-everywhere#858]
When running the most recent Firefox nightly (37.0a1 2015-01-01), https everywhere 5.0development2 seems to rewrite mzl.la links into bit.ly links, which is broken. I first noticed this when trying to go to http://mzl.la/teamweb, which should redirect to https://gear.mozilla.org/collections/apparel/products/mozilla-team-web-tshirt (and it does with https everywhere disabled). However, when https everywhere enabled, it instead redirects to http://bit.ly/a/warning?url=http%3a%2f%2fwww%2eteamviewer%2ecom%2fdownload%2fversion%5f6x%2fTeamViewer%5fHost%5fSetup%2eexe&hash=teamweb (which is what http://bit.ly/teamweb redirects to both with and without https everywhere).

**Comment by jsha** [comment]
Fixed.
