### ISSUE TITLE
Akamai rule blocks streams on ABC News

### ISSUE THREAD

**Issue by Akainaa** [EFForg/https-everywhere#8592]
Hello,

the streams on ABC News (video & Live) seem to be blocked. After disabling HTTPS they play well.

In the archive some earlier issues relate to Akamai, which is included in the ruleset. When I disable it the streams start to play. When I enable it they are blocked again.

HTTPS : 5.2.11
Firefox: 51.01 (64-bit)

The rules on ABC videos:
http://abcnews.go.com/international/video
![abc news rules 21 2 2017](https://cloud.githubusercontent.com/assets/19587172/23184548/85b92e4a-f880-11e6-8a78-045a0a24317a.PNG)

The rules on ABC Live:
http://abcnews.go.com/Live
![abc news live rules 21 2 2017](https://cloud.githubusercontent.com/assets/19587172/23184579/a4d2ddf8-f880-11e6-9fa6-2c0b0874fbd9.PNG)

**Comment by numismatika** [comment]
Usual CORS issue, combined with mixed content and an ugly loop on ABC News itself.
We can rewrite more of the page but without their help i would say this can't be properly solved.
