### ISSUE TITLE
[rules] Indymedia Grenoble is not self signed anymore

### ISSUE THREAD

**Issue by IndymediaGrenoble** [EFForg/https-everywhere#8632]
Hello. I come as a member of Indymedia Grenoble team.

Our certificate is not self signed anymore, and so, can be forced to https (even if we configured a 301 redirect to https, and HSTS).

**Comment by jeremyn** [comment]
Thanks for the issue @IndymediaGrenoble. What domains are you talking about specifically? Also if you are planning to HSTS preload (https://hstspreload.org) these domains then we would prefer not to include them in HTTPS Everywhere.

**Comment by IndymediaGrenoble** [comment]
We only work on grenoble.indymedia.org (and subdomains), so we can't HSTS preload indymedia.org entirely. :)

**Comment by Bisaloo** [comment]
`grenoble.indymedia.org` and its subdomains have been fully covered since 040e41090b90f82e778bed4208448f2cdb6cb8d9. Closing this issue. 

Feel free to reach out again if you happen to have other issues/requests about your subdomains in the future @IndymediaGrenoble.
