### ISSUE TITLE
AWS ruleset blocks loading of climate & history data on Weatherspark

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#874]
WeatherSpark is a fancy weather forecast app written in Flash.  I see the current Chrome stable AWS ruleset blocking loads of climate data on a page [like this one](http://weatherspark.com/#!dashboard;q=San%20Francisco%2C%20California%2C%20United%20States).  I haven't tested with Flash+Firefox yet.

**Comment by StevenRoddis** [comment]
My guy says this is a crossdomain.xml problem. Excluding it should fix it.
I will take this an investigate.

**Comment by StevenRoddis** [comment]
I had a look and the graphs load for me using Chrome 40 + HTTPSE 2015.1.22

I did notice weatherspark works with https so I'll make a rule for that site.
