### ISSUE TITLE
Release for WebExtensions

### ISSUE THREAD

**Issue by ssokolow** [EFForg/https-everywhere#8828]
[With the release of Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) (Entering stable channel in November, 2017), Mozilla plans to kill off XUL support.

I checked this tracker, the Tor tracker, the website, and the last several months of the mailing list, but I wasn't able to find any clear indication that this deadline is known, so I'm opening this issue report to ensure that I won't have to switch to Chrome or Firefox ESR when that deadline hits.

**Comment by e5f3c2ea895af0f27667** [comment]
Duplicate: https://github.com/EFForg/https-everywhere/issues/7389

**Comment by ssokolow** [comment]
Huh. I must've forgotten to make sure I unset the "open bugs only" filter when searching.
