### ISSUE TITLE
downgrade rules need periodic inspection

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#8833]
- [x] #8551
- [x] #8832 
- [x] #8834 
- [x] #8899 
- [x] #8906 
- [x] #9190 
- [x] #9271 
- [x] #9305 
- [x] #9311 
- [x] #9318 
- [x] #9319 
- [x] #9320 
- [x] #9334 
- [x] #9335 
- [x] #9339 
- [x] #9340 
- [x] #9349 
- [x] #9350 
- [x] #9381

**Comment by J0WI** [comment]
See also #7717

**Comment by ivysrono** [comment]
Apple: #8906

**Comment by J0WI** [comment]
#8551

**Comment by ivysrono** [comment]
#9271

**Comment by ivysrono** [comment]
Oak Ridge National Laboratory (partial) ?

I can't find downgrade rule on https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Oak-Ridge-National-Laboratory.xml

**Comment by J0WI** [comment]
The ruleset name has also changed, so this entry is obsolete.

**Comment by ivysrono** [comment]
#9304

**Comment by ivysrono** [comment]
#9311

**Comment by ivysrono** [comment]
#9318 
#9319 
#9320

**Comment by ivysrono** [comment]
#9334 
#9335 
#9339

**Comment by ivysrono** [comment]
#9349 
#9350

**Comment by ivysrono** [comment]
#9381 
End.
