### ISSUE TITLE
Videos on CBS Local don't show

### ISSUE THREAD

**Issue by OrganizedStalking** [EFForg/https-everywhere#8845]
http://sanfrancisco.cbslocal.com/2017/02/24/judge-orders-california-to-release-papers-discussing-risk-of-cell-phone-use/

**Comment by ivysrono** [comment]
I find several rulesets show red.
First fix:
#8848

**Comment by numismatika** [comment]
The Anv(ato) player is loaded via plain http and therefore i assumed active mixed content as the problem.
We can't secure that anv.bz stuff as it doesn't support TLS yet.

**Comment by Bisaloo** [comment]
Fixed by #14656 as well @J0WI
