### ISSUE TITLE
cdn.flashtalking.com does not always load with HTTPS

### ISSUE THREAD

**Issue by zneaa** [EFForg/https-everywhere#8878]
You can try it in https://www.phoronix.com/forums/

This resource doesn't load with HTTPS https://cdn.flashtalking.com/feeds/frameworks/js/api/20/FTFeed.min.js

I checked the flashtalking.com.xml rule but it seems cdn.flashtalking.com is included, is this a bug?

**Comment by gopherit** [comment]
I tried http://cdn.flashtalking.com/feeds/frameworks/js/api/20/FTFeed.min.js and landed on the https page just fine.

**Comment by Laayser** [comment]
@gopherit Actually @zneaa is correct, if you go to https://www.phoronix.com/forums/ then https://cdn.flashtalking.com/feeds/frameworks/js/api/20/FTFeed.min.js wont load using HTTPS.

**Comment by pipboy96** [comment]
Website does not seem to make any requests to `cdn.flashtalking.com` anymore. In addition, it redirects to HTTPS on its own, so there's no way to avoid mixed content warning unless the owners will fix it.
