### ISSUE TITLE
xkcd ruleset breaks uni.xkcd.com

### ISSUE THREAD

**Issue by GLolol** [EFForg/https-everywhere#888]
https://uni.xkcd.com/ tries to load http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js over plain HTTP, which gets blocked due to mixed content.

Tested with Chrome 39 + HTTPS Everywhere 2014.11.25, and Firefox 34 + HTTPS-Everywhere 4.0.2.

**Comment by reedy** [comment]
Might want to report this upstream too so that xkcd uses protocol relative urls

**Comment by StevenRoddis** [comment]
Project: https://github.com/chromakode/xkcdfools
Issue: https://github.com/chromakode/xkcdfools/issues/32
My pull request: https://github.com/chromakode/xkcdfools/pull/33
I'll ping Randall Munroe and see if we can get it fixed upstream.

**Comment by reedy** [comment]
Sweet, thanks! :+1:

**Comment by StevenRoddis** [comment]
Sadly xkcd has not fixed the problem, so I'll mark the rule `platform="mixedcontent"`
