### ISSUE TITLE
Time.com's SSL certificate is misconfigured, disable the ruleset

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/https-everywhere#8887]
[Time.com](https://www.time.com/) has its SSL certificate misconfigured, so the ruleset should be disabled.

**Comment by jeremyn** [comment]
Thanks for the report. https://time.com redirects to http://time.com but otherwise seems to work, so I suppose they fixed the problem on their side. Can you please confirm?

**Comment by anonsubmitter** [comment]
That is true, however, https://www.time.com/ does not redirect to the HTTP version of the site.
Example: http://www.time.com/time/magazine/article/0,9171,843812,00.html

**Comment by jeremyn** [comment]
Thanks for clarifying. I can confirm that there is an `invalid certificate` for https://www.time.com.

For reference, [here](https://github.com/EFForg/https-everywhere/blob/d96c3871542de6c24bd3806ab4bfda4d108f7990/src/chrome/content/rules/TIME.com.xml#L87) is where `www.time.com` is matched in `TIME.com.xml`. The ruleset should be rewritten to avoid using a wildcard, but a quicker fix of adding an [`exclusion`](https://www.eff.org/https-everywhere/rulesets#exclusions) for `www.time.com` would be okay for now.
