### ISSUE TITLE
Woot.com not working right

### ISSUE THREAD

**Issue by NathanAdored** [EFForg/https-everywhere#8905]
Today, I went to log into Woot.com and discovered that none of the mouse-over features at Woot.com were working anymore, at least not on any of the product pages.  Clicking on Sign In fails to bring up the login pane, mousing over the product image thumbnails along the right side on a product page does not cause the main product image to change accordingly, mousing over the different category names along the top  of the page (i.e. Home & Kitchen, Electronics, Computers, etc) does not bring up the related pane for those, either.  This was working fine the last time I was on Woot.com several days previously.

This is in the current version of  FIrefox on Windows 10 Pro 64bit .

If I turn HTTPS Everywhere off altogether in Firefox (i.e. for ALL websites in it), all those features on Woot,com start working again.

**Comment by numismatika** [comment]
CORS issue probably as the browser console is filled with them.
A lot of the pages content comes from cloudfront

**Comment by gloomy-ghost** [comment]
Woot.com supports https now and shouldn't be triggering CORS blocking anymore. Can you confirm if the issue is fixed?

**Comment by gloomy-ghost** [comment]
massive close per #15157
