### ISSUE TITLE
Exclusion for captive portal detection on Firefox for Android

### ISSUE THREAD

**Issue by serianox** [EFForg/https-everywhere#8921]
Android uses [http://clients3.google.com/generate_204](http://clients3.google.com/generate_204) to probe for captive portal on Wifi network. If the request does not return a status `204 No Content`, Android assumes that a captive portal is deployed on the network and shows a notification containing the text `Sign into Wifi`. Upon selecting this notification, Android starts the default browser to open this url, assuming the browser will land on the captive portal.

When _Firefox for Android_ is the default browser, and if HTTPS Everywhere is installed, the browser tries instead to fetch the webpage using HTTPS, which cause several issues, among others ([screen1](https://twitter.com/Serianox_/status/825648589200297985),[screen2](https://twitter.com/Serianox_/status/823690745693421568)):

- various certificate error if the captive portal tries to intercept on HTTPS anyway,
- connection error if the access point blocks HTTPS requests while the client is still unauthenticated,
- a blank page if the access point does not block HTTPS requests while the client is still unauthenticated.

This result in being unable to authenticate to a network using a captive portal without additional processing from the user, e.g.:

- temporarily or permanently disabling HTTPS Everywhere in Firefox, or
- reseting the default browser in Android to use Chrome instead.

These URL for captive portal detection should be whitelisted in HTTPS Everywhere.

The detection process is named _shill_ and is detailed [here](https://www.chromium.org/chromium-os/chromiumos-design-docs/network-portal-detection) for Chrome OS. Its behavior is consistent with the one encountered in Android, except that the URL list does not seem to be public or valid. It seems all Google endpoints, including [http://gstatic.com/generate_204](http://gstatic.com/generate_204) and [http://clients1.google.com/generate_204](http://clients1.google.com/generate_204) through [http://clients9.google.com/generate_204](http://clients9.google.com/generate_204) can be used and answer with a status `204 No Content`.

This issue was partially solved in #368.

**Comment by jeremyn** [comment]
Thanks for the report. This should be fixed by pull request #8947 which is included in the current version of the extension, so I'm closing this issue.

**Comment by serianox** [comment]
Tested and working.

Thanks!
