### ISSUE TITLE
"Block all unencrypted requests" mode unacceptably slow due to OCSP upgrade/retry logic

### ISSUE THREAD

**Issue by jseigel** [EFForg/https-everywhere#8931]
Sometimes when Firefox initiates a request with HTTPSEverywhere in the "Block all unencrypted requests" mode, it gets stuck in the "Connecting to ..." status. Connections eventually go through, but it might take 15-60 seconds, which is unacceptably slow. I've been noticing this for a while, but actually tried to track down the problem yesterday.

As I was logging out of YouTube, Firefox was attempting to connect to accounts.google.com and I saw the delay happening (this is not the only site I've had problems with). I ran tcpdump and saw a flood of traffic that looked like this:

`02:59:37.318699 IP [local IP].32952 > a23-60-139-27.deploy.static.akamaitechnologies.com.https: Flags [P.], seq 1:192, ack 1, win 229, options [nop,nop,TS val 12417359 ecr 1507624785], length 191
02:59:37.344509 IP a23-60-139-27.deploy.static.akamaitechnologies.com.https > [local IP].32952: Flags [.], ack 192, win 939, options [nop,nop,TS val 1507624812 ecr 12417359], length 0
02:59:37.344592 IP a23-60-139-27.deploy.static.akamaitechnologies.com.https > [local IP].32952: Flags [.], ack 192, win 939, options [nop,nop,TS val 1507624812 ecr 12417359], length 0
02:59:37.346817 IP a23-60-139-27.deploy.static.akamaitechnologies.com.https > [local IP].32952: Flags [.], seq 1:1389, ack 192, win 939, options [nop,nop,TS val 1507624815 ecr 12417359], length 1388
02:59:37.346897 IP [local IP].32952 > a23-60-139-27.deploy.static.akamaitechnologies.com.https: Flags [.], ack 1389, win 251, options [nop,nop,TS val 12417366 ecr 1507624815], length 0`

If I try to connect to that Akamai hostname over HTTPS, the server presents a certificate for `ocsp-ssl.ws.symantec.com`, which does not resolve in DNS. Interesting... but that hostname did give me a clue.

Looking at the OCSP URL listed in Google's intermediate certificate ("Google Internet Authority G2"), I found `http://g.symcd.com`, which resolves in DNS and does work over HTTP; however, if I try to connect over HTTPS, the server presents a certificate for `ocsp-ssl.ws.symantec.com`, which is of course a name mismatch and hence the certificate is untrusted.

My guess as to what's wrong: Based on #1004, OCSP requests over HTTP are blocked in the "Block all unencrypted requests" mode. However, HTTPSEverywhere recently implemented automatic connection upgrading, and based on the tcpdump traffic, OCSP requests appear to be subject to the same logic. I think this may be causing these requests to get stuck in a retry loop. The "randomness" of this problem as I experienced it is likely due to Firefox OCSP response caching behaviour.

Please audit the code paths that are followed under these failure conditions to ensure reasonable retry iterations and timeout lengths for OCSP (and probably CRL) requests. Thanks.

**Comment by Hainish** [comment]
Thanks for tracking this down @jseigel, this is very useful and I'll try to make a patch for it before the next release.

**Comment by Hainish** [comment]
@jseigel is there another testing url I can use? https://accounts.google.com/ loads just fine for me.

**Comment by Hainish** [comment]
Also if you can provide the version of Firefox you're using that would be useful.

**Comment by jseigel** [comment]
Unfortunately I don't have another URL to test as the behaviour is somewhat random. I'll try to document these going forward as I notice them.

I had the issue again last night logging out of YouTube, on Firefox 52 (Ubuntu 64-bit), but I don't think it's related at all to Firefox, as when I disable the "Block all unencrypted requests" option, everything just works again instantly.

Is there anything I can set in my Firefox configuration to help you debug? Logging? I understand you're trying to find a reproducible test case.

**Comment by jseigel** [comment]
Okay, this was super obvious, but it didn't occur to me when I posted before -- any site with a Symantec certificate has this behaviour. From checking a few sites, I've seen there are a couple variations of the HTTP OCSP URI in the certificate, but when navigating to the HTTPS version of the URI, the server always presents a certificate for the non-existent `ocsp-ssl.ws.symantec.com`.

I just experienced the issue with my bank's site. Another example is netflix.com. You can go down the Alexa Top 100 looking for sites with a Symantec-issued certificate and those should be valid test cases.

**Comment by Artefact2** [comment]
Is this still valid? I am experiencing the same kind of slowdowns only when I completely disable HTTP requests in the extension.

![](https://i.imgur.com/ihdFGMV.png)

![](https://i.imgur.com/g5jfsXM.png)

Are there any workarounds ?

**Comment by heckendorfc** [comment]
Disabling OCSP entirely has worked for me.

For Firefox, in about:config, set security.OCSP.enabled to 0.

**Comment by jseigel** [comment]
Since disabling OCSP entirely seemed heavy-handed to me, what I did was use a proxy PAC in FoxyProxy with some logic to black hole requests to *.symcb.com, *.symcd.com, and ocsp.godaddy.com (i.e., selectively disabling OCSP) -- I haven't had the issue since I did that.

I tried to reproduce the problem on the two domains you showed, but wasn't able to. I'll disable the proxy PAC rules and see if the issue returns.

**Comment by jseigel** [comment]
I haven't noticed the issue again after disabling the PAC file (and since FF57, FoxyProxy no longer supports PAC files). I didn't disable OCSP as suggested, so let's call this fixed. Thanks!

**Comment by Hainish** [comment]
Thank you!

On February 5, 2018 7:26:14 PM PST, Jon Seigel <notifications@github.com> wrote:
>Closed #8931.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/issues/8931#event-1459294112

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
