### ISSUE TITLE
hide icon on firefox

### ISSUE THREAD

**Issue by yukulele** [EFForg/https-everywhere#8946]
HTTPS Everywhere icon can't be hidded on firefox

**Comment by J0WI** [comment]
Of course it can. Have a look at this handy [tutorial](https://support.mozilla.org/t5/Customize-controls-options-and/Customize-Firefox-controls-buttons-and-toolbars/ta-p/2715).

**Comment by yukulele** [comment]
Ok sorry, usually I use "right-click" -> "Move to menu", that works with all others addons (even privacy badger)

thank you for your help!
