### ISSUE TITLE
chromium-preloads.py util uses outdated HSTS preload list source

### ISSUE THREAD

**Issue by klensy** [EFForg/https-everywhere#8955]
Hello.

Currently, script uses ```https://src.chromium.org/viewvc/chrome/trunk/src/net/http/transport_security_state_static.h?content-type=text%2Fplain``` as source for HSTS list, but it outdated.

More up to date source is ```https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json```.

But looks like this script isn't used anymore (or i can't find any track), so it can be removed.

**Comment by jeremyn** [comment]
Thanks for noticing that @klensy . It looks like [`chromium-preloads.py`](https://github.com/EFForg/https-everywhere/blob/ba5f5a1f52387bc66b0d7d8b32ed914e016a20de/utils/chromium-preloads.py) can be removed. @Hainish, do you agree?

**Comment by Hainish** [comment]
It looks like https://github.com/EFForg/https-everywhere/blob/0aa6a3256fe085646ac9dd8da7fd01a89e8cdfc7/utils/chromium-preloads.py duplicates the functionality of https://github.com/EFForg/https-everywhere/tree/0aa6a3256fe085646ac9dd8da7fd01a89e8cdfc7/utils/convert-hsts and can safely be deleted

**Comment by Hainish** [comment]
Deleted in https://github.com/EFForg/https-everywhere/commit/ba9b0ee3faa692a5a8c3f56e40a929e7ee010664
