### ISSUE TITLE
Add echo.opera.com to Opera rules

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#8959]

**Comment by RobGraham72** [comment]
https://github.com/EFForg/https-everywhere/pull/9051

**Comment by advaith1** [comment]
You can create a pull request [here](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Opera.xml).

**Comment by Bisaloo** [comment]
This is fixed by PR #6938 (once it's merged)
