### ISSUE TITLE
speedtest.tpg.com.au failing to load

### ISSUE THREAD

**Issue by scheinercc** [EFForg/https-everywhere#8970]
http://speedtest.tpg.com.au gets rewritten to https://speedtest.tpg.com.au which doesn't work - even when HTTPS Everywhere has been set to "disabled" in latest nightly 55.0a1 (2017-03-08) (64-bit) for Mac

**Comment by numismatika** [comment]
I doubt it is this addon. I can't reproduce that here and it also is unlikely that https-everywhere rewrites pages when it is not active. Does it show any active rules for that host ?

**Comment by gloomy-ghost** [comment]
HTTPS-Everywhere doesn't even have a ruleset for it: https://github.com/EFForg/https-everywhere/search?q=speedtest.tpg.com.au, can you disable other addons and try it again?

**Comment by scheinercc** [comment]
Thanks for checking, will try with all others disabled. It can't have been caught by https://www.eff.org/https-everywhere/atlas/domains/tpg.com.html, right?

**Comment by scheinercc** [comment]
It seems specific to one particular browser profile. I filled a but over in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1346624
