### ISSUE TITLE
https-everywhere doesn't work when accessing FTP server via HTTP

### ISSUE THREAD

**Issue by alexvong1995** [EFForg/https-everywhere#8987]
Consider this HTTP website: http://alpha.gnu.org/gnu/guix/

and its HTTPS variant: https://alpha.gnu.org/gnu/guix/. 

It seems https-everywhere fails to redirect the above HTTP link to its HTTPS variant.

I am using **Tor Browser 6.5.1** and **HTTPS Everywhere 5.2.12**.

Thank you!

**Comment by jeremyn** [comment]
Thanks for your report. By default, HTTPS Everywhere only rewrites URLs if they match a given ruleset. See [here](https://www.eff.org/https-everywhere/rulesets) for more information on rulesets. In this case, someone (you, perhaps) can look into updating the [`GNU.org.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/GNU.org.xml) ruleset to include http://alpha.gnu.org.

Another option is for you to enable the "Block all unencrypted requests" option in the HTTPS Everywhere add-on UI, in which case all URLs, including http://alpha.gnu.org/gnu/guix/ , should be rewritten to HTTPS. This can break a lot of sites though.

**Comment by alexvong1995** [comment]
Jeremy Nation <notifications@github.com> writes:

> Thanks for your report. By default, HTTPS Everywhere only rewrites URLs if they match a given
> ruleset. See here for more information on rulesets. In this case, someone (you, perhaps) can
> look into updating the GNU.org.xml ruleset to include http://alpha.gnu.org.
>
I see. I think I now understand why 'alpha.gnu.org' is not on the
ruleset. That's because it was only recently changed to support https. I
will update the ruleset once I figure out how to do it.

**Comment by Folant** [comment]
Well, since I completely updated it myself yesterday, I'm creating a pull request today.

**Comment by J0WI** [comment]
closed by #9002
