### ISSUE TITLE
dfat.gov.au ruleset is broken

### ISSUE THREAD

**Issue by lieryan** [EFForg/https-everywhere#8991]
I tried contacting [@dfat an Twitter](https://mobile.twitter.com/lieryan/status/840554936794398720), hopefully it will reach someone who can fix their site.

Example link: http://dfat.gov.au/ got redirected to https://www.dfat.gov.au, which gives SSL_ERROR_BAD_CERT_DOMAIN as the certificate used by the site doesn't contain www.dfat.gov.au.

**Comment by jeremyn** [comment]
Thanks for the report. Here is the ruleset for reference: [`DepartmentofForeignAffairsandTrade.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/DepartmentofForeignAffairsandTrade.xml)

**Comment by pipboy96** [comment]
Can no longer reproduce. Both https://dfat.gov.au/ and https://www.dfat.gov.au/ work now.
