### ISSUE TITLE
NAACP Site Broken / Rulesets

### ISSUE THREAD

**Issue by daniel-barrows** [EFForg/https-everywhere#8993]
HTTPS Everywhere appears to cause a problem with the NAACP website.

The problem can be repeated by attempting to visit the following URL with HTTPS Everywhere active:
http://www.naacp.org/issues/criminal-justice/

I was able to avoid the problem by adding an exception for the NAACP domain. However, I recommend modifying HTTPS Everywhere rulesets.

navigator.userAgent="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
HTTPS Everywhere 5.2.11

**Comment by jeremyn** [comment]
[`NAACP.xml`](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/NAACP.xml) ruleset, for reference.

**Comment by jeremyn** [comment]
Thanks for the report. Pull request https://github.com/EFForg/https-everywhere/pull/9141 fixes this problem and generally updates three NAACP rulesets. Please feel free to download and test the new rulesets yourself using the instructions [here](https://www.eff.org/https-everywhere/rulesets#testing), and let us know here if you have any trouble.

**Comment by pipboy96** [comment]
Fix PR merged.
