### ISSUE TITLE
Make Disqus not experimental

### ISSUE THREAD

**Issue by mattrobenolt** [EFForg/https-everywhere#900]
I'm not sure how we can do this, but I'd say that the Disqus support is solid and I've been helping maintain the list personally to make sure it works well. There's no need to have it still flagged as experimental.

**Comment by jsha** [comment]
Awesome, thanks for your work maintaining the ruleset. Based on your testing, I've put up a pull request to enable the rule by default in 4.0 (which will get merged into 5.0): https://github.com/EFForg/https-everywhere/pull/917.

If you don't mind my asking, how close is Disqus to HTTPS-by-default, and what obstacles stand in the way?

**Comment by mattrobenolt** [comment]
All I can say publicly is "close". :) I won't put a deadline on it, but I'm working hard on it.

**Comment by jsha** [comment]
Glad to hear it! Hopefully when you're done you can blog about it. Always good to hear about people's deployment experiences, it helps other folks along the way.

**Comment by mattrobenolt** [comment]
We definitely will. It's been a long work in progress.
