### ISSUE TITLE
politico.com ruleset broken

### ISSUE THREAD

**Issue by andrew-fuchs** [EFForg/https-everywhere#9000]
Politico.com URLs are being rewritten incorrectly.

For example:

    http://www.politico.com/agenda/story/2017/03/national-obesity-tracking-experiemnt-000335

Is rewritten to:

    https://secure.politico.com/agenda/story/2017/03/national-obesity-tracking-experiemnt-000335

**Comment by liquidsunshine** [comment]
I can confirm that this happens for me as well.  Chrome 57.0.2987.98 (64-bit) on Ubuntu 16.04.2.

To elaborate, the redirect results in a 404, and this seems to happen consistently with Politico links I have clicked on.  Disabling the "Politico.com (partial)" rule fixes the issue.

**Comment by Diagoras** [comment]
I can also confirm this, both with Chrome 56.0.2924.87 (64-bit) on El Capitan 10.11.4 and and with Firefox Mobile on Android.

To provide another example, this:

`http://www.politico.com/magazine/story/2017/03/why-courts-shouldnt-try-to-read-trumps-mind-214921`

is rewritten to:

`https://secure.politico.com/magazine/story/2017/03/why-courts-shouldnt-try-to-read-trumps-mind-214921`

**Comment by diego898** [comment]
I can also confirm - Is there a workaround besides right-clicking and opening incognito?

**Comment by liquidsunshine** [comment]
@diego898 - You can disable the Politico rule individually.  That should work around the issue.  However, until/unless it can be properly fixed, I think the rule should be removed from HTTPS Everywhere.

**Comment by gordon-morehouse** [comment]
This is happening for me on Chromium 56.0.2924.76 and Firefox 52.0.1 on Linux.

For people who are unfamiliar, a ruleset can be disabled by clicking the HTTPS Everywhere icon when on the site and then unchecking the "Politico (partial)" checkbox.

**Comment by diego898** [comment]
@gordon-morehouse thank you for the clear instructions!

**Comment by diego898** [comment]
Do I have to manually re-enable this rule if/when the issue is fixed?

**Comment by cschanaj** [comment]
Related: #9361

**Comment by J0WI** [comment]
The rule has been disabled in #9528

**Comment by gordon-morehouse** [comment]
It might be good to address pull request #9518 before forgetting about this, because I fixed every problem that I was able to observe.
