### ISSUE TITLE
nknews.org page layout is broken with HTTPS-E enabled

### ISSUE THREAD

**Issue by austin987** [EFForg/https-everywhere#902]
Example url:
http://www.nknews.org/2015/01/orders-not-always-followed-in-pyongyang-traffic-officer-tells-pro-nk-media/ / https://www.nknews.org/2015/01/orders-not-always-followed-in-pyongyang-traffic-officer-tells-pro-nk-media/

then HTTPS version doesn't load graphics, breaking the layout.

5.0Development2

**Comment by reedy** [comment]
So, it seems the site by default doesn't use protocol relative URLs. Which causes part of the problem.

But most of the CSS and JS are loaded from its own domain, and can be loaded over HTTPS...

**Comment by austin987** [comment]
Looks like there's a PR here:
https://github.com/EFForg/https-everywhere/pull/755

I tested it, but it doesn't work when applied to 5.0development.4-4-g517e001

**Comment by reedy** [comment]
You might want to comment on that pull request
