### ISSUE TITLE
The Pirate Bay is back up, and it no longer supports SSL/TLS

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#905]
The page at https://www.thepiratebay.se/ displays your web browsers usual error page. Removing the HTTPS and using regular HTTP loads the web page, but only if you force HTTPS Everywhere to be disabled or disable The Pirate Bay ruleset.

I would make a temporary change, because I have a feeling in 15 days when they make whatever announcement on their website, it will probably be something along the lines of "we're back".

I would have made the change myself, but my development machine is currently down and out. Hopefully this issue doesn't go the same way the last one did (an ignored, stale issue for months until it isn't relevant anymore).

**Comment by iambibhas** [comment]
This no longer shows the error page for the HTTPS. Could this be turned on please? It's really annoying to see the HTTP page being blocked with some ISP. Also, is it possible to define the ruleset inside my browser to force redirect to HTTPS?

**Comment by reedy** [comment]
You mean re-enable https://www.thepiratebay.se/ ?

**Comment by iambibhas** [comment]
@reddy yes. https://thepiratebay.se/ doesn't throw any error anymore. `.org.` seems to redirect to `.se` now.

**Comment by vgturtle127** [comment]
The .se domain actually now redirects to .mn. There are also 4 other backup domains, .gd, .la, .am, and .gs. So add rules for all of them, if you please. They all support SSL/TLS.

**Comment by kirelagin** [comment]
Actually, it is showing the error again.

**Comment by vgturtle127** [comment]
@kirelagin Works fine for me on the latest versions of Firefox and Chrome. You should check your settings and update to the latest version if you haven't yet.
