### ISSUE TITLE
Akamaihd.net ruleset breaks ooyala videos

### ISSUE THREAD

**Issue by Leonick** [EFForg/https-everywhere#9052]
In my particular case I'm trying to watch the premium videos at tested.com, the akamaihd.net ruleset break the videos.

When checking now the video was streamed from 94890ooyala-a.akamaihd.net

**Comment by numismatika** [comment]
Any mixed content or CORS warnings?
Is the OOyala rule active too?
Are there network requests to api.ooyala.com?

**Comment by Leonick** [comment]
Clicking play gives this in web console:
`GET XHR http://player.ooyala.com/player/all/B3dzY5OTE6_YMfk1WrB7y_nm4UmraSTx_1800.m3u8 [HTTP/1.1 200 OK 0ms]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://94890ooyala-a.akamaihd.net/B3dzY5OTE6_YMfk1WrB7y_nm4UmraSTx/HbKJtGy6IOu2wtc_6QWgqKq385rvEfCn6PpX4k4l_MHsyAmipQwGo4sFcPJelwWB/0.ts. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).`

Network log says Access-Control-Allow-Origin is "*".

The OOyala rule is inactive as Tested forces http on all pages but the login page.

No requests to api.ooyala.com, only player.ooyala.com.

Disabling Akamai rule makes video play in Firefox. Noticed last night that it works in without disabling any rules in Chromium based browsers.

**Comment by numismatika** [comment]
This null comparison seems weird, not sure where it comes from.

**Comment by numismatika** [comment]
Enabling OOYala doesn't fix it?

**Comment by Leonick** [comment]
No, forcing the ooyala ruleset only breaks the player further as tested is forcing itself to be http.

> - player.ooyala.com
>			Player JS correctly chooses secure player based on parent document
>			protocol, but fails if parent document is HTTP and player is rewritten to
>			HTTPS. Therefore, only enabled on mixedcontent platforms.

**Comment by Bisaloo** [comment]
All CORS issues will be fixed in the next release by #15157. Please reopen if you still have issues.
