### ISSUE TITLE
Mozilla Add-ons Lags Behind EFF Release Schedule by Several Weeks

### ISSUE THREAD

**Issue by gopherit** [EFForg/https-everywhere#9096]
_Edited Post:_
The official [Mozilla Add-ons page for HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) where many/most users would get this add-on falls behind the latest release.  For example, Mozilla shows 5.2.11 while 5.2.13 is the latest release.

_Original Post:_
I use the HTTPS Everywhere add-on in Thunderbird 52.0b4 (32-bit) for Windows, and it's still on 5.2.11.  And back when 5.2.11 was released, it was on 5.2.10 until just a couple weeks ago.  Is this something on Mozilla's end with the Thunderbird repository or something in our control?

**Comment by jeremyn** [comment]
I haven't installed HTTPS Everywhere in Thunderbird, but on Firefox it's still 5.2.11. So if there is some kind of version problem, it's not just with Thunderbird.

**Comment by gopherit** [comment]
5.2.12 shipped on [March 9](https://www.eff.org/https-everywhere), and all my Firefox, Tor Browser Bundle, and Orfox (Android) updated that day.  For me, it's just Thunderbird that lags behind for 3-4 weeks on the prior version.

**Comment by jeremyn** [comment]
@gopherit I'm on Ubuntu. What OS are you using?

@Hainish Any idea what's going on here?

**Comment by gopherit** [comment]
@jeremyn Firefox Beta and Firefox Developer Edition on Windows 7 64-bit.  Firefox Beta for Android and Orfox for Android.  And Tor Browser Bundle for Windows.  2 laptops with the above, so like half a dozen HTTPS Everywhere installs (ha).

It's not a showstopper, was just curious about how the Thunderbird add-ons worked and what the cause of the delay was.

**Comment by Bisaloo** [comment]
From what I have seen, the HTTPS-Everywhere version shipped by the mozilla add-on store always lags behind the release cycle.

To get the latest version of HTTPS-Everywhere, I had to install from the EFF website: https://www.eff.org/https-everywhere

Note that both sources provide signed add-ons, as required by firefox.

**Comment by jeremyn** [comment]
On https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/?src=search it shows v5.2.11 from February 14, 2017.

@Hainish Is there anything we can do about addons.mozilla.org providing old versions?

**Comment by Hainish** [comment]
I've sent an email to a colleague at Mozilla who hopefully can alleviate this problem, or at least direct me to someone who can.  I agree, it's pretty insane to have to wait for weeks until a release is deployed by AMO.  Luckily none of our releases recently have fixed security issues, but this won't be the case forever.  This level of delay is pretty new, I remember last year it wouldn't take nearly as long to get through review, maybe on average a day or two.

**Comment by jeremyn** [comment]
Oh, I hadn't considered the delay being in Mozilla's manual review process. For reference: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews , and also this discussion about review times in 2015/early 2016: https://blog.mozilla.org/addons/2016/03/04/breakthroughs-in-the-add-on-review-queues/

**Comment by gopherit** [comment]
I had originally incorrectly thought this was Thunderbird related, since all my Firefox instances are always up-to-date.  I must be getting the auto-updates directly from EFF instead of Mozilla except for Thunderbird.  Updated the Issue to more accurately reflect that this is on Mozilla's end, likely do their manual review process.

**Comment by jeremyn** [comment]
Does HTTPS Everywhere update itself outside of AMO? According to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews , that's not allowed for "Listed" add-ons ("Include their own update mechanism").

**Comment by Hainish** [comment]
@jeremyn here, the AMO-hosted and EFF-hosted addons should be considered separately.  The AMO-hosted addon does not attempt to update itself outside of the regular AMO mechanisms.  The EFF-hosted addon updates itself through a manifest file hosted on EFF.  Since these are considered separately, we are following AMO policies.

**Comment by jeremyn** [comment]
Does that mean the add-on I can download from AMO isn't exactly the same that I can download from EFF, or is it the same code that just reacts differently depending on whether it's installed from AMO or not?

**Comment by Hainish** [comment]
Functionality-wise, the only difference in the addons is the update mechanism.

**Comment by jeremyn** [comment]
So it is different code in the AMO vs the EFF build? I'm not saying it's wrong, I'm just clarifying.

**Comment by Hainish** [comment]
The code is the same. I believe Firefox keeps track of how the addon was originally installed, and uses the appropriate update mechanism.

**Comment by jeremyn** [comment]
Got it, thanks.

**Comment by Hainish** [comment]
I've been talking with a contact in Mozilla, who says about the release review process:

"A policy change is in the works that I believe is rolling out next week."

... and got the 5.2.13 release pushed out quickly.  Hopefully this problem will be alleviated in the future.  Closing for now, feel free to open a new ticket if this problem recurs.
