### ISSUE TITLE
mmo-champion.com broken via https

### ISSUE THREAD

**Issue by PekaFat** [EFForg/https-everywhere#9123]
HTTPS-Everywhere ver. 2017.3.17 now redirect http to https on mmo-champion.com and what it looks like:
![image](https://cloud.githubusercontent.com/assets/13280748/24073500/b4db6522-0c11-11e7-8c49-08a51e9f2020.png)

mmo-champion.com does not support https, please, fix it.

**Comment by jeremyn** [comment]
Thanks for the report. We recently merged a large set of related changes in https://github.com/EFForg/https-everywhere/pull/6287, and then later a specific fix in https://github.com/EFForg/https-everywhere/pull/9015 for the problem you describe here. Unfortunately it looks like the fix just missed the release that we had yesterday. This should be resolved in the next release.
