### ISSUE TITLE
Old rule for lostfilm.tv not working

### ISSUE THREAD

**Issue by kronblase** [EFForg/https-everywhere#9128]
http://lostfilm.tv → https://lostfilm.tv

**Comment by jeremyn** [comment]
[`lostfilm.tv.xml`](https://github.com/EFForg/https-everywhere/blob/56940e67e657a8903a16686da1f892f64dc2148b/src/chrome/content/rules/lostfilm.tv.xml) is a relatively new ruleset. This rewrite should be included in the current version of the extension, which is [5.2.13/2017.3.17](https://www.eff.org/https-everywhere). Please be sure you're using the most current version, and let us know if this is still not working for you.

**Comment by kronblase** [comment]
Clear. But I use extensions from addons.mozilla.org, and there it is slightly outdated (5.2.11).

**Comment by jeremyn** [comment]
I suspected that might be the problem. We're discussing the addons.mozilla.org lag in issue https://github.com/EFForg/https-everywhere/issues/9096, however this separate issue should be closed.

**Comment by kronblase** [comment]
I just installed version 5.2.13 from eff.org. Now **lostfilm.tv** is opened as-needed. It's strange that the addon did not delete the old version. I had to delete it manually.

**Comment by jeremyn** [comment]
Thanks for letting us know that it is fixed for you in the new version.
