### ISSUE TITLE
"View XML Source" command tries to access wrong URL

### ISSUE THREAD

**Issue by tanmatra** [EFForg/https-everywhere#914]
Dialog states, for example:

Filename: GoogleSearch.xml
URL: https://gitweb.torproject.org/https-everywhere.git/blob_plain/HEAD:/src/chrome/content/rules/GoogleSearch.xml
Unable to download source.

While the correct URL, it seems, would be:
https://gitweb.torproject.org/https-everywhere.git/plain/src/chrome/content/rules/GoogleSearch.xml

Version 4.0.2

**Comment by reedy** [comment]
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/fetch-source.js#L30-L32 is at fault
