### ISSUE TITLE
Specific settings for Private IP space (rfc1918) ?

### ISSUE THREAD

**Issue by juju4** [EFForg/https-everywhere#9142]
Currently HTTPS everywhere is a global setting.
There should be an option to include/exclude private IP space where traffic might not be encrypted or with lower tls settings (self-signed, ...)

Thanks

**Comment by jeremyn** [comment]
Thanks for your idea, but do you think we can close this issue as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2323?

**Comment by juju4** [comment]
In my opinion, rf1918 and localhost should be two different settings or an editable whitelist.
After from a code perspective, it would be probably the same.

**Comment by jeremyn** [comment]
Having a whitelist was suggested in https://github.com/EFForg/https-everywhere/issues/2323#issuecomment-167377814.

**Comment by jeremyn** [comment]
I'm closing this issue as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2323.
