### ISSUE TITLE
Prompt me the best resource for finding the maximum number of subdomains.

### ISSUE THREAD

**Issue by kronblase** [EFForg/https-everywhere#9151]
Prompt me the best resource for finding the maximum number of subdomains. Thank you in advance.

**Comment by Bisaloo** [comment]
[`Sublist3r`](https://github.com/aboul3la/Sublist3r), as recommended in the [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#enumerating-subdomains), works quite well.

**Comment by jeremyn** [comment]
I'm closing because the question has been answered.
