### ISSUE TITLE
Clean up duplicate-whitelist.txt

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9166]
The file [`duplicate-whitelist.txt`](https://github.com/EFForg/https-everywhere/blob/master/utils/duplicate-whitelist.txt) has outdated entries. 

For example, [`elementaryos.org`](https://github.com/EFForg/https-everywhere/blob/master/utils/duplicate-whitelist.txt#L79) doesn't seem to be an issue anymore ([proof](https://www.eff.org/https-everywhere/atlas/?elementaryos.org)).

I think it's difficult to ask contributors to know about this file and to think about checking it each time they submit a PR.

The best solution in my opinion would be to have an automated way to update this file. Two options come to mind:
- a script that run on a regular basis and remove outdated entries
- a small addition to travis checks to ask the contributor to remove an entry if it is in the whitelist but that's not needed after their changes.

**Comment by jeremyn** [comment]
We have a script that removes whitelist entries, [`utils/ruleset-coverage-whitelist-cleanup.sh`](https://github.com/EFForg/https-everywhere/blob/83d2966432c03a9e0df2f21acfa60e5754cf850f/utils/ruleset-coverage-whitelist-cleanup.sh). The normal process it that someone runs it every now and then, which you can see looking through [past issues and pull requests](https://github.com/EFForg/https-everywhere/search?q=whitelist&type=Issues&utf8=%E2%9C%93).

It's not really urgent to clean up the file. We should not confuse contributors by asking them to modify that file for each pull request.

**Comment by Bisaloo** [comment]
I may be mistaken but it looks like this script only cleans up [`ruleset-coverage-whitelist.txt`](https://github.com/EFForg/https-everywhere/blob/83d2966432c03a9e0df2f21acfa60e5754cf850f/utils/ruleset-coverage-whitelist.txt), which is a different file from the one I am talking about : [`duplicate-whitelist.txt`](https://github.com/EFForg/https-everywhere/blob/master/utils/duplicate-whitelist.txt)

**Comment by jeremyn** [comment]
Oh, you're right. I didn't know about that file. It looks like it's used [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/utils/trivial-validate.py#L39).

We still shouldn't ask random contributors to look at the file. I agree there should be some cleanup process on that file, manually or automated.
