### ISSUE TITLE
Why can not I finish the Travis check?

### ISSUE THREAD

**Issue by kronblase** [EFForg/https-everywhere#9167]
Why can not I finish the Travis check? I did not screw up with the script.

```
<ruleset name="Nvidia.ru">        
            <target host="nvidia.ru" />        
	    <target host="www.nvidia.ru" />       
	    <target host="ru.download.nvidia.com" />
	    <target host="store.nvidia.ru" />
            <target host="store-stage.nvidia.ru" />	
    
            <rule from="^http://nvidia\.ru/" to="https://www.nvidia.ru/" />
            <rule from="^http:" to="https:" />
</ruleset>
```

But always the same:

../src/chrome/content/rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Expecting an element test, got nothing

../src/chrome/content/rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Expecting an element target, got nothing

../src/chrome/content/rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Invalid sequence in interleave

../src/chrome/content/rules/nvidia.ru.xml:1: element ruleset: Relax-NG validity error : Element ruleset failed to validate content

../src/chrome/content/rules/nvidia.ru.xml fails to validate

ERROR: Validation of rulesets against relaxng.xml failed.

**Comment by jeremyn** [comment]
Please ask for help in the specific pull request (https://github.com/EFForg/https-everywhere/pull/9153) instead of opening a new issue.
