### ISSUE TITLE
Update travis 'rules' error message

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9170]
Travis still points to https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md in its [error message](https://github.com/EFForg/https-everywhere/blob/85824bbdc84d47017f387dd00738ca0c52d1391a/test/rules.sh#L35).

But it was deleted in https://github.com/EFForg/https-everywhere/commit/f2381549e5902629a97ae96449bd9c1dc3b81879.

So the error message should now point to the [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md).

**Comment by Bisaloo** [comment]
The link in the [FAQ on the EFF website](https://www.eff.org/https-everywhere/rulesets) should be removed/updated as well.

@Hainish

**Comment by Hainish** [comment]
Fixed as of https://github.com/EFForg/https-everywhere/commit/a27cd74fceb65af1da1f0393582288ec727b09ef and on the website.
