### ISSUE TITLE
dell.com (partial) rule breaks Dell XPS shop page

### ISSUE THREAD

**Issue by AgentME** [EFForg/https-everywhere#9246]
At http://www.dell.com/en-us/shop/category/laptops/xps-laptops, the "refine your search" dropdown menus don't work because of the "dell.com (partial)" rule. Disabling the rule fixes the page.

----

When you try to use one of the dropdown menus, you get this error in the console:

```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘http://universal.iperceptions.com’) does not match the recipient window’s origin (‘https://universal.iperceptions.com’).
```

Initially from this error I thought that disabling the iperceptions.com rule would fix it. It seems to fix the error, but doesn't fix the page.

**Comment by CubeTheThird** [comment]
I have experienced similar issues with dell.com
On this page, the configurator section fails to load: http://www.dell.com/en-us/shop/productdetails/alienware-13-laptop
Disabling the aforementioned rule fixes this too.

**Comment by advaith1** [comment]
Works fine for me, all the dropdowns work.

**Comment by petteyg** [comment]
Cannot load the dropdown "processor"/"memory" etc. menus on any section of their store pages with HTTPS Everywhere enabled. Most of the site just gives me blank pages with nothing but the menus. Turn HTTPS Everywhere off and everything on dell.com immediately starts working.

**Comment by koops76** [comment]
@J0WI Should we temporarily disable Dell.com ruleset?

**Comment by J0WI** [comment]
We should just exclude the specific requests to `afcs.dell.com`.

**Comment by koops76** [comment]
@J0WI Which URLs should we exclude?

**Comment by J0WI** [comment]
As far as I can see resources from `https://afcs.dell.com/bundles/` are affected.
