### ISSUE TITLE
Weird black blinking rectangles

### ISSUE THREAD

**Issue by onnokort** [EFForg/https-everywhere#9250]
Hi,

with HTTPSEverywhere enabled, I get a weird, momentarily blinking black rectangle on a couple sites, usually where a form (e.g. login form) is present, in the upper left screen area of FF. Just for like a tenth of a second or so.

I get this behavior e.g. for the login page on ebay.de.

Version: 5.2.13
FF: 49.0.2 on trusty ubuntu64 bit

I noticed it is httpseverywhere as I disabled/enabled this plugin and restarted FF. For the test, I have disabled all other plugins.

**Comment by jeremyn** [comment]
Thanks for the report. Can you please provide a specific, direct URL where you see the problem, ideally a site in English?

**Comment by pipboy96** [comment]
Pre-WebExtensions Firefox. Closing.
