### ISSUE TITLE
HTTPS Everywhere breaks Seriouseats.com videos

### ISSUE THREAD

**Issue by vidiat** [EFForg/https-everywhere#9263]

**Comment by Bisaloo** [comment]
> 08:29:37.526 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://hlsak-a.akamaihd.net/4841592010001/5361782679001/4841592010001_5361782679001_s-1.ts?pubId=4841592010001&videoId=5361756079001. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). 1 (unknown)

The culprit is the akamai ruleset.

**Comment by Bisaloo** [comment]
@J0WI, this is fixed since you merged #14710
