### ISSUE TITLE
HTTPS brakes livetrack.garmin.com

### ISSUE THREAD

**Issue by pprucia** [EFForg/https-everywhere#9303]
"Service Unavailable
The server is temporarily unable to service your request. Please try again later."

Over http site is working fine.

Mac OS X 10.11.6
Firefox 52.0.1

**Comment by advaith1** [comment]
I can confirm the error, the TLS is misconfigured.

The garmin.xml file includes *.garmin.com.

> This server could not prove that it is livetrack.garmin.com; its security certificate is from a248.e.akamai.net. This may be caused by a misconfiguration or an attacker intercepting your connection. Learn more.

**Comment by pipboy96** [comment]
Domain seems to fully support HTTPS now.
