### ISSUE TITLE
Please consider adding "Block all unencrypted requests" to the Firefox mobile addon

### ISSUE THREAD

**Issue by DapperedX** [EFForg/https-everywhere#9315]
First and foremost apologies if this is the incorrect way to request this, I'm a newb to Github. 

**Device-** Moto X 2014
**OS-** LineageOS 14.1- Android 7.1.1
**Browser-** Firefox Aurora version 54.0a2
**Addon Version in Question-** HTTPS Everywhere version 5.2.13
**Addon Installed From-** Official Firefox Add-On repository 

Block all unencrypted requests is an option in HTTPS Everywhere on the DESKTOP addon. It's not available as a setting in the mobile addon. 

I think this setting being missing is critical with the new ruling allowing US ISP's to track and sell our history to advertisers. 

Thank you

**Comment by Bisaloo** [comment]
This is fixed as far as I can tell. @DapperedX, feel free to report back if you're still having issues.
