### ISSUE TITLE
Sometimes we break Google Image Search on mobile Firefox

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#933]
The broken end-state is something like this:

https://images.google.com/search?tbm=isch

It seems to depend on both which starting point you take (go to images.google.com vs search and then click images), and to be a little nondeterministic.

**Comment by jsha** [comment]
Related to https://github.com/EFForg/https-everywhere/issues/1096

**Comment by semenko** [comment]
Tentative closing (per #1096), since I haven't seen this in a while -- likely fixed on Google's end.
