### ISSUE TITLE
sci-hub rules break redirection

### ISSUE THREAD

**Issue by doegox** [EFForg/https-everywhere#9332]
http://sci-hub.cc redirects to https://moscow.sci-hub.ac which is a 403 Forbidden
while https://sci-hub.cc is working fine.

So all the redirections to https://moscow.sci-hub.ac must be changed and imho a simple http to https rule should be enough:

* https://www.eff.org/https-everywhere/atlas/domains/sci-hub.ac-2.html
* https://www.eff.org/https-everywhere/atlas/domains/sci-hub.bz-2.html
* https://www.eff.org/https-everywhere/atlas/domains/sci-hub.cc-2.html
* https://www.eff.org/https-everywhere/atlas/domains/sci-hub.io-2.html
* https://www.eff.org/https-everywhere/atlas/domains/sci-hub.org.html

Note that http://sci-hub.la fails being redirected at all (https://www.eff.org/https-everywhere/atlas/domains/sci-hub.la.html)

**Comment by Bisaloo** [comment]
it's been fixed in #8561. We just need to wait for a release for the changes to get out now.

**Comment by doegox** [comment]
thanks
