### ISSUE TITLE
Perfect Forward Secrecy

### ISSUE THREAD

**Issue by r-barnes** [EFForg/https-everywhere#9343]
I wonder if it is possible to somehow highlight when a site is using Perfect Forward Secrecy vs. not?

This would seem to fit with the EFF's goal of [pushin PFS](https://www.eff.org/deeplinks/2013/08/pushing-perfect-forward-secrecy-important-web-privacy-protection).

**Comment by numismatika** [comment]
Key Exchange and related parameters are visible to addons.
This can be seen in https://calomel.org/firefox_ssl_validation.html

**Comment by r-barnes** [comment]
Looks like Firefox is changing their API so Calomel won't work anymore.

**Comment by numismatika** [comment]
where is this planned?

**Comment by gloomy-ghost** [comment]
The WebExtension doesn't provide such information (yet), so I'll close this issue for now as we can't do anything until it's supported in browsers.
