### ISSUE TITLE
How to handle rules that are prohibited by Tor only

### ISSUE THREAD

**Issue by ivysrono** [EFForg/https-everywhere#9395]
For example:
https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/bcebos.com.xml

SSL LABS grade B all of them.

Timeout on Tor browser 6.5.1
and travis : https://travis-ci.org/EFForg/https-everywhere/jobs/217819999#L452

**Comment by jeremyn** [comment]
We had a similar problem in PR https://github.com/EFForg/https-everywhere/pull/8940#issuecomment-288314081 with a suggested solution by @Bisaloo of:

> The only option I can think of right now is splitting this ruleset in `PBS.xml` and `PBS-problematic.xml` and put `platform="firefox chromium"` in `PBS-problematic.xml`

I haven't looked at the specific ruleset you linked but that solution seems okay to me generally.

**Comment by ivysrono** [comment]
Thanks.
I did not know platform more than mixedcontent before.
BTW, No Opera?

**Comment by Bisaloo** [comment]
The possible platforms are listed in [this file used by travis](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/utils/relaxng.xml#L15).

So as far as I know, no opera.

**Comment by ivysrono** [comment]
@Bisaloo Thanks.
We get some strange check error, Ok on Firefox, Chrome, Tor, however, timeout by travis.
#6921 
#9421
