### ISSUE TITLE
Incompatibility with Decentraleyes

### ISSUE THREAD

**Issue by darkenvy** [EFForg/https-everywhere#9404]
> Warning:
This extension failed to redirect a network request to https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js because another extension (Decentraleyes) redirected it to chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/1.8.2/jquery.min.js.dec

Decentraleyes is doing what it does. No error really occurs and a thrown error should be avoided in this case.

**Comment by Bisaloo** [comment]
Related issue in decentraleyes repo: https://github.com/Synzvato/decentraleyes/issues/148

**Comment by vidia** [comment]
I thought I'd chime in because I got the same error today. Is there a way to choose the processing order for extensions to prevent this?

**Comment by scriptHero** [comment]
@vidia 

> Only one extension is allowed to redirect a request [...] at a time. If more than one add-on attempts to modify the request, the most recently installed add-on wins and all others are ignored.

from ibrokemypie on the decentraleyes repo issue linked above

**Comment by vidia** [comment]
I see that now. Thank you.

I wonder if that's something that Chromium would consider changing. It
would add a lot of complexity, but I think it would be worth it.

**Comment by Synzvato** [comment]
Follow this brief guide to resolve the redirection conflicts:
https://decentraleyes.org/configure-https-everywhere/

**Comment by pipboy96** [comment]
Seems to be something we can't fix in any way, being related to how WebExtensions works. Manual fix already exists.
