### ISSUE TITLE
Pictures broken on iDownloadBlog.com

### ISSUE THREAD

**Issue by ymanden1991** [EFForg/https-everywhere#9412]
All pictures on [iDownloadBlog.com](url) are broken.

**Comment by Elehiggle** [comment]
Can confirm. At first I was browsing IDB for months without proper images. Now, since they have redesigned their page a few days ago, you only have plain text, which is unusable.

**Comment by Bisaloo** [comment]
This is fixed by #10085 as far as I can tell. @ymanden1991 @Elehiggle can you confirm?
