### ISSUE TITLE
BootstrapCDN.com rule partially breaks icons on theblaze.com

### ISSUE THREAD

**Issue by plieblang** [EFForg/https-everywhere#9432]
The icons on the header banner are broken.  By selectively disabling rules, I discovered the problem was with BootstrapCDN.com.
![theblaze_broken](https://cloud.githubusercontent.com/assets/17536531/24690548/15f75594-1993-11e7-8afa-ce1eb3ade109.PNG)
versus
![theblaze_proper](https://cloud.githubusercontent.com/assets/17536531/24690558/262e5318-1993-11e7-8f14-26057b0863d6.PNG)

**Comment by numismatika** [comment]
CORS issue, the remote fonts can't be loaded without a suitable header.
Theblaze itself can't be rewritten by https-everywhere because of mixed-content issues.
You should ask them to fix their page for TLS.

**Comment by plieblang** [comment]
No longer an issue.
