### ISSUE TITLE
google maps rule broken on huawei.com

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#9433]
http://consumer.huawei.com/en/support/service-center/index.htm

When Google maps rule active, selecting a country and city and hitting submit doesn't update the map. Disabling Google maps rule fixes it.

**Comment by gloomy-ghost** [comment]
I am unable to reproduce this issue, @terrorist96 can you confirm if this issue is fixed?

**Comment by terrorist96** [comment]
Confirmed.
