### ISSUE TITLE
search.amd.com: Insecure Connection

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/https-everywhere#9445]
search.amd.com cannot be used with HTTPS Everywhere by default. I get this message:

> ### Secure Connection Failed
> 
> An error occurred during a connection to search.amd.com. Peer attempted old style (potentially vulnerable) handshake. Error code: SSL_ERROR_UNSAFE_NEGOTIATION
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

**Comment by J0WI** [comment]
Confirmed, I get a cert mismatch with `security.ssl.require_safe_negotiation = false`.

**Comment by davidhedlund** [comment]
@J0WI Thank you.

**Comment by J0WI** [comment]
#9482

**Comment by jeremyn** [comment]
I'm closing this issue because I've merged pull request #9482 .
