### ISSUE TITLE
mozdev.org/bugs/: Insecure Connection

### ISSUE THREAD

**Issue by davidhedlund** [EFForg/https-everywhere#9446]
HTTPS Everywhere 5.2.13 is not compatible with mozdev.org/bugs/

>### Your connection is not secure
>
>The owner of www.mozdev.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
>
>www.mozdev.org uses an invalid security certificate.
>The certificate expired on 2016-09-11 19:39. The current time is 2017-04-04 07:14.
>Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by Bisaloo** [comment]
That ruleset should be off by default ([proof](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Mozdev.xml)).

Are you using the latest HTTPS-Everywhere version?

**Comment by davidhedlund** [comment]
@Bisaloo I'm using 5.2.13.

**Comment by davidhedlund** [comment]
@Bisaloo Sorry, I dont find ```extensions.https_everywhere.rule_toggle.Mozdev```.

**Comment by J0WI** [comment]
That's not a issue in HTTPS-Everywhere. The server sends a 301 redirect to https itself on `/bugs`

**Comment by davidhedlund** [comment]
@J0WI Sorry, you are right. Their cert. expired.

**Comment by davidhedlund** [comment]
https://github.com/davidhedlund/Feedback-for-websites/issues/12

**Comment by stanlane** [comment]
They have updated their certificate now.
