### ISSUE TITLE
Please manually check my domain (listed as HSTS elsewhere)

### ISSUE THREAD

**Issue by AbhishekGhosh** [EFForg/https-everywhere#9463]
My domain was manually listed here & there since the beginning of HSTS Everywhere. It was listed on this project and you can check here - https://hstspreload.org/?domain=thecustomizewindows.com 
Now suddenly it is removed from this list and my try to re-list with new rules making it is impossible pass. Four times I tried to pass someway -- https://github.com/EFForg/https-everywhere/pull/9462 

I am getting this on local. 

`2017-04-08 00:24:39,142 ERROR /Users/abhishekghosh/Desktop/h/Thecustomizewindows.com.xml: Fetch error: http://thecustomizewindows.com/ => https://thecustomizewindows.com/: Fetcher subprocess error: (4, '')`

I send email via newsletter link too. Domain has DANE. DNSSEC, colocation server, Dyn DNS. I fully followed documentation.

**Comment by jeremyn** [comment]
Hi @AbhishekGhosh , please keep discussion about a pull request in the pull request itself, instead of making a new issue.
