### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9466]
A lot of the FAQ is outdated and requires a rewrite.

**Comment by Hainish** [comment]
Related: #8187 #7936 #7282 #2088

**Comment by Hainish** [comment]
Related: #9467

**Comment by Bisaloo** [comment]
Is the FAQ translated in other languages than English? I think it would be a nice improvement. 

[Privacy badger already does it](https://www.eff.org/privacybadger).

**Comment by Hainish** [comment]
@Bisaloo it is not.  I agree, it would be good to have.  We could perhaps leverage transifex for this, but we don't want to do it until after we do the FAQ update.

**Comment by dvd2000** [comment]
@Hainish actually the translation of the FAQ to other languages is happening here: [EFForg/www-l10n](https://github.com/EFForg/www-l10n). Personally I'm working on the italian one. Should we wait for the update of the FAQ?

**Comment by Hainish** [comment]
@dvd2000 thanks for the notification - it looks like there hasn't been a commit for quite a while in that repo, though.  I'll check with our web dev team to see if it's still active.  Also, be aware that we've moved the FAQ (as well as a few other HTTPS Everywhere pages) into the repo: https://github.com/EFForg/https-everywhere/tree/master/docs

We should change the structure and maybe format of the docs path to support localization.

**Comment by dvd2000** [comment]
Ok @Hainish, thanks for your reply. I will wait for some news.

**Comment by Hainish** [comment]
@dvd2000 apparently that repo was created but never used to uplift translations as our web dev team deprioritized it.  I'd suggest any translation be made in _this_ repo, restructuring the `docs` path to support i18n in a PR (e.g. our current docs could go under `docs/en_US`.)

**Comment by Hainish** [comment]
And I suggest also holding off on this until we review the FAQ.

**Comment by dvd2000** [comment]
@Hainish Thanks for the update. I'll make a PR to move the docs and maybe write something to explain how to translate and how to add a new language; should I wait for the FAQ review?

EFF has a Transifex profile [here](https://www.transifex.com/eff/public/). I think that moving the translation process there would be better. What do you think?

**Comment by Hainish** [comment]
I thought about moving the translations to the Transifex page.  To do this, first you need to create the new strings in the files under https://github.com/EFForg/https-everywhere/tree/master/src/chrome/locale/en.  Every night, Transifex reads these files and creates new fields for the translators to fill.

This may be the way to go, though I suspect it would be kind of hard to auto-generate the markdown from the `dtd` file.

**Comment by dvd2000** [comment]
Probably that's not a good idea, it isn't very common to translate large pieces of text with transifex and as you said it will be quite hard to generate markdown from translation files.

Maybe will be easier to use normal PR's here on github.

**Comment by dvd2000** [comment]
@Hainish

**Comment by Hainish** [comment]
A new issue would be fine.

**Comment by apple-web-evangelist** [comment]
Related: #10020

**Comment by Bisaloo** [comment]
From https://github.com/EFForg/https-everywhere/issues/7343#issuecomment-255233076:

- add a test url in FAQ so users can see the extension in action (eg. http://freerangekitten.com/)

**Comment by zoracon** [comment]
The FAQ has been updated, closing. Thank you!
