### ISSUE TITLE
Golf Digest page not rendered right

### ISSUE THREAD

**Issue by CWR64** [EFForg/https-everywhere#9488]
Installed httpse into current Firefox and current Chrome on W10 64bit desktop PC.  It immediately caused this Golf Digest web page to render incorrectly: 
> 
> http://www.golfdigest.com/story/heres-what-it-was-like-inside-the-augusta-national-clubhouse-when-sergio-garcia-won-the-masters?mbid=nl_040917_Hitlist_Masters_PM&CNDID=21358373&spMailingID=10788923&spUserID=MTMyNjM1Njg3NDI2S0&spJobID=1140712479&spReportId=MTE0MDcxMjQ3OQS2

When I turned off httpse (both browsers) the page rendered OK again.  
If I have posted this problem to the wrong place, please let me know so that I can re-post properly.  I am a home user - not a developer.  Thanks in advance

**Comment by CWR64** [comment]
I see your info on github (whatever that is), but as a home user I can tell you that as of this minute the problem is not fixed.

http://www.golfdigest.com/story/johnny-millers-bold-fashion-claim-to-fame?mbid=nl_042717_daily_hitlist&CNDID=21358373&spMailingID=10907116&spUserID=MTMyNjM1Njg3NDI2S0&spJobID=1142195111&spReportId=MTE0MjE5NTExMQS2



________________________________

**Comment by J0WI** [comment]
It has been fixed in the master branch, please wait for our next release.

**Comment by CWR64** [comment]
Thank you.


Did I report the issue in the right way?

When is the next release due out?




________________________________

**Comment by J0WI** [comment]
Yes, you've reported it the right way, thanks.
The upcoming release is tracked in #9621.

**Comment by CWR64** [comment]
I see this:

Release 5.2.16 forthcoming #9621

But I see my version today as: 2017.4.19 which is a different date format than 5.2.16.
I don't know why you use two different formats for the date/release#, but it appears that stable 5.2.16 is not yet available for the Chrome browser.  If it is, then where can I get it?  If it is not, then when & where should I find stable 5.2.16 and what release level is it - 2017.5.dd?

Charles Robinson

Kyle, TX



________________________________

**Comment by J0WI** [comment]
The version number of the chromium version differs from the Firefox version.
You can find any release on https://github.com/EFForg/https-everywhere/releases
#9621 has not yet been resolved, so 5.2.16/2017.4.19 are the newest stable releases.

**Comment by CWR64** [comment]
OK.  How will I learn when the fix for 9621 is ready for home users like me to download/install?  I don't remember whether https-Everywhere automatically self-updates.

Charlie




________________________________

**Comment by J0WI** [comment]
Automatic updates for Add-Ons are enabled by default. It may take some time to roll them out for browser vendors.
If you want to get informed about new releases you can subscribe our mailing list:
https://lists.eff.org/mailman/listinfo/https-everywhere

**Comment by CWR64** [comment]
I thought this was all fixed but the Tiger Woods vid itself would not play until I disabled "https Everywhere" in current Firefox

http://www.golfdigest.com/story/paul-azinger-on-tiger-woods-some-players-that-think-theres-a-problem-there-with-pain-meds?mbid=nl_060917_daily_hitlist&CNDID=21358373&spMailingID=11225540&spUserID=MTMyNjM1Njg3NDI2S0&spJobID=1180808213&spReportId=MTE4MDgwODIxMwS2




________________________________

**Comment by J0WI** [comment]
Could you open a new issue for this?

**Comment by CWR64** [comment]
Done


Golf Digest vid won't play w/o disabling https Everywhere in Firefox #10274




________________________________
