### ISSUE TITLE
Add psol50.org.br

### ISSUE THREAD

**Issue by picsi** [EFForg/https-everywhere#9506]
www.psol50.org.br has an https version, but it is not automatically redirected.

**Comment by jeremyn** [comment]
Thanks for the report. I've added this to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-306309543` and am closing this issue.

**Comment by bardiharborow** [comment]
This domain has mixed content issues. @jeremyn can I get clarification about whether HTTPSE can do anything about that, as there is a rule for `http://i1.wp.com` but it's doesn't still doesn't stop the warnings.

**Comment by jeremyn** [comment]
@bardiharborow See https://www.eff.org/https-everywhere/rulesets#mixed-content-blocking-mcb.

**Comment by pipboy96** [comment]
Website no longer supports HTTPS.
