### ISSUE TITLE
Meetrics: double wildcards needed?

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#9515]
Checking the Meetrics ruleset we can clearly see:
`<rule from="^http://(s\d+)\.research\.de\.com/" to="https://$1.research.de.com/"/>`
the problem is that they also have additional subdomain levels below that.
Both
`
<target host="i2.s62.research.de.com" />`
and

`<target host="s62.research.de.com" />`

exist and the numbers are working at least up to 999 for both levels.
Since
`<rule from="^http://(s\d+)\.research\.de\.com/" to="https://$1.research.de.com/"/>`
doesn't cover both cases, is a double wildcard a solution?

**Comment by J0WI** [comment]
Whatever you tried to post, GitHub strips HTML chars like `<` and `>` from comments. SO I'm not sure what your question is.

**Comment by numismatika** [comment]
was the wrong markdown code to quote it, marking it as code instead of quote seems to be better now.

**Comment by J0WI** [comment]
A wildcard like `<target host="*.research.de.com" />` will match any level of subdomain, even `foo.bar.foo.bar.research.de.com`.

**Comment by numismatika** [comment]
maybe the (s\d+) then prevented the match & rewrite for the lower layer.
I will have to test more of these subdomains i guess.
