### ISSUE TITLE
OpenX needs a wildcard rule

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#9516]
Sublist3r shows over 600 subdomains which is more than the timeout for the tests can handle.
Unfortunately it is not yet preloadable.

**Comment by J0WI** [comment]
Do all 600 hosts support HTTPS?
Could you document this in #9549?

**Comment by numismatika** [comment]
I of course havent hecked all of these subdomains but so far most of those that are related to ads on other pages seem to use the same wildcard cert and work properly

**Comment by Bisaloo** [comment]
This was fixed in #9549. This issue can be closed.
