### ISSUE TITLE
theclarogroup.com  has an https version, but it is not automatically redirected.

### ISSUE THREAD

**Issue by jsalameh85** [EFForg/https-everywhere#9552]

**Comment by afarrow** [comment]
Do you know which subdomain(s) have https supported? I tried the usual suspects (no subdomain, www, secure) and they didn't support https. I ran [Sublist3r](https://github.com/aboul3la/Sublist3r) on the site and it found **245,500** subdomains so there's no way I'm going to go through all of those and see which subdomains are supported.

**Comment by pipboy96** [comment]
Closed by #18423.
