### ISSUE TITLE
Error in the FAQ

### ISSUE THREAD

**Issue by dvd2000** [EFForg/https-everywhere#9575]
In the faq in found this:

> Thus, you might get some protection even if you wouldn't have noticed that the target site is available in HTTPS.

That i suppose should be changed to this:

> Thus, you might get some protection even if you wouldn't have noticed that the target site is available in **HTTP.**

or to this:

> Thus, you might get some protection even if you wouldn't have noticed that the target site **is not** available in HTTPS.

But english is not my native language so it could be that I didn't interpret well the meaning of the sentence.

**Comment by J0WI** [comment]
This means that even if a site is available over HTTPS, but does not redirect you itself (so you don't know without manually typing the https), we will redirect you.
So for me the sentence looks correct.
