### ISSUE TITLE
.

### ISSUE THREAD

**Issue by PekaFat** [EFForg/https-everywhere#9576]

**Comment by J0WI** [comment]
Are all external links with `https://vk.com/away.php?to=` affected or just those to donationalerts?

**Comment by PekaFat** [comment]
I think all. Tested pastebin.com and wowhead.com - same result. But for redirect w/o https-everywhere you need use `&post=-145213353_23&cc_key=` too.

**Comment by swarmer** [comment]
I can confirm that HTTS everywhere breaks VK redirects. VK has a very advanced redirect system with cookies for reasons that are beyond understanding of mere mortals like me. Anyway, with HTTPS everywhere enabled browser doesn't send cookies in one of the requests.

It goes like this:
```
 -> https://vk.com/away.php?to=blahblah&cc_key=
 <- Response: set-cookie:remixsec_redir=blahblah; path=/; domain=.vk.com
    And 302's to away.vk.com
 -> http://away.vk.com/away.php
    Here the browser usually sends the cookie shown above, but not with HTTPS everywhere enabled.
    With no cookie set, redirect fails.
```

**Comment by J0WI** [comment]
@swarmer can you confirm that the redirect works when you use HTTPS on `away.vk.com`?

**Comment by swarmer** [comment]
Yes, when I manually go to https://away.vk.com/away.php, I'm redirected to the address that was saved in the cookie previously.

**Comment by J0WI** [comment]
Thanks!
So I think #9584 will fix this without making any exclusion.
