### ISSUE TITLE
Localisation: Hardcoded string in toolbar_button.xul

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#961]
The string "Block all HTTP requests" is hardcoded in toolbar_button.xul:46.

**Comment by StevenRoddis** [comment]
Thanks! I also noticed line 35 has "HTTPS" hardcoded.

**Comment by fuglede** [comment]
Sure, but it sounds to me like it would be a lot faster for a Transifex maintainer, if I understand [jsha's comment here](https://github.com/EFForg/https-everywhere/pull/966#discussion_r23559337); the other ones I added to the individual .dtd's manuall.

By the way, is that HTTPS label actually shown anywhere?

**Comment by jsha** [comment]
Yes, it's probably easier for me to just copy over all the latest strings before each release.

The HTTPS label is displayed if you customize your toolbar and drag the HTTPS Everywhere icon off of it and into the area of available icons. I think the proper fix is to change the string to be a reference to the "HTTPS Everywhere" string.

**Comment by fuglede** [comment]
Ah, that makes sense. I changed it to the extension name string in the pull request.
