### ISSUE TITLE
Why is autotools.io in ruleset-coverage-whitelist.txt?

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9627]
It doesn't look like the [ruleset for `autotools.io`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Autotools.io.xml) has coverage issues to me.

So why is it listed in [`ruleset-coverage-whitelist`](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-coverage-whitelist.txt#L493)?

The issue is that the hash of the current file matches the hash listed in the whitelist so it won't be remove by `ruleset-coverage-whitelist-cleanup.sh`.

```sh
sha256sum Autotools.io.xml | cut -c-64
```
>1074d5e1178a297d7bca2c929df0be05e154ae62bd4f4e705a25240562791955

**Comment by cschanaj** [comment]
The same thing holds true for `www.mint.com`. The ruleset [Mint.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Mint.xml) looks fine to me, yet it is listed [Here](https://github.com/EFForg/https-everywhere/blob/master/utils/ruleset-coverage-whitelist.txt#L3593) which the same hash.

**Comment by J0WI** [comment]
We didn't have any tests in 2014, so all existing rules have been white listed.

**Comment by Bisaloo** [comment]
Thank you @J0WI. Could you tag this as question please? In case someone happens to have the same question.
