### ISSUE TITLE
Proposed option for captive portals

### ISSUE THREAD

**Issue by glamrock** [EFForg/https-everywhere#963]
Following up on #384, I'd like to propose an option to bypass captive portals.  Launching example.com as a page should trigger the captive portal as normal. http://example.com is a basic example website, and while it *does* offer TLS connections, it doesn't contain any information that needs to be secured (or much information at all).  The usability benefits for solving this problem are pretty great =)

[Firefox's captive portal detection feature is still blocked by some other features & bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=562917).

**Comment by StevenRoddis** [comment]
https://github.com/EFForg/https-everywhere/issues/835

**Comment by jsha** [comment]
example.com is not included in the HTTPS Everywhere rulesets. So I think this already works? Let me know if you meant something more specific.

**Comment by semenko** [comment]
Closing, as this issue is quite old and my no longer be valid. Feel free to reopen if you think it's still a bug.
