### ISSUE TITLE
Translate FAQ

### ISSUE THREAD

**Issue by dvd2000** [EFForg/https-everywhere#9631]
Continuing from #9466. 
@Hainish 

As suggested, we should probably support the FAQ translation (as Privacy Badger does). Initially the translation process was there: [EFForg/www-l10n](https://github.com/EFForg/www-l10n), but this repo was not very active so we should consider making the translations in the https-everywhere repository.

We have two options:

1) Do all the job on GitHub through pull requests. In this case we should create a folder for each language inside the docs folder (docs/en_US, docs/fr, docs/it, ...) and just translate the .md files directly without changing the Markdown syntax. Here the problem is about the review of the translations (how can we assure the quality of the translations?).

2) Move the translation process to Transifex (EFF already as an account there). The problem in this case is about the creation of the .md files from the Transifex translation files. Also, it isn't very common to translate markdown files with Transifex. On the other side, Transifex offer a great platform for translator that will probably increase contributions.

What should we do? Do you have any other option?

**Comment by Bisaloo** [comment]
It is likely to be a quite small file and I think it's possible for one person to translate the whole file so Transifex is probably overkill (in addition with the issues you mentioned) so Github and PR sounds fine to me.

**Comment by dvd2000** [comment]
Ok, at the moment there is also some documentation for the developers in the docs folder (README, development, rulesets).
Should we move these documents somewhere else?
Otherwise we can keep them there and organize the docs folder like this:

```
+-- README.md
+-- development.md
+-- rulesets.md
+-- en_US
|   +-- faq_en.md
+-- fr
|   +-- faq_fr.md
+-- it
|   +-- faq_it.md
```

and so on for the other languages.

**Comment by Hainish** [comment]
@dvd2000 I'd suggest the following, almost identical schema:

```
+-- README.md
+-- en_US
|   +-- faq.md
|   +-- development.md
|   +-- rulesets.md
+-- fr
|   +-- faq.md
+-- it
|   +-- faq.md
```

And then maybe create a symlink from `default` to `en_US`, and make a note in the README.md that `en_US` is the canonical source.

**Comment by dvd2000** [comment]
@Hainish  I will write some instructions to help the translators, should I put them in docs/README ?

**Comment by Hainish** [comment]
Yes please

**Comment by dvd2000** [comment]
@Hainish I've written some instructions (PR #9670), tell me if you think I should add something else

**Comment by dvd2000** [comment]
I'll start to work on the italian translation

**Comment by pipboy96** [comment]
Spanish translation already exists, feel free to continue translating. Closing.
