### ISSUE TITLE
"Google Services Simple" causes problems for Crunchyroll ads

### ISSUE THREAD

**Issue by matthew-cline** [EFForg/https-everywhere#9662]
If the "Google Services Simple" rule (GoogleServices.xml) is used while watching videos at [Crunchyroll](http://www.crunchyroll.com), you'll intermittently get errors like this:

> 07:54:14.536 tpc.googlesyndication.com/sodar/sbhK2lTE.js:7 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://tpc.googlesyndication.com') does not match the recipient window's origin ('https://tpc.googlesyndication.com').
aa @ tpc.googlesyndication.com/sodar/sbhK2lTE.js:7

This will sometimes mess up the ad delivery code, making it take a long time for the player to display enough ads to get back to watching the content.

**Comment by pipboy96** [comment]
@matthew-cline Does this issue still exist?

**Comment by matthew-cline** [comment]
@pipboy96 I no longer have any issues watching Crunchyroll ads.  However, the "Google Services Simple" rule is no longer on for the crunchyroll.com, and I can't find that rule in order to turn it on.

**Comment by pipboy96** [comment]
@matthew-cline If it no longer shows in applied rulesets, that means nothing on the page is rewritten by this ruleset.
