### ISSUE TITLE
Stable UMich.edu (partial) rule breaks user page (umich.edu/~eecs381/)

### ISSUE THREAD

**Issue by yed** [EFForg/https-everywhere#9665]
Stable UMich.edu (partial) rule breaks
http://umich.edu/~eecs381/handouts/C++11_smart_ptrs.pdf
There is login page on:
https://umich.edu/~eecs381/handouts/C++11_smart_ptrs.pdf

**Comment by Bisaloo** [comment]
It seems to be the case for all user pages. More test urls:

- https://umich.edu/~historyj/
- https://www.umich.edu/~cses/
- https://www.umich.edu/~ocm/

**Comment by jeremyn** [comment]
Closed by #9937 .
