### ISSUE TITLE
Document translation process better

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#967]

**Comment by jeremyn** [comment]
Does https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md#contributing-translations resolve this issue?

**Comment by javiguajardo** [comment]
It seems that your issue is unclear, could you explain what's wrong with the translation process?

**Comment by zoracon** [comment]
Resolved, and being discussed currently for 2019 plans for moving translation efforts over
