### ISSUE TITLE
Add exclusion for *.chatango.com/fullpix

### ISSUE THREAD

**Issue by wannabacloud** [EFForg/https-everywhere#9685]
This website was working fine until last night. It is a messenger/PM service. Please help it work again.

**Comment by J0WI** [comment]
Could you please provide some more details about the issue?
Can you reproduce the issues in a new [Firefox Profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) with/without HTTPS Everywhere installed?

**Comment by domzy** [comment]
I think this is a problem with the website itself, not so much with HTTPS Everywhere. Look at the same link, once with http, and once with https
http://chatango.chatango.com/fullpix
https://chatango.chatango.com/fullpix
Personally, I have HTTPS Everywhere disabled on Chatango

**Comment by J0WI** [comment]
Confirm:
```
function init(){
	var nm = document.URL.split(".chatango.com")[0].split("http://").join("").split("www.").join("");
	var nm0 = nm.charAt(0);
	if(nm.length == 1){
		var nm1 = nm.charAt(0);
	} else {
		var nm1 = nm.charAt(1);
	}
	var img_url = "http://fp.chatango.com/profileimg/" + nm0 + "/" + nm1 + "/" + nm + "/full.jpg";
	document.getElementById("picture").innerHTML = "<img src='" + img_url + "'>";
	document.title = nm + "'s full picture";
}
```

The `split("http://")` part won't work with `https://`.😞

**Comment by pipboy96** [comment]
This issue can't be fixed without fixes on the website's side.

**Comment by J0WI** [comment]
We should add an exclusion for this path.

**Comment by pipboy96** [comment]
@J0WI I was going to make a PR to delete the ruleset. It's a better idea to add an exclusion, thanks for doing that.

**Comment by wannabacloud** [comment]
Can someone remove me from this thread
