### ISSUE TITLE
Indication when being redirected by HTTPS Everywhere

### ISSUE THREAD

**Issue by C0rn3j** [EFForg/https-everywhere#9688]
When I visit a site that has both HTTP and HTTPS enabled, I'd like to have an indication of that, as I like to contact projects that still do this and help/nag them to disable HTTP.

ATM the only way I know of to figure this out is by disabling the extension and then trying to load the site over HTTP again.

**Comment by jeremyn** [comment]
HTTPS Everywhere doesn't actually know if a site supports HTTP or not. It just rewrites URLs using a regex. There's a relevant discussion in issue https://github.com/EFForg/https-everywhere/issues/8239 about some concerns with adding the ability to HTTPS Everywhere to check HTTP requests.
