### ISSUE TITLE
Microsoft Account Two Factor Login Breaks in Firefox

### ISSUE THREAD

**Issue by wesdawg** [EFForg/https-everywhere#9691]
HTTPS Everywhere 5.2.15
Firefox 53 on Linux (Ubuntu)

## To reproduce:
Login to a Microsoft account that has TOTP (authenticator app) based two factor authentication enabled.

## Expected:
Entering the correct 2FA code once logs in to the account.

## Actual:
The correct 2FA code has to be entered twice before the login goes through successfully. No errors are displayed on the page or in the console, but after logging in, the landing URL contains an `MSPPError` fragment identifier, indicating that Microsoft's server detected an error during the login.

This only breaks in Firefox with HTTPS Everywhere enabled; clean Firefox and Chrome with HTTPS Everywhere work correctly.

**Comment by jeremyn** [comment]
Thanks for the report. This should be fixed by pull request https://github.com/EFForg/https-everywhere/pull/9694.

**Comment by J0WI** [comment]
closed by #9694
