### ISSUE TITLE
Add rule for Cvs.com

### ISSUE THREAD

**Issue by robatino** [EFForg/https-everywhere#9697]
HTTPS Everywhere currently doesn't have a rule for Cvs.com, so http://www.cvs.com doesn't redirect to https://www.cvs.com as it should.

**Comment by Bisaloo** [comment]
For anyone interested in working on this, some work has already been done in https://github.com/EFForg/https-everywhere/pull/6641.

**Comment by gloomy-ghost** [comment]
Thanks @Bisaloo, closing as duplicate of #5599
