### ISSUE TITLE
Problems on NYTimes.com

### ISSUE THREAD

**Issue by tekskater** [EFForg/https-everywhere#9701]
I get the error:

> We're sorry, we are not able to log you in.  In order to access our website, your browser must accept cookies from NYTimes.com.

when I visit https://www.nytimes.com/slideshow/2017/04/28/realestate/on-the-market-in-new-york-city.html and click on the picture to start the slide show, which redirects to:  http://www.nytimes.com/slideshow/2017/04/28/realestate/on-the-market-in-new-york-city/s/30OTM-NYC-slide-VVNR.html

The error URL that gets returned is:  https://myaccount.nytimes.com/auth/login?URI=https%3A%2F%2Fwww.nytimes.com%2Fslideshow%2F2017%2F04%2F28%2Frealestate%2Fon-the-market-in-new-york-city.html%3F_r%3D5&REFUSE_COOKIE_ERROR=SHOW_ERROR

First, I disabled the Optimizely (partial) rule, and it worked a few times.  Then, I started getting the error again until I disabled the NYTimes rule.

**Comment by J0WI** [comment]
This is likely because of a securecookie issue in the rule.
Can you provide some details about the login cookies that NYTimes sets in your browser?

**Comment by pipboy96** [comment]
Can't reproduce.
