### ISSUE TITLE
Mixed content completely breaks ReadWrite

### ISSUE THREAD

**Issue by nyuszika7h** [EFForg/https-everywhere#973]
> Zoinks! There's a problem
>
> It looks like you can't access some of the data needed to view this site. Often this is because the institution where this site is being accessed is blocking unrecognized domain names. If reloading the page does not fix this error, please notify your IT department and contact bugs@readwrite.com if you have any further questions.

This is because of mixed content.

**Comment by StevenRoddis** [comment]
Hi!
What browser and version of HTTPSE are you using?

**Comment by nyuszika7h** [comment]
Firefox 35.0.1, HTTPS Everywhere 5.0development.2.

**Comment by StevenRoddis** [comment]
Can confirm it breaks due to MCB. Preparing a fix.

**Comment by semenko** [comment]
looks fixed per above
