### ISSUE TITLE
Current state of HTTPS-Everywhere as a WebExtension

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#9763]
* Firefox 55 currently marks non WebExtensions as legacy
* Firefox 57 will drop support for legacy AddOns

Referring to #7389, we have already implemented WebExtensions, but it's still not the default for Firefox. We also have a bunch of (performance) issues that may be fixed by migrating to WebExtension APIs.

@Hainish @jsha
Could you please cultivate a list of tasks that needs to be done to ship HTTPS-Everywhere as a WebExtension for Firefox/Tor?

**Comment by Hainish** [comment]
This is on our radar, we're preparing for the transition already and have a timeline.

**Comment by J0WI** [comment]
Could you please make this progress/timeline public?
