### ISSUE TITLE
Auto-run ruleset-tests.js

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#978]
In order to maintain all rulesets in working order, we will need ruleset-tests.js to run automatically on some frequency.

It is probably too slow to run all of the tests on every commit. More likely, we will want to run all of the tests once a day (to make sure sites have not changed their structure and broken our rules), and run tests for only the changed rulesets on each pull request and/or merge.

For the daily tests, we should keep track of a site's pass/fail history, and not consider a one-day failure to be grounds for removal. However, if a site is flaky or fails for two days in a row, we should disable its ruleset - either by hand, with some tools to make it easy, or automatically.

**Comment by jsha** [comment]
We're going to use https-everywhere-checker instead. Still need to figure out how to run the http-fetching part on every commit or pull request.

**Comment by pipboy96** [comment]
`ruleset-tests.js` no longer seems to exist.
