### ISSUE TITLE
Unable to run ruleset tests

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#979]
@nemobis reports on #529:

>> Now when you open the HTTPS Everywhere context menu there will be a "Run HTTPS Everywhere Ruleset Tests" menu item.

> It's embarrassing, but I don't manage to do this: I see the context menu in Tools, but when I hover or click it nothing happens (Firefox 35.0). I guess I should file/look for a separate report/support item.

@nemobis, I updated the README to clarify you can also do this with `./test.sh --justrun`. Try that? Also, have you tried clicking the HTTPS Everywhere icon on the toolbar rather than the Tools menu?

**Comment by nemobis** [comment]
jsha, 26/01/2015 20:39:
> I updated the README to clarify you can also do this with |./test.sh
> --justrun|. Try that?

Great, this is good.

> Also, have you tried clicking the HTTPS Everywhere
> icon on the toolbar rather than the Tools menu?

No, because my toolbar as configured doesn't have such icon. But command 
line is much more comfortable anyway

**Comment by jeremyn** [comment]
@nemobis I don't see a `Run HTTPS Everywhere Ruleset Tests` option when I click the icon in Firefox, so I suppose this option has been removed since the issue was opened. Closing issue, but please feel free to reopen this issue with a comment if the problem still exists for you.
