### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#981]
Right now there are too many manual steps in making a release. We should automate:
- Checking that the Travis build is green for a given branch.
- Updating the various install.rdf and manifest.json with the given version.
- Creating release tags for Firefox and Chrome.
- Getting latest translations from Transifex.
- Verifying that reproducible builds still work, i.e. that the hash from the latest Travis build matches the hash when built locally.
- Opening correct upload URLs for Chrome Web Store, Opera add-ons, and addons.mozilla.org.

**Comment by J0WI** [comment]
linking to #13716

**Comment by Hainish** [comment]
Some of this was resolved in the migration to WebExtensions.  For instance, we have only one tag now, not a separate one for Firefox and Chrome.  Firefox also removed the ability to use a key owned by the extension developer for extension signing (unfortunately), which makes the signing process only applicable to Chrome.

This problem will also be alleviated, but not solved, with the delivery of rulesets out-of-band from the extension itself: https://github.com/EFForg/https-everywhere/issues/12606

**Comment by jeremyn** [comment]
@Hainish I think the only improvement out-of-band updates offers is that you'll be doing less full builds, but each full build will take just as many manual steps as it does now, is that right? Plus you'll have to make a new build process for the OOB updates. (It might be worth documenting what the OOB build process will be, in advance, to flush out problems now.)

**Comment by Hainish** [comment]
@jeremyn `sign-rulesets` does not change the extension release process but will give us the option to lengthen the time between builds in the future.

**Comment by J0WI** [comment]
linking to #457

**Comment by Hainish** [comment]
With out-of-band rulesets and WebExtensions support in Firefox this pain point has been greatly alleviated.  We only need to make new releases on major changes or bugfixes, otherwise a simple weekly ruleset release process suffices.  Closing.
