### ISSUE TITLE
Write webhook for ruleset changes

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#982]
We'd like to be able to enforce this constraint: Changes to existing rulesets should only be merged to 4.0 (or whatever branch is currently stable). New rulesets, or rulesets that don't yet exist in the stable branch, should only be merged to master.

Probably the easiest way to do this is a custom GitHub webhook for pull requests that acts like the Travis-CI integration. It should check whether the pull request is against the correct branch, and add a failing mark to the pull request if not.

It is probably easiest to develop and test this commit hook on a personal repo, then commit the code (preferably Python, but not required) into utils/, then EFF will run the production copy of the webhook on one of our servers.

**Comment by jsha** [comment]
Details about webhooks: https://developer.github.com/webhooks/

**Comment by pipboy96** [comment]
There is no longer a stable branch and master. Issue seems to be irrelevant.
