### ISSUE TITLE
Add site bgm.tv

### ISSUE THREAD

**Issue by yejingchen** [EFForg/https-everywhere#9827]
`bgm.tv` supports HTTPS (though its another domain name `bangumi.tv` doesn't)

I've written a trivial ruleset which seems to work on my browser (Firefox 53.0.2 x86_64):

```xml
<!-- Only bgm.tv support HTTPS, not bangumi.tv -->
<ruleset name="Bangumi">
	<target host="bgm.tv" />
		<test url="http://bgm.tv/timeline" />
		<test url="http://bgm.tv/group" />
	<target host="*.bgm.tv" />
		<test url="http://doujin.bgm.tv/" />

	<rule from="^http:"
		to="https:" />
</ruleset>
```

**Comment by jeremyn** [comment]
Thanks for the report. I've added this domain to `https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-306294102` and am closing this issue. Please feel free to create a pull request to actually add the domain to HTTPS Everywhere if you like.
