### ISSUE TITLE
Ruleset tests should compute coverage

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#984]
The test URLs for a given ruleset, when loaded, should trigger each rule, securecookie, or exclusion at least once. We should hook into HTTPSRules to calculate this, and hard-fail any ruleset with less than 100% coverage.

**Comment by jsha** [comment]
Update: I wound up incorporating this test with the HTTP fetch test in https-everywhere-checker. See `test-ruleset-coverage.sh`. We can now test for coverage, but most rules fail. We will have to gradually improve the situation.

Also note that the new coverage detection detects a lot of the common ruleset bugs listed in #460.

**Comment by pipboy96** [comment]
I believe this is already implemented, sans securecookie, in the coverage travis test. Please reopen if appropriate.
