### ISSUE TITLE
Cannot log into lanyrd.com

### ISSUE THREAD

**Issue by fmarier** [EFForg/https-everywhere#9848]
It looks like something in HTTPS Everywhere prevents me from logging into Lanyrd.com.

I tried on Chrome with HTTPS Everywhere and it didn't work. Then I disabled HTTPS Everywhere and I could login just fine.

**Comment by gmemstr** [comment]
Specifically this error crops up:

```
(index):1 XMLHttpRequest cannot load https://lanyrd.com/ignin/?next=http%3A//lanyrd.com/&ajax=1&modal=1&cachebust=1494289659593. Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.
```

After some cursory Google searches it appears this is a server-side issue, especially since the page redirects from `https://lanyrd.com/` -> `http://lanyrd.com/`.

**Comment by gloomy-ghost** [comment]
massive close per #15157
