### ISSUE TITLE
Conflict with Forecastfox

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9875]
Report from a user:

> Just installed HTTPS Everywhere and oddly it's blocking my "Forecastfox"
> weather program. I just can't win.
>
> Any ideas?

**Comment by J0WI** [comment]
Any reference to this "Forecastfox weather program"?

**Comment by Hainish** [comment]
https://addons.mozilla.org/en-US/firefox/addon/forecastfox-fix-version/ this seems to be it, though I haven't had any time to look into it.

**Comment by MDawg957** [comment]
I'm using HTTPSE 5.2.17 and Forecastfox from the link @Hainish mentioned.  No issues whatsoever.

Using Firefox ESR 52.1.2 32-bit on Windows 7.

**Comment by Hainish** [comment]
I just tested this in Firefox 53.0.2 (64-bit) on Debian 8, works fine for me as well.  Unless someone can corroborate, we should close this.
