### ISSUE TITLE
https://www.eff.org/https-everywhere is case insensitive

### ISSUE THREAD

**Issue by StevenRoddis** [EFForg/https-everywhere#994]
I've been noticing the url changes in Google search results I see variations including:
https://www.eff.org/https-everywhere
https://www.eff.org/Https-everywhere
https://www.eff.org/HTTPS-EVERYWHERE

I'd suggest using https://support.google.com/webmasters/answer/139066?hl=en
`<link rel="canonical" href="https://www.eff.org/https-everywhere" />`

**Comment by jsha** [comment]
Good idea, will do.
