### ISSUE TITLE
https-everywhere breaks CNN World Markets display

### ISSUE THREAD

**Issue by BobLobaw** [EFForg/https-everywhere#9964]
http://money.cnn.com/data/world_markets/americas/?iid=H_MKT_QL

Is supposed to show a world map with major markets superimposed, with current pricing, time to close, etc.

With https-everywhere installed is shows the blank map and then a text list of markets, prices, etc. only visible if you scroll down quite a ways, and unformated/illegible..

**Comment by jeremyn** [comment]
Thanks for the report. This is resolved by pull request https://github.com/EFForg/https-everywhere/pull/10301 by @cschanaj , so I'm closing this issue.
