### ISSUE TITLE
Full list of targets not displayed

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9965]
In WebExtensions version for Firefox, only the first-party domain is displayed in the drop-down menu.  All the rest of the targets (3rd parties, for instance) are missing.

Whether the rules are actually being applied for the third parties is an outstanding question.

**Comment by Bisaloo** [comment]
I am wondering if this is not a specific case of a more general issue: HTTPS-Everywhere doesn't display rulesets in the dropdown menu if the page is already loaded over `https`.

For example, try visiting http://stackexchange.com and https://stackexchange.com and notice the difference.

**Comment by Bisaloo** [comment]
I am not sure if that's the same issue but on http://ipxe.org/, the WebExtensions add-on displays a ruleset but the legacy XPCOM doesn't.

Maybe #10039 is the same issue after all.

**Comment by Hainish** [comment]
This was indeed the same underlying issue as https://github.com/EFForg/https-everywhere/issues/10039.  Closing.

**Comment by Bisaloo** [comment]
The two extensions still don't display the same list of rulesets.

[Test URL](https://www.naughtydog.com/).

- (Minor: the order is different)
- the XPCOM extension lists [`Google.com Subdomains`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Google.com_Subdomains.xml) while the WebExtensions extension lists [`Google.com Subdomains (complex)`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/Google.com_Subdomains_Complex.xml), [`Google Images`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/GoogleImages.xml) and [`Google Sorry`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/GoogleSorry.xml) and [`Google Videos`](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/GoogleVideos.xml). It looks like the WebExtensions HTTPS-Everywhere is finding which rulesets are used based on the targets but doesn't take into account the rewrite rules (`Google Sorry` shouldn't be in there).

Should I open a new issue or do you prefer to reopen this one?

**Comment by Bisaloo** [comment]
Another test url where the case described in the opening post of this issue hasn't been fixed: https://www.crcpress.com/

**Comment by Hainish** [comment]
Your edit applies to both of your last two comments, right?

**Comment by Bisaloo** [comment]
No, only to the last one.

I still think the WebExtensions HTTPS-Everywhere display ruleset only based on the targets and doesn't take into account the exact rewrite rules.

**Comment by Bisaloo** [comment]
Another, maybe simpler test url for the case I am describing:

https://www.prweb.com/

In that case, the rules list should be empty because we have no rules rewriting `www.prweb.com`. Yet, the WebExtensions add-on is listing `PRWeb (partial)`.
