### ISSUE TITLE
Content verification flag in Chrome, if set to enforce, (apparently) wrongly flags HTTPS Everywhere as corrupted

### ISSUE THREAD

**Issue by rusvnc** [EFForg/https-everywhere#998]
This issue came up last year. The content verification flag, which is now usefully functioning on Chrome Beta 41 with very few false positives (also the option to repair flagged extensions via the UI), still appears to flag HTTPS Everywhere. Attempting to repair does nothing - the extension is immediately reflagged. I suspect custom rules may be the culprit, but I don't know.

**Comment by Thesalan** [comment]
I can confirm : if I modify rule_list.js to add a new file in the list, Chrome set HTTPS Everywhere as corrupted. I can't add custom rules.
Tested on Chrome Stable 40.

**Comment by semenko** [comment]
This isn't something we can fix -- you can work around this by disabling content verification if you like.
