### ISSUE TITLE
Rewrite Python/bash tools in Node.js

### ISSUE THREAD

**Issue by strugee** [EFForg/https-everywhere#9993]
As CONTRIBUTING.md notes, newer utilities are written to be run under Node.js, but most of them are written in Python or bash. Various comments in this issue tracker have pointed out that it'd be really good if we could rewrite all these in JavaScript/Node instead.

In particular this would be a huge boon for contributor experience if we could rewrite enough such that ruleset contributions required little to no implicit global dependencies that need to be installed via `install-dev-dependencies.sh`.

**Comment by jeremyn** [comment]
I'm not totally on board with switching to Node, but I've discussed it with @Hainish and I agree there is value in making the utils codebase match the (JavaScript) extension codebase.

If we're going to rewrite existing utils for Node, then a first step would be to install Node/npm in `install-dev-dependencies.sh` and document its basic use in `CONTRIBUTING.md`.
