### ISSUE TITLE
Can't download pdf from jstor.org

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9994]
The rule [`JSTOR (partial)`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/JSTOR.org.xml) is currently causing problem when trying to download a pdf.

**Comment by jeremyn** [comment]
Please be more specific.

**Comment by Bisaloo** [comment]
Take for example this [test url](https://www.jstor.org/stable/2407630) but it works for any other paper.

When you click `Download PDF`, a new tab open where you are prompted to "Accept JSTOR's Terms and Conditions Below" but when you click `I Accept, Proceed To PDF`, nothing happens.

If HTTPS-Everywhere is disabled, the PDF is downloaded when you click `I Accept, Proceed To PDF`.

**Comment by Bisaloo** [comment]
I tried to investigate but I am at loss here. The browser console only shows `HTTP 200` and there is no `securecookie` rule in this ruleset.

**Comment by jeremyn** [comment]
I don't have a JSTOR account and can't test this.

@Hainish does anyone at EFF have a JSTOR account?

**Comment by Bisaloo** [comment]
Oh yeah, I forgot about that. You probably need an institutional IP (academia). I am not sure how it would work with an account.

**Comment by jeremyn** [comment]
@Bisaloo Can you get any hints from the developer tools console?

**Comment by Bisaloo** [comment]
I don't see anything useful there.

On the page where I am supposed to accept the terms, only 3 requests are made:
- a `POST` request to https://www.jstor.org/tc/verify
- a `GET` request to https://www.jstor.org/assets/global_20170530T1135/build/global/css/global.css
- a second `GET` request to https://www.jstor.org/assets/global_20170530T1135/build/global/css/global.css (apparently caused by the first `POST` request)

![screenshot from 2017-06-08 21-16-50](https://user-images.githubusercontent.com/10783929/26946570-117ddbe8-4c90-11e7-923b-1569a426c01f.png)

I am assuming the issue arises during the `POST` request but it returns `200`. Is that possible that it nonetheless fails somewhere?

**Comment by Hainish** [comment]
> Oh yeah, I forgot about that. You probably need an institutional IP (academia). I am not sure how it would work with an account.

I'll try and see if anyone here has an account nonetheless.

**Comment by Bisaloo** [comment]
After more testing, I believe this is actually not due to HTTPS-Everywhere. I can't reproduce this issue on a fresh profile with HTTPS-Everywhere installed and in my current profile, it doesn't work even with all add-ons disabled.
