### ISSUE TITLE
Some rule names have an extra tab at the beginning in the UI

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9995]
Test URL: http://www.hbw.com/

In this example, `Google APIs` and `Issuu.com (partial)` have an extra tab at the beginning of their name in the dropdown menu.

Related: #9958

**Comment by Hainish** [comment]
That's where the icon appears in the Chrome extension, it's probably an access issue.  Looking into this now.

**Comment by Hainish** [comment]
This has been fixed in https://github.com/Hainish/https-everywhere/tree/webextensions and will be incorporated into the next testing release.
