### ISSUE TITLE
Bring back link to the atlas

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#9996]
The dropdown menu used to link to the [atlas](https://www.eff.org/https-everywhere/atlas/) but it has been removed in the WebExtension version. I think it is really useful (especially for contributors but maybe they're not your main target).

Related: #9958

**Comment by Hainish** [comment]
This has been fixed in the `master` branch and will be deployed in the next testing release for Firefox as well as the next release for Chromium.
