### ISSUE TITLE
Isn't showed content on button menu in private browsing mode 

### ISSUE THREAD

**Issue by AlexBeLi** [EFForg/https-everywhere#9997]
On webextension version (Firefox 53.0.2 - 55(2017-05-22) definitely)
![https everywhere](https://cloud.githubusercontent.com/assets/20776735/26317419/d2e242a0-3f30-11e7-9f5a-365dc90c5652.png)
Related: #9958

**Comment by Hainish** [comment]
This is due to the issue described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

I'm working on this currently.

**Comment by Hainish** [comment]
This has been fixed in https://github.com/Hainish/https-everywhere/tree/webextensions and will be incorporated into the next testing release.
